### ISSUE TITLE
Fixup Yosemite Look and Feel

### ISSUE THREAD

**Issue by johnnye** [GoldenCheetah/GoldenCheetah#1024]
The default font for Yosemite has changed in the upcoming update, and the fonts are very small in GoldenCheetah.

![](http://cl.ly/image/391D1i0N2X2C/Screen%20Shot%202014-08-21%20at%2010.59.11.png)
![](http://cl.ly/image/1e0C1U0J1T2i/Screen%20Shot%202014-08-21%20at%2010.59.02.png)

**Comment by liversedge** [comment]
Also the unified title and toolbar is ugly (colors mismatch).

**Comment by Joern-R** [comment]
- When going to "full screen" (green circle button) - the header tool bar get's "lost" (difficult to describe) and you do not but the bar with the green/yellow/red icon again.

- The font in "Tab view" windows is pretty big - which makes longer texts - which often appear after translation - appearing in 2 lines - which is unreadable.

**Comment by liversedge** [comment]
Those seem to be issues with 5.4 of QT .......................

**Comment by liversedge** [comment]
https://bugreports.qt.io/browse/QTBUG-39210

**Comment by liversedge** [comment]
The toolbar caused the issue on QT5.4 as a workaround we hide the toolbar in fullscreen on OS X.
See commit 4b81b6ddc5329d9ebd1b14e9ab95b305a5746547.

**Comment by liversedge** [comment]
The defaults are fixed along with the toolbar so now we need to sort the upgrade to v3.2 process to fixup the rest (i.e. change the appearances settings).
