### ISSUE TITLE
Text wrapping issue on Mac 

### ISSUE THREAD

**Issue by johnnye** [GoldenCheetah/GoldenCheetah#1029]
The dates in the ride list don't wrap nicely on a mac.

![](http://cl.ly/image/0Y2m2D0J3a2h/Screen%20Shot%202014-08-21%20at%2013.06.53.png)

**Comment by liversedge** [comment]
Was it fixed with QT5 ?
Also the new ridecache code changed the model. 
It looks ok for me so curious to know if you still see this issue ?
