### ISSUE TITLE
Heart Rate Zone summary table is showing incorrect very high data.

### ISSUE THREAD

**Issue by ehrlinger** [GoldenCheetah/GoldenCheetah#1034]
I've been doing some recovery rides on days off, so my HR does not go very high. I've noticed in 3.1 release that my HR zone table has data in z1-z3, skips z4 and then data in z5.

![screen shot 2014-08-22 at 4 50 12 pm](https://cloud.githubusercontent.com/assets/1110676/4017380/8a44d304-2a3f-11e4-96b8-23f05d6d41e1.png)

Note in this screen shot that my MAX HR was 145, and yet the table indicates I was above 160 for 24minutes.

I only notice this when I'm on recovery days, but can grab the HR data and check if there is a miscalculation all the time.

(this is also in the devel version)

**Comment by liversedge** [comment]
this was fixed in 3.2
