### ISSUE TITLE
Click through from summary to ride

### ISSUE THREAD

**Issue by siovene** [GoldenCheetah/GoldenCheetah#1035]
When I'm on my Trends -> Summary page, I'm presented with some data, including my Maximums (Speed, power, HR, etc) and Peak Power (5 sec, 1 min, 5 min, etc).

It would be great if the values were links that took you to the correct activity (i.e. the one in which the clicked maximum or peak was performed), and an ad-hoc Interval was created for it, so you could examine it.

**Comment by amtriathlon** [comment]
This is now available for Overview chart and likely it will not be retrofitted to Summary, I think we could close this.

**Comment by liversedge** [comment]
Especially since Summary will be deprecated in 3.6 !
