### ISSUE TITLE
Search/Filter Results Incorrect

### ISSUE THREAD

**Issue by tonydagiau** [GoldenCheetah/GoldenCheetah#1040]
Nav: Diary > Activity Log, enter search condition such as "TSS > 100"
Result: Rides are filtered but not matching condition. Will see some rides with TSS < 100, others with no  TSS, and many meeting condition are actually excluded. Seems random

Same behavior with top bar Search field and when applying Filter. 

Shots:
![image](https://cloud.githubusercontent.com/assets/8550234/4079508/cc67b540-2ed5-11e4-9f38-cf07f1a690ec.png)

![image](https://cloud.githubusercontent.com/assets/8550234/4079516/e71b27aa-2ed5-11e4-9b84-9ce8bb5c8226.png)

GC 3.1.0 on Windows XP.

**Comment by ocharles** [comment]
I just encountered exactly this - I think toggling the filter or magnifying glass is extremely subtle and not intuitive, though I'm glad to understand it now.
