### ISSUE TITLE
Weight shown in wrong unit

### ISSUE THREAD

**Issue by gcoco** [GoldenCheetah/GoldenCheetah#1069]
Windows build 3100 official.

Options - Athlete - Unit = Imperial
Data Fields - Fields - Weight = Screen Tab = Workout. Diary = checked.

Ride view, under the Rides selection the weight is not shown in Imperial units.

Weight is also shown to four decimal places.
Would be better to truncate this to one or two decimal places
Would also be nice to show the units of measurement.

**Comment by liversedge** [comment]
Fixed with ridecache updates -- but weight MUST be a double.
