### ISSUE TITLE
Elite Turbo Muin VIrtual Power

### ISSUE THREAD

**Issue by muinuser** [GoldenCheetah/GoldenCheetah#1075]
Hello,
It'd be great to have support for this trainer.

Using data collected by Ray Maker available at http://www.dcrainmaker.com/2013/11/elite-turbo-unboxing.html#comment-378332 , I fit a cubic polynomial from the Muin velocity data to power (using both his Quarq and Stages data). The fit is given by (speed in km/hr):
 P = 2.30615942 * V -0.28395558 * pow(V,2) +  0.02099661 * pow(V,3)

This is for the 2014 version of the trainer, I think they changed the flywheel mass on the 2015 model.
Happy to submit a patch if that's easier.

Thanks

**Comment by Jee-O** [comment]
Will the support of this trainer still be implemented? I'm really looking forward to this feature as I'm now recovering from a fractured tibia and will be training inside for a long time. (I'm not Contador)

I really appreciate your work and would be happy to contribute if I had any programming skills. Is there any other way to help?
