### ISSUE TITLE
VirtualPower Calibration via Spindown

### ISSUE THREAD

**Issue by muinuser** [GoldenCheetah/GoldenCheetah#1083]
If there's interest in this I could try adding some methods.

Hard to do any testing myself though until I figure out why ANT+ over USB won't work when i compile GoldenCheetah.

Also, is there an easy method to decrease the build time? Maybe remove -O2?

**Comment by chrisone19** [comment]
Great idea. Happy to help validate data using power meter + trainer speed

**Comment by liversedge** [comment]
FR incorporated into #1654
