### ISSUE TITLE
can't remove power anomaly

### ISSUE THREAD

**Issue by szschwartz** [GoldenCheetah/GoldenCheetah#1084]
I had an anomaly in power which showed a single power reading of more than 35,000 watts (I wish).  It completely skewed my CP curve so I opened the edit function, searched for and located the anomaly and edited it to read zero power.  However the change is not reflected in my CP curve.  I then deleted that ride from the athlete activities but the high power reading still shows up in the CP curve and when I mouse over it the date of the deleted ride is shown.

**Comment by liversedge** [comment]
Fixed in 3.11
