### ISSUE TITLE
Interval Highlighting issue

### ISSUE THREAD

**Issue by gcoco** [GoldenCheetah/GoldenCheetah#1095]
Rides view - Rides chart select. Ride has multiple intervals.

If I mouse over an interval in the intervals section, the interval is correctly highlight in the Ride chart.

If I mouse over an interval on the Ride chart, often the interval that the cursor is over will not highlight or an incorrect interval will highlight. The interval section will show text "select an interval for summary info".

O/S: Windows     GC Build: 3.1.0

I have tested on Mac and Fedora and the problem does not occur.

**Comment by liversedge** [comment]
tested with qt5.4 and it works as expected on windows.
