### ISSUE TITLE
Discrepancy in ride data

### ISSUE THREAD

**Issue by MRM-Oly** [GoldenCheetah/GoldenCheetah#1097]
I'm downloading from a PowerTap Joule.  Here's a sample of the data summary from GC:

Duration:	56:55
Time Riding:	56:58
Distance (miles):	23.53
Work (kJ):	376
W' Work (kJ):	20
Elevation Gain (feet):	456

Averages
Athlete Weight (lbs):	148.00
Speed (mph):	24.8
Power (watts):	110
Heart Rate (bpm):	0
Cadence (rpm):	75
Temp (F):	55.3

And here's what PowerAgent (the PowerTap software) says about the same ride:
Total Elapsed Time	0:56:39
Ride Time (Time Moving)	0:54:11
Distance, mi	13.20
Work, kJ	355
Temperature, °F	55.0
Average Power, Watts	109
Average Cadence	 70
Average Speed, mph	13.98
Average Heart Rate	--
Weight, lbs	145.0
VAM	147
Device	CycleOps Joule v18.057

The PowerAgent summary is correct - I know I didn't average 25 mph.

**Comment by liversedge** [comment]
fixed in 3.3
