### ISSUE TITLE
training mode plot becomes flat line on win xp

### ISSUE THREAD

**Issue by torbjornjansson** [GoldenCheetah/GoldenCheetah#1104]
While running in training mode on my old garage win xp laptop, the plot becomes a flatline after some time. I didn't scrutinize the underlying power data. It is the latest release (v 3.1) of GC, but the feature was present also in 3.0. The attached screendump should illustrate the point. I didn't inspect the underlying data file before I deleted this one, but would guess from the TSS statistic that it was also corrupt.
![gc_crash](https://cloud.githubusercontent.com/assets/9396847/4780744/837a53aa-5c76-11e4-9928-21a4466b8f97.gif)

**Comment by liversedge** [comment]
cannot recreate
