### ISSUE TITLE
Add Sufferfest RPE to train view

### ISSUE THREAD

**Issue by dhague** [GoldenCheetah/GoldenCheetah#1105]
The Sufferfest videos display the desired RPE on a scale of 1-10. In their training plans this is mapped to HR or Power ranges based on FTP - e.g. 7.5/10 maps to 100% FTP.
It would be great to have "Suffering: 6.5" displayed when I am doing tempo, for example, and I could check that I am suffering at an adequate level for each interval in a session.
There are a few components to this:
1. Define the mapping
   * Set FTP Power or HR, and select which to use as the basis for the "Suffering" metric
   * Set percentage ranges for each level 1-10
   * Levels can be left blank, so if I only set L4 = 50%, L7.5 = 100%, L10 = 150% then linear interpolation is used to calculate the metric in between defined levels
2. Make the metric available for showing on the Train screen, preferably to 1 decimal place

This doesn't just have to be for Sufferfest RPE - the same principle could be used to show Coggan&Allen levels, for example.

**Comment by pajakgdynia** [comment]
Power cannot be simple translated into RPE. Fatigue decreases power at same RPE.

Look for "Understanding Critical Power and W'" on youtube. If it were verified, then maximal power keeps the curve all the time (RPE10 is about 90% of this value, RPE1 is on CP).

I've already done such tests (with sufferfest advice), and it looks more-or-less ok, but I had to change "my" parameters.
