### ISSUE TITLE
Please add ability to re-order chart headings

### ISSUE THREAD

**Issue by Swuzzlebubble** [GoldenCheetah/GoldenCheetah#1112]
The headings for new charts are added to the right of the pre-existing ones.
However it would be preferable to be able to sequence charts in a logical way or at least group related ones or put in order of most often used. 
Drag & drop would be snappiest, but a list box where you push titles up or down would do the job.

Another suggestion is for the default title of a new chart to be the "Preset" label rather then the chart type (when a Preset is used).
Eg You would get 'Power Profile' instead of 'Metric Trends' as default title if using that preset.

**Comment by liversedge** [comment]
new ux will address this.

**Comment by liversedge** [comment]
Am working on this now see #3395
