### ISSUE TITLE
Filters in custom curves

### ISSUE THREAD

**Issue by matthieudelcourt** [GoldenCheetah/GoldenCheetah#1115]
In the Metric Trends, I was wondering if it was possible to add filters to the option of each curve. As for now filters can be applied to all curves of a given custom plot but it would be awesome to let us filter each curve that we superimpose. For example I created a bunch of new categorical metrics (one of which is "Profile of the ride": which can be "Flat", "Hills", "Mountains") and I would like to plot a variable (say my best 5min speed) for each of those 3 levels within "Profile". So this would give us three different curves ("Flat", "Hills", "Mountains") in a single graph as opposed to just one right now. In case there is no conflict with the existing filter option I think this would be excellent and would add some flexibility in the graphing of our metrics especially when they are categorical. Thanks!

**Comment by liversedge** [comment]
Whilst adding filters for curves is unlikely, the concept of plotting 'sets' of data is important.
We will take a look at this in v3.2

**Comment by liversedge** [comment]
Fixed in aebec00813b1f62321f7123ad45a46d5e00887a5
