### ISSUE TITLE
Text cues to display on screen in training mode

### ISSUE THREAD

**Issue by torbjornjansson** [GoldenCheetah/GoldenCheetah#1118]
Is it possible to include text, defined in the .erg or .mrc file, to display on screen in training mode? I believe that the format allows it but GC doesn't implement it. Something like

[COURSE TEXT]
10 20 This text appears after 10 seconds and is displayed for 20 seconds
15 5 Five seconds later this line shows up below the previous line even before it is gone
[END COURSE TEXT]

**Comment by amtriathlon** [comment]
From #2967:
> There are .zwo workout files with textevents. It would be nice if goldencheetah would display them.
> Example:
> `<textevent timeoffset="559" message="We hope you enjoy todays workout"/>`
to consider when this feature gets implemented.

**Comment by amtriathlon** [comment]
Fomat used by TrainerRoad is described in https://github.com/GoldenCheetah/GoldenCheetah/issues/2098
