### ISSUE TITLE
Delete multiple activities at once

### ISSUE THREAD

**Issue by neury** [GoldenCheetah/GoldenCheetah#1128]
When setting up the user for the first time and importing several activities, some of them can be run or swim sessions or rides without power. Therefore would be very helpful if we could select multiple activities and delete them (I tried to do so in several ways - but I cannot select multiple activities).

**Comment by liversedge** [comment]
This is a BIG change to the way things work and not gonna happen in a hurry!

**Comment by amtriathlon** [comment]
I was thinking it could be implemented as an extension of BatchExportDialog, but not sure if it is the right approach and/or it is important enough.
