### ISSUE TITLE
Changing settings in "Ride" only affect the top graph in full plot.

### ISSUE THREAD

**Issue by yarrouye** [GoldenCheetah/GoldenCheetah#1158]
GC version: 3.1 and Github HEAD
Platforms: OS X, Linux

If "Full plot" is selected (the default), then changing settings with "More..." only affect the top graph. It is unclear if "full plot" means "always plot everything" or "always show the full plot even when using the zoom slider. I think it is the latter. If not, then I would argue that at least some of the options should apply to both curves, for example whether the curves are filled or not, especially as it seems like the default is not the same between 3.1 and what I just cloned from Github today.

Also (probably worth another bug if you do not have it yet), changing the grid setting has zero effect.

**Comment by liversedge** [comment]
Fullplot is the radar plot at the bottom of the screen that provides context for charts at the top.
This is working as designed.
