### ISSUE TITLE
Add Rides list to Train screen for StreetView selection

### ISSUE THREAD

**Issue by gcoco** [GoldenCheetah/GoldenCheetah#1160]
StreetView uses the current ride selected in the Rides pane.
The user should be able to select the ride they wish to use from the Trainer pane.

Add a Rides section on the left to allow the user to select a Ride to view while training.

**Comment by amtriathlon** [comment]
StreetView was removed by https://github.com/GoldenCheetah/GoldenCheetah/commit/99d90dea3255823e1e4acb3f41926b9eccd41e7e
