### ISSUE TITLE
Smart Recording only works on TCX, not FIT files

### ISSUE THREAD

**Issue by TomTraubert** [GoldenCheetah/GoldenCheetah#1164]
I own a Garmin Forerunner 220, the only recording mode avaiable is the "smart recording" mode (no 1 sec. recording mode).
I've checked the  "Use Garmin  Smart Recording"  and set the "Smart recording threshold" to 25 sec. When I try to import the Forerunner's ".fit" file, the software doesn't interpolate every intervals, but some intervals remains longer than 1 sec.. See attached images ("GC Issue 1")for instance, interval between 00:00:06 e 00:00:12. 
Because of this, the time of riding is shorter than the duration (56:16 vs 57:21), even when I didn't made any pause during the training (see image "GC Issue 2")
The second issue I found is that when, for instance, I've some lap of 10 sec., after the importing the durantions become of 7-8 sec. and all the metrics are wrong.

Tom Traubert
![gc issue 2](https://cloud.githubusercontent.com/assets/9916265/5158614/9ff6a5a4-7343-11e4-8470-b601ebfa0372.png)
![gc issue 1](https://cloud.githubusercontent.com/assets/9916265/5158615/a33aac92-7343-11e4-977a-b1389bce64eb.jpg)

**Comment by Joern-R** [comment]
Had a look at the FIT import code - even though it's not checking the Garmin Smart Recording Option there is a function coded to fill gaps in recording - which - just looking at the code should do the job (which is obviously does not - looking at the problem).

@TomTraubert - can you please send me your .FIT file  example(s) with the problem - I will have a look why the code is not working properly and try to fix for 3.11 - mail  -   joern.rm  at  gmail.com

**Comment by amtriathlon** [comment]
Joern, if you need another example here is one: http://connect.garmin.com/modern/activity/610418623, it's a 10k Race, downloaded .tcx shows correct "riding" time equal to  duration (37:05) but .fit (original file) only 36:18 when imported to GC.

**Comment by Joern-R** [comment]
Alejandro, can you please send me both the .FIT and the .TCX per via mail. (Can't download from your connect link myself) The code of handling gaps is in .FIT is different to what the code does in .TCX  gaps (and in .FIT it's not explicitly coded to look at SmartRecording gaps). Need to compare the resulting .JSONs / debug both variants to see where the difference comes from in order to fix. mail - joern.rm @ gmail.com

**Comment by TomTraubert** [comment]
@Joern-R I've sent you the original .fit file.

Thanks for the great work.

Tom Traubert

**Comment by amtriathlon** [comment]
Jörn, Your commit https://github.com/GoldenCheetah/GoldenCheetah/commit/f1a37ea895a939f431ecced84c6f17eaf5d7fd00 fixed the problem for me, thanks!
