### ISSUE TITLE
Setup for Indoor/Outdoor CP W'

### ISSUE THREAD

**Issue by ragman1976** [GoldenCheetah/GoldenCheetah#1167]
Hello,

my CP and W' values for indoor and outdoor cycling are very different. At the moment I always change the settings at the athlete folder when I switch from indoor to outdoor.
It would be very helpfull to have a possibility to set up different values for indoor and outdoor training.

Greets

**Comment by liversedge** [comment]
since you can override in a workout I am closing this.
