### ISSUE TITLE
Support Freemotion Spin Bike data (CSV format)

### ISSUE THREAD

**Issue by gldona** [GoldenCheetah/GoldenCheetah#1168]
Used a Freemotion equipped spin bike at the gym and it downloads to a CSV file on a USB drive.   When trying to upload the file, GC keeps starting that there is no data in the first line.  Download is unsuccessful. I had to manually enter date and time which seemed to initialize OK, just no download.

**Comment by gcoco** [comment]
If you do your own builds then as of the above commit a build that you do would work.
If you do not do your own builds then the next time a development build comes out you will be able to use this feature.
