### ISSUE TITLE
Compare mode

### ISSUE THREAD

**Issue by JensBerger** [GoldenCheetah/GoldenCheetah#1178]
Please add the ability to offset the X - axis of one or another graph in compare mode to better align the compared graphs.

**Comment by montanola** [comment]
It also would be great if axes could be modified as is done in Polar ProTrainer 5: sliding bar shown below
![screen shot 2015-03-24 at 12 05 27 am](https://cloud.githubusercontent.com/assets/3671741/6796096/5c3d981a-d1ba-11e4-9600-f5dbb1d0b5a7.png)

**Comment by leifwar** [comment]
It would be nice to be able to "scale" all selections according to total distance of one of the selections, assuming the distance is equal for the selected comparison. Sometimes doing runs on a fixed course I get different measured distances even when I now they are equal and it would be nice to select one of them as a reference.
