### ISSUE TITLE
Qt Creator cannot build GC because libqwt.a is not installed where it is being looked for

### ISSUE THREAD

**Issue by yarrouye** [GoldenCheetah/GoldenCheetah#1180]
The installation is done relative to the source path, but the link command for GC is relative to where the link is run, which in the case of Qt Creator is in an out of source directory.

The tiny patch below fixes this by putting libqwt.a in the build tree, not the source tree (good when your source tree is read only, too!).

--- a/qwt/src/src.pro
+++ b/qwt/src/src.pro
@@ -17,7 +17,7 @@
 TEMPLATE          = lib
 TARGET            = $$qwtLibraryTarget(qwt)
 
-DESTDIR           = $${QWT_ROOT}/lib
+DESTDIR           = $${OUT_PWD}/../lib
 
 contains(QWT_CONFIG, QwtDll) {

**Comment by Joern-R** [comment]
Committed through https://github.com/GoldenCheetah/GoldenCheetah/commit/70ff5f91e57f3e636a999c0f0ba8daa9255eb9fb
