### ISSUE TITLE
Multiple training devices causing crash

### ISSUE THREAD

**Issue by nagnew** [GoldenCheetah/GoldenCheetah#1181]
OSX 10.6.8
4GB RAM
GC3.1

GC runs fine apart from:  Can either use Computrainer as a training device, or ANT+ USB stick but not both at once, causes spinning wheel of death or program crash.  If I use either one on their own no problem.

What I"m looking to so is for CT to provide power data and ANT+ for HR and cadence

Does 3.1 support two devices at once?  Can post crash log if needed.

**Comment by liversedge** [comment]
is this still a problem I cannot recreate this.

**Comment by nagnew** [comment]
Mark

Yes, still seeing this issue (and maybe you've just received automated crash reports?)

I originally thought it might be outdated hardware/software causing a compatibility issues, but have just retested this on a new system and still have the problem.

The problem only occurs under a defined scenario as follows:

1.	Setup GC to receive input from the CT
1b.	Run GC no problem getting data from the CT

2.	Setup GC to receive input from ANT+ USB stick
2b.	I have two ANT+ devices (Garmin HR and Garmin cadence)
2c.	Run GC getting data from the ANT+ (2 devices, one profile) no problem

3.	However when I run GC trying to get data from both CT and ANT+ it crashes

4.	Have also just discovered that if I setup the ANT+ profile to only get data from one device (e.g. HR) then I can run GC with data from both CT and ANT+.  It's still unstable - crashes sometimes and other times not, but means I can run GC in the following configuration:
CT providing cadence and power
ANT+ providing HR

5.	So basically GC is usable.  Wonder if there;s some conflict with trying to pull cadence from both CT and ANT+?

Will email separately the crash log.

Hardware/software:

GC V3.3

Mac Mini (late 2014)
2.6GHz Intel Core i5
8 GB RAM
OS X 10.11.1 (El Capitan)
ANT+ USB stick (Dynastream Innovations)

CompuTrainer Lab (purchased 2009)

Garmin heart-rate sensor
Garmin cadence sensor 

Regards

Nathan Agnew

**Comment by liversedge** [comment]
Can you send the OS X crash log ?

Thanks
Mark

**Comment by amtriathlon** [comment]
I’m closing this since it refers to an older version and cannot be recreated.
