### ISSUE TITLE
Created a new season and can't open trends now

### ISSUE THREAD

**Issue by wyadbb** [GoldenCheetah/GoldenCheetah#1184]
I have just started using GC. I added a new season - setting the dates, and name but not the LTS stuff.
Now, when I go to Trends, it immediately crashes out.

Crash details here:

Cyclist: "Andrew"

Version Info

Build date: Aug 17 2014 23:59:06
Build id: 3100
Version: 3.1.0
DB Schema: 80
Metrics: 133
OS: Win
QT	4.8.6
QWT	6.1.1
GCC	4.9.0
SRMIO	0.1.1~git1 e84852a
OAUTH	1.0.3
D2XX	yes
QWTPLOT3D	0.2.6
KML	none
ICAL	1.0
USBXPRESS	yes
LIBUSB	yes
Wahoo API	none
VLC	yes
LUCENE	2.3.3.4
VIDEO	vlc

Metric Log

METRIC REFRESH STARTS: Wed 3. Dec 09:13:21 2014
Opening ride: 2014_11_13_07_59_40.fit
File open completed: 2014_11_13_07_59_40.fit
Getting weight: 2014_11_13_07_59_40.fit
Updating statistics: 2014_11_13_07_59_40.fit
Opening ride: 2014_11_13_17_41_33.fit
File open completed: 2014_11_13_17_41_33.fit
Getting weight: 2014_11_13_17_41_33.fit
Updating statistics: 2014_11_13_17_41_33.fit
Opening ride: 2014_11_13_18_15_28.fit
File open completed: 2014_11_13_18_15_28.fit
Getting weight: 2014_11_13_18_15_28.fit
Updating statistics: 2014_11_13_18_15_28.fit
Opening ride: 2014_11_14_16_43_57.fit
File open completed: 2014_11_14_16_43_57.fit
Getting weight: 2014_11_14_16_43_57.fit
Updating statistics: 2014_11_14_16_43_57.fit
Opening ride: 2014_11_15_12_08_25.json
File open completed: 2014_11_15_12_08_25.json
Getting weight: 2014_11_15_12_08_25.json
Updating statistics: 2014_11_15_12_08_25.json
Opening ride: 2014_11_15_13_35_40.fit
File open completed: 2014_11_15_13_35_40.fit
Getting weight: 2014_11_15_13_35_40.fit
Updating statistics: 2014_11_15_13_35_40.fit
Opening ride: 2014_11_15_15_36_58.json
File open completed: 2014_11_15_15_36_58.json
Getting weight: 2014_11_15_15_36_58.json
Updating statistics: 2014_11_15_15_36_58.json
Opening ride: 2014_11_17_08_45_24.fit
File open completed: 2014_11_17_08_45_24.fit
Getting weight: 2014_11_17_08_45_24.fit
Updating statistics: 2014_11_17_08_45_24.fit
Opening ride: 2014_11_17_18_24_30.fit
File open completed: 2014_11_17_18_24_30.fit
Getting weight: 2014_11_17_18_24_30.fit
Updating statistics: 2014_11_17_18_24_30.fit
Opening ride: 2014_11_18_07_54_38.fit
File open completed: 2014_11_18_07_54_38.fit
Getting weight: 2014_11_18_07_54_38.fit
Updating statistics: 2014_11_18_07_54_38.fit
Opening ride: 2014_11_18_18_44_27.fit
File open completed: 2014_11_18_18_44_27.fit
Getting weight: 2014_11_18_18_44_27.fit
Updating statistics: 2014_11_18_18_44_27.fit
Opening ride: 2014_11_20_12_21_25.fit
File open completed: 2014_11_20_12_21_25.fit
Getting weight: 2014_11_20_12_21_25.fit
Updating statistics: 2014_11_20_12_21_25.fit
Opening ride: 2014_11_21_07_48_15.fit
File open completed: 2014_11_21_07_48_15.fit
Getting weight: 2014_11_21_07_48_15.fit
Updating statistics: 2014_11_21_07_48_15.fit
Opening ride: 2014_11_21_17_17_13.fit
File open completed: 2014_11_21_17_17_13.fit
Getting weight: 2014_11_21_17_17_13.fit
Updating statistics: 2014_11_21_17_17_13.fit
Opening ride: 2014_11_23_08_50_19.json
File open completed: 2014_11_23_08_50_19.json
Getting weight: 2014_11_23_08_50_19.json
Updating statistics: 2014_11_23_08_50_19.json
Opening ride: 2014_11_24_07_53_24.fit
File open completed: 2014_11_24_07_53_24.fit
Getting weight: 2014_11_24_07_53_24.fit
Updating statistics: 2014_11_24_07_53_24.fit
Opening ride: 2014_11_25_08_31_53.fit
File open completed: 2014_11_25_08_31_53.fit
Getting weight: 2014_11_25_08_31_53.fit
Updating statistics: 2014_11_25_08_31_53.fit
Opening ride: 2014_11_25_18_12_35.fit
File open completed: 2014_11_25_18_12_35.fit
Getting weight: 2014_11_25_18_12_35.fit
Updating statistics: 2014_11_25_18_12_35.fit
Opening ride: 2014_11_26_12_38_26.json
File open completed: 2014_11_26_12_38_26.json
Getting weight: 2014_11_26_12_38_26.json
Updating statistics: 2014_11_26_12_38_26.json
Opening ride: 2014_11_27_22_22_03.fit
File open completed: 2014_11_27_22_22_03.fit
Getting weight: 2014_11_27_22_22_03.fit
Updating statistics: 2014_11_27_22_22_03.fit
Opening ride: 2014_11_28_07_52_46.fit
File open completed: 2014_11_28_07_52_46.fit
Getting weight: 2014_11_28_07_52_46.fit
Updating statistics: 2014_11_28_07_52_46.fit
Opening ride: 2014_11_30_09_13_47.fit
File open completed: 2014_11_30_09_13_47.fit
Getting weight: 2014_11_30_09_13_47.fit
Updating statistics: 2014_11_30_09_13_47.fit
Opening ride: 2014_12_01_07_36_48.fit
File open completed: 2014_12_01_07_36_48.fit
Getting weight: 2014_12_01_07_36_48.fit
Updating statistics: 2014_12_01_07_36_48.fit
Opening ride: 2014_12_02_08_00_55.fit
File open completed: 2014_12_02_08_00_55.fit
Getting weight: 2014_12_02_08_00_55.fit
Updating statistics: 2014_12_02_08_00_55.fit
COMMIT: Wed 3. Dec 09:13:22 2014
SIGNAL DATA CHANGED: Wed 3. Dec 09:13:22 2014
METRIC REFRESH ENDS: Wed 3. Dec 09:13:22 2014
Athlete Directory

.	Wed 3. Dec 09:13:22 2014
..	Thu 27. Nov 23:24:23 2014
index	Wed 3. Dec 09:13:22 2014
metric.log	Wed 3. Dec 09:13:22 2014
metricDBv3	Wed 3. Dec 09:13:22 2014
seasons.xml	Wed 3. Dec 09:13:03 2014
avatar.png	Wed 3. Dec 09:11:06 2014
hr.zones	Wed 3. Dec 09:11:06 2014
metadata.xml	Wed 3. Dec 09:11:06 2014
power.zones	Wed 3. Dec 09:11:06 2014
2014_11_28_07_52_46.cpx	Wed 3. Dec 09:08:32 2014
2014_11_30_09_13_47.cpx	Wed 3. Dec 09:08:32 2014
2014_12_01_07_36_48.cpx	Wed 3. Dec 09:08:32 2014
2014_12_02_08_00_55.cpx	Wed 3. Dec 09:08:33 2014
2014_12_02_08_00_55.fit	Tue 2. Dec 09:03:20 2014
2014_12_01_07_36_48.fit	Mon 1. Dec 08:43:20 2014
2014_11_30_09_13_47.fit	Sun 30. Nov 10:46:06 2014
analysis-layout.xml	Fri 28. Nov 19:24:27 2014
charts.xml	Fri 28. Nov 19:24:27 2014
namedsearches.xml	Fri 28. Nov 19:24:27 2014
2014_11_28_07_52_46.fit	Fri 28. Nov 08:47:14 2014
diary-layout.xml	Thu 27. Nov 23:56:53 2014
home-layout.xml	Thu 27. Nov 23:56:53 2014
2014_11_15_12_08_25.cpx	Thu 27. Nov 23:56:52 2014
2014_11_15_12_08_25.json	Thu 27. Nov 23:56:52 2014
2014_11_15_15_36_58.cpx	Thu 27. Nov 23:56:52 2014
2014_11_15_15_36_58.json	Thu 27. Nov 23:56:52 2014
2014_11_23_08_50_19.cpx	Thu 27. Nov 23:56:52 2014
2014_11_23_08_50_19.json	Thu 27. Nov 23:56:52 2014
2014_11_26_12_38_26.cpx	Thu 27. Nov 23:56:52 2014
2014_11_26_12_38_26.json	Thu 27. Nov 23:56:52 2014
2014_11_13_07_59_40.cpx	Thu 27. Nov 23:32:22 2014
2014_11_13_17_41_33.cpx	Thu 27. Nov 23:32:22 2014
2014_11_13_18_15_28.cpx	Thu 27. Nov 23:32:22 2014
2014_11_14_16_43_57.cpx	Thu 27. Nov 23:32:22 2014
2014_11_15_13_35_40.cpx	Thu 27. Nov 23:32:22 2014
2014_11_17_08_45_24.cpx	Thu 27. Nov 23:32:23 2014
2014_11_17_18_24_30.cpx	Thu 27. Nov 23:32:23 2014
2014_11_18_07_54_38.cpx	Thu 27. Nov 23:32:23 2014
2014_11_18_18_44_27.cpx	Thu 27. Nov 23:32:23 2014
2014_11_20_12_21_25.cpx	Thu 27. Nov 23:32:23 2014
2014_11_21_07_48_15.cpx	Thu 27. Nov 23:32:23 2014
2014_11_21_17_17_13.cpx	Thu 27. Nov 23:32:23 2014
2014_11_24_07_53_24.cpx	Thu 27. Nov 23:32:23 2014
2014_11_25_08_31_53.cpx	Thu 27. Nov 23:32:23 2014
2014_11_25_18_12_35.cpx	Thu 27. Nov 23:32:23 2014
2014_11_27_22_22_03.cpx	Thu 27. Nov 23:32:23 2014
2014_11_27_22_22_03.fit	Thu 27. Nov 08:50:22 2014
2014_11_26_12_38_26.fit.bak	Wed 26. Nov 13:26:30 2014
2014_11_25_18_12_35.fit	Tue 25. Nov 19:19:08 2014
2014_11_25_08_31_53.fit	Tue 25. Nov 09:32:04 2014
2014_11_24_07_53_24.fit	Mon 24. Nov 17:20:34 2014
2014_11_21_17_17_13.fit	Sun 23. Nov 12:20:40 2014
2014_11_23_08_50_19.fit.bak	Sun 23. Nov 12:20:20 2014
2014_11_21_07_48_15.fit	Fri 21. Nov 08:48:30 2014
2014_11_20_12_21_25.fit	Thu 20. Nov 13:11:58 2014
2014_11_18_18_44_27.fit	Tue 18. Nov 19:43:08 2014
2014_11_18_07_54_38.fit	Tue 18. Nov 09:05:14 2014
2014_11_17_18_24_30.fit	Mon 17. Nov 19:26:34 2014
2014_11_17_08_45_24.fit	Mon 17. Nov 10:13:10 2014
2014_11_15_15_36_58.fit.bak	Sat 15. Nov 16:30:16 2014
2014_11_15_13_35_40.fit	Sat 15. Nov 15:36:46 2014
2014_11_15_12_08_25.fit.bak	Sat 15. Nov 13:25:38 2014
2014_11_14_16_43_57.fit	Fri 14. Nov 18:32:42 2014
2014_11_13_07_59_40.fit	Thu 13. Nov 20:53:00 2014
2014_11_13_17_41_33.fit	Thu 13. Nov 20:53:00 2014
2014_11_13_18_15_28.fit	Thu 13. Nov 20:53:00 2014
All Settings

Andrew/LTSdays	42
Andrew/PMshowSBtoday	0
Andrew/STSdays	7
Andrew/bavigator/headingwidths	0|100|100|
Andrew/dv/url	
Andrew/gc/url	http://race.goldencheetah.org
Andrew/ltmwindow/autofilters	Workout Code|Sport
Andrew/ltmwindow/lastDateRange	{3b6caf86-f95d-4559-a1eb-294e511e05f7}
Andrew/mainwindow/splitterSizes/8	
Andrew/navigator/groupby	-1
Andrew/navigator/headings	*|Workout Code|Date|
Andrew/navigator/sortby	2
Andrew/navigator/sortbyorder	0
Andrew/nickname	
Andrew/safeexit	false
Andrew/splitter/LTM/hide	true
Andrew/splitter/LTM/hide/0	false
Andrew/splitter/LTM/hide/1	false
Andrew/splitter/LTM/hide/2	false
Andrew/splitter/LTM/hide/3	true
Andrew/splitter/LTM/hide/4	false
Andrew/splitter/LTM/hide/5	false
Andrew/splitter/LTM/sizes	
Andrew/splitter/analysis/hide	true
Andrew/splitter/analysis/hide/0	false
Andrew/splitter/analysis/hide/1	true
Andrew/splitter/analysis/hide/2	false
Andrew/splitter/analysis/hide/3	true
Andrew/splitter/diary/hide	true
Andrew/splitter/diary/hide/0	false
Andrew/splitter/diary/hide/1	true
Andrew/splitter/diary/hide/2	false
Andrew/splitter/diary/sizes	
Andrew/splitter/train/hide	true
Andrew/splitter/train/hide/0	false
Andrew/splitter/train/hide/1	false
Andrew/splitter/train/hide/2	false
Andrew/splitter/train/hide/3	false
Andrew/strava_token	0efd23416dbe742f5fa4e332eed24ebac2bec849
Andrew/tp/type	0
Andrew/tp/url	http://www.trainingpeaks.com
Andrew/unit	Metric
Andrew/versionused	3100
Andrew/webcal_url	
Andrew/wi/url	http://wbsapi.withings.net/
Andrew/zeo/url	http://app-pro.myzeo.com:8080/
CALTPOWER	255:0:255
CANTISS	0:255:255
CAPOWER	255:0:255
CATISS	255:0:255
CBALANCELEFT	178:0:0
CBALANCERIGHT	128:0:50
CCALACTUAL	0:255:0
CCALCELL	255:255:255
CCALCURRENT	51:153:255
CCALHEAD	230:230:230
CCALPLANNED	255:255:0
CCALTODAY	0:255:255
CCHROME	108:108:108
CDIAL	160:160:164
CLPS	0:255:255
CLTE	0:255:255
CNPOWER	255:0:255
COLORACCEL	0:255:255
COLORAEROEL	0:255:0
COLORAEROVE	0:0:255
COLORALTITUDESHADE	192:192:192
COLORALTITUTDE	160:160:164
COLORBIKESCORE	160:160:164
COLORCADENCE	0:204:204
COLORCALENDARTEXT	0:0:0
COLORCP	0:255:255
COLORDAILYSTRESS	255:0:0
COLORGRID	65:65:65
COLORHEARTRATE	255:0:0
COLORINTERVALHIGHLIGHTER	0:0:255
COLORLOAD	255:255:0
COLORLTS	0:255:0
COLORPLOTBACKGROUND	52:52:52
COLORPLOTMARKER	0:255:255
COLORPLOTSELECT	0:0:255
COLORPLOTTHUMBNAIL	160:160:164
COLORPLOTTITLE	0:0:0
COLORPLOTTRACKER	0:0:255
COLORPOWER	255:255:0
COLORRIDEPLOTBACKGROUND	52:52:52
COLORRIDEPLOTSYMBOLS	0:255:255
COLORRIDEPLOTXAXIS	0:0:255
COLORRIDEPLOTYAXIS	255:0:0
COLORSB	0:0:0
COLORSPEED	0:255:0
COLORSTS	0:0:255
COLORTEMPERATURE	255:255:0
COLORTORQUE	255:0:255
COLORTRAINPLOTBACKGROUND	0:0:0
COLORTSS	0:255:0
COLORWINDSPEED	0:128:0
COLORZONE1	255:0:255
COLORZONE10	160:160:164
COLORZONE2	42:0:255
COLORZONE3	0:170:255
COLORZONE4	0:255:128
COLORZONE5	85:255:0
COLORZONE6	255:213:0
COLORZONE7	255:0:0
COLORZONE8	160:160:164
COLORZONE9	160:160:164
CPOPUP	192:192:192
CPOPUPTEXT	255:255:255
CRIDECP	255:0:0
CRIDEGROUP	236:246:255
CRPS	255:0:255
CRTE	255:0:255
CSPINSCANLEFT	160:160:164
CSPINSCANRIGHT	0:255:255
CTILEBAR	160:160:164
CTILEBARSELECT	255:255:0
CTOOLBAR	240:240:240
CWBAL	255:0:0
CXPOWER	255:0:255
HRCOLORZONE1	255:0:255
HRCOLORZONE10	160:160:164
HRCOLORZONE2	42:0:255
HRCOLORZONE3	0:170:255
HRCOLORZONE4	0:255:128
HRCOLORZONE5	85:255:0
HRCOLORZONE6	255:213:0
HRCOLORZONE7	255:0:0
HRCOLORZONE8	160:160:164
HRCOLORZONE9	160:160:164
LTS	LTS
LTSname	Long Term Stress
SB	SB
SBname	Stress Balance
STS	STS
STSname	Short Term Stress
antialias	true
chrome	Mac
crankLength	150
dataprocess/fixgaps/stop	1
dataprocess/fixgaps/tolerance	1
dataprocess/fixhrspikes/max	220
dataprocess/fixspikes/max	1500
dataprocess/fixspikes/variance	1000
dataprocess/torqueadjust/adjustment	0 nm
devices	0
dp/Adjust Torque Values/apply	Manual
dp/Fix GPS errors/apply	Manual
dp/Fix Gaps in Recording/apply	Manual
dp/Fix HR Spikes/apply	Manual
dp/Fix Power Spikes/apply	Manual
elevationHysteresis	3.
font/calendar	MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0
font/calendarsize	8
font/chartlabels	MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0
font/chartlabelssize	8
font/chartmarkers	MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0
font/chartmarkerssize	8
font/default	MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0
font/defaultsize	10
font/titles	MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0
font/titlessize	10
garminHWMark	25
garminSmartRecord	2
homedirectory	C:/Users/db2admin/AppData/Local/GoldenCheetah
lang	en
linewidth	0.5
mainwindow/geometry	ÙÐË
mainwindow/lastImportPath	E:/Garmin/Activities
mainwindow/state	
rideBG	false
rideHead	true
rideScroll	true
show/tabbar	false
train/multi	false
wbal/formula	diff
wheelsize	2100
workoutDir	C:/Users/db2admin/AppData/Local/GoldenCheetah

**Comment by liversedge** [comment]
Negative date ranges fixed in 3.11
