### ISSUE TITLE
Time in W'Expended zones

### ISSUE THREAD

**Issue by Swuzzlebubble** [GoldenCheetah/GoldenCheetah#1192]
Create the concept of (user defined) W' Expended zones. 
[eg 0-25%, 25-50%...95%+ or whatever)
Allow user to plot time in W'Exp zones for rides or time periods (ie Ride, Trends, Diary)
Background: 
https://groups.google.com/forum/#!topic/golden-cheetah-users/DqpQz3ipC_U

**Comment by liversedge** [comment]
Fixed in 916e8ee7a1e96f0c87d994c764f1d9393e3b0aec and others.
