### ISSUE TITLE
Update Statistics Crashes repeatedly - Windows 7

### ISSUE THREAD

**Issue by kshaff03** [GoldenCheetah/GoldenCheetah#1197]
I've been using GC 3 for about a year now after upgrading from version 2.  I've always had frequent crashes when opening the application. I have a popup that says updating statistics and then I get a c++ runtime exception. I normally have to reopen GC about 10 to 20 times before it will actually open completely. The crash is random, it doesn't always happen on the same file. 

I love using the software, but obviously this is frustrating and as I continue to add more files, I'm concerned that I'm going to get to the point where I can no longer utilize the application.

Any thoughts on what might be happening?

**Comment by liversedge** [comment]
Fixed in 3.11
