### ISSUE TITLE
Chance resistance level for VP during training

### ISSUE THREAD

**Issue by michie1** [GoldenCheetah/GoldenCheetah#1203]
I'm using a Tacx Satori with the Virtual Power function with resistance level 4. Is is possible to add a function to change the resistance level during a training?

**Comment by TiBall** [comment]
Y, this would be super useful! I would rather call this issue: 
**Allow resistance control for Ant+ FE C trainers**

- Manual Resistance control (percentage) using e.g. up/down button, slider..
- Control resistance based on Power target of a loaded workout

**Comment by michie1** [comment]
@TiBall Back in 2014 I was using the virtual power function of Golden Cheetah without ANT+ FE C trainer, so I won't rename the issue. What you are talking about is a different feature.
