### ISSUE TITLE
GC can't find FTDI for Computrainer

### ISSUE THREAD

**Issue by wackerb** [GoldenCheetah/GoldenCheetah#1210]
I'm an end user (not very Apple savvy) trying to get GC to work on my girlfriend's MacBook Air. If this is the wrong place to post this, please redirect me. Thanks for any help.
MacBook Air, OSX 10.9.5
Installed FTDIUSBSerialDriver_10_4_10_5_10_6_10_7.mpkg
$ cd /dev
$ ls -l *usb*
crw-rw-rw-  1 root  wheel   19,   9 Dec 26 16:12 cu.usbserial-A40091Bx
crw-rw-rw-  1 root  wheel   19,   8 Dec 26 16:12 tty.usbserial-A40091Bx
*** NOTE only B versions, no A, same thing happened on multiple installs

USB device:
FT232R USB UART:

  Product ID:	0x6001
  Vendor ID:	0x0403  (Future Technology Devices International Limited)
  Version:	 6.00
  Serial Number:	A40091Bx
  Speed:	Up to 12 Mb/sec
  Manufacturer:	FTDI
  Location ID:	0x14200000 / 9
  Current Available (mA):	500
  Current Required (mA):	90

Trying to add Racermate Computrainer under Train the search is always unsuccessful.

The hardware works on a Windows system.
I disabled the APPELFTDI driver because I saw where it had broken the FTDI functionality in 10.9, but the same thing happened when it was still enabled.

I also tried the D2XX drivers with no luck.

**Comment by liversedge** [comment]
user request should go to the gc user group forum:
https://groups.google.com/forum/#!forum/golden-cheetah-users
