### ISSUE TITLE
Import from Polar Flowsync 

### ISSUE THREAD

**Issue by davidonribble** [GoldenCheetah/GoldenCheetah#1217]
I see someone has a similar problem, I am using the Polar V800 with Keo Bluetooth power pedals.
Using the Polar Flowsync software to export the training to GoldenCheetah in TCX format, all other data is exported apart from the power data. Have tried using the V800 Downloader app but with the same result. 
Obviously I like using GC to analyse my training data can anybody help with resolving this issue please?
In the process of emailing Polar with this problem (have seen somewhere on their website export to 3rd parts possible).
Alternative does anybody know how to extract data directly from the V800 into GC.

**Comment by Joern-R** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/issues/1212

**Comment by davidonribble** [comment]
Hi Joern

Thanks for your reply to my query, But I need some help with this.

I understand changing ns2 to ns3, but just how do i get into the exported file from flow sync to change this.

Have looked at the link 5529bcf and understand (at least I think I do) what you have done, it’s just been able to open the file in that format to make the change.

Regards

Dave

**Comment by Joern-R** [comment]
Export from Polar is explained here:

http://www.polar.com/en/support/how_do_i_export_individual_training_sessions_from_polar_flow_web_service?product_id=63838&category=faqs

TCX is plain text in XML format style, which you can edit with any text editor available on your system. On Window a very powerful and free text editor is Notepad++ (just google for it if you want to download).

Joern

**Comment by davidonribble** [comment]
Thanks Yes Notepad++ seems very powerful! I am going to state what might seem obvious but I take it that I'll have to change all the ns2 to ns3"s ?. in that case I think it would be a lot easier for my to wait until Golden Cheetah 3.11 is released, if that version will allow direct import of the power data.
