### ISSUE TITLE
Strava upload missing elevation data

### ISSUE THREAD

**Issue by srohweder** [GoldenCheetah/GoldenCheetah#1219]
Golden Cheetah shows the elevation of my ride on a Computrainer but when I share it to Strava it shows no elevation.  Power and cadence seem to pass through just fine.

**Comment by pieterhuibers** [comment]
I have tried this myself and have not found the same issue: my elevation data is uploaded to Strave without any problem. Have you checked the checkbox 'Altitude' when uploading your ride?
