### ISSUE TITLE
Garmin tcx file losing data when creating workout

### ISSUE THREAD

**Issue by freemanmr** [GoldenCheetah/GoldenCheetah#1230]
Loading a Garmin tcx file. Golden Cheetah shows all data, but when I export to a Computrainer CRS file, resulting course is 16 miles long instead of 25. Appears to be a valid CRS file and loads into RacerMate One, but just missing about 9 miles of the workout.

**Comment by liversedge** [comment]
sounds like a metric to imperial conversion gone wrong.

**Comment by freemanmr** [comment]
That is a great insight. Agree. The math works out on totals and for some intermediate values. Miles input is being treated as kilometers input and then converted back to miles. Elevation changes are also showing the same conversion problem. Grades are generally not as steep, although that should be coming directly from the TCX file and not calculated. I am guessing it is being calculated based on elevation change between segments.

 

This is all showing correctly in Golden Cheetah when I read the file in. It is only when it is exported as a Computrainer CRS file that the incorrect conversion seems to occur.

 

Shows the same problem if the input file is a GPX instead of TCX, so again points to conversion on output problem.

**Comment by liversedge** [comment]
will take a peek.

**Comment by freemanmr** [comment]
Thanks Mark. Do you need the TCX file?

**Comment by liversedge** [comment]
I have a few, but go on ! :)

**Comment by freemanmr** [comment]
Tried to send as an attachment and got a mail delivery failure.

**Comment by freemanmr** [comment]
Mark,

 

Any luck?

 

Merf

**Comment by amtriathlon** [comment]
This was fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/24fad147d0815551c1263e87f9c97b6c16f2cc40
