### ISSUE TITLE
No power data when importing a file from Polar Flow

### ISSUE THREAD

**Issue by jpswemmer** [GoldenCheetah/GoldenCheetah#1233]
Hi

Recently the Look Power pedals was converted from W.I.N.D to Bluetooth. In this process it is able to transmit different data then in the past. 
The old W.I.N.D technology files was exported via .HRM format which displayed power data in Golden Cheetah
The new file is being exported in .TCX format. It pulls all the data across ie. Heartrate, Speed, Cadence, Altitude, Lap Times. However no data of power is being displayed.   

I have a file that I can send. 

Thanks

**Comment by Joern-R** [comment]
Fixed in 3.11 - workaround described here

see https://github.com/GoldenCheetah/GoldenCheetah/issues/1212
