### ISSUE TITLE
compare charts screen usage

### ISSUE THREAD

**Issue by dhstuart** [GoldenCheetah/GoldenCheetah#1246]
The charts produced by the compare feature only use a small portion of the screen (or I have been unable to find how to change the size of the chart).

![image](https://cloud.githubusercontent.com/assets/10427496/5729072/517fbb14-9b24-11e4-87a2-fddb8886313c.png)

**Comment by liversedge** [comment]
use zoom in chart settings.
![screenshot from 2015-01-13 21 06 06](https://cloud.githubusercontent.com/assets/142876/5729161/0aac0514-9b68-11e4-9ece-0a828607b7e0.png)

**Comment by dhstuart** [comment]
Thanks for your quick reply!. It seemed like this feature had to be
somewhere and I was just missing it.
