### ISSUE TITLE
CALDAV - enhance authorization flow and allow OAUTH 2.0 for Google CALDAV

### ISSUE THREAD

**Issue by Joern-R** [GoldenCheetah/GoldenCheetah#1254]
Google has changed their Calendar API - and with this introduced OAUTH 2.0 authorization flow also for the CALDAV access (which from an API perspective is unchanged, since CALDAV follows a number of RFC standards.

http://googleappsdeveloper.blogspot.de/search/label/Google%20Calendar%20API

The old API / with old access / has be deprecated in recently - so that Google CALDAV access is not working any more.

When adding OAUTH 2.0 authorization flow it needs to be considered that the Authorization itself is not part of CALDAV - which means it has to be build in a way that the existing approach (no authorization / User/PW authorization) still work (e.g. for access to local CALDAV servers - NAS - or for Calendars working with the existing User/PW approach.

**Comment by liversedge** [comment]
Fixed with commit 338e265969a7a1daa895c6df2e79d916b0b1204b
