### ISSUE TITLE
UPDATE DOCUMENTATION FOR 3.2

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#1257]
To reflect new features etc

**Comment by liversedge** [comment]
Wiki

**Comment by liversedge** [comment]
FAQ

**Comment by Joern-R** [comment]
User Guide - Areas needing change / Enhance this comment if I missed something:
## Cross OS

Train View:
- generally to be done - but only after UX/UI update is done > 3.11

Configuration:
- Multi Sport / Pace Zones
- Autoimport
- Default values / Autocomplete
- CalDAV enhancements
- Zones - point not in zone not add to Z7 (adjust current docu)
- Wheelsize configuration

Use:
- Mark Activities as Swim, Run, ... (how to do that) <fieldvalues>"Bike,Run,Swim"</fieldvalues>
- Multiple new fix tools
- Search not cLucene any more - syntax description
- What's this help assist
- PMC Metrics
- Data Filter/Dynamic filters,...
-- Data Filter "Current"
-- Date STtring
-- ATL, CTL, TSB aliases & PMC data filter functions
- Use any metric for Stress calculator
- Create intervals on Google Map
- New Intervals illustration on AllPlot
- Scatter Plot - Trend Line
- HeatMap
- Veloclinic Plot - will need explanation

- Add a page on "Curves/Data series" explaining the series and potential sources
- Think about adding an overview of the available Metrics / it' getting so many that
   a page - structuring what's available (groups, use) seems helpfull

- New screenshots for adjusted menus, screen,...


## Windows Specific (probably not User Guide but Release Notes)

- Export as .KML

**Comment by liversedge** [comment]
Release Notes
