### ISSUE TITLE
A bug in pace metric?

### ISSUE THREAD

**Issue by mms7r** [GoldenCheetah/GoldenCheetah#1261]
I noticed that the pace metrics for my runs are incorrect (min/mile too fast). To isolate the issue I entered a manual activity with duration 1:00:00, distance 6.0 miles, and average speed 6.0 mph.
The pace for the activity is displayed as 09:39 min/mile. Shouldn't it be 10:00 min/mile?

GC built from master today 1/19/2015 -- Build ID 3102

**Comment by amtriathlon** [comment]
I think I fixed this with today commits, can you try again using the current master?

**Comment by mms7r** [comment]
Yes, that works for me with current master. I like the way you have the default pace correctly set from the values of the manual duration and distance. And a manual pace entry overrides that default. Nice. THANKS!
