### ISSUE TITLE
Seeding LTS for different metrics e.g. BikeScore, RunScore, SwimScore, TSS, An/Ae TISS

### ISSUE THREAD

**Issue by Cander1336** [GoldenCheetah/GoldenCheetah#1267]
Found no good way of using the PMC tab when tracking both the "PMC Coggan" and "Daniel PM" preset charts, due to a season set up with a fixed seeded LTS. If I set a appropriate seed value to fit the Coggan chart, it's fixed for all charts when I toogle in the charts menu and make my Daniel PM chart start with a too high value. Cannot create a new season for the same time period, and making a whole new tab doesn't help because the seasons in the Date menu remains.

Did I miss something or is it a missing functionality?

**Comment by liversedge** [comment]
This is an interesting problem.

In your case I would just say pick a load metric and stick with it. But when we have metrics tracking different types of load (multisport, An, Ae) this is a problem !

Its missing now, but will think about how we can fix it in 3.2

**Comment by Cander1336** [comment]
Manually editing LTS in the season when toggling between the two load metric charts as a temporary solution for now then.

Not a big demand for this feature I guess if it wasn't mentioned before now, as you said most people choose a load metric and stick to it. In my case I want to evaluate these two different ones for some time before choosing
