### ISSUE TITLE
Fix Minoura Virtual Power

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#1268]
On Thursday, 20 November 2014 19:00:46 UTC, Mark Liversedge wrote:
I'd like to get 3.11 out on time, around January.

I appreciate that you have a lot else to do, but if you have a few seconds I'd be grateful if you could update lines 117-172 in RealtimeController.cpp

This should be a straight cut & paste, assuming that I've got the maths syntax correct.
It shifts pow(n*V,3) to n*pow(V,3) & pow(n*V,2) to n*pow(V,2) in order to give the correct power curve.
The data sheet for the trainer is here: http://www.minoura.jp/_userdata/v100_performance-data.pdf 
The difference in the 2 equations can be visualised here: http://fooplot.com/plot/kvppv07onx:

// MINOURA - Has many gears
case 7 : //MINOURA V100 on H
{
double V = rtData.getSpeed();
// 7 = V100 on H: y = -0.0036x^3 + 0.2815x^2 + 3.4978x - 9.7857
rtData.setWatts(-0.0036*pow(V, 3) + 0.2815*pow(V,2) + (3.4978*V) - 9.7857);
}
break;
case 8 : //MINOURA V100 on 5
{
double V = rtData.getSpeed();
// 8 = V100 on 5: y = -0.0023x^3 + 0.2067x^2 + 3.8906x - 11.214
rtData.setWatts(-0.0023*pow(V, 3) + 0.2067*pow(V,2) + (3.8906*V) - 11.214);
}
break;
case 9 : //MINOURA V100 on 4
{
double V = rtData.getSpeed();
// 9 = V100 on 4: y = -0.00173x^3 + 0.1825x^2 + 3.4036x - 10
rtData.setWatts(-0.00173*pow(V, 3) + 0.1825*pow(V,2) + (3.4036*V) - 10.00);
}
break;
case 10 : //MINOURA V100 on 3
{
double V = rtData.getSpeed();
// 10 = V100 on 3: y = -0.0011x^3 + 0.1433x^2 + 2.8808x - 8.1429
rtData.setWatts(-0.0011*pow(V, 3) + 0.1433*pow(V,2) + (2.8808*V) - 8.1429);
}
break;
case 11 : //MINOURA V100 on 2
{
double V = rtData.getSpeed();
// 11 = V100 on 2: y = -0.0007x^3 + 0.1348x^2 + 1.581x - 3.3571
rtData.setWatts(-0.0007*pow(V, 3) +0.1348*pow(V,2) + (1.581*V) - 3.3571);
}
break;
case 12 : //MINOURA V100 on 1
{
double V = rtData.getSpeed();
// 12 = V100 on 1: y = 0.0004x^3 + 0.057x^2 + 1.7797x - 5.0714
rtData.setWatts(0.0004*pow(V, 3) + 0.057*pow(V,2) + (1.7797*V) - 5.0714);
}
break;
case 13 : //MINOURA V100 on L
{
double V = rtData.getSpeed();
// 13 = V100 on L: y = 0.0557x^2 + 1.231x - 3.7143
rtData.setWatts(0.0557*pow(V, 2) + (1.231*V) - 3.7143);
}
break;

**Comment by kamilj** [comment]
Fixed in https://github.com/GoldenCheetah/GoldenCheetah/pull/1349
