### ISSUE TITLE
How save a new device?

### ISSUE THREAD

**Issue by sangogi** [GoldenCheetah/GoldenCheetah#1269]
OS : Win 7 64bit
GC : 3.0

![image](https://cloud.githubusercontent.com/assets/4444700/5857420/00fc708e-a28f-11e4-960b-326103322e1c.png)

I'm paird a powermeter and dual sensor.

![image](https://cloud.githubusercontent.com/assets/4444700/5857352/5b063e4e-a28e-11e4-88bd-684415ac7c37.png)

And next step??

I don't save a new device.

**Comment by Joern-R** [comment]
It's a bug in the QT Wizard Framework on Windows. You need to activate the Aero Theme - then the buttons get visible. Nothing we can do about this for now. Just tested the latest code/latest QT framework. Problem fixed - buttons are also visible on Win7-Basis (no Aero) design.

Details here: https://groups.google.com/forum/?hl=de#!searchin/golden-cheetah-users/ant$20next$20button/golden-cheetah-users/CSrLSdzCeZ8/BT1nktA5xKMJ

Joern
