### ISSUE TITLE
Library tab on trends missing

### ISSUE THREAD

**Issue by asmallsol** [GoldenCheetah/GoldenCheetah#1284]
I just upgraded to  GC3.1 and watched a few of the tutorials videos and to access all the other charts (Skriba power, etc) he clicked the Library tab, then went through all the charts. On mine, there is no library tab, so I went to the "hamburger" menu and tried adding library but that option is not there. Am I missing something?

**Comment by Joern-R** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Side%20Bar_Trends%20view#charts

If you have upgraded from a previous release - non of the new charts is enabled by default - you can reset to default in the menu - but this means any of the own chart configuration is LOST.

The goldencheetah forum might be a better place to post for help whilst you get used to the program.
This is the bug and feature request logging system.
