### ISSUE TITLE
tomtom tcx Sport-Tag

### ISSUE THREAD

**Issue by tomtomGC** [GoldenCheetah/GoldenCheetah#1285]
Hi all,
Importing .tcx files from my TomTom Multisport watch does not function (Sport is always blank).
There is however "Sport" data in the files:
- Biking
- Running
- Other

Furthermore the file names indicate additional categories:
- Filename: Running_xx-xx-xx (XML-info: "Running")
- Filename: Cycling_xx-xx-xx (XML-info: "Biking")
- Filename: Treadmill_xx-xx-xx (XML-info: "Other")
- Filename: Pool_swim_xx-xx-xx (XML-info: "Other")
- Filename: Other_xx-xx-xx (XML-info: "Other")
_xx-xx-xx (indicates the start time of Training)

Any Chance These Infos could be put into the "Sport" tag (ideally the filename's info)?

Thx for your work!

**Comment by amtriathlon** [comment]
The first part was recently fixed in this commit: https://github.com/GoldenCheetah/GoldenCheetah/commit/685699729aeb895cbb9d177683346c962bafd5d6, and it will be included in the next 3.2 release.
