### ISSUE TITLE
Unkown FIT Device 70:-1 // sigmasport

### ISSUE THREAD

**Issue by dconka** [GoldenCheetah/GoldenCheetah#1286]
Hi,

When I import a SIGMA ROX 10.0 GPS .fit File GoldenCheetah just shows "Unknown FIT Device 70:-1. 

The FIT manufacturer id 70 (0x46) is with the string “sigmasport” associated. It would be great if you could update this. 

Thanks a lot for your great support.

Best regards,
Daniel

**Comment by dconka** [comment]
Super! Thanks a lot for your super fast support! :+1: 

Best regards,
Daniel

**Comment by liversedge** [comment]
you got lucky, it was easy to do and quicker to update the code than work out which release to put the feature request in !

**Comment by dconka** [comment]
You're right :)
I just have a further question. Actually there is just one ID for SIGMA SPORT. So if there will be a further device which supports the .fit file, is it possible to have different names for the same ID? As I know, there is actually no way to get as much IDs as Garmin. If there is no way to give different names for the same ID, we could use just "SIGMA SPORT". What do you think?

Thanks a lot for your help. :+1:

**Comment by liversedge** [comment]
If new ids come out we can change the code to match .. at present it sets the product id to -1.
When new products come out they'll need to identify it via that. We update regularly enough to be able to respond.

Not to mention all the ids are actually listed in the FIT SDK profiles .. the FIT code is being refactored to be more robust and complete anyway, so we'll fix it with that. Probably in the release after 3.2.

**Comment by dconka** [comment]
OK, I see you're well prepared! :-) 

Thanks a lot! :+1:
