### ISSUE TITLE
How to add power data to CSV

### ISSUE THREAD

**Issue by JoPieters** [GoldenCheetah/GoldenCheetah#1288]
I would like to add power data to the CSV file that I get from my training App before uploading to Cheetah for analysis. which field name should I use so the data are recognized correctly? Is there an overview of Field Names that Cheetah recognizes from CSV uploads?

**Comment by amtriathlon** [comment]
The PowerTap CSV format has these columns:
Minutes,Torq (N-m),Km/h,Watts,Km,Cadence,Hrate,ID,Altitude (m)
you can look other options in the source code comments https://github.com/GoldenCheetah/GoldenCheetah/blob/5f6c5954720aa6d97a597af6d51b0a41d2d53c7c/src/CsvRideFile.cpp

**Comment by JoPieters** [comment]
Alejandro - thanks. This helps. Will try to use the field names that I
could find.
Jo

2015-01-29 17:09 GMT+01:00 Alejandro Martinez <notifications@github.com>:

**Comment by JoPieters** [comment]
Hi Alejandro,
I am still struggling to get this working. The .tcx download file that I
can create from my training application is loaded in GC without any
problem. With the .cvs file I get errors all the time.
Would it be possible for you to send me an example .csv file of which you
know that GC has no problems. This may help me in correcting the problems
that I have.
Thank you in advance for your help.
Kind regards,
Jo

2015-01-29 19:40 GMT+01:00 Jo Pieters <jo.pm.pieters@gmail.com>:

**Comment by amtriathlon** [comment]
You can find valid files in the test folder: https://github.com/GoldenCheetah/GoldenCheetah/tree/master/test/rides, OTOH
if you prefer .tcx files you could also add power to them.
