### ISSUE TITLE
UPGRADE PROCESS FOR 3.2

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#1298]
Steps required...

**Comment by liversedge** [comment]
Deal with athlete weight metric and measures deprecation

**Comment by liversedge** [comment]
yosemite color defaults

**Comment by liversedge** [comment]
charts.xml needs replacing

**Comment by liversedge** [comment]
some example datafilters (e.g. date based, running, swimming)

**Comment by liversedge** [comment]
setup pace zones for running and swimming.

**Comment by liversedge** [comment]
fix trends view default background color !

**Comment by liversedge** [comment]
time moving not time riding and ride list configuration.

**Comment by liversedge** [comment]
time riding -> time moving in metadata.xml

**Comment by amtriathlon** [comment]
RPE and Session RPE in metadata.xml and PMC(Session RPE) in charts.xml would be interesting too.
