### ISSUE TITLE
After editing activity, activity-list scrolls up to oldest ride

### ISSUE THREAD

**Issue by stigbd** [GoldenCheetah/GoldenCheetah#1300]
Description from Chris
"After importing a file (A FIT from a Garmin 500), I navigate to the "Details" tab where I fill out "Workout Code" and "Sport".  If I hit TAB while in the "workout code" field, the "Rides" pane on the left scrolls all the way back to the very first workout I have--back in 2003."

I can confirm the same behaviour in my build.
![screenshot from 2015-02-04 09 47 01](https://cloud.githubusercontent.com/assets/1702357/6037381/5b5e03a8-ac53-11e4-8a0b-9a1425ce0534.png)

**Comment by cleeland** [comment]
The report from Stig is ubuntu/Qt 5.4.  My report is from OS X 10.10 and Qt 5.3.2 (homebrew install).

**Comment by cleeland** [comment]
@liversedge , if you could point me towards the source files that set up the widget for "workout code" text field and the ride scroll, I'll try to figure out how to make this work as expected.

The behavior I expect is that "tab" from workout code text field will move to the "sport" text field, and have effect on anything else anywhere. A tab-based exit from the field also implies hitting "enter" in the field, accepting the value.

**Comment by liversedge** [comment]
@chris -- it was quite a hard one to fix, check the commit .. but thanks for the offer.

**Comment by stigbd** [comment]
I can confirm that your commit fixed the issue for me, Mark. 
Thanks,
Stig

**Comment by cleeland** [comment]
Were all the changes in the commit directly related to fixing this issue?  If so, then I would have been looking in completely the wrong place to address this.
