### ISSUE TITLE
import file error

### ISSUE THREAD

**Issue by drell** [GoldenCheetah/GoldenCheetah#1302]
V 3.2 import file, tcx and fitlog, the moving time are wrong and consequently the other data, speed …

**Comment by liversedge** [comment]
what file?
what device?
does it import anwhere else?
can your provide a file?
can you provide more precise detail about the error?

**Comment by drell** [comment]
it happens with all tcx file, (and fitlog) in particular if there are laps
you can see for ex here
http://connect.garmin.com/activity/232708013#
if you found a solution please send me .exe file, or a file for win 32bit, i don't want to revert previous version or wait next release
![test](https://cloud.githubusercontent.com/assets/3542159/6057993/6539bb80-ad23-11e4-967d-ebbeeef21bb3.GIF)

**Comment by liversedge** [comment]
it looks like smart recording needs to be turned on in preferences.

**Comment by liversedge** [comment]
send me a tcx file and I'll take a look. liversedge gmail com

**Comment by liversedge** [comment]
you need to send it via email separately -- do not reply to this github notification.
Send in an email to liversedge gmail com :)

**Comment by drell** [comment]
it is likely, I had made a complete reset before install the new version. Can I automatic exclude, calendar text, sport from import a tcx file? I don’t need bike on toolbar

**Comment by liversedge** [comment]
not a bug, garmin smart recording with 3.2 already fixed this.
