### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#1305]
The html based summary has just about run the course and is now getting to be a bit rubbish.
I would like to replace it with a more interactive widget akin to a configurable dashboard.

It has 3 use cases; 
- trend dash
- diary/"today" dash
- ride sumary/"to plan".

**Comment by liversedge** [comment]
This looks nice: http://engage.reconinstruments.com/trips/175773
![screen shot 2015-04-25 at 16 49 02](https://cloud.githubusercontent.com/assets/142876/7333549/0cf95724-eb6b-11e4-867d-23f6e6e8a6cd.png)

**Comment by liversedge** [comment]
Interesting article https://uxmag.com/articles/the-psychology-behind-information-dashboards

**Comment by liversedge** [comment]
MOVING INTO 4.0 SO WE CAN DEPRECATE DEPENDENCIES ON WEBKIT

We will replace the html based summary page with one that uses widgets and animation.

**Comment by liversedge** [comment]
Bringing into 3.4.1 as webkit deprecation is now impacting builds and we need to move to qwebengine.
This means summary needs to be replaced before 3.4.1 can be released.

**Comment by liversedge** [comment]
**PRIOR TO 3.5 WE NEED TO ADD**
* configuration of tile settings, add and delete
* summary for a season

__Some additional tile types might include__
* Top N
* Athlete bests
* Mark a PB on ride summary (?)

**Comment by MaksVasilev** [comment]
Ok, but what way ti enable this? Current master buid - overview screen full blank.

**Comment by liversedge** [comment]
You need to build with QT 5.8.

**Comment by MaksVasilev** [comment]
In rolling-edge release openSUSE Tumbleweed still 5.7.1

**Comment by MaksVasilev** [comment]
May be detect version of Qt and not show new overview panel or show warning? Now it's blank and silent window.

**Comment by liversedge** [comment]
For 3.5 we will only do a summary of a ride. no compare and no season.
Needs to:
* be configurable
* work with different themes

**Comment by liversedge** [comment]
I think it should also respond to interval(s) selection for 3.5.

For some of the card types it doesn't matter -- but for zones, metrics, route etc we could do something interesting.

**Comment by liversedge** [comment]
Configuration of the overview has now been added via two commits:  410aaf6a93e9d4fa01b97db24eae2f61253cc005 and  2b54f68d5055dec5e982595ae41ade0fc1d3a8ab

**Comment by liversedge** [comment]
> You should also add a "More..." button because as it stands, there appears to be absolutely no way to get rid of the Dashboard or Overview charts from the Activities page.

The chart bar now has a drop down for chart settings.

**Comment by liversedge** [comment]
Closing as now has complete core functionality, no doubt more tile types will be added over time, but the main development is now complete... woohoo !

**Comment by liversedge** [comment]
Here we are in August 2021 and the dashboard finally got there, looks like this in v3.6:
![gotthere](https://user-images.githubusercontent.com/142876/128421021-9939a2e8-cdc7-49c4-8ff9-b844eb992108.png)
