### ISSUE TITLE
Stress Metric (SwimScore, GOVSS) fcalculated or wrong type of sport

### ISSUE THREAD

**Issue by Tria-Andy** [GoldenCheetah/GoldenCheetah#1310]
I saw an issue what maybe has two parts.
1) 
SwimScore / SRI is set for all new imported workouts and just after changes were made SwimScore /SRI is gone. Maybe a issue with the preselection of sport type during import. I have definied a DropBox selection for Sport with (Swim, Bike, Run, Body, Tria) and I can see sport is selected automatic.
2)
If values are set manual on e.g. a swim workout GC set GOVSS and IWF on that workout. So the workout has both stress metrics (SwimScore and GOVSS). The values are still there after changes on the workout and GOVSS has to be set to 0 manual. If it´s getting unchecked GOVSS value is back again.

**Comment by amtriathlon** [comment]
I could reproduce the problem, the running and swimming metrics doesn't set the value in the compute method when the activity corresponds to another sport, the update process would be reusing an instance which keeps the value from a previous invocation.
I will change the metrics to always set the value, but probably the update process also would need changes to avoid the same problem with other metrics.

**Comment by liversedge** [comment]
I have pulled your update, but we could call setValue(0.0) in compute beforehand to reset ?

**Comment by amtriathlon** [comment]
Yes, I think it would be a good idea to call setValue(0.0) and setCount(0) in RideMetric::computeMetrics as a prophylactic measure, other metrics have the same behavior. Is there another place to look for?

**Comment by liversedge** [comment]
No, I'm pretty confident ::computeMetrics() is all that needs to change
