### ISSUE TITLE
Mac config folders - mackup integration

### ISSUE THREAD

**Issue by jverdeyen** [GoldenCheetah/GoldenCheetah#1318]
Hi!

This isn't really an issue, just a request.

I would like to integrate GoldenCheetah with Mackup. Mackup is a configuration backup tool for Mac. This means settings and data is synced accross my Macbooks.
https://github.com/lra/mackup

Which folders are critical to share all settings and data this way?

Kind regards!

**Comment by liversedge** [comment]
please use forums for these kinds of requests.
