### ISSUE TITLE
Mac OSX - dragging mouse in 'ride' window crashes app

### ISSUE THREAD

**Issue by RJKflyer** [GoldenCheetah/GoldenCheetah#1337]
In the Ride Window, with Tabbed not Tiled display option, clicking and dragging the mouse on any of the graphs crashes the app.

**Comment by liversedge** [comment]
please provide a specific example and version info?

thanks

**Comment by RJKflyer** [comment]
Sorry Mark, try as I might I cannot now replicate it…

Closed…




On 22 May 2015, at 09:28, Mark Liversedge <notifications@github.com> wrote:

please provide a specific example and version info?

thanks
