### ISSUE TITLE
Mac OS X - CMD key api not being followed

### ISSUE THREAD

**Issue by RJKflyer** [GoldenCheetah/GoldenCheetah#1338]
Example: delete a ride, and a dialogue box asks for confirmation with two buttons: Cancel and Delete.

Cancel is correctly highlighted as 'default'

However, under Mac OS X, CMD and first letter of each button should enact the button.

So, CMD D should 'delete'

**Comment by liversedge** [comment]
There is no shortcut for delete on that dialog box.
