### ISSUE TITLE
Schwinn AC spin bike/ MPower console support request

### ISSUE THREAD

**Issue by cabracadabra** [GoldenCheetah/GoldenCheetah#1340]
Ultimately, I would like to import my indoor trainer workouts into Strava, showing distance, power, cadence.  I have looked and looked and have not found a way.  Strava accepts .tcx, .gpx or .fit files.  What the trainer generates via USB stick is a .csv file.  A truncated example is below.  I am able to view with Excel of course, and also can put in Training Peaks, but there is no free way to sync from Training Peaks (which I don't use normally) to Strava.  You'll see that the data below has no location information, thus I can't convert to .gpx (or haven't found a way).  Strava will accept non-moving, non-location files via Garmin Connect, but I don't use it nor have a Garmin device.  I normally do MTB ride w/ my Android phone and Strava.  When I tried to use Golden Cheetah to upload, it prompted for a date, I entered it, then it did not save correctly and now crashes everytime I open it after selecting the same athlete.  Any suggestions on how to get the file below to be compatible with a Strava upload?

Stage_Workout (min),Distance(mile),Speed (mph),Watts ,HR ,RPM 
0.1,0.038,21.71,192,0,66
0.2,0.067,12.79,50,0,19
0.3,0.088,18.46,126,0,71
0.4,0.126,23.80,245,0,106
0.5,0.163,21.49,187,0,102
0.6,0.199,20.95,175,0,100
0.7,0.234,20.68,169,0,98
0.8,0.268,20.77,171,0,98
0.9,0.303,20.38,163,0,94
1.0,0.336,18.35,124,0,67
1.1,0.358,10.93,35,0,36
1.2,0.372,4.58,8,0,14
1.3,0.376,2.09,3,0,5
>>>truncated
Stage_01_Total,
Stage distance(mile),3.591,
Speed Max (mph),27.68,
Watts Max,370
HR Max,0
RPM Max,106
KCal,139
10.1,3.627,26.30,321,0,90
10.2,3.675,29.10,427,0,84
10.3,3.721,28.07,385,0,80
10.4,3.767,27.19,352,0,80
10.5,3.812,27.38,359,0,80
10.6,3.858,26.91,342,0,80
10.7,3.903,27.73,372,0,80
>>>truncated

Stage_02_Total,
Stage distance(mile),2.281,
Speed Max (mph),29.73,
Watts Max,455
HR Max,0
RPM Max,93
KCal,103

16.1,5.888,18.75,131,0,87
16.2,5.927,27.86,377,0,88
16.3,5.972,26.88,341,0,82
16.4,6.016,26.45,326,0,82
16.5,6.061,26.27,320,0,80
16.6,6.105,27.00,345,0,83
16.7,6.150,26.77,337,0,84
>>>truncated

Stage_06_Total,
Stage distance(mile),2.903,
Speed Max (mph),29.73,
Watts Max,385
HR Max,0
RPM Max,110
KCal,105

Stage_Totals
Total Time,43.0,minutes
Total_distance:,15.288,
Speed Avg(mph),21.33,
Watts Avg,205
HR Avg,0
RPM Avg,80
Speed Max (mph),29.73,
Watts Max,455
HR Max,0
RPM Max,113
KCal,620

**Comment by j33433** [comment]
I realize this is an old issue, but I'm working on a beta version for a MPower to TCX converter. If anyone has non-truncated test files, please send to j33433@gmail.com

**Comment by j33433** [comment]
I've released my MPower tool. Binaries are available for Windows and OS X.

https://github.com/j33433/MPowerTCX
