### ISSUE TITLE
incorrect (much too high) 20min max power value

### ISSUE THREAD

**Issue by rollenfahrer** [GoldenCheetah/GoldenCheetah#1342]
When importing files from PerfPro Studio I noticed that the 20min max power value (potentially also others) seem to be calculated incorrectly. Obvious indication is that the max value shown by GC 3.2 in the observed case is higher than any single power sample in the file.
After analyzing the performance file in question I suspect that the problem arises from the fact that PerfPro stores the power samples in non-equidistant time intervals (little less than 1s).
I hacked the performance file such that the sampling instants are tied to a regular 1s grid, which gave correct max values in GC, hence this supports my theory.
Would have attached the performance file but don't know how.
Do you have a solution for this (quite annoying) issue?

BR

**Comment by liversedge** [comment]
tools > fix gaps

**Comment by rollenfahrer** [comment]
Hi Mark,

thanks for your quick answer. I checked the fix gaps setting. It says tolerance=1, stop=1. But it has no effect.
I think the problem is not caused by gaps in the activity file because there are no gaps in it.
I'd rather suspect that the max-power interval calculation does not properly handle activities that are sampled on an (slightly) irregular grid.
If you tell me how, I'll send you the activity file so that you can check it yorself.

BR

**Comment by rollenfahrer** [comment]
Hi Mark,

I've written a simple perl-script that resamples the file causing wrong max-values to a 1s grid by linear interpolation (see below). The input file is assumed to be in pwx format. That solves the issue for me, yet it's a bit inconvenient as it requires manual execution before each import. Is there a way to automate that in GC somehow?

BR

#!/usr/bin/perl

$k = 0;
$lastdist = 0;
$lastpwr = 0;
$lasthr = 0;
$lastspd = 0;
$lastcad = 0;
$lastt = 0;

while(<>) {
		if (!m/<sample>/) {
			print;
		} else {
			while(m|<sample><timeoffset>([0-9.]+)</timeoffset><hr>([0-9.]+)</hr><pwr>([0-9.]+)</pwr><spd>([0-9.]+)</spd><cad>([0-9.]+)</cad><dist>([0-9.]+)</dist></sample>|g) {
				if ( $1 == 0 ) {
					print $&;
					$k++;
				} else {
					while( $1 >= $k ) {
						$dt = ($k - $lastt)/($1 - $lastt);
						print  "<sample><timeoffset>".$k."</timeoffset><hr>".($lasthr+$dt*($2-$lasthr))."</hr><pwr>".($lastpwr+$dt*($3-$lastpwr))."</pwr><spd>".($lastspd+$dt*($4-$lastspd))."</spd><cad>".($lastcad+($5-$lastcad))."</cad><dist>".($lastdist+$dt*($6-$lastdist))."</dist></sample>";
						$k++;
					}
				}
				$lastt = $1;
				$lasthr = $2;
				$lastpwr = $3;
				$lastspd = $4;
				$lastcad = $5;
				$lastdist = $6;
				$rol = $';
			}
			print $rol;
		}
}

**Comment by liversedge** [comment]
You need to set stop to 30s or similar. That defines the minimum gap that will not be interpolated.

The explainer text explains the meaning of the parameters .

**Comment by rollenfahrer** [comment]
Hi Mark, I tried that with no effect. Maybe I don't really understand how the tool work. Is it sufficient to set the value or do I have to do anything else to make it effective for a specific workout? Or does it have effect on all files in the database or only on newly imported ones?
Moreover, when I re-open the dialogue, the previously set stop value is reset to 1 again.

All over, I don't believe that it's a gap issue since there are no gaps in the file. It's just that the samples coming from the kickr have a jitter of +/-200ms. An even if there were gaps it's hard to understand why this should give a 20min max value of 350W although all samples are below 320W.
