### ISSUE TITLE
When uploading a Garmin.gpx file the import screen stays at 50% and doesn't load any power data?

### ISSUE THREAD

**Issue by jefftinianow** [GoldenCheetah/GoldenCheetah#1344]

**Comment by RJKflyer** [comment]
Am no expert, but I know that some .gpx formats do NOT contain power data.

e.g. exporting .gpx from Strava, Strava says: "The file will then download to your computer with the file extension ".gpx". This file will contain your GPS coordinates, timestamps and accessory data like Heart Rate, Cadence and temperature. This feature does not export Power data."
