### ISSUE TITLE
highlight current ride in trends summary bests (please)

### ISSUE THREAD

**Issue by Swuzzlebubble** [GoldenCheetah/GoldenCheetah#1345]
Would it be possible to highlight the current ride or today's date in the Trends/summary/bests ?
To make it easier to spot them

![bests](https://cloud.githubusercontent.com/assets/7111597/6502388/29a9fd04-c377-11e4-9bd9-bf7387486c00.JPG)

**Comment by liversedge** [comment]
it highlights todays ride.
