### ISSUE TITLE
Full Screen Window in 3.2 - no exit possible

### ISSUE THREAD

**Issue by BorisHendrik** [GoldenCheetah/GoldenCheetah#1348]
Hello,

I hope this is the right place to mention this error and I don't bother you:

If version 3.2 is in full screen, it is not possible to close the full screen mode.
The green point in the upper left corner should appear if the mouse moves to the upper border of the window but is hidden behind the OSX menu bar. 

The search box appears twice. Maybe this is related.

![screen shot 2015-03-16 at 22 21 34](https://cloud.githubusercontent.com/assets/9917178/6676804/e09de032-cc2a-11e4-9297-3f185dba6d27.png)

![screen shot 2015-03-16 at 22 30 38](https://cloud.githubusercontent.com/assets/9917178/6676965/282f4016-cc2c-11e4-9d25-46d4cb75ebfb.png)

Build id 3102, under OSX 10.10.2

**Comment by liversedge** [comment]
yes it is a build issue. works ok on qt 5.3 rc1.
we need QT to fix it ...

**Comment by liversedge** [comment]
closing as not a GC bug.
