### ISSUE TITLE
Aerobic Power chart (Trends) no longer displays all power points.

### ISSUE THREAD

**Issue by PaulERoberts** [GoldenCheetah/GoldenCheetah#1353]
![screen shot 2015-04-03 at 12 17 49 am](https://cloud.githubusercontent.com/assets/11782347/6979329/356b83de-d997-11e4-9e82-f315185e7075.png)

**Comment by liversedge** [comment]
it is displaying for the date range selected.

**Comment by liversedge** [comment]
also check the binning is not weeks or months
