### ISSUE TITLE
"Ride" graph ( in Rides) no longer displays altitude. (

### ISSUE THREAD

**Issue by PaulERoberts** [GoldenCheetah/GoldenCheetah#1354]
Altitude does, however, display in Garmin Express, before file is exported to GC.)  

![screen shot 2015-04-03 at 12 22 56 am](https://cloud.githubusercontent.com/assets/11782347/6979396/f056d82e-d997-11e4-9b12-68af032b7aed.png)

**Comment by liversedge** [comment]
check chart settings.
