### ISSUE TITLE
Crash when trying to view Ride tab

### ISSUE THREAD

**Issue by jwmott** [GoldenCheetah/GoldenCheetah#1361]
GoldenCheetah consistently crashes whenever I try to view the Ride tab. 
![errormessage](https://cloud.githubusercontent.com/assets/11988289/7195761/f652ddd8-e48a-11e4-98d2-62a616560ab4.png)

Crash Report:

Cyclist: "Jim Mott"

Version Info

Build date: Aug 17 2014 23:59:06
Build id: 3100
Version: 3.1.0
DB Schema: 80
Metrics: 133
OS: Win
QT	4.8.6
QWT	6.1.1
GCC	4.9.0
SRMIO	0.1.1~git1 e84852a
OAUTH	1.0.3
D2XX	yes
QWTPLOT3D	0.2.6
KML	none
ICAL	1.0
USBXPRESS	yes
LIBUSB	yes
Wahoo API	none
VLC	yes
LUCENE	2.3.3.4
VIDEO	vlc

Metric Log

METRIC REFRESH STARTS: Wed Apr 15 22:53:20 2015
Opening ride: 2015_04_15_18_08_42.fit
File open completed: 2015_04_15_18_08_42.fit
Getting weight: 2015_04_15_18_08_42.fit
Updating statistics: 2015_04_15_18_08_42.fit
COMMIT: Wed Apr 15 22:53:20 2015
SIGNAL DATA CHANGED: Wed Apr 15 22:53:20 2015
METRIC REFRESH ENDS: Wed Apr 15 22:53:21 2015
Athlete Directory

.	Wed Apr 15 22:53:20 2015
..	Tue May 13 23:51:37 2014
index	Wed Apr 15 22:53:20 2015
metric.log	Wed Apr 15 22:53:21 2015
metricDBv3	Wed Apr 15 22:53:20 2015
2015_04_15_18_08_42.cpx	Wed Apr 15 22:53:18 2015
2015_04_15_18_08_42.fit	Wed Apr 15 22:21:47 2015
charts.xml	Fri Mar 27 22:44:14 2015
analysis-layout.xml	Fri Mar 27 22:44:10 2015
namedsearches.xml	Fri Mar 27 22:44:08 2015
2015_03_18_21_05_55.cpx	Sun Mar 22 21:04:08 2015
2015_03_21_18_02_19.cpx	Sun Mar 22 21:04:08 2015
2015_03_21_18_02_19.fit	Sun Mar 22 20:51:03 2015
2015_03_18_21_05_55.fit	Sun Mar 22 20:50:52 2015
2015_03_09_22_50_08.cpx	Sun Mar 15 22:04:32 2015
2015_03_13_00_05_57.cpx	Sun Mar 15 22:04:32 2015
2015_03_13_20_45_55.cpx	Sun Mar 15 22:04:31 2015
2015_03_14_16_11_32.cpx	Sun Mar 15 22:04:31 2015
2015_03_15_13_30_21.cpx	Sun Mar 15 22:04:30 2015
2015_03_15_13_30_21.fit	Sun Mar 15 21:39:35 2015
2015_03_14_16_11_32.fit	Sun Mar 15 21:39:21 2015
2015_03_13_20_45_55.fit	Sun Mar 15 21:39:08 2015
2015_03_13_00_05_57.fit	Sun Mar 15 21:38:54 2015
2015_03_09_22_50_08.fit	Sun Mar 15 21:38:46 2015
2015_03_02_22_43_43.cpx	Sun Mar 8 20:36:22 2015
2015_03_05_23_09_00.cpx	Sun Mar 8 20:36:21 2015
2015_03_06_20_37_51.cpx	Sun Mar 8 20:36:21 2015
2015_03_06_20_37_51.fit	Sat Mar 7 12:16:32 2015
2015_03_05_23_09_00.fit	Sat Mar 7 12:16:22 2015
2015_03_02_22_43_43.fit	Sat Mar 7 12:16:04 2015
home-layout.xml	Sat Feb 28 22:16:46 2015
avatar.png	Sat Feb 28 22:16:26 2015
hr.zones	Sat Feb 28 22:16:26 2015
metadata.xml	Sat Feb 28 22:16:26 2015
power.zones	Sat Feb 28 22:16:26 2015
2015_02_24_20_44_35.cpx	Sat Feb 28 22:10:06 2015
2015_02_27_00_05_30.cpx	Sat Feb 28 22:10:06 2015
2015_02_28_20_50_08.cpx	Sat Feb 28 22:10:06 2015
2015_02_28_20_50_08.fit	Sat Feb 28 21:34:12 2015
2015_02_27_00_05_30.fit	Sat Feb 28 21:34:05 2015
2015_02_24_20_44_35.fit	Sat Feb 28 21:33:59 2015
2015_01_29_23_52_25.cpx	Sun Feb 22 19:13:10 2015
2015_01_31_09_31_42.cpx	Sun Feb 22 19:13:10 2015
2015_02_03_20_30_15.cpx	Sun Feb 22 19:13:10 2015
2015_02_06_08_48_24.cpx	Sun Feb 22 19:13:09 2015
2015_02_10_19_50_44.cpx	Sun Feb 22 19:13:09 2015
2015_02_13_09_35_01.cpx	Sun Feb 22 19:13:09 2015
2015_02_16_08_29_17.cpx	Sun Feb 22 19:13:08 2015
2015_02_18_21_14_14.cpx	Sun Feb 22 19:13:08 2015
2015_02_20_19_47_47.cpx	Sun Feb 22 19:13:08 2015
2015_02_22_13_02_58.cpx	Sun Feb 22 19:13:07 2015
2015_02_22_13_02_58.fit	Sun Feb 22 18:56:41 2015
2015_02_20_19_47_47.fit	Sun Feb 22 18:56:38 2015
2015_02_18_21_14_14.fit	Sun Feb 22 18:56:34 2015
2015_02_16_08_29_17.fit	Sun Feb 22 18:56:29 2015
2015_02_13_09_35_01.fit	Sun Feb 22 18:56:25 2015
2015_02_10_19_50_44.fit	Sun Feb 22 18:56:23 2015
2015_02_06_08_48_24.fit	Sun Feb 22 18:56:19 2015
2015_02_03_20_30_15.fit	Sun Feb 22 18:56:16 2015
2015_01_31_09_31_42.fit	Sun Feb 22 18:56:11 2015
2015_01_29_23_52_25.fit	Sun Feb 22 18:56:08 2015
2015_01_13_21_32_52.fit.bak	Sun Feb 22 18:56:05 2015
2014_10_19_15_34_33.cpx	Fri Oct 24 00:02:37 2014
diary-layout.xml	Fri Oct 24 00:00:09 2014
2014_10_19_15_34_33.fit	Thu Oct 23 23:34:29 2014
2014_09_28_14_29_01.cpx	Mon Oct 20 21:11:48 2014
2014_10_01_17_44_00.cpx	Mon Oct 20 21:11:48 2014
2014_10_07_17_09_33.cpx	Mon Oct 20 21:11:47 2014
2014_10_08_17_31_04.cpx	Mon Oct 20 21:11:47 2014
2014_10_11_16_44_05.cpx	Mon Oct 20 21:11:46 2014
2014_10_12_17_35_21.cpx	Mon Oct 20 21:11:45 2014
2014_10_16_17_21_20.cpx	Mon Oct 20 21:11:45 2014
2014_10_18_14_45_45.cpx	Mon Oct 20 21:11:45 2014
2014_10_18_14_45_45.fit	Sat Oct 18 18:11:54 2014
2014_10_16_17_21_20.fit	Thu Oct 16 20:58:19 2014
2014_10_12_17_35_21.fit	Thu Oct 16 20:58:15 2014
2014_10_11_16_44_05.fit	Thu Oct 16 20:58:11 2014
2014_10_11_16_37_43.fit.bak	Thu Oct 16 20:58:06 2014
2014_10_08_17_31_04.fit	Thu Oct 16 20:58:05 2014
2014_10_07_17_09_33.fit	Thu Oct 16 20:58:00 2014
2014_10_01_17_44_00.fit	Thu Oct 16 20:57:54 2014
2014_09_28_14_29_01.fit	Mon Sep 29 20:19:40 2014
2014_09_07_13_45_49.cpx	Wed Sep 24 22:50:27 2014
2014_09_07_17_23_59.cpx	Wed Sep 24 22:50:27 2014
2014_09_08_18_20_42.cpx	Wed Sep 24 22:50:27 2014
2014_09_11_19_01_16.cpx	Wed Sep 24 22:50:27 2014
2014_09_17_17_43_02.cpx	Wed Sep 24 22:50:28 2014
2014_09_24_17_42_12.cpx	Wed Sep 24 22:50:28 2014
2014_08_27_17_59_45.cpx	Wed Sep 24 22:50:25 2014
2014_08_31_16_10_14.cpx	Wed Sep 24 22:50:25 2014
2014_09_01_17_20_10.cpx	Wed Sep 24 22:50:25 2014
2014_09_02_17_32_14.cpx	Wed Sep 24 22:50:26 2014
2014_09_03_17_48_12.cpx	Wed Sep 24 22:50:26 2014
2014_09_05_08_04_48.cpx	Wed Sep 24 22:50:26 2014
2014_09_06_17_21_03.cpx	Wed Sep 24 22:50:26 2014
2014_09_07_11_35_13.cpx	Wed Sep 24 22:50:26 2014
2014_06_08_18_36_25.cpx	Wed Sep 24 22:50:23 2014
2014_06_08_19_03_22.cpx	Wed Sep 24 22:50:24 2014
2014_06_11_18_10_07.cpx	Wed Sep 24 22:50:24 2014
2014_06_25_07_31_15.cpx	Wed Sep 24 22:50:24 2014
2014_06_25_18_19_01.cpx	Wed Sep 24 22:50:24 2014
2014_06_26_19_51_30.cpx	Wed Sep 24 22:50:24 2014
2014_08_25_18_36_19.cpx	Wed Sep 24 22:50:25 2014
2014_04_23_18_02_21.cpx	Wed Sep 24 22:50:22 2014
2014_05_14_18_03_48.cpx	Wed Sep 24 22:50:22 2014
2014_05_21_18_04_47.cpx	Wed Sep 24 22:50:23 2014
2014_05_28_18_08_13.cpx	Wed Sep 24 22:50:23 2014
2014_05_31_09_07_24.cpx	Wed Sep 24 22:50:23 2014
2014_09_24_17_42_12.fit	Wed Sep 24 20:59:15 2014
2014_09_17_17_43_02.fit	Thu Sep 18 19:43:57 2014
2014_09_11_19_01_16.fit	Thu Sep 18 19:43:43 2014
2014_09_08_18_20_42.fit	Thu Sep 18 19:43:40 2014
2014_09_07_13_45_49.json	Sun Sep 7 21:26:49 2014
2014_09_07_17_23_59.json	Sun Sep 7 21:26:49 2014
2014_09_07_11_35_13.fit	Sun Sep 7 19:57:39 2014
2014_09_06_17_21_03.fit	Sun Sep 7 19:57:35 2014
2014_09_05_08_04_48.fit	Sun Sep 7 19:57:27 2014
2014_09_03_17_48_12.fit	Sun Sep 7 19:57:25 2014
2014_09_02_17_32_14.fit	Tue Sep 2 18:04:54 2014
2014_09_01_17_20_10.fit	Tue Sep 2 18:04:51 2014
2014_08_31_16_10_14.fit	Tue Sep 2 18:04:44 2014
2014_08_27_17_59_45.fit	Wed Aug 27 21:06:11 2014
2014_08_25_18_36_19.fit	Mon Aug 25 22:15:45 2014
2014_06_26_19_51_30.fit	Mon Jun 30 20:55:22 2014
2014_06_25_18_19_01.fit	Mon Jun 30 20:55:18 2014
2014_06_25_07_31_15.fit	Mon Jun 30 20:55:12 2014
2014_06_11_18_10_07.json	Fri Jun 13 22:26:07 2014
2014_06_08_19_03_22.fit	Fri Jun 13 21:51:07 2014
2014_06_08_18_36_25.fit	Fri Jun 13 21:51:01 2014
2014_05_31_09_07_24.fit	Sun Jun 1 09:51:15 2014
2014_05_28_18_08_13.fit	Wed May 28 22:21:54 2014
2014_05_21_18_04_47.fit	Wed May 21 21:34:43 2014
2014_05_14_18_03_48.fit	Wed May 14 22:29:25 2014
2014_04_23_18_02_21.fit	Thu Apr 24 00:38:30 2014
All Settings

CALTPOWER	255:0:255
CANTISS	0:255:255
CAPOWER	255:0:255
CATISS	255:0:255
CBALANCELEFT	178:0:0
CBALANCERIGHT	128:0:50
CCALACTUAL	0:255:0
CCALCELL	255:255:255
CCALCURRENT	51:153:255
CCALHEAD	230:230:230
CCALPLANNED	255:255:0
CCALTODAY	0:255:255
CCHROME	128:128:128
CDIAL	160:160:164
CLPS	0:255:255
CLTE	0:255:255
CNPOWER	255:0:255
COLORACCEL	0:255:255
COLORAEROEL	0:255:0
COLORAEROVE	0:0:255
COLORALTITUDESHADE	192:192:192
COLORALTITUTDE	160:160:164
COLORBIKESCORE	160:160:164
COLORCADENCE	0:204:204
COLORCALENDARTEXT	0:0:0
COLORCALIBRATIONMARKER	40:40:40
COLORCP	255:0:0
COLORDAILYSTRESS	255:0:0
COLORGRID	47:47:47
COLORHEARTRATE	255:0:0
COLORINTERVALHIGHLIGHTER	0:0:255
COLORLOAD	255:255:0
COLORLTS	0:255:0
COLORPLOTBACKGROUND	52:52:52
COLORPLOTMARKER	0:255:255
COLORPLOTSELECT	0:0:255
COLORPLOTTHUMBNAIL	160:160:164
COLORPLOTTITLE	0:0:0
COLORPLOTTRACKER	0:0:255
COLORPOWER	255:255:0
COLORRIDEPLOTBACKGROUND	52:52:52
COLORRIDEPLOTSYMBOLS	0:255:255
COLORRIDEPLOTXAXIS	0:255:255
COLORRIDEPLOTYAXIS	0:255:255
COLORSB	0:0:0
COLORSPEED	0:255:0
COLORSTS	0:0:255
COLORTEMPERATURE	255:255:0
COLORTORQUE	255:0:255
COLORTRAINPLOTBACKGROUND	52:52:52
COLORTSS	0:255:0
COLORWINDSPEED	0:128:0
COLORZONE1	255:0:255
COLORZONE10	160:160:164
COLORZONE2	42:0:255
COLORZONE3	0:170:255
COLORZONE4	0:255:128
COLORZONE5	85:255:0
COLORZONE6	255:213:0
COLORZONE7	255:0:0
COLORZONE8	160:160:164
COLORZONE9	160:160:164
CPOPUP	192:192:192
CPOPUPTEXT	255:255:255
CRIDECP	255:0:0
CRIDEGROUP	236:246:255
CRPS	255:0:255
CRTE	255:0:255
CSPINSCANLEFT	160:160:164
CSPINSCANRIGHT	0:255:255
CTILEBAR	160:160:164
CTILEBARSELECT	255:255:0
CTOOLBAR	240:240:240
CWBAL	255:0:0
CXPOWER	255:0:255
HRCOLORZONE1	255:0:255
HRCOLORZONE10	160:160:164
HRCOLORZONE2	42:0:255
HRCOLORZONE3	0:170:255
HRCOLORZONE4	0:255:128
HRCOLORZONE5	85:255:0
HRCOLORZONE6	255:213:0
HRCOLORZONE7	255:0:0
HRCOLORZONE8	160:160:164
HRCOLORZONE9	160:160:164
Jess Yurchich/bavigator/headingwidths	0|29|50|120|
Jess Yurchich/blank/analysis	false
Jess Yurchich/blank/diary	false
Jess Yurchich/blank/home	false
Jess Yurchich/blank/train	false
Jess Yurchich/ltmwindow/lastDateRange	{00000000-0000-0000-0000-000000000001}
Jess Yurchich/mainwindow/splitterSizes	
Jess Yurchich/navigator/groupby	-1
Jess Yurchich/navigator/headings	*|Workout Code|TSS|Date|
Jess Yurchich/navigator/sortby	2
Jess Yurchich/navigator/sortbyorder	0
Jess Yurchich/safeexit	true
Jess Yurchich/splitter/LTM/hide	true
Jess Yurchich/splitter/LTM/hide/0	false
Jess Yurchich/splitter/LTM/hide/1	false
Jess Yurchich/splitter/LTM/hide/2	false
Jess Yurchich/splitter/LTM/hide/3	true
Jess Yurchich/splitter/analysis/hide	true
Jess Yurchich/splitter/analysis/hide/0	false
Jess Yurchich/splitter/analysis/hide/1	true
Jess Yurchich/splitter/analysis/hide/2	false
Jess Yurchich/splitter/analysis/hide/3	true
Jess Yurchich/splitter/diary/hide	true
Jess Yurchich/splitter/diary/hide/0	false
Jess Yurchich/splitter/diary/hide/1	false
Jess Yurchich/splitter/diary/hide/2	true
Jess Yurchich/splitter/train/hide	true
Jess Yurchich/splitter/train/hide/0	false
Jess Yurchich/splitter/train/hide/1	false
Jess Yurchich/splitter/train/hide/2	false
Jess Yurchich/splitter/train/hide/3	false
Jess Yurchich/unit	Imperial
Jess Yurchich/versionused	3032
Jim Mott/LTSdays	42
Jim Mott/PMshowSBtoday	0
Jim Mott/STSdays	7
Jim Mott/bavigator/headingwidths	0|43|59|98|
Jim Mott/blank/analysis	true
Jim Mott/blank/diary	false
Jim Mott/blank/home	false
Jim Mott/blank/train	false
Jim Mott/dv/url	
Jim Mott/gc/url	http://race.goldencheetah.org
Jim Mott/ltmwindow/autofilters	Workout Code|Sport
Jim Mott/ltmwindow/lastDateRange	{00000000-0000-0000-0000-000000000005}
Jim Mott/mainwindow/splitterSizes	
Jim Mott/mainwindow/splitterSizes/2	
Jim Mott/navigator/groupby	-1
Jim Mott/navigator/headings	*|Workout Code|TSS|Date|
Jim Mott/navigator/sortby	6
Jim Mott/navigator/sortbyorder	0
Jim Mott/nickname	Road Bike
Jim Mott/safeexit	false
Jim Mott/splitter/LTM/hide	true
Jim Mott/splitter/LTM/hide/0	false
Jim Mott/splitter/LTM/hide/1	false
Jim Mott/splitter/LTM/hide/2	true
Jim Mott/splitter/LTM/hide/3	true
Jim Mott/splitter/LTM/hide/4	false
Jim Mott/splitter/LTM/hide/5	true
Jim Mott/splitter/LTM/sizes	
Jim Mott/splitter/analysis/hide	true
Jim Mott/splitter/analysis/hide/0	false
Jim Mott/splitter/analysis/hide/1	true
Jim Mott/splitter/analysis/hide/2	false
Jim Mott/splitter/analysis/hide/3	true
Jim Mott/splitter/diary/hide	true
Jim Mott/splitter/diary/hide/0	false
Jim Mott/splitter/diary/hide/1	false
Jim Mott/splitter/diary/hide/2	true
Jim Mott/splitter/train/hide	true
Jim Mott/splitter/train/hide/0	false
Jim Mott/splitter/train/hide/1	false
Jim Mott/splitter/train/hide/2	false
Jim Mott/splitter/train/hide/3	false
Jim Mott/tp/type	0
Jim Mott/tp/url	http://www.trainingpeaks.com
Jim Mott/tw/url	http://www.twitter.com
Jim Mott/unit	Imperial
Jim Mott/versionused	3100
Jim Mott/webcal_url	
Jim Mott/wi/url	http://wbsapi.withings.net/
Jim Mott/zeo/url	http://app-pro.myzeo.com:8080/
Jim/LTSdays	42
Jim/PMshowSBtoday	0
Jim/STSdays	7
Jim/bavigator/headingwidths	0|49|87|161|
Jim/blank/analysis	false
Jim/blank/diary	false
Jim/blank/home	false
Jim/blank/train	false
Jim/dv/url	
Jim/gc/url	http://race.goldencheetah.org
Jim/ltmwindow/autofilters	Workout Code|Sport
Jim/ltmwindow/lastDateRange	{00000000-0000-0000-0000-000000000004}
Jim/mainwindow/splitterSizes	
Jim/mainwindow/splitterSizes/2	
Jim/navigator/groupby	-1
Jim/navigator/headings	*|Workout Code|TSS|Date|
Jim/navigator/sortby	2
Jim/navigator/sortbyorder	0
Jim/nickname	Triathlon Bike
Jim/safeexit	false
Jim/splitter/LTM/hide	true
Jim/splitter/LTM/hide/0	false
Jim/splitter/LTM/hide/1	false
Jim/splitter/LTM/hide/2	true
Jim/splitter/LTM/hide/3	true
Jim/splitter/LTM/sizes	
Jim/splitter/analysis/hide	true
Jim/splitter/analysis/hide/0	false
Jim/splitter/analysis/hide/1	true
Jim/splitter/analysis/hide/2	false
Jim/splitter/analysis/hide/3	true
Jim/splitter/analysis/sizes	
Jim/splitter/diary/hide	true
Jim/splitter/diary/hide/0	false
Jim/splitter/diary/hide/1	false
Jim/splitter/diary/hide/2	true
Jim/splitter/train/hide	true
Jim/splitter/train/hide/0	false
Jim/splitter/train/hide/1	false
Jim/splitter/train/hide/2	false
Jim/splitter/train/hide/3	false
Jim/tp/type	0
Jim/tp/url	http://www.trainingpeaks.com
Jim/tw/url	http://www.twitter.com
Jim/unit	Imperial
Jim/versionused	3100
Jim/webcal_url	
Jim/wi/url	http://wbsapi.withings.net/
Jim/zeo/url	http://app-pro.myzeo.com:8080/
LTS	LTS
LTSname	Long Term Stress
SB	SB
SBname	Stress Balance
STS	STS
STSname	Short Term Stress
antialias	false
chrome	Mac
crankLength	172.5
dataprocess/fixgaps/stop	1
dataprocess/fixgaps/tolerance	1
dataprocess/fixhrspikes/max	220
dataprocess/fixspikes/max	1500
dataprocess/fixspikes/variance	1000
dataprocess/torqueadjust/adjustment	0 nm
devices	0
dp/Adjust Torque Values/apply	Manual
dp/Fix GPS errors/apply	Manual
dp/Fix Gaps in Recording/apply	Manual
dp/Fix HR Spikes/apply	Manual
dp/Fix Power Spikes/apply	Manual
elevationHysteresis	3.
font/calendar	MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0
font/calendarsize	12
font/chartlabels	MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0
font/chartlabelssize	12
font/chartmarkers	MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0
font/chartmarkerssize	12
font/default	MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0
font/defaultsize	12
font/popup	10
font/titles	MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0
font/titlessize	12
garminHWMark	25
garminSmartRecord	2
homedirectory	C:/Users/Jim/AppData/Local/GoldenCheetah
lang	en
linewidth	2
mainwindow/geometry	ÙÐË
mainwindow/lastImportPath	C:/Users/Jim/Documents/CycleOps/Mott, Jim .power/data
mainwindow/lastOpened	Jim
mainwindow/state	
rideBG	false
rideHead	true
rideScroll	true
shadezones	true
show/tabbar	false
train/multi	false
unit	Imperial
wbal/formula	diff
wheelsize	2100
workoutDir	C:\Users\Jim\Documents\CycleOps\Mott, Jim .power\data

**Comment by liversedge** [comment]
Does it do the same after a restart ?
Interested in the ride 2015_04_15_18_08_42.fit - did you just import it ?
What happens if you remove it from the athlete directory ?

**Comment by jwmott** [comment]
Yes it still happens after a restart.
I did just import that ride, but the crash occurs when I click Ride for all workouts I've ever added (I've never been able to see the Ride screen without a crash).
The behavior is the same when I remove it from the directory (I assume this means delete the ride).

Trying to think of other useful information for you...
All my rides come form a CycleOps Joule and are .fit files. 
I import them all manually (Import from file...)
All the other tabs work fine when I click them (Summary, Details, CP, Map, etc)

Let me know if I can provide anything else.

**Comment by liversedge** [comment]
Can you send me one of your rides ?
liversedge gmail com.

Thanks

**Comment by liversedge** [comment]
no data received 
unable to recreate
assume not interested in resolution so closing.
