### ISSUE TITLE
Intensity Factor not correctly displayed

### ISSUE THREAD

**Issue by jerry389** [GoldenCheetah/GoldenCheetah#1364]
The intensity factor from both a train window and power tap joule are reading "1". The w/kg is not showing as N/A.

**Comment by jerry389** [comment]
I need to clarify. The IF metric displays properly on the graphed data but shows up as a 1 on the Metric summary screen. Same issue with W/kg.

**Comment by liversedge** [comment]
What version are you using Jerry - this was fixed a long time ago.

**Comment by jerry389** [comment]
3.2 beta



—

**Comment by liversedge** [comment]
Strange. Can you post some example screenshots ?

**Comment by jerry389** [comment]
Mark,

It appears that IF, RI, WKG and EF are static and set to 1. Is there something is settings I missed?




![screen shot 2015-04-29 at 7 09 16 am](https://cloud.githubusercontent.com/assets/12145647/7389982/4e7af404-ee41-11e4-9653-ad390a56ee1b.png)
![screen shot 2015-04-29 at 7 15 59 am](https://cloud.githubusercontent.com/assets/12145647/7389985/52e2fe2e-ee41-11e4-845e-c60d6e8ce8ef.png)

**Comment by liversedge** [comment]
is this still a problem?
I cannot recreate.
