### ISSUE TITLE
Critical Speed

### ISSUE THREAD

**Issue by matthieudelcourt** [GoldenCheetah/GoldenCheetah#1365]
The Critical Speed graph seems a bit off as there is some extrapolation of the speed (less than 5min) that is way too high when it should really plateau. For example, my critical speed for 10min is around 50km/h and at 1min it's 110km/h and at 15sec it's 319km/h. This makes the y-axis go a lot higher than it really should and it makes it hard to really see what's going on for the realistic time intervals (>5min).

**Comment by liversedge** [comment]
its intended for running.
