### ISSUE TITLE
Importing tcx file from Polar Flow strange Speed results

### ISSUE THREAD

**Issue by knuky** [GoldenCheetah/GoldenCheetah#1368]
Im getting a strange saw tooth result when graphing the speed data coming from Polar Flow. 

Im wondering if its a bug on the Golden Cheetah import or the Polar Flow export. I have attached an image of part of the graph and have a the tcx file.
![speed](https://cloud.githubusercontent.com/assets/12403836/7579085/6ae4fd7c-f89d-11e4-8306-7093fcc5c69f.jpeg)

**Comment by liversedge** [comment]
the source data is the problem.
