### ISSUE TITLE
GC unable to read Sigma Log Files (SLF) from newer versions of the Sigma Data Center

### ISSUE THREAD

**Issue by cmichelen** [GoldenCheetah/GoldenCheetah#1369]
It seems that GC can only read files created by versions of Sigma Data Center earlier than 2.1 (Current version is 4.0). Unfortunatey newer computers won't work with the older versions of the Data Center. GC cannot read the CSV from the Sigma Data Center either.

**Comment by eugenpp** [comment]
Sigma Data Center 4.0 exports SLF file with different format than 2.x or 3.x.

**Comment by oTTo81** [comment]
Any news on this matter maybe. 

BR,oTTo

Love GC. ;)

**Comment by oTTo81** [comment]
Guess not. :(
