### ISSUE TITLE
Elevation display, and therefore sort, in Activities pane is alpha

### ISSUE THREAD

**Issue by batsonjay** [GoldenCheetah/GoldenCheetah#1375]
To reproduce: On the Activities tab, in the Activities (list) pane, click column to sort by Elevation.

Note that resulting activity list is sorted by alpha / string value - not numeric value. E.g. you might see a list in this order: 10, 100, 20, 200, etc.

Values should be treated as a numeric (vs. string), and sorted thusly.

**Comment by liversedge** [comment]
This is fixed in 3.2 :)
