### ISSUE TITLE
PowerTap (Old) Grey Counsel - Power approx 30 watts too high

### ISSUE THREAD

**Issue by geoleo55** [GoldenCheetah/GoldenCheetah#1378]
When importing from an older Grey Counsel PowerTap computer, all the data is correct, except the power data, both individual power numbers and the average power for the session. For example, AVG power reported in PowerAgent for one ride is 198, however, the average power reported by GC is 228. When the same file is ported into Strava, the power related errors remain; however, they are corrected when ported into Training Peaks. Odd. (Thanks for the boost of confidence, however ;-) )

**Comment by liversedge** [comment]
likely gaps in recording or smart recording.
