### ISSUE TITLE
Auto CP

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#1381]
A tool to set CP config based upon model estimates.
Maybe check after import or model refreshes too ?

**Comment by antoniusriha** [comment]
I like this idea. I think however, that date range of the the model feed data must be configurable. Currently it's set to the rolling bests of the last 12 weeks. This seems to be a rather long period in my opinion.
Another thing I'd like to suggest, is to add semi-automatic power zones management: The user gets to see a list of all model estimates and can then choose which to include in the config.
