### ISSUE TITLE
Air density calculator: add ability to use relative humidity

### ISSUE THREAD

**Issue by dhague** [GoldenCheetah/GoldenCheetah#1383]
RH can be used in placeof dewpoint, and a RH meter can be had very cheaply. UI would allow either/or selection of dewpoint/RH.

dhague to implement

**Comment by dhague** [comment]
From http://climate.envsci.rutgers.edu/pdf/LawrenceRHdewpointBAMS.pdf:
dewpoint = temp - (((100-RH)/5) * ((temp/300)^2)) - 0.00135*((RH-84)^2) + 0.35

the maximum error in dewpoint using this equation over the whole range of 50% <= RH <= 100% and 0° < t < 30°C is 0.3°C

Given that air density is relatively insensitive to RH, this is more than adequate for our needs.

**Comment by amtriathlon** [comment]
From Robert Chung at: https://groups.google.com/d/msg/golden-cheetah-users/m3IvodfZWZA/AFNuGX-JBgAJ
> As an aside, the rho calculator in GC currently presumes "station pressure" so there is no altitude adjustment. We should add a checkbox if the baro pressure is for "official" or "sea level" baseline, or if it's already altitude adjusted for a particular location, and add the altitude adjustment if needed.

For the adjustment we could use `AirPressure(altitude)/AirPressure(0)` from:
https://github.com/GoldenCheetah/GoldenCheetah/blob/67384872d04729c03ee3047518d7322491862d67/src/Train/PhysicsUtility.h#L34
