### ISSUE TITLE
Air density calculator: read Average Temp from current activity

### ISSUE THREAD

**Issue by dhague** [GoldenCheetah/GoldenCheetah#1386]
dhague to implement

**Comment by liversedge** [comment]
putting into v4 queue as we've closed 3.2 for release.

**Comment by liversedge** [comment]
Hi Darren,

How goes it ? should I put into v4.0 queue for after Christmas ?

Cheers
Mark

**Comment by dhague** [comment]
Please do - my spare cycles right now are being taken up with Elite Dangerous & cyclocross, but the winter GC coding season is imminent :)

**Comment by liversedge** [comment]
Done :)

**Comment by amtriathlon** [comment]
I cannot see a use case for this, but since Rho calculator is likely used mostly for AeroLab, to use the Average Temp for current ride would be useful.
