### ISSUE TITLE
Error - local type 15 without previous definition

### ISSUE THREAD

**Issue by perry** [GoldenCheetah/GoldenCheetah#1389]
![](http://i.imgur.com/nVwxodq.png)
![](http://i.imgur.com/aJQr0ZF.png)

The files were processed on Strava fine. I tested in both the stable and dev releases.

Files in question: 
- https://www.dropbox.com/s/m36zimsaostdbob/2015-05-23-08-08-06.fit?dl=0
- https://www.dropbox.com/s/r4ryvbuzj10p9kw/2015-05-24-08-04-40.fit?dl=0
- https://www.dropbox.com/s/65gvadsjm11q2dd/2015-05-25-08-04-54.fit?dl=0

**Comment by Joern-R** [comment]
I checked your files with the fit test app - which report same error on the files like GC / and some more on corrupt data.

In Strava 2 files can be uploaded - but report "partially corrupted file, could be truncated" as an error. The 3rd file reports ""bad time data" and is not uploaded at all.

So something is wrong in your .FIT files.

Therefore I close the message.
