### ISSUE TITLE
Train Mode: ANT+ should only use configured devices, if they are specified

### ISSUE THREAD

**Issue by dhague** [GoldenCheetah/GoldenCheetah#1391]
I have an ANT+ profile set up to use a HR strap and a GSC-10 on my turbo. When I start Train Mode, 50% of the time GC will select the GSC-10 on the bike instead of the one on the turbo, even though the ANT+ profile does not mention the one on the bike.

**Comment by liversedge** [comment]
This should have been fixed in d43ee7b6a464f90681a34370235c8ba00a100929 ?

**Comment by dhague** [comment]
Compiling the latest source now to check - thanks!

**Comment by dhague** [comment]
Checked with a new build - it is indeed working fine now.

**Comment by liversedge** [comment]
thanks :)
