### ISSUE TITLE
Add support for ANT FE-C profile (a.k.a. fitness equiment controls / trainer resistance)

### ISSUE THREAD

**Issue by dresco** [GoldenCheetah/GoldenCheetah#1393]

**Comment by stschake** [comment]
I've started work on this on the ant-fec branch of my fork. I upgraded my Tacx Vortex to FE-C, so I have half of the devices supporting this standard available for testing ;)

The FE-C profile has lots of things they term "simulation mode" where the fitness equipment tries to estimate resistance from parameters like slope and wind resistance coefficients. I think that mode is suspect from a training standpoint so I will be focusing on implementing the power (W) setpoint mode.

**Comment by liversedge** [comment]
Cool.


The 'slope' mode in training view is essentially the same thing.

**Comment by vlcvboyer** [comment]
FYI I've just worked on ANT FE-C protocol
I used stschake contrib as basis and started implementation of additional features such as simulation mode (slope & wind), etc. 
(WIP is located on my github: https://github.com/vlcvboyer/GoldenCheetah/tree/ant-fec)

**Comment by liversedge** [comment]
This was added in v3.3
