### ISSUE TITLE
Git master segfaults on Fedora 22

### ISSUE THREAD

**Issue by prokoudine** [GoldenCheetah/GoldenCheetah#1395]
Case 1. 

How to reproduce:

1. Build on Fedora 22 (32bit).
2. Start, create new athlete.
3. Close.
4. Start again.
5. Et voila! :)

What happens as per GDB:

#0  0xffffffff in QString::operator=(QString const&) () at /lib/libQtCore.so.4
#1  0x086717c5 in RideDBparse(RideDBContext*) (jc=jc@entry=0x8e2d3a8) at RideDB.tab.c:743
#2  0x08675b13 in RideCache::load() (this=0x8dc10d0) at RideDB.y:282
#3  0x0848b601 in RideCache::RideCache(Context*) (this=0x8dc10d0, context=0x8d12c10) at RideCache.cpp:72
#4  0x08169b8d in Athlete::Athlete(Context*, QDir const&) (this=0x8d1eea0, context=0x8d12c10, homeDir=...) at Athlete.cpp:166
#5  0x08384ec9 in MainWindow::MainWindow(QDir const&) (this=0x8d12b58, home=...) at MainWindow.cpp:119
#6  0x0808b151 in main(int, char**) (argc=1, argv=0xbffff174) at main.cpp:293

Case 2.

How to reproduce:

1. Remove all configs.
2. Create a new athlete, open.
3. Import a GPX file (which worked just fine in v3.1).
3. Boom :)

What happens as per GDB:

#0  0xffffffff in QString::operator=(QString const&) () at /lib/libQtCore.so.4
#1  0x08668d7a in JsonRideFileparse(JsonContext*) (jc=jc@entry=0x8edf3d8) at JsonRideFile.tab.c:1039
#2  0x0866a831 in JsonFileReader::openRideFile(QFile&, QStringList&, QList<RideFile*>*) const (this=0x8b8c490, file=..., errors=...)
    at JsonRideFile.y:360
#3  0x084b8cff in RideFileFactory::openRideFile(Context*, QFile&, QStringList&, QList<RideFile*>*) const (this=0x8b71bf8, context=context@entry=0x8d7aef0, file=..., errors=..., rideList=rideList@entry=0x0) at RideFile.cpp:558
#4  0x084ed407 in RideItem::ride(bool) (this=this@entry=0x941a130, open=open@entry=true) at RideItem.cpp:143
#5  0x084ecc44 in RideItem::refresh() (this=0x941a130) at RideItem.cpp:501
#6  0x0848731d in RideCache::addRide(QString, bool, bool) (this=0x8e611b8, name=..., dosignal=true, useTempActivities=true)
    at RideCache.cpp:191
#7  0x081632ef in Athlete::addRide(QString, bool, bool) (this=0x8e245f0, name=..., dosignal=dosignal@entry=true, useTempActivities=useTempActivities@entry=true) at Athlete.cpp:241
#8  0x084dc799 in RideImportWizard::abortClicked() (this=0x8ee98c0) at RideImportWizard.cpp:973
#9  0xffffffff in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () at /lib/libQtCore.so.4
#10 0xffffffff in QAbstractButton::clicked(bool) () at /lib/libQtGui.so.4
#11 0xffffffff in QAbstractButtonPrivate::emitClicked() () at /lib/libQtGui.so.4
#12 0xffffffff in QAbstractButtonPrivate::click() () at /lib/libQtGui.so.4
#13 0xffffffff in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /lib/libQtGui.so.4
#14 0xffffffff in QWidget::event(QEvent*) () at /lib/libQtGui.so.4
#15 0xffffffff in QAbstractButton::event(QEvent*) () at /lib/libQtGui.so.4
#16 0xffffffff in QPushButton::event(QEvent*) () at /lib/libQtGui.so.4
#17 0xffffffff in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/libQtGui.so.4
#18 0xffffffff in QApplication::notify(QObject*, QEvent*) () at /lib/libQtGui.so.4
#19 0xffffffff in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /lib/libQtCore.so.4
#20 0xffffffff in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /lib/libQtGui.so.4
#21 0xffffffff in QETWidget::translateMouseEvent(_XEvent const*) () at /lib/libQtGui.so.4
#22 0xffffffff in QApplication::x11ProcessEvent(_XEvent*) () at /lib/libQtGui.so.4
#23 0xffffffff in x11EventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib/libQtGui.so.4
#24 0xffffffff in g_main_context_dispatch () at /lib/libglib-2.0.so.0
#25 0xffffffff in g_main_context_iterate.isra () at /lib/libglib-2.0.so.0
#26 0xffffffff in g_main_context_iteration () at /lib/libglib-2.0.so.0
#27 0xffffffff in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/libQtCore.so.4
#28 0xffffffff in QGuiEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/libQtGui.so.4
#29 0xffffffff in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/libQtCore.so.4
#30 0xffffffff in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/libQtCore.so.4
#31 0xffffffff in QCoreApplication::exec() () at /lib/libQtCore.so.4
#32 0xffffffff in QApplication::exec() () at /lib/libQtGui.so.4
#33 0x0808ac12 in main(int, char**) (argc=1, argv=0xbffff174) at main.cpp:338

**Comment by liversedge** [comment]
Can you send me the gpx file please?
liversedge gmail com

**Comment by liversedge** [comment]
also, please do a make clean; make as the yacc parser doesn't get remade (its a bug in qmake) when it's dependencies change.

if you want to do this quicker; touch *.y; make is faster !

**Comment by liversedge** [comment]
also make sure you are building using a version of lex/yacc or flex/bison that support reentrant parsers.
I think this is a build issue and have marked as such until I can see otherwise :)

**Comment by prokoudine** [comment]
I think I got it to work by carefully following build instructions instead of trying to use byacc like a loony that I am :) Closing the report.

**Comment by liversedge** [comment]
thanks.
