### ISSUE TITLE
Calculation of climbing speed (m height/h)

### ISSUE THREAD

**Issue by Peter2m** [GoldenCheetah/GoldenCheetah#1398]
As i see it, the climbing speed is calculated at the moment on the basis of total riding time....i would find it useful if the climbing speed is calculated on the basis of the relevant uphill riding time.

**Comment by stigbd** [comment]
Just curious: Why did you close this issue, @Peter2m ? Do you no longer think it is an issue, or is the issue fixed? (My reason for asking is that I too would think uphill riding time would be the correct approach.)

**Comment by liversedge** [comment]
For info; these metrics are computed against a ride and against an interval.
In 3.2 we automatically create intervals for climbing so this is a duplicate of that feature request.
So its pretty straight forward to get a summary of time climbing.

![screen shot 2015-06-11 at 10 45 53](https://cloud.githubusercontent.com/assets/142876/8104240/1678215a-1027-11e5-8a16-0d3e1c4edbd6.png)

**Comment by Peter2m** [comment]
I was not aware, that i closed the issue..i am not good with the
computer.i also think, that the total ride time leads to a pretty sensless
value, whereas the climbing time would make sense.

Regards

 

-----Ursprüngliche Nachricht-----
Von: Stig B. Dørmænen [mailto:notifications@github.com] 
Gesendet: Donnerstag, 11. Juni 2015 11:20
An: GoldenCheetah/GoldenCheetah
Cc: Peter2m
Betreff: Re: [GoldenCheetah] Calculation of climbing speed (m height/h)
(#1398)

 

Just curious: Why did you close this issue, @Peter2m
<https://github.com/Peter2m>  ? Do you no longer think it is an issue, or is
the issue fixed? (My reason for asking is that I too would think uphill
riding time would be the correct approach.)


Reply to this email directly or view
<https://github.com/GoldenCheetah/GoldenCheetah/issues/1398#issuecomment-111
055987>  it on GitHub.
<https://github.com/notifications/beacon/ALNnNdcKKsPBhefRMUwVOb6Hioc9u2j2ks5
oSUpLgaJpZM4E_W_f.gif>

**Comment by Peter2m** [comment]
-          I believe, that computing it against the total ride time does not
make much sense, whereas the climing time would lead to a usefule
value..this was actually my point.

-          When can we expect 3.2.i am looking forward to it.

 

Thank you for yr great work Markbest regards

Peter

 

-----Ursprüngliche Nachricht-----
Von: Mark Liversedge [mailto:notifications@github.com] 
Gesendet: Donnerstag, 11. Juni 2015 11:47
An: GoldenCheetah/GoldenCheetah
Cc: Peter2m
Betreff: Re: [GoldenCheetah] Calculation of climbing speed (m height/h)
(#1398)

 

For info; these metrics are computed against a ride and against an interval.
In 3.2 we automatically create intervals for climbing so this is a duplicate
of that feature request.
So its pretty straight forward to get a summary of time climbing.

 
<https://cloud.githubusercontent.com/assets/142876/8104240/1678215a-1027-11e
5-8a16-0d3e1c4edbd6.png> screen shot 2015-06-11 at 10 45 53


Reply to this email directly or view
<https://github.com/GoldenCheetah/GoldenCheetah/issues/1398#issuecomment-111
069580>  it on GitHub.
<https://github.com/notifications/beacon/ALNnNRfVHXAHB-1cucIpdCG65d163-pkks5
oSVB2gaJpZM4E_W_f.gif>

**Comment by Peter2m** [comment]
-          I have now downloaded 3.2..the intervalls for climbing are not
created as shown below.

-          Do not unterstand the values in the slope chart (obviously to
small to be % or degree values).   

 

Thanks for helping me.

 

-----Ursprüngliche Nachricht-----
Von: Mark Liversedge [mailto:notifications@github.com] 
Gesendet: Donnerstag, 11. Juni 2015 11:47
An: GoldenCheetah/GoldenCheetah
Cc: Peter2m
Betreff: Re: [GoldenCheetah] Calculation of climbing speed (m height/h)
(#1398)

 

For info; these metrics are computed against a ride and against an interval.
In 3.2 we automatically create intervals for climbing so this is a duplicate
of that feature request.
So its pretty straight forward to get a summary of time climbing.

 
<https://cloud.githubusercontent.com/assets/142876/8104240/1678215a-1027-11e
5-8a16-0d3e1c4edbd6.png> screen shot 2015-06-11 at 10 45 53


Reply to this email directly or view
<https://github.com/GoldenCheetah/GoldenCheetah/issues/1398#issuecomment-111
069580>  it on GitHub.
<https://github.com/notifications/beacon/ALNnNRfVHXAHB-1cucIpdCG65d163-pkks5
oSVB2gaJpZM4E_W_f.gif>
