### ISSUE TITLE
Feature Request:  Ability to edit athlete profile in golden cheetah

### ISSUE THREAD

**Issue by gfisher1970** [GoldenCheetah/GoldenCheetah#1402]
Seems like there isn't a way to edit an athlete profile (e.g. if power zones change) in the application.  Can this be added at some point?  If it exists can you pls send instructions to update?

Gabby

**Comment by liversedge** [comment]
Tool > options on Linux/Windows GoldenCheetah > preferences on OS X.
Please use the forums for help thanks.
https://groups.google.com/forum/#!forum/golden-cheetah-users
