### ISSUE TITLE
Updating translations

### ISSUE THREAD

**Issue by prokoudine** [GoldenCheetah/GoldenCheetah#1403]
Hi,

I'm in the process of updating the heavily deteriorated Russian translation of GoldenCheetah. What's the correct way to update TS files?

The way I always did it with Qt-based software is to generate a new top-level PRO file by running 'qmake -project', then running lupdate against that newly created file. However, I'm not entirely sure this is the right way to do that with GC where multiple PRO files exist.

For instance, I end up with descriptions of heart rate zones (Active Recovery etc.) never showing up as translated in UI even after running the whole 'make clean && lrelease && qmake -recursive && make' routine.

Please advise.

**Comment by amtriathlon** [comment]
Hi, you can run lupdate on the existing src.pro to update translatios/gc_ru.ts, modify it and make, something like this:
`cd src
lupdate src.pro -ts translations/gc_ru.ts
***change translations/gc_ru.ts using linguist (or editor)***
make`
Hope it helps!
