### ISSUE TITLE
Norwegian translation

### ISSUE THREAD

**Issue by stigbd** [GoldenCheetah/GoldenCheetah#1406]
This is a proposed feature request for a Norwegian Translation.

I am willing to help realize this, but I have no idea if anybody else wants to use it and/or contribute. Please comment if you find a Norwegian translation useful to you.

(Unfortunately I have no numbers on how many Norwegians there are using Golden Cheetah.)

**Comment by liversedge** [comment]
Thank you !

All the Norwegians I know speak about 5 languages each and always put us Brits to shame (!). You are welcome to look at this, be warned there are a lot of texts to translate.
