### ISSUE TITLE
Non-translatable messages in UI

### ISSUE THREAD

**Issue by prokoudine** [GoldenCheetah/GoldenCheetah#1410]
src/WPrime.cpp, lines 71 through 74:

    { 0, 25, "W1", "Recovered" },
    { 25, 50, "W2", "Moderate Fatigue" },
    { 50, 75, "W3", "Heavy Fatigue" },
    { 75, 100, "W4", "Severe Fatigue" }

**Comment by liversedge** [comment]
Try something like:

diff --git a/src/WPrime.cpp b/src/WPrime.cpp
index 86dfefc..70b0b13 100644
--- a/src/WPrime.cpp
+++ b/src/WPrime.cpp
@@ -68,10 +68,10 @@ static struct WPRIMEZONES {
 
 } wbal_zones[] = {
 
-    { 0, 25, "W1", "Recovered" },
-    { 25, 50, "W2", "Moderate Fatigue" },
-    { 50, 75, "W3", "Heavy Fatigue" },
-    { 75, 100, "W4", "Severe Fatigue" }
+    { 0, 25, "W1", QT_TR_NOOP("Recovered") },
+    { 25, 50, "W2", QT_TR_NOOP("Moderate Fatigue") },
+    { 50, 75, "W3", QT_TR_NOOP("Heavy Fatigue") },
+    { 75, 100, "W4", QT_TR_NOOP("Severe Fatigue") }
 
 };

**Comment by prokoudine** [comment]
lupdate says:

/home/alex/soft/sports/GoldenCheetah/src/WPrime.cpp:71: tr() cannot be called without context
/home/alex/soft/sports/GoldenCheetah/src/WPrime.cpp:72: tr() cannot be called without context
/home/alex/soft/sports/GoldenCheetah/src/WPrime.cpp:73: tr() cannot be called without context
/home/alex/soft/sports/GoldenCheetah/src/WPrime.cpp:74: tr() cannot be called without context
/home/alex/soft/sports/GoldenCheetah/src/WPrime.cpp:566: Class 'WPrime' lacks Q_OBJECT macro

**Comment by amtriathlon** [comment]
This happens because WPrime is not a Q_OBJECT but you can provide translation context without changing that, just add Q_DECLARE_TR_FUNCTIONS(WPrime) to class definition in WPrime.h, try this:
```javascript
class WPrime {
    Q_DECLARE_TR_FUNCTIONS(WPrime)

    public:
```

**Comment by prokoudine** [comment]
Nope, didn't work here. I still get " tr() cannot be called without context".

**Comment by liversedge** [comment]
```C++
diff --git a/src/WPrime.cpp b/src/WPrime.cpp
index 86dfefc..f1f855f 100644
--- a/src/WPrime.cpp
+++ b/src/WPrime.cpp
@@ -64,19 +64,20 @@ const int WprimeMatchMinJoules = 100;
 static struct WPRIMEZONES {
 
     int lo, hi; 
-    QString name, desc;
+    QString name;
+    const char *desc;
 
 } wbal_zones[] = { 
 
-    { 0, 25, "W1", "Recovered" },
-    { 25, 50, "W2", "Moderate Fatigue" },
-    { 50, 75, "W3", "Heavy Fatigue" },
-    { 75, 100, "W4", "Severe Fatigue" }
+    { 0, 25, "W1", QT_TRANSLATE_NOOP("wbalzone", "Recovered") },
+    { 25, 50, "W2", QT_TRANSLATE_NOOP("wbalzone", "Moderate Fatigue") },
+    { 50, 75, "W3", QT_TRANSLATE_NOOP("wbalzone", "Heavy Fatigue") },
+    { 75, 100, "W4", QT_TRANSLATE_NOOP("wbalzone", "Severe Fatigue") }
 
 };
 
 QString WPrime::zoneName(int i) { return wbal_zones[i].name; }
-QString WPrime::zoneDesc(int i) { return wbal_zones[i].desc; }
+QString WPrime::zoneDesc(int i) { return qApp->translate("wbalzone", wbal_zones[i].desc); }
 
 
 WPrime::WPrime()
@@ -592,7 +593,7 @@ WPrime::summarize(int WPRIME, QVector<double> wtiz, QColor color)
 
         // basics
         summary += QString("<td align=\"center\">%1</td>").arg(wbal_zones[zone].name);
-        summary += QString("<td align=\"center\">%1</td>").arg(wbal_zones[zone].desc);
+        summary += QString("<td align=\"center\">%1</td>").arg(qApp->translate("wbalzone", wbal_zones[zone].desc));
         summary += QString("<td align=\"center\">%1</td>").arg(WPRIME - (WPRIME / 100.0f * wbal_zones[zone].lo), 0, 'f', 0); 
 
         if (zone == 3)
diff --git a/src/WPrime.h b/src/WPrime.h
index 3b1daea..26d0239 100644
--- a/src/WPrime.h
+++ b/src/WPrime.h
@@ -38,6 +38,7 @@ struct Match {
 
 class WPrime {
 
+    Q_DECLARE_TR_FUNCTIONS(WPrime)
 
     public: 
 

```

**Comment by prokoudine** [comment]
That fixed it, thanks!

Additionally, I guess lines 566 and 573 through 578 in WPrime.cpp might need a similar fix: messages do end up in the TS file, but these messages show up in English anyway.
