### ISSUE TITLE
SWOLF support

### ISSUE THREAD

**Issue by prokoudine** [GoldenCheetah/GoldenCheetah#1414]
Now that GoldenCheetah is a multi-sport software with support for swimming metrics, it might be a good idea to add SWOLF which is a "traditional" metric to estimate technique efficiency in pool swims.

The math is simply:

amount of both left/right hand strokes per 50m + time in seconds for 50m = SWOLF score

The strokes data is usually present in FIT files and suchlike.

Here's a nice overview:

http://marathonswimmers.org/blog/2012/04/swolf-swim-efficiency/

And here's what e.g. SportTracks does with it:

http://sporttracks.mobi/blog/what-is-swolf-swimming-metrics-explained

**Comment by amtriathlon** [comment]
SWolf metric added in https://github.com/GoldenCheetah/GoldenCheetah/commit/bed89537448527c93831a30dc86099b6d738f946, it is also available as User Data in Ride chart from the cloud.
