### ISSUE TITLE
Pace chart support on the Ride/Activity tab

### ISSUE THREAD

**Issue by prokoudine** [GoldenCheetah/GoldenCheetah#1418]
Currently you can view speed on the Ride/Activity tab, but there is no pace for either running or swimming.

For running, I would suggest min:sec/km and min:sec/mile depending on user preferences, and for swimming — min:sec/100m and min:sec/100yrd respectively.

E.g. Strava additionally calculates gradient-corrected pace, that is, the pace one would run at if it wasn't for slopes. Not sure it's all that useful, but if your fancies take you there, then why the hell not? :)

**Comment by prokoudine** [comment]
On a second thought, general availability of the pace metric would be nice. I can see it used in e.g. Y axis on the Scatter tab. Well, I'm sure you know best what to do :)

**Comment by amtriathlon** [comment]
In v3.2 there are already gradient&variability-corrected pace for running (xPace) and variability-corrected pace for swimming (xPace Swim) as metrics, in v4 they could be added as derived series in a similar way to NP.
We may also to add Pace/Swim Pace, but I'm not sure if this is would be the best way.

**Comment by liversedge** [comment]
I think the axis titles for "speed" need to change to "pace" and pace units, when charting runs and swims in e.g. "ride" plot, histogram, scatter etc

**Comment by amtriathlon** [comment]
Agree, that's a better option, IMHO.

**Comment by prokoudine** [comment]
The thing is, there is no xPace or XPaceSwim option for either X or Y axis in the Scatter chart settings dialog.

**Comment by amtriathlon** [comment]
That's right, in the same way that there is no NP/xPower nor any other
average/"average like" metric available in the Scatter chart.

2015-06-27 19:35 GMT-03:00 Alexandre Prokoudine <notifications@github.com>:

> The thing is, there is no xPace or XPaceSwim option for either X or Y axis
> in the Scatter chart settings dialog.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoldenCheetah/GoldenCheetah/issues/1418#issuecomment-116163705>
> .
>



-- 
Alejandro.

**Comment by liversedge** [comment]
One of the things I would like to do is update the scatter chart to plot metrics for rides and intervals in the same way as we plot ride data. I can't find it now but pretty sure there is a feature request for this in the v4 queue.

**Comment by amtriathlon** [comment]
I think it is #1308
<https://github.com/GoldenCheetah/GoldenCheetah/issues/1308>, it would be
very interesting to have the scatter plot enabled for Trends!

2015-06-28 13:17 GMT-03:00 Mark Liversedge <notifications@github.com>:

> One of the things I would like to do is update the scatter chart to plot
> metrics for rides and intervals in the same way as we plot ride data. I
> can't find it now but pretty sure there is a feature request for this in
> the v4 queue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoldenCheetah/GoldenCheetah/issues/1418#issuecomment-116295297>
> .
>



-- 
Alejandro.
