### ISSUE TITLE
General High-DPI support

### ISSUE THREAD

**Issue by AndyBryson** [GoldenCheetah/GoldenCheetah#1420]
![image](https://cloud.githubusercontent.com/assets/2845832/8341270/a5facece-1abb-11e5-861f-b4f003a73853.png)

GC looks very bad out of the box on my high-dpi monitor in Windows (not tested in other OS), and I was unable to correct it using user configurable settings (within the app).

A quick work around is to add `-platform windows:dpiawareness=0` to the shortcut. http://doc.qt.io/qt-5/highdpi.html

My monitor is 13" 3200*1800.

**Comment by liversedge** [comment]
yuck !

Serves you right for having such a nice monitor ;)

When you say "add -platform windows:dpiawareness=0 to the shortcut", you can do that as a user, did it make a difference ?

**Comment by AndyBryson** [comment]
Yeah, I changed the target in the shortcut to: `"C:\Program Files\Golden Cheetah\GoldenCheetah.exe" -platform windows:dpiawareness=0` and it looks great. The documentation about that setting says:
> Windows will pretend to the application that it is running on a standard display of 96 DPI of 1920x1080 and scale the application accordingly. It is intended to accommodate older applications designed for low DPI displays. Some artifacts may result from this type of scaling.

**Comment by liversedge** [comment]
Out of interest Andy what monitor GPU combo did you go for, am tempted to try this for myself, obviously so I can address issues such as these ;)

**Comment by AndyBryson** [comment]
I got the new [Dell XPS 13](http://www.dell.com/uk/p/xps-13-9343-laptop/pd) laptop.

It's very good, but HighDPI support is so bad on Linux desktop environments that I couldn't use it. It's not perfect on Windows either, but it is a lot better. A load of applications suffer the same sort of problem that I report here, with QT being the worst offender. I thought all of the issues would have been sorted by now, but I was wrong.

**Comment by nvercamm** [comment]
I've got the same issue on a Dell XPS 15, 4K resolution high DPI. Thanks to Andy's workaround the numbers are again readable.

**Comment by cleveruplink** [comment]
I haven't found these workarounds to work on Windows 10, am I missing something?

**Comment by liversedge** [comment]
You need to be using a QT5 build.

**Comment by liversedge** [comment]
dpiawareness now largely means removing fixed size dialogs.

**Comment by bdb** [comment]
Qt 5.6 has expanded support for HiDPI on all platforms: http://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/

**Comment by liversedge** [comment]
We will fix this in 3.5, closing this in preference for: #2386
