### ISSUE TITLE
Preferences in fullscreen in OSX confuses users

### ISSUE THREAD

**Issue by tacotuesday** [GoldenCheetah/GoldenCheetah#1427]
After maximizing to a full screen, a translucent bar shows up where the window resize controls should be. Program doesn't exit full screen with ESC. Additionally, the Preferences window opens full screen; after adjusting preferences and choosing "Save" or "Save and Quit", the window closes but leaves a black screen where the Preferences window had been open.
![goldencheetah-nominimize](https://cloud.githubusercontent.com/assets/1495452/8418953/6218880a-1e84-11e5-855a-80198ddcfeb6.png)

Additionally, the Preferences window opens full screen; after adjusting preferences and choosing "Save" or "Save and Quit", the window closes but leaves a black screen where the Preferences window had been open.
![screen shot 2015-06-29 at 17 24 09](https://cloud.githubusercontent.com/assets/1495452/8418954/6221c532-1e84-11e5-8257-8d34afb13bcd.png)

**Comment by liversedge** [comment]
fixed in 3.2.

**Comment by tacotuesday** [comment]
It is still in 3.2.

![screen shot 2015-06-29 at 17 58 38](https://cloud.githubusercontent.com/assets/1495452/8419557/b2aeff98-1e88-11e5-8216-c9bc2ec06a42.png)

**Comment by liversedge** [comment]
The fullscreen prefs "problem" needs to be addressed.
