### ISSUE TITLE
UPDATE GOLDENCHEETAH WEBSITE FOR V3.2

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#1431]
Need a new section 'Advice' to cover;

1. Estimating CP, Pmax and W'

**Comment by liversedge** [comment]
Add to the science section to include
- CV model
- GOVSS
- SwimScore

**Comment by amtriathlon** [comment]
We could also add some advice about how to set CV for running and swimming pace zones.

**Comment by liversedge** [comment]
~~From v3.2 the website update also means publishing default charts and layout xml files to www.goldencheetah.org/defaults/x.x/~~ Done over at goldencheetah.github.io
