### ISSUE TITLE
Edit interval distance

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#1432]
>This is specially valuable with swim sets that include kicking (or single arm) drills, which would typically have zero as distance for the interval.

I thought to add the option to specify distance in Edit Interval dialog to set speed at average value for the samples in the interval and to fix distance accordingly, or we could add a separate "Fix Interval Distance" action. Other ideas or comments are welcome!

**Comment by amtriathlon** [comment]
I implemented a version for the first option, it directly modify the RideFile without using the RideCommand interfase, seems to be working and updates are visible in RideSummary and Editor, but I'm not sure how it interacts with the RideCache.

**Comment by liversedge** [comment]
Fixed with c4c15ada67a3a28bea78b1c115077f6b667ad9b7
