### ISSUE TITLE
Allow switching between CT slope and erg mode during a workout

### ISSUE THREAD

**Issue by inuse** [GoldenCheetah/GoldenCheetah#146]
I'd like to be able to toggle the CT back and forth between slope and erg mode without having to quit the workout. This would let me do things like a power test with the first few intervals in erg mode, then switch to slope mode for the 20 min test, then switch back.

**Comment by poprocki** [comment]
Any update on this? I think it's a very important feature for doing an FTP test. Also, it would be nice to allow support for switching between slope and erg modes in a .erg file, since I can't reach my keyboard on the bike.
