### ISSUE TITLE
Clean up bad GPS data

### ISSUE THREAD

**Issue by areinhardt25** [GoldenCheetah/GoldenCheetah#1469]
I've tried the GPS points fix routine and it works in most cases, but in cases where there is a significant deviation in lat/long from the trend to that point in time, it doesn't catch the non-zero signal "deviation". For example, it's running along at a lat of 50 and then the next points (1 sec apart) are 25, then 12 then back to 50. It's impossible to have that rapid a change in position. Maybe look at the delta between subsequent points and ignore ones that are > than some threshold? That threshold could be based on velocity at that time if you want to get fancy, or just assume a speed of 200kph or something ridiculously high (for cycling). If the change in either lat or long alone is > than threshold, assume the point is invalid and correct it the way it does for 0 deg points. I can think of a few ways to work through that logic, you still need to catch the several 0 points in a row as invalid, but it shouldn't be too bad. I'm not sure what the Garmin website does but it doesn't have these issues. Thanks and great work by the way!

**Comment by liversedge** [comment]
Why is your GPS data so bad ?

**Comment by areinhardt25** [comment]
I wouldn't say the GPS data is bad.  Just came back from a 1.5 hr road ride; I use a Garmin Edge 500 for ref and live in the Canadian prairies, so wide open skies for the most part except on my route today, a few tree lined streets.  In that ride, I have 0/0 lat/long when the Garmin autostops at lights and stop signs.  Fine.  Apart from that, there are 7 spots during the ride where the lat (and I'll just talk about lat, long behaves the same) drops to 0 for 3-5 sec.  On most of these, the lat is 50 (normal value), 25, 0,0,0, 50, 50....  The 25 value varies from 12 to 37, but clearly, it's a figment of going down to zero.  There are also a few cases were it goes goes from 50 to 0 for a sec or two, then back to 50.  I suspect that has to do with the algorithm in the Garmin.  This behaviour is very normal for me, very rarely do I get a ride that doesn't have these intermediary points in them someplace.  I have to expect that others would be seeing the same thing...or is it just my unit in which case Garmin may want to examine it to see what's up (the firmware is up to date BTW).

**Comment by huepf** [comment]
I am having the same issue with a Garmin FR920XT but only for a month or so (probably a software update). There are a few measurements with coordinates somewhere in Niger (although I ride in Austria). Always have to manually fix the data afterwards. Strava and Garmin Connect can handle those spikes.

**Comment by liversedge** [comment]
What values are the "spikes" ?

**Comment by huepf** [comment]
I have already removed the spikes from the activity in GC so I downloaded the original file from Garmin Connect and imported it in GC. Everything was fine.

Usually I synchronise my activities with Trainingpeaks so I tried that and the spikes are back.

I compared the values at the time stamp with the spikes and it seems as if Trainingpeaks tries to smooth the data from the actual coordinates to zero values.
Original Garmin lat data:
48.190492088 (this is where I ride)
0
0
0

Trainingpeaks data with the same timestamps:
48.190490723 (this is where I ride)
32.126993815 (interpolation to 0)
16.063496908 (interpolation to 0)
0                      (and finally 0)

I attached the Garmin original fit file and the TP file for further analysis.

I guess areinhardt25 also uses TP to sync the data. Right?
[Archive.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/191949/Archive.zip)

**Comment by areinhardt25** [comment]
Actually, I don't use TP, just use GC.  In my case, the Garmin gives location points which look like the interpolations in your second sample set above, and GC doesn't realize that those are not right.  If the points were actually 0, GC would fix them, but not when they are in between "real" and 0, I'm sure it's just looking for 0 points, and not making a judgment that going from 48deg to 32deg lat in a second is impossible for mere mortals.

**Comment by liversedge** [comment]
We could improve the Fix GPS tool to calculate speed from GPS and Time and delete bad points when its inhuman.

**Comment by areinhardt25** [comment]
That would solve the problem.  Thanks!
