### ISSUE TITLE
Encoding broken in tabs' captions

### ISSUE THREAD

**Issue by prokoudine** [GoldenCheetah/GoldenCheetah#1474]
After some of the recent changes GC started rendering captions of tabs in the Activities section in broken codepage for the Russian locale. The translation file is fine, but names like translated versions of 'Ride', 'Details' et al. look like this:

![2015-07-29 22-45-36](https://cloud.githubusercontent.com/assets/57467/8968109/fcd35b28-3643-11e5-8d4d-d9ffc699ee6a.png)

That's not Russian, that's Gibberish :)

Tested on commit 34a6ffc (most recent Git checkout at the moment).

**Comment by prokoudine** [comment]
Additional note: every time I launch GC, the caption seems to grow. I would assume that for some reason GC tries to append the caption's text to the current caption at every launch.

**Comment by prokoudine** [comment]
Another additional note: resetting the layout fixes this within current session, and you have to do it for each mode/layout separately. As soon as you relaunch the app, it all goes to hell again :)

**Comment by amtriathlon** [comment]
This also happens using any of the recent official RC4 builds?

**Comment by MaksVasilev** [comment]
I confirm this on current git snapshot (06.08.2015)

**Comment by prokoudine** [comment]
I don't see this in the windows 64bit build of rc4, but I do see this on linux.

**Comment by MaksVasilev** [comment]
This bug NOT present on Qt5 build. I'm rebuild and test it on same source with Qt 5.4.2: all ok!

**Comment by liversedge** [comment]
I've changed the code to only translate when they are reset, not to try and reset every time they are loaded.

Not sure why it would break though.
