### ISSUE TITLE
TRIMP Points Not Calculated

### ISSUE THREAD

**Issue by cdessert1995** [GoldenCheetah/GoldenCheetah#1479]
I downloaded GC today and added 12 rides in the last month. They include heart rate data but not power data, so I wanted to use TRIMP to analyze them. When I first uploaded the rides, the TRIMP was calculated and I had a LTS/STS/Stress graph. Then, on the left column, under "Charts," I clicked from "PMC (TRIMP)" to "Stress (TISS)" and suddenly all the rides were assigned a TRIMP score of zero. Clicking back did not fix this. 

I decided to delete and reupload the rides to GC. They still had a zero TRIMP score. I then uninstalled GC, and reinstalled. Somehow, even after uninstalling, when I opened it back up my athlete was still there, along with all the changes I made to the UI and my rides! I did this several times because I couldn't really believe that I uninstalled it correctly, with the same result. I even deleted the ride files from my computer, downloaded new ones, and reuploaded them, and still got a zero TRIMP score. I'm out of ideas; is there a way to fix this? Thanks a bunch.

**Comment by liversedge** [comment]
Hi there is a user forum https://groups.google.com/forum/#!forum/golden-cheetah-users for new users.
Please post your questions there :)

This bug tracker is for reporting bugs.

Thanks
Mark
