### ISSUE TITLE
Request: Tie HR warnings to Max-HR instead of hard-coded 200bpm

### ISSUE THREAD

**Issue by Swuzzlebubble** [GoldenCheetah/GoldenCheetah#1483]
Suspicious high HR warnings are generated above 200bpm.
This might be better tied to Max-HR because eg juniors may have Max-HR above 200
For others, numbers below 200 but above Max may be spikes but unreported.

Also other measures like cadence that have hard-coded threshold for warnings may be better as user-defined limits. Eg Cadence warnings are above 150, which is a bit low for say track riders and/or juniors on restricted gears

**Comment by amtriathlon** [comment]
For speed the threshold is fixed at 100kph, it would be desirable to have different thresholds for bike/run/swim
