### ISSUE TITLE
Sorting activities by TSS: should be numeric, not lexicographic

### ISSUE THREAD

**Issue by dhague** [GoldenCheetah/GoldenCheetah#1484]
In the Activites pane, I click on the TSS column to sort actvities by TSS.

Observed: TSS values sorted lexically: 18, 182, 183, 19, 192, 195, ...

Expected: TSS values sorted numerically: 18, 19, 182, 183, 192, 195, ...

GC build date: Jun 21 2015 15:11:49 
Build id: 3104
Version: (developer build)
DB Schema: 112
Metrics: 252
OS: Win

**Comment by liversedge** [comment]
This has been fixed in 3.2 by commit 0502124a89fffc71d6ae7fc4450507805e1fa2fe and a few later that refined it.
