### ISSUE TITLE
Incorrect data labels

### ISSUE THREAD

**Issue by jtbrasel** [GoldenCheetah/GoldenCheetah#1488]
![screen shot 2015-08-06 at 6 04 54 am](https://cloud.githubusercontent.com/assets/13677200/9110172/18b6daaa-3c01-11e5-9295-ba30c9d81ec2.png)
Distance in yellow, TSS in red. The data labels above the bars are correct for TSS, but incorrect for distance - note the labels on the distance scale on the left-hand side of the screen. So the height of the bar is correct, but the label above it is incorrect.

**Comment by liversedge** [comment]
What version are you using?

**Comment by jtbrasel** [comment]
3.1.0

**Comment by liversedge** [comment]
Its fixed in 3.2 :)
