### ISSUE TITLE
Gear Ratio trend ignored pause in activity

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#1490]
![gear_trend](https://cloud.githubusercontent.com/assets/1708135/9118320/3d16d766-3c78-11e5-83d8-81cbd5e30fb3.png)

Gear Ratio Di2 (brown) trend - shifted to the right without pauses.

Activity file: http://velo100.ru/files/856837704.fit_.zip

**Comment by liversedge** [comment]
Whilst I agree it is a bug, you can avoid it by fixing the gaps in recording.
There are several points in the ride where the gaps are > 1s.

FWIW, if you like a dark theme, the Chrome Color in the colors list (its right at the bottom of the list) sets the background for the toolbar etc. If you set this to a dark color the foreground will adjust accordingly.

**Comment by MaksVasilev** [comment]
Points with gaps are > 1s - this is a standart pause in device. All other trends show it normal.

**Comment by Joern-R** [comment]
Problem occurs when setting "Smoothing" > 1. Basically GearRatio shall not be "Smoothed" at all - since it calculates discrete values. Will look into this.
