### ISSUE TITLE
Are averages and Metrics calculated from the DURATION or TIME RIDING?

### ISSUE THREAD

**Issue by davepalese** [GoldenCheetah/GoldenCheetah#1505]
It would be great if the AVERAGES and METRICS numbers on the summary were calculated from just the TIME RIDING and not the DURATION. This affects the AVERAGE POWER, XPOWER, TSS and so on. Or am I missing something? Can you tell GC to do one or the other?

**Comment by liversedge** [comment]
Please use the user forums for questions.
https://groups.google.com/forum/#!forum/golden-cheetah-users

Thanks :)

**Comment by davepalese** [comment]
Will do.
Thanks

*Dave Palese*
General Manager, Gorham Bike and Ski
Certified Master BodyGeometry FIT Technician
dave@gorhambike.com <mailto:dave@gorhambike.com> | 207.773.1700
693 Congress St., Portland, ME 04102
www.gorhambike.com <http://www.gorhambike.com>

**Comment by liversedge** [comment]
Saw your post and responded, but now wondering if this is to support you when doing a bike fit ?
I'm now wondering if maybe there are some use-cases where this might be useful after all.

**Comment by davepalese** [comment]
Thanks for getting back to me, Mark. And BTW, I just wanted to say that 
what you and your collaborators have created in GC is really awesome. I 
am a coach of 15 years now and have been a WKO+ user through that time 
and now use GC. Really great.

That said....

I don't use it for bike fits, although, now that you mention it, I could 
see the benefits of it there and how only riding time calculations would 
work for that application.

To be honest, it's more that I want my numbers between GC and 
TrainingPeaks to align better. And I suspect that this is why they 
don't. Am I wrong?

I just think it should just be an option to set it one way or another.

Thanks again for your time.

*Dave Palese*
General Manager, Gorham Bike and Ski
Certified Master BodyGeometry FIT Technician
dave@gorhambike.com <mailto:dave@gorhambike.com> | 207.773.1700
693 Congress St., Portland, ME 04102
www.gorhambike.com <http://www.gorhambike.com>
