### ISSUE TITLE
Unable to build with Qt 5.4.2 on Linux

### ISSUE THREAD

**Issue by prokoudine** [GoldenCheetah/GoldenCheetah#1508]
Got Fedora 22, 32bit. Using 'qmake-qt5 -recursive' with subsequent 'make' produces:

make[1]: Entering directory '/home/alex/soft/sports/goldencheetah-2015-08-10/src'
g++ -c -pipe -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -O2 -Wall -W -D_REENTRANT -fPIC -DGC_VIDEO_VLC -DGC_HAVE_ICAL -DGC_HAVE_LIBUSB -DGC_HAVE_VLC -DQXT_STATIC -DGC_HAVE_SOAP -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WEBKITWIDGETS_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_WEBKIT_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_SCRIPT_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -I../qwt/src -I../qxt/src -I../qtsolutions/json -isystem /usr/include -isystem /usr/include -isystem /usr/include -I../qtsolutions/soap -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWebKitWidgets -isystem /usr/include/qt5/QtMultimediaWidgets -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtWebKit -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtScript -isystem /usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtCore -I. -I/usr/lib/qt5/mkspecs/linux-g++ -o ICalendar.o ICalendar.cpp
In file included from /usr/include/qt5/QtWidgets/qabstractitemview.h:39:0,
                 from /usr/include/qt5/QtWidgets/qtreeview.h:37,
                 from /usr/include/qt5/QtWidgets/qtreewidget.h:37,
                 from /usr/include/qt5/QtWidgets/QTreeWidget:1,
                 from Athlete.h:24,
                 from ICalendar.cpp:19:
/usr/include/qt5/QtCore/qitemselectionmodel.h:85:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 0)
                        ^
In file included from /usr/include/qt5/QtGui/QtGui:4:0,
                 from Athlete.h:25,
                 from ICalendar.cpp:19:
/usr/include/qt5/QtGui/qaccessible.h:414:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 0)
                        ^
/usr/include/qt5/QtGui/qaccessible.h:954:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 0)
                        ^
In file included from /usr/include/qt5/QtGui/QtGui:10:0,
                 from Athlete.h:25,
                 from ICalendar.cpp:19:
/usr/include/qt5/QtGui/qiconengine.h:77:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 0)
                        ^
In file included from /usr/include/qt5/QtGui/qsurface.h:38:0,
                 from /usr/include/qt5/QtGui/qoffscreensurface.h:38,
                 from /usr/include/qt5/QtGui/QtGui:31,
                 from Athlete.h:25,
                 from ICalendar.cpp:19:
/usr/include/qt5/QtGui/qsurfaceformat.h:122:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 2)
                        ^
In file included from /usr/include/qt5/QtGui/QtGui:47:0,
                 from Athlete.h:25,
                 from ICalendar.cpp:19:
/usr/include/qt5/QtGui/qmatrix4x4.h:1088:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 0)
                        ^
In file included from /usr/include/qt5/QtGui/QtGui:56:0,
                 from Athlete.h:25,
                 from ICalendar.cpp:19:
/usr/include/qt5/QtGui/qopenglfunctions.h:252:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 0)
                        ^
In file included from /usr/include/qt5/QtGui/QtGui:60:0,
                 from Athlete.h:25,
                 from ICalendar.cpp:19:
/usr/include/qt5/QtGui/qopengltexture.h:345:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 3)
                        ^
/usr/include/qt5/QtGui/qopengltexture.h:373:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 3)
                        ^
In file included from /usr/include/qt5/QtGui/qdesktopservices.h:38:0,
                 from /usr/include/qt5/QtGui/QtGui:100,
                 from Athlete.h:25,
                 from ICalendar.cpp:19:
/usr/include/qt5/QtCore/qstandardpaths.h:87:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 2)
                        ^
In file included from /usr/include/qt5/QtGui/QtGui:100:0,
                 from Athlete.h:25,
                 from ICalendar.cpp:19:
/usr/include/qt5/QtGui/qdesktopservices.h:56:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 0)
                        ^
In file included from /usr/include/qt5/QtWidgets/QHeaderView:1:0,
                 from Athlete.h:27,
                 from ICalendar.cpp:19:
/usr/include/qt5/QtWidgets/qheaderview.h:111:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 0)
                        ^
/usr/include/qt5/QtWidgets/qheaderview.h:118:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 0)
                        ^
/usr/include/qt5/QtWidgets/qheaderview.h:133:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 0)
                        ^
In file included from /usr/include/qt5/QtWidgets/QApplication:1:0,
                 from GcWindowRegistry.h:23,
                 from GoldenCheetah.h:43,
                 from ICalendar.h:21,
                 from ICalendar.cpp:20:
/usr/include/qt5/QtWidgets/qapplication.h:103:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 0)
                        ^
/usr/include/qt5/QtWidgets/qapplication.h:143:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 0)
                        ^
/usr/include/qt5/QtWidgets/qapplication.h:173:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5, 0)
                        ^
In file included from /usr/include/QtCore/qchar.h:45:0,
                 from /usr/include/QtCore/qstring.h:45,
                 from /usr/include/qt5/QtCore/qdir.h:37,
                 from /usr/include/qt5/QtCore/QDir:1,
                 from Athlete.h:22,
                 from ICalendar.cpp:19:
/usr/include/qt5/QtCore/qdir.h: In function 'bool qIsDetached(T&) [with T = QDir]':
/usr/include/qt5/QtCore/qdir.h:217:1: error: 'class QDir' has no member named 'isDetached'
 Q_DECLARE_SHARED(QDir)
 ^
/usr/include/qt5/QtCore/qdir.h: In function 'void qSwap(T&, T&) [with T = QDir]':
/usr/include/qt5/QtCore/qdir.h:217:1: error: 'class QDir' has no member named 'data_ptr'
 Q_DECLARE_SHARED(QDir)
 ^
/usr/include/qt5/QtCore/qdir.h:217:1: error: 'class QDir' has no member named 'data_ptr'
 Q_DECLARE_SHARED(QDir)
 ^
/usr/include/qt5/QtCore/qdir.h: In function 'void std::swap(_Tp&, _Tp&) [with _Tp = QDir]':
/usr/include/qt5/QtCore/qdir.h:217:1: error: 'class QDir' has no member named 'data_ptr'
 Q_DECLARE_SHARED(QDir)
 ^
/usr/include/qt5/QtCore/qdir.h:217:1: error: 'class QDir' has no member named 'data_ptr'
 Q_DECLARE_SHARED(QDir)
 ^
In file included from /usr/include/qt5/QtWidgets/qwidget.h:45:0,
                 from /usr/include/qt5/QtWidgets/qframe.h:37,
                 from /usr/include/qt5/QtWidgets/qabstractscrollarea.h:37,
                 from /usr/include/qt5/QtWidgets/qabstractitemview.h:37,
                 from /usr/include/qt5/QtWidgets/qtreeview.h:37,
                 from /usr/include/qt5/QtWidgets/qtreewidget.h:37,
                 from /usr/include/qt5/QtWidgets/QTreeWidget:1,
                 from Athlete.h:24,
                 from ICalendar.cpp:19:
/usr/include/qt5/QtWidgets/qsizepolicy.h: At global scope:
/usr/include/qt5/QtWidgets/qsizepolicy.h:44:24: error: variable 'Q_WIDGETS_EXPORT QSizePolicy' has initializer but incomplete type
 class Q_WIDGETS_EXPORT QSizePolicy
                        ^
In file included from /usr/include/QtCore/qobject.h:47:0,
                 from /usr/include/QtCore/qiodevice.h:46,
                 from /usr/include/QtCore/qfile.h:45,
                 from /usr/include/QtCore/qfileinfo.h:45,
                 from /usr/include/qt5/QtCore/qdir.h:38,
                 from /usr/include/qt5/QtCore/QDir:1,
                 from Athlete.h:22,
                 from ICalendar.cpp:19:
/usr/include/qt5/QtWidgets/qsizepolicy.h:46:5: error: expected primary-expression before 'public'
     Q_GADGET
     ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:46:5: error: expected '}' before 'public'
/usr/include/qt5/QtWidgets/qsizepolicy.h:46:5: error: expected ',' or ';' before 'public'
/usr/include/qt5/QtWidgets/qsizepolicy.h:46:5: error: expected unqualified-id before 'private'
     Q_GADGET
     ^
In file included from /usr/include/qt5/QtWidgets/qwidget.h:45:0,
                 from /usr/include/qt5/QtWidgets/qframe.h:37,
                 from /usr/include/qt5/QtWidgets/qabstractscrollarea.h:37,
                 from /usr/include/qt5/QtWidgets/qabstractitemview.h:37,
                 from /usr/include/qt5/QtWidgets/qtreeview.h:37,
                 from /usr/include/qt5/QtWidgets/qtreewidget.h:37,
                 from /usr/include/qt5/QtWidgets/QTreeWidget:1,
                 from Athlete.h:24,
                 from ICalendar.cpp:19:
/usr/include/qt5/QtWidgets/qsizepolicy.h:59:19: error: 'GrowFlag' was not declared in this scope
         Minimum = GrowFlag,
                   ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:60:19: error: 'ShrinkFlag' was not declared in this scope
         Maximum = ShrinkFlag,
                   ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:61:21: error: 'GrowFlag' was not declared in this scope
         Preferred = GrowFlag | ShrinkFlag,
                     ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:61:32: error: 'ShrinkFlag' was not declared in this scope
         Preferred = GrowFlag | ShrinkFlag,
                                ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:62:28: error: 'GrowFlag' was not declared in this scope
         MinimumExpanding = GrowFlag | ExpandFlag,
                            ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:62:39: error: 'ExpandFlag' was not declared in this scope
         MinimumExpanding = GrowFlag | ExpandFlag,
                                       ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:63:21: error: 'GrowFlag' was not declared in this scope
         Expanding = GrowFlag | ShrinkFlag | ExpandFlag,
                     ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:63:32: error: 'ShrinkFlag' was not declared in this scope
         Expanding = GrowFlag | ShrinkFlag | ExpandFlag,
                                ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:63:45: error: 'ExpandFlag' was not declared in this scope
         Expanding = GrowFlag | ShrinkFlag | ExpandFlag,
                                             ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:64:19: error: 'ShrinkFlag' was not declared in this scope
         Ignored = ShrinkFlag | GrowFlag | IgnoreFlag
                   ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:64:32: error: 'GrowFlag' was not declared in this scope
         Ignored = ShrinkFlag | GrowFlag | IgnoreFlag
                                ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:64:43: error: 'IgnoreFlag' was not declared in this scope
         Ignored = ShrinkFlag | GrowFlag | IgnoreFlag
                                           ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'int QSizePolicy()':
/usr/include/qt5/QtWidgets/qsizepolicy.h:86:21: error: only constructors take member initializers
     QSizePolicy() : data(0) { }
                     ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'int QSizePolicy(Policy, Policy, ControlType)':
/usr/include/qt5/QtWidgets/qsizepolicy.h:89:11: error: only constructors take member initializers
         : data(0) {
           ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:90:9: error: 'bits' was not declared in this scope
         bits.horPolicy = horizontal;
         ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:92:28: error: 'setControlType' was not declared in this scope
         setControlType(type);
                            ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: At global scope:
/usr/include/qt5/QtWidgets/qsizepolicy.h:94:31: error: non-member function 'Policy horizontalPolicy()' cannot have cv-qualifier
     Policy horizontalPolicy() const { return static_cast<Policy>(bits.horPolicy); }
                               ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'Policy horizontalPolicy()':
/usr/include/qt5/QtWidgets/qsizepolicy.h:94:66: error: 'bits' was not declared in this scope
     Policy horizontalPolicy() const { return static_cast<Policy>(bits.horPolicy); }
                                                                  ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: At global scope:
/usr/include/qt5/QtWidgets/qsizepolicy.h:95:29: error: non-member function 'Policy verticalPolicy()' cannot have cv-qualifier
     Policy verticalPolicy() const { return static_cast<Policy>(bits.verPolicy); }
                             ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'Policy verticalPolicy()':
/usr/include/qt5/QtWidgets/qsizepolicy.h:95:64: error: 'bits' was not declared in this scope
     Policy verticalPolicy() const { return static_cast<Policy>(bits.verPolicy); }
                                                                ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: At global scope:
/usr/include/qt5/QtWidgets/qsizepolicy.h:96:31: error: non-member function 'ControlType controlType()' cannot have cv-qualifier
     ControlType controlType() const;
                               ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'void setHorizontalPolicy(Policy)':
/usr/include/qt5/QtWidgets/qsizepolicy.h:98:42: error: 'bits' was not declared in this scope
     void setHorizontalPolicy(Policy d) { bits.horPolicy = d; }
                                          ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'void setVerticalPolicy(Policy)':
/usr/include/qt5/QtWidgets/qsizepolicy.h:99:40: error: 'bits' was not declared in this scope
     void setVerticalPolicy(Policy d) { bits.verPolicy = d; }
                                        ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: At global scope:
/usr/include/qt5/QtWidgets/qsizepolicy.h:102:44: error: non-member function 'Qt::Orientations expandingDirections()' cannot have cv-qualifier
     Qt::Orientations expandingDirections() const {
                                            ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'Qt::Orientations expandingDirections()':
/usr/include/qt5/QtWidgets/qsizepolicy.h:104:32: error: 'ExpandFlag' was not declared in this scope
         if (verticalPolicy() & ExpandFlag)
                                ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:106:34: error: 'ExpandFlag' was not declared in this scope
         if (horizontalPolicy() & ExpandFlag)
                                  ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'void setHeightForWidth(bool)':
/usr/include/qt5/QtWidgets/qsizepolicy.h:111:38: error: 'bits' was not declared in this scope
     void setHeightForWidth(bool b) { bits.hfw = b;  }
                                      ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: At global scope:
/usr/include/qt5/QtWidgets/qsizepolicy.h:112:30: error: non-member function 'bool hasHeightForWidth()' cannot have cv-qualifier
     bool hasHeightForWidth() const { return bits.hfw; }
                              ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'bool hasHeightForWidth()':
/usr/include/qt5/QtWidgets/qsizepolicy.h:112:45: error: 'bits' was not declared in this scope
     bool hasHeightForWidth() const { return bits.hfw; }
                                             ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'void setWidthForHeight(bool)':
/usr/include/qt5/QtWidgets/qsizepolicy.h:113:38: error: 'bits' was not declared in this scope
     void setWidthForHeight(bool b) { bits.wfh = b;  }
                                      ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: At global scope:
/usr/include/qt5/QtWidgets/qsizepolicy.h:114:30: error: non-member function 'bool hasWidthForHeight()' cannot have cv-qualifier
     bool hasWidthForHeight() const { return bits.wfh; }
                              ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'bool hasWidthForHeight()':
/usr/include/qt5/QtWidgets/qsizepolicy.h:114:45: error: 'bits' was not declared in this scope
     bool hasWidthForHeight() const { return bits.wfh; }
                                             ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: At global scope:
/usr/include/qt5/QtWidgets/qsizepolicy.h:116:27: error: 'QSizePolicy' does not name a type
     bool operator==(const QSizePolicy& s) const { return data == s.data; }
                           ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:116:43: error: non-member function 'bool operator==(const int&)' cannot have cv-qualifier
     bool operator==(const QSizePolicy& s) const { return data == s.data; }
                                           ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:116:43: error: 'bool operator==(const int&)' must have an argument of class or enumerated type
/usr/include/qt5/QtWidgets/qsizepolicy.h:117:27: error: 'QSizePolicy' does not name a type
     bool operator!=(const QSizePolicy& s) const { return data != s.data; }
                           ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:117:43: error: non-member function 'bool operator!=(const int&)' cannot have cv-qualifier
     bool operator!=(const QSizePolicy& s) const { return data != s.data; }
                                           ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:117:43: error: 'bool operator!=(const int&)' must have an argument of class or enumerated type
/usr/include/qt5/QtWidgets/qsizepolicy.h:118:30: error: expected constructor, destructor, or type conversion before ';' token
     operator QVariant() const; // implemented in qlayoutitem.cpp
                              ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:120:29: error: non-member function 'int horizontalStretch()' cannot have cv-qualifier
     int horizontalStretch() const { return static_cast<int>(bits.horStretch); }
                             ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'int horizontalStretch()':
/usr/include/qt5/QtWidgets/qsizepolicy.h:120:61: error: 'bits' was not declared in this scope
     int horizontalStretch() const { return static_cast<int>(bits.horStretch); }
                                                             ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: At global scope:
/usr/include/qt5/QtWidgets/qsizepolicy.h:121:27: error: non-member function 'int verticalStretch()' cannot have cv-qualifier
     int verticalStretch() const { return static_cast<int>(bits.verStretch); }
                           ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'int verticalStretch()':
/usr/include/qt5/QtWidgets/qsizepolicy.h:121:59: error: 'bits' was not declared in this scope
     int verticalStretch() const { return static_cast<int>(bits.verStretch); }
                                                           ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'void setHorizontalStretch(int)':
/usr/include/qt5/QtWidgets/qsizepolicy.h:122:52: error: 'bits' was not declared in this scope
     void setHorizontalStretch(int stretchFactor) { bits.horStretch = static_cast<quint32>(qBound(0, stretchFactor, 255)); }
                                                    ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'void setVerticalStretch(int)':
/usr/include/qt5/QtWidgets/qsizepolicy.h:123:50: error: 'bits' was not declared in this scope
     void setVerticalStretch(int stretchFactor) { bits.verStretch = static_cast<quint32>(qBound(0, stretchFactor, 255)); }
                                                  ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: At global scope:
/usr/include/qt5/QtWidgets/qsizepolicy.h:125:33: error: non-member function 'bool retainSizeWhenHidden()' cannot have cv-qualifier
     bool retainSizeWhenHidden() const { return bits.retainSizeWhenHidden; }
                                 ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'bool retainSizeWhenHidden()':
/usr/include/qt5/QtWidgets/qsizepolicy.h:125:48: error: 'bits' was not declared in this scope
     bool retainSizeWhenHidden() const { return bits.retainSizeWhenHidden; }
                                                ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'void setRetainSizeWhenHidden(bool)':
/usr/include/qt5/QtWidgets/qsizepolicy.h:126:53: error: 'bits' was not declared in this scope
     void setRetainSizeWhenHidden(bool retainSize) { bits.retainSizeWhenHidden = retainSize; }
                                                     ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: At global scope:
/usr/include/qt5/QtWidgets/qsizepolicy.h:131:1: error: expected unqualified-id before 'private'
 private:
 ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:134:5: error: 'friend' used outside of class
     friend Q_WIDGETS_EXPORT QDataStream &operator>>(QDataStream &, QSizePolicy &);
     ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:134:41: error: expected initializer before '&' token
     friend Q_WIDGETS_EXPORT QDataStream &operator>>(QDataStream &, QSizePolicy &);
                                         ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: In function 'int QSizePolicy(int)':
/usr/include/qt5/QtWidgets/qsizepolicy.h:136:26: error: only constructors take member initializers
     QSizePolicy(int i) : data(i) { }
                          ^
/usr/include/qt5/QtWidgets/qsizepolicy.h: At global scope:
/usr/include/qt5/QtWidgets/qsizepolicy.h:151:5: error: namespace-scope anonymous aggregates must be static
     };
     ^
/usr/include/qt5/QtWidgets/qsizepolicy.h:152:1: error: expected declaration before '}' token
 };
 ^
Makefile:5867: recipe for target 'ICalendar.o' failed
make[1]: *** [ICalendar.o] Error 1
make[1]: Leaving directory '/home/alex/soft/sports/goldencheetah-2015-08-10/src'
Makefile:86: recipe for target 'sub-src-make_first-ordered' failed
make: *** [sub-src-make_first-ordered] Error 2

Am I trying to do something silly?

**Comment by liversedge** [comment]
all these errors are related to your build environment, you will need to check your include paths.

please use the developers list for these kinds of questions / discussions.
https://groups.google.com/forum/#!forum/golden-cheetah-developers

Thanks
