### ISSUE TITLE
User parameters for Power Estimation Tool 

### ISSUE THREAD

**Issue by Peter2m** [GoldenCheetah/GoldenCheetah#1511]
On which values of weight of equipment these estimations are based on....the resulting power values seem relatively small......the weight of my mountainbike fe is approx 12kg.....how can i adjust the weight.....i would think that this should be don in an seperate equipment data field.

**Comment by liversedge** [comment]
Yes, I recently used the power estimator for mountain biking and the numbers were a bit off, RR was the big one for me. We should add some way of changing the model parameters when estimating power.
