### ISSUE TITLE
Weight in Summary Page incorrect

### ISSUE THREAD

**Issue by nickdodo** [GoldenCheetah/GoldenCheetah#1519]
My weight is 140lbs. 
The Summary page in trends shows the average as 308.65 lbs
I have selected imperial under athlete preferences.
It seems strange that this is 2.2 x my weight.
I found this issue before but it is closed...

**Comment by amtriathlon** [comment]
Which version are you using?

**Comment by nickdodo** [comment]
Hi atriathlon,
I should have noted it - the version is 
Version 3.2.0_RC2
Build Id 3105
Build Date Jun 28 2015 23:54:15

**Comment by amtriathlon** [comment]
This was fixed after RC2 in https://github.com/GoldenCheetah/GoldenCheetah/commit/92c89d43eae3b2449cd338b62d1bbb85ac0540dd, I should be Ok in the release version, which is already available on the main site http://www.goldencheetah.org/#section-download

**Comment by nickdodo** [comment]
Many thanks - I'll download it.

**Comment by nickdodo** [comment]
Downloaded and installed - much better
Thanks
