### ISSUE TITLE
GC 3.2 Freeze tabbing between Trends> Aerobic and Anaerobic Power

### ISSUE THREAD

**Issue by RJKflyer** [GoldenCheetah/GoldenCheetah#1520]
In Trends, selecting Aerobic Power, then selecting Anaerobic Power cases a freeze. Have to Force Quit. Mac 10.10.4
![screen shot 2015-08-18 at 15 20 32](https://cloud.githubusercontent.com/assets/11195133/9332631/7c2806ac-45bd-11e5-849d-43fa206df1ea.png)

**Comment by liversedge** [comment]
reset charts.
