### ISSUE TITLE
TRIMP Points ommited from PMC when HR has been entered manually

### ISSUE THREAD

**Issue by Red1n** [GoldenCheetah/GoldenCheetah#1523]
In version 3.1 when TRIMP Zonal Points is plotted on a PMC graph the data shows bars for rides where there is HR recorded and where no HR has been recorded and an average heart rate has been entered in the details screen.
In version 3.2 the bars for the manually entered TRIMP Zonal Points are not shown

**Comment by amtriathlon** [comment]
If you use TRIMP Points or TRIMP(100) Points manually overriding average heart rate would automatically generate a TRIMP value based on that average, but TRIMP Zonal Points are based on Time in HR zones weighted by the corresponding coefficients in HR Zones, not on average HR, so manually overriding average HR doesn't produce a TRIMP value > 0, that doesn't seem to be changed from the inception on that metric back in 2010.
With the current code to override TRIMP Zonal Points you need to override the metric itself or the Time in HR Zone(s), not just average HR.

**Comment by Red1n** [comment]
Thank you for the explanation of how TRIMP works, however this is not my experience of using GC 3.1. Where rides were recorded without HR data I entered an average figure in the metrics screen. GC then calculated a TRIMP score and showed the Zonal points in my PMC graph. 
It is the fact that 3.2 longer displays this data in the graph in 3.2 that caused me to raise the issue.

**Comment by amtriathlon** [comment]
Oh, I understand the issue now: TRIMP Zonal Points were not supported for PMC use on v3.1, this is a new feature for 3.2, the PMC you had in 3.1 was based on TRIMP Points which automatically get a value from average HR. If your prefer that behavior continue to use TRIMP Points as base metric for PMC as it was in 3.1, it will behave exactly the same.

**Comment by amtriathlon** [comment]
Follow up: in the next version these should work as you expect https://github.com/GoldenCheetah/GoldenCheetah/issues/1528

**Comment by Red1n** [comment]
Brilliant. Thank you for the explanations and follow up.
