### ISSUE TITLE
TRIMP Zonal Points fallback when Average HR has been entered manually

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#1528]
When time in HR zones is zero, but there is a non-zero Average HR, Time Moving (or Duration) can be assigned to the zone corresponding to Average HR for TRIMP Zonal Points calculation.
Follow-up from https://github.com/GoldenCheetah/GoldenCheetah/issues/1523

**Comment by liversedge** [comment]
First commit :)

**Comment by amtriathlon** [comment]
I had to push something simple to see if it was true ;-)

BTW, labels indicating reason, priority and milestone are ok?

**Comment by liversedge** [comment]
Don't sweat those, I tend to come along and mess with them.
I'm a little OCD in that respect !
