### ISSUE TITLE
Faulty sorting in activity log 

### ISSUE THREAD

**Issue by JCB-K** [GoldenCheetah/GoldenCheetah#1533]
See screenshot where the data is sorted by TSS. It doesn't sort by the total value but by the first character, then 2nd character secondary etc. The same way alphabetic sorting works, basically. Same goes for all other columns in this view.

![screen shot 2015-08-24 at 09 42 11](https://cloud.githubusercontent.com/assets/636039/9435074/c6b51260-4a44-11e5-854d-4ab0781e83cd.png)

**Comment by JCB-K** [comment]
GC 3.2 on latest OS X.

**Comment by liversedge** [comment]
That isn't 3.2, at least not the final release.

**Comment by liversedge** [comment]
That issue was fixed after RC2.

**Comment by JCB-K** [comment]
My bad, was still running an outdated development version. Updated now.
