### ISSUE TITLE
Elite Crono Mag elastogel virtual power support?

### ISSUE THREAD

**Issue by pirnie** [GoldenCheetah/GoldenCheetah#1538]
Would it be possible to add the power curve for this trainer into golden cheetah?

![27c](https://cloud.githubusercontent.com/assets/5950369/9472825/6d0d6238-4b4f-11e5-8709-87d55f230900.png)

http://www.powercurvesensor.com/files/27c.png

It would be appreciated greatly!

**Comment by beenhead** [comment]
+1 Thanks
