### ISSUE TITLE
GC V3.2 August 12 version, trouble saving changes using Ctrl-S.

### ISSUE THREAD

**Issue by twizzle** [GoldenCheetah/GoldenCheetah#1542]
If you make changes to an activity (Notes and Weight, for instance) and hit Ctrl-S to save, it doesn't save the .json file but in the case of "notes", it does update the text in the activities list.  If you change a metric or notes, you can right-click on the activity in the list and select "save changes"  or use the Activity->Save Changes menu item, they both work.  Just not Ctrl-S.

**Comment by liversedge** [comment]
If you are on a Mac it is Cmd-S

**Comment by twizzle** [comment]
Windows.

'M'.

**Comment by liversedge** [comment]
fixed in 3.3
