### ISSUE TITLE
Win version of v3.2 incorrectly exports notes with Cyrillics to TrainingPeaks

### ISSUE THREAD

**Issue by prokoudine** [GoldenCheetah/GoldenCheetah#1547]
The official Windows 64bit build of v3.2 exports garbage instead of Cyrillics to TrainingPeaks (looks like codepage/encoding bug). My own 32bit builds on Linux don't have that bug.

![training-peaks-export-cyrrillics-from-win-64bit](https://cloud.githubusercontent.com/assets/57467/9602455/5c9b4caa-50b1-11e5-99a0-0d8c1e342839.jpg)

**Comment by Joern-R** [comment]
Just tested with German Locale - the PWX file created look fine. (And this is what is sent to TP).
Can you please check how the Comment block looks like if you use the "Export" function and export the file as .pwx to your local disk.

And please send me your files (.JSON and .PWX) - created on your Windows PC - so I can try if I can reproduce the problem on my system (even though I am running a different Locale). Windows is a bit tricky w.r.t. Locales / Codepages. Linux/MacOs are fully Unicode. 

email:  joern.rm  at   gmail.com

I compared the code to other places where we are writing XML or Text Files like the .JSON files - in those places we are using QTextStream and pre-actively set "UTF-8" as codec. 

Thanks for your support.
Joern

**Comment by Joern-R** [comment]
The fix was applied to 3.2.0 Tag code and a private build with the fix was shared with Alex to test it before merging. Test was confirmed to be successful and problem is resolved.
