### ISSUE TITLE
Add Garmin segments as intervals

### ISSUE THREAD

**Issue by peteonbike** [GoldenCheetah/GoldenCheetah#1548]
If I could work out the coding for this I would......
Garmin have introduced segments which are basically an auto start/stop interval. When you open a garmin fit file they are recorded in the same way an interval is except they are labelled as "segment" and have a segment name.
How hard would it be to show these in golden cheetah?
thanks
ps version 3.2 is brilliant!

**Comment by gille** [comment]
Would you be willing to share a .FIT file (I assume that's format) containing this? either to the bug or just email me (mgille at the google mail service).
