### ISSUE TITLE
Document built in metrics and formulas etc

### ISSUE THREAD

**Issue by Peter2m** [GoldenCheetah/GoldenCheetah#1556]
- I would find a list of all installed metrics, which indicates what formulas etc have been applied, and a short explanation and/or hint to relevant articles in the web very, very helpful (fe climb_rating and many others, especially the more scientific metrics). (in the manual)
- (Again) i like to suggest that the metric VAM (vertical climbing speed) should be drived from the uphill periods of every ride only....
-  Besides VAMCP_setting, also W`, as well as Pmax should be an installed metric.

I hope you do find my proposals good (or at least understand them)
Best regards
Peter Zweimüller

**Comment by amtriathlon** [comment]
I'm closing this because built in metrics are documented in 2 ways for V4.0:
1) Tooltips over metrics lists in Metrics Config and Metrics Trends charts
2) Glossary: https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Glossary
