### ISSUE TITLE
Support Metrics in Calendar Text

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#1563]
Metrics should be allowed on the calendar -- also, what if the metric is not defined in metadata ?

**Comment by liversedge** [comment]
fixed in 3.3

**Comment by amtriathlon** [comment]
The fix in 3.3 prepend the field name when field type is non-text, but the value is still obtained via getTag, which doesn't work for metrics/overrides.
Recent discussion on the forum: https://groups.google.com/d/msg/golden-cheetah-users/-d7P0Y6e4Gk/59ca79RKCQAJ
