### ISSUE TITLE
Importing Data from Strava

### ISSUE THREAD

**Issue by brucesz54** [GoldenCheetah/GoldenCheetah#1567]
I have around 90 rides I'd like to download from Strava. When I choose "Import from File" in the menu, all .gpx files are validated, however, the import stops at step 3 of 4 "Confirm Date & Time". The "Save" option remains gray and can't be selected. I have been able to import individual workouts by selecting only a single .gpx. Is there a way to batch import all files?

**Comment by hnaess** [comment]
Experienced similar issue, both in my caue I tried to import the original .FIT files which I had copied from my Garmin Edge 800 device.

**Comment by liversedge** [comment]
do the gpx files contain the ride date and time?
the step is asking you to provide that information because it is not found in the files you are importing.

**Comment by brucesz54** [comment]
Mark,
The files did not have Date & Time.  Even though the files had no data, I added a date and the program accepted them.
There were 8 other files with no data so I deleted them before importing the other 83. Worked fine.
Is this the appropriate link to ask questions about the program as I get more into its use?
Thanks, 
Bruce Schwartz

**Comment by liversedge** [comment]
We have a user forum for that kind of stuff: https://groups.google.com/forum/#!forum/golden-cheetah-users
