### ISSUE TITLE
Pace of running intervals

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#1568]
Hi,

I'm using GC 3.2 on Ubuntu 15.04 and have noticed a bug in the detection of the peak pace for running intervals. The detected pace for the intervals seems to be different from the actual pace, as you can see in the screenshots in attachment. The 20 min peak pace is detected as 6:17 min/km, while the actual pace is 5:48 min/km.
 
![Interval detection - peak pace for running activities](https://cloud.githubusercontent.com/assets/14836910/10100703/e00b854c-6393-11e5-9aaa-242faea7a799.png)

I've seen differences in pace up to 0:30 min/km, where the detected pace can be either faster or slower than the actual pace.
It seems that the incorrect value of 6.3 (= 6:17 min/km) is used for the charts in the long term trends as you can see below.
 
![Use of incorrect peak pace in long term trends](https://cloud.githubusercontent.com/assets/14836910/10100702/e00a3cf0-6393-11e5-8901-3707890f78f5.png)

The same behaviour occurs when running GC 3.2 under Windows 7. I'm recording the activities with a Garmin Edge 800 and 1s recording. I tried selecting "Smart recording" in the GoldenCheetah settings, but this does not make any difference.

Any idea if this is a (known) bug or if it has something to do with my hardware and/or settings?

Kind regards,

Nigel

**Comment by liversedge** [comment]
You have gaps in recording.

**Comment by amtriathlon** [comment]
Hi Nigel, actually there is a difference between the way best pace and intervals are computed (including zeros) and the way average speed/pace is calculated (without zeros / using time moving), but that doesn't seems to explain your differences, can you upload the file here or at the google group?

BTW, those distance intervals should show (pace) instead of (0w), I will change that.

**Comment by nigelvdv** [comment]
Hi,

I just checked for gaps in recording and couldn't find any, every second seems to have a measurement. Normally I don't have to stop during my runs as well. I ran the fix gaps tool anyway, but no change in detected or actual pace.

I uploaded the original file from my Garmin to dropbox:
https://www.dropbox.com/s/94spc66jrqfkgv6/2015-09-22-09-30-10.fit?dl=0

And the exported file from GoldenCheetah:
https://www.dropbox.com/s/ajj73h2rzsqs3pb/2015-09-22_GC_export_nigelvdv.csv?dl=0

Curious to see if you are noticing the same differences.

Kind regards!

Nigel

**Comment by amtriathlon** [comment]
The problem seems to be the speed channel doesn't match the distance one, best intervals and curve are computed as the average of speed while average speed/pace is calculated as distance traveled divided (moving) time.
Even when there is no gaps nor zero speed in the intervals both calculations don't match in this file.
This can be easily verified in the Edit "chart", selecting an interval highlight the involved samples and allows to copy and paste them to a spreadsheet to verify the computations.
Did you use a footpod for speed or only GPS?

**Comment by nigelvdv** [comment]
Only gps data, a footpod can't be used with a garmin edge.

**Comment by amtriathlon** [comment]
Anyway the problem is both data, speed and distance, are directly what comes from the device for each second and they don't agree...

**Comment by nigelvdv** [comment]
Strange, i'll try to let both of them correspond with each other by editting them in a spreadsheet later this weekend. If that improves things I might contact garmin's support service.

Thanks for the help!

**Comment by nigelvdv** [comment]
Hi, 

Speed and distance data indeed are not corresponding with each other, so I tried a few things:

1. Distance was kept, the speed was recalculated to correspond with the distance. The logged 1s-speed data increase in comparison with the original data. Are these data provided by my GPS device (in the fit-file), or are they calculated by GoldenCheetah? If they are in the fit-file I might contact Garmin's helpdesk to see if  they are aware.

2. Speed was kept, while the distance was recalculated to correspond with the speed. The distance decreases from 9 to 8.4km in comparison with the original data.

When doing this, the detected pace of intervals corresponds with the actual pace for both of the edits. E.g. when recalculating speed - 20min pace detected and actual = 5:48 min/km
When recalculating distance -  20min pace detected and actual = 6:17 min/km

In order to check which one of the 2 is correct, I recreated the gps track in routeyou.com. Distance for the route was 9km on routeyou, which corresponds with the first data edit, where speed was recalculated and distance was kept.

I used an online calculator for the distance between lat-long coordinates as well. This also confirms that distance data are correct.

I will edit the speed data of all my running files (lucklily I just started running, so no big deal).
I was wondering if in future versions of GC it wouldn't be better to calculate all pace data based on distance and time, instead of using the speed data?

Kind regards,

Nigel

**Comment by nigelvdv** [comment]
Update: I tried recalculating speed based on distance and time. Detected paces and actual paces were very similar in comparison with the original data, unfortunately this introduced some speed spikes up to 30km/h...

As an alternative I tried something else. I uploaded my original fit file from my garmin edge 800 to strava, exported it once as a gpx and once as a tcx and imported both of them to GoldenCheetah. Both the gpx and tcx import gave me equal detected and actual paces! The gpx import did result in some speed spikes, but the tcx import just looks great. Detected pace seems reliable, long term metric trends are fine, no speed spikes,... Problem solved I guess.

Below you can see the CV curves for:
Pink: the original file (with unreliable detected paces)
Blue: the original file where the speed was recalculated based on distance and time (reliable detected paces with speed spikes)
Yellow: strava gpx import (reliable detected paces with speed spikes)
Red: strava tcx import (reliable detected paces without speed spikes)

![data edits for detected-actual pace](https://cloud.githubusercontent.com/assets/14836910/10134442/fc62014a-65e5-11e5-9f88-49af9b3d563a.png)

Kind regards,

Nigel

**Comment by amtriathlon** [comment]
Interesting Nigel, can you verify if the strava tcx comes with speed or upload that file?

The FIT file came with both data, distance and speed per sample, they are imported to GC as they come just converted to km and km/h.

The TCX file can have speed, in which case it is imported as it comes just converted to km/h, or may have not, in which case it is derived from distance so it is ensured to match it.

It should be easy to add a "Fix Speed" tool to replace the provided speed with one derived from distance (I already build a basic one: https://github.com/amtriathlon/GoldenCheetah/commit/8d3d12120f8d5bf169a6acea35c218c3bb6b9330), but as you found the problem are the speed spikes, it seems Strava did some smoothing job on distance data which helps to avoid them.

**Comment by nigelvdv** [comment]
Hi,

The tcx file seems to come with speed data (in m/s it seems), while the gpx file only has the coordinates and timestamps.

The speed data samples are always increasing or decreasing in discrete steps it seems, to be more specific always 0.1, 0.2, 0.3, ... m/s. So strava isn't just recalculating distance and time into speed... The end result seems realistic for my runs however, so they seem to be doing something right! Especially for runs, where gps data are always somewhat flakey.

Via dropbox you can find the tcx and gpx files.

The gpx file: 
https://www.dropbox.com/s/ezysergyr0je7l1/48%20-%20Run%20-garmin-strava.gpx?dl=0

The tcx file:
https://www.dropbox.com/s/w79lsmqi7s6tkpr/48-run%20-garmin-strava.tcx?dl=0

Kind regards,

Nigel

**Comment by amtriathlon** [comment]
Nigel, the Fix Speed from Distance in the next version will allow to match speed to incremental distance with optional smoothing via a Moving Average filter to lower speed spikes, in your sample file using 5 sec gives similar results to Strava. The tool can be configured to run automatically on file imports.
Cheers and thank for your support.
