### ISSUE TITLE
Add - virtual power for Elite Turbo Muin 2015

### ISSUE THREAD

**Issue by piotrekowalski** [GoldenCheetah/GoldenCheetah#1575]
2013 version of this trainer is already added.
But my new version 2015 shows different values.

Here is working equation, similar curve was added in Zwift.
https://support.zwift.com/hc/en-us/community/posts/202185169-Adding-zPower-for-Elite-Turbo-Muin

p = 0,0001745 \* v ^4 - 0,002527 \* v ^3 + 0,651 \* v ^2 - 8,512 \* v + 51,468

or simpler version:

p = 0,02 \* v ^3 + 0,356 \* v ^2 + 8,979 \* v + 47,433

This will give greater value:

150W @ 20kmh instead of 100W (vs. 2013)
270W @ 25kmh instead of 210W (vs. 2013)
450W @ 30kmh instead of 380W (vs. 2013)

much closer to this graph:
http://cdn.elite-it.com/sites/default/files/imagegallery/turbo-muin-graphics-cadence-speed_0.jpg

**Comment by toddan80** [comment]
Is there any possibility to get turbo muin 2015 in the next build?
I'm willing to test and report so it's bug free for 4.0 milestone ;)
