### ISSUE TITLE
Crash while downloading, Joule GPS+, Mac ElCapitan

### ISSUE THREAD

**Issue by portig** [GoldenCheetah/GoldenCheetah#1581]
When downloading the rides from my new Joule GPS+, GoldenCheetah finds 15 activities. Downloading these, it consistently (after several attempts) crashes while processing activity 14. Below is the crash report (attaching it did not work):

Cyclist: "Harald"

Version Info

Build date: Aug 14 2015 23:37:51
Build id: 3200
Version: 3.2.0
DB Schema: 115
Metrics: 259
OS: Mac OS X 10.11
QT	5.4.2
QWT	6.1.1
GCC	4.2.1
SRMIO	yes
OAUTH	yes
D2XX	yes
QWTPLOT3D	0.3.1
KML	none
ICAL	1.0
USBXPRESS	none
LIBUSB	yes
Wahoo API	none
VLC	none
VIDEO	quicktime
SAMPLERATE	0.1.8
SSL	yes

Metric Log

Athlete Directory - Activities

..	Sun Oct 4 22:06:03 2015
.	Wed Sep 30 19:59:59 2015
2015_09_30_16_24_28.json	Wed Sep 30 19:59:58 2015
2015_09_26_09_22_24.json	Sun Sep 27 22:29:59 2015
Athlete Directory - Cache

..	Sun Oct 4 22:06:03 2015
rideDB.json	Sun Oct 4 16:47:03 2015
.	Wed Sep 30 19:59:59 2015
2015_09_30_16_24_28.cpx	Wed Sep 30 19:59:59 2015
2015_09_26_09_22_24.cpx	Sun Sep 27 22:29:59 2015
Athlete Directory - Config

..	Sun Oct 4 22:06:03 2015
analysis-layout.xml	Sun Oct 4 16:47:03 2015
charts.xml	Sun Oct 4 16:47:03 2015
routes.xml	Sun Oct 4 16:47:03 2015
namedsearches.xml	Sun Oct 4 16:47:02 2015
home-layout.xml	Wed Sep 30 20:52:00 2015
.	Wed Sep 30 20:51:59 2015
autoimport.xml	Wed Sep 30 20:15:06 2015
hr.zones	Wed Sep 30 20:15:06 2015
metadata.xml	Wed Sep 30 20:15:06 2015
run-pace.zones	Wed Sep 30 20:15:06 2015
avatar.png	Wed Sep 30 20:15:05 2015
power.zones	Wed Sep 30 20:15:05 2015
swim-pace.zones	Sun Sep 27 22:27:54 2015
Athlete Directory - Workouts

..	Sun Oct 4 22:06:03 2015
.	Sun Sep 27 22:27:54 2015
Athlete Directory - Imports

..	Sun Oct 4 22:06:03 2015
.	Wed Sep 30 19:59:58 2015
28d91111-4d28-462a-ad19-15ba89868d6a_2015_09_30_16_24_28.fit	Wed Sep 30 19:59:58 2015
401ea541-ec35-4402-a705-2f4cea8bfad0_2015_09_26_09_22_24.fit	Sun Sep 27 22:29:59 2015
Athlete Directory - Downloads

.	Sun Oct 4 22:10:51 2015
2015_09_17_21_26_23.bin2	Sun Oct 4 22:08:05 2015
..	Sun Oct 4 22:06:03 2015
All Settings

AKDeviceUnlockState	false
AppleActionOnDoubleClick	Minimize
AppleAntiAliasingThreshold	4
AppleCollationOrder	root
AppleICUDateFormatStrings	
AppleICUTimeFormatStrings	
AppleKeyboardUIMode	0
AppleLanguages	
AppleLocale	en_US
AppleMeasurementUnits	Inches
AppleMetricUnits	false
AppleMiniaturizeOnDoubleClick	true
AppleScrollAnimationEnabled	true
CALTPOWER	255:0:255
CANTISS	0:255:255
CAPOWER	255:0:255
CATISS	255:0:255
CBALANCELEFT	178:0:0
CBALANCERIGHT	128:0:50
CCALACTUAL	0:255:0
CCALCELL	255:255:255
CCALCURRENT	178:215:255
CCALHEAD	230:230:230
CCALPLANNED	255:255:0
CCALTODAY	0:255:255
CCHROME	229:229:229
CDIAL	160:160:164
CHHB	0:127:204
CLPS	0:255:255
CLTE	0:255:255
CNPOWER	255:0:255
CO2HB	209:5:114
COLORACCEL	0:255:255
COLORAEROEL	0:255:0
COLORAEROVE	0:0:255
COLORALTITUDESHADE	192:192:192
COLORALTITUTDE	160:160:164
COLORBIKESCORE	160:160:164
COLORCADENCE	0:204:204
COLORCALENDARTEXT	0:0:0
COLORCORETEMP	255:173:92
COLORCP	142:40:0
COLORDAILYSTRESS	255:0:0
COLORGCT	255:144:0
COLORGEAR	255:144:0
COLORGRID	232:219:150
COLORHEARTRATE	255:0:0
COLORINTERVALHIGHLIGHTER	182:73:38
COLORLOAD	255:255:0
COLORLTS	0:255:0
COLORPLOTBACKGROUND	255:240:165
COLORPLOTMARKER	70:137:102
COLORPLOTSELECT	182:73:38
COLORPLOTTHUMBNAIL	160:160:164
COLORPLOTTITLE	0:0:0
COLORPLOTTRACKER	182:73:38
COLORPOWER	85:90:127
COLORRCAD	255:144:0
COLORRIDEPLOTBACKGROUND	255:240:165
COLORRIDEPLOTSYMBOLS	70:137:102
COLORRIDEPLOTXAXIS	70:137:102
COLORRIDEPLOTYAXIS	70:137:102
COLORRVERT	255:144:0
COLORSB	0:0:0
COLORSMO2	0:137:119
COLORSPEED	0:255:0
COLORSTS	0:0:255
COLORTEMPERATURE	255:255:0
COLORTHB	163:68:2
COLORTORQUE	255:0:255
COLORTRAINPLOTBACKGROUND	255:240:165
COLORTRENDPLOTBACKGROUND	255:240:165
COLORTSS	0:255:0
COLORWINDSPEED	0:128:0
COLORZONE1	255:0:255
COLORZONE10	160:160:164
COLORZONE2	42:0:255
COLORZONE3	0:170:255
COLORZONE4	0:255:128
COLORZONE5	85:255:0
COLORZONE6	255:213:0
COLORZONE7	255:0:0
COLORZONE8	160:160:164
COLORZONE9	160:160:164
CPOPUP	192:192:192
CPOPUPTEXT	255:255:255
CRIDECP	142:40:0
CRIDEGROUP	236:246:255
CRPS	255:0:255
CRTE	255:0:255
CSLOPE	0:255:0
CSPINSCANLEFT	160:160:164
CSPINSCANRIGHT	0:255:255
CTILEBAR	160:160:164
CTILEBARSELECT	255:255:0
CTOOLBAR	237:237:237
CWBAL	142:40:0
CXPOWER	255:0:255
Country	US
HRCOLORZONE1	255:0:255
HRCOLORZONE10	160:160:164
HRCOLORZONE2	42:0:255
HRCOLORZONE3	0:170:255
HRCOLORZONE4	0:255:128
HRCOLORZONE5	85:255:0
HRCOLORZONE6	255:213:0
HRCOLORZONE7	255:0:0
HRCOLORZONE8	160:160:164
HRCOLORZONE9	160:160:164
Harald/LTSdays	42
Harald/PMshowSBtoday	0
Harald/STSdays	7
Harald/bavigator/headingwidths	0|100|100|
Harald/dv/googlecalid	
Harald/dv/type	0
Harald/dv/url	
Harald/height	1.69925997447968
Harald/intervals/discovery	57
Harald/ltmwindow/autofilters	Workout Code|Sport
Harald/ltmwindow/lastDateRange	{00000000-0000-0000-0000-000000000012}
Harald/navigator/groupby	-1
Harald/navigator/headings	*|Workout Code|Date|
Harald/navigator/sortby	2
Harald/navigator/sortbyorder	0
Harald/nickname	Harald
Harald/safeexit	false
Harald/splitter/LTM/hide	true
Harald/splitter/LTM/hide/0	false
Harald/splitter/LTM/hide/1	false
Harald/splitter/LTM/hide/2	false
Harald/splitter/LTM/hide/3	true
Harald/splitter/analysis/hide	true
Harald/splitter/analysis/hide/0	false
Harald/splitter/analysis/hide/1	true
Harald/splitter/analysis/hide/2	false
Harald/splitter/analysis/hide/3	true
Harald/splitter/diary/hide	true
Harald/splitter/diary/hide/0	false
Harald/splitter/diary/hide/1	false
Harald/splitter/diary/hide/2	true
Harald/splitter/train/hide	true
Harald/splitter/train/hide/0	false
Harald/splitter/train/hide/1	false
Harald/splitter/train/hide/2	false
Harald/splitter/train/hide/3	false
Harald/tp/type	0
Harald/tp/url	http://www.trainingpeaks.com
Harald/unit	Imperial
Harald/upgradesuccess/folder	true
Harald/versionused	3200
Harald/wbaltau	300
Harald/webcal_url	
Harald/wi/url	http://wbsapi.withings.net/
LTS	LTS
LTSname	Long Term Stress
MultipleSessionEnabled	true
NSAutomaticDashSubstitutionEnabled	true
NSAutomaticQuoteSubstitutionEnabled	true
NSAutomaticSpellingCorrectionEnabled	true
NSCloseAlwaysConfirmsChanges	true
NSNavPanelFileLastListModeForOpenModeKey	2
NSNavPanelFileLastListModeForSaveModeKey	1
NSNavPanelFileListModeForOpenMode2	2
NSNavPanelFileListModeForSaveMode2	1
NSNavPanelSidebarKeyForOpen	
NSNavPanelSidebarKeyForSave	
NSNavRecentPlaces	
NSNavSortOrder	
NSNavSortOrder_10/6	
NSPersonNameDefaultDisplayNameOrder	0
NSPersonNameDefaultShortNameFormat	0
NSPersonNameDefaultShouldPreferNicknamesPreference	0
NSPreferredSpellServerLanguage	en
NSPreferredWebServices	
NSUserDictionaryReplacementItems	
NSUserReplacementItems	
NavPanelFileListModeForOpenMode	2
NavPanelFileListModeForSaveMode	1
NavPanelSpotlightSearchScopeMode	2
SB	SB
SBname	Stress Balance
SGTRecentFileSearches	
STS	STS
STSname	Short Term Stress
WebAutomaticSpellingCorrectionEnabled	true
antialias	true
chrome	Flat
com/apple/AppleModemSettingTool/LastCountryCode	US
com/apple/ColorSync/Devices	
com/apple/CommonPanels/CalibrateDisplay/identifier-7BD8CC3E	com.apple.ColorSyncCalibrator
com/apple/CommonPanels/CalibrateDisplay/seed	-1120508567
com/apple/DictionaryServices	
com/apple/TimeZonePref/Last_Selected_City	
com/apple/keyboard/fnState	false
com/apple/mouse/tapBehavior	3
com/apple/preferences/timezone/selected_city	
com/apple/springing/delay	1
com/apple/springing/enabled	true
com/apple/swipescrolldirection	true
com/apple/trackpad/enableSecondaryClick	true
com/apple/trackpad/fiveFingerPinchSwipeGesture	2
com/apple/trackpad/fourFingerHorizSwipeGesture	2
com/apple/trackpad/fourFingerPinchSwipeGesture	2
com/apple/trackpad/fourFingerVertSwipeGesture	2
com/apple/trackpad/momentumScroll	true
com/apple/trackpad/pinchGesture	true
com/apple/trackpad/rotateGesture	true
com/apple/trackpad/scaling	2.5
com/apple/trackpad/scrollBehavior	2
com/apple/trackpad/threeFingerDragGesture	true
com/apple/trackpad/threeFingerHorizSwipeGesture	0
com/apple/trackpad/threeFingerTapGesture	0
com/apple/trackpad/threeFingerVertSwipeGesture	0
com/apple/trackpad/trackpadCornerClickBehavior	0
com/apple/trackpad/twoFingerDoubleTapGesture	1
com/apple/trackpad/twoFingerFromRightEdgeSwipeGesture	3
com/apple/trackpad/version	5
com/apple/updatesettings_did_disable_ftp	true
crankLength	170
dataprocess/fixgaps/stop	1
dataprocess/fixgaps/tolerance	1
dataprocess/fixhrspikes/max	170
dataprocess/fixspikes/max	700
dataprocess/fixspikes/variance	700
dataprocess/poweradjust/adjustment	0
dataprocess/torqueadjust/adjustment	0 nm
devices	0
dp/Add Torque Values/apply	Manual
dp/Adjust Power Values/apply	Manual
dp/Adjust Torque Values/apply	Manual
dp/Estimate Power Values/apply	Manual
dp/Fix Elevation errors/apply	Manual
dp/Fix GPS errors/apply	Manual
dp/Fix Gaps in Recording/apply	Manual
dp/Fix HR Spikes/apply	Manual
dp/Fix Power Spikes/apply	Manual
dp/Set SmO2/tHb from Speed and Cadence/apply	Manual
elevationHysteresis	3.
font/calendar	Abadi MT Condensed Extra Bold,10,-1,5,50,0,0,0,0,0
font/calendarsize	9
font/chartlabels	Abadi MT Condensed Extra Bold,10,-1,5,50,0,0,0,0,0
font/chartlabelssize	9
font/chartmarkers	Abadi MT Condensed Extra Bold,10,-1,5,50,0,0,0,0,0
font/chartmarkerssize	9
font/default	Abadi MT Condensed Extra Bold,10,-1,5,50,0,0,0,0,0
font/defaultsize	13
font/titles	Abadi MT Condensed Extra Bold,10,-1,5,50,0,0,0,0,0
font/titlessize	11
garminHWMark	25
garminSmartRecord	2
homedirectory	/Users/Harald/Library/GoldenCheetah
lang	en
linewidth	0.5
mainwindow/geometry	���
mainwindow/lastDownloadDevice	Joule 1.0, GPS or GPS+
mainwindow/lastDownloadPort	D2XX: PowerTap Joule GPS+
mainwindow/lastImportPath	/Users/Harald/Documents/CycleOps/Joule GPS+.power/data
mainwindow/lastOpened	Harald
mainwindow/state	
pace	true
rideBG	false
show/tabbar	false
train/multi	false
warnexit	true
wbal/formula	diff
wheelsize	2099
workoutDir	/Users/Harald/Library

**Comment by liversedge** [comment]
fixed in 3.3
