### ISSUE TITLE
Curves erratic when Compare Mode is ON

### ISSUE THREAD

**Issue by WaldoPepper** [GoldenCheetah/GoldenCheetah#1586]
Hi, I experience an erratic display of the HR, Speed, etc. curves when I switch on Compare Mode (see screenshot). All data was sync from TrainingPeaks. Initially it was shared with TrainingPeaks via Garmin Connect (recorded with an Edge 1000). Smooth was identically set to "2" in both mode ON and OFF.

Other data synced from TP (e.g. those originally coming from Polar Flow by means of an *,tcx file) shows up fine in Compare Mode.

I tried to add the *.jason file to this issue, but GitHub wont let me.... :-(

![compare off](https://cloud.githubusercontent.com/assets/15046307/10388840/ebe9717a-6e5c-11e5-9e39-ff94cb898a72.PNG)
![compare on](https://cloud.githubusercontent.com/assets/15046307/10388848/fbc18880-6e5c-11e5-9b60-4ba4f6f59bd4.PNG)

**Comment by liversedge** [comment]
What version are you running?

**Comment by WaldoPepper** [comment]
Version 3.1.0

I am experiencing the same behaviour when I slide the Smooth slider (especially in the 3-8 region).

**Comment by liversedge** [comment]
I believe this is fixed in 3.2

**Comment by liversedge** [comment]
But do check smart recording and gaps are fixed.

**Comment by WaldoPepper** [comment]
Just checked it in 3.2.0

It's looking good! I think we can close this one.

One comment, though: it seems that when I sync with TrainingPeaks in 3.2.0 even activities that are not finished/contain no data are synced now. In the past these where skipped (IIRC with a message "Not enough data found" or something similar).

With this new sync behaviour I think an option "skip empty activities" when syncing with TP is needed.

**Comment by liversedge** [comment]
Yeah.. some folks wanted to metadata.

**Comment by WaldoPepper** [comment]
.....and some (including me) do not ;-)

Should I open the suggestion for an additional option as an separate issue?
