### ISSUE TITLE
New selection option "select finished activities only" for TrainingPeaks sync dialog

### ISSUE THREAD

**Issue by WaldoPepper** [GoldenCheetah/GoldenCheetah#1587]
When syncing with TrainingPeaks in GoldenCheetah 3.2.0 even activities that are not finished/contain no data are now synced.

In the past these where skipped (IIRC with a message "Not enough data found" or something similar).

With this new sync behaviour I think besides "select all" a new selection option "select finished activities only" is needed in the TrainingPeaks sync dialog (unfinished activities have a 00:00:00 time and duration stamp).

**Comment by amtriathlon** [comment]
Closed since TrainingPeaks sync was deprecated.
