### ISSUE TITLE
Tacx i-flow support

### ISSUE THREAD

**Issue by tnikolai2** [GoldenCheetah/GoldenCheetah#1590]
It must be like fortius but i cant add i-flow trainer.

**Comment by tnikolai2** [comment]
i try to compile but error

g++ -Wl,-s -mthreads -Wl,-subsystem,windows -o release\GoldenCheetah.exe object_script.GoldenCheetah.Release  -L"d:\coding\qt\lib" -lmingw32 -lqtmain release\windowsico_res.o ../qwt/lib/libqwt.a -lm -lz -lws2_32 -lQtWebKit4 -lQtScript4 -lQtSvg4 -lQtSql4 -lQtXml4 -lQtGui4 -lQtNetwork4 -lQtCore4



d:/coding/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: cannot find -lz
collect2.exe: error: ld returned 1 exit status
Makefile.Release:903: recipe for target 'release\GoldenCheetah.exe' failed

**Comment by liversedge** [comment]
Please use the developer forums for help with compiling etc.
They are here: https://groups.google.com/forum/#!forum/golden-cheetah-developers
