### ISSUE TITLE
QDate.fromString()'s bug in some locales

### ISSUE THREAD

**Issue by jinseokl** [GoldenCheetah/GoldenCheetah#1592]
I've experienced some problem in importing file to GC, also I found that many users in Korea have same problem.
I think the root cause is QDate.fromString()'s bug in parsing strings in some specific locales.
So I slightly modified RideImportWizard.cpp file, replacing "dd MMM yyyy" into "dd MM yyyy" and then the problem did not occur any more.
So I gently request GC developers to apply this change if there is not an issue about changing the date format.

Best Regards,
Jinseok

**Comment by Joern-R** [comment]
Dear Jinseok,

thanks for the report - just checked the documentation - using Locale dependent formats when "working" with the dates (converting from/toString) like in RideImportWizard seems to need special attention in QT (or just using a format which is not locale-sensitive like MM). 

Did you notice any other places where the Locale may cause problems, does the format work fine in case of simple output/display fields ?

The only other place I found where QDate.fromString(...MMM ...) is used is the the Compare Pane - here it's used when sorting the date column.

Can you please check/confirm if the pure output/display formats work find in Korean,
And also if the Compare Pane "Sorting by dates" is affected by the problem as well or not.

 Thanks and kind regards.
Joern

**Comment by jinseokl** [comment]
Dear Joern,

Thank you for your kind reply, let me check other places after work and report again.

Thank you.
Jinseok

**Comment by jinseokl** [comment]
Sorry for the late report, I was so busy these days.
Anyway, I tested sorting the date in both ComparePane.cpp without any modification and with replacing 'MMM' into 'MM' and both worked well in my environment.

Thank you,
Jinseok

**Comment by Joern-R** [comment]
Thanks Jinseok.

@liversedge - to make sure to not run into any locale issues related to "toString" in date formats with "MMM" shall we move to "MM" which is locale independent in those 2 locations - RideImportWizard and ComparePane Sorting ? - Just let me know - I will do the changes then.

Joern

**Comment by liversedge** [comment]
MM still works for other locales ? If so, then please feel free to change.

**Comment by Joern-R** [comment]
MM is not considering locale.
Then I will do the change and test for sure ;-)

http://doc.qt.io/qt-5/qdate.html#toString

2015-10-21 9:47 GMT+02:00 Mark Liversedge <notifications@github.com>:

**Comment by liversedge** [comment]
Hmm. I am not sure about this, the date format is "01 Jan 2015" which looking at the docs is MMM since MM is the month number ?

But if you are testing and it works ... its a big change to make at this point !!! 
We definitely need to test it on QT4 and QT5 !!!

**Comment by Joern-R** [comment]
No sure if I get your concern. We are currently using "MMM" in
RideImportWizard in "toString" and "fromString" - for the UI. So the
current displayed text is locale dependent.
Changing to "MM" would make it local unaware - which should have less
dependencies on QT version,...

And I will only change the 2 places where we handle dates special by
writing and re-reading them from the UI. In all other places we should not
change the format since
there is no need.

Let's give it a try and check.

2015-10-21 12:09 GMT+02:00 Mark Liversedge <notifications@github.com>:

**Comment by amtriathlon** [comment]
I think the change is safe, but a potential confusion may arise for
north-american users between DD MM YYYY and MM DD YYYY, perhaps YYYY MM DD
could avoid this issue.

**Comment by Joern-R** [comment]
Good hint - thanks - I have now applied ISO 8601 format - which should fit around the globe
and is nicely supported by QT (YYYY-MM-DD).

**Comment by Joern-R** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/98cb17b12456c9c86c3e1329f43befded33f6bb3
