### ISSUE TITLE
Let's extend Tacx Vortex Support to non-Smart Version

### ISSUE THREAD

**Issue by flyingflo** [GoldenCheetah/GoldenCheetah#1598]
Hi,

I just tried @stschake 's new Tacx Vortex Support #1213 with my Tacx Vortex non-Smart. In other words, I have the old Version called iVortex. It was not detected by the "Add Device Wizard". So there seems to be some difference to the Vortex Smart.

Can you give me any hint on how to dig into that?

thx, Florian

**Comment by liversedge** [comment]
It is not possible.

http://www.tacx.com/en/service/analyse/what-heart-rate-belt-can-i-use-and-is-it-included

The url above is regarding fe-c support, despite the name !

**Comment by stschake** [comment]
@liversedge: you might have fired too quick here ;)

This is in regards to the propietary Tacx ANT protocol that I implemented back then in #1213 when Tacx didn't support FE-C yet.

I did have a look at the Tacx software I looked at when REing that, and there is indeed a mention of a VortexDisplay. Did your non-smart Vortex come with a display control unit?

**Comment by liversedge** [comment]
Happy to reopen if you have code that will do this.

**Comment by flyingflo** [comment]
Yes, my Vortex has a display control unit. It can either control the Vortex brake directly, or it can be used as a remote control for the TTS software from Tacx. Older versions of TTS required the display to relay data to (and probably from) the brake. Some time ago, with a firmware and TTS update, it became optional.

**Comment by flyingflo** [comment]
@liversedge: The Tacx website says, that the iVortex will not get an upgrade to support FE-C. But that might not necessarily mean that GoldenCheetah can not support the Vortex ANT protocol. Anyways, I want to try it.

**Comment by liversedge** [comment]
Happy to reopen if Stefan thinks he can reverse engineer the secret Tacx protocol

**Comment by flyingflo** [comment]
Good news: I looked into the device detection code and guessed it might be interesting to reorder the devices in the detection window.
My Tacx Vortex was detected, without any changes to the source, yet. Now I have to try if it actually works.

**Comment by flyingflo** [comment]
Thx for your work, guys!

@liversedge Keep the issue closed, it works, basically!
@stschake These Vortex models seem to use the same protocol. The head unit can also be used to send target power values and display current values.

Anyways, it does not work reliably. But I think my problems are not related to the ANT protocol, but to the ANT USB adapter handling. I have a "usb2" and GC accesses it through libusb. It seems to suffer from communication problems like:

```
lost info for channel 0 
** CLOSING CHANNEL 0 ** 
usb_interrupt_write Error writing [ -110 ]:  could not detach kernel driver from interface 0: No data available 
```

and 

```
lost info for channel 0 
** CLOSING CHANNEL 0 ** 
usb_interrupt_write Error writing [ -110 ]:  No error 
```

That's a different story.

**Comment by liversedge** [comment]
you on windows or linux ?
