### ISSUE TITLE
Heart rate in activity-charts in percent of max heart rate not in bpm

### ISSUE THREAD

**Issue by DanRom89** [GoldenCheetah/GoldenCheetah#1606]
Hi there,

is it possible to show the heart rate in charts in percent of maximum heart rate and not in bpm.

**Comment by Joern-R** [comment]
Please use the forums for help questions: https://groups.google.com/forum/#!forum/golden-cheetah-users
Specific on your question. It's not possible up to 3.2 - it will be possible by user formulas in 3.3 coming end of 2015
