### ISSUE TITLE
Bug - Pace zones problem - not updating for Run

### ISSUE THREAD

**Issue by peterjoo** [GoldenCheetah/GoldenCheetah#1611]
I think there is something wrong with updating the pace zones for running (under Tools/Options/Athletes/Pace Zones). There isn't seem to be a way to update the changes. Normally, a little button called "Update" would pop up on the right but it doesn't appear.

I added and deleted by using the little "plus" and "minus" buttons and now the entire "Pace Zones" on the Summary page is gone.

Using version 3.2.0 on Win7

**Comment by amtriathlon** [comment]
This is not a bug, just the update of CV config is not yet implemented in v3.2 for Pace Zones.
WRT disappearing zones beware the default starting date for a new added CV is today, if you want it to apply for pre-existing workout you need to change today for a previous date.
