### ISSUE TITLE
GC blocked while loading tracker of a range of dates

### ISSUE THREAD

**Issue by arturogpedraz** [GoldenCheetah/GoldenCheetah#1637]
I created a pair of range dates in the trends tab, but when i click on the tracker sub-tab, program get freezed.

All the other tabs, and the default date ranges load properly.  

== CRASH REPORT == (cannot attach it)

Version Info

Build date: Aug 14 2015 23:37:51
Build id: 3200
Version: 3.2.0
DB Schema: 115
Metrics: 259
OS: Mac OS X 10.11
QT	5.4.2
QWT	6.1.1
GCC	4.2.1
SRMIO	yes
OAUTH	yes
D2XX	yes
QWTPLOT3D	0.3.1
KML	none
ICAL	1.0
USBXPRESS	none
LIBUSB	yes
Wahoo API	none
VLC	none
VIDEO	quicktime
SAMPLERATE	0.1.8
SSL	yes

Metric Log

METRIC REFRESH STARTS: lun ago 24 00:51:46 2015
COMMIT: lun ago 24 00:51:46 2015
OPTIMISE: lun ago 24 00:51:46 2015
SIGNAL DATA CHANGED: lun ago 24 00:51:46 2015
METRIC REFRESH ENDS: lun ago 24 00:51:46 2015
Athlete Directory - Activities

2015_11_03_19_36_24.json	sáb nov 7 14:42:37 2015
2015_11_07_11_02_08.json	sáb nov 7 14:29:49 2015
.	sáb nov 7 14:17:34 2015
2015_10_27_17_36_48.json	lun nov 2 17:44:12 2015
2015_10_27_17_41_24.json	lun nov 2 17:44:12 2015
2015_10_25_09_56_18.json	lun oct 26 20:29:11 2015
2015_10_22_20_13_57.json	jue oct 22 23:13:50 2015
2015_10_20_20_27_12.json	jue oct 22 23:13:49 2015
2015_09_12_14_19_07.json	lun sept 14 00:52:21 2015
2015_09_13_18_41_50.json	lun sept 14 00:52:21 2015
2015_08_30_11_48_06.json	dom ago 30 13:20:18 2015
2015_08_26_20_24_54.json	jue ago 27 03:16:21 2015
2015_08_25_18_13_58.json	mar ago 25 22:19:33 2015
2015_08_24_18_51_06.json	mar ago 25 02:07:04 2015
2015_08_13_20_31_00.json	mar ago 25 02:07:03 2015
2015_08_22_08_00_53.json	mar ago 25 02:07:03 2015
..	lun ago 24 00:54:17 2015
Athlete Directory - Cache

rideDB.json	sáb nov 7 14:42:38 2015
2015_11_03_19_36_24.cpx	sáb nov 7 14:42:37 2015
2015_11_07_11_02_08.cpx	sáb nov 7 14:29:50 2015
.	sáb nov 7 14:17:34 2015
2015_08_22_08_00_53.cpx	mié nov 4 09:27:58 2015
2015_10_25_09_56_18.cpx	mié nov 4 09:27:57 2015
2015_10_27_17_36_48.cpx	lun nov 2 17:44:12 2015
2015_10_27_17_41_24.cpx	lun nov 2 17:44:12 2015
2015_10_22_20_13_57.cpx	jue oct 22 23:13:50 2015
2015_10_20_20_27_12.cpx	jue oct 22 23:13:49 2015
2015_09_12_14_19_07.cpx	lun sept 14 00:52:21 2015
2015_09_13_18_41_50.cpx	lun sept 14 00:52:21 2015
2015_08_30_11_48_06.cpx	dom ago 30 13:20:18 2015
2015_08_26_20_24_54.cpx	jue ago 27 03:16:21 2015
2015_08_25_18_13_58.cpx	mar ago 25 22:19:33 2015
2015_08_24_18_51_06.cpx	mar ago 25 02:07:04 2015
2015_08_13_20_31_00.cpx	mar ago 25 02:07:03 2015
..	lun ago 24 00:54:17 2015
Athlete Directory - Config

seasons.xml	sáb nov 7 15:23:15 2015
.	sáb nov 7 15:11:57 2015
analysis-layout.xml	sáb nov 7 14:42:38 2015
charts.xml	sáb nov 7 14:42:38 2015
home-layout.xml	sáb nov 7 14:42:38 2015
routes.xml	sáb nov 7 14:42:38 2015
namedsearches.xml	sáb nov 7 14:42:37 2015
autoimport.xml	mié nov 4 09:27:53 2015
avatar.png	mié nov 4 09:27:53 2015
hr.zones	mié nov 4 09:27:53 2015
metadata.xml	mié nov 4 09:27:53 2015
power.zones	mié nov 4 09:27:53 2015
run-pace.zones	mié nov 4 09:27:53 2015
diary-layout.xml	mar nov 3 21:03:13 2015
..	lun ago 24 00:54:17 2015
Athlete Directory - Workouts

..	lun ago 24 00:54:17 2015
.	lun ago 24 00:54:16 2015
Athlete Directory - Imports

.	sáb nov 7 14:17:33 2015
949727320_2015_11_07_11_02_08.fit	sáb nov 7 14:17:33 2015
946508932_2015_11_03_19_36_24.fit	mar nov 3 20:53:00 2015
3528828_2015_10_27_17_36_48.fit	mar oct 27 18:32:16 2015
939839438_2015_10_27_17_41_24.fit	mar oct 27 18:32:16 2015
939072013_2015_10_26_19_35_44.fit	lun oct 26 22:05:48 2015
937642584_2015_10_25_09_56_18.fit	lun oct 26 08:41:24 2015
3486857_2015_10_20_20_27_12.fit	jue oct 22 23:05:08 2015
3499420_2015_10_22_20_13_57.fit	jue oct 22 23:05:08 2015
896223059_2015_09_12_14_19_07.fit	lun sept 14 00:18:16 2015
897678095_2015_09_13_18_41_50.fit	lun sept 14 00:18:16 2015
882183928_2015_08_30_11_48_06.fit	dom ago 30 13:12:59 2015
3217206_2015_08_26_20_24_54.fit	jue ago 27 03:05:09 2015
877486165_2015_08_25_18_13_58.fit	mar ago 25 21:50:40 2015
873888569_2015_08_22_08_00_53.fit	mar ago 25 02:05:18 2015
3183932_2015_08_13_20_31_00.fit	mar ago 25 01:52:12 2015
876451195_2015_08_24_18_51_06.fit	lun ago 24 21:34:46 2015
..	lun ago 24 00:54:17 2015
2015_08_08_08_19_44.fit	jue ago 13 18:45:54 2015
Athlete Directory - Downloads

..	lun ago 24 00:54:17 2015
.	lun ago 24 00:54:16 2015
All Settings

AKDeviceUnlockState	false
AppleActionOnDoubleClick	Maximize
AppleAntiAliasingThreshold	4
AppleLanguages	es
AppleLocale	es_ES
AppleMiniaturizeOnDoubleClick	false
AppleTextDirection	0
Arturo/LTSdays	42
Arturo/PMshowSBtoday	0
Arturo/STSdays	7
Arturo/bavigator/headingwidths	0|92|92|
Arturo/dv/googlecalid	
Arturo/dv/type	0
Arturo/dv/url	
Arturo/gc/url	http://race.goldencheetah.org
Arturo/height	1.71
Arturo/intervals/discovery	57
Arturo/ltmwindow/autofilters	Código Entrenamiento|Deporte
Arturo/ltmwindow/lastDateRange	{42e12153-fb20-43f8-97c4-097aa6841f40}
Arturo/navigator/groupby	-1
Arturo/navigator/headings	*|Código Entrenamiento|Fecha|
Arturo/navigator/sortby	4
Arturo/navigator/sortbyorder	1
Arturo/nickname	ARTURO
Arturo/safeexit	false
Arturo/splitter/LTM/hide	true
Arturo/splitter/LTM/hide/0	false
Arturo/splitter/LTM/hide/1	false
Arturo/splitter/LTM/hide/2	false
Arturo/splitter/LTM/hide/3	true
Arturo/splitter/LTM/hide/4	false
Arturo/splitter/LTM/hide/5	false
Arturo/splitter/LTM/sizes	
Arturo/splitter/analysis/hide	true
Arturo/splitter/analysis/hide/0	false
Arturo/splitter/analysis/hide/1	true
Arturo/splitter/analysis/hide/2	false
Arturo/splitter/analysis/hide/3	false
Arturo/splitter/analysis/sizes	
Arturo/splitter/diary/hide	true
Arturo/splitter/diary/hide/0	false
Arturo/splitter/diary/hide/1	false
Arturo/splitter/diary/hide/2	true
Arturo/splitter/train/hide	true
Arturo/splitter/train/hide/0	false
Arturo/splitter/train/hide/1	false
Arturo/splitter/train/hide/2	false
Arturo/splitter/train/hide/3	false
Arturo/strava_token	c365cd66463ec0e2b2bf515e4dba6d00b8057168
Arturo/tp/type	0
Arturo/tp/url	http://www.trainingpeaks.com
Arturo/unit	Metric
Arturo/upgradesuccess/folder	true
Arturo/versionused	3200
Arturo/wbaltau	300
Arturo/webcal_url	
Arturo/wi/url	http://wbsapi.withings.net/
Arturo/zeo/url	http://app-pro.myzeo.com:8080/
CALTPOWER	255:0:255
CANTISS	0:255:255
CAPOWER	255:0:255
CATISS	255:0:255
CBALANCELEFT	178:0:0
CBALANCERIGHT	128:0:50
CCALACTUAL	0:255:0
CCALCELL	255:255:255
CCALCURRENT	178:215:255
CCALHEAD	230:230:230
CCALPLANNED	255:255:0
CCALTODAY	0:255:255
CCHROME	229:229:229
CDIAL	160:160:164
CHHB	0:127:204
CLPS	0:255:255
CLTE	0:255:255
CNPOWER	255:0:255
CO2HB	209:5:114
COLORACCEL	0:255:255
COLORAEROEL	0:255:0
COLORAEROVE	0:0:255
COLORALTITUDESHADE	192:192:192
COLORALTITUTDE	160:160:164
COLORBIKESCORE	160:160:164
COLORCADENCE	0:204:204
COLORCALENDARTEXT	0:0:0
COLORCORETEMP	255:173:92
COLORCP	0:255:255
COLORDAILYSTRESS	255:0:0
COLORGCT	255:144:0
COLORGEAR	255:144:0
COLORGRID	65:65:65
COLORHEARTRATE	255:0:0
COLORINTERVALHIGHLIGHTER	0:0:255
COLORLOAD	255:255:0
COLORLTS	0:255:0
COLORPLOTBACKGROUND	52:52:52
COLORPLOTMARKER	0:255:255
COLORPLOTSELECT	0:0:255
COLORPLOTTHUMBNAIL	160:160:164
COLORPLOTTITLE	0:0:0
COLORPLOTTRACKER	0:0:255
COLORPOWER	255:255:0
COLORRCAD	255:144:0
COLORRIDEPLOTBACKGROUND	52:52:52
COLORRIDEPLOTSYMBOLS	0:255:255
COLORRIDEPLOTXAXIS	0:0:255
COLORRIDEPLOTYAXIS	255:0:0
COLORRVERT	255:144:0
COLORSB	0:0:0
COLORSMO2	0:137:119
COLORSPEED	0:255:0
COLORSTS	0:0:255
COLORTEMPERATURE	255:255:0
COLORTHB	163:68:2
COLORTORQUE	255:0:255
COLORTRAINPLOTBACKGROUND	0:0:0
COLORTRENDPLOTBACKGROUND	52:52:52
COLORTSS	0:255:0
COLORWINDSPEED	0:128:0
COLORZONE1	255:0:255
COLORZONE10	160:160:164
COLORZONE2	42:0:255
COLORZONE3	0:170:255
COLORZONE4	0:255:128
COLORZONE5	85:255:0
COLORZONE6	255:213:0
COLORZONE7	255:0:0
COLORZONE8	160:160:164
COLORZONE9	160:160:164
CPOPUP	192:192:192
CPOPUPTEXT	255:255:255
CRIDECP	255:0:0
CRIDEGROUP	236:246:255
CRPS	255:0:255
CRTE	255:0:255
CSLOPE	0:255:0
CSPINSCANLEFT	160:160:164
CSPINSCANRIGHT	0:255:255
CTILEBAR	160:160:164
CTILEBARSELECT	255:255:0
CTOOLBAR	237:237:237
CWBAL	255:0:0
CXPOWER	255:0:255
Country	ES
HRCOLORZONE1	255:0:255
HRCOLORZONE10	160:160:164
HRCOLORZONE2	42:0:255
HRCOLORZONE3	0:170:255
HRCOLORZONE4	0:255:128
HRCOLORZONE5	85:255:0
HRCOLORZONE6	255:213:0
HRCOLORZONE7	255:0:0
HRCOLORZONE8	160:160:164
HRCOLORZONE9	160:160:164
LTS	ELP
LTSname	Estrés a Largo Plazo
NSNavPanelFileLastListModeForOpenModeKey	1
NSNavPanelFileListModeForOpenMode2	1
NSNavRecentPlaces	
NSPersonNameDefaultDisplayNameOrder	0
NSPersonNameDefaultShortNameFormat	0
NSPersonNameDefaultShouldPreferNicknamesPreference	0
NSPreferredWebServices	
NSUserDictionaryReplacementItems	
NavPanelFileListModeForOpenMode	1
SB	BE
SBname	Balance de Estrés
STS	ECP
STSname	Estrés a Corto Plazo
antialias	true
chrome	Flat
com/apple/AppleModemSettingTool/LastCountryCode	ES
com/apple/ColorSync/Devices	
com/apple/TimeZonePref/Last_Selected_City	
com/apple/mouse/tapBehavior	1
com/apple/preferences/timezone/selected_city	
com/apple/springing/delay	0.5
com/apple/springing/enabled	true
com/apple/swipescrolldirection	true
com/apple/trackpad/enableSecondaryClick	true
com/apple/trackpad/fiveFingerPinchSwipeGesture	2
com/apple/trackpad/forceClick	true
com/apple/trackpad/fourFingerHorizSwipeGesture	2
com/apple/trackpad/fourFingerPinchSwipeGesture	2
com/apple/trackpad/fourFingerVertSwipeGesture	2
com/apple/trackpad/momentumScroll	true
com/apple/trackpad/pinchGesture	true
com/apple/trackpad/rotateGesture	true
com/apple/trackpad/scrollBehavior	2
com/apple/trackpad/threeFingerDragGesture	true
com/apple/trackpad/threeFingerHorizSwipeGesture	0
com/apple/trackpad/threeFingerTapGesture	0
com/apple/trackpad/threeFingerVertSwipeGesture	0
com/apple/trackpad/twoFingerDoubleTapGesture	1
com/apple/trackpad/twoFingerFromRightEdgeSwipeGesture	3
com/apple/trackpad/version	5
com/apple/updatesettings_did_disable_ftp	true
crankLength	170
dataprocess/fixgaps/stop	1
dataprocess/fixgaps/tolerance	1
dataprocess/fixhrspikes/max	220
dataprocess/fixspikes/max	1500
dataprocess/fixspikes/variance	1000
dataprocess/poweradjust/adjustment	0
dataprocess/torqueadjust/adjustment	0 nm
devices	0
dp/Agregar Valores de Par/apply	Manual
dp/Ajustar Valores de Par/apply	Manual
dp/Ajustar Valores de Potencia/apply	Manual
dp/Corregir GPS/apply	Manual
dp/Corregir Picos/apply	Manual
dp/Corregir errores de Altimetría/apply	Manual
dp/Corregir picos de FC/apply	Manual
dp/Establecer SmO2/tHb a partir de Velocidad y Cadencia/apply	Manual
dp/Estimar Valores de Potencia/apply	Manual
dp/Rellenar Vacíos/apply	Manual
elevationHysteresis	3.
font/calendar	Lucida Grande,8,-1,5,50,0,0,0,0,0
font/calendarsize	7
font/chartlabels	Lucida Grande,8,-1,5,50,0,0,0,0,0
font/chartlabelssize	7
font/chartmarkers	Lucida Grande,8,-1,5,50,0,0,0,0,0
font/chartmarkerssize	7
font/default	Lucida Grande,8,-1,5,50,0,0,0,0,0
font/defaultsize	9
font/titles	Lucida Grande,8,-1,5,50,0,0,0,0,0
font/titlessize	7
garminHWMark	25
garminSmartRecord	2
homedirectory	
lang	es
linewidth	0.5
mainwindow/geometry	���
mainwindow/lastImportPath	/Users/arturogarciapedraz/Downloads
mainwindow/lastOpened	Arturo
mainwindow/state	
pace	true
rideBG	false
show/tabbar	false
train/multi	false
warnexit	true
wbal/formula	diff
wheelsize	1913
workoutDir	/Users/arturogarciapedraz/Library/GoldenCheetah

**Comment by liversedge** [comment]
need to reset charts and view
