### ISSUE TITLE
goldencheetah download page

### ISSUE THREAD

**Issue by vlcvboyer** [GoldenCheetah/GoldenCheetah#1639]
At present when we ask for "goldencheetah download" google answer "http://www.goldencheetah.org/download.html" 

This is the old site and **v3.1.0 is indicated as current release** instead of 3.2 (and 3.3 soon !)

This page has to redirect to "http://www.goldencheetah.org/#section-download" which is the up-to-date one.

**Comment by gcoco** [comment]
Fixed. 
https://github.com/GoldenCheetah/goldencheetah.github.io/commit/128b6cdb341b7919f1cd040b175c1ae1b8e64a04

Website bugs should be raised against repo: https://github.com/GoldenCheetah/goldencheetah.github.io
