### ISSUE TITLE
Device Calibration

### ISSUE THREAD

**Issue by dresco** [GoldenCheetah/GoldenCheetah#1654]
Place-holder for calibration support.

Am currently working on this, but would be good to get a milestone against it - next release after 3.3?
- Code needs a good cleanup but I have ANT+ FE-C spindown calibration working now.
- Next I will look at zero offset for ANT+ power meters.
- A big question for me is what the controls might look like? I've temporarily hacked extra icons / keyboard bindings into the toolbar (up/down/calibrate). Works for me, but I know this is an area that's been lacking for a while.

Thoughts welcome..

**Comment by liversedge** [comment]
I think we need to add a 'connect' step as the first thing that you do, which connects to the device and starts collecting telemetry but doesn't start recording / load setting till you press start.

I like the idea of large controls that appear as an overlay when the mouse moves or keys pressed and they fade out if not used after 5 seconds.

**Comment by liversedge** [comment]
Should I defer this to 4.1 ?

Need to plan out the last 3 months of development before the release cycle begins ...

**Comment by dresco** [comment]
Hi Mark, yes to pushing out to 4.1 I think..

**Comment by liversedge** [comment]
done, thanks :)

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/f771fd6f27e9e30bc2b4c0ee408913a9c9270cf5 and related commits.
