### ISSUE TITLE
High DPI support on Mac

### ISSUE THREAD

**Issue by bdb** [GoldenCheetah/GoldenCheetah#1660]
I noticed this in 3.1 and 3.2. The tab item names are cut off. And now in 3.3 dev the ride chart names suffer the same fate (they were fine in 3.1/2).

This is on 10.11.1

<img width="534" alt="screen shot 2015-11-12 at 7 23 39 pm" src="https://cloud.githubusercontent.com/assets/130739/11136358/445d5eee-8973-11e5-9dd2-9aa466c868e9.png">

<img width="979" alt="screen shot 2015-11-12 at 7 23 23 pm" src="https://cloud.githubusercontent.com/assets/130739/11136361/47a7ff46-8973-11e5-83e0-b39c4315130a.png">

**Comment by liversedge** [comment]
see the faq on hi dpi support

**Comment by bdb** [comment]
This is OS X, not Windows. The only entry in the FAQ is for Windows. QT 5.1 and up provide support, yet GC got worse (see the ride chart) in the 3.3 move to high res.

**Comment by liversedge** [comment]
The only change in 3.3 is using QT5.
But yes, it seems a problem.

**Comment by bdb** [comment]
It seems this issue should be retiled "Add full native support for HiDPI" or something like that. Relying on it "just working" is not a good solution for an app as complex as GC.

There's this: http://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/ and the link the FAQ points to http://doc.qt.io/qt-5/highdpi.html has some info as well.

I wish I could help more, but I have zero experience with Qt (15 years of Cocoa though).

**Comment by liversedge** [comment]
See #1420, keep this one open since it gives similar examples for Mac retina.

**Comment by liversedge** [comment]
This is fixed in 3.4.
