### ISSUE TITLE
Unclear on what the open source license for this software is

### ISSUE THREAD

**Issue by ocharles** [GoldenCheetah/GoldenCheetah#1678]
http://www.goldencheetah.org/license.html doesn't mention which version of the GPL is being used. The link on that page is currently describing GPL v3. However https://github.com/GoldenCheetah/GoldenCheetah/blob/master/COPYING seems to suggest it's GPL 2+ - could you clarify what the intended license is? This information is needed to package Golden Cheetah for [NixOS](https://nixos.org). Thanks!

**Comment by liversedge** [comment]
that is a great question. I would say we are GPL 3 because we mix in with MIT licensed stuff but will check the legal position and get back to you,

**Comment by liversedge** [comment]
It is GPL version 3. Will update the COPYING file.
