### ISSUE TITLE
Importdata Swim-File from Fenix 3 with HRM-Swim is wrong RC3.3

### ISSUE THREAD

**Issue by studnik** [GoldenCheetah/GoldenCheetah#1687]
The Import of Swim-File from Fenix 3 withe HRM-Swim is wrong

- Speed ist wrong
- No Import HF (only as tcx-File)
- Wrong Devicename (Garmin or FR920XT Tcx)

https://connect.garmin.com/modern/activity/961374366

Greats!

![unbenannt](https://cloud.githubusercontent.com/assets/15957294/11319160/722757ac-906d-11e5-9b13-bf12882b5540.png)

**Comment by amtriathlon** [comment]
The TCX import doesn't seem easy to fix in this case, you can try the new Edit>Fix Speed tool using higher values for the smoothing parameter or "Clear Contents" for the Speed column in Edit chart.

Do you have a .fit file to test v3.3 RC2 import?

**Comment by studnik** [comment]
Hi Alejandro!

Sure! Here it is. In the meantime, I import first the fit and later I copy/paste the missing HF-Data from the thx. I think the ppeed is corecct, because in RC1 I have only use the thx.

Are the Metric correkt (CLT, ALT, TSB..?) Iam new in the analysis of swim values. The swim score are very high...

The importname of the Fenix in run/bike called "Garmin Fenix3".

Thanks!!

https://onedrive.live.com/redir?resid=F38C382BB7A3F5C9!243575&authkey=!AJUC1z11L7sM6oo&ithint=folder%2cFIT

**Comment by amtriathlon** [comment]
Thanks for the sample file but I'm afraid we cannot solve this issue for v3.3 FIT importer, HR seems to be added at the end of file in undocumented format: http://www.dcrainmaker.com/2015/07/garmins-hr-swimming-straps.html#comment-1330762
OTOH I think we can fix the TCX importer.

**Comment by amtriathlon** [comment]
This commit https://github.com/GoldenCheetah/GoldenCheetah/commit/7d5b6a8bd64e42c003a23ac5f3140da9ce0a34be should fix the speed problem for TCX files. I would left the issue open due to the FIT HR problem.

**Comment by liversedge** [comment]
Lets see if ANT/FIT gets fixed to support this and revisit later in v4 or perhaps v4.1 ..........

**Comment by amtriathlon** [comment]
The last version of FIT SDK supports HRM-Tri/Swim, from the Release Notes:

>16.30
>-Added new Plugin Architecture with Heart Rate Plugin example
>--Allows parsing of Garmin HRM-Tri stored heart rate data

There is also a sample plugin code showing how to merge the HR data in CPP using the SDK.

**Comment by liversedge** [comment]
OK thanks. Shouldn't the data be described in the FIT documentation ????

**Comment by amtriathlon** [comment]
I think it is, the HR message (#132) in profile, but I don't see that message coming in FitRideFile.cpp, perhaps the low level details have somewhat changed and we are not reading this new message correctly.

**Comment by studnik** [comment]
HI @amtriathlon! I think the HF-Import is now correct! But GC RC3 don´t import the cadence. I will put my latest Files

https://onedrive.live.com/redir?resid=F38C382BB7A3F5C9!243575&authkey=!AJUC1z11L7sM6oo&ithint=folder%2cFIT

**Comment by amtriathlon** [comment]
When you import the FIT file you have Speed and Cadence (no HR for now since we cannot parse the added HR yet) and when you import the TCX you have Speed and HR (no Cadence since it is not included in the TCX file as you can directly verify in the file). You could use Activity->Combine Activities or Copy&Paste in the edit chart to have both Cadence and HR.

**Comment by amtriathlon** [comment]
Damien fixed the HR-Swim import from FIT files in https://github.com/GoldenCheetah/GoldenCheetah/commit/957ae470999b9a57b5b8ec57e75512d4baede1ec
