### ISSUE TITLE
Temperature graph does not respect Units

### ISSUE THREAD

**Issue by gcoco** [GoldenCheetah/GoldenCheetah#1688]
In Analysis - Ride the Temperature graph always is displayed as Metric even when Imperial is selected.

Version: 3.3-RC2

**Comment by liversedge** [comment]
The plot isn't refreshed when you change units, I should fix that. But when a ride is selected the temperature is replotted in F.

![screenshot from 2015-11-22 08 44 21](https://cloud.githubusercontent.com/assets/142876/11322815/6cd97e5a-90f5-11e5-9e8a-a8bf3181c32c.png)
