### ISSUE TITLE
Adding a new CP value mixes up Pmax and W' setting

### ISSUE THREAD

**Issue by gille** [GoldenCheetah/GoldenCheetah#1690]
See image, I set W' to 20kJ, but Pmax gets that value and W' seems to get the value from the FTP field.

![golden_cheetah_cp_bug](https://cloud.githubusercontent.com/assets/749403/11326646/5369ceec-9123-11e5-9072-2c15f79edea6.png)

**Comment by liversedge** [comment]
Are you using RC1 or RC2 ?
It /should/ be fixed in RC2.

**Comment by gille** [comment]
I'm using Windows 64bit RC2.

**Comment by liversedge** [comment]
Sigh.

 Yep. This happens when you use the "Add" or "Update" button. Its a gui error on updating the view (it doesn't take into account the useCPforFtp setting correctly. if you save the zones should still be fine.

Will fix.

Sigh.
