### ISSUE TITLE
speed drop to 0 km/h for a few seconds while workout

### ISSUE THREAD

**Issue by Yanick7** [GoldenCheetah/GoldenCheetah#1705]
Hi,

I have an issue using the Kickr with a speed and cadence sensor. I get speed drop.(sometime speed is 0 and sometimes is displaying the correct value.) I have the firmware 1.3.32 installed. I have try with version 3.0 and 3.3 GC. I have seen this issue in the device wizard and in a workout when both are pair. If I unpair the speed and cadence sensor the speed is accurate(no more drop) in the device wizard and in a workout.

List of hardware use:

Garmin ANT+ USB 1 dongle.
Kickr
Bluesc (speed and cadence)
tickr(heart rate monitor)

**Comment by vlcvboyer** [comment]
Hi!

Is it 3.3RC2?
Do you experience this issue with both 3.0 and 3.3?

Best regards

Vianney

**Comment by liversedge** [comment]
The GSC-10 is returning 0 speed because there is no wheel attached when you are on the kickr.
Don't pair the S+C sensor -- it will return 0 values as you have experienced.

**Comment by Yanick7** [comment]
Hi,

I have seen this behavior in 3.2 and 3.3 RC2.(corrected the version number in the initial post.)

The part of not having a wheel attached is obvious on a kickr and that the S&C sensor will return 0,

Yes the work around for it is to disable the S&C sensor and use the kickr speed cadence but I loose a valuable metric the cadence that for me while training indoor is as much if not more important than speed.

I see that you have tag this as not a bug, it's your call.

Cordiality,
 
Yanick

**Comment by liversedge** [comment]
Sure. The reason it is not a bug is we are using data that is sent from the sensor.
Their are 3 options here (a) don't pair a S+C sensor when speed will be returned as 0 (b) buy a cadence only sensor and pair that (c) add an option to disable data series returned by a paired sensor in GC.

Option (c) is a feature request :)

**Comment by Yanick7** [comment]
Thank for the details, I am used to jira that offer enhancement or feature request as a state and not a bug means not an issue. Anyway, I will use option A until option C is available.

Thank you
