### ISSUE TITLE
Overwrite local files when syncing remote repo doesn't work

### ISSUE THREAD

**Issue by gille** [GoldenCheetah/GoldenCheetah#1706]
I discovered this while adding Google Drive support. 

If the file exists locally nothing happens when I try to download the remote file and I just get "downloading 0/0" even after checkboxing "overwrite". If I delete the local activity I can download it as expected.

**Comment by paulj49457** [comment]
If Auto import filtering and file import exclusion #3770 gets accepted for merging into the project, I'll look to extend it to include an overwrite option, as this change implements menus in the auto Athlete auto import config window and auto importation window that could easily be extended to make overwriting optional.

**Comment by paulj49457** [comment]
Auto import filtering and file import exclusion #3770 probably fixes this issue as the "overwrite" checkbox has been re-enabled and now works correctly.

**Comment by amtriathlon** [comment]
It works in current master, tested using Strava and DropBox, but the overwrite setting is generic so it should also work for other Cloud Services.
