### ISSUE TITLE
[map] OpenStreetMap support for map needed!

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#1709]
Google/Bing maps not usable for me (not satelite imagery, only map data) - too very bad geodata  on map or no data on big region.

1) Strava magrate from google map to OpenStreetMap and use MapBox tiles based on OpenStreetMap data. About MapBox: https://www.mapbox.com/about/maps/

2) Garmin Connect use MapQuest tiles based on OpenStreetMap data.

3) TrainingPeaks can show map use MapQuest tiles or use native OpenStreetMap default tiles.

OpenStreetMap default render: http://www.openstreetmap.org/

**Comment by bekreyev** [comment]
The ability to instantly updating OpenStreetMap maps can be very useful for the sport competition, so this functionality is useful for the project. I support the proposal.

**Comment by PedroSEQld** [comment]
Open Street Map is available (I am using version 3.5)
Activities>Map>More
![image](https://user-images.githubusercontent.com/47828623/140443407-71b07e9b-ccf3-4a9a-8e58-b030eca34f5a.png)

>Chart Settings
![image](https://user-images.githubusercontent.com/47828623/140443343-0f5ea436-629d-4dbd-8d22-337dd56a9c20.png)
>Map - from dropdown select/change to OpenStreetMap. Click 'Done'
![image](https://user-images.githubusercontent.com/47828623/140443553-d58c1f15-11e6-4711-84bb-4ec0fcad6ee9.png)
