### ISSUE TITLE
Average speed wrong

### ISSUE THREAD

**Issue by cheetahah** [GoldenCheetah/GoldenCheetah#1712]
I'm using data from a powertap and the average speed is wrong in the summary pages.  Maximums appear to be correct, but averages are waaay too high.  See screenshot.

As far as I can tell I have everything set up correctly.  Units set to imperial in preferences.  Power output seems to be about right.

![screen shot 2015-12-02 at 7 22 49 pm](https://cloud.githubusercontent.com/assets/16128064/11551028/2169985a-992a-11e5-894a-50b21d9bb70d.png)

**Comment by liversedge** [comment]
There is a problem with the file, likely recorded using smart recording and smart recording is not enabled in preferences. 

Please also make sure you are running a recent version, v3.3 is the latest.

**Comment by cheetahah** [comment]
Hmmm, can I get a little more info?  There's no mention of this in the FAQ.  I didn't record with a garmin/smart record, just used the little yellow computer that came with the powertap.  I'm running 3.3.  I also couldn't find any "smart recording" to enable in the preferences of golden cheetah.  Am I missing something?  Thanks for your help

**Comment by cheetahah** [comment]
Actually, I'm an idiot.  Found the smart recording option in the preferences, but averages are still wrong.

**Comment by liversedge** [comment]
you need to reimport the original.

**Comment by cheetahah** [comment]
YES!  It works!  thanks!!!
