### ISSUE TITLE
Trends PMC Time in Zone 

### ISSUE THREAD

**Issue by Bikeace175** [GoldenCheetah/GoldenCheetah#1714]
Hi,
I have updated to Golden Cheetah V3.3.

All my ride data is there but I cannot view the PMC, Timein Zone, Aerobic and Anaerobic charts in the Trends area.

Regards Andrew

**Comment by liversedge** [comment]
view > reset layout
chart sidebar > reset to defaults

Your config was wiped by running an earlier release after running a later release.
