### ISSUE TITLE
cadence chart: spent time always 0 at particular cadence values

### ISSUE THREAD

**Issue by hauke-w** [GoldenCheetah/GoldenCheetah#1717]
In the cadence chart of an activity the spent time drops always down to 0 at particular cadence values if "Bin Width" = 1, although I have been cycling with that cadence.
I observed this for all my activities and cadence values of 80, 100 and 107 1/min.

![Screenshot](http://i63.tinypic.com/14lhw1i.png)

**Comment by Joern-R** [comment]
Which version are you using - cannot reproduce in 3.3 - and what happens if you choose a different bin width.

**Comment by hauke-w** [comment]
I observed this with Version 3.3. and 3.2 (the first version I used).
When I use different bin widths there is no drop to 0. However, there is a clearly visible local minimum at 100 1/min for a bin width of 2.
For higher bin widths the effect is not obvious.
The other cadence values are so rare that there is no obviously wrong value perceptible for bin widths greater than 1.

**Comment by Joern-R** [comment]
Can you please share a ride which were the problem can be reproduced - at best the one you used for the screenshot. Send to joern.rm  at  gmail.com

**Comment by grauser** [comment]
Can you send some (2-3) of your files to me (Damien.Grauser at gmail) ?
Thank you.


Damien

2015-12-06 16:50 GMT+01:00 hauke-w <notifications@github.com>:

**Comment by hauke-w** [comment]
Hi Jörn and Damien,

I have just sent you an e-mail with 3 Fit files.

Regards
Hauke

**Comment by hauke-w** [comment]
I think I found the cause of this. My Device (Garmin Edge 810) does not record some cadence values.

**Comment by Joern-R** [comment]
Not a GC error - closed.
