### ISSUE TITLE
Problems compiling on Arch

### ISSUE THREAD

**Issue by maxammann** [GoldenCheetah/GoldenCheetah#1725]
**Make**
```
[root@mpv-mingw-build ~]# make --version
GNU Make 4.1
Gebaut für x86_64-unknown-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
Lizenz GPLv3+: GNU GPL Version 3 oder später <http://gnu.org/licenses/gpl.html>
Dies ist freie Software: Sie können sie nach Belieben ändern und weiter verteilen.
Soweit es die Gesetze erlauben gibt es KEINE GARANTIE.
```

**qmake**
```
[root@mpv-mingw-build ~]# qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib
```

**g++**
```
[root@mpv-mingw-build ~]# g++ --version
g++ (GCC) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
Dies ist freie Software; die Kopierbedingungen stehen in den Quellen. Es
gibt KEINE Garantie; auch nicht für MARKTGÄNGIGKEIT oder FÜR SPEZIELLE ZWECKE.
```

**Output of Make: https://gist.github.com/maxammann/7608245fc7c8c96e2016**

Compiling wtih qt4 also fails, but with an other error.

PS: Trying to build a package for arch

**Comment by liversedge** [comment]
The QWT lib we include in the repo doesn't compile with gcc5, they have updated the code in their project. It may be time to drop our local copy and link in with QWT as a mandatory external dependency.

Will look into it.

**Comment by maxammann** [comment]
K, thanks already though about this :/ Second problem today with gcc5. Sometimes it really hurts to be rolling release :/

**Comment by liversedge** [comment]
Tell me about it. QT5 is the stuff of nightmares.
PS: thanks for packaging GC :+1:

**Comment by maxammann** [comment]
btw: Do you know how to tell qmake to use an other version of gcc?

**Comment by liversedge** [comment]
https://wiki.qt.io/Undocumented_QMake is good for all the secrets
I think you can just define QMAKE_CC defines the C compiler, QMAKE_CXX is C++
see: http://stackoverflow.com/questions/6609117/changing-compiler-in-qt

**Comment by maxammann** [comment]
Tried compiling with gcc 4.9 with the same results. 4.8 didn't accept a compiler flag :/

Which version of gcc do you use?

**Comment by nickb937** [comment]
I've been building with Arch for the past few weeks without any issues, targetting Qt5.  I'll take a look to see if I made any local changes, but I'm pretty sure I've not had to.

**Comment by maxammann** [comment]
Problem seems to be linked to this one: https://groups.google.com/forum/#!topic/golden-cheetah-users/ujNWKud5N4g

Tried to build this on a clean arch virtual machine. Same results.

**Comment by maxammann** [comment]
Maybe there's a problem with these lines:

```
g++-4.9 -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -Wall -W -D_REENTRANT -DQWT_NO_SVG -DQWT_NO_OPENGL -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtCore -Imoc -I/usr/lib/qt/mkspecs/linux-g++ -o obj/qwt_scale_map.o qwt_scale_map.cpp
gcc -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -Wall -W -D_REENTRANT -DQWT_NO_SVG -DQWT_NO_OPENGL -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtCore -Imoc -I/usr/lib/qt/mkspecs/linux-g++ -o obj/qwt_scale_map_table.o qwt_scale_map_table.h
g++-4.9 -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -Wall -W -D_REENTRANT -DQWT_NO_SVG -DQWT_NO_OPENGL -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtCore -Imoc -I/usr/lib/qt/mkspecs/linux-g++ -o obj/qwt_spline.o qwt_spline.cpp
```

It tries to use gcc but it should use gcc-4.9.

**Comment by maxammann** [comment]
OK, sorry for this trouble. Managed to compile it by first compiling **qwt**, then **kqoauth**. Then adding -lssl and -lcrypto to the src.pro and then compiling **src**.

Running the build.pro file does not work. Not sure whether it's mentioned in INSTALL-LINUX clearly enough. At least it wasn't clear enough for me.

None the less not sure what the build.pro script is for.

**Comment by liversedge** [comment]
build.pro works on ubuntu .. but you may need to make clean if you've previously run qmake etc with a different qwtconfig.pri etc.

Glad you got it working :)

Be interested to hear what changes you think we should make to INSTALL-LINUX based upon your experience on Arch

Cheers
Mark :+1:

**Comment by maxammann** [comment]
Probably going to make a PR for the compile instructions.

Here's the aur package for gc: https://aur.archlinux.org/packages/golden-cheetah-git/

@nickb937 would be nice if you could try it.

**Comment by liversedge** [comment]
Thanks Max,

Looking at the build instructions from that link it doesn't bring in any optional build dependencies which is fine, but means 3d plots, diary view and a few other things will be missing.

Also of note the secrets needed for dropbox, strava and twitter etc are not baked in.

I think we (GC project) are going to have to build Linux packages ourselves; possibly stick to just .deb and .rpm. Will try and resolve this over the next few months.

Thanks
Mark

**Comment by maxammann** [comment]
Yeah, planning to integrate those libraries as well. Just wanted to get a first build working :D

Need it to track my progress :D

**Comment by nickb937** [comment]
@maxammann: the PKGBUILD worked fine for me

**Comment by liversedge** [comment]
Ah ok, thanks .. have reopened the issue.

**Comment by maxammann** [comment]
Got quite a few working. Everything seems to work except ical and vlc. Going to look into it tomorrow.
Also going to need a build of vlc which uses qt5, because if I link to qt4 and qt5 it just crashes :D
```
#0  0x00000000004acca0 in QString::~QString (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/qt/QtCore/qstring.h:1053
#1  ICalendar::data (this=0x0, date=..., role=role@entry=260) at ICalendar.cpp:265
#2  0x00000000004b59a4 in GcCalendarModel::data (this=0x1e76250, proxyIndex=..., role=<optimized out>) at GcCalendarModel.h:263
#3  0x0000000000680688 in QModelIndex::data (arole=8, this=0x7fffffffc9d0) at /usr/include/qt/QtCore/qabstractitemmodel.h:420
#4  GcMiniCalendar::setDate (this=0x1e75d00, _month=_month@entry=1, _year=_year@entry=2000) at DiarySidebar.cpp:850
#5  0x00000000006869bb in GcMultiCalendar::GcMultiCalendar (this=0x1e73c30, context=0x13dbe80) at DiarySidebar.cpp:894
#6  0x00000000005a3e57 in AnalysisSidebar::AnalysisSidebar (this=0x1e70b30, context=0x13dbe80) at AnalysisSidebar.cpp:54
#7  0x0000000000a54781 in AnalysisView::AnalysisView (this=0x1e67a50, context=0x13dbe80, controls=0x1e694b0) at Views.cpp:31
#8  0x00000000009eb801 in Tab::Tab (this=0x184d010, context=0x13dbe80) at Tab.cpp:64
#9  0x00000000007eb3ef in MainWindow::MainWindow (this=0x13dbfd0, home=...) at MainWindow.cpp:131
#10 0x000000000045df8d in main (argc=1, argv=<optimized out>) at main.cpp:478
```
![2015-12-21-23 55 04-screenshot](https://cloud.githubusercontent.com/assets/905221/11943517/c3735bc2-a83e-11e5-8e60-ed084a1c35ba.png)

**Comment by maxammann** [comment]
K, did a complete recomile. VLC and ical seem to work now. Could you provide me a checklist to check whether all libraries are working as expected?

**Comment by liversedge** [comment]
The VLC compilation issues a warning about the QT4 plugin causing a crash on QT5.

**Comment by liversedge** [comment]
QWT3D - add a 3d plot
KML - import/export to KML
ICAL - setup a local calendar in prefs (if it compiles, its almost certainly working)
USB - use an ANT+ device in train view
Wahoo - deprecated - we should remove from the about box
VLC - play a video in train view
SAMPLERATE - merge two files recorded at different samplerates
SSL/KAUTH stuff won't add any value since most services have a client token that is secret.

If you can get a build working I can share the tokens, but the problem here is keeping them secret, they must not be posted to public websites or source code repositories.

**Comment by maxammann** [comment]
k, tested everything except the usb lib, as I no not own a ANT+ device and the web services which need a token.

Just VLC seems not to work correctly. It tells in the settings that it uses vlc, but the video player does not show up. Do I have to use a training which is directly linked to a video that the player shows?

**Comment by liversedge** [comment]
Yes.. but its probably fine if it compiles.

**Comment by maxammann** [comment]
Finished my work on all optional libraries: https://aur.archlinux.org/packages/golden-cheetah-git/

Everything seems to be working. Closing this issue for now as there are no more comilition issues on arch :D
