### ISSUE TITLE
Many tabs in Trends now empty since updating to 3.3

### ISSUE THREAD

**Issue by ocharles** [GoldenCheetah/GoldenCheetah#1740]
Hi

I just updated to 3.3 and a lot of my tabs in "Trends" are showing up completely empty. The summary tab does show all the data I'd expected, but Tracker, Stress, PMC, CP History, Aerobic Power and Anaerobic Power are all completely blank. Doesn't seem to matter what date range I choose, and the search box is clear. I don't think I have any filters active either.

**Comment by liversedge** [comment]
You need to reset the layout (view->reset layout).
This is caused by reverting to an earlier version of GC without restoring (after running a later version)

**Comment by ocharles** [comment]
Oh you might be right - it looks like I have 3.2 pinned to my taskbar!

**Comment by ocharles** [comment]
I tried "View -> Reset Layout" in 3.3 and still have nothing in the charts - could there be anything else I need to do?

**Comment by liversedge** [comment]
if they are charts from the sidebar then you need to reset to default in the sidebar.

**Comment by ocharles** [comment]
Never mind, doing that for the third time seems to have fixed it. Weird! Thanks, and congrats on 3.3 :)

**Comment by liversedge** [comment]
no probs.
