### ISSUE TITLE
Time moving figure completely out

### ISSUE THREAD

**Issue by Whittaker555** [GoldenCheetah/GoldenCheetah#1744]
A good few of my rides have discrepancies with the time moving and duration. See the attached images and it says a elapsed time of 7:36 and a time moving of 2:07, giving me an average of 80.3 kph. Other posts have said fix gaps in recoding but this crashes my golden cheetah.

Hope someone can help!
![screen shot 2015-12-23 at 22 45 54](https://cloud.githubusercontent.com/assets/16296333/11986410/1a833ffc-a9c7-11e5-9f36-1b263a33205a.png)

**Comment by liversedge** [comment]
Can you share the ride that has the problem liversedge gmail com

**Comment by Whittaker555** [comment]
Thanks, I have just emailed you now.

**Comment by liversedge** [comment]
smart recording needs to be enabled in preferences as the bike computer being used has smart recording enabled.
