### ISSUE TITLE
Toolbar disappears when maximising window size

### ISSUE THREAD

**Issue by murdockcrc** [GoldenCheetah/GoldenCheetah#1747]
Repro steps:

- Open goldencheetah
- Double-click the top bar of the program's window to maximise the window to full screen.
- The toolbar (Trends, Diary, Activities, Train) disappears.
- In order to show it again, one needs to click View -> Show Toolbar, uncheck it and check it again.

This is happening on 3.3 build Id 3933

**Comment by liversedge** [comment]
its by design, to avoid a qt bug in fullscreen mode.
