### ISSUE TITLE
Model FTP/CP does not update when adding rides

### ISSUE THREAD

**Issue by gille** [GoldenCheetah/GoldenCheetah#1750]
It will however update when I close my athlete and reopen it.

**Comment by liversedge** [comment]
Model estimate refresh etc is a bit crappy in general, should look at how we can improve it.

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/f8af6334fb70a117595afed74c48cf9ca314e302
