### ISSUE TITLE
Add edit button for train devices

### ISSUE THREAD

**Issue by morejiik** [GoldenCheetah/GoldenCheetah#1752]
It's possible to add a button for editing the trainers under "Tool->Options...->Train Devices (tab)" so I can modify them easily without going in the "configglobal-trainmode.ini" ?
Thank you!
(Btw I'm not sure if this is the right way to add a feature request! Tell me the "official" way if I'm wrong!)

**Comment by liversedge** [comment]
delete and readd is the only way right now.
given that training devices are rarely changed it is such an edge case we are unlikely to ever address this (aside from recommending just adding a new one).

**Comment by morejiik** [comment]
Ok! Thank you.

**Comment by liversedge** [comment]
You may find that jone picks this up and has a go, but maybe not too :)

**Comment by maxammann** [comment]
Maybe going to give it a go. Seems like a good feature to start

**Comment by liversedge** [comment]
COOL ! Go for it :)

**Comment by maxammann** [comment]
Hmm, didn't read carefully enough :/. Don't have an ANT+ stick/device around. Do you know a way of emulating one?

**Comment by liversedge** [comment]
I would avoid this as a first attempt to code something.

The device wizard is extremely complex and you are likely to introduce multiple regressions trying to adapt it....
