### ISSUE TITLE
Tcx import total distance error

### ISSUE THREAD

**Issue by chrilarc** [GoldenCheetah/GoldenCheetah#1754]
When I import a tcx file generated by polar flow, the total distance data is bad.

**Comment by chrilarc** [comment]
It seems to be bad when there is only one lap.
Here are 2 .tcx files: one is OK, one is bad
[polar_flow_tcx.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/75535/polar_flow_tcx.zip)

**Comment by rrooster** [comment]
I'm having this problem too.

**Comment by rrooster** [comment]
I'm using GoldenCheetah v.3.3 for OSX (10.11), DB schema 123, metrics 274

**Comment by Yo-hans** [comment]
I'm seeing distance significantly inflated ~120km should be 88. 
.tcx file exported from Movescount
GC V3.3 build id 3933

Same file imports into Trainingpeaks and Montebello ascent correctly.
Note: the file does not have any power data.

**Comment by liversedge** [comment]
I imported the files and they match the distance in the file e.g. 2015_12_31_11-05-14.tcx is 13 km in length.

I wonder what language and locale you are using ?

**Comment by Yo-hans** [comment]
I've attached .fit and .tcx files [Archive.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/121394/Archive.zip)

**Comment by liversedge** [comment]
@Yo-hans those files don't include distance, just GPS, are they from SportTracks?

**Comment by Yo-hans** [comment]
Hi Mark

They're recorded on a Suunto Ambit 3 Peak watch, sent to Movescount and then exported from there. 

Thanks

**Comment by liversedge** [comment]
With only GPS data we approximate distance using a haversine formula. For accurate distance data we need it in the file.

**Comment by Yo-hans** [comment]
Ok, that makes a bit of sense as I'd previously seen some differences but small. The difference on this particular ride are quite large ~36% and stood out like a sore thumb. 

Do you know of any tools I could use to get to a closer approximation?

Thanks

**Comment by liversedge** [comment]
Actually, looking at the code it derives distance from speed.
Looks like the data is bad.

**Comment by Yo-hans** [comment]
Thanks, I’ll see if Suunto can help with that.

**Comment by amtriathlon** [comment]
Have you tried to import directly the SML files generated by Suunto Ambit 3?
They are supported in v3.3

2016-02-08 8:32 GMT-03:00 Yo-hans <notifications@github.com>:

> Thanks, I’ll see if Suunto can help with that.
>
> > On 8 Feb 2016, at 10:23 PM, Mark Liversedge <notifications@github.com>
> wrote:
> >
> > Actually, looking at the code it derives distance from speed.
> > Looks like the data is bad.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/GoldenCheetah/GoldenCheetah/issues/1754#issuecomment-181321573
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoldenCheetah/GoldenCheetah/issues/1754#issuecomment-181327265>
> .
>



-- 
Alejandro.

**Comment by Yo-hans** [comment]
Sorry, I missed this response.
How do I access the SML file that you mention?
Thanks

**Comment by amtriathlon** [comment]
After Moveslink finish syncing.the SML files should be on:

Windows:
C:\Users\{username}\AppData\Roaming\Suunto\Moveslink2
Note: You may have to enable the show hidden files option in Windows Explorer.

Mac:
Under your home directory:
~/Library/Application Support/Suunto/Moveslink2

**Comment by Yo-hans** [comment]
Fantastic, so easy.

Thanks very much

**Comment by Yo-hans** [comment]
Oops. spoke too soon.

HR data is missing.

I've attached the sms file zipped as well as a screenshot of the data stream from the edit page.


![screen shot 2016-02-26 at 12 03 42 pm](https://cloud.githubusercontent.com/assets/8775529/13340020/0d667b76-dc81-11e5-8ec2-740cb70d838d.png)

[AA6810511D000C00-2016-02-06T09_04_41-0.sml.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/147522/AA6810511D000C00-2016-02-06T09_04_41-0.sml.zip)

**Comment by amtriathlon** [comment]
That file doesn't have HR data at the periodic samples, only R-R data (HRV)
at the end of the file, and we don't have support for HRV data yet...

**Comment by Yo-hans** [comment]
Here's the file in GC after export from Movescount and with the incorrect distance data but with HR data

![screen shot 2016-02-26 at 12 13 36 pm]

(https://cloud.githubusercontent.com/assets/8775529/13340193/855b1dca-dc82-11e5-9500-bd071c0b628f.png)

And here's the HR graph form the movescount screen

![screen shot 2016-02-26 at 12 16 48 pm](https://cloud.githubusercontent.com/assets/8775529/13340248/f432ebf6-dc82-11e5-83a1-9592c42d46ed.png)

Thank you

**Comment by Yo-hans** [comment]
So perhaps Suunto are calculating the HR data from the R-R measurements

**Comment by amtriathlon** [comment]
I think so.

The strange thing is other SML files come with periodic HR data in addition
to R-R records but I don't know if it is a configurable feature.

**Comment by Yo-hans** [comment]
Are there settings somewhere for me to check?

**Comment by amtriathlon** [comment]
I don't know, it is something new for me.

**Comment by amtriathlon** [comment]
Followup at https://github.com/GoldenCheetah/GoldenCheetah/issues/1841
