### ISSUE TITLE
"This week (N activities)" doesn't count correctly

### ISSUE THREAD

**Issue by gille** [GoldenCheetah/GoldenCheetah#1764]
Maybe this is because the year rolled over but it's claiming I've done two rides this week and I've ridden every day since Tuesday which should be five. 

The two rides it claims I've done is Jan 1st and 2nd.

**Comment by liversedge** [comment]
Whereabouts are you seeing this?
Any chance of a screenshot?

**Comment by gille** [comment]
Since it contains a bunch of info about me I'll email it to you.

**Comment by liversedge** [comment]
For info, after receiving an email from Magnus it is the count in group by in the ride navigator.

**Comment by bdb** [comment]
This may be fixed by a commit in my PR #1777, https://github.com/bdb/GoldenCheetah/commit/27a56332267fea147d693b0873a2c316388f3a70

Not sure at all, but the context of the fix involves weeks.
