### ISSUE TITLE
build error: missing -lz

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#1770]
I have a error on build process on last stage - linker:

```
clang++ -ccc-gcc-name g++ -Wl,-rpath-link,/usr/lib64 -o GoldenCheetah [more *.o files]  -L../qwt/lib -lqwt -lm ../kqoauth/libkqoauth.a -lssl -lcrypto -L/usr/lib64 -lQt5Svg -lQt5WebKitWidgets -lQt5MultimediaWidgets -lQt5Widgets -lQt5WebKit -lQt5Multimedia -lQt5Gui -lQt5Xml -lQt5Sql -lQt5Network -lQt5Script -lQt5Concurrent -lQt5SerialPort -lQt5Core -lGL -lpthread 
/usr/bin/ld: zip.o: undefined reference to symbol 'inflateInit2_'
/lib64/libz.so.1: error adding symbols: DSO missing from command line
clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:1582: recipe for target 'GoldenCheetah' failed
make[1]: *** [GoldenCheetah] Error 1
```

I'm manualy added "-lz" to end of linker command line and have no error.

openSUSE 13.2, x86_64, clang-3.5

**Comment by liversedge** [comment]
gcconfig.pri.in instructs you to add -lz if it is not being linked by QT.
you need to update gcconfig.pri

**Comment by diophantus7** [comment]
I get the same error
`/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: zip.o: undefined reference to symbol 'inflateEnd'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /lib64/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1025: GoldenCheetah] Error 1
make[1]: Leaving directory '/home/user/bin/GoldenCheetah-3.4/src'
make: *** [Makefile:113: sub-src-make_default-ordered] Error 2
`
I tried adding/removing the line `LIBZ_LIBS = -lz` in src/gccconfig.pri.in, but it didn't help. Any ideas?

**Comment by amtriathlon** [comment]
> I tried adding/removing the line LIBZ_LIBS = -lz in src/gccconfig.pri.in, but it didn't help. Any ideas?

As stated before you need to change src/gccofig.pri
