### ISSUE TITLE
CP (Ext) Estimate

### ISSUE THREAD

**Issue by jonbev** [GoldenCheetah/GoldenCheetah#1771]
I have started using power for running using Stryd but it is affecting my CP (Ext) Estimate for cycling.

If you point me in the right direction I might be able to sort it myself?

**Comment by liversedge** [comment]
RideCache.cpp line 682 and 722 need to skip activities that are not runs.

**Comment by grauser** [comment]
commit 5ae5da1b0fb50d23085ae5348a3c96f57057d80d
