### ISSUE TITLE
Add FIT export support (for e.g L/R power balance)

### ISSUE THREAD

**Issue by bdb** [GoldenCheetah/GoldenCheetah#1774]
It appears that GC will consume L/R power balance from .fit files, but then there is no way to get that information back out with any of the currently supported export file formats. Could .fit export be added or perhaps the TCX or PWX formats updated to support L/R balance?

It's certainly possible to just use the original fit file, but that does not work if there's garbage (spikes, etc) in it that needs to be corrected using GC.

**Comment by liversedge** [comment]
Neither the TCX not the PWX formats support LR balance.
