### ISSUE TITLE
Problem with non standard ASCII characters in Media Library / Train View

### ISSUE THREAD

**Issue by Joern-R** [GoldenCheetah/GoldenCheetah#1787]
Windows / VLC Player - Video is not shown if the path to the Video contains a not "standard" ASCII character.  Example below. Has been reported / confirmed to related to the 'ü' on the user list. 

<library name="Media Library">
    <ref>D:/users/Günter/Downloads/FulGaz_competition1.mp4</ref>   not working
    <ref>D:/TrainingVideos/FulGaz_competition2.mp4</ref> working
</library>

**Comment by liversedge** [comment]
Almost certainly caused by VideoWindow, line 496 fileURL.toLatin1() ....
