### ISSUE TITLE
Bryton Rider 310 fit file

### ISSUE THREAD

**Issue by michie1** [GoldenCheetah/GoldenCheetah#1788]
The fit file the Bryton Rider 310 produces is wrongly imported into GC, as can seen in the following screenshot.
![brytonfitfile](https://cloud.githubusercontent.com/assets/1347371/12233699/41e8d1a0-b869-11e5-83d9-429015bc1c85.png)
Here is a fit file example, but named as zip file: [160109152536.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/85722/160109152536.zip)

**Comment by liversedge** [comment]
Horrible !

I wonder if it is recorded with smart recording. Try enabling Gamin Smart Recording in preferences/options and re-import?

**Comment by michie1** [comment]
I have a powermeter and enabled 1 sec recording on the Bryton. In the GC settings Garmin smart recording was not enabled, but when enabled I get different, but still wrong data.
![bryton_gc_smart](https://cloud.githubusercontent.com/assets/1347371/12234974/ddc1a8ca-b870-11e5-8dd9-6062485ff74b.png)

**Comment by liversedge** [comment]
Send me a file and I'll take a peek.
liversedge gmail

**Comment by michie1** [comment]
I noticed differences between version 3100 and 3940, but still both wrong.

**Comment by michie1** [comment]
"The fit file itself appears to be valid. While the format is not typical, we do not enforce having only one message per timestamp."
https://www.thisisant.com/forum/viewthread/6367/#6943

**Comment by drell** [comment]
There is a problem with altitude too.

**Comment by michie1** [comment]
I did not check altitude yet because I live in a flat area, but Mario from the previous posted link (thisisant) says "The latitude and longitude values are reported in units of semicircles."

**Comment by drell** [comment]
The altitude is wrong only if import the fit in gc.
 The files are a bit strange and appear not conform to fit standard.
 They work online platform site but no in pc platform program.

**Comment by gornostaevdev** [comment]
Same issue with my 310.

**Comment by grauser** [comment]
Duplicate #2029

**Comment by drell** [comment]
It is closed but in 3.4 august the is not full support for file

**Comment by liversedge** [comment]
the issue is being tracked in #2029

**Comment by hrcsaba** [comment]
Hi, the Bryton 310 .fit import is almost perfect, but the elevation data seems corrupt :(
