### ISSUE TITLE
Column Chooser not working

### ISSUE THREAD

**Issue by jonpanoff** [GoldenCheetah/GoldenCheetah#1792]
Hi,
I am using V3.3 of Golden Cheetah on the mac and the column chooser isn't working on the activities tab. I tried dragging. double clicking etc and nothing. Also it is near impossible to get the right widths of the columns. It does strange things when you try and change the widths.. Help please

**Comment by liversedge** [comment]
please use the forums for this kind of thing .. this is the place for bugs :)
https://groups.google.com/forum/#!forum/golden-cheetah-users
