### ISSUE TITLE
Change antlog file save location

### ISSUE THREAD

**Issue by gcoco** [GoldenCheetah/GoldenCheetah#1793]
At the moment the antlog file is saved to the directory where GC is run from. For Windows this generally means that the file cannot be saved due to permissions.

Recommend that the file should be saved to the Athlete that is performing the training.

Ideally we should save each antlog file (if the ride is saved) as the raw file before the JSON conversion as we do with other file formats that we import.

**Comment by dresco** [comment]
Thanks, agree that it would be good to save it in a more deterministic location. Will do that this weekend..

Am not convinced about saving prior versions though. (The data is only useful for debugging - can't be used to recreate the activity).

**Comment by liversedge** [comment]
Yeah, just do it for new ones. Best place to put it is in /records (where the csv recorded data goes).

**Comment by dresco** [comment]
Sorry, just for clarity, was meaning I don't think it's worth saving more than one file (per athlete)..

Am plodding away at decoupling the telemetry from workout start/stop, and as part of this I was thinking about adding a checkbox to make the antlog optional (as I hope to have telemetry running all the time train view is active).
