### ISSUE TITLE
Train View dialogues appear behind stop / play window

### ISSUE THREAD

**Issue by david-waterworth** [GoldenCheetah/GoldenCheetah#1797]
Hi,

There's code in the FortiusController::getRealtimeData and AntLocaController::getRealtimeData which shows a dialogue if the device isn't working properly, i.e. below. On my machine (Windows 10 x64) these appear directly behind the small floating play / stop window and yet are modal so must dismiss them before you can interact with the UI (which requires alt-tab / enter since cannot hit the ok button due to the other window on top)

It would be preferable if the devices communicate errors back to the train view rather than handle themselves - i.e. add an error code / error message field to RealtimeData and pass back status this way

```
if(!myFortius->isRunning())
{
    QMessageBox msgBox;
    msgBox.setText(tr("Cannot Connect to Fortius"));
    msgBox.setIcon(QMessageBox::Critical);
    msgBox.exec();
    parent->Stop(1);
    return;
}
```

**Comment by liversedge** [comment]
this was fixed by the dresco update that added status window in the compare pane at the bottom of train view.
