### ISSUE TITLE
Crash at startup due to index out of range in PMCData::refresh

### ISSUE THREAD

**Issue by WaterworthD** [GoldenCheetah/GoldenCheetah#1803]
The code below is from line 379 of PMCData.cpp

if day <= stsDays_ then [day-stsDays_-1] will always be -ve yet this expression is then used as a loop index inside the if statement

I suspect the check should be for day > stsDays_ instead as this will ensure that  [day-stsDays_-1]  >= 0

                if (day <= stsDays_) {
                    if (start_.addDays(day).daysTo(QDate::currentDate())<-1-stsDays_) {
                        ltsAtStsDays1 = expected_lts_[day-stsDays_-1];
                    } else {
                        ltsAtStsDays1 = lts_[day-stsDays_-1];
                    }

                    if (start_.addDays(day).daysTo(QDate::currentDate())<-stsDays_) {
                        ltsAtStsDays2 = expected_lts_[day-stsDays_];
                    } else {
                        ltsAtStsDays2 = lts_[day-stsDays_];
                    }
                }

Dave

**Comment by liversedge** [comment]
I will ask Damien to take a look. I can't work out what all this code is doing.

**Comment by grauser** [comment]
Yes, thank you Dave ! 
I will correct.

**Comment by liversedge** [comment]
Thanks Damien!

**Comment by WaterworthD** [comment]
Also what does the following do?

doesn't day && day == day

So I think this runs the first block if day <= srsDays and the 2nd if day > srsDays && day != 0 

            // rolling stress for STS days
            if (day && day <= stsDays_) {
                // just starting out
                expected_rollingStress += expected_lts_[day] - lastLts;
                expected_rr_[day] = expected_rollingStress;
            } else if (day) {
                expected_rollingStress += expected_lts_[day] - lastLts;
                expected_rollingStress -= ltsAtStsDays2 - ltsAtStsDays1;
                expected_rr_[day] = expected_rollingStress;
            }
