### ISSUE TITLE
Crash using Mac OS X

### ISSUE THREAD

**Issue by aplack** [GoldenCheetah/GoldenCheetah#1806]
Finally got round to upgrading from GC v2.0 to 3.3, but it keeps crashing on opening

Wondering if it's to do with number of files it has to process as goes back to 2012?

[GC Crash Report 1.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/98191/GC.Crash.Report.1.txt)

**Comment by liversedge** [comment]
unlikely to be volume, probably bad data.
what does the upgrade report say?

**Comment by aplack** [comment]
not gone through it line by line, but seems to say all successful with no failures

[GCUpgrade.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/98194/GCUpgrade.txt)

thanks for prompt response btw

**Comment by liversedge** [comment]
It might be better to create a new athlete and import the data fresh.
If you start on the command line
```
% goldencheetah --
```
it will prompt and let you create a new athlete. Then you can drag and drop the data in batches into the new athlete.

If thats a ballache, be interested to try and recreate -- you can send a zip of your activities via dropbox or similar? I'm liversedge gmail com

**Comment by aplack** [comment]
thanks - message sent

**Comment by amtriathlon** [comment]
This refers to an old version, please test using the last development build an reopen if you can reproduce it.
