### ISSUE TITLE
Broadcasting of live data in Training Mode - Feature Request

### ISSUE THREAD

**Issue by bjarkason** [GoldenCheetah/GoldenCheetah#1812]
Sending live sensor data in Training Mode to an OPC server would be a very useful feature.
An "Broadcast to OPC" option in the menu would enable the user to specify the OPC and choose what sensor data is sent to an OPC.

**Comment by nickb937** [comment]
I thought OPC was only used for SCADA systems.

**Comment by bjarkason** [comment]
Yes, OPC UA is becoming a standard protocol in the industry and mostly used for SCADA.
The protocol is open-source and cross-platform. To import the live sensor data from Golden Cheetah into another program in real-time, i believe OPC UA webservice would be very suitable. I believe some other users/developers would be interested having access to the live sensor data in real time for use in another applications. (For example, I want to access the real sensor data from the bike in LabView, which currently does not support direct ANT+ data acquisition).

If you have some ideas of other methods to broadcast the sensor data in real-time and making it accessible to other applications, please leave a comment.
