### ISSUE TITLE
FEATURE REQUEST: Manual entry of ambient temperature

### ISSUE THREAD

**Issue by RJKflyer** [GoldenCheetah/GoldenCheetah#1813]
External rides using typical cycling computers tend to report ambient temperature, which is passed to GC.

However, when using an indoor trainer, most do not, or can not (for reasons of mechanical temperature effects) report ambient temp. Under these circumstances, GC appears to either get 'sent' or decides to 'use' a default/null temperature value of -427 degF.

It would be useful if an ambient temperature value could be added manually, as temp affects rider performance and would allow the ambient temp impact of workouts to be evaluated.

**Comment by amtriathlon** [comment]
Average Temp metric can be manually overridden, just like any other metric in GC or, if you have the data, a Temp column can be pasted on Ride Editor
