### ISSUE TITLE
GC 3.3 will not find Kickr FE-C

### ISSUE THREAD

**Issue by ahfranks** [GoldenCheetah/GoldenCheetah#1822]
GC 3.3 will find Kickr speed and power over ANT+ but not FE-C.

**Comment by liversedge** [comment]
Please make sure you are searching the FE-C channel and have updated the firmware on the Kickr to the version that supports FE-C.

**Comment by ahfranks** [comment]
Can you enlighten me on how to search the channel? I was under the
impression it was just ANT+. Also I've got the latest kickr Fw. Do I need
to backdate it?

**Comment by liversedge** [comment]
Make sure the dialog is searching for an FE-C device, see this picture:

![screen shot 2016-01-31 at 16 58 20](https://cloud.githubusercontent.com/assets/142876/12703478/057fccfe-c83c-11e5-818d-3b8a7206ed29.png)

I think you may need a beta FW for the Kickr to get FE-C support.
I'd suggest following up on the user forums.

**Comment by ahfranks** [comment]
I updated to newest beta FW 1.4.39 and it paired, but it doesn't seem to be controlling the Kickr still. Any other steps I missed? I don't need to select anything from the "virtual" menu right?
