### ISSUE TITLE
Two instances of GC open in train mode - only one works with ANT+ devices

### ISSUE THREAD

**Issue by ahfranks** [GoldenCheetah/GoldenCheetah#1824]
As a follow up to my last issue (got FE-C to pair using Kickr FW 1.4.39), I'm trying to run two instances (athletes with already added devices) of GC in train mode and whichever I start workout on first gets control over the ANT+ devices. 

I have two ANT+ sticks and can see all 8 channels fill up if I try to add devices on one instance but if I disable 4 and try to add another 4 on the other instance, no joy.

**Comment by liversedge** [comment]
Not likely to look at this for a long time. so putting in the parking lot.
