### ISSUE TITLE
export from myETraining, import of TCX and speed

### ISSUE THREAD

**Issue by ainthek** [GoldenCheetah/GoldenCheetah#1826]
in XML the sped reads 28.198634 but on the screen after import I see 101,5150 (in Editor). On OSX version of GC, what is wrong ? (import in GC, export in MyEtraing ?, me ?) Thanx a lot 
![screen shot 2016-02-02 at 22 27 18](https://cloud.githubusercontent.com/assets/559519/12764858/27eb152a-c9fc-11e5-9416-c779cb86407b.png)
[route[1].tcx.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/114712/route.1.tcx.zip)

<Track>
                    <Trackpoint>
                        <Time>2016-01-24T14:19:37.130Z</Time>
                        <DistanceMeters>7.000000</DistanceMeters>
                        <Cadence>66.000000</Cadence>
                        <Extensions>
                            <TPX xmlns="http://www.garmin.com/xmlschemas/ActivityExtension/v2" CadenceSensor="Bike">
                                <Speed>28.198634</Speed>
                                <Watts>531.000000</Watts>
                            </TPX>
                        </Extensions>
                        <HeartRateBpm xsi:type="HeartRateInBeatsPerMinute_t">
                            <Value>0.000000</Value>
                        </HeartRateBpm>
                    </Trackpoint>

**Comment by liversedge** [comment]
Thats a bad file. Speed should be in meters per second.

**Comment by ainthek** [comment]
tnanx a lot, will report to 'elite' team ;-)

**Comment by ainthek** [comment]
Dear Customer 
Garmin connect and Strava required km/h on the tcx file
Please refer to GoldenCheetah to know which standard they use
Regards
Andrea Brotto
Elite srl

**Comment by ainthek** [comment]
If anyone runs to this problem, here is a script that helps with conversion
https://github.com/ainthek/elite-trainers/tree/master/bin
