### ISSUE TITLE
Most .pwx files are corrupt when exporting, cannot import into Training Peaks

### ISSUE THREAD

**Issue by raschultz** [GoldenCheetah/GoldenCheetah#1828]
Batch exporting the files then trying to upload to training peaks, 2/3 of the files will not import. Working with training peaks, they say that files are corrupt. This needs to be addressed on the Golden Cheetah side. These are the .pwx files. Sample file attached.
[Uploading 02-01-2016.zip…]()

**Comment by liversedge** [comment]
you need to host the files somewhere and post a url as attachments are not valid.
I doubt there is a problem since the TP upload has been working for over 5 years.
But send me a couple of the source files and I will take a look (don't send the pwx, send the originals you imported into GC).

liversedge gmail com

**Comment by liversedge** [comment]
also, why are you batch exporting when you can upload directly to trainingpeaks from GC?

**Comment by raschultz** [comment]
Because I thought that was the right way to do it.,
The SHARE/UPLOAD to TP does work.
Not sure why the other way doesnt

**Comment by liversedge** [comment]
OK. If you send me a file I'll take a look, but if upload works then really only TrainingPeaks can answer why it would work in one way and not the other.

**Comment by raschultz** [comment]
Uploading one-by-one now successfully. Have a Skype meeting with TP in a couple hours, will ask them.

**Comment by liversedge** [comment]
You can upload in batch from the share menu, don't need to do it one by one !

**Comment by liversedge** [comment]
see: https://vimeo.com/105980432
