### ISSUE TITLE
Problem building from source Ubuntu 14 and 15

### ISSUE THREAD

**Issue by jtamuc** [GoldenCheetah/GoldenCheetah#1829]
Good afternoon,
I am attempting to build on my Ubuntu system without having to use a Windows virtual machine. I have tried several times with my current Ubuntu 15 laptop, and just tried on a clean install of Ubuntu 14 LTS following the steps given in INSTALL-LINUX. The error message is shown below:

In file included from ../../../../anaconda/include/QtCore/qhash.h:47:0,
                 from ../../../../anaconda/include/QtCore/qdebug.h:46,
                 from qwt_scale_map.h:18,
                 from qwt_scale_map_table.h:14:
../../../../anaconda/include/QtCore/qiterator.h:81:1: error: expected declaration specifiers before ‘QT_MODULE’
 QT_MODULE(Core)
 ^
In file included from ../../../../anaconda/include/QtCore/qhash.h:48:0,
                 from ../../../../anaconda/include/QtCore/qdebug.h:46,
                 from qwt_scale_map.h:18,
                 from qwt_scale_map_table.h:14:
../../../../anaconda/include/QtCore/qlist.h:50:20: fatal error: iterator: No such file or directory
compilation terminated.
Makefile:520: recipe for target 'obj/qwt_scale_map_table.o' failed
make[2]: *** [obj/qwt_scale_map_table.o] Error 1
make[2]: Leaving directory '/home/john/Sourcefolders/GoldenCheetah/qwt/src'
Makefile:39: recipe for target 'sub-src-make_default-ordered' failed
make[1]: *** [sub-src-make_default-ordered] Error 2
make[1]: Leaving directory '/home/john/Sourcefolders/GoldenCheetah/qwt'
Makefile:41: recipe for target 'sub-qwt-make_default-ordered' failed
make: *** [sub-qwt-make_default-ordered] Error 2

I had about 50 more errors above but it looks like the fatal error kicked it out. I checked the directory and /include/QtCore/qlist.h does exist. 

Any help would be appreciated!

Jack

**Comment by liversedge** [comment]
what version of gcc and qt are you using?

**Comment by liversedge** [comment]
fwiw, the developers use ubuntu, so this will be a toolchain issue.

**Comment by jtamuc** [comment]
I am using Qt 4.8.7 installed from synaptic. Have tried it both on a fresh
install and in my anaconda virutal env.

gcc is the ubuntu 5.2.1 version.

Thank you!

**Comment by jtamuc** [comment]
When I run the SDK for Qt I do not get an option to build Qt4, just Qt5. I
downloaded the Qt4 opensource 4.8.5 but am at a loss as to how to install.
Thus I decided to install Qt4 from synaptic.

**Comment by liversedge** [comment]
QT packages are downloaded from http://www.qt.io/download/
I would recommend building with QT5.5 until QT5.6 comes along.
I suspect QT4.8.7 and your G++ toolchain are not compatible (or some parameters are needed to make g++ play along)

**Comment by ihewitt** [comment]
I'm not a ubuntu user but:

`fatal error: iterator: No such file or directory`

implies that there's a problem finding your std c++ libraries.

`g++ -E -x c++ - -v < /dev/null` will tell you where g++ is looking for its headers.
`apt-file search -x '/usr/include/c\+\+/[0-9]\.[0-9]/iterator$'` will show which package contains that header.
and `dpkg --get-selections | grep libstdc++` will show you which you have installed.

**Comment by liversedge** [comment]
closing this as it doesn't belong here, its not a FR or bug.

thanks

**Comment by viiru-** [comment]
I think the fix to this issue is the following patch:

diff --git a/qwt/src/src.pri b/qwt/src/src.pri
index 74206f2..eb831ac 100644
--- a/qwt/src/src.pri
+++ b/qwt/src/src.pri
@@ -77,7 +77,6 @@ SOURCES += \
     qwt_scale_div.cpp \
     qwt_scale_draw.cpp \
     qwt_scale_map.cpp \
-    qwt_scale_map_table.h \
     qwt_spline.cpp \
     qwt_scale_engine.cpp \
     qwt_symbol.cpp \

In essence, qwt_scale_map_table.h is listed in both HEADERS and SOURCES. Looks like a copy&paste mistake to me.
