### ISSUE TITLE
events and overlapping seasons

### ISSUE THREAD

**Issue by mistrix** [GoldenCheetah/GoldenCheetah#1830]
Events may only be defined for user-defined seasons but not for "All Dates". When working with overlapping seasons (p.e. calendar years and training cycles) the topical behaviour seems to be, to display events defined for an overlapping later season but not for an overlapping previous one. Hence, if setting up events for training cycles (guess that would be typical/intended) charts filtered for calendar year "season" show no events for the beginning (i.e."old" training cycle), but only for the end (i.e. "new" trainingh cycle).

Could that be corrected to include plotting events of any overlapping season for arbitralily time filtered views? Thanks

**Comment by liversedge** [comment]
Thats how it works for now.
