### ISSUE TITLE
Options not saved - GC 3.2 - Ubuntu 15.10

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#1834]
Hi,

I just installed GC 3.2 on Linux Ubuntu 15.10 on a new laptop. 

Unfortunately I have issues filling in the options, such as crank length, weight, appearance, metrics,... All these settings seem to be reset to factory defaults at each restart. 

I never had this issue on previous installs of GC 3.2 running on Ubuntu 15.10. I am using dropbox to store all my files, so I suspect it might have something to do with a corrupt file from a previous install. I am using GC 3.2 on  Windows 10 as well using the same synced dropbox folder. Over there everything works as expected.

Any ideas how I could try to fix this without losing my data?

Thanks!

Kind regards,

Nigel

**Comment by liversedge** [comment]
Config is now stored in the athlete directory.
You are probably losing it due you your dropbox setup ?

**Comment by nigelvdv** [comment]
The same dropbox setup (dual boot windows10-ubuntu 15.10) used to work on my previous laptop.
In my current setup I can update and save all settings under windows10. Settings don't get reverted. Once I open GC on ubuntu all those settings do get reverted.

Is there a specific file where these settings are stored? I might try to copy-paste it manually.

**Comment by liversedge** [comment]
All the .ini files.

**Comment by liversedge** [comment]
I may close this since it is not recreatable and is related to your setup.
Do come back with any solutions you find so others with similar problems can learn from it :)

THANKS

**Comment by nigelvdv** [comment]
Hi,

I have no .ini files in any of my folders on dropbox...

Strange that I can change and save settings under Windows, isn't it? Surely there needs to be a file containing the changes somewhere. I changed some settings, cranklengthe and added some metrics, at 11h39. 

In attachment you can see the files that were updated at that time in my athlete folder. I can't find any recent changes in other GoldenCheetah related folders (Program Files and AppData).

![schermafdruk 2016-02-08 11 47 43](https://cloud.githubusercontent.com/assets/14836910/12883768/37c0525a-ce5a-11e5-8d16-74a4507dedc0.png)

If there is no solution I might do a clean install of GC without linking to dropbox and then copy paste my activities manually. I am afraid to lose data such as notes and added personal data fields, so would prefer to find another solution.

Thanks for the help!

Kind regards,

Nigel

**Comment by liversedge** [comment]
Global config is saved in the top level directory, athlete specific ini files are in the athlete config directory when you press save in preferences or quite the application. 

Open GC, edit something *and make a change* then press save.
You will see the ini files update. If you don't make a change nothing is saved.

**Comment by nigelvdv** [comment]
No ini files in the top folder or in any of the athlete files.

I added 3 metrics to bests, saved the changes, quit the program, let dropbox sync and opened the program again. The 3 added metrics (10min...) are shown correctly:

![schermafdruk 2016-02-08 12 11 17](https://cloud.githubusercontent.com/assets/14836910/12884333/cd1cbaf2-ce5d-11e5-956b-6efc9e0e0a25.png)

No ini files found anywhere in GoldenCheetah (and subsequently the changes are not shown under ubuntu):

![schermafdruk 2016-02-08 12 12 08](https://cloud.githubusercontent.com/assets/14836910/12884331/c822e49a-ce5d-11e5-9ab7-e2799bf9a901.png)

**Comment by liversedge** [comment]
There's not much I can do to help you.
Check you're running 3.3 on both PCs and check the location configured in preferences for athlete data.
Other than that it just works.

**Comment by nigelvdv** [comment]
I'll try a clean install first. I am still running 3.2 though, didn't manage to get 3.3 riunning on Ubuntu.

Thanks anyway!
