### ISSUE TITLE
Column Chooser isn't working with new Mac version

### ISSUE THREAD

**Issue by jonpanoff** [GoldenCheetah/GoldenCheetah#1839]
Is anyone else seeing this? Can drag a new column from he chooser but it doesn't add it. Have tried deleting ones already there but doesn't work either

**Comment by liversedge** [comment]
Can't recreate this at all. What version of OSX you running ?

**Comment by jonpanoff** [comment]
Running El Capitan

**Comment by jonpanoff** [comment]
Hi Mark,

I got it working. I was positioning the box and not the cursor. I stumbled across my mistake just then. Thanks for testing it out on your end..

Regards

Jonathan

**Comment by liversedge** [comment]
no probs.

**Comment by jonpanoff** [comment]
Is there an easy way to get the columns to space nicely? I am constantly dragging and adjusting them and then when I add a new column they all crunch up to the right hand side and I have to start all over again. Also on the Model section of the Activity summary my P-Max seems to be stuck at 1562W even though my Pmax of the activities are all different. What does the Pmax in the model section represent?
