### ISSUE TITLE
heart rate data not imported from suunto .sml file

### ISSUE THREAD

**Issue by panos1234** [GoldenCheetah/GoldenCheetah#1841]
Hello

When I import .sml files i don't get any heart rate data.
If i export the same activities in .fit or .gpx, i get heart rate data but speed and time moving data are incorrect.
Can you fix this problem ?

**Comment by amtriathlon** [comment]
It works with the SML files I tested, can you post sole of the failing ones to see what is the problem?

**Comment by panos1234** [comment]
Hello

I can't upload a zip file to github, so i am sending you the problem file.
This happen with my other bike workouts this week.
The previous week it was all ok, so i am guessing there is something wrong
with the file.

Thank you
Panos

**Comment by amtriathlon** [comment]
Please send it to amtriathlon at gmail dot com, thanks

**Comment by amtriathlon** [comment]
These files have R-R data but no HR data at the sample level, we would need to rebuild sample level HR from R-R data to fix this.
