### ISSUE TITLE
Document Metrics and their meaning

### ISSUE THREAD

**Issue by panos1234** [GoldenCheetah/GoldenCheetah#1850]
I am overwhelmed from the load of metrics in GC.
My understanding is that most of the metrics fall in two categories: Skiba metrics and Training Peaks metrics.
So i think it would be very practical for everybody to choose which SET OF METRICS GC will load at start up, from which the user will be able to select and create charts from.
That could be done by making the relevant selection in the option menu.

Regards

**Comment by liversedge** [comment]
Thats not really true. There are skiba and coggan stress metrics, but these account for maybe 8-10 metrics of the 260 available.

It would be good to document them all though !

**Comment by panos1234** [comment]
Another thing that would be useful, is in the curve settings menu, to groups similar items together and instead of a long list of metrics, to have submenus. For example you could group average metrics in one submenu, max metrics in another, skiba metrics in a third one etc

**Comment by liversedge** [comment]
Yeah, we're looking at a classification scheme for metrics, since so many of them are roughly equivalent. This involves identifying metrics that correlate strongly with each other...
