### ISSUE TITLE
Addview not working

### ISSUE THREAD

**Issue by ihewitt** [GoldenCheetah/GoldenCheetah#1852]
Under dev GoldenCheetah, on Linux, Qt5.5.1 the Add Chart menu from the main menu doesn't work for me. The small toolbar menu option does still work.

On my machine/config it appears that this is because the call to text() in MainWindow::addChart is returning a string with accelerator markup. (i.e. it returns "&Workout" rather than "Workout")

`if (GcWindows[i].name == action->text()) {`

Replacing this with a call to toolTip() instead returns the correct text and fixes the issue for me since this defaults to the original message text unless explicitly set.

`if (GcWindows[i].name == action->toolTip()) {`

**Comment by ihewitt** [comment]
Is this a qt5 issue? just a kde/linux issue?

**Comment by liversedge** [comment]
Never seen this.

**Comment by ihewitt** [comment]
Strange, I have had it consistently on qt5. The documentation implies this shouldn't be happening though: http://doc.qt.io/qt-5/qaction.html#QAction-1  stating that the action will use a stripped version of the text, although that's a bit vague and says that's for tool buttons.
Perhaps this is a qt bug for this version, I'll try a little test app to see what the scenarios/permutations are.

**Comment by ihewitt** [comment]
Ok, weird. It seems to happen for the actions passed via the "selected" slot, querying the menu action when it is added returns the plain text, but from the action to the slot has the accelerator.
I can reproduce in a simple application: https://gist.github.com/ihewitt/8a3e15e60e8c7f20cf22

I see the output as shown in the screenshot.
![menus](https://cloud.githubusercontent.com/assets/4063020/13301458/e84b3d58-db3c-11e5-9a28-ebc8eb184f7b.png)

**Comment by liversedge** [comment]
What I really don't understand is those texts do not have shortcuts in them, they are defined in GcWindows.cpp

**Comment by liversedge** [comment]
And I build with QT 5.5.1 on OSX and have no issues.

**Comment by liversedge** [comment]
https://bugs.kde.org/show_bug.cgi?id=345023

**Comment by ihewitt** [comment]
Aha, interesting, although that short testcase I wrote shows has nothing to do with designer. It looks like there's a deeper library issue there. I'll comment on that bug.

**Comment by liversedge** [comment]
Its the kde plugin

**Comment by ihewitt** [comment]
No, it's a KDE runtime issue, since we're not relying on the designer-or its plugin for creating the resources, we're doing it programatically both in GC and in that short testcase.
It's just that the original reporters were seeing the underlying bug exposed using the kde plugin.

So well, yes, it *is* the kde plugin, but only because there's a deeper problem. :)

**Comment by ihewitt** [comment]
ok, there's a simple workaround, adding:

```
[Development]
AutoCheckAccelerators=false
```
to ~/.config/kdeglobals 

Fixes the problem, although that does mean that anyone running on KDE will not understand why the menus aren't working and might take some time to locate the fix. :(
In the process I had the attached patch locally, which adds window manager detection, reports window manager in the version dialog, and uses the alternative text if running on KDE. just feels like a sledgehammer to a minor issue!
Patch: [wm-detect.diff](https://github.com/GoldenCheetah/GoldenCheetah/files/146863/wm-detect.txt)

**Comment by liversedge** [comment]
Why not just use the tooltip instead, or are there other issues with that?

**Comment by ihewitt** [comment]
Nope no issues - misinterpreted your comments as "this is a platform issue" so implemented a platform fix. ;)
Just feels slightly wrong doing the tooltip, after all the text() *should* work.

**Comment by liversedge** [comment]
oh lord, if the simple answer is to use the tooltip lets do that !
(and a comment to explain why text() isn't used)

:+1:

**Comment by amtriathlon** [comment]
I think this proposed solution could also be applied here, since is it is simple and safe: https://github.com/GoldenCheetah/GoldenCheetah/issues/2930#issuecomment-424902114
