### ISSUE TITLE
Training mode should disable screensaver/power saving mode

### ISSUE THREAD

**Issue by ocharles** [GoldenCheetah/GoldenCheetah#1859]
Just did a training session last night for the first time in train mode (rather than using Trainer Road). Great work! However, I found it quite difficult to complete my VO2 Max interval as 10 seconds into it my monitor turned off :)

**Comment by liversedge** [comment]
What O/S ?

**Comment by ocharles** [comment]
Windows, but for some reason you already read my mind ;)
