### ISSUE TITLE
Audio cues in train mode when entering/leaving intervals

### ISSUE THREAD

**Issue by ocharles** [GoldenCheetah/GoldenCheetah#1860]
When you're digging deep and chewing the stem in an anaerobic effort, it is very hard to know when you reach the end of the interval. It would be great if we could have some audio cues counting in and out of intervals (Trainer Road gives you a 3 on-the-second chimes).

**Comment by amtriathlon** [comment]
This was implemented by @dresco for v3.5: https://github.com/GoldenCheetah/GoldenCheetah/blob/709994c3e7fe22d65bb721b65c5b1caa91b39005/src/Train/TrainSidebar.cpp#L1804
It can be enabled in Options/Preferences:
![image](https://user-images.githubusercontent.com/1444784/86186636-f6ef4180-bb0f-11ea-95d1-e354e17a112b.png)
