### ISSUE TITLE
calDAV link not parsed/stored correctly 

### ISSUE THREAD

**Issue by KBentley57** [GoldenCheetah/GoldenCheetah#1862]
Hi all,

I'm trying to use my own caldav server for the calendar integration.  However, the link to my personal calendar contains the '@' character in the url, because of the username.  This messes with the parsing/storing for some reason.  When I use an address for a newly created test user, everything works as expected.  I thought the problem must lie somewhere in calling of the url from 

url = appsettings->cvalue(context->athlete->cyclist, GC_DVURL, "").toString();

in the CalDAV::doDownload() function, but it looks as if the url is also stored incorrectly in the user config file:

[dv]
url=http://dav.server.org/cal.php/calendars/user%40domain.com/default/
user=user@domain.com
pass=*******
type=0
googlecalid=

For example, the url as entered should be 
http://dav.server.org/cal.php/calendars/user@domain.com/default/
And is returned with error as
http://dav.server.org/cal.php/calendars/user%254domain.com/default/

and as a working example, this works fine. 
http://dav.server.org/cal.php/calendars/test/default/
username: test
password: test 

This is using GC 3.3 on linux.  Since it's not storing / parsing the url correctly, there's a good chance that it also will be messing up the username with the same symbol.

**Comment by liversedge** [comment]
@ symbols are not allowed in URLs, so they are replaced with %40.

**Comment by KBentley57** [comment]
I see.  Is there any workaround for this besides creating a new username without the @ character?
