### ISSUE TITLE
Efforts section in 3.3 - what titles mean

### ISSUE THREAD

**Issue by dragonflypl** [GoldenCheetah/GoldenCheetah#1863]
Hi,

Intervals look awesome. But what descriptions mean, e.g.:
- L5 TTE of XXX
- L6 TE Match
- L7 Match of XXX

Is there a wiki page with description? Basically what TE/TTE mean and what is the difference between MATCH entries vs OF entries.

Thanks!

**Comment by ranaalisaeed** [comment]
Any action on this?

**Comment by liversedge** [comment]
https://vimeo.com/130530369

The forum is more suited to such questions.
