### ISSUE TITLE
Unable to establish a database connection.

### ISSUE THREAD

**Issue by freekode** [GoldenCheetah/GoldenCheetah#1865]
With each start the program I have such error
```
Unable to establish a database connection.
This feature requires SQLite support. Please read the Qt SQL driver documentation for information how to build it.
Click Cancel to exit.
```
I found the same problem [here](https://groups.google.com/forum/#!topic/golden-cheetah-users/7zp-pG6rrbk) but the solution not worked to me.
Actually when I click Cancel, the program operates normally.

But today I tried to ride a workout with my trainer (which connected by ant+ stick), all ant stuff paired perfectly, but unfortunately after several seconds of workout they are disconnected. After several tryings have no success, each time the same situation.
Also workout which I downloaded and created not showing in the left list.

So may be problem with database connection some how connected with other problems.
Can you explain what should I do about database.

**Comment by liversedge** [comment]
Which release are you using?
Are you using the published builds?

**Comment by freekode** [comment]
installed from debian repo
Build date: Nov 30 2015 07:47:03
Build id: 3933
Version: 3.3.0RC1
DB Schema: 123
Metrics: 274
OS: Linux

Debian Sid

**Comment by gcoco** [comment]
Can you do an update and install the 3.3.0 release build that is in Sid?
If you are running i386 or x64 then the other fix will not work as it does not use Qt4 anymore.

**Comment by freekode** [comment]
> it does not use Qt4 anymore.
very good mention
so with my current version of GoldenCheetah I installed `libqt5sql5-sqlite` and now problem is fixed.
