### ISSUE TITLE
Combine Files Causing Crash

### ISSUE THREAD

**Issue by paulyg911gt** [GoldenCheetah/GoldenCheetah#1866]
When combining two files (in my case a Garmin file and a csv data file from my BSX) that have been imported and saved in GC, if I try to combine them using Align Using Start Time or Align Using Shared Data Series, GC crashes.  This has happened multiple times, even with a cold restart to my Windows 10 machine (win 10 fresh build, not upgraded from win 7). This has not happened until today. Here is the report from Align Using Shared Data Series crash (HR and power are common between the two files):

Cyclist: "Paul Xxxxxxxx"

Version Info

Build date: Nov 29 2015 18:32:31
Build id: 3933
Version: v3.3.0
DB Schema: 123
Metrics: 274
OS: Win
QT	5.4.2
QWT	6.1.1
GCC	4.9.2
SRMIO	yes
OAUTH	yes
D2XX	yes
QWTPLOT3D	0.3.0
KML	yes
ICAL	1.0
USBXPRESS	yes
LIBUSB	yes
Wahoo API	none
VLC	yes
VIDEO	vlc
SAMPLERATE	0.1.8
SSL	yes

Metric Log

Athlete Directory - Activities

Athlete Directory - Cache

Athlete Directory - Config

Athlete Directory - Workouts

Athlete Directory - Imports

Athlete Directory - Downloads

All Settings

CALTPOWER	255:0:255
CANTISS	0:255:255
CAPOWER	255:0:255
CATISS	255:0:255
CBALANCELEFT	178:0:0
CBALANCERIGHT	128:0:50
CCALACTUAL	0:255:0
CCALCELL	255:255:255
CCALCURRENT	10:36:106
CCALHEAD	230:230:230
CCALPLANNED	255:255:0
CCALTODAY	0:255:255
CCHROME	229:229:229
CDIAL	160:160:164
CHHB	0:127:204
CLPS	0:255:255
CLTE	0:255:255
CNPOWER	255:0:255
CO2HB	209:5:114
COLORACCEL	0:255:255
COLORAEROEL	0:255:0
COLORAEROVE	0:0:255
COLORALTITUDESHADE	192:192:192
COLORALTITUTDE	160:160:164
COLORBIKESCORE	160:160:164
COLORCADENCE	0:204:204
COLORCALENDARTEXT	0:0:0
COLORCORETEMP	255:173:92
COLORCP	255:0:0
COLORDAILYSTRESS	255:0:0
COLORGCT	255:144:0
COLORGEAR	255:144:0
COLORGRID	47:47:47
COLORHEARTRATE	255:0:0
COLORINTERVALHIGHLIGHTER	0:0:255
COLORLOAD	255:255:0
COLORLTS	0:255:0
COLORPLOTBACKGROUND	52:52:52
COLORPLOTMARKER	0:255:255
COLORPLOTSELECT	0:0:255
COLORPLOTTHUMBNAIL	160:160:164
COLORPLOTTITLE	0:0:0
COLORPLOTTRACKER	0:0:255
COLORPOWER	255:255:0
COLORRCAD	255:144:0
COLORRIDEPLOTBACKGROUND	52:52:52
COLORRIDEPLOTSYMBOLS	0:255:255
COLORRIDEPLOTXAXIS	0:255:255
COLORRIDEPLOTYAXIS	0:255:255
COLORRVERT	255:144:0
COLORSB	0:0:0
COLORSMO2	0:137:119
COLORSPEED	0:255:0
COLORSTS	0:0:255
COLORTEMPERATURE	255:255:0
COLORTHB	163:68:2
COLORTORQUE	255:0:255
COLORTRAINPLOTBACKGROUND	52:52:52
COLORTRENDPLOTBACKGROUND	52:52:52
COLORTSS	0:255:0
COLORWINDSPEED	0:128:0
COLORZONE1	255:0:255
COLORZONE10	160:160:164
COLORZONE2	42:0:255
COLORZONE3	0:170:255
COLORZONE4	0:255:128
COLORZONE5	85:255:0
COLORZONE6	255:213:0
COLORZONE7	255:0:0
COLORZONE8	160:160:164
COLORZONE9	160:160:164
CPOPUP	192:192:192
CPOPUPTEXT	255:255:255
CRIDECP	255:0:0
CRIDEGROUP	236:246:255
CRPS	255:0:255
CRTE	255:0:255
CSLOPE	0:255:0
CSPINSCANLEFT	160:160:164
CSPINSCANRIGHT	0:255:255
CTILEBAR	160:160:164
CTILEBARSELECT	255:255:0
CTOOLBAR	212:208:200
CWBAL	255:0:0
CXPOWER	255:0:255
HRCOLORZONE1	255:0:255
HRCOLORZONE10	160:160:164
HRCOLORZONE2	42:0:255
HRCOLORZONE3	0:170:255
HRCOLORZONE4	0:255:128
HRCOLORZONE5	85:255:0
HRCOLORZONE6	255:213:0
HRCOLORZONE7	255:0:0
HRCOLORZONE8	160:160:164
HRCOLORZONE9	160:160:164
chrome	Flat
font/calendar	MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0
font/calendarsize	12
font/chartlabels	MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0
font/chartlabelssize	12
font/chartmarkers	MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0
font/chartmarkerssize	12
font/default	MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0
font/defaultsize	12
font/titles	MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0
font/titlessize	12
homedirectory	C:/Users/Paul Greenberg/AppData/Local/GoldenCheetah
mainwindow/geometry	���
mainwindow/lastImportPath	F:/Dropbox/Apps/TrainerRoad
mainwindow/lastOpened	Paul Greenberg
mainwindow/lastWorkoutPath	F:/Downloads
mainwindow/state	
starthttp	true
antialias	false
dataprocess/fixderivepower/crr	0.0031
dataprocess/fixgaps/stop	1
dataprocess/fixgaps/tolerance	1
dataprocess/fixhrspikes/max	220
dataprocess/fixspeed/ma	1
dataprocess/fixspikes/max	1500
dataprocess/fixspikes/variance	1000
dataprocess/poweradjust/adjustment	0
dataprocess/torqueadjust/adjustment	0 nm
dp/Add Torque Values/apply	Manual
dp/Adjust Power Values/apply	Manual
dp/Adjust Torque Values/apply	Manual
dp/Estimate Distance Values/apply	Manual
dp/Estimate Power Values/apply	Manual
dp/Fix Elevation errors/apply	Manual
dp/Fix Freewheeling/apply	Manual
dp/Fix GPS errors/apply	Manual
dp/Fix Gaps in Recording/apply	Manual
dp/Fix HR Spikes/apply	Manual
dp/Fix Moxy/apply	Manual
dp/Fix Power Spikes/apply	Manual
dp/Fix SmO2 Anomaly/apply	Manual
dp/Fix Speed/apply	Manual
elevationHysteresis	3.
garminHWMark	25
garminSmartRecord	2
lang	en
linewidth	2
pace	false
rideBG	false
rideHead	true
rideScroll	true
rideSummaryWindow/bestsMetrics	5s_critical_power,1m_critical_power,5m_critical_power,20m_cr
shadezones	true
show/tabbar	false
swimpace	true
unit	Imperial
warnexit	true
wbal/formula	diff
workoutDir	C:/Users/Paul/AppData/Local/GoldenCheetah
devicedef1	
devicedef2	
devicename1	bsx2
devicename2	BSX
devicepostProcess1	0
devicepostProcess2	0
deviceprof1	3115d, 3115m
deviceprof2	3115m
devices	2
devicespec1	
devicespec2	
devicetype1	128
devicetype2	128
devicewheel1	2100
devicewheel2	2100
train/multi	true
id	{3d296088-fb88-49c8-886e-3c020c5bba60}
safeexit	false
upgradesuccess/folder	true
versionused	3933
blank/analysis	true
blank/train	false
ltmwindow/autofilters	Workout Code|Sport
ltmwindow/lastDateRange	{00000000-0000-0000-0000-000000000012}
mainwindow/splitterSizes/2	
splitter/LTM/hide	true
splitter/LTM/hide/0	false
splitter/LTM/hide/1	false
splitter/LTM/hide/2	false
splitter/LTM/hide/3	true
splitter/analysis/hide	true
splitter/analysis/hide/0	false
splitter/analysis/hide/1	true
splitter/analysis/hide/2	false
splitter/analysis/hide/3	true
splitter/diary/hide	true
splitter/diary/hide/0	false
splitter/diary/hide/1	false
splitter/diary/hide/2	true
splitter/train/hide	true
splitter/train/hide/0	false
splitter/train/hide/1	false
splitter/train/hide/2	false
splitter/train/hide/3	false
splitter/train/hide/4	false
splitter/train/sizes	
LTSdays	42
PMshowSBtoday	0
STSdays	7
autobackup/counter	6
autobackup/folder	Z:/Golden Cheetah Backup
autobackup/period	10
cp/useforftp	0
crankLength	170
intervals/discovery	57
navigator/groupby	-1
navigator/headings	*|Workout Code|Date|
navigator/headingwidths	0|250|250|
navigator/sortby	2
navigator/sortbyorder	0
networkfilestore/folder	
wbaltau	300
webcal_url	
wheelsize	2099
dropbox/folder	
dv/type	0
dv/url	
tp/type	5
wi/url	http://wbsapi.withings.net/

BTW, a huge thanks for writing this program. After taking the time to learn all the features of GC, I cannot go back to my WKO+3.

Thanks,

Paul

**Comment by liversedge** [comment]
Can you send me the two files, would be good to try and recreate?

liversedge gmail com

**Comment by paulyg911gt** [comment]
Mark:

Please see attached. Both the original files and the GC files.  And no
laughing at my meager power  ;-).  I found that if I combined using same
start time it would combine. If I moved the time slider, it would crash.

Best Regards,

Paul



On Sun, Feb 28, 2016 at 4:51 PM, Mark Liversedge <notifications@github.com>
wrote:

> Can you send me the two files, would be good to try and recreate?
>
> liversedge gmail com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoldenCheetah/GoldenCheetah/issues/1866#issuecomment-189951319>
> .
>



-- 
Paul S. Greenberg
30 Owenoke Park
Westport, CT 06880
(203) 454-4731 Home
(203) 253-7436 Mobile

**Comment by paulyg911gt** [comment]
Mark:

Here are the two sets of files, the 2 raw data files and the 2 GC files.

Best Regards,

Paul
[2016_02_28_12_33_11.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/150156/2016_02_28_12_33_11.zip)
