### ISSUE TITLE
Improper weight/height conversion when switching units

### ISSUE THREAD

**Issue by jeffbromberger** [GoldenCheetah/GoldenCheetah#1868]
My units started as metric after installation and my weight was 83.5kg.  Height was 193cm.  I selected imperial units and was prompted to have GC restart.  After restarting the units were imperial but the numbers had been "double converted".  For example, I was listed at 405.9lbs.  405.9lbs is 184.1kg.  And 184.1lbs is 83.5kg.  The same thing happened with my height which ended up at 29.9in.

**Comment by gcoco** [comment]
What OS? Which version of GC are you running?

**Comment by jeffbromberger** [comment]
Win 10 x64, latest version of GC.  Had it happen on two machines with that
same config so I think it should be easy to repro.  Let me know if I can
supply any more info.

**Comment by liversedge** [comment]
a) GC does not restart for units conversion, it restarts for change of language only
b) all data is stored in metric units regardless of the setting

If you enter imperial units when metric are selected you will experience the "issue" you describe.

**Comment by jeffbromberger** [comment]
a) is incorrect.  I have done this multiple times including again just now.


1) I launch GC (currently my units are imperial and my weight/height are
correct)
2) I go to Tools->Options and on the general tab select "Metric" for unit.
3) I hit Save
4) GC immediately pops up prompting to restart

restarts...

1) I go to Tools->Options then Athlete then Measures and now I am 37.9kg
and 490.2cm

So this "issue" is real.

**Comment by jeffbromberger** [comment]
Just fyi, GC is prompting to restart on many more things than just
language.  I changed my weight from 184.3 to 184 and it is asking me to
restart.  The message is also bizarre and perhaps points to the real bug.
It says "You changed the location of the athlete library" which of course I
did not.

**Comment by liversedge** [comment]
Thats more likely.

Set the athlete library field to the location of your athletes and save.
See if it keeps asking to restart from that point on.

Are you running 3.3 ?

Mark

**Comment by jeffbromberger** [comment]
By setting that location and saving, and restarting, it now no longer asks
me to restart after each change.  BUT, the conversion issue still exists.
I start with Imperial and height of 76 inches.  I select metric and save.
Then I go back to my athlete measures and my height is 490.2cm.  As a user
I would expect an auto-conversion from 76" to 193cm.  Or, less good but
still understandable would be if the scalar stayed the same and I was now
76cm instead of 76".  But 490.2cm is certainly not correct.

**Comment by liversedge** [comment]
What version are you running?

**Comment by jeffbromberger** [comment]
3.3

**Comment by liversedge** [comment]
OK, there are 2 issues here:

1) when no athlete directory is set the preferences panel thinks it has changed when you press save
2) when changing unit preferences AND the measures values for the athlete the conversion is borked.

For (1) just fill in the athlete directory as a workaround (we can fix this separately)

For (2) Change the unit preferences and save, go back and change the weight/height measures in the units and press save. DON'T CHANGE UNIT PREFS AND WEIGHT/HEIGHT AT THE SAME TIME. (we can fix this too).

Mark

**Comment by jeffbromberger** [comment]
Just to be clear though, I see the incorrect measures after only having changed the unit preferences.  I.e. it doesn't first get messed up when I do both, it is simply the changing of the unit preference that immediately shows incorrect values for the measures.  Also, if I then change back to the original unit preference - again without touching any measures - then my original numbers are back to being correct.  So the "double conversion" seems to happen in both directions and correctly unroll itself at least.

I don't need a workaround for my own personal usage, I was simply reporting this to be helpful so you guys would know about it.

**Comment by liversedge** [comment]
Yes, you are correct (!)

If you go back and forth in two subsequent updates you end up with the value you started with.
It seems to be converting twice.

Hmmm.

Mark
