### ISSUE TITLE
There is no way to clear the blue line in the performance chart before starting a new workout

### ISSUE THREAD

**Issue by brettacook** [GoldenCheetah/GoldenCheetah#1874]
When starting a new workout, the blue line on the performance chart (which I believe is the previous workout) stays on the screen.  Since the line is persistent, it continues to get more and more cluttered with successive workouts.  There should be a way to remove this line before starting a workout (all other lines are cleared when a new workout is started).  Attached is a screenshot of the blue line that won't go away.
My thought is either a pull-down item in the view menu to reset this value, or some other way to clear it.  I believe the only way currently available is to exit GoldenCheetah and restart - which just seems very clunky.
![goldencheetahblueline](https://cloud.githubusercontent.com/assets/16944189/13555502/445e6bac-e37f-11e5-9bb0-6aba0900c6a7.jpg)

**Comment by amtriathlon** [comment]
I am closing this since it refers to a very old version. Please reopen if you can recreate when v3.5
