### ISSUE TITLE
PMC Data not refreshed when overriding the metric used

### ISSUE THREAD

**Issue by Whittaker555** [GoldenCheetah/GoldenCheetah#1883]
I have managed to manually input a estimated trimp figure for an event but this seems to not affect the PMC(trimp) chart. Is it going to be possible for me to do this and have it represented on the PMC?

Thanks!

**Comment by amtriathlon** [comment]
You need to override the "TRIMP Points" metric which is the base of PMC(TRIMP), for how to do this see the FAQ: https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-METRICS#how-do-i-add-a-metric-to-the-details-screen-so-i-can-override-it-

**Comment by Whittaker555** [comment]
Sorry I have done this but it doesn't affect the PMC =/ 

(sorry amtriathlon i didn't word my post very clearly)

**Comment by liversedge** [comment]
The PMC computation isn't invalidated when you override a metric.
If you restart GC it will get refreshed.

**Comment by Whittaker555** [comment]
All sorted! Thanks!

**Comment by liversedge** [comment]
re-opened as the problem needs to be fixed :)

**Comment by liversedge** [comment]
was fixed!
