### ISSUE TITLE
Separate LTHR per sport

### ISSUE THREAD

**Issue by prokoudine** [GoldenCheetah/GoldenCheetah#1884]
Joe Friel recommends (http://home.trainingpeaks.com/blog/article/joe-friel-s-quick-guide-to-setting-zones) measuring LTHR for each sport and using slightly differently calculated heart rate zones for running and cycling accordingly. It would be great to have that supported in GC.

**Comment by amtriathlon** [comment]
Fixed https://github.com/GoldenCheetah/GoldenCheetah/pull/1956
