### ISSUE TITLE
Garmin swim file issue

### ISSUE THREAD

**Issue by Ankok** [GoldenCheetah/GoldenCheetah#1885]
Hi,

I have a Garmin Fenix 2 and started swimming recently. When I import the indoor swim files into GC on my Mac all time and distance info is lost. If I import the file into GC as a .tcx I get time and speed, but it takes minutes as seconds so I swim world records.
How can I fix this? Attached an example of a fit file.

[2016-03-12-14-27-17-Zwembad.fit.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/172813/2016-03-12-14-27-17-Zwembad.fit.zip)

**Comment by amtriathlon** [comment]
This fit file can be imported to GC, but you need to enable "Garmin Smart Recording" and set threshold to 25sec or higher, see https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Preferences_General
