### ISSUE TITLE
Bug: Incorrect / miss-labelled data fields when export to .fitlog and .tcx

### ISSUE THREAD

**Issue by tfk2** [GoldenCheetah/GoldenCheetah#1888]
v3.3.0 build 3933

1. I import sm02 from bsx's csv file
2. Data seems ok in GC: SM02 + HR 
3. I export either .fitlog or .tcx from GC
4. When I look at .fitlog or .tcx they both only seem to contain HR data ( I assume it is SM02 mislabelled).

**Comment by liversedge** [comment]
Do either file formats support smo2 data?

**Comment by tfk2** [comment]
got me there. don't know sorry.

even if they don't, it would still be putting the wrong measure in the wrong place?
I wanted to export a FIT file but that's not possible in GC right? 
FIT files DO support smot/tHb - albeit not officially I believe (eg Moxy FIT files)

I am looking at the .fitlog/.tcx with 3rd party software. Error could be with their import. I have already asked that.

**Comment by liversedge** [comment]
you can't export smo2 in current file formats except .FIT.
it would be great if we could, but thats a lot of work since they only have a tainted SDK for mac/win (and not linux/bsd etc)
