### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by AartGoossens** [GoldenCheetah/GoldenCheetah#1898]
I want to start working on a Dutch translation for GC.
I already found the `src/Resources/translations/gc_...` and I will start by creating a `gc_nl.ts` file. Are there any other files that should be added/updated to make this work?

**Comment by amtriathlon** [comment]
Hi, in this commit you can see what to change to add a new language to v3.3:
https://github.com/GoldenCheetah/GoldenCheetah/pull/1552/commits/33016507ebc5b37e130dc725f8bc6188af75f459
This one is what to add for v4.0:
https://github.com/GoldenCheetah/GoldenCheetah/commit/454790a5ca0ad064619deeafddd1568dadbd5a82

**Comment by AartGoossens** [comment]
Thanks @amtriathlon that really helps
