### ISSUE TITLE
Google Map

### ISSUE THREAD

**Issue by Haas01** [GoldenCheetah/GoldenCheetah#1901]
[Haas_GC_crash.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/188549/Haas_GC_crash.txt)

Google Map: Reproducible crash when clicking on the track...

Michael Haas

**Comment by liversedge** [comment]
closed by owner

**Comment by liversedge** [comment]
? Why do you keep opening and closing this report ?

**Comment by Haas01** [comment]
Sorry, unwanted...
