### ISSUE TITLE
`Auto-Hide` training controls scrolls training view upwards on hide

### ISSUE THREAD

**Issue by jackson15j** [GoldenCheetah/GoldenCheetah#1902]
Seen this issue in February development release of v4.0. If you have the default training layout, enable `auto-hide`, queue a video+erg file and scroll the training window down to see video+workout; the windows jumps up by the the size of the training controls when they do hide. ie. On hide, it jumps up so you the workout pane is off the bottom of the window.

Reproduction:
- Surface 3 (Windows 10), GoldenCheetah_v4.0-DEV1602_64bit_Win.zip unpacked.
- Reset Training layouts.
- Configure trainer & add both a workout & video.
- Select, workout & video and then scroll training window so (Video & Workout panes are in view).
- Enable `auto-hide` of controls.
- Start workout.
- When controls hide, the training window scrolls up so that the workout pane is off the bottom of the window.
- Attempting to scroll the window down will un-hide the controls.
- Repeats above issue on subsequent hides.

**Comment by amtriathlon** [comment]
I am closing this since it refers to a very old version. Please reopen if you can recreate when v3.5
