### ISSUE TITLE
Multiple activities on the same day

### ISSUE THREAD

**Issue by panos1234** [GoldenCheetah/GoldenCheetah#1906]
I don't know if it has been reported in the past but i noticed that when you have multiple activities on the same day:
1. In the Diary > Activity summary you can only see the summary of the first activity of the day.
2. Moreover, in the Diary > Calendar view, if you have allocate a color background for each sport type, the calendar day background color is set according to the first activity of the day and you can't distinguish days with multiple types of activities.

**Comment by liversedge** [comment]
That's right. Its just one of those things, there are no plans to change it.
