### ISSUE TITLE
Provide Linux AppImage

### ISSUE THREAD

**Issue by probonopd** [GoldenCheetah/GoldenCheetah#1913]
Given that you provide binaries for Windows and OS X but not for Linux yet I thought maybe you'd be interested in distributing GoldenCheetah in the AppImage format. It lets you package once and reach users on all major desktop distributions.

The key idea of the AppImage format is one app = one file. Every AppImage contains an app and all the files the app needs to run. In other words, each AppImage has no dependencies other than what is included in the targeted base operating system(s).

For more information, have a look at http://appimage.org/ and check e.g., https://github.com/probonopd/AppImages/blob/master/recipes/subsurface/Recipe

**Comment by amtriathlon** [comment]
Thanks for the heads up, I think the capacity to access serial devices without changes to source code nor libraries and the ability to upload a self-contained file for users to simply download and execute can be very useful for this project!
For initial testing I'm using the attached script after a standard Linux build on current master:
[linux-deploy.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/1916387/linux-deploy.txt)
First tests, including download from a servial device (PowerTap Cervo) seem to be working on Ubuntu 16.04

**Comment by probonopd** [comment]
Thanks @amtriathlon, it would be cool if someone could add this to https://github.com/GoldenCheetah/GoldenCheetah/blob/master/.travis.yml. Could even use https://github.com/probonopd/uploadtool to upload each build to GitHub Releases.

**Comment by amtriathlon** [comment]
Thanks, currently we are not using Travis for Linux build, only for MacOS, we should fix this but for now I will put the deploy script on travis/linux
Another problem we need to solve is to bundle python 3.6 since the version under development adds a Python chart using embedding. Do you have some pointer about how to bundle python on the AppImage?

**Comment by probonopd** [comment]
For Python, please see https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps

**Comment by amtriathlon** [comment]
Thanks, I will give it a try soon.
For now an AppImage for the last development build is attached to the release (https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/v3.5-DEV1804), it's generated on Ubuntu 16.04 and it seems to work also on 17.10, but not on 14.04 or previous.
We need to do more testing.

**Comment by probonopd** [comment]
Can you please make one on 14.04? That way it will run on all still-supported Ubuntu releases. Thanks.

**Comment by amtriathlon** [comment]
The PR which closes the issue does it, it uses Trusty on Travis-ci for that purpose.

**Comment by probonopd** [comment]
Thank you very much @amtriathlon :+1:
