### ISSUE TITLE
SML Import

### ISSUE THREAD

**Issue by look241** [GoldenCheetah/GoldenCheetah#1916]
Can anyone enlighten me as to how to import from my Ambit. For the life of me i cannot see how this is achieved. 
I am using Mac.
I can import file from my Garmin device but when i connect my watch there is no file to browse to as the watch does not connect as a device for me to view even though movescount sees it as connected

**Comment by amtriathlon** [comment]
After Moveslink finish syncing.the SML files should be on:

Windows:
C:\Users{username}\AppData\Roaming\Suunto\Moveslink2
Note: You may have to enable the show hidden files option in Windows Explorer.

Mac:
Under your home directory:
~/Library/Application Support/Suunto/Moveslink2
