### ISSUE TITLE
Couple of issues in Trends Tracker screen

### ISSUE THREAD

**Issue by jeffbromberger** [GoldenCheetah/GoldenCheetah#1917]
I have my units set to imperial and my weight is 184 lbs, for example.  In the Tracker screen it shows (kg) as the label but still shows 184.  This should either, ideally, be labeled (lbs) or worst case print my weight in kg.  Also, the Distance shows (kg) but is listing the numeric value for miles.  Bottom line, it seems as though just the (unit) text needs to change, not the values.

One other thing on this screen... when I select the "This week" data range it shows a row for Mar 2016 and Apr 2016, which makes sense since the week spanned both months.  But when I select "This month" it shows no rows at all.  The April data from the "This week" results should at least be showing in the "This month" results, no?   As another data point, when I select "This year" it shows Jan, Feb, Mar and Apr as expected.

**Comment by jeffbromberger** [comment]
This is the latest version 3.3 Nov 29 2015, running on Win 10 x64...

**Comment by liversedge** [comment]
You should edit the labels. They are user definable.
