### ISSUE TITLE
aPower missing in user formulas

### ISSUE THREAD

**Issue by fabrylama** [GoldenCheetah/GoldenCheetah#1928]
Hi, I would like to add an user formula to plot the difference between power and aPower (or the ratio), but I can't find aPower in the available metrics. 

Thanks

**Comment by liversedge** [comment]
Please use the user forums for questions. this is a bug tracking system.
https://groups.google.com/forum/#!forum/golden-cheetah-users

**Comment by fabrylama** [comment]
Sorry about that, I genuinely thought it was a bug.
