### ISSUE TITLE
Can't install v4.0-DEV1603 on Debian Sid

### ISSUE THREAD

**Issue by freekode** [GoldenCheetah/GoldenCheetah#1929]
GoldenCheetah requires libical1, but it is not available
```
$ sudo apt-get install libical1
...
Package libical1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libical1a:i386 libical1a

E: Package 'libical1' has no installation candidate

```
I installed libical1a, unfortunately problem didn't resolved.

**Comment by gcoco** [comment]
Even though this is build with a static libical I left the libical1 in the control file.
You can fix this by doing the following from a terminal window where the deb file is downloaded.
```
dpkg-deb -R GoldenCheetah_v4.0-DEV1603*.deb gc-deb
sed -i "s|libical1, ||" gc-deb/DEBIAN/control
dpkg-deb -b gc-deb GoldenCheetah_v4.0-DEV1603.deb
```
Then install the GoldenCheetah_v4.0-DEV1603.deb file that was created.

**Comment by freekode** [comment]
Thanks a lot, working!
