### ISSUE TITLE
Multiple Activity Import - First One Always Collapsed

### ISSUE THREAD

**Issue by linalan** [GoldenCheetah/GoldenCheetah#1930]
Cosmetic Bug - "Import from file" .. multiple activities, the first one chronologically always ends up collapsed while the rest are expanded. See April 7, 2016 in screenshot. Imported activities from the 7th thru the 17th and the 7th is the only one collapsed. 

V3.3
Build 3933
OS X 10.11.4

<img width="227" alt="collapsed" src="https://cloud.githubusercontent.com/assets/18307112/14603099/6f8f651a-059e-11e6-89ea-bbe585251225.png">

**Comment by amtriathlon** [comment]
I think this is the same as https://github.com/GoldenCheetah/GoldenCheetah/issues/3074, let's keep just one open for tracking.
