### ISSUE TITLE
Toolbar Disappears

### ISSUE THREAD

**Issue by linalan** [GoldenCheetah/GoldenCheetah#1931]
Toolbar disappears when going full screen, yet View > Show Toolbar is still enabled. 

When returning to non-fullscreen, the toolbar is still missing even though enabled. Have to manually disable and then re-enable View > Show Toolbar before the toolbar returns. 

Not sure what the expected behavior is here. I would think that when going fullscreen, GC should toggle the toolbar off assuming it was enabled to begin with. Then when returning to non-fullscreen, turn it back on. 

GC v3.3
Build 3933
OS X 10.11.4

<img width="935" alt="notoolbar" src="https://cloud.githubusercontent.com/assets/18307112/14603486/7f427036-05a0-11e6-83e3-21e559c7a81a.png">

**Comment by liversedge** [comment]
Its by design to avoid a QT fullscreen bug.

**Comment by liversedge** [comment]
The m,
