### ISSUE TITLE
Font Spacing/Sizing Issue

### ISSUE THREAD

**Issue by linalan** [GoldenCheetah/GoldenCheetah#1932]
Cosmetic Bug 
System language is zh-tw. GC is set to use English. I tried changing the system language to English followed by a reboot, but the result was the same. 

<img width="502" alt="prefs1" src="https://cloud.githubusercontent.com/assets/18307112/14603867/e123dad6-05a2-11e6-9c50-6424149afa12.png">

<img width="517" alt="prefs2" src="https://cloud.githubusercontent.com/assets/18307112/14603873/e73c41c4-05a2-11e6-8fb0-5ab3163eee2c.png">

<img width="333" alt="aboutgc" src="https://cloud.githubusercontent.com/assets/18307112/14603887/fbf58d64-05a2-11e6-861a-cb7fbfd613fc.png">

**Comment by bdb** [comment]
You are probably on a Retina display. GC does not have official HiDPI support. See #1420 and #1660.

**Comment by liversedge** [comment]
This is fixed with 3.4 and native support for scaling.
