### ISSUE TITLE
Config of Mapquest API Key

### ISSUE THREAD

**Issue by sto1** [GoldenCheetah/GoldenCheetah#1934]
At the moment the request for the elevation correction gives allways 0. (in springtime a lot of people bike)
would it be possibe to make the mapquest key a config in the runtime rather than in the precompilation file 
gcconfig.pri
// Free API key at https://developer.mapquest.com/.
// You can then add it to gcconfig.pri
Would help a lot.

**Comment by nigelvdv** [comment]
Is there a maximum amount of corrections you can perform? I did the elevation correction with a postprocess filter for all my activities year by year. Initially this went well, but for the last batches I seem to get 0 elevation gain for each activity.
Using GC Dev 1705 on Linux Mint 18.1.

**Comment by liversedge** [comment]
Yes the API has a limit, adding your own key via prefs is not possible at this point.
