### ISSUE TITLE
Crash on new Linux build

### ISSUE THREAD

**Issue by cwwees** [GoldenCheetah/GoldenCheetah#1941]
Newly upgraded Lubuntu to xenial and GoldenCheetah is in apt-get, auto-upgrade to 3.3.0RC1.  Been using for three years or more and happy to see the new version to match Windows (I switch between computers).  This version crashes as soon as I press any menu to change to any other window.  I can upload a file (or multiple files) and use | Activities | Summary just fine.  Any other display I pick causes it to crash.  

Sample crash file pasted below, though I don't understand what it tells us about what went wrong.  I continue to use the current GC on Windows with the same data.  I generated a new athlete and imported all my files (I have backups of the original Garmin files before GC reads them).  Same symptoms in each case.

Charlie

Cyclist: "Charlie Weesner"

Version Info

Build date: Mar 22 2016 20:14:23
Build id: 3933
Version: 3.3.0RC1
DB Schema: 123
Metrics: 274
OS: Linux
QT  5.5.1
QWT 6.1.1
GCC 5.3.1
SRMIO   none
OAUTH   yes
D2XX    none
QWTPLOT3D   0.2.6
KML yes
ICAL    1.0
USBXPRESS   none
LIBUSB  yes
Wahoo API   none
VLC yes
VIDEO   vlc
SAMPLERATE  none
SSL yes

Metric Log

METRIC REFRESH STARTS: Mon Apr 25 20:52:01 2016
Opening ride: 2016_04_25_17_34_15.json
File open completed: 2016_04_25_17_34_15.json
Getting weight: 2016_04_25_17_34_15.json
Updating statistics: 2016_04_25_17_34_15.json
COMMIT: Mon Apr 25 20:52:01 2016
OPTIMISE: Mon Apr 25 20:52:01 2016
SIGNAL DATA CHANGED: Mon Apr 25 20:52:01 2016
METRIC REFRESH ENDS: Mon Apr 25 20:52:02 2016
Athlete Directory - Activities

Athlete Directory - Cache

Athlete Directory - Config

Athlete Directory - Workouts

Athlete Directory - Imports

Athlete Directory - Downloads

All Settings

CALTPOWER   255:0:255
CANTISS 0:255:255
CAPOWER 255:0:255
CATISS  255:0:255
CBALANCELEFT    178:0:0
CBALANCERIGHT   128:0:50
CCALACTUAL  0:255:0
CCALCELL    255:255:255
CCALCURRENT 143:178:207
CCALHEAD    230:230:230
CCALPLANNED 255:255:0
CCALTODAY   0:255:255
CCHROME 229:229:229
CDIAL   160:160:164
CLPS    0:255:255
CLTE    0:255:255
CNPOWER 255:0:255
COLORACCEL  0:255:255
COLORAEROEL 0:255:0
COLORAEROVE 0:0:255
COLORALTITUDESHADE  192:192:192
COLORALTITUTDE  160:160:164
COLORBIKESCORE  160:160:164
COLORCADENCE    0:204:204
COLORCALENDARTEXT   0:0:0
COLORCP 255:0:0
COLORDAILYSTRESS    255:0:0
COLORGRID   47:47:47
COLORHEARTRATE  255:0:0
COLORINTERVALHIGHLIGHTER    0:0:255
COLORLOAD   255:255:0
COLORLTS    0:255:0
COLORPLOTBACKGROUND 52:52:52
COLORPLOTMARKER 0:255:255
COLORPLOTSELECT 0:0:255
COLORPLOTTHUMBNAIL  160:160:164
COLORPLOTTITLE  0:0:0
COLORPLOTTRACKER    0:0:255
COLORPOWER  255:255:0
COLORRIDEPLOTBACKGROUND 52:52:52
COLORRIDEPLOTSYMBOLS    0:255:255
COLORRIDEPLOTXAXIS  0:255:255
COLORRIDEPLOTYAXIS  0:255:255
COLORSB 0:0:0
COLORSPEED  0:255:0
COLORSTS    0:0:255
COLORTEMPERATURE    255:255:0
COLORTORQUE 255:0:255
COLORTRAINPLOTBACKGROUND    52:52:52
COLORTRENDPLOTBACKGROUND    52:52:52
COLORTSS    0:255:0
COLORWINDSPEED  0:128:0
COLORZONE1  255:0:255
COLORZONE10 160:160:164
COLORZONE2  42:0:255
COLORZONE3  0:170:255
COLORZONE4  0:255:128
COLORZONE5  85:255:0
COLORZONE6  255:213:0
COLORZONE7  255:0:0
COLORZONE8  160:160:164
COLORZONE9  160:160:164
CPOPUP  192:192:192
CPOPUPTEXT  255:255:255
CRIDECP 255:0:0
CRIDEGROUP  236:246:255
CRPS    255:0:255
CRTE    255:0:255
CSPINSCANLEFT   160:160:164
CSPINSCANRIGHT  0:255:255
CTILEBAR    160:160:164
CTILEBARSELECT  255:255:0
CTOOLBAR    242:241:240
CWBAL   255:0:0
CXPOWER 255:0:255
HRCOLORZONE1    255:0:255
HRCOLORZONE10   160:160:164
HRCOLORZONE2    42:0:255
HRCOLORZONE3    0:170:255
HRCOLORZONE4    0:255:128
HRCOLORZONE5    85:255:0
HRCOLORZONE6    255:213:0
HRCOLORZONE7    255:0:0
HRCOLORZONE8    160:160:164
HRCOLORZONE9    160:160:164
chrome  Flat
font/calendar   Ubuntu,8,-1,5,50,0,0,0,0,0
font/calendarsize   8
font/chartlabels    Ubuntu,8,-1,5,50,0,0,0,0,0
font/chartlabelssize    8
font/chartmarkers   Ubuntu,8,-1,5,50,0,0,0,0,0
font/chartmarkerssize   8
font/default    Ubuntu,8,-1,5,50,0,0,0,0,0
font/defaultsize    10
font/titles Ubuntu,8,-1,5,50,0,0,0,0,0
font/titlessize 10
homedirectory   /home/cwwees/.goldencheetah
mainwindow/geometry #���
mainwindow/lastImportPath   /media/cwwees/GARMIN/Garmin/Activities
mainwindow/lastOpened   Charlie Weesner
mainwindow/state  
antialias   true
bikeScoreDays   50
bikeScoreMode   manual
dataprocess/fixgaps/stop    1
dataprocess/fixgaps/tolerance   1
dataprocess/fixhrspikes/max 220
dataprocess/fixspikes/max   1500
dataprocess/fixspikes/variance  1000
dataprocess/torqueadjust/adjustment 0 nm
dp/Adjust Torque Values/apply   Manual
dp/Fix GPS errors/apply Manual
dp/Fix Gaps in Recording/apply  Manual
dp/Fix HR Spikes/apply  Manual
dp/Fix Power Spikes/apply   Manual
elevationHysteresis 3.
garminHWMark    25
garminSmartRecord   2
lang    en
linewidth   0.5
rideBG  false
rideHead    true
rideScroll  true
show/tabbar false
unit    Imperial
wbal/formula    diff
workoutDir  /home/cwwees/.goldencheetah
devices 0
train/multi false
id  {77d659ed-18bc-404b-bb4f-8105ebd13587}
safeexit    false
upgradesuccess/folder   true
versionused 3933
ltmwindow/autofilters   Workout Code|Sport
ltmwindow/lastDateRange {00000000-0000-0000-0000-000000000007}
mainwindow/splitterSizes/2  
mainwindow/splitterSizes/8  
splitter/LTM/hide   true
splitter/LTM/hide/0 false
splitter/LTM/hide/1 false
splitter/LTM/hide/2 true
splitter/LTM/hide/3 false
splitter/LTM/hide/4 true
splitter/LTM/hide/5 false
splitter/LTM/sizes  
splitter/analysis/hide  true
splitter/analysis/hide/0    false
splitter/analysis/hide/1    true
splitter/analysis/hide/2    false
splitter/analysis/hide/3    true
splitter/diary/hide true
splitter/diary/hide/0   false
splitter/diary/hide/1   false
splitter/diary/hide/2   true
splitter/train/hide true
splitter/train/hide/0   false
splitter/train/hide/1   false
splitter/train/hide/2   false
splitter/train/hide/3   false
LTSdays 42
PMshowSBtoday   0
STSdays 7
crankLength 150
navigator/groupby   -1
navigator/headings  *|Date|TSS|
navigator/headingwidths 0|136|55|
navigator/sortby    2
webcal_url  
wheelsize   2100
dv/url  
tp/type 0
wi/url  http://wbsapi.withings.net/

**Comment by amtriathlon** [comment]
I'm closing this since it applies to a very old version, please try the last one and see https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md
