### ISSUE TITLE
SML import - HR data lost

### ISSUE THREAD

**Issue by henolo** [GoldenCheetah/GoldenCheetah#1945]
When I import SML files the heart rate data disappears.
It is in the file since it appears in movescount. But in GC it is gone.
![hr gone](https://cloud.githubusercontent.com/assets/15927134/14944043/fa466268-0fe8-11e6-8311-9ceb1f1d2877.png)
rgs
Henrik

**Comment by amtriathlon** [comment]
AFAIK this happens when HR is not available at the sample level but only as R-R data at the end of the file, can you confirm if this is the case or to upload a sample file?

**Comment by henolo** [comment]
Yes there is R-R HR data in the file. So apparently no GC code that reads and interprets R-R time intervals. Conceptually it should not be very complicated - it is just the time between consecutive heart beats, but the FIT file format might make this messy anyway. 
/Henrik

**Comment by henolo** [comment]
Now realized that this is a duplicated of issue 1841

**Comment by amtriathlon** [comment]
Yes, the code in GC only handles HR when it comes at sample level, which was the case with Ambit 2 files I had for testing, R-R data could be backfilled when available but we should do some kind of filtering to reduce variability. I will give it a try.

**Comment by amtriathlon** [comment]
Henrik, I've added code to master to use R-R to backfill HR data, it is tested using a contributed file but, if you can do more testing it would be useful.

**Comment by henolo** [comment]
Unfortuantely I am still a newbie on how to handle git and being able to run stuff that don't have an installer. But I guess there have never been a better time to start to learn so downloaded github but have not figured it all out yet...

Anyway I can read code so just analysing instead.

Low bpm handling
There might be a problem when HR is below 60 bpm, (R-r is above 1 second). Then there probably might not be a HR value for the one or two samples inbetween: timeIndex(secs+1) and timeindex(secs+2).

This depends on how randomly missing HR values are handled. Usually one get noise but in GC I don't know what happens...

Very low bpm might not be a problem for most people but very well trained people do have remarkably low bpms. Especially if they are looking for their rest value. In wikip they state 33 bpm as a minimum, but with added variability I guess that one need to handle below 30 bpm to be truly safe, (R-R>2sec). Ie need to handle two "copy" bpm:s inbetween samples. https://en.wikipedia.org/wiki/Heart_rate#Resting_heart_rate

Something like this might do it (instead of new rows 281-283):

if (secs + rr >= trunc(secs) + 1.0) {
                rideFile->setPointValue(rideFile->timeIndex(secs), rideFile->hr, round(60.0/ ewmaRR));
            }
if (secs + rr >= trunc(secs) + 2.0) {
                rideFile->setPointValue(rideFile->timeIndex(secs+1), rideFile->hr, round(60.0/ ewmaRR));
            }
if (secs + rr >= trunc(secs) + 3.0) {
                rideFile->setPointValue(rideFile->timeIndex(secs+2), rideFile->hr, round(60.0/ ewmaRR));
            }

rgs
Henrik

**Comment by amtriathlon** [comment]
Good observation, I've changed to account for this: https://github.com/GoldenCheetah/GoldenCheetah/pull/1950/commits/42b8f043d83b4f53eb4ae72c7e7f608e80dd6533, thanks!

**Comment by henolo** [comment]
Yes this was a good place for a for-loop…

Great!

Henrik

 

Från: Alejandro Martinez [mailto:notifications@github.com] 
Skickat: den 4 maj 2016 02:25
Till: GoldenCheetah/GoldenCheetah
Kopia: henolo; Author
Ämne: Re: [GoldenCheetah/GoldenCheetah] SML import - HR data lost (#1945)

 

Good observation, I've changed to account for this:  <https://github.com/GoldenCheetah/GoldenCheetah/pull/1950/commits/42b8f043d83b4f53eb4ae72c7e7f608e80dd6533> 42b8f04, thanks!
