### ISSUE TITLE
1604 crash on OS X

### ISSUE THREAD

**Issue by thompsar** [GoldenCheetah/GoldenCheetah#1947]
Installed 1604 build and everything worked fine. Attempted to set the path for R in user preferences (and probably assigned the wrong path), restarted golden cheetah and now 1064 will not start up (bounces once in the doc and disappears). 

5/3/16 11:26:04.618 AM com.apple.xpc.launchd[1]: (Personal.GoldenCheetah.256352[707]) Service exited with abnormal code: 2

Reverting to 1603 works just fine. 

I tried installing everything fresh by renaming ~/Library/GoldenCheetah to no avail, is there a hidden file somewhere with this faulty R path, or is that a red herring?

**Comment by liversedge** [comment]
please use the forums to discuss.
start with --no-r to disable R and correct the path setting.
use R to find the right value:

> print(R.home())
> q()

**Comment by thompsar** [comment]
Apologies, I didn't know if here or there was the correct place to report this.

**Comment by liversedge** [comment]
no worries!
