### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by nenadjev** [GoldenCheetah/GoldenCheetah#1948]
#I run v4.0-DEV1604_64bit_Win, but after I set R installation Directory I can't to start GC. I got messege Fatal error: unable to open base package.

**Comment by liversedge** [comment]
see https://github.com/GoldenCheetah/GoldenCheetah/issues/1947

**Comment by liversedge** [comment]
please use forums for dev build queries. thank.

**Comment by nenadjev** [comment]
I solved.
Sorry for mistake.

Regards

**Comment by liversedge** [comment]
no bother.. remember to share any interesting scripts :)
