### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by nenadjev** [GoldenCheetah/GoldenCheetah#1952]
crach, GoldenCheetah_v4.0-DEV1604
[GC cr.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/250257/GC.cr.txt)

**Comment by amtriathlon** [comment]
I'm closing this since it applies to a very old dev version, please try the last one and see https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md
