### ISSUE TITLE
Weight tab

### ISSUE THREAD

**Issue by nal3x** [GoldenCheetah/GoldenCheetah#1954]
It would be great if there was a tab under the Athlete menu (in Options) in which the user could save his weight values for different time periods. Just like in Power and Heartrate Zones tabs. Then, these weight values could be used to calculate w/kg for each activity, instead of having the user enter a weight value each time he imports an activity (or let goldencheetah use the default weight value). 

I think this would be also helpful in case a user imports separate weight values from a file. These values could be saved in this tab, and all his activities would have the correct weight value for the corresponding time period. 

Also, as soon as the above does not currently exist, it would be useful if gc didn't read the default weight value when an activity is imported and the user has not entered a new weight value. Instead gc could read the last nonzero weight value from the most recent activities.

**Comment by MaksVasilev** [comment]
I approve and join to request for add weght history statistic.

**Comment by MaksVasilev** [comment]
Between: Garmin Edge 1000 activites in FIT file have short athletes profile with weight. I debug fit file from my Edge 1000 and have Age, Sex, Weight, Height, MaxHR, MaxHR for Bike.

Maybe autoimport Weight data from activites if have it?

**Comment by MaksVasilev** [comment]
Garmin Edge 1000 FIT file with Weight info: http://velo100.ru/files/2016-04-13-15-33-17.fit_.zip

**Comment by amtriathlon** [comment]
I think we could leverage on the existing Withings cache as backend and to add a UI like requested to Measures tab, including an option to import from a CSV as requested in https://github.com/GoldenCheetah/GoldenCheetah/issues/2284
