### ISSUE TITLE
GC Dropbox integration is broken

### ISSUE THREAD

**Issue by picrots** [GoldenCheetah/GoldenCheetah#1957]
It is broken (at least on my machines) at authentication stage.
You can login to Dropbox fine but It stucks after clicking allow button within Dropbox dialog. basically pressing 'allow' or 'cancel' buttons doesn't do anything.
This is broken in both official latest version and in dev version of GC.

**Comment by liversedge** [comment]
for which operating system?

works for me on Linux, OSX and Windows

**Comment by picrots** [comment]
I am using it on windows on Surface pro 3. also tested it on windows running on Virtual box.
I've checked my Dropbox and it made the app permission entry for GC but its status is pending.

**Comment by amtriathlon** [comment]
I am having the same problem on Linux (Ubuntu 16:04) using the last published development build or my own build the behavior is the same: allow or cancel doesn't do anything. Dropbox sync via LocalStore is working in the same machine.

**Comment by liversedge** [comment]
Will check with Gareth to make sure the right client api key is being used in the build.

It definitely works for me using my own personal build...

**Comment by gcoco** [comment]
Tested both 32bit and 64bit and they both worked.
I wonder if Dropbox had a temporary issue?

**Comment by picrots** [comment]
Yes it seems working now!
