### ISSUE TITLE
[bug] After "Merge pull request #1956" TRIMP for Run activites always =0 on trend

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#1958]
In Activity summary (detail for 1 activity) TRIMP is OK, but on progress trend all TRIMP values always = 0 for all "Run" events.

**Comment by amtriathlon** [comment]
Did you defined HR zones for running?

**Comment by MaksVasilev** [comment]
I found problem. 
If i try add HR zones for running, GC change date from 01.01.1900 to current. I add 2 row with same zones: now and add with data 01.01.1900: TRIMP returns.

I see: GC must always get zones without data analyze if only 1 row in profile present. If 0 row present - get zones from default (bike) profile.

**Comment by amtriathlon** [comment]
There is no fallback to bike HR zones, if you want HR metrics for running you need to have running HR zones defined for the date range when they happened.

**Comment by MaksVasilev** [comment]
Fallback needed.

**Comment by liversedge** [comment]
I don't think a "fallback" is appropriate, but if HR for running is not configured startup it should default to the bike one at startup -- to ease transition from current config.
