### ISSUE TITLE
"navigator" fields breaks after language change.

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#1960]
I configure field for trainings "navigator":

http://velo100.ru/files/GC-Fields-bug-01.png

| Date | Time | Total time | Distance | Average speed | Normalized power | Trimp |

Part of this fields have translation, and in config file we have:

```
headings=*|\x414\x430\x442\x430|\x412\x440\x435\x43c\x44f|\x414\x43b\x438\x442\x435\x43b\x44c\x43d\x43e\x441\x442\x44c|\x414\x438\x441\x442\x430\x43d\x446\x438\x44f|\x421\x440\x435\x434\x43d\x44f\x44f \x441\x43a\x43e\x440\x43e\x441\x442\x44c|NP|TRIMP Points|
headingwidths=0|113|91|87|90|79|76|57|
```

If i change language from system (Russian) to English i have strange fields in navigator and no way to revert it, only delete and configure again:

http://velo100.ru/files/GC-Fields-bug-02.png

May be save in config always field name only as is use in code and use separate table with translatabele displays name for fields?

**Comment by MaksVasilev** [comment]
Additional: need to add custom display name for fields. For example: field for distance have internal code "distance", this name save in config. Display name for this by default is "Distance", default translated name "Дистанция", but i lake see it in navigator (only in navigator) as short "км".

**Comment by amtriathlon** [comment]
The original problem is similar to what happens to chart names et.al. when you change languages, perhaps we could "solve" it in a similar simple way: adding a reset to default option to the hamburger menu.
WRT to the second comment I don't understand which the problem is.
