### ISSUE TITLE
Multiply selection in navigator for mass edit

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#1962]
I need next quest: select over 500 activites to change it from "Bike" sport to another.
I add new sport in config (data fields, sport), use filter find all activites to edit, but navigator works only for 1 activites by time.

Fields i need to mass edit in "Details" tab:

1) Sport. I'm use over 16 type of sport but this in import always Run, Bike or Swim. I change manualy sport for every next imported activity but can't mass change for archve of past activites.

2) Device. This not always correct detected by GC. Fenix 3 with old firmware have "FR920XT" in activity info. Fresh Fenix activity have "Fenix 3" in device info. But i have activites from real FR920XT. I'm quick and without problem select workouts to need change use find/filter, but can't change all for 1 time.

3) Keywords. For keyword not need to mass replace, but need to mass add value for field.

**Comment by amtriathlon** [comment]
The new set/unset/isset formulas provide this functionality, albeit not in GUI mode, see https://groups.google.com/d/msg/golden-cheetah-users/orBY1d3LKlU/vo50NqzuBwAJ

**Comment by amtriathlon** [comment]
Closed for the same reason as https://github.com/GoldenCheetah/GoldenCheetah/issues/291
