### ISSUE TITLE
Custom tile server for OpenStreetMap map

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#1963]
Big thanks for openstreetmap support.

Next step: support for custom tile server in map settings. Now it "http://tile.openstreetmap.org/": 
https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/Charts/RideMapWindow.cpp#L493

Please add in map config 2 elements:
1) checkbox "Use custom tile server" (active only if OpenStreetMap selected)
2) textbox for custom tile server. If it's not defined or checkbox not checked use by default "http://tile.openstreetmap.org/".

**Comment by Joern-R** [comment]
Fixed via https://github.com/GoldenCheetah/GoldenCheetah/commit/caffabc4c6aab708138b29e039ce1d4ac694f41c

**Comment by MaksVasilev** [comment]
Thank you. But it needs more checking trailing '/'. If you enter a URL with a slash at the end, the map does not work.

**Comment by liversedge** [comment]
Don't add a trailing slash.

**Comment by MaksVasilev** [comment]
I'm test GC with new custom map settings: it's work. 

![custom map](http://velo100.ru/files/GC-custom-map-01.png)
