### ISSUE TITLE
invalid recording gap

### ISSUE THREAD

**Issue by already5th** [GoldenCheetah/GoldenCheetah#1966]
I use a Garmin Forerunner 310 XT to record my activities. Among them, also the swim training: in this case, however, only the time and the split in laps are recorded.
Activities are uploaded in my Mac by Garmin Express and then imported by GoldenCeetah. As a result: the time of each lap loos good in the EDIT window, but each lap gets a virtual length of 0.01...useless!!
Thanks for helping.

**Comment by amtriathlon** [comment]
Try to enable "Garmin Smart Recording" in GoldenCheetah and to import the
files again
