### ISSUE TITLE
Metric Trends weird behavior with CP and different date selections

### ISSUE THREAD

**Issue by nileracecrew** [GoldenCheetah/GoldenCheetah#1970]
I've set up a Metric Trends chart to look at modeled CP over time. Depending on which date range I have selected, different data gets display, even for what should be the same days. Below are some example screenshots.

I don't ride every day (hence the crummy CP numbers) so I have a hunch this has something to do with how GC interpolates the daily CP value.

Last 14 days:
![screen shot 2016-05-18 at 8 16 45 pm](https://cloud.githubusercontent.com/assets/12072865/15381685/94694162-1d36-11e6-9cfe-c267554b5c78.png)

Last 21 days, data doesn't agree with Last 14 days table:
![screen shot 2016-05-18 at 8 16 59 pm](https://cloud.githubusercontent.com/assets/12072865/15381691/9d3f0736-1d36-11e6-9878-501b73205d1d.png)

Last 3 months, Table stops at Apr 19 2016, even though there is data past that date (and doesn't agree with smaller date ranges):
![screen shot 2016-05-18 at 8 18 31 pm](https://cloud.githubusercontent.com/assets/12072865/15381668/69554bd8-1d36-11e6-86b0-690034f0589a.png)

**Comment by amtriathlon** [comment]
Model Estimates have been completely revamped in the last development build, please try again with it.
