### ISSUE TITLE
Build 3942 missing Heart Rate Zones table in Summary tab for runs

### ISSUE THREAD

**Issue by mms7r** [GoldenCheetah/GoldenCheetah#1974]
My runs include data for heart rate zones, pace zones, and power zones.

In build 3940 the Summary tab for runs displayed tables for Power Zones, W' Balance Zones, Pace Zones, and Heart Rate Zones. (Build id: 3940, DB Schema: 127, Metrics: 277, OS: Linux)

In build 3942 the Summary tab omits the Heart Rate Zones table for run events. The Heart Rate Zones table is shown for bike events. (Build id: 3942, DB Schema: 128, Metrics: 278, OS: Linux)

**Comment by amtriathlon** [comment]
in build 3942 if there is no run-hr.zones file in athlete's config folder
at startup the one for cycling is used and behavior should be the same as
the previous build, but if run-hr.zones is present it must have zones
active for the dates of the run activities for HR zones to be computed and
showed.

**Comment by amtriathlon** [comment]
The problem happens when there is a run-hr.zones file without ranges and this kind of file is generated when you save config. I will change it to check for no ranges present.

**Comment by mms7r** [comment]
Yes, you nailed it. I was able to copy hr.zones to hr-run.zones and then the Summary HR Zones table gets displayed. (I could do that because my hr-run LT happened to be based on running <insert blush\>. I will do a bike LT Real Soon Now :-) )

THANKS, Ale!
