### ISSUE TITLE
HR zones as background

### ISSUE THREAD

**Issue by watts4speed** [GoldenCheetah/GoldenCheetah#1981]
In some charts the power zones are shown in the background when "Shade Zones" is checked, for example in the KPI chart.  What would be really helpful is to have the same kind of background zones for heart rate.  Also being able to use this kind of background with the Activities charts would be extremely helpful in monitoring and accessing athlete fitness and progress over time.  This would be really useful for training heart rate approaches used in Ironman or other ultra-endurance programs.

**Comment by amtriathlon** [comment]
Duplicates https://github.com/GoldenCheetah/GoldenCheetah/issues/901
