### ISSUE TITLE
cannot set Intensity Factor (IF) manually to calculate PMC

### ISSUE THREAD

**Issue by piotrekk8** [GoldenCheetah/GoldenCheetah#1988]
PMC does not calculate properly ACL, CTL and TSB for HR-based workouts without IF.
TSS can be set manually in Activity Details, but IF can not.

https://raw.githubusercontent.com/GoldenCheetah/GoldenCheetah/master/doc/wiki/Activity_Details-Metric.jpg

**Comment by liversedge** [comment]
ACL, CTL and TSB do not use IF.
If you want to override IF you can add it in the metadata config, see the faq.
