### ISSUE TITLE
When trying it asks for me to enter a nickname and doesn't care if I already have

### ISSUE THREAD

**Issue by gille** [GoldenCheetah/GoldenCheetah#1989]
See screenshot.

![2016-06-04 1](https://cloud.githubusercontent.com/assets/749403/15802335/d3f2a092-2a62-11e6-8b9e-dd711ddf29eb.png)

**Comment by Joern-R** [comment]
We allow a different nickname for the Cloud upload than the one defined in the athlete preferences (since the one in the athlete was intended internally, while the Cloud one is visible to everybody.) - To simplify rename the field label to "Name" to avoid misunderstandings.

**Comment by liversedge** [comment]
We /could/ use it for the same thing ?

**Comment by Joern-R** [comment]
Fine for me as well - then I make it "display only" in the chart upload screen - and if it's not maintained in the athlete settings, request the user to maintain it in the athlete settings first before a chart can be uploaded.

**Comment by liversedge** [comment]
Or let them enter it when its blank and update the setting at that point (no need to tell them either since they don't use it) ?
Save a lot of hassle that way !

**Comment by Joern-R** [comment]
Ok - will do it like that.

**Comment by Joern-R** [comment]
Fix by 51e132c45b4464d475231a26afbb865216c1323f

Thanks for the hint.

**Comment by gille** [comment]
Ah. I actually think I was hitting the issue of nickname length.

I used 4 characters. It would probably be good to have the error message point out the validation error (incorrect characters, too short, too long etc).

**Comment by Joern-R** [comment]
I removed all validations and we use the existing nickname now. Adding a
new one was just not needed :-)

2016-06-06 1:39 GMT+02:00 Magnus Gille <notifications@github.com>:
