### ISSUE TITLE
Crash; occurred while joining activities

### ISSUE THREAD

**Issue by batsonjay** [GoldenCheetah/GoldenCheetah#1996]
Note: Was joining activities using data from Wahoo Elemnt. Wahoo has had some issues, and data is not perfectly clean. (E.g. some invalid mileage data during sensor timeouts). I don't know if this is related....

[2016-06-06-gc-crash-joining-activities.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/304800/2016-06-06-gc-crash-joining-activities.txt)

**Comment by gernot-hochmuth** [comment]
To support this issue: I recently noticed that GC crashes when joining an additional activity (from a Garmin sportswatch) to a Moxy activity. Strangely it works the other way round (joining the Moxy dataset to the Garmin dataset). I can't tell whether this is a general issue or whether it is related to one specific Moxy dataset as it worked both ways beforehand with different Moxy datasets.
[20160807_gc_crash_joining_activities.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/405557/20160807_gc_crash_joining_activities.txt)

**Comment by amtriathlon** [comment]
I'm closing this since it refers to an old version, if it can be recreated in the last development build please reopen attaching sample files to reproduce the issue.
