### ISSUE TITLE
Garmin asynchronous Heart Rate data from HRM-Swim unit broken in GC.

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#2001]
HRM-Swim and HRM-Tri heart rate sensors have asynchronous buffered metod of write data. This work autonomously from main unit (Fenix3, FR920XT or Epix) and sync all HR data only when all units out of water and activity stop and save. In realtime writing activity main unit write in HR data only that data what recived in real-time mode: < 1% of time, where body with sensors and unit stay ower the water. This data showed in GC.

File with full time HR data from HRM-Swim: http://velo100.ru/files/66LC5719.FIT_.zip

All data on Garmin Connect: https://connect.garmin.com/modern/activity/1222927197

**Comment by MaksVasilev** [comment]
Just another FIT file from Fenix3 + HRM-Tri: http://velo100.ru/files/67HJ5546.FIT_.zip

All HR data in activity on Garmin Connect: https://connect.garmin.com/modern/activity/1260292894

Yes, file directly from Fenix3 device.
Yes, All HR data in file present and added to end of file.

**Comment by MaksVasilev** [comment]
Full damp with HR data: https://github.com/MaksVasilev/fit2gpx/blob/master/test/67HJ5546.read

At end of FIT file messages number 12 (hr) have reference time between real timstamp and time in HRM-tri devices. Messages 11 (hr) have field with 8 values per record with hr data (field num 6) and time (field num 9)

**Comment by grauser** [comment]
I will look this evening.

**Comment by MaksVasilev** [comment]
Fresh sample from HRM-Swim:

File: https://github.com/MaksVasilev/fit2gpx/blob/master/test/682I3734.FIT?raw=true
Dump:https://github.com/MaksVasilev/fit2gpx/blob/master/test/682I3734.read

on Garmin Connect: https://connect.garmin.com/modern/activity/1285021986

**Comment by grauser** [comment]
Thank you.

I am on the problem. But there is a few difficulties...

**Comment by adriangibbons** [comment]
Hi @grauser 

I'm implementing functionality to parse this async HR data in my [project](https://github.com/adriangibbons/php-fit-file-analysis) but I'm struggling to find information on how the data is encoded.

It looks like you authored the ```decodeHr()``` method. Where did you find the information to write this? Particularly the handling of event_timestamp_12 values?

I'm fairly familiar with the FIT SDK but couldn't find the information in there or on the site, dev forum, etc...

I've had some success using our code as a basis to rewrite it in PHP, but it's not yet quite working...

Thanks in advance, Adrian.

**Comment by grauser** [comment]
If I remember correctly I didn't find any documentation (and I was surprised). 
I had to deduct (not easily) from the description of event_timestamp_12 in Profile.xlsx and analogy with compressed timestamp testing on the dump provided by @MaksVasilev (I have no swim hr strap).

**Comment by grauser** [comment]
Good luck for you project @adriangibbons !

**Comment by adriangibbons** [comment]
Well you did a great job, so thanks for your efforts! I've just about managed to port into PHP and it seems to match the output from the Java FitCSVTool from the SDK. I was wondering if it was similar to the compressed timestamps but it had been a while since I'd looked at this. Was good to refresh my binary arithmetic anyway :)
