### ISSUE TITLE
[bug] Elevation data wrong from Garmin FIT

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#2007]
Elevation data from Garmin: http://velo100.ru/files/elev-155.png

FIT file: http://velo100.ru/files/2016-07-08-17-11-27.fit_.zip

Activity on Garmin Connect: https://connect.garmin.com/modern/activity/1246629060

On Strava: https://www.strava.com/activities/634168541

Incorrect data in GC: http://velo100.ru/files/elev-155-193.png

Need to always use Garmin elevation data if device have barrometric altimiter.

**Comment by liversedge** [comment]
Can you describe what you think is the problem?

Can you confirm the FIT file is from a device directly and not downloaded from Garmin Connect.
(We know Garmin Connect borks elevation data)

I use FIT from an SRM PC8 and elevation data is fine.

**Comment by MaksVasilev** [comment]
Garmin Edge 1000 show 155 m of elevation. Screenshot 1.

FIT file from Edge 1000 - second link.

Garmin Connect show 155 m.
Strava show 155 m.

GC show 193 m elevation - this is inccorect.

**Comment by liversedge** [comment]
Please read the FAQ regarding hysteresis.

**Comment by MaksVasilev** [comment]
Garmin Connect broke elevation data from device and recalculate it only if device not have barrometric altimiter (low price range device). In all other device Garmin Connect always use raw elevation data from device.

All manipulation with hysteresis increase difference betwen real elevation and incorrect data in GC.
This a bug in GC.
