### ISSUE TITLE
Extensible Data Model via XDATA

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#2010]
Add the ability to augment activity data with raw samples from other kinds of devices or even data series that are not currently supported.
1. Add XDATA sgements to the GC ridefile and file formats :100: 
2. Add XDATA support for FitRideFile for Weather data :100: 
3. Add XDATA to the Ride Editor :100: 
4. Add XDATA to the Merge Activity Wizard (to attach from CSV etc)
5. Add XDATA to the R API :100: 
6. Add XDATA to the datafilter syntax :100: 
7. Add XDATA developer fields support :100:

**Comment by liversedge** [comment]
__DataFilter updates__

d27627 First bit of XDATA in DataFilter (to filter rides that contain it)
0f416e1  Second bit to enable XDATA for user data and user metrics

**Comment by liversedge** [comment]
__Ride Editor updates__
aaec9ce Add XDATA to Ride Editor Part 1 of 2
b9bcce2  Add XDATA to Ride Editor Part 2 of 2
f0b9390 Ride Editor XDATA cell delegate
142da52 Fix Ride Editor Header Background Style
1c96edc Ride Editor Cosmetic Nits
544af86 Fix XDataEditor compile error on Windows
9578193 Fix XDATA Model Compile errors on Windows
3170e43 Ride Editor Remove XDATA by closing tab
07c4adf Ride Editor XDATA row/col add/delete
8198bdf RideEditor tabs "+" to add new XDATA series

**Comment by liversedge** [comment]
__XDATA file format updates__

d81f146 FitRideFile : Add weather xdata
f318689 FitRideFile : Weather data small correction
6c73ce6 XDATA Fix Memory Leak and Example Weather File
974edf1 Merge pull request #2009 from amtriathlon/BestTime
45d5ba8 Added SWIM XData for pool swims
ec8c613 FitRideFile: Changes in decodeDevice (not used)
db6c737 Tools : Add a tool to derive headwind from weather data

**Comment by liversedge** [comment]
See 6f4a349c7f90764152b5ecb6062fbfc612728910 which uses xdata for rowing data.

**Comment by liversedge** [comment]
__XDATA from R__

63d3e61a99b0fd6a57e55edbbe2e35754a28efef Add XDATA to R:GC.activity()

**Comment by liversedge** [comment]
Update (4) above - adding XDATA merge from generic CSV would also support having multiple devices too. see #2051 for example re: multiple moxy devices.

**Comment by liversedge** [comment]
Finalised in 3.4

**Comment by liversedge** [comment]
Reopening to include merge XDATA into 3.4, so users can create their own XDATA series.

**Comment by liversedge** [comment]
We'll sort merge in v4.0

**Comment by zisp** [comment]
So it looks like 3.4RC2 is reading in xData, but it doesn't appear to be able to do anything with it yet?  (I'm using a Stryd with Leg Spring Stiffness that I'd like to see in GC.)  Am I missing something, or is it still just too early in the implementation?

**Comment by liversedge** [comment]
XDATA is available in user data, formulas and R. When we release we'll post a video covering how to use it, but for now its contained within the wiki for R and formula expressions

**Comment by DavidDavidov** [comment]
In GC 3.5 for Mac I have Leg Spring Stiffness XDATA for an activity:  https://cl.ly/6026f963fe2c
but can not find a way to add it to a chart. Attempting this way: https://cl.ly/97d3c52deafb
Please advise

**Comment by DavidDavidov** [comment]
I resolved my issue. 
FTR in https://vimeo.com/191463556 at 6:45 is shown the right syntax.
So I updated my formula to `XDATA("*", "Leg Spring Stiffness", interpolate)`
Now Leg Spring Stiffness chart is available

**Comment by amtriathlon** [comment]
In v3.5 XDATA is preserved across merge, I think we could implement the item 4 above adding a way to import XDATA series to the CSV importer using a format like:
```
XDATA name
Time, Distance, serie1[:units1], serie2[:units2], ..., serienN[:unitsN]
secs, km, value1, value2, ..., valueN
...
```
When a CSV file with starting with the XDATA keyword is imported the "name" XDATA will be created with the series specified in the second line (units are optional) and values imported accordingly.
This file could then be merged using the merge activity wizard to add more standard or XDATA series.

**Comment by amtriathlon** [comment]
The new Python Data Processor are an alternative and more flexible way to add XData series, including pulling data from online services: https://github.com/GoldenCheetah/GoldenCheetah/commit/9f1187390faf9a41f1cda44d719272a5e3bc4562
