### ISSUE TITLE
Nothing is Visible

### ISSUE THREAD

**Issue by jsbrad7** [GoldenCheetah/GoldenCheetah#2017]
Suddenly, I can't see anything.  I know the activities are there, see them on the left sidebar & in the data folder, but no details are visible.  Same goes for "Trends" & "Diary" views.  Tried uninstalling & re-installing, but that didn't help surprisingly.  Some setting get changed some how?

**Comment by liversedge** [comment]
View->Reset Layout ?

**Comment by jsbrad7** [comment]
that did it - thanks
