### ISSUE TITLE
A few user friendly improvements

### ISSUE THREAD

**Issue by panos1234** [GoldenCheetah/GoldenCheetah#2021]
1. In TRENDS menu i have many charts. If i want to see one of those on the right side of the horizontal menu, i click on the arrow and it scrolls the menu bar horizontally. It would be nicer if instead of scrolling horizontally, the arrow showed a drop down menu with the rest of the charts.

2. Multiple find and replace. Let's say i have 10 activities with workout code "apples" and i want to change it to "apples and oranges". It would be nice if i could search all the activities for "apples" and replace it with "apples and oranges" without having to change it in each one separately.

Thanks

**Comment by panos1234** [comment]
3. At import of an activity, automatically add specific notes or workout  code depending on some variables (time of day, distance, duration etc)

**Comment by liversedge** [comment]
2. is already available see set() in https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Formula-Syntax-and-Expressions

1 is not likely to happen, its a UX thing that is better addressed with a design that doesn't use tabs.

**Comment by panos1234** [comment]
And where exactly do i add the set() funtion ?

**Comment by liversedge** [comment]
There is a user forum here: https://groups.google.com/forum/#!forum/golden-cheetah-users
There are also a number of tutorials at http://www.goldencheetah.org/#section-tutorials

This issue / feature tracker is for managing bugs and the development queue.
