### ISSUE TITLE
Wrong values in 60 min power in the tracker chart

### ISSUE THREAD

**Issue by gillesF78** [GoldenCheetah/GoldenCheetah#2022]
In the Trends > Tracker Chart, the values of my 60 min power is false (41.4 instead of 305W for example).

**Comment by liversedge** [comment]
You may need to reset the view, as the old chart was wrong (View->Reset Layout).
Also, please make sure you are running v3.3.

**Comment by gillesF78** [comment]
The version I use is the July 2016 development build ID 3944.

View->Reset Layout solved the problem.

Gilles
