### ISSUE TITLE
Hide Curve

### ISSUE THREAD

**Issue by pswoods** [GoldenCheetah/GoldenCheetah#2031]
I like the ability to selectively show just one curve in each chart. I would also like the ability to hide individual curves. E.g. in the default **Activities>Stress** chart, I would like to analyze my commute as W' versus Elevation without going into **More...>Chart Settings...** and hiding Power, then going through the same to unhide it.  I.e. if I could simply hide the power curve with a click or two, it would make this analysis so much easier. 

Another example: I made a MMP Peaks/Weeks chart as described in Allen and Coggan Training and Racing with a Power Meter with curves for LOTS of durations, highlighting the highest 1 for each curve. This is handy for the rare occasion that I make a new fatigue profile, but week to week I would rather look at just 5s, 1m, and 20m. Instead of making two charts - one of which is just taking up space most of the time, it would be handier to hide all the curves I only need once in a while.

Hope that makes sense. Thanks for the great software! GoldenCheetah is so helpful and useful to me.

**Comment by amtriathlon** [comment]
If you enable "Show Legends" you can selectively hide each curve just clicking on the legend

**Comment by pswoods** [comment]
Cool thanks! 

I find I can do this in the Trends module but not in Activities. 

I.e. When I'm in the chart Activities>Stress, I go into More... > Chart Settings... I can't find any option for "Show Legend". 

The charts in the Trends module have this but not the charts in Activities. 

I am using 4.0 (1607).

**Comment by amtriathlon** [comment]
Right, this is a feature of Metric Trends charts.
Curves in Activity auto-hide/show depending on data availability.
