### ISSUE TITLE
Heartrates smoothed during TCX import

### ISSUE THREAD

**Issue by ldatgithub** [GoldenCheetah/GoldenCheetah#2033]
When importing a TCX files with trackpoints gaps (>1second) even with all processing set to manual, the import will create second-to-second entries, filling the gaps and smoothing the missing data fields. 

It is also smoothing the heartrates making it a real number and successively smaller till it flatlines (0).  Heartrates should not be smoothed.

In 3.3 and 4.0

**Comment by liversedge** [comment]
if you do not want smart recording fixed up then
a) don't use smart recording
b) disable smoothing in preferences

**Comment by ldatgithub** [comment]
liversedge, thanks for the prompt reply, and a great application. Yes it is possible to do that, but smoothing is necessary for the other data like speed, location etc.  It is only that smoothing heartrates this way is kind of strange to reduce them to zero, fractionary numbers, an approach rarely seen.  I guess if you have a gap of x seconds with HR=150 on the initial entry and HR=154 on the second, it is not expected to see your heartrate change frantically  to 68.5, 30.75, 0. and back to 151. Maybe an option is to smooth between the values of the interval, like 151,152,152 etc. All the best.

**Comment by ldatgithub** [comment]
Just to clarify, the smoothing I am referring to is the initial one during the import of TCX files (or any file with gaps in the HR measurements), to avoid impossible values. So even if the gap is relatively long like  HR: 150 0 0 0 0 0 0 160 it seems more sensible to transform it to 150 152 154 156 158 160 (instead of what is happening now (150 68.5 25 19 0 0 160).  Just a thought... regards
