### ISSUE TITLE
Identification of Garmin Vivoactive and BSX Insight 2 in Fit file reader

### ISSUE THREAD

**Issue by gernot-hochmuth** [GoldenCheetah/GoldenCheetah#2040]
A _Garmin Vivoactive_ sportswatch might be identified by the product code _1907_ when importing a Fit file. The _Garmin Vivoactive_ is  identified as "_GARMIN 1907_" in the summary tab in GC.
A _BSX Insight 2_ sensor might be identified by the manufacturer code _98_ and the product code _2_ when importing a Fit file. The _BSX_ is  identified as "_unknown device 98:2_" in the summary tab in GC when importing a Fit file. When importing a CSV file it is identified as "_BSX Insight_". Viewing a CSV file generated by a BSX sensor (3rd line in the CSV file)  one can read "_manufacturer 98 product 2_".
Can other users of such devices verify the identifiers of these devices (or even contribute by adding manufacturer codes resp. product codes of further devices)?
I can supply a patch to "FitRideFile.cpp" to implement the changes.

**Comment by grauser** [comment]
Vivoactive and BSX are both in the actual Fit parser.
