### ISSUE TITLE
Setting chart y-axis min max value

### ISSUE THREAD

**Issue by piotr-kubica** [GoldenCheetah/GoldenCheetah#2044]
Setting chart y-axis min max value so the chart data is displayed more detailed (closely, zoomed).

For example I have a chart with weight data, but can't see the small differences on the chart since in my case the weight changes from about 77.8 to 78.2 but the chart's y-axis starts from 0. 
A hack would be to expand the window vertically but that is pointless since I want multiple charts on one page.

Can this be done in the R programming language?
https://stat.ethz.ch/pipermail/r-help/2008-June/165558.html

Mentioned allready before in:
https://groups.google.com/forum/#!topic/golden-cheetah-users/8-_9wY0Y_Mg

**Comment by amtriathlon** [comment]
I you click the corresponding y-axis a couple of handles allow to change min/max values although the setting is not persistent, the new User Charts allows to set min/max values for each axis permanently, see the wiki and the Weight Tracking example in CloudDB.

**Comment by amtriathlon** [comment]
Let’s keep this open for context since the cited forum thread has useful information, in case someone is interested in to implement it and to avoid repetitions.

**Comment by liversedge** [comment]
Worth noting that axis ranges can be set when working with User Charts.
