### ISSUE TITLE
I cannot plot metrics of only selected intervals within my activities

### ISSUE THREAD

**Issue by already5th** [GoldenCheetah/GoldenCheetah#2047]
Hello,
I want to plot the trend of my speed in the last months while running at similar HF (for example, by selecting among my activities only 10' intervals with average HF between X and Y).
I wonder if this is possible in Golden Cheetah...among all the available functions ;o)
Thanks for any suggestion.
BR, Ste

**Comment by amtriathlon** [comment]
In v4 you can define a User Metric to compute average speed when HR is between a fixed range and then use it at interval or activity level for Activity Summary or to create a chart in Trends view.
