### ISSUE TITLE
Moxy minimum Sm02 and Thb values

### ISSUE THREAD

**Issue by ryinc** [GoldenCheetah/GoldenCheetah#2050]
When the minimum and maximum Sm02 and Thb metrics are added to "Summary" and "Interval", Golden Cheetah is not working correctly.

(1) Minimum values displayed are actually maximum values rather than minimum values
(2) The maximum Smo2 and THb values are not actually added to the "metrics" summary despite being selected in the Options>Metrics>Summary

**Comment by gernot-hochmuth** [comment]
with reference to (1): I noticed the incorrect calculation of the minimum values of **SmO2** and **tHb** as well. These errors can easily be corrected in file *src/Metrics/BasicRideMetrics.cpp*. Mind that **tHb** - i.e. the absolute concentration of hemoglobin in the blood in the specific muscle - should not become zero, as this would imply that the muscle were totally drained from blood. Following that logic the average of **tHb** should be calculated excluding zero values as well (as it is done with heart rate). 
I am not quite sure whether the minimum value of **SmO2** might become zero, as that would imply that the examined muscle had consumed all available oxygen. May someone with a deeper knowledge in physiology comment on that.
