### ISSUE TITLE
Support multiple muscle oxygenation devices

### ISSUE THREAD

**Issue by ryinc** [GoldenCheetah/GoldenCheetah#2051]
In moxy/muscle oxygenation assessments it is often necessary to use multiple oxygenation devices (for example to see differences between muscles directly involved vs muscles that are less involved).

Is it possible to support multiple muscle oxygenation devices for a particular activity. E.g. Sm02-1;Sm02-2 etc.

**Comment by liversedge** [comment]
Merging data into XDATA would do that, see #2010.
