### ISSUE TITLE
Windows Defender treats QT components as malware

### ISSUE THREAD

**Issue by cleveruplink** [GoldenCheetah/GoldenCheetah#2054]
Windows 10 Defender has just scanned my computer, spotted the QT components in the Goldencheetah folder and helpfully deleted them, rendering Goldencheetah unusable.

**Comment by liversedge** [comment]
You need to contact Microsoft for their faulty software.
You can just reinstall GC to get the files back

**Comment by cleveruplink** [comment]
Thanks Mark. I did restore the items that Defender deleted and got it working again. Note that reinstalling GC didn't work as the offending items were flagged up and removed immediately.
I know this isn't a GC bug as such but it's an issue that's worth being aware of because I doubt the built in malware software for Windows 10 is going to change in a hurry. This could therefore have an impact on whether people can use GC on Windows 10 without a workaround.

Get Outlook for iOS




On Mon, Aug 15, 2016 at 8:37 AM +0100, "Mark Liversedge" <notifications@github.com> wrote:





Closed #2054.

--
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/GoldenCheetah/GoldenCheetah/issues/2054#event-755364655
