### ISSUE TITLE
Ride duration wraps to zero at 24 hours, mean max charts don't display

### ISSUE THREAD

**Issue by eerdverk** [GoldenCheetah/GoldenCheetah#2056]
Ride duration in "edit" starts again at 0:00:00.000 at 24 hours. Mean max charts didn't lengthen to include the length of this ride. Mean max charts don't display curve summarizing entire ride, either. Laps do display though. Ride summary page displays duration correctly, and "time in pz" under "trends" tab seems correct too.

I would suggest allowing duration hours to continue upwards as a fix rather than trying to split days out of it. "Hour 27" of a ride makes more logical sense than "day 1 hour 3"... it would really be duration day 2, and possibly calendar day 3.

Attached is the ride. I imported it, derived torque values, then exited to save.

[C2016-08-16-15-HamItoiOno.fit.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/423727/C2016-08-16-15-HamItoiOno.fit.zip)

**Comment by amtriathlon** [comment]
I am closing this for the same reasons as #3359
