### ISSUE TITLE
Error - Local Type 2 Without Previous Definition

### ISSUE THREAD

**Issue by TonyMather** [GoldenCheetah/GoldenCheetah#2057]
I'm getting this error when importing .FIT files from Zwift.

I've uploaded the same files into WKO+ and TrainingPeaks successfully, so don't think the issue is with the files.
<img width="1032" alt="screen shot 2016-08-21 at 08 50 29" src="https://cloud.githubusercontent.com/assets/21153123/17836046/fa6bb612-677c-11e6-9c0f-2a8b9e5ebd7b.png">

<img width="501" alt="screen shot 2016-08-21 at 08 53 30" src="https://cloud.githubusercontent.com/assets/21153123/17836048/fd53dbf2-677c-11e6-9e8b-c85889f889a3.png">

**Comment by amtriathlon** [comment]
This should be fixed in v3.4, try using the last development build from https://github.com/GoldenCheetah/GoldenCheetah/releases

**Comment by TonyMather** [comment]
I'm still getting this error on v3.4 DEV 1608

**Comment by grauser** [comment]
Could you attach your file ?

**Comment by GeorgeBalanos** [comment]
Hi there!

I am a lecturer at the University of Birmingham with no coding experience and I will be supervising final year students on a project that will involve the analysis of Zwift files. I have downloaded and installed GoldenCheetah (v 3.5) but I get the error shown above by TonyMather when I try to open .fit files from my Zwift activities.

Any idea what I need to change to make GoldenCheetah open these files? I would be grateful for any advice.

Thanks a lot!

George

**Comment by amtriathlon** [comment]
Something similar has been reported to happen when the Zwift ride is not completed: https://github.com/GoldenCheetah/GoldenCheetah/issues/3479

If you want to diagnose by yourself, here is where that error is reported:
https://github.com/GoldenCheetah/GoldenCheetah/blob/8b651b50dc4488805dab3939e1719224b51cf4ba/src/FileIO/FitRideFile.cpp#L2789
Otherwise, please attach a sample file producing it

**Comment by GeorgeBalanos** [comment]
Thanks a lot for the reply. I am not confident enough to work through the code so I am attaching the file in case you can help. 

Attaching a .FIT file was not accepted so I have changed the file extension to .TXT for now.

[2018-11-20-18-31-11.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/5167025/2018-11-20-18-31-11.txt)

Thanks again!

George

**Comment by GeorgeBalanos** [comment]
Don't worry! I just realised that this was a problem created by the file uploaded, not the program.

Thanks a lot!
