### ISSUE TITLE
Running Cadence in Garmin FIT use "fractional_cadence" with float

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#2060]
In Garmin FIT files for Running metrics use 2 field for Cadence:

```
    [field id=4] cadence 79 rpm
    [field id=53] fractional_cadence 0.5 rpm
```

This record in Garmin show as  159 spm ( (79 + 0.5 rpm) x 2)

But in GC i see only integer "79" in "Edit" mode.

FIT file:  https://github.com/MaksVasilev/fit2gpx/blob/44a0e45fbdc12839899d460825fc5866fba0229e/test/68MK1405.FIT?raw=true

Dump of this FIT file: https://github.com/MaksVasilev/fit2gpx/blob/44a0e45fbdc12839899d460825fc5866fba0229e/test/68MK1405.FIT.dump

Activity in Garmin Connect: https://connect.garmin.com/modern/activity/1316823498

**Comment by grauser** [comment]
fix in commit 00e3e13e59dd0d9078f0ac921291f48d7f3dff86
