### ISSUE TITLE
Stress diagram shows incorrect temperature

### ISSUE THREAD

**Issue by softmove** [GoldenCheetah/GoldenCheetah#2065]
the temperature is shown with wrong values and I'm missing 
axis designation/labeling
![2016-08-24a](https://cloud.githubusercontent.com/assets/21222589/17935866/22362540-6a1d-11e6-9fb8-509f7fd4120e.jpg)

v4.0-dev1607

**Comment by softmove** [comment]
sorry, can't upload the fit file, because GitHub is telling me I should use a *.zip file, what I have already done. How-to?

**Comment by softmove** [comment]
Hm, this is strange.
If I set the smothness to 1, everything is ok.
If I set it back to 2, the line is wrong again as shown above.

**Comment by liversedge** [comment]
send me the file, its the data that is the issue. liversedge gmail com

**Comment by softmove** [comment]
Here it is.
Could you please check, if the elevation is missing for the first approx. 30 secs?
GC is showing me 0 values.
I have to open a ticket at the Wahoo support then.

thx



Von: Mark Liversedge [mailto:notifications@github.com]
Gesendet: Freitag, 26. August 2016 12:19
An: GoldenCheetah/GoldenCheetah
Cc: Christof Lindner; State change
Betreff: Re: [GoldenCheetah/GoldenCheetah] Stress diagram shows incorrect temperature (#2065)


send me the file, its the data that is the issue. liversedge gmail com

**Comment by liversedge** [comment]
DONT REPLY TO THE NOTIFICATION FROM GITHUB -- SEND IT TO MY EMAIL
liversedge gmail com

THANKS

**Comment by liversedge** [comment]
MY SINCERE APOLOGIES.

I have recreated this and will fix shortly.

Sorry for being difficult.

**Comment by softmove** [comment]
No problem.

Thanks for fixing this and giving us such a great software!
