### ISSUE TITLE
Add "NOT CONTAINS" operator

### ISSUE THREAD

**Issue by panos1234** [GoldenCheetah/GoldenCheetah#2067]
My case:

I am splitting activities to be able to compare manually or automatically recorded laps/splits/intervals from different activities.

This produce new activities that are duplicate (i am keeping the original activity).

The easiest way to hide those duplicates, is to add a "duplicate" comment in the notes and create a filter, that i will use in the Trends and Activities panes, to show only activities that "Notes NOT CONTAINS "duplicate"".

At the moment, my intervals are small and i am using a "Duration>200" filter, but when i get to 30/40/60 min intervals, that would be a problem because i have sorter activities that i want to be included in the calculation of pmc and various other charts.

Thanks

**Comment by liversedge** [comment]
try:

! (Notes contains "duplicate")

**Comment by panos1234** [comment]
Thanks i will try that.

Meanwhile update the documentation because i didn't find any mention of the
use of ! in:
https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_SearchFilter
where i was searching for

But i see now it exists in:
https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Formula-Syntax-and-Expressions
without any example that would make it easier for someone with no
programming languages knowledge to understand its use

Thanks

**Comment by liversedge** [comment]
Feel free, the wiki is user maintained.

**Comment by liversedge** [comment]
Cool!

Thanks 👍
