### ISSUE TITLE
Error importing Garmin Fenix 3 runs - "Error - local type 15 without previous definition"

### ISSUE THREAD

**Issue by krootee** [GoldenCheetah/GoldenCheetah#2068]
Import from Garmin Fenix 3 is not working anymore with latest Garmin firmware.
Another addition is Moxy data fields that are supported with this version, but those runs were without Moxy sensor.
Runs from Wednesday is ok as seen on screenshot.
<img width="688" alt="1" src="https://cloud.githubusercontent.com/assets/1162001/18019069/0fc0e04a-6be3-11e6-973a-558d251ae7b2.png">
<img width="329" alt="2" src="https://cloud.githubusercontent.com/assets/1162001/18019070/0fc6776c-6be3-11e6-801e-9d57cb38ebdb.png">

**Comment by liversedge** [comment]
already fixed in 3.4, see development builds.

**Comment by krootee** [comment]
Thank you!
