### ISSUE TITLE
Duplicate Chart functionality

### ISSUE THREAD

**Issue by panos1234** [GoldenCheetah/GoldenCheetah#2069]
It would be convenient if the user could duplicate an existing chart,
That is useful if you want to track the same metrics for different types of workout.
All you have to do is change the filter and the title.

**Comment by amtriathlon** [comment]
In current development build you can duplicate an existing chart via export to a file and the drag&drop the .gcchart file over GC to import it again.
OTOH, If you just want to use the same chart with different filters, you could create named filters and then select which one to apply on the left sidebar or on the filter box without the need to duplicate charts, that way you can even use compare mode which now honors filters.

**Comment by amtriathlon** [comment]
Duplicares https://github.com/GoldenCheetah/GoldenCheetah/issues/428
