### ISSUE TITLE
Dual CP values

### ISSUE THREAD

**Issue by panos1234** [GoldenCheetah/GoldenCheetah#2070]
As most cyclist i believe, i have different FTP values for hills and for flat.

Based on multiple 20min uphill FTP tests, my UFTP (uphill ftp) is 273w.
Based on one 20min flat FTP test, my FFTP (flat ftp) is 223w.

I would like GC to calculate rides' tss, atl, ctl, w prime and all the relevant to FTP metrics,
based on my UFTP or FFTP. The decision by GC of what FTP should be used to calculate the metrics above, should be made by a word that the user has put in the notes (i.e. "hill", "flat", "or whatever the user decide to use as a mark".

**Comment by amtriathlon** [comment]
You can directly override CV (and FTP) at activity level, see https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-METRICS#can-i-set-a-different-cpftp-for-different-reasons-eg-cpftp-on-a-trainer

**Comment by panos1234** [comment]
Thanks for that.
Probably i have deleted that field, so i added some extra info in the documentation in someone else in the future does the same.

**Comment by panos1234** [comment]
Ok, i see how i can override CV but i don't see how to override FTP value.
How can i do that ?

**Comment by amtriathlon** [comment]
Exactly in the same way, just use "FTP" instead of "CV" for the name field.

**Comment by liversedge** [comment]
Hi,

For future reference please use the user forums for help requests as this is a bug and feature tracker.

Thanks

Mark
