### ISSUE TITLE
Crash while starting any analysis

### ISSUE THREAD

**Issue by DATABIKE** [GoldenCheetah/GoldenCheetah#2071]
Hi,
Since last GC update which converted all rides raw format to GC format, GC does not work anymore. I just can upload rides but while clicking for any analysis, GC crashes...
I am on updated UBUNTU 16.04 LTS.
I have removed and installed GC several times but it does not make it work...
Thanks for your help :)

**Comment by amtriathlon** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md
