### ISSUE TITLE
Nutrition Tracking

### ISSUE THREAD

**Issue by panos1234** [GoldenCheetah/GoldenCheetah#2073]
If you, the developers of GC, did not eat for a month, GC would stop stop being developed (and you stop training and eventually, living).
Do i need to say more about how important is to track everyday nutrition ?

It is already implemented in Sporttracks + Calorie Balance plugin very well.

**Comment by amtriathlon** [comment]
Subsumed in https://github.com/GoldenCheetah/GoldenCheetah/issues/2872
