### ISSUE TITLE
Preferences not available after changing language setting

### ISSUE THREAD

**Issue by offroadhunter** [GoldenCheetah/GoldenCheetah#2076]
Hi all,

after I changed the language from english to german, preferences cannot be reached in the menu bar.

System: Mac OS X 10.11.6
Golden Cheetah: Version 3.3 Build ID: 3933

**Comment by specialex** [comment]
In German it is under "Werkzeuge" > "Optionen"
Dont know why.

**Comment by liversedge** [comment]
Fixed in  ea7aa2ccf4f0b24aaee456057ea5fa3f67a753c6
