### ISSUE TITLE
Metric Overrides are applied to intervals

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#2078]
For example if you override Duration or Distance for an activity all intervals have the full Duration or Distance, this is manifest on manual workouts with laps, as reported on https://groups.google.com/forum/#!topic/golden-cheetah-users/ZmJUgyIYHzA, but it happens in every case when a metric is overridden.

**Comment by liversedge** [comment]
This is a tricky one to solve - maybe we allow overrides to be set for an interval too ?
That is definitely a v4 feature !!

**Comment by amtriathlon** [comment]
Not sure about interval level overrides, may be too complex from user's POV, the previous behavior (to ignore overrides for intervals) was simpler to understand and probably enough for the majority of cases, but I may be wrong.
In the meantime I will disable Duration and Distance overrides for manuals workouts when we have laps to avoid this problem for that case in V3.4

**Comment by amtriathlon** [comment]
Hi Mark, I think I found a simple solution for this use, please check: https://github.com/amtriathlon/GoldenCheetah/commit/587b994d8d0ac36dd614e81e921a7550260eb1a5
Cheers, Ale
