### ISSUE TITLE
GoldenCheetah crashes after device is added (Ubuntu 14.04 + 16.04)

### ISSUE THREAD

**Issue by udjamaflip** [GoldenCheetah/GoldenCheetah#2082]
Hey there,

I've got a replicatable issue on my main computer with fresh Ubuntu installations, I first experienced it on 16.04 and assumed non-compatibility, however, I reinstalled fresh Ubuntu 14.04 (better GPU support) and get the same issue.

Step 1: Installed GC using apt
Step 2: Create user in GC
Step 3: Click add Fortius device (device will be found - my device is an i-flow)
Step 4: Provide the .hex file from a local directory
Step 5: Click next and GC will crash

The data dump below is from the crash on 16.04, but it's the same crash+steps. Happy to provide more info if needed.

ProblemType: Crash
Architecture: amd64
CurrentDesktop: Unity
Date: Sun Sep  4 10:50:09 2016
DistroRelease: Ubuntu 16.04
ExecutablePath: /usr/bin/GoldenCheetah
ExecutableTimestamp: 1458677843
ProcCmdline: GoldenCheetah
ProcCwd: /home/andy
ProcEnviron:
 PATH=(custom, user)
 SHELL=/bin/bash
 LANG=en_AU.UTF-8
 LANGUAGE=en_AU:en
 XDG_RUNTIME_DIR=<set>
ProcMaps:
[DELETE]
ProcStatus:
 Name: GoldenCheetah
 State:    S (sleeping)
 Tgid: 13776
 Ngid: 0
 Pid:  13776
 PPid: 3732
 TracerPid:    0
 Uid:  1000   1000   1000   1000
 Gid:  1000   1000   1000   1000
 FDSize:   64
 Groups:   4 24 27 30 46 113 128 1000 
 NStgid:   13776
 NSpid:    13776
 NSpgid:   3995
 NSsid:    3995
 VmPeak:    2590856 kB
 VmSize:    2589772 kB
 VmLck:           0 kB
 VmPin:           0 kB
 VmHWM:      138308 kB
 VmRSS:      137836 kB
 VmData:    2061888 kB
 VmStk:         144 kB
 VmExe:       12712 kB
 VmLib:      181696 kB
 VmPTE:        1152 kB
 VmPMD:          24 kB
 VmSwap:          0 kB
 HugetlbPages:        0 kB
 Threads:  15
 SigQ: 1/63885
 SigPnd:   0000000000000000
 ShdPnd:   0000000000000000
 SigBlk:   0000000000000000
 SigIgn:   0000000000001000
 SigCgt:   0000000180010000
 CapInh:   0000000000000000
 CapPrm:   0000000000000000
 CapEff:   0000000000000000
 CapBnd:   0000003fffffffff
 CapAmb:   0000000000000000
 Seccomp:  0
 Cpus_allowed: ff
 Cpus_allowed_list:    0-7
 Mems_allowed: 00000000,00000001
 Mems_allowed_list:    0
 voluntary_ctxt_switches:  8427
 nonvoluntary_ctxt_switches:   331
Signal: 11
Uname: Linux 4.4.0-34-generic x86_64
UserGroups: adm cdrom dip lpadmin plugdev sambashare sudo
_LogindSession: c2
CoreDump: base64
 [DELETED]
ApportVersion: 2.20.1-0ubuntu2.1
Dependencies:
 [DELETED]
Disassembly:
 => 0x55a8c5:  mov    0x40(%rax),%rax
    0x55a8c9:  mov    0x30(%rax),%rsi
    0x55a8cd:  lea    0x40(%rsp),%rax
    0x55a8d2:  mov    %rax,%rdi
    0x55a8d5:  mov    %rax,%rbx
    0x55a8d8:  mov    %rax,0x10(%rsp)
    0x55a8dd:  add    $0x10,%rsi
    0x55a8e1:  callq  0x4a1840 <_ZN4QDirC1ERKS_@plt>
    0x55a8e6:  lea    0x50(%rsp),%rax
    0x55a8eb:  mov    %rbx,%rsi
    0x55a8ee:  mov    %rax,%rdi
    0x55a8f1:  mov    %rax,0x18(%rsp)
    0x55a8f6:  callq  0x49e740 <_ZNK4QDir13canonicalPathEv@plt>
    0x55a8fb:  mov    0x50(%rsp),%rax
    0x55a900:  mov    (%rax),%ecx
    0x55a902:  mov    %rax,0x60(%rsp)
EcryptfsInUse: Yes
InstallationDate: Installed on 2016-08-18 (16 days ago)
InstallationMedia: Ubuntu 16.04.1 LTS "Xenial Xerus" - Release amd64 (20160719)
JournalErrors:
 [DELETED]

**Comment by liversedge** [comment]
This is fixed (I believe) in the latest dev build 3.4-1608.

**Comment by udjamaflip** [comment]
Thanks for the quick response, can the dev version be installed through apt?

**Comment by liversedge** [comment]
Debian releases aren't quite so fast !
You can download the .deb from the releases page here on github.

**Comment by udjamaflip** [comment]
Sorry to stick to a closed report, but I'm then met with "Cannot Connect to Fortius" when I managed to get to the training window.

Same seems to be getting dragged up here: https://groups.google.com/forum/#!msg/golden-cheetah-users/K1nBKkAUjKw/gkf6LgJnrBUJ

I noticed the original post mentions creating a udev rule for GC, is that necessary still?

**Comment by liversedge** [comment]
udev rules are needed for all usb devices,  not so much about GC as Linux.
so, yeah, you will need one.
