### ISSUE TITLE
Athlete type into CP-W' model used on activity summary

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#2087]
Hi,

I've been using goldencheetah with a powermeter for about 18 months now and something that has always struck me is that for my activities the W' value on the summary page of an acitivity always seems to be too high for my capablities and the CP value (accordingly) too low.

If I use the formula CP(t) = CP + W'/t , than this gives me values for e.g. 180s intervals that are more or less 30W too high compared to what I'm capable of. When interval times increase the power values obviously get more realistic.

I've been playing around a little bit with the CP and W' solver in the latest development build and noticed that there are lots of parameter sets that return a fitting model for the exhaustion points. I guess the same is true for the model that is used in the activity summary. So wouldn't it be a good idea to ask for an athlete type before estimating CP and W'? 

For example let's say that statistically the best set of parameters are W'=30kJ and CP=290W. However the user has defined his athlete type to triathlete/non-sprinter/...  In that case it might be better to choose another set of parameters that might statistically be slightly worse. If W'=22kJ and CP=300W for example, power values above 8minutes are similar for both, while the short intervals are probably more realistic for a triathlete type.

 Or maybe it would be possible to give a range of possible CP and W' parameters for all athlete types (sprinter -> pursuiter -> puncheur -> climber -> timetriallist -> triathlete...), in that case no action is required from the user whatsoever. It might even tell them something extra about their strengths and weaknesses.

Kind regards,

Nigel

**Comment by liversedge** [comment]
There are quite a few points to address !
```
If I use the formula CP(t) = CP + W'/t , than this gives me values for e.g. 180s intervals that are more or less 30W too high compared to what I'm capable of. When interval times increase the power values obviously get more realistic.
```
Have to performed a 3min all out test?
The CP model is generally robust between 2 and 20 minutes. But the model is only as good as the data you collect; i.e. how often you perform all out efforts at reasonable durations between 2 and 20 minutes.


```
I've been playing around a little bit with the CP and W' solver in the latest development build and noticed that there are lots of parameter sets that return a fitting model for the exhaustion points. I guess the same is true for the model that is used in the activity summary. So wouldn't it be a good idea to ask for an athlete type before estimating CP and W'?
```

The model used in the solver is the W'bal model not the Critical Power model. The parameters also control the boundaries used. It has nothing to do with the CP model. Your 'guess' is not true.

```
Or maybe it would be possible to give a range of possible CP and W' parameters for all athlete types (sprinter -> pursuiter -> puncheur -> climber -> timetriallist -> triathlete...), in that case no action is required from the user whatsoever. It might even tell them something extra about their strengths and weaknesses.
```

This concept is pure pseudo-science. There are no studies that provide any evidence regarding the relationship between event specialisation and the relationship between peak powers. It may seem like it is an accepted fact because you have read it so many times.

There have been studies to look at peak powers for elite athletes, but this phenotyping concept is mostly from you know who, and is not based on any science.

**Comment by nigelvdv** [comment]
Hi,

I start most of my tests with a 3 minute all out interval, so I guess those are actually my most representative efforts in my case.

I admit I don't know much about the modelling or science behind it, nor am I influenced by pseudo science of others. It just struck me that in my case (I'm not generalizing at all) I couldn't find an agreement between what GC tells me I should be able to do and what I can really do. Also I read that W' values above 30kJ are quite high and I don't see myself as someone with good anaerobic capabilities. Probably even rather the opposite.

Anyway, I know modelling is all about statistics and where statistics are involved there are always outliers. So maybe I'm just one of them. It doesn't make Golden Cheetah less valuable for me, no worries!

Kind regards,

Nigel
