### ISSUE TITLE
Chart Title after import broken non ascii symbols

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#2092]
1) Create ani chart or use any standart chart.

2) Export chart to .gchart file

[http://velo100.ru/files/GC-chart-name-bug-01.png](http://velo100.ru/files/GC-chart-name-bug-01.png)

3) Drag gchart file in GC to import

[http://velo100.ru/files/GC-chart-name-bug-02.png](http://velo100.ru/files/GC-chart-name-bug-02.png)

4) Chart imported, but title broken

[http://velo100.ru/files/GC-chart-name-bug-03.png](http://velo100.ru/files/GC-chart-name-bug-03.png)

**Comment by amtriathlon** [comment]
The non-ascii symbols are lost on import when calling toLatin1 method here:
https://github.com/GoldenCheetah/GoldenCheetah/blob/d6cf7ad4ed965d49465df14f7a33067f1f9292a1/src/Charts/GoldenCheetah.cpp#L1011, but I'm not sure if MVJSON can handle them.

**Comment by amtriathlon** [comment]
Using toStdString to convert to Utf-8 instead of Latin1 works for spanish accented vowels, can you test with cyrillic characters?

**Comment by MaksVasilev** [comment]
I can check on Linux today

**Comment by MaksVasilev** [comment]
Now all ok, thanks.

Linux x86_64,
Qt 5.6.1
gcc 6.2.1
