### ISSUE TITLE
Chart settings disappeared

### ISSUE THREAD

**Issue by specialex** [GoldenCheetah/GoldenCheetah#2095]
Dear Team, 
Sorry but my chart settings had disappeared :-(
If I go to chart settings, I only can change the chart name but for example at activities > summary chart, I can change only the name of the chart :-(

[GC1.pdf](https://github.com/GoldenCheetah/GoldenCheetah/files/489839/GC1.pdf)

Best Regards

Alex

**Comment by liversedge** [comment]
Summary chart has no settings.

**Comment by specialex** [comment]
THX for the quick reply!
I was wrong! If I go to "Trends" > "Summary" I should be able to select a timing window, but I can't 
:-(
Best Regards

Alex

**Comment by liversedge** [comment]
If you add a summary chart on trends view does it offer a date range?

**Comment by specialex** [comment]
No

**Comment by liversedge** [comment]
What version are you running?

**Comment by specialex** [comment]
3.4 DEV1608

**Comment by liversedge** [comment]
Weird, I can't recreate that.
![screenshot from 2016-09-23 15-52-08](https://cloud.githubusercontent.com/assets/142876/18790189/c3614540-81a5-11e6-8678-c5219f4a8551.png)

**Comment by specialex** [comment]
In the past it was looking like yours but now it disappeared :-(

**Comment by specialex** [comment]
I am using the German version.

**Comment by Joern-R** [comment]
I just tried it out. Can reproduce it - it relates to the language - when testing EN and FR the right chart is added while in DE, GC does not add the "Summary" of Trends when adding on Trends, but the "Summary" chart of activity.

**Comment by liversedge** [comment]
The names are deliberately different Activity Summary and Summary .. since the names are used to lookup from the menu.

Either the menu should have a way of getting back to the Chart ID or just change the translation.

Thanks for looking into it !

**Comment by Joern-R** [comment]
Thanks Mark - looks like I did that wrong some time ago. My bad.
@specialex - thanks for bringing that up.

Fixed through e7679a6b70a3bbd2a79428e513398f72f88f66ff

**Comment by liversedge** [comment]
:+1:

**Comment by specialex** [comment]
THX for the quick Fix!
Basic question: How can I install a Fix?
Sorry I am new here!

**Comment by Joern-R** [comment]
The fix will be part of the next Dev. Build. Or you need to compile/build
your own version.

2016-09-24 12:11 GMT+02:00 specialex <notifications@github.com>:
