### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by jtjvdh** [GoldenCheetah/GoldenCheetah#2101]
With importing FIT files from Garmin issues occur: timing event type 20 or truncated file body for every file. uploading same file in wko, garmin connect of strava does not yield any errors.

**Comment by liversedge** [comment]
have you tried the development builds?

**Comment by jtjvdh** [comment]
I have 3.3.0 installed. Will try development version tonight

2016-09-26 16:58 GMT+02:00 Mark Liversedge <notifications@github.com>:

**Comment by jtjvdh** [comment]
Within development import works fine

**Comment by liversedge** [comment]
COOL. Thanks for getting back.
We're releasing 3.4 specifically to get FIT 2 support out there
