### ISSUE TITLE
Crash when downloading data if WiFi adapter is off

### ISSUE THREAD

**Issue by Mickyduck55** [GoldenCheetah/GoldenCheetah#2103]
Hi not a big issue but if my old PCs network adapter goes to sleep (or I switch it off accidentally as the switch situated in a easy to flick position) and I try to download data from Dropbox or Withings GC crashes.  Probably not an issue for most people as their adapter probably stays on

**Comment by Joern-R** [comment]
Can re-create by de-activating the network adapter. Will check / try to fix this.

**Comment by Joern-R** [comment]
Fixed via https://github.com/GoldenCheetah/GoldenCheetah/pull/2119/commits/559feba1fbed7476e35be1826d7472cf44bdca2f
