### ISSUE TITLE
Garmin 520 uploads seem to get Time Moving wrong

### ISSUE THREAD

**Issue by davidh2075** [GoldenCheetah/GoldenCheetah#2106]
I started using a Garmin 520 about a month ago. GC reports it as a Garmin 2530.
Recently noticed that my average speed had increased dramatically to about 100km/h, or more. I've been training a bit, but not that much!

Looks like Time Moving is a lot lower than it should be for rides imported from the 520. Also correspondingly lower Interval and heart rate zone times. I'd been using an old version, so upgraded to GC 3.3. No change.

Comparing GC with Garmin Connect and Strava for a ride yesterday:

GC 3.3 - Duration: 1:31:00; Time Moving: 22:12; Distance (km): 34.247
Garmin Connect - Elapsed Time (duration): 1:30:59; Moving Time: 1:24:17; Distance: 34.25 km
Strava - Elapsed Time (duration): 1:30:59; Moving Time: 1:25:31; Distance: 34.2km

Is there a config setting I'm missing that's required for the 520? Something to do with the Garmin Smart Recording?

I can provide a data file for the ride if necessary.

**Comment by liversedge** [comment]
We have made a lot of changes to support FIT 2 files in 3.4 RC1, perhaps you could try it and see if the problem is now fixed?

https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/V3.4-RC1

**Comment by amtriathlon** [comment]
> davidh2075 commented 14 hours ago: Is there a config setting I'm missing that's required for the 520? Something to do with the Garmin Smart Recording?

You can see if there are gaps in recording in the Editor tab, see Anomalies button, they can be fixed using the Fix Gaps tool (more info at the wiki).

If Garmin 520 is using Smart Recording you need to have Garmin Smart Recording enabled using a high enough Threshold *before* import the file to avoid the gaps.

**Comment by davidh2075** [comment]
Installing 3.4 RC1 fixed the issue.
There were a lot of gaps in recording, but it looks like it was because 3.3 was reading only about every fifth data sample. Now the only anomalies are at the expected places, e.g. recording pauses and long stops.
Now I'm off to delete and re-load a month's activities :-(
Thanks for your help.

**Comment by johanekstrom** [comment]
I had the same problem, using 4.0 dev 1607. Apparently, the settings in my Garmin had changed to smart recording after a recent software update, so that was the issue for me.
