### ISSUE TITLE
VERSION 3.4 RELEASE CYCLE

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#2107]
List of actions (not issues) that need to be performed for the 3.4 release cycle.

**Comment by liversedge** [comment]
Finalise translations

**Comment by liversedge** [comment]
Update Website

Feature list needs updating (not done since 3.2) : 
* Refresh all of the feature sections for latest updates
* Add list of languages supported under features
* Add workout editing under features
* Add analytics (R, user metrics, user formulas) under features
* Add share charts via CloudDB

Science section needs updating
* Interval Training (workout design)

**Comment by liversedge** [comment]
Release Final Build

* Save snapshot of final build to new 3.4 branch on github
* Add to goldencheetah.org website
* Post release notes to website
* Announcement on the usual sites

**Comment by MaksVasilev** [comment]
I'm finalise Russian translation towards evening 30.09.2016. It is not too late?

**Comment by liversedge** [comment]
You still have time !

We typically run through 4-10 release candidates. I'm hoping we are at the low end this time :)

**Comment by MaksVasilev** [comment]
Ok, I will gradually translate.
