### ISSUE TITLE
Importing error from Stryd IQ app for Garmin

### ISSUE THREAD

**Issue by Hezelnutt** [GoldenCheetah/GoldenCheetah#2108]
Hi,

I have been using my Stryd for some time, and recently got a new Garmin to use it with the Stryd IQ app.

Importing the .FIT file directly from the device gives an error: local type 15 with previous definition. Do you have any idea what it could mean?

I have already list the problem at the Stryd forum: http://club.stryd.com/t/errors-when-importing-iq-file-to-golden-cheetah/2713

FIT file attached

**Comment by Hezelnutt** [comment]
It seems the file is not attached, it gives an error that the file type is not supported (although I have made it to a .zip file). Can I email it to you?

**Comment by liversedge** [comment]
liversedge@gmail.com

Although you should try the 3.4 RC1 which has full FIT 2.0 support.

**Comment by Hezelnutt** [comment]
I just emailed you the file.

I am using version 4.0 so I guess that should not be the problem

**Comment by liversedge** [comment]
Are you sure? It hasn't arrived yet.

**Comment by Hezelnutt** [comment]
Something must have gone wrong ;) Take 2 for the .fit file.

Regards,
Tim

2016-09-29 13:21 GMT+02:00 Mark Liversedge <notifications@github.com>:

**Comment by liversedge** [comment]
If you are replying to these emails with an attachment they will be stripped -- these emails are from the ticketing system.

Please send the file to liversedge@gmail.com

**Comment by amtriathlon** [comment]
> Hezelnutt commented 2 hours ago: "I am using version 4.0 so I guess that should not be the problem"
Beware full FIT 2.0 support is included in V3.4 RC1, not in previous version 4.0 development releases

**Comment by liversedge** [comment]
Got the file, thanks. It works fine in 3.4RC1.

There is a weird FIELD_88 developer field in there that is always 300, but other than that it works fine.

You can get 3.4 RC1 here: https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/V3.4-RC1

**Comment by Hezelnutt** [comment]
Thanks Mark, it works fine with version 3.4 RC1

However, it does not import metrics like GCT and vertical oscillation. Is this a limitation of GC or does this have to do with the .FIT file import?

**Comment by liversedge** [comment]
Works for me.
![screenshot from 2016-10-01 10-22-19](https://cloud.githubusercontent.com/assets/142876/19013157/15220164-87c1-11e6-84a4-6c5753dcfe93.png)

**Comment by Hezelnutt** [comment]
Thanks. I had thought it would automatically appear in the ride graph, but I needed some extra steps. That is now fixed, thanks for the help! Amazing work

**Comment by cnbuff410** [comment]
@liversedge, Kun from Stryd here.

It looks like GC is not compatible with our latest FIT 2.0 file with developer field data in. I verified the FIT file using TP, Strava and the decoder comes with FIT driver package so the file itself should be fine. Can you take a look to see what's the issue with decoding it in GC?

Thanks!
[1476972263-GIR.fit.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/542516/1476972263-GIR.fit.zip)

**Comment by amtriathlon** [comment]
Hi Kun, I think this was recently fixed by Damien in this commit https://github.com/GoldenCheetah/GoldenCheetah/commit/3ece3e070aab6465b750a5e6a1994d395248bc40, your sample file imports in my build including it, but check the comment at the end about scaling.
Cheers, Ale.

**Comment by jonbev** [comment]
@cnbuff410 

Hi Kun.

Strava doesnt seem to work with the new FIT2.0 files that contain IQ data from Stryd. See this one - https://www.strava.com/activities/750471761

https://connect.garmin.com/modern/activity/1413053179

**Comment by cnbuff410** [comment]
@jonbev I think that's Strava not being compatible with 2.0, if you transfer directly from Garmin Connect to Strava the same issue would happen. 

I don't know when Strava is going to fix that, I hope they will soon.
