### ISSUE TITLE
Average Power

### ISSUE THREAD

**Issue by leeen82** [GoldenCheetah/GoldenCheetah#2109]
I'd like to be able to view my average power for a ride in the activity summary tab calculated without including the zeros, as garmin offers.  I have yet to find a way to do this in GC but found several conversations around google on the topic with no clear solution.  If a solution exists, please point me to it.

**Comment by liversedge** [comment]
Please use the user forums for help requests, this is a defect logging system.
See: https://groups.google.com/forum/#!forum/golden-cheetah-users

ps: there is an Non-zero Average Power metric.
