### ISSUE TITLE
UG_Compare Pane shows 'Pace Swim' 'Distance Swim' when viewing Bike segment

### ISSUE THREAD

**Issue by Doorshifter** [GoldenCheetah/GoldenCheetah#2110]
![screen shot 1](https://cloud.githubusercontent.com/assets/22545406/18994371/ceb5dcd0-8727-11e6-9b3e-f97e34336940.png)

Tested with 3.4 RC1

**Comment by liversedge** [comment]
Metrics are displayed for all sports.
