### ISSUE TITLE
Edit Interval color and time changes don't stick via this dialog box. result in 3.4 RC1 crash 

### ISSUE THREAD

**Issue by Doorshifter** [GoldenCheetah/GoldenCheetah#2111]
![screen shot 2](https://cloud.githubusercontent.com/assets/22545406/18994519/7a531ec2-8728-11e6-8db6-a7d12f3827b3.png)

Changes to and interval/segment don't stick after they are changed via this dialog.
When quitting GC and discarding the detected change (this flag is set1) GC crashes with attached results.
[GC 3.4 RC1 crash after quit and discarding invisable changes.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/503134/GC.3.4.RC1.crash.after.quit.and.discarding.invisable.changes.txt)

**Comment by liversedge** [comment]
Colors are only applicable to user defined intervals.
We should disable editing discovered segments.

**Comment by Doorshifter** [comment]
indeed the colours aren't that interesting. The time period is more for fine tuning the segment. In the deep down under in GC there seems to a flag telling that something has changed in that particular ride file, which is actually not the case. It is pointing out the correct file and then it crashes.

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/649d3ee014fa08bea57a5b986264a81e8d50083c
