### ISSUE TITLE
Edge 800 temp measurement garbeld in graphs

### ISSUE THREAD

**Issue by Doorshifter** [GoldenCheetah/GoldenCheetah#2113]
Edge 800 is slow to start measuring temperatures. The start data of many rides looks like this because of that.
![screen shot 4](https://cloud.githubusercontent.com/assets/22545406/18995538/e9a014de-872c-11e6-8978-d1b217aa70c1.png)
empty record fields are handle by GC in a undocumented way resulting in a temperature graph like this.
![screen shot 5](https://cloud.githubusercontent.com/assets/22545406/18995579/1d9c5964-872d-11e6-8e13-07e53e0745c9.png)
which is a hot day, in degrees C  for any day in the world :-)

Copy paste of some values in de editor to the empty fields resolve the issue in the graph. Since it it only a few seconds (in the beginning of the ride) this could be solved in a different way in GC, with cause major inflouences. Ignore empty fields in temp records, set them to 0, take the first real occurrence and copy it in the empty fields...

**Comment by amtriathlon** [comment]
I have been testing #2951 and found it is easy to fix Garmin 800 imported files with this issue using a Python data processor s.t. the following:
```
# pad temperature (assuming -255 == unset)
activity = GC.activity()
if ('temperature' in activity.keys()):
	temp = activity['temperature']

	# find first Temp
	firstTemp = None
	for i, a in enumerate(temp):
		if a != -255:
			firstTemp = (i, a)
			break
	# pad missing vals
	for i in range(0, firstTemp[0]):
		temp[i] = firstTemp[1]
```
Once created it can be run using Edit menu like builtin data processors, very nice!
