### ISSUE TITLE
FIT2.0 - SmO₂/tHb in FIT file Edge1000 import error: local type 15 without previous defenition

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#2115]
Software: GC 3946, git master at 30.09.2016

Hardware:
1) BSX Insight Generation2
2) Garmin Edge 1000 (with "Moxy Edge Data Field, v1.2, 28.09.2016": https://apps.garmin.com/ru-RU/apps/a7e5e253-4392-495b-a072-8883c92d7211)
3) Garmin Fenix3  (with "Moxy fenix3 Data Field, v1.2, 28.09.2016": https://apps.garmin.com/ru-RU/apps/5521d2bf-1234-4ac7-a8c8-4e3f452a4597)

One Activity write on 2 devices.

FIT from Edge1000: https://drive.google.com/open?id=0Bz55gCMCGxBbM01BSE8zZkVNRWc
FIT from Fenix3: https://drive.google.com/open?id=0Bz55gCMCGxBbMjZtSjF5MHBhb3c

On Garmin Connect:

Edge1000 (show SmO₂/tHb as Connect IQ field) https://connect.garmin.com/modern/activity/1386655455
Fenix3 (don't show SmO₂/tHb) https://connect.garmin.com/modern/activity/1386657626

This 2 files use different way to save data in FIT. Edge1000 and Fenix3 not have native metod to use SmO₂ sensor without Connect IQ field. Only FR735 now can use SmO₂ sensor as regular ANT+ sensor.

1) **File from Fenix3 import successful and show SmO₂, tHb, O₂Hb, HHb**
https://drive.google.com/open?id=0Bz55gCMCGxBbRFBUc2syck8zS0k

2) **File from Edge1000 have error: local type 15 without previous defenition.**
https://drive.google.com/open?id=0Bz55gCMCGxBbZHJDUXFYbS04V2c

**Comment by grauser** [comment]
Thank you Maks,

Could you provide the dump of the Edge1000 file ?

Thank you !

**Comment by MaksVasilev** [comment]
Dump from Edge1000 file: https://drive.google.com/open?id=0Bz55gCMCGxBbbEJ2eGdWd3MwQ1k

I see that not only smo2 application writes to the FIT, and another DataField as it is now to write to a file: Trimp.

I use 3 custom Data Field on Edgee: Trimp, w'bal and Moxy. Trimp before of today not write in FIT.

But, in dump i don't see any developer data.

**Comment by MaksVasilev** [comment]
I delete "Trimp" data field and new FIT files from Edge1000 import successful:
https://drive.google.com/open?id=0Bz55gCMCGxBbb1JtVkV5MjJjMzA
https://drive.google.com/open?id=0Bz55gCMCGxBbMWlCTkFCYlRhZTA

Error not in SmO2 data! Error in data from field "Trimp".

**Comment by grauser** [comment]
Thank you @MaksVasilev
