### ISSUE TITLE
GC doesn't detect pedalling on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by udjamaflip** [GoldenCheetah/GoldenCheetah#2116]
I'm using a Tacx flow and Garmin HR monitor.
The HR is appearing, but when I start the session and begin pedalling nothing happens.

Could this be an issue with udev rule I have?

```
:~$ cat /etc/udev/rules.d/90-tacx-fortius.rules 
ACTION!="add", GOTO="fortius_end"
SUBSYSTEM!="usb", GOTO="fortius_end"

ATTRS{idVendor}=="3561", ATTRS{idProduct}=="e6be", MODE="0666"
ATTRS{idVendor}=="1932", ATTRS{idProduct}=="e6be", MODE="0666"

LABEL="fortius_end"
```

It's labelled as a Fortius, but everything should be correct. GC does see the device.

**Comment by amtriathlon** [comment]
Closing because is better to use the forum for usage questions.
