### ISSUE TITLE
Language Help

### ISSUE THREAD

**Issue by EarningIre** [GoldenCheetah/GoldenCheetah#2118]
I downloaded golden cheetah and created my rider name and all was well. While looking through the app it suddenly converted to the French language (I'm in Texas). I completely deleted the app and reinstalled it but it still had my created profile and is still in french. The language change drop down does not give me an English choice. Probably a simple fix but I'm in unknown territory. Thanks in advance for any help.

**Comment by liversedge** [comment]
Language is set in options on windows, preferences on Mac.
