### ISSUE TITLE
Switching athlete causes a crash

### ISSUE THREAD

**Issue by planetawylie** [GoldenCheetah/GoldenCheetah#2122]
Hi, when switching to a new athlete with no data, the GC app goes into a "Not responding' state, then it displays the 'crash' window, and then it actually displays the new athlete's window.

Crash report attached. 'GC_crash_20161002_switching_athlete.txt'

[GC_crash_20161002_switching_athlete.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/505488/GC_crash_20161002_switching_athlete.txt)

I'm on the latest code release. Windows 10 Pro,  x64bit.

Thx,
Andrew

**Comment by planetawylie** [comment]
Note, switching from the new athlete to another athlete with data, does not cause a crash.

**Comment by Joern-R** [comment]
Hi,

tried to reproduce on Win 10 / 64bit - with 3.4RC1 - which is the latest build. Problem does not occur here. Tried multiple sequences.

So I suggest to either check 3.4RC1 or (if you do not want to try a Release Candidate) wait for final 3.4.

Closed for now.

Thanks.
Joern

**Comment by planetawylie** [comment]
Thanks, I will give this a try once I return home from business trip.
