### ISSUE TITLE
New athlete, heartrate zone 'from date' not working correctly

### ISSUE THREAD

**Issue by planetawylie** [GoldenCheetah/GoldenCheetah#2123]
Started a new athlete. The '1900 Jan 1' dated year is the default.

I edit the 'from date' field. I enter a '16' for the year but this actually translated it to '1916' is the date, not '2016'. You really need to start using full 'yyyy' date format and/or provide a popup selector.

I enter '99' for the year, which translates to '1999'. I increase the value to '00', using the up arrow incrementer, which translates to '2000'. I incremented all the way to '16', i.e 2016.

I updated the entry and saved. I then went back to the athlete heartrate zone and it was displaying as '1916' again.

I have another athlete with data, and although the date selection field still assumes starting at '19yy', it successfully saves it as 2016 after incrementing up after entering '99'. Only with the new athlete and no data has a problem.

Thx,
Andrew

**Comment by Joern-R** [comment]
The screen input format is taken automatically from your system date format settings - e.g. on Windows you need to set your Date Format to something with "yyyy" - and the input field will offer this as well.

That should resolve your issue.

**Comment by planetawylie** [comment]
Hi there

Don't you think a date selector should work regardless of the format on the  system machine. I usually expect the system date format to be used for presentation not date calc (except for TZ).

Otherwise everyone has to use a format to make the software work? And then change it before running a report because they need the other format to display it differently?

**Comment by liversedge** [comment]
No I don't. Users set their preferences for a reason.

**Comment by planetawylie** [comment]
So no presentation layer separated from the actual calculation underneath ?

**Comment by MaksVasilev** [comment]
This not a bug, but big usability problem for very small elemenraty operations. Always use YYYY mask for year - good solvation for GC.

**Comment by planetawylie** [comment]
K. Will agree to disagree. Just found it odd that the local date/time format/culture override settings in my Windoze box is ignored by the app. 

I will also say because it can't be repeated enough...this is one of the best apps out there, and you are filling a very large gap in this market. Chapeau!

**Comment by amtriathlon** [comment]
Apparently there is a problem with some locales in Linux, see https://groups.google.com/forum/#!topic/golden-cheetah-users/sf9NmFFaKDg, I was thinking to enable a calendar popup for QDateEdit fields to alleviate the usability problem when the user has a system with 2 digits year format configured. Any objections?
