### ISSUE TITLE
Ride >Details< new default data fields do not show up

### ISSUE THREAD

**Issue by specialex** [GoldenCheetah/GoldenCheetah#2127]
Hi,
using GC on MAC V3.4 RC1 Version 
I created a lot of defaults under "Data Fields" to track Km etc. separate for some of my components.
This week I got new components, so I changed so defaults (created new ones and deleted old ones) but the new ones do not show up.
![bildschirmfoto 2016-10-05 um 22 29 11](https://cloud.githubusercontent.com/assets/22396006/19130385/38cd9bcc-8b4b-11e6-8eb2-3975f33798c0.png)
![bildschirmfoto 2016-10-05 um 22 17 22](https://cloud.githubusercontent.com/assets/22396006/19130391/3ce0fcd6-8b4b-11e6-9ada-a46520fef0d0.png)

Best Regards
Alex

**Comment by specialex** [comment]
![bildschirmfoto 2016-10-05 um 22 37 59](https://cloud.githubusercontent.com/assets/22396006/19131131/761de4ac-8b4e-11e6-824c-9d4bc1cd2326.png)

**Comment by specialex** [comment]
Problem solved :-) forgot to modify values under filds :-(

**Comment by liversedge** [comment]
thanks for updating us, it really helps !
