### ISSUE TITLE
Feature request: Support BSX Insight SmO₂ sensor as serial device (like a Moxy, for import activites)

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#2130]
Native BSX soft support only Windows and uses only for 2 action:

1) Update firmware for sensor
2) Upload data from sensor to server BSX, where it can download over browser back to user.

Uploading requires internet and work very badly: 4 of 5 activites fly to black hole. Yes, it's a bug on BSX soft, but soft use on windows standart D2XX FTDI drivers. GC have support for D2XX.

**Comment by grauser** [comment]
I close this issue. 
I asked BSX support several time if we can receive the protocole to download from the sensor but I had no response. 
And now BSX has officially shut down. If someone can give use more information I will be happy to reopen.
