### ISSUE TITLE
Ordering of segments

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#2132]
I would like to request following feature. At the moment it's possible to order user intervals. It would be nice if the detected segments could be ordered by time as well. Untill now they seem to be ordered by the date the segments have been first created.

Kind regards,

Nigel

**Comment by mtbkeith** [comment]
Please describe the two pages; the one in which you can order intervals and the screen in which you want to order segments? A screenshot can also be really helpful to those who may be looking for something to investigate and may not know the code inside/out (seeing & then searching for text in the codebase can clue a developer in!)

**Comment by nigelvdv** [comment]
Hi,

I attached 2 screenshots. The first one is the first climb I did during that activity after approximately 1h riding. The other one is the last climb I did during that activity after 5h. 

I created segments for both stretches of road during a previous activity. As you can see the segments are detected but not displayed in the correct order. The first one (Betsberg - Gontrode) should be displayed as the first of all segments, while the other one (Valkenberg - Brakel) should be last. At the moment I think they are ordered chronologically based on date created.

![first segment betsberg gontrode after 1h](https://cloud.githubusercontent.com/assets/14836910/24576931/e7e40a06-16c4-11e7-83a0-1b7dfe47e8ea.png)


![last segment valkenberg brakel after 5h](https://cloud.githubusercontent.com/assets/14836910/24576932/e7e573e6-16c4-11e7-8c4f-6e4e435641ac.png)


Kind regards,

Nigel
