### ISSUE TITLE
Crash on deleting phase in the season

### ISSUE THREAD

**Issue by freekode** [GoldenCheetah/GoldenCheetah#2139]
Have a season, created a 2 phases just for a test, they created good. But during deleting any of these phases the program is crushing. After starting again, the problem repeating (crash during removing). And phases not removing at all.
If it's interesting, here info:
```
Season name: Race Season 2016
From: 02/11/2015
To: 08/10/2016

Phase name: Preparation
Type: Prep
From: 16/10/2016
To: 30/10/2016

Phase name: Bb
Type: Build
From: 02/10/2016
To: 02/11/2016
```

**Comment by liversedge** [comment]
This should be fixed in the 3.4 dev build / rc, which version are you running?

**Comment by freekode** [comment]
```
Version: ...master@v3.4-RC1
Build id: 3946
```

**Comment by liversedge** [comment]
Oh it looks like the crash fix was on add. Not sure delete has ever been tested!
Will look to fix it.
