### ISSUE TITLE
Pace Zones seems to be wrong calculated

### ISSUE THREAD

**Issue by CodeGosu** [GoldenCheetah/GoldenCheetah#2141]
I tried to enter Pace Zones from Joe Friel and the result isn't what I expected. I entered my the zones manually from Trainingpeaks for the last CV.

Values from run-pace.tones file:

DEFAULTS:
Zone 5c,Anaerobic Capacity,0%
Zone 5b,Aerobic Capacity,90%
Zone 5a,Lactate Threshold,97%
Zone 4,Sub Lactate Threshold,99%
Zone 3,Tempo,106%
Zone 2,Aerobic Threshold,114%
Zone 1,Active Recovery,129%

2016/05/13: CV=12.5
Zone 1,Active Recovery,3.0025
Zone 2,Aerobic Threshold,9.54907
Zone 3,Tempo,10.7784
Zone 4,Sub Lactate Threshold,11.6129
Zone 5a,Lactate Threshold,12.2867
Zone 5b,Aerobic Capacity,12.7208
Zone 5c,Anaerobic Capacity,13.6882

Buildnumber is 3933

**Comment by amtriathlon** [comment]
Percentages in Default are based on velocity (CV=12.5km/h in this case) so if you want to use those percentages based on pace they need to be inverted, s.t.:

DEFAULTS:
Zone 1,Active Recovery,0%
Zone 2,Aerobic Threshold,78%
Zone 3,Tempo,88%
Zone 4,Sub Lactate Threshold,94%
Zone 5a,Lactate Threshold,101%
Zone 5b,Aerobic Capacity,103%
Zone 5c,Anaerobic Capacity,111%

2016/05/13: CV=12.5

**Comment by CodeGosu** [comment]
Ok, but I enter my CV in min/km or min/mile and it's not clear or described that the calculation is made in km/h.

**Comment by amtriathlon** [comment]
This way percentages represent relative intensity WRT CV and default zones work as an example but, if you consider this should be documented in a better way, you are welcome to do it at the wiki, it is open to user's contributions: https://github.com/GoldenCheetah/GoldenCheetah/wiki

**Comment by CodeGosu** [comment]
Ok, done. I'm very new to GoldenCheetah and Github, hope I can contribute something to this great tool.
