### ISSUE TITLE
REST API return json

### ISSUE THREAD

**Issue by freekode** [GoldenCheetah/GoldenCheetah#2143]
Working with json is much easier than with csv.
So could you add ability to return json if request contains Content-Type=application/json

**Comment by liversedge** [comment]
you can pass the content type, and we already honor content-type. see the docs:
https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_REST-API-documentation

**Comment by liversedge** [comment]
Actually it looks like the docs are out of date.
You can pass ?format=json, ?format=csv etc

See:https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/Core/APIWebService.cpp
