### ISSUE TITLE
Trainingpeaks synchronization

### ISSUE THREAD

**Issue by Fred6666** [GoldenCheetah/GoldenCheetah#2146]
I can't synchronize anymore my trainingpeaks data with GoldenCheetah. It crashes the software
[runtime error.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/545500/runtime.error.txt)
![capture](https://cloud.githubusercontent.com/assets/22990580/19615725/55b13dbe-9836-11e6-92b8-7eeac595676e.PNG)

**Comment by Joern-R** [comment]
Obsolete since Trainingpeaks has deprecated their sync. support used by GC.

Details: https://groups.google.com/d/msg/golden-cheetah-users/g3_bsD-U9Zo/yFlRd5ZLCwAJ
