### ISSUE TITLE
Incorrect speed and elevation in train view 

### ISSUE THREAD

**Issue by bluSpark** [GoldenCheetah/GoldenCheetah#2147]
I am using an Elite Drivo trainer which broadcasts power, speed and cadence. GC displays the speed incorrectly. e.g. 20 kph is displayed mostly 60-70 kph and briefly flickers back to show 20 kph. 

Also, the elevation is wrong in the train via. I loaded a GPS file that starts and ends at the same point, but the graph in the train view shows the elevation at the end is well below the starting elevation. The elevation is displayed correctly in the activity tab 

Would appreciate an explanation or help. 

Thanks 
Hany

**Comment by viiru-** [comment]
Are you connecting to the trainer over ANT+ or BTLE?

**Comment by bluSpark** [comment]
I am connecting over ANT+. I did manage to figure out the issue with the speed but not the elevation being incorrect. The speed issue was due to selecting the combined speed/cadence option. Instead I just selected the cadence only and the speed was displayed properly.

But the elevation in the train view is still wrong and it baffles me, since it is correct in the activity view.

**Comment by amtriathlon** [comment]
This seems the same as recently solved #2999
