### ISSUE TITLE
Activity Run, Summary, Average speed and pace time are incorrect

### ISSUE THREAD

**Issue by Timels** [GoldenCheetah/GoldenCheetah#2161]
GC V3.4-RC1 id: 3946 Activity Run, Summary, Average speed and pace time are incorrect

GC Shows in tab Summary a wrong value off the average run speed and pace time. The data shows a speed around the 10/12 kph.

![tab_summary](https://cloud.githubusercontent.com/assets/23135447/19828687/52c5c7cc-9dcd-11e6-8fda-72bb620bc7da.jpg)
![tab_edit](https://cloud.githubusercontent.com/assets/23135447/19828690/58753752-9dcd-11e6-8d29-0805f215e29b.jpg)

**Comment by liversedge** [comment]
You have smart recording enabled.

**Comment by liversedge** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-MOST-COMMON-QUESTIONS-OF-ALL

I've added an explainer to the FAQ, this comes up very frequently !

**Comment by Timels** [comment]
Thnx! after reinstall forgot to enabled it by the athleetsettings :) (watch isn't able to record every second)

**Comment by liversedge** [comment]
:+1:
