### ISSUE TITLE
Stryd .FIT Import status "Error - local type 4 without previous definition"

### ISSUE THREAD

**Issue by passar** [GoldenCheetah/GoldenCheetah#2164]
Hello everyone,
Seems like Styrd has changed their .FIT file in some way. I use arch linux on three machines that have GoldenCheetah-git installs ranging from the last 6 months to now and none of them can import successfully. There is no difference importing a single file or several.
In the Import Status i get:
Error - local type 4 without previous definition

And selecting a date does not change the matter.
Save dose make the 100% with the notice of:
Import Complete. 0 of 1 successful.

I have included a file for the good brains to help out.

BTW. Thank you for contributing to this awesome software that makes people better athletes!

[1477675651-GIR.fit.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/562194/1477675651-GIR.fit.zip)

**Comment by liversedge** [comment]
See 3.4 RC1 https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/V3.4-RC1

Thanks for reporting  the issue, but it should already be fixed.
We're preparing a release right now :)

**Comment by jonbev** [comment]
I can confirm it is working in the latest build.
