### ISSUE TITLE
Calendar information more than one workouts

### ISSUE THREAD

**Issue by Portaner** [GoldenCheetah/GoldenCheetah#2166]
Hi,
the calendar (side bar) show only one training session a day. As triathlete I have on some days two training sessions. This I can not see so in calendar. In my smartphone for example in news, at the bottom right, I see the number of unread news. A picture is worth a thousand words, there are two proposals what I mean (GC_Calendar.jpg). "2" there are two trainings session on the day

Thanks,
Jörg

![gc_calendar](https://cloud.githubusercontent.com/assets/23188632/19887592/a11f30d0-a029-11e6-83a7-32aff6930d77.jpg)

**Comment by liversedge** [comment]
Yes, this is a great idea and easy to do.

**Comment by liversedge** [comment]
Pushing into v4.0

**Comment by ward** [comment]
In a similar vein, the colour priority in the calendar seems to just be the earliest activity of that day. (Correct me if I am wrong) On a race day I will often have three activities: warmup, race, cooldown. The race is the main focus here, but the warmup seems to be the one picked to colour the date in the calendar.

**Comment by amtriathlon** [comment]
In Diary view there is a full page calendar available which shows each activity colored and with a summary like the ride navigator, additionally it can show Events imported from external calendars of from Trends view.

**Comment by liversedge** [comment]
Closing this as new calendar functionality will replace this request.
