### ISSUE TITLE
"Average FTP in %" in Intervall-View

### ISSUE THREAD

**Issue by Portaner** [GoldenCheetah/GoldenCheetah#2167]
Hi,
In the trainings plan from Coggan the interval have the value in % from FTP. This information is missing in the intervall-view. Perhaps is better to show the "Average FTP in %" (GC_Interval.jpg) than "Max Power"

Thanks,
Jörg

![gc_interval](https://cloud.githubusercontent.com/assets/23188632/19887703/5241a9c4-a02a-11e6-8964-824e9be9987d.jpg)

**Comment by amtriathlon** [comment]
Hi Jörg, in v3.4RC1 you can define a custom metric using the formula 100*Average_Power/config(ftp) as value and add it to Interval Metrics instead of Max Power if you like.

**Comment by amtriathlon** [comment]
I'm closing this since it is too similar to IF and it can be implemented as a custom metric in v3.4
