### ISSUE TITLE
No Power data when using Stryd Power AddOn

### ISSUE THREAD

**Issue by Rennschnecke21805** [GoldenCheetah/GoldenCheetah#2169]
Hi,
I've been using the Stryd Powermeter in combination with a Garmin FR735XT for 5 month now. So far I was relying on the Stryd IQApp to record and interpret my running data with GC. 
However, sice Gramin and Stryd collaborted and released the StrydPower AddOn to monitior and record running power in the Garmin running mode instead of using the Stryd IQApp I favor this option. (The Garmin running mode simply gives you more options to customize screens etc.) Thus I was very happy to see, that with with the GC v3.4-DEV1608 Develpment release I can now download my running data to GC directly from the watch again. 
The only problem is that these **datasets - where Power is recorded with the StryPower Add on in the Garmin running mode - are obviously missing those additional running data from the Stryd Powermeter.**
Strangely, when I look at the very same dataset in Garmin connect (I hate that platform!) all data are visible... Also first uploading the dataset to either Garmin conncet or StryPowerCenter and then downloading from there to GC does not change that.
Any help would be very much appreciated. I definitely want to stick with GC - but I also want to use the StrydPower AddOn...

**Comment by liversedge** [comment]
Have a try with RC1 and let us know if there is still a problem?
https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/V3.4-RC1

**Comment by Rennschnecke21805** [comment]
Wow, thanks for the fast reply.
Unfortunately the problem still persists with V3.4-RC1...

**Comment by Rennschnecke21805** [comment]
Maybe this has something to do with the error message I get when I open GC now ?
(see attachment)




------------------------------------------------------------
Dr. rer. nat. Michaela Renner-Schneck

phone: +49 171 7365272
e-mail: michaela.schneck@gmail.com

**Comment by amtriathlon** [comment]
There are changes related to FIT import in current master which are not included in v3.4RC1, if you can upload one of your failing files and post a link we will test it to see if this is already fixed. Thanks!

**Comment by Rennschnecke21805** [comment]
Hi Alejandro,

Since the .FIT file was not accepted for download on GitHub I'm sendig it over via e-mail
Attached you find two datasets of similar Sessions the one from 10/26/2016 (6AQE0519.FIT) was recorded in Garmin running mode with the StrydPower AddOn - and does not display Power-Data or any other running metrics from the Stryd - whereas the one from 11/02/2016 (6B281607.FIT) was recorded using the Stryd IQApp - here als data from the Stryd are readily accessible.

 



------------------------------------------------------------
Dr. rer. nat. Michaela Renner-Schneck

phone: +49 171 7365272
e-mail: michaela.schneck@gmail.com

**Comment by amtriathlon** [comment]
Using the current master the sample files import all Stryd data correctly, the fix will be available on RC2.
