### ISSUE TITLE
Feature Request: Calculate Power from slope in train mode

### ISSUE THREAD

**Issue by vbretsch** [GoldenCheetah/GoldenCheetah#2172]
I would like very much to be able to import gpx files into Golden cheetah train mode and then ride the track. 
Ideally Golden Cheetah should calulate resistance from the file as it has all necessary data, (elevation and slope data from gps track, the athletes weight and current speed (or some calculated metric from power produced by athlete on trainer)) and then adjust resistance of the trainer.

i am using current development version 3.4.
Would that be possible?

Regards,
Volker

**Comment by amtriathlon** [comment]
The ability to import and ride gpx files in Train mode was implemented in https://github.com/GoldenCheetah/GoldenCheetah/commit/1402f6ad6a87fa80474749f0eed70bbe6d0cf674
