### ISSUE TITLE
DSO missing from command line

### ISSUE THREAD

**Issue by pavlinux** [GoldenCheetah/GoldenCheetah#2173]
Debian 8.6 x64 

$ git clone ...
$ make clean; qmake; make; 
....
`g++ -m64 -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu -o GoldenCheetah qtsoap.o QTFullScreen.o qtsegmentcontrol.o VideoWindow.o TwitterDialog.o Dropbox.o GoogleDrive.o MonarkController.o MonarkConnection.o Kettler.o KettlerController.o KettlerConnection.o ANTChannel.o ANT.o ANTlocalController.o ANTLogger.o ANTMessage.o Aerolab.o AerolabWindow.o AllPlot.o AllPlotInterval.o AllPlotSlopeCurve.o AllPlotWindow.o BingMap.o BlankState.o ChartBar.o ChartSettings.o CPPlot.o CpPlotCurve.o CriticalPowerWindow.o ExhaustionDialog.o GcOverlayWidget.o GcPane.o GoldenCheetah.o GoogleMapControl.o HistogramWindow.o HomeWindow.o HrPwPlot.o HrPwWindow.o IndendPlotMarker.o IntervalSummaryWindow.o LogTimeScaleDraw.o LTMCanvasPicker.o LTMChartParser.o LTMOutliers.o LTMPlot.o LTMPopup.o LTMSettings.o LTMTool.o LTMTrend.o LTMWindow.o MetadataWindow.o MUPlot.o MUWidget.o PfPvPlot.o PfPvWindow.o PowerHist.o ReferenceLineDialog.o RideEditor.o RideMapWindow.o RideSummaryWindow.o ScatterPlot.o ScatterWindow.o SmallPlot.o SummaryWindow.o TreeMapPlot.o TreeMapWindow.o RideWindow.o CalendarDownload.o FileStore.o LocalFileStore.o OAuthDialog.o ShareDialog.o SportPlusHealthUploader.o TPDownload.o TPDownloadDialog.o TPUpload.o TPUploadDialog.o TrainingstagebuchUploader.o VeloHeroUploader.o WithingsDownload.o Athlete.o Context.o DataFilter.o FreeSearch.o GcUpgrade.o IdleTimer.o IntervalItem.o main.o NamedSearch.o RideCache.o RideCacheModel.o RideItem.o Route.o RouteParser.o Season.o SeasonParser.o Settings.o Specification.o TimeUtils.o Units.o UserData.o Utils.o AthleteBackup.o Bin2RideFile.o BinRideFile.o CommPort.o Computrainer3dpFile.o CsvRideFile.o DataProcessor.o Device.o FitlogParser.o FitlogRideFile.o FitRideFile.o FixDeriveDistance.o FixDeriveHeadwind.o FixDerivePower.o FixDeriveTorque.o FixElevation.o FixLapSwim.o FixFreewheeling.o FixGaps.o FixGPS.o FixRunningCadence.o FixRunningPower.o FixHRSpikes.o FixMoxy.o FixPower.o FixSmO2.o FixSpeed.o FixSpikes.o FixTorque.o GcRideFile.o GpxParser.o GpxRideFile.o JouleDevice.o LapsEditor.o MacroDevice.o ManualRideFile.o MoxyDevice.o PolarRideFile.o PowerTapDevice.o PowerTapUtil.o PwxRideFile.o QuarqParser.o QuarqRideFile.o RawRideFile.o RideAutoImportConfig.o RideFileCache.o RideFileCommand.o RideFile.o RideFileTableModel.o Serial.o SlfParser.o SlfRideFile.o SmfParser.o SmfRideFile.o SmlParser.o SmlRideFile.o SrdRideFile.o SrmRideFile.o SyncRideFile.o TacxCafRideFile.o TcxParser.o TcxRideFile.o TxtRideFile.o WkoRideFile.o XDataDialog.o XDataTableModel.o AboutDialog.o AddIntervalDialog.o AnalysisSidebar.o ChooseCyclistDialog.o ColorButton.o Colors.o CompareDateRange.o CompareInterval.o ComparePane.o ConfigDialog.o DiarySidebar.o DragBar.o EstimateCPDialog.o GcCrashDialog.o GcScopeBar.o GcSideBarItem.o GcToolBar.o GcWindowLayout.o GcWindowRegistry.o GenerateHeatMapDialog.o GProgressDialog.o HelpWhatsThis.o HelpWindow.o IntervalTreeView.o LTMSidebar.o MainWindow.o NewCyclistDialog.o Pages.o RideNavigator.o SaveDialogs.o SearchBox.o SearchFilterBox.o SolveCPDialog.o Tab.o TabView.o ToolsRhoEstimator.o Views.o BatchExportDialog.o DownloadRideDialog.o ManualRideDialog.o EditUserMetricDialog.o MergeActivityWizard.o RideImportWizard.o SplitActivityWizard.o SolverDisplay.o aBikeScore.o aCoggan.o AerobicDecoupling.o BasicRideMetrics.o BikeScore.o Coggan.o CPSolver.o DanielsPoints.o ExtendedCriticalPower.o GOVSS.o HrTimeInZone.o HrZones.o LeftRightBalance.o PaceTimeInZone.o PaceZones.o PDModel.o PeakPace.o PeakPower.o PMCData.o RideMetadata.o RideMetric.o RunMetrics.o SwimMetrics.o SpecialFields.o Statistic.o SustainMetric.o SwimScore.o TimeInZone.o TRIMPPoints.o UserMetric.o UserMetricParser.o VDOTCalculator.o VDOT.o WattsPerKilogram.o WPrime.o Zones.o codeeditor.o mvjson.o qwt_plot_gapped_curve.o qxtspanslider.o qxtstringspinbox.o zip.o AddDeviceWizard.o ComputrainerController.o Computrainer.o DeviceConfiguration.o DeviceTypes.o DialWindow.o ErgDB.o ErgDBDownloadDialog.o ErgFile.o ErgFilePlot.o Library.o LibraryParser.o MeterWidget.o NullController.o RealtimeController.o RealtimeData.o RealtimePlot.o RealtimePlotWindow.o RemoteControl.o SpinScanPlot.o SpinScanPlotWindow.o SpinScanPolarPlot.o TrainBottom.o TrainDB.o TrainSidebar.o VideoLayoutParser.o VideoSyncFile.o WorkoutPlotWindow.o WorkoutWidget.o WorkoutWidgetItems.o WorkoutWindow.o WorkoutWizard.o ZwoParser.o qrc_application.o qrc_RideWindow.o moc_qtsoap.o moc_QTFullScreen.o moc_qtsegmentcontrol.o moc_VideoWindow.o moc_TwitterDialog.o moc_Dropbox.o moc_GoogleDrive.o moc_MonarkConnection.o moc_Kettler.o moc_KettlerConnection.o moc_ANTChannel.o moc_ANT.o moc_ANTlocalController.o moc_ANTLogger.o moc_Aerolab.o moc_AerolabWindow.o moc_AllPlot.o moc_AllPlotInterval.o moc_AllPlotWindow.o moc_BingMap.o moc_BlankState.o moc_ChartBar.o moc_ChartSettings.o moc_CPPlot.o moc_CriticalPowerWindow.o moc_ExhaustionDialog.o moc_GcOverlayWidget.o moc_GcPane.o moc_GoldenCheetah.o moc_GoogleMapControl.o moc_HistogramWindow.o moc_HomeWindow.o moc_HrPwPlot.o moc_HrPwWindow.o moc_IntervalSummaryWindow.o moc_LTMCanvasPicker.o moc_LTMChartParser.o moc_LTMPlot.o moc_LTMPopup.o moc_LTMSettings.o moc_LTMTool.o moc_LTMWindow.o moc_MetadataWindow.o moc_MUPlot.o moc_MUWidget.o moc_PfPvPlot.o moc_PfPvWindow.o moc_PowerHist.o moc_ReferenceLineDialog.o moc_RideEditor.o moc_RideMapWindow.o moc_RideSummaryWindow.o moc_ScatterPlot.o moc_ScatterWindow.o moc_SmallPlot.o moc_SummaryWindow.o moc_TreeMapPlot.o moc_TreeMapWindow.o moc_RideWindow.o moc_CalendarDownload.o moc_FileStore.o moc_LocalFileStore.o moc_OAuthDialog.o moc_ShareDialog.o moc_SportPlusHealthUploader.o moc_TPDownloadDialog.o moc_TPDownload.o moc_TPUploadDialog.o moc_TPUpload.o moc_TrainingstagebuchUploader.o moc_VeloHeroUploader.o moc_WithingsDownload.o moc_Athlete.o moc_Context.o moc_DataFilter.o moc_FreeSearch.o moc_GcCalendarModel.o moc_GcUpgrade.o moc_IdleTimer.o moc_IntervalItem.o moc_NamedSearch.o moc_RideCache.o moc_RideCacheModel.o moc_RideItem.o moc_Route.o moc_Season.o moc_TimeUtils.o moc_UserData.o moc_AthleteBackup.o moc_DataProcessor.o moc_Device.o moc_LapsEditor.o moc_RideAutoImportConfig.o moc_RideFileCommand.o moc_RideFile.o moc_RideFileTableModel.o moc_XDataDialog.o moc_XDataTableModel.o moc_AboutDialog.o moc_AddIntervalDialog.o moc_AnalysisSidebar.o moc_ChooseCyclistDialog.o moc_ColorButton.o moc_Colors.o moc_ComparePane.o moc_ConfigDialog.o moc_DiarySidebar.o moc_DragBar.o moc_EstimateCPDialog.o moc_GcCrashDialog.o moc_GcScopeBar.o moc_GcSideBarItem.o moc_GcToolBar.o moc_GenerateHeatMapDialog.o moc_GProgressDialog.o moc_HelpWhatsThis.o moc_HelpWindow.o moc_IntervalTreeView.o moc_LTMSidebar.o moc_MainWindow.o moc_NewCyclistDialog.o moc_Pages.o moc_RideNavigator.o moc_RideNavigatorProxy.o moc_SaveDialogs.o moc_SearchBox.o moc_SearchFilterBox.o moc_SolveCPDialog.o moc_Tab.o moc_TabView.o moc_ToolsRhoEstimator.o moc_Views.o moc_BatchExportDialog.o moc_DownloadRideDialog.o moc_ManualRideDialog.o moc_MergeActivityWizard.o moc_RideImportWizard.o moc_SplitActivityWizard.o moc_SolverDisplay.o moc_CPSolver.o moc_HrZones.o moc_PaceZones.o moc_PDModel.o moc_PMCData.o moc_RideMetadata.o moc_UserMetricSettings.o moc_VDOTCalculator.o moc_Zones.o moc_codeeditor.o moc_qxtspanslider.o moc_qxtspanslider_p.o moc_qxtstringspinbox.o moc_AddDeviceWizard.o moc_ComputrainerController.o moc_DialWindow.o moc_ErgDBDownloadDialog.o moc_ErgDB.o moc_ErgFilePlot.o moc_Library.o moc_NullController.o moc_RealtimeController.o moc_RealtimePlot.o moc_RealtimePlotWindow.o moc_SpinScanPlot.o moc_SpinScanPlotWindow.o moc_SpinScanPolarPlot.o moc_TrainBottom.o moc_TrainDB.o moc_TrainSidebar.o moc_WorkoutPlotWindow.o moc_WorkoutWidget.o moc_WorkoutWindow.o moc_WorkoutWizard.o DataFilter_yacc.o JsonRideFile_yacc.o WithingsParser_yacc.o RideDB_yacc.o DataFilter_lex.o JsonRideFile_lex.o WithingsParser_lex.o RideDB_lex.o   -L/usr/X11R6/lib64 -L/media/disk/src/GoldenCheetah/src/../qwt/lib -lqwt -lm /media/disk/src/GoldenCheetah/src/../kqoauth/libkqoauth.a -lssl -lcrypto -lQt5MultimediaWidgets -lQt5WebKitWidgets -lQt5Svg -lQt5Multimedia -lQt5WebKit -lQt5Widgets -lQt5SerialPort -lQt5Concurrent -lQt5Network -lQt5Sql -lQt5Xml -lQt5Gui -lQt5Core -lGL -lpthread 
/usr/bin/ld: zip.o: undefined reference to symbol 'inflateInit2_'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:1377: recipe for target 'GoldenCheetah' failed
make: *** [GoldenCheetah] Error 1'

**Comment by liversedge** [comment]
add -lz in gcconfig.pri

**Comment by piotr-kubica** [comment]
Hi,

I am having same problem.
Adding -lz does not help.

> collect2: error: ld returned 1 exit status
> Makefile:1720: recipe for target 'GoldenCheetah' failed
> make: *** [GoldenCheetah] Error 1

I also have lots undefined references...
> /home/pio/Qt5.5.1/5.5/gcc_64/lib/libQt5WebKit.so: undefined reference to `gst_object_unref'

**Comment by pavlinux** [comment]
/usr/bin/ld: FileStore.o: undefined reference to symbol 'inflateInit2_'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:1372: recipe for target 'GoldenCheetah' failed
make[1]: *** [GoldenCheetah] Error 1
make[1]: Leaving directory '/media/disk/src/GoldenCheetah/src'
Makefile:126: recipe for target 'sub-src-make_first-ordered' failed
make: *** [sub-src-make_first-ordered] Error 2

**Comment by elluck91** [comment]
> add -lz in gcconfig.pri

You need to elaborate more...

**Comment by amtriathlon** [comment]
See: https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/gcconfig.pri.in#L214
