### ISSUE TITLE
Finding an existing athlete directory on first run

### ISSUE THREAD

**Issue by ehrlinger** [GoldenCheetah/GoldenCheetah#2174]
When I install a new instance of GC, and already have an athlete library available, it's a pain to set up. Specifically since I store the library in a shared file system that does not align with the "GC standard".

The current process forces me to create a new athlete just so I can navigate to the library directory where my actual athlete is stored. If I get that selection wrong (by selecting the top level athlete directory, instead of the parent of the athlete) I have to create another athlete to correct that mistake.

Can we add a browse option to the athlete selection dialog that can be used to navigate the file system to an existing athlete library?

**Comment by amtriathlon** [comment]
This is a very specific use case, which can be solved specifying directory and athlete on the command line:

```
GoldenCheetah --help
GoldenCheetah V3.6-DEV2009 (4002)
usage: GoldenCheetah [[directory] athlete]

--help or --usage   to print this message and exit
--version           to print detailed version information and exit
--server            to run as an API server
--debug             to turn on redirection of messages to goldencheetah.log [debug build]
--clouddbcurator    to add CloudDB curator specific functions to the menus
--no-python         to disable Python startup
--no-r              to disable R startup

Specify the folder and/or athlete to open on startup
If no parameters are passed it will reopen the last athlete.

```
