### ISSUE TITLE
qwkcode -> erg -> qwkcode rounding errors

### ISSUE THREAD

**Issue by SparkyT** [GoldenCheetah/GoldenCheetah#2175]
Using the new workout editor, rounding of some times result in values changing when the workout is reloaded.
V3.4RC2, build 3947, Windows 10

To reproduce:
- Start a new workout in the designer
- Add 80s@250r80s@150 to the qwkcode editor
- Save workout
- Click away from workout/close GC
- Open workout in editor
- Now shows as 79s@250r80s@150

Is this due to only saving the time points to 2 decimal places?

Larger example attached. .erg file created using qwkcode with 90 rows of data as follows

1s@250r1s@150
2s@250r2s@150
3s@250r3s@150
etc.
etc..
90s@250r90s@150

When loaded as a workout, several rows have times rounded up or down.  Fine for a normal ride but not if following a video.

[numbersWorkout.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/576574/numbersWorkout.zip)

**Comment by amtriathlon** [comment]
This is also reported as https://github.com/GoldenCheetah/GoldenCheetah/issues/2726, let's keep just one.
