### ISSUE TITLE
Custom Metrics Errors

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#2181]
I've been doing some testing systematic in v3.4RC2 because of some random behavior with custom metrics s.t. obtaining a correct result using the test button and zero for the cached value at the same metric and activity, the causes I could identify are two:
1) Changing the metric symbol without changing the formula doesn't recalculate metrics so all values go to zero until some custom metric formula changes forcing a metrics re-computation, this workaround seems to fix the problem: https://github.com/amtriathlon/GoldenCheetah/commit/1a515f9891ac444868f84363f773f75929f69c82, but probably there are better solutions.
2) Sometimes custom metrics stop being calculated for newly imported activities while the test button for the same metric and activity shows the correct value, the problem seems to be related to the UserMetric destructor deleting the program while there are still live clones sharing it, this workaround avoids this problem: https://github.com/amtriathlon/GoldenCheetah/commit/07eff6ae64ef8fa60d821ac45578fa28b6d93c93, but it creates a memory leak when custom metrics definitions change, so a better solution would be desirable.

**Comment by liversedge** [comment]
Do you have a way of testing any correction for #2 ?

I'm looking to fix this but need a reliable way to recreate the error.

**Comment by amtriathlon** [comment]
I am using this custom metric configured for summary and intervals:
![strokeindex](https://cloud.githubusercontent.com/assets/1444784/20225068/19831b0e-a84a-11e6-8451-28f3d62ab467.png)
Then I restart GC and import this file: https://github.com/GoldenCheetah/GoldenCheetah/blob/master/test/swims/GarminSwimExample.fit, if all values for Stroke Index are 0.00 I have recreated the error, otherwise I delete the activity, close GC and try again, normally it takes 1-3 attempts in my build.

**Comment by amtriathlon** [comment]
Adding log at UserMetric constructors and destructor shows a sequence like this at startup:
```
Create original
Create clone
Destroy original
...
<import file>
...
Create Clone
Destroy Clone
<this pair repeated for each interval>
```

So program is deleted before the new clones for metric computation are created, I think the error shows up depending on the memory being reused or not.

**Comment by liversedge** [comment]
the create original, create clone, delete original is the problem, yes?

**Comment by amtriathlon** [comment]
Yes, the clone goes to the metric factory and the original is destroyed deleting the program

**Comment by liversedge** [comment]
I think I've fixed it with this: b9a12c6d60f39bd767a1e4268ab6478b9d41c3e8

Can you confirm?

**Comment by liversedge** [comment]
Also, I'm not convinced on #1 above, how do you recreate this?

**Comment by amtriathlon** [comment]
Yes, the fix seems to be working, I cannot reproduce the problem using the procedure above, Excellent!

WRT #1 now the behavior is different (my previous description was influenced by #2), it is simply not possible to change only the symbol:
- In the existing metric I change symbol from Stroke_Index to SI
- the list seems to be ok with the new symbol
- save
- going again to options (or after restart) symbol is the old one again (Stroke_Index).
If I change the symbol AND the formula, all works as expected.
This is a minor problem, probably of no major practical significance, I just found it trying to reproduce #2.

**Comment by liversedge** [comment]
Perfect, will just leave it as it is then, and close this issue.
