### ISSUE TITLE
Bug: SmO₂/tHb from FIT file in 10 - 100 times greater than it actually is

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#2183]
In last 1-2 week commit a have big new bug - SmO₂/tHb from FIT file in 10 - 100 times greater than it actually is (600-800 SmO₂ and 1500-1800 tHb):

[http://velo100.ru/files/20161113_113339.png](http://velo100.ru/files/20161113_113339.png)

In Edit mode a see same data in SmO₂ and tHb:

[http://velo100.ru/files/20161113_113424.png](http://velo100.ru/files/20161113_113424.png)

But in Developer data i see normal values:

[http://velo100.ru/files/20161113_113447.png](http://velo100.ru/files/20161113_113447.png)

FIT file from Garmin Fenix 3: http://velo100.ru/files/6BCL0319.FIT_.zip

GC from git master 13.11.2016, 3947

**Comment by liversedge** [comment]
Damien is looking at this but it is a historic issue as Moxy have changed the way this works anyway.

**Comment by MaksVasilev** [comment]
http://velo100.ru/files/20161115_141040.png

GC from git master 15.11.2016 - all ok, thanks.
