### ISSUE TITLE
loosing Speed accuracy with direct Suunto SML Import / AMBIT2

### ISSUE THREAD

**Issue by mondoshiwan** [GoldenCheetah/GoldenCheetah#2184]
SML import works fine, but i'm loosing the speed accuracy. The speed data is only imported in integer values, all decimals are lost. I'm using an Ambit 2 and GC 3.3 and this is also the case with the 3.4 prerelease. Known issue?

**Comment by henolo** [comment]
I do have the speed decimals shown in the "Ride" speed diagram, but there are no decimals shown in the speed column in the "Edit" table.

**Comment by amtriathlon** [comment]
The original SML files (copied to the import folder) and the JSON files (stored in the activities) folder are both text files, it should be possible to check if the conversion done at import (*3.6) is ok. If the problem were at the editor it should happen also with other file types.

**Comment by mondoshiwan** [comment]
the speed data stored in the json file is integer, the decimals are lost at the import. This happens with running and cycling moves with the original sml file. Interestingly the import from a swimming move works fine. no loose or cutting decimals from the speed column here.
I could help myself for now with a combined activity using an exported tcx file from MC and override the speed data in GC with the data from that tcx file. That works.
While importing these tcx files you will not loose the decimals at the speed column.

**Comment by liversedge** [comment]
all data series stored in json are doubles, including speed.

**Comment by amtriathlon** [comment]
My fault, the problem is the round at https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/FileIO/SmlParser.cpp#L157 which should not be there, probably a copy paste error. It's easy to fix and I would like to do before 3.4 release, but I'm on travel and I don't have the tools for a proper commit...

**Comment by liversedge** [comment]
No problem Ale, I'll do it today.

Thanks.

**Comment by henolo** [comment]
In case not already noticed.

There are similar rounding operations done on HR (L143) and Cadence (L151) not only Speed,

So one might correct them as well, in order to introduce less "noise" in the ride data.

Thanks!!

**Comment by liversedge** [comment]
Cadence and HR are in RPM and BPM which are definitely integers!

**Comment by henolo** [comment]
Now you lost me. So not everything in .json are doubles then, or?

 

Från: Mark Liversedge [mailto:notifications@github.com] 
Skickat: den 18 november 2016 10:15
Till: GoldenCheetah/GoldenCheetah
Kopia: henolo; Comment
Ämne: Re: [GoldenCheetah/GoldenCheetah] loosing Speed accuracy with direct Suunto SML Import / AMBIT2 (#2184)

 

Cadence and HR are in RPM and BPM which are definitely integers!
