### ISSUE TITLE
Missing 'Refresh' in 'Metrics Trends' Chart  when using one metric multiple times with filter

### ISSUE THREAD

**Issue by robolaf** [GoldenCheetah/GoldenCheetah#2185]
Hi,
Thanks for adding the filters for curves. I tested and found a bug which I try to describe as simple as possible:

Add a Metric Trends chart with two curves with the same metric (here Time Moving) but one with a filter, like this:
![curve](https://cloud.githubusercontent.com/assets/7139815/20247187/f8c2f18c-a9c5-11e6-87a6-9b6f3579446e.png)
 
The other one can be without filter - but must be same metric.
If you than click different years/ time periods, than the follwoing errors occur:
1. The bars of the filtered metric seem not to be cleared/refresh as they appear and overlay the current bars => see below that for example after today bars are displayed.
2. With every new time period selection there appear more dots at the bottom.

![chart](https://cloud.githubusercontent.com/assets/7139815/20247195/32939272-a9c6-11e6-9e82-8de115bf5e02.PNG)

Please note: it does not happen if I use the metric only once in the chart.

I hope this is sufficient to be reproduced and helps to fix the bug.

Many thanks and regards,
Olaf

PS. I am on 3.4 RC2 but it happen with the prev. release, too.

**Comment by liversedge** [comment]
Yes this is a bug, the code does not support having the same metric twice in the same chart.
We will need to fix this in v4.

**Comment by amtriathlon** [comment]
A simple workaround is to replace the metric with a formula consisting just in the metric

**Comment by amtriathlon** [comment]
I've been bitten by this recently and it is really confusing, specially when it happens on a library chart since it affects perfectly fine library charts selected afterwards.

The cause of the issue seems to be inserting duplicate keys in curves QHash.

Since the curves hash is always scanned completely and never accessed by key, the simplest solution is to make it a QMultiHash, I did some testing and it seems to be working properly.

I will push that one line fix, if there are no objections.

**Comment by liversedge** [comment]
hmmm, there really shouldnt be duplicates, at least that was the original idea anyway

**Comment by amtriathlon** [comment]
> hmmm, there really shouldnt be duplicates, at least that was the original idea anyway

Why?

Nothing prevents duplicates (Metrics/Measures or PMC/Banister/Best) be added, and in some cases it is a useful feature.

There seems to be no uniqueness requirement in LTMPlot logic, the key is never used to access the hash, only to check if the curve is a trend/outlier/etc. and to retrieve the base metric information. Just allowing duplicates seems to work ok.

**Comment by liversedge** [comment]
if it works then thats great, just wonder if there are any bugs hidden in there, but simple fixes are good !!!

**Comment by amtriathlon** [comment]
I will push the fix, but keep under observation just in case.
