### ISSUE TITLE
Pace display in Compare Activities & Intervalls Section

### ISSUE THREAD

**Issue by robolaf** [GoldenCheetah/GoldenCheetah#2188]
Hi, In the 'Compare Activities & Intervalls' Pace is displayed as fraction (3.5 min/km) - it should be 3:30.
![pacebug](https://cloud.githubusercontent.com/assets/7139815/20362802/213a3cfa-ac3d-11e6-9318-951077fca097.PNG)

Would be nice if this could be corrected. Many thanks.

**Comment by amtriathlon** [comment]
We need to change the call to getForSymbol and subsequent formatting at https://github.com/GoldenCheetah/GoldenCheetah/blob/eee3a0bb134aefca4c590ff543ccfab1ad626e90/src/Gui/ComparePane.cpp#L311 - https://github.com/GoldenCheetah/GoldenCheetah/blob/eee3a0bb134aefca4c590ff543ccfab1ad626e90/src/Gui/ComparePane.cpp#L321 for a call to getStringForSymbol which formats the value using RideMetric::toString method
