### ISSUE TITLE
GC 3.3 crash Mac OS 10.10

### ISSUE THREAD

**Issue by mondoshiwan** [GoldenCheetah/GoldenCheetah#2190]
steps:

at the edit chart -> selecting the *Paste Special* command with the control key. note: this command is only available  if something is copied to the clipboard.

In that opening dialog box, if you try to check the *first line has headings* check box… then GC will immediately crash.

On Monday i could check, if this happens with 10.11 and 10.12 too.

**Comment by mondoshiwan** [comment]
same thing with GC v4 and OS 10.11

**Comment by AartGoossens** [comment]
Replicated on MacOS 10.12.1 while trying to paste some data from Excel.

**Comment by liversedge** [comment]
We are no longer fixing bugs in 3.3 as 3.4 is now released.
Please remember to post the OSX crash log :)

**Comment by mondoshiwan** [comment]
still present in v4 here you go:

[GoldenCheetah_2016-11-25-122501_MacMini.crash.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/613504/GoldenCheetah_2016-11-25-122501_MacMini.crash.zip)
