### ISSUE TITLE
GC 3.4 Oxy chart

### ISSUE THREAD

**Issue by gadartt** [GoldenCheetah/GoldenCheetah#2193]
GC 3.4

Windows 64 bit version.

GC is locking up when I select the Oxy chart.  The chart doesn't appear, it just locks.  I have to use the OS to force quit.

**Comment by liversedge** [comment]
Please reset your charts and see if it continues. (view->reset layout)

**Comment by liversedge** [comment]
does it do it with a particular ride, perhaps the same one that causes merge to crash?

**Comment by gadartt** [comment]
Trying a different ride...   I tried a couple -- few rides have SmO2-- and they are fine.  I thought I had a bad file, but now when I go back to that file it is fine.  Odd.

**Comment by gadartt** [comment]
"that file" = the original file I had an issue with.

**Comment by gadartt** [comment]
I shut down GC and am back to having the issue with the original file again.  I shut it down again, went to one of my other files first and it is fine.  Then I go back to the original file I had an issue with and it works fine again.    It is weird.  I'll delete the file and re-merge the SmO2 data.

**Comment by liversedge** [comment]
send me the file it sounds like there is an issue

**Comment by gadartt** [comment]
I already deleted it.  :-(

**Comment by gadartt** [comment]
BTW, this issue was with the file that was causing the merge to crash.  I attached the files on that ticket.  I can't get the files to merge again.  Merging by timestamp just locks up GC, although it merged the files the first time.

**Comment by gadartt** [comment]
Nearly certain this was caused by bad data from combining activities.  Reported under GC 3.4 Combining activities #2192 .

Closing this issue.
