### ISSUE TITLE
Tacx wortex smart power controll not working.

### ISSUE THREAD

**Issue by KasparsSle** [GoldenCheetah/GoldenCheetah#2197]
Downloaded version 3.4 and connected my  garmin heart rate monitor + Tacx vortex smart with suunto ant+ dongle.  Downloaded some workouts from ERG db and started workout. I received heart rate, power, cadence reading  but power control was not working. Thought that there is a problem with my linux version. Same thing on windows 7. 

I made one workout with help of wizard. Power control started working. Same thing for windows 7  and linux 64 bit ports. Looks like something is not initialized until workout is created. 

Thank You. Nice Job.

**Comment by manuelpichler** [comment]
I can confirm this issue for Ubuntu 16.04., power control of the Tacx Vortex does not work when I choose a *.pgmf file. Everything else works like a charm.

thx for your work

**Comment by amtriathlon** [comment]
I am closing this since it refers to a very old version. Please reopen if you can recreate when v3.5
