### ISSUE TITLE
Ambit2 SML swimfile import fails using drillmode on watch (?) with GC 3.3 MacOS

### ISSUE THREAD

**Issue by mondoshiwan** [GoldenCheetah/GoldenCheetah#2198]
today i had a swim and was using the drillmode to manually add some lenght in the beginning of the workout. this seems to break the import from the original sml file, only the first 500m (1102rows of data) have been imported, but that workout was a bit longer… The fit file exported from movescount (5267 data rows) works, no issues there, I add both original files for further investigation. thx in advance!

[AMBIT_SML_swimfiles.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/607424/AMBIT_SML_swimfiles.zip)

**Comment by amtriathlon** [comment]
I would like to add support for Drill mode and length-by-length XData for SML files but I don't have an Ambit watch for testing so I would need more information.
Can you add a written description of the workout to help me to interpret the file?
Thanks!

**Comment by mondoshiwan** [comment]
sounds nice… :) i'll try to give as much support as i can… That specific workout started with a 300m warmup, but the watch missed some pools there, if i remember that right. Then followed 8x 50m, with drills on the first 25m, added manually at the end of that interval. You can find them in the sml file if you do a search for:

<Type>StyleChange</Type>

then you will find the drills:

<PrevPoolLengthStyle>Drill</PrevPoolLengthStyle>

hope this help for now

**Comment by mondoshiwan** [comment]
BTW, for swimmer it would be nice, if there would be a graphical bar chart that shows the intervals (by length) separated from the rests in-between. Don't know if this has been implemented in 3.4. i'm still on 3.3, due to Mac…

I'm doing a lot of intervals and the Ambit2 is missing often some pool length in my case… so an editor, based on that chart above, to adjust the length of the intervals, would be the coolest thing ever.

cheers, carsten

**Comment by amtriathlon** [comment]
The problem doesn't seems to be drill-mode per se, but the way it is used to "fix" missed lengths which triggers a bug in the import, I fixed that bug and the file now imports similar to the .fit one.
The problem is this is not drill mode intended use and, while it fixes distance, it produces very high speed values which impact on xPace/TriScore metrics.

I think the chart you suggest is similar to this tool to fix .fit files: http://www.swimmingwatchtools.com/, we don't have anything like this in v3.4 but the length-by-length records can be edited at the editor and there is a Fix tool to fix speed and distance data afterwards.

I will try to add length-by-length records for SML files in future versions.

**Comment by mondoshiwan** [comment]
thx for checking and clarifying!

To edit the interval lenght is really a pain with thousands of rows… :) for now im overwriting the whole Distance in Metrics.



Am 24.11.2016 um 15:27 schrieb Alejandro Martinez:

**Comment by amtriathlon** [comment]
You are right, to edit lengths is a PITA but it should be something quite
exceptional, IME the main reason swim watches misses lengths is a
not-streamlined-enough push-off from the walls, perhaps some attention to
turns and push-off can fix the root problem.

**Comment by mondoshiwan** [comment]
You are right, main thing is to keep an eye on the turns, but especialy with the Ambit2 this is not the only reason. After a while the watch will glitch and detects only half of the lengths, even if you push hard and saving too high speeds also.  Later, after some more Intervals the watch will be back again with right turn detection. So this a PITA too. The Ambit3 is used to be far better in turn recognation, but i don’t own one… and don’t want one… no ANT+ support for my Powermeter. 
thx!
