### ISSUE TITLE
Swedish translation imminent

### ISSUE THREAD

**Issue by henolo** [GoldenCheetah/GoldenCheetah#2201]
Hi,
just want to mention that in a few days I should be finished with the first run-through of the swedish translation. Still struggling to create an environment to do my own builds but I guess that will sort itself out with time. Meanwhile, where should I put/send the file? Seen some were published on the google groups forum. Big thanks to the German translators - did help a lot to have input from two languages (and the c++ "translator" as well :-) Do make it easier to understand context better. If someone wants a "pipecleaner" version asap, Just let me know. /Henrik

**Comment by liversedge** [comment]
Fantastic !

We are planning on a 3.4.1 shortly after Christmas so you have time. 
I'll let Ale respond on how to get the translation in

**Comment by Joern-R** [comment]
Henrik - if you want to build on Windows, just drop me a mail joern.rm at gmail.com - we can discuss than what you would need to build under MSVC

**Comment by amtriathlon** [comment]
Hi Henrik, great news!
When you have a gc_se.ts file you want to share you can email it to me, or rename it to gc_se.txt and upload here, and I will do the changes to the source code to add Swedish and commit your translation.

**Comment by henolo** [comment]
Thanks!
Indeed 3.4.1 appears feasible to sort out various inconsistencies, misunderstandings, and miscellaneous writing errors... 
Regarding builds, thanks for the support offer!  I started out with a win machine but after a while I moved on to ubuntu so for now I think I will spend some more time on the ubuntu one, but if I change my mind I do now know where to send questions!!
Will put a .txt here.

**Comment by henolo** [comment]
A file!

[gc_se_snapshot161125.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/613366/gc_se_snapshot161125.txt)

Need to know how accelerator keys are handled. Are they automatically adapting to what is "&":ed in the .ts or do one need to mimic the keys in .cpp exactly for it to work?

**Comment by amtriathlon** [comment]
You can choose the accelerator keys you want using "&", no need to try follow the English ones, just be careful there is no conflicts, there is an option in linguist to validate them.
