### ISSUE TITLE
Ambit sml import - slope seems to be to low / GC 3.4 Mac

### ISSUE THREAD

**Issue by mondoshiwan** [GoldenCheetah/GoldenCheetah#2204]
are the slope values calculated by GC? anyway they seemed to be too low. they are almost as half as compared to the values from an imported movescount tcx file, and that seem to be more realworld to me. the two ride files for a check:

[Ambit_ride.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/611692/Ambit_ride.zip)

**Comment by amtriathlon** [comment]
Altitude data is imported without modifications from SML file, you can check the values in Edit tab, slope is computed by GC by a generic process which is not particular for SML files, if altitude data is different may be movescount does some altitude correction.
In GC you can use Edit->Fix Elevation Errors to do the same base on an online service, this will recompute slope automatically based on the fixed altitude data.

**Comment by mondoshiwan** [comment]
issue closed too early… :)
movescount is not duing any altitude correction, i did a check in the editor. There is still a difference how GC is handling that data from the sml file compared to an tcx.

**Comment by mondoshiwan** [comment]
again…

here is a run with a turning point. 32m going down in the beginning - so 32 m going up at the end. Altitude is correctly imported from the sml file - graph is looking fine, but

slope is almost flated out…but there is an 8 to 10% descent and ascent.



i will open a new issue, if this won’t be checked

**Comment by amtriathlon** [comment]
I've closed this issue because, as you said, this is not a problem with SML import, there is an open issue related to slope calculation: https://github.com/GoldenCheetah/GoldenCheetah/issues/1536. Anyway you can reopen this if you have elements to think this is a different problem and/or particularly related to SML files.

**Comment by mondoshiwan** [comment]
did’nt knew that this is an open issue. But why is it working with a tcx file with the same altitude data…

The solution for now is to copy the entire slope values out of the tcx import and paste them over, that works for now.
