### ISSUE TITLE
Feature Request: offset power by absolute value

### ISSUE THREAD

**Issue by siovene** [GoldenCheetah/GoldenCheetah#2207]
I know that in GC you can modify the power by a percentage, but my other power meter seems to be at a fixed offset of -10 W (one is Garmin Vector, the other is Tacx Neo, and I assume those 10 W are partly due to drive train efficiency).

Could you modify the **Edit -> Adjust Power Values...** window to allow absolute values too, in addition to percentages?

**Comment by amtriathlon** [comment]
@Joern-R implemented this in https://github.com/GoldenCheetah/GoldenCheetah/pull/2608
