### ISSUE TITLE
Feature Request : Autosave Feature

### ISSUE THREAD

**Issue by rgeorge1985** [GoldenCheetah/GoldenCheetah#2208]
After performing multiple changes to an activity or activities, if user forgets to save changes and GC V3.4 crashes, the changes made are lost (something I have encountered multiple times). 

To increase productivity, an autosave must be introduced. Autosave interval must be user modify friendly. After crash, GC begins from last auto-save. Apologies if I'm overlooking such a feature if already present.

**Comment by liversedge** [comment]
there is a setting in preferences to warn about unsaved data on exit.
we deliberately do not autosave since undo/redo is not widely available.
