### ISSUE TITLE
GC 3.4 MacOS: Preferences window cannot be closed in fullscreen mode

### ISSUE THREAD

**Issue by AartGoossens** [GoldenCheetah/GoldenCheetah#2209]
Steps to reproduce: Open GC. Enter fullscreen mode. Open Preferences. Press Close or Save in Preferences window.
Outcome: Interface disappears and a black empty fullscreen window remains. Cannot be closed with CMD+w.
![screen shot 2016-11-25 at 14 37 30](https://cloud.githubusercontent.com/assets/4079295/20626872/c07e91ea-b31c-11e6-94d2-6b3511c1458b.png)

**Comment by liversedge** [comment]
this is how full screen works in MacOS.. you need to alt-tab

**Comment by AartGoossens** [comment]
I understand that but the Preferences window still needs to be closed. That is currently not possible without restarting GC. Otherwise you'll end up with this:
![screen shot 2016-11-25 at 15 16 37](https://cloud.githubusercontent.com/assets/4079295/20627738/4dd2d83a-b322-11e6-84ae-cba825eaab42.png)
Either the Preference window needs to close itself after pressing close or save or it should at least respond to CMD+w. At the moment it does neither.

**Comment by ritchey5440** [comment]
Sadly I must say, that this problem is still present to these days with GC 3.5 released. I don't get it, why the preferences window can't be separate and overlaid as the other windows are (like e.g. "CP and W' Estimator").

**Comment by amtriathlon** [comment]
I cannot reproduce this behavior using current v3.6 build on macOS Catalina, so lets assume it is already fixed.
