### ISSUE TITLE
feature request: importing Ambits personal app data

### ISSUE THREAD

**Issue by mondoshiwan** [GoldenCheetah/GoldenCheetah#2211]
One of the main advantages of Ambits is that you can write your own apps and record them to the sml file. Would be nice if these 'app data' could be imported to the xData too. e.g. for swimming i build a simple Rest Time Counter to determine the intervals, with that additionel data it could be helpful to fix the interval lenght in future.
Or for my rides i have created an own real time slope app…

Ambit can run 5 apps at a time max, but you don't have to store all of them. Format can be integer, float or time. Right behind the header in a sml file the apps are defined:

<Apps> <App> <Name>SWIC-2-1</Name> <AppId>10414323</AppId> <Format>Integer</Format> <Prefix>int</Prefix> <Logged>True</Logged> <Displayed>True</Displayed> <Running>True</Running> </App> <App> <Name>TotalRestTimeV_</Name> <AppId>10411403</AppId> <Format>Time</Format> <Prefix>Rest</Prefix> <Logged>True</Logged> <Displayed>True</Displayed> <Running>True</Running> </App> <App> <Name>sendoff</Name> <AppId>10547230</AppId> <Format>Time</Format> <Logged>False</Logged> <Displayed>True</Displayed> <Running>True</Running> </App>

In the data section they stored then like this:

<AppsData> <AppData> <AppNumber>2</AppNumber> <Value>94</Value> </AppData> <AppData> <AppNumber>1</AppNumber> <Value>3</Value> </AppData> </AppsData>

testfile:

[C8C70A511B001500-2016-11-25T07_05_32-0.sml.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/613445/C8C70A511B001500-2016-11-25T07_05_32-0.sml.zip)

this would be an awesome killerfeature… there is no other way to pull that data out of Movescount, till now…

thx in advance, carsten

**Comment by amtriathlon** [comment]
According to [DCRainmaker](https://www.dcrainmaker.com/2019/01/suunto-announces-decommission-plans-for-movescount-platform-impacting-some-watches.html), Suunto has pretty much abandoned this feature:
> The other less obvious semi-big ticket item here is that this officially kills off Suunto’s journey with their app platform. Once over on the new Suunto platform, the older series Ambit/Traverse units that could access the Suunto app store will no longer be able to do so. Suunto hints at this here and there, but it’s as clear cut as they could. Apps are dead. Simple as that. Though, I suppose most of us saw that coming. When Suunto released their Spartan series a few summers back, it lacked apps – so this isn’t an unexpected turn of events.
