### ISSUE TITLE
scrolling in TrainView window confuses the graphical pattern

### ISSUE THREAD

**Issue by mondoshiwan** [GoldenCheetah/GoldenCheetah#2213]
In TrainView on my 13" MacBook (Intel HD Graphics 4000 1024 MB 1280x800 resolution) srolling is confusing and doubling the arrangement of the pattern:

![bildschirmfoto 2016-11-26 um 11 55 23](https://cloud.githubusercontent.com/assets/23431166/20639940/d8a9e4e4-b3d1-11e6-93d7-a7cb8cd0db95.png)

with a mouse over it will rearange.

GC v4, MacOs 10.10

**Comment by liversedge** [comment]
yuck.

are you really on 10.10 ? (Yosemite)

**Comment by mondoshiwan** [comment]
on this machine…yes :)
on Monday i could do a test with 10.11 and 10.12 on other machines using higher resolution.

**Comment by liversedge** [comment]
ok thanks. its v3.4 btw.

**Comment by mondoshiwan** [comment]
ok… v3.4 :) this issue seemed not to be related to the MacBooks only. i tested on a MacMini with Intel Graphics 4000 1536MB with a native resolution 1920x1200. on 10.11 and 10.12 still the same issue. Even resetting the Layout doesn't help. Version 3.2 on a 10.6.8 machine is not! affected.

![bildschirmfoto 2016-11-28 um 10 40 44](https://cloud.githubusercontent.com/assets/23431166/20663748/ea423480-b558-11e6-97d9-e74894c72d31.png)

**Comment by liversedge** [comment]
Can you check you are using build 3955 ? (in about)

**Comment by mondoshiwan** [comment]
yupp! it is

**Comment by liversedge** [comment]
we are not going to develop this ui.
