### ISSUE TITLE
GC3.4: Incorrect import of speed data for running and swimming from tcx

### ISSUE THREAD

**Issue by onannen** [GoldenCheetah/GoldenCheetah#2218]
I'm new to GC and I'm using GC3.4 on a Win 10 64bit system. I have a Polar V800 to track my activities. To export the data and convert them to .tcx and .hrm files
 I work with the tool Bipolar. When I import swim or run data to GC the speed values are incorrect, although the data in the .tcx files are correct. At swimming almost all 
 speed values are 0. And at running the speed values are increased until around 38 km/h and than varying around that value for all the following data. I attached the source tcx
 files and screen shots from the editor in GC.
![gc_run_editor](https://cloud.githubusercontent.com/assets/17336716/20648639/bbeab6e0-b4ac-11e6-9c82-9fc9968d8f6b.PNG)

![gc_swim_editor](https://cloud.githubusercontent.com/assets/17336716/20648640/bbed3398-b4ac-11e6-808c-d209d8cf1703.PNG)
[GC_run_export.tcx.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/614715/GC_run_export.tcx.txt)
[GC_swim_export.tcx.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/614714/GC_swim_export.tcx.txt)

**Comment by Joern-R** [comment]
Sorry to say - but the problem are caused by your TCX files - which are not correct.

Your running file:
Speed in TCX is defined in m/s (I re-checked by exporting from Garmin Connect in .TCX) - 1 m/s == 3.6 km/h which is the format in GC - your data looks like km/h. (which makes 10.00 of your data to 36 in GC)

Your swim file:
Just a few samples in the beginning have values > 0. Which seem to be m/s as well. Then the rest is 0 - which is what GC shows.

**Comment by onannen** [comment]
Thank you for the fast answer. Than have to adjust the values before I import the file.
Btw is there a possibility to adjust the values resp. set a factor during importing into GC?

**Comment by amtriathlon** [comment]
The run file is easy to fix, you can copy the column from Editor to an spreasheet, divide by 3.6 and copy back if you want to preserve the TCX file speed vaiues, or you can use the Edit->Fix Speed from Distance tool for an easier procedure. The swim file doesn't seem easy to fix OTOH.

**Comment by onannen** [comment]
Thanks a lot! The tool to fix the speed works great.
