### ISSUE TITLE
GC 3.4: start time of laps on vivoactive hr

### ISSUE THREAD

**Issue by kemphoto** [GoldenCheetah/GoldenCheetah#2219]
I updated my vivoactive hr (device type Garmin 2337) to firmware 3.30. GC 3.3 would not import the new .fit files, but now GC 3.4 does. The issue is that the laps all have the same start time of 0:00 which can be seen in the Ride chart. I am attaching a couple of these files.

[1459345080.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/614793/1459345080.zip)
[1457018754.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/614796/1457018754.zip)

**Comment by Joern-R** [comment]
The problem was introduced by a custom field in the "laps" segment of the FIT file (through an non-Garmin CIQ app).

It's fixed via: https://github.com/GoldenCheetah/GoldenCheetah/commit/2e6dd6ce60021546498b59c1a38497b882504450  which will be part of the next release.
