### ISSUE TITLE
Error importing a Bryton Rider 350 .fit file

### ISSUE THREAD

**Issue by ddevilliers** [GoldenCheetah/GoldenCheetah#2224]
When importing my ride (.fit) logged with a Bryton Rider 530 the Time, Duration and Distance is wrong. Importing it into Strava has no problems.

**Comment by liversedge** [comment]
Have you tried v3.4?

**Comment by parlaghg** [comment]
I think that this is the same issue what is already tracked in #2029.
V3.4 makes some improvements, but it is still not good.
