### ISSUE TITLE
GC fails to detect R

### ISSUE THREAD

**Issue by LiamMcCalloway** [GoldenCheetah/GoldenCheetah#2228]
GC fails to detect R (R Studio detects it fine).

Distribution: Arch Linux. GC v.3.4

I tried to see in Rembed how the detection was done, but this is above my skill level..

If this helps, `export` returns no R-related environment variables.

**Comment by liversedge** [comment]
Please use the user forums for help.
https://groups.google.com/forum/#!forum/golden-cheetah-users
