### ISSUE TITLE
New activities uploading, but not updating PMC trend curves

### ISSUE THREAD

**Issue by davetapson** [GoldenCheetah/GoldenCheetah#2229]
Hi

I have used GC for several years, no probs, all great. 

However, when I now upload activities, the PMC chart (which is my goto) doesn't update.

The only thing that I've done that may have caused this it to try and enter a manual activity - it was after this point that the PMC chart stopped updating.

Any idea what could have caused this?

Windows 10, mid range 64bit laptop, uploading from Joule GPS.  As stated, it's worked fine for years.

Regards
Dave

**Comment by davetapson** [comment]
It seems that the Triscore / xPower / Relative Intensity / TRIMP Points are not being calcuated.  I suppose this is why the PMC chart is not being updated?
![working - nov 13](https://cloud.githubusercontent.com/assets/13338858/20879242/77d2d3ae-badb-11e6-95b7-817b2d67d120.PNG)
![not working nov19](https://cloud.githubusercontent.com/assets/13338858/20879245/799d001a-badb-11e6-9539-6a036e0fbfe0.PNG)
![pmc](https://cloud.githubusercontent.com/assets/13338858/20879243/7814eb68-badb-11e6-8127-484de8e726f9.PNG)

**Comment by liversedge** [comment]
Have you tried in 3.4 ?

**Comment by davetapson** [comment]
Yep - was using an older version and upgraded to try and fix the problem.

Am installing on another laptop to see if that version will update PMC chart (i.e. default settings etc)

**Comment by davetapson** [comment]
Looking at the screenshots I see that he Work and W'work values are not being calculated either.

**Comment by liversedge** [comment]
That will be because the ride doesn't include power.

**Comment by davetapson** [comment]
Look at the top screenshot - it was calculated there.  Am using PowerCal...

**Comment by davetapson** [comment]
Ok - so opened the two data files that produced the two screen shots above, and the one has power values (Watts) and the other does not.

Would that be why the PMC chart is not updating - would those values be mandatory - I suppose my question really is 'Can the data for the PMC chart only be calculated from the Power values provided by PowerCal, or can it be calculated from HR/duration etc?)

That said, I need to figure out why the power data is not being returned in the power file.

**Comment by davetapson** [comment]
Have installed GC on second laptop and downloaded last couple activities - they don't reflect on the PMC chart.  But probably related to the power data not being returned?

**Comment by liversedge** [comment]
Power based metrics will not be calculate if power is not present in the file !

**Comment by davetapson** [comment]
Ok, thanks.
