### ISSUE TITLE
[Feature Request] track gear usage

### ISSUE THREAD

**Issue by potuz** [GoldenCheetah/GoldenCheetah#2232]
It'd be useful to create a gear/components database and allow the user to track Km ridden/ran with each component. Is there any branch already trying to do something like this? I could fork the project and try to add this myself.

**Comment by panos1234** [comment]
You can track equipment with the current functionality. 

I track km or time for wheels, tyres, chain, power meter battery.

**Comment by potuz** [comment]
Ah thanks, I hadn't found it, I guess it's by adding Data Fields in Preferences.

**Comment by liversedge** [comment]
there is a video tutorial for metadata on the goldencheetah website.
