### ISSUE TITLE
Expression calculation issue

### ISSUE THREAD

**Issue by Audisport9** [GoldenCheetah/GoldenCheetah#2234]
Hello,
I'm trying to use SPEED and PACE in a few calculations. The charts below are my test charts to make sure of units and data points are correct. When these are used in a user data expression they are not always calculated correctly. If you look at the run cadence chart you will see that I have speed selected in curves, then i use SPEED in a user data expression. The green is the curves data points and the red is the calculated expression data points. The calculated should be identical to the green but it is not. This is true even if i turn off curves speed data in this chart. The Calculated expression values still display incorrectly.

Then when you look at the run pace and speed chart, you will see speed shows correctly but calculated pace is not correct. It is interesting how one chart to another is changing how the same calculated expression is displayed. Both SPEED and PACE are from the formula syntax and expressions wiki. At the moment i'm having to look at CSV data in excel and double check GC calculated data. It's not very efficient.

Thanks for the help,
Tim

![run_cadence_pace_graph](https://cloud.githubusercontent.com/assets/24303861/20912555/09ab6eb4-bb3e-11e6-8888-1b4572fc8065.jpg)
![run_cadence_pace_settings](https://cloud.githubusercontent.com/assets/24303861/20912556/09addcb2-bb3e-11e6-8351-383945777b3b.jpg)
![running_speed_pace_graph](https://cloud.githubusercontent.com/assets/24303861/20912558/09af21f8-bb3e-11e6-8388-1995c807b159.jpg)
![running_speed_pace_settings](https://cloud.githubusercontent.com/assets/24303861/20912557/09aec8b6-bb3e-11e6-815f-df46e756a70e.jpg)

**Comment by amtriathlon** [comment]
Discussed at the forum: https://groups.google.com/d/msg/golden-cheetah-users/3O3G5XUUqtA/N9yDH1z1DQAJ
