### ISSUE TITLE
Feature Request: Avg metrics from start

### ISSUE THREAD

**Issue by funkymaster** [GoldenCheetah/GoldenCheetah#2248]
It would be very helpful to have all the interval metrics not only for the interval.
I'd like to get the same metrics from start.
Exactly from start to the end of an interval.

e.g. if I have 3 intervals with 3, 5 and 2 minutes the interval metrics should show the following.

Interval 1
- time: 03:00
- time from start: 03:00

Interval 2
- time: 05:00
- time from start: 08:00

Interval 3
- time: 02:00
- time from start: 10:00

The same for distance, avg speed and so on.

Thanks in advance!

V4.0-DEV1607

**Comment by liversedge** [comment]
why is this useful for _every_ interval?

**Comment by funkymaster** [comment]
e.g. distance + climb meters to all these points would we get visible at a glance very clear in the workout summary table.
If we are going to lap races, we would have a nice table in the workout summary where we could see f.i. the avg speed from start increasing or decreasing.
This is sure more interesting for the summary table than for the charts where we can select what we need, but it would also be helpful there. As far as I know, wouldn't it be visible in all interval views (summary, charts, ...) if we select such a metric for intervals in the options?
But I know, this request duplicates the interval metrics.

**Comment by amtriathlon** [comment]
I am closing this since this feature seems very specific for the requesting user and, currently, this kind of metrics can be created by the user as Custom Metrics using the before function (see https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Creating-User-Metrics).
