### ISSUE TITLE
no negative temperature values in Stress and Oxy chart

### ISSUE THREAD

**Issue by funkymaster** [GoldenCheetah/GoldenCheetah#2250]
GC doesn't show negative temperature values in these charts.
I don't know if more charts are affected by this issue, because I haven't tested it due to lack of time.
May be the problem occurs because the temperature is linked to the speed axis labels.

V4.0-DEV1607

**Comment by liversedge** [comment]
screenshot?

**Comment by funkymaster** [comment]
Yes.
Additionally if I try to set the axis min max values in the activity temperature chart, the chart view toggles somehow strange.
I'll send you the fit file Mark.
![2016-12-11](https://cloud.githubusercontent.com/assets/21222589/21083809/c3009baa-bff8-11e6-93b8-787789fbf67a.jpg)
![2016-12-11a](https://cloud.githubusercontent.com/assets/21222589/21083810/c6f59f62-bff8-11e6-8c4d-953b12613db6.jpg)

**Comment by bgrabow** [comment]
In https://github.com/GoldenCheetah/GoldenCheetah/commit/c75092dd33f3a6867d608c8322cb9c9a0618feb3 the axis scale for some charts was changed to range from ymin:ymax instead of 0:ymax. Try checking if the problem still exists after applying this change.

**Comment by funkymaster** [comment]
Ok, how can I apply this?
Thanks.

**Comment by funkymaster** [comment]
Hm, ok, I found the dev. guide.
I think this will take a while...

**Comment by funkymaster** [comment]
Hi again,

I'm sorry, but I couldn't manage to build the project.
The links for Qt are invalid here: http://www.goldencheetah.org/developers-guide.html
and here: https://github.com/GoldenCheetah/GoldenCheetah/blob/master/INSTALL-WIN32
So I tried to use this one: http://download.qt.io/official_releases/qt/5.6/5.6.2/qt-opensource-windows-x86-mingw492-5.6.2.exe
but I got errors like "missing modules in (Qt) webengine, web... aso" when creating the makefile.
I'd set the flag nowebkit in gcconfig.pri.
So I don't know how to go on.
Due to a holiday trip and my profession, I can't test till mid Jan.

br

**Comment by bgrabow** [comment]
Send me the FIT file you're looking at and I can take a look at the charts with my build. I'll screenshot what it looks like and we can figure out from there if my changes fixed your issue.

**Comment by funkymaster** [comment]
Ok, I've sent you the file.

**Comment by funkymaster** [comment]
Have you got the file?

**Comment by funkymaster** [comment]
This seems to work now with v3.5-DEV1703

**Comment by liversedge** [comment]
Thanks for the feedback. Will close.
