### ISSUE TITLE
Training Peaks Synchronisation- Network Transfer Error

### ISSUE THREAD

**Issue by chrisnew69** [GoldenCheetah/GoldenCheetah#2254]
When trying to sync with Training Peaks the following error is appearing.  This happens with both version 3.3 and 3.4

Error:Network transport error (401): Error downloading https://www.trainingpeaks.com:443/tpwebservices/service.asmx - server replied: Internal Server Error

<img width="417" alt="screenshot 2016-12-16 12 36 30" src="https://cloud.githubusercontent.com/assets/24607010/21263007/4df8782c-c38c-11e6-9706-46198b8ce9a4.png">

**Comment by liversedge** [comment]
https://groups.google.com/d/msg/golden-cheetah-users/g3_bsD-U9Zo/yFlRd5ZLCwAJ
