### ISSUE TITLE
Feature Request: Activity Title in LTMPopup.cpp window.

### ISSUE THREAD

**Issue by markalston** [GoldenCheetah/GoldenCheetah#2255]
When using the PMC chart I often want to click on some activity to see what I did that made my LTS or STS jump.  

The popup window is handy with all the metrics and activities for that day but without the activity title I find myself having to go into Activities to figure out what that session was.

The pop up shows the activity notes but if the activity title was shown just above the notes that would be super handy.  

I think that the following change would do it but I currently can't test:

```

void
LTMPopup::rideSelected()
{
    // which ride is selected
    int index = 0;
    if (rides->selectedItems().count())
        index = rides->selectedItems().first()->row();

    // do we have any rides and is the index within bounds
    if (selected.count() > index) {

        RideItem *have = context->athlete->rideCache->getRide(selected[index]);

        if (have) {

            // update summary
            metrics->setText(""); //! stop crash (?)
            metrics->setText(setSummaryHTML(have));

            notes->setText(""); //! stop crash (?)
            // Changed the code below to show activity title in notes. Just a quick idea of possibly how to do it.
           QString notes_value =have->getText("Title", "");
            if (notes_value == "") {
                  notes->setText(have->getText("Notes", ""));
            } else {
                  notes->setText(notes_value + "/n" + have->getText("Notes", ""));
           }
        }
    }
    resizeEvent(NULL);
}
```

Thanks.

**Comment by liversedge** [comment]
"Title" is a metadata field you have created, it isn't standard.

Sorry.

**Comment by markalston** [comment]
Ok, what about adding a "chart edit" function like all the other charts have where we could add metadata fields to the popup?
