### ISSUE TITLE
Work exported in Cal from device, reported as KJ in GC

### ISSUE THREAD

**Issue by potuz** [GoldenCheetah/GoldenCheetah#2257]
I found [Golden Cheetah - Bug #387 (New) Wrong amount of Work (kJ) displayed](https://groups.google.com/forum/#!topic/golden-cheetah-users/WoNneW0orX8) with essentially the same issue. My Garmin Edge 520 reports total work in Calories for an activity (and does not provide an option to change this unit) and GC reports the exact same number in KJ. 

I see hardcoded the string "Work (KJ)" in [ltm-summary.html:35](https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/Resources/html/ltm-summary.html)  and in [BasicRideMetrics.cpp](../blob/master/src/Metrics/BasicRideMetrics.cpp) the setting is both KJ in Imperial Units and Metric units. 

Am I right to assume that GC just reports in KJ what's actually Cal in this case?

**Comment by liversedge** [comment]
This comes up soooooooooooo often, we should put it into the FAQ.

Energy Out as a percentage of Energy burned is Human Efficiency whilst cycling is typically in the 23-25%.
Energy Out is Power Output is measured in Watts, which in Energy is Watts x Seconds Joules.
To Concert 1 Joule is 0.000239006 Calories.

__So, basically joules and K Calories are the same__
Work / Efficiency * Convert / 1000 = KCals.

**Comment by potuz** [comment]
Ohhh crap the worst part is that I should've thought about this as is very much remarked in a famous book. Sorry for the fuzz. I looked for a forum before posting this time but the only thing I found is a Google group but they require a phone to register an account
