### ISSUE TITLE
Athlete auto import saves fit files a second time if PC time zone is changed

### ISSUE THREAD

**Issue by funkymaster** [GoldenCheetah/GoldenCheetah#2258]
Due to a holiday and training trip in another time zone I changed the time zone on a Win7 x64 computer from +01.00  to 00.00.
The next time when I opened GC, the auto import feature saved all the already stored workouts of the last 90 days once again.

V4.0-DEV1607

**Comment by funkymaster** [comment]
To clarify this a little.
This bug duplicates the workouts, where 50% of them simply never have been done. I assume if I would change the time zone to f.i. -05.00 again, all the workouts would be stored a third time. This is a little nasty because it makes the PMC trend unusable. To delete the workouts does not help, because they are stored again when I open GC the next time.
I don't know how the auto import feature checks if a workout is already stored, but it looks like the local time is involved in it. Maybe it would be better to use UTC to determine if a workout was already stored.

**Comment by Joern-R** [comment]
Fix via https://github.com/GoldenCheetah/GoldenCheetah/commit/bd62548a46f050c9441eb24238fdf4179a22e516
