### ISSUE TITLE
Erratic speed from Tacx trainers

### ISSUE THREAD

**Issue by dresco** [GoldenCheetah/GoldenCheetah#2259]
It seems lots of people are still affected by erratic readings from Tacx trainers, following the move away from nullCount processing in 48317fb7a78f625e0e72b3ccb3410cd6cad5f5b7, this would probably be a good fix to get into 3.4.1

The underlying issue is that instead of providing event updates with every message, the TACX trainers send 3 or 4 ANT messages with no updates, interspersed with bigger jumps in values. This short series without updates is enough to trigger the 'stopping' logic in the above commit.

I looked into this earlier in the year, and I think we have a few options;

1) Revert to original nullCount logic, zeroing out speed and cadence after 12 unchanged messages (3s). Proven to work, but does make stopping jerky when riding to a video (the original issue that @vlcvboyer was addressing).

2) Blacklist speed and cadence sensor if also a Tacx FE-C device. Speed and cadence data also comes from the FE-C channel, so hiding the S&C channel would 'fix' the majority of new smart trainers. Still leaves older trainers broken though..

3) Determine device manufacturer, and revert to original nullCount logic only for Tacx devices

4) Hybrid approach, trigger on nullCount, but also ramping down instead of a hard stop. (An old patch that was never submitted upstream, but gives an idea of the approach is here 65adcb5de23ad66e55049cd0d7869a8d22370c3f)

I think my preference would be for 3 or 4, very open to suggestions though..

**Comment by liversedge** [comment]
I vote 3 - to isolate for Tacx, its their borked telemetry that causes the problem?
And we have the code already, so no major effort.

**Comment by dresco** [comment]
Cool, unless Vianney  disagrees, I'll look to do that this week. Should act as a gentle reintroduction before tackling anything more complex!

**Comment by dresco** [comment]
Sigh, the little detail I'd forgotten about is that the Speed & Cadence sensor profile doesn't include a manufacturer data page :(

**Comment by liversedge** [comment]
but it comes from the same channel as the tacx FE-C device, so can sport it that way instead ?

**Comment by dresco** [comment]
Yeah, that was the approach I took for the blacklisting option (basically just ignores the S&C channel if there is a FE-C channel with the same device id). I'll update my code against current master & post a new link for review.. 

Only other problem is that of course it won't work for older (non FE-C) Tacx trainers. Must admit I'm not sure what models that encompasses?

**Comment by liversedge** [comment]
IIRC Its only been reported for FE-C trainers, Tacx didn't do open ANT+ prior to that. They recently saw the light :)

**Comment by liversedge** [comment]
Any update on this? Has it been fixed, and should this issue be closed?

**Comment by dooferdog** [comment]
Guys, I am still a user of Golden Cheetah struggling with the erratic speed input using my Tacx Vortex. As you seem to have identified the issue is there any chance of applying the fix as it drives me nuts and seems to wreck my distance stats also? Would be much appreciated.

**Comment by dresco** [comment]
Sorry, I've not touched the code in a couple of years, but from memory this only affected the Tacx speed & cadence channel. If you pair with the trainers FE-C channel only then I don't think you'll see the problem?

**Comment by dooferdog** [comment]
Thanks for the hint. I've only just dusted off the trainer after a couple of years and thought the pairing I'd done with GC was fairly automatic. Any hints as to how to do what you are suggesting please?. Thanks.
