### ISSUE TITLE
Smoothing in Realtime charts

### ISSUE THREAD

**Issue by MoxyRoger** [GoldenCheetah/GoldenCheetah#2261]
The smoothing in Realtime charts doesn't work like I'd expect it to.  When the smoothing value is adjusted, it induces an offset in the data trace.  See the following video.

[https://youtu.be/YuLxnX7cux0](url)

**Comment by rkantos** [comment]
I think I'm also experiencing this problem. What I also get is that the chart only displays 10 seconds of data while I'm still shown the 10...20...30...40...50...60 "Seconds Ago" bottom axis titles. Shouldn't the chart thus display 60 seconds of data? How is the chart supposed to work?

**Comment by amtriathlon** [comment]
Smoothing is implemented as a moving average of the last N 200msec/5Hz samples, were n is the value you select from 1 (no smoothing) to 150 (last 30sec average), and yes, it necessarily introduces a proportional delay.
