### ISSUE TITLE
SmO₂ and tHb not recording in Trainer.

### ISSUE THREAD

**Issue by gadartt** [GoldenCheetah/GoldenCheetah#2265]
I am using a BSX Insight.  I have it paired using the Moxy setting in Train view.  SmO₂ displays correctly on the screen. I don't display tHb. I assume it displays fine as well, but I don't know.

Attached are my workout files.  The workouts were repeated serially. I didn't get off the bike, nor stop my BSX Insight between sets.  I performed the first workout, saved it, and then started the second in Train view. 

When I look at the files afterward, the SmO₂ and tHb are intermittently recorded -- mostly zeros.  The second set doesn't have tHb data series although I thought it would.  I don't know if that is another issue or not. 

[Files.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/674537/Files.zip)

Greg

PS:  GC Version 3.4 build 3950 on Windows 10 - 64 bit.

**Comment by grauser** [comment]
fin in commit 7bfe33812440104697c8db6999d1da4040433bda
