### ISSUE TITLE
cant import a sigma slf file

### ISSUE THREAD

**Issue by frankerbs** [GoldenCheetah/GoldenCheetah#2271]
I use the new sigma Rox 11.0.
Until now by using the Rox 10.0 the import was perfect. But today after my first ride GC shuts alwas down by pressing the save button at the import dialog. The first import step is successful, but the second not.

Where should I send the *.slf file to?

**Comment by frankerbs** [comment]
[2016_12_31__10_49_LongSlowBikeRischenauPolleEmmerthalPyrmont.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/679670/2016_12_31__10_49_LongSlowBikeRischenauPolleEmmerthalPyrmont.zip)

![greenshot_2016-12-31_15-36-10](https://cloud.githubusercontent.com/assets/24854282/21577967/c53b5c4a-cf6e-11e6-9daf-0c470450ca2e.jpg)

**Comment by Joern-R** [comment]
Rox 11 changed the file format  and does not contain the "samplingRate" value - "Aufzeichnungsintervall" anymore, which is required for GC to work.
As a workaround you can modify your files by changing the "0" in the line
`<samplingRate>0</samplingRate>` to whatever you have configured. 
Your example uses 
`<samplingRate>1</samplingRate>` then the import to GC works again.

A fix is done for the next release: https://github.com/GoldenCheetah/GoldenCheetah/commit/e64db28e54fbd97cc689ee7e37860dff94026a9a
