### ISSUE TITLE
weird text

### ISSUE THREAD

**Issue by matty-1973** [GoldenCheetah/GoldenCheetah#2274]
I have recently installed Golden Cheetah on macOsx, when opening i have strange icons instead of txt.
Not sure if its an install problem or just something i have/haven't done?

**Comment by peteaylward** [comment]
I'm getting this too. It's legitimate text but using a non-system icon font I've got installed: 'Sports' in my case.

MacOS Sierra 10.12.2 

![athlete_pete](https://cloud.githubusercontent.com/assets/1489374/21594560/e59b43ca-d11b-11e6-97bb-1027fd66ad97.png)

**Comment by matty-1973** [comment]
Thanks for that Pete, makes sense now. Disabled the offending font, now everything is whole lot easier to read...

**Comment by Joern-R** [comment]
Consider this to be resolved then. 

Thanks.
