### ISSUE TITLE
Export ride files as .FIT format

### ISSUE THREAD

**Issue by msiniscal** [GoldenCheetah/GoldenCheetah#2275]
All of the other major file formats are available except .FIT  The .GPX format does not retain all the metrics and the .TCX format is about 35 times the size of a .FIT. When I edit out wattage spikes I need to save the file and upload to Strava, otherwise I get bogus historical W and W/kg data.
Is .FIT file trademarked or licensed? Is it possible to save as .FIT?

**Comment by liversedge** [comment]
FIT export has been completed and will be part of v3.5

**Comment by msiniscal** [comment]
Thanks I was able to correct errors, output a .fit file and it loaded correctly on Strava.


Matt Siniscal



________________________________
