### ISSUE TITLE
W' matches/Intervals

### ISSUE THREAD

**Issue by lethhenning** [GoldenCheetah/GoldenCheetah#2280]
I can´t get it to find intervals based on W' cost.
It don´t find W' matches either.

OSX version 3.4 build 3957

<img width="874" alt="skjermbilde 2017-01-04 22 03 35" src="https://cloud.githubusercontent.com/assets/24833224/21659250/253f115a-d2ca-11e6-8f67-c334979d0be6.png">

**Comment by liversedge** [comment]
Set your W' tau to zero in athlete settings.
Its a bug that we've fixed in the source, but will be in the next dev build.
