### ISSUE TITLE
GC crashed  when I start to create a user interval with the mouse

### ISSUE THREAD

**Issue by fbaecker** [GoldenCheetah/GoldenCheetah#2281]
Hello,

I am using Version V3.4-RC2. When I am in activities the ride view an try to create a user interval with the mouse and the left mouse button GC crashed. 

![srceen](https://cloud.githubusercontent.com/assets/24937778/21682223/b5d95318-d353-11e6-96e8-973644b1e5bd.JPG)

Regards,
Frank

**Comment by liversedge** [comment]
please try the release binary from www.goldencheetah.org. RC2 is old.

**Comment by fbaecker** [comment]
I have installed the version from www.goldencheetah.org but unfortunately this version v3.4 32bit Windows has the same problem.

**Comment by fbaecker** [comment]
I did the same action with a ride, what I import today and with this file it works. So it seems it is only a problem with some files.

I hope this info is helpful for you.

**Comment by dcquad** [comment]
you know, I see the same crash on OS X 10.14 Mojave using the latest dev build. I can't seem to create a user interval without a crash.

**Comment by amtriathlon** [comment]
I cannot reproduce this issue on v3.5 RC1.
