### ISSUE TITLE
Pinning a CPU at 100%

### ISSUE THREAD

**Issue by joekearney** [GoldenCheetah/GoldenCheetah#2283]
On Mac/Sierra, built against #2276.

I did a training session, stopped that but left GC open, and an hour later noticed low battery and spinning CPU. Attached is a sample log from Activity Monitor.

I might guess from this that the KettlerConnection is still open, spinning in serial requests to it.

I don't know if this is something introduced by the Kettler serial support or something that can happen more generally.

[gc-burn-cpu-sample.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/689788/gc-burn-cpu-sample.txt)

**Comment by Ramoonus** [comment]
does this error still exist?

**Comment by joekearney** [comment]
I don't know, I haven't tested this for a long while. Happy to close this if there's no further evidence.
