### ISSUE TITLE
Feature request: Display multiple ANT+ devices HR and power on screen

### ISSUE THREAD

**Issue by rkantos** [GoldenCheetah/GoldenCheetah#2287]
Hi,

Could you add a feature to Golden Cheetah similar to these apps:

https://play.google.com/store/apps/details?id=com.frankandroid.antfitnessMultiHRM

https://play.google.com/store/apps/details?id=com.iforpowell.android.ippeloton

Basically what is needed is to scan multiple ANT+ devices and display their data on the screen. I know most USB / ANT+ -devices have a limitation of 7-8 devices, but this could be circumvented by attaching multiple of them and / or like the first app seems to circumvent hardware restrictions: 

"Using more that the foreseen 8 channels available to the ANT+™ chip, requires to force the listening mode and leave the TX always on!! It may not work correctly or even not detect HRM belts, according to your setup. "

**Comment by amtriathlon** [comment]
I am closing this since it will not likely be implemented, for the reasons stated in https://github.com/GoldenCheetah/GoldenCheetah/issues/974#issuecomment-581028446
