### ISSUE TITLE
Critical VAM x-axis

### ISSUE THREAD

**Issue by matthieudelcourt** [GoldenCheetah/GoldenCheetah#2289]
Hi, I downloaded the GC version 3.4 (the latest official version) and it seems that the problem on the Critical VAM x-axis is back. I don't see the x-axis before 5min. Also, comparing the data to Strava it seems that the values are quite off (100m/h to 200m/h difference). I'm happy to give you an example on my own data. I think that the problem also carries over the hovering option which  is also incorrect. The x-axis isn't therefore showing the 1min VAM in place of the 5min for example (which makes it higher than it should).

Any chance this can be adjusted?
Thanks a lot for your amazing coding skills!

Cheers :-)
Matt

**Comment by amtriathlon** [comment]
This is by design: https://github.com/GoldenCheetah/GoldenCheetah/blob/e06c93ca0e39968a006313c99eb6bb392522ba32/src/Charts/CPPlot.cpp#L1653
