### ISSUE TITLE
Golden Cheetah doesn't stop

### ISSUE THREAD

**Issue by pratoni** [GoldenCheetah/GoldenCheetah#2290]
I don't know if this is a known issue or not.

I have the Golden Cheetah 3.2.0 QT4 32 bits (because it's on an old PC with Windows XP).

When I click on the "X" (cross) button to close the GC, it closes the window but the process doesn't die.

If I open the Task Manager, I see that the "GoldenCheetah.exe" process doesn't disappear, no matter how much time passes from the closing of the program... 

When I try to shutdown the PC, the Windows says that the GC it's still open and tries to close it.

I allways have to choose the "End Now" option to kill the process...

It's this normal?

**Comment by liversedge** [comment]
No, thats not normal !

**Comment by pratoni** [comment]
It's there anything that I can do to correct the problem?

**Comment by pratoni** [comment]
Another detail...

If I close the GC and then open it again it launches another "GoldenCheetah.exe" and the previous stays alive. I see then 2 "GoldenCheetah.exe" processes on Task Manager...

**Comment by liversedge** [comment]
Does it do the same if you run it as administrator?

**Comment by pratoni** [comment]
The user is already an administrator of the PC.

I don't think that XP has that "Run as Administrator" feature...

**Comment by liversedge** [comment]
I'm not sure then, if you create a new athlete and open that (with no data) does it shutdown properly?

**Comment by pratoni** [comment]
I will try latter and give you feedback...

**Comment by Joern-R** [comment]
Since this problem refers to an old version with an OS not supported any more I will close it. If the problem appears on the latest version, please either re-open or create a new issue on this.
