### ISSUE TITLE
Toolbar is too high / wasting screen estate

### ISSUE THREAD

**Issue by arunh** [GoldenCheetah/GoldenCheetah#2292]
The toolbar is too high for its content on MacOS (possibly other OS too). Whilst this isn't an issue on larger screens, when used with a 13" laptop on the go it is actually quite a large section of wasted screen estate since the size is not proportional. I think the UI will look cleaner if the tool bar is sized to be just high enough to fit the buttons and search bar. I've tried to show what I mean in attached screenshot.

I have a fixed for this, can submit a pull request unless there is a good reason not to do this?

![screen shot 2017-01-11 at 16 53 42](https://cloud.githubusercontent.com/assets/804578/21857843/cdc19b78-d81e-11e6-9d12-a7f29ea506e0.png)

**Comment by liversedge** [comment]
you can hide the toolbar from the view menu.

**Comment by arunh** [comment]
I realise that, but wouldn't it make sense to correct the padding - I have
a code fix?
