### ISSUE TITLE
Translation File Names Incorrect - Fails Build on Clean Checkout

### ISSUE THREAD

**Issue by arunh** [GoldenCheetah/GoldenCheetah#2294]
Clean checkout:

    $ cd ~/Projects/GoldenCheetah/qwt
    $ cp qwtconfig.pri.in qwtconfig.pri
    $ cd ../src
    $ cp gcconfig.pri.in gcconfig.pri

Then:

    qmake -spec macx-g++ -recursive

Results in:

    RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_fr.qm'
    RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_ja.qm'
    ...

Issue is that the files in Resources/translations are named:

    gc_fr.ts
    gc_ja.ts
    ...

Correcting files names in 'Resources/application.qrc' fixes issue.

**Comment by amtriathlon** [comment]
No it's not a file name issue, .ts files are the source translation files and .qm are the binaries resulting after processing using lrelease tool, make creates them if lrelease path is correctly configured in gcconfig.pri

**Comment by Evo221** [comment]
@amtriathlon I'm seeing the same issue on Debian 10 with QMAKE_LRELEASE correctly set in gccconfig.pri. I'm trlying to build GoldenCheetah-3.5-DEV1903 from v3.5-DEV1903.tar.gz.

```
% qmake -recursive
Reading /home/evo/opt/GoldenCheetah-3.5-DEV1903/qwt/qwt.pro
 Reading /home/evo/opt/GoldenCheetah-3.5-DEV1903/qwt/src/src.pro
Reading /home/evo/opt/GoldenCheetah-3.5-DEV1903/src/src.pro
RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_fr.qm'
RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_ja.qm'
RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_it.qm'
RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_pt-br.qm'
RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_de.qm'
RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_ru.qm'
RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_cs.qm'
RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_es.qm'
RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_pt.qm'
RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_zh-cn.qm'
RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_zh-tw.qm'
RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_nl.qm'
RCC: Error in 'Resources/application.qrc': Cannot find file 'translations/gc_sv.qm'
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
```



I can provide the log of running
```
qmake -d -recursive
```
if it would help. I can also open a new issue if necroing this one is frowned upon.
