### ISSUE TITLE
Travis CI Deployment

### ISSUE THREAD

**Issue by arunh** [GoldenCheetah/GoldenCheetah#2297]
Travis deployment to GitHub releases is currently disabled. Comments in '.travis.yml' note this is due to a read-only filesystem error. The reason for this is that in the 'after_success' section, the cwd is changed to /Volumes/GoldenCheetah, moving away from the GitHub root. Returning to the GitHub root at end of 'after_success' with 'cd -' would do the trick and deployment could work. 

For deployment to work properly, would also need to tag the build in Git which can be done with a couple of lines in 'after_success'.

I can look at this if there is appetite for it? Seems useful to have the product from a Travis build captured rather than discarded. Could tag it in the form 'golden-cheetah-master-$TRAVIS_BUILD_NUMBER'.

    ##deploy broken in travis, read-only filesystem error
    ##before_deploy:
    ##- gem install mime-types -v 2.6.2
    ##deploy:
    ##  provider: releases
    ##  api_key: $GH_OAUTH_TOKEN
    ##  file: GoldenCheetah_$QT.dmg
    ##  skip_cleanup: true
    ##  on:
    ##    tags: true

**Comment by liversedge** [comment]
Please do, this would be absolutely fantastic.

Let me know how I can help (note the Today's Plan secrets have not been added to the gems yet).

**Comment by arunh** [comment]
OK, leave it with me. I'll put a pull request together over the next week
or so.

**Comment by arunh** [comment]
Pull request #2301 submitted.

**Comment by liversedge** [comment]
OK, so what do I need to do ?

I'm a CI numpty, always get it wrong.....

**Comment by arunh** [comment]
Merge the pull request, then I've put some instructions in the comments of
the request telling you how to generate the API key. Let me know if you
need more info?

**Comment by arunh** [comment]
I just noted that the repo name is arunh/GoldenCheetah (which is my fork) -
you're going to want to change this to 'GoldenCheetah/GoldenCheetah' when
you update the api_key. Sorry about that, not sure how that slipped through!

**Comment by liversedge** [comment]
I've got travis installed, but not clear what section of the .travis.yml file you want deleting before running ```travis update releases```. Also, there are a number of secrets in there and don't want to lose them.

You on skype for a brief chat to explain?

**Comment by liversedge** [comment]
Asks me to upload a file?
```
markl@monolith:~/Projects/Live/GoldenCheetah$ travis setup releases
Username: liversedge@gmail.com
Password for liversedge@gmail.com: **********
File to Upload:```

Sorry for dumbass Qs but have no experience of travis

**Comment by arunh** [comment]
File to upload is our artefact, you want 'src/$FINAL_NAME'

Answer yes to following three question after this

I'm on skype, can call you in 10 mins? What's your username?

**Comment by liversedge** [comment]
I'm mliversedge, am on now. Think I've updated the key.

**Comment by arunh** [comment]
Yep, looks like you've sorted it. I've sent a contact req on Skype...
message me on there if you do need to chat - otherwise I'll keep and eye on
the CI build.

**Comment by liversedge** [comment]
Yes, now we need some way of marking a commit to generate a build instead of doing it for all.
Could get messy !

Something like #Publish-Build at the end of the commit?

Any ideas on that?

**Comment by arunh** [comment]
Travis can be configured to only deploy tagged commits, so possibly could...

add the following in the "deploy:on" section of travis file.

    on:
      ...
      tags: true

Then after commit you want to release and before push e.g

    #git add / commit files for change
    git tag -a v3.4-RC1 <commit id>
    git push

I'm no git expert but I think this would work.

Bit more info here:
https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A

and

https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by liversedge** [comment]
Perfect, that makes sense.

**Comment by arunh** [comment]
I'll test it out on my fork tomorrow if I get a chance, but it seems to be
the "standard" way deploy is used (although I haven't before being more of
the continuous deployment mindset) so sure we can get it to work.

**Comment by liversedge** [comment]
I added a tagged commit but no builds was deployed, suspect there is something missing.
Would be great to get this working.

**Comment by arunh** [comment]
What commands did you use to tag / commit / push?

**Comment by liversedge** [comment]
git commit -a --edit 
git tag -am 

git push origin master
git push --tags origin master ## realised I needed to push tags explicitly, but did before build in progress

**Comment by arunh** [comment]
Try this sequence, will push the file and tags together...

git commit -a --edit
git tag -am
git push --follow-tags origin master

**Comment by arunh** [comment]
Also, when you tag - make sure you fix it on a commit, e.g.

git tag -a tag-release-1 7d4c9f6384d0b76ca28f3e7c9980bb982272fde6

**Comment by arunh** [comment]
Just to confirm, tested working with tags in my fork. Here is the sequence
I used (note I am working on a branch called tagtest so replace that with
master or your branch name)

git branch tagtest
git checkout tagtest
vi README.md #make a change
git add README.md
git commit -m "Testing tag release"
git log #grab the commit id from above
git tag -a tag-release-1 7d4c9f6384d0b76ca28f3e7c9980bb982272fde6
git push --follow-tags origin tagtest

**Comment by liversedge** [comment]
Cool. I must confess I thought all tags were for a specific commit.

**Comment by arunh** [comment]
Yes, I think you're right on that.

**Comment by liversedge** [comment]
I think this can be closed now?

**Comment by arunh** [comment]
Agree
