### ISSUE TITLE
Application Crash on Activity Download

### ISSUE THREAD

**Issue by watermelonjam** [GoldenCheetah/GoldenCheetah#2298]
When downloading an activity from an ancient PowerTap head unit (from a 300PT Pro trainer), GoldenCheetah,exe version 3.4 crashes on Windows 7 SP1.  Version 3.3 did not.  The interface is Serial USB using the FTDI driver.  The crash occurs after writing the raw data
[2017_01_13_17_32_11.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/705588/2017_01_13_17_32_11.zip)
.  Event log details:

Faulting application name: GoldenCheetah.exe, version: 0.0.0.0, time stamp: 0x583170c6
Faulting module name: ucrtbase.DLL, version: 10.0.10586.9, time stamp: 0x5642c48d
Exception code: 0xc0000417
Fault offset: 0x0000000000068539
Faulting process id: 0x2a4c
Faulting application start time: 0x01d26df77e979275
Faulting application path: C:\Program Files\Golden Cheetah\GoldenCheetah.exe
Faulting module path: C:\Windows\system32\ucrtbase.DLL
Report Id: d4a30965-d9ea-11e6-a958-e4b318188d5e

**Comment by liversedge** [comment]
I can't recreate on Linux with the latest build, so maybe it is fixed.
Will try on Windows with the official build later today and see.

**Comment by liversedge** [comment]
Are you still experiencing this issue?

**Comment by watermelonjam** [comment]
I am.  Downgrading to previous version kept me going through the winter.  But that one doesn't like the data from Garmin Connect IQ apps on my outside bike.... which is fixed in 3.4.

**Comment by liversedge** [comment]
You are downgrading to 3.3 and the problem goes away?

**Comment by watermelonjam** [comment]
It goes away.  3.3 recognizes that the previous result was a crash, notifies me, then starts normally.  The data that caused the crash isn't loaded, but can be downloaded by 3.3 without issue.
