### ISSUE TITLE
Developer's Guide link is broken on wiki

### ISSUE THREAD

**Issue by ssalenik** [GoldenCheetah/GoldenCheetah#2302]
Hi,
The link to the dev's guide on the wiki (http://www.goldencheetah.org/developers-guide.html) is no longer valid. Not sure if this guide exists somewhere else.

**Comment by liversedge** [comment]
Will write a new one and put into the wiki

**Comment by x2764tech** [comment]
@liversedge is there any update on this? I've been trying to get something building/working on Windows (and have updated the wiki with my findings) but I getting to a point where I'm stuck.
I know @Joern-R has done some work on this, so it would be great to get his input too.

**Comment by Joern-R** [comment]
I need to find the time - biggest topic is not how to build GC in MSVC - but how to build the libraries - they are partly quite tricky.

For now you can follow / and download the dependencies from our CI build as described in the Appveyor .yml file. For Appveyor I have bundled the dependencies in addition to MSVC and provided a .pro which allows build with those dependencies.

You find some info also here:
https://groups.google.com/d/msg/golden-cheetah-developers/m97IfBQR-8o/TsMDblWyAgAJ

**Comment by Joern-R** [comment]
Build instructions for Windows have been updated to the current state:

See: https://github.com/GoldenCheetah/GoldenCheetah/commit/7b59dd68c704222df633fb72dd417eac56f5befc

Feedback/Adjustments are welcome - I do not have a totally clean environment to test it.

Thanks.
Joern
