### ISSUE TITLE
Wahoo Kickr speed fluctuates between actual and 0 (Ant+)

### ISSUE THREAD

**Issue by planetawylie** [GoldenCheetah/GoldenCheetah#2303]
Hi, I'm on GC build 3950, v3.4, Win 10. Must say first, the new version is fantastic. So much faster and loving the graphing and training editor. Kudos!

I borrowed my friend's new Wahoo Kickr (on latest firmware) as I am thinking of getting one, and hooked it up to Zwift....that was a completely different experience to my current 'dumb' trainer!

Then hooked it up to GC. Everything paired successfully but the speed readout in training mode fluctuates between actual and zero...everything else appears fine. So I paired up the Kickr to my Garmin and it shows the speed steadily as did Zwift (all this is Ant+). The (iOS) Wahoo utility app shows via bluetooth the speed is consistent too.

I recorded a session on both GC and Garmin and I've attached their files 
if it helps. Or is there a known issue with the Kickr. In the past it has had a few issues but I was hoping they had ironed most of those out by now.

Thx,
Andrew

[GC Kickr issue.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/711943/GC.Kickr.issue.zip)

**Comment by liversedge** [comment]
make sure you don't have a gc-10 paired.

**Comment by p3ck** [comment]
> make sure you don't have a gc-10 paired.

I don't understand.  What is a gc-10?  

I am seeing this issue as well.

**Comment by liversedge** [comment]
it is when we receive speed/cadence from the kickr AND a speed/cadence sensor.
