### ISSUE TITLE
No activities in critical power solver

### ISSUE THREAD

**Issue by bluesquall** [GoldenCheetah/GoldenCheetah#2310]
Perhaps I'm missing something simple here, but I can't seem to get any activities to show up in the list on the bottom left when I try to use the CP and W' solver. I've tried searching and filtering, and also dragging the workout over from the list on the left side of the main window in the Activities tab.

It may not be relevant, but all of my workouts in GC are on a turbo trainer at home, because I've been recovering from an injury and not riding outside.

**Comment by liversedge** [comment]
Please use the forums for help questions.
Only rides with exhaustion points are used by the solver.
