### ISSUE TITLE
Allow resistance control for Ant+ FE C trainers

### ISSUE THREAD

**Issue by TiBall** [GoldenCheetah/GoldenCheetah#2312]
- Manual resistance control (percentage) using e.g. up/down button, slider.. 

- Control resistance based on the power target of a loaded workout

**Comment by Joern-R** [comment]
* Manual adjustment is possbile in 3.5 (DEV Versions are already available.
* ERG Mode sets resistance relative to the CP/FTP registered in the file.

Done
