### ISSUE TITLE
Developer Guide

### ISSUE THREAD

**Issue by juansta** [GoldenCheetah/GoldenCheetah#2313]
I'm unable to see the developer guide hosted on http://www.goldencheetah.org. I hit an Error 404 each time.

This broken link is provided in the Wiki pages. Im not able to actually find any developers guide to actually carry out the update.

[Golden Cheetah Website - Developer's Guide](http://www.goldencheetah.org/developers-guide.html)

**Comment by liversedge** [comment]
you are following a stale link from a google search. it doesn't exist anymore.

**Comment by juansta** [comment]
No, Im following a link from the wiki.

https://github.com/GoldenCheetah/GoldenCheetah/wiki/Developers-guide

**Comment by liversedge** [comment]
ah, sorry, have removed it there.

we need to write a better guide as the old one was too generic and not related to the GC codebase and so out of date it wasn't useful.

**Comment by juansta** [comment]
OK, fair enough...

duplicate of #2302
