### ISSUE TITLE
No TSS for run with power data

### ISSUE THREAD

**Issue by Hezelnutt** [GoldenCheetah/GoldenCheetah#2314]
I have a Stryd powermeter for running and thus powerdata for my runs. I have also added critical power / FTP in my athlete profile for both cycling and running.

However, I get TSS values for cycling but not for running (this remains 0). I am using version 3.4 which should have better run power support. 

Is this function not yet available or might there be something wrong with my data?

**Comment by liversedge** [comment]
TSS is a metric that only applies to cycling.
