### ISSUE TITLE
GTK port?

### ISSUE THREAD

**Issue by aleprovencio** [GoldenCheetah/GoldenCheetah#2315]
Hello guys, are there any plans to port this beautiful app to GTK so the users of this toolkit are not forced to install QT dependencies?

**Comment by liversedge** [comment]
no, because GTK is not cross platform.

**Comment by aleprovencio** [comment]
@liversedge thanks for answering, I might be missing something but why do you say it's not cross platform? i.e. https://www.gtk.org/screenshots/

**Comment by aleprovencio** [comment]
@liversedge, can you please clarify this ?

**Comment by liversedge** [comment]
Its not going to happen, there is absolutely no reason to do this.
Why do you think we would !?

**Comment by aleprovencio** [comment]
I don't use other QT apps on my PC so it was kind of a selfish request.  Anyways, Golden-Cheetah is very good reason to install some QT dependencies and a software I'm very thankful for its existance. However, I got confused about your comment on GTK not being cross-platform.
