### ISSUE TITLE
Application Crash When Deleting Train Device

### ISSUE THREAD

**Issue by darrencope** [GoldenCheetah/GoldenCheetah#2317]
If there's only one device present in the Train View List of devices, deleting the device will cause GC to crash. This happens repeatedly using GC 3.4.

**Comment by Joern-R** [comment]
I just tested it (Windows - most recent code) - delete all my devices, created a new one and deleted this one again. No problems.

We are planning a Dev. Release soon. Can you please check again when this release is available.

Thanks.

**Comment by Joern-R** [comment]
@darrencope - any update on this with the latest DEV release - 1710 ?

**Comment by Joern-R** [comment]
Closed for now, since it can't be reproduced in the latest builds. If the problem occurs again, please re-open. Cheers. Joern
