### ISSUE TITLE
Prevent Computer From Going to Sleep While In Train Mode

### ISSUE THREAD

**Issue by darrencope** [GoldenCheetah/GoldenCheetah#2324]
I have my laptop set to turn off the screen and go to sleep after a set time, as I suspect a lot of people do. I noticed while using train mode for the first time in a while that it went to sleep, thinking the computer was inactive. It would be nice if GC could tell the system to stay awake and on until the activity is ended. 

I don't know technically how this would work, but seems like a lot of apps are able to do this (think fullscreen videos, etc.). I recognize that it may be a pain since different OSes likely behave differently.

**Comment by liversedge** [comment]
what os are you on?

**Comment by darrencope** [comment]
Sorry; I intended to mention that, but forgot. Windows 10.

**Comment by Joern-R** [comment]
I found an QT based example how to do this under Windows:

https://github.com/jepoirrier/forbidSleepingMode by using the

SetThreadExecutionState function as described below:
https://msdn.microsoft.com/en-us/library/aa373208(VS.85).aspx

There is nothing Qt native on this as it is very OS specific. I actually do not feel comforable enough in the RealTime code to easily do this. But maybe someone else picks it up.
