### ISSUE TITLE
Cannot read FIT file with third parties data

### ISSUE THREAD

**Issue by pavlinux** [GoldenCheetah/GoldenCheetah#2327]
Cannot read FIT file with third parties data. for ex. **My Training impact (TRIPM)** Connect IQ app, **Xert** apps,... 

https://apps.garmin.com/ru-RU/apps/880ffc12-e0ef-46d1-b8de-c5defa646f33

**Comment by liversedge** [comment]
Please provide an example file - our FIT parser in 3.4 can read all developer fields.

**Comment by pavlinux** [comment]
http://i89.fastpic.ru/big/2017/0224/97/41300a00442d1976e9efe1f146b9c297.png
https://ufile.io/dac70

**Comment by pavlinux** [comment]
$ fitdump.pl 2017-02-23-19-32-39.fit
....
Local message type: 14 (message number: 206)
  xxx3 (3-64-STRING): "**Trimp**"
  xxx8 (8-16-STRING, INVALID): ""
  xxx13 (13-1-UINT16, INVALID): 65535
  xxx14 (14-1-UINT16): 20
  xxx0 (0-1-UINT8): 0
  xxx1 (1-1-UINT8): 0
  xxx2 (2-1-UINT8): 136
  xxx6 (6-1-UINT8, INVALID): 255
  xxx7 (7-1-SINT8, INVALID): 127
  xxx15 (15-1-UINT8, INVALID): 255
...

**Comment by grauser** [comment]
As Mark said GC can read fit 2.0 since version 3.4 and I tested today with the TRIMP IQ field with no issue.
