### ISSUE TITLE
BikeScore value designated for Runs with estimated run power

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#2329]
Hi,

There seems to be a filter bug for the BikeScore metric. There is a value given to BikeScore for running activities based on running power. I guess BikeScore should be for bike activities only. I noticed this when playing around with the running power estimation tool. 

I have a chart displaying GOVSS, SwimScore and BikeScore trends. In this case there both GOVSS and BikeScore are tracked for a single activity, skewing the long term trends. 

The TriScore value seems unaffected, as it keeps the GOVSS value and doesn't seem to add the updated BikeScore value on top of that.

Kind regards,

Nigel

**Comment by amtriathlon** [comment]
You can add a filter to the BikeScore curve to avoid this problem
