### ISSUE TITLE
Tcx data errors exporting to garmin connect

### ISSUE THREAD

**Issue by nefren** [GoldenCheetah/GoldenCheetah#2331]
I use a Bkool Classic trainer with GC. When I export an activity to Tcx file from GC to upload to Garmin Connect, only appears power data from bkool. Time and distance data do not apear. In time data fields total time is 0:00 but elapsed time is correct!
Cadence and heart rate sensors data are correct.

![captura de pantalla 2017-02-07 a las 10 28 26](https://cloud.githubusercontent.com/assets/25540049/22685406/7d5d74d8-ed20-11e6-9fe8-46b77d511e67.png)
![captura de pantalla 2017-02-07 a las 10 29 02](https://cloud.githubusercontent.com/assets/25540049/22685407/7d6338a0-ed20-11e6-810e-5a3647417e11.png)

**Comment by Joern-R** [comment]
Sorry - this was a bug in 3.4 which has been fixed for the next release

Fixed by: https://github.com/GoldenCheetah/GoldenCheetah/commit/a3ec10a298977e5d3fee87706a76e28ef3bcb390
