### ISSUE TITLE
Longitude and Latitude values are broken when data is exported to CSV file

### ISSUE THREAD

**Issue by krzysiek-b** [GoldenCheetah/GoldenCheetah#2337]
What I have in GPX file is "51.931958754" when it's exported to CSV file the value becomes "51.9319". Ths same for all lon and lat values.

**Comment by krzysiek-b** [comment]
I see the issue probably exists in CsvFileReader::writeRideFile method. Maybe it can be fixed by adding qSetRealNumberPrecision?

**Comment by krzysiek-b** [comment]
I would like to help you with this issue by providing a pull request but seems that INSTALL-WIN32 steps are out of sync with the configuration files from master. Also I cannot compile the source code. I'm trying to solve this but if you could give me a hint I could provide the pull request faster :)

`In file included from Train\/RemoteControl.h:23,
                 from Train\/TrainSidebar.h:32,
                 from Train\/VideoWindow.h:130,
                 from Train\VideoWindow.cpp:21:
ANT/ANT.h:41:25: error: QElapsedTimer: No such file or directory
In file included from Train\/RemoteControl.h:23,
                 from Train\/TrainSidebar.h:32,
                 from Train\/VideoWindow.h:130,
                 from Train\VideoWindow.cpp:21:
ANT/ANT.h:711: error: 'QElapsedTimer' does not name a type
mingw32-make[2]: *** [release/VideoWindow.o] Error 1
mingw32-make[2]: Leaving directory d:/coding/GoldenCheetah/src
mingw32-make[1]: *** [release] Error 2
mingw32-make[1]: Leaving directory d:/coding/GoldenCheetah/src
mingw32-make: *** [sub-src-sub_Release_ordered] Error 2`

**Comment by stschake** [comment]
The easiest way to setup the build on Windows is to copy what the automatic build / continuous integration does:

https://github.com/GoldenCheetah/GoldenCheetah/blob/master/appveyor.yml

**Comment by Joern-R** [comment]
We have now an kind of "SDK" as well as an upddated win32-install guide:

https://groups.google.com/d/msg/golden-cheetah-developers/gGlHxKH1BNw/l2uDKw6_AAAJ

Hope that helps - contribution to GoldenCheetah welcome.

**Comment by mtbkeith** [comment]
This issue is resolved per 2428
