### ISSUE TITLE
Train mode - better handling for USB device access

### ISSUE THREAD

**Issue by dresco** [GoldenCheetah/GoldenCheetah#2339]
The USB ANT+ device being present but inaccessible (for example - in use by Garmin ANT Agent) seems to be a common issue for new users, and should be caught by the error handling.

Review & update the the device opening code to return an error more consistently. This may also help with adding support for multiple ANT+ USB sticks.

Feel free to assign to me, thanks!

**Comment by dresco** [comment]
Have picked off a few issues.

Firstly, if we got no response to the initial ANT+ reset messages, we were carrying on regardless and would then end up in a state where we're not receiving any data. (I only see this when the previous training session has been closed unexpectedly - i.e. Ctrl-C).

Secondly, the LibUSB code to open and configure the port was not treating it as an error if either usb_set_configuration() or usb_claim_interface() failed. This was masking failures due to the device already being in use (by Garmin ANT Agent etc).

Note that Linux support is complicated by the fact that we have to forcibly disconnect the usb serial driver during connection. Because of this, we attempt to grab the first enumerated device regardless of whether it is already in use. However, for other OS, we can now correctly iterate over multiple ANT sticks (for instance one for Zwift and one for GC) to find an unused one.

Finally, we weren't reacting to the USB device being removed. 

All these cases are now treated as an error, closing the ANT thread. This results in the "Cannot open ANT+ device" message to the user who can then try again..

Have pushed these fixes to a USB branch in my repo, will test them for a week or so on Linux & Windows before submitting a pull request. (Mainly want to verify that the device removal check isn't triggered by any transient USB issues).

**Comment by liversedge** [comment]
How is this? Should I move to the v4.0 queue ?

Cheers
Mark

**Comment by dresco** [comment]
Sorry, I forgot to reference the issue in the pull request. Good news is it's all done and merged under #2423

**Comment by liversedge** [comment]
cool!
