### ISSUE TITLE
Support for Polar H6 realtime monitor setup

### ISSUE THREAD

**Issue by valandil** [GoldenCheetah/GoldenCheetah#2343]
The [wiki](https://github.com/GoldenCheetah/GoldenCheetah/wiki/Realtime-set-up) describes a realtime setup for ANT+ devices, but I think is associated with an older version of GoldenCheetah. 

Should it be possible to pair a Polar H6 heart rate monitor, i.e. a Bluetooth LE HR monitor to GoldenCheetah? 

My attempts so far have failed. The Add a device wizard will not detect the belt, regardless of whether it is paired to my computer or not.

**Comment by Joern-R** [comment]
BT/BTLE is not (yet) supported on Windows (in case you are using Windows, please close the issue).
In the next release BT will not be visible any more in the Device Wizard on Windows.

**Comment by valandil** [comment]
I am indeed using Windows. Is there a timeline for support of that feature?

**Comment by Joern-R** [comment]
No - since the QT Framework we are using for all platforms is not supporting BT on Windows yet.

**Comment by valandil** [comment]
Ah, I see. I'll follow the development of Qt then :)
