### ISSUE TITLE
TrainingPeak Synchronization Not Working

### ISSUE THREAD

**Issue by OregonRain** [GoldenCheetah/GoldenCheetah#2344]
Hello, I Keep getting an error telling me the TP server is had an internal error.  It does not seem to be a TP server issue since it happens all of the time and I don't see anyone else complaining about it.  It used to work just fine for me.  However, the last successful synch was on 4 June 2016.  Prior to that, I never had a problem synchronizing. 

![screen shot 2017-02-12 at 8 24 09 pm](https://cloud.githubusercontent.com/assets/25811449/23008706/4ae88e14-f3c6-11e6-9c33-a29165066b86.png)

**Comment by OregonRain** [comment]
I have submitted a ticket with TrainingPeaks asking if there is a server error.

**Comment by liversedge** [comment]
https://groups.google.com/d/msg/golden-cheetah-users/g3_bsD-U9Zo/yFlRd5ZLCwAJ

**Comment by OregonRain** [comment]
Thank you for answering my question.  I appreciate your support.
