### ISSUE TITLE
Timezone Issues with Cloud Synchronisation (Dropbox)

### ISSUE THREAD

**Issue by arunh** [GoldenCheetah/GoldenCheetah#2350]
I have come across a problem where files created in different timezones will never synchronise with DropBox - they will upload, but that will always appear in the sync list. It appears to be related to timezones.

Unfortunately I don't know for sure the date/time on my Garmin Edge, but of the devices involved this is the most likely to have still been on UK time whilst my laptop would have updated automatically from the NTP server to French time. However, as the Edge connects to my phone via Bluetooth it is possible that it also had the correct French time from that source.

Here is an example of a file that was recorded on a Garmin Edge 520 in France (UTC+1). Note the difference between the filename (UTC+1) and the actual ride start time (UTC).

File name:
```
    2017_02_08_09_49_45.json
````

Header lines:
```{
  "RIDE":{
    "STARTTIME":"2017\/02\/08 08:49:45 UTC ",
```
		
I tried closing GC and ammending the STARTTIME in the file, but this had no effect. As such I edited cache/rideDB.json entry (again with GC closed)...

From this:
```{
  "filename":"2017_02_08_09_49_45.json",
  "date":"2017/02/08 08:49:45 UTC",
```
      
To this:
```{
  "filename":"2017_02_08_09_49_45.json",
  "date":"2017/02/08 09:49:45 UTC",
```
      
This appears to have cured the issue. Is there some way already to force refresh the rideDB to remove all the files affected by this problem as a workaround or is manual editing the only way?

I guess there is some "bug" here around detection of time zones across devices but not really sure how to take forward.

**Comment by arunh** [comment]
I tried deleting the "rideDB.json" file in cache completely. It was re-created and the issue appears cured... probably a sufficient workaround :)

**Comment by liversedge** [comment]
I haven't been able to recreate so closing. If we can find a way to recreate will reopen.

Thanks

Mark
