### ISSUE TITLE
Box synchornisation

### ISSUE THREAD

**Issue by freekode** [GoldenCheetah/GoldenCheetah#2356]
Make the same sync as with Google Drive/Dropbox

[Documentation](https://docs.box.com/docs)

**Comment by liversedge** [comment]
Shuffling to 3.6

**Comment by amtriathlon** [comment]
I am closing this since nobody seems interested in their implementation, and It looks like Box is more directed to enterprises than individuals, not a good match for GoldenCheetah anyway.
