### ISSUE TITLE
Please add SmO2 to Workout Editor

### ISSUE THREAD

**Issue by climbingtrainer** [GoldenCheetah/GoldenCheetah#2365]
Is it possible to add SmO2 vs Duration to be plotted in Workout Editor or instead make Charts/Telemetry editable so we can plot versus Time/Duration?  I am doing HIIT resistance training (with weights) and not using a Power meter so without a display of SmO2 versus time I cannot visualize the intensity of my intervals and the rate of recovery in between intervals, until the Training session has been completed and I analyze the data under Activities.

By being able to see SmO2 vs Duration in Workout mode it would be possible to maximize the benefits of any interval training not only for resistance training, but also for Cycling, Rowing, etc. (when combined with Power, etc.) as opposed to monitoring Power alone.

Ideally, the Workout editor should allow for the addition of continuous display of Power, Heart Rate,  SmO2 & (other?) versus time.  In case it can not be added to Workout Editor then upgrading the Chart editing features (in Train view) to plot versus time and change the Scale of the Y-axis would allow for an improved training session.

Cheers,

**Comment by liversedge** [comment]
Sm02 are already available in the editor.
