### ISSUE TITLE
isRun==1 despite manually changing activity type to "Bike"

### ISSUE THREAD

**Issue by thigger** [GoldenCheetah/GoldenCheetah#2367]
Golden Cheetah v3.4 (build 3950)
Originally multisport files imported from Garmin 920XT watch
Cadence is recorded as "run cadence" throughout. This means that when the activity is manually split, GoldenCheetah ignores the fact that "Sport" has been set to bike on one of the new activities and continues to treat it as a run. Bike power data ends up polluting the run CP curve, and filtering activities by "isRun=1" shows the bike activity amongst the run activities.

Expected behaviour
GC should honour the manual setting of sport type

Workaround
Delete the "run cadence" column and associated data; GC starts to listen to the manual setting.

**Comment by thigger** [comment]
I've not played with the GC source, but on a quick look it appears that it's here - 

src/FileIO/RideFile.cpp:207

```
RideFile::isRun() const
{
    // for now we just look at Sport and if there are any
    // running specific data series in the data
    return (getTag("Sport", "") == "Run" || getTag("Sport", "") == tr("Run")) ||
           (areDataPresent()->rvert || areDataPresent()->rcad || areDataPresent()->rcontact);
}
```
The presence of any running data is allowed to override the "Sport" tag. 

Obviously the fact that the cadence data is considered as "running" data in a multisport file is another issue, but I'd imagine that would require a lot of work to allow GC to import multisport files properly,

**Comment by thigger** [comment]
```
return (getTag("Sport", "") == "Run" || getTag("Sport", "") == tr("Run")) ||
           (getTag("Sport","") == "" && (areDataPresent()->rvert || areDataPresent()->rcad || areDataPresent()->rcontact))
```

I don't know exactly how the sport tagging works but how about something like that so that the presence of run data only overrides the tag if it's not set?

**Comment by amtriathlon** [comment]
Thanks for your contribution!

**Comment by amtriathlon** [comment]
Fixed in https://github.com/GoldenCheetah/GoldenCheetah/commit/a5c3701f2d084ff51e55842f4ccc3786f87ad496
