### ISSUE TITLE
Data Fields -> Notes Keywords Could Support Multiple Fields

### ISSUE THREAD

**Issue by arunh** [GoldenCheetah/GoldenCheetah#2371]
I'm interested in changing the behaviour of the "Notes Keywords" functionality to allow each keyword to specify the field it scans against rather than have a single global field as we do today. The logic would continue from the top until a match is found as it does today.

In order to preserve existing user's highlighting, we would have to update all existing rules during migration to use the global data field the user specified. OR, we could leave the global data field in place and allow new rules to specify field.

Just looking for feedback at the moment but I'm happy to code this up if there are no objections since it is something I would like to use/already have a use-case for (I like all my activities with an estimated TSS to be light gray, but I also like to use colour to show if a ride was indoor or outdoor if there was a real TSS attached. At the moment I can't have both)

**Comment by liversedge** [comment]
Too complicated for general users. I get what you are trying to do, but frankly it will make the config unusable !

**Comment by arunh** [comment]
Yes, fair enough. What would be really cool would be a plugin framework so
one could extend things like this without impacting general users / keep
bespoke functionality separate from the main code.
