### ISSUE TITLE
Several problems with metric diagrams

### ISSUE THREAD

**Issue by greglemond** [GoldenCheetah/GoldenCheetah#2373]
Hi, I have a metric diagram which shows time in movement for five types of sport. However, four of them are displayed in the legend only (1st pic). Settings of metrics are obviously the same.

![1](https://cloud.githubusercontent.com/assets/26170553/23561809/20fd04d2-0040-11e7-9cf1-2105197ccc42.png)

Furthermore, if I have once touched this drop down (on top of 2nd pic) menu captions of bars disappear (3rd pic).

![2](https://cloud.githubusercontent.com/assets/26170553/23561983/e5dbcd74-0040-11e7-84c7-b0ad2298db00.png)

![3](https://cloud.githubusercontent.com/assets/26170553/23561991/eda33f9c-0040-11e7-90f5-2161bf3ebdac.png)

Another thing is that after editing the diagram some modification of the legend occurs (4th pic).

![4](https://cloud.githubusercontent.com/assets/26170553/23562048/1f1356ac-0041-11e7-9a23-205081b697da.png)

Do you have any ideas how to fix these problems? Thank you. :)

**Comment by greglemond** [comment]
Should I desicribe the issues more precisely or in other words? Is something unclear? Thank you in advance.

**Comment by amtriathlon** [comment]
This is another case of https://github.com/GoldenCheetah/GoldenCheetah/issues/2185, to chart the same metric more than one time the workaround is to use formulas.
