### ISSUE TITLE
Workout Editor Quickcode Recognizing "LAP"

### ISSUE THREAD

**Issue by GCuser99** [GoldenCheetah/GoldenCheetah#2385]
I noticed that when editing a workout using the Workout Editor, and then save, the laps are removed from the workout. A solution would be for the quickcode to read and recognize the keyword "LAP" in the code sequence, like:

2m@190
20m@175
LAP
2m@190
20m@175
LAP
..
..
..

Thanks!

**Comment by erikboto** [comment]
You can add a "L" to the end of the lines you want to generate laps.

**Comment by GCuser99** [comment]
Ok. Any reason why "L" should have to be at the end of a line? Couldn't it be on a line by itself, or at the beginning of a line? Maybe that restriction is why there seems to be a problem... If I use the old "create a new workout" under tools, or make a workout manually with a text editor, and include laps, and then try to edit in the workout editor, the lap designations don't always show up in the Quick Code panel. And user gets really confused! Maybe I'll submit another bug report with snapshots of what I am talking about.

Thanks!

**Comment by erikboto** [comment]
The rationale for having it at end of the qwkcode lines is that it can apply to each interval of lines that are repeated, e.g. 2x20m@300r5m@100L. I guess it doesn't have to be the only way, but keeping the syntax as easy as possible is always good. If you can provide an example maybe we can leave the bug open and I'll try to get the time to have a look at it.

**Comment by GCuser99** [comment]
I understand the rationale. I did provide an example of when it is going wrong in a separate bug report. See #2390 LAP designations lost after editing in Workout Editor .
thanks! 

    On Tuesday, March 14, 2017 12:18 AM, Erik Botö <notifications@github.com> wrote:
 

 The rationale for having it at end of the qwkcode lines is that it can apply to each interval of lines that are repeated, e.g. 2x20m@300r5m@100L. I guess it doesn't have to be the only way, but keeping the syntax as easy as possible is always good. If you can provide an example maybe we can leave the bug open and I'll try to get the time to have a look at it.—

**Comment by GCuser99** [comment]
One last comment on this... As I was riding outside today on basically a multi-lap ride, I realized that I hit the lap button to bookmark both the beginning and end of a lap for stats purposes. There is a warmup segment before I arrive at the beginning of the first lap. I hit the lap button at the start of that first lap, and then for every time I cross that lap start. If I do N laps, that results in N+1 lap designations. So if I were to try to recreate the same on my trainer, with a warmup segment, only being able to do something like 3x5m@175r3m@120L would not bracket the first lap with a lap designation at the start and end of the lap. Do you see what I am getting at? The lap designation is not just a counter for me - its a way to bracket equal segments of the ride for statistics.

Thanks for your consideration...
