### ISSUE TITLE
Activity, Import from file, Polar *.hrm - Fail in unit

### ISSUE THREAD

**Issue by BWonder** [GoldenCheetah/GoldenCheetah#2387]
Updated from GC3.3 to GC3.5 dev 1703.
Everything worked on GC3.3 (haven't tested GC3.4)
1)
Reading data  from a Polar HRM file (RS800SD) ignores? the km/mile bit. (in the file) and assumes miles.
Results are workouts that are 1.6X larger when in metric.
(reproducible 3 of 3 GC installs)
2)
Reading data  from a Polar HRM file (15010401.hrm)  results in: 
Error - Could not find in pdd file: "D:/Data/xxxxxxxxxxxx/2015/20150104.pdd"
Both files exits, however don't know why the 2nd (*.pdd) file gives an error while present.
(reproducible on 1 GC install and discovered by trying to combine activities)

As said both errors where not in GC3.3 and examples are imported successfully with that version.

**Comment by liversedge** [comment]
Thanks for the feedback -- Leif added support for HRV data and has possible broken support.
Will look at it.

Any chance you can send me the hrm and pdd files to test with?

liversedge @ gmail.com ...

**Comment by BWonder** [comment]
Mailed 2 of the hrm/pdd files tot test with (much more available if needed).
Will test the 2nd error on a 2nd install tomorrow.

**Comment by leifwar** [comment]
Check if 8a80b3ea fixed the second issue.

**Comment by BWonder** [comment]
@leifwar i quess checking could only be done by installing the complete development environment? Planned in doing that but doesn't look as a very easy process.

Update 2nd error: It looked like this error didn't happen on my work PC, however after testing with the files uploaded to liversedge the errors where the same.
I took a look at the *.hrm and they where exact the same.
The *.pdd where different, in the (newer) pdd there was one extra line with "0 0 0 0 0". 
according to the Polar PDD file format after a [ExerciseInfo1] there should follow 25 lines.
My file had 26 lines, i looks like an update last year in "Polar Protrainer 5" may cause this. (will check tonight)
After manual removing the extra line in the pdd file, importing the hrm no longer generates a pdd error.

1st "bug" still remains
First lines from my hrm file:
[Params]
Version=106
Monitor=37
SMode=110000100
First thing i did notice: according to the Polar HRM2 file format Version=106 has 8 bits (a..h) and versions 1.07 9 bits (a..i). My file has 9 bits however is labeled 106 (Polar Protrainer did this since the beginning in 2006).
SMode bit "h" indicates US / Euro unit (0 = Euro (km, km/h, m, °C),  1 = US (miles, mph, ft, °F))
In my files this is indeed "0" which should be km/h.
(This part was right in GC3.3)

**Comment by liversedge** [comment]
Lets wait and test with the next development build in April.

**Comment by leifwar** [comment]
I had similar problems importing data from different versions of Polar Protrainer 5, thus I changed the code to read the provided value indicating number of lines in "[ExcerciseInfo1]" (third column in the first row after [ExcerciseInfo.]). Check if this number differ in the two files.

**Comment by leifwar** [comment]
Found the error for the 1st bug (my fault). Will fix it

**Comment by BWonder** [comment]
Indeed, in the changed PDD this number (Nbr Of Num Rows) is increased by one. 
So this number and the actual number of rows match (counting starts at 0).
2nd issue looks solved as i see the changes in the code

1st issue, when i manual change bit "h" to 1 it reads km/h as km/h. 
SMode=110000100 (km exercise read as miles and converted to km -> distance/speed 1.6x to high)
SMode=110000110 (km excersie read as km and no conversion -> distance/speed ok (as GC3.3)

As liversedge wrote i will wait and test with the April development build.

**Comment by liversedge** [comment]
Hi Leif,

Is this bug fixed -- was there a PR to fix it ?

Mark

**Comment by leifwar** [comment]
Commit 8c3a69d5 should handle the first, while 8a80b3e and 96a43a6 should fix the second issue.

**Comment by BWonder** [comment]
Bugs Fixed!
Tested with Version 3.5 Development Build 1705 (skipped testing with 1704 because crashed in train)
Metrics and Importing now works again.
Thanks
