### ISSUE TITLE
Move backup directory path from profile configuration

### ISSUE THREAD

**Issue by freekode** [GoldenCheetah/GoldenCheetah#2388]
Is it possible to move path for backup directory, from profile specific configuration to application config?
Why I need that? I am syncing config folder (from profile directory) on several computers, and on each computer I have different backup destination.
I understand that backup works only for profile, not for application. But probably is there some solution in that situation?

**Comment by amtriathlon** [comment]
You could use a symbolic link in each computer with the same name but pointing to their corresponding backup destination.
