### ISSUE TITLE
LAP designations lost after editing in Workout Editor

### ISSUE THREAD

**Issue by GCuser99** [GoldenCheetah/GoldenCheetah#2390]
Using 3.5-DEV 1703.  Here is the sequence:

1) I created a workout using the "Create new workout" under tools, designating 3 laps. See attached file "x_lap_test_1.erg"
2) I then opened in the workout editor - laps lines show up in display window fine, but LAP designations do not show up in quick code window (see lap_test_1.jpg)
3) I then add one quick code line at the end of the sequence - lap lines disappear in the display window (see lap_test_1_after_adding_line.jpg
4) I save as x_lap_test_2.erg - all laps are removed from file - see x_lap_test_2.erg

It is my understanding that I can explicitly add a lap in the workout editor by adding an "L" at the end of a quick code line. Can it only be placed at the end of a line? Why not at the beginning, or on a line by itself? Seems like it shouldn't matter. Anyway, for some reason laps generated manually or using the old workout creation tool are getting lost in the new workout editor. I suspect that it has something to do with the requirement that "L" can only be added to the end of a quick code line.

I think all of the following should be allowed in quick code:
2m@190L
L10m@100
L
3xL2m@70r5m@190
3x2m@70Lr5m@190

Thanks!

[workouts.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/839142/workouts.zip)
![lap_test_1](https://cloud.githubusercontent.com/assets/26237126/23867536/d26d5994-07e1-11e7-9307-193ccf3855ed.JPG)
![lap_test_1_after_adding_line](https://cloud.githubusercontent.com/assets/26237126/23867646/356ec1f4-07e2-11e7-982f-8cac079c98cf.JPG)

**Comment by amtriathlon** [comment]
Closing as this was discussed and clarified in #2385
