### ISSUE TITLE
Exhaustion points set on rides, but nothing in solver or To_Exhaustion

### ISSUE THREAD

**Issue by ocharles** [GoldenCheetah/GoldenCheetah#2393]
I've never been able to get the solver to actually work. I tried again today, and have a ride with some exhaustion points:

![2017-03-17-185819_1404x1118_scrot](https://cloud.githubusercontent.com/assets/20878/24058630/b59cc74a-0b43-11e7-82a9-7abbd8c04827.png)

Yet if I search for `To_Exhaustion` no activities match, and if I open the W' Solver, no activities are available.

**Comment by liversedge** [comment]
Please use the forums for help, this is a bug logging system.
See: https://groups.google.com/forum/#!forum/golden-cheetah-users

**Comment by ocharles** [comment]
How is this not a bug report?

**Comment by liversedge** [comment]
Save.

**Comment by ocharles** [comment]
I had saved (and also restarted Golden Cheetah) but neither helped. However, it does seem to work in the latest development build.

**Comment by liversedge** [comment]
Thanks for the update.
