### ISSUE TITLE
[3.5 / Build 1703] Regression - New Ride Upload & Detail Editing Not Updating UI

### ISSUE THREAD

**Issue by arunh** [GoldenCheetah/GoldenCheetah#2394]
In 3.4 when a new ride is uploaded and the details edited, e.g. workout title, these changes are immediately reflected in the column view on the left as soon as focus leaves the detail editor. In 3.5/1703 when the details are changed, they are not reflected in in the left hand activity list even after manually saving. Restarting GC sees the details correctly reflected.

The attached screenshots probably help to highlight issue.

After details updated, and clicked out of detail editor. Note how the ride on 17 Mar looks compared to those below. This is after a manual save.

![before](https://cloud.githubusercontent.com/assets/804578/24060993/95957866-0b4d-11e7-9933-b51fadd52290.png)

After restart, ride now rendered correctly:

![after](https://cloud.githubusercontent.com/assets/804578/24061025/aae55d76-0b4d-11e7-89ab-ecd6530b1f4d.png)

I'd be happy to take a look at trying to fix this, but don't really know where to start in the code base. If someone could give me a pointer I can put together a fix.

**Comment by liversedge** [comment]
This: 8b01c448a4046fbe700ed92df9076c8f0d1ad166

We need a better way to update the ridelist than a full model reset...

**Comment by liversedge** [comment]
Do make sure you test with qt 5.8.

**Comment by arunh** [comment]
Thanks Mark, I'll try and take a look at this as time allows.

**Comment by arunh** [comment]
Mark, how do you feel about adding a "Refresh" option to the Activities
hamburger menu that would call modelReset()? It's not a long term fix, that
is obviously doing a more selective model refresh, but it would make the
current build have a good workaround for having this functionality
currently disabled.

**Comment by liversedge** [comment]
YUCK!

The model update needs to be handled correctly in the AbstractProxy. Its a thorny issue since we have 2 proxies one for filtering and one for grouping. I can take a look at it sometime in the next couple of weeks. 

The old loss of selection was even worse IMHO, so won't revert that.

**Comment by arunh** [comment]
That's clear then :)

**Comment by liversedge** [comment]
I've fixed the refresh when data changes with this commit: 4cb9715567687ecd5e2f57961ac6ebce1e61e8d9

**Comment by arunh** [comment]
Thanks Mark

**Comment by liversedge** [comment]
I think this can be closed? The 'new file upload' aspect is a bit of a red-herring?
This is just about the sidebar not updating when you change metadata, right?

**Comment by arunh** [comment]
Yes, I'd say so... the bug was just the steps I observed before you
explained issue.

**Comment by liversedge** [comment]
Cool, thanks. Closing.
