### ISSUE TITLE
CP used instead of FTP in workout creator and train view

### ISSUE THREAD

**Issue by fabrylama** [GoldenCheetah/GoldenCheetah#2397]
In the athlete settings I have selected "use FTP for coggan", but in the "create new workout" tool if I create a lap at 100% FTP, the result is a lap at 100% CP
In the train view CP is used instead of FTP to calculate TSS and IF.

For the workout creator I would like the option to decide whether to use %CP or %FTP. 

version 3.5 dev

**Comment by GCuser99** [comment]
I agree and think that there should be a "Scale workout power by..." option with choices %FTP/%CP in the Power Metrics section.

**Comment by liversedge** [comment]
Its only used for calulating metrics at present. We could look to adjust. Have added to the v4 queue.

**Comment by fabrylama** [comment]
Well, it's not only used to calculate metrics. It's also used to create workouts in the "create new workout" tool, the old one, not the new one in the train view.

If I create a workout as %FTP, I expect it to be at 100%FTP and not at CP.
For me it's not a problem, since I have only a few watts of difference, but the user (in an italian roadbike forum) who reported to me the issue has to train using a different athlete with a fake CP=FTP profile.

**Comment by liversedge** [comment]
FTP was introduced to support the metrics that are based off it (IF, NP, TSS et al).

I guess we could use it instead of CP when creating workouts .. not sure its really that crucial tho. I've left the request open so it could be addressed if enough users think it is important.
