### ISSUE TITLE
[GC 3.5 - Build 1703] [Linux Mint 18.1] Crash when selecting a chart in the sidebar on Trends view

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#2400]
I often get a crash when selecting a previously created chart in the sidebar. It doesn't seem to matter if the charts contain regular metrics or custom user metrics. When the charts are placed in the top bar, crashes don't occur (or far less frequently). Below you can see the backtrace using gdb.

>  Thread 1 "GoldenCheetah" received signal SIGSEGV, Segmentation fault.
0x0000000000628726 in LTMPlot::createMetricData(Context*, LTMSettings*, MetricDetail, QVector<double>&, QVector<double>&, int&, bool) ()
(gdb) bt
#0  0x0000000000628726 in LTMPlot::createMetricData(Context*, LTMSettings*, MetricDetail, QVector<double>&, QVector<double>&, int&, bool) ()
#1  0x000000000062f306 in LTMPlot::createCurveData(Context*, LTMSettings*, MetricDetail, QVector<double>&, QVector<double>&, int&, bool) ()
#2  0x0000000000630e61 in LTMPlot::setData(LTMSettings*) ()
#3  0x0000000000663dd8 in LTMWindow::refreshStackPlots() ()
#4  0x00000000006674e8 in LTMWindow::refreshPlot() ()
#5  0x0000000000667aa0 in LTMWindow::refresh() ()
#6  0x0000000000ac67ad in LTMWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#7  0x00007fffed83b3e1 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /opt/GoldenCheetah/lib/libQt5Core.so.5
#8  0x00000000006564ad in LTMTool::applySettings() ()
#9  0x0000000000667e9c in LTMWindow::presetSelected(int) ()
#10 0x0000000000ac6753 in LTMWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#11 0x00007fffed83b3e1 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /opt/GoldenCheetah/lib/libQt5Core.so.5
#12 0x0000000000ad3ad1 in Context::presetSelected(int) ()
#13 0x00000000008b1a60 in LTMSidebar::presetSelectionChanged() ()
#14 0x0000000000ae55bd in LTMSidebar::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#15 0x00007fffed83b3e1 in QMetaObject::activate(QObject*, int, int, void**) ()

**Comment by liversedge** [comment]
I can't recreate this, but looking at the recent changes I think I can  see a fix in LTMPlot.
Its fixed via f346611390bcba8ee4e37a135aa24def4b10db90 I think.

Can you test and let me know if it still occurs?

**Comment by nigelvdv** [comment]
Is there a guide somewhere how to test this?

**Comment by liversedge** [comment]
Sorry I don't follow -- you reported the bug, are you still able to recreate after this commit?

Apols if I am being dumb.

**Comment by nigelvdv** [comment]
I guess I need to build a .deb package myself with this new code inserted, right?

If not, it still happens in my current version. 95% of the time I select a chart.

**Comment by nigelvdv** [comment]
I can't recreate this issue on another user. Strange thing is that this user has the same charts.xml file in its configuration. Could it be that this issue is related to the number of activities? My main user has almost 3000 activities, while the other one only has +/-100.

**Comment by liversedge** [comment]
AH! I was being dumb. I thought you were building from source !
I will close, since no matter how hard I try I cannot recreate.

The next dev build is in a couple of weeks, will be in that.

**Comment by nigelvdv** [comment]
Hi Mark,

I just wanted to let you know that I performed a fresh Linux Mint install and customized all GoldenCheetah parameters step by step until I bumped into the problems again:
1. Installed GC3.5: No crashes
2. Changed Athletes default folder to new empty dropbox folder: no crashes
3. Added all my .json activity files: no crashes
4. Added usermetrics.xml to the Athlete folder: no crashes
5. Replaced home-layout.xml, diary-layout.xml, analysis-layout.xml in the config folder: no crashes
6. Added all the pace and power zones to the config folder: no crashes
7. Replaced metadata.xml and namedsearches.xml in the config folder: no crashes

8. Replaced charts.xml in the config folder: lots of crashes when selecting or editing charts
9. Removed the charts.xml file: no crashes
10. Adding a chart to the sidebar with a custom user metric: crashes again
11. Adding a chart to the topbar with a custom user metric: no crashes so far

You can find my usermetrics.xml and charts.xml in following dropbox link. Maybe you will be able to recreate this behaviour.

[usermetrics.xml and charts.xml](https://www.dropbox.com/sh/kt8cr23j9e905fv/AABa8oUx0gnER3_7oJhoE2Dda?dl=0)

Kind regards,
Nigel

**Comment by liversedge** [comment]
Hi Nigel - this is with the 1703 Dev build not a build incorporating the fix ?

**Comment by nigelvdv** [comment]
Still the 1703 build, so possibly already fixed indeed. If I find the time, I'll try to create a.new build

**Comment by liversedge** [comment]
No its ok, we will do a build in the next 2 weeks or so. I think this is fixed, we will find out soon enough :)

**Comment by gcoco** [comment]
Hi. Try this build: https://github.com/gcoco/CI-for-GoldenCheetah/releases/download/Final/GoldenCheetah_3.5.0dev.20170320_WEBENGINE_amd64.deb

**Comment by nigelvdv** [comment]
Seems to work fine (so far) :clap:
