### ISSUE TITLE
[GC 3.5 - Build 1703] [Linux Mint 18.1] Representation error of data series in bar-style

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#2402]
There seems to be a representation problem in charts that contain stacked bars. See example below:

[Screenshot chart with bars](https://www.dropbox.com/s/301f94ay1m0xiy3/Chart%20-%20problem%20bars.png?dl=0)

On top you can see stacked bars representing Triscore for Run (red), Bike (green), Swim (blue). Being injured I didn't run between 19 February and 16 March. 
Still there are some red bars for run activities visible. The bottom three charts show the same activities in stick-style and not stacked. No unexpected run activities over there.
The short term stress curve for run activities is shown as well. Here the ghost activities are not showing either.

**Comment by liversedge** [comment]
can't open that image?

**Comment by nigelvdv** [comment]
Should work now

**Comment by amtriathlon** [comment]
I think this is another case of https://github.com/GoldenCheetah/GoldenCheetah/issues/2185, to chart the same metric more than one time you need to use formulas.
