### ISSUE TITLE
HRV with Version 3.5 Development Build 1703

### ISSUE THREAD

**Issue by Wox1** [GoldenCheetah/GoldenCheetah#2404]
Hello,

I have tested the new version for Version 3.5 Development Build 1703 for Win 64.
The Garmin Edge Fit File worked very well and the HRV is show in the workout!
But when i make a workout on my hometrainer (kettler) with GC under "training" the HRV don't creat?

Sincerely
Wox

**Comment by liversedge** [comment]
R-R is not captured in train view at present, there is some code in there but we should make it part of the captured data and csv file. have put into v4 queue.

**Comment by erikboto** [comment]
Also, when reading heart rate from the Kettler bike it's just heart rate. You will not be able to get HRV data from the Kettler bike.

**Comment by liversedge** [comment]
Will close. Thanks Erik.
