### ISSUE TITLE
XData is lost when splitting/merging activity

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#2406]
When splitting an activity only standard data remain. In my case the "Extra" tab and the "HRV" tab get dismissed.

Original fit-file was recorded with a Garmin 735.

**Comment by liversedge** [comment]
Yes this is a known ommission and should probably be resolved for 3.5.

**Comment by liversedge** [comment]
Merge has a similar shortcoming.
