### ISSUE TITLE
Segmentation fault (Debian 8.3 & libQtGui.so.4*)

### ISSUE THREAD

**Issue by pavlinux** [GoldenCheetah/GoldenCheetah#2407]
pavel@amd64:/usr/src/GoldenCheetah/src$ ./GoldenCheetah 
**Segmentation fault**
pavel@amd64:/usr/src/GoldenCheetah/src$ su
Password: 
root@amd64:/usr/src/GoldenCheetah/src# mv /usr/lib/x86_64-linux-gnu/libQtGui.so.4* /
root@amd64:/usr/src/GoldenCheetah/src# mv /usr/lib/x86_64-linux-gnu/libQtGui.so.4* /^C
root@amd64:/usr/src/GoldenCheetah/src# exit
pavel@amd64:/usr/src/GoldenCheetah/src$ ./GoldenCheetah 
**geom: QRect(0,0 2560x1024) no hidpi support available**
pavel@amd64:/usr/src/GoldenCheetah/src$

1. Dual monitor combined in single via Nvidia TwinView: 1280x1024 + 1280x1024 = 2560x1024 
2. Xfce4

**Comment by liversedge** [comment]
Hi,

You need to build with Qt5 if you want hidpi.
We don't formally support building with QT4 any more.
The issues you describe are related to your toolchain and LD_LIBRARY_PATH I suspect.

I'm closing this as its not present in the .deb we release (to my knowledge anyway).

THANKS,
Mark

PS: Will re-open if there is a genuine error we need to address in the code !

**Comment by pavlinux** [comment]
QT5 dload() - /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk2.so
libqgtk2.so linked with libQtGui.so.4

**Comment by liversedge** [comment]
Not sure how I can fix that :)

Or is this a general issue related to running Qt4 on Debian 8?

**Comment by pavlinux** [comment]
#  mv  /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk2.so /
 ./GoldenCheetah 
geom: QRect(0,0 2560x1024) no hidpi support available
....
Warning, but run :)

**Comment by pavlinux** [comment]
$ export QT_DEBUG_PLUGINS=1
$ ./GoldenCheetah

....
Got keys from plugin meta data ("gtk2")
QFactoryLoader::QFactoryLoader() checking directory path "/media/disk/src/GoldenCheetah/src/platformthemes" ...
Segmentation fault

**Comment by pavlinux** [comment]
$ make 
Core/main.cpp: In function 'int main(int, char**)':
Core/main.cpp:321:11: warning: variable 'screenSize' set but not used [-Wunused-but-set-variable]
     QRect screenSize = desktop->availableGeometry();
           ^

**Comment by pavlinux** [comment]
diff --git a/src/Core/main.cpp b/src/Core/main.cpp
index 0659b86..322d6b2 100644
--- a/src/Core/main.cpp
+++ b/src/Core/main.cpp
@@ -315,6 +315,10 @@ main(int argc, char *argv[])
     // hidpi ratios -- single desktop for now
     desktop = QApplication::desktop();
 
+#if QT_VERSION_MAJOR < 5
+#error "Debian 8.3 bug. Configure QT distributive"
+#endif
+
     // We will set screen ratio factor for sizing when a screen
     // is greater than the Surface Pro 3 2160x1440, since its a break
     // point with resolutions above that being devices like the

**Comment by pavlinux** [comment]
diff --git a/src/Core/main.cpp b/src/Core/main.cpp
index 0659b86..f755b4c 100644
--- a/src/Core/main.cpp
+++ b/src/Core/main.cpp
@@ -331,7 +331,7 @@ main(int argc, char *argv[])
     dpiXFactor = 1.0;
     dpiYFactor = 1.0;
 
-#if QT_VERSION_MAJOR >= 5
+#if QT_VERSION >= 0x050000
 #ifndef Q_OS_MAC // not needed on a Mac
     // if we're running with dpiawareness of 0 the screen resolution
     // will be expressed taking into account the scaling applied
