### ISSUE TITLE
Blank Default field causes hang while importing

### ISSUE THREAD

**Issue by bwalding** [GoldenCheetah/GoldenCheetah#2408]
## Steps

1. Open athlete configuration
2. Data Fields tab
3. Defaults sub-tab
4. Add a new field "Title" - leave all other entries blank
5. Import TCX file (although I suspect this isn't relevant).

## Outcome
Goldencheetah locks up

Thread-trace after I killed it:
```
Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   libsystem_malloc.dylib          0x00007fffc05f7e84 free + 87
1   com.yourcompany.GoldenCheetah   0x000000010a5bf0de RideMetadata::setLinkedDefaults(RideFile*) + 990
2   com.yourcompany.GoldenCheetah   0x000000010a507da5 RideImportWizard::abortClicked() + 6293
3   org.qt-project.QtCore           0x000000010bb81539 QMetaObject::activate(QObject*, int, int, void**) + 3113
```

## Cause

I'm not sure why a loops is required in RideMetadata::setLinkedDefaults (perhaps to do multi-step linked fields), but the root cause is that because the default value is blank, the change process is triggered each time, and GoldenCheetah never breaks out of the loop.

I see two solutions - fix the link update code (to know when it was a no-op) or put in a depth counter.

(You could say - "well don't do that" - but it wasn't until I looked at a stack trace that I even knew I had a `Title` in the defaults setup for my athlete)

**Comment by liversedge** [comment]
Thanks, do you have a patch?

**Comment by bwalding** [comment]
Not at present - only just checked out all the code and built it for the first time.  I have a crashing bug in the Computrainer calibrate screen that is far more pressing (as I am losing the start of my vo2max intervals occasionally!)

I think there is also an argument for preventing the configuration screen from persisting the bad configuration in the first place as well.

**Comment by bwalding** [comment]
PR #2413 addresses this issue

**Comment by Joern-R** [comment]
PR is merged - closed (thanks)
