### ISSUE TITLE
Activity Interval Avg Speed Error

### ISSUE THREAD

**Issue by GCuser99** [GoldenCheetah/GoldenCheetah#2412]
Using 3.5-DEV 1703. The average speed for the interval "Stephanie's Trail" is wrong. It shows 98 mph when it should be around 9.4 mph. In edit view, distances, times, and speeds look ok for this interval. In the summary window, the distance and time duration look fine too. This happens to be the only interval of the activity that isn't sampled a 1 sec intervals. The activity was created by combining a number of ride segments. Attached is a screen shot and the associated json activity file.

Thanks!

![interval stats](https://cloud.githubusercontent.com/assets/26237126/24311686/de943a78-109a-11e7-8e44-b0e0aa03eef6.JPG)

[2017_03_24_06_14_33.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/869044/2017_03_24_06_14_33.zip)

**Comment by Joern-R** [comment]
Not sure how you created that file. GC assumes a fixed sampling rate in the .json which you can look-up in the file here - "RECINTSECS":1

Running the "Fix Gaps in Recording" tools interpolates the missing data - after that the averages look fine.
