### ISSUE TITLE
Cadence value different from TCX file, half cadence

### ISSUE THREAD

**Issue by scuba0405** [GoldenCheetah/GoldenCheetah#2416]
I am having low cadence readings after importing from Garmin Connect TCX file. Cadence is about half of what it should be. Looking at the Cheetah Editor and comparing to the Garmin file, the values do NOT match line for line, not even close. Values in Garmin file are realistic.

Any tips?

**Comment by liversedge** [comment]
Suspect you have recorded with smart recording.
You can turn that on in preferences, it will interpolate as needed on import.

**Comment by scuba0405** [comment]
Garmin is set to Smart
Cheetah is set to Use Garmin Smart Recording, Smart Recording threshold, tried 1-5 secs. Deleted a few rides and reimported each. Still coming back with low cadences when viewed in the Editor.
Also, tried unchecking Use Garmin Sm.Rec, no effect.
