### ISSUE TITLE
 Matches / Intervals by kJ not found (build 1703 - 1705 - 1708)

### ISSUE THREAD

**Issue by Thskov** [GoldenCheetah/GoldenCheetah#2430]
The 3.5 build 1703 do not to find any matches/intervals based on kJ. Not by using "find Intervals" nor automatically at import. Same behavior as in 3.4.
Running on Mac (Sierra 10.12.3) and import of sessions with several matches burned (and found by 3.3)
My first issue listed here so please instruct me if more information needed.

**Comment by liversedge** [comment]
Check your config in Preferences > Intervals and Athlete > Power Zones and  that you are running 3.5 dev.

**Comment by Thskov** [comment]
Please find 3 pictures attached.

- Intervals auto-discovery is on,
- CP 321W (ftp set to the same for convinience),  W' 25500W
- Confirm that I'm on build 1703

![powerzones](https://cloud.githubusercontent.com/assets/26841223/24580858/a17bf476-16ff-11e7-8f73-d14de7b1223a.jpeg)
![version](https://cloud.githubusercontent.com/assets/26841223/24580859/a3f3654a-16ff-11e7-8d10-d7d7cc485b7b.jpeg)
![intervals](https://cloud.githubusercontent.com/assets/26841223/24580861/a652d23a-16ff-11e7-8898-345212cdbeed.jpeg)

**Comment by liversedge** [comment]
Strange, the rides have power and you didn't override CP or TAU ?

**Comment by Thskov** [comment]
Yes power from Garmin Vector v2 or Stages v2. I've tested with version 3.3 and that version finds the matches. No override of CP. 
TAU is set to 300s but I'm using differential method.
Had the same problem in 3.4.

Could it be left overs from an installation of version 3.4? 
I'm installing using the provided DMG files but never cleaned out the former versions (except when testing wether 3.3. found matches. 

After a ride today the auto-discovery found 5 sustained Z7 efforts of 6-11s but I know that there should be more and several matches burned. I can submit the fit files if that would help?

**Comment by Thskov** [comment]
Further details:
Sustained efforts are located but only on outdoor rides. So maybe I just need to train harder.
No matches found in two years of rides imported recently. Not by auto-discovery or interval finder.
