### ISSUE TITLE
Losing connectivity to CompuTrainer sends Train mode into error loop

### ISSUE THREAD

**Issue by bwalding** [GoldenCheetah/GoldenCheetah#2439]
If the USB plug comes loose or is bumped (or under some other less obvious conditions with the HBC / cable / power), then GC goes into a loop with a modal dialog stating:

"Cannot Connect to Computrainer"

It looks like the code is trying to "stop" at that point, but in my case I just end up in a loop that is really tricky to break out of.

(Just putting this as a place holder in case someone has already done something to fix this - otherwise I will take a look)

**Comment by davereeck** [comment]
I've got the same problem. I'm currently using Force Quit to get out of it.

**Comment by amtriathlon** [comment]
I think this can be solved replacing the modal dialog with a non-blocking emit setNotification so the "Cannot Connect to Computrainer" message is displayed in TrainBottom notification area unobstrusively.

**Comment by amtriathlon** [comment]
I've tested this and it works, when the connection cannot be established or fails, the notification is displyed as:
![Computrainer](https://user-images.githubusercontent.com/1444784/84091584-3a500780-a9cb-11ea-8561-49504f9f3c3e.png)
the button remains in connected state and it doesn't seems to reconnect automatically, but it is enabled, it can be used to disconnect and re-connect to re-establish the loosed connection and, more important, GoldenCheetah is not blocked anymore in this situation.
