### ISSUE TITLE
GC Build 1703 Crash on start

### ISSUE THREAD

**Issue by MatzeG** [GoldenCheetah/GoldenCheetah#2440]
[CGcrash.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/895707/CGcrash.zip)

GC crash on start

**Comment by gcoco** [comment]
Does this still happen with the 1705 build?
If so can you provide more information on when the issue started?
Have you tried starting using a new user? Do you have R installed and what version?

**Comment by MatzeG** [comment]
Hi gcoco
in the build 1705 is the crash on the start solved. But ... in some cases i get a crash when i switch from activities to trends. I can 
[GoldenCheetah.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1010468/GoldenCheetah.zip)

**Comment by amtriathlon** [comment]
I'm closing this since it corresponds to an older dev build, please try with the last one and see followup on the thread open for that purpose on the user's forum.
