### ISSUE TITLE
GC Build 1703 Crash when clicking Tab in Trends view

### ISSUE THREAD

**Issue by ragman1976** [GoldenCheetah/GoldenCheetah#2441]
Unhandled exception 0xc0000005
RAX=ffffffff RCX=0 RDX=c010 RBX=2
RSP=2d7930 RBP=2d7a30 RSI=0 RDI=2d7c78
R8=1999999999999998 R9=0 R10=1 R11=2d7770
R12=0 R13=2d7e40 R14=2d7e34 R15=2d7e28

GoldenCheetah.exe@0x13fc50000!+0x151c41
GoldenCheetah.exe@0x13fc50000!+0x14f99e
GoldenCheetah.exe@0x13fc50000!+0x1611c9
GoldenCheetah.exe@0x13fc50000!+0x184ece
GoldenCheetah.exe@0x13fc50000!+0x1832a1
GoldenCheetah.exe@0x13fc50000!+0x1822e7
GoldenCheetah.exe@0x13fc50000!+0x4d2589
Qt5Core.dll!QMetaObject::activate+0x574
GoldenCheetah.exe@0x13fc50000!+0x4ceacc
GoldenCheetah.exe@0x13fc50000!+0x12dd76
GoldenCheetah.exe@0x13fc50000!+0x4cf5ff
GoldenCheetah.exe@0x13fc50000!+0x4ced0d
GoldenCheetah.exe@0x13fc50000!+0x4cec21
GoldenCheetah.exe@0x13fc50000!+0x4d2fd1
Qt5Core.dll!QMetaProperty::write+0x494
Qt5Core.dll!QObject::setProperty+0x2a3
GoldenCheetah.exe@0x13fc50000!+0x13b4cf
Qt5Core.dll!QMetaObject::activate+0x574
GoldenCheetah.exe@0x13fc50000!+0x4ccb30
Qt5Core.dll!QMetaObject::activate+0x574
Qt5Core.dll!QSignalMapper::map+0x110
Qt5Core.dll!QMetaObject::activate+0x574
GoldenCheetah.exe@0x13fc50000!+0x4e1a80
GoldenCheetah.exe@0x13fc50000!+0x320e15
Qt5Widgets.dll!QApplicationPrivate::notify_helper+0x140
Qt5Widgets.dll!QApplication::notify+0x8b3
Qt5Core.dll!QCoreApplication::notifyInternal2+0xb9
Qt5Widgets.dll!QApplicationPrivate::sendMouseEvent+0x326
Qt5Widgets.dll!QSizePolicy::QSizePolicy+0x2cbc
Qt5Widgets.dll!QSizePolicy::QSizePolicy+0xa65
Qt5Widgets.dll!QApplicationPrivate::notify_helper+0x140
Qt5Widgets.dll!QApplication::notify+0x1b72
Qt5Core.dll!QCoreApplication::notifyInternal2+0xb9
Qt5Gui.dll!QGuiApplicationPrivate::processMouseEvent+0x7f4
Qt5Gui.dll!QWindowSystemInterface::sendWindowSystemEvents+0x9b
Qt5Core.dll!QEventDispatcherWin32::processEvents+0xe15
USER32.dll!TranslateMessageEx+0x29d
USER32.dll!TranslateMessage+0x1ea
Qt5Core.dll!QEventDispatcherWin32::processEvents+0x546
qwindows.dll!qt_plugin_query_metadata+0x1849
Qt5Core.dll!QEventLoop::exec+0x1b3
Qt5Core.dll!QCoreApplication::exec+0x144
GoldenCheetah.exe@0x13fc50000!+0x22ff3b
GoldenCheetah.exe@0x13fc50000!+0x55f514
GoldenCheetah.exe@0x13fc50000!+0x55eaef
kernel32.dll!BaseThreadInitThunk+0xd
ntdll.dll!RtlUserThreadStart+0x21

**Comment by liversedge** [comment]
Already fixed,
Thanks
