### ISSUE TITLE
Crash Train View

### ISSUE THREAD

**Issue by ragman1976** [GoldenCheetah/GoldenCheetah#2455]
Unhandled exception 0xc0000005
RAX=1500000000 RCX=249aed311c0 RDX=7b9e8f4a80 RBX=c4
RSP=7b9e8f4a50 RBP=7b9e8f4b50 RSI=c8 RDI=249984dae80
R8=1 R9=8000 R10=249b7e09420 R11=7b9e8f4a48
R12=550c0000 R13=0 R14=32 R15=bd

GoldenCheetah.exe@0x7ff6da7d0000!+0x4b9baa
Qt5Widgets.dll!QWidget::event+0x5a5
Qt5Widgets.dll!QApplicationPrivate::notify_helper+0x140
Qt5Widgets.dll!QApplication::notify+0x1b72
Qt5Core.dll!QCoreApplication::notifyInternal2+0xb9
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0x8b3
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QWidgetPrivate::paintSiblingsRecursive+0x3b8
Qt5Widgets.dll!QWidgetPrivate::drawWidget+0xa73
Qt5Widgets.dll!QApplication::windowIcon+0x1a23
Qt5Widgets.dll!QWidget::event+0xa54
Qt5Widgets.dll!QMainWindow::event+0x32e
Qt5Widgets.dll!QApplicationPrivate::notify_helper+0x140
Qt5Widgets.dll!QApplication::notify+0x1b72
Qt5Core.dll!QCoreApplication::notifyInternal2+0xb9
Qt5Widgets.dll!QWidgetPrivate::scrollRect+0x546
Qt5Widgets.dll!QWidgetPrivate::invalidateBuffer_resizeHelper+0xab2
Qt5Widgets.dll!QWidget::repaint+0xab
Qt5Widgets.dll!QWidget::repaint+0x4f
GoldenCheetah.exe@0x7ff6da7d0000!+0x4c689c
Qt5Core.dll!QMetaObject::activate+0x574
GoldenCheetah.exe@0x7ff6da7d0000!+0x4fc3c4
GoldenCheetah.exe@0x7ff6da7d0000!+0x4aeac5
Qt5Core.dll!QMetaObject::activate+0x574
Qt5Core.dll!QItemSelectionModel::emitSelectionChanged+0x5cc
Qt5Core.dll!QItemSelectionModel::select+0x261
Qt5Widgets.dll!QTreeViewPrivate::select+0x733
Qt5Widgets.dll!QTreeView::setSelection+0x2d9
Qt5Widgets.dll!QAbstractItemView::mousePressEvent+0x35a
Qt5Widgets.dll!QTreeView::mousePressEvent+0x89
Qt5Widgets.dll!QWidget::event+0xc6
Qt5Widgets.dll!QFrame::event+0x37
Qt5Widgets.dll!QAbstractItemView::viewportEvent+0x2e7
Qt5Core.dll!QCoreApplicationPrivate::sendThroughObjectEventFilters+0xdd
Qt5Widgets.dll!QApplicationPrivate::notify_helper+0x12c
Qt5Widgets.dll!QApplication::notify+0x8b3
Qt5Core.dll!QCoreApplication::notifyInternal2+0xb9
Qt5Widgets.dll!QApplicationPrivate::sendMouseEvent+0x326
Qt5Widgets.dll!QSizePolicy::QSizePolicy+0x2cbc
Qt5Widgets.dll!QSizePolicy::QSizePolicy+0xa65
Qt5Widgets.dll!QApplicationPrivate::notify_helper+0x140
Qt5Widgets.dll!QApplication::notify+0x1b72
Qt5Core.dll!QCoreApplication::notifyInternal2+0xb9
Qt5Gui.dll!QGuiApplicationPrivate::processMouseEvent+0x7f4
Qt5Gui.dll!QWindowSystemInterface::sendWindowSystemEvents+0x9b
Qt5Core.dll!QEventDispatcherWin32::processEvents+0xe15
USER32.dll!CallWindowProcW+0x4d0
USER32.dll!DispatchMessageW+0x1af
Qt5Core.dll!QEventDispatcherWin32::processEvents+0x546
qwindows.dll!qt_plugin_query_metadata+0x1849
Qt5Core.dll!QEventLoop::exec+0x1b3
Qt5Core.dll!QCoreApplication::exec+0x144
GoldenCheetah.exe@0x7ff6da7d0000!+0x24fc53
GoldenCheetah.exe@0x7ff6da7d0000!+0x581a34
GoldenCheetah.exe@0x7ff6da7d0000!+0x581017
KERNEL32.DLL!BaseThreadInitThunk+0x14
ntdll.dll!RtlUserThreadStart+0x21

**Comment by liversedge** [comment]
![timesaver](https://cloud.githubusercontent.com/assets/142876/25090349/8048c162-237a-11e7-9b5b-b3efbb13104c.png)
