### ISSUE TITLE
GC 3.5 Build 1704 Crash on virewing Workout  

### ISSUE THREAD

**Issue by socratesp** [GoldenCheetah/GoldenCheetah#2456]
I am running a  Linux Mint 18.1. When i click on a workout the GC crashes and displays "Segmentation Fault" on command line

**Comment by liversedge** [comment]
![timesaver](https://cloud.githubusercontent.com/assets/142876/25142113/adae5fe8-245d-11e7-8da6-40a66b91a8c8.png)
