### ISSUE TITLE
Crash when selecting Trends->Tracker

### ISSUE THREAD

**Issue by mtbkeith** [GoldenCheetah/GoldenCheetah#2460]
MacOS
SHA: f29942afd7714a9b6d4c7746fa8890028c9d0b32

crash while evaluating: 
double xValue = columns[i].x[0];

Process:               GoldenCheetah_KR [4427]
Path:                  /Users/USER/*/GoldenCheetah_KR.app/Contents/MacOS/GoldenCheetah_KR
Identifier:            com.foo.GoldenCheetah-KR
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           GoldenCheetah_KR [4427]
User ID:               501

Date/Time:             2017-04-19 11:08:43.215 -0600
OS Version:            Mac OS X 10.12.3 (16D32)
Report Version:        12
Anonymous UUID:        362A1E83-4A59-0C06-830E-8F1DE6FFE3C8

Sleep/Wake UUID:       031AFB52-79AE-46C5-889C-8A7FCDAA67A5

Time Awake Since Boot: 260000 seconds
Time Since Wake:       10000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fffe1dcadd6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fffe1eb6787 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fffe1d30420 abort + 129
3   org.qt-project.QtCore         	0x0000000104db68c9 qt_message_fatal(QtMsgType, QMessageLogContext const&, QString const&) + 9
4   org.qt-project.QtCore         	0x0000000104db8297 QMessageLogger::fatal(char const*, ...) const + 231
5   org.qt-project.QtCore         	0x0000000104db3192 qt_assert_x(char const*, char const*, char const*, int) + 82
6   com.foo.GoldenCheetah-KR  	0x00000001027722b3 QVector<double>::operator[](int) + 83 (qvector.h:437)
7   com.foo.GoldenCheetah-KR  	0x00000001028fd3e5 LTMWindow::dataTable(bool) + 3461 (LTMWindow.cpp:1165)
8   com.foo.GoldenCheetah-KR  	0x00000001028fa115 LTMWindow::refreshDataTable() + 37 (LTMWindow.cpp:1047)
9   com.foo.GoldenCheetah-KR  	0x00000001028f788b LTMWindow::refreshPlot() + 203 (LTMWindow.cpp:483)
10  com.foo.GoldenCheetah-KR  	0x00000001028f8994 LTMWindow::filterChanged() + 3604 (LTMWindow.cpp:865)
11  com.foo.GoldenCheetah-KR  	0x00000001028fb158 LTMWindow::dateRangeChanged(DateRange) + 264 (LTMWindow.cpp:808)
12  com.foo.GoldenCheetah-KR  	0x0000000102f0e64f LTMWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 287 (moc_LTMWindow.cpp:236)
13  org.qt-project.QtCore         	0x0000000104fbd2e1 QMetaObject::activate(QObject*, int, int, void**) + 913
14  com.foo.GoldenCheetah-KR  	0x0000000102f079d2 GcWindow::dateRangeChanged(DateRange) + 66 (moc_GoldenCheetah.cpp:523)
15  com.foo.GoldenCheetah-KR  	0x000000010285d0ee GcWindow::setDateRange(DateRange) + 78 (GoldenCheetah.cpp:125)
16  com.foo.GoldenCheetah-KR  	0x0000000102f073df GcWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 3807 (moc_GoldenCheetah.cpp:396)
17  com.foo.GoldenCheetah-KR  	0x0000000102f07f09 GcWindow::qt_metacall(QMetaObject::Call, int, void**) + 249 (moc_GoldenCheetah.cpp:447)
18  com.foo.GoldenCheetah-KR  	0x0000000102f081b3 GcChartWindow::qt_metacall(QMetaObject::Call, int, void**) + 51 (moc_GoldenCheetah.cpp:654)
19  com.foo.GoldenCheetah-KR  	0x0000000102f0fbb3 LTMWindow::qt_metacall(QMetaObject::Call, int, void**) + 51 (moc_LTMWindow.cpp:368)
20  org.qt-project.QtCore         	0x0000000104f98faf QMetaProperty::write(QObject*, QVariant const&) const + 1455
21  org.qt-project.QtCore         	0x0000000104fbdfac QObject::setProperty(char const*, QVariant const&) + 108
22  com.foo.GoldenCheetah-KR  	0x0000000102876d47 HomeWindow::tabSelected(int) + 679 (HomeWindow.cpp:399)
23  com.foo.GoldenCheetah-KR  	0x0000000102f0a156 HomeWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 278 (moc_HomeWindow.cpp:201)
24  org.qt-project.QtCore         	0x0000000104fbd2e1 QMetaObject::activate(QObject*, int, int, void**) + 913
25  com.foo.GoldenCheetah-KR  	0x0000000102f02996 ChartBar::currentIndexChanged(int) + 70 (moc_ChartBar.cpp:199)
26  com.foo.GoldenCheetah-KR  	0x0000000102817fc3 ChartBar::clicked(int) + 163 (ChartBar.cpp:309)
27  com.foo.GoldenCheetah-KR  	0x0000000102f02778 ChartBar::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 344 (moc_ChartBar.cpp:134)
28  org.qt-project.QtCore         	0x0000000104fbd2e1 QMetaObject::activate(QObject*, int, int, void**) + 913
29  org.qt-project.QtCore         	0x0000000104fc2435 QSignalMapper::map(QObject*) + 213
30  org.qt-project.QtCore         	0x0000000104fbd2e1 QMetaObject::activate(QObject*, int, int, void**) + 913
31  com.foo.GoldenCheetah-KR  	0x0000000102f37d68 GcScopeButton::clicked(bool) + 72 (moc_GcScopeBar.cpp:144)
32  com.foo.GoldenCheetah-KR  	0x0000000102c2ac28 GcScopeButton::event(QEvent*) + 136 (GcScopeBar.cpp:411)
33  org.qt-project.QtWidgets      	0x000000010430058d QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
34  org.qt-project.QtWidgets      	0x0000000104303ca0 QApplication::notify(QObject*, QEvent*) + 9440
35  org.qt-project.QtCore         	0x0000000104f8c544 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
36  org.qt-project.QtWidgets      	0x0000000104300ef7 QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) + 871
37  org.qt-project.QtWidgets      	0x00000001043618fb QWidgetWindow::handleMouseEvent(QMouseEvent*) + 1387
38  org.qt-project.QtWidgets      	0x000000010436094f QWidgetWindow::event(QEvent*) + 175
39  org.qt-project.QtWidgets      	0x000000010430058d QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
40  org.qt-project.QtWidgets      	0x0000000104302ed2 QApplication::notify(QObject*, QEvent*) + 5906
41  org.qt-project.QtCore         	0x0000000104f8c544 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
42  org.qt-project.QtGui          	0x00000001048db21a QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 2794
43  org.qt-project.QtGui          	0x00000001048c249b QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 155
44  libqcocoa.dylib               	0x000000010c64b821 QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 33
45  com.apple.CoreFoundation      	0x00007fffcc76e981 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
46  com.apple.CoreFoundation      	0x00007fffcc74fa7d __CFRunLoopDoSources0 + 557
47  com.apple.CoreFoundation      	0x00007fffcc74ef76 __CFRunLoopRun + 934
48  com.apple.CoreFoundation      	0x00007fffcc74e974 CFRunLoopRunSpecific + 420
49  com.apple.HIToolbox           	0x00007fffcbcdaa5c RunCurrentEventLoopInMode + 240
50  com.apple.HIToolbox           	0x00007fffcbcda799 ReceiveNextEventCommon + 184
51  com.apple.HIToolbox           	0x00007fffcbcda6c6 _BlockUntilNextEventMatchingListInModeWithFilter + 71
52  com.apple.AppKit              	0x00007fffca2805b4 _DPSNextEvent + 1120
53  com.apple.AppKit              	0x00007fffca9fad6b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2789
54  com.apple.AppKit              	0x00007fffca274f35 -[NSApplication run] + 926
55  libqcocoa.dylib               	0x000000010c64a6bf QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2143
56  org.qt-project.QtCore         	0x0000000104f88781 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 401
57  org.qt-project.QtCore         	0x0000000104f8cbb5 QCoreApplication::exec() + 341
58  com.foo.GoldenCheetah-KR  	0x0000000102a64f31 main + 10865 (main.cpp:675)
59  libdyld.dylib                 	0x00007fffe1c9c255 start + 1

**Comment by Joern-R** [comment]
Regression introduced by https://github.com/GoldenCheetah/GoldenCheetah/pull/2422/commits/bff5c7a85322255ece7224d3e9e9d32f64d7998e - sorry. 

Fix https://github.com/GoldenCheetah/GoldenCheetah/commit/be2edb82e633eaf2df59d246be7c0bc3bdbe1984

Can you please check if the fix work (since I have not chart definition where the problem occured).

**Comment by mtbkeith** [comment]
@Joern-R Fixed! Thanks

**Comment by Joern-R** [comment]
Thanks for testing - will close then.
