### ISSUE TITLE
y-axis of charts chooses max of all activity 'bests'

### ISSUE THREAD

**Issue by mtbkeith** [GoldenCheetah/GoldenCheetah#2463]
When selecting one activity such as Bike with CV showing the y-axis at kph, a max of 140 is shown for one of my activities. Then select a Run The CV chart continues to show the y-axis scale at 140, despite the activity being much slower. 

However, if the Run was selected first then CV graph shown, the max Y-value shown would be 30 (kph). Selecting the Bike after the Run does increase the y-max to 140 yet switching back to the Run maintains this at 140 just as the other operation.

Problem appears to be somewhere in 

CPPlot::plotBests(RideItem *rideItem)

probably related to this or similar calls:
setAxisScale(yLeft, 0, 1.1*values[0]);

Related request: https://github.com/GoldenCheetah/GoldenCheetah/issues/2044

see attached images:
Select Run straight off
<img width="1007" alt="grab-run-cv-first" src="https://cloud.githubusercontent.com/assets/9326275/25213837/c007a692-2550-11e7-99fa-21d439e77b35.png">
Select Bike, increasing max-y value
<img width="1185" alt="grab-bike-cv-second" src="https://cloud.githubusercontent.com/assets/9326275/25213839/c0578964-2550-11e7-9f53-013a2d06b1c4.png">
Select Run again, max-y value maintained from cycling.
<img width="1072" alt="grab-run-cv-third" src="https://cloud.githubusercontent.com/assets/9326275/25213838/c056a2a6-2550-11e7-8f0d-b269d1c56c2e.png">

**Comment by amtriathlon** [comment]
I cannot reproduce this in current master, likely fixed already.
