### ISSUE TITLE
Hrv Elite Sync

### ISSUE THREAD

**Issue by teomtb4** [GoldenCheetah/GoldenCheetah#2467]

**Comment by liversedge** [comment]
?

**Comment by amtriathlon** [comment]
Starting with https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/v3.5-DEV1708 it is possible to import HRV measures from CSV files, supported features and formats are described in the wiki https://github.com/GoldenCheetah/GoldenCheetah/wiki/HRV

**Comment by teomtb4** [comment]
Thanks, great job !!!Matteo



----Messaggio originale----

Da: "Alejandro Martinez" <notifications@github.com>

Data: 14/08/2017 14.57

A: "GoldenCheetah/GoldenCheetah"<GoldenCheetah@noreply.github.com>

Cc: "teomtb4"<parolomatteo@libero.it>, "Author"<author@noreply.github.com>

Ogg: Re: [GoldenCheetah/GoldenCheetah] Hrv Elite Sync (#2467)




Starting with https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/v3.5-DEV1708 it is possible to import HRV measures from CSV files, supported features and formats are described in the wiki https://github.com/GoldenCheetah/GoldenCheetah/wiki/HRV
