### ISSUE TITLE
GC 3.4: Crash when using Aerolab on splitted activity

### ISSUE THREAD

**Issue by Mrnofish** [GoldenCheetah/GoldenCheetah#2479]
OS: Windows 10 64-bit 1703
GC: v3.4 64-bit downloaded from the official site

Steps to reproduce:

1. Create new athlete profile
2. Import activity from original .fit file
Mine was recorded by a Garmin Edge 500 running FW v3.3
3. Split Activity
I have used lap markers from the original recording.
4. Add Aerolab chart
5. Select activity
6. Press "Estimate Crr & CdA" button
7. BOOM

Running Aerolab on the relevant subsection of the original ride doesn't make it crash.

This may also result in some corruption of the cache: GC was abnormally slow to start on my original profile (many minutes of wait) and seemingly went back to normal after deleting the entire folder and letting GC regenerate it.

I also could find no crash log in AppData/Local/goldencheetah, nor was offered any notification or chance to report a crash, besides the profile selection dialog opening.

edit: I've added a ride file that should help; split Lap 2 to a new activity; the actual values in Aerolab seem to make no difference, so just press the Estimate button, and it should crash (I have verified that this is the case for me using a new profile and the attached file).

[2017_04_24_18_00_00.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/963032/2017_04_24_18_00_00.zip)

**Comment by Mrnofish** [comment]
I expanded the original report with a ride file and detailed steps on how to reproduce the crash.

**Comment by amtriathlon** [comment]
I've imported your file to v3.5dev1708, split Lap 2 and used Aerolab without crashes, can you try the new development build?

**Comment by Mrnofish** [comment]
I did, crashes just the same for me. This is from the Windows Event Log:

Faulting application name: GoldenCheetah.exe, version: 0.0.0.0, time stamp: 0x598342c9
Faulting module name: ntdll.dll, version: 10.0.15063.447, time stamp: 0xa329d3a8
Exception code: 0xc0000374
Fault offset: 0x00000000000f775f
Faulting process id: 0x41b8
Faulting application path: C:\Program Files\Golden Cheetah inDev\GoldenCheetah.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll

**Comment by amtriathlon** [comment]
I re-tested this file on v3.5 RC1 without crashes.
