### ISSUE TITLE
Weirdness in time-based metrics calculated by GC

### ISSUE THREAD

**Issue by Mrnofish** [GoldenCheetah/GoldenCheetah#2480]
Spotted something weird while analyzing historical data - my TRIMP-driven PMC saw stress scores for 2013 drop strangely during the central part of the year. Further investigation shown inflated average speeds during the same period, and ultimately that Time Moving was being grossly understated, just like time in zone, leading to falsely low TRIMP scores.
![gc-howtobecomefast1](https://cloud.githubusercontent.com/assets/28036193/25418907/702fcad8-2a4f-11e7-8857-c7406fbb01eb.png)
![gc-howtobecomefast2](https://cloud.githubusercontent.com/assets/28036193/25418908/70324808-2a4f-11e7-8bb3-5c0d86f7618c.png)
![gc-howtobecomefast3](https://cloud.githubusercontent.com/assets/28036193/25418909/7035f16a-2a4f-11e7-88fb-5fde5d73d476.png)

I've attached a partly anonymized json file which should reproduce the issue when imported into a new profile (it does for me). Running GC's Fix Gaps and Fix Speed from Distance brings the figures more in line to what is reported by Garmin Connect and Strava, with Moving Time being 3:23 versus GC's claim of 3:16.

I'm aware GC is not supposed to fix the data behind the scenes, however it does seem to me that GC's being massively oversensitive to whatever it is it thinks is wrong in the recordings here.

[2013_08_15_16_43_25.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/957357/2013_08_15_16_43_25.zip)

**Comment by liversedge** [comment]
The files were recorded with Garmin Smart Recording enabled. 
You can post process these files with Fix Gaps, or set Garmin Smart Recording on in Options.

**Comment by Mrnofish** [comment]
Just because a file has gaps in them, it doesn't mean the Garmin had Smart Recording on: even yesterday's ride has gaps, most activities have them. More, I'd be surprised if there's an activity in my whole library that doesn't have gaps.

My Garmin has been set to 1-sec since day 1, and I certainly didn't go flipping that setting randomly. What would be the point of that?

Also, setting Garmin Smart Recording to On in GC's Options changes absolutely nothing.

**Comment by liversedge** [comment]
I believe you stated that this only happened for a certain period -- perhaps after a firmware update that flipped it on?

**Comment by liversedge** [comment]
FWIW, if your head unit is set to 1-sec recording there will be no gaps in recording. There may be samples with no data, but there won't be missing samples. Unless your headunit is faulty or you chose to pause recording.

**Comment by Mrnofish** [comment]
During everyday use, there is no indication that the unit is working incorrectly, I also ran a chkdsk /R on the unit's file system which found no problem. Is there anything I should check or try?

Having reviewed some recent activities, I wonder if the samples may be missing because of a loss of GPS fix. This is how they appear in GC:

![image](https://cloud.githubusercontent.com/assets/28036193/25452306/7895a316-2ac5-11e7-96b5-6ff3eda6aeb8.png)

After converting the original FIT file into a CSV with the latest FIT SDK, the first sample after the gap has data from sensors but is missing GPS coordinates. Before and after that sample, there are two messages, which begin with:

`Data,4,unknown,unknown,<timestamp>,unknown,,`

followed by a bunch of "<single digit>,,unknown", and ending with:

`unknown,"255",,unknown,"255",,,,,,,,,,,,,,,,,`

Unsurprisingly:

`Definition,4,unknown,unknown,1,,unknown,1,,unknown,1,,unknown,1,,unknown,1,,unknown,1,,unknown,1,,unknown,1,,unknown,1,,unknown,1,,,,,,,,,,,,,,,,,`

There are other Data,4 messages in the file though, so they may be unrelated to the missing samples. What do you think?
