### ISSUE TITLE
Support different bikes / equipment

### ISSUE THREAD

**Issue by UlysseUlysse** [GoldenCheetah/GoldenCheetah#2481]
Hi Mark, why don't envisage doing several size of whells  such as for example on for an Mountainbike and a other for road bike, Best regards Paul

**Comment by liversedge** [comment]
This  is a duplicate of #1572

**Comment by UlysseUlysse** [comment]
Sorry I d'ont speak English, thank you for the link

**Comment by liversedge** [comment]
No worries !
