### ISSUE TITLE
GC 3.4 crash while uploading file

### ISSUE THREAD

**Issue by Luchito97** [GoldenCheetah/GoldenCheetah#2482]

**Comment by liversedge** [comment]
Do you have any further details?
Can you share the file (via email liversedge@gmail.com) ?
There isn't enough information to progress this issue.

**Comment by Luchito97** [comment]
I installed the 3.5v and now it works. Thank you
Luca

2017-04-27 17:11 GMT+02:00 Mark Liversedge <notifications@github.com>:
