### ISSUE TITLE
"Dashboard" item gear icon does nothing

### ISSUE THREAD

**Issue by BrettDikeman** [GoldenCheetah/GoldenCheetah#2483]
The gear icon here does nothing except highlight when clicked:

<img width="400" alt="screen shot 2017-04-27 at 12 39 57 pm" src="https://cloud.githubusercontent.com/assets/4131229/25494177/c52147b8-2b46-11e7-9e02-c78fb5ed6f3a.png">

**Comment by liversedge** [comment]
Overview is a wip
