### ISSUE TITLE
Strava "share" has a confusing confirmation message

### ISSUE THREAD

**Issue by BrettDikeman** [GoldenCheetah/GoldenCheetah#2484]
Dev build 1704:

<img width="207" alt="screen shot 2017-04-19 at 10 22 59 pm" src="https://cloud.githubusercontent.com/assets/4131229/25494404/8cb9e8b6-2b47-11e7-9704-500d1836539b.png">

**Comment by liversedge** [comment]
Is this your own build?

**Comment by BrettDikeman** [comment]
Nope, I always use your builds. Also, I'm on OS X 10.9, if that matters.

<img width="251" alt="screen shot 2017-04-27 at 1 05 41 pm" src="https://cloud.githubusercontent.com/assets/4131229/25495183/4b0eadf4-2b4a-11e7-8880-7a8bf1f4abe6.png">

**Comment by freekode** [comment]
I also had the same problem, but now new sync with strava was introduced. So in the last version there is no such problem.

**Comment by liversedge** [comment]
Yes, I could not recreate it. Will close now.
