### ISSUE TITLE
Selecting OpenStreetMap tile service breaks map tile loading after an application restart.

### ISSUE THREAD

**Issue by BrettDikeman** [GoldenCheetah/GoldenCheetah#2485]
Dev build 1704:

<img width="508" alt="screen shot 2017-04-27 at 12 51 28 pm" src="https://cloud.githubusercontent.com/assets/4131229/25494635/44d62a90-2b48-11e7-995f-3f234270b5ba.png">

To reproduce:

- Set the tile service to OpenStreetMap (verify map tiles load)

- Close GC

- Open GC and go to map view for an activity. No tiles are loaded.

- Toggle tile service to Bing or Google, then back to OSM. Tiles are loaded.

Edit: it may be necessary to select a different OSM tile server in order to get tiles to load.

**Comment by liversedge** [comment]
Fixed in dfa5992762fed25aa5dc355e6d41d04c1bb14646
