### ISSUE TITLE
Google logo is displayed in map view regardless of what tile service is in use

### ISSUE THREAD

**Issue by BrettDikeman** [GoldenCheetah/GoldenCheetah#2486]
Dev build 1704:

<img width="476" alt="screen shot 2017-04-27 at 12 58 24 pm" src="https://cloud.githubusercontent.com/assets/4131229/25494897/3b7530ee-2b49-11e7-871c-d7ee35e0dbf2.png">

**Comment by grauser** [comment]
Yes, we use the google maps javascript library for displaying OpenStreetMap map tiles.

This is one of several approaches for displaying OpenStreetMap (alternative can be Leaflet or OpenLayers)

**Comment by BrettDikeman** [comment]
Aha! TIL. Side question: how possible would it be to implement some sort of
caching of tiles? It's a bummer when you're offline and can't see any maps
:-\.
