### ISSUE TITLE
Interval labels in chart view are not redrawn correctly when hover-over drop-down menu is activated

### ISSUE THREAD

**Issue by BrettDikeman** [GoldenCheetah/GoldenCheetah#2488]
<img width="927" alt="screen shot 2017-04-27 at 2 55 21 pm" src="https://cloud.githubusercontent.com/assets/4131229/25499473/950678a6-2b59-11e7-99d1-64a5cb6a9a8a.png">
<img width="630" alt="screen shot 2017-04-27 at 2 53 56 pm" src="https://cloud.githubusercontent.com/assets/4131229/25499476/950d1f3a-2b59-11e7-9fff-a6120856b73b.png">
<img width="688" alt="screen shot 2017-04-27 at 2 53 41 pm" src="https://cloud.githubusercontent.com/assets/4131229/25499475/9508e8f2-2b59-11e7-8f7d-8d5d4fa14121.png">
<img width="106" alt="screen shot 2017-04-27 at 2 53 01 pm" src="https://cloud.githubusercontent.com/assets/4131229/25499474/9507c972-2b59-11e7-9c9a-c93667c4f341.png">

Dev build 3961/1704, OS X 10.9.

**Comment by amtriathlon** [comment]
This refers to an old dev build, please reopen if you can reproduce the issue with the latest v3.5 build.

**Comment by BrettDikeman** [comment]
![Screen Shot 2019-11-17 at 1 17 10 AM](https://user-images.githubusercontent.com/4131229/69003935-c0deb380-08d8-11ea-9838-2cd7ee2f530a.png)

In the mid-October release candidate, on OS X 10.12 - yes, this two year old bug still exists. In a chart tab, create a selection. Then just swipe your cursor up.

The bug appears to be related to different logic used when the cursor exits out of the drop-down UI upward; the labels are correctly re-drawn if the cursor exits below.

Unsubscribing from this bug, FYI.
