### ISSUE TITLE
TodaysPlan::writeFile() should upload more data (RPE, weight, etc)

### ISSUE THREAD

**Issue by potuz** [GoldenCheetah/GoldenCheetah#2493]
The current upload to todaysplan only sends filename and userID and extra data like RPE, weight, fat, etc.. is not transmitted. 

Changing the request json to something like
```
    QString json;
    json  = QString("{ filename: \"%1\"").arg(remotename);
    if (userId.length()>0) 
        json.append(QString(", userId: %1").arg(userId));
    json.append(" , rpe=4.1 }");
```
does work and todaysplan updates the RPE value to 4.1. The problem is that the data is compressed in this function and passing extra info will require some refactoring. 

Perhaps in the generic upload dialog one should be able to decide which data to upload and then to ``CloudService::writeFile`` an extra arg should be added listing these parameters. 

EDIT: Ah right, I see that the third not used parameter holds the ride uncompressed anyway... then it's easy to patch it to upload some data if present

**Comment by grauser** [comment]
Yes , sending RPE (and LPS and TQS) was lost in one of my commits.
I will add this again (using RPE, LPS and TQS metadata)

But with like @liversedge did with name in Strava we can perhaps ask the user which metadata should be used for RPE.

**Comment by potuz** [comment]
I'm using the small attached patch that works for me... 
[todaysplan_upload_rpe.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/965371/todaysplan_upload_rpe.txt)

**Comment by liversedge** [comment]
Do not change the readFile and writeFile API to support service specific information.

Damien's idea of selecting a metadata field to source RPE is not right. GC already assumes RPE is being set in a metadata field called "RPE" (it is used in metrics etc).

**Comment by liversedge** [comment]
Happy for the TodaysPlan::writeFile() function to address this though :)

**Comment by liversedge** [comment]
the patch looks fine !

**Comment by grauser** [comment]
I have the code ready.
But OK RPE is metatag RPE
TQR (Total quality recovery) for TQR ?
And LPS (Leg pain score) ? LPS (it is pain in Today's plan json...)

**Comment by liversedge** [comment]
Yes that would be fine. We should document these somewhere !

**Comment by liversedge** [comment]
Is this fixed now?

**Comment by grauser** [comment]
I have to push. But I want some more tests.

**Comment by grauser** [comment]
fin in 186a33898dcd70f89b423e019387b6c839ae8321

**Comment by liversedge** [comment]
THANKS
