### ISSUE TITLE
Apperance setting in 3.5

### ISSUE THREAD

**Issue by nenadjev** [GoldenCheetah/GoldenCheetah#2496]
Why did you change Apperance setting in 3.5? There were more options in previous versions. We were able to adjust diffetrent fonts for different things. In 3.5 we have only one font adjusment, and I can't adjust the proper font sizes, it are or the to large or to small.

**Comment by liversedge** [comment]
Because most users weren't using that and we needed a way of managing font sizes across hi-dpi and normal displays in a cross-platform way.

**Comment by GSkrt** [comment]
I still can't find a way to manage my high DPI display on Ubuntu. QT fonts of the menus follow the appearance settings but I can't find a way to change fonts in the windows. Is there a workaround ??
