### ISSUE TITLE
New build segfaults on Debian Unstable

### ISSUE THREAD

**Issue by prokoudine** [GoldenCheetah/GoldenCheetah#2498]
New alpha/beta build of GC crashes immediately after being started on Debian Unstable:

Using your deb build:

$ GoldenCheetah 
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
Segmentation fault

(gdb) run
Starting program: /usr/bin/GoldenCheetah 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdd1d0700 (LWP 27173)]
[New Thread 0x7fffd30f4700 (LWP 27174)]
[New Thread 0x7fffd28f3700 (LWP 27175)]
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0

Thread 1 "GoldenCheetah" received signal SIGSEGV, Segmentation fault.
0x00000000004be0b4 in RCanvas::circle(double, double, double, QPen, QBrush) ()
(gdb) bt
#0  0x00000000004be0b4 in RCanvas::circle(double, double, double, QPen, QBrush) ()
#1  0x00000000004b4ffd in RGraphicsDevice::Circle(double, double, double, R_GE_gcontext*, _DevDesc*) ()
#2  0x00007fffc3aa4593 in GEaddDevice () from /usr/lib/R/lib/libR.so
#3  0x00007fffc3aa472b in GEaddDevice2 () from /usr/lib/R/lib/libR.so
#4  0x00000000004b644c in RGraphicsDevice::createGD() ()
#5  0x000000000049dc77 in RTool::RTool() ()
#6  0x0000000000472765 in main ()

**Comment by liversedge** [comment]
Can you start with --no-r 

What version of R do you have installed?

Thanks

**Comment by liversedge** [comment]
Looks like it has been built with R 3.0.2, which is old.
Will see if we can get it built with 3.3.x, and examine code to fixup when R is a different release.

**Comment by prokoudine** [comment]
R is 3.4.0 here. Running with '--no-r' helps, thanks!

**Comment by liversedge** [comment]
Need to work out how to support different versions of R.

**Comment by liversedge** [comment]
This has now been fixed with commit a75b7b3db18775c8
