### ISSUE TITLE
TCX file no L/R Balance. 

### ISSUE THREAD

**Issue by Jkanphoto** [GoldenCheetah/GoldenCheetah#2499]
Hi. Recently changed to a Garmin device. After it upload files to Garmin connect and I download the files as TCX, it doesn't show L/R balance in Golden Cheetah. I tried using GPX, and that simply shows no data at all...  Did I just messed up some setting in Golden Cheetah or is this an actual bug? Someone please help :/ 

Linked to pictures
https://ibb.co/gOkfy5
https://ibb.co/eX2cd5

**Comment by amtriathlon** [comment]
TCX format doesn't support L/R Balance, you need to export the original .fit from Garmin Connect
