### ISSUE TITLE
Windows build error

### ISSUE THREAD

**Issue by Boundarycondition** [GoldenCheetah/GoldenCheetah#2501]
Hi,

I wanted to get in touch as I am having some trouble building golden cheetah from source through QT creator. I followed the guide as posted on:
https://github.com/GoldenCheetah/GoldenCheetah/wiki/Building-golden-cheetah-for-windows. No kidding about the compile time... ;) but I was unsuccessful in launching the .exe. I have access to two machines one running win 10 and the other win 8. While I can run the build from within Qt creator on the win 8 machine unfortunately launching the .exe fails with the following message: 

> The procedure entry point ?toUtf8@QString@@QEGBA?AVQByteArray@@XZ could not be located in the dynamic link library C:\development\github\goldencheetah\src\release\kqoauth0.dll

On win10 message I can't run the build as the compile output message gives the following error:

> libkmldom.pdb
libkmlbase.pdb
libkmldom.lib(vec2.obj):-1: warning: LNK4099: PDB 'libkmldom.pdb' was not found with 'libkmldom.lib(vec2.obj)' or at 'C:\development\github\build-build-Desktop_Qt_5_8_0_MSVC2015_64bit-Release\src\release\libkmldom.pdb'; linking object as if no debug info

Not sure where to go from here.

As for the guide can I suggest the following additions to an otherwise clear guide:

- "Installation" of winflexbison and adding a system path to the file folder (This error showed up as win_bison.exe not found.)

-  copy paste the following files from Joern's individual folders into the src/release/ folder which contains the GoldenCheetah.exe (kqoauth0.dll, libsamplerate-0.dll, SiUSBXp.dll), from the QT installation (Qt5Charts.dll, Qt5WebEngineCore.dll, QT5WebengineWidgets.dll) and as already stated the VLC. At least these came up during my process, but basically it wasn't clear into which folder I needed to copy them into.

Many thanks

**Comment by Joern-R** [comment]
There is a "Windows SDK" with all dependencies (which is better documented than the CI libs) - here: https://github.com/GoldenCheetah/WindowsSDK/releases

Please put further questions on compiling/development to the Development group here: https://groups.google.com/forum/?hl=de#!forum/golden-cheetah-developers

Cheers.
Joern
