### ISSUE TITLE
Strava sync doesn't create intervals

### ISSUE THREAD

**Issue by lemppari** [GoldenCheetah/GoldenCheetah#2505]
When syncing data from Strava the lap information is not imported as intervals. The whole exercise is imported as one lap.

**Comment by EagleEye666666** [comment]
I have checked several exports of GC. Any exported file provide the lap data, also the FIT not. Furthermore, any of that files can be manually imported to garmin connect.
The file size of the exported TCX is crazy. 2 hour ride more than 5 MB? But when using the strava upload function the window claims size of 245 kb... if that uses TCX it's strange. Has the export / export batch other code for export of the GC data? I find it hard to check that on my own.
FIT file is so small that it looks suspicious and only strava can handle these GC exported file, but there is no lap data either.
I tried to upload these files to Endomondo as well. No success.
Well and that's it, there is no other useful format for export from GC and manual import to other platforms. 
Do you plan GPX file support in the future?

**Comment by lemppari** [comment]
The laps are now imported with https://github.com/GoldenCheetah/GoldenCheetah/commit/d2c03af6391071d4f01b5a61ac0ed0fd54620b99. However the laps are not in correct place.
