### ISSUE TITLE
TSS per hour averaging problems in Metrics Trends charts

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#2508]
The problem was reported at the forum (https://groups.google.com/d/msg/golden-cheetah-users/0mrLR07rxIs/RewazEhXAwAJ) and it seems to be due to the TSS per hour metric set count to hours while LTMPlot averaging assumes count is an integer number of seconds.
Two solutions possible solutions:
1) change LTMPlot to remove that assumption and allows count to be a double
2) change TSS per hour metric to be like other metrics where count is seconds and document count should be seconds, even for custom metrics.

**Comment by liversedge** [comment]
I'd keep things simple and set count to seconds. Anything else runs the risk of introducing a regression.

Not sure why count would be assumed to be seconds !

**Comment by amtriathlon** [comment]
The assumption in Metric Trends is count is an integer value, not necessarily seconds, lets got with the simpler solution.
