### ISSUE TITLE
Import from Sporttracks.mobi - Missing speed data, wrong elevation

### ISSUE THREAD

**Issue by Sepp-Mobil** [GoldenCheetah/GoldenCheetah#2512]
After Importing my data from Sporttracks.mobi which i use to record my training since 2007, the speed data is not imported. Also on overview page, the "time moving" seems to be wrong as well as the elevation. I did a ride about 2 hours with 480m elev. gained, GC shows 112479m.

**Comment by liversedge** [comment]
Thank you. Will fix this. We need to derive speed from time and distance.

**Comment by liversedge** [comment]
@grauser hey damien, still looking at this or would you like me to take a look?

Cheers
Mark
