### ISSUE TITLE
Dropbox API v1 migrate to API v2

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#2528]
The dropbox API is being deprecated, we have till the end of June to migrate to V2
This has been outstsanding for 12 months -- I just noticed.

https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

**Comment by liversedge** [comment]
The deadline for publishing this is:
**September 28, 2017: API v1 endpoints are turned off.**

**Comment by Joern-R** [comment]
@liversedge are you working on this ? otherwise I can take over.

**Comment by liversedge** [comment]
Thank you

**Comment by liversedge** [comment]
BTW, I did push one commit for this: 8c3ac5f15b9386e4691f45a13d972d8c29558816

**Comment by Joern-R** [comment]
A - now I know why the OAUTH stuff does not need any adjustment.

**Comment by Joern-R** [comment]
Closed via the commit above and

https://github.com/GoldenCheetah/GoldenCheetah/commit/d8df5f228864d862713375e37d788243be75b4e9
