### ISSUE TITLE
crash when sync(download) from strava.com GC DEV 3.5 1705 win10 x64

### ISSUE THREAD

**Issue by izerwu** [GoldenCheetah/GoldenCheetah#2529]
memory usage increase when downloading and will cause low memory then finally crashed

**Comment by amtriathlon** [comment]
If you can reproduce this on the last development build (https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/v3.5-DEV1710) please comment on the corresponding thread at the users forum: https://groups.google.com/d/msg/golden-cheetah-users/CiwAwufvQRA/m7O1UgN-AAAJ
