### ISSUE TITLE
Read lap names from FIT files

### ISSUE THREAD

**Issue by prokoudine** [GoldenCheetah/GoldenCheetah#2533]
When I import a .fit file to TrainingPeaks, it reads lap names from a structured workout, e.g. 

Lap 1 Freestyle
Rest
Lap 2 Drill
Rest

etc.

But GoldenCheetah just automatically names all laps using 'Lap N+1' naming scheme. Would be nice to just read all that data from FIT files if possible.

**Comment by grauser** [comment]
Could you attach a file ?
Thank you.

**Comment by prokoudine** [comment]
Here is one: [1758571391.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1033424/1758571391.zip)

**Comment by amtriathlon** [comment]
@grauser have you investigated this?
I have the impression this laps names are not form the FIT file but generated by the applications, but I may be wrong.

**Comment by liversedge** [comment]
lap names are not stored in fit files.
