### ISSUE TITLE
CP history

### ISSUE THREAD

**Issue by henolo** [GoldenCheetah/GoldenCheetah#2534]
v3.5-DEV1705

Some curves have messed up x-axis values for the newer values (these dates are shown as older than they should).
This depends on the time period.
Longer periods have "compressed" new values.
Shorter periods are ok.
"Latest 28 days" and shorter are shown ok, "Latest 2 months" and longer are not.
![latest 28 days](https://cloud.githubusercontent.com/assets/15927134/26523320/8ae6ffd4-4315-11e7-924b-ead14c9096e9.jpg)
![latest 2 months](https://cloud.githubusercontent.com/assets/15927134/26523323/93e568f0-4315-11e7-942a-30495cb30e1a.jpg)

**Comment by riccioclista** [comment]
I can confirm that one for current master (167165ca15724d88b7a796e40d4494a14216996f).

**Comment by henolo** [comment]
The error behavior in my case has changed since I initially reported it. Now (Oct 25) all Date Ranges but one are ok. "Last 12 Months" is still plotted with wrong dates. Could be that some data (activities or analysis of activities) are not "shaped" as this plot needs them to be.

**Comment by riccioclista** [comment]
I've debugged into the code and found that the plotting code doesn't account for gaps in the underlying model data. For example, if you have model estimates for January and May, it plots the May data right next to the January data without leaving the proper gap. I'll try to make the code more rebust in that regard.

**Comment by henolo** [comment]
I can confirm that there are larger gaps during the winter (2016/2017) in my case - fits well with the very messed up 12 month view. And also some shorter gaps more recently due to various "issues" like inspecting the tarmac and germs and yes they are ideed "time-compressing" more or less all the durations to the left. Didn't observe this until now.

**Comment by henolo** [comment]
Closing!
