### ISSUE TITLE
ant+ signal strength

### ISSUE THREAD

**Issue by 80ka** [GoldenCheetah/GoldenCheetah#2537]
Is there a way to monitor the ANT+ signal strength from a .fit file of a Garmin device ?

**Comment by rkantos** [comment]
What do you mean by monitor? To my knowledge of inspecting and editing fit-files, the files that Garmin devices output do not contain any signal strength data for neither GPS or ANT+-devices. The fit-file/protocol certainly has provisions to make signal strength recording possible, but again at least Garmin devices do not save such data.

Resources:
FIT -SDK https://www.thisisant.com/resources/fit/
simple tool for fit-csv conversion: http://garmin.kiesewetter.nl/

**Comment by Joern-R** [comment]
Nothing which relates to GoldenCheetah software / feature request or bug. Therefore closed.
