### ISSUE TITLE
Visual issue with Date Ranges when creating Metric Trends chart

### ISSUE THREAD

**Issue by guitartmaker** [GoldenCheetah/GoldenCheetah#2539]
I'm new to GC (but loving it!) 

In both 3.4 and 3.5(1705), when creating a metric trends chart, the date selector has visual issues (see photo). When I click and drag the window down, it resizes so that I can see and use the text.

![chart_setup](https://cloud.githubusercontent.com/assets/29206296/26803873/80cb10c4-4a0b-11e7-9105-6e9abc33e851.png)

Apologies if this has been noted previously. I'm new to GitHub... 

I'm on OSX 10.12.5 
2012 13" macbook pro (Non-retina display)

**Comment by guitartmaker** [comment]
Also seems to happen in the preferences pane in 3.5.
![preferences](https://cloud.githubusercontent.com/assets/29206296/26809495/d877bc0e-4a2a-11e7-885d-5c8b2a0d1c38.png)

**Comment by liversedge** [comment]
What is your screen resolution?

**Comment by guitartmaker** [comment]
Resolution is 1280x800.

**Comment by amtriathlon** [comment]
I can reproduce this, it happens when the dialog size is too small to fit the widget minimum sizes, just making the dialog bigger (by drag and drop on the border), fixes it.
