### ISSUE TITLE
0 elevation gain--no elevation column in the data??

### ISSUE THREAD

**Issue by Walter4000** [GoldenCheetah/GoldenCheetah#2541]
I have had a significant number of rides load in from my Garmin 1000 or files exported from virtual training, or garmin connect, show 0 for elevation gain, with no elevation column in the data so elevation correction does not help.  The data shows on the garmin 1000, starve, garmin connect, mapmyride, and virtualtraining, so I know it is in the file being loaded.

**Comment by Joern-R** [comment]
Please provide examples files - you can .ZIP them and attach here - or in case of privacy concerns send them via mail - "joern.rm  at  gmail.com" - with reference to this GitHub issue.

**Comment by Joern-R** [comment]
Files received - works with recent DEV build.

**Comment by Walter4000** [comment]
Thank you.  I will try that build and let you know if I have any further occurrences of this issue.  If you don’t hear anything further from me on this, assume the issue is solved.
