### ISSUE TITLE
GC.activity() crashes in activity R chart if specified activity has no data.frame

### ISSUE THREAD

**Issue by DougLeonard** [GoldenCheetah/GoldenCheetah#2542]
The test chart looks like this

acts=GC.activities(filter="")
activities=GC.activity(activity=acts[1])

The error is:
attempt to set index 0/0 in SET_STRING_ELT

This succeeds for rides with normal data but fails for rides with only summary data, i.e when the Edit tab is empty.  "rides" like this are legitimate as personal records and can end up in GC through batch import from strava etc.

I'd expect some kind of place holder empty data frame to be returned.

**Comment by DougLeonard** [comment]
GC build is 3962 (3.5 DEV-1705), chart is run from the activities tab.

**Comment by liversedge** [comment]
What does acts look like?
i.e. in the console type:
acts = GC.activities(filter="")
str(acts)

**Comment by liversedge** [comment]
i.e. the assign operator in R is <-

**Comment by DougLeonard** [comment]
= is also assign.  It's synonymous, has been for a long time apparently.  I know it's a little going against the R culture, but I prefer the style and it's my chart, not GC code.   

Anyway, acts looks like an array of date/times (can't cut and paste, feature rejected ;) .. understandably though).  acts[2] works.  Only rides without time-step data fail.

**Comment by DougLeonard** [comment]
ok, so it's synonymous in the context of assign, not everywhere.  <- won't work for function parameters, so synonymous isn't quite accurate, redundant is though.

**Comment by DougLeonard** [comment]
Anyway, workaround for the moment is adding 'Data contains "S"'  to the filter.  It's a workaround but as some people's data will potentially break with strange errors on other people's charts,  it is just a workaround, not a fix I think.
