### ISSUE TITLE
GC.activity() crashes about 1 in 4 times.

### ISSUE THREAD

**Issue by DougLeonard** [GoldenCheetah/GoldenCheetah#2545]
I have a suspicion this won't be easily reproducible, and thus may not be very useful information.

entire contents of R chart:

actfilt='Data contains "S"'
acts=GC.activities(filter=actfilt)
activities=GC.activity(acts[])

3.5-DEV1705

This works sometimes, but about 1 in 4 times (just switching to another chart and back to re-run it) GC crashes entirely.  It _seems_ like probably including fewer activities helps, but I haven't been able to trace it to any particular activities.  Since it works sometimes, I did try rm ing the variables involved between execution.

**Comment by DougLeonard** [comment]
For what it's worth, this is performed in the activity side (not trends, probably should be) and it's grabbing 86 rides.

**Comment by DougLeonard** [comment]
The following seems to be a workaround unless you really need all rides in memory at once:
actfilt = 'Data contains "S"'
act_ids = GC.activities(filter=actfilt)
for (i in 1:length(act_ids)) {
     act=GC.activity(act_ids[i])[[1]]
# print length of activity in seconds (or do something else useful here)
    print(act$seconds[length(act$seconds)])
}


Unlike the documented method, this does not construct an array of activity dataframes and loop through those elements.

It instead constructs an array of activity identifiers, and for each one creates a single dataframe, so only one dataframe is constructed at a time. Most importantly, it's not crashing.

**Comment by liversedge** [comment]
the assignment operator is "<-"

**Comment by liversedge** [comment]
you should also check for an empty array. Please move your queries to the developers mailing list as they are related to your R code.

https://groups.google.com/forum/#!forum/golden-cheetah-developers

**Comment by DougLeonard** [comment]
On Mon, Jun 12, 2017 at 3:37 PM, Mark Liversedge <notifications@github.com>
wrote:

> the assignment operator is "<-"
>

I don't know if you're factually confused about the validity of "=" or if
you're just trying teach me "good form".  It's one or the other.

-Doug

**Comment by DougLeonard** [comment]
I'm not a beginner at programming, and not as young as I wish.  The array isn't empty and as I said above, I can loop through each element in the array and pass it to GC.activity and everything is fine.  And even passing the whole thing works, except when it crashes.  The array was generated with a GC builtin and passed to a GC builtin. It's possible I made a mistake, maybe something that's corrupting R with every pass, but not one you've pointed out yet.  It's a pretty simple test case.

**Comment by DougLeonard** [comment]
I should have added this is all on windows, 10 to be specific.
