### ISSUE TITLE
Metrics incorrect on summary page

### ISSUE THREAD

**Issue by Chadmarriott** [GoldenCheetah/GoldenCheetah#2548]
My metrics on the Trends Summary page have recently gone crazy:

CTL:	15130978 (0 - 319511136)
ATL:	15131845 (0 - 1575476243)
TSB:	-887 (-1255965106 - 135186977)
RR:	157 (-49050793 - 319510899)
TriScore:	13981825003
TRIMP Points:	37084
TSS:	40395

On the activity summary page and in the PMC they are normal.  Any ideas?

**Comment by amtriathlon** [comment]
Please see https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md
