### ISSUE TITLE
Importing TCX file hangs on Step 4 of 4: Save to Library

### ISSUE THREAD

**Issue by russellk2017** [GoldenCheetah/GoldenCheetah#2549]
Hi
I am on Windows 10 v3.4 build id 3950. Tried to import file but simply hangs. Tried to create a manual ride but this hangs as well, which leads me to think that the file is not corrupt. This issue started today after amending some activity details (TISS, weight) for previous rides.
tks for your help
R

**Comment by russellk2017** [comment]
Have uninstalled GC and reinstalled but still have the same issue.

**Comment by Joern-R** [comment]
Please check with a recent DEV version if the problem still exists.

**Comment by Joern-R** [comment]
Assume this to be fixed by recents corrections. If it still exists in the latest DEV Version, please re-open an provide an example TCX file so that we can reproduce the problem.
