### ISSUE TITLE
TRIMP not calculated per activity; thus CTL, ATL and TSB etc graphs are blank.

### ISSUE THREAD

**Issue by PeterBullen** [GoldenCheetah/GoldenCheetah#2550]
GoldenCheetah v3.4; 64 bit

950 cycling activities recorded from 2011 to current date.

I have recently started using the Trend Graphs; those that are populated are most excellent. However the following contain no data and are essentially blank apart from the time line dated axis:
Stress (TISS)
PMC; all variations.

From the online FAQs it seems that the TRIMP Points per activity provide critical input into the above graphs. The TRIMP Points field for each of the individual activities listed also blank; whereas all power numbers, heart rate, distance etc are all OK.

I have so far:
selected View Menu-> Reset Layout; to no effect.
uninstalled and reinstalled; to no effect.

I expect that something somewhere needs to be "turned on" but alas I can't find any reference to same in the FAQs or YouTube videos.

Can you point me in the right direction.
Many thanks
Peter Bullen

**Comment by amtriathlon** [comment]
Hi Peter, this is for bug/feature tracking, please use the forum for questions: https://groups.google.com/forum/#!forum/golden-cheetah-users
All power related PMC metrics (TSS/TISS/BikeScore/etc) depends on having CP/FTP set for the date of the activity, TRIMP requires LTHR, etc. You can do these in Options/Preferrences>Athlete>Zones with the From Date predating your activities.
