### ISSUE TITLE
GC V3.4 / 3.5 Fails to Launch in Windows. Crash Report Attached.

### ISSUE THREAD

**Issue by rgeorge1985** [GoldenCheetah/GoldenCheetah#2551]
A seemingly inexplicable error has began since this morning whereby GC fails to launch. I backedup my library files and uninstalled/installed GC more than 5 times. This is happening with both the 3.4 stable build and the 3.5 dev build. On clicking on installed icon, fails to launch and a crash report is generated as follows : 

**Unhandled exception 0xc0000005
RAX=b0cfabdc10 RCX=0 RDX=b0cffcdd50 RBX=b0cd5bec38
RSP=b0cd5beb80 RBP=18 RSI=b0cffcdd50 RDI=b0d2194f60
R8=1 R9=5 R10=b0cfabd350 R11=0
R12=6e57b428 R13=6e57b370 R14=1 R15=1

GoldenCheetah.exe@0x7ff6ecdf0000!+0x47c19
GoldenCheetah.exe@0x7ff6ecdf0000!+0x41645
R.dll!GEaddDevice+0x124
R.dll!GEaddDevice2+0x8e
GoldenCheetah.exe@0x7ff6ecdf0000!+0x42536
GoldenCheetah.exe@0x7ff6ecdf0000!+0x41565
GoldenCheetah.exe@0x7ff6ecdf0000!+0x2b5c7
GoldenCheetah.exe@0x7ff6ecdf0000!+0x24b066
GoldenCheetah.exe@0x7ff6ecdf0000!+0x57e654
GoldenCheetah.exe@0x7ff6ecdf0000!+0x57dc37
KERNEL32.DLL!BaseThreadInitThunk+0x22
ntdll.dll!RtlUserThreadStart+0x34**

Please advise!

**Comment by amtriathlon** [comment]
To use R from within GC check the version of R used to build GC in the About box and install that version before to enable the integration.
