### ISSUE TITLE
Decimal separator not preserved when copy-pasting data in Edit mode

### ISSUE THREAD

**Issue by havu1977** [GoldenCheetah/GoldenCheetah#2552]
The data imported from .TCX and .FIT files is being imported using "." as the separator (I don't know if this is a feature of .TCX and .FIT). In any case when a column that has data values with "." separator is copied to another column the value is being truncated to integer i.e. the separator is lost. I believe the reason is that the separator for Finland is a comma "," instead of a dot ".". I didn't find a way to change this in GoldenCheetah.

I believe this would work if the separator would be left intact during copy-paste operations.

**Comment by havu1977** [comment]
Steps to reproduce:

1) Change your location/locale to Finland (in Windows). This will change the decimal separator to a comma","
2) Import a .FIT/.TCX file that contains columns that have decimal numbers
3) The imported data will show dot "." as the separator
4) Copy-paste one of such columns somewhere else and the value gets truncated to integer

A workaround today is to change the Windows location to US when playing with copy-paste.

**Comment by nigelvdv** [comment]
Issue still present in latest development build (June 2018).
My locale is Belgium-Dutch, so my system also uses a comma as the decimal separator.
