### ISSUE TITLE
.fit batch export fails

### ISSUE THREAD

**Issue by altuna98** [GoldenCheetah/GoldenCheetah#2556]
When I batch export activities on FIT format, exports 193 activities and then GC closes. No crash report.

Windows 10.

**Comment by Joern-R** [comment]
I just did some testing - it seems that it's not the number (I export > 500) - but manual activities with lack of data for .FIT seem not be handled properly. Will do some more testing and try to fix. For such activities also the single export fails / and "kills" GoldenCheetah.

**Comment by altuna98** [comment]
Exactly, was I ride with missing data that failed. Tested deleting that ride and works fine. Thank you
