### ISSUE TITLE
Crash when switching to Trends view

### ISSUE THREAD

**Issue by ragman1976** [GoldenCheetah/GoldenCheetah#2557]
Unhandled exception 0xc0000005
RAX=0 RCX=599ddf05 RDX=1 RBX=25a374dd648
RSP=c8252fab58 RBP=25a14d80750 RSI=0 RDI=8
R8=10 R9=58250000 R10=1 R11=0
R12=3d7f R13=0 R14=0 R15=800016702d800fef

atio6axx.dll!DrvPresentBuffers+0x16135b5
atio6axx.dll!DrvPresentBuffers+0xe3de53
atio6axx.dll!DrvPresentBuffers+0xe3ac5d
atio6axx.dll!DrvPresentBuffers+0xe2c39d
atio6axx.dll!DrvPresentBuffers+0xe1c106
atio6axx.dll!DrvPresentBuffers+0xad04c3
atio6axx.dll!DrvPresentBuffers+0xad102f
atio6axx.dll!DrvPresentBuffers+0xab5dae
atio6axx.dll!DrvPresentBuffers+0xa80240
atio6axx.dll!DrvPresentBuffers+0xa7e462
atio6axx.dll!DrvPresentBuffers+0xa15a61
atio6axx.dll!DrvPresentBuffers+0xa19c4d
atio6axx.dll!DrvPresentBuffers+0xa1c3ae
atio6axx.dll!DrvPresentBuffers+0xa28e15
atio6axx.dll!DrvPresentBuffers+0xa4f31e
atio6axx.dll!DrvPresentBuffers+0xa532aa
atio6axx.dll!DrvPresentBuffers+0x9fcf94
atio6axx.dll!DrvPresentBuffers+0x8ff21
Qt5WebEngineCore.dll!QEnableSharedFromThis<QtWebEngineCore::BrowserContextAdapter>::QEnableSharedFromThis<QtWebEngineCore::BrowserContextAdapter>+0x215136
Qt5WebEngineCore.dll!QEnableSharedFromThis<QtWebEngineCore::BrowserContextAdapter>::QEnableSharedFromThis<QtWebEngineCore::BrowserContextAdapter>+0x2477e1
Qt5WebEngineCore.dll!QtWebEngineCore::BrowserContextAdapter::isOffTheRecord+0x118af
Qt5WebEngineCore.dll!QtWebEngineCore::BrowserContextAdapter::isOffTheRecord+0x108f6
Qt5WebEngineCore.dll!QtWebEngineCore::BrowserContextAdapter::isOffTheRecord+0xa027
Qt5WebEngineCore.dll!QtWebEngineCore::BrowserContextAdapter::isOffTheRecord+0xba67
Qt5WebEngineCore.dll!QtWebEngineCore::BrowserContextAdapter::isOffTheRecord+0x84ca
Qt5WebEngineCore.dll!QtWebEngineCore::BrowserContextAdapter::isOffTheRecord+0xb8a8
Qt5WebEngineCore.dll!QtWebEngineCore::BrowserContextAdapter::isOffTheRecord+0xb1d2
Qt5WebEngineCore.dll!QtWebEngineCore::BrowserContextAdapter::isOffTheRecord+0xb156
Qt5WebEngineCore.dll!QtWebEngineCore::BrowserContextAdapter::isOffTheRecord+0xdf0f
Qt5WebEngineCore.dll!GetHandleVerifier+0x7bbc
Qt5WebEngineCore.dll!QtWebEngineCore::FilePickerController::qt_static_metacall+0x2873e9
Qt5WebEngineCore.dll!QtWebEngineCore::FilePickerController::qt_static_metacall+0x286a53
Qt5WebEngineCore.dll!GetHandleVerifier+0x9ff6
Qt5WebEngineCore.dll!QtWebEngineCore::FilePickerController::qt_static_metacall+0x29338e
Qt5WebEngineCore.dll!QtWebEngineCore::WebContentsAdapter::d_func+0xb76
Qt5WebEngineCore.dll!QtWebEngineCore::WebContentsAdapter::d_func+0x1080
Qt5WebEngineCore.dll!QtWebEngineCore::FilePickerController::qt_static_metacall+0x26d52a
KERNEL32.DLL!BaseThreadInitThunk+0x14
ntdll.dll!RtlUserThreadStart+0x21

**Comment by liversedge** [comment]
Which version are you using?

**Comment by ragman1976** [comment]
OS: WIN10
GC: Version 3.5 Development Build 1705

**Comment by amtriathlon** [comment]
If you can reproduce this on the last development build please comment on the corresponding thread at the users forum: https://groups.google.com/d/msg/golden-cheetah-users/CiwAwufvQRA/m7O1UgN-AAAJ
