### ISSUE TITLE
Problem with fit and gpx files

### ISSUE THREAD

**Issue by vagrale13** [GoldenCheetah/GoldenCheetah#2559]
I have problem with fit and gpx files.
My device is _Bryton Rider 310_ and save the routes in .fit files.
When i import .fit file the Duration, Time Moving and some others are not correct. Also the Map tab is empty. When i upload the .fit file to strava, everything is ok.
When i download .gpx file from strava, everything are ok except the laps. Goldencheetah doesn't show the laps. 

_- Linux Mint 18.1 32bit_ 
_- GoldenCheetah_V3.4_Qt5.5.1_

**Comment by amtriathlon** [comment]
The problem importing Bryton generated FIT files is a known issue: https://github.com/GoldenCheetah/GoldenCheetah/issues/2029 and GPX files don't support laps nor power data, but you can export TCX files from Strava which shouldn't have these limitations, see https://support.strava.com/hc/en-us/articles/216918437-Exporting-your-Data-and-Bulk-Export#TCX

**Comment by vagrale13** [comment]
Thanks amtriathlon. With _.tcx_ files everything are ok.
