### ISSUE TITLE
Custom Metrics: name does not update

### ISSUE THREAD

**Issue by pavelkroupa** [GoldenCheetah/GoldenCheetah#2570]
Hello, I created a Custom Metric: "My_avg_Slope"
The I added this Metric to Intervals overview.
When I update/ rename a "Symbol" or the "Name" of this metric, it is NOT saved.

Would be nice to add a "Average Slope" standard metric.

Thanks for help

**Comment by liversedge** [comment]
The metric is saved when you press save in options.

**Comment by pavelkroupa** [comment]
I tried couple of times, but even when I press the Save button and restart the program, nothing is saved.
I am using Windows 7 64 bit

**Comment by amtriathlon** [comment]
Change something in the formula, besides Symbol/Name, and it will be saved when you press the Save button.

**Comment by pavelkroupa** [comment]
Thanks for help. It works :)
