### ISSUE TITLE
Problem install on ubuntu 17.04

### ISSUE THREAD

**Issue by zaogta** [GoldenCheetah/GoldenCheetah#2571]
can't install GoldenCheetah_V3.4_Qt5.5.1_amd64.deb on Ubuntu Mate 17.04
Fehler: Abhängigkeit nicht erfüllbar: libgstreamer0.10-0
Error: Dependency can not be fulfilled: libgstreamer0.10-0

**Comment by amtriathlon** [comment]
You should search for and install manually this dependency and then retry V3.4 installation, this happens since 17.04 is newer than V3.4, it should be fixed for v3.5.

**Comment by amtriathlon** [comment]
Have you tried to install the last development build?
https://github.com/GoldenCheetah/GoldenCheetah/releases

**Comment by zaogta** [comment]
After installing the libgstreamer0.10-0, it worked "Not nice".
