### ISSUE TITLE
Using OpenStreetMap requires API Key

### ISSUE THREAD

**Issue by naclander** [GoldenCheetah/GoldenCheetah#2572]
When viewing the map using OpenStreetMap ( OpenCycleMap, actually ) I see a water mark at every tile saying "API Key Required". 

I think GoldenCheetah should have an API key already no? Otherwise it should be made clear to the user how to aquire an API key themselves ( maybe at the menu selecting the Map type ).

P.S. Thanks for the effort put into the project so far.

**Comment by liversedge** [comment]
You need to register for your own api key if you are building your own. We don't share any of the GC client keys publically since they are private to the official builds.

**Comment by naclander** [comment]
@liversedge thanks. Maybe adding a tip about this in GC would prevent future users from thinking this is a bug.
