### ISSUE TITLE
Crash v3.5 when hovering on new Window/new Tab menu

### ISSUE THREAD

**Issue by podiumbound** [GoldenCheetah/GoldenCheetah#2576]
I've encountered a crash with v3.5 on a computer whose GC athlete folder is in dropbox. What's somewhat unique is that it's a macbook air with a pretty full hard drive, so the user has moved the dropbox to a permanently installed, high-capacity SD card. I don't know if this is part of the problem or not, since v3.4 seems to work fine in this configuration. 

GC crashes specifically when it's about to load the list of athletes when the user hovers over the new window/new tab menu options. Crash log attached.

[crashlog.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/1178427/crashlog.txt)

**Comment by amtriathlon** [comment]
If you can reproduce this on the last development build please comment on the corresponding thread at the users forum: https://groups.google.com/d/msg/golden-cheetah-users/CiwAwufvQRA/m7O1UgN-AAAJ
