### ISSUE TITLE
Options>Athlete >Measurements - Column headings are wrong

### ISSUE THREAD

**Issue by Casakari** [GoldenCheetah/GoldenCheetah#2577]
After tracking 8 measurement sets, I realized that the columns are off. It look like an extra Time column is in there which is shifting the headers to the right.

Build 3962
Version 3.5-DEV1705

**Comment by amtriathlon** [comment]
It is already fixed in master but not included in that build, see https://github.com/GoldenCheetah/GoldenCheetah/commit/c867299378ea809b54f4209eeee225d4b357ade3
