### ISSUE TITLE
TCX Export: GC Intervals to Laps in TCX

### ISSUE THREAD

**Issue by EagleEye666666** [GoldenCheetah/GoldenCheetah#2579]
Hi there,
It would be nice if the Intervals of GC could be exported as proper Laps in the TCX file export. It's quite annoying if your interval/lap data is missing in Strava.
I have checked the code and saw that you sync/upload Strava in TCX format. I have tested also manual export to TCX format to confirm missing intervals > laps.

Maybe I will try to implement that on my own.

GC v3.5-DEV1705X

**Comment by amtriathlon** [comment]
This has been discussed before and rejected due to restrictions of TCX format, see https://github.com/GoldenCheetah/GoldenCheetah/issues/576, the Strava issue (https://github.com/GoldenCheetah/GoldenCheetah/issues/2505) is pending and probably could be solved uploading FIT instead of TCX files

**Comment by EagleEye666666** [comment]
I did some researches before I posted, keywords Strava and also TCX. I must have missed that one. Yeah I thought so as well that using FIT file format for sync with Strava might solve the issue.
Sorry for wasting your time!

**Comment by EagleEye666666** [comment]
I have checked several exports of GC. Any exported file provide the lap data, also the FIT not. Furthermore any of that files can be manually imported to garmin connect. 
File size of the exported TCX is crazy. 2 hour ride more than 5 MB? But when using the strava upload function the window claims size of 245 kb... if that uses TCX it's strange. Has the export / export batch other code for export of the GC data? I find it hard to check that on my own.
FIT file is so small that it looks suspicious and only strava can handle these GC exported file, but there is no lap data.
Well and that's it, there is no other useful format for export from GC and manual import to other platforms. Do you plan GPX file support in the future?
