### ISSUE TITLE
Wrong average kph

### ISSUE THREAD

**Issue by romewasntbuiltonaday** [GoldenCheetah/GoldenCheetah#2580]
I see average kph above 100 kph which is impossible for me to sustain such an effort. I'm using the 3.5 1705 version. The imports are from Strava.

Please fix this error.

Best regards,
Roman

**Comment by liversedge** [comment]
Check the data in the editor, click on anomalies. Then fix the errant data.

**Comment by romewasntbuiltonaday** [comment]
Hello,

I've found the problem with the unrealistic max kph. The problem is the 
Strava import.
When I import the fit files directly, then it works .

Best regards,
Roman

**Comment by amtriathlon** [comment]
This is likely due to Smart Recording in the original file producing gaps in recording, the last development build expands Smart Recording in the same way as importing the original fit file: https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/v3.5-DEV1710
