### ISSUE TITLE
Crash on start up Mac OS

### ISSUE THREAD

**Issue by Sloggi-1** [GoldenCheetah/GoldenCheetah#2582]
All 64Bit versions of GC crash on start up with Mac OS 10.12.6. The last universal build functions flawlessly. For the crash it doesn't matter if there exists an athlete directory or not. The crash happens after a completely virgin install. Attached is the Mac crash log. Help would be greatly appreciated.

[GC_crash_report.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/1188967/GC_crash_report.txt)

**Comment by cipriancaba** [comment]
I can confirm the problem on MacOS 10.12.6 .. This probably started happening after I installed R on system level and checked some stuff in the options regarding R library.. Bad idea.. tried uninstalling, removing all files and folders related to app, but it's still not working
Still happening with the August release
[crash_golden_cheetah.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/1202405/crash_golden_cheetah.txt)

**Comment by cipriancaba** [comment]
I can confirm that uninstalling R library fixes the issue.. it warned me that it was disabled in options and starts successfully after

**Comment by liversedge** [comment]
The 1708 dev build fixed this.

**Comment by cipriancaba** [comment]
Well, this happened to me on build 1708 as well.. Only after completely removing R library as per https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Uninstalling-under-macOS the app started working again

**Comment by liversedge** [comment]
Can you please provied the crash log for 1708

**Comment by cipriancaba** [comment]
Sure, it's in my first post https://github.com/GoldenCheetah/GoldenCheetah/files/1202405/crash_golden_cheetah.txt

**Comment by liversedge** [comment]
The MacOS binary 1708 was published yesterday, your first post is from 5 days ago.

**Comment by cipriancaba** [comment]
I'm not the OP

**Comment by Sloggi-1** [comment]
The original problem still persists with build 1708 and is independent of whether R is installed or not. Here is the new crash report.

[Crash Report Mac OS 1708.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/1205033/Crash.Report.Mac.OS.1708.txt)

**Comment by amtriathlon** [comment]
Which R version are you using?
I had a similar problem on Linux using 1708 with an older version of R which was solved upgrading to R 3.4.1

**Comment by Sloggi-1** [comment]
R wasn't even installed on the Mac when the problem first arose. Installing the latest version of R and removing it again has made no difference either.
