### ISSUE TITLE
Feature Request: Custom name for uploaded activities

### ISSUE THREAD

**Issue by freekode** [GoldenCheetah/GoldenCheetah#2583]
I would like to have ability to upload activities with custom name.
e.g: `$field.startDate [$field.sport] "$field.myCustomField"`
will be translated to `06-05-2017 17:18:23 Swim "I like it"`

**Comment by amtriathlon** [comment]
Have you tried using "Calendar Text" for name and checking the Diary option for the custom field(s) you want to include?

**Comment by freekode** [comment]
Sorry, my fault, wrote wrong description.
