### ISSUE TITLE
Feature Request: Custom name for uploaded activities during synchronisation.

### ISSUE THREAD

**Issue by freekode** [GoldenCheetah/GoldenCheetah#2585]
When I upload activities to Strava (or another external service) I would like to have ability to upload activities with custom name.
e.g: $field.startDate [$field.sport] "$field.myCustomField"
will be translated to 06-05-2017 17:18:23 Swim "I like it"

Now when I upload activity from GoldenCheetah to Strava I have just start date.

**Comment by amtriathlon** [comment]
In the last development build (https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/v3.5-DEV1705X) you can select which field to use as name in Strava:
![strava](https://user-images.githubusercontent.com/1444784/28829289-9e1a3a04-76a9-11e7-852a-80fa718c19b0.png)
You can choose any text field, including Calendar Text which can be further customized using the Diary setting.
