### ISSUE TITLE
can't access USB ant+ device on osx

### ISSUE THREAD

**Issue by ssalenik** [GoldenCheetah/GoldenCheetah#2591]
Using Mac OSX 10.12.5; tried with GC 3.4 and DEV-V3.5 1708

heres the console log on v3.5 when trying to pair devices:

> antlog path: "/var/folders/9g/dclyp36d717_6zppr8tfygsc0000gn/T/antlog.raw"
> Found a Garmin USB2 ANT+ stick: "/dev/bus/usb/001/017-0fcf-1008-00-00"
> usb_set_configuration Error:  usb_set_configuration(SetConfiguration): device not opened for exclusive access
> ANT device reset was not acknowledged !...try again
> ANT device reset was not acknowledged !...try again
> ANT device reset was not acknowledged !...try again
> ANT device reset was not acknowledged !...try again
> ANT+ reset not acknowledged, closing..

Note that the UI stays on the pairing page "searching" for devices. Would probably be good if the UI indicated when USB setup failed.

**Comment by ssalenik** [comment]
FYI, I just tried it on ubuntu 16.10 running on VirtualBox on the same osx machine and it didn't work either... so don't know if its an issue with the mac host or with my usb device. Its one of these:
https://www.amazon.ca/gp/product/B00KNQG7RQ/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

**Comment by liversedge** [comment]
Disable garmin ant agent to get access to the USB stick.

**Comment by ssalenik** [comment]
Ah thanks! It was Garmin Express that I had to kill... not sure why it needs access to my ant+ stick...
