### ISSUE TITLE
Menu bar failure

### ISSUE THREAD

**Issue by Haas01** [GoldenCheetah/GoldenCheetah#2592]
In version 3.5 the menu bar disappears switching between trends, diary and activities. F11 (full screen) solves the problem. The mistake appears only under Windows 10 and 4K resolution.

**Comment by liversedge** [comment]
The diary is in tile mode so doesn't have a menu bar.

**Comment by Haas01** [comment]
Mark,
  
  I did not mean the menu of the diary, it's the main menu that disappears. Better said: it is overlaid optically and&nbsp;the single menus are selectable by the cursor.
  
  Greetings
  
  Michael
  
  
  ____________________________________________
  Michael Haas, Prof Dr Med, DMD
  Medical University of Graz, School of Dental Medicine
  Billrothgasse 4, 8036 Graz, Austria
  m-haas@m-haas.at
  
  
  &nbsp; 
---- GoldenCheetah/GoldenCheetah schrieb ----
  &nbsp; >

**Comment by liversedge** [comment]
Can you provide a screenshot? (you can drag and drop into the comments here).
I have installed and run the dev build on Windows 10 with a 4k display (DELL XPS) and it seems ok to me.

**Comment by Haas01** [comment]
![image](https://user-images.githubusercontent.com/17576350/29030646-13c90104-7b8c-11e7-9260-e3fc29c2b80f.png)
I have a Dell Precision 7710 notebook. No main menu, the double view of the activity menu and further problems to show the zones in the CP. Maybe there is a problem in my graphic driver.

**Comment by Haas01** [comment]
I could find the problem. It was a new version of the Intel (R) HD Graphics 350 driver. Interestingly the mistake appeared only in GC.
Thank you

**Comment by liversedge** [comment]
Blimey! Thanks for updating the issue.
