### ISSUE TITLE
Notes empty on Today's Plan when upload activity

### ISSUE THREAD

**Issue by freekode** [GoldenCheetah/GoldenCheetah#2595]
When I upload activity from GoldenCheetah to Today's Plant, my notes are empty on Today's Plant website. Instead my notes show as title of activity.
Still fields like RPE, TQR properly filled.
So I think better to set activity name as Workout Code, and notes writes on proper place

**Comment by Joern-R** [comment]
Besides RPE,... we are not explicitely settings any field on Today's Plan. TP's upload and download API uses the GoldenCheetah JSON format. So we are providing the full file for the upload. The interpretation which field on Today's Plan with which field in GoldenCheetah happens in Today's Plan. So nothing we can change/improve here from our side. Therefore closed.
