### ISSUE TITLE
"Error - Unknow file type" importing tcx (DEV1708)

### ISSUE THREAD

**Issue by ecanuriag** [GoldenCheetah/GoldenCheetah#2596]
In DEV1708 I am having problems importing tcx files generated with TCXCreator a tool which merge both, hrm and gpx files into a tcx. With previous DEV version was working fine. Other tcx from other sources are working. I am attaching a sample file.

[17080801_HRMGPX_2017.08.08_15-45-18.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1217638/17080801_HRMGPX_2017.08.08_15-45-18.zip)

**Comment by amtriathlon** [comment]
There was 2 changes to TcxParser from the last dev built included in this PR https://github.com/GoldenCheetah/GoldenCheetah/pull/2562, but reverting them doesn't seem to fix this issue...
BTW, if you import the hrm file and there is a gpx with the same name in the folder GC should merge them automatically.

**Comment by amtriathlon** [comment]
The problem is not with tcx files in particular but the presence of "." in the file name in general: the string after the "." is taken as suffix in RideImportWizzard, "08_15-45-18.tcx" in this case, and it doen't match "tcx" nor any other file type extension. Renaming the file avoids the issue.

**Comment by ecanuriag** [comment]
Thanks, I will try it as soon as I can
