### ISSUE TITLE
Run Power Data Imported Incorrectly

### ISSUE THREAD

**Issue by lazy-pete** [GoldenCheetah/GoldenCheetah#2597]
Hi, I've been using the 'estimate run power' function which seems to work well. Recently I started using a Connect iq data field which estimates run power in real time on my Garmin Edge 820 (which i use in bike mode running, then convert activity to run manually) which seems to do a good job. The data it displays is recorded correctly in the FIT file, and displayed in Garmin connect, however when I import the file into Golden Cheetah the power figures are vastly reduced - 16W Avg / 19W Max instead of 232.1 Avg / 292.4 Max.

When I tried to use the estimate run power to override and replace the faulty data nothing happened. 

Is there something I can do to fix this ?

**Comment by lazy-pete** [comment]
Actually worked out that what seems to be happening is the temperature data is being displayed as power in Golden Cheetah, for some reason, with no power data imported at all.

**Comment by amtriathlon** [comment]
For any kind of debugging on the import part we would need a sample file.

>When I tried to use the estimate run power to override and replace the faulty data nothing happened.

Estimate Run Power does nothing when Power data is present or the activity is not a Run, if you want to discard the existing Power data you must do that first at the Editor.

**Comment by lazy-pete** [comment]
i don't seem to be able to upload a copy of he original FIT file ?

**Comment by amtriathlon** [comment]
Compressing will do the trick https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by lazy-pete** [comment]
[2017-08-08-09-15-59.fit.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1219795/2017-08-08-09-15-59.fit.zip)
thanks

**Comment by amtriathlon** [comment]
This file doesn't show power when imported to Garmin Connect or Strava, it is likely a problem with the originating App, may be a newer version fixes it.
