### ISSUE TITLE
Chart scale not remmbered

### ISSUE THREAD

**Issue by pavelkroupa** [GoldenCheetah/GoldenCheetah#2600]
I always adjust the charts to see Heart rate: 105-180 BPM, and cadence from 65-105.
When I switch to different chart or different activity, I have to re-adjust all scales.Would be nice to add some sort of checkbox to fix the current scale.
Or is there some other work around?
Thanks,
Pavel

**Comment by amtriathlon** [comment]
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/2044
