### ISSUE TITLE
Strava Sync

### ISSUE THREAD

**Issue by Dicval** [GoldenCheetah/GoldenCheetah#2601]
I have problems with STRAVA and GC sync. It looks like it's sync as you can see in the attached picture, but it doesn't works. No files sync with GC. Can anyone tell me what can I do?

![strava sync](https://user-images.githubusercontent.com/31159041/29486528-38ff51b6-84e8-11e7-851a-e79d0ad7030f.png)

**Comment by amtriathlon** [comment]
This is a bug&feature tracking system, please use the [forum](https://groups.google.com/forum/#!forum/golden-cheetah-users) for usage questions.
