### ISSUE TITLE
Multiple power zones for multiple bikes

### ISSUE THREAD

**Issue by AdamMuz** [GoldenCheetah/GoldenCheetah#2603]
It is a common thing that there are power differences put by the same rider on TT bike vs Road bike.
Multiple sets of power definitions ( FTP, CP, W'Bal) would solve the problem. 
In such case there should be a possibility to define the set of power parameters for each ride during the download

**Comment by amtriathlon** [comment]
Multiple power zones have been proposed before and rejected, see the wiki: https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-METRICS#can-i-set-a-different-cpftp-for-different-reasons-eg-cpftp-on-a-trainer-.
It is possible to automate the CP/FTP/etc. override a data field indicates the use of TT bike, Trainer, etc. using defaults, see https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Preferences_Data-Fields#defaults
