### ISSUE TITLE
Strava Sync doesn't handle Garmin Smart Recording nor Lap Swims

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#2605]
Activities downloaded from Strava via the new Sync in current 3.5 master which were recorded using Garmin Smart Recording have gaps, this is particularly notable on running using devices were Smart Recording cannot be disable, this can be fixed using fix gaps but probably we should do the expansion like when direct import.
Lap Swims also need expansion and Fix Gaps doesn't work so well in this case since some of necessary information comes with lap records.

**Comment by victorcerezuela** [comment]
I have this problem but i cant fix with fix gaps, it also happened with running. In the image you can see that movement time isn't the real one.
Hope i can find a solution
![captura de pantalla 2017-09-09 a las 21 34 58](https://user-images.githubusercontent.com/11005286/30243294-c6a6ce94-95a6-11e7-865f-d038b994e8d9.png)

**Comment by amtriathlon** [comment]
As I commented before Fix Gaps doesn't work for lap swimming files, with proper parameters it can be used to fix running and open water activities.

**Comment by victorcerezuela** [comment]
And which are those parameters?, the picture I send is in open water swimming but i couldnt fix.
So many thanks.

**Comment by amtriathlon** [comment]
It is explained at the wiki: https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-RUNNING-&-SWIMMING#how-to-fix-runs-and-swims

**Comment by victorcerezuela** [comment]
Leí detenidamente el post pero me ha sido imposible arreglarlo, tanto en carrera como en natación me da valores erróneos ;(

**Comment by amtriathlon** [comment]
Para consultas está el foro de usuarios (https://groups.google.com/forum/#!forum/golden-cheetah-users), este es un sistema de seguimiento de errores y nuevas funciones.
