### ISSUE TITLE
Feature Request : 'Sub-Filter' by Workout Code

### ISSUE THREAD

**Issue by rgeorge1985** [GoldenCheetah/GoldenCheetah#2610]
A kind request for a sub-filter by user-defined workout codes for a sport such that graph data and tabular data only show activities related to workout code within a given sport.

Example :  During a week, individual wants to filter only those runs that have the workout code 'RunIntervals' or maybe just indoor runs with the workout code 'Treadmill'. 

What is the coding complexity to expanding and making filtering more powerful?

**Comment by amtriathlon** [comment]
Why not to use combined queries for that purpose?

**Comment by rgeorge1985** [comment]
How would it work for the particular example I posted using a workout code?

**Comment by amtriathlon** [comment]
You can use a combined filter s.t. `Sport="Run" AND Workout_Code="Intervals"`
Filters are very powerful, you can find a complete explanation at the wiki(https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_SearchFilter), a tutorial on the main site (http://www.goldencheetah.org/#section-tutorials) and to use the forum for questions.
