### ISSUE TITLE
3D charts not working

### ISSUE THREAD

**Issue by jackendrick** [GoldenCheetah/GoldenCheetah#2611]
Hi,

I am using v3.4 on a OSx 10.12.6. When trying to create a 3D chart the window opens but shows nothing other than the 'more' tab. A screenshot is attached. I have tried this with different activites.

Are there any troubleshooting steps to try?
![snip20170901_3](https://user-images.githubusercontent.com/15262220/29983005-35712026-8f54-11e7-9c8b-39d15a4d0125.png)

Thanks in advance
James

**Comment by arnean** [comment]
I have similar problem, but under Windows 7. I'm using GC 3.5-DEV1710. Most of the time 3D plot window is empty just like shown by jackendrick, but sometimes it contains bits and pieces from other window. I've added screenshot to show this. My graphics card is Intel HD 3000 - nothing special. No problems in other programs. I tried to find some switches or environment variables to turn of the 3D acceleration but didn't find any.


![image](https://user-images.githubusercontent.com/34253696/33579766-85824880-d953-11e7-8e3f-6909e7a1bcc0.png)

**Comment by arnean** [comment]
I did some more search and found this page:

https://bugreports.qt.io/browse/QTBUG-42240

I looked for Qt source code and apparently my graphics card is blacklisted:

https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/windows/openglblacklists/default.json?h=5.9

There are some environment variables that are supposed to control this behaviour (e.g. QT_OPENGL_BUGLIST, QT_OPENGL, ...) did not seem to have any effect - what am I missing here?

**Comment by arnean** [comment]
One more thing - I tried to debug the OpenGL stack as described here:

http://blog.qt.io/blog/2017/01/18/opengl-implementation-qt-quick-app-using-today/

But the environment variables did not have any effect.

**Comment by arnean** [comment]
In my case 

 set QT_OPENGL=desktop

before launching the Golden Cheetah from command line helped. Without this variable Qt is doing OpenGL version autodetection and for some reason the Intel HD3000 specific version was not good enough, then it tried some other options, but apparently those were not also good enough.

**Comment by liversedge** [comment]
the 3d lib we use is no longer supported on OSX, so we cannot build this chart any more.
