### ISSUE TITLE
V3.5 1708 can't conncet to ANT+ devices on OSX

### ISSUE THREAD

**Issue by mondoshiwan** [GoldenCheetah/GoldenCheetah#2618]
i'm using 10.10 and the siliconlab driver with an old Garmin USB stick. If opening the assistent for a new device the usb stick seemed to be detected, cause i right got to the search window, once ANT+ is selected. But then it won't find any device. No Heartrate or other sensors.

could do a check on 10.12 next week

GC V3.4 is finding all sensors right the way.

**Comment by tjdunnigan** [comment]
I am using 10.12 with a Suunto usb device and am able to detect and connect to heart rate and Tacx trainer sensors.

**Comment by mondoshiwan** [comment]
10.12 on a MacMini isn't working for me either - same old Garmin Stick. The stick is found, but GC won't connect to any sensors.

**Comment by marcelrufino** [comment]
Try to close Gamin Express app and Garmin Express Service (icon on toolbar).

**Comment by mondoshiwan** [comment]
Garmins ANT Agent isn't running and i don't have Garmin Express installed…

**Comment by mondoshiwan** [comment]
the problem is the older ANT+ stick… bought myself the *new* gen smaller one, in this case the Suunto stick, and it works now flawlessly.

**Comment by Joern-R** [comment]
Hardware problem / older ANT+ stick.
