### ISSUE TITLE
Events is not appearing on Phases Metric Trends Chart's

### ISSUE THREAD

**Issue by marcelrufino** [GoldenCheetah/GoldenCheetah#2620]
When you create Phases from an Event, only the first Phases shows Events on a Metric Trends Chart. Any one above it does not show the events on the chart.

**Comment by qheath** [comment]
Before #2826, seasons were only selected if they started during the phase (e.g. the phase is the first of the season and starts at the same time).

#2826 was only a partial fix, as it added seasons that ends during the phase (e.g. the phase is the last of the season and ends at the same time).

This still skips seasons that start before and end after the phase (e.g. the phase belongs to the season, and is neither the first nor the last).
