### ISSUE TITLE
Improve Charts Data Range "to Today" + Number (days/weeks/months/years)

### ISSUE THREAD

**Issue by marcelrufino** [GoldenCheetah/GoldenCheetah#2621]
At Data Rage Field on Chart Setup window - Basic TAB:

Add two fields after options that has "today": (integer) + combo (days/weeks/months/years).

ie.: Current selection thru today + 1 month.

**Comment by Joern-R** [comment]
Can you please explain the use-case for this. Since GC (so far) has not planning component, there is no future data (only actual activities) - so what's the need/reason to such future periods?

**Comment by Joern-R** [comment]
Unclear use-case. Closed.
