### ISSUE TITLE
Can´t see all my data in GoldenCheetah v.3.4 and v.3.5

### ISSUE THREAD

**Issue by bernbutt** [GoldenCheetah/GoldenCheetah#2623]
Started up on new pc, Win10Pro-64bit, with V.3.4 and importet all my data from GarminEdge520 2017.
When I look at activities-Summary - I can see all my activities, 31/3-to day.
In Trends summery - I can see data from every month.
Trends Trucker - all data.
Trends Stress - 17/7 - to today. I don´t understand this!
Trends PMC - 16/7 - to today. I don´t understand this!
Trends cpHistory - all data.
Trends Aerobic Power - 27/3 - to today.
Trends Anarobic Power - 27/3 - to today.
Trends Libary - 17/7 - to day. I don´t understand this!
Diary - 31/3 - to day.
Chart settings is: 2016 - to today.
It is same problems in V3.5!
What can I do - so I can se all my data?

**Comment by amtriathlon** [comment]
This is for bugs&features tracking, please see the [wiki](https://github.com/GoldenCheetah/GoldenCheetah/wiki) and use the [forum](https://groups.google.com/forum/#!forum/golden-cheetah-users) for help.
