### ISSUE TITLE
Run Power - No TSS

### ISSUE THREAD

**Issue by Simontri** [GoldenCheetah/GoldenCheetah#2624]
I have a problem with run power. 
As i import data via a Garmin watch from a Stryd food powermeter, no TSS is shown. I have set up my CP etc. For bike data it works fine, but with run data i don´t get any TSS.
Therefore the graphs in "trends" PMC (coggan) don´t add my runs as well... 

Sorry for my bad english and I hope fore help
Simon

**Comment by amtriathlon** [comment]
This is for bugs&features tracking, please see the [wiki](https://github.com/GoldenCheetah/GoldenCheetah/wiki) and use the [forum](https://groups.google.com/forum/#!forum/golden-cheetah-users) for help.
