### ISSUE TITLE
Feature request: Critical Power vs Benchmark 

### ISSUE THREAD

**Issue by borriej** [GoldenCheetah/GoldenCheetah#2625]
Using this benchmark W/kg per category:
http://home.trainingpeaks.com/getmedia/a4f43215-cd08-4a58-93b8-b9c8801727fa/PowerProfile

Can we make a feature that plots our Critical Power into Categories?
Someting like:
https://wpassets.trainingpeaks.com/wp-content/uploads/2017/01/12200052/Power-Profile.pngwidth700height394ext.png

So I can easily see how I - as a rider - compare to the benchmark.

Idea: Maybe on the tab 'trends' > 'summary' .. we already have athletes best, maybe we can add a diagram below it.

Thank you developers for this program!

**Comment by amtriathlon** [comment]
Trends > Summary is already pretty complicated and may be copyright issues involved, but it is possible to add this as an R Chart, look at this example at the forum: https://groups.google.com/forum/#!topic/golden-cheetah-users/rTx5_aKg0_Y

**Comment by amtriathlon** [comment]
I'm closing this since this feature request can be fulfilled using existing charting facilities, there is an even more complete version available for download from the cloud.
