### ISSUE TITLE
Ant+ device cannot simultaneously detect HR monitor & Power meter

### ISSUE THREAD

**Issue by darny** [GoldenCheetah/GoldenCheetah#2629]
Good day. GC newbie here. 

I successfully paired my **CycleOps PowerTap** & **Garmin Heart Rate monitor** in GC following this [**video tutorial**](https://vimeo.com/151291424). It even showed the Ant+ IDs of both devices during the pairing. However, when I tried to record a workout (clicked the Play button), it only detected my HR monitor but not the power meter. I clicked the On & Off button in the **Intensity Adjustments and Workout Control** until it's green and 90% of the time it only detected my HR monitor and 10% my Power meter - but never both.

I consulted the [**UserGuide on adding devices**](https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Preferences_Train-Devices) but it said that _**... still a work in progress - more details to be added ...**_ 

Appreciate the help.

**Randy**

<hr/>

Specs: 
- Win 7 Pro - 64 bit
- GC v3.4 ([detailed **About** screenshot](https://i.imgur.com/ke1a8GO.png))
- Trainer - [Minoura M70-R Magnetic Trainer](https://www.rei.com/product/793632/minoura-m70-r-magnetic-trainer)
- Ant USB Stick: Silicon Labs Software 
- Driver version: 3.1.0.0
<hr/>

**Comment by amtriathlon** [comment]
Hi Randy, this is for bugs&features tracking, please use the user forum for help: https://groups.google.com/forum/#!forum/golden-cheetah-users
