### ISSUE TITLE
[Old 54] Export courses to gps device 

### ISSUE THREAD

**Issue by grauser** [GoldenCheetah/GoldenCheetah#263]
Added by Julian Baumgartner over 2 years ago. Updated over 1 year ago.
## Description

Currently Garmin head units can receive routes/courses from Garmin Training Center that can be used for navigation/training. A user can go to a website like MapMyRide and create (or locate and existing) route and export it to .crs format. That file can then be imported into Garmin Training Center and sent to the device (300, 500, 705, etc...)

Similar to the "Maps" tab which is an embedded webpage, perhaps a MapMyRide or gmaps-pedometer, google maps page or custom GC page could be embedded that would allow the creation of a route and export to a connected device... This would help bypass extra steps and make GC well, ROCK! ;)

Related issues
## History
- 1) Updated by Mark Liversedge over 1 year ago
  Target version set to 3.1

**Comment by amtriathlon** [comment]
Garmin ecosystem has got better and it is very easy to create routes and transfer to devices using Garmin Connect Mobile, I think it doesn't make too much sense to add this feature to GoldenCheetah now.
