### ISSUE TITLE
Kurt Kinetic trainer 

### ISSUE THREAD

**Issue by rlquinlan** [GoldenCheetah/GoldenCheetah#2634]
how do I import CSV file format from Kurt Kinetic trainer? When I do it currently a 13 mile ride shows as a 85 mile ride and many parameters are incorrect.
Is it user error? or do I need to modify the csv format?

**Comment by Joern-R** [comment]
There a plenty of CSV formats from different sources. Checking the code I can't find a specific implementation for Kurt Kinetic trainers. According to the Kinetic documentation you can also export as FIT file - which is supported and should work.

**Comment by rlquinlan** [comment]
Thanks Joel!
I had been exporting as a csv, and did not see the .fit capability.

Thanks!..
We love the trainer!!!
