### ISSUE TITLE
Possible memory leak: interval creation

### ISSUE THREAD

**Issue by nicolasschmidt** [GoldenCheetah/GoldenCheetah#2635]
![screen shot 2017-09-26 at 2 08 07 pm](https://user-images.githubusercontent.com/1957039/30921890-9698829c-a375-11e7-8b05-0d6ac2f4967a.png)

When creating intervals, the RAM usage goes up really fast. Changing activity does not free the memory. Saving the activity does not free the memory. If GC app is closed then reopen, you can see the new intervals (Selection#1, Selection#2, etc...) and the RAM usage is low (normal). Creating new intervals at this point recreate the problem.

Tested on a Mac with 3.4 and also with 3.5 (build 1708)

**Comment by amtriathlon** [comment]
Once an activity is viewed or edited it will remain in memory until GC is closed.
See https://github.com/GoldenCheetah/GoldenCheetah/wiki/GoldenCheetah-memory-consumption-and-recommendations
