### ISSUE TITLE
Video Player black in V3.5 under macOS High Sierra

### ISSUE THREAD

**Issue by RolandGo** [GoldenCheetah/GoldenCheetah#2637]
Starting a workout in the most recent V3.5, the Video Player plays the sound of the video (MP4 format), but no picture is shown. Furthermore, imported videos are only shown in the left sidebar after a restart of the app.

Video playback works with V3.4, but only when not using the Robot as the device.

**Comment by amtriathlon** [comment]
This is a known problem, see https://github.com/GoldenCheetah/GoldenCheetah/issues/2242
