### ISSUE TITLE
Dropbox sync failure

### ISSUE THREAD

**Issue by drnovsek** [GoldenCheetah/GoldenCheetah#2640]
Hi, it seems that Dropbox sync stopped working.
I can successfully authorize account, however when trying to upload/sync will fail with:
'Network error' (error when uploading).
Network Problem reading Dropbox data (details error when attempting to sync).

It stopped working on two Windows systems (Win7 and Win Server 2012R2).

Anyone else has the same problem?

**Comment by amtriathlon** [comment]
Yes, it's a known problem which is fixed in the last development build: https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/v3.5-DEV1710
