### ISSUE TITLE
New dev build crash

### ISSUE THREAD

**Issue by jonbev** [GoldenCheetah/GoldenCheetah#2642]
I updated to the latest dev build on my Ubuntu machine and couldn't get it to start up just crashed straight away. I uninstalled and reinstalled and managed to get it running once but it now wont run again even with uninstall and reinstall. I suspect this is my issue but would appreciate any help?

I installed it with 
sudo dpkg -i /home/bev/Downloads/GoldenCheetah_v3.5-DEV1710_amd64.deb

![image](https://user-images.githubusercontent.com/2034227/31121094-c916ab32-a82e-11e7-9e13-2483d9370b77.png)

**Comment by amtriathlon** [comment]
Which version of R do you have installed?
R v3.4.2 should work and you can start GC with --no-r option to avoid R integration.

**Comment by jonbev** [comment]
I dont have R installed. Just tried the --no-r option and it worked.

Thanks!!
