### ISSUE TITLE
GC 3.5 B3693 Crash when Manual ERG Mode

### ISSUE THREAD

**Issue by marcelrufino** [GoldenCheetah/GoldenCheetah#2643]
Devices ->

HR : Garmin HRM3-SS
Power & cadence : Tacx Vortex Smart T2180
Trainer : Tacx Vortex Smart T2180

macOS High Sierra 10.13.1 Beta
GC 3.4 Build id : 3693
To reproduce ->
1/ Choose Manual erg mode workout
2/ Start the workout
4/ Crash

**Comment by liversedge** [comment]
This is fixed in 3.5 dev.
