### ISSUE TITLE
Unable to use R charts (Mac OS 10.12.6, R 3.4.2  and GC v3.4 build 3597)

### ISSUE THREAD

**Issue by nesnahal** [GoldenCheetah/GoldenCheetah#2648]
I installed R and opened it and checked R.home(). Pointed GC to the directory and restarted. When I add a R chart I cannot see the script editor or console. I downloaded a R chart and the frame is present on the trend view but has no content.

I watched the video about R charts and am stumped. Anybody had the same issue or know what might resolve this issue? Thanks.

**Comment by amtriathlon** [comment]
Check the R version you installed, if it is 3.4.x you need to upgrade GC to the last 3.5 dev build or to downgrade R to 3.3.x, AFAIA

**Comment by nesnahal** [comment]
I just identified that 3.4.2 is not the 3.2.4 listed on the about page.
