### ISSUE TITLE
Withings is now Nokia Health: Deprecated functionality

### ISSUE THREAD

**Issue by SirLouen** [GoldenCheetah/GoldenCheetah#2650]
I've seen that GoldenCheetah Withing API pairing has been deprecated

Reading this is an obsolete guide:
https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-UPLOADING-AND-DOWNLOADING

Any news about this issue?

**Comment by amtriathlon** [comment]
The new API is integrated in the last development builds (see https://github.com/GoldenCheetah/GoldenCheetah/releases), you can authorize using Share > Add Clound Account > Measures > Withings and download using Share > Get Body Measures.
We should update the documentation before release.

**Comment by SirLouen** [comment]
Incredible revamp of the development branch. Now it works fine

**Comment by amtriathlon** [comment]
Note added to the wiki for future reference: https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-UPLOADING-AND-DOWNLOADING#when-setting-up-my-withings-wifi-scales-where-do-i-get-the-userid-and-key-
