### ISSUE TITLE
Bug: StreetView not working

### ISSUE THREAD

**Issue by SirLouen** [GoldenCheetah/GoldenCheetah#2651]
Version: Dev branch 3.5-DEV1710
Windows 10

1. Select activity with a route
2. In Train tab, import the activity with the Workout Wizard
3. Start the train mode

Nothing appears in StreetView chart:
https://i.imgur.com/fpYT2Dw.png

Sample route activity imported in Workout Wizard:
https://i.imgur.com/ERd0MaX.png

**Comment by amtriathlon** [comment]
According to [this thread](https://groups.google.com/d/msg/golden-cheetah-users/hz4Y4X4Qlcc/H1dMVc1GAwAJ) on the users forum StreetView was removed from v3.4, but the posibility to add a StreetView chart to the Train view is still available in 3.5-DEV1710.
I think we should remove the chart for v3.5 if it cannot be fixed to avoid confusions.

**Comment by Joern-R** [comment]
Chart is removed (since it has been deprecated before). Fix https://github.com/GoldenCheetah/GoldenCheetah/commit/99d90dea3255823e1e4acb3f41926b9eccd41e7e
