### ISSUE TITLE
Outputting the Live Biometric Data to another program?

### ISSUE THREAD

**Issue by rrmallin** [GoldenCheetah/GoldenCheetah#2652]
Hello! 
First - this is not an issue but rather a request for a feature...
This is also my first post on Github and I am pretty new to coding!
I am a graduate student in Integrated Media at UT Austin where I am trying to harness biometric data to influence live visuals. (Green numbers for a lower heart rate and progressively more red the higher it gets ect.)
GoldenCheetah works well for this with my Garmin HR/Ant+ combo and generates it own UI - but I want to make my own! I was able to pull some data through the web API using localhost:12021 - I am wondering if there is a port/command/.dll I can pull the "heart rate variable" from live as Golden Cheetah is running - or if this can be added?
Thanks!!

**Comment by mtbkeith** [comment]
This is not for features or "how to".

**Comment by stschake** [comment]
Using GoldenCheetah for this if you don't want the UI is going to be more pain than it's worth. Reading HR from an ANT+ strap is very simple once you have something that does the ANT+ stuff for you. Here is an example in Python, which is a good fit for quick prototyping work:

https://www.johannesbader.ch/2014/06/track-your-heartrate-on-raspberry-pi-with-ant/

(You don't need the raspberry)

**Comment by amtriathlon** [comment]
I'm closing this since it seems a discussion more appropriate for the developers forum, please see https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md
