### ISSUE TITLE
All gone wrong

### ISSUE THREAD

**Issue by Anthonyclu** [GoldenCheetah/GoldenCheetah#2653]
Hi, I downloaded the new Beta version and changed the font and GC went haywire and became unreadable. I uninstalled and reinstalled several times but the most recent version I can get to work is 3.2 and that is with a new profile. I would like to go back to 3.4 if possible. Any advice would be appreciated.

**Comment by amtriathlon** [comment]
Please use the user's forum for help, this is for bugs&features tracking, this may help: https://groups.google.com/forum/#!topic/golden-cheetah-users/KApxQN4X7_o

**Comment by Anthonyclu** [comment]
I think it is a bug, the font is not just small all I have is lines and squares. I can't change the font because the preferences are gone.

**Comment by amtriathlon** [comment]
May be, so please use the thread intended to report issues with the last development build: https://groups.google.com/d/msg/golden-cheetah-users/CiwAwufvQRA/m7O1UgN-AAAJ
Also it's more likely you get help about how to restore your system to usable state at the forum.

**Comment by amtriathlon** [comment]
Followup: https://groups.google.com/forum/#!topic/golden-cheetah-users/BasO1j4-01Y
