### ISSUE TITLE
This app can't run on your PC

### ISSUE THREAD

**Issue by swdesouza** [GoldenCheetah/GoldenCheetah#2655]
I have been using GC on the same PC for well over a year.  I now can't open it.  I have tried downloading/repairing the installation but get the same error.  I wonder if its something to do with a Windows 10 update?

**Comment by Joern-R** [comment]
Hard to say - the Windows Builds are done under Windows 10 - 64bit (for
both 32 bit and 64 bit version) and such a problem has not been reported.
When asking google for this error message,
there are plenty of sites explaining what potentially can be done in you
Windows installation to fix the problem. Please check this first. (Sorry
for not being able to point to a solution directly).

Cheers.
Joern

2017-10-16 20:07 GMT+02:00 swdesouza <notifications@github.com>:

**Comment by Joern-R** [comment]
For further support (as this seems not to be a general bug in the GoldenCheetah Windows builds) please check here how to proceed:

https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md

Cheers.
Joern

**Comment by swdesouza** [comment]
I would post this but I can’t as you’ve closed the thread.  I downloaded the beta version instead and that seems to work fine so no idea what the problem was.

Thanks

Stephen
