### ISSUE TITLE
Some bug of bryton 310

### ISSUE THREAD

**Issue by zwq984063985** [GoldenCheetah/GoldenCheetah#2657]
![image](https://user-images.githubusercontent.com/25601565/31750262-76e5da42-b4b1-11e7-87d9-0dbbbfacb91a.png)

[171018194848.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1396828/171018194848.zip)

**Comment by amtriathlon** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/issues/2029

**Comment by hrcsaba** [comment]
Hi, the Bryton 310 .fit import is almost perfect, but the elevation data seems corrupt :(
