### ISSUE TITLE
Trends Speed graph issue

### ISSUE THREAD

**Issue by AlanFretten** [GoldenCheetah/GoldenCheetah#2658]
![golden cheetah1](https://user-images.githubusercontent.com/32901454/31765401-27a62b0c-b4bc-11e7-9d6c-5fa2f904527b.JPG)
I have noticed that if you view the trends speed graph it always displays the x-axis values in KM/h although it says MPH. I have selected Imperial in settings.

**Comment by amtriathlon** [comment]
Good catch!
The code to convert from metric to imperial in this case is wrong since it scales the values of the arrays which are counts not kph: https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/Charts/PowerHist.cpp#L1363
