### ISSUE TITLE
Data downloaded from Garmin, verified parsed and finished but no data showing

### ISSUE THREAD

**Issue by KarlReadSimpson** [GoldenCheetah/GoldenCheetah#2659]
Please bear with me as i am new to this!
Set up the account last night and downloaded the software, plugged my Garmin Edge 705 into the laptop via USB connection but could not do a direct download from the item so went the "import data route"
The screens for the drag and drop came back and i took the data from the Garmin history folder which was on the removable E drive? I dragged all of it across, it verified it, saved the files and then hit the finish button. At that point i expected the fields on the Golden Cheetah screens to be populated as it would having previously used Training Peaks WKO3 but nothing, they are all blank.
There is probably something really simple that i have missed but not being computer savvy i cannot figure it out. 
I would appreciate any help/guidance that anyone can offer.
Regards

Karl

**Comment by amtriathlon** [comment]
Before you open an issue please review the [contributing guidelines](https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md) for this repository.

**Comment by amtriathlon** [comment]
Before you open an issue please review the [contributing](https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md) guidelines for this repository.

**Comment by KarlReadSimpson** [comment]
So what do I do? There is no one to contact to help me, I am 51 years old struggling with a head injury that I suffered as a result of being knocked off by a car 4 years ago and am just asking for help?

**Comment by liversedge** [comment]
Ale sent a link that explains: https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md

This system is for defect and feature request management not general help and support.
