### ISSUE TITLE
Problem with Date and Time while importing ZWIFT Files into Golden Cheetah

### ISSUE THREAD

**Issue by mtbkeith** [GoldenCheetah/GoldenCheetah#2669]
Importing from ZWIFT files causes dates to show up prior to 1989-12-31 00:00:00.

This was reported by Frank Wechsel on the Google group for GoldenCheetah. 

![grab-gc-user-bildschirmfoto 2017-10-24 um 14 26 10](https://user-images.githubusercontent.com/9326275/32036082-b40535e8-b9da-11e7-9397-3edd90766deb.jpg)

Thanks to TJDunnigan for attaching some files for investigation.

**Comment by mtbkeith** [comment]
Opened pull request to merge fix:
https://github.com/GoldenCheetah/GoldenCheetah/pull/2670

**Comment by mtbkeith** [comment]
Attached you can see the outcome of parsing a file which was duplicated and name obfuscated; they parse to nearly the same time; lacking the timezone information which was left out of the Zwift file. 
 
<img width="922" alt="grab-gc-zwift-date-issue-my-fix" src="https://user-images.githubusercontent.com/9326275/32036480-5114c540-b9dd-11e7-96c4-7b7890dc3a9c.png">

**Comment by Joern-R** [comment]
PR is merged - so I consider this done. Thanks.
