### ISSUE TITLE
ZWO import "Power" attribute

### ISSUE THREAD

**Issue by j33433** [GoldenCheetah/GoldenCheetah#2671]
https://github.com/GoldenCheetah/GoldenCheetah/blob/a42adad4a0b5185d35ebf28bae31edaa8e39b526/src/Train/ZwoParser.cpp#L55

"Power" may be present instead of "PowerLow" with "PowerHigh"

The recent dev version imports this as all zero powers.

**Comment by liversedge** [comment]
Thanks for raising this - do you have a sample file we can test with?

**Comment by j33433** [comment]
This is freshly made with Zwift's editor.

[GC_Test.zwo.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/1420001/GC_Test.zwo.txt)

**Comment by Joern-R** [comment]
Since I started using Zwift more extensively, I can have a look and try to fix it.

**Comment by Joern-R** [comment]
Fixed via https://github.com/GoldenCheetah/GoldenCheetah/commit/53e6b9887f9ed01e02542e8f7ef88cc4db877c86
