### ISSUE TITLE
Unrecognised .fit files downloaded from TrainingPeaks

### ISSUE THREAD

**Issue by bernmc** [GoldenCheetah/GoldenCheetah#2674]
I realise that TP is gradually been weeded out of GC code.

However, I wonder if it is intentional that user data in the form of .fit files downloaded from TP is no longer recognised by GC? Noticed this when upgrading from an earlier build (which imported these files without issue this morning), to V3.5 1710 on MacOSX - the new build generates an error when attempting to import.

**Steps**: 
Export user data from TP - log in->settings->export data; unzip download, and decompress individual files to .fit

GC - Activity->Import from file, generates:

Error - Unknown File type.

Screenshot and sample .fit attached

<img width="1352" alt="screenshot 2017-10-29 11 24 01" src="https://user-images.githubusercontent.com/19817426/32139963-881f811c-bc9c-11e7-9a80-4ea0ae49614d.png">

**Comment by liversedge** [comment]
try renaming it so its filename.fit rather than xx.uu.xx.fit

**Comment by bernmc** [comment]
Thanks Mark - that worked. Had to remove all .'s except the final .fit

**Comment by gcoco** [comment]
To me the is is a bug. I assume we have some sort of split going on and we are not checking the last in an array or not allowing for more than one period in a filename which is not good coding.

**Comment by gcoco** [comment]
Or should I more accurately say not a user friendly feature.
