### ISSUE TITLE
Add Cloud Wizard (google drive) does not work

### ISSUE THREAD

**Issue by cdknight** [GoldenCheetah/GoldenCheetah#2675]
I tried to click the "Authorise" button for Google Drive on GoldenCheetah and it opened a window with 404 error. Is this normal?

![image](https://user-images.githubusercontent.com/25418058/32150843-e201eafc-bced-11e7-887f-acdda5c2eb08.png)

Operating System: Manjaro Linux on KDE Plasma
Build id = 3964

**Comment by liversedge** [comment]
Its likely a build issue with the latest development build.
