### ISSUE TITLE
Changing STS period does not change trend curves

### ISSUE THREAD

**Issue by jmrius** [GoldenCheetah/GoldenCheetah#2680]
After changing Changing STS averaging period in Athlete settings, there is not change in the trend curves. I deleted the cache files, but the trend PMC STS curves remain the same as before changing STS period.
GC version = 3.5 DEV1710

**Comment by Joern-R** [comment]
I just had a look into my data - changed both STS value (default 7 days) and LTS value (default 42) - in the Model Tab of my Athlete's properties - both changes had immediate effect when "Saving" - without the need to clear any cache,...

Please re-check - and provide some screenshots.

I am using 1710 + the latest commits - so re-checking with next dev-build (planned for early next year) would also be an option.

Thanks.
Joern

**Comment by Joern-R** [comment]
Closed for now - could not be re-produced and no further feedback/details.
