### ISSUE TITLE
Feature Request: Ride data in map chart

### ISSUE THREAD

**Issue by potuz** [GoldenCheetah/GoldenCheetah#2687]
Often times I find myself uploading to Strava just to use this functionality that I find quite useful, specially on races or weekends group rides to easily remember the situation where the efforts/matches happened. I'd love to have the ride chart  curves underneath the map chart, so that hovering on the curves would also move a pointer in the map marking the location. I would be also useful if to have the intervals shown just like in the attached screenshot in Strava so that double clicking on them would highlight the segment in the map and rescale the curves underneath just as in the "ride" chart. 
![strava](https://user-images.githubusercontent.com/16044918/32626583-dfb958fc-c576-11e7-8adc-4957c264515c.jpg)

**Comment by amtriathlon** [comment]
Hovering is not available but you can view the selected interval(s) simultaneously in map and ride chart using Tiled instead of Tabbed mode:
![map ride-in-tiled-mode](https://user-images.githubusercontent.com/1444784/32634154-05df962e-c589-11e7-903d-47adc8b809ad.png)
