### ISSUE TITLE
Manual data entry wipeout

### ISSUE THREAD

**Issue by rgeorge1985** [GoldenCheetah/GoldenCheetah#2688]
I've been noticing this annoying phenomena laterly and hesistant to call it bug but dont know what else it is. Currently on v3.5-DEV1708

Issue : After manual input of data in "Details" tab (after manually importing files) and hitting save erases all the input I added in the same tab forcing me to repeat the entry process again.  

Example : Imported one's week's worth of files to GC. Starting from the more recent file, I start entering data into the details tab into fields I have creatd myself to give context to the activity. After data entry, I move onto the next file, keep entering data. But when I click back to the previous activity, I notice all the data I entered manually has been wiped out.  

Any idea what is causing this?

**Comment by bwalding** [comment]
Still happening?  

I just tried importing a few files (running master ce4d3eb) , then updating the Workout tab and clicking back and forth without saving. The data updated correctly in the Workout tab.
