### ISSUE TITLE
rpmlint reports E: incorrect-fsf-address

### ISSUE THREAD

**Issue by martinkg** [GoldenCheetah/GoldenCheetah#2689]
rpmlint reports E: incorrect-fsf-address

GoldenCheetah-debugsource.x86_64: E: incorrect-fsf-address /usr/src/debug/GoldenCheetah-3.5-0.1.20171110gitfd2f54d.fc27.x86_64/src/Train/EzUsb.c
The Free Software Foundation address in this file seems to be outdated or
misspelled.  Ask upstream to update the address, or if this is a license file,
possibly the entire file with a new copy available from the FSF.

GoldenCheetah-debugsource.x86_64: E: incorrect-fsf-address /usr/src/debug/GoldenCheetah-3.5-0.1.20171110gitfd2f54d.fc27.x86_64/src/Train/EzUsb.h
The Free Software Foundation address in this file seems to be outdated or
misspelled.  Ask upstream to update the address, or if this is a license file,
possibly the entire file with a new copy available from the FSF.

attached is a patch that fix this.
[GoldenCheetah-fsf-fix.patch.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/1461840/GoldenCheetah-fsf-fix.patch.txt)

**Comment by liversedge** [comment]
Ah ok, thanks for this. Those two files are copies from another project, but will fix them up.
