### ISSUE TITLE
Appdata.xml file for Gnome Software Center 

### ISSUE THREAD

**Issue by martinkg** [GoldenCheetah/GoldenCheetah#2690]
Hi,

I' am working on a GoldenCheetah rpm package for Fedora. The Fedora Package Policy suggest, if the program contains a gui, to install a appdata.xml file. Could you please add the attached appdata.xml file [1] to GoldenCheetah, so that it can installed with the Gnome Software Center. see: https://people.freedesktop.org/~hughsient/appdata

[1] https://martinkg.fedorapeople.org/Packages/GoldenCheetah/GoldenCheetah.appdata.xml

Thanks Martin

**Comment by cdknight** [comment]
The file looks fine, but I would recommend using screen shots showing newer features of GoldenCheetah. This is just me, but you could also add content to the description. Also, I didn't find the launchable and other building and application information tags such as releases. Otherwise looking good!

**Comment by martinkg** [comment]
could you please post the link to the newer features and a description, i will add it then.
Other information like launchable, building and application information tags such as releases, are
not necessare here, because the distribution provides a executable.

**Comment by cdknight** [comment]
Sure, here are some screenshots (these are links to the images with the descriptions):

<a href="http://www.goldencheetah.org/img/RideIndoor2.png">Video with Indoor Trainer</a>
<a href="https://user-images.githubusercontent.com/25418058/33226882-0b477658-d165-11e7-9671-87ec8efb6675.png">Google Street View image</a>

I'm very new to GoldenCheetah myself so possibly these descriptions could be incorrect.
