### ISSUE TITLE
findPeaks duration doesn't match Duration metric for intervals

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#2694]
The intervals created by findPeaks are 1 sample shorter for metrics calculations on intervals, this is evident for Duration but also applies to any metric so, for example the power included in the label for Peak Power intervals doesn't match the average power even when there are no gaps in the file.

The problem can be fixed reverting the commented change on https://github.com/GoldenCheetah/GoldenCheetah/blob/bf13f70c821faa0f9d262611f3e3ee6ad9b31c06/src/Gui/AddIntervalDialog.cpp#L881, I suspect this was a fix for the older method of computing metrics for intervals creating RideFile(s) but it doesn't match the new one using Specification(s), but I'm not sure, may be @liversedge  and/or @grauser remember this?

Probably something similar is happening with findFirsts but I have not tested it yet.

**Comment by liversedge** [comment]
I don't recall this change, but I do recall spending 2 weeks fixing code everywhere to be consistent !
If  this change broke that then it should be removed, do you know what the commit was?

**Comment by amtriathlon** [comment]
It's there from the initial commit by @grauser 
 (https://github.com/GoldenCheetah/GoldenCheetah/commit/60e14f9dbc6cd679fa32d867b810f5af4fa3d451#diff-4c6c92920515aba771c77c50876a744d), probably it was needed when interval metrics were computed using RideFile(s) but now the stop point is excluded and the intervals are 1 sample short.

**Comment by liversedge** [comment]
Well its wrong, but my brain melted trying to understand the code. Are you looking to fix it?

**Comment by grauser** [comment]
I can correct this if ok for @amtriathlon .
But I don't undrstand how it can be wtong since 2012.
For me it is right to exckude the last point.

**Comment by liversedge** [comment]
I am surprised too,

Each data point represents the average power from the timestamp for recIntSecs. This is why we always adjust timestamps to start from 0s.

Each datapoint represents the average power over a period of time:
0: 0-1s
1: 1-2s
2: 2-3s
3: 3-4s
4: 4-5s
5: 5-6s
6: 6-7s
7: 7-8s
8: 8-9s
9: 9-10s

If an interval starts at exactly one minute into the ride, then the first data point for the interval is at 60s, representing the average power from 60-61s. The very first sample in a ride represents the average power from 0s and has a timestamp of 0s.

I'm pretty sure thats how the rest of the code works .. hopefully !

**Comment by liversedge** [comment]
So, an interval with start of 0s and end of 10s is 11 seconds long.

**Comment by grauser** [comment]
I will check today if Ale didn't correct already

**Comment by liversedge** [comment]
Cool. I cannot tell if this is really a problem with this code !

**Comment by liversedge** [comment]
Also, the main problem in the past was always with Powertaps 1.26s recording interval and having to account for the point at which the interval ended - since it was almost never exactly on a 1s point.

**Comment by amtriathlon** [comment]
Perhaps is better to see an example, this uses the Marmote test file (https://github.com/GoldenCheetah/GoldenCheetah/blob/master/test/rides/2009_07_04_06_09_48.wko) and standard peak power intervals:

![findpeakpower10s](https://user-images.githubusercontent.com/1444784/32746180-9837f202-c893-11e7-9810-8dfeeb6262ee.png)

All samples each second are present, Duration metric is 9 seconds instead of 10 and Average Power is different from findPeaks average power

Time | Distance | Power | Rolling Avg
03:10:20 | 68.458 | 382 | 382
03:10:21 | 68.465 | 560 | 471
03:10:22 | 68.472 | 577 | 506
03:10:23 | 68.480 | 619 | 535
03:10:24 | 68.488 | 599 | 547
03:10:25 | 68.496 | 579 | 553
03:10:26 | 68.504 | 579 | 556
03:10:27 | 68.513 | 510 | 551
03:10:28 | 68.520 | 510 | 546
03:10:29 | 68.528 | 310 | 523

From the rolling average is clear that the last power value (310) is not included in the Average Power metric but it is correctly included in the findPeaks average power calculation, both problems are solved changing to the commented out code on the OP, but I don't know if there is a better solution.

**Comment by liversedge** [comment]
those intervals were created by WKO (and highlights an issue regarding the importer not translating intervals to our scheme ) .. or did you delete the interval and re-add with findPeaks ?

**Comment by amtriathlon** [comment]
I created the intervals a new using Find Intervals > Standard, the same happen with the auto-discovered intervals but in those is not that easy to show the boundaries since Edit Interval is not available

**Comment by liversedge** [comment]
phew. ok. then it needs to be corrected which is a relief !

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/bb3c33bc164308648d968a3303e17087ec67f9e1.
Manual swims and runs and pool swims may need to be updated since were fitted to the 1sec short laps...

**Comment by ErnstZwingenberger** [comment]
Is my issue (wrong peak power calculations) related to this one or is my ride data file corrupt ?
I am using V 3.6 DEV2101 Build nr: 4003
![GoldenCheetah_findPeaks_Issue](https://user-images.githubusercontent.com/878285/112997225-344f3100-916d-11eb-950e-930dbfff9d8f.png)
The calculated peak power values are wrong. The max. power value in the raw data is 489 Watt. However I am not sure if GC can handle the same timestamps multipe times?
The source of the ride file is from RGT uploaded to Strave and from Strave downloaded into Golden Cheetah.

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
