### ISSUE TITLE
No data for swim with Garmin 735

### ISSUE THREAD

**Issue by Hezelnutt** [GoldenCheetah/GoldenCheetah#2695]
When importing swim workouts from my Garmin 735 in Golden Cheetah, the file has no data.

All variables (distance, time etc) are 0, and under the 'edit' tab there is also no data available.

On the Garmin website the workouts have no problem showing up. Also, I have had no problems with swim workouts in Golden Cheetah before with a different Garmin watch. Thus, it seems to be the specific combination of the Garmin 735 and Golden Cheetah that gives the errors.

If you have any idea what the problem is, this is much appreciated.

**Comment by amtriathlon** [comment]
Can you provide a test file?

**Comment by Hezelnutt** [comment]
Sure, I have attached the file

[7BG64750.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1479726/7BG64750.zip)

**Comment by amtriathlon** [comment]
It seems to import Ok on the last development build (https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/v3.5-DEV1710):
![garmin735swim](https://user-images.githubusercontent.com/1444784/32921015-90e7c882-cb0a-11e7-9842-170a7edcffd8.png)
We should add the Garmin 2158 as Garmin 735 although.

**Comment by Hezelnutt** [comment]
Hi,

Thanks for the help.

I installed the new GC version, but I still get the same result. I also started a new 'athlete' account and added only the swim workout, but still the same result.

Have you got any other idea what could be the problem? It is weird, the picture you showed is exactly the result I need.

**Comment by amtriathlon** [comment]
This happens if you have Garmin Smart Recording disabled, see options/preferences:
![garminsmartrecording](https://user-images.githubusercontent.com/1444784/32947622-ea144e10-cb7a-11e7-9d83-8e6957b1d6c7.png)

**Comment by Hezelnutt** [comment]
Thank you so much, that did the trick!

Upon importing the file again, the swim data appears. However, the already imported swim workouts remain unchanged. Is there an easy way to fix this, or would I have to re-import all these workouts?

**Comment by amtriathlon** [comment]
No, you need to re-import them, the originals are stored on the imports folder under the athlete directory, see the About box.
