### ISSUE TITLE
Minutes OR Seconds in Time vs Speed Chart (Compare Mode)?

### ISSUE THREAD

**Issue by rgeorge1985** [GoldenCheetah/GoldenCheetah#2697]
**Issue :
![compare](https://user-images.githubusercontent.com/23737973/32947464-6536e9ba-cbb5-11e7-827a-39dc9112036a.JPG)

** While comparing two runs both from 10K races using the compare pane, clicking on the Time vs Speed chart in the Activites Tab shows the Y axis (time) in triple digit minutes. The histogram (attached) shows highest time spent at speed to be greater than 400 minutes, which is not possible in a 10K format. 

Version being used : v3.5-DEV1708
Build Id : 3963

**Comment by CrossThree** [comment]
This seems to happen when you create a histogram plot while compare is active. Here, the plot on the left was refreshed, the one on the right was just created, while compare is turned on:
![image](https://user-images.githubusercontent.com/24485772/36625687-b384b2ea-18fa-11e8-8723-3e58af8a16ab.png)

If I toggle compare off, then on, the plot is refreshed and the vertical plot range is correctly labeled:
![image](https://user-images.githubusercontent.com/24485772/36625704-f1950c38-18fa-11e8-8181-d9c01b13f096.png)
