### ISSUE TITLE
Sync and Upload are not consistent

### ISSUE THREAD

**Issue by qheath** [GoldenCheetah/GoldenCheetah#2700]
Uploading via `Upload` sends the information in cache, currently shown by GC.  This is not ideal because, if GC crashes before this information can be saved to file, it looses the changes and gets out of sync with the upload.

Uploading via `Synchronize` sends the information in the file.  This is not ideal because, if the activity was changed but not saved, the upload is already outdated.

These behaviours should at least be made coherent.  It would also be convenient to have activities be systematically saved when uploaded; this could be made automatic.

**Comment by Joern-R** [comment]
Added a check if there are unsaved activities - with the option to Save was is still unsaved. This makes it clear for the users - and their decision what they want.

https://github.com/GoldenCheetah/GoldenCheetah/pull/2825
