### ISSUE TITLE
Problema golden cheetah

### ISSUE THREAD

**Issue by Angelo28791** [GoldenCheetah/GoldenCheetah#2701]
Ho installato la versione 3.5, visto che la versione 3.2 mi dava problemi. Nell' installazione del programma non ho potuto installare Microsoft silvelight poichè ho già installato la versione 86 bit. Ora riscontro il problema della mancata visualizzazione dei grafici, fondamentali per me. Cosa posso fare? Installo la versione a 64 bit di Microsoft Silver Light? Grazie

**Comment by amtriathlon** [comment]
Please use the users forum for help, it's explained in the contributing lines (https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md) which should be read before to open a new issue.
