### ISSUE TITLE
Crash Golden cheetah 3.2

### ISSUE THREAD

**Issue by Angelo28791** [GoldenCheetah/GoldenCheetah#2702]
Salve, in apertura di Golden cheetah mi esce il seguente messaggio di crash. Cosa devo fare?
[Crash.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/1488188/Crash.txt)

Grazie

**Comment by amtriathlon** [comment]
Please use the users forum for help, it's explained in the contributing lines (https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md) which should be read before to open a new issue.
