### ISSUE TITLE
Should be "if (antMessage.leftOrCombinedPedalSmoothness != 0xFF && andMessage.rightPedalSmoothness != 0xFF) {)

### ISSUE THREAD

**Issue by pepelkod** [GoldenCheetah/GoldenCheetah#2705]
https://github.com/GoldenCheetah/GoldenCheetah/blob/b282299d25b38c0a1c18b72e086d3df761353280/src/ANT/ANTChannel.cpp#L671

**Comment by Joern-R** [comment]
Fix via e51ba522186717998637d180156d5852726a55de

Thanks for making us aware - classic "Copy&Paste" Error.
