### ISSUE TITLE
Python Chart

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#2708]
Embed python into GC in a similar fashion to the R integration.

This will enable more complex processing and access to common machine learning frameworks like TensorFlow and similar without having to worry about C level integration.

**Comment by liversedge** [comment]
Step 1: Embed Python

* embed the interpreter
* new chart type
* console commands and output capture
* run script on change (ride/season)

**Comment by liversedge** [comment]
Step 2: Provide API to access GC data

* GC module (that is automatically imported)
* Add the same semantics as the R API

**Comment by liversedge** [comment]
Step 3: Provide API to work with the plot canvas

* create and manipulate Qt Charts
* enable hover for points?
* process interval selection?

There is potential for a far richer UX with interaction etc than the R chart currently offers

**Comment by stschake** [comment]
One warning for step 2: providing an API. Exposing a module with functions is simple through CPython, but exposing an OOP interface with Python classes is very very boilerplate heavy and involves lots of nasty reference counting stuff that is easy to get subtly wrong. 

If you want an OOP API, the options are basically only exposing functions from C++ and writing Python modules that wrap those, or using a binding generator (SWIG or Shiboken).

**Comment by liversedge** [comment]
Thanks Stefan. Ale is going to pick that up with help from me and Damien.

If you look at the [R API](https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Working-with-R), do you have any thoughts on how we might translate that to Python, based upon your experience?

**Comment by podiumbound** [comment]
I use [Plotly](https://plot.ly/python/) quite a bit for plotting in R, and they seem to have a parallel library to work with Python. Not sure if it's an option in this context, but just putting it out there.

**Comment by liversedge** [comment]
Yes, that's a great point. 

In fact the notebook approach using Jupyter is something that would be really cool to try and encompass, perhaps separately to the the typical chart UX where it reloads as seasons/rides are selected.

Since we have a web browser built in courtesy of GC it might not be too hard... and of course plotly would work well in a notebook chart. We would still have a chart that reloads as you navigate data.

**Comment by stschake** [comment]
There is this:

https://qtconsole.readthedocs.io/en/stable/

(Haven't looked at the code though, could be a massive pain)

**Comment by liversedge** [comment]
Nah. Already got Python 3.6 embedded and running in threads, so no issues. Will push tomorrow/Sat as need to sort out interrupting long running scripts with ESC or ^C via Py_AddPendingCall.

**Comment by AartGoossens** [comment]
Great initiative to implement Python in GoldenCheetah! I wrote a [small client](https://github.com/AartGoossens/goldencheetahlib) that uses the GC REST CLIENT to get be able to play with activity data in Python but being able to do that directly in GC makes a big difference.

I do not have any knowledge about connecting the GC core to Python so I really cannot help there but I wonder if you already thought about how activities (and other data) are represented in Python? It is my understanding that in the R charts most of the data is returned as an R dataframe. For Python there is a similar data structure available, the [pandas dataframe](http://pandas.pydata.org/pandas-docs/stable/dsintro.html#dataframe). I am working on a subclass of this class [here](https://github.com/AartGoossens/athletic_pandas/blob/master/athletic_pandas/models.py) but that might be too much tailored to my personal needs...
As pandas dataframes are easily converted to numpy arrays using them in e.g. TensorFlow and scikit-learn should be straightforward. Only have personal experience with scikit-learn though.

**Comment by liversedge** [comment]
Thanks Aart -- good insight !

**Comment by podiumbound** [comment]
I heard about this the other day: https://github.com/wesm/feather. Not sure if it would be helpful or not, but seems like a good option to allow for interoperability between R and Python

**Comment by liversedge** [comment]
That's interesting, perhaps for an export format?

One thing is becoming clear with this, we need to think carefully about the API. I'd really like to give python devs something really powerful without making it too complex for novices.

**Comment by liversedge** [comment]
@AartGoossens reckon pandas is too specialised and introduces a dependency - so will create a dict of arrays so folks can convert to dataframes, numpy arrays etc if they want to. try and keep it all generic python for compatibility.

**Comment by liversedge** [comment]
so an object with a sample dictionary and a columns, where the index is one of the arrays.
aka http://www.ritchieng.com/creating-dataframe-from-objects/

**Comment by AartGoossens** [comment]
Indeed, converting plain dictionaries to dataframes is easy. On the other hand, analyzing data that is stored in dictionaries and lists in Python is not beginner friendly because lists are not built for data analysis. For example, calculating the average of a list would require you to do this:
```python
from statistics import mean
mean(activity['power'])
```
Where in numpy, pandas or similar this would just be something along the lines of
```python
activity.power.mean()
```
I do not know what kind of people will use Python charts but my guess is that they are just like the users of R charts not necessarily R/Python experts but just want to be able to fiddle around with the data. For me then it makes sense to make that as easy as possible.
About dependencies: I understand your point that you want to minimize dependencies, but for most OS'es users will have to install Python manually anyway: I think there might be a few Linux distributions that ship Python 3.6 by default, but MacOS is still at 2.7.10 if I'm not mistaken and Windows doesn't ship with Python at all. This is already a dependency. Pointing users to a Python 3.6 installer that ships with numpy/pandas/scikit-learn (talking about Anaconda here...) would make installing Python and these dependencies just one step and in my opinion not too much of an inconvenience.

**Comment by liversedge** [comment]
Fair point, I'm cool with pointing folks to installers, just don't want to be dependent on particular modules being installed. I'll take advice on whats best. Mac 2.7 is a pain, want to stick to 3.

**Comment by liversedge** [comment]
@AartGoossens Hmm. I'm coming round to your view Aart.  Numpy arrays seem like a clean memory efficient way to pass the data back. Using native python arrays looks poor since there is no C api and we'd need to pass as a buffer and unpack into an array in python before returning it to the user. That sucks.

As soon as we mandate numpy we  might as well mandate pandas. So ... which is the better choice, and do you have any view on other options to consider?

**Comment by liversedge** [comment]
@AartGoossens looks like pandas is pure python, so numpy arrays are pretty much the only good choice?

**Comment by liversedge** [comment]
@AartGoossens I've come full circle and will use the [buffer protocol](https://jakevdp.github.io/blog/2014/05/05/introduction-to-the-python-buffer-protocol/) to provide acccess to GC data -- it can be consumed by the numpy, pandas and array modules and I might be able to cache them with open rides too (need to work out how to invalidate them on the python side to avoid any garbage collection issues).

**Comment by AartGoossens** [comment]
@liversedge Pandas is built on top of Numpy. I didn't know about the buffer protocol but it looks interesting, will read more about it to get to know it better. What are the main advantages of the buffer protocol over e.g. Numpy?

**Comment by liversedge** [comment]
@AartGoossens I like the buffer protocol because it provides access to raw data, introduces no dependencies and will work with numpy, array etc. it also looks like managing memory consumption might be easier -- I'm wondering if I can create a proxy into the GC memory structures without having to copy it into a temporary format -- that would be super efficient !

**Comment by AartGoossens** [comment]
@liversedge That's fancy indeed! Do you expect issues with memory consumption? And do you have any figures of memory consumption in the R charts? The R charts don't share the GC memory structures either right?

**Comment by liversedge** [comment]
@AartGoossens no figures, but the R API eats memory like crazy!! We don't have any choice on the R side. But Python feels like a different kind of beast. Not least since its used so extensively for this kind of thing (which R is not).

I'm not 100% convinced I can proxy using the buffer protocol but suspect passing data via contiguous arrays is the #1 priority, since its so much more efficient down the line from numpy and panda through scikit and tensorflow et al.

**Comment by liversedge** [comment]
@AartGoossens looks like the approach is pretty good. Here is the code to get a pandas dataframe. It might be possible to have a variant or parameter for the GC.activity() function to return pandas instead of needing to do the conversion. We're trying to expose much of the API in python so its 'purer'.
```
import pandas
## Create a Pandas dataframe for the ride
rd=GC.activity()
ix = range(0,len(rd["seconds"]))
df = pandas.DataFrame(rd, columns=rd.keys(), index=ix)
end = time.clock()
```

**Comment by liversedge** [comment]
@podiumbound actually I think you have a good point. Plotting in python is focused on generation of web assets. I think it makes sense to enable the python script to generate a webpage that is loaded and displayed. It certainly makes for getting going quickly and plotly is really impressive.

might be a bit complex for initial users but then, so is python ...

**Comment by liversedge** [comment]
Using a web view to display plots generated from python works with lots of popular charting modules; plotly, matplotlib, bokeh, ggplot and many others will write to html that can then be loaded in a browser (or in our case a webengineview).

Here is an example scatter plot using numpy and plotly:
```
##
## Python program will run on selection.
##
import numpy as np
import plotly
from plotly.graph_objs import Scatter, Layout

## Create a Pandas dataframe for the ride
xx = np.asarray(GC.series(10))
yy = np.asarray(GC.series(1))

## Prepare Plot
f =plotly.offline.plot({
    "data": [Scatter(x=xx, y=yy, mode = 'markers')],
    "layout": Layout(title="Power / Cadence")
}, auto_open = False)

## Load Plot
GC.webpage(f)

```

**Comment by amtriathlon** [comment]
Very nice! That was fast!

**Comment by kbilleter** [comment]
Cool.  Just tested.  Python's working directory seems to be '/' for me, so I had to add a filename option to the plot command

**Comment by oberti** [comment]
Good job mark......very fast

**Comment by liversedge** [comment]
Step 4: Manage Dependencies

* Need to recognise dependencies
* Need to ensure they are honored ? 

Should we mandate pipenv or similar?

**Comment by liversedge** [comment]
Will come back to dependency management at a later date, closing as Ale has now completed the API
