### ISSUE TITLE
Official Release 3.4 Install Crashing

### ISSUE THREAD

**Issue by acorso522** [GoldenCheetah/GoldenCheetah#2712]
Not sure what the best way to communicate an issue for an official release is (feels like github is for dev issues) but I'm running MacOS Sierra 10.12.6 on a MacBook Air (13-inch, Mid 2013) and after opening the dmg, every time I try to open the app, it immediately crashes and asks if I want to reopen. I'm trying to do the official release of 3.4 so no idea what the problem could be here. I can try installing from source later this weekend though.

**Comment by Joern-R** [comment]
Please use the users forum for help, it's explained in the contributing lines (https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md) which should be read before to open a new issue.

Your problems sounds like the one described in the users forum here: https://groups.google.com/d/msg/golden-cheetah-users/gULN7lA5BN4/VN3xNGirAwAJ

Please check - I will close for now.
