### ISSUE TITLE
Elite Fluid Elastogel (round unit) support

### ISSUE THREAD

**Issue by danmalcolm** [GoldenCheetah/GoldenCheetah#2720]
Add a new virtual power profile for the Elite Fluid Elastogel (round unit), using the power curve from powercurvesensor.com.

I may look into implementing this myself but thought I'd add the request here first. Any of the following would be useful:

* Hints on how to get from power curve graph to calculation - I'm looking at using a polynomial regression calculation
* Any other power information available for this trainer that I could use

**Comment by danmalcolm** [comment]
I obtained the following figures from the power curve graph:

0 0
2.5 7
5 13
7.5 20
10 27
12.5 37
15 46
20 74
25 109
30 158
35 218
40 295
45 390
50 510
55 650
60 814

The Online Polynomial Regression tool at http://www.xuru.org/rt/PR.asp produced the following function (with a polynomial degree of 8):

y = 4.957201555·10-11 x8 - 1.174191767·10-8 x7 + 1.09599761·10-6 x6 - 5.081940407·10-5 x5 + 1.203270989·10-3 x4 - 9.93619499·10-3 x3 + 3.844466391·10-2 x2 + 2.553782634 x + 1.221444877·10-1

**Comment by wholenineyards** [comment]
I would also find support for this trainer very helpful.

**Comment by wholenineyards** [comment]
I used a tool at http://polynomialregression.drque.net/online.php to get
f( x ) = 0.06417034921314188   + 2.4324441481209464x + 0.00020274271362228152x2 + 0.0030925155807855578x3
I believe the code changes required to to add this should be along the lines of adding a switch case in   RealtimeController.cpp:
`case 65: // ELITE CRONO FLUID (round)`
        `     {`
`        double v = rtData.getSpeed();`
`        rtData.setWatts(2.43244*V + 2.02742e-004*pow(V,2) + 3.09251e-003*pow(V,3));`
        `     }`
        `     break;`

and adding an item to   the UI code in AddDeviceWizard.cpp:
`virtualPower->addItem(tr("Power   - Elite Crono Fluid (round)"));`

Obviously this would be better added by the other Elite trainers, but I don't feel I have the expertise for a pull request.
