### ISSUE TITLE
Power Range v.s. Specific Power number in ERG mode?

### ISSUE THREAD

**Issue by dcandjb** [GoldenCheetah/GoldenCheetah#2727]
Is it possible in the current version of GC to create a workout that limits your power to a range?  For example on easy days I might just want to do a free ride (no minimum watts) but limit my watts to a maximum of 170 watts.  Or if I want to do a specific range of say 200-250 watts.  I can imaging a few other instances where I might either want to set a floor or ceiling or both in a workout.  is this possible?  If not, could this be something to consider for new releases?

Thanks!

**Comment by Joern-R** [comment]
No - it's not possible - and I am actually not aware on any software doing this. 

Why not ? ERG mode means the trainer resistance is controlled by the software - so what shall any software do with a intervall like 200-250 watts. Which resistance shall be set - 200 or 250 or something in the middle. If you want to have a range of watts, ERG mode is not the ride option - and the trainer software cannot control/set such a range.

If you want to limit your watts - do not use ERG mode and just ride your trainer in normal resistance mode - like you would ride on a road.
