### ISSUE TITLE
Speed inaccurate? or just trainer

### ISSUE THREAD

**Issue by Bentth** [GoldenCheetah/GoldenCheetah#2729]
Not sure if it's an issue with my trainer or the software.
There are some drops, seen in gear ratio and speed.

This is a 5 minute interval at 225-235 watts. Cadence and power are smooth and no gear changes.
Is this an issue with my trainer or the software? My wheel size is 2100 since that is the default when pairing.

Here is link of image: [link](https://i.gyazo.com/94e7e47cfa79860eb65963ca5d7812d5.png)

Also is there a setting the computer tells the trainer to have more resistance when intervals start? I feel a difference but not too much. I guess what i'm stelling is that ERG isn't working that well..

Do love the program though :)

Cheers

**Comment by Joern-R** [comment]
Gear ratio is "simulated" from Speed and Cadence (if no DI2 data exist). So it cannot be accurate - and since your speed and cadence id fluctuate this cause the structure. It's an indicator - not more.
