### ISSUE TITLE
Show averages on all plot for currently visible section

### ISSUE THREAD

**Issue by grauser** [GoldenCheetah/GoldenCheetah#273]
Added by hejman komarac about 2 years ago. Updated over 1 year ago.
## Description

Hello, i am using GC now for about 3 month and really do like GC, but for former SRM Users there are some things missing and i hope that it would be possible to add without too much effort.

When you zoom into a ride in the "Ride Plot" it would be really helpful, to have a little window or "mouse over" that shows average power, HR and so on for exact that part of the ride i am looking at right now.

Another thing which shouldn`t be too hard concerns the "Histograms" or "weekly summary" or "Metrics" view....i would like to see somewhere how much time i spent riding (overall), in zone 1, 2, 3 and so on during the last 4 Weeks, 3 Month and the last year... i know that it is possible to see how much time i spent riding during a week in june or i can plot a graph that tells me that i was riding 1.2 hours on July 5th and 2.3 hours two days later an so on, but its inefficient to summarize everything by hand or even worse, create an excel sheet to get it done.

So...one possibility would be to add the possibility to show more than one ride in the "histograms" view and additionally show the sum over all as number.

Another, maybe easier yet more comfortable to use way would be, that weekly summary would not only be weekly, but also monthly, yearly and so on. Maybe someone could insert a drop down menu where the user could choose the time of his interest.

The last possibility would be a little for example 3-digit number that summarizes all values currently shown in the "metrics" view.

Thank you

Add
Related issues
## History
- 1) Updated by Justin Knotzke about 2 years ago
  Status changed from New to Feedback

Hi,

Could you please do me a favor and open this up again as a feature request as it is not a bug. Once you do that, I'll close the bug report for you.
Thanks
J
## 
- 2) Updated by Jamie Kimberley about 2 years ago

When you move this to a feature, can you split it up into several requests. They all fit under "Minor changes to improve fast interpretation of relevant training data" but it helps people identify a project to work on, and allows us to better track and close issues as they are completed.
## 
- 3) Updated by Jamie Kimberley about 2 years ago
  Tracker changed from Bug to Feature
## 
- 4) Updated by Mark Liversedge over 1 year ago
  Target version set to 3.1
  Update Watch Copy Delete

**Comment by riccioclista** [comment]
@liversedge , I think this can be closed, because you can see a summary of averages if you select a time span to create an interval - this is not exactly what was asked for but probably close enough

**Comment by amtriathlon** [comment]
Agree the interval summary showing averages/totals of selected/unselected intervals is close enough.
