### ISSUE TITLE
sml swimming file import Xdata stroke type

### ISSUE THREAD

**Issue by mondoshiwan** [GoldenCheetah/GoldenCheetah#2737]
there is one incorrect thing while importing the Xdata.
If an Interval is longer than one length, usual it is…

e.g. 100m freestyle at 25m pool length, then the Xdata shows up 3x stroke type 6 and then, only at the last one, the correct type 1.
seems that only at the end of an interval or at a change, the stroke type is stored by Ambit, and for all other lengths GC puts in here value 6, but it should use the last stored swimming style.

here is a file with only freestyle to fiddle around:
[C8C70A511B001500-2017-12-28T07_07_19-0.sml.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1591693/C8C70A511B001500-2017-12-28T07_07_19-0.sml.zip)

and this is with mixed styles which were correct at beginning and end:
[C8C70A511B001500-2017-12-19T07_07_48-0.sml.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1591695/C8C70A511B001500-2017-12-19T07_07_48-0.sml.zip)

but all length with type 6 should be "1"

**Comment by amtriathlon** [comment]
The "6" means the style is unknown/mixed for the length, which is the information we have for the length, I don't see how we can fix this based only on the info in the sml file.

**Comment by mondoshiwan** [comment]
my solution for now is an Excle/Numbers sheet to find and substitute the mixed type (6) with the number correct styles.

**Comment by amtriathlon** [comment]
I checked both files and the style we use to generate the XData is what the file reports, the 6 corresponds to this case: <PrevPoolLengthStyle>Other</PrevPoolLengthStyle>, I'm afraid the watch is not reliably detecting your stroke.

**Comment by mondoshiwan** [comment]
You didn' got it right…

the watch is detecting the right style but not storing it for every lenght, only a t the end of an interval and GC, if it's not finding a style for a lenght, will put in a 6 for mixed style.That's the issue.


Am 14.02.2018 um 00:15 schrieb Alejandro Martinez:

**Comment by amtriathlon** [comment]
SML files are text, look for PrevPoolLengthStyle tags and you will see what I’m saying.

**Comment by mondoshiwan** [comment]
and this PrevPoolLenghtStyle tag is valid for all previous lenghts without that tag, e.g. there is no style change. usually since the last rest when the prevStyle tag is 0.




Am 14.02.2018 um 11:38 schrieb Alejandro Martinez:

**Comment by mondoshiwan** [comment]
ok now i see what you mean…

PrevPoolLengthStyle>Other</PrevPoolLengthStyle

sorry, but could it be that "other" is the rest?
 i will do a short test the other days with only freestyle

Am 14.02.2018 um 11:38 schrieb Alejandro Martinez:

**Comment by mondoshiwan** [comment]
HI Alejandro,

it's not a bug, either the watch or GC. It's a wrong interpretation. I never see any mixed swimstyles on movescount. I took a deeper look at the sml.

It works as follows:

the prevPoolLengthStyle tag does what it says, it always the previous Length. And it will only change on stylechange or at the end of an interval. So at the beginning at an interval or on start,
it will always  tag the first lenght with *other*, because there was an rest before.

movescount/Suunto takes the last tag for all  previous recorded lenghts, but GC takes the first tag for the upcoming lenghts and only take the last one for the last lenght. That's the difference.
Any way to sort this out?



 
Am 14.02.2018 um 11:38 schrieb Alejandro Martinez:

**Comment by mondoshiwan** [comment]
now we are talking … :) did a swim yesterday and seperated a 200m warmup in freestyle to make it a bit more easy. On these 8 lenght there are 2 <PrevPoolLengthStyle> tags, as expected. right at the start the *other*, cause there was no length before (or a rest) and only at the end the *freestyle* tag, cause there was no stylechange in beteween. in movescount it looks like this:
![bildschirmfoto 2018-02-16 um 10 29 28](https://user-images.githubusercontent.com/23431166/36301747-3b5dabb8-1306-11e8-9ca5-be0749504410.png)

all previous lenght are correct tagged with freestyle. My account is public you can take a look here:
http://www.movescount.com/moves/move201216707

GC will only tag the last lenght with freestyle:
![bildschirmfoto 2018-02-16 um 10 45 50](https://user-images.githubusercontent.com/23431166/36301875-a619b3de-1306-11e8-945d-f6365b4e4aba.png)
you could do a 1000m freestyle swim with no rests and would only swam 25m freestyle at the last lenght…
the original sml:
[C8C70A511B001500-2018-02-15T07_05_26-0.sml.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1730807/C8C70A511B001500-2018-02-15T07_05_26-0.sml.zip)

GC should ignore the first *other* tag , cause it's the beginning of a new interval and must use tle next one for all previous lenghts.

to fiddle more around this is the file after the warming up in different styles:
[C8C70A511B001500-2018-02-15T07_11_07-0.sml.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1730820/C8C70A511B001500-2018-02-15T07_11_07-0.sml.zip)
 and the link:
http://www.movescount.com/moves/move201216714

hope this helps!

**Comment by amtriathlon** [comment]
Thanks, I will reopen the issue but I’m not enthusiastic about this change

**Comment by amtriathlon** [comment]
Since Suunto is moving away from the SML format and switching to FIT (https://apizone.suunto.com/docs/services/workout-api/operations/export-user-workout-in-fit?) it doesn’t make sense to invest time in an obscure issue like this.
