### ISSUE TITLE
Fix Lap Swim from Length Data tool

### ISSUE THREAD

**Issue by mondoshiwan** [GoldenCheetah/GoldenCheetah#2739]
when i try to use this tool on an imported Suunto sml file, it will immediately delete all data within that activity.
can someone reproduce?

dev3.5-1710 Mac OS 10.10

[C8C70A511B001500-2017-12-19T07_07_48-0.sml.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1593055/C8C70A511B001500-2017-12-19T07_07_48-0.sml.zip)

**Comment by amtriathlon** [comment]
I imported your file on current master and dev3.5-1710, immediately afterwards I ran Edit>Fix Lap Swim from Length data and it works as expected, here is the result: 
[2017_12_19_07_07_48.json.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1717774/2017_12_19_07_07_48.json.zip)

**Comment by amtriathlon** [comment]
Today tested on a Mac using dev3.5-1710 with the same result, as above.

**Comment by mondoshiwan** [comment]
will send you later some screenshots


Am 14.02.2018 um 00:24 schrieb Alejandro Martinez:
