### ISSUE TITLE
[Old 141] Pre-populate fields on metric page.

### ISSUE THREAD

**Issue by grauser** [GoldenCheetah/GoldenCheetah#274]
Added by John Ehrlinger about 2 years ago. Updated over 1 year ago.

Description
--
Why do all the variables on metric page (developer versions) default to zero, even if the ride already has some value for that field?

I did a ride, and my PT batteries died. I had 48 miles in, but continued on for about another 20. When I went to adjust the distance, it defaults to 0. Auto initializing this would reduce a visual bounce, and guide the user to data formatting... i.e. adjusting the time variables.

Add
Related issues

History
--
* 1) Updated by Mark Liversedge over 1 year ago
Target version set to 3.1

**Comment by liversedge** [comment]
Not a bug / Damien has added defaulting metadata.
