### ISSUE TITLE
Kettler Erogracer with USB interface not workin in training mode

### ISSUE THREAD

**Issue by vbretsch** [GoldenCheetah/GoldenCheetah#2743]
I have a rather new Kettler Ergoracer bike, that has a USB Interface. When connected to windows 10 it shows up as UART on Com3.
When running Golden Cheetah in training mode, GC states the bike to be connected but it does not show any readings from the bike nor does it transfer resistance data to the bike.
I do have another, older Kettler Ergoracer as well with a serial connector that when connected to my windows 10 PC via a Serial to USB dongle everything works perfectly.
Golden Cheetah is the current development version Version 3.5 Development Build 1710.
If any more information for troubleshooting is required i would be very happy to help!

**Comment by liversedge** [comment]
is this still an issue?

**Comment by amtriathlon** [comment]
Closing due to lack of feedback after 2 years.
