### ISSUE TITLE
Feature request: total_timer_time field into Summary page of GC4, + "default" HR zone profile

### ISSUE THREAD

**Issue by jifizipazu** [GoldenCheetah/GoldenCheetah#2745]
Hi, now there is only fields time elapsed time and moving time, but the most important data "total time" is missing.
And second request is additional HR zone profile for other sports than cycling or running. If I for example XC-ski, I would like to use default profile for that, like I do with Garmin, so I get _duration on zone_ data correctly. Now I have to change activity as running for a while to only see that data -still it doesn't calculate correctly diary summaries.

**Comment by amtriathlon** [comment]
What would be "total time"?

**Comment by jifizipazu** [comment]
So long time without activity so I forget this issue.

Total time is defined by fit-file data format, field is called "timer_time". Definition can be found https://www.thisisant.com/resources/fit/
FIT File Types Description -> 13 Totals File -> 13.1 FIT Messages -> Table 13-1. FIT Messages Contained in Totals File

**Comment by amtriathlon** [comment]
Even when it is easy to add timer_time as User Metric it seems a good idea to add it as built-in and to use it to fix the problem with Time in Zone percentages when there are pauses without records (a.k.a gaps).
I will give it a try.
