### ISSUE TITLE
Date range, trend view - most default date ranges do not include current week data

### ISSUE THREAD

**Issue by nesnahal** [GoldenCheetah/GoldenCheetah#2746]
I'm stumped.

When I select the default ranges I don't always get the current week's rides. The Season that I created that includes the current week in the date range lists the rides in the display summary & charts but the default ranges do not include the current week rides in the display summary or charts.

Here is an example of what ride data is populated verse what I expected to see from the selection (reviewing ride data on 6 Jan 18):

All dates - includes rides from 5 Jan 18 (latest ride) - 02 Jan 10 (first ride entered) ** this is correct**
This year - populates with rides completed on 29 Dec 17 - 02 Jan 17 **expected rides for 2018 (05 Jan 18 - 01 Jan 18)**
This month -  populates with rides completed on 29 Dec 17 - 02 Dec 17 ** expected Jan 18 rides**
Last month - populates with rides completed on 29 Nov 17 - 1 Nov 17 ** expected Dec 17 rides**
This week - populates with rides completed on 29 Dec 17 - 25 Dec 17 ** expected rides for the week of 1 Jan 18 - 6 Jan 18**
Last week - populates with rides completed on 23 Dec 17 - 18 Dec 17 ** expected rides for the week of 25 Dec 17 - 31 Dec 17**

This is the pattern for all the default ranges that it seems to be selecting rides from date range(start) - 7 to date range(end) - 7 and not date range(start) - date range(end).

When I try to use the compare feature using "This Week" GC crashes. Using the compare with ranges that do not include this week (1 Jan 18 - 6 Jan 18) the compare view populates as expected.

Any guidance is greatly appreciated. Thanks, Lane

**Comment by nesnahal** [comment]
Build date: Dec 28 2016
Build id: 3957
Version: V3.4
OS: Mac OS X 10.13

**Comment by amtriathlon** [comment]
I cannot recreate this issue, please test using the last development build and reopen if you can reproduce it.
