### ISSUE TITLE
kcal energy consumption

### ISSUE THREAD

**Issue by philonspecialized** [GoldenCheetah/GoldenCheetah#2748]
call me blind but i cannot find the kcal information. but after a few threads i know that the kj info only shows the real energie for paddeling. i dont know for what this info is usefull so please let me know it. but i and probably many others like to see the kcal infos for my foodplan. 
sorry for my bad english and thanks alot

**Comment by amtriathlon** [comment]
Please use the forum for usage questions, as explained in https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md
