### ISSUE TITLE
CRASH with 3.4 when trying to Share > Share online... to RwGPS

### ISSUE THREAD

**Issue by RJKflyer** [GoldenCheetah/GoldenCheetah#2749]
I have one online Share configured - RwGPS.

If I try to upload any activity to RwGPS using Share > Share online... GC 3.4 crashes.

Data selected is the default set of Power, Cadence, Altitude, HeartRate

**Comment by liversedge** [comment]
is this still present in 3.5 dev?

**Comment by liversedge** [comment]
no feedback so closing
