### ISSUE TITLE
Metric trends formula graphs a straight horizontal line when working with a vector of over 100 activities

### ISSUE THREAD

**Issue by ward** [GoldenCheetah/GoldenCheetah#2751]
*Apologies if this has been reported before. I feel like I have seen it pass by in the mailing list at some point, but am not able to find either the mailing list post or an issue about it.*

## Use case

I am trying to have a rolling total show over certain date ranges. For this I add a formula graph in a metric trend tab with the following code:

```
Distance[[Date-30:Date]]
```

and aggregating as Average. This works up to a point.

## Issue

Once past a certain threshold, the graph will give up and end up drawing a straight horizontal line for the remainder of the graph. As far as I can tell, this threshold is having over 100 activities in the vector returned by the `Date` range (just change that 30 to 150 or so to test). You can see this more clearly if you use `count()` around the formula to return the count rather than the sum of the vector. Even if at a later point in that graph, the vector should return fewer than 100 activities again, it will still show just the horizontal line.

Using filters to restrict the number of activities that might appear in the vector does not change anything. I assume filtering is done after the vector failure.

## Source Location

I have not built from source, so I could be mistaken, but the issue seems to be in the [DataFilter](https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/Core/DataFilter.cpp#L2928)'s `case Leaf::Vector` and the snipping that happens there. From what I can tell, it seems to be, at least partially, by design.

* Is there a strong reason for limiting vectors to 100 activities?
* Besides the 100 activity limit design decision, I would (somewhat) expect the graph to "fix" itself later on at least, once the result is fewer than 100 activities again. This may be a bug regardless of design decisions.

**Comment by liversedge** [comment]
The vector is not being truncated.
The "snips" are cached computations, following the classic functional programming "memoization" pattern.

**Comment by ward** [comment]
Then I do not know what the cause is, but it does still happen regardless :P Any other information that I could provide and which could be useful?

**Comment by amtriathlon** [comment]
IMO the problem is not a truncation one, but the memorization catching a static value for dynamic expression, IOW the signature is constant so the cached value too but the real value can change for an expression s.t. sum(Distance([[Date-120:Date]])

**Comment by liversedge** [comment]
Yes, that makes sense. Its a tricky problem to solve!!!
-- maybe for now we should disable it.

**Comment by liversedge** [comment]
cool.
