### ISSUE TITLE
Show Tooltips for metrics everwhere

### ISSUE THREAD

**Issue by Genussradler** [GoldenCheetah/GoldenCheetah#2754]
for a new user it would be helpfull to have tooltips with an explanation for every metric that is shown somewhere in the software. Especially for abbreviations. So you don't have to look for every metric in the option dialog you don't know.

**Comment by amtriathlon** [comment]
In https://github.com/GoldenCheetah/GoldenCheetah/commit/e075008689f48710b216cbc6b5eb2381b1fd803b tooltips were added to all metrics and parameters in Ride Summary to show the corresponding descriptions.
