### ISSUE TITLE
Add Direct navigation to year/month on Diary Calendar

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#2756]
When you have several years of data it is very slow to move month to month on Activities view and, while filters using Date comparisons solve this issue, they are not that intuitive for new users.

**Comment by amtriathlon** [comment]
I looked at this more in depth and I was not satisfied with the solutions I found to the original issue, additionally the scroll bar on Activities view already provides a way to move faster.
In Diary view that possibility is not available and the full calendar UI is more amenable to allow direct change of month/year.

**Comment by sanfordhk** [comment]
does this really work? I do not see this new navigation on the 3.5 RC1 Windows nor Mac builds..

**Comment by amtriathlon** [comment]
In Diary View full calendar now you can edit month/year and press enter for direct navigation or use the spindles on the right to step through years:
![DiaryCalendar](https://user-images.githubusercontent.com/1444784/67011577-472f8c00-f0c6-11e9-9213-4afdc44ec214.png)
In Activity View the mini calendar is unchanged but the navigator handle has a minimum size to allow fast movement even when you have a lot of activities, in my case it was unusable before this change:
![RideNavigator](https://user-images.githubusercontent.com/1444784/67011834-b2795e00-f0c6-11e9-8940-9bc5cb4e2b4a.png)

**Comment by sanfordhk** [comment]
Okay I got it now... I was looking at the mini calendar (somehow the calendar view was deleted from my diary view). I think the change to the navigator handle could have caused a minor UI bug in the activity navigator though. It seems that there is not enough space to display the last activity in the list if one has been imported in the current session. The next GC startup fixes this.
![Screen Shot 2019-10-17 at 10 13 57 PM](https://user-images.githubusercontent.com/8951463/67022832-70870100-f134-11e9-8268-b8e8daa8299f.png)

**Comment by amtriathlon** [comment]
I think that is this pre-existing issue: https://github.com/GoldenCheetah/GoldenCheetah/issues/3074
