### ISSUE TITLE
Popup Menu Icon on OSX Search is Badly Scaled (Cosmetic)

### ISSUE THREAD

**Issue by arunh** [GoldenCheetah/GoldenCheetah#2759]
Search box on latest master code, compiler with Qt 5.10 is rendering like this on OSX:

![screen shot 2018-01-22 at 17 40 34](https://user-images.githubusercontent.com/804578/35239390-4320b1f4-ffa8-11e7-9970-8cee0507d585.png)

It appears fine on Windows so fix created to correct stylesheet only for OSX as this appears to be a single-platform issue. Result of code fix is:

![screen shot 2018-01-22 at 17 42 28](https://user-images.githubusercontent.com/804578/35239481-7d7db73e-ffa8-11e7-8250-069efa0ade13.png)

I'm not sure this is the perfect solution, but it's a lot nicer that it looked before!

**Comment by bwalding** [comment]
These little cosmetic fixes add up over time - everything looks a lot more polished!

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/pull/2760/commits/301194000fefe3861e1adf87a550f3b822931379
