### ISSUE TITLE
[Old 148] Interval Mapping in Aerolab

### ISSUE THREAD

**Issue by grauser** [GoldenCheetah/GoldenCheetah#276]
Added by Andy Froncioni about 2 years ago. Updated over 1 year ago.
## Description

This issue regards the ability to tag intervals in Aerolab according to virtual elevation protocols. Out-and-backs and loops are the common forms of ride protocols.

This feature requires 2 components: "Interval tagging" and "Interval mapping".

1) Interval Tagging:
In the interval selection context menu, intervals can be tagged as "OUT", "BACK", or "LOOP".

2) Interval Mapping:
OUT intervals are displayed in Aerolab "as is". BACK intervals are displayed mirrored about the turnaround point so that they can be compared to the OUT interval. LOOP intervals are all plotted as superimposed graphs.

design_review_28_09_2010.jpg (43.1 kB)   Andy Froncioni, 10/03/2010 08:43 pm
tag_interval.jpg (150.3 kB)   Andy Froncioni, 10/03/2010 08:44 pm
## History
- 1 Updated by Andy Froncioni about 2 years ago
  Assignee set to Andy Froncioni
## 
- 2 Updated by Andy Froncioni about 2 years ago
  File design_review_28_09_2010.jpg added

The mapping of rides can be seen in the attached file (or questionable clarity :-) )...
## 
- 3 Updated by Andy Froncioni about 2 years ago
  File tag_interval.jpg added

Andy Froncioni wrote:

The mapping of rides can be seen in the attached file (or questionable clarity :-) )...

Tagging and mapping, that is...
## 
- 4) Updated by Mark Liversedge over 1 year ago
  Target version set to 3.1

**Comment by amtriathlon** [comment]
I am closing this since it was subsumed by https://github.com/GoldenCheetah/GoldenCheetah/issues/3561
