### ISSUE TITLE
Re-order charts in 'Trends', 'Diary' etc.

### ISSUE THREAD

**Issue by Hezelnutt** [GoldenCheetah/GoldenCheetah#2763]
Hi, 

I would like to reorder the charts for the 'Trends', 'Diary' etc. views.

To my knowledge this is not possible. This is quite a nuisance. New charts are always placed at the end of the list, sometimes it is more helpful to have them at a different location.

If this is already possible but I am not aware of it, I would be very glad to know ;)

**Comment by amtriathlon** [comment]
Duplicated of https://github.com/GoldenCheetah/GoldenCheetah/issues/1112, please read the contributing guidelines before open new issues.
