### ISSUE TITLE
aproximate power calculating

### ISSUE THREAD

**Issue by IlGehring** [GoldenCheetah/GoldenCheetah#2766]
I have an idea to make the power calculation more exactly, for example for velomobils.
Like the "Kreuzotter"-Calculator (http://infotom.de/kreuzotter/#) we need not only a field for
rolling resistance of course also a field for air resistance to calculate a power.

**Comment by mtbkeith** [comment]
how about just using your own power as a starting point? Say, if you rode one section before calculate based on w/kg & time difference?

**Comment by amtriathlon** [comment]
In v3.5 the CdA can be customized:
![estimatepower](https://user-images.githubusercontent.com/1444784/36422658-cb3af142-161b-11e8-90bc-3a24ac5b49d3.png)
you can test it using the last dev build from https://github.com/GoldenCheetah/GoldenCheetah/releases
