### ISSUE TITLE
Installing 3.5 DEV1710 on Ubuntu 16.04 and similar

### ISSUE THREAD

**Issue by mlanner** [GoldenCheetah/GoldenCheetah#2770]
I tried to install 3.5 DEV1710 on elementary OS 0.4.1 (Loki), which is based on Ubuntu 16.04 LTS. It didn't really work. After a bit of digging I figured out that it wasn't happy because of an old version of R. What it seems to want is 3.4.x.

Here's what I needed to do to get it working:

```
sudo apt install software-properties-common python-software-properties
sudo add-apt-repository ppa:marutter/rrutter
sudo apt update
sudo apt install vlc r-base-core libgstreamer libgstreamer-plugins-base0.10.0
sudo ln -s /usr/lib/x86_64-linux-gnu/vlc /usr/lib/vlc
```

You may want to add this to installation instructions and dependencies somewhere.

Thanks for great software!

**Comment by liversedge** [comment]
Thanks we will add this to the README when we push out a release.
