### ISSUE TITLE
GC cannot connect to BTLE device

### ISSUE THREAD

**Issue by lnussbaum** [GoldenCheetah/GoldenCheetah#2771]
I'm trying to use BTLE to connect to various devices (HR, Tacx Vortex). This fails with 3.4. Since there were some changes in git, I also tried with V3.5, and it also fails.

When connecting manually using hcitool lescan, then gatttool -t random -b .... -I, it seems to work fine.

I'm not sure how I can help to debug this further.

I noticed that gatttool with -t random works, but without it, it doesn't. but looking at GC's code, the random address flag seems to be set correctly?

**Comment by lnussbaum** [comment]
so I started to look into this.

It might be a stupid question, but shouldn't we use BT40Controller rather than ANTlocalController in AddPairBTLE::initializePage ?

https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/Train/AddDeviceWizard.cpp#L894

**Comment by acht** [comment]
searching for BTLE devices is only working in case a ANT+ dongle is connected (at least for me).

**Comment by liversedge** [comment]
There is no bug. ANT+ FE-C is over ANT. We support BTLE devices like HR and Cadence, but not trainers since there is no standard yet (to my knowledge). If one is published as a GATT profile we will support it.

**Comment by Frono** [comment]
Maybe not bug as apparently the software is designed this way. However, if feel it to be counter-intuitive. As someone new to GoldenCheetah,  I expected that the software would be able to find and add Bluetooth sensors without having to purchase an ant+ dongle for the computer. After searching and finding this post I ordered an ant+ dongle for my computer. After plugging in the dongle GoldenCheetah found all my Bluetooth sensors... 
Is it a difficult thing to have the software look for both at the same time?

**Comment by jkms** [comment]
I believe I have just discovered this as well. I haven't ordered an ANT+ dongle yet (and I don't really want to, as I don't have any ANT sensors).

+1 for the ability to add BTLE devices without an unneccessary  ANT+ dongle.

**Comment by merdoks2** [comment]
I believe there is bluetooth standard for smart trainers ( FTMS) https://support.kinomap.com/hc/en-us/articles/360015335632-What-is-the-FTMS-protocol-   
It would be awesome if it would be available

**Comment by Frono** [comment]
I went and looked at [bluetooth.com](https://www.bluetooth.com/specifications/gatt) GATT specifications and found: 

-FTMP - Fitness Machine Profile
-FTMS - Fitness Machine Service

Both have been adopted and are listed as active. 
I'm not sure if these are what was needed, but they sound like it...

**Comment by Frono** [comment]
@jkms 
If this helps, you don't need to get the expensive garmin ant+ adapter to get GC to find your bluetooth devices. [This cheap one](https://www.amazon.com/gp/product/B01M3VQP6Z) worked when I was testing on my old Mac Mini. It is only $15, and you can just unplug it and put it in a drawer after you have paired your bluetooth sensors...

**Comment by dtawom** [comment]
Same issue here, Polar OH1, GC won't find it.  What really irks me is I purchased an actual Garmin ANT + for use with an old smart watch for heart rate monitoring and ended up going a different direction because the watch was garbage.  Now that I need the Ant + dongle I can't find it so I guess I'll drop another $15 on the one Frono linked, thanks man, 20 bucks is 20 bucks.  I know the second I confirm the order I'm going to find the Garmin receiver.

**Comment by jeacott1** [comment]
2 years on and this is still open?

**Comment by amtriathlon** [comment]
I can reproduce this issue with v3.5 RC1: a scosche rhythm+ is not found in BTLE without an ANT+ dongle but it is found after connecting one.

**Comment by amtriathlon** [comment]
Looking at AddDeviceWizard it seems to need the presence of an ANT+ dongle and dual (BTLE/ANT+) sensors s.t. the Scosche Rhythm+ I tested.
If I am right pure BTLE sensors could not be detected, even in the presence of an ANT+ dongle, st. the Polar H7 reported in https://github.com/GoldenCheetah/GoldenCheetah/issues/2983, but I don't have one for testing.

**Comment by amtriathlon** [comment]
I did some more tests and to confirm that, even when AddDeviceWizzard will never show a pure BTLE device (or a Dual device without an ANT+ dongle), if you just continue the device setup process the next time you start this device all compatible BTLE devices (Hr, Power and Speed/Cadence) will be automatically scanned and activated.
Specifically I could setup and use my Scosche Rhythm+ without an ANT+ dongle in a Mac Book Air with High Sierra and GC v3.5 RC1.

**Comment by dominickp** [comment]
I'm new to GC and I don't exactly follow the details of this thread. But I'm trying to pair a Polar H10 with bluetooth to GC (I only have a bluetooth dongle, not ANT+). I have it paired in Windows and Windows detects it as a heart rate monitor but the Bluetooth option in the "Add Device Wizard" doesn't find anything and does not let me proceed with setup.

I understand that a fix was made in the recent RCX. I installed that to test it out and now the "Add Devize Wizard" doesn't show Bluetooth devices as an option anymore even though the PC does support bluetooth via this dongle and the option is enabled in Windows.

**Comment by amtriathlon** [comment]
Sorry but the fix is for MacOS and Linux, GC doesn’t have Bluetooth support on Windows yet.

**Comment by dominickp** [comment]
Thanks for the reply. Will ANT+ work with Windows though?

**Comment by amtriathlon** [comment]
Yes

**Comment by eanema** [comment]
I have just downloaded and compiled the master branch (4b53b2466) in an attempt to connect to my Elite Suito using Bluetooth. I do not have an ANT+ dongle. I am new to Golden Cheetah so I'm not positive how to use the software, but I added a device, selected bluetooth, it searched, then offered me a screen with heart rate/speed+cadence/power and auto-detect on device startup. I continued to setup the new device, but I don't know how to trigger connecting to it. Can someone point me in the right direction on how to get this connected?

FYI I am running Ubuntu 18.04/32 bit on an ancient dell laptop circa 2006.

**Comment by amtriathlon** [comment]
Just select the created device in the left sidebar and press the red button on the lower panel to start and search for sensors.
There is an official build including this fix you can download from the Assets part of https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/V3.5-RC2X and a users forum to get help: https://groups.google.com/forum/#!forum/golden-cheetah-users
