### ISSUE TITLE
V3.5 segfaults on startup on Debian 9 stretch

### ISSUE THREAD

**Issue by lnussbaum** [GoldenCheetah/GoldenCheetah#2772]
Hi,

On debian 9 "stretch", GC 3.5 segfaults on startup:

(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /usr/bin/GoldenCheetah 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffddada700 (LWP 17191)]
[New Thread 0x7fffd427e700 (LWP 17192)]
[New Thread 0x7fffd3a7d700 (LWP 17193)]

Thread 1 "GoldenCheetah" received signal SIGSEGV, Segmentation fault.
0x00000000004b700f in RGraphicsDevice::Close(_DevDesc*) ()
(gdb) bt
#0  0x00000000004b700f in RGraphicsDevice::Close(_DevDesc*) ()
#1  0x00007fffd0414e06 in Rf_selectDevice () from /usr/lib/R/lib/libR.so
#2  0x00000000004b89df in RGraphicsDevice::createGD() ()
#3  0x000000000049f817 in RTool::RTool() ()
#4  0x00000000004733f5 in main ()

retrying several times, I could get it to start (hence my other issue about BTLE). I thought I would report this anyway.

**Comment by liversedge** [comment]
Its likely a mismatch on R versions.

start with --no-r
