### ISSUE TITLE
error on Debian package installation: /var/lib/dpkg/info/goldencheetah.postinst: line 4: /usr/lib/vlc/vlc-cache-gen: No such file or directory

### ISSUE THREAD

**Issue by lnussbaum** [GoldenCheetah/GoldenCheetah#2773]
Hi,

I get this error on debian package installation:
```
/var/lib/dpkg/info/goldencheetah.postinst: line 4: /usr/lib/vlc/vlc-cache-gen: No such file or directory
```
Apparently, on amd64, this file is now in
libvlc-bin: /usr/lib/x86_64-linux-gnu/vlc/vlc-cache-gen

is the way those Debian packages are generated documented somewhere? Maybe I could help fix this properly (I'm a debian developer)

**Comment by amtriathlon** [comment]
Can you check if this https://github.com/GoldenCheetah/GoldenCheetah/issues/2770 fixes the issue?
