### ISSUE TITLE
GC 3.5 Crash on launch attempt (existing profile)

### ISSUE THREAD

**Issue by surfer3287** [GoldenCheetah/GoldenCheetah#2774]
Just updated to OSX High Sierra 10.13.3.  GC 3.5 crashes when I attempt to launch the application using the only existing profile.  It will allow me to create a new profile (I created one called "Test" and it allowed me to enter DOB, weight, etc.).  However, when I attempted to open my regular profile once GC had launched successfully, it crashed immediately.  

Not sure what exactly to share from the problem report, so I hope what I have attached helps.  If not, please let me know what part I should copy/paste to assist.

Ryan

![screen shot 2018-02-01 at 12 53 24 pm](https://user-images.githubusercontent.com/36048581/35694379-2be353b2-074f-11e8-89e7-b9ee3bef4ddd.png)

**Comment by liversedge** [comment]
New High Sierra builds released.
