### ISSUE TITLE
Latest dev build fails due to PythonEmbed.h

### ISSUE THREAD

**Issue by WaterworthD** [GoldenCheetah/GoldenCheetah#2775]
Hi,

It looks to me like the latest dev build fails when GC_WANT_PYTHON isn't defined. If not set, Python/PythonEmbed.h isn't included in HEADERS (src.pro) which causes a compilation error in DataFilter.cpp as PythonEmbed.h is included regardless of GC_WANT_PYTHON

main.cpp and GcCrashDialog.cpp also include Python/PythonEmbed.h 

Regards
Dave

**Comment by WaterworthD** [comment]
The build also fails if GC_WANT_R isn't define. 

It would be useful to update the INSTALL-WIN32 guide for R and Python. I took notes as I went so feel free to merge the following in:

# Python

# Download python 3.6 installer from https://www.python.org/ftp/python/3.6.0/python-3.6.0-amd64.exe
# install for all users (C:\Program Files\Python36)
# download sip-4.19.7.zip from http://www.riverbankcomputing.com/software/sip/download
# unzip to c:\dev\sip-4.19.7
# from CMD prompt
> CALL "C:\Qt\Qt5.8.0\5.8\msvc2015_64\bin\qtenv2.bat"
> CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
> CD c:\dev\sip-4.19.7
> "C:\Program Files\Python36\python" configure.py
> nmake

# R

# Download R 3.4.3 from https://cran.r-project.org/bin/windows/base/R-3.4.3-win.exe
# Run installer
# from CMD prompt
> SET R_HOME = C:\Program Files\R\R-3.4.3
> R
> install.packages('Rcpp')
> install.packages('RInside')
> quit()

**Comment by liversedge** [comment]
Will fix code to honor GC_WANT_PYTHON and GC_WANT_T in DataFilter
