### ISSUE TITLE
checksum for releases

### ISSUE THREAD

**Issue by philipishungry** [GoldenCheetah/GoldenCheetah#2778]
can you please add checksums for releases

something like the way it is done here:
https://github.com/ethereum/mist/releases

**Comment by liversedge** [comment]
fair shout. will use:
```
$ shasum -a 256 
```

**Comment by philipishungry** [comment]
hi thanks for the update with new Feb dev release. 
is it possible to get checksum for the source,
thanks

**Comment by liversedge** [comment]
we don't publish those, guthub does. I guess you could raise a request on them?
