### ISSUE TITLE
Trouble with High Sierra

### ISSUE THREAD

**Issue by plodunov** [GoldenCheetah/GoldenCheetah#2779]
Hello. Yesterday all work is OK, but now have a bug after Strava synchronization:
![2018-02-06 9 53 45](https://user-images.githubusercontent.com/36186453/35847431-8258e9ca-0b2b-11e8-9b3d-a192e59e6841.jpg)

Please, help me!)

**Comment by liversedge** [comment]
I'm upgrading the mac build environment to get a high sierra build out.
Should be in the next week or so.

**Comment by liversedge** [comment]
The new builds will fix this issue - also please check your font choice in preferences.

**Comment by plodunov** [comment]
Thanks! How I can check the font? 
And what is the approximate time to update high sierra?
