### ISSUE TITLE
"Fix Elevation Data Not Possible : Monthly Free Plan Limit Exceeded"  ?

### ISSUE THREAD

**Issue by rgeorge1985** [GoldenCheetah/GoldenCheetah#2780]
Ale / Mark,

Please explain what the attached popup messages mean. It does this when I manually import .tcx files off Polar Flow. Never spotted this one before, so quite new to me. These errors has been happening since the last few days although the importing process is not affected. Is it a bug? Thanks.

![capture](https://user-images.githubusercontent.com/23737973/35897330-1a40d7bc-0bda-11e8-8b9e-afa5ce3a5319.JPG)

![capture1](https://user-images.githubusercontent.com/23737973/35897427-93fc1742-0bda-11e8-9929-640732e1a130.JPG)

Specs of GC : 
Build date : Aug 3 2017 
Build Id : 3963
Version : v3.5-DEV1708
DB Scheme : 142
Metrics : 353
OS : Win

**Comment by Joern-R** [comment]
No, ist not a bug - the Web Service we are using has limited free calls.
Please switch of the "Fix Elevation" Feature during Import, the the message
will not occur.
We changed the code to a) report the quota problem (which is something we
can't change, despite someone finds a free Web Service or a service with
higher quotas,
b) make sure that the import is not stopped by the problem.



2018-02-07 4:49 GMT+01:00 Ron <notifications@github.com>:
