### ISSUE TITLE
GC 3.5 1802 Metrics Division return "inf"

### ISSUE THREAD

**Issue by PonessM** [GoldenCheetah/GoldenCheetah#2787]
After Upgrade for Testing, the Metric Calculation of Duration/3600 returns a inf.

Example:
Duration: 2890;
Duration/1: 2890;
Duration/10: 40642314066475723046607737872873824
Duration/1000: inf
Duration/3600: inf

**Comment by liversedge** [comment]
Where?

**Comment by PonessM** [comment]
at Custom metrics:
sample Code
{
value{ Duration/3600)}
}

**Comment by liversedge** [comment]
Is Duration non-zero ?

**Comment by PonessM** [comment]
Duration is in non Zero, in the last activity (swim): 2890.

**Comment by PonessM** [comment]
In another Activity, the Duration ist 3630; The Result of Duration/3600 is also inf

**Comment by liversedge** [comment]
can you share the file?

**Comment by PonessM** [comment]
<img width="661" alt="bildschirmfoto 2018-02-17 um 15 28 21" src="https://user-images.githubusercontent.com/19608169/36341991-5f1c9522-13f7-11e8-8e14-7a9f4bb192a3.png">

[activity.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/1733745/activity.txt)
Format ist GC JSON

**Comment by PonessM** [comment]
Did some Experiments, because the Charts Formula are also broken. I have a Chart that simple show the daily TriScore as a bar, an 3 graphs, one for easy, which ist just the lts(TriScore)*2, one with lts(TriScore)*3 an one with *5.

So i take the last Bike Activity with Power Data an typed test the formula with the custom Metric Window:

Code:
{
value {
#TRIMP_Zonal_Points; # Result was 76
#lts(TRIMP_Zonal_Points); #Result was 28
#lts(TRIMP_Zonal_Points)*2; #Result was 0
#lts(TRIMP_Zonal_Points)^2; #Result was 0
28*2 #Result was 0;
}
}

**Comment by amtriathlon** [comment]
What is your config? Can you try switching to English and test again?

**Comment by PonessM** [comment]
I switch to English, same results.

Setup:
MacBook Pro 13" w. Touchbar late 2016, 3,3 GHz i7 with 16 GB Ram
High Sierra, 10.13.3

Garmin Fenix 3 HR, with Hrm Run, Garmin Speed und Cadence Sensor for BIke
Power over Elite Real Turbo Muin Interactive Trainer 

Fit Source: mostly Garmin. For Bike, current Zwift.

Config for GC, main Tab
<img width="690" alt="bildschirmfoto 2018-02-21 um 12 27 19" src="https://user-images.githubusercontent.com/19608169/36477753-a05840d2-1702-11e8-9fb1-6e7fdd8d6492.png">

**Comment by amtriathlon** [comment]
The data filter seems to be broken in v3.5 18.02 MAC build,  there is a discussion in the corresponding thread at the users forum

**Comment by amtriathlon** [comment]
Fixed in the update build, see https://groups.google.com/forum/#!topic/golden-cheetah-users/9oFmCjr1h7o
