### ISSUE TITLE
Suunto and Tacx Speed & Cadence Sensors (inaccurate speed) 

### ISSUE THREAD

**Issue by tglaub** [GoldenCheetah/GoldenCheetah#2789]
My Ant+ Speed & Cadence Sensors  from Suunto and Tacx (Suunto Bike Sensor, TACX T-2015) are showing inaccurate speed in training mode, cadence is correct. It seeams that the displayed speed is switching every second between correct and half of the speed.

**Comment by liversedge** [comment]
don't pair the S+C sensor if using an FE-C device.

**Comment by tglaub** [comment]
I dont pair them simultaneously. The S&C sensors are mounted on different bikes.
