### ISSUE TITLE
Messagebox when suceess in HRV measurement download

### ISSUE THREAD

**Issue by Portaner** [GoldenCheetah/GoldenCheetah#2790]
It would be nice, that at the end of the download from HRV-Files a message box appears. At the moment I do not know if the download "suceess".

![hrv_measurements_download](https://user-images.githubusercontent.com/23188632/36353832-bdacbc1e-14cb-11e8-82dd-a2a244a156d1.png)

**Comment by amtriathlon** [comment]
In the success case you will see the progress bar going to 100%:
![downloadhrvmeasures](https://user-images.githubusercontent.com/1444784/36354572-542af46a-14b5-11e8-9477-befd3f2f77d1.png)
Otherwise an error message box will pop-up, s.t.
![downloadhrvmeasureserror](https://user-images.githubusercontent.com/1444784/36354599-b2a92cf0-14b5-11e8-95f8-4dd85f9c997f.png)

**Comment by Portaner** [comment]
sorry, but I don't see no any text in the field (MacBook Air 13" with macOS High Sierra, Version 10.13.3)

![hrv_dialog_after_download](https://user-images.githubusercontent.com/23188632/36633276-b04c2ba6-1992-11e8-8147-1a78b4ece6bb.png)

**Comment by Joern-R** [comment]
Thanks for pointing that out - (we see the percentage on Windows and on Linux) - but for Mac it seems to be disabled by default - here a snippet from the documentation:

> textVisible : bool
> This property holds whether the current completed percentage should be displayed
> This property may be ignored by the style (e.g., **QMacStyle never draws the text**).

So it looks like we need to add something (at least) for Mac to report on the end of the import.

**Comment by liversedge** [comment]
are you fixing this Joern?

**Comment by Joern-R** [comment]
Yes - will do this sometime next week.

**Comment by Joern-R** [comment]
Fixed via https://github.com/GoldenCheetah/GoldenCheetah/pull/2821/commits/a2ace2e008b3c57b8db88ba191c9a20a473fbcc6
