### ISSUE TITLE
Tooltip on Vo2Max header to explain that is based on a 5 minute sample

### ISSUE THREAD

**Issue by hnaess** [GoldenCheetah/GoldenCheetah#2793]
This thread explain the calculations behind the Vo2Max:
https://groups.google.com/forum/#!topic/golden-cheetah-users/sMvaY8czTZE

I suggest that the header for the Vo2Max (ex. in Trends > Summary) have a tooltip that explains that this is based on a 5 minute sample.

Background: Based on a FTP I did today, I got a high Vo2max at my Garmin, but low on GC. Was a bit suprised, and had to Google it. Would be easier if it was included in the UI. (or alternative way to calulcate it, ex. in the Tools menu)

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/pull/2794/commits/e075008689f48710b216cbc6b5eb2381b1fd803b
