### ISSUE TITLE
connecting GC to dropbox

### ISSUE THREAD

**Issue by sozzen** [GoldenCheetah/GoldenCheetah#2795]
Hi when I try to setup GC on my laptop I want to connect it to dropbox. However when i try to auth it I dont get any image in the CAPTCHA check. Not sure if its a win10 issue, or javascript? 
I use win10 and GC version 3.4 64 bit.

**Comment by amtriathlon** [comment]
The DropBox API v3.4 used is no longer available, dev builds for v3.5 use the new DropBox API, you can download them from https://github.com/GoldenCheetah/GoldenCheetah/releases
