### ISSUE TITLE
Add Feathub voting (feature request)

### ISSUE THREAD

**Issue by mow4cash** [GoldenCheetah/GoldenCheetah#2796]
I was thinking maybe a Feathub for GC would be beneficial. I'm not sure if the devs are too busy to take on other ideas. If GC is looking for community feedback this would be great to have. Ether way it's free, easy to setup, and can't hurt IMO.

**Comment by liversedge** [comment]
Do you know if it uses Github issues or do we need to replicate them?

**Comment by mow4cash** [comment]
They need to be replicated however anyone can make a feature request and vote.  You can also simply add a little chart to the main GC github page showing the the top requests from feathub and a link to vote or add new requests. I could pick some current issues from Github to seed feathub until it catches on. If feathub catches on people should stop using github for requests and you could eventually close open requests in github. Most projects still use both requests systems in a way but feathub could cut down on simple requests made to github.

"Please submit and vote on feature requests on FeatHub instead of opening a Github Issue" Could be added

**Comment by liversedge** [comment]
shame. would be nice to get a voting system on top.

**Comment by mow4cash** [comment]
You and a lot of other people want the same. It's the second most requested feature on Feathub, maybe one day it will happen.
https://feathub.com/feathub/feathub

**Comment by liversedge** [comment]
will go vote for it :)

**Comment by amtriathlon** [comment]
Why not to use reactions to github issues for this purpose?
It allows sorting by reactions s.t. https://github.com/GoldenCheetah/GoldenCheetah/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
