### ISSUE TITLE
no support for R 3.3.3 with dev 1802 anymore?

### ISSUE THREAD

**Issue by mondoshiwan** [GoldenCheetah/GoldenCheetah#2798]
on a Mac OS 10.10 machine i noticed that R couldn't be activated anymore. At the Version menue i found the hint:
![bildschirmfoto 2018-02-23 um 12 58 18](https://user-images.githubusercontent.com/23431166/36593514-38a6e2d8-189a-11e8-95f8-a7ff1206ea15.png)
seems like GC is looking for R 3.4.3…

the dev build 3.5 1710 was running fine with R 3.3.3 on a Yosemity machine. Version 3.4.3 is only running above MacOs 10.11

**Comment by liversedge** [comment]
thats right. We build with 3.4 and only support 3.4 or higher.
It is possible to build for 3.3 if you want that support.
We are tied to the binary compatibility changes in R and had to draw the line somewhere.
If you update to El Capitan you will be able to run 3.4+ ?

**Comment by mondoshiwan** [comment]
on that specific machine i can't upgrade due to older audio hardware and drivers. so a 3.3 support would be nice, or i have to stick with dev 1710 there

**Comment by liversedge** [comment]
Or run without R embedded, python support is available from 3.5
