### ISSUE TITLE
High DPI issue

### ISSUE THREAD

**Issue by mow4cash** [GoldenCheetah/GoldenCheetah#2800]
![capture](https://user-images.githubusercontent.com/16341157/36678751-9439b980-1adf-11e8-9608-7410b561e051.PNG)
Is this the correct way to have GC displayed correctly on a 4k resolution tv? I thought there was some dpi fixes so I wasn't sure if the dpi was supposed to be auto correcting. The setting in the picture does work for me. 
v 3.5 dev1802

**Comment by liversedge** [comment]
You should use the native scaling in GC to avoid nasty rendering artefacts.
Under Tools > Options > Appearance there is a slider to adjust font scaling.

**Comment by mow4cash** [comment]
![capture](https://user-images.githubusercontent.com/16341157/36680138-f53a6a56-1ae2-11e8-87c4-3fff39631251.PNG)This is what my screen looks like when I use the native scaling in GC by itself with the slider set to max.

**Comment by mow4cash** [comment]
![capture](https://user-images.githubusercontent.com/16341157/36680713-8f50f4ba-1ae4-11e8-8863-8ee66a1e2dc4.PNG)
This is with native GC scaling set to medium low and windows overide scaling enabled.

**Comment by liversedge** [comment]
Are you running 3.5 1802 ?

**Comment by mow4cash** [comment]
Yes 3.5 1802

**Comment by liversedge** [comment]
You have selected maximum scaling for native?
Please restart GC after doing so as toolbar resizing seems to still be broken in QT5.9
