### ISSUE TITLE
REST API queries remain in memory

### ISSUE THREAD

**Issue by podiumbound** [GoldenCheetah/GoldenCheetah#2801]
I have been doing a bunch of work lately making fairly extensive use of the REST API queries. I found  that GoldenCheetah was using 30GB of memory at one point following analysis of a bunch of files. I don't know if I'm not using it properly (most likely), or if there's no garbage collection once data has been requested. Figured I would flag it here either way.

**Comment by liversedge** [comment]
Thanks will investigate.

Which API do you use the most?

**Comment by podiumbound** [comment]
RESTful API, using R external to GC. I use the httr package to get csv and json activity data, because asychronous requests were getting me into trouble using RCurl.

Mike

**Comment by liversedge** [comment]
have put into parking lot unless someone screams.

**Comment by amtriathlon** [comment]
It looks like this could be a sequel of https://github.com/GoldenCheetah/GoldenCheetah/issues/4248. It would be interesting to know if it still happens after that one was fixed.
