### ISSUE TITLE
Nokia Health (Withings) Scale import not working in 1802

### ISSUE THREAD

**Issue by bobsica** [GoldenCheetah/GoldenCheetah#2802]
Sorry to re-open this problem [#2786](https://github.com/GoldenCheetah/GoldenCheetah/issues/2786), but I am now using 1802 and still get the following error (even after removing the Withings account and restarting) as in the previous version: 

> {"status":342,"error":"The signature (using Oauth) is invalid"}

I viewed [#2764](https://github.com/GoldenCheetah/GoldenCheetah/issues/2764) as was suggested previously but that didn't help. Is there anything I can do to help debug this? Perhaps I have some token access file that needs to be manually deleted?

**Comment by planetawylie** [comment]
@bobsica 
Hi there, what did you do to resolve this? I'm on 1802, and clicking the 'Authorize' button does nothing. Just sits there.
Tx

**Comment by bobsica** [comment]
I found out it will be fixed in the next update.

**Comment by fabbr** [comment]
Is this a Nokia API problem @bobsica ? I have being trying to pull data from the API and all I get is: 
{"status":342,"error":"The signature (using Oauth) is invalid"}

**Comment by SSTPIERRE2** [comment]
@fabbr @bobsica Hi there, I've also been searching around the net for a solution. I've had code getting measurement data via Nokia API for months that suddenly started hitting this 342 error. Did something change in their API that I may need to change my code for?

**Comment by bobsica** [comment]
Sorry I don't know beyond what I've said: it was working in 1802, Noika changed something, now it doesn't work but Mark Liversedge said in the next release it would be fixed. I imagine that will be soon.
