### ISSUE TITLE
ErgDB download is broken

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#2803]
The base URL redirects to https which breaks the download.
Easy to fix: use https instead !

**Comment by samgiest** [comment]
Still broken in GoldenCheetah-3.5-DEV1903
uses url "https://www.73summits.com/ergdb/" which doesnt work needs to be https://www.ergdb.org/ or http://www.ergdb.org/

**Comment by sergiogoro** [comment]
> Still broken in GoldenCheetah-3.5-DEV1903
> uses url "https://www.73summits.com/ergdb/" which doesnt work needs to be https://www.ergdb.org/ or http://www.ergdb.org/

Can't access here too, same version

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/issues/2963

**Comment by sergiogoro** [comment]
> See #2963

Thanks for replying; but, i can't see the relation.
On #2963 it's the history of the old site being down, and a new one coming up, and user emails and that things.

But, has of now having a working site (this: https://ergdb.org/ ) I assumed, the ergdb fiels download was implemented to work with that site.
Maybe i did get it wrong and the download feature isn't going to be implemented with the new site. Why?

Thanks

**Comment by amtriathlon** [comment]
That thread is open to track the status of the new implementation, which is not just to change the URL, and therefore the one to follow to get updates.

**Comment by sergiogoro** [comment]
> That issue is open to track the status of the new implementation, which is not just to change the URL, and therefore the one to follow to get updates.

Ok, Thanks a lot
