### ISSUE TITLE
wrong elevation gain when importing zwift ride

### ISSUE THREAD

**Issue by ckyr** [GoldenCheetah/GoldenCheetah#2807]
I am using version 3.5 and download zwift rides by syncing to strava. Elevation gain is wrong in all rides. Strava shows same value as zwift. How can I fix this?

**Comment by ckyr** [comment]
I now noticed that all rides (including virtual rides from zwift and actual rides) display elevation gain numbers that are significantly different from strava or the cycling computer (for actual rides)

**Comment by ckyr** [comment]
Thank you Joern. Yes, in my experience it doesn't matter how you import the ride into GC, the imported value shown in GC is the same. However, the value in GC is different from the value shown in strava or zwift. Does this make any sense?

**Comment by liversedge** [comment]
This is covered in the FAQ here: https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-METRICS#Why-is-elevation-different-in-GoldenCheetah-to-my-other-training-software--website
