### ISSUE TITLE
Package as a snap

### ISSUE THREAD

**Issue by clauded** [GoldenCheetah/GoldenCheetah#2808]
I was wondering if it would be possible to package GC as a snap : this way, the app can be run on any Linux distribution that supports snap, you're not tied to a specific version of a distro and it's libs and the application can be updated automatically.
Here's some relevant info : https://docs.snapcraft.io/build-snaps/your-first-snap

**Comment by liversedge** [comment]
If you're interested in pursuing this that would be cool. Happy to help but recommend you checkout the Travis setup first.

Cheers

**Comment by clauded** [comment]
The Travis setup seems to be on Mac, I'm on Linux...
I made a partially working snap but I don't have the resources to test it. I'm publishing what I've done so far.
[gc.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/1791151/gc.txt)

**Comment by liversedge** [comment]
Travis supports Linux too .. we stopped doing it but I can't recall why. Possibly because of the overhead not yielding too much value for CI purposes.

**Comment by liversedge** [comment]
will peek at it tomorrow!

**Comment by gcoco** [comment]
Hi, Take a look at:
https://github.com/gcoco/CI-for-GoldenCheetah/blob/Linux-QT5/.travis.yml
Basically how it is build these days. 
I like the idea of the snap as the addition of Python has complicated the build process.
You need to install qttools5-dev-tools to the build so that you get lrelease in the snap.
Ideally we would build a docker image and have snap run in that.

**Comment by clauded** [comment]
I made a few changes to be similar to the work done by @gcoco .
Compilation is done with QT 5.5 (the one built in with snapcraft/ubuntu 16.04). I don't know if GC uses specific stuff in QT 5.8. For now I can't do much more as I don't have what's needed to test. Let me know if I can help.

**Comment by liversedge** [comment]
It needs to be built with 5.9 and there is some interest from end-users to be able to use this to get a binary built.

One other question -- we have a bunch of "secrets" for API keys, is there a way these can be consumed by a snap without making the values public ?

**Comment by clauded** [comment]
To build it with 5.9+, we could do it like you build bc now or when 18.04
is stable, build the snap under 18.04 and use the Qt version that comes
with it (I guess you'll prefer the first option). As for the secrets, if I
understand correctly, it's encrypted in your Travis configuration and
passed as environment variables. If that's the case, I think it can be done
the same way with snapcraft.


Le 17 mars 2018 02 h 43, "Mark Liversedge" <notifications@github.com> a
écrit :

It needs to be built with 5.9 and there is some interest from end-users to
be able to use this to get a binary built.

One other question -- we have a bunch of "secrets" for API keys, is there a
way these can be consumed by a snap without making the values public ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GoldenCheetah/GoldenCheetah/issues/2808#issuecomment-373898882>,
or mute the thread

**Comment by gcoco** [comment]
I've been working with this snap and snap building appears only fully supported at this time in 16.04 (build fails on 17.10). I think I can figure out in the snap to install qt via a tar file and build. My issue I ran into was access to devices via the snap. I couldn't do a download from an olderv powertap via d2xx or ant+ via usb1/2. Have to do some research on how this needs to be setup. Other than that the snap send great. Ran on a few different os with no issue.

**Comment by clauded** [comment]
Have a look here : https://docs.snapcraft.io/reference/interfaces

**Comment by clauded** [comment]
> One other question -- we have a bunch of "secrets" for API keys, is there a way these can be consumed by a snap without making the values public ?
I added instructions in my repo for Travis build of the snap : if you use secure variables for your "secrets" for API keys, then you're good to go.

**Comment by amtriathlon** [comment]
> Have a look here : https://docs.snapcraft.io/reference/interfaces

IIUC the only way to go for the snap to access devices is to modifiy the device access code, including libraries,  is that correct?

**Comment by amtriathlon** [comment]
It seems the limitations to access local IO devices using standard API is too restrictive for GoldenCheetah, currently we are using AppImage which is distribution agnostic and doesn't have those limitations, I will close this due to inactivity.
