### ISSUE TITLE
KPI diagrams: sort by date descending

### ISSUE THREAD

**Issue by Genussradler** [GoldenCheetah/GoldenCheetah#2813]
In the Trends/KPI section it would be helpful to sort the data tables by date descending, so that you always have the latest values on top of the list. When the tables are sorted by date ascending, you always have to scroll down to the latest values. 
If possible, a diagram or user configuration would be nice, so that the user don't have to resort every time again.

**Comment by 3e9b** [comment]
Yes, this is an ongoing frustration of mine.

**Comment by amtriathlon** [comment]
I am closing this since the feature is available in the new Table tiles of v3.6 Overview chart, and it will not be retrofitted to metrics trends charts.
