### ISSUE TITLE
ANT+ connection lost in train mode

### ISSUE THREAD

**Issue by huschauer** [GoldenCheetah/GoldenCheetah#2816]
GC Build date Oct 27 2016, Build id 3944, Version 4.0.0-DEV1607
Ubuntu 2017.10
Train Mode connects to Tacx Neo. Starting training (RLV mode) works well for 2 minutes, then suddenly all data (Power, HR, cadence, speed) freeze and do not come back. Not sure connection is lost or software hangs. Tried two different machines and 3 different ANT+ sticks.
Only running latest stable downloadable 3.4 version for Windows downloaded from website works fine. However, I prefer to use Ubuntu, so would like to see this working in the long run.
If you need any further info, let me know.
BTW, I love GC and am using it since years for tracking and analyzing my data. Thanks you very much for all of this. Great work.

**Comment by liversedge** [comment]
Have you tried the DEB for 3.4 that is available to download on the goldencheetah.org website?

**Comment by huschauer** [comment]
Yes, but it did not install after throwing an error message. I cannot remember from top of my head what the message read exactly. If you need, I will re-try and feedback.

**Comment by huschauer** [comment]
Hi, I have tried to install the .deb again and installation quit having unmet dependencies for libgstreamer0.10-0 and libgstreamer-plugins-base0.10-0. I think both packages are on Version 1.0 in Ubuntu 17.10. As I read from the WWW Ubuntu does no longer provide libgstreamer0.10 packages any more since 16.10. I can confirm this for 17.10, which is what I am running on my machines.

**Comment by riccioclista** [comment]
As a workaround you can manually install libgstreamer0.10 from an older ubuntu version
