### ISSUE TITLE
Slope in RLV mode not used in ride data

### ISSUE THREAD

**Issue by huschauer** [GoldenCheetah/GoldenCheetah#2818]
I have used RLV mode recently and noted that elevation gain is not recorded. As the slope information is there and the machine and GC emulate that quite well, it should be easy to calculate absolute height and elevation gain and save that in the data of the ride. It would add valuable data to the data set and make it more like real world experience. Some of the videos we are riding include steep climbs and it would be great to have the elevation data recorded for the users.

**Comment by liversedge** [comment]
Unless your turbo can fly you are exercising at the same altitude during the workout !
Have put into parking lot.

**Comment by huschauer** [comment]
Thanks, the PGMF file basically provides all the data, other exercise files probably do similarly.
