### ISSUE TITLE
TCX export lacks 2 basic totals

### ISSUE THREAD

**Issue by huschauer** [GoldenCheetah/GoldenCheetah#2819]
I am currently uploading my swim, bike, run data to Garmin website in parallel to having them on GC. For training sessions done in Golden Cheetah train mode, I am exporting this as TCX (I could not find a FIT export). Loading the TCX file to Garmin, leaves total time and total distance at zero. Is there a way of transferring that piece of data as well? It is all there, and I am manually adding it on the Garmin Connect site for each ride taking it from GC. I guess that TCX has some section for totals and that these data only need to be added there.

**Comment by amtriathlon** [comment]
This is an error on v3.4, it was fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/a3ec10a298977e5d3fee87706a76e28ef3bcb390 and it is available on v3.5 dev built 18.02
