### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by potuz** [GoldenCheetah/GoldenCheetah#2830]
In the attached video you can see two problems with my version of GC  Build 3965 against QT 5.9.4. The video explained:

1) Open GC
2) See that the fonts in the upper panes are tiny. 
3) Open Tools->Options and hit "Save" (without changing anything in preferences)
4) See that the fonts in the upper panes have changed size! (this is the first issue)
5) Open the trends view panel (see that the side pane has not changed at all!)
6) hover over the side panel (see that now the side panel shows the seasons panel as it should, this is the second issue)

The first issue is that font preferences seem not to be read until I go explicitly to Options and save them (even without changes). The second issue is not so bothersome. 
[gc-capture.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1835108/gc-capture.zip)

**Comment by liversedge** [comment]
deprecated summary widgets

**Comment by liversedge** [comment]
see: 94368068796a345bc9e2cc5d28a22aea29c0a9a4 and 094307f6f8b8ffa94f75bd8ba5c014a03ddfa45c

**Comment by potuz** [comment]
Applied both patches and did not solve the main problem about preferences not being read. The second issue is solved though.
