### ISSUE TITLE
libvlccore.so.8: cannot open shared object file. Linux Mint 18.3

### ISSUE THREAD

**Issue by petermoo** [GoldenCheetah/GoldenCheetah#2831]
`/usr/lib/vlc/vlc-cache-gen: error while loading shared libraries: libvlccore.so.8: cannot open shared object file: No such file or directory`
Linux Mint Cinnamon 18.3. Error occurs with GoldenCheetah_V3.4_Qt5.5.1_amd64.deb and GoldenCheetah_v3.5-DEV1710_amd64.deb.

I googled for ways to install libvlccore.so.8 along side libvlccore.so.9 and did not find anything. LM 18.3 has GC 3.3 in a repository. I needed something listed as updated in 3.4. 3.4 install failed so I tested 3.5. The LM Software Manager says 3.5.0dev+20171003 is installed. I could not find GC in the menu.

I uninstalled 3.5 using the Software Manager then installed 3.3 to see what would happen. GC appears in the menu. Selecting the menu entry does not start the application. I will look in the logs for errors.

**Comment by petermoo** [comment]
I posted a Linux Mint question in https://forums.linuxmint.com/viewtopic.php?f=47&t=266238 then continued with research.
It sees that the package libvlccore8 version 2.2.2 contains libvlccore.so.8 but version 3.0.0 of the same package contains libvlccore.so.9. The new version flowed from Ubuntu into Linux Mint. It might be in Debian test, which is the base for Ubuntu, but not yet in Debian stable.

**Comment by petermoo** [comment]
I compiled from source. Crashed into several differences between docs and actual. Used Qt5 versions of Qt related packages. The application starts and displays data from my Forerunner 235.

Four hours to make the compile work. Ugh!

**Comment by petermoo** [comment]
VLC not working. Listed all vlc in Synaptic. VLC was version 2.2.2. libvlccore8 was version 3.0.0. I did a full delete and reinstall of VLC. VLC and libvlccore8 both at version 2.2.2. VLC now working. GoldenCheetah still working.

I do not know what changed libvlccore8 from 2.2.2 to 3.0.0. GoldenCheetah might have worked without the compile if I had fixed libvlccore8 first.

**Comment by amtriathlon** [comment]
The user forum is a better place to give/have feedback on these issues, see https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md
