### ISSUE TITLE
RLV mode data

### ISSUE THREAD

**Issue by JamiePocock** [GoldenCheetah/GoldenCheetah#2832]
Hello, could I request more data be recorded to the main database in RLV mode?
Power (watts), Cadence (cad), time (hr), speed and then have the ability to export the additional data to the compatible formats in GC such as the .fit file format.

Thank you.

**Comment by amtriathlon** [comment]
In v3.5 data recorded each second include the real data provided by the sensors you have configured in the selected device(s) s.t. (HR, Speed, Cadence, Power, etc.) plus virtual data including Altitude for RLV mode and (Altitude, Latitude, Longitude) for GPX mode.
