### ISSUE TITLE
Cannot install this into Linux Mint 18.x ???

### ISSUE THREAD

**Issue by phd21** [GoldenCheetah/GoldenCheetah#2833]
Hello GoldenCheetah,

I am using Linux Mint 18.x based on Ubuntu 16.04 and whenever I try to install this I get errors, or it acts like it installed, but there are no menu items or desktop shortcuts, so I run "sudo apt install -f" and get the errors? Are there better binaries or Installation instructions available? Are there some missing dependencies or whatever that need to be installed? Do you have an AppImage packaging of this software which would be great.

Whenever I try to install this it will not complete. I get VLC errors???
`Setting up goldencheetah (3.5.0dev+20170808) ...
/var/lib/dpkg/info/goldencheetah.postinst: line 5: /usr/lib/vlc/vlc-cache-gen: No such file or directory
dpkg: error processing package goldencheetah (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 goldencheetah
E: Sub-process /usr/bin/dpkg returned an error code (1)`

Best regards,
Phil
phd21

**Comment by clauded** [comment]
VLC is a dependency of GC. Have you tried to install VLC?

**Comment by phd21** [comment]
Hi clauded,

Thanks for replying.

Yes, I have VLC v4.x.x installed. In fact, I'm pretty sure VLC is installed in all Linux Mint editions.

What now?

**Comment by petermoo** [comment]
See also https://github.com/GoldenCheetah/GoldenCheetah/issues/2831

**Comment by clauded** [comment]
VLC 4.x?? Maybe 3.x or 2.x but certainly not 4.x!!

First, validate the VLC version : dpkg -l | grep vlc
Then check if directory /usr/lib/vlc exists : ls /usr/lib

It's possible that vlc-cache-gen is in /usr/lib/x86_64-linux-gnu/vlc. To fix this:

sudo ln -s /usr/lib/x86_64-linux-gnu/vlc /usr/lib/vlc

**Comment by petermoo** [comment]
My "clean" LM 18.3 Cinnamon has VLC 2.2.2. libvlccore8 was somehow changed from 2.2.2 to 3.0.0. VLC failed. I completely removed VLC and reinstalled. libvlccore8 reverted to version 2.2.2. VLC works. GoldenCheetah works. This might have fixed my install problem and saved a compilation.

Open Synaptic Package Manager. Search by name for vlc. Check that VLc and all the VLC components are the same version.

**Comment by amtriathlon** [comment]
The user forum is a better place to give/have feedback on these issues, see https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md
