### ISSUE TITLE
GC v3.5-DEV1802 on Win10 x64: Nokia Health setup not working

### ISSUE THREAD

**Issue by mlanner** [GoldenCheetah/GoldenCheetah#2836]
On a Windows 10 x64 machine I can't get the 'Cloud Wizard' for Nokia Health to work. I've followed the instructions here:

https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-UPLOADING-AND-DOWNLOADING#when-setting-up-my-withings-wifi-scales-where-do-i-get-the-userid-and-key-

... and specifically the process in the "**NOTE:**" section at the bottom.

**How to reproduce:**

Following the instructions, I get to the screen called **Service Credentials** and I can see:

> Authorise `Authorise`
> Token

If I click on the  `Authorise` button nothing happens. I expected this to pop up some other window for me to enter in my Nokia Health credentials or perhaps take me to the Nokia Health page for validation and linking my account.

If I click on the `Next` button it simply takes me to a new screen called **Done**, saying:

```
Add Cloud Account
Sync on start    false
Sync on import   false
```

(I wanted to test the v3.5 dev build on Linux, but there's no pre-built installer for it yet it seems.)

**Comment by amtriathlon** [comment]
#2834 and https://github.com/GoldenCheetah/GoldenCheetah/issues/2802
