### ISSUE TITLE
Strava Activites have incorrect Moving Times

### ISSUE THREAD

**Issue by clifforddw** [GoldenCheetah/GoldenCheetah#2838]
I noticed that activities imported from Strava have an incorrect moving time. My activities are recorded on a Garim Edge 1000 with auto Pause.  I tested a few things on this issue. I imported the original fit file from the device and that reports the same times as Strava. I then imported the file exported from Strava using the /export_tcx feature. This too shows the correct times when imported in GC. Also both these two methods have the same no of samples. The issue seems to be with the file GC imports from Strava through the import process. Interdentally this file has about 1/3 less samples too. 

Happy to supply and samples to help.

**Comment by clifforddw** [comment]
I am using the Feb Dev build of v3.5 1802, Tested and the same behavior in the Oct Build.

I have tried importing with Smart on and Off same result.

My GPS is set to 1s recording NOT Smart.

Similar behavior to #2605   but  I dont use smart.

**Comment by amtriathlon** [comment]
Please attach a sample file which allows to reproduce the issue.

**Comment by clifforddw** [comment]
Right a little more testing files attached. 
[GC Sample.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1863813/GC.Sample.zip)

**Smart On:**
fit import: Correct Timing, moving time, 3:33:51
TCX import: Correct Timing, moving time, 3:33:51
GC Strava Download: Incorrect Timing, moving time, 2:20:18

**Smart Off**
fit import: Incorrect Timing, moving time, 2:17:24
TCX import: Correct Timing, moving time, 2:17:25
GC Strava Download: Incorrect Timing, moving time, 2:17:16

**Comment by amtriathlon** [comment]
There is a bug in the interpolation code which doesn't fix a gap of just one sample and the streams provided by Strava have lot of those small gaps, as you can see in the Edit tab. I will fix it.

**Comment by clifforddw** [comment]
Great will give it a test in the next build, thanks amazing collaboration !

**Comment by clifforddw** [comment]
I see your commits to fix this  are failing  some of the tests let me know if i can help in any way ?

**Comment by bobsica** [comment]
I am having this same problem as @clifforddw . Garmin 520 with smart recording off. The ride gets into Garmin Connect and Strava OK, but importing either file into GC gets the moving time wrong for all my recent rides. An example is attached. TrainerRoad files work correctly.
[gpx-tcx-ride-file.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2954071/gpx-tcx-ride-file.zip)
