### ISSUE TITLE
French translation improvement

### ISSUE THREAD

**Issue by 00livier** [GoldenCheetah/GoldenCheetah#2839]
Hi

In attachment you'll find improvement for french translation.
It mainly fix typos.

Regards

[gc_fr.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1862700/gc_fr.zip)

**Comment by liversedge** [comment]
@grauser do you want to check this?

**Comment by grauser** [comment]
Thank you @00livier, 
I just committed your changes.
