### ISSUE TITLE
3.5DEV1802 - Ride Plot - x-axis is distance - R-R incorrectly plotted 

### ISSUE THREAD

**Issue by henolo** [GoldenCheetah/GoldenCheetah#2842]
3.5DEV1802 - Ride Plot
Only applies to when distance is selected for x-axis.
Attached screen dump. The top waveform is the regular Heartfrequency (HF) waveform.
The R-R waveform below is incorrectly stretched about 2x in distance compared to the HF.

![bild](https://user-images.githubusercontent.com/15927134/38417175-9a3efe04-3997-11e8-9617-5527bfe455bc.png)

**Comment by amtriathlon** [comment]
Hi Henrik, we have a generic way to plot any XData series as User Data, for example using the formula:
`XDATA("HRV",` "R-R", sparse)*1000
and units in ms doesn't seem to exhibit that behavior.
Can you confirm this with your data?

I think, instead to try to fix this issue, we should revert f095416c5c7196aaac789aadf193f4922049bbb2 since it is redundant and it adds unnecessary complexity to an already loaded AllPlot.

**Comment by henolo** [comment]
Hi Alejandro,

 

It appears that the raw HRV/R-R data already is in ms so I had to change the formula into:

 

XDATA("HRV", "R-R", sparse)

 

Then I get a plot with r-r in ms on y-axis which plots ok with both time and distance on x-axis.

 

Great!

Henrik

 

Från: Alejandro Martinez [mailto:notifications@github.com] 
Skickat: den 15 december 2019 23:48
Till: GoldenCheetah/GoldenCheetah <GoldenCheetah@noreply.github.com>
Kopia: Henrik <henrik@hallfose.com>; Author <author@noreply.github.com>
Ämne: Re: [GoldenCheetah/GoldenCheetah] 3.5DEV1802 - Ride Plot - x-axis is distance - R-R incorrectly plotted (#2842)

 

Hi Henrik, we have a generic way to plot any XData series as User Data, for example using the formula:
XDATA("HRV", "R-R", sparse)*1000
and units in ms doesn't seem to exhibit that behavior.
Can you confirm this with your data?

I think, instead to try to fix this issue, we should revert  <https://github.com/GoldenCheetah/GoldenCheetah/commit/f095416c5c7196aaac789aadf193f4922049bbb2> f095416 since it is redundant and it adds unnecessary complexity to an already loaded AllPlot.

**Comment by henolo** [comment]
One important  thing that I just realized.

 

The R-R flag mechanism is not working with the formula below so every time there is a “bad” measurement this is not removed and this deforms the waveform.

Didn’t see this until I zoomed in a lot…

 

So this needs some modification of the formula.

 

/Henrik

 

Från: Henrik Johansson [mailto:henrik@hallfose.com] 
Skickat: den 16 december 2019 19:34
Till: 'GoldenCheetah/GoldenCheetah' <reply@reply.github.com>
Ämne: SV: [GoldenCheetah/GoldenCheetah] 3.5DEV1802 - Ride Plot - x-axis is distance - R-R incorrectly plotted (#2842)

 

Hi Alejandro,

 

It appears that the raw HRV/R-R data already is in ms so I had to change the formula into:

 

XDATA("HRV", "R-R", sparse)

 

Then I get a plot with r-r in ms on y-axis which plots ok with both time and distance on x-axis.

 

Great!

Henrik

 

Från: Alejandro Martinez [mailto:notifications@github.com] 
Skickat: den 15 december 2019 23:48
Till: GoldenCheetah/GoldenCheetah <GoldenCheetah@noreply.github.com <mailto:GoldenCheetah@noreply.github.com> >
Kopia: Henrik <henrik@hallfose.com <mailto:henrik@hallfose.com> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Ämne: Re: [GoldenCheetah/GoldenCheetah] 3.5DEV1802 - Ride Plot - x-axis is distance - R-R incorrectly plotted (#2842)

 

Hi Henrik, we have a generic way to plot any XData series as User Data, for example using the formula:
XDATA("HRV", "R-R", sparse)*1000
and units in ms doesn't seem to exhibit that behavior.
Can you confirm this with your data?

I think, instead to try to fix this issue, we should revert  <https://github.com/GoldenCheetah/GoldenCheetah/commit/f095416c5c7196aaac789aadf193f4922049bbb2> f095416 since it is redundant and it adds unnecessary complexity to an already loaded AllPlot.

**Comment by amtriathlon** [comment]
Thanks for the feedback Henrik!

You are right, I had an old sample file with R-R in seconds.

If you want to plot only non-outliers the formula could be:

`XDATA("HRV",` "R-R?flag", sparse)=1 ? XDATA("HRV", "R-R", sparse) : 0

**Comment by henolo** [comment]
Hmmm, the zero at the end of the formula should be replaced with something that is not plotted at all. The zero is just a new but different error. Is there a NaN or similar that one can use?

**Comment by amtriathlon** [comment]
Regrettably there is no such thing that is not plotted at all for XData, 0 is an impossible value which is a good option without smoothing, but It messes the smoothing feature.
An alternative could be to use the last known good value:
```
if (XDATA("HRV", "R-R?flag", sparse)=1) {
    R_R <- XDATA("HRV", "R-R", sparse);
    R_R;
} else {
    R_R;
}
```

**Comment by henolo** [comment]
This "last good known value" approach is good enough, in my opinion. Thanks!

**Comment by amtriathlon** [comment]
Thanks for the feedback, I added the formula to the wiki entry for HRV.
