### ISSUE TITLE
(V3.5 DEV 1804) TSS has disappeared

### ISSUE THREAD

**Issue by MattDunstall** [GoldenCheetah/GoldenCheetah#2845]
TSS is no longer present in list of metrics to display in all 4 modules (Train, Trends, Activity, Diary).. this has knock on impact on custom metrics I have running that refer to TSS.

**Comment by liversedge** [comment]
It is renamed to avoid using TrainingPeaks trademarks, existing charts will continue to work, new charts will need to use the renamed versions:
* TSS -> BikeStress
* IF -> BikeIntensity
* NP -> IsoPower
