### ISSUE TITLE
XData in R Charts: only one value per second (XData with more data points per second incomplete in R)

### ISSUE THREAD

**Issue by ninardos** [GoldenCheetah/GoldenCheetah#2847]
Accessing XDATA from R or python only provides resampled values (e. g. 1 second). 
To do analysis on XDATA with a variable time stamp it is necessary to access the raw XDATA time series. 

The concrete use case is analysis of R-R data with R or Python scripts.

**Comment by amtriathlon** [comment]
The current implementation is for Python and it allows to access raw XData from custom metrics using embedded Python scripts.

**Comment by amtriathlon** [comment]
Last commit adds the R counterpart, intended to be used in R charts exclusively.

**Comment by ninardos** [comment]
Thanks Alejandro!

I will try it with the next dev build.

Best,

Stefan


-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 04.05.18, 21:27, Alejandro Martinez <notifications@github.com> schrieb:
Last commit adds the R counterpart, intended to be used in R charts exclusively.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/GoldenCheetah/GoldenCheetah","title":"GoldenCheetah/GoldenCheetah","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/GoldenCheetah/GoldenCheetah"}},"updates":{"snippets":[{"icon":"PERSON","message":"@amtriathlon in #2847: Last commit adds the R counterpart, intended to be used in R charts exclusively."}],"action":{"name":"View Issue","url":"https://github.com/GoldenCheetah/GoldenCheetah/issues/2847#issuecomment-386708585"}}}
