### ISSUE TITLE
Activity Intervals for R and Python Charts

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#2848]
I propose to add a new API called activity.intervals/activityIntervals, similar to season.intervals/seasonIntervals with these differences:
- only intervals for the requested activity are returned
- date/time, which is not needed since it will be that of the activity for all intervals, are replaced by interval start/stop (which can be seconds or indices for the sample arrays)
- selected as a new field to indicate the interval is selected in the lateral sidebar (alternatively/additionally it could be a parameter to obtain all or just only selected intervals)

For the chart to be able to react to changes in interval selection changes we should refresh when interval selection changes, if this proves too slow we we could make it an option to optimize the case when the chart doesn't change when interval selection changes, but probably this is overkill.

Related forum discussion: https://groups.google.com/d/msg/golden-cheetah-users/0gfAtOQUjNM/_wZ4QbHPBwAJ

**Comment by arc111** [comment]
I think this will be a great addition and will be much easier to use than having to filter the active ride intervals out of the season intervals.  Plus the start and stop values will be easier to use than having to manage DateTime arithmetic and filtering, particularly if the start and stop values can be directly used to slice the ride data.

**Comment by amtriathlon** [comment]
In current master start and stop are seconds from start, they are returned as float since they may be not int, and can be used to obtain efficiently the corresponding indices for slicing using numpy.searchsorted on the time series.
