### ISSUE TITLE
Crashes on "Find Intervals ..."

### ISSUE THREAD

**Issue by Kraftlakl** [GoldenCheetah/GoldenCheetah#2849]
The application crashes after "Find Intervals" when trying to "Add to Activity". Not sure yet, but I think this only happens after an acitivity has already been saved, whereas "Add to Activity" seems to work on unsaved activities.

**Comment by liversedge** [comment]
what version are you running?
can you recreate this in 3.5-dev ?

**Comment by Kraftlakl** [comment]
hi,
thanks for taking care. currently i am running 3.4up to now i dindn't dare to install 3.5-dev. i will now and come back to you.
robert. Robert Böhm mailto:robert_boehm@yahoo.com

      Von: Mark Liversedge <notifications@github.com>
 An: GoldenCheetah/GoldenCheetah <GoldenCheetah@noreply.github.com> 
CC: Kraftlakl <robert_boehm@yahoo.com>; Author <author@noreply.github.com>
 Gesendet: 21:04 Donnerstag, 19.April 2018
 Betreff: Re: [GoldenCheetah/GoldenCheetah] Crashes on "Find Intervals ..." (#2849)
   
what version are you running?
can you recreate this in 3.5-dev ?—

**Comment by Kraftlakl** [comment]
hi,
negative. i cannot recreate this in 3.5-DEV1710. works like a charm.
thank you, robert. Robert Böhm mailto:robert_boehm@yahoo.com

      Von: Mark Liversedge <notifications@github.com>
 An: GoldenCheetah/GoldenCheetah <GoldenCheetah@noreply.github.com> 
CC: Kraftlakl <robert_boehm@yahoo.com>; Author <author@noreply.github.com>
 Gesendet: 21:04 Donnerstag, 19.April 2018
 Betreff: Re: [GoldenCheetah/GoldenCheetah] Crashes on "Find Intervals ..." (#2849)
   
what version are you running?
can you recreate this in 3.5-dev ?—

**Comment by amtriathlon** [comment]
Let's assume it is fixed then.

**Comment by Kraftlakl** [comment]
hi, i'm sorry - but i just found out it has returned. i'm running 3.5/3991. same as above, crashed on "Find Intervals" when trying to "Add to Activity" (only for previously saved activities).
i have no idea what had made it disappear, nor return.
