### ISSUE TITLE
Error when compiling from source on Fedora 27

### ISSUE THREAD

**Issue by cfabio** [GoldenCheetah/GoldenCheetah#2851]
I have some trouble compiling from source on Fedora 27, I tried both golden cheetah version 3.5 and master branch.
Last time I was able to built it correctly was April 2 2018, when today I tried updating the software I got an error telling me libical was missing, proceed to install it using dnf but then the following error pop-up:
`Gui/LTMSidebar.cpp: In member function ‘void LTMSidebar::addEvent()’:
Gui/LTMSidebar.cpp:1283:31: error: ‘class Athlete’ has no member named ‘davCalendar’
         if (context->athlete->davCalendar->getConfig())
                               ^~~~~~~~~~~
Gui/LTMSidebar.cpp:1284:36: error: ‘class Athlete’ has no member named ‘davCalendar’
             if (!context->athlete->davCalendar->upload(&myevent))
                                    ^~~~~~~~~~~
`

**Comment by liversedge** [comment]
please raise build support requests on the developer mailing list.
thanks.
