### ISSUE TITLE
BikeScore and TSS

### ISSUE THREAD

**Issue by jgonzis** [GoldenCheetah/GoldenCheetah#2852]
In the previous version, when I make a activity without PowerMeter, if I put the information in TSS or BikeScore it changes the PMC. Now it doesn't affect. 

What I'm making wrong?.

Many thanks

**Comment by liversedge** [comment]
This was a bug introduced when we deprecated the TrainingPeaks trademarks. I will fix it.

**Comment by jgonzis** [comment]
Many thanks
