### ISSUE TITLE
GC Crashes with Swim (indoor, no GPS) Data.

### ISSUE THREAD

**Issue by juanmcasillas** [GoldenCheetah/GoldenCheetah#2853]
Hello,

I have an issue with SWIM FIT (indoor, no GPS) files on Mac OS version / Sierra OS. I can't test on windows.

problem description:
When importing SWIM FIT file data into Golden Cheetah, GC crashes.

The FIT file has been recorded on FENIX3, with 1 second interval, NO GPS (indoor swim) with Pool Length of 25m. The FIT file has laps. All the swim sessions FIT files make GC crashes.

Any help?
Thanks in advance,
Juan M. Casillas

File attached (original FIT file)

[2643183899.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1941263/2643183899.zip)

**Comment by liversedge** [comment]
Which version are you running?
Have you tried with v3.5-dev1804?

**Comment by juanmcasillas** [comment]
Hi Mark, thanks for your kick response. I tried with the latest 3 or four versions (I install them when you upload the releases at GitHub)

**Comment by liversedge** [comment]
It works fine for me on DEV-1804. Do you have any user metrics that might be causing an issue?
https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/v3.5-DEV1804

**Comment by liversedge** [comment]
Otherwise capture the macOS crash log and post it here - that will help identify the source of the crash.

**Comment by juanmcasillas** [comment]
The file has hrm data and stroke metrics (All the data recorded with the Garmin triathlon hrm sensor).

I use the same version than you.

I'm at work. This evening (I'm in Spain) I collect the crash log and post it here.

Thanks for your support

**Comment by juanmcasillas** [comment]
With DEV-1804 in windows (fresh install) it works perfectly.

Maybe It's a MacOS specific issue. I will check it this evening.

In MacOs, when I install the new releases, I just delete the /Applications/GoldenCheetah.app and install the new one (Application Support & Athlete data is leaved untouched). Is this the "right" way of do it? Or I have to delete *everything* each time I updated?

Thanks for your support and amazing work.

**Comment by juanmcasillas** [comment]
Hello again

 I got it. **I need to have enabled** **"Use Garmin Smart Recording"** in **Options** in order to parse SWIM files. If not checked, it crashes on windows too.

Thanks for your support.
Anyway, I will check it on MacOS, but it looks like that is the problem.

Thanks.

**Comment by liversedge** [comment]
Perfect, I can fix that.

**Comment by liversedge** [comment]
@amtriathlon are you ok with the commit ?

esp. the bit about enabling smart recording for swim laps? (in this case time goes backwards)

**Comment by liversedge** [comment]
See eb363c3fab01bdcbde19b0ed4377764bbd62380d
(I mistyped the issue number it fixes, sigh)

**Comment by amtriathlon** [comment]
Thanks Mark
The idea around to honor Enable Smart Recording was to give the option to preserve the original data but, for lap swims it makes no sense and it confuse users, besides the original data is now stored as XDdata. I will change all the formats which import lap swims to expand unconditionally.
