### ISSUE TITLE
v3.5-DEV1804 manual TSS metric override fails

### ISSUE THREAD

**Issue by valipod** [GoldenCheetah/GoldenCheetah#2854]
Since v3.5-DEV1804 the manual TSS metric override is ignored when building the PMC (for runs, for example). The value appears to be saved, it is retained between seesions, but nothing appears on the PMC (i.e. only the bike sessions do). I downgraded to DEV1802 and all the runs that were added after the upgrade to 1804 (and only those) had no value in the TSS metric override (i.e. the metric was not set). After setting the values again, the PMC builds correctly, the runs appear, all OK.

**Comment by liversedge** [comment]
already fixed in #2852

**Comment by valipod** [comment]
Sorry, my mistake for only searching in open tickets.

**Comment by liversedge** [comment]
hey, no worries :)
