### ISSUE TITLE
New start

### ISSUE THREAD

**Issue by danst0** [GoldenCheetah/GoldenCheetah#2857]
Hi,

I just started new to GC and imported all my activities. Now I don't know what to make of the CTL, ATL, ... values... Any hints?

Daniel

![bildschirmfoto 2018-04-29 um 09 34 52](https://user-images.githubusercontent.com/1544506/39405705-cad184f0-4ba9-11e8-8f51-8dbb7a2b730b.png)

**Comment by liversedge** [comment]
Please use DEV-1804, this is fixed in the development builds.
https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/v3.5-DEV1804

**Comment by danst0** [comment]
I am not so sure... Should be the latest release now.

![bildschirmfoto 2018-04-29 um 19 51 28](https://user-images.githubusercontent.com/1544506/39409411-dbdb8d62-4be6-11e8-8a2d-84cbe392c63c.png)

**Comment by danst0** [comment]
I am not sure that closed and already fixed is the right status for this issue...
