### ISSUE TITLE
Python API GC.seasonIntervals() returns wrong time value for the intervals

### ISSUE THREAD

**Issue by arc111** [GoldenCheetah/GoldenCheetah#2860]
All of the intervals for a specific ride are returning the same time value, the time of the ride.  So there is no way to determine when the interval actually started within the ride.   This does not happen for the R API GC.season.intervals(), which returns the actual start time of each individual interval within the ride.

**Comment by arc111** [comment]
It appears that the problem is in the lines below.  The time is getting set from the ride time without adjusting it by item->start:

`PyObject*
Bindings::seasonIntervals(DateRange range, QString type) const
{
...

           // TIME
           QTime t = ride->dateTime.time();
           PyList_SET_ITEM(timelist, idx, PyTime_FromTime(t.hour(), t.minute(), t.second(), t.msec()*10));

...
}
`

**Comment by amtriathlon** [comment]
Thanks for the report, I will fix it.
