### ISSUE TITLE
Bike Fatigue Profile/Fatigue & Peak Trends giving errors in console.

### ISSUE THREAD

**Issue by v1sionmaster** [GoldenCheetah/GoldenCheetah#2861]
I've been using GC for about 9 months and was delighted to see the addition of the 'Fatigue Profile Trend' in the latest release.
Sadly I can't get them to display any data, as each one shows an error message in the lower half of the console.
At first I assumed it was because I needed Python and spend a few hours installing the latest version and the required modules (as described elsewhere in Github). 
I have both R and Python installed.
Sadly I can't work out how to extract the text from the trends, but am enclosing a screen shot of the messages at the end of the report for the Bike Fatigue Profile.
I'm not a programmer, but can certainly find my way around most things if I get the right pointers.
Any help would be VERY WELCOME! Is anyone else having the same issues? Is there anything in common between the 3 trends that are in error? :-)
![golden cheetah](https://user-images.githubusercontent.com/38918646/39534872-7db49756-4e2a-11e8-9aa9-208bd8e14400.jpg)
![gc fatigue profile](https://user-images.githubusercontent.com/38918646/39534929-9882e2d6-4e2a-11e8-9904-6d9d18d25477.jpg)

**Comment by v1sionmaster** [comment]
![golden cheetah](https://user-images.githubusercontent.com/38918646/39534088-a455114e-4e28-11e8-94e9-90cb030f4c8b.jpg)

**Comment by amtriathlon** [comment]
See https://groups.google.com/d/msg/golden-cheetah-users/Rj2t_TpHNFU/3Z8etC9rAwAJ

**Comment by v1sionmaster** [comment]
thanks amtriathlon! I see that Normalised Power NP no longer exists and why (replaced by IsoPower - I just don't understand exactly how to implement the change ;-)

**Comment by amtriathlon** [comment]
Please use the forum to get help.
