### ISSUE TITLE
Problem parsing Swim File HRM (FIT Format) (maybe a bug?)

### ISSUE THREAD

**Issue by juanmcasillas** [GoldenCheetah/GoldenCheetah#2862]
Hello

Today I was swimming, and I have to disconnect for a moment the HRM sensor (unbuckle it from my chest). I continue swiming, and download the data to Connect (Garmin). I see the HRM data fine. I download the FIT file, and import it into Golden Cheetah, and in the point that the HRM data goes to 0 (when I unbuckle it) the HRM remains 0 until the end of the exercise.

I export the data to a TCX file, import with GC and everything goes ok. Maybe a bug ?

My config:
Garmin Smart Recording Active, with 1 second interval.
Mac OS Sierra 10.12
GC Build Date: 14 2018 09:26:41, 
GC Build ID: 3966 
DEV-V3.5 1804

I attach the FIT file and the TCX one inside a zip.
The screenshots show the TCX (OK) and the FIT file (BAD).

Thanks in advance,
Juan M. Casillas

[files_fit_and_tcx.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/1977744/files_fit_and_tcx.zip)
![tcx_ok](https://user-images.githubusercontent.com/16412250/39674831-636e2f26-5152-11e8-9e9b-f841a50ff9a7.png)
![fit_bad](https://user-images.githubusercontent.com/16412250/39674832-6507411a-5152-11e8-80cc-bc008bba4cd9.png)

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/5383430b19e6e7d40e70a8fa1c61cc59be424549
