### ISSUE TITLE
Windows 10 Golden Cheetah 3.4 64 bit does not launch after install

### ISSUE THREAD

**Issue by stb-github** [GoldenCheetah/GoldenCheetah#2864]
Hi,
I downloaded the current stable release today and tried installing. It said I needed to install Microsoft Visual C++ Redistributable 14.0.23026. That step failed because 14.0.24123 is already installed on my laptop.
The rest of the installation continued without a problem. However, the program will not launch.

Any help is appreciated.

**Comment by Joern-R** [comment]
If the VC++ Redist is existing and a more recent version is not the cause. Is there any error message coming up - if not, please check the Event Log in Windows and post the error message log there.

One effect in 3.4 was sometimes related to problems with the "R" installation. So please do try to start GoldenCheetah.exe with parameter --no-r

**Comment by stb-github** [comment]
Thanks. R is installed on the laptop. I will post the error messages and try starting it with the --no-r parameter later today.

**Comment by stb-github** [comment]
Running it with --no-r appears to work. Thanks for the help.
