### ISSUE TITLE
Time with speed different from zero

### ISSUE THREAD

**Issue by JoeFri** [GoldenCheetah/GoldenCheetah#2865]
Since a few training sessions the time with speed different from zero ist always wrong in my GoldenCheetah program and therefore the average velocity ist also wrong!
What happened, what can be the mistake and how can I get back to the write ones?

**Comment by liversedge** [comment]
The speed is supplied by the device usually, are you sure the issue is with GC, how is the data recorded and then imported into GC?

Otherwise check you are not using some kind of smart recording and if so enable it in preferences and re-import the file.

If the file is from SportTracks.mobi then do let us know as that is different too.

**Comment by JoeFri** [comment]
Hello Mark,
thanks for your answer.
As headunit I use SIGMA ROX11.0. The data is transtered via SIGMA DATA CENTER as a fit-format (.fit)!
Up to now, it worked without any problems, but since a few trainings it didn‘t. Ans I can‘t find the mistake.
Best regards 
Joachim 

Von meinem iPhone gesendet

**Comment by JoeFri** [comment]
Hello Mark,

yes it does!

You find the newest file as an annex.

Best regards 

Gesendet von Mail für Windows 10

Von: Mark Liversedge
Gesendet: Montag, 21. Mai 2018 09:19
An: GoldenCheetah/GoldenCheetah
Cc: JoeFri; Author
Betreff: Re: [GoldenCheetah/GoldenCheetah] Time with speed different from zero(#2865)

Does it still persist?
If so can you share a file via dropbox (or similar) ?
THANKS

**Comment by amtriathlon** [comment]
The likely reason is to have Smart Recording disabled in Preferences, if it is not the case please attach a zipped sample file (to the issue not email) and reopen.
