### ISSUE TITLE
Laps/breaks from SLF file

### ISSUE THREAD

**Issue by damjanev** [GoldenCheetah/GoldenCheetah#2869]
Hi there.

I'm trying to use GoldenCheetah to combine the positioning data from a smartphone app (GPX/TCX) with a HR, cadence and temperature data from my Sigma ROX 5.0 cyclocomputer. The "combine activity" feature seems to be the one to go but i have issue when the activity has stops (and they almost always have stops). The Sigma ROX device stops recording, while the exports from the GPS/sports apps that i use (all of them) still record the breaks. Time ticking with zero speed. This makes the two recordings unmergable :-(

By briefly analyzing the possible export formats from Sigma DATACENTER application, i have concluded that, when exporting to SLF, there are tags at the end of the document that indicate lap markings and breaks that are not imported into GoldenCheetah. There is a `<Markers>` section after the `<Entries>` section with <Marker> tags for each lap and/or break. If GoldenCheetah can process the type="p" markers (pause) an insert them into the activity as stopped time (clock keeps ticking, speed is zero, cadence is zero, HR and temperature can be either zero or interpolate with last recorded value), then there will be no issue with merging the activities. Type="l" markers are lap markers. It's a nice feature to have, but not necessary.

Sample:

`<?xml version="1.0" encoding="utf-8"?>
<Activity fileDate="Thu May 17 21:38:45 GMT+0200 2018" revision="400">
	<Computer unit="rox50" serial="33589280" activityType="Cycling" dateCode="5805Thu May 17 17:38:55 GMT+0200 2018"/>
	<GeneralInformation>
...
loads of general information data
...
	</GeneralInformation>
	<Entries>
...
bunch of activity entries with speed, cadence, HR, and temperature data
...
	</Entries>
	<Markers>
		<Marker calories="0" description="" duration="5200" number="0" time="16900" timeAbsolute="16900" title="" type="p" distance="544.709" distanceAbsolute="544.709"/>
		<Marker calories="0" description="" duration="0" number="0" time="89300" timeAbsolute="89300" title="" type="l" averageCadence="53" averageHeartrate="146" averageSpeed="2.7222222222222223" distance="2424.278" distanceAbsolute="2424.278" maximumCadence="0" maximumHeartrate="179" maximumSpeed="8.752777777777778"/>
		<Marker calories="0" description="" duration="2300" number="1" time="46300" timeAbsolute="63200" title="" type="p" distance="1390.8380000000002" distanceAbsolute="1935.547"/>
		<Marker calories="0" description="" duration="0" number="1" time="211800" timeAbsolute="301100" title="" type="l" averageCadence="57" averageHeartrate="163" averageSpeed="2.036111111111111" distance="4321.071" distanceAbsolute="6745.349" maximumCadence="0" maximumHeartrate="175" maximumSpeed="4.186111111111111"/>
		<Marker calories="0" description="" duration="31100" number="2" time="238100" timeAbsolute="301300" title="" type="p" distance="4831.332" distanceAbsolute="6766.879000000001"/>
		<Marker calories="0" description="" duration="0" number="2" time="112200" timeAbsolute="413300" title="" type="l" averageCadence="57" averageHeartrate="156" averageSpeed="4.330555555555556" distance="4715.07" distanceAbsolute="11460.419" maximumCadence="0" maximumHeartrate="167" maximumSpeed="13.211111111111112"/>
		<Marker calories="0" description="" duration="0" number="3" time="53300" timeAbsolute="466600" title="" type="l" averageCadence="79" averageHeartrate="129" averageSpeed="10.477777777777778" distance="5552.587" distanceAbsolute="17013.006" maximumCadence="0" maximumHeartrate="165" maximumSpeed="15.113888888888887"/>
		<Marker calories="0" description="" duration="2600" number="3" time="192300" timeAbsolute="493600" title="" type="p" distance="12353.914" distanceAbsolute="19120.793"/>
		<Marker calories="0" description="" duration="500" number="4" time="21400" timeAbsolute="515000" title="" type="p" distance="1358.5429999999978" distanceAbsolute="20479.336"/>
		<Marker calories="0" description="" duration="0" number="4" time="113900" timeAbsolute="580500" title="" type="l" averageCadence="65" averageHeartrate="134" averageSpeed="4.913888888888889" distance="5522.445" distanceAbsolute="22535.451" maximumCadence="0" maximumHeartrate="151" maximumSpeed="10.166666666666666"/>
		<Marker calories="0" description="" duration="125300" number="5" time="16100" timeAbsolute="531000" title="" type="p" distance="738.4789999999994" distanceAbsolute="21217.815"/>
		<Marker calories="0" description="" duration="126100" number="6" time="400" timeAbsolute="531400" title="" type="p" distance="8.61200000000099" distanceAbsolute="21226.427"/>
		<Marker calories="0" description="" duration="8700" number="7" time="10100" timeAbsolute="541500" title="" type="p" distance="363.85699999999997" distanceAbsolute="21590.284"/>
		<Marker calories="0" description="" duration="400" number="8" time="33800" timeAbsolute="575000" title="" type="p" distance="936.5550000000003" distanceAbsolute="22526.839"/>
	</Markers>
</Activity>`

**Comment by merdoks2** [comment]
Same here, I am using ROX6.0 and most of the time , data can't be merged , due to different reasons : Stops at red light , pauses to sort out mechanical issues and so on. At the time I use python script which attempts to adjust timing based on markers with type =='l' , thus I have some errors to iron out, so I won't be posting it here yet.

**Comment by amtriathlon** [comment]
Have you tried to use Edit > Fix Gaps to remove the gaps before merging?
It is documented in https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Activity-Processing#edit-tool-fix-gaps-in-recording

**Comment by grmpl** [comment]
I run into the same problem and created a python-script. You can find it in [https://github.com/grmpl/Sigma_SLF_Pythonscripts](url)
