### ISSUE TITLE
Problem with parsing .gpx-file from Road Grand Tours

### ISSUE THREAD

**Issue by Edw2edw** [GoldenCheetah/GoldenCheetah#2870]
Hello

It seems that GC does not calculate moving time properly while parsing .gpx-file with five trackpoints per second (exported workout from RoadGrandTours.com). "Time moving" exceeds the "duration" by five times.
Thereby I see unrealistic indicators for PMC and peak power over 1000 watts @ 1 hour (O_O).
Maybe it's a bug?

[RoadGrandTours_Passo-Dello-Stelvio_2018-05-20_07-20-37.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2022806/RoadGrandTours_Passo-Dello-Stelvio_2018-05-20_07-20-37.zip)

![gc1](https://user-images.githubusercontent.com/39489747/40311102-14bf96ec-5d39-11e8-9188-2e3757fa9a80.jpg)
![gc2](https://user-images.githubusercontent.com/39489747/40311103-14e4892a-5d39-11e8-8eae-b95d4ca589e4.jpg)

**Comment by liversedge** [comment]
Can you share an example file (via dropbox) ?
It sounds like the recording interval is 0.2s ???!??!?!

**Comment by liversedge** [comment]
Hmmm. So the timestamp basically repeats, there are 5 records for every second.
Not sure how to fix that, it seems a bug to me.

Are there any options to change recording interval ?

I will look at the GPX parser to see if there is an easy fix.

**Comment by Edw2edw** [comment]
No, there are not any options to change recording interval in Road Grand Tours.

**Comment by amtriathlon** [comment]
It seems to be Ok when imported on current master:

![RoadGrandTours_Passo-Dello-Stelvio_2018-05-20_07-20-37](https://user-images.githubusercontent.com/1444784/56855052-a8945080-6916-11e9-9ebb-32ab6a870f5f.png)
