### ISSUE TITLE
Suunto issue with Ambit3 RUN when importing activities (TCX or other file formats)

### ISSUE THREAD

**Issue by luckyprofr** [GoldenCheetah/GoldenCheetah#2871]
Hello all, i have an issue when i import activities (running) from my Suunto watch. Whatever the format file i use (tcx or other), after importing it to GoldenCheetah, some values will be incorrect (average speed for example). Does someone know how to resolve this major issue ? Am i the only one to find it ? GoldenCheetah is an amazing product but with this issue, i can't use it.. Thanks for your reply :)

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/issues/1916 for how to import the Suunto native format.

**Comment by amtriathlon** [comment]
If you want to report an error please provide a sample file and details to reproduce the issue.
