### ISSUE TITLE
Make Time Dependent Measures extensible

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#2872]
In v3.5 we have Body and Hrv measures groups with common access APIs (LTM Charts, Formulas, R, Python and REST), the idea is to generalize the code to enable definition, maintenance and import from CSV files for other groups s.t. Nutrition, Sleep, Well Being, etc.
The idea is to keep the repositories separate but to unify the handling code and Download dialog.

**Comment by liversedge** [comment]
I think this is a brilliant idea, chapeau.

**Comment by amtriathlon** [comment]
Status update: The code is ready for merge except for the UI to edit Measures config, currently a .ini file to be manually edited, I need to finish this.
Direct access to daily measures: we need a fast(er) way to view/edit measures for the day, double click on the day in the mini/full calendar seem reasonable, other ideas are welcome.

**Comment by amtriathlon** [comment]
Additionally to the UX to manage config, an interesting complement would be the possibility to add downloaders in Python, in the line of the new [Custom Data Processors in Python](https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Custom-Data-Processors-in-Python), so time dependent data can be pulled from online services s.t. MyFitnessPal reusing existing Python code s.t. https://github.com/coddingtonbear/python-myfitnesspal
