### ISSUE TITLE
Everything shows incorrect while I Exported from Bryton

### ISSUE THREAD

**Issue by supercyclist** [GoldenCheetah/GoldenCheetah#2875]
Everything or every analyzis result shows very incorrect ( like for a 1hr duration ride , it shows 9hrs in GC ). I uploaded the activity frm bryton ( fitfile upload)

**Comment by amtriathlon** [comment]
This has been reported previously, see https://github.com/GoldenCheetah/GoldenCheetah/issues/2029 for details and workarounds.
