### ISSUE TITLE
HRV data from Garmin 735

### ISSUE THREAD

**Issue by Hezelnutt** [GoldenCheetah/GoldenCheetah#2876]
I am trying to use a Garmin 735 with chest strap to collect HRV data (when I wake up).

Importing the data in GC and looking in the Editor, I can only see the "heart rate' column, there is no 'R-R interval' column. Does this have to do with data recording on my Garmin?

Based on the reading the page below, it seems this data can also be accessed using the xdata formula, however I was unable to do this. If this is causing the issue, any help would be welcome.
https://github.com/GoldenCheetah/GoldenCheetah/wiki/HRV

Also, if there is a better place to ask these questions, please let me know. The HRV functions of GC are really promising!

**Comment by amtriathlon** [comment]
This may help: https://support.firstbeat.com/en/support/solutions/articles/9000061051-how-to-upload-measurements-from-selected-garmin-devices, there is a users forum when you can get more help, as explained in the contributing guidelines.
