### ISSUE TITLE
Strava authorize - 302 HTTP redirect problem

### ISSUE THREAD

**Issue by AirVetra** [GoldenCheetah/GoldenCheetah#2879]
After I press Authorise in pop-up windows for Strava login it shows Golden cheetah page and small window with this error:-(

Error retrieving access token, Error transferring https://www.strava.com/oauth/token? - server replied: Bad Request (302)

**Comment by liversedge** [comment]
We don't publish the api keys. they are secret.
If you want to build your own you will need to register with Strava as a developer.

**Comment by AirVetra** [comment]
Sorry, I'm trying just to link GC to Strava with proposed tools - just add Stava in Add Cloud account section

**Comment by liversedge** [comment]
OK, Strava are returning a 302 redirect response on authorise that is breaking the authorisation flow.

This needs to be fixed.
