### ISSUE TITLE
Can't Import Power Data from Garmin Connect IQ Running Power Estimator

### ISSUE THREAD

**Issue by lincomatic** [GoldenCheetah/GoldenCheetah#2882]
I use Running Power Estimator II data field with my Garmin watch.
https://apps.garmin.com/en-US/apps/530bd211-afd5-41a6-8204-9a2f7ac94541

It calculates running power in Watts, but I don't see it when I load the file into GoldenCheetah.
I looked into the XData via the Edit function, and the power is in xdata=DEVELOPER data series=RunPowerE

Is there a way to configure GC so that it will just read the RunPowerE and treat it as standard power data?
If not, I would appreciate a pointer on how to add this functionality.

**Comment by liversedge** [comment]
I think the best 'design' for this would be to create a generic 'Fix Tools' dataprocessor that allowed you to copy data series from XDATA into Standard Series.

It would have parameters:
Source XDATA: DEVELOPER / RunPowerE
Target: Power
Overwrite: Y/N

Then you could configure it to only run on import and only do this if RunPowerE is present.

See the Power Estimator dataprocessor (https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/FileIO/FixDerivePower.cpp) for an example that estimates power (lots of that code can be dropped!).

For working with XDATA, there is some code in the FilterHRV code (https://github.com/GoldenCheetah/GoldenCheetah/blob/e7d079dad6156f6288e1ed7480c8d89c6b7e4c9a/src/Metrics/HrvMetrics.cpp) that works with HRV data that should help understand how to work with it.

To learn a bit more about data processors see: https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Activity-Processing

Make sense?

**Comment by amtriathlon** [comment]
This could a good issue for https://github.com/GoldenCheetah/GoldenCheetah/pull/2951
