### ISSUE TITLE
Strava auth error

### ISSUE THREAD

**Issue by thecoser** [GoldenCheetah/GoldenCheetah#2883]
Getting this message when trying to auth Strava with GoldenCheetah:

Error retrieving access token, Error downloading https://www.strava.com/oauth/token? - server replied: Bad Request (302)

**Comment by liversedge** [comment]
already fixed. see  #2879

**Comment by thecoser** [comment]
But i just got this error today, before and after redownloading latest version....

**Comment by thecoser** [comment]
But i just got this message today from latest download….

**Comment by liversedge** [comment]
The code has been fixed, a new build will come out later.

**Comment by thecoser** [comment]
thanks

**Comment by bloomo** [comment]
It's currently October 27th. Is there an estimation for when the new build with this fix will be released?

**Comment by amtriathlon** [comment]
Try this build: https://github.com/GoldenCheetah/GoldenCheetah/releases/download/v3.5-DEV1810/GoldenCheetah_v3.5-DEV1810-x86_64-ssl.AppImage

**Comment by amtriathlon** [comment]
It is included in v3.5dev18.10 build

**Comment by bloomo** [comment]
> It is included in v3.5dev18.10 build

Thank you - just went into the releases section on Git and there it was. Is there a reason this is not linked onto the site yet?

**Comment by bloomo** [comment]
Thanks Alejandro - hadn't thought to look into the releases section on Git.
Was downloading off the site.
