### ISSUE TITLE
Filter R-R outliers takes a long time (with GC not reactive in between)

### ISSUE THREAD

**Issue by ninardos** [GoldenCheetah/GoldenCheetah#2884]
When I start the filter R-R outliers tool by the menu: 

Edit -> filter R-R outliers ("Bearbeiten" -> "Filtere R-R Ausreisser...")
then select "Set Resting HRV" ("Ruhe HRV festlegen") and klick ok

GC freezes for a few seconds (the update bar on windows (light blue/cyan). It usually takes a few seconds (at least 3-5, sometimes longer on a windows 7, pentium i5) until GC gets reactive again.

Since HRV files are very small (1 - 3 min. duration) I wonder why this is so.

Best regards,

Stefan

**Comment by amtriathlon** [comment]
When you select Set Rest HRV option the processing time will be dominated by the need to recompute the metrics for the activities which may depend on this data, not the HRV file itself when it is small.

**Comment by ninardos** [comment]
Hi Alejandro,

thanks for your answer.

I probably do not understand the underlying technical constraints enough.

When I do the calculation on a single file of 2 minutes to add one single entry for HRV metrics of a day (Resting HR , RMSSD etc.) I would expect that the calculation of the metrics for this day do not take long.
If I understand correctly, this is the case.

But why need the metrics for the activities (all?) be recomputed?
I somehow supposed, that adding the HRV metrics of the day (a few numbers) to the already calculated metrics is a very small task. Especially since I do not see any connections to metrics that do change based on historic data (like for example TSS of a newly added activity in the past would change TSB, ATL, CTL for all future activities).

Best regrads,

Stefan

**Comment by amtriathlon** [comment]
All Rest XXX metrics depend on HRV measues and custom metrics also can depend on them, the metric cache algorithm is general and recomputes all metrics for the affected activities, which are the ones on the date of the new measures and days following until other measures are available. If you want to add several measures it is faster to do from the newest to the oldest, although the alternative mechanism I proposed to you on the users forum doesn't require this step.
If you want to propose an alternative we are open to consider Pull Requests.
