### ISSUE TITLE
Can't import FIT file to Garmin Connect

### ISSUE THREAD

**Issue by raven-ie** [GoldenCheetah/GoldenCheetah#2886]
I've tried to use GC to fix powerspikes and incorrect Normalized Power and TSS. Unfortunately output .fit file can not be imported into Garmin Connect and does not inclued device information or session info (normalized power, tss, etc).

**Comment by liversedge** [comment]
which version of GC are you using?

**Comment by liversedge** [comment]
GC meaning GoldenCheetah not Garmin Connect. Damn.

**Comment by raven-ie** [comment]
Yes, sorry for the confusion. I was using both DEV1802 and new one with same result. New one crashes for me though on parsing activities. I'm gonna send crashlog once I'm back home.

**Comment by Ramoonus** [comment]
can you send the log?

**Comment by amtriathlon** [comment]
Please try the last v3.5dev from 
https://github.com/GoldenCheetah/GoldenCheetah/releases, there are some fixes for exporting.

**Comment by amtriathlon** [comment]
I've tried with https://github.com/GoldenCheetah/GoldenCheetah/tree/V3.5-RC1 to generate a simple training file using the Robot device:

![image](https://user-images.githubusercontent.com/1444784/68158162-d396d700-ff2d-11e9-84ee-0c5bbc8c745e.png)

Then exported as FIT and it imports to Garmin Connect without issues:
![image](https://user-images.githubusercontent.com/1444784/68157901-53707180-ff2d-11e9-8197-1e78fe436358.png)

If you can recreate the problem with RC1 please reopen this providing a sample source file for testing.
