### ISSUE TITLE
R Problems in GC

### ISSUE THREAD

**Issue by Scout99** [GoldenCheetah/GoldenCheetah#2887]
I can´t work with R in GC.
I can no longer use all the R programs I´ve created and downloaded from GC

The following error occurs when querying a variable
d<-GC.activity
str(d)

Error in inDL(x, as.logical(local),as.logical(now), ...): 
unable to load shared object ´C:/Programm Files/R/R-4.5.3/library/stats/libs/x64/stats.dll´:
LoadLibrary failure: Das angegebene Modul wurde nicht gefunden.

## GC.build()		3967
![image](https://user-images.githubusercontent.com/37848550/41810180-2cc0265a-76fa-11e8-8178-ed8791115ab3.png)

**Comment by amtriathlon** [comment]
See https://groups.google.com/d/msg/golden-cheetah-users/AcpruIAIPnE/yNklyDNlBgAJ
