### ISSUE TITLE
workout mode in an GC android app

### ISSUE THREAD

**Issue by PGMercier** [GoldenCheetah/GoldenCheetah#2888]
First - gc member since long time - so happy with everything - working great! THANKS.

I wonder if there is any plan in brining  the GC pc program to a GC android app. Enableling you to record your workout (when you are on the road) and being able to import your desinged erg files - from the firstclass GC workout editor.  
There are many apps that is recording but I havent found one where you can import your own erg files (except taking a membership in trainerroad etc). 
If Im wrong please advice me.

BR and thanks

**Comment by amtriathlon** [comment]
Currently Train mode is an integral part of GoldenCheetah and it will not be available on Android anytime soon, there was interest to make it a separate app but it didn’t progressed, see https://github.com/GoldenCheetah/GoldenCheetah/issues/939

**Comment by PGMercier** [comment]
Alejandro
thx - must say I love Golden Cheetah - been a user for years.
is there a way to run the trainer view at the same time as you run Bkool app. I have tried many different version but will not work. I want bkool to be a slave and GC to control the ERG-mode.
I you have time pls respond
br Peter
    Den onsdag 11 december 2019 13:10:47 CET, Alejandro Martinez <notifications@github.com> skrev:  
 
 
Currently Train mode is an integral part of GoldenCheetah and it will not be available on Android anytime soon, there was interest to make it a separate app but it didn’t progressed, see #939

**Comment by amtriathlon** [comment]
I don't know, I have no experience with bkool trainer or apps, I would suggest to ask in users forum.
In theory you could control a device via ANT+ FE-C and simultaneously monitor it via ANT+ using another device, for example a Garmin watch. But it is up to the trainer device if it supports multiple connections and/or ANT+/BLE simultaneously when the App connects via BLE.

**Comment by PGMercier** [comment]
👍
Thx

Skickat från min iPhone
