### ISSUE TITLE
Crashreport

### ISSUE THREAD

**Issue by tuijldert** [GoldenCheetah/GoldenCheetah#2889]
[GoldenCheetahCrash.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/2130760/GoldenCheetahCrash.txt)

with a Teasi connected while searching for devices.
Issues with USB connection, doesn't see the device.
On ubuntu 16.04 desktop version.
Hope this helps.

Cheers,
Tom.

**Comment by amtriathlon** [comment]
This refers to and old pre-release version (Version: 3.3.0RC1), please use the last released version (v3.4) or the last development build for the offcial site: http://www.goldencheetah.org/#section-download
