### ISSUE TITLE
Empties data file: Fix lap swim from length data

### ISSUE THREAD

**Issue by bobsica** [GoldenCheetah/GoldenCheetah#2892]
I forgot to change my garmin watch from 25 to 50 m, did a swim and downloaded it to GC. If I use "Fix lap swim from length data" in Edit and type in 50 for pool length all my data disappears, I'm left with a blank file.

Mac, High Sierra, 3967 build on 8 June

**Comment by amtriathlon** [comment]
I just tried to change the pool length from 25 to 50 in a test activity from Garmin Swim and it behaves as expected, distance is doubled, no data lost. Can you post the offending file?

**Comment by bobsica** [comment]
Attached is the tcx version of the file. It was recorded with a Garmin Tactix Bravo in Swimming mode.

[testSwim.tcx.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2199104/testSwim.tcx.zip)

**Comment by amtriathlon** [comment]
This problem happens when Garmin Smart Recording is disabled in preferences, since the user is explicitly requesting the lap expansion we can ignore that setting to avoid confusion.
