### ISSUE TITLE
Alternate Athlete Data Location 

### ISSUE THREAD

**Issue by todfox** [GoldenCheetah/GoldenCheetah#2893]
It would be smashing if it would be possible to change the athlete data location from Users/XXXX/AppData/Local to some other location. The use case is that I use multiple computers and have everything on a network drive. It would be great to open GC on any computer looking at the same data.

**Comment by liversedge** [comment]
It's in options

**Comment by todfox** [comment]
then the bug is that you cant open the application to get to options
without creating an athlete which is redundant given the data exists once
pointing to the right location
