### ISSUE TITLE
HRV data duplicate of last known input

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#2896]
Hi,

Whenever there is an activity with missing HRV input for that day in "Options > Athlete > HRV", it seems that the last known measurement gets displayed in long term metrics charts. 
This skews the trend lines of these data.

GoldenCheetah v3.5, June beta release, Linux Mint 19.3

Kind regards,

Nigel

![hrv data duplicates](https://user-images.githubusercontent.com/14836910/43040560-08dd4f02-8d47-11e8-909c-f3f28d7e114d.png)

**Comment by amtriathlon** [comment]
Agree, this makes sense for Body measures but not for Hrv measures, I will change them to return 0 when there is no entry for the day since 0 is not considered to compute trend lines.
