### ISSUE TITLE
TSB Training Stress Balance must be delayed in the plot (TRIMP Point)

### ISSUE THREAD

**Issue by cramerx** [GoldenCheetah/GoldenCheetah#2897]
Hi,
I think that TSB Training Stress Balance must be delayed in the plot.
If TSB=LTS-STS then TSB must be delayed back by 1 day

**Comment by liversedge** [comment]
This is how it works in e.g. TrainingPeaks.
If you want it to refect on the same day then there is a setting in options/preferences to do this.
