### ISSUE TITLE
Activity map chart has "For development purposes only" watermark

### ISSUE THREAD

**Issue by bstegmaier** [GoldenCheetah/GoldenCheetah#2898]
**Precondition**
GoldenCheetah v3.4 on MacOSX
Activity map chart configured to use google maps

**Scenario**
Given I open an activity
When I go to the "map" chart

**Actual**
Then I see a watermarked map (text: "For development purposes only") with my track 
And I see a popup saying "This page can't load Google Maps correctly"
<img width="901" alt="screen shot 2018-07-26 at 15 12 26" src="https://user-images.githubusercontent.com/1767130/43264432-6c39da96-90e6-11e8-8fa3-0fcacca927b3.png">

**Expected**
Then I see the map with my track

**Comment**
This is probably since Google maps is no longer free. You have to associate a credit card with your account in case you exceed the $200 monthly free credit.

**Comment by liversedge** [comment]
Google have changed their maps API and require it to be paid and licensed.
We will be deprecating support.
Please use the options to select another maps provider.

**Comment by bstegmaier** [comment]
Bing maps seems to be the only working option right now, since you also seem to use the Google maps client for displaying OSM tiles.

**Comment by liversedge** [comment]
Bing is deprecated too in the next release !
The OSM tileserver can be changed in 3.5dev.

Maps pivoted, and I think they'll lose a lot of users.

**Comment by Axinet** [comment]
No way to enable them conditionally since 3.5 when user provide his own API key? So optional like R charts only if someone makes additional steps to enable?

**Comment by mod-bike** [comment]
Hello,
just downloaded Version 3.5-DEV1901
No Option to Change map Providers in menue?

How do i change f.e. to OpenStreetMap?

Regards
