### ISSUE TITLE
Map not displaying - "This page can't load Google Maps correctly"

### ISSUE THREAD

**Issue by tscoleman** [GoldenCheetah/GoldenCheetah#2899]
Starting three days ago I cannot display maps of rides - I get a message "This page can't load Google Maps correctly"

Could this be due to some change in the Google maps API? 

This occurs on two different machines (both Mac), it originally occurred with an older release but I just updated to the most recent production release (V3.4) and it still occurs. Screenshot attached.

![screen shot 2018-07-31 at 2 46 12 pm](https://user-images.githubusercontent.com/29666819/43480265-c76f2bb2-94d0-11e8-8e03-923008c040e1.png)

**Comment by amtriathlon** [comment]
see https://github.com/GoldenCheetah/GoldenCheetah/issues/2898
