### ISSUE TITLE
Ubuntu 16.04 build: QJson

### ISSUE THREAD

**Issue by j33433** [GoldenCheetah/GoldenCheetah#2900]
`Cloud/WithingsDownload.h:26:23: fatal error: QJsonObject: No such file or directory`

I've tried a few Ubuntu packages and some gits, but haven't found the right thing to install for this.

**Comment by liversedge** [comment]
Please use the golden cheetah developers mailing list for build support - this is a bug tracking system.
You need to install Qt5 and a minimum of Qt 5.9 is now supported officially.
