### ISSUE TITLE
Strava walk activity type is imported and affects ride stats

### ISSUE THREAD

**Issue by sigriffiths** [GoldenCheetah/GoldenCheetah#2907]
Lastest mac dev build 3.5 1806.

When importing from strava walks are incorrectly assigned to rides and hence messes up the figures.

How to repro:

1.  Go for a walk on strava or import from somewhere else eg GCM
2. Sync from strava to golden cheetah
3. Compare your figures.

Let me know if there is anything else I can provide to help with this,

Looking at the code it appears to be an issue with how rides are detected.  

https://github.com/GoldenCheetah/GoldenCheetah/blob/a86b0e9b74882ed83af3eb9293d97331ea95a500/src/FileIO/RideFile.cpp#L216

So if its a run or a swim they are identified.  Anything else from strava is classified as a ride which to me seems like it would cause issues when people are using multisport devices and doing multiple different types of activities reported back to strava.

Thanks,

Si

**Comment by sigriffiths** [comment]
Possibly do a isRide() check with a regex on 'ride|bike|cycl' to catch rides, indoor rides, virtual rides, handcycle etc etc

Hope this helps

**Comment by sigriffiths** [comment]
As above.  When importing via strava it only filters our Run and Swim.  Everything else is considered a ride which messes up the numbers for things like walks.

https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/Cloud/Strava.cpp#L273

I don't think when importing this is correct

**Comment by liversedge** [comment]
This is how GC works, the majority of users don't use metadata at all, so we always assume it is a ride.
If you don't want it included use filters. (e.g. Sport != "Walk")

**Comment by liversedge** [comment]
Just to expand a little

- Values in Sport are multilanguage and user dependant, so we can't check for bike, cycle etc since there may be different values depending upon language.
- Further, often sport is blank because users just don't maintain metadata so we really can't id bike rides easily. 
- OTOH, if users want to import swim and run files we have been explicit about what values they should use.

Hope this makes sense.

**Comment by sigriffiths** [comment]
Ok cool thank you for you help 👍
