### ISSUE TITLE
List of all segments

### ISSUE THREAD

**Issue by Genussradler** [GoldenCheetah/GoldenCheetah#2908]
it would be nice to have a searchable list of all segments. Maybe with some statistical data like "number of efforts", "best time", "last date".
A double click on a segment will show all efforts the same way as in the comparison area.

**Comment by amtriathlon** [comment]
Currently something like this is possible to implement as a Python chart, there is an example in the forum. User Charts could be used in the future with https://github.com/GoldenCheetah/GoldenCheetah/issues/3626
