### ISSUE TITLE
need better funktion(s) to correct gps and/or distance data

### ISSUE THREAD

**Issue by IlGehring** [GoldenCheetah/GoldenCheetah#2910]
I have bad gps and/or distance data where it would help to correct following issues

1.) The correct speed out of distance function, doesn´t work right, after using my data is still freakly fluctuating, still in an other way, even when I only use the gps data , which can be created with the guess distance function.

1.) I need a funktion to smooth out values in tables who they are extremly fluctuating,
2.) The new funktion has also make a normalize correction of freak values first and..
3.) kill  values who are the result of bad gps reciption, while I don´t move

4.) if it´s possible, it would be nice the a new funktion for gps values, could correct the data in that way that the line through the data points will make a line and not go zigzag.

Greetings from Lüneburg

IlGehring

**Comment by amtriathlon** [comment]
Fix speed from distance allows smoothing using a moving average filter raising the parameter up to 60:secs

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/pull/3049/commits/1b37aa975fa80fbbee4bc1a65bc435ea465bb78f
