### ISSUE TITLE
AppImg no more working on Debian Testing

### ISSUE THREAD

**Issue by 00livier** [GoldenCheetah/GoldenCheetah#2915]
Hi,

After recent update of Debian testing release, Appimage GoldenCheetah_v3.5-DEV1806-x86_64.AppImage is starting and gives output
./GoldenCheetah_v3.5-DEV1806-x86_64.AppImage: symbol lookup error: /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0: undefined symbol: xcb_dri3_get_supported_modifiers

AppImage uses system /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0 which now use method xcb_dri3_get_supported_modifiers from lib libxcb-dri3.so.0.
Issue is AppImage includes an older version of lib libxcb-dri3.so.0 that doesn't include xcb_dri3_get_supported_modifiers method.
My config Debian testing updated with packages:
libglx-mesa0 : 18.1.6-1
libxcb-dri3-0 : 1.13-2

Workaround:
Extract all files from image with command:
./GoldenCheetah_v3.5-DEV1806-x86_64.AppImage --appimage-extract
In folder squashfs-root/lib remove file libxcb-dri3.so.0
Launch binary GoldenCheetah from squashfs-root instead of AppImage

Regards,
Olivier

**Comment by probonopd** [comment]
Similar: https://github.com/SuperTux/supertux/issues/928
