### ISSUE TITLE
Very unstable on Mac Mini

### ISSUE THREAD

**Issue by Frono** [GoldenCheetah/GoldenCheetah#2916]
So far the Dev build 3.5 1806 is very unstable on MacOS 10.13.6 running on a Mac Mini I7. I am using a Wahoo Kickr V1.0 via ANT+ (Turned off Bluetooth completely on Mac due to issues). Crashes are too numerous to fully describe.

1. After Initial Setup I cannot get the add device screen to come up without crashing the app. To stop the power spikes, I had to hand edit the trainer configuration file to remove the power and speed sensors from the Kickr device.
2. Often when hitting the power button on the training screen the app will crash.
3. During training sessions the app will occasionally crash when adjusting the power up or down.

I have also tried 1804, 1802, and V3.4...  Is it possible that something foundational like the Qt version is not compatible with MacOS 10.13.6? This is pretty much a blank machine that has only run TrainerRoad, Sufferfest, Zwift, and Bkool software. It has plenty of memory and has had no issues with any of the subscription apps.

**Comment by liversedge** [comment]
Have never tried on a Mac Mini, the code you are having trouble with is related to USB, which may have incompatiblities (we've never tried). It could be the version of libusb is out of date for a mini. It runs fine on High Sierra, the published binaries are compiled with it.

**Comment by liversedge** [comment]
Would be interesting to see a crash dump, it may give hints about what is not working.

**Comment by Frono** [comment]
I tried to install on an older Mac Mini, installed the software and successfully added the trainer, when I tried to add another device GC crashed. Here is that crash file

[Older_Mac_Dump_V1.0.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/2334102/Older_Mac_Dump_V1.0.txt)

**Comment by Frono** [comment]
Ok, I have managed to get GC to compile on a machine with libusb-compat V0.1.5. So it is the newer libusb V 1.0.22 with a libusb .1 compatibility wrapper. What would be the process to change the published binaries to use it?

**Comment by liversedge** [comment]
Will add to build for the next development build and lets see if it works out ok

**Comment by liversedge** [comment]
@Frono just to let you know am working on a build, should be out in the next day or so -- with libusb-compat. note there is also a build for no libusb-compat just in case. will update you when its available.

**Comment by Frono** [comment]
I see a Mac 1810 build there now. Is it the one with libusb-compat?

**Comment by liversedge** [comment]
No, thats why I marked it as [no libusb-compat] :)

**Comment by liversedge** [comment]
@Frono have added a new build with libusb compat and libusb-1.0, can you let me know if this works ok? if so will close this issue and use for future macOS builds.

**Comment by Frono** [comment]
Error "Cannot open ANT+ device" with the new version.

Tried the no libusb-compat version too, and have the same instability as before.

**Comment by liversedge** [comment]
thanks. I'm using libusb-1.0 and usb-compat straight from git repos, might need to go find the versions you built with.

**Comment by Frono** [comment]
Is there something more I need to do on my end? I pasted my versions into the message above. 
I'm still trying to get everything to compile on Mojave, but the .app I compiled on High Sierra is still running fine on the Mojave mac mini.

**Comment by Frono** [comment]
Just as a FYI... I have successfully compiled and tested GC with the libusb-compat and libusb 1.0 on the 2009 Mac Mini running El Capitan 10.11.6. On all my compiles I'm running the latest Qt 5.11.2. I disabled all the other libraries in the src .pri file.

**Comment by amtriathlon** [comment]
In v3.5 libusb1-0 is directly supported (https://github.com/GoldenCheetah/GoldenCheetah/pull/2919) and travis-ci builds use it (https://github.com/GoldenCheetah/GoldenCheetah/commit/eff123e0e243f725da0b571f869f4140c5c5ef2f).
