### ISSUE TITLE
Readme for MacOS

### ISSUE THREAD

**Issue by Frono** [GoldenCheetah/GoldenCheetah#2917]
The Install instructions to create a dev environment for MacOS could use an update. Using the current readme, I have been unable to get source to compile on a clean mac. I'm not sure if it is due to the version of Qt or maybe compiler settings.

**Comment by Frono** [comment]
Crash dump 1 is from hitting the power button in the training screen.
[Dumpfile_01.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/2334045/Dumpfile_01.txt)
Crash dump 2 is from trying to add an ant device.
[Dumpfile_02.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/2334048/Dumpfile_02.txt)

**Comment by Frono** [comment]
I have updated the readme for MacOS mostly using homebrew instead of macports. I had to install libical. Even though I had it disabled in the gcconfig.pri.in, the code kept trying to include it. 

How should I go about updating the ReadMe, normal GIT process?

**Comment by amtriathlon** [comment]
You need to change gcconfig.pri, not gcconfig.pri.in which is just a sample config file used to create gcconfig.pri. How to contribute is explained in https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md.
