### ISSUE TITLE
[Old 614] Support USB1 on Mac/Linux without driver

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#292]
Support for USB1 sticks on mac/linux is via a virtual comm port and thus mandates the silabs driver install.

On Windows we use the SILabs USBXpress sdk to interface with USB1 sticks, but it is not available on Linux/Mac.

There is an open source stack for USBXpress on top of libusb that should work on Mac/Linux and is attached.

If we can incorporate this into the GC code we will always interact directly with ANT sticks via libusb which will simplify the setup and usage.

It is also worth noting that the Mac OS X Lion upgrade removes the VCP driver, not sure why, but suggests it is not well liked in Cupertino ;)

SiUSBXp_v0.01.c   (15.4 kB)   Mark Liversedge, 01/24/2012 01:59 am
Add
Related issues

History

#1 Updated by Mark Liversedge 10 months ago
Assignee set to Mark Liversedge
Target version set to 3.0
 
It is also worth noting that the USB1 stick requires a usb_reset to clear conditions when it gets 'stuck', and moving to a usb API will allow us to do this (it is not possible when using a VCP).

Also, have made the target for this v3.0

#2 Updated by Mark Liversedge 10 months ago
Target version changed from 3.0 to 3.1
 
After some experimentation I think its best to push this out to 3.1 -- it is going to need a fair bit of work and testing. As the current code is working its probably better to focus on more pressing issues first.

**Comment by WesTyler** [comment]
I'm totally necro-bumping this, and sorry, but has anyone happened to find a solution for the USBXpress sdk on mac/linux?
