### ISSUE TITLE
Strava Sync not working any longer

### ISSUE THREAD

**Issue by crenner** [GoldenCheetah/GoldenCheetah#2920]
For about three weeks, I cannot sync with Strava any longer. New rides do not come in anymore after August 5th. Tried to create new account but get the message:

Error retrieving access token, Error creating SSL context (error:140A90C4:SSL routines:func(169):reason(196)) (99)

Compiled myself using QT5.8 (with oauth support). Same issue with GC from Ubuntu 18.04. Latest development build does not even get there (saying that oauth support not available).

Would be great to get any support on this.

**Comment by amtriathlon** [comment]
To build with Strava support you need to register with Strava and configure the API keys, see https://github.com/GoldenCheetah/GoldenCheetah/wiki/Strava-configuration

**Comment by crenner** [comment]
Thanks for the response. I tried this but Strava does not accept the auth callback domain. I think this is a Strava problem, because the input field doesn't accept any input really.

However, what's puzzling me is that it all has worked until I upgraded to Ubuntu 18.04 (from 17.10). When I first set up the sync, I did not need to do anything manually (it worked through the "create sync account" in GC). I used the development build (18.04 or 18.06).   I had a proper app for GC in Strava and this worked for weeks. After the upgrade to 18.04, I did not realize it was due to this upgrade (still not 100% sure it's that, but reasonable). Syncing stopped working and removed the app in Strava and tried to reconnect through GC which then failed. However, syncing was broken even before that.

When I now try to recreate the app in Strava through GC, I get two different error messages depending on whether libssl1.0 or libssl1.1 is installed. I hence believe it's due to libssl (any maybe additionally a problem in Strava as stated above). Any idea?

**Comment by crenner** [comment]
Changed the strava_token variable in <MyName>/config/athlete-private.ini. Now it appears to work again. :-) Thanks! Your post lead me to the right actions.

Final thing, though: Right now, GC only syncs public rides from Strava. Any chance to download private activities as well?

**Comment by amtriathlon** [comment]
These are 2 separate issues:
- Strava keys are needed only at build time, the ones used for official builds are not public so you need to register with Strava if you want to build by yourself.
- The issue with v3.5-DEV1806 is likely related to the OpenSSL version included with Ubuntu 18.04, the AppImage was generated on 16.04 with OpenSSL 1.0.2g  1 Mar 2016

**Comment by crenner** [comment]
Ok, I got the point. However, it looks like there's a problem with OpenSLL 1.0.2n / 1.1 (from 18.04) when doing the Authorization through GC (which probably created the Strava App / API connection). This worked in GC 1806 on Ubuntu 17.10 but not 18.04.

Regarding the Strava API problem, I contacted them and hope to get an answer. At the moment, you cannot create an App, because the form does not accept /any/ auth domain. The workaround is to disable JavaScript, input the auth domain (with http:// prepended) and on the next page (uploading the icon), re-enable JS and refresh (F5).

**Comment by liversedge** [comment]
Is this really a bug?

Does the official dev build work?

**Comment by paologaffu** [comment]
@liversedge on my Windows is working. But how to install GC 3.5 DEV 1806 on Ubuntu? I try to download rpm file and convert it into a deb file, but installation goes wrong

**Comment by Vertux** [comment]
With the macOS version Dev v3.5 1806 the Strava Sync works without any issues.

**Comment by liversedge** [comment]
this is related to appimag build issues and so closing as a duplicate (and appimage is experimental anyway)

**Comment by amtriathlon** [comment]
> dev3.5 for Ubuntu worked under 17.10 but stopped working on 18.04. I assume this is due to the shipped OpenSSL packets; I received different errors when having 1.0 and 1.1 installed. For 1.0, the actual (sub)version in 18.04 is slightly different

To solve this issue the last AppImage v3.5 DEV 1810 is packaged including libssl and libcrypto and allows to authorize Strava on Ubuntu 18.10

**Comment by mike-rennie** [comment]
H all! 

Running GC:
Build id: 3969 
Version v3.5=DEV1901
OS: Win (Windows 10). 

The Strava sync setup is unable to be completed. Each time it proceeds through the account login to the "Authorize Golden Cheetah to Connect to Strava" screen. Leaving all defaults ticked and clicking "Authorize" incessantly results in an "SSL Token Refresh Error" stating 'Error retrieving access token, Socket operation timed out (4).' 

Is anyone able to advise a resolution for this issue?

Many thanks.

**Comment by TurboGit** [comment]
Yes, with 2.5 1903 I get a crash (segmentation violation) when I start. And I cannot sync with Strava with 1810. All versions seems to be broken with Strava. The AppImage tells me that I don't have the proper SSL library for authorization process!
