### ISSUE TITLE
create, rename and stop segments

### ISSUE THREAD

**Issue by Genussradler** [GoldenCheetah/GoldenCheetah#2922]
hi,

when creating a segment, for me it would be useful if the rename dialog will pop up automatically, because that's what I do when I create a segment from "climb x".
Then it happened one or two times that I accidently stopped tracking a segment instead of renaming it, because renaming and stopping are right beside in the context menu. A security question like "do you really want to stop tracking of this segment" could prevent this.

greetings
  Marco

**Comment by grauser** [comment]
commit 72ac997a8493da680f37a9a536d0d02c92b21471 add a message box to confirm : "Are you sure you want to stop tracking this segment?"

**Comment by amtriathlon** [comment]
I think we can close this since the create and rename is at odds with current implementation and, probably it's not worth the effort to implement it. The warning on stop should be enough for now.
