### ISSUE TITLE
map not working in 3.5 and 3.5dev1806 - "this page cannot load Google Maps correctly"

### ISSUE THREAD

**Issue by PeeTeeH** [GoldenCheetah/GoldenCheetah#2925]
No matter what map source is selected it shows "this page cannot load Google Maps correctly" error.
The same error is shown when OSM is selected as tile provider.
Yes, I am aware about change of Google map licensing.
I am just noticing that it throws the same error while using OSM servers too.

**Comment by batsonjay** [comment]
I see the same behavior in build 1810. To reproduce:
- Set chart setting for map set to OSM
- Select a ride; then select map tab

Behavior: The map displays fine (e.g. no "for development purposes only" overly as in Google Maps), but the error dialog from Google saying "This page can't load Google Maps correctly" still floats on map on tab load. Error dialog properly goes away after "OK" dismissal, but returns each time map tab is displayed (e.g. select another ride).

![maps](https://user-images.githubusercontent.com/552327/46536039-3d503780-c87b-11e8-985e-24d1ce4687bc.jpg)

**Comment by amtriathlon** [comment]
It's a known issue, Google Maps client API is used even when OSM is selected, it is being replaced by @grauser in current master: https://github.com/GoldenCheetah/GoldenCheetah/commit/f7f2ca1d651cf2e161fbf372b18c5b646431c7d4

**Comment by petermoo** [comment]
Is there an issue/entry for that change, one we can track?

**Comment by amtriathlon** [comment]
Last update: 
https://github.com/GoldenCheetah/GoldenCheetah/commit/5ed9890149a1d035f4f042877409f7f7840093ea

**Comment by grauser** [comment]
Fixed with last commit : ca9b5b27bbaba51da3d06faf35ad2f20f5fe94a9

**Comment by ghhs1979** [comment]
Is this in the 3.4 version of GC? Apparently I downloaded 3.5-DEV1806 before a permanent fix was made available. This is totally annoying. I finally installed 3.5-DEV1903 and it is fixed. I didn't see this issue indicated in any release notes (that I read and searched). Maybe I was not looking in the right place.
