### ISSUE TITLE
Incorrect power values for time segments

### ISSUE THREAD

**Issue by Vertux** [GoldenCheetah/GoldenCheetah#2928]
I use the macOS version Dev v3.5 1806. In the last weeks I have seen a couple of my workout statistics where the power values of time segments are not plausible - here is an example:
![bildschirmfoto 2018-09-16 um 15 34 19](https://user-images.githubusercontent.com/10457918/45597071-c2f06e00-b9c6-11e8-8a22-dc51af4e3baf.png)
As you can see, the power value of the 20min segment is lower than the power value of the 30min segment, which is impossible, because it is a rule of thumb that the average values remain the same or decrease as time periods increase.

**Comment by liversedge** [comment]
Check your data - e.g. in the ride editor fix all the anomalies.

**Comment by Vertux** [comment]
@liversedge I cannot see any anomalies in my raw data (Zwift), I am pretty sure it is a bug. If you look at the graphics the segments are not plausible.
![bildschirmfoto 2018-09-16 um 15 31 47](https://user-images.githubusercontent.com/10457918/45715032-84f47500-bb93-11e8-8589-adf0d0ef3655.png)
![bildschirmfoto 2018-09-16 um 15 32 18](https://user-images.githubusercontent.com/10457918/45715046-8d4cb000-bb93-11e8-8ac6-4617be3af2c3.png)
![bildschirmfoto 2018-09-16 um 15 32 01](https://user-images.githubusercontent.com/10457918/45715052-92116400-bb93-11e8-9f01-6f1fa040d903.png)
It seems the segment algorithm does not pick the right parts on the timeline.

**Comment by amtriathlon** [comment]
> because it is a rule of thumb that the average values remain the same or decrease as time periods increase.
This is not true, think about it.

**Comment by Vertux** [comment]
@amtriathlon In my case, the average power for 20min **AND** 30min have to be 194W, because there is no rule that the sections must not be completely congruent - it would not make any sense either.

> This is not true, think about it.

Please explain your opinion, I do not know what you mean.

In my humble opinion an algorithm would take the power data of the longest time section e.g. 60min and move it along the whole data timeline until it finds the average power maximum, then it would take the next smaller time section and would do the same thing again etc.

**Comment by amtriathlon** [comment]
Suppose you ride 10min at 300w followed by 10min at 200w and then 10min at 300w
Which are your 20’ and 30’?
Is your rule true in this case?
BTW the users forum is a better place for this kind of discussion.

**Comment by liversedge** [comment]
There is an entry in the FAQ that explains why power at longer durations can be higher than at shorter.

**Comment by Vertux** [comment]
@liversedge Thank you, I was not aware of that.
