### ISSUE TITLE
Cannot Close RideImportWizard Dialog

### ISSUE THREAD

**Issue by ohyonghao** [GoldenCheetah/GoldenCheetah#2930]
This was tested on Linux with Qt5.11.1 compiled from master, but originally also found from the 3.5 tag also compiled with the same settings.
Importing Activities the Abort and Finish button always runs Save as the QString comparison of the dialog text includes an & in front of the text which is not present from the string returned by tr(). Because of this the dialog can never be closed and the program must be killed to remove the dialog.

**Comment by liversedge** [comment]
I think you are exp[eriencing a translation issue, what language are you using?

**Comment by flyingflo** [comment]
Hey, if you are on KDE, I bet it is the issue I documented a while ago. There is a simple workaround.
[Check this FAQ!](https://github.com/GoldenCheetah/GoldenCheetah/wiki/Working-around-KDE-shortcut-injection)

**Comment by ohyonghao** [comment]
Hello flyingflo, I think that is exactly what is causing the issue. I think it is indicative of a design flaw in relying on label text information for control structure. I have submitted a pull request that uses enumeration instead of overloading of button function. I shouldn't have to change my KDE global configurations to satisfy a single program. This would then remove that feature from all Qt programs in KDE where it might be desirable.

**Comment by flyingflo** [comment]
I fully agree. 
The core problem is threefold:
- the arguably bad style of *encoding dialog workflow state in button text* in goldencheetah,
- QT encoding keyboard accelerators in button text with and `&`,
- and the KDE accessibility module that injects such accelerators automatically,

and hence, changes the button text and consequently breaks goldencheetah's dialog workflow state.

Unfortunately, the button-text-state-encoding pattern is used in many dialogs, so to really get rid of this flaw it would need a lot of small changes.

If you're interested, this [pull request](https://github.com/GoldenCheetah/GoldenCheetah/pull/2165) documents how we found out.

**Comment by liversedge** [comment]
Changing button texts is evil, disabling it only affects QT apps.

**Comment by liversedge** [comment]
@david-waterworth I think that's probably a good idea - QString::replace("&","") returns a ref but does not alter the string itself.

**Comment by ohyonghao** [comment]
Doing a replace on the string for comparison is sweeping the problem under the rug. It's a hack. The proper way is through enum states for controlling workflow. My pull request includes three buttons, each with the correct text, and a function to control and set the current state. The functions to save, abort, and finish are independently connected to their respective buttons signals so that an Abort button always aborts, a Save button always saves, and a Finish button always finishes, independent of any text mangling that might occur.
Is there a proper branch to put pull requests on other than master? Two of us have made apparent fixes to the same code. The discussion should follow which already completed solution to go with rather than additional hacks.

**Comment by david-waterworth** [comment]
I notice that QObject appears to have an objectName property. You could perhaps set this to an ID and then use instead of the button text in the compare. That way nasty injections, or changes in language won't impact?

**Comment by liversedge** [comment]
I'm pretty sure (but would need to check) that objectName is used to route signals, so would be a bit of an issue.
