### ISSUE TITLE
Best Half Marathon/Best Marathon Curves

### ISSUE THREAD

**Issue by crgal** [GoldenCheetah/GoldenCheetah#2932]
This curves should be mapped against runs only but when I create a chart with this curves they map data from workouts that have bike assigned as sport giving incorrect chart for the user.

**Comment by liversedge** [comment]
You can use a filter in the chart to only use runs:
![screenshot from 2018-09-19 09-13-49](https://user-images.githubusercontent.com/142876/45740131-6cfd0f80-bbec-11e8-88c4-4e8513b89852.png)

In future its best to use the user forums for help:
https://groups.google.com/forum/#!forum/golden-cheetah-users
