### ISSUE TITLE
Summary View in different language

### ISSUE THREAD

**Issue by VeloPerformance** [GoldenCheetah/GoldenCheetah#2933]
hi,

I upgraded from V3.4 to 3.5 now my summary review is in a different language(russian i think)
The rest of the app is in english. Is there a way to fix this?

**Comment by liversedge** [comment]
The language setting is in preferences.

**Comment by liversedge** [comment]
You may also want to check the font settings.

**Comment by VeloPerformance** [comment]
Hi Mark,

I sent you a screen grab of my summary page. I can’t seem to find the font tab menu that you told me about.

Regards
Zaid

**Comment by liversedge** [comment]
the font choice is in appearances.
