### ISSUE TITLE
Strava sync still active despite disabling it in Golden Cheetah

### ISSUE THREAD

**Issue by nfkb** [GoldenCheetah/GoldenCheetah#2936]
Hello, 

I have found that Strava automatic sync was still active for an athlete despite deleting all cloud accounts. 
I had to revoke access in Strava to stop this.
At the opening of Golden Cheetah, it stills tries to connect to something but at least no files is downloaded.
![screenshot 2018-09-28 a 17 01 24](https://user-images.githubusercontent.com/23717480/46216654-62571e80-c340-11e8-9478-5305d86fe31f.jpg)
![screenshot 2018-09-28 a 17 01 16](https://user-images.githubusercontent.com/23717480/46216655-62571e80-c340-11e8-8a52-de38c6de45a7.jpg)

Is there something I am misunderstanding ? Thank you

**Comment by liversedge** [comment]
It looks like deleting the entry doesn't delete the details, add a strava account and set the auto import flag to unset.
