### ISSUE TITLE
Tacx Fortius T1932 Not Recognised in 'Find Add Training Device'

### ISSUE THREAD

**Issue by v1sionmaster** [GoldenCheetah/GoldenCheetah#2937]
I've been trying to get my Tacx Fortius recognised by GC for some while and with the colder months approaching thought I'd give it another go.
It's listed within GC, in the available devices for selection (V3.5 -1806). I've done a lot of searching on the forums and have seen entries from Dave Waterworth relating to driver signing etc, but I can't discover (particularly as it's still listed in the add device list) if the issues relating to it not being found have ever been resolved.
I have also seen this:
https://github.com/GoldenCheetah/GoldenCheetah/commit/5e9a5dc75c27a2f0bc6d092807cd46492e3fac3b 
But I have absolutely NO IDEA what to do with the information there! 
Please can anyone talk me through this in simple (ish) terms? ;-)
I'm on Windows 10 64bit.
THANK YOU!!! :-)

**Comment by nickcolloff** [comment]
I have exactly the same problem. Normally use TACX TTS4 but support has been stopped, and features are breaking down one by one. Thought I'd try GC, but m having great difficulty getting my Tacx Fortius T1932 recognized by the software. Found references to libusb-win32-bin-1.2.6.0 as a solution, but this does not apply to Windows 10. Any ideas?

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.

**Comment by nickcolloff** [comment]
I have posted a message on Groups.Google, but can't seem to find the post now. Not entirely sure how to use it.

**Comment by amtriathlon** [comment]
The first post is moderated to avoid spam, so a moderator has to authorize it before going public, next posts are immediate. Meanwhile you could search the forum to look for others having similar issues and how they solve them.

**Comment by nickcolloff** [comment]
Thanks for the feedback. Yes I figured not that the post would need to be moderated, that's why it's not appearing. Have checked my USB devices and the VR_interface from the T1932 device is on USB RootHub - Port 1, which I would have thought would be the obvious first choice for any search by the GC software. I'll see what responses I get. Have looked for others with similar problem, but have not yet seen a solution. Thanks again.
