### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [GoldenCheetah/GoldenCheetah#2938]
i've downloaded Version '3.4' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all. i guess the **CFBundleVersion** and **CFBundleShortVersionString** entries in your **Info.plist** file are missing.
all apps on macOS are supposed to contain valid version information.

**Comment by core-code** [comment]
thanks! just a note, you might want to consider removing the 'CFBundleGetInfoString' key as it has been deprecated for more than 10 years.

**Comment by amtriathlon** [comment]
Will do, thanks!
