### ISSUE TITLE
Wind speed units for the running power estimator

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#2940]
Hi,

I've been using the running power estimator and noticed that sometimes the maximum values I obtain become unrealistically high when the wind speed is inserted in km/h (as stated in the information).
 
The average power of intervals when running against for example a 5 beaufort wind often tops out at 1000W, which seems to be some sort of maximum in the calculation. 5 beaufort is more or less 33 km/h or  9 m/s.

Could it be that wind speed should be inserted in m/s instead? That seems to give a more credible estimation.

Kind regards,

Nigel

**Comment by amtriathlon** [comment]
No, wind speed expected to be in km/h and converted to m/s in the code.

OTOH the wind we are talking about is at center of mass altitude which is much lower than the one informed by meteorological stations at higher altitude, unless you are using an anemometer to measure at ~1m you will need to adjust it, look for wind gradient.

**Comment by nigelvdv** [comment]
Thanks, I learned something about wind speed by using GoldenCheetah!
I keep getting funky results though. I guess I'll just leave wind speed empty for my estimations and disregard windy runs.

Kind regards,

Nigel
