### ISSUE TITLE
support maps from GPXSee-maps

### ISSUE THREAD

**Issue by MeisterP** [GoldenCheetah/GoldenCheetah#2941]
It would be awesome if GoldenCheetah would support the map config files from https://github.com/tumic0/GPXSee-maps (including api keys and user accounts).

http://www.gpxsee.org/doc.html#online
http://www.gpxsee.org/map/1.2/map.xsd

**Comment by amtriathlon** [comment]
I am closing this since it is not likely to be added as a builtin feature, while interested users/developers could eventually use Python embedding to show these maps as a Python chart.

**Comment by MeisterP** [comment]
> use Python embedding to show these maps as a Python chart

That's what I actually do for more advanced maps. So I totally agree that this feature request is obsolete.

**Comment by amtriathlon** [comment]
> > use Python embedding to show these maps as a Python chart
> 
> That's what I actually do for more advanced maps. So I totally agree that this feature request is obsolete.

Great, so you could contribute a Python chart to CloudDB making this feature available for other GC users.

**Comment by MeisterP** [comment]
I don't have CloudDB access since I build GC from source. And [keys are only available for official builds](https://github.com/GoldenCheetah/CloudDB/issues/1)

**Comment by amtriathlon** [comment]
> I don't have CloudDB access since I build GC from source. And [keys are only available for official builds](https://github.com/GoldenCheetah/CloudDB/issues/1)

If you export the chart and attach the .gchart file, I could upload it on your behalf, or you could share it on the users forum.
