### ISSUE TITLE
Golden cheetah crashing on Windows 10 64 bits

### ISSUE THREAD

**Issue by eferragu** [GoldenCheetah/GoldenCheetah#2943]
Hello,

GoldenCheetah would not start. I would get the following Windows log.

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-10-12T19:52:59.373088800Z" /> 
  <EventRecordID>2934</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-HO5TTTO</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>120746132285</Data> 
  <Data>4</Data> 
  <Data>APPCRASH</Data> 
  <Data>Non disponible</Data> 
  <Data>0</Data> 
  <Data>GoldenCheetah.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>583170c6</Data> 
  <Data>GoldenCheetah.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>583170c6</Data> 
  <Data>c0000005</Data> 
  <Data>000000000004bdd9</Data> 
  <Data /> 
  <Data /> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB8C0.tmp.mdmp \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB95E.tmp.WERInternalMetadata.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB97E.tmp.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB97C.tmp.csv \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB98D.tmp.txt</Data> 
  <Data>C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_GoldenCheetah.ex_eb27d75e213f8521b44be8a195b835bc39dea87_8a86c129_4f30bfe5</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>4e728a7c-662b-43c1-a9ec-e747b2e54a1b</Data> 
  <Data>268435456</Data> 
  <Data>5f7bd8491fe404e942ece64726a6affc</Data> 
  <Data>0</Data> 
  </EventData>
  </Event>

Then I desinstalled R and it launched.

Does anybody know why R is causing a problem ? Maybe the R version I had is not compatible with GC ?

Thanks for your feedback.

Emmanuel

**Comment by amtriathlon** [comment]
Yes, R introduced a binary compatibility issue in v3.4, so you need to check which version was used to build GC in About... and use a version accordingly or disable R in GC.
This is a bug and feature tracking system, please use the users forum for questions.

**Comment by vap0rtranz** [comment]
Not a bug?!   'binary incompatibility' is the very definition of a kind of bug everywhere that I've seen software deployed.  Whether you blame the developers of R or GC doesn't matter.

"WON'T FIX" would be a better label if the GC dev believe this is R's fault.

**Comment by amtriathlon** [comment]
GC v3.4 works with R v3.3, R v3.4 and v3.5 were introduced after GCv3.4 release and they are binary incompatible, if you want R integration wit GC v3.4 you need to install R v3.3.
If you want to use R v3.4 or v3.5 with GC you need to install one of the latests GC v3.5 DEV builds.

**Comment by vap0rtranz** [comment]
OK I was going to try an older release of GC (v3.3) but good to know the latest Dev build fixes this.
