### ISSUE TITLE
Cannot create workouts on MacOS V3.4

### ISSUE THREAD

**Issue by acormack93** [GoldenCheetah/GoldenCheetah#2945]
When creating a workout via the wizard or editor, the message: "workout name already exists in directory:0" then it prompts the removal of the file. End result is that it cannot be created. Also tested in the latest MacOS development build

**Comment by amtriathlon** [comment]
This happens when your user doesn’t have write permission on the configured workouts directory, check your settings in Preferences.

**Comment by acormack93** [comment]
Ergh PEBKAC, thanks closing
