### ISSUE TITLE
GC refuses to communicate with Joule GPS/GPS+

### ISSUE THREAD

**Issue by TheWayOfTheWheel** [GoldenCheetah/GoldenCheetah#2947]
Ubuntu 18.04.
When GC attempts to communicate with a Joule GPS/GPS+, it always throws up a Timeout error after several seconds.

I've verified that there is no linux-related issue with the FTDI driver by plugging in an FT232R-based USB serial interface with TX and RX connected together (i.e. loopback), opening /dev/ttyUSB0 wtih puTTY, and observing that anything typed is echoed back.

**Comment by amtriathlon** [comment]
You need to add an udev rule specific for the Joule, see: https://groups.google.com/d/msg/golden-cheetah-users/wYUheHWYsEE/EdeAVoElAAAJ
