### ISSUE TITLE
Typos in Spanish translation

### ISSUE THREAD

**Issue by jgpallero** [GoldenCheetah/GoldenCheetah#2953]
I've detected and corrected a typo in the Spanish translation file gc_es.ts. Almost all appearances of the word "Resumen" were misspelled as "Resúmen", but the correct word is without accent. As I'm not a git nor github user (I have an account, but I'm not a git user) I attach the corrected gc_es.ts file.
[gc_es.tar.gz](https://github.com/GoldenCheetah/GoldenCheetah/files/2549233/gc_es.tar.gz)

**Comment by amtriathlon** [comment]
Thanks!
