### ISSUE TITLE
Issue with connecting multiple devices

### ISSUE THREAD

**Issue by MichaelBavaria** [GoldenCheetah/GoldenCheetah#2954]
HI, I am already with version 3.5.
I only can connect one device with GC. If I connect my heartbeat device, I can´t connect my smart trainer anymore, Same the other way around!!
Is there a solution?

**Comment by MichaelBavaria** [comment]
Hi - to make it more precise: I am using the 64bit version on windows and and USB ANT+ stick

**Comment by liversedge** [comment]
When setting up an ANT device you need to pair all devices you want to use together.
Do not pair each sensor as separate devices.
There is a tutorial on the GC website on using train view that might be useful.

**Comment by Joern-R** [comment]
2nd hint is: If you have connected a set of devices and configured "Autoconnect" in the 
"Options -> Train" configuration, the autoconnected device is blocking the setup of a new configuration file (list of devices is empty). 

You can either switch off the "Autoconnect" feature, or just de-active the connection via the "Green Button" on the Trainer Screen. I just re-tested the feature with DEV1810 (Win64Bit) by removing the existing configuration and adding a new one - Both Trainer FE-C and HR Strap work perfectly fine.

**Comment by MichaelBavaria** [comment]
Hi guys,
just checke your advice. Deleted all devices and re-connected them in one shot as "one" unit!
Now it is working perfect!
Great and clear advice!
Thank you very much !
Michael
