### ISSUE TITLE
About the L/R Balance computation

### ISSUE THREAD

**Issue by jgpallero** [GoldenCheetah/GoldenCheetah#2955]
Hello:

The way GC computes the Left/Right Balance can be seen in the file src/Metrics/LeftRightBalance.cpp and looks like
```
while (it.hasNext()) {
    struct RideFilePoint *point = it.next();
    if (point->cad && point->lrbalance > 0.0f) {
        total += point->lrbalance;
        ++count;
    }
}
```
i. e. only data with cadence greater than 0 and lrvalue greater than 0 is used.

But this way can be problematic, at least in my case. I own a Favero Assiona DUO pedals and I've noted that when I'm not pedaling sometimes the value 100 is assigned to the lrbalance field instead the expected 0 value, so the average computation is slightly biased towards the left pedal. This assignation of 100 comes more or less randomly, as I have confirmed via programming with the Garmin SDK, and also in the Edit tab of GC (actually I've not made a deep research, so this is the reason I say "more or less randomly", but it is obvious that the 100 values must be addressed as 0 values). As sometimes the cadence measure have some lag there are data with lrbalance=100 with cadende!=0, and also data with lrbalance=0 with cadende!=0, which is the reason the code has the check lrbalance > 0.0f instead of only the if (point->cad). I don't know if this occurs with other power meters or with Favero Assioma DUO with other firmware than 3.0, but at least in my case I've noted this situation. So a more refined code must be in my opinion
```
while (it.hasNext()) {
    struct RideFilePoint *point = it.next();
    if (point->cad && point->lrbalance > 0.0f && point->lrbalance < 100.0f) {
        total += point->lrbalance;
        ++count;
    }
}
```
Other possible solution could be to check for power greater than 0 instead cadence or lrbalance. Or maybe a complete check like
```
while (it.hasNext()) {
    struct RideFilePoint *point = it.next();
    if (point->watts > 0.0f && point->cad && point->lrbalance > 0.0f && point->lrbalance < 100.0f) {
        total += point->lrbalance;
        ++count;
    }
}
```
in order to be absolutely sure. These additions have no side effects and work for any power meter.

Other question to consider, which I support, is whether other metrics like pedal smoothness average, torque efectiveness average and maybe others should be computed taking into account these lrbalance values, i. e., if these metrics should be take into account only valid lrbalance values.

I attach a small GNU Octave/Matlab code in order to see some results. The 'mean_gc' value is the result computed by GC, and the 'mean_proposed1' and 'mean_proposed2' are the ones proposed here (I prefer the second one). I attach also the original *.fit file where data of power 0 and lrbalance 0 or 100 can be seen
[2018-11-10-11-29-13.fit.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2568636/2018-11-10-11-29-13.fit.zip)
[lrb.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2569697/lrb.zip)

I've written also a Python chart, and I've uploaded it to CloudDB. It is called Balance and implements the second option I proposed (it works only with the entire workout), i. e., it checks for point->watts > 0.0f && point->cad && point->lrbalance > 0.0f && point->lrbalance < 100.0f. I would like other users check it in order to test if the problem appears with other powermeters than Favero Assioma

**Comment by jgpallero** [comment]
Was this suggestion finally included in the GC 3.5 January 2019 build?

**Comment by jgpallero** [comment]
Hi,
Was this suggestion taken into account?
Thanks

**Comment by amtriathlon** [comment]
The second option seems safe. Do you like to make it a [Pull Request](https://help.github.com/en/articles/about-pull-requests)?
