### ISSUE TITLE
Missing support for x-train CSVdata

### ISSUE THREAD

**Issue by Captain-Gryf** [GoldenCheetah/GoldenCheetah#2956]
X-trainer (http://www.x-trainer.dk) supply data in csv format, it would be nice if these files could be imported into GoldenCheetah

**Comment by Captain-Gryf** [comment]
Files for change has been committed.

**Comment by Captain-Gryf** [comment]
I'm not able to commit the changes, so here is the patch, I hope some one can assist in committing the changes.

[0001-Support-for-x-Trainer-http-www.x-trainer.dk-added.patch.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2592902/0001-Support-for-x-Trainer-http-www.x-trainer.dk-added.patch.zip)

**Comment by Captain-Gryf** [comment]
Anyone who can help me with this one?

**Comment by Captain-Gryf** [comment]
Anyone who can help me with this one?

**Comment by grauser** [comment]
commit 7cf6783
