### ISSUE TITLE
Settings for new user

### ISSUE THREAD

**Issue by plandes** [GoldenCheetah/GoldenCheetah#2959]
I'm new to Goldencheetah.  I had a previous copy installed, but reinstalled to the latest development version.  Every time the app starts it prompts for which athlete to use.  In addition, settings will only persist after one relaunch.  However, after that, some settings are not kept (i.e. font size).

**Comment by Estee31** [comment]
I seem to have the same problem. New settings remain stored after the first relaunch, but the next time starting GC comes with the message that an upgrade from version 3.2 requires a new folder structure, after which all Athlete settings are reset to default values.
Did you find a solution already ? Are you working on OS ?

**Comment by amtriathlon** [comment]
This may help https://github.com/GoldenCheetah/GoldenCheetah/wiki/Upgrade_v3.2_Troubleshooting_Guide and in the users forum probably you can find more info and feedback from other users.

**Comment by plandes** [comment]
@Estee31 I am on MacOS (10.13) and this comes from a brand new install.  This is the first time I am using the software.  The settings stay for one restart of the software, then _most_ of the settings revert back to defaults.

**Comment by plandes** [comment]
@amtriathlon Regarding the "refactored" athlete directory--the bug seems to be centered around this new refactored code.  I have blown that directory away several times and tried many different things from several fresh reinstalls.  Nothing works.  This is definitely a bug.

**Comment by amtriathlon** [comment]
System specific settings are stored outside of GC folder, see for details: https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-DATA#where-are-settings-located

**Comment by plandes** [comment]
FYI--The problem for me was resolved when I did a clean install and re-install of GoldenCheetah.  I believe the issue had something to do with that I installed Microsoft R (for my own research) and then told where GC where the install was.  This time I didn't do that.  Hope this helps others down the line.  **Authors**: *Thank you* for making this awesome software!

Regards,
Paul
