### ISSUE TITLE
Average swim pace calculation - trends tab

### ISSUE THREAD

**Issue by miichall** [GoldenCheetah/GoldenCheetah#2960]
In Trends / Summary / Averages swim pace has wrong value presented. Current calculation is done as total distance divided by total time (m/min) and description is given as min:sec/100m.

**Comment by amtriathlon** [comment]
No, the units are min/100m (or min/100yd according to settings) but it includes all your activities, if you want just the swims use a Sport filter on the side bar.
Please see the FAQs (https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-RUNNING-&-SWIMMING) and the users forum (https://groups.google.com/forum/#!forum/golden-cheetah-users) for usage questions.
