### ISSUE TITLE
Many menu items not working

### ISSUE THREAD

**Issue by ingen63** [GoldenCheetah/GoldenCheetah#2962]
Hoi Mark,
 I update today to 3.5-DEV-1802, and many menu's have avery strange behaviour.As soon as I click on  Activities->Details  I am no longer able to click on any other menu item except the first one (Activities->Summary) . For the other menu items it works. 
 For trends it is even worse switching the meenu only works reliable if I jump always back to the first menu entry. Other wise the other entries are not selectable. I already created a new test athlete under a new fresh athlete directory and only imported 2 old trainings, but didn't help..

Following infrastructure used:
Windows 10 Versio   1803
Laptop with 32 GB

**Comment by liversedge** [comment]
What language are you using?

**Comment by ingen63** [comment]
German, btwI switched GC to english and still the same

**Comment by Joern-R** [comment]
Why are you using 1802 - latest version is DEV1810 - please uninstall and test with the latest DEV version.

**Comment by Joern-R** [comment]
Hard to say what the reason is. I am building the Windows Builds (and using them nearly daily on my own) in Windows 10 - 64Bit - 1803.

One idea - if you did not change/configure a lot in the standard chart menus would be to reset the layouts to the default.

In German it's located under "Ansicht->Layout zurücksetzen". You can/have to do this for each of the Main Menues "Trends", "Tagebuch", "Aktivitäten" separately.

**Comment by ingen63** [comment]
I have already done that and also created a complete new user. Dient fix it. Is there a way to get all traces of 3.4 removed before I start installing 3.5 again? E.g Registry and so on.

**Comment by amtriathlon** [comment]
The wiki explains were the settings are on each platform: https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-DATA#where-are-settings-located, pleas reopen if you can recreate after removing them and installing the last v3.5 build from: https://github.com/GoldenCheetah/GoldenCheetah/releases

**Comment by amtriathlon** [comment]
The experience from a couple of similar cases, menus not working and GoldenCheetah locked in Full Screen mode, shows it can be solved removing
`C:\Users\USERNAME\AppData\Roaming\goldencheetah.org\GoldenCheetah.ini`
when GoldenCheetah is closed.
