### ISSUE TITLE
ErgDB is down

### ISSUE THREAD

**Issue by gitmopp** [GoldenCheetah/GoldenCheetah#2963]
The ErgDB [https://www.73summits.com/ergdb/](url) is down since at least one weak.
I didn't find any mirror with ERG files.
It seems like ErgDB is down forevery, so it can be removed.

**Comment by Schwinni77** [comment]
Too bad I just started with GC and couldn't download even one workout. :(

**Comment by liversedge** [comment]
Its annoying because we can host them, but the original maintainer is not responding at all.

**Comment by Ramoonus** [comment]
maybe you should change the issue to: remove ErgDB functionality?

**Comment by valdelin** [comment]
is it possible to setup another erg database such as https://trainerdb-84bdb.firebaseapp.com?

**Comment by avanlaningham** [comment]
Hello, I am the creator of https://www.ergdb.org.   I have all or most of the workouts from the previous  https://www.73summits.com/ergdb/    If you guys want me to build an API compatible for GC I will.  That would make it a simple change to switch to my URL from the old non-existent API.

**Comment by liversedge** [comment]
Hi Avan,

That would be terrific. If you already have an API we could just adapt to use that.
If you calc TSS and IF and a description etc that would be useful.

I'm liversedge@gmail.com if you want to discuss offline.

**Comment by sscafidip** [comment]
That sound terrific... is there any chance for both to integrate comments for each segment, and possible to add additional fields into GC, like force, segment comment, next everything

**Comment by avanlaningham** [comment]
sscafidip, I am open to just about anything that benefits riders. This sounds fine but I need to understand the use cases better. For example, I don't think an MRC file has segment comments in it but I could be wrong.  Just need to understand it better.  We can discuss verbally or my email is alex / ergdb.org

**Comment by sscafidip** [comment]
Dear Alex
I also take the chance to ask you whether the new ergDb portal would import .erg\.mrc. So we can store what we have built in GC
Thanks
S

**Comment by avanlaningham** [comment]
S, yes I definitely planned on doing it via API but now I realize web upload is great feature I can do quickly, should be able to do it next week. For now one file at a time but could be in bulk in the future. If your workouts were in the old ErgDb they should be here already.

**Comment by mondoshiwan** [comment]
great news! is there any chance that we can store/export a workout file also as a fit file in GC to throw it on a Garmin device?

**Comment by avanlaningham** [comment]
> Dear Alex
> I also take the chance to ask you whether the new ergDb portal would import .erg.mrc. So we can store what we have built in GC
> Thanks
> S

I now allow upload of ERG and MRC files on the site.  You can see a quick video here
https://www.ergdb.org/2019/02/16/feature-upload-erg-or-mrc-file/

I don't support this [COURSE TEXT] yet but I will work on that.

**Comment by avanlaningham** [comment]
> great news! is there any chance that we can store/export a workout file also as a fit file with GC to throw it on a Garmin device?

Yes, I want to add FIT file export for sure.  This is a bit harder.  We would love to have it done before summer.

**Comment by batsonjay** [comment]
@avanlaningham Workouts on ergdb.org currently have a username / author associated with them. I'm the author of some.

Is website login working at ergdb.org - and by this I mean "Should I, as author of some workouts, be able to log in under the username/email address that originally created them? If it should, then let's take a dialog out of this GitHub thread to see why it's not working for me.  My email: batsonjay/gmail

**Comment by avanlaningham** [comment]
> @avanlaningham Workouts on ergdb.org currently have a username / author associated with them. I'm the author of some.
> 
> Is website login working at ergdb.org - and by this I mean "Should I, as author of some workouts, be able to log in under the username/email address that originally created them? If it should, then let's take a dialog out of this GitHub thread to see why it's not working for me. My email: batsonjay/gmail

Hello batsonjay.  I am happy you asked this question.  I am not affiliated with the previous site but did get permission to take it over.  I would love it if previous users would let me know their old username and I can associate them to your new account.  I have created a blog post with a list of all the old usernames. If you let me know yours I can fix it.  Read here

https://www.ergdb.org/2019/02/18/users-and-workouts-from-73summits-com/

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/0e08a7b8bc8a6f7495981ddeb633ce1e2b487e3e

**Comment by cameronmehl** [comment]
I'm still confused about this issue - can someone **please** put it in clear english how to download the ErgDB to GC 3.5 dev build 1903?

**Comment by amtriathlon** [comment]
As the dates show this issue was fixed after GC 3.5 dev build 1903 was published.

**Comment by amtriathlon** [comment]
I am re-opening this issue since it is not working anymore, the error reported is `NoSuchKey`:

```
$ curl https://shared-web.s3.amazonaws.com/ergdb/json/public_workouts.json
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>ergdb/json/public_workouts.json</Key><RequestId>C3888GZ1MCFRW9YF</RequestId><HostId>UCZShC6krgowSELsv8poheBp2EphLmIT9LJD2zRccII5ihYZ0icvC2ETgOJvK832mGGjKF/zozsRSkrU73xLU/EZTjbIV6bqE4rsmf7+Cus=</HostId></Error>
```

@avanlaningham, Did the API change recently?

**Comment by avanlaningham** [comment]
Oh No... I had no idea that was still working.  I am trying to see if I can recover it.

**Comment by avanlaningham** [comment]
Fixed. Sorry about that.

**Comment by avanlaningham** [comment]
Just for the record in this thread.  ERGdb is now https://trainerday.com in case for any reason I don't respond here or anyone needs anything.

**Comment by amtriathlon** [comment]
Thank you, Ale!

I will change "Download workouts from ErgDB" to "Download workouts from TrainerDay" in GoldenCheetah for the next builds.

**Comment by avanlaningham** [comment]
It's best to send me an email at support@trainerday.com for API key, or maybe we could do private messages here.  I am not a github user that much... just git user :)
