### ISSUE TITLE
'Connect Wizard' crashes when attempting to connect to CompuTrainer using serial/usb

### ISSUE THREAD

**Issue by tellgent** [GoldenCheetah/GoldenCheetah#2964]
Running latest Win10.  Racemate1, et al are able to discover correct port and connect to CompuTrainer successfully.  Tried different GC versions both 32 and 64 bit without success.  The GC 'Add Device Wizard' not only fails to connect to the CT, but also hangs - 'Not Responding' Windows message.

GC error report summary:

Version Info

Build date: Jun 7 2013 14:56:55
Build id: 3010
Version: 3.0
DB Schema: 48
OS: Win
QT	4.8.4
QWT	6.0.1
GCC	4.8.0
SRMIO	yes
OAUTH	1.0.1
D2XX	yes
QWTPLOT3D	0.2.6
KML	none
ICAL	0.44
USBXPRESS	yes
LIBUSB	yes
Wahoo API	none
VLC	yes
LUCENE	2.3.3.4

**Comment by liversedge** [comment]
Please upgrade.

**Comment by tellgent** [comment]
Is this issue closed?  As I pointed out in the description, the problem persists regardless of GC version 3.0.0 ...,  3.3, 3.4. noth 32 and 64 bit.
I really like GC and would like to have it working.  I am currently running it on an older version on an Win XP machine.
What's most frustrating is the crashing rather than trapping the condition and providing some diagnostic. 
My background is software development but does not include comm/driver issues.
Thanks for any help.
__________________________________________
Stephen P. Young
home +1 (250) 931-1789  mobile +1 (360) 328-2577

 

    On Wednesday, November 21, 2018, 11:59:06 PM PST, Mark Liversedge <notifications@github.com> wrote:  
 
 
Closed #2964.
