### ISSUE TITLE
Incorrect speed GPX from endomondo

### ISSUE THREAD

**Issue by bwiklak** [GoldenCheetah/GoldenCheetah#2965]
I'm getting incorrect speed when importing data exported from Endomondo.
AFAIU it's caused by Endomondo dropping some data points form export so not every second is recorded.
As a result we have a situation where for those missing seconds software remembers last distance and suddenly when new record is present we have another distance and speed is calculated as this new distance difference divided by one second instead of time between actual and previous record.
If e.g. in second 5 we have a distance 100m and in second 8 we have a distance 118m it's 6 m/s but I'll get 18 m/s. 

What can be done with it?
Alternatively, if I would like to add support for such files where should I look in the code? If GoldenCheetah assumes that data is recorded every second I can imagine at least adding better estimation to missing time frames.

**Comment by amtriathlon** [comment]
There is a tool to fill the gaps in recording by interpolation, see https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Activity-Processing#edit-tool-fix-gaps-in-recording to run it manually and https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Preferences_Data-Fields#processing to configure for automatic processing on import.

**Comment by bwiklak** [comment]
I checked this but it does not work. I don't see any effect on track.
I checked release and dev vesion. Tried parameters ranging from default to (0.5,1000), gpx and tcx format.

[20181124_15030[gpx].txt](https://github.com/GoldenCheetah/GoldenCheetah/files/2618735/20181124_15030.gpx.txt)

Both graph and exported data is intact.
