### ISSUE TITLE
Best time for standard distances - Add 8km

### ISSUE THREAD

**Issue by Stumont** [GoldenCheetah/GoldenCheetah#2966]
Hello Team,
I just started using Golden Cheetah this past weekend and am really impressed - no bugs so far and lots of great functionality for an analyst geek !

Is there any chance of adding 8k to the list of best times for standard distances, as the gap between 5km to 10km is quite large and I run tons of runs between 5km and 10km. It'll be much appreciated if you can make this little change please?

**Comment by amtriathlon** [comment]
You can define it as a custom metric (or directly plot it) using the bestime(distance) function, please see the wiki and use the users forum for help.
