### ISSUE TITLE
Default  graphics not working

### ISSUE THREAD

**Issue by albondigor** [GoldenCheetah/GoldenCheetah#2971]
Default graphics on trends are not working (the ones of the column of the left)... anyone have solve the problem?

**Comment by amtriathlon** [comment]
1st entry on the FAQ: https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-MOST-COMMON-QUESTIONS-OF-ALL#Why-are-my-charts-blank-or-data-is-missing

**Comment by albondigor** [comment]
I reset the charts of the sidebar to default, but it still not working when i click on any of the charts, it does not happen anything). If I restore the whole layout, would I loose all the charts (with my own configuration)? Thank you

**Comment by amtriathlon** [comment]
Yes, but you can manually recreate the Library chart, which is required for the sidebar to work, see: https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Side-Bar_Trends-view#charts
BTW, this is a tracking system, there is a users forum to get help.

**Comment by albondigor** [comment]
Problem solved, thank you. Great job for the open source!!
