### ISSUE TITLE
erratic speed with GC 3.4 and Kinetic inRide 3 ANT+ PWR and SPD

### ISSUE THREAD

**Issue by v-src** [GoldenCheetah/GoldenCheetah#2972]
Just wondering if anyone else has used GC 3.4 with the new-ish Kinetic inRide 3 gizmo for Kinetic trainers to provide power, speed and cadence over ANT+ (as well as BTLE).

I updated my Kinetic Road Machine Smart recently to use the inRide 3 and it is working fine with GC 3.4 for recording power and cadence, but speed is highly erratic.  With the wheel size set to 170mm (as directed by Kinetic to match the roller circumference), speed reads OK much of the time, but will very frequently drop down from the expected value of for example 18 mph to 1.5 mph even as power and cadence are stable for an 18 mph effort.

I've done training sessions recorded simultaneously on a Garmin 500 over ANT+, the Kinetic Fit app over BTLE, and GC 3.4 over ANT+ where they match up reasonably well on power and cadence, but speed is stable only on the Garmin head unit and Kinetic Fit app, while dropping to ~1.5 mph very frequently on GC.  I've sent the files to Kinetic for them to investigate the case from their end.

Is anyone else seeing this type of behavior?

If I change my device config in GC to read from a Wahoo Blue SC for speed over ANT+ (with a normal wheel size), speed is stable throughout.

I'm wondering if GC is having trouble reading the inRide 3's SPD and PWR data from the same ANT ID (is that the right terminology?) and it is showing up in the erratic speed reading?

**Comment by v-src** [comment]
Hm...looking at the speed data where it goes from good to bad back to good when it should be stable, it's suspicious that the ratio of the good/expected speed and the bad recorded speed is basically the same as the ratio of the "default" wheel size 2100mm and the specified wheel size 170mm.

So is there an error occurring while computing some speed events and it's falling back to some defaults?  But if that were so, I would expect the bad speeds to be 12 times faster rather than slower at 1/12 times.

**Comment by v-src** [comment]
[20181208-1047 golden cheetah ANT+.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2660057/20181208-1047.golden.cheetah.ANT%2B.zip)

Here's the .csv capturing a training session with the frequent, bad speed readings (mostly ~2.5 kph rather than ~30 kph)

**Comment by r1032987** [comment]
I also have the same speed issue with the Kinetic InRide 3 pod. I am using GC v 3.3 over ANT+ connection.
My speed varies between 300 km/h, 157 km/h, and actual speed.

**Comment by Ramoonus** [comment]
which firmware version are you using?

**Comment by Ramoonus** [comment]
> I also have the same speed issue with the Kinetic InRide 3 pod. I am using GC v 3.3 over ANT+ connection.

have you tried v3.4 or 3.5?

**Comment by v-src** [comment]
I'm running firmware v1.2.  The kinetic fit app says it is up to date.

On the GC side, I saw the problem with the 3.4 stable release as well as 3.5 dev build 1810, which I'm still running.

**Comment by r1032987** [comment]
I also have  firmware v1.2, and is up to date. I will add the cadence data from the InRide 3 is low by 7-10rpm. I have seen this on the Kinetic iOS app, and on my new Garmin 520 Edge +. I will try  GC 3.4 on another windows 10 x64 laptop over the weekend.

**Comment by v-src** [comment]
Are you also seeing the jumpy/erratic speed issue on your Kinetic iOS app and Garmin 520?  Or are you talking about the low cadence issue when you refer to those receivers?

If the latter, I believe that is a totally separate issue from the jumpy/erratic speed issue.  From what I've read, lots of folks see low cadence readings produced from the inRide on all receiving devices/apps. 
 Kinetic has tried to improve the accuracy of their cadence guestimate, but if cadence is important for your training, it's probably worthwhile to get a magnet-based cadence sensor.

I suppose GC could use an adjustment factor to account for the low cadence reading, but I wouldn't expect it to be much beyond adding some pre-configured offset since the one-reading-per-second nature of the ANT+ data GC is getting far less than what is available to the inRide for its already inaccurate cadence guestimate.

**Comment by r1032987** [comment]
I apologize for not being clear. When using the InRide 3 pod with:

- GC 3.3 over ANT+, I see wild speed changes, up to 300km/h. I didn't have a cadence window open in GC train mode. 

GC 3.4 over ANT+, I see lesser speed changes, up to 115 km/h. I didn't have a cadence window open in GC train mode. 

GC 3.4 over bluetooth, GC just won't connect using win10 x64 laptop bluetooth. GC just won't pick up on my InRIde bluetooth. Neither  with a known good BLE heart rate transmitter. This doesn't impact me. I wanted to try all the same.

Garmin Edge 520+ over ANT+, speed number are good, and cadence numbers are 5-7rpm less. When compared to wired cateye cycle computer.

V-SCR, you are completely correct regarding the cadence magnet sensor.

**Comment by fickert** [comment]
I am experiencing the same issue using the latest 3.5 dev build (1903). The power and speed readings are fluctuating wildly (up to 430 km/h), only the cadence numbers look realistic. On the kinetic app (Android) the measurements are fine.

**Comment by igloox** [comment]
> GC 3.4 over bluetooth, GC just won't connect using win10 x64 laptop bluetooth. GC just won't pick up on my InRIde bluetooth. Neither with a known good BLE heart rate transmitter. This doesn't impact me. I wanted to try all the same.

On a tangentally-related note, I can't get GC to 'see' my BLE InRide2 or BLE heart-rate monitor either. Ubuntu 16.04 or 18.04, GC 3.4 or 3.5.

**Comment by amtriathlon** [comment]
> On a tangentally-related note, I can't get GC to 'see' my BLE InRide2 or BLE heart-rate monitor either. Ubuntu 16.04 or 18.04, GC 3.4 or 3.5.

BLE pairing is fixed in v3.5 RC2X for Linux and MacOS, sensors are looking for when you start the device, the pairing step is not really necessary and it was misleading in previous versions.
