### ISSUE TITLE
Wahoo Elemnt .fit file error on importation 

### ISSUE THREAD

**Issue by MaxTurcHot** [GoldenCheetah/GoldenCheetah#2973]
When trying to import .fit file coming from a Wahoo Elemnt Bolt device, it creates an importation error as follow:
Error - local type 1 without previous definition

I'm using the following version of GC:
Build date: May 3 2018 19:02:13
Build id: 3944
Version: 4.0.0-DEV1607
DB Schema: 128
Metrics: 278
OS: Linux

I provided pictures of:
- the version tag.
- The importation error
- A problematic fit file coming from a Wahoo Elemnt device.

![gc_fit_error](https://user-images.githubusercontent.com/9440862/49698702-46b89180-fb95-11e8-817f-77fa866b718e.png)

![gc_version](https://user-images.githubusercontent.com/9440862/49698704-4c15dc00-fb95-11e8-8628-c47f229e9654.png)

[fitfile.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2660611/fitfile.zip)

**Comment by amtriathlon** [comment]
This is an old development version, please use the last one from: https://github.com/GoldenCheetah/GoldenCheetah/releases

**Comment by MaxTurcHot** [comment]
It is working now.
Version 4.0.0 is older than 3.5, that was not obvious since I'm a new user.
I am extremely impressed by all the work done for this software. I am addict !
