### ISSUE TITLE
Usability problem: Coach mode - select athlete on start

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#2977]
I have usability problem, as athletes Coach/Team sport manager. I can't select athlete on start GoldenCheetah, always start last used profile. It's very long to wait last used profile to load, to select in menu open different profile.

solution:

1) In preferences new check box: "Always select athlete on start" or inverted setting "Always use last opened athlete profile on start".

Dialog to select profile show only if GC crash.

2) Select profile in command line arguments

Select profile in command line arguments as: "GoldenCheetah --profile=\<uuid\>".

If --profile argument used, then open only this profile and ignore last used (if settings in article "1)" set to use last opened".

**Comment by amtriathlon** [comment]
This is the default behavior, but it can be overridden at he command line: you can specify the athlete you want to open or -- to prompt interactive selection independently of the last opened one.

```
GoldenCheetah DEV-V3.5 1810 (3968)
usage: GoldenCheetah [[directory] athlete]

--help or --version to print this message and exit
--server            to run as an API server
--debug             to turn on redirection of messages to goldencheetah.log [debug build]
--clouddbcurator    to add CloudDB curator specific functions to the menus
--no-python         to disable Python startup
--no-r              to disable R startup

Specify the folder and/or athlete to open on startup
If no parameters are passed it will reopen the last athlete.

```

**Comment by MaksVasilev** [comment]
Thanks, in Windows it is difficult to learn about it.

But that's only half the problem. I have many profiles (>20) and I would like to have quick shortcuts only to 2-3 and the rest to choose through the selection dialog at the start.

**Comment by liversedge** [comment]
If the athlete does not exist then it will prompt every time e.g.

GoldenCheetah **nonono**

Will cause the cyclist dialog to popup (assuming you don't have an athlete called **nonono**)

**Comment by MaksVasilev** [comment]
It's not very elegant, but it works.

**Comment by amtriathlon** [comment]
-- also works and is more elegant ;-)
