### ISSUE TITLE
Usability problem: non-Unicode string in zone settings

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#2978]
I often have to transfer an athlete's profile between different computers. Most often Linux - > Windows.

All zones description in config files use native locale and broken if profile moved to different computer.

Affected files:

hr.zones
power.zones
run-hr.zones
run-pace.zones
run-power.zones
swim-pace.zones

Solution: always save all translation-related files only in UTF-8 codepage.

**Comment by MaksVasilev** [comment]
![non-unicode-zones](https://user-images.githubusercontent.com/1708135/49937611-58c56780-fee8-11e8-8613-009c4411a067.png)

**Comment by MaksVasilev** [comment]
I checked. The error is not fully fixed. Zone files for the new profile are now written correctly in UTF-8, but the display uses a non-Unicode locale.
![path835](https://user-images.githubusercontent.com/1708135/55556016-3baee180-56ef-11e9-8e1d-d25223fa2869.png)

**Comment by amtriathlon** [comment]
I cannot reproduce the problem, It works for me, I just created a new Athlete and imported an activity in current master:
![Screenshot from 2019-04-04 11-07-24](https://user-images.githubusercontent.com/1444784/55562527-7c483400-56ca-11e9-8ac4-61393bf1ba98.png)
I don't understand Russian but the strings looks reasonably good.

**Comment by MaksVasilev** [comment]
@amtriathlon Your image looks good, is it Mac?. But I tried to move completely the directory with profiles of all athletes and to create a new profile. The problem persists. Maybe Qt/C++ under Macos and Windows use different defaults when reading from a file.

**Comment by amtriathlon** [comment]
That was on Ubuntu, on Windows 10 I can reproduce the issue, but I have no idea which the problem is.
