### ISSUE TITLE
Golden Cheetah doesn't see my Polar H7?

### ISSUE THREAD

**Issue by jkms** [GoldenCheetah/GoldenCheetah#2983]
My HRM is connected:
![image](https://user-images.githubusercontent.com/660916/50240229-1208bf00-0379-11e9-8d69-322a8f092b65.png)

But GC doesn't find it?
![image](https://user-images.githubusercontent.com/660916/50240288-382e5f00-0379-11e9-8e48-c966076b0174.png)

Fedora KDE 29.

**Comment by jkms** [comment]
Hmm... Maybe a duplicate of #2771 ?

**Comment by jkms** [comment]
Maybe it's not a duplicate. I borrowed a friend's ANT dongle, setup the udev rules, and I still can't detect my HRM. Though, now more device options are shown when searching for BTLE?

![image](https://user-images.githubusercontent.com/660916/50297517-d7169200-0431-11e9-927d-c47c6582b7eb.png)

**Comment by amtriathlon** [comment]
The H7 supports only one BT connection, check if you have other device previously connected to it.

**Comment by jkms** [comment]
thanks @amtriathlon, but I'm pretty sure it's connected correctly.  I can see the device connected via `bluetoothctl`, and I disabled bluetooth on my phone...

**Comment by jkms** [comment]
Is this even supported on Linux? I think I read in a forum that BTLE is only supported in OSX, but I can't find confirmation one way or the other...

**Comment by J-F-M** [comment]
No luck here either with the Polar H7 on neither Mac OS (3.4) nor Linux (3.5) (builtin BT 4.0/4.1 in both cases)

Initially my Tacx Vortex wasn't seen either on BTLE, until I added an Ant+ dongle, after which it was visible to GC also via BTLE. But no change for the H7.

**Comment by amtriathlon** [comment]
I think this is related to #2771, the presence of an Ant+ dongle enables discovery of dual BTLE/ANT+ sensors, but it should fail with BTLE only ones s.t. Polar H7

**Comment by amtriathlon** [comment]
@jkms please see the last update to #2771, if you ignore the searching state and just go ahead and complete the device setup it should work when you activate the created device, the problem is just in the wizzard.
Any feedback is welcome.
