### ISSUE TITLE
Problem with Athlete Weight

### ISSUE THREAD

**Issue by shippet** [GoldenCheetah/GoldenCheetah#2984]
Hi all,

This is the version of GC I am using:
![version](https://user-images.githubusercontent.com/6514246/50383992-f1ce5c80-06f8-11e9-859d-73c14737b186.PNG)

I found a problem with Athlete Weight showed in the Activities --> Summary tab
![summary](https://user-images.githubusercontent.com/6514246/50383999-204c3780-06f9-11e9-9e6f-ae631d662b4d.PNG)

Although I set my weight to 64.0 Kg in the Activities --> Details tab, 
![detail](https://user-images.githubusercontent.com/6514246/50384070-1b3bb800-06fa-11e9-8109-eeb7fd801dab.PNG)

it still shows 63.0 Kg in the Activities --> Summary tab.
It is 63.0 Kg because the lastest weight I set in Athlete --> Measurements is 63.0 Kg
![athlete](https://user-images.githubusercontent.com/6514246/50384054-d748b300-06f9-11e9-8dd2-7b7920d7de9d.PNG)

The activity is created by riding on a smart trainer and recording with Golden Cheetah.
I used GC v3.4-DEV before and it works fine(import .tcx files), then I upgraded it to v3.5-DEV and bought a smart trainer and created activity like so, maybe this is the reason?

Thank you for your reply. Have a nice training session!

**Comment by amtriathlon** [comment]
If you want to use Weight at the activity level you need to remove the time dependent entries since these have priority.
