### ISSUE TITLE
Cannot authorise dropbox account

### ISSUE THREAD

**Issue by Mickyduck55** [GoldenCheetah/GoldenCheetah#2987]
Hi just updated Susans GC to latest Dev build and she can no synch using dropbox.  We have gone through the auth process and dropbox end seems fine as we got the new devise alert but we get this error in GC
![gc](https://user-images.githubusercontent.com/22476749/50548052-ee2d5f00-0c3d-11e9-91c4-6b84d62e3cdd.PNG)
All is OK using her account on my PC
Thanks

**Comment by amtriathlon** [comment]
The users forum is a better place to get help, see https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md

**Comment by Mickyduck55** [comment]
Just done that thanks so closed this
