### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by JacoLouw** [GoldenCheetah/GoldenCheetah#2988]
Hi guys

I just installed the latest beta version 3.5 DEV1810 and the scaling of the menus, charts etc is almost not readable anymore. I am using a ms surface pro and it was all fine in version 3.4.

I know this is a beta version and not the final product, just wanted to give you a heads up.
Keep up the great work!

Best regards
![annotation 2018-12-31 160752](https://user-images.githubusercontent.com/18688673/50562729-d8d83380-0d16-11e9-9621-0cfbbba3d424.gif)

**Comment by Ramoonus** [comment]
are you using 4K?

**Comment by mow4cash** [comment]
For years I have had the same issue. I'm using 4k. I have to use windows scaling but that messes up GC. I just deal with it and hope one day it gets fixed. I'm surprised this is not a bigger issues since 4k is widely used.

**Comment by liversedge** [comment]
We will ultimately deprecate the summary view, the overview chart is a replacement.
The issue is basically related to using the Qt webview (chromium) for rendering.

**Comment by mow4cash** [comment]
Out of curiosity I took off windows scaling. The latest GC is now scaling correctly (maybe it included a Qt update)? After a quick check it looks like the calendar is the only thing not scaling correctly.

The summary view is great. Is the plan add the missing summary metrics into overview before depreciation? I would be sad to lose the summary view. Overview looks great with movable widgets but I don't see any way to customize the metrics it uses.
![image](https://user-images.githubusercontent.com/16341157/52169928-3395ee00-270e-11e9-92d0-097eb822c13e.png)

**Comment by liversedge** [comment]
The configurability is the thing that is holding up 3.5 being released.

**Comment by mow4cash** [comment]
That's great to hear configuration is on the way. Thanks for all the work you do.

Upon further investigation scaling is still not working correctly. I have no clue how it worked for a brief time in the third screen shot, now it's back to the same view as @JacoLouw . I take it windows 4k users are out of luck and should not expect a fix unless Qt changes something?

**Comment by jifizipazu** [comment]
> 
> 
> We will ultimately deprecate the summary view, the overview chart is a replacement.
> The issue is basically related to using the Qt webview (chromium) for rendering.

@liversedge 
I hope you are not meaning that also Summary and Details view would be deprecated?!

Summary and Details view is compulsory. It's the most useful and used view. This new Overview view is totally useless. ...at least it's for me or everybody how want to see facts of activity. If Summary and Details view will be deprecated, it's sure that I will never upgrade to a new version of Golden Cheetah. My programming skills aren't enough to restore this view into GC3.5.

**Comment by amtriathlon** [comment]
On Windows 10 changing high DPI settings to Override high DPI scalling / Scaling perfomed by System solves this problem, including the mini-calendar in Activities view:

![image](https://user-images.githubusercontent.com/1444784/55595040-76793f80-5718-11e9-980c-04d7aefca842.png)

This was reported at the users forum and confirmed to work

**Comment by amtriathlon** [comment]
Added an entry to the Wiki: https://github.com/GoldenCheetah/GoldenCheetah/wiki/Scaling-Issues-on-High-DPI-Systems
