### ISSUE TITLE
Enhancement: Qt 5.12

### ISSUE THREAD

**Issue by Ramoonus** [GoldenCheetah/GoldenCheetah#2993]
Upgrade to a newer version of Qt, for example 5.12 (latest)
http://blog.qt.io/blog/2019/01/11/qt-5-12-lts-road-faster-qml-application-startup/

**Comment by liversedge** [comment]
we build and release to the Qt schedule for LTS.

**Comment by Ramoonus** [comment]
Qt 5.12 is LTS; https://www.qt.io/blog/2018/12/06/qt-5-12-lts-released

**Comment by liversedge** [comment]
Ramon, the build release is managed by the build team, we are currently building Windows with 5.10 and will move to 5.14. This is not something for the bug/feature tracker.  We are fully aware of the Qt release schedule, LTS and revised policies for open source projects.
