### ISSUE TITLE
Enhancement: GNU R 3.5

### ISSUE THREAD

**Issue by Ramoonus** [GoldenCheetah/GoldenCheetah#2994]
Upgrade from R 3.4 to 3.5
https://cran.r-project.org/src/base/R-3/

**Comment by amtriathlon** [comment]
You can use R 3.5 with GC 3.5 dev 18.10 if you like, it is compatible.

**Comment by Ramoonus** [comment]
the setup contains 3.4

**Comment by petrvod** [comment]
You can go to Tools/Options/General and point it to your R installation directory. But sure, if the devs still plan to package R with GC, it would be nice to get newer version.

**Comment by Joern-R** [comment]
On windows we moved to 3.5.2 in the build (even though not really necessary). Other builds need to decide when to move.

**Comment by Ramoonus** [comment]
bump to 3.6.2?
