### ISSUE TITLE
Teach combine activities to interpolate location from separate gpx based on distance

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3002]
Adding new functionality to combine activities per thread on golden cheetah developers alias:

Extend combine activities to allow synchronization based on distance?
https://groups.google.com/forum/#!topic/golden-cheetah-developers/uBmrVCFCEbk

Will add new option for combine activity merge.

Scenario to support is:

Ride RLV file in golden cheetah, video is synced with a gpx, along with slope. Currently ride does not record virtual location, the location and altitude data is lost. Combine activities can be taught to merge the RLV's GPX's location data back into the ride.

Since these two GPX occurred at different times and have different sample rates the merge is not a straight copy. Instead the training rides' distance can be used to interpolate along the RLV's location data.

**Comment by liversedge** [comment]
OK, cool. I think this is a new merge strategy so should be added as such.
Happy to review code and help out, just use direct email. Happy to chat/hangout too if that helps.

**Comment by liversedge** [comment]
closing since it was added via cd9b03e4840864644ef9cddc3c35359b5a3e5a3e
