### ISSUE TITLE
Crash related to training mode (MacOS)

### ISSUE THREAD

**Issue by fredcostapinto** [GoldenCheetah/GoldenCheetah#3006]
I have used GC for years focusing on analysis and was really happy with it.
Few weeks ago I decided to give it a try for training and it has been great.
Nonetheless, I've had several crashes, always related to training mode.
Thankfully, I never crashed during a ride (in training) but always before I start, either when selecting workouts or changing something in the device configuration.
Usually, I only have a Tacx Vortex Smart & Garmin HRM (both through ANT+ dongle). I've tried BT but it feels less reliable.
It crashes in a sort of random fashion; today it happened when I tried to add a new config using power meter pedals (Assioma Duo). After a few restarts (both of GC and the MacOS computer) it ended up working. I saved the error output in case someone can help me translate it.
Thanks in advance for any input! I'm still very glad to use GC for training now and will keep using it, regardless of these minor annoyances.
Best,
Fred

GC for MacOS build 3968 (DEV_V3.5 1810) - I tried the stable version as well but it didn't solve it.
MacOS High Sierra (10.13.6)

**Comment by fredcostapinto** [comment]
Update: I'm running both versions (stable and dev) in parallel) and it looks like the latest stable version is not prone to crashing in training mode. I keep both because the DEV version seems to handle sync to strava better. Therefore, it looks like the crash in training mode was brought by something in the DEV version.

**Comment by amtriathlon** [comment]
There is a continuous integration build which would be interesting if you can test to see if it fixes this issue. It is build using a newer libusb to access the ANT+ dongle and, additionally, also fixes the Strava sync issue. You can download it from: https://transfer.sh/pVgdx/dev-prerelease-branch-master-build-3271.dmg

**Comment by fredcostapinto** [comment]
Thanks @amtriathlon - I'll give it a try and let you know how it went.
