### ISSUE TITLE
Golden Cheetah disk images couldn't be opened

### ISSUE THREAD

**Issue by sleeponastar** [GoldenCheetah/GoldenCheetah#3007]
Hi,
When starting GoldenCheetah_v3.5_DEV1901_MacOS_64bit.dmg file have a problem "The following disk images couldn't be opened /w Reason: no mountable file system"

Is it possible to fix?
OS: 10.11.6 El Capitan

**Comment by oneilljohn** [comment]
I'm also on 10.11.6 and have the same issue. The checksum for the DMG is correct.

**Comment by dreaman1003** [comment]
macOS Sierra (10.12) and earlier is actually not able to mount the new Apple File System (APFS).
3.5_DEV1901_MacOS_64bit.dmg is new Apple File System (APFS).

Could you rebuild it for older versions of macOS ?

**Comment by cleeland** [comment]
I'm guessing it has an apps filesystem rather than hfs+.

Is the packaging script on github?

**Comment by cleeland** [comment]
Answering my own question, it's in `travis/osx/after_success.sh`, which uses the Qt facility `macdeployqt` to generate the dmg.  According to the very last paragraph on https://doc.qt.io/qt-5.9/osx-deployment.html:
> Note: macOS High Sierra introduced the new Apple File System (APFS). Older versions of macOS cannot read .dmg files that are formatted with APFS. By default, macdeployqt uses the older HFS+ file system for compatibility with all versions of macOS currently supported by Qt. Use the -fs option to specify a different file system.

So, I think we should be able to add `-fs hfs+` to the command line options to get HFS+ formatted DMG.

**Comment by amtriathlon** [comment]
Fixed by d93404fe77d560f0a4cd69775fc85d2387758c2d, published as 18.03 build
