### ISSUE TITLE
Issues importing workouts in training mode (MRC and ZWO)

### ISSUE THREAD

**Issue by fredcostapinto** [GoldenCheetah/GoldenCheetah#3008]
Related to https://github.com/GoldenCheetah/GoldenCheetah/issues/3006

I've tried both the stable and dev versions (latest) for training mode and found two issues (on the MacOS) that I'd like to share.
I've used GC for training before and had mixed results (it used to crash a few times before it worked - see issue #3006 referred to above).
Now, stable build 3954 is able to open .mrc workouts but when I try to run .zwo (that worked perfectly before) they appear totally messed up (see below).
<img width="1280" alt="mrc_build3954" src="https://user-images.githubusercontent.com/37844529/51990857-0b4d8b80-2491-11e9-92fe-98f05c3dddc3.png">
<img width="1280" alt="zwo_build3954" src="https://user-images.githubusercontent.com/37844529/51990890-1a343e00-2491-11e9-83c1-573971db009f.png">
On the other hand, in DEV 1901 I'm able to open both .mrc and .zwo perfectly but it fails to run and gives the message "Cannot open ANT+ device".
<img width="1280" alt="zwo_dev1901" src="https://user-images.githubusercontent.com/37844529/51991119-94fd5900-2491-11e9-8c64-387fd8ff8ae8.png">
<img width="1280" alt="mrc_dev1901" src="https://user-images.githubusercontent.com/37844529/51991214-c9711500-2491-11e9-839a-797464b37d13.png">
Any help is greatly appreciated! I had converted several workouts to .zwo and have used them a lot. Now I'm in the process of rewriting them with the new workout editor (beautiful, by the way) but it's sort of a wasted time.
Thanks a lot!
Fred

**Comment by fredcostapinto** [comment]
Found a workaround my issue. If I open the .zwo file in GC v. 3.5 (dev #1901) and choose "save as" from the editor then I can save a new file that v. 3.4 (3954 stable) will open just fine and run.
The erros reported above still remain but now I can open my .zwo training file and run them.
Best,
Fred

**Comment by mondoshiwan** [comment]
under MacOs 10.12.6 MacBook the same issue with #1901 -> can't connect to ANT+ device.
But with the previous version #1810 there are no issues and a mrc file runs flawless:
![bildschirmfoto 2019-02-10 um 13 05 55](https://user-images.githubusercontent.com/23431166/52534601-eafcb700-2d43-11e9-81b1-d4f32c76a731.png)

**Comment by mondoshiwan** [comment]
meanwhile i did have some crashes with #1810 while trying to connect ANT+
![bildschirmfoto 2019-02-17 um 11 48 32](https://user-images.githubusercontent.com/23431166/52911966-1aaf4000-32ab-11e9-9938-76ecc5357264.png)

the report:
[GoldenCheetah_2019-02-17-114425_MacBook13.crash.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2872862/GoldenCheetah_2019-02-17-114425_MacBook13.crash.zip)

**Comment by amtriathlon** [comment]
I’m closing this since the original issue is fixed in v3.5 and we are approaching releases so not doing more fixes on v3.4.
For the collaterals please try the RC2X  the automatically generated  build for Mac, which uses libusb-1.0.23 and it can be downloaded from: https://transfer.sh/sKSxD/dev-prerelease-branch-master-build-3309.dmg
