### ISSUE TITLE
Unsupported SRM File Format version: 17

### ISSUE THREAD

**Issue by jyanota** [GoldenCheetah/GoldenCheetah#3009]
Hello, is it possible to drag and drop SRM files from SRM X file directory? Example attached.
[jasony-20181231075921.srm.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2814015/jasony-20181231075921.srm.zip)

**Comment by admrobrts** [comment]
Was this ever resolved? I'm having a similar issue. 

I have data that was imported into SRMX (ver 3.2.632) from a PowerControl7 that Golden Cheetah (ver 3.4 and 3.5 RC1) simply won't recognise. When I try import the .srm files I get the following error:
_ERROR - Unsupported SRM file format version: 20_

Any idea how I can resolve this? I can't re-download the files with Golden Cheetah from the PowerControl7 head unit as they were deleted once imported into SRMX.

**Comment by amtriathlon** [comment]
Looking at the parser supprted versions are 5, 6, 7 and 9:
https://github.com/GoldenCheetah/GoldenCheetah/blob/2b291f28b7381a3bda136d57088db3e4c18f8491/src/FileIO/SrmRideFile.cpp#L113
History shows that part of the code has not received significative updates in several years.

**Comment by amtriathlon** [comment]
> Any idea how I can resolve this? I can't re-download the files with Golden Cheetah from the PowerControl7 head unit as they were deleted once imported into SRMX.

According to this tutorial you could export your files in FIT format: http://www.srm.de/support/software/srmx/tutorials/

**Comment by liversedge** [comment]
use fit files. we are no longer developing support for srm file formats.
