### ISSUE TITLE
Change map provider via menu

### ISSUE THREAD

**Issue by mod-bike** [GoldenCheetah/GoldenCheetah#3012]
Hello,
just downloaded Version 3.5-DEV1901
No Option to Change map Providers in menue?
How do i change e.g. to OpenStreetMap?
Regards

**Comment by Joern-R** [comment]
Please make yourself familiar with the basic concepts of chart configuration. Even though the Wiki does not reflect the latest updates it still covers the main concepts:

https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Charts-Bar_General-handling

Please use the users forum to get help. See https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md
