### ISSUE TITLE
Strava workouts synchronize without data

### ISSUE THREAD

**Issue by alexlrobertson** [GoldenCheetah/GoldenCheetah#3019]
Strava activities synchronize but have no data after being synchronized.

Build date: Jan 19 2019 11:03:34
Build id: 3969
Version: DEV-V3.5 1901
DB Schema: 149
Metrics: 359
OS: Mac OS X 10.13

**Comment by loicprieur** [comment]
same issue on
Build date Jan 19 2019 23:46:37
Build id: 3969
Version: (developer build)
DB Schema: 149
Metrics: 359
ubuntu 4.18.0-15-generic x86_64

Synced as expected until 2 days ago.

Attached sample activity json
[2019_02_13_18_11_11.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2867450/2019_02_13_18_11_11.zip)

**Comment by MarkRebuck** [comment]
Strava had an issue where they finally hit their 2^32'nd workout.  I'm wondering if the Strava workout ID is a 32 bit integer in GoldenCheetah?

**Comment by sergiogoro** [comment]
Same thing here

I've just updated to the latest:
```
Build date: Jan 19 2019 10:37:40
Build id: 3969
version: 3.5-DEV1901
Metrics: 359
OS: Win
```

But, also noticed this glitch a few days ago, with the previous dev build.

Thx for your work team! ;)

**Comment by suskozaver** [comment]
Same here, same build.

**Comment by sleeponastar** [comment]
Hello,

The same problem on a previous dev build
Build date: Sep 27 2018 15:24:53
Build id: 3968
Version: DEV-V3.5 1810
DB Schema: 148
Metrics: 358
OS: Mac OS X 10.11

**Comment by ritzelrocker** [comment]
same here with 18010 & 1901.

**Comment by Joern-R** [comment]
It look like Strava has changed / introduced the rate limiting as described here: https://developers.strava.com/docs/

Or even is more restrictive now like desribed here: https://twitter.com/champagnethomas/status/1095743506193305600 

Interestingly the HTTP code 429 is not even mentioned in the original documentation in case of rate limiting - but seems now to be in place.

**Comment by liversedge** [comment]
Strava is having performance issues. It’s not clear yet if this is throttling or server side problems.

**Comment by doubledadster** [comment]
> Strava activities synchronize but have no data after being synchronized.
> 
> Build date: Jan 19 2019 11:03:34
> Build id: 3969
> Version: DEV-V3.5 1901
> DB Schema: 149
> Metrics: 359
> OS: Mac OS X 10.13

Same issue, same build except OS: Mac OS X 10.14

**Comment by ntadmin** [comment]
Same effect an a clean install of GoldenCheetah:

Build date: Jan 19 2019 11:03:34
Build id: 3969
Version: DEV-V3.5 1901
DB Schema: 149
Metrics: 359
OS: Mac OS X 10.14

Set up Strava sync form scratch. It finds 11 activities in then past month to sync. I tell it to do so. The first 8 sync correctly, the most recent three (dated Feb 14, 16, 19) sync but with no data as described above.

**Comment by edserbroers** [comment]
same issue here also indeed on the previous builds! all files since feb 14 are empty

**Comment by liversedge** [comment]
@Joern-R you are right there is a throttle on the streams endpoint, we need to slow down requests...

**Comment by grauser** [comment]
Like @MarkRebuck proposed the issue is in 32 bit integer for Strava ID.

**Comment by hellgelino** [comment]
Same problem here. Newest Dev Build Windows 64Bit.

**Comment by liversedge** [comment]
We will get a dev build out this weekend 23/02 with this fix.

**Comment by jonbev** [comment]
Would it be possible to have a AppImage built for this fix please?

**Comment by amtriathlon** [comment]
The AppImage is available now

**Comment by alexlrobertson** [comment]
Looking good in the new app image!

**Comment by ritzelrocker** [comment]
it works fine :-)
Thanks !
