### ISSUE TITLE
Attempt to authorize Withings account results in "Client id not authorized"

### ISSUE THREAD

**Issue by spawn-github** [GoldenCheetah/GoldenCheetah#3022]
Using 3.5-DEV1810 build 3968 (debian provided package, on x64), I'm attempting to connect my Withings account, and running into a "Client id not authorized" message.

Using the Options/Athlete/Accounts tab, I'm able to successfully submit my Withings username and password via the Oauth pop-up window. The resulting Withings page prompts to "Select a user" (there are multiple users associated this Withings account). When I select the appropriate user, it results in plain page with the "Client id not authorized" message, and nothing further happens.

It looks like a another user reported similar behavior via the google user group back in April: https://groups.google.com/d/msg/golden-cheetah-users/Qjn4Xe8ShQ0/Gi4g3gIiCAAJ

Happy to provide any additional information I may have left out.

Thanks!

**Comment by spawn-github** [comment]
Poking at the withings API, based on info I can find in the source code, reveals the "Client id not authorized" message is being returned by Withings. 

The GC source (core/system.h) also reveals the withings client id is private to the GC build system, so I'm not able to troubleshoot this further.

**Comment by liversedge** [comment]
I just tried it and it works fine. Check with latest dev build.

**Comment by spawn-github** [comment]
It just occurred to me that the Debian folks are probably compiling their packages from source, without any of the cloud oauth tokens? Does that sound plausible? If so, is there general guidance on how this situation should be handled?

**Comment by liversedge** [comment]
Use official builds from GoldenCheetah.org

**Comment by doylek** [comment]
I'm getting this same error with both the 1901 and 1903 development builds from Github on Ubuntu 16.04 LTS. I'm not building my own as @spawn-github suggested. The download new measurements feature worked fine in 1810 and previous development builds.
