### ISSUE TITLE
banister response model

### ISSUE THREAD

**Issue by jpcrono** [GoldenCheetah/GoldenCheetah#3023]
unable to find this model in the 3.5 dev build. no mention of how to create this chart in the tutorial. any guidance would be very helpful. great product. any plans to add a yearly training planner?

**Comment by liversedge** [comment]
please use forums for help.

**Comment by jpcrono** [comment]
would you please pass me a link to the appropriate

**Comment by liversedge** [comment]
https://groups.google.com/forum/#!forum/golden-cheetah-users
