### ISSUE TITLE
Exporting garmin .fit activities from GC to csv reduces accuracy of lat and lon by 6 digits

### ISSUE THREAD

**Issue by adamdoescode** [GoldenCheetah/GoldenCheetah#3024]
Short: Batch export of activities results to csv results in a reduction of lat and lon decimal values by 6 digits. The issue can be worked around by exporting to xml instead, which includes up to 9 digits after the dot.

I have uploaded a series of .fit files to GC to then quickly convert them to csv files using batch export. Exporting to csv and then plotting the result produces a grainy map.
![example low res](https://user-images.githubusercontent.com/13943324/52910441-83b6a800-32eb-11e9-94f5-f332be6533f5.jpg)

If I manually copy the data from entry in GC into an empty csv and perform the same plot I get a far more accurate map of my route.
![high res example](https://user-images.githubusercontent.com/13943324/52910472-e314b800-32eb-11e9-9692-7db4c8dfe179.jpg)

I noticed when exporting to xml I get the high resolution lat lon coords. I am happy to just turn xml into pandas dfs and then doing what I want with those :)

I've never submitted an issue before, let me know if you need more information!

**Comment by liversedge** [comment]
This has literally just been identified by another developer working on train view.
Will be fixed shortly.
