### ISSUE TITLE
Not downloading any data from Strava

### ISSUE THREAD

**Issue by CycingS** [GoldenCheetah/GoldenCheetah#3026]
I have always had no issues with syncing my GC account with Strava, however since the 14th of Feb I've not been able to successfully sync any data. The ride is recognised but no data is imported to GC and all durations, distances etc are 0....

**Comment by maartenmennes** [comment]
yes, same problem here

**Comment by liversedge** [comment]
See #3019 release of new dev build this weekend 23/02.
