### ISSUE TITLE
Option to go to activity from Trends

### ISSUE THREAD

**Issue by xabiliza** [GoldenCheetah/GoldenCheetah#3028]
v3.5- DEV1810
Is there any option to go directly to the activity clicking in Bikestress point ? Would be nice feature to have some options like this with right button click. now only shows a summary of the activity

![screenshot - 190222 - 002](https://user-images.githubusercontent.com/28784280/53226594-dbeb0280-367b-11e9-840e-9f95b991c7e7.png)

**Comment by amtriathlon** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/issues/922
