### ISSUE TITLE
Power phases of Garmin Edge 1030

### ISSUE THREAD

**Issue by msporting** [GoldenCheetah/GoldenCheetah#3030]
The power phases recorded by System Vector with the Garmin Edge 1030 are not read correctly in GC 3.5 Dev. 1903.

**Comment by Ramoonus** [comment]
do you have any data?

**Comment by msporting** [comment]
enclosed a typical FIT file from Garmin Edge 1030

[2019-02-20-12-59-53.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2902263/2019-02-20-12-59-53.zip)

**Comment by grauser** [comment]
Tested your file.
Power phases and PCO values match between GoldenCheetah and GarminConnect.

**Comment by msporting** [comment]
When I import this file with GC DEV 1903 I get very high scores for the power phases. You can not work with these values. is this only when setting German?
![grafik](https://user-images.githubusercontent.com/6757361/58758484-f86cc580-851b-11e9-8e64-9a83479bd942.png)

**Comment by grauser** [comment]
Yes there few points with outliers/limit values.
I will ignore values > 360°
