### ISSUE TITLE
Athlete Bests Power way off from virtual ride

### ISSUE THREAD

**Issue by rcolombo21** [GoldenCheetah/GoldenCheetah#3032]
There seems to be an issue with the athlete bests incorporation from a virtual ride done on road grand tours and imported through strava. It shows my 20 min peak power at 760. When I go to the date in question there is nothing like these numbers.

**Comment by amtriathlon** [comment]
This likely is a data gap problem, please see the wiki and the users forum to get help as explained in https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md
