### ISSUE TITLE
Version 3.5 dev1901

### ISSUE THREAD

**Issue by OliverUsnu** [GoldenCheetah/GoldenCheetah#3033]
Hi Mark
I updated from 3.3 and now have a number of missing fields in different screens.
The calender summary no longer is visible. 
The sort of the data in calender under activities is no longer in date order could this be the reason?
The number of activities in the month stopped graphing  after the 19th February which is when i did the update. 
Do i need to revert to an older version again?
Cheers

**Comment by edserbroers** [comment]
One of the solutions is to update to version 1903 because this will fix some of your issues

**Comment by OliverUsnu** [comment]
Thanks for that advice the graphs are back and the summary is once more complete.
I will continue checking it out

**Comment by Joern-R** [comment]
I consider your problem to be resolved - if not please use the forum for such questions.

https://groups.google.com/forum/?hl=de#!forum/golden-cheetah-users
