### ISSUE TITLE
Version 3.5 dev1901 & Strava

### ISSUE THREAD

**Issue by rgeorge1985** [GoldenCheetah/GoldenCheetah#3034]
Downloaded the latest Dev version yesterday to correct a Strava synchronising issue where none of the performance charts would show up. 

After downloading, the issue remains. The past data still does not show. 

What do I need to do? Should I delete the old activities and re-sync?

**Comment by amtriathlon** [comment]
Please use the forum for usage questions, there is a thread open for each dev build.
We use issues to track bug and features, see 
https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md
