### ISSUE TITLE
VirusTotal.com seems to have a glitch on GoldenCheetah_v3.5-DEV1903_64bit_Linux.AppImage

### ISSUE THREAD

**Issue by frief** [GoldenCheetah/GoldenCheetah#3035]
I'm **extremely** sure that this is a glitch within VirusTotal.com, just think I should mention it here:

When searching via SHA-256 sum VirusTotal.com claims to have a file with the very same SHA-256 and SHA-1 and MD5 sum as GoldenCheetah_v3.5-DEV1903_64bit_Linux.AppImage

The file is dated **2006-09-18** (or earlier). This should be near impossible (probably even when several galaxies are involved).
I tried to archive the link
https://www.virustotal.com/#/file/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855/details
with https://web.archive.org/ but likely did not succeed.

So I'm filing here and append the screenshot:

![screenshot_20190226_223534](https://user-images.githubusercontent.com/2320349/53449779-f413a680-3a1a-11e9-92f6-b6a637f4a3ad.png)

**Comment by amtriathlon** [comment]
I've updated GoldenCheetah_v3.5-DEV1903_64bit_Linux.AppImage to fix Withings, SportTracks and OpenData secrets so the hashes have changed, I hope they don't collision again.
