### ISSUE TITLE
Version 3.5 dev1903 Overview chart 

### ISSUE THREAD

**Issue by OliverUsnu** [GoldenCheetah/GoldenCheetah#3036]
I have now loaded dev1903 and the Overview chart was in the list of standard charts however it is a plain white screen. By selecting the add more charts I have been able to re create the overview chart and it appears correctly but there is no more option in the top left corner to be able to alter the settings or to cloose the chart out from the list.
The white screen also has no more options to delete it.
Any thoughts of how to fix it?

**Comment by amtriathlon** [comment]
Please use the forum to get help as explained in 
https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md
