### ISSUE TITLE
Fe-C and Tacx Neo

### ISSUE THREAD

**Issue by MarcinBa** [GoldenCheetah/GoldenCheetah#3038]
GoldenCheetah_v3.5-DEV1903_64bit_Windows.exe

I'm not able to start training with Tacx Neo.
Pairing GC and Neo works fine (Neo ID is visible), I selects only Fe-C channel, nothing else.
Then when I push the button to connect I gets "Connected" and short after that "Disconnected".

Is there any log available in GC which can gives me more information? I was programming some simple app with ANT+ in the past, so maybe I can figure it out...

Regards,
Marcin

**Comment by Ramoonus** [comment]
you don`t have any other apps open which can steal the connection?

**Comment by amtriathlon** [comment]
The log file is called antlog.raw, you can find more info and feedback in the users forum
