### ISSUE TITLE
Trend charts are not working

### ISSUE THREAD

**Issue by skraburski** [GoldenCheetah/GoldenCheetah#3039]
Hi,
I'm having exactly the same issues as @JohannesHeinrich in #2939. 
I'm running latest GC DEV V3.5 1903 build 3970 on Mac OS X 10.14.3

I can see all graphs which were predefined (i.e. Stress, PMC, CP History, CP, CP, ...) but when I'm trying to see different chart (i.e. PMC TriScore) it's not rendering any datam, neither in form of chart or data table.

<img width="1422" alt="zrzut ekranu 2019-03-5 o 12 15 56" src="https://user-images.githubusercontent.com/26367162/53802119-45eb8d80-3f41-11e9-9a1a-f9ca906b59f8.png">

**Comment by amtriathlon** [comment]
Please see the Wiki FAQs and use the users forum to get help, see https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md
