### ISSUE TITLE
Activity List Not Drawing Correctly on Windows with High-DPI/with DPI Awareness Switch

### ISSUE THREAD

**Issue by arunh** [GoldenCheetah/GoldenCheetah#3040]
When starting GC on a high-DPI screen (3840x2160) with the 'windows:dpiawareness=0' switch, the activity list is not correctly rendered and does not use available space.

![annotation 2019-03-05 213132](https://user-images.githubusercontent.com/804578/53839236-e6b46a00-3f8e-11e9-8012-20415998df07.jpg)

If I grab the vertical divider and move it, the activity list correctly redraws itself...

![annotation 2019-03-05 213213](https://user-images.githubusercontent.com/804578/53839286-0ba8dd00-3f8f-11e9-856a-467ff039c738.jpg)

Not a major bug, definitely cosmetic.

**Comment by amtriathlon** [comment]
We recently added this to FAQs: https://github.com/GoldenCheetah/GoldenCheetah/wiki/Scaling-Issues-on-High-DPI-Systems
