### ISSUE TITLE
Unable to import charts (.gchart)

### ISSUE THREAD

**Issue by v1sionmaster** [GoldenCheetah/GoldenCheetah#3041]
I wanted to backup all of my charts, saving them individually as .gchart, but have found that when I attempt to drag the files onto the open GC window (to import them), I get a 'forbidden symbol' - a circle with diagonal line across. I am therefore unable to restore any of my own saved charts or import those from others (as .gchart). 
This is the first time I have tried this so I have no idea if it is version dependant - I'm on v 3.5 - Dev1903 Build 3970 on windows 64 bit.
Am I doing something wrong or might this be a bug?
PS I've just tried uploading a custom chart as an alternative to saving them locally, but get an error message saying my email address is invalid so that avenue isn't open to me either.
Many thanks!!

**Comment by Joern-R** [comment]
I just exported a chart and imported again - via Drag&Drop without problem - Win10/64Bit Build DEV1903. Can you please attach a chart definition here. If Github does not like the extension, just add .txt to it. I will test the import so see what's happening.

**Comment by v1sionmaster** [comment]
Hi Joern - THANK YOU!
Please take your pick from any of these:
All are *.gchart with the file type changed to *.txt
[Level 4 Fatigue Profile.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/2947142/Level.4.Fatigue.Profile.txt)
[Level 5 Fatigue Profile.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/2947143/Level.5.Fatigue.Profile.txt)
[Level 6 Fatigue Profile.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/2947144/Level.6.Fatigue.Profile.txt)
[Level 7 Fatigue Profile.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/2947145/Level.7.Fatigue.Profile.txt)
[PMC & RR.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/2947146/PMC.RR.txt)
Have you been able to upload charts?
Thanks so much for your help!
Tim

**Comment by liversedge** [comment]
Which chart are you looking at when you drop?
Try any other than the overview chart?

**Comment by v1sionmaster** [comment]
Hi Mark

It makes no difference which Trends tab or Activities I have open (I’m in tabbed mode and not tiled) or where I attempt to drop the file i.e. on the trend, on the side panels, on the tab bar etc, etc – I am still shown the prohibition sign.

I’m not quite sure which the ‘Overview Chart’ is that you refer to.

I tried to take a screen shot, but of course the mouse pointer disappears! So I’ve taken a photo with my phone. You can see the prohibition symbol circled in red on the enclosed photo.

I hope I’m just doing something wrong! ;-)

If there is ANYTHING else I can try, or other info I can provide, please let me know!

Thank you so much for all you and your team do for us!!!!!

Tim

 

IMG_4962.JPG

**Comment by v1sionmaster** [comment]
![IMG_4962](https://user-images.githubusercontent.com/38918646/54071087-f0c0bc00-425f-11e9-893e-31e6494d5184.JPG)

**Comment by liversedge** [comment]
Make sure they have the .gchart extension. Looks like your filenames aren't quite right.

**Comment by Joern-R** [comment]
The reason why it's not imported is that you use a lot of "." within your files as seperators. Just removing the extra "." in the names before ."gchart" extension allow the import. While technically Windows allows such file name I have rarely seen such a pattern. Will look into the code if the behaviour can easily be changed so that the import ignores the extra "." signs before the file extension. For now you have to rename your files.
Joern

**Comment by v1sionmaster** [comment]
Hi Mark - I changed the file types from .gchart to .txt so that they could be uploaded here. 
The file type .gchart is not supported.
 'We don't support that file type' (in red) appears when you attempt to drag them to the message window. 
They need the file type changing back to .gchart to be able to use them or test them...
Tim

**Comment by v1sionmaster** [comment]
Joern-R
When following the link to my uploaded charts, I see what you mean! I didn't add those "." separators, which were in fact spaces in the original file name. So they have somehow been substituted during the upload/download process - very strange!
The charts were simply exported to my desktop via the individual trends 'More/ Export Chart' drop down menu. I didn't manipulate them in any way after that.
I have tried both removing the spaces in my own locally stored .gchart files, downloading my own uploaded charts from this thread and removing the "." separators and converting back to .gchart, but the result is still the same - I can not re import the charts - or any from other sources either.
Is there any merritt in uninstalling GC and starting again. I keep GC backed up, but am not sure if I would then have to re create the custom charts that I use at the moment or re enter all of the data paths under  athlete options/General as well as any power zones that I have created. I would need advice on that aspect.
Thanks for your help.... :-)

**Comment by Joern-R** [comment]
I removed the additional "." from the file name and had no problem to import. I also created a chart with a description containing an number of " ", exported it, and imported without any issue.

What's your operating system and version ? 

De-installing / re-installing will most likely not fix such an issue. Something is wrong with your file name. And it's for now a mystery for me what's going on.

**Comment by v1sionmaster** [comment]
Hi

I’m on windows 10 64 bit with all updates current.

Might it help to send me a different file to try? Perhaps that would rule out any local file name issues?

I run GC from:

"C:\Program Files\Golden Cheetah\GoldenCheetah.exe" Tim -platform windows:dpiawareness=0: and run as administrator .

ANY file type (not that you’d expect any thing different) shows the prohibited symbol when dragged over GC – it appears that GC doesn’t recognise the file type .gchart…. Stating the obvious maybe…..

**Comment by Joern-R** [comment]
Sorry to say - I have not idea what the reason for this behaviour could be. I am building/running on Win10/64Bit 1809. No such issues. Also had a look into the code. The additional "."s do not make a difference. My first thinking that the additional "." caused the problem were actually wrong. I just imported one of your charts (without removing the extra ".").

So I am out of ideas - maybe someone can replicate. I can't.

**Comment by v1sionmaster** [comment]
OK Joern – thanks for sparing the time and effort to try! J

**Comment by v1sionmaster** [comment]
Can GC be backed up in such a way as to include all existing custom trends?

**Comment by amtriathlon** [comment]
>Can GC be backed up in such a way as to include all existing custom trends?

Custom Trends charts are stored in home-layout.xml and charts library on charts.xml, both files are under the config folder in athlete's directory.
