### ISSUE TITLE
Debian 9 - VERSION 3.5 DEVELOPMENT BUILD MARCH 2019

### ISSUE THREAD

**Issue by UlysseUlysse** [GoldenCheetah/GoldenCheetah#3045]
Hello,
Debian GNU / Linux 9 (stretch) 64 bit
GoldenCheetah Latest VERSION 3.5 DEVELOPMENT BUILD MARCH 2019
- Always untimely closures, without error message, for no particular reason ...
Thanks for sharing, have a nice day
Paul Vandenbosch

**Comment by TurboGit** [comment]
I have the same issue on Debian/sid.

**Comment by TurboGit** [comment]
More about this, I found a way to get traces on the console. And as I suspected it is an OpenSSL issue:

```
Python loaded [3.6.3 (default, Oct  6 2017, 00:00:00)  [GCC 4.8.4]]
Auto configuration failed
140104989393600:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
140104989393600:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140104989393600:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140104989393600:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
QMutex: destroying locked mutex
```
Now, not sure how to fix that. I can't find  libssl_conf.so!

**Comment by TurboGit** [comment]
Probably a Goldencheetah issue, a workaround is:

```
$ export OPENSSL_CONF=~/bin/etc/openssl.cnf
$ ~/Téléchargements/GoldenCheetah_v3.5-DEV1903_64bit_Linux.AppImage
```

**Comment by amtriathlon** [comment]
Yes, this has been reported before at the forum for 19.01: https://groups.google.com/d/msg/golden-cheetah-users/j3xqlELi2Gc/6aBBAwoSFAAJ
We have recently switched the build environment from Ubuntu 14.04 to 16.04, if you want to give it a try these build is based on current master: https://transfer.sh/9Jyfb/dev-prerelease-branch-master-build-3094.AppImage

**Comment by amtriathlon** [comment]
For v3.5 the workaround is in the wiki (https://github.com/GoldenCheetah/GoldenCheetah/wiki/SSL-problems-in-some-Linux-distributions), for the next version we plan to switch to Qt5.12.6 or later which uses OpenSSL 1.1 and don’t include libssl/libcrypto in de AppImage anymore.

**Comment by UlysseUlysse** [comment]
@ amtriathlon thanks for the information, good to you
