### ISSUE TITLE
Moving Time incorrect in GC for outside rides

### ISSUE THREAD

**Issue by bobsica** [GoldenCheetah/GoldenCheetah#3046]
I am having this same problem as @clifforddw in the linked issue that is marked "closed". Garmin 520 with smart recording off. The ride gets into Garmin Connect and Strava OK, but importing either file into GC gets the moving time wrong for all my recent rides. An example is attached. TrainerRoad files work correctly.
[gpx-tcx-ride-file.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2954071/gpx-tcx-ride-file.zip)

_Originally posted by @bobsica in https://github.com/GoldenCheetah/GoldenCheetah/issues/2838#issuecomment-471718769_

**Comment by amtriathlon** [comment]
Your files have gaps in recording, please see the wiki and the users forum to get help.

**Comment by bobsica** [comment]
That worked perfect @amtriathlon , thanks very much for pointing that out.
