### ISSUE TITLE
humonhexzone retrieve from R

### ISSUE THREAD

**Issue by sscafidip** [GoldenCheetah/GoldenCheetah#3050]
I have a humon hex device and I l like to create R charts.
Can anyhow tell me how I get from R the data.

From GC Scripting I have this working

XDATA("DEVELOPER","humonhexzone",sparse)
while in R usually I get the data from
y <- GC.activity()

**Comment by liversedge** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Working-with-R#activity

Please use the forums for help requests, this is a bugs forum.
