### ISSUE TITLE
German translation for Z7 "Neuromuskulär" is broken

### ISSUE THREAD

**Issue by Genussradler** [GoldenCheetah/GoldenCheetah#3051]
Build Id 3970

![image](https://user-images.githubusercontent.com/35425767/54473928-d0a07800-47de-11e9-8e28-2d10b5ea720c.png)

maybe a problem with the umlaut "ä"

**Comment by Joern-R** [comment]
Translation is already fixed some weeks. You can adjust your text manually (single click on the text field in configuratin allows editing). Since the zones are user configuration they are not overwritten by corrected versions.
