### ISSUE TITLE
wrong unit in CP chart

### ISSUE THREAD

**Issue by Genussradler** [GoldenCheetah/GoldenCheetah#3052]
in the tooltip of the CP chart the unit is percent. i think it should be watt

![image](https://user-images.githubusercontent.com/35425767/54480695-ea1be100-482b-11e9-9f6f-7d3ef8fe78eb.png)

**Comment by amtriathlon** [comment]
It is percent when you check the Show as percentage checkbox in chart settings, as explained in the wiki: https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_ChartTypes_Trends#critical-mean-maximal
