### ISSUE TITLE
Erratic speed data when using Polar V650.

### ISSUE THREAD

**Issue by carlos-the-fast** [GoldenCheetah/GoldenCheetah#3054]
Switched to a V650 as my main bike computer for road and indoor training, with speed, cadeance and HR as my main metrics.
When I export the .tcx file from Polar Flow to GC the speed data shows some strange characteristics...as shown.
Polar Flow is fine but I much prefer GC for my analytics.
Am I doing something wrong or is Polar still not fully supported?
Carl.
![GC sample](https://user-images.githubusercontent.com/48697008/54645908-62d1a600-4a95-11e9-8e5e-dd34c7b4eab2.PNG)

**Comment by ericchristoffersen** [comment]
Assuming the data is bad this would be pretty easy to filter. Can you share the file?

**Comment by carlos-the-fast** [comment]
Hi,
here's both the csv and tcx files. The csv looks fine? but don't know with the tcx. Which is way i'm confused.
Thanks.
[2019-03-12_16-54-35.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2999587/2019-03-12_16-54-35.zip)
[2019-03-12_16-54-35(1).zip](https://github.com/GoldenCheetah/GoldenCheetah/files/2999588/2019-03-12_16-54-35.1.zip)

**Comment by carlos-the-fast** [comment]
Files added.

**Comment by amtriathlon** [comment]
The TCX file doesn't have speed, the GC TCX parser computes speed using time and distance deltas sample by sample without smoothing, you can add smooth the computed speed using a moving average filter (up to 60sec) using Edit > Fix Speed from Distance

**Comment by amtriathlon** [comment]
Also you can see 
https://github.com/GoldenCheetah/GoldenCheetah/issues/1711

**Comment by carlos-the-fast** [comment]
Latest try, not sure if Iam supposed to have a 'save' button? Always goes back to '1' and doesn't appear to make any change?
![GC fix](https://user-images.githubusercontent.com/48697008/55424557-704c5d00-5578-11e9-838f-7a4475fbb8f3.PNG)

**Comment by amtriathlon** [comment]
In this case Moving Average Seconds = 1 will not make any change since speed is already computed by distance, set it to 60 for example and when you press Ok speed will be smoothed.
As explained in #1711 an alternative would be to sync via Strava.
