### ISSUE TITLE
Cant import fit files from garmin connect or stryd power centre

### ISSUE THREAD

**Issue by CJvdm** [GoldenCheetah/GoldenCheetah#3059]
![image](https://user-images.githubusercontent.com/48939004/54974041-39d07a00-4f9b-11e9-8fd5-912a247c6f98.png)

Getting this error since 15 February 2019 Last successful import was on the 13th Feb
The files contain power data pre and post 13th Feb. I suspect there were
[3386684871.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3006702/3386684871.zip)
 changes on the garmin fit file

**Comment by grauser** [comment]
Could you give us your GoldenCheetah version ?

**Comment by CJvdm** [comment]
![image](https://user-images.githubusercontent.com/48939004/57833965-8413f180-77bb-11e9-950d-669c8ff6140b.png)

**Comment by CJvdm** [comment]
I used Version 3.4 (Current Stable Release) before trying the development release

**Comment by CJvdm** [comment]
------ Original Message ------
