### ISSUE TITLE
renaming segments is not working

### ISSUE THREAD

**Issue by Genussradler** [GoldenCheetah/GoldenCheetah#3061]
Hello,

I created a segment out of a climb intervall. After that it is shown in the segment. Then I right click on the new segment and chose "rename". But when I submit a new name, nothing changes.

I have GC version v3.5-DEV1903

**Comment by amtriathlon** [comment]
I think the problem is the original interval being an automatically created one, which doesn't allow renaming. To avoid confusion we should disable renaming in this case.

**Comment by Genussradler** [comment]
hm, the function to create/copy an interval from an automatically created one ist pretty handy. And I think it worked in a previous version. If you disable the renaming then I have to create these segments manually which could be pretty annoying

**Comment by amtriathlon** [comment]
The segment renaming was implemented after #2111, so it is not the same issue.
It would be useful to know which was the last version when this worked.
