### ISSUE TITLE
Freeze / slow loading, tab switch in v3.5beta

### ISSUE THREAD

**Issue by brentrug** [GoldenCheetah/GoldenCheetah#3062]
Hi,
I used v3.5 beta on my Macbook PRO with Mojave without any issues. I have also R Studio installed, no problems.

Then I added a new activity and suddenly, GC acts very slow and weird.

Even my whole Mac is kind of freezed, except for the mouse for like 1min.

Tried to uninstall GC and remove all activities and also the profile... Didn't help. 

In the end GC starts, but then also switching tabs from Activities to Trends for example takes ages and again my Mac is freezing meanwhile... It happens for all the tabs... Finally you can change tabs, but just suuuuper slow...

It's weird... Is there anything I can do to make the v3.5 work? I really like your software! ;)

**Comment by amtriathlon** [comment]
The users forum is the place to get help, you can find a thread on each dev release and reported solutions to problems like this.

**Comment by brentrug** [comment]
OK, sorry ;)
