### ISSUE TITLE
Wrong elevation calculation from FIT file

### ISSUE THREAD

**Issue by sleeponastar** [GoldenCheetah/GoldenCheetah#3067]
1. Have a problem with Elevation gain (meters) calculation when loading my FIT file into GC. Counts me 1684 meters when loading to GC vs 130 m when loading **the same file** to Training Peaks vs 169 m loading to Strava.

2. Also I do not see running cadence graph in GC but see it in TP or Strava

Recording device Suunto Ambit3 Sport: [Move_2019_03_17_10_24_32_Running.fit.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3029922/Move_2019_03_17_10_24_32_Running.fit.zip)

**Comment by amtriathlon** [comment]
1) See https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-METRICS#Why-is-elevation-different-in-GoldenCheetah-to-my-other-training-software--website
2) You need to enable Run Cadence in the Activity/Ride chart

**Comment by sleeponastar** [comment]
@amtriathlon  I'm sure it is not referred to the article you mentioned as it does not allow me to adjust the value in x10 times. I'm ok with the difference of several meters, but as I'm running flat the Elevation can't be almost 1700m.

**Comment by sleeponastar** [comment]
@amtriathlon moreover if I load the same file extracted from movescount in TCX and load it to GC I get 168m that is quite close to other software. Are you sure the delimiter is not missing?

**Comment by amtriathlon** [comment]
Elevation Gain is recomputed from altitude (https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/Metrics/BasicRideMetrics.cpp#L736), the problem with this file is it has several records when Altitude goes to 0 which provokes a rise in Elevation Gain when Altitude returns to normal, you can check this at the Editor, removing those zeroes fixes the issue.

**Comment by amtriathlon** [comment]
Just added a workaround to avoid this issue: when altitude is missing in some records it is padded with last value instead of zero, it will be available in the next build but requires to re-import the offending files.

**Comment by sleeponastar** [comment]
Thnx, sounds good

**Comment by funkymaster** [comment]
That's great! But just a short similar question. What if altitude is missing for the first couple of records where no valid values are available before? Could we have a similar workaround here? Maybe to fill the missing values with the data of the first valid value (reverse). This would be really nice, because my Elemnt often doesn't write the first couple of values in the fit file. (f.i. heart rate, altitude, temperature)

**Comment by Cogens** [comment]
Also my Elemnt isn't recording the altitutde for the first few seconds, resulting in 0 values. When it starts recording this first value is considered as elevation gain, thus producing a wrong total elevation gain.

**Comment by amtriathlon** [comment]
You can fix that in Data > Raw Data or, if you want an automated solution, create a Custom Data Processor for the task and enable it to run on import. If you have further questions, please go to the users forum.
