### ISSUE TITLE
Fix elevation not working in V3.5 DEV-1903 OS Windows 10

### ISSUE THREAD

**Issue by meindertvd** [GoldenCheetah/GoldenCheetah#3068]
The fix elevation tool consistently returns Network error 4 and then proceeds to delete the existing elevation data to zeroes. Internet connection is working as normal.

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/issues/1800 and https://github.com/GoldenCheetah/GoldenCheetah/issues/2780, you can revert the altitude change using the Undo button in Edit chart.

**Comment by amtriathlon** [comment]
Network Error 4 is TimeoutError: the connection to the remote server timed out, we can make this error more explicit but not to fix it.
