### ISSUE TITLE
V3.5 DEV-1903 OS Win. problems with font encoding.

### ISSUE THREAD

**Issue by CERNEAVSKIO** [GoldenCheetah/GoldenCheetah#3069]
how to fix?
screenshot
http://prntscr.com/n7cyzn

**Comment by MaksVasilev** [comment]
It's like to old bug: #2978

**Comment by amtriathlon** [comment]
The fix for #2978 should work for new users, but it doesn’t include fixing old config files, you need to change them manually, see https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Preferences_Athlete_Training-Zones#zonesdefault-tab

**Comment by CERNEAVSKIO** [comment]
Thanks for answers . Everything worked only with encoding .win 1251  File *.zones .   I know how to fix it. Thank !!!
