### ISSUE TITLE
Wrong values after import of Movescount data

### ISSUE THREAD

**Issue by Bachelotelli** [GoldenCheetah/GoldenCheetah#3070]
Hey, I've got wrong values in my elevation gain after I imported data from Movescount. V3.5. 
The numbers are just incredibly off, like 18000m elevation gain in a 10k run. 

Thanks for the help 
Phil

**Comment by amtriathlon** [comment]
The likely cause is records with Altitude=0, see https://github.com/GoldenCheetah/GoldenCheetah/issues/3067
