### ISSUE TITLE
GC on Mac updating "in its own application bundle"

### ISSUE THREAD

**Issue by bobsica** [GoldenCheetah/GoldenCheetah#3073]
Version 3.5 Development Build March 2019

I'm running this (and the past development builds) on a Mac using 10.14.4 Mojave. This latest version is very slow, requiring minutes to start, and minutes to switch tabs. Memory usage is high (9 Gb). Also, if left open it causes my nightly backup software to take 2-3x longer (hours) to run. The backup log suggests the app is updating "in its own application bundle"

Can I provide any further information to help investigate this behaviour?

**Comment by amtriathlon** [comment]
Have you seen the FAQs?
https://github.com/GoldenCheetah/GoldenCheetah/wiki/Severe-Performance-Issues

**Comment by bobsica** [comment]
No, I searched the issues but missed that FAQ, sorry. The Privacy/Accessibility authorization was my problem. Thanks so much for pointing me in the right direction.
