### ISSUE TITLE
Application crashes on Add Activity (Find Intervals)

### ISSUE THREAD

**Issue by hnaess** [GoldenCheetah/GoldenCheetah#3077]
Find Intervals crashes, tested on both
- Peak Power
- Heart Rate

on three different activities

Crashes (exit application, with black screen) when I click on "Add to Activity" in the Find Intervals Dialogue box (Module)

I tried to delete the newest activity, re-sync, and before saving - find intervals, and add to activities, then it works.

Running on v3.5-DEV1903
[crash- log and dump files.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3077423/crash-.log.and.dump.files.zip)

**Comment by amtriathlon** [comment]
If this happens again with v3.5 RC1 please reopen attaching the offending file and the steps to reproduce the problem, the logs and dump files are not that useful in these case regrettably.
