### ISSUE TITLE
Application crashes on Compare Activties

### ISSUE THREAD

**Issue by hnaess** [GoldenCheetah/GoldenCheetah#3079]
When I try to compare a segment on a activity it crashes

1. Open Golden Cheeath
2. Choose 'Toogle Compare Pane' in menu bar (top right corner)
3. Drag on segments from Segments it crashs (black screen)

See attached log files
[crash- log and dump files compare.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3077912/crash-.log.and.dump.files.compare.zip)

Version:DEV1903

**Comment by loc4me** [comment]
I just tried this with V3.5-RC1 but I dragged two activities over from the left activities panel. I was able to compare the rides without the application crashing.

I did notice an issue when clicking on the column names to sort the list. I would loose the text in some of the columns and It would not come back even if I resorted by some other column.
