### ISSUE TITLE
[Old 447] Create New Athlete as Copy

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#308]
When creatng a new athlete it would be nice to be able to create as a copy of an existing athlete (to have same layouts, colors etc).

Add
Related issues

History
#1 Updated by Mark Liversedge 11 months ago

Target version changed from 3.0 to 3.1

Propose we combine this with the new configuration scheme (i.e. moving to ~subdirectories for config, workouts, caches, ride files). This will be along with moving to a native file format in v3.1.

**Comment by scr142** [comment]
I'm happy to look at this change, as I assume it requires an addtional menu option for cloning an athlete, and then deciding many and which content of the /config files to copy to the new athlete. If we can agree some more detail I can start work on it.

**Comment by amtriathlon** [comment]
I think this should be considered together (or after) the New Athlete is added to Athletes View and re-established (or not) as a manu option.
