### ISSUE TITLE
Problems regarding "gpxpx:PowerInWatts"

### ISSUE THREAD

**Issue by Dieggu** [GoldenCheetah/GoldenCheetah#3084]
I am using GC v3.5-DEV1903, Build id: 3970 and I import the gpx-Files from UrbanBiker (https://github.com/Sublimis/UrbanBiker).
When importing, the tag "pgxpx:PowerInWatts" is not imported.  According to (https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/FileIO/GpxRideFile.cpp) I would expted, the tag to be supported, which would be really great.

Snippet from the gpx-file:
`<trkpt lat="48.8793539400" lon="9.1870567100"><time>2019-04-18T14:12:42.013Z</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:atemp>27.3</gpxtpx:atemp><gpxtpx:hr>125</gpxtpx:hr><gpxtpx:cad>86</gpxtpx:cad></gpxtpx:TrackPointExtension>**<gpxpx:PowerInWatts>92</gpxpx:PowerInWatts>**</extensions></trkpt>
`
Here is the gpx-file as .txt:
[2019-04-18_16-12.gpx.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/3099792/2019-04-18_16-12.gpx.txt)
 and a hardcopy of what is recognized by GC:
![GC](https://user-images.githubusercontent.com/48885090/56453259-22897000-6340-11e9-9257-70e575c5188d.JPG)

Any help would be appreciated.

Kind regards,
Diegu

**Comment by amtriathlon** [comment]
That variant is not accepted by the current parser (see https://github.com/GoldenCheetah/GoldenCheetah/blob/15e70f9e9d299ca651f072580a597b1fb4e8b07f/src/FileIO/GpxParser.cpp#L142), but it is easy to add.

**Comment by amtriathlon** [comment]
Thanks for the test file, the fix will be included in the next build.

**Comment by Dieggu** [comment]
So Cool! Thanks a lot. Looking forward to it.

**Comment by Mark-hub** [comment]
Hi amtriathlon, I have the same issue as Dieggu. I've just installed the GoldenCheetah development version 3.5 (windows 64) and it doesn't recognise the power record ifrom the UrbanBiker .gpx file.
Has this been overlooked or did you mean the next build after the current development build? Cheers

**Comment by amtriathlon** [comment]
Next build after the fix, current dev build is previous.

**Comment by Mark-hub** [comment]
Great, thanks.
