### ISSUE TITLE
Distribution chart (Activities vs Distance) crashes

### ISSUE THREAD

**Issue by rb83421** [GoldenCheetah/GoldenCheetah#3085]
Given GC is started and Tends view is selected
When i create a new distribution chart.
And for plot i select metrics 
And on distribution (y-axis) i select Distance 
Then GC crashes.

Tried with a test user where there is less data it also crashes.

Screenshot  before select of Distance after that action is crashes:
![DistributionChartCrash](https://user-images.githubusercontent.com/49694615/56467639-ce56bc80-6421-11e9-8f64-e2267dc5d2d1.png)

crash reports:
[crash_1038_210419.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3101044/crash_1038_210419.zip)

**Comment by amtriathlon** [comment]
It seems this chart doesn't handle precision>2 and (long time ago) I raised Distance precision to 3 for better display of swim distances, since Distance Swim in m/yd was introduced afterwards that change could be reverted. Or fix the chart...

**Comment by rb83421** [comment]
I can confirm that is the precision
in BasicRideMetrics.cpp

```
    void initialize() {
        setName(tr("Distance"));
        setType(RideMetric::Total);
        setMetricUnits(tr("km"));
        setImperialUnits(tr("miles"));
        setPrecision(3);
        setConversion(MILES_PER_KM);
        setDescription(tr("Total Distance in km or miles"));
    }
```
```
    void initialize() {
        setName(tr("Distance"));
        setType(RideMetric::Total);
        setMetricUnits(tr("km"));
        setImperialUnits(tr("miles"));
        setPrecision(2);
        setConversion(MILES_PER_KM);
        setDescription(tr("Total Distance in km or miles"));
    }
```
This works indeed for the distribution chart. 

I'm trying to understand/learn how to debug/find this. (i'm not a CPP/QT programmer)
I couldn't find this with the crash/stack trace.

Can you elaborate one how did you find this was the cause?
