### ISSUE TITLE
3970 appears to import Strava even when account removed

### ISSUE THREAD

**Issue by RJKflyer** [GoldenCheetah/GoldenCheetah#3088]
Added Strava to permit auto import via Preferences > Athlete > Account, and disabled file import from Preferences > Athlete > Auto Import.

However, soon found this to not be usable as Strava exports gpx so much data (e.g. L/R balance) is lost.

Deleted Account and reverted to file import but GC 3970 still imports from Strava when opened, resulting in duplicate activities.

**Comment by amtriathlon** [comment]
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/2936
