### ISSUE TITLE
Heart rate values are not interpolated (for each second) when data is imported from RR-data

### ISSUE THREAD

**Issue by ninardos** [GoldenCheetah/GoldenCheetah#3095]
When I import heart rate data from HRV reading values (a file with RR values per line in ms) then the heart rate data in Golden Cheetah is positioned at the precise ms.

When RR-values are bigger than one second, in some cases individual seconds get "jumped". 
When plotting this is not necessarily an issue, unless you use the compare pane.

Comparing two activities where one has an entry in a particular second and another one omits this second, the ommited value is assumed to be zero.

I stumbled upon this, when I wanted to compare accuracy of different devices (phone vs hr monitor). In one import every second gets assigned an HR value, in the other one not.

**Comment by ninardos** [comment]
Example files with 10 RR-values that are exactly 1000 ms apart (1001...1010, vs 1901...1910).
In compare mode HR shows as:

![image](https://user-images.githubusercontent.com/28820522/57540856-f9ac3780-734d-11e9-917f-3e74915cd007.png)
which is surprising, as heart rate is not zero at those times.
I am unsure how to deal with this issue, but maybe HR should be set for each second where currently zeros are imputed to be an average of adjacent values, or last value?

Edit pane, data in GC, for the acitivty with RR-values from 1901....1910 (note that the last value is not imported):
![image](https://user-images.githubusercontent.com/28820522/57541016-5dcefb80-734e-11e9-8376-1cbf4ffa1cb9.png)

![image](https://user-images.githubusercontent.com/28820522/57541039-6cb5ae00-734e-11e9-85de-9ff8f04777bb.png)

Edit pane, data in GC, for the acitivty with RR-values from 1001....1010:
![image](https://user-images.githubusercontent.com/28820522/57541120-98389880-734e-11e9-892e-6a0653080118.png)

![image](https://user-images.githubusercontent.com/28820522/57541093-8b1ba980-734e-11e9-8802-411e8e7b2ec3.png)

File 1:
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910

File 2:
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010

**Comment by ericchristoffersen** [comment]
There is a fixup pass today for hr under Edit: "Fixup HR Spikes" that will do a linear interpolation from neighboring values for hr samples with value 0.

**Comment by ericchristoffersen** [comment]
Beware "comparing accuracy" when sample rates are different. When you import a series into a gpx the data is put into buckets with overlapping range. In your case you have a lower sample rate than the gpx buckets so there is no data for some buckets. There is no 'right way' to generally interpolate data and even this 'copy to overlapped bucket' skews the data.

Also: hr fundamentally has a sample window size. If your devices have different convention for how to compute hr then it will be tough to specify a 'best'.

**Comment by ninardos** [comment]
Yes, I agree, it is difficult for HR to specify a best.
With HR, given as RR-values, it seems conceptually difficult to treat HR as a continuous function, so I have no good suggestion. For my comparison I use 5 second moving average windows, but this also is a somewhat arbitrary choice.

I just noted, that the current implementation produces a weird comparison.
I (and probably most other users) can live with this.

**Comment by ericchristoffersen** [comment]
Try running the above fixup pass. It'll at least disappear the zeros so let you more reasonably compare. Just beware that sample rate problems are really subtle.

**Comment by ninardos** [comment]
The fixup pass in this case is not doing anything, the values that are there are not zero.
The described phenomenon occurs, if in one data set there are e. g. values for each second, but in  second data set, there are values for e. g. every second second and then a comparison is done.
The comparison seems to compare on a basis of each second, so if dataset 2 only contains values for 2, 4, 6, ... seconds, values for 1, 3, 5, ... are interpreted as 0. 

As there are no entries at 1, 3, 5 seconds in the data, the fixup does not have anything to correct.

It is not a terrible problem, just something I noted. Maybe in the handling of the compare pane it could be interpreted differently (e. g. do not interpret values as zero that are not in the data, just do not plot them).

**Comment by amtriathlon** [comment]
When I implemented that import the objective was to record the real data as XData to be used by the HRV code, the standard data was just a "placeholder" but to be of any utility it needs interpolation since GC works with fixed sampling intervals.

**Comment by ninardos** [comment]
Thanks Alexandro, for the hint to XData, this is a way to solve it. 

If I calculate HR from RR-data using the formula 60*1000/XDATA("HRV", "R-R", resample) then the compare pane will show a useful comparison.

![image](https://user-images.githubusercontent.com/28820522/57565306-be485200-73bb-11e9-834e-f2bd0604c837.png)

instead of

![image](https://user-images.githubusercontent.com/28820522/57565314-dae48a00-73bb-11e9-9a07-27c6eea1e72d.png)

**Comment by ninardos** [comment]
By the way, is there a way to resample an activities data (so as to change the data that GC is working with, that is, the one shown in the edit pane)?
