### ISSUE TITLE
Aeropod/iBike CSV crashes Aerolab

### ISSUE THREAD

**Issue by BillOsler** [GoldenCheetah/GoldenCheetah#3096]
Golden Cheetah can import the CSV data files generated by Velocomp's Aeropod, mostly without problems, but when attempting to analyze those files in Aerolab a large proportion of those Aeropod CSV files cause Golden Cheetah to crash after clicking the "Estimate CdA and Crr" button.  Using Aerolab without clicking the "Estimate CdA and Crr" button does not appear to cause any problems.
[AeropodProblemFiles.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3170103/AeropodProblemFiles.zip)
I have noted this behavior using both 64 bit and 32 bit Windows versions (3.4) and also the 64 bit pre-release 3.5.
In some cases I can eliminate the problem by correcting the elevation information in the file but not in all cases.

**Comment by amtriathlon** [comment]
I can not recreate this on v3.5 RC1 64bit, on one of the attached files Estimate ends with valid values:

![Aerolab1](https://user-images.githubusercontent.com/1444784/68209157-88260c80-ffb1-11e9-9d82-37139508023e.png)

and on the other one:

![Aerolab2](https://user-images.githubusercontent.com/1444784/68209159-88bea300-ffb1-11e9-96ee-301281a9e18c.png)

it shows a message box stating the estimates found are invalid (Estimates out-of-range).

**Comment by amtriathlon** [comment]
Likely fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/72bc73ceacbe81bfae4717f31f4ee26cf5ff7718#diff-9b5d621b1e27be16618d562ecaafd8a0
