### ISSUE TITLE
[Old 441] Add multisport metrics

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#310]
Add metrics for other sports (via Ale Martinez)

"If there is interest in the multisport road I would add:
- Run Training metrics: Daniels Points would be easy and GOVSS would be interesting as it has a published definition
- Swim Training metrics: SwimScore is quite interesting and it has a published definition
- Enhaced manual entry form with distance/time intervals (useful for swimming and running)"

Add
Related issues

History

#1 Updated by Mark Liversedge 12 months ago
Target version changed from 3.0 to 3.1
 
We can pick this up in 3.1. Ultimately GC is a cycling app and this is not a priority for now

**Comment by amtriathlon** [comment]
I think we can close this one since most of these features are already implemented.
