### ISSUE TITLE
Cadence values get lower on merge workouts

### ISSUE THREAD

**Issue by IlGehring** [GoldenCheetah/GoldenCheetah#3100]
I have merged two workouts and get half cadence.
Today I merged 4 files, cadence in every single workout before merging is correct, after merging cadence values were smaller beginning with the first from ca. 70 to 10 second to fourth ca. 70 -> 35.
I have no smart recording. Workouts are from are .fit files from wahoo app . Immeaditly after import values are correct.

**Comment by IlGehring** [comment]
I have checked , it is not the merge funktion wrong. the files get even lower values after doing something other . in fact , when goldencheetah saves something or so, goldencheetah works wrong on workout like a script has started to reduce the cadence.

**Comment by amtriathlon** [comment]
The only way I can imagine this happening is you have the Data Processor “Fix Running Cadence” enables to run automatically  on save.
Otherwise please attach one fit file and screen captures showing this behavior.
