### ISSUE TITLE
Inconsistent running pace with fastes xx seconds intervals in activity summery view

### ISSUE THREAD

**Issue by weiznich** [GoldenCheetah/GoldenCheetah#3106]
![error](https://user-images.githubusercontent.com/1674512/57889429-5020e680-7824-11e9-9162-a696768e04a7.png)
(I've edited the image a bit to only contain the relevant information)

The running pace shown in the interval name and the actual calculated? pace for this interval in the summary table do not match. 

Enviroment infos:
* Activity was imported from a garmin fit file
* OS: Ubuntu 19.04
* GoldenCheetah from the current appimage (Build id 3970)

Just let me know if there are further information required and I will try to add them.

**Comment by amtriathlon** [comment]
The main issue here is the rounding of speed previous to pace conversion for display in the interval name:
https://github.com/GoldenCheetah/GoldenCheetah/blob/649d3ee014fa08bea57a5b986264a81e8d50083c/src/Gui/AddIntervalDialog.cpp#L961

A secondary issue is that pace is computed from speed series while Average Pace is computed from distance series and they may differ, but the user has the option to reconcile them using Edit > Fix Speed from Distance tool.
