### ISSUE TITLE
build 3970 does not detect activity date and time even though its present in the file on .tcx and .json files

### ISSUE THREAD

**Issue by VincentJGeisler** [GoldenCheetah/GoldenCheetah#3108]
when importing activities from strava, garmin or polar in .tcx or .json format GC does not detect activity date even though they are clearly right at the top of the file. eg
JSON
{
  "exportVersion": "1.0",
  "name": "Other indoor",
  "deviceId": "9DFAF413",
  "startTime": "2016-01-20T15:37:48.000",
  "stopTime": "2016-01-20T15:56:48.000",
TCX
 <?xml version="1.0" encoding="UTF-8"?>
<TrainingCenterDatabase xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2 http://www.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd">
            <Activities>
              <Activity Sport="Biking">
            <Id>2019-02-25T23:13:22Z</Id>
  

clearly the start time and duration can be claculated from the headers but GC asks for date /time when trying to import either of these files.

**Comment by amtriathlon** [comment]
Can you attach sample files (zipped) for testing?
