### ISSUE TITLE
FIT openwater swim activities import is wrong 

### ISSUE THREAD

**Issue by robolaf** [GoldenCheetah/GoldenCheetah#3109]
Hi,
When importing an open-water-swim activity (recorded with my Garmin 920XT) the GC activity gets very strange… It seems only when the watch gets a GPS signal it moves fast for a sec., see below:
 
![image](https://user-images.githubusercontent.com/7139815/58264296-e81b5480-7d7d-11e9-859b-1396158447c1.png)

For the activity time moving is then only a few seconds while the activity lasts for serveral minutes. In Garmin the same activity looks like this(and I would also expect to see this in GC):
 
![image](https://user-images.githubusercontent.com/7139815/58264366-084b1380-7d7e-11e9-908a-c5c64f05d6fe.png)

Attached is the FIT file… 
[95JG5223.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3212901/95JG5223.zip)

Could someone look after this issue or am I the only one who experiences this issue. BTW, this is the same with every openwater swim activity I import.

Thanks for the great software!

**Comment by amtriathlon** [comment]
See the wiki (https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-RUNNING-&-SWIMMING#how-to-import-runs-and-swims-for-best-results) and, please use the forum to get help!
