### ISSUE TITLE
The operation couldn’t be completed. (OSStatus error 99999.)

### ISSUE THREAD

**Issue by MichaelGradek** [GoldenCheetah/GoldenCheetah#3117]
I get the following message when I try to open Golden Cheetah. I've tried both the one you can download from goldencheetah.org as well as the pre-release for March 2019 downloading the .dmg directly from GitHub.

<img width="422" alt="Screenshot 2019-06-03 at 13 45 24" src="https://user-images.githubusercontent.com/1625670/58799567-ee26f600-8605-11e9-826f-cc08327b787a.png">

I'm running on Mac OS 10.14.3

**Comment by amtriathlon** [comment]
This may be an issue on your system, see https://discussions.apple.com/thread/8463852 for example.
You may get more responses on the users forum, we use issue tracker for bugs and features.
