### ISSUE TITLE
Datatable, missing data in trends view

### ISSUE THREAD

**Issue by desie** [GoldenCheetah/GoldenCheetah#3120]
In trends module, when datatable view is activated, sometimes last data is missing, depending on which phase/season is selected. It seems that it depend of the phase/season start date.

**Comment by amtriathlon** [comment]
Beware in datatable view the series are not padded with zeros at the end, by design they are shortened to the shortest one.
For example if you have a chart with PMC/Measures data and Metrics/Formula series the chart goes till the end date but the table only until the last activity in the range.
