### ISSUE TITLE
Pace shown in min/km when units set to Imperial.

### ISSUE THREAD

**Issue by SyntaxError6** [GoldenCheetah/GoldenCheetah#3121]
Pace is shown as min/km when the units is set to imperial in the user preferences. 

App version 3.4.
OS Mac 64bit.

**Comment by amtriathlon** [comment]
Please see the wiki and use the forum to get help.
https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-RUNNING-&-SWIMMING#how-can-i-choose-pace-units-for-running-and-swimming

**Comment by SyntaxError6** [comment]
Wow that setting is buried down in there. Appreciate the tip.

**Comment by amtriathlon** [comment]
I have the intention to move it (see https://github.com/GoldenCheetah/GoldenCheetah/issues/2253), but never found the time/motivation to do so...
