### ISSUE TITLE
Garmin files won't open

### ISSUE THREAD

**Issue by dougkuwahara** [GoldenCheetah/GoldenCheetah#3123]
Last Fall my Garmin files uploaded easily to GC, now I have a Garmin 520+ and files won't load.  Message says no supported files found.    Garmin still uses *fit. files

**Comment by amtriathlon** [comment]
Yes, but FIT file format has evolved, the last versions are supported by v3.5 dev builds but not v3.4

**Comment by dougkuwahara** [comment]
Thanks.  Suspected as much.  Too bad.  Used to love GC. Got to find something else.
