### ISSUE TITLE
FIT: Add Lezyne Super GPS unit

### ISSUE THREAD

**Issue by ju00atgmx** [GoldenCheetah/GoldenCheetah#3128]
Lezyne Super GPS unit is reported as unknown device. Could someone please add 258|4 "Lezyne Super GPS" to FitRideFile.cpp?
Thank you!

**Comment by mtbkeith** [comment]
can you attach a fit file from the Super GPS?

**Comment by ju00atgmx** [comment]
I'm sorry, the issue editor does not accept my zipped fit-file ("Somethng went really wrong..."). What I'm doing wrong?

**Comment by ju00atgmx** [comment]
Found the problem; some javascript was disabled. The zipped fit file: [3752554A.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3352026/3752554A.zip)

**Comment by mtbkeith** [comment]
pull request: https://github.com/GoldenCheetah/GoldenCheetah/pull/3129

**Comment by Joern-R** [comment]
Fixed via 1e1dceef730fdc6de4efa040375444210de37305
