### ISSUE TITLE
Sincronizar Garmin Edge 820

### ISSUE THREAD

**Issue by Guille88** [GoldenCheetah/GoldenCheetah#3130]
Hola,

Estoy buscando la manera de sincronizar mi Garmin Edge 820 para poder entrenar en Rodillo e ir viendo los datos en el ordenador pero no soy capaz.
Como podría hacer?

**Comment by amtriathlon** [comment]
Este sitio es para seguimiento de errores y nuevas facilidades, hay un foro de usuarios para consultas, una wiki y una sección de tutoriales donde puedes encontrar uno que explica como usar el programa con rodillo: http://www.goldencheetah.org/#section-tutorials
