### ISSUE TITLE
Silent install on Windows

### ISSUE THREAD

**Issue by guillaume-ferry** [GoldenCheetah/GoldenCheetah#3131]
Hello,

is there a way to do a silent install on Windows and skip the VisualC++ 2015 redistribuable licence message box when VisualC++ 2015 redistribuable is already installed?

Thanks

**Comment by amtriathlon** [comment]
Please use the forums to get help.

**Comment by guillaume-ferry** [comment]
I'm sorry but I do not think the forum can fix anything. This is a bug in the design of the software, since the silent installation just does not work. The problem is that the installation of the .net framework redisrtibuable is forced without any conditions, interactively, even if the concerned station executes a version of .NET framework identical or more recent. Under these conditions it becomes impossible to deploy the software automatically on a park. How to correct the problem? thank you in advance

**Comment by amtriathlon** [comment]
If you need to ask, the user and developers forum are where you can find answers.

**Comment by Joern-R** [comment]
Just had a look at the installer script/tools and changed them so that the 2 additional components (Redistributables and R) are now unselected by default. From next installer version on this will be default.

**Comment by Joern-R** [comment]
With this change the problem on silent installs should be resolved.

**Comment by guillaume-ferry** [comment]
Thanks a lot !!!!
