### ISSUE TITLE
Swimming results from Garmin 945 not correctly loaded where 935 results are

### ISSUE THREAD

**Issue by kemptm** [GoldenCheetah/GoldenCheetah#3138]
Swims recorded on a Garmin Forerunner 945 are not correctly loading to GC Build ID: 3970.  All lap distances are zero. Swims recorded on a Garmin Forerunner 935 are correctly loaded.  The TCX files seem to be essentially identical. The files are attached.

[Garmin945Swim.tcx.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/3493921/Garmin945Swim.tcx.txt)
[Garmin935Swim.tcx.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/3493922/Garmin935Swim.tcx.txt)

**Comment by amtriathlon** [comment]
The difference between both files is the 945 doesn't have DistanceMeters for any Trackpoint (only for Laps) and the parser depends on DistanceMeters on Trackpoint s.t.

```
<Trackpoint>
            <Time>2019-08-12T14:04:21.000Z</Time>
            <DistanceMeters>182.8800048828125</DistanceMeters>
            <HeartRateBpm>
              <Value>99</Value>
            </HeartRateBpm>
            <Extensions>
              <ns3:TPX>
                <ns3:Speed>0.8399999737739563</ns3:Speed>
              </ns3:TPX>
            </Extensions>
          </Trackpoint>
```

**Comment by amtriathlon** [comment]
BTW, have you tried to import the original FIT files?
It's the recommended course of action for best data quality: https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-RUNNING-&-SWIMMING#how-to-import-runs-and-swims-for-best-results

**Comment by kemptm** [comment]
Thanks!  That works and is the method I'll use going forward.
