### ISSUE TITLE
Connect two fit files from Garmin with autopause

### ISSUE THREAD

**Issue by teamtacho** [GoldenCheetah/GoldenCheetah#3139]
Hi
The result for two combined fit files from Garmin Edge 820 is wrong in terms of:
Meters (Altitude) up: Far too high
BikeStress (TSS): Too high
BikeScore: Too high
Data for the two (rounds) are:
HM: 2027+247=2274
TSS: 280+31=311
BikeScore: 263+29=292
Data for the combined activity:
HM: 33803
TSS: 354
Bike Score: 317
Best Regards Michael
[Pfronten2.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3495973/Pfronten2.zip)
[Pfronten1.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3495974/Pfronten1.zip)

**Comment by amtriathlon** [comment]
Hi Michael, there are 2 issues:
1) Autopause generates gaps in recording which may produce strange results in several GC metrics and tools, the recommendation there is a tool to correct this: https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Activity-Processing#edit-tool-fix-gaps-in-recording
2) by definition TSS and BikeScore are not additive and they have an effect, called RATSS (Recovery Augmented TSS) in Wattage list, which provokes an augment in TSS when pauses are included vs the same activity wihout the pauses.

**Comment by teamtacho** [comment]
Thanks Alejandro
Got it !
But what about Meters in altitude?
Best Regards Michael 

Von meinem iPhone gesendet

**Comment by amtriathlon** [comment]
Have you tried running Fix Gaps with tolerance=1 and stop=1 before merging? It gives me Elevation Gain = 2164 for the combined file using current master.

**Comment by teamtacho** [comment]
Hi Alejandro 
Ok. I imported the two files, made the correction, saved both and merged them.
It fits now. 
Thanks a lot.
Best Regards Michael 

Von meinem iPhone gesendet
