### ISSUE TITLE
NamedSearch.cpp not reading namedsearches.xml in UTF-8 encoding

### ISSUE THREAD

**Issue by sanfordhk** [GoldenCheetah/GoldenCheetah#3143]
This issue is similar to #2978. Basically if non-ASCII characters are provided as translations under the context NamedSearches to provide the default named search strings, the text will display well on creation of a new Athlete profile, and the file namedsearches.xml is generated correctly on exit. On second opening of the profile, the texts are read as question marks.
The problem comes from the use of unprotect function in NamedSearch.cpp. Should be changed to UTF-8 safe escape functions.

**Comment by amtriathlon** [comment]
You are right, in particular this step in unprotect seems to be the culprit:
https://github.com/GoldenCheetah/GoldenCheetah/blob/e68afa6aeabab193e339d57e4398ff1699fd4115/src/Core/NamedSearch.cpp#L54
It doesn't seem to make any sense, I don't understand whats the rationale for it was.
Removing it and using directly string in the next line fixes the issue for me.

**Comment by sanfordhk** [comment]
There is already an UTF-8 safe xmlprotect and unprotect function under Utils.cpp.
https://github.com/GoldenCheetah/GoldenCheetah/blob/e68afa6aeabab193e339d57e4398ff1699fd4115/src/Core/UserData.cpp#L278
https://github.com/GoldenCheetah/GoldenCheetah/blob/e68afa6aeabab193e339d57e4398ff1699fd4115/src/Core/UserData.cpp#L320

**Comment by amtriathlon** [comment]
Yes, I thought about using it but, since it uses different escaping sequences it will introduce compatibility problems with previous namedsearches.xml files.
