### ISSUE TITLE
Banister Chart and Banister Helper

### ISSUE THREAD

**Issue by teamtacho** [GoldenCheetah/GoldenCheetah#3156]
Hi
There is a Bansiter Chart in the download area available and also a good tutorial on the GC website.
Unfortunatelly that chart is empty and there is no Banister Helper available as explained in the video.
Was went wrong or what do I have to do the get this chart up and running?
Best Regards
Michael

**Comment by amtriathlon** [comment]
Please use the forum for questions and discussions.
