### ISSUE TITLE
Power Index

### ISSUE THREAD

**Issue by teamtacho** [GoldenCheetah/GoldenCheetah#3157]
Hi
On Marks Blog there is a explanation of the Power Index. The formular and the result in the tabel doesn't match. 
Mark said:
_So plugging the numbers into the formula, the predicted power for 4, 10 and 20 minute intervals, for our average athlete (CP=261w, W'=15.5kj, Pmax=1100w) are shown below, along with the average powers from above, the calculated power index percentage and rank:_
In the formular  P(t)=W'/t - **W'/CP-Pmax** + CP  I do not understand the 2nd part (W'/CP-Pmax) which don't contribute a Power value but a Time value.
Please can you provide a short explanation.
Best Regards
Michael

**Comment by amtriathlon** [comment]
Please use the forum for questions and discussions.
