### ISSUE TITLE
Chart Presets missing curves

### ISSUE THREAD

**Issue by db369** [GoldenCheetah/GoldenCheetah#3158]
I'm using the 3.5 dev build on Linux Mint 19.2 for Strava/Withings syncing. 

After installing I noticed that many of the default charts were blank. I assumed it was due to lack of data, but after using it for some time and watching some videos on the use of them, I realize that the presets are missing default curves. Selecting a preset (under "Chart Settings") and clicking "Apply" also does nothing. I have to manually add curves. 

I've been searching everywhere, but this doesn't appear to be a common issue. I'd love to hear any ideas on how to correct this. Thanks.

**Comment by amtriathlon** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-MOST-COMMON-QUESTIONS-OF-ALL#Why-are-my-charts-blank-or-data-is-missing

**Comment by db369** [comment]
Ugh, thank you! Sorry I missed that.
