### ISSUE TITLE
Error while Strava authorization

### ISSUE THREAD

**Issue by floriansemm** [GoldenCheetah/GoldenCheetah#3159]
When I have logged in into Strava and clicked "Authorize" the following error pops up:

```Error retrieving access token, Error downloading https://www.strava.com/oauth/token? - server replied: Bad Request (302)```

OS: MacOs
Build id: 3957
Version: 3.4

**Comment by amtriathlon** [comment]
Some online services have updated their protocols since v3.4 was released, to use them you can try the last development build for v3.5 or wait for the release

**Comment by floriansemm** [comment]
In v3.5 the problem is solved. Thanks for your help.
