### ISSUE TITLE
Altitude and Speed data null on Fenix 5/6

### ISSUE THREAD

**Issue by Gialandra** [GoldenCheetah/GoldenCheetah#3161]
I want to notice that since I updated the firmware of my Garmin Fenix 5 Plus to version 8.40 GoldenCheetah no longer reads altitude data. Maybe has Garmin changed the format of FIT files since the new update?

**Comment by amtriathlon** [comment]
Can you attach a sample zipped fit file?

**Comment by Gialandra** [comment]
Here it is.

Il giorno mar 10 set 2019 alle ore 09:52 Alejandro Martinez <
notifications@github.com> ha scritto:

**Comment by amtriathlon** [comment]
Email attachments don’t work on GitHub, you need to use their UI.

**Comment by Gialandra** [comment]
I try again
[2019-09-07-11-22-19.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3597518/2019-09-07-11-22-19.zip)

**Comment by amtriathlon** [comment]
Are you using a footpod s.t. Stryd?

Altitude data is reported using an enhanced field in this file:
**Field=78, name=enhanced_altitude, scale=5, offset=500, units=m**
Speed also is reported as:
**Field=73, name=enhanced_speed, scale=1000, offset=0, units=m/s**
Both are imported and show in Editor EXTRA tab, but we should use them to replace standard ones.

**Comment by Gialandra** [comment]
No, I don't use footpod.

In the meantime I tried also with SportTracks and even here I had the same behavior: after updating the firmware the software no longer reads the altidutine field

**Comment by amtriathlon** [comment]
I tried changing the code to import the enhanced altitude and speed fields as standard ones, it looks reasonable to me, but please check the results in the attached file:
[2019-09-07-11-22-19.json.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3636770/2019-09-07-11-22-19.json.zip)

**Comment by Gialandra** [comment]
I am unable to judge completely, I can say that the altitude gain provided by Garmin Connect is 75 meters versus 60 meters provided by GC. If you want to try a file with more height difference, I send you the one of today that at least exceeds 1000 meters.
[2019-09-20-17-46-06.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3637569/2019-09-20-17-46-06.zip)
Thank you
Marco

**Comment by amtriathlon** [comment]
Imported using the last modification this one has  Elevation Gain (meters): 1143 using Elevation Hysteresis (meters): 3

**Comment by Gialandra** [comment]
Sorry, I forgot to says Connect values: D+ 1.118 m / D- 1.124 m

I don't know if the differences are reasonable

**Comment by amtriathlon** [comment]
I think they are, Elevation Gain depends on the Hysteresis parameter used to compute it as explained in FAQs, for example raising it from 3m to 5m reduces Elevation Gain to 1126m in this case.

**Comment by Gialandra** [comment]
Thank you for your support. How can enjoy from your work?

Best regards
Marco
