### ISSUE TITLE
Error - local type 1 without previous definition

### ISSUE THREAD

**Issue by spikecol** [GoldenCheetah/GoldenCheetah#3162]
Hi, first time posting on the web so if it is in the wrong place... sorry.

I am encountering an error when trying to import my .fit files into GC 3.3 on Mac OSX 64 bit. The error is: Error - local type 1 without previous definition. The files are from a Wahoo Element Bolt. They all work on my Linux machine.

Cheers

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md

FIT file format has evolved and GC v3.3 can't understand the new format, you need to upgrade to the last build of v3.5 to import them.
