### ISSUE TITLE
GC doesn't recognise ANT+ devices on macOS

### ISSUE THREAD

**Issue by hockeyratte92** [GoldenCheetah/GoldenCheetah#3164]
I have a Macbook Pro from 2019 running the latest macOS version. I use the latest Garmin ANT+ stick to connect heart rate, cadence sensor and an Elite Direto smart trainer to the computer. The ANT Stick is connected to the computer using a USB-A to USB-C adapter from Apple. 

In Trainerroad, all devices are recognised without problems. However, GC (dev_v3.5 1903) cannot find the devices. I already tried the latest stable version without any difference. 

Any idea how I could get GC connected properly?

**Comment by amtriathlon** [comment]
It is much more likely you get answers on users forum, which is intended for that purpose.

**Comment by amtriathlon** [comment]
We have independent confirmations https://github.com/GoldenCheetah/GoldenCheetah/pull/2919 fixes this issue.
