### ISSUE TITLE
Crash on startup - DEV1903

### ISSUE THREAD

**Issue by Sasse82** [GoldenCheetah/GoldenCheetah#3165]
Hi there.

I'm having a problem that my GC is crashing right on start (after selecting my account).
The first time it crashed was after I made some changes in the options and clicked on "save".
After that, it crashes on startup. I already tried a reboot and a reinstall (no uninstall before), but it didn't help.

Additional information: The program started to run slowly since a few weeks now. Every action I did (changing workouts, going to trends, etc..) took a lot more time than before, but it never crashed until today.

You have any Idea what it could be and how I can fix it without loosing my database?

Thanks!

Edit: The problem seems not to be the program itself but my database. Creating a new user works fine, but opening my old one results in a crash. Can I somehow fix/repair my database?

**Comment by Sasse82** [comment]
Thanks, that was exactly the same issue.
But I don't even know how these changes came in, I never changed the zone names manually.

Unfortunately for me, I realized it too late and I had to go back to my last backup of April regarding the power zones, but that's still better than loosing the whole database.

**Comment by amtriathlon** [comment]
That issue is fixed, but we need to generate a new build to make it available. Sorry.
