### ISSUE TITLE
fortius issues ubuntu 1904

### ISSUE THREAD

**Issue by 7h3ju57** [GoldenCheetah/GoldenCheetah#3169]
I'm trying to using GC with my fortius 1932 but it doesn't seem to work well at all.

the power brake periodically stops, power and cadence arent displayed.
ive tried using with and without firmware file.

**Comment by amtriathlon** [comment]
Which GC version are you using?

**Comment by 7h3ju57** [comment]
I'm using the latest pre release that is available (GoldenCheetah_v3.5-DEV1903_64bit_Linux.AppImage)

I believe it was successfully connecting. I am running as root, since running as a user it would error out stating it couldn't connect. Once connected I can start the training session which makes the green light on the hardware interface start blinking, which I believe means its interacting with the power brake. All stats remain at zero, but every ~10 seconds, the power brake seems to go into the hardest mode, which I found to be the issue when cadence wasn't measured with TTS4.

Is their any debug flags I can set or debugging I can try and narrow down where the issue is?

Thanks for the quick reply :)

**Comment by amtriathlon** [comment]
The code has not changed but I’m not sure the AppImage has been tested in this configuration, you could try v3.4 just to be sure the issue is not build related.
The permissions config for USB ports is explained in the wiki, although there is much more info in the user’s group, you may even get more feedback there.

**Comment by 7h3ju57** [comment]
So I install Ubuntu 1604 to test GC 3.4 and still getting the same issue, is there anyway to read raw data being received?

**Comment by 7h3ju57** [comment]
I got it to work using windows 10!! It still wasn't working using Ubuntu but for now I'm just going to continue using this with windows. Thanks for your help!
