### ISSUE TITLE
[Old 383] Record and track measures

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#317]
The code for a measures database is already in the 3.0 codebase but is not well thought through. This needs to be resolved. Additionally, the existing withings support should be part of this.

**Comment by amtriathlon** [comment]
In v3.5 we have BodyMeasures and HrvMeasures with CSV import and local maintenance, access from LTM/R/Python charts and Data Filters. Withings and Today Plan download is supported for BodyMeasures.
I'm closing this but a more general approach and calendar integration may be desirable for future versions.
