### ISSUE TITLE
Unrealistic spikes in intervals

### ISSUE THREAD

**Issue by v1sionmaster** [GoldenCheetah/GoldenCheetah#3170]
Issue tracker is **only** for Bugs and Features, before to open a new issue please read the Contributing document (link at the right) and use the forums if you need help.
![Interval Spikes](https://user-images.githubusercontent.com/38918646/65720128-3a0f1680-e09f-11e9-9c8b-1d6600c989b1.jpg)
I uploaded this file through Strava and it came from an activity in Road Grand Tours. The interval summary shows a 10 second interval of 505 watts, but the Activity Edit panel shows that power was 128 - 146 watts during that period.
There are other spikes too at 1 sec and 5 sec which can't be seen in the Edit panel. I can't add the .gpx here but have it available.
Is it possible to investigate this please? 
Thanks!

**Comment by amtriathlon** [comment]
The wiggled red line indicates some anomaly, visually it seems to be duplicate samples but you can use the anomalies button to see details. The users forum is the place for this kind of questions.
