### ISSUE TITLE
Session RPE bug

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#3171]
Hi,

I just noticed that there is a bug with the calculation of session RPE. It only appears to be calculated for activities after 01 January 2013. This is observed for activities with RPE input and input for duration and time moving, both with and without gps data.

Running the latest development build on linux as an appimage.

Kind regards,

Nigel

**Comment by amtriathlon** [comment]
This is highly unlike knowing the code since date has no role in Session RPE.
Anyway I tested using my activities from 2011 and Session RPE is computed as expected in Ubuntu.
Are you looking at Session RPE as a Summary Metric or only thru a PMC?

**Comment by nigelvdv** [comment]
Hi,

See screenshot below. I added the same activity twice and changed the date manually on import. The activity just contains distance, duration and time moving.

The one imported as a 2012 activity doesn't show session RPE, the one imported as a 2013 activity does... No idea what other differences there could be.

Kind regards,

Nigel

![Screenshot Session RPE](https://user-images.githubusercontent.com/14836910/65855094-99e71500-e35e-11e9-8d9f-85432d2eb9cb.png)

**Comment by amtriathlon** [comment]
If you add Session RPE as summary metric how looks the Summary for this activity?
Trying to understand if the problem is the metric or the calendar text.

**Comment by nigelvdv** [comment]
Makes no difference. 0 for dates before 01 January 2013.

When 3.5 gets released I will start a new configuration from scratch. Chances are big that this issue will resolve itself that way. It can't be that I am the first one noticing this behaviour, so most likely something to do with my configuration...

**Comment by amtriathlon** [comment]
I would try a full cache rebuild: close GC, remove Athlete’s cache folder contents, restart GC and wait to completion

**Comment by nigelvdv** [comment]
That was the first thing I did. It made no difference though...

**Comment by amtriathlon** [comment]
Can you recreate the issue with a minimum setup?
I mean, just create a new Athlete and import these 2 activities.

**Comment by nigelvdv** [comment]
It seems to be ok when I create a new athlete!
I did already try it on 2 different athlete profiles before, but both of them are "old" ones.

I guess I'll have to recreate my main athlete's profile and copy-paste all activities.

Kind regards,

Nigel

**Comment by amtriathlon** [comment]
If you copy the .json from activities folder all your metadata, intervals, etc. will be preserved.
It would be interesting to transfer config files one by one to one to try to understand what conditions is provoking this weird behavior since the Session RPE metrics is too simple to be wrong: https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/Metrics/TRIMPPoints.cpp#L345

**Comment by nigelvdv** [comment]
I deleted all folders (visible+hidden) related to GoldenCheetah and started from scratch. I copied all my activities and all relevant config files to a newly created athlete. 

Session RPE is now calculated for all activities! 
The only thing I still need to import are my custom user metrics, but I need to clean those out before I do that. GoldenCheetah was getting too slow due to some of them. 

Kind regards,

Nigel

**Comment by nigelvdv** [comment]
I think I found a possible cause of this bug. Session RPE doesn't get calculated if you didn't specifiy your heartrate zones for that date. 
I only started using a HR monitor in 2013, so my zones were only registered from 1 January 2013. I changed the date and everything is fine now!

**Comment by amtriathlon** [comment]
Bingo!
This is an old copy&paste error: https://github.com/GoldenCheetah/GoldenCheetah/blob/322a2c52658bf35beabdb3a83279474956e100d9/src/Metrics/TRIMPPoints.cpp#L340

I will fix it.
