### ISSUE TITLE
'Download Chart' leads to 'CloudDB' error. v3.5 Dev build.

### ISSUE THREAD

**Issue by slowtwitch** [GoldenCheetah/GoldenCheetah#3172]
I'm attempting to download a new chart format (Banister model), the menu worked at first but didn't download. Now attempts to visit the store are returned with error message of 'Technical error with CloudDB'.

**Comment by amtriathlon** [comment]
There may be temporary errors with CloudDB, but I tested right now and it is working, downloaded the Banister chart without issues. Local connectivity may also be an issue, see the users forum pinned thread: https://groups.google.com/forum/#!topic/golden-cheetah-users/TIXYuun6ntY and, please, use it to get help.
