### ISSUE TITLE
Issue with CUSTOM field

### ISSUE THREAD

**Issue by oberti** [GoldenCheetah/GoldenCheetah#3175]
I have problems with 7 "custom" fields created by me.
To enter values in this field, I usually use the TAB key to move from one field to the next.
It happens, however, that if I enter the data in the 1st field, press TAB, insert the values in the 2nd, TAB and so on, all the values I insert have a final zero (sometimes even initial).
When I notice the GC error and return for example to the 2nd field, all the values return to 0.
To resolve I must insert in 1st value, press TAB and wait for the cursor to start flashing on the 2nd field to be able to enter the value.
The first is a DOUBLE field, the other INTEGERS.

VERSION 3.5 DEVELOPMENT BUILD MARCH 2019
![Cattura](https://user-images.githubusercontent.com/34515429/66102682-74067e00-e5b3-11e9-8e1d-06ccedd22cfe.PNG)

**Comment by amtriathlon** [comment]
I cannot reproduce the behavior on Linux, even on old hardware I cannot type fast enough. Which is your computer configuration, hardware and operating system?

**Comment by oberti** [comment]
> I cannot reproduce the behavior on Linux, even on old hardware I cannot type fast enough. Which is your computer configuration, hardware and operating system?

My pc :
Dell precision t5810
16gb ram
windows 10 1803 64bit
Intel xeon E5 3.5Ghz
Nvidia Quadro M4000

But I had the same issue with Windows 7 x64 in my previous pc

Thanks

**Comment by amtriathlon** [comment]
I cannot recreate this on Windows 10 either.
Can you attach your config/metadata.xml file?

**Comment by oberti** [comment]
> I cannot recreate this on Windows 10 either.
> Can you attach your config/metadata.xml file?


[metadata.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/3690607/metadata.zip)
Thanks

**Comment by amtriathlon** [comment]
I tried using that metadata.xml on an athlete with near 6000 activities in my Dell notebook but I cannot reproduce the behavior you describe: using tab to change from one field to the next is instantaneous and typing immediately doesn't produce bogus data, changing to other field using the cursor never makes other fields to go to zero.

**Comment by oberti** [comment]
Thanks for the tests
