### ISSUE TITLE
Strava Sync Issue 3.5dev Build 1903

### ISSUE THREAD

**Issue by scttmllmn** [GoldenCheetah/GoldenCheetah#3176]
Hello,

I'm having the same issue as the fellow below. When I try to authorize Strava I get the error "Error retrieving access token, Socket operation timed out (4)."

[https://github.com/GoldenCheetah/GoldenCheetah/issues/3011](url)

I've installed and uninstalled a few times, which seemed to work the the last person. Unfortunately that didn't fix my issue. I'm not sure if this is related or not, but I saw the same error during installation about C++ as they did, and I also tried to set up an API on Strava before I realized that was not for default builds. I didn't alter any of the GC files, but I can't figure out how to get rid of the API on Strava.

Thanks!

Edit: Found it, and was able to get everything to work with those instructions and restarting my computer. Thanks!
 
[https://github.com/GoldenCheetah/GoldenCheetah/wiki/Windows-10-Connectivity-Issues](url)

**Comment by amtriathlon** [comment]
See the users forum, there is a pinned thread.
