### ISSUE TITLE
Withings "call to the webservice failed"

### ISSUE THREAD

**Issue by loc4me** [GoldenCheetah/GoldenCheetah#3178]
Using MacOS and v3.5 Dev build 1903. I can enter my Withings account and select the user but the OAuth window then reports "call to the webservice failed"

**Comment by amtriathlon** [comment]
I can recreate on Ubuntu Linux using current master, so I think it is not platform dependent.
Just for clarity sake: to fetch Withings data using a previous authorization is working, this error happens only when you try to authorize in the callback step.

**Comment by amtriathlon** [comment]
Today authorization seems to be working normally, can you try again?

**Comment by loc4me** [comment]
I updated to V3.5-RC1 and I was able to get an authorization code for Withings. It looks like it imported the data correctly for the date range I gave it.
