### ISSUE TITLE
Progress of average power in an interval

### ISSUE THREAD

**Issue by greglemond** [GoldenCheetah/GoldenCheetah#3181]
Hi all, I want to add a new trend line in the training chart: the progress of average power in an interval. Obviously, this needs to be programmed.
The benefit would be to recognize easily when an interval is started with increased power.
Many thanks in advance.

**Comment by amtriathlon** [comment]
The standard Activity chart is already very complex and v3.5 allows the users to build custom charts using interval information, including to be reactive to the interval(s) selected in the left side bar:
in R: https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Working-with-R#gcactivityintervalstype-activity0
in Python: https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Working-with-Python#gcactivityintervalstype-activitynone
I would suggest to give a look to the charts uploaded to CloudDB to see if there is already something similar to what you are looking for or to use the users forum to get help about how to build one.
