### ISSUE TITLE
Apperance settings

### ISSUE THREAD

**Issue by nenadjev** [GoldenCheetah/GoldenCheetah#3182]
There is big difference in font size in application. Can you fix it somehow?
![Capture](https://user-images.githubusercontent.com/11903273/66703062-ba27b400-ed0e-11e9-8627-86738a1058ee.PNG)

**Comment by msporting** [comment]
cant see the Problem, help you can find in the WIKI

**Comment by nenadjev** [comment]
> cant see the Problem, help you can find in the WIKI

In the WIKI is Apperance options for 3.2v
https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Preferences_Appearance

Now there in 3.5v1903 is no possibility to change appearance separate.

![Capture1](https://user-images.githubusercontent.com/11903273/66707051-5071cf00-ed3b-11e9-9bfc-88e8ba79c825.PNG)

**Comment by amtriathlon** [comment]
In the FAQs there is some useful info if you are using HiDPI https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-MOST-COMMON-QUESTIONS-OF-ALL#how-do-i-fix-tiny-text-on-high-dpi-displays

**Comment by nenadjev** [comment]
OK. Thank you. I tried it, but I will keep as was. I don't like visual look after scaling.

**Comment by amtriathlon** [comment]
There is a replacement fro summaries in course, see https://github.com/GoldenCheetah/GoldenCheetah/issues/1305
