### ISSUE TITLE
Feature Request to support JSON file from TechnoGym

### ISSUE THREAD

**Issue by mg1011** [GoldenCheetah/GoldenCheetah#3185]
I have been playing with the JSON file from TechnoGym Equipment and MyWellness Cloud(where the data lives and have been unable to get it working properly.  I am attaching the sample export from the website.  I have some bogus data in there for review.  Just curious if it is possible to extract anything from this.

This was an indoor treadmill run, with power, cadence, and some other data.  The issue I see is that its not sampled at a certain rate.. ie every so many seconds.  Its just a start time and finish time..
[export.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/3736541/export.txt)

I can potentially gather more data if this is something that can be worked with.

**Comment by amtriathlon** [comment]
It doesn't seems to include sample data, just a summaries for separate activities.
There is already a request for bulk import of manual activities like this: https://github.com/GoldenCheetah/GoldenCheetah/issues/725
