### ISSUE TITLE
Can not connect to dropbox.

### ISSUE THREAD

**Issue by mrflyf** [GoldenCheetah/GoldenCheetah#3186]
I have an issue when I am trying to authorise to Dropbox. When clicking on the "Authorise" button (under "Options" / "Passwords) it looks like loading but nothing happens. It is no problem to close the window again, so I doesn't freeze.

![Dropbox](https://user-images.githubusercontent.com/55757422/67040539-fcdcf800-f123-11e9-92a9-ef320c2a4f94.JPG)

**Comment by amtriathlon** [comment]
Please use the forum to get help, there is a pinned thread at the top about connection issues.
