### ISSUE TITLE
Summary page font doesn't scale

### ISSUE THREAD

**Issue by dramaticbulgarian** [GoldenCheetah/GoldenCheetah#3190]
In the new 3.5-rc1 version on windows I'm experiencing an issue where the font in the Summary/Time and Distance report pages does not resize with the rest of the UI, as can be seen [here](https://i.imgur.com/s91TGq6.png). This happens regardless of which font and font scale is chosen for the UI.

**Comment by amtriathlon** [comment]
There is a thread at the forum to discuss v3.5 RC1 issues, also see https://github.com/GoldenCheetah/GoldenCheetah/issues/3182
