### ISSUE TITLE
Route segment identification not working

### ISSUE THREAD

**Issue by GuyMelville** [GoldenCheetah/GoldenCheetah#3192]
I am using the latest beta build for windows. I  note that GIS based route segments are not being identified.

Looking at the code on GitHub, I see that the precision is set at 1 m. This means that a cyclist has to cycle within 1 m of their original track in order for a lap to be identified by GC.

May I suggest a precision that is more practical for cyclists such as considering the width of a path or road lane (e.g. 3 m to 5 m).

Are route segments only based on passing the start point, or can the program identify laps following a lead -in?

**Comment by liversedge** [comment]
I'm not sure your description is correct. but will leave open. for now.

**Comment by amtriathlon** [comment]
It would be useful to have more information: one or more activity files where the route should be identified but is not, and config/routes.xml file.

**Comment by Mountaingoat1** [comment]
I'll report another issue with laps (segments). I hit the lap button on my Garmin to create a lap that will later become a segment. When I review the lap on the map in Golden Cheetah, it doesn't match the actual section on the road. To be more clear: The marked stretch of road on the map is not where it should be. It can differ with 500 metres or more. In Garmin Connect the maps shows the correct stretch of the road. The distance and time is the same.

See the attached pictures.

![Goldencheetah](https://user-images.githubusercontent.com/58813913/78559922-7fae5800-7815-11ea-9a5d-284bb71ea03f.jpg)
![Garminconnect](https://user-images.githubusercontent.com/58813913/78559939-84730c00-7815-11ea-862a-39c18eeab171.jpg)

**Comment by amtriathlon** [comment]
> I am using the latest beta build for windows. I note that GIS based route segments are not being identified.
> 
> Looking at the code on GitHub, I see that the precision is set at 1 m. This means that a cyclist has to cycle within 1 m of their original track in order for a lap to be identified by GC.
> 
> May I suggest a precision that is more practical for cyclists such as considering the width of a path or road lane (e.g. 3 m to 5 m).

Minimum precision to start the search is 100m, 1m is the maximum precision, intended to stop the search once a point close enough if found.

> Are route segments only based on passing the start point, or can the program identify laps following a lead -in?

The initial point for the segment is looked over all the ride, it doesn't need to be the first point.
