### ISSUE TITLE
Units of Work on Charts

### ISSUE THREAD

**Issue by GuyMelville** [GoldenCheetah/GoldenCheetah#3194]
This one could be because I am an engineer.

The units of work on a range charts don't match.

Activity Ride Chart Scale is in kJ, float-over is in J
![image](https://user-images.githubusercontent.com/56834737/67225318-edfb8b80-f42a-11e9-8c35-fb191f56b7ad.png)

Activity Stress Chart W' Bal in kJ on axis, float-over is in J, but stated unings are kJ
![image](https://user-images.githubusercontent.com/56834737/67225636-7f6afd80-f42b-11e9-91e1-56a0589a5a33.png)

Activity CP Chart viewed as Work v Time: Axis units given as kJ, float over indicates units unknown

![image](https://user-images.githubusercontent.com/56834737/67225986-15068d00-f42c-11e9-90e9-fdb9168a4fbe.png)

Trends CP Chart as for Activities CP chart

Trends PMC Chart: Ist the green chart really TSS. Is it not rate of change of TSS or some other difference measure?

![image](https://user-images.githubusercontent.com/56834737/67226379-ac6be000-f42c-11e9-945d-b92efe787b10.png)

**Comment by amtriathlon** [comment]
For the last chart the green curve is RR, the label can be fixed by the user editing the chart.

**Comment by GuyMelville** [comment]
Hi Alejandro,

How are you? Many thanks for your response.

I'll certainly look into that.

I look forward to seeing a hard change in a future build  😁

Best regards,

Guy a
