### ISSUE TITLE
Power Zone shading on Trends CP chart

### ISSUE THREAD

**Issue by GuyMelville** [GoldenCheetah/GoldenCheetah#3198]
Hi,
Build: v3.5 RC1

The power zone shading on the Trends CP chart do not appear to be reforming correctly. The zones do not have the limits as set in the athlete data.

Example Athlete power xone limits are:
![image](https://user-images.githubusercontent.com/56834737/67403572-09d96b80-f5aa-11e9-8513-cdd8b7fe9937.png)

Giving actual zones of:
![image](https://user-images.githubusercontent.com/56834737/67403806-6046aa00-f5aa-11e9-92ce-5e6fb27ec2b2.png)

But the shading is:
![image](https://user-images.githubusercontent.com/56834737/67406133-96d1f400-f5ad-11e9-8207-c424c728da78.png)

Based on the Bests curve, the lower limits are:
Z6 158
Z5 139
Z4 119
Z3  100

Are the limits being manipulated for the Trends curve?

**Comment by amtriathlon** [comment]
Yes, CPs for the from date and to date are averaged and new zones are computed from this.

**Comment by GuyMelville** [comment]
Hi Alejandro,

Thanks for your replay.

May I ask how the averaging is done? All the activities over the period of
the trend had the same power zone data and therefore the trend zones should
be those of the individual activity within that trend period.

What do you think?

Best regards,

Guy

**Comment by amtriathlon** [comment]
Re-read my response above and, please, use the forum to get answers.
