### ISSUE TITLE
Strava OAuth Updates - Bad Request - invalid Scope and Refresh Token

### ISSUE THREAD

**Issue by lee-staples** [GoldenCheetah/GoldenCheetah#3199]
When trying to authorise an Athlete using OAuth get the following response:

{"message":"Bad Request","errors":[{"resource":"Authorize","field":"scope","code":"invalid"}]}

I have found that this is due to Strava changing, the API and the scope no longer accepts view_private or write. Suggest to replace this with activity:read_all,activity:write

http://developers.strava.com/docs/authentication/

--- GoldenCheetah-3.5-RC1/src/Cloud/OAuthDialog.cpp 2019-10-14 09:53:51.000000000 +0100
+++ GoldenCheetah-3.5-RC1/src/Cloud/OAuthDialog.cpp.new 2019-10-24 17:10:34.041901033 +0100
@@ -104,7 +104,7 @@

     urlstr = QString("https://www.strava.com/oauth/authorize?");
     urlstr.append("client_id=").append(GC_STRAVA_CLIENT_ID).append("&");
\-   urlstr.append("scope=view_private,write&");
\+   urlstr.append("scope=activity:read_all,activity:write&");
   urlstr.append("redirect_uri=http://www.goldencheetah.org/&");
   urlstr.append("response_type=code&");
   urlstr.append("approval_prompt=force"); help.

**Comment by amtriathlon** [comment]
I’ve tried yesterday to re-authorize my Strava account using v3.5 RC1 and it was successful, I left all permissions checked on Strava dialog.

**Comment by lee-staples** [comment]
@amtriathlon,

According to the changelog: https://developers.strava.com/docs/oauth-updates/ this will not impact when used previously during the migration period which ended on the 15th of October as would automatically migrate.

Rather than re-authorize can you try removing the connection and recreating.

May have to remove the strava_token from ~/.goldencheetah/<athletee>/config/athlete-private.ini

**Comment by amtriathlon** [comment]
After removing the Strava account in GC and manually deleting the strava_token from athlete-private.ini authorization still works for me.

**Comment by lee-staples** [comment]
😕 - Might just be my Strava account.
As I get the error if put the URL straight into the browser - have put my client_id into the string.

https://www.strava.com/oauth/authorize?client_id=13056&scope=view_private,write&redirect_uri=http://www.goldencheetah.org/&response_type=code&approval_prompt=force

https://www.strava.com/oauth/authorize?client_id=13056&scope=read_all,activity:write&redirect_uri=http://www.goldencheetah.org/&response_type=code&approval_prompt=force

**Comment by Schrekkorr** [comment]
I get the same error. No idea how to work around.

**Comment by amtriathlon** [comment]
Thanks @lee-staples for your contribution, I will commit this update but using just the minimum scope we need to sync, which is activity:read_all,activity:write.

**Comment by amtriathlon** [comment]
I reopen this issue since we need to handle the refresh token, otherwise once the new short lived access token becomes invalid (around 6hs according to docs), the user needs to authorize again.
