### ISSUE TITLE
Cannot search/filter Metrics in Trends > Add Chart > Metric Trends (Windows)

### ISSUE THREAD

**Issue by Mrnofish** [GoldenCheetah/GoldenCheetah#3202]
How to reproduce:

1. Select Trends
2. From the Hamburger Menu, Add Chart > Metric Trends
3. Within the Chart Setup dialog, select the Curves tab, press "+"
4. In the Curve Settings dialog, type into the search/filter text box, then press Enter

Observed behavior: the Color selector dialog opens up.

In the attached screenshot, notice how the Color Selector is always highlighted. TAB/Shift-TAB do not move the focus away from Color.

![Golden Cheetah Chart Setup Bug](https://user-images.githubusercontent.com/28036193/67642603-a20a8400-f90d-11e9-8b92-c47653036f9b.PNG)

**Comment by amtriathlon** [comment]
The highlight of Color indicates it is the default button, the one to be activated if you press enter. 
Tab/Alt-Tab moves the focus around controls in my tests (Windows and Linux) but the search lens and down arrow to select filter doesn't get the focus so they have to be activated using a mouse or trackpad.
I think this is just one of the limitations you will find if you try to use GC without a mouse or trackpad.

**Comment by Mrnofish** [comment]
> I think this is just one of the limitations you will find if you try to use GC without a mouse or trackpad.

Unfortunately, I can see no "Go!" button, or any way to start the search/filter operation using the mouse, so what should I be doing exactly?

The text field has already been activated (using the mouse) as you can see from the thin blue outline around it, as well as the text cursor after the word I typed in there, i.e. "heart".

I would say good UI design would still use Enter to start the search, but a Go or equivalent button would probably still be a good idea to accommodate the less experienced computer users.

BTW I cannot imagine any rational reason for making the color selector the default control, that should be assigned to the OK button instead.

**Comment by amtriathlon** [comment]
For search/filter see the wiki: https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_SearchFilter
The filter will be activated after Ok

**Comment by Mrnofish** [comment]
Wait, what? We're talking about filtering inside the Curve Settings Dialog, not filtering activities from the main GC window, which is what the linked wiki page is about.

I know perfectly well that activity search/filtering can be started from the main GC window by pressing Enter, but the same technique doesn't work from within the Curves Setup dialog and there is no UI element that can be interacted with by using a pointing device, unlike your previous suggestion seemed to indicate.

That functionality is still broken and hunting for metrics which you don't know exactly the name of among a squillion others that are alpha sorted is a needle-in-a-haystack proposition.

And clearly it shouldn't be that way, since the UI has provision to narrow down the metrics list.

Can you please re-open the bug, now?

**Comment by amtriathlon** [comment]
Auto completer works only in filter mode, not in search mode as shown in your screen capture.
The wiki explain the difference and how to switch between modes.
Enter will do syntax check in the next build.
