### ISSUE TITLE
After upgrading from 3.5 1903 to RC1, Ward-Smith and Veloclinic Estimations not working/break tables

### ISSUE THREAD

**Issue by Mrnofish** [GoldenCheetah/GoldenCheetah#3203]
Metric Trends Chart Setup; all estimates are set to Absolute.

![Golden Cheetah Power Estimates Setup](https://user-images.githubusercontent.com/28036193/67643170-a5553e00-f914-11e9-87fd-0507b286e573.PNG)

In RC1 the table comes up blank, while in chart view, the chart is missing the Ward-Smith and Veloclinic estimations.

Removing WS and Velo curves makes the table display correctly.

**Comment by amtriathlon** [comment]
These models were disabled: https://github.com/GoldenCheetah/GoldenCheetah/commit/7ff5a970df21874f396e32d172f35c3e1251bcb8#diff-099aff978870a68106cf5a5398f522af

**Comment by Mrnofish** [comment]
Thanks. Perhaps they should be temporarily removed from existing charts and Measures as well to reduce/avoid confusion.

**Comment by amtriathlon** [comment]
They are not used in default charts, AFAIK.
