### ISSUE TITLE
L/R balance v3.5-RC1

### ISSUE THREAD

**Issue by nenadjev** [GoldenCheetah/GoldenCheetah#3204]
There is difference in L/R balanse between GC i Garmin in v3.5-RC1

![Capture](https://user-images.githubusercontent.com/11903273/67695643-b1d5a700-f9a5-11e9-91e9-f6188c8aec4e.PNG)
![Capture1](https://user-images.githubusercontent.com/11903273/67695656-b4d09780-f9a5-11e9-8770-733fcce089f6.PNG)

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/5a93a2c62f68c7c1b36873d7897d3e319c08e706
