### ISSUE TITLE
ANT+ Connection Works for 2-5 minutes, then freezes until I unplug+plug in the USB Stick again & restart GoldenCheetah

### ISSUE THREAD

**Issue by charles-m-knox** [GoldenCheetah/GoldenCheetah#3207]
Similar to #3020, ANT+ USB stick connection dies after a few minutes. I'm running Ubuntu 18.04.3. I  followed the udev instructions listed in the Wiki. I'm running GC version 3.5-DEV1708.

I'll post more details as I come across them.

**Comment by charles-m-knox** [comment]
I switched to the latest dev build running version 3.5 dev rc1 (3980), and also noticed this tidbit in the [Wiki page](https://github.com/GoldenCheetah/GoldenCheetah/wiki/ANT--and-BTLE-Troubleshooting):

> When connecting your smart trainer to GC you should only connect the FE-C channel. No need to select Power and Speed as your trainer already sends this data on the FE-C channel for GoldenCheetah to read.

It seems to be working after manually unselecting the Power readout from my ANT+ trainer and only selecting the FE-C. 

I remembered having to do this weeks ago as well, but somewhere along the line I must have deleted + re-added the device and forgotten to unselect the Power readout from the paring window.

For the record, I'm using a CycleOps magnus.

**Comment by ThomasKregelin** [comment]
I had this problem with my Elite Nero Trainer. At the time I use GoldenCheetah 3.5 on Ubuntu 20.10 with an ANT+ USB Stick. 

After unselecting everything but the FE-C Trainer it worked flawlessly for me. 

Thanks for the solution. I was quite frustrated until I found this issue descritpion.
