### ISSUE TITLE
'Last 32 months' period in Trends not showing correct data?

### ISSUE THREAD

**Issue by ElDjoeri** [GoldenCheetah/GoldenCheetah#3208]
Dear,

Just started using Golden Cheetah and exploring the software. Imported data and while reviewing the Trends tab, I noticed that the 'Last 32 months' shows 51 activities (while I had more during that timeframe).

When I switch to the 'Last 12 months' period, the number of activities is indeed (a lot) more than 51. Could it be there is an error in the time range that is used for the 32 months period?

Kind regards,

Joeri

**Comment by amtriathlon** [comment]
May be a translation error, there is no “Last 32 months“ date range in English. Which language are you using?

**Comment by ElDjoeri** [comment]
Dear Alejandro,

I am using Dutch. After your reply, I checked the English wording and can confirm it is a translation error. (Should have thought about it and check it in the English UI first)

In English: 'Last 3 months', is erronuoulsy translated to: 'Laatste 32 maanden' in Dutch. The correct wording in Dutch is: 'Laatste 3 maanden'.

That also makes sense, given that the order in English is from small to large for the periods list in the Trends. While 32 was not in the Dutch UI. (Sitting in between 2 months and 6 months).

If you'd like, I can pass on the translation error on the correct page (since this isn't a code bug), or will you pass it on? (In case of the first, could you send me a link to the correct place?)

Kind regards.

Joeri

**Comment by amtriathlon** [comment]
Thanks, I will fix it.
