### ISSUE TITLE
Problems with Tacx Speed & cadence sensor

### ISSUE THREAD

**Issue by Leukhin** [GoldenCheetah/GoldenCheetah#3210]
Hello everyone, I ran into the problem of speed jitter when using the cycle machine and the TACX T2015 sensor.
Everything appears as follows: when I start doing a workout, when I reach about 20 km / h, a speed of 10 to 20 km per hour starts to jump, while the speed is about 20 km per hour, that is, it seems to fail. if I spin 30 km per hour, then the speed will fall to 20 km per hour or so, the values ​​are always different!

Golden cheetah 3.5

**Comment by amtriathlon** [comment]
There is a previous report (https://github.com/GoldenCheetah/GoldenCheetah/issues/2259) about a similar issue, but it is not clear if you also have FE/C or only the speed sensor.
In you athlete’s folder a log file (antlog.raw) is created which can help to diagnose.

**Comment by AnHaug** [comment]
Hi,

the antlog.raw file in my athlete's folder is empty (size 0). How can I activate logging?

Thanks
Andreas

**Comment by Ramoonus** [comment]
which version of GC are you using?

**Comment by wbagdon** [comment]
I'm using a TacX Neo 2 via BLE and seeing the same issue.
OS: Linux
GC 3.5

The speed appears to work for a bit and then drop off.
[2020_05_03_13_45_46.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4577235/2020_05_03_13_45_46.zip)

Let me know if there's more information I can provide
