### ISSUE TITLE
Improve Training Mode by improving Video-Layout.xml functionality.

### ISSUE THREAD

**Issue by sskpe500** [GoldenCheetah/GoldenCheetah#3213]
Please look at the forum post titled 

Training Mode #1 Wish List item - An updated  Video-Layout.xml file

Request that the following 3 variables be configured so they can be added to the Video-layout.xml

1) Target Power
2) Time running since start, 
3) Segment time remaining.

 Ale Martinez done some research on this and responded: 

Looking at the code (https://github.com/GoldenCheetah/GoldenCheetah/blob/bf9b42d5172211c21e186832d9399bc71af67164/src/Train/VideoWindow.cpp#L290) only Speed/Power/Cadence/HR are available as source for overlay meters currently, to add some additional real time data series in the same way would be an easy change, a little more complex would be to allow any supported one from RealTimeData (https://github.com/GoldenCheetah/GoldenCheetah/blob/bf9b42d5172211c21e186832d9399bc71af67164/src/Train/RealtimeData.cpp#L464).

**Comment by sskpe500** [comment]
![Video Overlay Idea](https://user-images.githubusercontent.com/4543524/68816431-0df62780-0644-11ea-9d7a-c1ccfc7d5d3c.png)
This is a picture of what I am trying to do

**Comment by sskpe500** [comment]
![Trainer Mode pic2](https://user-images.githubusercontent.com/4543524/68816525-5c0b2b00-0644-11ea-9688-585c5f03840f.png)
This shows how I already have the wattage , Heart rate, and cadence displayed on the video overlay

**Comment by amtriathlon** [comment]
I seems to me the layout you want can be achieved using Text meters in video-layout.xml, similar to:
https://github.com/GoldenCheetah/GoldenCheetah/blob/8e46c5d2b6443f995268dc90ba9d62a31459cfe5/src/Resources/xml/video-layout.xml#L53

I will add new sources: "Load", "Time", "ErgTimeRemaining" for your request and "LapTime"/"LapTimeRemaining" since they are similar.
