### ISSUE TITLE
Auto BackUp with UNC path failed

### ISSUE THREAD

**Issue by deix** [GoldenCheetah/GoldenCheetah#3219]
Dear GoldenCheetah Team,

I have some issues with "Auto BackUp" with UNC path. Even though I am able to specify the UNC path using the "Browse" button:
![GC_BackUp_0](https://user-images.githubusercontent.com/8902727/69417039-3521b880-0d18-11ea-8cbe-ab844786bedd.png)

I get the the error message trying to execute BackUp:
![GC_BackUp](https://user-images.githubusercontent.com/8902727/69417042-36eb7c00-0d18-11ea-8409-1b9be8313951.png)

There are no "space bars" in the path, only the "\" or "/" UNC slashes.

Best regards
Michal 
GoldenCheetah 3.5RC1
Windows 10 64bit

**Comment by amtriathlon** [comment]
GC v3.5 is using [QStorageInfo](https://doc.qt.io/qt-5.9/qstorageinfo.html) to check disk space available on backup directory and this method works for mounted storage and drives according to documentation, you would need to mount the network drive in your OS before to use it as a backup destination.

**Comment by deix** [comment]
Hi Alejandro,
This explains the fact, that I was not able to make backup. Will it not be an idea to add kind of "sanity check" for selected path - it could detect the "UNC" style and then report error via eg. [QMessageBox Class](https://doc.qt.io/qt-5/qmessagebox.html) ?
Best regards
Michal

**Comment by amtriathlon** [comment]
I'm not sure since the UNC path may work if the remote drive is mounted, besides a check at config time can become invalid at backup time. We could add a note to the Wiki.

**Comment by amtriathlon** [comment]
Added a note to both, backup folder on preferences and backup menu documentation.
