### ISSUE TITLE
O(n^2) string building in tracker table - busy hang

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3222]
I'm using golden cheetah on my tablet. My big sweaty sausage fingers sometimes press the wrong tab on the touch screen. Today I accidentally visited the "Tracker" tab under "Trends" and golden cheetah froze with 100% cpu for more than an hour before I killed it.

I profiled and found the problem is all those calls to summary.Arg() in the dataTable construction as for each of them QTCore does a string search and replace of wildcards on the entire string. There is always at least one wildcard near the end of the row that's just been appended. The issue is that summary is the complete string for the table.

I re-wrote the loop that fills each row to populate a QString rowSummary, then do a summary += rowSummary at the end of each row. This brought my time down from > 1 hour to about 5 seconds. 5 seconds is still too long but at least useable instead of broken.

**Comment by ericchristoffersen** [comment]
Implemented change and made pull request.

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/6ca8e49a523e5d7705a563efbbabb8f1230e7449

I checked RideSummary as another candidate to suffer this problem, but it seems to be Ok, when the activities tables are built args are replaced before appending to the result string.
