### ISSUE TITLE
Record Altitude When Training with Classic RLV

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3230]
Tried out some old rlv disks and find there's no altitude data modelled even though the trainer mode has access to slope. Train mode should calculate estimated altitude so climb data can be displayed while riding and also recorded as part of ride summary.

**Comment by amtriathlon** [comment]
There was a pending request for this feature (https://github.com/GoldenCheetah/GoldenCheetah/issues/2818), but lets keep this one since you are willing to implement it.

**Comment by ericchristoffersen** [comment]
Darn. I even searched.

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/2b291f28b7381a3bda136d57088db3e4c18f8491
