### ISSUE TITLE
Running activities from Xert

### ISSUE THREAD

**Issue by AceAzameen** [GoldenCheetah/GoldenCheetah#3232]
All running activities (with stryd power data) were changed to Bike mode when downloaded/synced from Xert.

**Comment by amtriathlon** [comment]
Can you give us more details?

Looking at the code it seems to be setting the Sport tag according to the activity_type informed by Xert:
https://github.com/GoldenCheetah/GoldenCheetah/blob/2b291f28b7381a3bda136d57088db3e4c18f8491/src/Cloud/Xert.cpp#L407
```
        if (!ride["summary"].toObject()["activity_type"].isNull()) {
            QString stype = ride["summary"].toObject()["activity_type"].toString();
            if (stype == "Cycling") ret->setTag("Sport", "Bike");
            else if (stype == "Running") ret->setTag("Sport", "Run");
            else if (stype == "Swimming") ret->setTag("Sport", "Swim");
            else ret->setTag("Sport", stype);
        }
```

**Comment by amtriathlon** [comment]
I am closing this since, without more information, it doesn't look like a bug in our code.
Please reopen if you can contribute with more information, including a test file to upload to Xert to recreate the issue if possible.
