### ISSUE TITLE
[Old 361] Strava "sections"

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#324]
Strava has a great feature in which you can create "sections" using GPS data, for example - a hill you often go over or place you regularly time trial through. Its like being able to specify an geography based interval and then compare performance over it. Would love to see something like this in Golden Cheetah so that you could see how your average time, power, etc. vary over sections of rides I regularly go over.

Thanks in advance

Add
Related issues

History

#1 Updated by Mark Liversedge over 1 year ago
Target version set to 3.1
#2 Updated by Damien Grauser over 1 year ago
Assignee set to Damien Grauser

**Comment by grauser** [comment]
We have Route, GPS segment, in V3.2
