### ISSUE TITLE
Fix Fix Power Spikes

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3241]
Improve Fix Power Spike Feature:

1) Fix power spikes currently stops operating if a sample is found that is under the max variance, where intent was perhaps to skip just that sample.

2) Add option (check boxes) for fix power spikes to also interpolate cadence, speed, gear and slope for those samples with anomolous power readings.

3) Probably we should change the defaults. I think most people would wish to interpolate a sample based on its variance. Depends on how noisy the normal data is but I think I would prefer something like 500 watts and variance of 20%.

**Comment by ericchristoffersen** [comment]
Dialed change back to just #1 and #3. Fixing other types of spike related problems involves fixing speed which is an involved problem.

**Comment by amtriathlon** [comment]
I think default max power value was set to a too low value for most users (200 watts will trigger a lot of false anomalies, s.t. https://github.com/GoldenCheetah/GoldenCheetah/issues/3318), IMO we should revert this value to the previous default.
I am not sure about the change in variance.

**Comment by ericchristoffersen** [comment]
Remember the core of that change is that the variance filter was previously totally broken in that if single sample was found to exceeded variance the filter would process no subsequent samples... Variance had to be kept too high or filtering was truncated, so it was simply a bandpass where only threshold mattered.

The new behavior recognizes spikes as being above threshold (today default 200) AND above variance (today default variance is 20).

What I find on my own trainer is that power spikes occur at all intensities and can be both up and down, the key is how much variance you wish to tolerate in your power readings.

I recommend you all play around with the current settings and see what works for you.

**Comment by Ragbrai** [comment]
Hi I would like to remove a power spike from my data:
1 sec Power-1977wats
Ave HR 88
Ave Cadence 74
Ave Speed 12

How can I do this?  In previous versions I could edit my data and correct the power number.  I don't see that feature in the 3.5 version

**Comment by amtriathlon** [comment]
We have a wiki and a user’s forum if you need help.
