### ISSUE TITLE
RideCache Problem: all intervals are showing the same values for most metrics in v3.5 RC2

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#3244]
![Screenshot from 2019-12-07 17-10-27](https://user-images.githubusercontent.com/1444784/70380226-715b3880-1916-11ea-8558-d3736211617b.png)

Note that all intervals have the same values for most of the metrics, notably Duration.
The displayed testing file is https://github.com/GoldenCheetah/GoldenCheetah/blob/master/test/rides/2009_07_04_06_09_48.wko, but the problem is general and, for what I have seen up to this point, caused by the write cache part of https://github.com/GoldenCheetah/GoldenCheetah/pull/3235, since:
a) deleting the cache I can see the problem in the cache file after the first save, without the need to restart GC so the load part is not yet involved.
b) reverting https://github.com/GoldenCheetah/GoldenCheetah/commit/fa9a59d60ced1cd0baf0f1650ed3b026f3e5d13d and running after deleting the cache file seems to fix the problem.

**Comment by ericchristoffersen** [comment]
Rats. I was worried that I didn't have enough tests for the escape characters.

**Comment by ericchristoffersen** [comment]
Pushed fix to revert the cache write change. Verified that intervals are correct on cache reload.

**Comment by amtriathlon** [comment]
It looks like a copy paste error, look at the final 2 lines of your changes where item is used instead of interval to point to metrics and counts, this explains the metrics (and counts) for the whole activity are used for all intervals.
