### ISSUE TITLE
user metrics is not evaluated on rides

### ISSUE THREAD

**Issue by gillesF78** [GoldenCheetah/GoldenCheetah#3249]
I installed version 3.5-RC1-64bit on windows.

The user metrics that was working in version 3.4-dev1 is not anymore evaluated on previous and imported rides
![GC-no_user_metrics](https://user-images.githubusercontent.com/20644297/70433159-46d9be80-1a81-11ea-8e07-8d74ea73625c.png)
:

hrTSS:

{
init { myVal <- 0; }
sample{
if(Data contains "P") myVal <- TSS;
else myVal <- TRIMP(100)_Points * 1.2;
}
value { myVal; }
}

Thanks

Gilles

**Comment by amtriathlon** [comment]
TSS is no longer available in v3.5, additionally that code can be simplified and improved.
Please use the forum to get help.
BTW,  TriScore fallbacks to TRIMP Zonal Points when there is no power in v3.5
