### ISSUE TITLE
[Old 353] Aerolab features

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#325]
I'm going to suggest a few usability features that could be added to Aerolab.
1. (highish priority, and maybe simple) Right now the elevation offset is limited to about +/- 300 meters. However, if the ride file includes elevation data and the initial elevation is higher than 300m then there's no way to "bring the VE up" to match the start point. That's a problem if the ride starts at, say, 2000m -- in that case, the vertical scale is so large that it often swamps out the VE. A simple and quick fix would be to extend the range of the eoffset slider but a better way might be to see whether the data includes elevation and automatically adjust the initial elevation to that.
2. Zooming into a segment. Right now Aerolab models the entire ride file but there's no simple way to zoom into a particular section of the ride. It would be very cool if sliders like those on the main ride plot could be added to the Aerolab window so focus on a segment of the ride. (If the data included elevation data you'd want to reset the starting elevation as in #1 above).
3. Adding a checkbox for whether the segment being analyzed (which could be the entire ride) is an out-and-back. If so, then add a "mirror" VE line in gray. That is, if you're doing an out-and-back on a half-pipe course, the VE profiles for the first and last km should be mirror images of each other. That's often helpful for finding the "right" Crr and CdA, or diagnosing different wind conditions on the outbound and inbound legs. Sometimes the start/finish might be a little bit off, so zooming as in #2 can be useful to cut off the non-matching bits.
4. Adding an air density calculator for rho. Right now we have to calculate rho outside of GC.
5. (lower priority) Out-and-backs can be handled with a check box and a mirrored gray line but loops are a bit trickier. Basically, one nice solution is to "stack" the loop VE's on top of each other. That could be done if there were a slider for the number of loops for a particular zoomed in segment -- the slider would be non-integer because sometimes you might only do 2-1/2 loops. Then you calculate the VE as always but if the loop slider is > 1.00, you plot the VE as overlaid loops for the right distance into each loop.

0001-added-a-new-air-density-rho-estimator-dialog-box-hoo.patch   - air density calculator/estimator patch (15 kB)   Steve Gribble, 01/07/2012 04:26 pm
Add
Related issues

History
#1 Updated by Mark Liversedge over 1 year ago

Target version set to 3.1
#2 Updated by Steve Gribble 10 months ago

File 0001-added-a-new-air-density-rho-estimator-dialog-box-hoo.patch added
% Done changed from 0 to 20
Estimated time set to 4.00
Patch Attached changed from No to Yes

Hi folks,

I've attached a patch that adds an air density (Rho) estimator to Golden Cheetah. Users supply the estimator with measurements of temperature, air pressure, and dew point, and the estimator uses Herman Wobus' model for vapor pressure, plus the standard equations for calculating air density, to provide Rho. This feature is useful for dialing in the Rho value in aerolab.

The patch hooks the estimator into the Tools menu as another dialog box, similar to the CP estimator that's also under the tools menu.

Enjoy!
--Steve
#3 Updated by Mark Liversedge 10 months ago

rho estimator applied in changeset #5c8beee46

**Comment by RedIsFaster** [comment]
Are fixes for elevation limits only targetting 4.0?

**Comment by amtriathlon** [comment]
I am closing this since it was subsumed by https://github.com/GoldenCheetah/GoldenCheetah/issues/3561
