### ISSUE TITLE
Accents on characters

### ISSUE THREAD

**Issue by gillesF78** [GoldenCheetah/GoldenCheetah#3250]
In version 3.5-RC1 windows 64 bits :
Accents are not correctly displayed in the Activities tab. It looks like a UTF-charset misconfiguration:
![GC-no_accents](https://user-images.githubusercontent.com/20644297/70433567-602f3a80-1a82-11ea-9631-ecb0b8af2652.png)

**Comment by amtriathlon** [comment]
This is fixed in v3.5 RC2 but you may need to edit Zones > Defaults to get the accents back.
