### ISSUE TITLE
WaterRower import and analyzation?

### ISSUE THREAD

**Issue by TanjaZ84** [GoldenCheetah/GoldenCheetah#3255]
Hi there,
first and foremost thank you a lot for providing this great software!
I am not sure if it is allright to post this here because it is against the "contributing guidelines" from my current display's right side frame but it says here (https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-GENERAL#How-do-I-report-a-bug-or-request-a-new-feature) to do so, so I just go ahead and hope it will be ok!

I am either a ambitious athlete nor a computer wizard but I like to look at my workout's data and I love my privacy so I am really grateful for GC althoug it is a bit "too much" for my comprehension capability.
I do row indoor (winter) and run outside (summer) so I would like to compare running workouts to rowing sessions. To record my rowing I use "Coxswain" which is a open source android app (https://github.com/svenmeier/coxswain) and lets me export a *.tcx-file.
So here is my "request": 
Could you implement "rowing" as a sport with its own metrics i.e. Strokerate? 
And could you add the Coxswain export file to your importable files, so that Golden Cheetah knows what data means what?

Again thanks for your effort and work!
Regards

**Comment by amtriathlon** [comment]
I would suggest first to learn how to use GoldenCheetah current facilities, see the wiki for information and the users forum for questions. Most of what you are currently requesting is already possible, including to define Stroke Rate as a metric or to analyze rowing all your rowing data.
After that you may have a more clear definition of what to ask for.

**Comment by TanjaZ84** [comment]
Hi amitriathlon
thanks für your time. The sad thing is I already spent most of last week and all of last weekend trying to understand GC. I won't go into detail of what I did and what I accomplished on my own because that's pretty sad. Would you point me in the right direction of the wiki because I did not find those answers there?

**Comment by amtriathlon** [comment]
If you want to define Row as a new sport you can start here: https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Preferences_Data-Fields

To filter your activities and charts see https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_SearchFilter

To define custom metrics for rowing s.t. Stroke Rate or pace each 500m https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Creating-User-Metrics.

But the users forum to search and to ask these questions and there you can receive answers from other users: https://groups.google.com/forum/#!forum/golden-cheetah-users

**Comment by MelHarbour** [comment]
As a rower/coach (responsible for getting @liversedge to add some rowing related features to GC, happy to contribute experience of using it for analysing rowing. If you've got specific questions etc, I might be able to add some how-tos to the Wiki.

**Comment by amtriathlon** [comment]
That would be interesting @MelHarbour, as we have a section to the wiki for Running&Swimming it would be useful to have one for rowing.
