### ISSUE TITLE
Opening Window

### ISSUE THREAD

**Issue by MaxLaturte** [GoldenCheetah/GoldenCheetah#3256]
I'm a cycling coach and I have few athletes profiles saved. When opening GC, why isn't the athlete choosing window not always appearing and systematicaly openig one of the athlete's profile ?
Is there some parameter to solve this problem ?
Currently working on v3.5 RC2X but the problem already was the same on v3.4 & 3.5 RC1
Thx for informations,

**Comment by amtriathlon** [comment]
This is more like a feature than an issue: GC is primarily intended for athletes and, by Default, it opens the last closed user at startup. You can force the select athlete dialog be showed at startup passing — as command line parameter.
