### ISSUE TITLE
Strava still not syncing after upgrade to RC2 and strava reauth

### ISSUE THREAD

**Issue by VincentJGeisler** [GoldenCheetah/GoldenCheetah#3257]
I've got the same problems as outlined in #3216. Problem still not fixed after upgrade to latest RC

last sucessful update was oct 23

**Comment by amtriathlon** [comment]
Is there any error message present on goldencheetah.log after a sync attempt?

**Comment by Mountaingoat1** [comment]
Same troubles here. It worked for a while with RC2, then suddenly did not work today. I'm on Win 7. Not sure where to find goldencheetah.log.

**Comment by amtriathlon** [comment]
> Not sure where to find goldencheetah.log.

Parallel to athlete’s folder, see Help>About

**Comment by amtriathlon** [comment]
I teste v3.5RC2X on Windows 10 just now and it is working normally for me.
Please see https://groups.google.com/d/msg/golden-cheetah-users/TIXYuun6ntY/vkz5AIJ1BwAJ
