### ISSUE TITLE
How to create a speed vs deltatime/delta distance graph

### ISSUE THREAD

**Issue by montemuggio** [GoldenCheetah/GoldenCheetah#3258]
Hi all,

I am making some test between a footpod and the GPS on my Garmin 935 to determine the differences in pace/speed.
I understand from this WKO guide that is possible to compare the speed channel from the watch/pod to the delta time/distance to assess if there are mismatched between the two way to measure speed/pace.

https://help.trainingpeaks.com/hc/en-us/articles/360030942511-Calculating-Workout-Speed-In-WKO

Is it possible to replicate in Golden Cheetah the  chart as displayed in the above webpace?

thanks
Michele

**Comment by amtriathlon** [comment]
The Activity chart allows to define User Data curves, the formula for the speed series is just `SPEED` and for distance/time  `3600*(DISTANCE[INDEX]-DISTANCE[INDEX-1])/(SECS[INDEX]-SECS[INDEX-1])`.
BTW, documentation is in the Wiki and the place to ask this questions is the users forum.
