### ISSUE TITLE
RPE import from Strava

### ISSUE THREAD

**Issue by MaxLaturte** [GoldenCheetah/GoldenCheetah#3259]
Hi,
Do someone know if the RPE is an information supported into .fit files imported from Strava ?

Since the update on Strava where we can fill RPE on activities, is it possible to import automatically this information to GC ?
I suppose not, but anyway, had to ask ! :)

Thx

**Comment by amtriathlon** [comment]
Apparently not: https://developers.strava.com/docs/reference/#api-models-DetailedActivity
