### ISSUE TITLE
Please add installer for Mac for RC2x

### ISSUE THREAD

**Issue by lkgarrison** [GoldenCheetah/GoldenCheetah#3264]
I would like to request an installer for Mac for the latest 3.5 release candidate. I had been eagerly awaiting Strava sync support, encountered https://github.com/GoldenCheetah/GoldenCheetah/issues/3216, saw that it would be fixed in an upcoming update, and now am unable to install that update on my OS.

If an installer for Mac could be added to the list of assets for the RC 2x release, I'd be happy to test the latest iteration of 3.5 and provide any useful feedback I encounter during my usage. 

Thank you!

**Comment by amtriathlon** [comment]
From the issue you referenced:
> Until the official RC2X build for Mac is available the automatically generated one can be downloaded from: https://transfer.sh/sKSxD/dev-prerelease-branch-master-build-3309.dmg

**Comment by amtriathlon** [comment]
The ci build is uploaded as GoldenCheetah_v3.5-RC2X_64bit_MacOS-ci.dmg to the release.
When the official build is ready it will be added there too.
