### ISSUE TITLE
Importing fit files from my Garmin request (problems)

### ISSUE THREAD

**Issue by ToniPriego** [GoldenCheetah/GoldenCheetah#3265]
I could download all my fit files from Garmin. I send an email to them and they prepared me a .zip file.
In this .zip file I have around 3.700 fit files. But when I try to import them, there are some that they are in blank or corrupt, so the program don't le me continue. I was thinking for the size of the file, but it doesn't work. What can I do?

**Comment by amtriathlon** [comment]
We have a users forum to ask for these questions.
