### ISSUE TITLE
Strava not syncing (Debian 9 / Windows10)

### ISSUE THREAD

**Issue by parri80** [GoldenCheetah/GoldenCheetah#3266]
Hi Team,

there is no way te sync any activite from time now, I tested from many different computers and operating systems with the same result, syncronization window never updates the activites stored on Strava, so you need to perform this task manually.

It's being a mess to deal with this on a daily basis, has this been treated before? is there any workaround or solution to this problem?

I would like also to add that there are other tools retrieving Strava data with no issue for the same profiles.

Thank you in advance for your valuable help.

With best regards

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/issues/3216
