### ISSUE TITLE
Can we make the UI more usable with tablet?

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3268]
My trainer is hooked to a 12" tablet screen with 1920x1080 resolution. The 4 pixel wide scroll bars are pretty much impossible to access with my phat phingers. Could we please please please make the scroll bars wider? Or have the scrollbar widths controlled somewhere?

Primary pain for me is having to access the device settings from the main ui. Once I'm at the settings page I can navigate with keyboard but before that is multiple wrong selections with my fingers.

**Comment by gogolo2** [comment]
I support this. Easiest solution would be to make the bars wider. A tablet mode of GC would be best.

**Comment by amtriathlon** [comment]
I am afraid It is not very likely a tablet mode be introduced anytime soon.

Perhaps a more specific requirement could be addressed, are you talking about the sidebar scrollbars or anything else?
