### ISSUE TITLE
V3.5-RC2X TSS edit.

### ISSUE THREAD

**Issue by galileo-82** [GoldenCheetah/GoldenCheetah#3269]
Hello, 

TSS edit on Details/Metric tab is not working (running V3.5-RC2X) although it was working properly in previous version. A number can be edited but when clicked outside of the box it goes to zero automatically. I made a search but did not find a similar topic.

Thanks.

**Comment by amtriathlon** [comment]
TSS is being deprecated in v3.5, there is a compatibility metric named TSS to enable pre-existing charts to continue working but it has several limitations. I recommend to add a Data Field in preferences similar to your existing TSS but named BikeStress and use it for overrides, it will impact on your TSS dependent charts and it is a better solution for moving forward.

**Comment by galileo-82** [comment]
> TSS is being deprecated in v3.5, there is a compatibility metric named TSS to enable pre-existing charts to continue working but it has several limitations. I recommend to add a Data Field in preferences similar to your existing TSS but named BikeStress and use it for overrides, it will impact on your TSS dependent charts and it is a better solution for moving forward.

Many thanks for your response. I have manually edited BikeScore in the Details/Metrics tab of the activity, but it does not impact on TSS unfortunately. I searched under chart settings to add Bike Stress but there is no option. :(

**Comment by amtriathlon** [comment]
BikeScore is an independent metric, the new name for TSS is BikeStress and you can add it to Details tab with an entry like this in Options/Preferences > Data Fields:
![BikeStressOverride](https://user-images.githubusercontent.com/1444784/71268127-f6891900-232a-11ea-8306-7352eea9f0f3.png)

**Comment by galileo-82** [comment]
> BikeScore is an independent metric, the new name for TSS is BikeStress and you can add it to Details tab with an entry like this in Options/Preferences > Data Fields:
> ![BikeStressOverride](https://user-images.githubusercontent.com/1444784/71268127-f6891900-232a-11ea-8306-7352eea9f0f3.png)

![GC options 2](https://user-images.githubusercontent.com/56796799/71310520-b787c000-241d-11ea-8ba9-b25d5dc13ed5.png)

Unfortunately there is no BikeStress here. Please see attached file.

**Comment by amtriathlon** [comment]
For new users it is created automatically, existing users need to add it using the (+) button and the arrows to order.

**Comment by galileo-82** [comment]
> For new users it is created automatically, existing users need to add it using the (+) button and the arrows to order.

I click the (+) button but there is no choice to add anything. :( 
![GC opt3](https://user-images.githubusercontent.com/56796799/71323124-71dbfd80-24d8-11ea-84a8-af8af4d5a685.png)

**Comment by amtriathlon** [comment]
A new field was added at the first row, a simple click allows to change the Screen Tab or Field part, the arrows at the bottom left allows to position the selected field were you want.

**Comment by galileo-82** [comment]
> A new field was added at the first row, a simple click allows to change the Screen Tab or Field part, the arrows at the bottom left allows to position the selected field were you want.

Many thanks for your help, I appreciate it! I thought a drop down menu would appear, but the solution is to manually write "BikeStress" :)

**Comment by nanainmk** [comment]
I tried this method a few weeks ago and could still not get it to work properly

**Comment by amtriathlon** [comment]
> I tried this method a few weeks ago and could still not get it to work properly,does not give you a tick box next to bikestress in the edit metrics tab and does not overwrite imported details because of this. Have tried deleting the TSS field and just leaving bikestress there and that does not work either

It’s BikeStress, not bikestress

**Comment by nanainmk** [comment]
Thanks don`t see why you would have a capital letter halfway through a word but it works now so ThaNks
