### ISSUE TITLE
Suunto 9 Swimming activities FIT format 

### ISSUE THREAD

**Issue by goosst** [GoldenCheetah/GoldenCheetah#3272]
Hello,

If I sync my activities through Strava, swim activities create strange metrics values (see screenshot below). As a consequence it messes up those nice graphs about CTL, RR etc. . 
It doesn't matter if it was a swim-activity which has been manually added or has automatically synced through my watch (suunto).
I'm pretty sure my critical swimming speed isn't set very accurate, but I don't think it can explain this order of magnitude of numbers (unless I'm mixing up units somewhere). 

I'm using version V3.5 RC2X

![GC_screenshot](https://user-images.githubusercontent.com/8907127/71483499-69513300-2808-11ea-925a-409ef7b393c6.png)

Thanks!

**Comment by amtriathlon** [comment]
Swimming activities via Strava and FIT files are tested using Garmin devices only, you would need to attach Suunti testing files if you want them diagnosed/supported.
Suunto SML files are tested for lap and OW swims, but I’m afraid Suunto is not making them easily available anymore.

**Comment by goosst** [comment]
Thanks for the reply.

Just for clarity, also when adding a swim as a manual activity on strava (i.e. adding a time and distance manually, without any link to a watch), it produces this result. So my question is not entirely linked to suunto.



Here you can download a fit file (exported from the suunto app, created with a suunto 9): http://users.telenet.be/goosst/Swimming_2019-12-24T09_21_59.fit
It produces the following results in Goldencheetah and in the suunto app (which is also wrong but at least closer to reality ... ): 

![gc_fit](https://user-images.githubusercontent.com/8907127/71486959-12a02500-2819-11ea-86e6-f8daf8ee6fc9.png)


![Screenshot_20191226-194916](https://user-images.githubusercontent.com/8907127/71486960-12a02500-2819-11ea-9515-f55b652883b4.png)

**Comment by amtriathlon** [comment]
Directly importing this file doesn't produce useful data, some detailed debugging woud be necessary.

OTOH Uploading this file to, or creating a similar manual activity, in Strava gives siimilar results when sync to GC: Distance 600m, Time 11:12, Average Pace 1:52, TriScore 7 with CV 1:37, all of this looks reasonable.

The impossible values you see for CTL/ATL/etc. depend on TriScore values for previous activities, so you need to look at them, in the wiki you can find some guidance: https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-RUNNING-&-SWIMMING#why-the-triscore-value-is-zero-or-so-high

**Comment by goosst** [comment]
Thanks for the checking and feedback.

I'm probably missing something but it's always a swimming activity that generates outliers for CTL etc.. Here are a few screenshots from random activities:
![gc_screenshots](https://user-images.githubusercontent.com/8907127/71521332-93fec280-28c0-11ea-96b5-b733e2ce8229.png)

The trimp scores looks quite normal indeed. So maybe I should just ignore those CTL/ATL numbers for multi-sport activities.
![trimpstuff](https://user-images.githubusercontent.com/8907127/71521386-d9bb8b00-28c0-11ea-975b-01ac4e1b7410.png)

thanks

**Comment by amtriathlon** [comment]
> I'm probably missing something but it's always a swimming activity that generates outliers for CTL etc.. Here are a few screenshots from random activities:

What I think you are missing is CTL and ATL are exponentially weighted moving averages so they depend on TriScore for all the previous activities (swims in this case), the source of those high numbers are some outliers like the one on november which causes that big spike in ATL & CTL.
If you add TriScore to the chart it is easier to find and fix them. The wiki explain why and how and you can use the forum to get help.

I will let this open since we should fix Suunto 9 FIT files import and your sample file is useful for that.

**Comment by goosst** [comment]
ok, fair enough :)
If .fit files from suunto are interesting, let me now if you need additional ones and I can export a quantity through the suunto app. (Quite annoying way to get to your data, but let's hope it's just a transition phase from suunto).

**Comment by amtriathlon** [comment]
A couple of swim files with an associated description indicating the workout structure would be useful, thanks!

**Comment by goosst** [comment]
Here are a few: users.telenet.be/goosst/suunto9_swim.zip
let me know if you've downloaded them, then I'll delete the zip file again.
