### ISSUE TITLE
Support more Sport Types, ie: map VirtualRun to Run

### ISSUE THREAD

**Issue by ph4r** [GoldenCheetah/GoldenCheetah#3278]
I do over half of my training on Zwift currently, and Strava pulls in those events with Sport type set to VirtualRide or VirtualRun.  I just noticed that when that happens since the Sport is unknown the data is not included in trends and perhaps other areas (such as auto-finding appropriate intervals).  Some people like to keep indoor and outdoor metrics separate (as if they were separate sports); however, I am happy to consider them the same.  Option to suit me is to provide an Import Task to remap sports to a user list, or add these types as aliases automatically.  For the others a much more complicated solution may include an ability to create a new sport and choose how it is treated in total.

**Comment by amtriathlon** [comment]
I thinke for the Sport field VirtualRun and VirtualRide should be mapped to Run and Bike respectively and SubSport used to differentiate them, like in FIT file import.

**Comment by ph4r** [comment]
Elegant Code Change, I assume this this only works on newly synced activities?  Is there a non-manual method to update my existing database to match?

**Comment by amtriathlon** [comment]
Yes, the change is in download code. You can use set in the filter box to change existing activities:
`set(SubSport, Sport, Sport="VirtualRun")`
and then
`set(Sport, "Run", Sport="VirtualRun")`

**Comment by ph4r** [comment]
Thanks, I'm currently on V3.5-RC2X and SubSport isn't a field, so I used keywords for now and stored filters to update my Zwift Runs and Rides until this is released.

set(Keywords, Sport, Sport="VirtualRun")
set(Sport, "Run", Sport="VirtualRun")
set(Keywords, Sport, Sport="VirtualRide")
set(Sport, "Bike", Sport="VirtualRide")

**Comment by amtriathlon** [comment]
Likely because your Athlete was created with a previous version, for new athletes it is create automatically, for existing ones you can add it, see the wiki for how to add metadata fields.
