### ISSUE TITLE
HR Zones 

### ISSUE THREAD

**Issue by Fluxator** [GoldenCheetah/GoldenCheetah#3279]
Workouts with sports other than Bike/Run/Swim are sometimes recorded for stress tracking via HR (TRIMP/Triscore). 
GC uses Bike HR zones  for TRIMP calculations even if other zones are defined for running. 
Most of the time the running zones would be more accurate. Dedicated zones for everything other than Bike/Run would be even better.

**Comment by amtriathlon** [comment]
If you prefer to use Run Zones for others sports you could set Sport="Run" and to use the SubSport field to differentiate them in filters.
The real solution is to make any sport first class generalizing Hr/Power/Pace zones for any sport, not just swim, bike and run. May be in the next release if there demand for it, I will open a feature request for this.

**Comment by Fluxator** [comment]
> you could set Sport="Run"

I thought about that, but it is has its disadvantages: 
- requires manual editing of workouts
- it messes up strava sync 
- it messes with filters

Feels like GC is quite close to supporting this but not quite there. 
I agree with the real solution, but that sounds like work.

**Comment by amtriathlon** [comment]
Manual edit can be avoided using set in the filter box, for example if the Run-like sport is Row:
`set(SubSport, Sport, Sport="Row")` and then `set(Sport, "Run", Sport="Row")`
filters are easily changed in GC and wrt to Strava sync it could be a problem if you use upload, not for download only.
Yes, the generalization requires some design, coding and testing. Looking retrospectively would have been better to go that way from start, but we were adding sports incrementally and here we are.

**Comment by Fluxator** [comment]
Thanks, it's not pretty, but it works. 

Alternatively, a simple change in GC would be to offer a checkbox "use as default zone model" in the bike/run zones and then use that for all sports other than bike/run.

**Comment by amtriathlon** [comment]
> Alternatively, a simple change in GC would be to offer a checkbox "use as default zone model" in the bike/run zones and then use that for all sports other than bike/run.

IMHO that’s far from a simple change and, considering all the places in code that needs to be changed, I would prefer to directly go to zones generalization.

**Comment by amtriathlon** [comment]
I'm closing this since it is subsumed in the more general https://github.com/GoldenCheetah/GoldenCheetah/issues/3280
