### ISSUE TITLE
Generalize Power and HR zones for any sport

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#3280]
Currently we have:
- Power Zones for Bike and Run, default Bike.
- HR Zones for Bike and Run, default Bike.
- Pace Zones for Run (min/km or min/mi) and Swim (min/100m or min/100yd), default Run.

Some users are using GC for sports other than S/B/R and they have requested to have zones specific for these.

**Comment by amtriathlon** [comment]
I plan to implement this in 3 parts:

1. Add normalized sport field to RideItem/RideDB as primary field deriving isRun/isSwim from it for compatibility plus isRide/isXtrain for consistency, use them in DataFilter and RideSummary.
2. Use sport instead of isRun/isSwim to access zones preserving existing ones and adding the new ones by demand based on default zones.
3. Add Rowing as a test case, eventually with pace in mm:ss/500m

**Comment by srwareham** [comment]
Just echoing that a min/500m pace for rowing would be amazing.

Are there plans for GC to be able to import/store other rowing data? I wouldn't anticipate the data would really be integrated for trends etc., at least for a good while. 

If helpful, I've attached a CSV of a Concept2 rowing workout recorded using the BoatCoach Android app. This is the only cloud-free way of capturing second-by-second workout data from an Erg that I've come across and might at least be a good starting point for a data model.
[boatcoach_2020-05-06__11-20-26.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/4587946/boatcoach_2020-05-06__11-20-26.txt)

**Comment by liversedge** [comment]
we support rowperfect3 files, with much of the stroke data going into xdata series, so could extend to include other formats too. will have a look at the file.

I don't row any more (have a C2 in the attic) so don't know if boatcoach is popular or just one that you use? Would like to support the most popular formats first ...

**Comment by srwareham** [comment]
The official app developed by Concept2 is called ErgRace, however, it does not record any session-level data. It was written by Dan Eiref. He then went on to write BoatCoach, which at least seems to be from the same code base. From my research it is the *only* non-cloud option, however I'd be quite excited if anyone else had experiences to the contrary.

**Comment by liversedge** [comment]
Have added a new issue #3434 for boatcoach support, can continue the dsicussion there.

**Comment by amtriathlon** [comment]
If you want a Row Pace metric, similar to Pace or Swim Pace but in min/500m units, you can add it as a custom metric like this:

![Row_Pace](https://user-images.githubusercontent.com/1444784/81323742-33e90b80-906c-11ea-8965-4e4dc96291b6.png)

I will upload it to CloudDB for v3.6

**Comment by Mickyduck55** [comment]
First time I have commented on here but I think a lot of people who row (on C2) will by now be using ErgData which Im sure you know is C2s App. and C2s online logbook I also have RowPro which seamlessly links to the C2 logbook.  From the C2 logbook I can export data as FIT... which I do and import to GC.  The data is displayed in the ride window and looks just like a "ride" with laps being logged as every 5 mins.  Happy to supply any files that are required from C2 logbook as CSV, TCX or FIT.... these are the export formats available, as I said FIT imports to GC without errors.

**Comment by amtriathlon** [comment]
Hi, if FIT is working I think we should use it as a richer and more compact format, if you want to add a sample it can be attached after zip compression.

**Comment by Mickyduck55** [comment]
Hi Ale
here is aFIT  file from the C2 logbook.. I have added a snapshot of how it
looks in "ride"
Thanks for all your help re the Fortikus LOL

**Comment by amtriathlon** [comment]
Thanks, but attachments by mail don't work, you need to drag&drop the zipped file on github site.

**Comment by Mickyduck55** [comment]
If only I could find it !!!

**Comment by amtriathlon** [comment]
Where you wrote your first comment: https://github.com/GoldenCheetah/GoldenCheetah/issues/3280

**Comment by Mickyduck55** [comment]
Found it...

[Downloads.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4806870/Downloads.zip)

**Comment by amtriathlon** [comment]
It looks good when imported, only problem is variable recording interval each 2-3 secs, but this is easy to solve using Edit > Fix Gaps, after that all GC metrics should be Ok.

**Comment by Mickyduck55** [comment]
Not sure I understand that.. if I go to edit in GC there is a reading every
second

**Comment by Mickyduck55** [comment]
End of row data.. one entry every second

**Comment by amtriathlon** [comment]
Likely because you have Smart Recording enabled in Options/Preferences so gaps are automatically interpolated on import, I would suggest to switch to users forum (https://groups.google.com/forum/#!forum/golden-cheetah-users) for any other question.

**Comment by Mickyduck55** [comment]
OK thanks will delete my comments.. including this one

**Comment by TanjaZ84** [comment]
> 
> I don't row any more (have a C2 in the attic) so don't know if boatcoach is popular or just one that you use? Would like to support the most popular formats first ...

I think one of the most used rowing machines is the Waterrower (also known from Hous of Cards). Together with the android app coxswain you get a *tcx-file. I would be happy to provide example files.

I think for rowers it would be interesting to correlate stroke frequency, power, velocity and heart rate.
