### ISSUE TITLE
Memory leak on strava synch

### ISSUE THREAD

**Issue by arpia49** [GoldenCheetah/GoldenCheetah#3290]
Hello, I've spotted what it looks like a memory leak on strava activity synch and download (haven't tested upload).

Memory consumption starts to grow with every downloaded/proccessed activity. When syching more than 200 activities, it usually consumes all my RAM and closes.

Screenshots and what I think it is the related crash log and dump, attached.

![2020-01-09 23_36_13-Window](https://user-images.githubusercontent.com/126833/72111142-39db1400-333a-11ea-9fee-a7d47a43332c.png)

![2020-01-09 23_43_12-Window](https://user-images.githubusercontent.com/126833/72111146-3a73aa80-333a-11ea-97a5-b274c2572920.png)

[crash_2324_090120.log](https://github.com/GoldenCheetah/GoldenCheetah/files/4042899/crash_2324_090120.log)

[crash_2324_090120.dmp.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/4042903/crash_2324_090120.dmp.txt)

Windows 64bits, 3.5RC2X.

**Comment by amtriathlon** [comment]
How much RAM do you have?

That memory consumption doesn’t seem exaggerated if you are importing several hundreds of activities at a time and plan to have several years of history on a single athlete.

See this thread with a good explanation about GC memory requirement vs performance trade off: https://groups.google.com/d/msg/golden-cheetah-users/uIdc1gHsAkw/aV6dcy5QBAAJ

**Comment by arpia49** [comment]
Hello, I think it is a bug (an unimortant one) as:

- It is consuming memory that seems not used after the synch as after the restar it consumes far less. - It is closing the app and generating a crash file.

But it is true that:

- Only 4GB of RAM on my desktop.
- It is easy to restart thre process after the close.
