### ISSUE TITLE
Strava Sync funktioniert nicht

### ISSUE THREAD

**Issue by lavamann** [GoldenCheetah/GoldenCheetah#3292]
Strava Sync funktioniert nicht mit Version 3.5 RC2X. Habe alles versucht, neu authentiziert, etc.
Token in GC ist nicht der gleiche wie in Strava
Fehler: "Zeitüberschreitung bei Socketoperation"

**Comment by amtriathlon** [comment]
see https://groups.google.com/d/msg/golden-cheetah-users/TIXYuun6ntY/vkz5AIJ1BwAJ

**Comment by lavamann** [comment]
Dies funktioniert aber nicht !

**Comment by amtriathlon** [comment]
Please, use the forum to get help.

**Comment by lavamann** [comment]
i think this is the forum

**Comment by amtriathlon** [comment]
There’s a link to the forum in the 1st answer.

**Comment by lavamann** [comment]
so i've done everything as described in the link and also reinstalled GC.
It is still not working, so it must be a false code!!!!

**Comment by liversedge** [comment]
I just tried it and it works. Authorise with Strava via add account, then sync (make sure you set the date range to a range that includes some activity).

If the code was broken there would be a lot more reports of issues, believe me. We have a large user base. 

Make sure you are using the latest dev build from here:
https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/V3.5-RC2X

Also, the full release is due in a week or so.

**Comment by lavamann** [comment]
So i tried it again, nothing works. After login  in strava via Facebook and allow Golden cheetah, the fault "socket Operation (4)" appears.

**Comment by lavamann** [comment]
How should i set a Data Range?

**Comment by amtriathlon** [comment]
If you post in the users forum may be other user with the same problem can explain what he did i to solve it.
GitHub issues are used to track bugs and features only, as a FOSS we don’t have the resources to give case by case support here.

**Comment by lavamann** [comment]
Yes and according to many Users of the Forum it is a bug!
