### ISSUE TITLE
Release 3.5 - New user activity blank screen close button crashes app

### ISSUE THREAD

**Issue by bolieu541** [GoldenCheetah/GoldenCheetah#3295]
With the new release 3.5, I found a bug. I'm running MacOS High Sierra.

I created a new athlete to test the new software. I don't have any activities imported to the athlete profile. So, in the activity tab, I have the default Blank Screen explaining what to do to import a ride. I click on the "Don't show this next time" and then on the close button. It makes GoldenCheetah crash.

[ActivityBlankScreenCloseIssue_log.pdf](https://github.com/GoldenCheetah/GoldenCheetah/files/4055512/ActivityBlankScreenCloseIssue_log.pdf)

**Comment by amtriathlon** [comment]
I can reproduce the issue on Linux, the backtrace indicates it is a problem in Overview window.

**Comment by liversedge** [comment]
I am just fixing it. We will need to rebuild 3.5 binaries.
