### ISSUE TITLE
Strava sync not working after upgrade from 3.5 RC2 to official release

### ISSUE THREAD

**Issue by andyjw7** [GoldenCheetah/GoldenCheetah#3296]
Hi,

I updated from 3.5 RC2 to the official 3.5 build today, and can no longer get Strava sync to work. It worked fine for me in RC2.

I have tried the following with no luck:
1. Re-authorised Strava account through preferences
2. Deleted and re-added Strava account through preferences (also re-authorising)
3. Removed GC access from Strava and then deleted and re-added Strava through preferences

It seems that no one else has reported this so I am willing to accept I am being very dim, and the solution may be obvious, but I have searched here and the support forum and cannot find any information.

Import of weigh data from Withings still works fine, if that has any bearing!

I am running GC on a  MacBook Pro on Mojave v10.14.6.

**Comment by doubledadster** [comment]
I am having exactly the same issue.  Strava sync (incorrectly) shows "Uploads" but not "Downloads".  Same technical environment

**Comment by liversedge** [comment]
I have re-authorised and tested just now and it worked fine, it may be that Strava are rate limiting users from GC, with the new release there has been a lot of activity.

For info; the three tabs upload - shows local files, download - shows files that are on strava, synchronise shows files that need to be synced (i.e on one but not the other).

**Comment by amtriathlon** [comment]
Agree Mark, I just tested and received a rate limit error in the Linux console:
`error "Error transferring https://www.strava.com/api/v3/athlete/activities?before=1579143680&after=1576292480&per_page=30&page=1 - server replied: Too Many Requests"
`
To the users: please, use the forum to get technical support, this tracker is only for bugs and features.

**Comment by doubledadster** [comment]
Thanks @amtriathlon.  Most users do not have access to the Linux console, so it appears to us to be a bug.
Appreciate the hard work - I'll be patient with Strava!

<img width="459" alt="GClog" src="https://user-images.githubusercontent.com/36490790/72468084-f4876e00-37a1-11ea-8d41-d272d0885a21.png">

**Comment by liversedge** [comment]
I have requested an increase to the rate limit, lets hope the Strava devs are feeling generous :)

**Comment by bartvanandel** [comment]
> Agree Mark, I just tested and received a rate limit error in the Linux console:
> `error "Error transferring https://www.strava.com/api/v3/athlete/activities?before=1579143680&after=1576292480&per_page=30&page=1 - server replied: Too Many Requests" `
> To the users: please, use the forum to get technical support, this tracker is only for bugs and features.

I consider it a bug (or a much needed feature if you will) that GC doesn't inform users that data sync could not be performed. Currently it just looks like all went fine and there is no new data, while in fact, the request pretty much fails. If the Strava guys don't feel generous enough, could this be added?

**Comment by amtriathlon** [comment]
For the next version it could be revised, in the meantime you can check goldencheetah.log parallel to your Athlete’s folder

**Comment by lkgarrison** [comment]
I have been consistently hitting this issue the last 2-3 weeks on my Mac. Should this issue still be closed if users are unable to sync Strava activities?

I'd be happy to report what the logs say, but I haven't had any luck locating them so far.

**Comment by liversedge** [comment]
I test regularly to see if there are issues and they seem to be fine to me.
If you can locate the log (it is in the gc folder) with evidence we can look at this.
We have ~2000 users registered with Strava, if there was a global issue we would hear about it.

**Comment by doubledadster** [comment]
I am on a Mac, and the sync has been working perfectly for me recently.  Thanks Mark for asking for the increase to the rate limit.
