### ISSUE TITLE
.fit import with RR, RR is truncated at end

### ISSUE THREAD

**Issue by henolo** [GoldenCheetah/GoldenCheetah#3297]
With 3.5 Win64
Imported .fit from suunto movescount. Last ~7 minutes of rr-data is not imported. When the same .fit file is imported into firstbeat athlete the rr-da is there.
Quite strange, since this was working with 3.5RC2X with similar files.

**Comment by amtriathlon** [comment]
The FIT file importer has not changed from RC2X to release: https://github.com/GoldenCheetah/GoldenCheetah/commits/master/src/FileIO/FitRideFile.cpp

**Comment by henolo** [comment]
Ok, then something "new" might have appeared in the file, it is enclosed with wrong ending, it should be a .fit
[Move_2020_01_15_19_27_16_Running.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/4072833/Move_2020_01_15_19_27_16_Running.txt)
.
When looking in the GC data editor the duration of the three sheets are as follows:
STANDARD 00:24:38.000
EXTRA 00:24:39.000
HRV 00:17:56.550

**Comment by erikboto** [comment]
Just a thought, could it be that the file has dropouts of HRV-data?

Looking at the implementation in FitRideFile is looks as the times for the RR-intervals are just added to calculate at the timestamp part of the XDATA samples. So if there is missed RR-samples, I think that would lead to that all those missed samples will sum up to a gap at the end of the activity even if they are actually spread out during the activity.

I'm not sure if there's a way to actually get the times for the RR-intervals records from the fit-file, or if that data simple isn't in the fit-files.

**Comment by henolo** [comment]
Erik, there are "always" missing rr samples due to radio interference and other "obstructions" and this causes the following rr sample to ~double (or even triple if there is a cluster with two consecutive missing samples). In the file that I uploaded these are quite rare, about <1%, there are examples with about 10% that imports fine. Will try to run the dynastream fit2csv converter on this file to see if something odd occurs.

**Comment by henolo** [comment]
Took a look at the RR data with FFRT (fitFileRepairTool) and it appears to be at least one weird thing.

In the first 3 timestamps there are multiple quite large RR samples that adds up to much more than a second for each timestamp. So this is strange. After this start GC starts skipping samples regularly. Added this excelfile FFRT data in columns A,B,C and I put also the RR column from GC Data/HRV in column H and a simple diff in column E.

[FitFileRepairTool-FITRR-to-XL.xlsx](https://github.com/GoldenCheetah/GoldenCheetah/files/4124220/FitFileRepairTool-FITRR-to-XL.xlsx)
 
TimeStamp   UTC | ColNo | RRvalue
-- | -- | --
18:27:17 | 1 | 1,001
18:27:17 | 2 | 0,985
18:27:17 | 3 | 0,911
18:27:20 | 1 | 0,909
18:27:20 | 2 | 0,887
18:27:22 | 1 | 0,86
18:27:22 | 2 | 0,856
18:27:22 | 3 | 0,83

**Comment by erikboto** [comment]
Ah, the import of HRV values only works when there's an array of values in a record. When there is only one value in the fit hrv record it doesn't get added at all.

If you look at the excel sheet, all values with only a "ColNo" = 1 value are missing from the GC column. A quick look at the code in a debug session confirms this. Shouldn't be too hard to fix.

**Comment by erikboto** [comment]
With the fix proposed in the PR I get the same number of HRV records in GC as in the dump from FitFileRepairTool as @henolo posted above.

**Comment by amtriathlon** [comment]
It looks like the R-R data now goes to the end:
![Issue3297](https://user-images.githubusercontent.com/1444784/73313326-acd4fd80-4209-11ea-84ab-ec0e7a36a977.png)
Thanks Erik, I will merge it adding the test file
