### ISSUE TITLE
GC 3.5 crashing in Trainmode while connecting to ANT+ MacOs

### ISSUE THREAD

**Issue by mondoshiwan** [GoldenCheetah/GoldenCheetah#3303]
GC 3.5 Mac OS Version is crashing often while trying to connect to the ANT+ device in Trainmode.
It's a bit of luck not running into it. If the connect is done without a crash, everything is running fine. For more investigation here is the latest log:

[GoldenCheetah_2020-01-18-125402_MacBook13.crash.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4080625/GoldenCheetah_2020-01-18-125402_MacBook13.crash.zip)

**Comment by amtriathlon** [comment]
Travis-ci generates automatically a build using an updated version of libusb (1.0.23), can you test if that fixes this problem?
That build can be downloaded from: https://transfer.sh/J6MmS/dev-prerelease-branch-master-build-3378.dmg

**Comment by mondoshiwan** [comment]
Unfortunately not. With that build GC always crashes even when you switch from activity tab to the train tab. At the prefs i turned off the autoconnect to ANT+ to avoid this with the 3.5 build, but with build 3378 it will crash while switching to train mode.

[GoldenCheetah_2020-01-19-121320_MacBook13.crash.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4082560/GoldenCheetah_2020-01-19-121320_MacBook13.crash.zip)

**Comment by PhilGrunewald** [comment]
I had the same issue with MacBook and 3.5 (crashes during training mode recording, shortly after comms with Tacx Neo failed).
For me this new version seems a lot more stable in Train mode. The new text window and 'failed to connect Ant+' message window are helpful feedback. I tried turning connected devices on and off and no crashes occurred. When disconnecting the Ant+ dongle no errors are thrown and it doesn't reconnect until toggling the connect button with the power symbol.

I did however get a crash in Activities, when attempting to delete the activity. After restart that worked fine.

The main frustration with crashes is lost data. Could training data be auto-saved during training, say every 30 seconds? The files are quite small and it is fair to assume that most people want the data saved anyway.

**Comment by amtriathlon** [comment]
> Could training data be auto-saved during training, say every 30 seconds? The files are quite small and it is fair to assume that most people want the data saved anyway.

During training data is saved to disk each second to a file with yyyy_MM_dd_hh_mm_ss.csv name in records folder, on session end this file is the one offered for import, but you can import it manually after a crash.

**Comment by amtriathlon** [comment]
> Unfortunately not. With that build GC always crashes even when you switch from activity tab to the train tab. At the prefs i turned off the autoconnect to ANT+ to avoid this with the 3.5 build, but with build 3378 it will crash while switching to train mode.

This is likely due to the experimental enabling of Qt5 video in that build, I disabled video for the new builds, the last on can be downloaded from: https://transfer.sh/W6iXh/dev-prerelease-branch-master-build-3383.dmg

**Comment by mondoshiwan** [comment]
>> Unfortunately not. With that build GC always crashes even when you switch from activity tab to the train tab. At the prefs i turned off the autoconnect to ANT+ to avoid this with the 3.5 build, but with build 3378 it will crash while switching to train mode.

> This is likely due to the experimental enabling of Qt5 video in that build, I disabled video for the new builds, the last on can be downloaded from: https://transfer.sh/W6iXh/dev-prerelease-branch-master-build-3383.dmg

no crashes anymore with build 3383! Tried to trigger a crash like Phil with dis- and reconnecting the ANT connection or pulling off the ANT+ Stick, but no way… runs flawless ;-) on a MacBook 10.12.6

**Comment by vlisjak** [comment]
> This is likely due to the experimental enabling of Qt5 video in that build, I disabled video for the new builds, the last on can be downloaded from: https://transfer.sh/W6iXh/dev-prerelease-branch-master-build-3383.dmg

transfer.sh link returns "Not Found" - could you share again pls?

**Comment by amtriathlon** [comment]
Transfer.sh links are temporary, this one is similar to the official build but it uses libusb1.0.23, it should work on High Sierra or later macOS:
https://transfer.sh/6j6OA/Goldencheetah_v3.5_64bit_MacOS-libusb1.0.23.dmg
Please give us feedback if you use it.

**Comment by vlisjak** [comment]
> Transfer.sh links are temporary, this one is similar to the official build but it uses libusb1.0.23, it should work on High Sierra or later macOS:

Works perfectly! Thanks

**Comment by tjdunnigan** [comment]
> Travis-ci generates automatically a build using an updated version of libusb (1.0.23), can you test if that fixes this problem?
> That build can be downloaded from: https://transfer.sh/J6MmS/dev-prerelease-branch-master-build-3378.dmg

Works great for me. Catalina 10.15.3, MacBook Pro, USB-C ports with conversion dongle.

**Comment by PonessM** [comment]
Please can you repost a updated link. A time ago, you had release two different Build for mac, one based on the libusb 1.0. Now a had upgraded to the 3.5 Release, and the Trainer is not recognized any more. 

Thank you, for your great work.

**Comment by amtriathlon** [comment]
Currently I can’t, transfer.sh is having problems.
The alternative would be to upload to GitHub, but I’m not sure where would be a good place.

**Comment by PonessM** [comment]
> Currently I can’t, transfer.sh is having problems.
> The alternative would be to upload to GitHub, but I’m not sure where would be a good place.

That is a good question. Maybe in Form of an experimental release. But this can be a little bit confusing, to other member. As an alternative, maybe you can publish a instruction how to build with libusb 1.0 at local and/or using travis-ci from a copy of the 3.5 branch. The install-mac only link to the old Version.

**Comment by amtriathlon** [comment]
This one is the last I uploaded, similar to the official build but with libusb1.0.23, it should work on High Sierra or later macOS: https://transfer.sh/ou67p/GoldenCheetah_v3.5_64bit_MacOS_libusb-1.0.23.dmg

**Comment by PonessM** [comment]
After some Test i can say the following:
The ANT Interface is running very good with libusb-1.0. But the BtLE Interface does not found any Devices anymore.

HW Config:
 Modellname:	MacBook Pro
 Modell-Identifizierung:	MacBookPro13,2 (late 2016, 4x Thunderbold 3)
 CPU:	Dual-Core Intel Core i7
 CPU-Speed:	3,3 GHz
 RAM:	16 GB
Graphic: Intel Iris Graphics 550 1536 MB
USB-Adapter: Apple USB-C to USB-A/HDMI/USB-C, Hardware Revision 1

SW-Config: MacOS Catalina, 10.15.3

**Comment by amtriathlon** [comment]
Beware BTLE pairing has changed in v3.5 and it is different from ANT+: in the pairing step Add Device Wizzard just inform which sensors are supported but they are not looked for at that point.
Only when you start the device (selecting it in the left sidebar and using the red Start button on the bottom bar) the BTLE sensors are searched and activated so you should view the dials displaying the corresponding data.

**Comment by liversedge** [comment]
I'd add that catalina has new device protection that may prohibit unsigned binaries from accessing bluetooth devices -- check dmesg for any warnings or errors.

**Comment by willtaylor** [comment]
> This one is the last I uploaded, similar to the official build but with libusb1.0.23, it should work on High Sierra or later macOS: https://transfer.sh/MLU2K/GoldenCheetah_v3.5_64bit_MacOS_libusb-1.0.23.dmg
> Feedback, including hw and sw config, is welcome.

The link seems to have expired again.  Would you mind publishing it again?  Is there a branch or tag that one could use to clone the repo and build their own copy of this version?

**Comment by amtriathlon** [comment]
>Is there a branch or tag that one could use to clone the repo and build their own copy of this version?

You can use https://github.com/GoldenCheetah/GoldenCheetah/commits/release_3.5.0 since the changes to source code to enable libusb-1.0 are included (https://github.com/GoldenCheetah/GoldenCheetah/commit/c284885f8b87b52c7c0990683e86f80da5bdf5be), but you need to enable them in gcconfig.pri at build time.

> The link seems to have expired again. Would you mind publishing it again?

I uploaded GoldenCheetah_v3.5_64bit_MacOS_libusb-1.0.23.dmg to https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/V3.5 as an alternative build for macOS, since users feedback indicates it solve this issue, and to avoid the need to continuously update the link, which is a PITA.

**Comment by brianp** [comment]
> I uploaded GoldenCheetah_v3.5_64bit_MacOS_libusb-1.0.23.dmg to https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/V3.5 as an alternative build for macOS, since users feedback indicates it solve this issue, and to avoid the need to continuously update the link, which is a PITA.

Just chiming in that this build also fixed the problem for me. Thanks!
