### ISSUE TITLE
file loading V3.5

### ISSUE THREAD

**Issue by Alscuppy** [GoldenCheetah/GoldenCheetah#3304]
installed V3.5 2020 over V3.5 dev1903 on windows 32 

Athlete with large activities file would not install

After long "upload" updating a files with 882 entries the program crashed.

smaller athlete files loaded OK as did a much reduced version of the larger file

it seems the CPU/memory of the laptop gives up at a certain point in the load

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/wiki/GoldenCheetah-memory-consumption-and-recommendations
