### ISSUE TITLE
Strava sync broken on 64bit app of windows

### ISSUE THREAD

**Issue by Overcomb3** [GoldenCheetah/GoldenCheetah#3305]
When I use GC3.5 64bit for windows I couldn't sync Strava, so I installed 32bit app it works well.
Are there any problems only for 64bit app?

**Comment by amtriathlon** [comment]
No, but they depend on different operating system DLLs and likely there is a problem with some of the 64bit ones on your system.
There is a pinned thread in users forum to discuss this: https://groups.google.com/d/msg/golden-cheetah-users/TIXYuun6ntY/vkz5AIJ1BwAJ
