### ISSUE TITLE
 python chart directory set to root in OS X Catalina?

### ISSUE THREAD

**Issue by ChristopherShort** [GoldenCheetah/GoldenCheetah#3316]
Golden Cheetah: 3.5 (Build id 39990)
OS: OS X (Catalina)
Python: 3.6.4

From the console, ```os.getcwd()``` returns ``` '/' ```

This may explain the error returned when I tried the first example from [Working with Python](https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Working-with-Python).

The error at the end of the traceback is: 

```
File "~/Users.../goldencheetah/lib/python3.6/site-packages/plotly/io/_html.py", line 527, in write_html

with open(file, "w") as f:
OSError: [Errno 30] Read-only file system: 'temp-plot.html'
```

(apologies for shortened typing, it doesn't appear copy is enabled in the console)

Perhaps I've missed a setting for the python chart directory?  

cheers
Chris 
ps - first time using GC, seems very powerful, and relatively easy to figure out - thnx all

**Comment by rb83421** [comment]
I like to be more specific where to write files see first example update (should this be changed on the wiki)?

```
##
## Python program will run on selection.
##
import numpy as np
import plotly
from plotly.graph_objs import Scatter, Layout
import tempfile
import pathlib


## Retrieve power and cadence
xx = np.asarray(GC.series(GC.SERIES_WATTS))
yy = np.asarray(GC.series(GC.SERIES_CAD))

# Define temporary file
temp_file = tempfile.NamedTemporaryFile(mode="w+t", prefix="GC_", suffix=".html", delete=False)

## Prepare Plot
plotly.offline.plot({
    "data": [Scatter(x=xx, y=yy, mode = 'markers')],
    "layout": Layout(title="Power / Cadence")
}, auto_open = False, filename=temp_file.name)

## Load Plot
GC.webpage(pathlib.Path(temp_file.name).as_uri())
```

**Comment by ChristopherShort** [comment]
+1 for using the standard python approach to managing temp files across OS's in wiki examples.

That resolved my issue.

thanks
Chris

**Comment by amtriathlon** [comment]
We are not setting the current directory explicitly for Python embedding, so it is the GoldenCheetah program initial working directory, which is assigned by the operating system and can depend on how the program is launched. I updated the wiki example to avoid this issue.

**Comment by ChristopherShort** [comment]
Not sure it's doing that either - to get the absolute path of the current directory `Path().absolute()`  returns `/` (as a cross check against `os.getcwd()` used above)

But root is definitely not writeable in Catalina.  

On the other hand, I'm not sure what GC's initial working directory is (or how it handles temporary files)

thnx for updating the wiki.

cheers

**Comment by amtriathlon** [comment]
See https://stackoverflow.com/questions/4521151/mac-app-default-working-directory
On Linux starting the program from the command line sets the initial working directory to the current directory, Windows has the option to set the initial working directory at the shortcut, etc.
To write a portable script better to use standard libraries for temporary files.
