### ISSUE TITLE
GC V3.5 build 3991 Mac OS many invalid data spike candidates now being flagged

### ISSUE THREAD

**Issue by AlanGraham0** [GoldenCheetah/GoldenCheetah#3318]
Issue tracker is **only** for Bugs and Features, before to open a new issue please read the Contributing document (link at the right), and use the forums if you need help or technical support.

**Comment by AlanGraham0** [comment]
Recently installed V3.5 from the dmg image.  I've noticed that there are many (20-30) per hour data spike candidates appearing in the anomaly window.  For instance, finished a strava SST ride on a tacx new smart in erg mode.

For instance, 
19:43 230 watts 86 cadence
19:44 243 watts 88 cadence  Data spike
19:45 255 watts 90 cadence

Can't attach fit files, if anyone works on this, please get in touch for more details.

**Comment by AlanGraham0** [comment]
I'm confused by stating this is a forum question.  This behaviour was introduced by this version.  The same rides in the previous version did not have any data spike candidates

**Comment by amtriathlon** [comment]
So the behavior has changed, not necessarily it is a bug, it seems a good topic to discuss in the forum.

**Comment by amtriathlon** [comment]
Default values for Fix Power Spikes were changed and the new max power value is too low for most users, it can be changed in https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Preferences_Data-Fields#processing, but we should augment the default value, IMHO.

**Comment by ericchristoffersen** [comment]
The core of that recent change was to fix issue where variance filter was broken. Previously if single sample was found to exceeded variance the filter loop exited and it would process no subsequent samples... Variance had to be kept stupid high or filtering was truncated, so fix spikes became a bandpass and only threshold mattered.

The new behavior recognizes spikes as being above threshold (today default 200) AND above variance (today default variance is 20).

What I find on my own trainer is that power spikes occur at all intensities and can be both up and down, the key is how much variance you wish to tolerate in your power readings.

I'm not wedded to any particular value but 200/20 didn't seem too horrible to me. I recommend you all play around with the current settings and see what works for you. Lets change the defaults if there is an obvious consensus. I suspect if anything it would be the variance default that should increase.

**Comment by amtriathlon** [comment]
Since it has not been more complains about this and it is just a matter of default values, I'm closing this.
