### ISSUE TITLE
Brake error on Tacx Flux S and 2

### ISSUE THREAD

**Issue by AnHaug** [GoldenCheetah/GoldenCheetah#3319]
With GC 3.5 and Tacx Flux S (newest firmware) the video display shows ("Bremsenfehler" - brake error). Workouts (non video) are not working meaning brake is not controlled by GC.

Platform: Windows 10

**Comment by amtriathlon** [comment]
In the wiki FAQ there are some guidelines for troubleshooting and you can search the users forum where you will find mixed experiences and, eventually, ask for help.
This doesn’t seem to be a GC bug nor something we can give technical support here.

**Comment by amtriathlon** [comment]
It seems to be a pattern with Tacx Flux using newer firmware, this is how it looks like according to the screen capture posted by another user in users forum:

![brake-fault](https://user-images.githubusercontent.com/1444784/74938546-f6f66c80-53cc-11ea-8705-8566f7803b41.jpg)

NB1: currently Trainer status is not displayed on notifications window, only on Video when Video Overlays are active, and this is available only in Windows, so it will be unnoticed on macOS/Linux.

NB2: since the Trainers reporting this error are working with other training applications I will reopen this as a feature request to support this device waiting for a developer with access to a Tacx Flux willing to work on this.

**Comment by cyrusso** [comment]
Having the same issue with my new Tacx Flux S trainer, used to train on GC with my previous trainer Tacx Vortex Smart, but it had an issue and needed replacement. I've just set the new gear and was looking forward to run GC but it doesn't control the brake/resistance. I'm looking forward for device support on a new version of GC

**Comment by amtriathlon** [comment]
Based in [this experience with other Tacx trainer](https://groups.google.com/d/msg/golden-cheetah-users/wFsMMiKYi5s/HX2LEKFCDQAJ) I would suggest to disable bluetooth on all devices (Notebook, Tablet, Cell Phone) around the trainer and try again.

**Comment by vonmoock** [comment]
It is a problem with all the Flux modells S and 2. it has nothing to do with bluetooth decices. Wont work in a Garage where there is no other equipment than the trainer and a PC-Tower without bluethoot and with a Ant+dongle. The problem persitst up to the newest update from 12/14 (when I remember right the date). And it affects not onlythe rlv-vodeos but also the selfdesigned or not workouts of GC. I have no idea of coding, but if it helps sombody to betatest I am on your side with a Win 10 and Flux 2.

**Comment by amtriathlon** [comment]
Thanks for the confirmation.
This issue is labeled as device support request since, until a developer has direct access to one of such devices to understand and implement the changes required to support them, we consider these trainers not supported.
In the short term realistic options are to look for another software if you want to use this trainer or a different trainer if you want to use GC.

**Comment by peret2000** [comment]
Maybe I'm adding more confusion. I have a Tacx Flux S, and it works fine with GC using BTLE. I experienced the brake error issue when using CYCPLUS ANT+ dongle.
So, according to my experience, the problem is neither the trainer not GC, but CYCPLUS dongle

**Comment by amtriathlon** [comment]
That's interesting, the CYCPLUS is a no go, it has been confirmed in the forums and we have documented it in the wiki.

Regrettably several users refuse to read the wiki and to use the forums for support.

**Comment by vonmoock** [comment]
Mine is an Garmin Ant+ Stick, Will try the bleutooth alone and report.

**Comment by amtriathlon** [comment]
Beware our BTLE support for TACX only handles set gradient, so slope mode only, not erg support yet: Fue bastante evidente este año que, entre la economía y la salu

**Comment by peret2000** [comment]
I can test it, of cpurse. I have never used erg mode, just slope mode, but I can test it with BTLE if you make those modifications you have in mind, and report back. Previously, I will test erg mode with current binary to notice the problem. Regards

**Comment by amtriathlon** [comment]
Here you can find a Windows installer with erg mode set target watts enabled for Tacx ANT+ over BTLE: https://ci.appveyor.com/project/Joern-R/goldencheetah-knhd8/builds/37021689/artifacts

**Comment by peret2000** [comment]
Oops! Sorry, I am using Ubuntu. With windows I never could put it to work in a reliable way. If you tell me the commit Id, perhaps I can get the binaries (from travis CI), I read something in the forum about that; although maybe they persist for 24 hours. In such case, I think I can manage to compile from the sources, so, with commit Id I could do that, unless you prefer to use specific precompiled settings, different from the ones in travis CI

**Comment by peret2000** [comment]
I think I have found it: #3736
So, I will test with that build

**Comment by vonmoock** [comment]
Thanks you so mich! At a First glance gc is working perfect with ble 4.0 in erg! Have a healthy 2021! --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 28.12.20, 17:59 schrieb Alejandro Martinez <notifications@github.com>:

   
  Here you can find a Windows installer with erg mode set target watts enabled for Tacx ANT+ over BTLE: https://ci.appveyor.com/project/Joern-R/goldencheetah-knhd8/builds/37021689/artifacts

**Comment by peret2000** [comment]
I agree: it is working perfectly. With a previous build, nothing happens when pressing the 'up' or 'down' arrows in Erg Mode training. With this build, you can feel as it hardens or softens pedalling. Thanks!

**Comment by amtriathlon** [comment]
Perfect, I will merge it for inclusion in the next dev build. Thanks!
