### ISSUE TITLE
Update jQuery to 1.12

### ISSUE THREAD

**Issue by Ramoonus** [GoldenCheetah/GoldenCheetah#3334]
update file: src/Resources/web/jquery-1.6.4.min.js to jQuery 1.12.4
https://code.jquery.com/jquery-1.12.4.min.js

**Comment by Ramoonus** [comment]
preferably 3.4
https://code.jquery.com/jquery/

**Comment by amtriathlon** [comment]
For what purpose?

**Comment by Ramoonus** [comment]
staying within the 1.x branch should not impact the codebase negatively

**Comment by amtriathlon** [comment]
It was not a theoretical but a practical question.

The only part of the code using it (RideWindow) is temporarily disabled since their migration from Qt WebKit to Qt WebEngine still is pending.

Do you plan to work on that?

**Comment by Ramoonus** [comment]
I`m not going to work on WebKit --> WebEngine
atleast not in this ticket

**Comment by amtriathlon** [comment]
So lets close this.
