### ISSUE TITLE
Drag and Drop workout and GPX files doesn't import them

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#3337]
After the introduction of the ability to use GPX files as workouts, when GPX files are dropped onto GC, workout import is triggered (instead of activity import as before), and it fails with unrecognized file type message.
Current workaround is to import via the corresponding menu option for each case.

**Comment by liversedge** [comment]
I'm not sure this is a bug, so much as an edge case?
I guess we could decide what to do based upon the active view?

**Comment by amtriathlon** [comment]
The bug  part is the import fails.
To decide what to import based on active view is a good idea now the intersection of valid formats is not empty.

**Comment by amtriathlon** [comment]
It is not particular to GPX files nor was introduced recently, it looks like a long standing copy&paste bug:
https://github.com/GoldenCheetah/GoldenCheetah/blob/835f7cff92c43cdeff490325e2dbc93a4b3257ba/src/Gui/MainWindow.cpp#L1315
`filenames` should be `workouts`

**Comment by amtriathlon** [comment]
Fixing this allows to import any supported workout file by drag and drop, but I agree to limit this to when Train is the active view to avoid the conflict in case of GPX files.
