### ISSUE TITLE
GC download from ErgDB produces workout which cannot be executed in v3.5

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#3338]
The .erg2 workouts are displayed correctly on Workout Editor but any attempt to execute them is stopped immediately.

Current workaround is to use the Save As... button on Workout Editor to save the as .erg

An alternative workflow is to download from ErgDB web to .erg files and import them.

**Comment by smann004** [comment]
[proposed Label] "Error - Insufficient valid data in file when starting workout downloaded from ErgDB"
It took me some time to find this bug but I believe it is the one that is preventing me from starting to use GC with anything but the standard "Manual Erg Mode" and "Manual Slope Mode". Once I watched a video to figure out how to make the workout editor appear I was then able to follow the workaround shown above "Current workaround is to use the Save As... button on Workout Editor to save the as .erg"
Thanks
![GC](https://user-images.githubusercontent.com/5266534/87237173-a05bf000-c3b8-11ea-93ce-aa38adc52908.png)

**Comment by amtriathlon** [comment]
It is already fixed if you use any v3.6 build, for v3.5 users we added an entry in FAQs to the wiki

**Comment by smann004** [comment]
Thank you for your work and for reminding me that as a user of open source I'm a member of a community and not a paying customer. I am using the latest dev. build now without issue.
