### ISSUE TITLE
Segments disappear

### ISSUE THREAD

**Issue by Mountaingoat1** [GoldenCheetah/GoldenCheetah#3345]
First of all, thanks for an awesome software!! 

I'm using Zwift, and creating segments for different hills and other kinds of segments there. Once I create them in GC the segments are recognized for the activities where I passed them, but next time I open Golden Cheetah some of them are gone. For example i try to log a downhill segment, and this one seems tricky to keep. I always save when I exit GC. Any ideas? 

Btw, would it be an idea to have some sort of overview for all the segments created?

**Comment by amtriathlon** [comment]
Segments are saved to config/routes.xml in your athlete's folder, you can check there if they are present. There is already an open feature request to list all segments: https://github.com/GoldenCheetah/GoldenCheetah/issues/2908

**Comment by Mountaingoat1** [comment]
I checked right now and the missing segment is in the routes.xml.

**Comment by amtriathlon** [comment]
So they are saved, which is the problem then:

1. they are not recognized in the same ride after restart?
2. or they are not recognized in similar rides?

**Comment by Mountaingoat1** [comment]
Not in the same ride or other rides, at least those that I checked and I know contains the segment. It seems that uphill segments work better though.

**Comment by amtriathlon** [comment]
Ok, let's then consolidate this with the open issue on segment identification https://github.com/GoldenCheetah/GoldenCheetah/issues/3192
