### ISSUE TITLE
Tacx Flux FE-C ERG Problems

### ISSUE THREAD

**Issue by scouseman** [GoldenCheetah/GoldenCheetah#3348]
Hi,
I am running GC 3.5 Build 3991 x64 on windows 10.
I read the WIKI & FAQ "Troubleshooting TacX Device FE-C connection" and I turn off Bluetooth on all nearby devices.
I can control the resistance with Tacx software, Zwift, Trainerroad, PerfPro, etc
I add Devices with FE-C and select unused for all other items, it's ok, in training view I can see all info power, cadence, speed, etc... but GoldenCheetah doesn't control the resistance of my smart trainer.
I have also tried pairing FE-C on different channels
The manual slope mode does not work either.
I have made sure no other software is running in the background which could be interfering.
screenshot from add device wizard: [https://i.ibb.co/23Cmzwg/Capture.jpg](url)

Here is a link to the erg file [https://pastebin.com/RNGSHaRW](url)
And here is a link to the GC output file [ https://pastebin.com/3ZUD1yuB](url)
Here is the contents of the trainer config file [https://pastebin.com/djgKBWNJ](url)

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/issues/3319
