### ISSUE TITLE
Cleanup changes for my numerical code

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3350]
There were a few things bugging me that I didn't change before. Now I've had time to test I'd like to make these changes:

- Fix the acceleration calculation in bicyclesim (dvdt) to use instant acceleration instead of slope between two v points. There is a numeric difference from this change but its better now.
- Cache spline coefficients - no numeric change.
- A few trig identities - no numeric change.

**Comment by ericchristoffersen** [comment]
I think this is ready to go. Can someone review?

**Comment by liversedge** [comment]
Will do. Thanks!

**Comment by ericchristoffersen** [comment]
Closing. Was merged march 11.
