### ISSUE TITLE
Bikestress/TSS

### ISSUE THREAD

**Issue by nanainmk** [GoldenCheetah/GoldenCheetah#3356]
Issue tracker is **only** for Bugs and Features, before to open a new issue please read the Contributing document (link at the right), and use the forums if you need help or technical support.
I have just updated to GC 3.5 and i do not have the ability to manually adjust the bikestress, IF and NP amounts as it defaults to zero every time i try to correct them

**Comment by amtriathlon** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/issues/3269
