### ISSUE TITLE
Create Average Total TE and PS values in Ride Summary

### ISSUE THREAD

**Issue by ph4r** [GoldenCheetah/GoldenCheetah#3357]
I see from code in BasicRideMetrics.cpp that suggests you have support for Power Meters that produce Left and Right independent values, but perhaps not for single-sided power meters which only produce one value such as the single-sided Stages v3 Power Meter I'm currently using.  I would like to see this value on the Ride Summary or Overview Charts.  If it exists already somewhere else, please let me know where.

**Comment by amtriathlon** [comment]
In addition to Left/Right TE and PS there is a Combined PS field in the FIT specification, which is imported as XData in the Edit/Extra tab, if present in the file.
