### ISSUE TITLE
Edit python script outside GC?

### ISSUE THREAD

**Issue by PhilGrunewald** [GoldenCheetah/GoldenCheetah#3358]
I love the Python Chart feature, but don't like editing scripts inside GC. Is it possible to edit them externally (e.g. with vim or other)? I cannot find where the files are stored.

**Comment by liversedge** [comment]
They are in the chart attributes. Use cut and paste?

**Comment by rb83421** [comment]
Hi Phil,

You also might have a look into this project:
https://github.com/rb83421/GoldenCheetah_Python_Chart_Wrapper


Op ma 24 feb. 2020 18:56 schreef Phil Grunewald <notifications@github.com>:

**Comment by liversedge** [comment]
That's interesting !

Lemme know if some hooks in GC would help make it slicker.

Also, I've been working on an API to use to plot on a qt chart, its master now, looks like this:
![screenshot](https://user-images.githubusercontent.com/142876/75188744-9789bb00-5744-11ea-8705-04228b6c2355.png)

It uses qt charts and supports pie, bar, scatter and line charts.

**Comment by rb83421** [comment]
Hi Mark,

Nice to see your progress.

I opened an discussion on the forum to continue discussion where it should be.
[GC feature request / some hooks in GC would help make it slicker](https://groups.google.com/forum/#!topic/golden-cheetah-developers/o_SB7ZvFdv8)

**Comment by liversedge** [comment]
Good idea. Will respond tomorrow, some big topics there !
