### ISSUE TITLE
RideFile resample seconds limit of 25 hours is Too Small

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3359]
RideFile::resample discards samples if the total ride time is more than 25 hours:

        // yuck! nasty data -- ignore it
        if (p->secs > (25*60*60)) continue;

I'm trying to accumulate a long trip into a single gpx and this totally breaks it. Many adventure races are longer than that.

Can we please use a bigger number? I vote <0 and > 1 year in seconds should be discarded.

**Comment by amtriathlon** [comment]
According to https://github.com/GoldenCheetah/GoldenCheetah/issues/2056 it seems there are other issues with activities longer than 24hr, but I have not tried nor looked at in detail.

**Comment by ericchristoffersen** [comment]
When I was looking for what was blocking me I found a bunch of crazy time stuff in the charting code.

The good news is that the charting I looked at seemed fine once I recomputed distance and then regenerated speed from distance.

**Comment by liversedge** [comment]
Sorry, but 24hrs is a limit for multiple reasons, this will introduce too many regressions for an edge case that has only been raised a couple of times in the last 14 years.

**Comment by ericchristoffersen** [comment]
Some arguments for raising the limit, or at least removing this particular filter:

- The limit manifests as a silent failure that today simply corrupts data. when merging two big rides the points with high time are thrown out. Then later points are merged into the end. It makes a mess that sucks to undo. Note this is a silent corruption.

Now that I have constructed a continuous week-long ride I seem to be able to use well it in gc:

- Gc doesn’t stop me from importing or loading it or exporting it, which means any issues you’re concerned about are exposed today to users.

- Gc seems to work fine with it, worst I see is that except some of the charting is really slow. The various edit and activity actions seem to work well.

If goal is to reject long files and prevent people from acting on them then we can do that, but not a kind approach to fail here.

I think better approach is to allow it and fix what is actually wrong in gc, or at least harden against it.

My use case: I had to create a single gpx for my 2 month Bikepacking trip, then export to Kml to make a movie with google earth pro. The gps utilities I found that should do this were either broken or needed to be purchased. I was really happy once this was fixed.

**Comment by liversedge** [comment]
I agree we should harden against it. I thought the import wizard refused files >24 hours. There are a few other places that should do the same (e.g. ridefilecache compute).

**Comment by ericchristoffersen** [comment]
What is the actual reason for the time limit? Other than you not thinking its important. It can't be perf because there is no limit today on sample count. Something somewhere that is too hard to fix? I do see inconsistency in how time is handled through the product, is that where the dragons live? Maybe we could go through and fix it?

**Comment by liversedge** [comment]
Because there are assumptions across the code that it is less than 24 hours, from displaying time values through data structures and algorithms. Allowing longer will definitely introduce regressions that are just not worth it for an edge case.
