### ISSUE TITLE
[Old 289] Allow user-defined coefficients for Virtual Power

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#337]
As suggested by Clint Westhoff:
In the “virtual channel” box it would allow for a lot more customization if you had a “custom” option for the virtual power. Maybe when it was selected a box could pop up asking for wheel/tire circumference so that speed can be calculated and then giving the user the opportunity to enter the other variables for the third order polynomial manually. That way anyone with a trainer could have virtual power calculated, so long as they know their power curve, even if their trainer isn’t on the dropdown list.

CustomVPower.png - Custom virtual power UI (3.5 kB)   Darren Hague, 03/28/2011 05:06 pm
Add
Related issues

History
#1 Updated by Mark Liversedge over 1 year ago

Target version changed from 3.0 to 3.1

Deferred to 3.1 since it is a minor feature that will require a fair amount of coding and testing. Or more succinctly, lets put in the 'do it later' pile.

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/pull/3410
