### ISSUE TITLE
RideWithGPS upload doesn't work since API has changed

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#3371]
The origin seems to be they have changed their API, here is the debug output:
```
[Cloud/RideWithGPS.cpp:81 open] RideWithGPS::open
[Cloud/RideWithGPS.cpp:103 writeFile] RideWithGPS::writeFile(2020_02_27_16_17_14.json)
[Cloud/RideWithGPS.cpp:178 writeFileCompleted] RideWithGPS::writeFileCompleted()
[Cloud/RideWithGPS.cpp:182 writeFileCompleted] reply:<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty/1.15.8.2</center>
</body>
</html>

```
The crash is due to the use of root pointer without NULL checking in: https://github.com/GoldenCheetah/GoldenCheetah/blob/a86b0e9b74882ed83af3eb9293d97331ea95a500/src/Cloud/RideWithGPS.cpp#L195

Reported at the forum: https://groups.google.com/d/msg/golden-cheetah-users/xjRTx7pS5h8/GE-hrVujBAAJ

It looks like they have changed the authorization scheme, so it is not just an entry point change: https://ridewithgps.com/api

**Comment by grauser** [comment]
It seems we have to implement version2 of the RWGPS API.

**Comment by liversedge** [comment]
Details for the api are here (for some reason I could not find when looked at the weekend):
https://ridewithgps.com/api

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/c701c8a5101f22ef467406ba0b569f87b8ab1435

**Comment by liversedge** [comment]
does anyone care about this, wondering if its simpler to just remove support for ridewithgps ?
