### ISSUE TITLE
Allow FixGPS to smooth altitude when there is no lat/lon present

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3373]
This thread a user has a workout that needs altitude smoothing when there is no lat/lon data.

https://groups.google.com/d/msg/golden-cheetah-users/5d2YunLhpW0/y3nx06MNBwAJ

Currently FixGPS refuses to run in less there is lat/lon data.

Issue is fixgps should be able to perform altitude smoothing even when there is no lat/lon data present.

**Comment by amtriathlon** [comment]
Complement of https://github.com/GoldenCheetah/GoldenCheetah/issues/3320
