### ISSUE TITLE
GC.webpage in current git master

### ISSUE THREAD

**Issue by MeisterP** [GoldenCheetah/GoldenCheetah#3375]
Hi,
I wanted to try the new UserChart feature and installed the current git master. So far so good. Great work :)

Unfortunately, the old python charts don't work any more. The html file is still generated, but `GC.webpage()` doesn't display anything. This is on Linux, compiled from source.

I know this is still work in progress. Thought I'd give you a heads up anyway ;)

**Comment by liversedge** [comment]
Go to chart settings and set to show webpage.

**Comment by MeisterP** [comment]
> Go to chart settings and set to show webpage.

the checkbox is checked and it still shows nothing

**Comment by liversedge** [comment]
Will fix, if you uncheck and check it gets there, but the logic is a mess.
