### ISSUE TITLE
Generic Chart Enhancements

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#3378]
Some additional enhancements that should be added to the generic chart before releasing 3.6
* older charts adopt similar (as possible) UX (e.g. legend)
* compare mode
* interval selection
* render as table
* series group - faceting
* bars and lines on line chart
* histogram on bar chart
* panning and zooming
* group by week/month/year
* annotations - shapes/line markers/notes
* augment series with z,d,t values to show on hover (e.g. datetime of point highlighted)
* units/scaling/decimal places on axis/markers
* ~~fill curves~~ df2d436a0216f1a5830f1be85692f42448df6021 / ribbon / area curves
* shading / background
* ~~use color config (CPOWER etc) from themes~~ 176226545ffa9d3f2f5ec2e1879a2a5e6780538f
* animation
* legend flow layout
* quick options from legend (color)
* show stats in legend when selection active

Datafilter supporting enhancements
* ~~working with dates (week, day, year)~~ 73f11db57810f29df835783279430ba340a46e2d adc9fc84cdc694c6a5b7efbee408ed6a9277f8c3
* ~~interpolate time series~~  5772f6fd2f769267d57bcd18d095131d260217c6
* ~~resample time series~~  47e67f4d379fdc6fa15a803bef9238c97248151d
* ~~filtering meanmax efforts~~ ce89389451676b65e1c09e990d4783c36b7c0a1d
* ~~xdata samples~~ 96b4cacec90bd9cad4a7bd5025326a5859b72b3f
* ~~wbal data~~ 21415379af2d5b49b5b3629bd203cd2936cfdd89
* ~~measures~~ 7a0ed0792b53b8b3090091cb3703cf70ef776479
* ~~access performances and tests~~ 6c318059818eb6a002d84beb118c8c954c478196
* ~~reference other curve vectors in a chart e.g. curve(series, y)~~ bda728696f61ef877511c95129fedd1df2ea3f77
* ~~aggregating - as per the R function~~ 021ecda647ff6f6e0074f4fbd444df1630c0a603
* ~~binning~~ f261a76b9ed7a4f4662cfbb1fea5350c549af38d 

Some nits that need resolving
* ~~series cannot be reordered~~ b7a56a9dd9a3a35d94f9c48774acd2c95d8d0df1
* opengl ignores z-order
* series names with space in them
* ugly vertical legend
* opengl and selection curves coloring
* labels missing on opengl, don't allow both options together
* hover out of plot area 'nan' and absurd values

**Comment by liversedge** [comment]
Need a name for the datafilter language, its R-like so maybe reflect that?

**Comment by paulj49457** [comment]
> Need a name for the datafilter language, its R-like so maybe reflect that?

CheetaR

**Comment by arnold-c** [comment]
Hi @liversedge, not sure if this would be incorporated under your point "bars and lines on line chart", but there are a couple of chart areas that I think would be useful to add (though please correct me if it's already possible):

1. When multiple variables are plotted, such as in the "Performance chart" (especially when stacked), it would be useful to be able to show all variable values in the hover box description, and perhaps a vertical line through all plots at the time point being examined.
2. It would be useful to be able to change properties of charts, such as line thickness or transparancy, in addition to the colour specifications.
3. In the "Performance chart" it would be useful to be able to flip between shading with Power zones and HR zones.
3. It would be useful to apply the models in the Trend plots to HR Curves, to help an athlete define thresholds and zones, much like for CP or CV.

Thanks for all the work you guys do on this!

**Comment by liversedge** [comment]
The performance chart and CP plot are not generic charts, they are older plots from earlier versions.
It is possible to recreate them using a generic chart at which point your requests are achievable now, you just need to create them.
I do have an outstanding feature that is already in the first comment at the top, which is to retrospectively apply legends and hover styles to the old charts for a unified look and feel.

**Comment by liversedge** [comment]
Closing for 3.6 release- may transfer some of the other updates to version 3.7 (likely split into smaller issues since this issue is more of an epic)
