### ISSUE TITLE
TACX vortex smart 2180 searching

### ISSUE THREAD

**Issue by coozoo** [GoldenCheetah/GoldenCheetah#3383]
Hi
I've tried to pair my device with GC without luck (no matter is it old or new firmware).

Not sure that I've hit a bug or something else.

In zwift it works fine well not really fine it's "paired" with device only when zwift in search mode and I've replug dongle and it is immediately shows my vortex :). I've mention this because  it's actually some kind of confirmation that they can work together.

my device ANT dongle:
# lsusb|grep -i ant
Bus 001 Device 067: ID 0fcf:1008 Dynastream Innovations, Inc. ANTUSB2 Stick

1. I'm selecting "ANT+ and FE-C" (first item in list)
2. A see that GC recognized my dongle. 
3. But all sensors are in "Searching..." state.
I've tried pedaling, I'm not sure how long should I do this but tried for 1 minute and it is still in searching.

Tested this on WIN7 (and booted into linux the same PC) where ZWIFT works fine.

I'm out of ideas how to find what's wrong. 
Or maybe vortex is simply not supported device?

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Preferences_Train-Devices#troubleshooting-tacx-device-fe-c-connection and look for Vortex in the users forum, lot of information and experiences there.

**Comment by coozoo** [comment]
Actually I read this already and it is looks outdated because

`FE-C (the bottom of the list)`

But now FE-C on the top of list.

`If you TacX trainer FE-C is not working as expected trying turning off bluetooth on your phone/ipad/other controller device. i.e. your phone connected to the trainer via bluetooth will stop the trainer from connecting via ANT+ to GC.`

and sure i've checked this that's why I've wrote that zwift working I've just closed zwift and tried GC in different ways without success.

I'm usually checking all forums and any available info before opening issues, And for me it looks like some kind of bug.... but if you insist that it is should work than OK but actually it doesn't

**Comment by amtriathlon** [comment]
Just a cursory search on the users forum shows:
a) a recent experience from a user using a Vortex without problems: https://groups.google.com/forum/#!searchin/golden-cheetah-users/vortex%7Csort:date/golden-cheetah-users/ZbtL0ReqNhc/22JhGrfOBQAJ
b) an older post showing to close Zwift may be not enough: https://groups.google.com/d/msg/golden-cheetah-users/wFsMMiKYi5s/HX2LEKFCDQAJ
