### ISSUE TITLE
problems with tsb

### ISSUE THREAD

**Issue by Eduardoq174** [GoldenCheetah/GoldenCheetah#3386]
had to reinstall golden cheetah because my pc crashed and now my training stress balance graphic is not working right,  the substraction of ctl minus atl doesn't match the tsb, is not lke wrong bit the result jumps 1 day ahead and the worst is the same error is in both my windows pc and my Mac, I really apreciate any help
![EUTAv95XYAU84N-](https://user-images.githubusercontent.com/62909447/77959881-92b0ad80-7294-11ea-8592-f2bbc6eb2113.jpg)
![EUTBPY7WsAE_9op](https://user-images.githubusercontent.com/62909447/77959884-947a7100-7294-11ea-9cb2-b489d35d550f.jpg)

**Comment by amtriathlon** [comment]
Please, user the users forum for help.
