### ISSUE TITLE
Installed GC 3.5 64Bit on WIN10 and menus don't work.

### ISSUE THREAD

**Issue by KuotaGrant** [GoldenCheetah/GoldenCheetah#3387]
Installed GC 3.5 64Bit on WIN10 and menus don't work.  Specifically the typical Windows commands on the top left page are completely inert.  Thanks

**Comment by amtriathlon** [comment]
There was a similar report some time ago (https://github.com/GoldenCheetah/GoldenCheetah/issues/2962), but we couldn't reproduce it.

**Comment by KuotaGrant** [comment]
> There was a similar report some time ago (#2962), but we couldn't reproduce it.

Thanks.  I have uninstalled the GC 3.5, rebooted the computer and reinstalled.  Still have same issue.  Because of this I am unable to add any new files to the GC.  Any ideas would be great.

**Comment by amtriathlon** [comment]
I would try View > Reset layout or to create another athlete, this can be done adding a non existing athlete (or —) to the command line.

**Comment by KuotaGrant** [comment]
Hi Alejandro

I just posted the following on Google Groups, oops I got confused between you 
and a fellow named Dan. 

As you know I installed the latest GC 3.5 and had no access to the Windows 
commands at all, rendering GC useless.  For the benefit of others, I had the 
same issue as Alejandro Martinez, below.  I uninstalled and reinstalled on 
WIN10 64Bit and still nothing and could not upload a file or delete or create a 
new athlete.  


Dan, your advice to Alejandro was helpful although I was unable to determine 
the location of GoldenCheetah.ini via a Windows Explorer file search and the 
link 
wasn't helpful as I am a Joe Schmoe and not a programmer.  

So what I did was search for all the Golden Cheetah program directories one by one until I landed here C:\Users\USERNAME\AppData\Roaming\goldencheetah.org.  I was able to delete the GoldenCheetah.ini and launch the GC 3.5.  


It worked PERFECTLY!!  Many thanks for all your help!  


"Initial main window state is stored in GoldenCheetah.ini and this file is not removed on uninstall IIRC, 
I would try removing it when GC is closed and restart GC.



Location is OS dependent as explained in 
https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-DATA#where-are-settings-located"




On Monday, February 17, 2020 at 10:16:47 AM UTC-6, Ale Martinez (Please don't 
email or cc me) wrote:
El lunes, 17 de febrero de 2020, 13:09:14 (UTC-3), Dan escribió:
Hi ,
I have uninstalled GC ,  deleted user data and done a clean install by the 
issue with the menus still exists.
Is this a known Windows 10 issue?
Any ideas on how to fix ?


Initial main window state is stored in GoldenCheetah.ini and this file is not 
removed on uninstall IIRC, I would try removing it when GC is closed and 
restart GC.


Location is OS dependent as explained in 
https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-DATA#where-are-settings-
located

Grant Suderman 

----- Original Message -----

**Comment by KuotaGrant** [comment]
Just wanted to say how thankful I am for the help on this forum!  There's no way I could have done that on my own.  Thank-you!

**Comment by amtriathlon** [comment]
Thanks for the feedback, let's add this to the wiki: https://github.com/GoldenCheetah/GoldenCheetah/wiki/GoldenCheeetah-locked-in-Full-Screen-mode-and-menus-don%27t-work

**Comment by KuotaGrant** [comment]
Great!  Just seems so random that 
it's only an issue for very few people.  

Thanks again Alejandro!

Grant Suderman 
----- Original Message -----
