### ISSUE TITLE
Clarify documentation: Control Tacx Smart via ANT+ only?

### ISSUE THREAD

**Issue by probonopd** [GoldenCheetah/GoldenCheetah#3388]
http://www.goldencheetah.org/ says:

> Any ANT+ FE-C Trainer (e.g. Vortex Smart/Neo, Kickr, Muin) 

Recent Tacx Smart devices such as the Satori Smart T2400 and the Vortex Smart T2180 are advertised to also have Bluetooth in addition to ANT+. Since most computers do have Bluetooth built in but not ANT+, the question is:

Can GC also control those devices with Bluetooth, removing the need for an ANT+ USB dongle?

Maybe this can also be added to the FAQ.

**Comment by amtriathlon** [comment]
Short answer is yes.
In v3.5, BTLE is supported only in macOS and Linux and only to monitor power, heart rate and speed/cadence sensors, there is no equivalent to FE-C.

**Comment by amtriathlon** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-TRAIN#which-devices-are-supported-by-goldencheetah-train
