### ISSUE TITLE
Saris H3

### ISSUE THREAD

**Issue by Martinlap09** [GoldenCheetah/GoldenCheetah#3390]
you should add the Saris H3 home trainer.

Thank you

**Comment by Joern-R** [comment]
The Saris H3 is an ANT+ FE-C Trainer (like Wahoo Kickr, Tacx Neo,...) no need to specifically add it somewhere. Just couple it as an FE-C Trainer and it should work.

**Comment by iamjones2** [comment]
@Martinlap09 did you get yours working? I can add mine, but it is not working. No power and not moving.
