### ISSUE TITLE
Training Mode : Freeze at the end of workouts during the import data

### ISSUE THREAD

**Issue by gillesF78** [GoldenCheetah/GoldenCheetah#3392]
When a workout is done, GC freezes unexpectedly during the import data process.

This issue occurs randomly : the import process can succeed, or fail without reason.

See the attached screen shot :
![bug_golden-cheetah](https://user-images.githubusercontent.com/20644297/78533914-fdf50500-77e9-11ea-8fbd-33e85c3df95d.png)

**Comment by amtriathlon** [comment]
I would check the disk for possible corruption, after that you could force a full cache rebuild: close GC, empty athlete's cache folder, and restart GC.

**Comment by gillesF78** [comment]
The problem still occurs after forcing the cache rebuild.
The disk is working correctly.
I forced the cache rebuild by erasing all the contents of the cache folder.

**Comment by liversedge** [comment]
Its highly likely that GC is not closing correctly. What happens when you close GC from the menu?
