### ISSUE TITLE
Python exit() close GC.

### ISSUE THREAD

**Issue by pavlinux** [GoldenCheetah/GoldenCheetah#3393]
Steps.
1. Open Python console;
2. input exit(); 

DIE!

![exit](https://user-images.githubusercontent.com/1057453/78662139-910c6880-78d8-11ea-8c02-71510aaa3dc6.png)

**Comment by liversedge** [comment]
don't do that.

**Comment by pavlinux** [comment]
lamerz, child process must not close parent!!!

**Comment by liversedge** [comment]
it doesn't -- unless the user does, which you should not do.
also, it is embedded not a child process.

**Comment by pavlinux** [comment]
OK, type in Ptyhon console 

>>> pmc = GC.seasonPmc("")

**Comment by pavlinux** [comment]
> it doesn't -- unless the user does, which you should not do.
> also, it is embedded not a child process.

It doesn’t matter what type: fork, thread, child, exec, 
Just must not close. This is a canonical rule since UNIVAC

**Comment by pavlinux** [comment]
Get python thread from console 

```
import ctypes
import os

SYS_gettid = 186
libc = ctypes.cdll.LoadLibrary('libc.so.6')
tid=libc.syscall(SYS_gettid)
print("PYTHON THREAD", tid)
```

**Comment by pavlinux** [comment]
Get python thread from linux shell console

```
$ top -H -p `pidof GoldenCheetah`
```
