### ISSUE TITLE
Can't detect FEC trainer on any release version (Mac + ANT stick + NEO 2T)

### ISSUE THREAD

**Issue by COG-Cardio** [GoldenCheetah/GoldenCheetah#3407]
All other apps are able to connect via FEC to the trainer and control it, except GC. I always just get the attached image, and with no COM port options
<img width="736" alt="Screenshot 2020-04-22 at 17 47 13" src="https://user-images.githubusercontent.com/64183332/80058511-5a159400-8521-11ea-8066-93d5faaa3cd7.png">

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/issues/3303
