### ISSUE TITLE
Summary shows wrong duration

### ISSUE THREAD

**Issue by skeetor** [GoldenCheetah/GoldenCheetah#3412]
I was importing a FIT file from my Garmin 210XT (I didn't find out if I can import directly from the watch, so I used the file.
I was running in intervalls with 2 minutes vs. 1 Minute. On the summary page the duration is sometimes off. In some cases this is not a big deal, because it's only one second, but there are several intervalls where the 1 Minute break is listed with '27', '30', '33' and '32', whatever that means? Seconds? Minutes, etc?

![image](https://user-images.githubusercontent.com/13402331/80225593-8fb69c00-864b-11ea-9fda-1ffce6b87747.png)

**Comment by amtriathlon** [comment]
Duration without ":" separator is in seconds.
You would need to attach the file for any kind of diagnosis, zip compression is required by GitHub.

**Comment by skeetor** [comment]
Here is the FIT file. I now switched my sport to "Run" and now I can see the pace. I noticed that the pace is all wrong, because it shows  pace of 3 Minutes. I would be happy if that were the case, but my pace is more like between 6:45 and 7:30. :)

[20200424-084014-A4O84015.ZIP](https://github.com/GoldenCheetah/GoldenCheetah/files/4530211/20200424-084014-A4O84015.ZIP)

**Comment by amtriathlon** [comment]
> Here is the FIT file. I now switched my sport to "Run" and now I can see the pace. I noticed that the pace is all wrong, because it shows pace of 3 Minutes. I would be happy if that were the case, but my pace is more like between 6:45 and 7:30. :)
> 
> Could it be that this is because of the armswing?

No, the problem is your Garmin is using Smart Recording and you don't have Smart Recording processing enabled in GoldenCheetah.
See https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-RUNNING-&-SWIMMING#how-to-import-runs-and-swims-for-best-results and, please, use the users forum to get help.
