### ISSUE TITLE
Python close GC.

### ISSUE THREAD

**Issue by pavlinux** [GoldenCheetah/GoldenCheetah#3417]
https://github.com/GoldenCheetah/GoldenCheetah/issues/3393

Get python thread from console 

```
import ctypes
import os

SYS_gettid = 186
libc = ctypes.cdll.LoadLibrary('libc.so.6')
tid=libc.syscall(SYS_gettid)
print("PYTHON THREAD", tid)
```

Get python thread from linux shell console

```
$ top -H -p `pidof GoldenCheetah`
```

PID/THREADID = 27005 **IT'S A DAUGHTER PROCESS OF GC** 

![thread](https://user-images.githubusercontent.com/1057453/80280778-ecc75600-870e-11ea-9c3a-83720bd6e21e.png)
![идид](https://user-images.githubusercontent.com/1057453/80280779-edf88300-870e-11ea-93ab-b6d17a27b39b.png)

**Comment by amtriathlon** [comment]
Since you are so invested in this issue may be you could look for a solution yourself: https://stackoverflow.com/questions/5540277/how-to-prevent-embedded-python-to-exit-my-process

**Comment by amtriathlon** [comment]
Closing due to lack of interest.
