### ISSUE TITLE
Feature Request: CRR scale in Aerolab Chung Analysis Chart is not wide enough

### ISSUE THREAD

**Issue by NickD111** [GoldenCheetah/GoldenCheetah#3418]
This is a feature request resulting from a difficulty I encountered recently using the Aerolab Chung Analysis Chart.  I have frequently used the feature in the past to determine the CdA for my TT bike, which is presumably it's primary use for most GC users.

More recently, I wanted to do a CRR analysis for my cyclocross bike. Unfortunately the CRR slider on the chart only goes to a maximum of 0.01, whereas my analysis showed that even on tarmac, the knobbly tyres were very close or higher than 0.01.  On an off-road grass loop, the CRR is significantly above this 0.01 upper limit, typically around 0.020-0.025.  This limitation in GC meant that I had to do the analysis manually, outside of GC, which was a bit of a pain.

Could I suggest that either:
1) The scale of the CRR slider is increased, to at least 0.03.
2) Or if it's better to retain the fine scale of the current CRR chart slider, perhaps create a second 'off-road' version of the Aerolab Chung Analysis Chart.

Thanks

**Comment by liversedge** [comment]
This was fixed in commit 34df3c3e4366d62ebeec618d9ce1bc7c94f2bcbd and is available in the 3.5 release here: https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/V3.5
