### ISSUE TITLE
AUTOMATIC WEATHER DATA ISSUE

### ISSUE THREAD

**Issue by oberti** [GoldenCheetah/GoldenCheetah#3432]
Hi , referring to issue #2958 ,with the new version of python this pythonfixes don't work....

This is the message : in line 1 , no module named core

Incompatibilty from python 3.6 to 3.7.7 ?

THANKS

**Comment by amtriathlon** [comment]
No, but you need to pip install in python 3.7 all the required modules you previously installed in 3.6 to have it working, in particular the first version imports the request module.
What is wrong with the users forum to get help?

**Comment by oberti** [comment]
Ok ...I thought it was an issue.
I write on forum
thanks
