### ISSUE TITLE
Windows 64 and Taxc Fortius 

### ISSUE THREAD

**Issue by a3areval** [GoldenCheetah/GoldenCheetah#3436]
Hi guys

I am new to this software and I guess I am not following something correctly. I downloaded the version 3.5 on windows 64 but my computer does not recognize the fortius though USB.

I could not find a link to a forum of users where this might have been discuss, so apologies if this is the wrong forum for this question.

What instructions do I need?

**Comment by amtriathlon** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/blob/master/CONTRIBUTING.md#how-to-get-help
