### ISSUE TITLE
support legendonly in GC.addCurve

### ISSUE THREAD

**Issue by MeisterP** [GoldenCheetah/GoldenCheetah#3437]
This makes a data series available in the legend without initial displaying it. In plotly, the option is `visible='legendonly'`

For me, this is a convenient option to have a clutter free first graph with an easy option to display additional data series.

**Comment by amtriathlon** [comment]
You can add data series with an empty program for this effect, I don't think we need a specific option.

**Comment by MeisterP** [comment]
On 23.11.20 16:28, Alejandro Martinez wrote:
> You can add data series with an empty program for this effect, I don't think we need a specific option.
> 


I think you misunderstood the feature request.

To quote the plotly manual:
Traces have a visible attribute. If set to legendonly, the trace is 
hidden from the graph implicitly. Click on the name in the legend to 
display the hidden trace.


An online example is available here:
https://plotly.com/python/legend/#hiding-the-trace-initially

**Comment by amtriathlon** [comment]
There is an open issue for Generic Chart Enhancements: https://github.com/GoldenCheetah/GoldenCheetah/issues/3378
