### ISSUE TITLE
Google Drive access scope "drive" has been revoked

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#3440]
Error message: "The functionality connect with google has been temporarily disabled for this application"

I think, If it cannot be re-enabled, we should remove that scope to avoid confussion.

I've tested drive.file is working, but not tested drive.appdata

Reported at the forum: https://groups.google.com/d/msg/golden-cheetah-users/90RxegypOn8/68sjDwBgCAAJ

**Comment by liversedge** [comment]
Its because we need to get GoldenCheetah accredited, I will start the process and report back here.

**Comment by amtriathlon** [comment]
We have report from users trying to use Google Drive saying Google authentication doesn't work anymore: https://groups.google.com/g/golden-cheetah-users/c/kUsTl9oLyo4/m/PLGm1T_qBgAJ

I can reproduce it using latest snapshot builds, and master build with Qt5.15-2:
```
Couldn't sign you in
‪
This browser or app may not be secure

Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
```
It looks like Google authentication process is more restrictive now.

Strava using Google authentication neither works, according to: https://github.com/GoldenCheetah/GoldenCheetah/issues/3850

**Comment by amtriathlon** [comment]
Here is an explanation of the authentication issue and a temporary workaround: https://github.com/qutebrowser/qutebrowser/issues/5182, it looks like a moving target...

**Comment by liversedge** [comment]
We may need to make a statement about no longer supporting Google authentication due to their policies.

**Comment by amtriathlon** [comment]
Setting the http user agent and restricting scope to drive.file allows to restore the sync functionality, I think it is enough for now.
