### ISSUE TITLE
Connecting to ANT+ inconsistent

### ISSUE THREAD

**Issue by charles-m-knox** [GoldenCheetah/GoldenCheetah#3441]
Hi all, I'm using a CycleOps Magnus smart trainer with GC build ID 3991, v3.5, build date 1/18/2020. This is occuring on Windows and on an Ubuntu 20.04 VM with USB passthrough from the Windows host.

I have also tried the latest development build (https://github.com/GoldenCheetah/GoldenCheetah/releases/tag/v3.6-DEV2005) to see if it resolves the issue, and it still persists.

## Issue

Very often when I try to connect to my ANT+ device, the connection immediately toggles from "Connecting.." to "Disconnected...". See the two GIF's below:

### Trying to Connect

This gif shows me trying to connect to the ANT+ device upon starting up GC. You can see that upon clicking the power button, it immediately flips back to disconnected.

![goldencheetah_connect_failures](https://user-images.githubusercontent.com/8022749/81715958-a9b6f380-942d-11ea-919d-ffa4d1d1bde4.gif)

### Trying to Disconnect

This gif shows me trying to disconnect after a functional session of use:

![goldencheetah_disconnect_failures](https://user-images.githubusercontent.com/8022749/81715961-aa4f8a00-942d-11ea-86ab-0e9a70986e14.gif)

You can see that it does not actually disconnect from the device properly, and toggles right back to the "Connected" state.

### Logs on Windows

I was able to find where some logs are stored on Windows by looking at `%APPDATA%\..\Local\GoldenCheetah`. I can paste these logs if needed.

### `configglobal-trainmode.ini`

Here are the contents of my `configglobal-trainmode.ini` file, I am not sure if this is causing issues:

```
[General]
devices=1
devicename1=ant
devicetype1=128
devicewheel1=1992
devicestride1=115
devicespec1=
deviceprof1=15177f
devicedef1=PCS
devicepostProcess1=3
devicename2=BT
devicetype2=8192
devicewheel2=2130
devicestride2=115
devicespec2=
deviceprof2=
devicedef2=PCS
devicepostProcess2=0

[train]
multi=false
autoconnect=false
autohide=false
lapalert=false

[remote]
start=
stop=
lap=
higher=
lower=
calibrate=
```

### Troubleshooting Steps from Wiki

I have followed the recommendations from https://github.com/GoldenCheetah/GoldenCheetah/wiki/ANT--and-BTLE-Troubleshooting on how to properly configure the device:

* Removed all bluetooth interactions w/ the device by turning off bluetooth from both my PC and phone (they were both paired)
* Configured the device to only use the FE-C, and setting the power/cadence/speed all to "Unused" in the menu
* On Linux, I have also followed the steps to configure udev and added myself to `dialout` group, with logout/login

### Other Behaviors

I also would like to point out that GC crashes 100% of the time if I try to delete the ANT+ device from GC after it's been paired and connected.

Additionally, the ANT+ device-add menu only shows the Power reading changing when I pedal on the bike. It does not show any change in any other readings, such as speed/cadence and even the FE-C does not show a power change. **However, when I do finally get the connection working, the FE-C and GC actually do work, despite this.**

## Help needed

A few main questions:

* Are there any suggestions or thoughts on why this is occurring?
* How do I start GC in debug mode so I can figure out what's happening?
* Is the information to start GC in debug mode in the wiki somewhere?

This particular struggle happens to me every time I use GC. I've been using it fairly regularly for many months now. However, today it hit me particularly bad, and I was stuck trying to just add/delete ANT+ devices and connect for an hour straight. Usually I only have to fret with this for 1-5 minutes tops. I'll admit it was extremely frustrating.

I was not able to find any information about how to debug GoldenCheetah in the wiki. If this information is presented there somewhere, please help me identify it, I'll try to help contribute to make it easier to find that info for others.

**Comment by amtriathlon** [comment]
If you want to debug the protocol, all interactions are logged to the antlog.raw file, this is a binary file and this script can read it: https://github.com/GoldenCheetah/GoldenCheetah/blob/master/util/antlog.py
The file is created on the Athlete folder for each Train session and on /tmp during sensor discovery.

But my suggerence would be first to use an USB cable extender to put the ANT+ closer to the trainer and/or look for interference sources s.t. nearby wifi routers, etc.

**Comment by charles-m-knox** [comment]
Hey @amtriathlon, thank you for your response. I'll try out a USB extension cable and will try out the raw log script. Will report the results in 1-2 days.

**Comment by twillis449** [comment]
I am having similar issues with GoldenCheetah on Ubuntu 20.04. The compiled AppImage GoldenCheetah_v3.6-DEV2009_x64.AppImage works fine and detects my ANT+ sensors under Ubuntu 18.04 on a Dell Latitude E6540. When I attempt to use this image under Ubuntu 20.04 on the same computer nothing is detected.
