### ISSUE TITLE
Power button does not activate in training

### ISSUE THREAD

**Issue by mendizalea** [GoldenCheetah/GoldenCheetah#3446]
I am trying to train for the first time with GC but I cannot start. I have correctly connected the sensors using ANT +, I enter training mode, I select the device and the workout and when I press the Power button it turns green but it jumps often to red.

I am trying to read the log according to the following issue:
https://github.com/GoldenCheetah/GoldenCheetah/issues/3441

but the script gives me the following error:
```
File "antlog.py", line 27
   print str (timestamp) + '-' \
      ^
SyntaxError: invalid syntax
```

Log file attached.
[antlog.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4631342/antlog.zip)

Thanks

**Comment by amtriathlon** [comment]
That script is for Python 2
