### ISSUE TITLE
[QUESTION] import zwift files 

### ISSUE THREAD

**Issue by loretoparisi** [GoldenCheetah/GoldenCheetah#3447]
Is it possibile to import Zwift `zwo` files? In my understanding the format is supported, but on macOS I cannot import (the importer says unrecognized format).
Thank you.

**Comment by amtriathlon** [comment]
Yes, but you need to import them as workouts, not as activities.
Use the forum to ask questions and get help, please.

**Comment by loretoparisi** [comment]
@amtriathlon thank you. If I do import workout from Tools.

this is my example workout 
http://zwofactory.com/?a=FTP%20Training&n=3x15%20FTP%20Intervals&d=15%20minute%20warmup%2C%203x%2015%20minute%20FTP%20efforts%20and%208%20minute%20recoveries%2C%20with%2015%20minute%20endurance%20cool-down&t=&w=r0GO142Ds08C1Ts0P02Ss0DC1Es0P02Ss0DC1Es0P02Ss0DC1Er0P0231J

After import I cannot see anything in `Workouts`

<img width="1322" alt="Schermata 2020-05-19 alle 11 37 14" src="https://user-images.githubusercontent.com/163333/82310823-29603780-99c5-11ea-8f82-6edb96525885.png">

Thank you.

**Comment by liversedge** [comment]
Please use the forums to ask questions, this is for bugs and feature requests only.

**Comment by amtriathlon** [comment]
Also watch the Train View tutorial on the main site: http://www.goldencheetah.org/#section-tutorials
