### ISSUE TITLE
Strava get gears, is it possible?

### ISSUE THREAD

**Issue by dasarro23** [GoldenCheetah/GoldenCheetah#3449]
Hello,

I have been reviewing the GoldenCheetah integration code with Strava API and I think it would be nice to include a call to the following context to get equipment:

https://developers.strava.com/docs/reference/#api-Gears-getGearById

In this way activities with Strava origin could be better filtered or organized without being a manual task in importing or synchronizing.

I have carried out tests with my user and the obtaining of data is viable but I would not know how to include it within the Golden data model.

For example to add it in the extra section of the activity or as an additional value in training

Would it be possible? I would like to contribute

Thanks greetings!!

**Comment by amtriathlon** [comment]
GoldenCheetah haven't got a Gears database, but you could use the Equipment metadata field to store the Gear used on an activity, may be by Description or Brand/Model.
Recently we added something like this when importing from ST3, see https://github.com/GoldenCheetah/GoldenCheetah/issues/3406

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/96c8508da291a42f65694027ceedbf2f791be8a3
