### ISSUE TITLE
Hearthrate as a number

### ISSUE THREAD

**Issue by Angoring** [GoldenCheetah/GoldenCheetah#3450]
Helo there,

i am having some issues with the Golden Cheetah App. I configurated my Hearth-rate and I'm able to display it as a grpahic. But i would like to see my Hearth-rate as a number. Can someone help me?

**Comment by amtriathlon** [comment]
Yes, but at the users forum: https://groups.google.com/forum/#!forum/golden-cheetah-users.
This is to track bugs and features.
