### ISSUE TITLE
File GcWindowRegistry.cpp does not compile since removal of #include "RideWindow.h"

### ISSUE THREAD

**Issue by michelrdagenais** [GoldenCheetah/GoldenCheetah#3455]
If you dont define NOWEBKIT, which is the default: src/gcconfig.pri.in:#DEFINES += NOWEBKIT

You get compilation errors:

Gui/GcWindowRegistry.cpp: In static member function ‘static GcChartWindow* GcWindowRegistry::newGcWindow(GcWinID, Context*)’:
Gui/GcWindowRegistry.cpp:231:52: error: expected type-specifier before ‘MapWindow’
  231 |     case GcWindowTypes::MapWindow: returning = new MapWindow(context); break;
      |                                                    ^~~~~~~~~
Gui/GcWindowRegistry.cpp:232:59: error: expected type-specifier before ‘StreetViewWindow’
  232 |     case GcWindowTypes::StreetViewWindow: returning = new StreetViewWindow(context); break;
      |                                                           ^~~~~~~~~~~~~~~~

This seems linked to the following lines being removed from Gui/GcWindowRegistry.cpp in commit a0add0bdc9874a75afce37d66b3a4b0af557d7ce:

51 #ifndef NOWEBKIT
52 #include "RideWindow.h"
53 #endif
54 #include "RideMapWindow.h"

**Comment by Frono** [comment]
I have the same errors when trying to compile with the NOWEBKIT line commented out in src/gcconfig.pri.

> In file included from Train/ErgFile.h:35,
                 from Train/TrainSidebar.h:28,
                 from Train/VideoWindow.h:130,
                 from Gui/GcWindowRegistry.cpp:35:
FileIO/LocationInterpolation.h: In member function ‘void MyBitset<T_bitsize>::truncate()’:
FileIO/LocationInterpolation.h:340:67: warning: left shift of negative value [-Wshift-negative-value]
     void truncate() { m_mask &= (((unsigned)(-1 << (32 - T_bitsize))) >> (32 - T_bitsize)); }
                                                                   ^
Gui/GcWindowRegistry.cpp: In static member function ‘static GcChartWindow* GcWindowRegistry::newGcWindow(GcWinID, Context*)’:
Gui/GcWindowRegistry.cpp:231:52: error: expected type-specifier before ‘MapWindow’
     case GcWindowTypes::MapWindow: returning = new MapWindow(context); break;
                                                    ^~~~~~~~~
Gui/GcWindowRegistry.cpp:232:59: error: expected type-specifier before ‘StreetViewWindow’
     case GcWindowTypes::StreetViewWindow: returning = new StreetViewWindow(context); break;
                                                           ^~~~~~~~~~~~~~~~
make[1]: *** [Makefile:24795: GcWindowRegistry.o] Error 1
make[1]: Leaving directory '/home/pi/projects/GoldenCheetah/src'
make: *** [Makefile:89: sub-src-make_first-ordered] Error 





If I remove the comment I get the qmake error that 'webengine webenginecore webenginewidgets webchannel positioning' are unknown modules in QT.

**Comment by amtriathlon** [comment]
I think after MapWindow and StreetViewWindow the #ifdef NOWEBKIT case should be the only included and the else case removed, together with the conditional compile lines at:
https://github.com/GoldenCheetah/GoldenCheetah/blob/a0add0bdc9874a75afce37d66b3a4b0af557d7ce/src/Gui/GcWindowRegistry.cpp#L226
This has likely happened because we are not building anymore using WebKit, so that case is not tested or maintained anymore.

**Comment by liversedge** [comment]
Removed WEBKIT support in  f4fcc93693a3c68b58cb305aaee412fa444499bc
