### ISSUE TITLE
Crash - QWaylandGLContext: failed to create EGLContext, error=3009

### ISSUE THREAD

**Issue by Danysan1** [GoldenCheetah/GoldenCheetah#3465]
I have installed GoldenCheetah on my Fedora 32 PC via Gnome Software and successfully imported my ride files. 

When I start the program and choose my user, however, the program crashes. Looking at the logs I found these messages: `QSocketNotifier: Can only be used with threads started with QThread` and `QWaylandGLContext: failed to create EGLContext, error=3009`.

Searching on the web the second message I found https://github.com/yuzu-emu/yuzu/issues/2960 which suggested the problem was QT_QPA_PLATFORM defaulting to wayland, so I tried running the program from command line with the command `QT_QPA_PLATFORM=xcb GoldenCheetah` and it now works correctly.

GoldenCheetah should identify if such variable change is necessary and apply it automatically.

**Comment by amtriathlon** [comment]
We are not generating that build, so you should report it to whoever is generating it.

Our builds are available at: http://www.goldencheetah.org/#section-download

**Comment by Danysan1** [comment]
Ok.
Reported in https://bugzilla.redhat.com/show_bug.cgi?id=1842192 .
Closing this.
