### ISSUE TITLE
Golden Cheetah hangs in workout mode...but records correctly (v3.5)

### ISSUE THREAD

**Issue by carvegybe** [GoldenCheetah/GoldenCheetah#3474]
Hi All

I am hoping you can help me explain and correct how GC displays an activity. This is a Trainerroad workout called Bashful +2 which I sought to record using my TR app on the phone and GC on my PC at the same time. Towards the end of the workout I noticed GC would get stuck for a couple of seconds, but I thought it must have been recording correctly because remaining time was consistent with my phone. Indeed, when I look at the activity profile I see odd missing values every minute over the last 20 minutes, but the underlying data file seems fine. I attach here a screen capture of what the activity looks like on GC. The .csv data file format is not accepted for attaching, but the data file is complete without the dropouts shown in the screen capture. Can anyone assist with this?

My set up:
Windows 10 PC with all recent updates and Garmin USB dongle connected via ANT+ to Garmin chest HR and Stages Gen 3 Power Meter on the left crank of my mountain bike. The PM only sends power and cadence data as far as I know.

Thank you

Carvegybe
![Bashfulplus2](https://user-images.githubusercontent.com/66437787/83795844-165c9100-a66e-11ea-96e7-e92efbeec2c0.JPG)

**Comment by carvegybe** [comment]
Why is this closed? I never received a response? And the issue persisted when I tried another workout - in fact the stripy part started 10 minutes into the workout - as did intermittent screen freezing, which is not ideal when trying to hold target power.

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
