### ISSUE TITLE
Elevation Widget: paintevent performs 2x iteration over ergfile point array

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3478]
Debugging the vlc hangs I found significant time being spend in the elevation widget PaintEvent, it is doing two complete passes over the ergfile points in order to compute something that only changes on widget resize. Moved elevation polygon onto the elevation widget and only recompute on size change. This reduces load and eliminates elevation widget flickering on long route files.

Unfortunately this does nothing for the hangs.

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/d55cd20639327ca6565a3d9cacaf59fd7e7e3561
