### ISSUE TITLE
Incomplete Activities Not Handled

### ISSUE THREAD

**Issue by GuyMelville** [GoldenCheetah/GoldenCheetah#3479]
Version 3.7 Development
Platform Windows 10 64-bit
Installation: GoldenCheetah_v3.6-DEV2005_x64.exe

Process: Uploading activities
Error occurs when an incomplete FIT file (as produced by Zwift when a ride is not completed. This file is formed when the user selects a different game world and route fromthe default selection.
Result:
![image](https://user-images.githubusercontent.com/56834737/83903408-fa341f00-a755-11ea-9709-83567378003a.png)
Following this message, the dialog and the whole GC instance close.

These files were handled in previous versions of GC, showing an error  message.

**Comment by amtriathlon** [comment]
Can you attach a file provoking the crash for debugging?

**Comment by GuyMelville** [comment]
Hi,

How are you/

Sorry for the delay in getting back to yoou. Here is a causal Zwift generated Zwift FIT file.

Best regards,

Guy
[
[2020-06-03-15-43-39.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4754174/2020-06-03-15-43-39.zip)
](url)

**Comment by amtriathlon** [comment]
I can reproduce the crash, but I cannot readily debug it.
Since it is and edge case happenning with incomplete files, let's put it in the parking lot.

**Comment by GuyMelville** [comment]
I have re-installed the previous full release version of GC and it handles
these incomplete files produced by Zwift. as I use Zwift a lot for my
training, I will have to use the previous release until this issue is
resolved.

I don't necessarily understand why there is a change. You might consider
bringing back the modules from the previous version, which handle these
files.

Best regards,

Guy

**Comment by amtriathlon** [comment]
This is likely related to the handling of multi session/multisport fit files, but I don't think we should revert that functionality just to handle malformed files. It's your call to continue to use the previous version if it fits you better.

**Comment by amtriathlon** [comment]
Avoiding the split step when there are errors fixes the crash:

![incomplete-fit-file](https://user-images.githubusercontent.com/1444784/84550750-d6d31c00-ace1-11ea-974d-93c4c941f4ea.png)

**Comment by GuyMelville** [comment]
Thank you.

May I ask how I set it up to avoid the split step?

Best wishes,

Guy

**Comment by amtriathlon** [comment]
No setup required, if there are errors the session split step is always avoided, it really made no sense in that situation.

**Comment by cjue** [comment]
> No setup required, if there are errors the session split step is always avoided, it really made no sense in that situation.

If I understand correctly, your fix avoids the crash, but the files are still not imported because of the parsing error.

As this happens quite frequently to my Zwift recordings I am interested in importing these recordings anyway, if I can find a good way to improve the parsing code. 

Would special case handling for files with problems like these be welcome, or would you prefer never to import "less than perfectly valid" files?

**Comment by GuyMelville** [comment]
Thank you

**Comment by amtriathlon** [comment]
> If I understand correctly, your fix avoids the crash, but the files are still not imported because of the parsing error.

Exactly, it restores the previous behavior before the multisport split.

> As this happens quite frequently to my Zwift recordings I am interested in importing these recordings anyway

Search for FIT file repair tools, there are several available.

> if I can find a good way to improve the parsing code.

Contributions are welcome, look for the contribution guidelines in the wiki and use the developer’s forum if you have questions.
