### ISSUE TITLE
Anomalies not identifyed when slected in Anomalites dialog

### ISSUE THREAD

**Issue by GuyMelville** [GoldenCheetah/GoldenCheetah#3480]
Version: 3.7 Development
Platform: Windows 10
Installation: GoldenCheetah_v3.6-DEV2005_x64.exe

Process: Finding Anomalies
A Suspiciously High cadence was identified by the Anomalies Finder. the anomaly is not identified when the listed anomaly is clicked.

![image](https://user-images.githubusercontent.com/56834737/83905126-0b325f80-a759-11ea-98d3-bfc88e6691b5.png)

**Comment by amtriathlon** [comment]
That anomaly is identified by a red weaving underline, if you mean the row is not selected on click, please attach the json file to recreate the issue.

**Comment by GuyMelville** [comment]
Hi,

Sorry again for my delayed response.

Here is the source FIT file.

I have looked at this again on other files and gaps in recording anomalies were being located as underlined in the data.  The high cadence in this file wasn't.
[2020-06-04-19-00-17.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4754211/2020-06-04-19-00-17.zip)


Best regards,

Guy

**Comment by liversedge** [comment]
the cadence is 208, at 2711 seconds and has a wavy underline to show this.
