### ISSUE TITLE
Add support for Polar SRD -filees

### ISSUE THREAD

**Issue by krissen** [GoldenCheetah/GoldenCheetah#3486]
Hi,

I have a bunch of old `srd` -files, workouts recorded with a Polar S625sx watch. I'm looking to convert them into a format which is supported elsewhere (like `tcx` or some such).

I believe `srd` files was the raw format Polar's watches recorded workouts as, internally. `hrm`-files, of which you already have support, is the format Polar's software converted it to. 

Back in the day, I used `s710` ([Google Code](https://code.google.com/archive/p/s710/) | [Github](https://github.com/ra1fh/s710)) to download workouts; it also had a tool for converting `srd` to `hrm`. There is also [s725](https://github.com/ra1fh/s725), which has a `hrmtool` for converting from both `srd` and `hrm`. However, neither tool works as-is on my `srd`-files.

If I remember correctly, I had to make some changes in the code of `s710` to make it work, but 15 years has passed; I don't have the code nor do I remember how. (I'm not fluent in C and believe I had help from the author of the program to figure it out at the time.)

[Here](https://www.dropbox.com/s/esdb8nskldo2z3t/20050211T123700.02625.srd?dl=0) is a sample `srd`.

**Comment by liversedge** [comment]
They are already supported.

**Comment by krissen** [comment]
> They are already supported.

<img width="911" alt="Skärmklipp 2020-06-08 13 01 56" src="https://user-images.githubusercontent.com/2943684/84023569-9d6c7a80-a988-11ea-87b0-036aa6bb1949.png">

Ah! I mistook the error `Could not read file` for entire lack of support of filetype. Guess it's `srd`'s recorded by this particular watch, or some such, then.

Shall I open a new issue for error in reading `srd` -files?
