### ISSUE TITLE
Add Garmin MTB Dynamics

### ISSUE THREAD

**Issue by deix** [GoldenCheetah/GoldenCheetah#3488]
Hi GC Developers,

After the last update of firmware for Edge x30 series, the [Garmin MTB Dynamics](https://support.garmin.com/en-US/?faq=LnMrHIIquc8loZMhtxZ0i7) can be activated also for road profiles. This "metadata" can already be imported from FIT files:

![MTB raw data](https://user-images.githubusercontent.com/8902727/84130518-ad956000-aa43-11ea-97ed-791c0815716b.png)

Looking at the Garmin Connect site I can "decode" the values as:

**FIELD_114 -> "Grit"
FIELD_115 -> "Flow"**

I was not able to record "Jump Metrics" yet (jump count, jump distance, hangtime, and jump speed) - is not that easy to be triggered on my Edge 830 during road ride. 

![MTB Garmin](https://user-images.githubusercontent.com/8902727/84130567-bc7c1280-aa43-11ea-8c0e-31a86b0019c0.png)

I am aware, that this is not the "core functionality" for road riders, but this data can nevertheless be used for evaluation the ride.

Regards
Michal

**Comment by amtriathlon** [comment]
It seems easy to add, can you attach a zipped sample file?

**Comment by deix** [comment]
Hi Alejandro,

Yes of course - please find a sample I have created yesterdag evening: [2020-06-11-20-36-47.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4768785/2020-06-11-20-36-47.zip)

Regards
Michal

**Comment by amtriathlon** [comment]
Thanks!

![MTB-GritFlow](https://user-images.githubusercontent.com/1444784/84513835-6c4dbc00-aca0-11ea-8675-2fb19249634c.png)
