### ISSUE TITLE
Some SRD files are not imported successfully

### ISSUE THREAD

**Issue by krissen** [GoldenCheetah/GoldenCheetah#3489]
Although there is support for importing Polar's SRD-files, some such files do not import successfully.
<img width="911" alt="Skärmklipp 2020-06-08 13 01 56" src="https://user-images.githubusercontent.com/2943684/84136409-8d699f00-aa4b-11ea-8c7b-676bea9c6f8d.png">

Here are two examples: [[1](https://www.dropbox.com/s/esdb8nskldo2z3t/20050211T123700.02625.srd?dl=0), [2](https://www.dropbox.com/s/q6474pzo7k9fb1l/20060814T171741.02984.srd?dl=0)]. (I have +200 others if you'd like additional test files. I've tried to import several into GoldenCheetah, and have got the same error at every attempt so far.)

I haven't looked at your code, and I don't know what specifically is failing in the import, but I have also tried another tool (`hrmtool` from repository [s725](https://github.com/ra1fh/s725)) which initially had similar results. However, the author has been very helpful and support for the provided `srd`-files in `hrmtool` is almost complete! See s725 [issue #1](https://github.com/ra1fh/s725/issues/1).

**Comment by amtriathlon** [comment]
It looks like that project is based on the same “S710” project code included in GC, so likely those fixes could be backported: https://github.com/GoldenCheetah/GoldenCheetah/blob/6e8bad3d19c21d53417638eed662ff6321cfe19f/src/FileIO/SrdRideFile.cpp#L146

**Comment by krissen** [comment]
Yes, it is! Great; will comment here once the last detail has been fixed over at s725.

**Comment by krissen** [comment]
With the latest changes in the master branch of s725, it's `hrmtool` can convert the previously provided `srd`-files into `tcx`-files which GC can successfully import (see below).

<img width="917" alt="Skärmklipp 2020-06-10 12 01 10" src="https://user-images.githubusercontent.com/2943684/84255247-a2f5cc00-ab12-11ea-8feb-3950a7e3630b.png">

**Comment by krissen** [comment]
> Are both files from the same or different Polar watches?

They are from the same watch. I have about 250 files. Of them, merely 12 are like the second srd (the one from 2006), whereas the bulk of them are like the srd from 2005. The difference I noticed myself, is that even without the interval-change, I got tcx sample-results with hrmtool from the srd from 2006; I did not from the one from 2005. Not sure why though, nor why they would be different. Probably a setting or some sort in the watch. 🤷‍♂️

The s725 project also has some [test srd -files](https://github.com/ra1fh/s725/tree/master/tests) in the repository.

> if you can build from source you can test it, otherwise let me know which OS are you using.

I tried to build from source, but got a QpainterPath -error. If there's a _macOS_ build of the master branch readily available, I could test it?

**Comment by amtriathlon** [comment]
> I tried to build from source, but got a QpainterPath -error. If there's a _macOS_ build of the master branch readily available, I could test it?

You need Qt 5.14 or 5.13, that error happens with Qt 5.15

**Comment by krissen** [comment]
> You need Qt 5.14 or 5.13, that error happens with Qt 5.15

👍

Built through the previous hurdle. Now stumbled on:
```
Core/DataFilter.h:33:10: fatal error: 'gsl/gsl_randist.h' file not found
```

Package gsl is on version 2.6.

**Comment by amtriathlon** [comment]
Yow may need to configure where GSL include and libraries are: https://github.com/GoldenCheetah/GoldenCheetah/blob/16e00fde908db249053bf83f853e2e07ef82d210/src/gcconfig.pri.in#L15

**Comment by krissen** [comment]
> Yow may need to configure where GSL include and libraries are:

👍

Obstacle overcome. Next hurdle:
```
      ZipReader::fileData(QString const&) const in zip.o
  "_inflateInit2_", referenced from:
      CloudService::uncompressRide(QByteArray*, QString, QStringList&) in CloudService.o
      RideFileFactory::openRideFile(Context*, QFile&, QStringList&, QList<RideFile*>*) const in RideFile.o
      ZipReader::fileData(QString const&) const in zip.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:2088: GoldenCheetah.app/Contents/MacOS/GoldenCheetah] Error 1
```

**Comment by krissen** [comment]
Keep running into things. Now
```
eMetric*> const*, Specification, DateRange) in DataFilter.o
ld: symbol(s) not found for architecture x86_64
```
Maybe I'll just wait until a snapshot release and test that. 🤷‍♂️

**Comment by amtriathlon** [comment]
The error message is truncated, but if you were making incremental changes to gcconfig.pri it may be a good idea to rebuild from scratch: make clean; qmake -r; make

**Comment by krissen** [comment]
> The error message is truncated, but if you were making incremental changes to gcconfig.pri it may be a good idea to rebuild from scratch: make clean; qmake -r; make

Check; that, I have done with each change. 

```
  "_gsl_set_error_handler_off", referenced from:
      _main in main.o
  "_gsl_stats_median_from_sorted_data", referenced from:
      Leaf::eval(DataFilterRuntime*, Leaf*, float, long, RideItem*, RideFilePoint*, QHash<QString, RideMetric*> const*, Specification, DateRange) in DataFilter.o
  "_gsl_stats_quantile_from_sorted_data", referenced from:
      Leaf::eval(DataFilterRuntime*, Leaf*, float, long, RideItem*, RideFilePoint*, QHash<QString, RideMetric*> const*, Specification, DateRange) in DataFilter.o
  "_gsl_vector_alloc", referenced from:
      Leaf::eval(DataFilterRuntime*, Leaf*, float, long, RideItem*, RideFilePoint*, QHash<QString, RideMetric*> const*, Specification, DateRange) in DataFilter.o
  "_gsl_vector_free", referenced from:
      Leaf::eval(DataFilterRuntime*, Leaf*, float, long, RideItem*, RideFilePoint*, QHash<QString, RideMetric*> const*, Specification, DateRange) in DataFilter.o
  "_gsl_vector_get", referenced from:
      Leaf::eval(DataFilterRuntime*, Leaf*, float, long, RideItem*, RideFilePoint*, QHash<QString, RideMetric*> const*, Specification, DateRange) in DataFilter.o
  "_gsl_vector_set", referenced from:
      Leaf::eval(DataFilterRuntime*, Leaf*, float, long, RideItem*, RideFilePoint*, QHash<QString, RideMetric*> const*, Specification, DateRange) in DataFilter.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:2088: GoldenCheetah.app/Contents/MacOS/GoldenCheetah] Error 1
```

But it's fine; I can wait for a snapshot release.

**Comment by liversedge** [comment]
you are linking with 32 bit libs not 64 bit

**Comment by krissen** [comment]
Still on QT 5.14.2, but
```
-I/usr/local/Cellar/qt/5.14.2/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.14.2/lib/QtPositioning.framework/Headers -I/usr/local/Cellar/qt/5.14.2/lib/QtBluetooth.framework/Headers -I/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.14.2/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.14.2/lib -o AddIntervalDialog.o Gui/AddIntervalDialog.cpp
In file included from Gui/AddIntervalDialog.cpp:19:
In file included from Gui/AddIntervalDialog.h:21:
In file included from Charts/GoldenCheetah.h:31:
In file included from /usr/local/Cellar/qt/5.14.2/lib/QtWidgets.framework/Headers/QMenu:1:
In file included from /usr/local/Cellar/qt/5.14.2/lib/QtWidgets.framework/Headers/qmenu.h:44:
/usr/local/Cellar/qt/5.14.2/lib/QtWidgets.framework/Headers/qwidget.h:47:10: fatal error:
      'QtGui/qpaintdevice.h' file not found
#include <QtGui/qpaintdevice.h>
         ^~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/qt/5.14.2/lib/QtWidgets.framework/Headers/qwidget.h:47:10: note: did not find header
      'qpaintdevice.h' in framework 'QtGui' (loaded from '/usr/local/Cellar/qt/5.14.2/lib')
1 error generated.
make[1]: *** [Makefile:125622: AddIntervalDialog.o] Fel 1
```

**Comment by amtriathlon** [comment]
It seems you have issues with your Qt install, if you have further questions about building, please use https://groups.google.com/forum/#!forum/golden-cheetah-developers

> The s725 project also has some [test srd -files](https://github.com/ra1fh/s725/tree/master/tests) in the repository.

Those files and the 2 in our test/rides from S720 also work, I will add your files to the test suite and merge the changes, so they will be available on the next snapshot build.

**Comment by amtriathlon** [comment]
> But it's fine; I can wait for a snapshot release.

You can download the last master build from transfer.sh, the link it's at the end of the Travis-ci log: https://travis-ci.org/github/GoldenCheetah/GoldenCheetah/jobs/697972700

**Comment by krissen** [comment]
> You can download the last master build from transfer.sh, the link it's at the end of the Travis-ci log: https://travis-ci.org/github/GoldenCheetah/GoldenCheetah/jobs/697972700

Thank you. Can confirm this build can add most of my srd-files.

Here is one that the GC build can't read ([srd](https://www.dropbox.com/s/olgjtlj4ui8xpw7/20041231T140659.02157.srd?dl=0)). Using the aforementioned hrmtool with the `-I S625` switch, I can convert the srd to [a tcx](https://www.dropbox.com/s/pbwtnkybjahiydd/20041231T140659.02157.tcx?dl=0) which is successfully imported by GC. 

I don't know what the difference is between this srd and the others. Hopefully just a minor edge-case (even more so than srd-files in general), but commenting nonetheless so it's known.
