### ISSUE TITLE
Tab name width

### ISSUE THREAD

**Issue by jgpallero** [GoldenCheetah/GoldenCheetah#3494]
I can see in the 3.6 version that the tab name width has increased, putting big blank space at right and left of each name. Could be possible to adjust the tab name width to the actual text width of each name?

**Comment by liversedge** [comment]
No.

We are in transition at the moment, the tabs will become chart spaces i.e. multiple charts under each tab. So you are likely to have far fewer tabs anyway. 

Right now its a bit annoying to scroll, but you should be able to use a trackpad or cursor keys to make it easier.
