### ISSUE TITLE
CP graph shows spikes

### ISSUE THREAD

**Issue by Cooledynth** [GoldenCheetah/GoldenCheetah#3495]
For activities the CP graph can show that longer times have a higher power than shorter durations. For example in this image the power for 3min 30 is lower than the 5 minute power, which shouldn't be possible.
![image](https://user-images.githubusercontent.com/48383114/84487925-61daf480-ac97-11ea-8ba1-f4529794a829.png)

**Comment by amtriathlon** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-METRICS#Why-does-my-CP-chart-show-higher-watts-for-a-longer-duration
