### ISSUE TITLE
LTHR detected & additional data from Garmin FIT files

### ISSUE THREAD

**Issue by deix** [GoldenCheetah/GoldenCheetah#3496]
Hi GC Developers,

Looking at one of my previous FTP tests (FIT file: [2020-02-28-16-17-01.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4774506/2020-02-28-16-17-01.zip)) I have noticed, that **LTHR detected** value has not been imported (even though other values, like TE, have) - is this not supported yet ?

![LTHR detected   FTP](https://user-images.githubusercontent.com/8902727/84567418-e05b9300-ad78-11ea-9e81-9c172ce09239.png)

Moreover, can some additional "metadata" be extracted from Garmin FIT file and added: **"Load", "FTP detected", "Calories Burned", "Est. Sweat Loss**" ?

Best regards
Michal

**Comment by amtriathlon** [comment]
Physiological metrics in FIT files are undocumented in FIT SDK, the ones detected were reverse engineered at https://github.com/GoldenCheetah/GoldenCheetah/commit/807ea685d66b48e62d6526cc5c6f1875d3f58345, the LTHR field we decode is only for running, the bike one likely comes in other field but we cannot decode it yet and it is not clear looking at the values which the field is, the same happens with detected FTP.
