### ISSUE TITLE
RouteDistance in dial window should use correct units and be printed as float not int.

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3499]
Route distance is showing distance in (int)km. Should be made to print the same as the other dial distances (including convert to miles for those non-metric peoples.)

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/f47c3003a79f3c0a00ca82f12101ff62b28db2b6
