### ISSUE TITLE
ErgFile has mode field that looks redundant with format.

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3501]
ErgFile has a mode field, its almost always set together with format. Looks like all uses could be removed and replaced with format. There might be a path via computrainer but I doubt it. Maybe computrainer people can check?

**Comment by amtriathlon** [comment]
Computrainer has a 3rd mode, which doesn't seem to be in use, but the distinction is potentially useful if mixed mode workouts (https://github.com/GoldenCheetah/GoldenCheetah/issues/2220) are ever implemented.

**Comment by ericchristoffersen** [comment]
> Computrainer has a 3rd mode, which doesn't seem to be in use, but the distinction is potentially useful if mixed mode workouts (#2220) are ever implemented.

I think... if someone wanted to support computrainer level, that an ergfile mode diverging from format is not be the right approach.

Given that the computrainer 'mode' doesn't work today, and really can't work - I'm pretty keen to clean this out. This is not just placeholder code just waiting to be filled out, it is an error. Put another way - suppose I wanted to add that mode field as it is today? Would you accept the change as progress?

I think it is a healthy simplification to get things to a crisp state where data files are data, are const, and are not to be used to stash runtime state. I think stashing the current trainer mode on the ergfile is a perfect example of what we don't want to do. Since nobody is yet using it its an easy thing to delete.

If someone wants to add a new trainer mode that is fine but it really requires that the top level train mode knows how to operate that way and ergfile doesn't even need to know about it.

**Comment by amtriathlon** [comment]
What I am trying to say is: if we ever decide to implement mixed mode it would be a good opportunity to revise that decision and make changes since it would require extensive testing. If it is not provoking errors or difficulting the implementation of new features I would prefer not to change just for the reasons you enumerate, we have +120 issues open to deal with before that.
