### ISSUE TITLE
Malware/Trojan Horse

### ISSUE THREAD

**Issue by SolosoftNL** [GoldenCheetah/GoldenCheetah#3502]
While downloading the latest build (3.6 June) i got the following message:

HEUR/APC, Heuristic, Gen:Heur, Gen:Trojan.Heur, Memscan:[variant], Deepscan:generic.malware

**Comment by liversedge** [comment]
Its a false positive. The malware provider needs to update.
Which software are you using?

**Comment by SolosoftNL** [comment]
ok, i will update. Using F-secure btw.

**Comment by ericchristoffersen** [comment]
I wonder what it saw and flagged?
