### ISSUE TITLE
Favero Assioma Duo and Garmin sensor ids

### ISSUE THREAD

**Issue by tkswe88** [GoldenCheetah/GoldenCheetah#3503]
To add the Assioma Duo power meter pedal, adding a line like
                case 12: return "Favero Assioma Duo";
at l. 538 in FitRideFile.cpp works for me.

If you wanted to add more information on the current dual ANT+/Bluetooth Garmin sensors, these additions to lines 335-398 in FitRideFile.cpp would do the job
  	        case 16: return "Garmin Cadence Sensor 2";
  	        case 3192: return "Garmin Speed Sensor 2";
       	        case 3299: return "Garmin HRM-Dual";

**Comment by deix** [comment]
Hi, 

I have just checked my new "Garmin Cadence Sensor 2" - it seems that it has id "20":

![IMG_2439](https://user-images.githubusercontent.com/8902727/84699052-22d7c800-af51-11ea-88bb-0c4e7ca50a69.jpg)

Regards
Michal

**Comment by deix** [comment]
As mentioned above my new "Garmin Cadence Sensor 2" has ID 20 - I have bought it as "only cadence". My wife's has bought "combo" - Garmin cadenace & speed v2, and her sensor has ID 16, as You wrote. Conclusion - both ID should be implemented:

![Cadance](https://user-images.githubusercontent.com/8902727/84700172-0472cc00-af53-11ea-91fb-d21e77b5501d.png)

Regards
Michal

**Comment by tkswe88** [comment]
To @amtriathlon and @deix, many thanks!
