### ISSUE TITLE
3.6-dev-06.2020  crash as startup on Windows 10

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#3504]
After update from 3.5 release to current 3.6-dev (06.2020) GC crash on startup after checkin percents from 0 to 100%, before show main window.

[crash_1828_160620.log](https://github.com/GoldenCheetah/GoldenCheetah/files/4787553/crash_1828_160620.log)
[crash_1828_160620.dmp.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4787560/crash_1828_160620.dmp.zip)

I completely cleared the directory with the program data (athlete profiles and settings) and made a clean start. After creating a new profile, the GC also failed.

[crash_1831_160620.log](https://github.com/GoldenCheetah/GoldenCheetah/files/4787571/crash_1831_160620.log)
[crash_1831_160620.dmp.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4787575/crash_1831_160620.dmp.zip)

Windows 10 Home 64 bit, version 1909, all updates

**Comment by MaksVasilev** [comment]
I test linux Appimage version on current openSUSE Tumbleweed x86_64 - it's work ok.

**Comment by amtriathlon** [comment]
https://groups.google.com/d/msg/golden-cheetah-users/95eXJXeHq68/_yiJKaFOAwAJ
