### ISSUE TITLE
Strava upload/sync query - ride appearing under "Following", not under "You"

### ISSUE THREAD

**Issue by Hikerbiker** [GoldenCheetah/GoldenCheetah#3505]
Hi 

I'm a new GC user and attempted to upload/sync my first ride (which I originally exported from Elite's My E-Training App and then uploaded into GC) into Strava but noticed that the ride information appeared in the "Following" list, rather than under "You" within Strava. I deleted and retried uploading/syncing several times over but it continues to appear in this way.

I have attempted to find a previous post on this issue but could not find one. It is clearly a little odd not to have the ride appearing under your own page and there is no way to move it into the correct place. I presume this is not how the upload/sync to Strava is intended to behave and requires a minor fix?

I am using GC latest stable version on Windows 10.

Kind regards and thanks

**Comment by amtriathlon** [comment]
They should be listed on My Activities: https://www.strava.com/athlete/training
