### ISSUE TITLE
Garmin Fenix 6 - Incorrect Device and Sport

### ISSUE THREAD

**Issue by philroyle** [GoldenCheetah/GoldenCheetah#3507]
I'm using a Garmin Fenix 6 (Sapphire) but Golden Cheetah is identifying it only as "Garmin 3290" in the Device field.  

Also, the Sport field is being misidentified frequently - for example, the attached .fit file (recorded as a Run activity, downloaded as original from Garmin Connect) imports with an empty Sport field and a SubSport field as "whitewater".

Version: V3.6-DEV2006

[5096533607.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4788027/5096533607.zip)

**Comment by amtriathlon** [comment]
It's weird this file has 2 sets of sport/subsport fields in the same session message, the first is the one shown in Garmin Connect and the second is the one we are displaying.
