### ISSUE TITLE
3.6 not launching on Windows 10 Home 64 bit Build 18363

### ISSUE THREAD

**Issue by gh13** [GoldenCheetah/GoldenCheetah#3508]
When launching v3.6 on Windows 10 Home 64 bit Build 18363. The initialisation window increments to 100% but the application does not launch. I reverted back to v3.5, which works as expected

**Comment by amtriathlon** [comment]
See https://groups.google.com/d/msg/golden-cheetah-users/95eXJXeHq68/_yiJKaFOAwAJ
