### ISSUE TITLE
HRV (R-R) data not available for the "Ride Chart"

### ISSUE THREAD

**Issue by deix** [GoldenCheetah/GoldenCheetah#3510]
Hi GC develeopers,

After I have installed VERSION 3.6 DEVELOPMENT, I am not any more able to select HRV (R-R) data for the Ride Chart - only the "Heart Rate" is available: 

![Ride chart](https://user-images.githubusercontent.com/8902727/84897007-38f69d00-b0a5-11ea-912a-4cedc1d21a07.png)

The HRV data has been imported properly from FIT file:

![Data](https://user-images.githubusercontent.com/8902727/84896995-36944300-b0a5-11ea-9048-83d5f2fb6a19.png)

HRV (R-R) has been available to plot in v3.5. Is there any setting I need to activate / configuration file to be adjusted in the 3.6 ?

Best regards
Michal

**Comment by amtriathlon** [comment]
Yes, the ad-hoc R-R curve had some issues and was removed since it can build as User Data with greater flexibility, see the wiki for how to: https://github.com/GoldenCheetah/GoldenCheetah/wiki/HRV#importing-and-processing-r-r-data-in-goldencheetah
