### ISSUE TITLE
Hide lap dotted lines in activity view

### ISSUE THREAD

**Issue by gillesF78** [GoldenCheetah/GoldenCheetah#3514]
In the Activities > Ride view, it would be nice to have an option to hide lap vertical dotted lines.

![gc-hide-laps](https://user-images.githubusercontent.com/20644297/85063487-81e44980-b1aa-11ea-8a81-f27f50681d68.png)

**Comment by amtriathlon** [comment]
This looks like a duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/2215
