### ISSUE TITLE
Ant+ issue windows 10

### ISSUE THREAD

**Issue by SolosoftNL** [GoldenCheetah/GoldenCheetah#3521]
Hello Devs! 

I've got troubles pairing with my devices by using Ant+. At first the devices are recognized, but after starting the actual workout then the following message apears; see attatchment.
![IMG_20200623_114206](https://user-images.githubusercontent.com/6184198/85414737-c71ec780-b56c-11ea-89cf-bdcf1cf57e85.jpg)

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
