### ISSUE TITLE
The collapse of the graph of the Right (Left) Power Phase during a pause in training.

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#3524]
The trend of LPP, RPP breaks in two cases:
1) there was a normal pause in the training,
2) the head unit lost connect with the power meter, and then recovered

![GC-Left-Right-Power-Phase-01](https://user-images.githubusercontent.com/1708135/85986446-ee561880-b9f4-11ea-80b3-b0e90f1b4b3e.png)

![GC-Left-Right-Power-Phase-03](https://user-images.githubusercontent.com/1708135/85986456-f44bf980-b9f4-11ea-900a-a1b540f46775.png)

[5159111462.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4844430/5159111462.zip)
[5064805894 (1).zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4844441/5064805894.1.zip)

**Comment by amtriathlon** [comment]
It looks like a glitch on smoothing when there are gaps, removing smoothing or gaps fixes it.

**Comment by MaksVasilev** [comment]
![image](https://user-images.githubusercontent.com/1708135/86104367-9daef000-bac6-11ea-889d-2fc1cd2fc6ac.png)

Yes, without smoothing, the graph does not tend to zero on X

But the pause in the recording - this is normal for training. Sometimes athletes use autopause for long training sessions. The sensors do not" Wake up " at the same time.

**Comment by amtriathlon** [comment]
> But the pause in the recording - this is normal for training. Sometimes athletes use autopause for long training sessions. The sensors do not" Wake up " at the same time.

Edit > Fix Gaps was created to fix these cases.

**Comment by MaksVasilev** [comment]
Yes, the "Fix Gaps" works. I thought that I had it enabled "when importing", but it turned out that it is disabled.
