### ISSUE TITLE
Automatic import from Xert has mostly 0 values for speed and calculated moving time reflects this. 

### ISSUE THREAD

**Issue by twizzle** [GoldenCheetah/GoldenCheetah#3526]
GC3.5, Linux 64bit AppImage on Ubuntu.  When data is imported from Xert, the speed data is mostly zeros and this is reflected in the moving time value. Correcting speed from distance is a workaround, but "not optimal".

**Comment by amtriathlon** [comment]
Can you attach the original file uploaded to Xert for testing?

**Comment by twizzle** [comment]
Sample file - when loaded from Garmin to Xert then sync'd to GC, the speed data is missing. The speed data *appears* to be in Xert, it's certainly charting it.  
[2020-06-30-04-41-05.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/4850240/2020-06-30-04-41-05.zip)

**Comment by twizzle** [comment]
Oh, and if I download the original file from Xert and load into GC, the speed data is there.  It only appears to drop it when importing via the shared account.
