### ISSUE TITLE
Add 1mi and 10mi options to Available Metrics under Preferences - Metrics - Bests

### ISSUE THREAD

**Issue by Clinberg** [GoldenCheetah/GoldenCheetah#3527]
- 1 mile is a traditional performance metric for running. See https://en.wikipedia.org/wiki/Mile_run_world_record_progression

- 10 mile is still quite a popular distance for running too, admittedly not as popular as 5k / 10k / Half- or Full- marathon, but still - several famous races in each country. In NL examples are Amsterdam Dam2dam (https://www.damloop.nl/) and Tilburg 10mi (https://www.tilburgtenmiles.nl/).

The ask is to add above distances to Available Metrics under Preferences - Metrics - Bests.

<img width="712" alt="GC_no_best_mile" src="https://user-images.githubusercontent.com/881942/86170996-476c9c00-bb1c-11ea-9227-dba05a841b60.png">

**Comment by amtriathlon** [comment]
There is a function to compute best time for any distance you can use in a custom metric: https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Formula-Syntax-and-Expressions#besttimedistance

**Comment by Clinberg** [comment]
Thanks for your reply @amtriathlon.

How would 'besttime(distance)' function help adding Available metric for PB? 

The use case I described is to configure athlete bests metric for say 1mi, and then you can see this displayed for each season under Trends - Summary, without need for any custom charts. What I try to say is that this is seemingly very easy implementable improvement to the _default_ trends functionality, not a custom metric that very few users would ever configure.

**Comment by amtriathlon** [comment]
> How would 'besttime(distance)' function help adding Available metric for PB?

Once you define the requested custom metrics using it, they behave like built in metrics and can be added to bests the same way. See the wiki for details and the users forum if you need help.

For v3.6 we added the ability to share user metrics via CloudDB, so other users can find and add them.

**Comment by amtriathlon** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-RUNNING-&-SWIMMING#how-can-i-track-my-best-times-on-predetermined-distances

**Comment by Clinberg** [comment]
Hey @amtriathlon, many thanks for writing this wiki paragraph! 
It really is quite straight forward and indeed falls into generic framework without the need to hardcode.

One issue with added custom PBs though - they seem to be reverse ordered worse to best, i.e. desc instead of asc. Any idea how to fix that?
![custom_pb](https://user-images.githubusercontent.com/881942/86286604-11481e80-bbe7-11ea-8cc2-c2bf00168b23.png)
