### ISSUE TITLE
"Estimate Running Power" dialog more informative

### ISSUE THREAD

**Issue by petrus82** [GoldenCheetah/GoldenCheetah#3528]
In line 191 of src/FileIO/FixRunningPower.cpp the function FixRunningPower::postProcess just returns nothing if the sports tag of the ride is set to anything other then run. It took me about half an hour including a look into the source code why this dialog just returned no power values. It would be nice to inform the user of this pitfall, possibly offering something like "Would you like to set the ride type to running?" If yes -> set ride to "run" and continue, if no -> do nothing.

**Comment by petrus82** [comment]
Would this help?

QMessageBox::StandardButton ride_type_user;
ride_type_user = QMessageBox::question(this, "Ride type is not set", "Would you like to set the ride type to run?",
	QMessageBox::Yes|QMessageBox::No);

if (ride_type_user == QMessageBox::Yes) {
	// set ride type to run
	ride.isRun = true;
}

**Comment by amtriathlon** [comment]
> In line 191 of src/FileIO/FixRunningPower.cpp the function FixRunningPower::postProcess just returns nothing if the sports tag of the ride is set to anything other then run. It took me about half an hour including a look into the source code why this dialog just returned no power values.

All Running-specific features added to GC depend on activities being identified as Runs, and "Running" in the name should be a cue, the same happens with Swimming-specific features.
If you are new to GC, this may help: https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-RUNNING-&-SWIMMING

>  It would be nice to inform the user of this pitfall, possibly offering something like "Would you like to set the ride type to running?" 

Currently no Data Processor does that since they are prepared to be used non-interactively when configured to run automatically, this could be done only when the DP is run manually, but in that case all DP should be revisited.

**Comment by petrus82** [comment]
Thank you for your answer, so possibly all DP should be changed to complain about an unset ride type. I am sorry that I can't contribute to that, currently I can't compile GC due to problems with qt version 5.15

**Comment by amtriathlon** [comment]
All DPs have preconditions and do nothing if they are not meet, IIRC.

**Comment by petrus82** [comment]
So the solution would be to inform the user about the preconditions, e.g. at least something like "before you can expect a result of this power calculation, you have to first set the ride type to "running" in the details tab of your ride" if a corresponding check with a dialogbox is not possible. This could be done in the description of the DPs dialogform.

**Comment by liversedge** [comment]
A dialog box is indeed not possible because data processors can be configured to run automatically on import and save.
Updating the description is a simple enough change.
