### ISSUE TITLE
Pi 4 Makefile instructions list a line that does not exist.

### ISSUE THREAD

**Issue by blibenson** [GoldenCheetah/GoldenCheetah#3532]
The current Github documentation has instructions to:

uncomment line #LIBS += -lz

Perhaps I am missing something but that line does not exist in the Makefile.

**Comment by bodylinksystems** [comment]
I asked the same question from WITHIN the forums, and even mentioned that this topic was closed (by the person who was "helping" me and the person who closed this question here), and and still no one has any idea and you cannot contact someone directly.

Unless you can contact Frodo directly, I'm sorry to report that no one is willing to help.

**Comment by gcoco** [comment]
Not sure why you are looking for a Makefile as the instructions tell you to edit the gcconfig.pri file and uncomment the LIBS += -lz

**Comment by blibenson** [comment]
> Not sure why you are looking for a Makefile as the instructions tell you to edit the gcconfig.pri file and uncomment the LIBS += -lz
> 
> Which when I read gcconfig.pri has been change to: #LIBZ_LIBS = -lz and #LIBUSB_USE_V_1 = true # don't use on Windows
> 
> Feel free to update the WIKI with the update.

The only reference in the Github installation documentation to gcconfig.pri is if you want to enable Strava functionality so I am not sure what you are referring to. The body of the documentation references the Makefile and changes that need to be made to it which is why I posted the comment. Anyone who is not familiar with Linux will be confused by the existing documentation if they attempt to compile the code.

**Comment by blibenson** [comment]
My mistake for referencing a Makefile vs gcconfig.pri, however, anyone who is not familiar with Linux will likely be confused by the fact that the line in the documentation does not exist in the file.
