### ISSUE TITLE
New User, application crash when pressing close on Activities view

### ISSUE THREAD

**Issue by MattiLaitala** [GoldenCheetah/GoldenCheetah#3536]
GoldenCheetah-3.5-1.fc32.x86_64 on Fedora 32, getting following crash
![Kuvakaappaus - 2020-07-09 18-20-39](https://user-images.githubusercontent.com/31206520/87058697-0c035900-c211-11ea-8d45-20d683873a3e.png)

#0  QColor::operator=(QColor const&) (this=0x555558d40808, color=...) at painting/qcolor.cpp:2929
#1  0x0000555555806fe1 in Card::setData(RideItem*) () at Charts/OverviewWindow.cpp:562
#2  0x000055555580bccc in OverviewWindow::rideSelected() () at /usr/include/qt5/QtCore/qobject.h:503
#3  0x0000555555e88d16 in OverviewWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x5555573167e0, _c=<optimized out>, _id=<optimized out>, _a=0x7fffffffbf60)
    at .moc/moc_OverviewWindow.cpp:495
#4  0x00007fffef56ffb0 in doActivate<false>(QObject*, int, void**) (sender=0x5555573167e0, signal_index=10, argv=argv@entry=0x7fffffffbf60)
    at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:395
#5  0x00007fffef56a7f8 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**)
    (sender=<optimized out>, m=m@entry=0x555556898fa0 <GcWindow::staticMetaObject>, local_signal_index=local_signal_index@entry=3, argv=argv@entry=0x7fffffffbf60) at kernel/qobject.cpp:3930
#6  0x0000555555e966a6 in GcWindow::rideItemChanged(RideItem*) (this=<optimized out>, _t1=<optimized out>) at .moc/moc_GoldenCheetah.cpp:492
#7  0x00005555558bef3d in GcWindow::setRideItem(RideItem*) (this=<optimized out>, x=<optimized out>) at Charts/GoldenCheetah.cpp:120
#8  0x0000555555e975c8 in GcWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x5555573167e0, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at .moc/moc_GoldenCheetah.cpp:395
#9  0x0000555555e97d3b in GcWindow::qt_metacall(QMetaObject::Call, int, void**) (this=this@entry=0x5555573167e0, _c=_c@entry=QMetaObject::WriteProperty, _id=4, _a=_a@entry=0x7fffffffc120)
    at .moc/moc_GoldenCheetah.cpp:450

For me it looks like 
Charts/OverviewWindow.cpp Card::setData is missing null input check?
Crash happens when pressing close on actitivites view, see screen capture. 
![Kuvakaappaus - 2020-07-09 18-22-49](https://user-images.githubusercontent.com/31206520/87059121-98158080-c211-11ea-93d3-4a70fa3fdac9.png)

I am new to this application and I am just trying to import my first entry recorded at my friends computer. Thus I do not have any activities to show but crashing should not happen.

**Comment by amtriathlon** [comment]
Version indicates that is a developer build, please use one of our official builds from http://www.goldencheetah.org/#section-download and https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
