### ISSUE TITLE
Win32/Heri virus found

### ISSUE THREAD

**Issue by nickcolloff** [GoldenCheetah/GoldenCheetah#3539]
Just tried to install 'Current Stable' Win32 version of GC on an old laptop as a testbed. This computer has not been used for many years and still has a very old version of AVG antivirus installed. On installation, AVG flagged Win32/Heri virus in the GC.exe file as a high severity risk. Not sure if this is really a problem but AVG will not let me run the file, even if I wanted to. Thought you should know about this. Have checked for virus contributions but last reported was in 2013, and issue was closed.

**Comment by amtriathlon** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/issues/438#issuecomment-657491358

**Comment by smann004** [comment]
I have only windows security and malwarebytes installed on the system that I installed the 64 bit version of GC 3.6 dev build. I did get quite a few warning message but I bypassed them all. Knowing that this is a dev. build I assumed I knew the reason for the warnings.
