### ISSUE TITLE
[Feature Request] [Usability] Custom metrics should always be at the top of the list of metrics

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#3542]
Currently, the list of metrics is formed in alphabetical order, which makes it very difficult to find the created metrics.

Custom metrics should always be at the top of the list of metrics: in settings, in selecting metrics in trends, and so on. Additionally, custom metrics in the list must be highlighted in color, bold, or some other way.

**Comment by amtriathlon** [comment]
In future versions we could revisit the metrics selection process, may be to include some kind of classification, but this doesn't seem to be an issue since Custom Metrics are listed separately and managed by the user.

**Comment by MaksVasilev** [comment]
In definition page - yes. But in selector - no, this alphabet sort.

![image](https://user-images.githubusercontent.com/1708135/90475022-5391d480-e12f-11ea-8c22-f42de2ac090e.png)

**Comment by MaksVasilev** [comment]
All metrics selectors show metrics list in non-native alphabetical sorting.
![image](https://user-images.githubusercontent.com/1708135/90475223-bf743d00-e12f-11ea-9ea9-802ba679a843.png)
