### ISSUE TITLE
Durations of more than 24 h in brevets or ultra-endurance events

### ISSUE THREAD

**Issue by tkswe88** [GoldenCheetah/GoldenCheetah#3548]
I tried to manually enter activities from a number of brevets, including a few 600 km rides. These were in duration more than 24 hours long. However, such data are not accepted in Golden Cheetah's Manual Entry window, because the duration variable is of type QTime in format hh:mm:ss limiting the hour part to values of 0-23. QTime is really aimed at variables that represent a particular time of day rather than durations. There does not seem to been any corresponding data type suitable for durations in Qt, which is a pity. 

It was great if this problem with manual entries could be fixed. Possibly, an integer variable just holding duration in seconds would be a reasonable substitute. Unfortunately, I do not have any fit or gpx files from such longer rides to test, whether the file import of GPS recorded activities is also affected.

Also in the Manual Entry window, distance and the ride metrics BikeStress, BikeScore, work and Daniel points may have to low maximum values to allow for long brevets or ultra-endurance events. This is a simple fix though.

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/issues/3359
