### ISSUE TITLE
dead link in FAQs

### ISSUE THREAD

**Issue by MatthiasThelen** [GoldenCheetah/GoldenCheetah#3550]
Not too important, but a dead link could be found in the FAQs at:

"In practice, NP and xPower are largely the same, whilst Daniels EqP place much higher emphasis on upper intensity work. For more info on xPower see Dr Skiba's paper on BikeScore **http://perfprostudio.com/webhelp/studio/scr/BikeScore.htm**"

Thanks for all your work!

**Comment by liversedge** [comment]
Thanks have fixed it.
