### ISSUE TITLE
Wrong order of results for time based "Best x" tile in new Trends/Overview view

### ISSUE THREAD

**Issue by weiznich** [GoldenCheetah/GoldenCheetah#3552]
I tried to replicate parts of the old "Summary" view in the Trends section of GoldenCheetah. For "Best x" tiles based on time (where lower == better) the order seems to be wrong. See the attached picture:
![bug](https://user-images.githubusercontent.com/1674512/88936203-2cec2680-d272-11ea-8bf5-e5366ae8e280.png)

I would expect the following behavior: Either GoldenCheetah would infer the correct order for the selected metric automatically or there is an option to configure this while creating the corresponding tile.

Version Information: 
![version](https://user-images.githubusercontent.com/1674512/88936474-7ccaed80-d272-11ea-90fd-cf54613c1312.png)

(Latest Appimage)

**Comment by weiznich** [comment]
Thanks for the fast fix. The interesting thing is that it seems to work for me now after restarting the application (without recompiling).

Additionally I've found two other Bugs/Inconsistencies in the same component: (Not sure if you like new bug reports for those)

* With the "fixed" sorting Pace value of `00:00` are shown as first value. I'm not sure where they are coming from, the corresponding activities. See the attached image. If required it may also be possible to provide one of those activities in a non-public manner.

![nulls_first](https://user-images.githubusercontent.com/1674512/89014919-c31d5c80-d305-11ea-9764-3fef89f63930.png)

* Filters seem to have no influence on the values shown on the overview dashboard at all. As I organize records of multiple different disciplines with GoldenCheetah it was quite useful to filter by discipline to show for example the fastest runs in the last n days/months.

**Comment by liversedge** [comment]
The filter selected on trends view is honored.

**Comment by weiznich** [comment]
So I've played a bit more with filters in the trends view:

* The overview dashboard is not updated for me if I change the current filter. If I switch tabs (from overview to summary and back) the view overview dashboard is updated.
* The update seems to affect only some tiles. See the two attached images for examples. I've recorded 4 activities in the last 7 days. All of them are runs and are correctly classified as such. If I filter by `Sport MATCHES "Run"` everything looks fine, but if I filter by `Sport MATCHES "Bike"` only some tiles get update. Especially note the difference between 0 Total Hours for Bike but 4 recorded activities in the "Best 10km" table.
![run](https://user-images.githubusercontent.com/1674512/89016637-9159c500-d308-11ea-97ac-b5c8530c3e22.png)
![bike](https://user-images.githubusercontent.com/1674512/89016635-90c12e80-d308-11ea-958b-93229fa1076e.png)

* The images above show again some times of `00:00`. I would guess the reason there is as simple as the recorded activities are simply not "long" enough to be 10km/half marathon. In fact I did not run a half marathon in the last week and I did only two runs (that ones with "correct" times) > 10km.

Let me know if there is anything else I can provide to help solving this.

**Comment by liversedge** [comment]
the topn tile has a filter, you should filter out zero values and sport there e.g: isRun && Distance > 10

I think further questions should go to the forums please.
https://groups.google.com/forum/#!forum/golden-cheetah-users

**Comment by weiznich** [comment]
> the topn tile has a filter, you should filter out zero values and sport there e.g: isRun && Distance > 10

Maybe that has already changed on the master branch, but at least in my version there is no possibility to specify a filter for a "Best n" tile. I can only set a name and select a metric. I think it would be possible to make this work via custom metrics, but I'm not sure what use case you have in mind for showing zero values there as first values for the metrics provided by default. Yes they are theoretically the "best" values by just sorting them, but if you didn't complete distance x I would not rate this as "best" value.

Beside of that I would probably be fine if the whole dashboard does not respect filters and requires the user to configure filters at tile level. It's just that the current behavior of applying filters only to some kind of tiles is totally inconsistent in my opinion.  (Though it would be great if it's possible to replicate the behavior of the old summary view here as I would prefer not having to create different dashboards for each of my filters as this would be a quite large number for combinatorial reasons)

> I think further questions should go to the forums please.
https://groups.google.com/forum/#!forum/golden-cheetah-users

Just to clarify that: I don not see anything I've written above as "question". I'm trying to report things I would consider as bugs or inconsistencies. Or to word it differently: I'm not interested in getting answers to questions how to use GoldenCheetah, but I'm interested in filling bug reports for features that are broken from my point of view. If such reports need to follow a certain template please point me to the corresponding guide. (And maybe add a github issue template?)

**Comment by liversedge** [comment]
![topn](https://user-images.githubusercontent.com/142876/89023068-e56da500-d31a-11ea-90b2-23d3d644d0d3.png)

This is the config screen for a TopN tile.

**Comment by weiznich** [comment]
Seems like this option is not available yet on the last preview release. That would definitively allow to workaround the issue with the "to short" best x km times :+1:
Seems like https://github.com/GoldenCheetah/GoldenCheetah/commit/837a7c6154caa5964cd9ae7a6e84381aaa97bbae is the corresponding commit. As far as I understand the code it also honors the "global" filters, so sorry for the noise.

**Comment by liversedge** [comment]
There are snapshot builds here: http://goldencheetah-binaries.s3-website-us-east-1.amazonaws.com/
