### ISSUE TITLE
Crashes and warning in log file DEV build 2006 on linux

### ISSUE THREAD

**Issue by nigelvdv** [GoldenCheetah/GoldenCheetah#3553]
Dear all,

I am running V3,6-DEV2006 as linux appimage and experience some crashes, especially while editting charts in the sidebar column.

The log shows following warning:
lmmin: number of data points (0) smaller than number of parameters (2)
Release of profile requested but WebEnginePage still not deleted. Expect troubles !

When the program actually crashes, then the second line doesn't appear.

Any ideas what this means?

Kind regards,

Nigel

**Comment by amtriathlon** [comment]
It is hard to know without a stacktrace, you can obtain one using gdb:
```
$ gdb GoldenCheetah
(gdb) r
use GC until crash
(gdb) bt

```
