### ISSUE TITLE
Crash while calling GC.webpage()

### ISSUE THREAD

**Issue by tonghs** [GoldenCheetah/GoldenCheetah#3554]
Demo code:
```python
GC.webpage(THE_HTML_FILE_PATH)
```

For example: 
```python
GC.webpage("file:///tmp/GC_cts9w7g1.html")
```

My complete code:
```python
##
## Python program will run on selection.
##
import numpy as np
import plotly
from plotly.graph_objs import Scatter, Layout
import tempfile
import pathlib


## Retrieve power and cadence
xx = np.asarray(GC.series(GC.SERIES_WATTS))
yy = np.asarray(GC.series(GC.SERIES_CAD))

# Define temporary file
temp_file = tempfile.NamedTemporaryFile(mode="w+t", prefix="GC_", suffix=".html", delete=False)

## Prepare Plot
plotly.offline.plot({
    "data": [Scatter(x=xx, y=yy, mode = 'markers')],
    "layout": Layout(title="Power / Cadence")
}, auto_open = False, filename=temp_file.name)

## Load Plot
GC.webpage(pathlib.Path(temp_file.name).as_uri())  # crash here
```

* OS Version: Mac OS 10.16.6
* GoldenCheetah Version: V3.5 (version id: 3991)
* Python Version: 3.6.9

Mac OS log file:
[crash_log.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/5013811/crash_log.txt)

**Comment by amtriathlon** [comment]
Looking at the crash log it seems you are running that code from a Python fix, not a Python Chart, GC.webpage is not intended to be used in that context, and I can confirm it crashes the program if you do.
We should avoid the crash and fail gracefully, but this will no work, GC.webpage is intended for Python Charts.

**Comment by tonghs** [comment]
> Looking at the crash log it seems you are running that code from a Python fix, not a Python Chart, GC.webpage is not intended to be used in that context, and I can confirm it crashes the program if you do.
> We should avoid the crash and fail gracefully, but this will no work, GC.webpage is intended for Python Charts.

Get it. Thanks a lot!
