### ISSUE TITLE
Incorrect average values for laps/intervals from strava import

### ISSUE THREAD

**Issue by bigmike500** [GoldenCheetah/GoldenCheetah#3556]
I have started using the strava import function, and have just noticed that in the laps / intervals in the summary tap are incorrect in GC.

Strava
![strava summary lap intervals](https://user-images.githubusercontent.com/50369545/89313729-c9e30100-d670-11ea-8c1c-2f1f8be40201.jpg)

GC
![GC summary lap intervals](https://user-images.githubusercontent.com/50369545/89313710-c6e81080-d670-11ea-9023-aedf0fe0ef73.jpg)

not sure what is causing this error

**Comment by amtriathlon** [comment]
The likely cause is Gaps in recording.
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
