### ISSUE TITLE
FTP error message

### ISSUE THREAD

**Issue by Junge74** [GoldenCheetah/GoldenCheetah#3557]
Hi,
Just updated to version 3.5 and in the Trends > PC window I get the following message where the FTP estimation used to be:
RMSE 10w CV 4.4 [envelope] 24301 points [MMP]

I have no programming skills, just a simple user, it worked fine in the previous 3.4 version, can someone please help me out?

Thanks!
[
![FTP calculation error](https://user-images.githubusercontent.com/69246716/89410819-b4c7aa00-d724-11ea-92de-76c313e46dd2.jpg)

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
