### ISSUE TITLE
Golden Cheetah extremely slow on MacBook Air

### ISSUE THREAD

**Issue by leisure17** [GoldenCheetah/GoldenCheetah#3560]
On my macbook air with os mojave 10.14.6 Golden Cheetah starts extremely slow since a couple of days; and changing from "activities" to "trends" is also taking several minutes. 
Tried to clean up my mac, tried to re-install GoldenCheetah, it all remains the same. 
Wanted to delete old activities (I have more than 800 actually, but this seems only possible one by one.

Installing the older GC version worked fast, but with this version most of my activities of 2019 and 2020 were no longer available and could not import them. With the current version installed again, all my data are available.

Does anybody have an idea? Thanks for help!

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/wiki/Severe-Performance-Issues and, please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.

**Comment by leisure17** [comment]
Hello Alejandro,

Thank you so much for your great help, now it works as usual!

Best regards,
Wolfgang
