### ISSUE TITLE
Z3 Pace Zone in swimming pool activity

### ISSUE THREAD

**Issue by sabata4** [GoldenCheetah/GoldenCheetah#3563]
I think that it's an issue but please review it.

I upload a swimming pool activity from garmin connect, and it's strange because, all the swimming pool activities (the run activities are ok and the open water too) from the last months in the Overview the Pace Zone the Z3 column always it's 0. I add 2 fit fles and some images:

![Screenshot_2](https://user-images.githubusercontent.com/41129474/89926304-f795f000-dc04-11ea-8b1c-ddad9003dbc1.png)
![Screenshot_3](https://user-images.githubusercontent.com/41129474/89926306-f8c71d00-dc04-11ea-94ad-e44ea9c9bae7.png)
![Screenshot_1](https://user-images.githubusercontent.com/41129474/89926308-f95fb380-dc04-11ea-86ea-476b14e853c9.png)

[2020.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5058288/2020.zip)

Thanks a lot to all the developers!

**Comment by amtriathlon** [comment]
Default pace swim zones are thinner than run ones, and speed data has a lot less variability in pool swims than in OW swims since it is not measured sample by sample but computed from length durations.
You can check the range for Zone 3 in preferences and check your activity has any speed in this range at the Editor, for us to do that, we would need to know the CV you have configured for the date of this activity.

**Comment by sabata4** [comment]
yes, here there are the speed tab for the 2 activities that I attacherd before:
![Screenshot_2](https://user-images.githubusercontent.com/41129474/89931322-4c893480-dc0c-11ea-9f98-d9a9915d533e.png)
![Screenshot_1](https://user-images.githubusercontent.com/41129474/89931327-4d21cb00-dc0c-11ea-871d-d72917148948.png)

the z3 is so thin...

but i suppose that the addition of the % Z1-Z6 have to be 100%, no?

**Comment by amtriathlon** [comment]
That histogram chart has a "Show in Zones" option which is more useful for this purpose.

Again, if you want we reproduce this issue, we need to know the CV value you have configured.

**Comment by sabata4** [comment]
the charts.... if it's not an issue, i'm sorry... 

![Screenshot_3](https://user-images.githubusercontent.com/41129474/89941286-1606e600-dc1b-11ea-8c4e-90f1e69a732d.png)
![Screenshot_1](https://user-images.githubusercontent.com/41129474/89941288-17381300-dc1b-11ea-880a-a5265e4eeceb.png)
![Screenshot_2](https://user-images.githubusercontent.com/41129474/89941289-17d0a980-dc1b-11ea-81fd-f67224f28c20.png)

**Comment by amtriathlon** [comment]
There is an unnecessary rounding when computing speed from length duration, I will fix it.
In this case changing the zone 3 limit to 2:00 to make it slightly wider shows a more even distribution since lots of samples has speed=3kmh/pace=2:00min/100m due to the rounding.
