### ISSUE TITLE
Average Heart Rate on Tracker tab table mode

### ISSUE THREAD

**Issue by sabata4** [GoldenCheetah/GoldenCheetah#3566]
hello, there are a difference in some month average heart rate if you use different Date Ranges filters. Here 2 images:

Filter THIS YEAR

![Screenshot_1](https://user-images.githubusercontent.com/41129474/90036039-d1cf2080-dcc2-11ea-96a2-2036f5131adf.png)

and the second one, filter LAST 12 MONTH

![Screenshot_2](https://user-images.githubusercontent.com/41129474/90036122-eb706800-dcc2-11ea-8456-cc338872e6ad.png)

**Comment by amtriathlon** [comment]
Does this happen only in table mode or also in curve mode?

**Comment by sabata4** [comment]
I'm trying to see the curves but i have a little problem.... because the window that opens to configure the chart it's too big and can't be reduced...

![Screenshot_1](https://user-images.githubusercontent.com/41129474/90177109-55b00800-ddaa-11ea-9916-2e62d9a578ec.png)

**Comment by sabata4** [comment]
well, in the summary tab I have a similar problem...

![Screenshot_2](https://user-images.githubusercontent.com/41129474/90177275-9a3ba380-ddaa-11ea-9296-892afff93c15.png)

**Comment by amtriathlon** [comment]
Hovering the cursor over the chart top-center reveals controls allowing to switch data table on/off

**Comment by sabata4** [comment]
you are right,.. in the curves the data seems correct...

![Screenshot_2](https://user-images.githubusercontent.com/41129474/90227989-c17b8a80-de15-11ea-80e3-59d0072a1e37.png)

the problem with the window is that are too large.... i can move them but i can't move up to see all the buttons.

**Comment by sabata4** [comment]
checking this i have seen that in the table view the CTL is always 0 and in the curves view is correct...

![Screenshot_3](https://user-images.githubusercontent.com/41129474/90228673-eb817c80-de16-11ea-9d0e-f06cd894bfc1.png)
