### ISSUE TITLE
Best 1000m and Best 1500m swim

### ISSUE THREAD

**Issue by sabata4** [GoldenCheetah/GoldenCheetah#3567]
I'm not sure if it's a issue o a problem with the activities distances with the swimming pool activities.

If i filter the swim activities in the summary tab I've configurated to see the BEST 1000 and BET 1500, and I see this:

![Screenshot_1](https://user-images.githubusercontent.com/41129474/90071176-618dc280-dcf5-11ea-9653-fa47b2b41568.png)

the thing is that i have best times in 1000 and 1500 meters swim that don't are in the BEST list:

![Screenshot_2](https://user-images.githubusercontent.com/41129474/90071250-871acc00-dcf5-11ea-9853-16232b494964.png)

**Comment by amtriathlon** [comment]
Best1000m and Best1500m are computed based on speed data and they may differ from time and distance If there are problems with the data. You can add those metrics to summary for testing or to use find intervals best pace for distance, which uses the same algorithm, to cross check.

**Comment by sabata4** [comment]
I tried what you explain..... 

![Screenshot_1](https://user-images.githubusercontent.com/41129474/90146265-1f11c780-dd81-11ea-8cbe-52159e2b9e2f.png)

I'm not sure if the problem is with the data from the fit file... Maybe it's because the distance it's 0.999.... not sure... here there are some fit files that I see in the edit tab but not sure if there are any problem with them...

the truth is that in the Best 1500 there are only 5 results... but in the list there are 10 swims 1500 meters or more....

12 august swim is a 1500 meters swim.... it appears in the BEST 1000 and not in the BEST 1500 (where there are only 5 results).

[Downloads.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5069629/Downloads.zip)

**Comment by amtriathlon** [comment]
The problem is the way the data is imported, it makes the distance slightly short, enough for the Best 1500 (or 1000) cannot be computed. I will look to fix it.

**Comment by sabata4** [comment]
Thanks a lot!!!

**Comment by sabata4** [comment]
I had been testing this issue in the last sanpshot (25/08) and i think that is not solved. Let me show you:

The 31 july swim is a 1000 meters swim and the time have to be on the BEST 1000 but 

![Screenshot_1](https://user-images.githubusercontent.com/41129474/91361391-79d30680-e7f8-11ea-9040-97495ed0556a.png)

![Screenshot_2](https://user-images.githubusercontent.com/41129474/91361403-7f305100-e7f8-11ea-83d7-04e798db9b9f.png)

Here the raw data:

![Screenshot_3](https://user-images.githubusercontent.com/41129474/91361536-d0d8db80-e7f8-11ea-9ddc-aac5c59544c2.png)

in the BEST 1500, you can see 6 results (only the 6 swims with more than 1500 meters, noone of the 1500 meteres swims is on the board.

**Comment by amtriathlon** [comment]
To fix previously imported activities you need to run Edit > Fix Lap Swim on them, newly imported activities should be Ok.
