### ISSUE TITLE
[Feature Request] [Usability] Edit TAB distance

### ISSUE THREAD

**Issue by sabata4** [GoldenCheetah/GoldenCheetah#3568]
When you edit the XDATA on a swim activity, if you swim in a 25 meters pool you need 3 decimals on the distance.... but the editor only allows 2 decimals.... then the best way is to edit the json directly with the notepad, because you can't.

![Screenshot_1](https://user-images.githubusercontent.com/41129474/90151320-e248cf00-dd86-11ea-993c-a1cf2dd17b77.png)

**Comment by amtriathlon** [comment]
XData entry needs a revision, but in this case there is no need to edit distance or time in this case since Edit > Fix Lap Swim will recompute them from pool length and duration.

**Comment by sabata4** [comment]
yes, i have used this function.... but sometimes when you are on the pool the clock counts more pools than the correct one... then you need to edit the XDATa to "fusion" 2 pools into one..... but yes it's a "nice to" feature....

**Comment by amtriathlon** [comment]
No, the "right" way to solve that is to add the missing length, split the duration in both, and use Edit > Fix Lap Swim

**Comment by sabata4** [comment]
but, the problem is when you have more length than the real distnace.... for example, sometimes if ypu stop swimming because there are another person in the swimmingpool in your way, the clock counts 2 lenghts.... and the real lenght is 1....  sometimes you swim 1000 meters (40 lengths in a 25 pool) but you finish with 1050 by a mistake

in this case your solution didn't work no? I'm used to edit the xdata....

**Comment by amtriathlon** [comment]
Just delete the spurious lengths o change their type to pause, and fix duration of the adjacent if corresponds, and Fix Lap Swim will recompute distance, and all related metrics accordingly.

**Comment by sabata4** [comment]
Thnaks!!!
