### ISSUE TITLE
[Feature Request] [Usability] Fat Mass - Fat Percent

### ISSUE THREAD

**Issue by sabata4** [GoldenCheetah/GoldenCheetah#3569]
It's a very simple request but could be interesting in the measurements page to autocalculate the fat mass with the fat percent or autocalculate the fat percent with the fat mass...

![Screenshot_1](https://user-images.githubusercontent.com/41129474/90228458-8a59a900-de16-11ea-8ca0-263379abe3fb.png)

**Comment by amtriathlon** [comment]
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/3533
