### ISSUE TITLE
Segment matching issue

### ISSUE THREAD

**Issue by conover-s** [GoldenCheetah/GoldenCheetah#3571]
[files.gz](https://github.com/GoldenCheetah/GoldenCheetah/files/5077721/files.gz)

The problem occurs when a ride crosses the start point of a segment but diverges for some reason then at some point later in the ride the segment is ridden for real.  For example in the ride example that I attached (mtb ride), I go down the hill (segment backwards) and ride around on the trails at the bottom of the hill.  Then eventually ride up the hill (the segment).  In this case the up hill climb should match the segment but the code misses it.

What happens in the code (Route.cpp, search method) is that when I ride down the hill running the segment backwards the code matches up the start of the segment as I approach that point.  The code actually processed the first 5 segment points before it recognizes that I'm diverging.  You can see this in the log that I supplied.  So the code resets the segment loop index "n" to 0 and continues looking in the ride points for the start of the segment.  NOTE: the segment loop index got reset to 0, but since the code doesn't break out of the ride point loop the current segment point is the 5th point which is where it left off when trying to match the start when I rode down the hill (segment backward).  You can see this in the log file, the point is still the 5th point even though "n" is 0.   So now when I come back to the hill and ride the segment for real the code is trying to find the segment start using the 5th segment point.  That works ok and the match is found (although not the true start) but here is the problem, once the 5th segment point is matched to a ride point then the code breaks out of the ride point loop and goes to get the next segment point, but remember we previously reset the segment index to 0 so now the next segment point retrieved is the 2nd segment point (2nd because the loop counter gets incremented from 0 to 1 which is another small issue, should be reset to -1 to get the first, 0th point).   So now the segment looks like its moving from the 5th segment point to the 2nd segment point and I'm actually riding the other way.  So this shows up as a divergence and the segment is never matched.

Solution:  After a divergence reset the segment index to -1 and break out of the ride point loop so that the 1st segment point is picked  up.

I've included a version of Route.cpp with the logging in the search method (logs in C:\temp\routexxxxx.log). The Route.cpp also contains a second version of the method "search" called "search2" with one possible fix for the problem.   I used boolean "resetroute" and set it to true in two places where where the code needs to reset the segment point and break out of the ride point loop in the case where diverge is found.  Then check for this condition at the bottom.  Reset the segment index to -1.   You can just swap out the call to "search" with "search2" and reload the ride and see the segment get matched.

route.xml:                                  contains route "ClimbtoTwistSis"
routeClimetoTwistSis.log:    contains logging and shows the error
2020_06_01_05_53_10.fit:   the ride that causes the problem
Route.cpp:                             code with logging in original method (search) and new method with fix (search2)
Route.h:                                 new method "search2"

**Comment by amtriathlon** [comment]
The attached file only contains the fit file, if you want to propose a change please see https://github.com/GoldenCheetah/GoldenCheetah/wiki/Guidelines-for-submitting-a-patch

**Comment by conover-s** [comment]
[files2.tar.gz](https://github.com/GoldenCheetah/GoldenCheetah/files/5079159/files2.tar.gz)

$ ls
files2.tar.gz

$ tar -xzvf files2.tar.gz
2020_06_01_05_53_10.fit
Route.cpp
Route.h
routeClimbtoTwistSis.log
routes.xml

**Comment by conover-s** [comment]
Added pull request 3573 with the patch for this issue.
