### ISSUE TITLE
Run Pace trend - Swim Pace trend

### ISSUE THREAD

**Issue by sabata4** [GoldenCheetah/GoldenCheetah#3575]
In the Run Pace trend and the Swim Pace in the table view and the curve view there are different number of registers. And example:

the curve model shows data from 16 august... the table model no.

![Screenshot_2](https://user-images.githubusercontent.com/41129474/90377911-fd625a00-e078-11ea-9e24-55bc288c7080.png)

![Screenshot_3](https://user-images.githubusercontent.com/41129474/90377919-ff2c1d80-e078-11ea-9135-303f1102fbe9.png)

**Comment by amtriathlon** [comment]
See the note about table mode: https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_ChartTypes_Trends#basic-settings
