### ISSUE TITLE
Downloaded training workout exits after 1 second

### ISSUE THREAD

**Issue by glynternet** [GoldenCheetah/GoldenCheetah#3576]
GC Build:
![build_data](https://user-images.githubusercontent.com/1295698/90488725-39a6c080-e134-11ea-8730-36bf2a57e203.png)

If I download a session within Golden Cheetah and then press play to do the session, it will exit after 1 second and then show a message "Error - Insufficient valid data...", as shown below...
![ErrorMessage](https://user-images.githubusercontent.com/1295698/90487992-221b0800-e133-11ea-887c-74d12bc69ece.png)

If I then go to TrainerDay and manually download the same workout, any of the file formats from TrainerDay will work and I can do the workout.

The following are the different views of the workouts, downloaded through Golden Cheetah vs downloaded through browser.

**Some (probably irrelevent) differences to note:**
* The file extensions in the workouts list are different. The one downloaded through Golden Cheetah shows `.erg2` as the extension
![file extensions](https://user-images.githubusercontent.com/1295698/90488302-a2da0400-e133-11ea-9b0f-c723c7948d40.png)
* Some extra information on the graph panel of the manually imported workout

Downloaded through Golden Cheetah
![downloaded view](https://user-images.githubusercontent.com/1295698/90488001-25ae8f00-e133-11ea-9423-2cb7c6b512a7.png)

Downloaded through browser and imported into Golden Cheetah
![manually_downloaded](https://user-images.githubusercontent.com/1295698/90487999-2515f880-e133-11ea-8847-75fc2f1be3ea.png)

**Comment by amtriathlon** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-TRAIN#why-erg2-workouts-downloaded-from-ergdb-terminate-immediately-in-v35

**Comment by glynternet** [comment]
Ah, perfect, thanks!
I didn't see anything in the issues for it but I will check the wiki first next time 😄
