### ISSUE TITLE
Incorrect power in intervals

### ISSUE THREAD

**Issue by pardojavi** [GoldenCheetah/GoldenCheetah#3584]
The power that appears in the intervals section doesn't corresponde with the reality.
Yesterday I did three 10' laps and these are the results:
LAP1:
Golden Cheetah Average Power: 237
Real Power: 255
Normalized Power: 255

LAP 2:
Golden Cheetah Average Power: 188
Real Power: 234
Normalized Power: 233

LAP 3:
Golden Cheetah Average Power: 178
Real Power: 244
Normalized Power: 244

The device used was a Garmin EDGE 1000 with a quarq power meter.
The Golden Cheetah version is: V3.5, Build ID: 3991, Build Date:Jan 18 2020

Kind regards.

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-METRICS#why-is-a-metric-eg-tss-or-average-power-different-in-goldencheetah-to-garmin-connect, if you have a file without anomalies detected in Editor to reproduce this behavior please attach it for further analysis, otherwise use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.

**Comment by pardojavi** [comment]
Hola Alejandro,
El fichero está bien ya que lo veo correctamente en otras plataformas.
Esto mismo me está pasando últimamente con todas las sesiones en las que hago series, los vatios medios no me los calcula bien con mucha diferencia.
Adjunto un fichero de ejemplo en formato JSON y también el fichero exportado directamente de Garmin Connect.




Un saludo.

**Comment by amtriathlon** [comment]
¿Leíste el enlace que te pasé y miraste la pestaña Editor para asegurarte que no hay anomalías?

**Comment by pardojavi** [comment]
Hola,
Si, perdón… lo miré y si que aparecen anomalías, pero esto me ocurre en estas dos últimas versiones de Golden Cheetah en todos los ficheros:


Incluso en Strava las veo bien:


Un saludo.


Tanto en Garmin Connect como en TrainingPeaks aparecen bien.
No se de donde puede venir ese error ya que ocurre en todos lo ficheros.

**Comment by amtriathlon** [comment]
Lo más probable es que esas anomalías estén provocando el resultado que ves, te sugiero que leas el enlace que te pasé y arregles las anomalías como se explica en la wiki y compares los resultados, si aún así tienes dudas, tenemos un foro de usuarios para consultas: https://groups.google.com/forum/#!forum/golden-cheetah-users, este sitio es solo para errores confirmados y nuevas características.
