### ISSUE TITLE
Refresh issue new overview tab

### ISSUE THREAD

**Issue by rb83421** [GoldenCheetah/GoldenCheetah#3585]
Hi,

I noticed with the new overview chart (GC version 3.6 snapshot build 4001 of 28 August) that it does not refresh when you select an new date range in trend view. The progress bar beneath the the value is updated correctly only values are not updated
I'm running on windows.

It will refresh when you move your mouse over it

Kind Regards,
RB

**Comment by amtriathlon** [comment]
There has been several changes related to display issues and performance from that build would suggest to try again using a newer one s.t. https://ci.appveyor.com/project/Joern-R/goldencheetah-knhd8/builds/35087418/artifacts

**Comment by rb83421** [comment]
Hi,

I can confirm that the issue is solved with the newly mentioned snapshot version 

Kind Regards,
RB
