### ISSUE TITLE
Extremely slow with OpenGL rendering

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#3587]
Tested on Windows build on https://github.com/GoldenCheetah/GoldenCheetah/commit/b2da0afb83dcc1d897691942811e3b871247c999 and https://github.com/GoldenCheetah/GoldenCheetah/commit/6164dd963f154ce9a05661167b23c6c06b2649dd

After OpenGL rendering was enabled, trends and graphs were drawn with a long delay: a delay of 3-8 seconds for any mouse movement.

Interval highlighting does not work or only works after several attempts to select an interval with a delay of about 10 seconds.

Trends are selected with a delay of about 5 seconds.

![image](https://user-images.githubusercontent.com/1708135/92319723-fa2d0f00-f023-11ea-83ef-91e09f89bd67.png)

Windows 10 Pro, version 2004,  x86_64

AMD 9750 4-x Core, 8 GB RAM, SSD
Video: AMD Radeon HD 6900 Series, GDDR5 2 GB - last stable drivers installed

All 3D games on Steam, that match the level of this PC, work normally (aka Witcher2, Xcom2).

**Comment by MaksVasilev** [comment]
I checked in Linux: it works fine and fast.

![image](https://user-images.githubusercontent.com/1708135/92405083-8e3ec980-13d-11ea-905b-2b7528724858.png)

openSUSE Tumbleweed 2020-08-20, x86_64,
Driver: "radeon"
Renderer: "AMD CAYMAN (DRM 2.50.0 / 5.7.11-1-default, LLVM 10.0.0)"
The X.Org Foundation, 1.20.8

**Comment by liversedge** [comment]
Amd opengl drivers on Windows have reports of significant performance issues. Will see if there is something we can do. Possibly disabling hardware shaders for their drivers.

**Comment by liversedge** [comment]
The only chart that was affected by opengl was the overview chart. I suspect there is something else going on here.

**Comment by amtriathlon** [comment]
This builds has OpenGL disabled if you want to try: https://ci.appveyor.com/project/Joern-R/goldencheetah-knhd8/builds/35087418/artifacts

**Comment by MaksVasilev** [comment]
@amtriathlon yes, this artefact work normally on Windows with Radeon HD6970

**Comment by freekode** [comment]
I believe I have the same issue on OSX. It's veeery slow when I on new Overview page.
<img width="445" alt="Screenshot 2020-09-14 at 20 07 52" src="https://user-images.githubusercontent.com/940893/93121947-f9e8df80-f6c5-11ea-90d1-f6d66d1f8122.png">

**Comment by amtriathlon** [comment]
> I believe I have the same issue on OSX. It's veeery slow when I on new Overview page.

It is a related issue, it has been discussed in the forum thread about DEV2009, and it should be fixed in latest snapshot: http://goldencheetah-binaries.s3-website-us-east-1.amazonaws.com/?prefix=MacOS/

**Comment by freekode** [comment]
Thank you, just tested, working well

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/e95eb7b39d29c4ed39e1240f4fe8a370f03d5026
