### ISSUE TITLE
Performance Plots (Altitude, Altitude/Slope and Slope Plots) Don't Refresh when the series for X-Axis is not present

### ISSUE THREAD

**Issue by rgeorge1985** [GoldenCheetah/GoldenCheetah#3588]
In the latest development version, I notice when I import a .gpx file off from Strava, the subject plots in the Performance tab are being borrowed from the previous listed activity which is incorrect. I do not see the altitude & slope plots native to this file. 

I tried this with two .gpx files of the segment from two different sources on Strava. Can someone else replicate this?  Is the issue particular to the two latest development builds?

Thx,
-RG

**Comment by rgeorge1985** [comment]
** Update **

Tried doing this in the previous stable version 3.5 and I get the same issue. It seems like something in the "Activity -> Import from File..." function isn't updating the subject performance plots for the current file, but using previous activity information. Please have a look at this, I'm catching this in both stable and development versions. 

Test file is the .gpx file downloaded for this activity --> [](https://www.strava.com/activities/4013645253/segments/2737235901933877120)

-RG

**Comment by rgeorge1985** [comment]
**Update** 

Attaching two images showing the issue. 

In image #1, the previous activity file with its own altitude/slope information. 

In image #2, the new activity file continues to show the old activity's plot.

![Issue 1](https://user-images.githubusercontent.com/23737973/92334940-731f7b80-f0a3-11ea-8bb1-52d9e5ec4452.JPG)
![Issue 2](https://user-images.githubusercontent.com/23737973/92334942-74e93f00-f0a3-11ea-82de-3dfb725ab393.JPG)

**Comment by amtriathlon** [comment]
It is a bug: lack of reset when there is no data to chart.

**Comment by amtriathlon** [comment]
Just for clarity sake: this has not been reported before likely because it is a rare edge case: the data series selected for the X-Axis is not present in the activity, in the example above X-Axis is Time and the selected activity is a route without time, something similar happens if Distance is selected fro the X-Axis and the selected activity has no Distance data.

**Comment by rgeorge1985** [comment]
> Just for clarity sake: this has not been reported before likely because it is a rare edge case: the data series selected for the X-Axis is not present in the activity, in the example above X-Axis is Time and the selected activity is a route without time, something similar happens if Distance is selected fro the X-Axis and the selected activity has no Distance data.

Ah , its always me with these rare edge cases! Sorry for breaking the tool, it was not intended.  :)

**Comment by amtriathlon** [comment]
> Ah , its always me with these rare edge cases! Sorry for breaking the tool, it was not intended. :)

No problem, we need to fix this, but since it is unlikely you are looking for a blank chart, it is better to change X-Axis to distance in this case.
