### ISSUE TITLE
dev version 3.6 2009  can't be opened on mac os 10.11

### ISSUE THREAD

**Issue by kouik03** [GoldenCheetah/GoldenCheetah#3591]
3.6 dev can't be opened on mac os 10.11 , is that expected ? is this a strong requirement for any os specific feature ? I guess I'm not the only one who can't upgrade for other softwares.

**Comment by amtriathlon** [comment]
We are generating 3.6 dev and snapshot builds automatically on Travis-ci macOS 10.13 environment, the next release build is around a year ahead, so there is time to upgrade.
