### ISSUE TITLE
[Feature][Packaging] Gentoo ebuild request

### ISSUE THREAD

**Issue by penguinolog** [GoldenCheetah/GoldenCheetah#3592]
GoldenCheetah is already packaged as bre-built, but for gentoo it's common to build from sources.
IMHO adding official ebuild will be helpful for end-users

**Comment by MaksVasilev** [comment]
This request is more logical to ask gentoo mantainers in the [official Gentoo support channel](https://www.gentoo.org/support/) ([Bug report guide](https://wiki.gentoo.org/wiki/Bugzilla/Bug_report_guide)).

The AppImage package works fine in most modern Linux distributions.

**Comment by amtriathlon** [comment]
See https://appimage.org/ for more info, regrettably Gentoo doesn't seem to be supported yet, lets hope it will be in the future.
Otherwise the AppImage can be extracted to be repackaged, but we don't have resources to do this for every distribution, sorry.

**Comment by amtriathlon** [comment]
FYI, we have a recent success report using current v3.6,AppImage build on Gentoo: https://github.com/GoldenCheetah/GoldenCheetah/issues/3727
