### ISSUE TITLE
Incorrect profile in video chart

### ISSUE THREAD

**Issue by ghost** [GoldenCheetah/GoldenCheetah#3596]
I'm using Developer build (build id: 4001). I created gradient workout in GC workout creator. But when i started my workout, last part (i think 1km) is displayed incorrectly. 

It is visible on image. At the bottom is actual profile and in video chart you can see it starts to descend. Last part where is descending is 5.7% (positive)
http://89.212.19.139/profile_in_video.png

But when i used original (demo) workout file + video + rlv, profile is displayed correctly (in video chart).

BTW, i really like new and improved GC. Great work!

**Comment by ericchristoffersen** [comment]
Are you talking about riding a crs file? Did you create it in workout creator by importing an activity? Can you please share the activity you imported and the resulting workout file?

I just tried importing a workout into 'workout creator' and created a crs. Seemed to work ok. Crs files are run in 'strict slope mode' meaning the slope in the file is the slope you should get, so you should see crisp boundaries between gradients.

You can ride an exported json file directly which will do a smoothly interpolated slope for the altitude changes.

**Comment by kub3r4** [comment]
I didn't use any activity to create crs file. I used workout creator form, Gradient option. This was in Dev build June 2020. Didn't try it in September build yet.

Crs file is very small, so i will just paste data.
```
[COURSE HEADER]
VERSION = 2
UNITS = METRIC
DESCRIPTION = golden cheetah
FILE NAME = F:/GC/10k_5-7max.crs
DISTANCE GRADE WIND
[END COURSE HEADER]
[COURSE DATA]
1 0.5 0
2 1.2 0
2.1 3.2 0
1.9 2.7 0
1.7 2.3 0
2.3 4.3 0
0.8 3.4 0
1.2 5.7 0
[END COURSE DATA]
```

**Comment by ericchristoffersen** [comment]
The nested loops that conspired to draw the elevation line were pretty hard to read. Turns out it was always skipping the segment to the final point. Rewrote in a simpler form and it looks good. I'll create pull request soon.

![elevwidgetfixed](https://user-images.githubusercontent.com/46055145/93630805-74a04c00-f99f-11ea-8f3f-150d9a9e6996.JPG)

**Comment by ericchristoffersen** [comment]
Hi Ale. The rewritten code is now very simple. I went to create pull and find I already made some fixes to elevation widget, it no longer needs to loop over ergfile to find min and max. That change is part of #3442 .Can you let me know if that change will go in so I can build off it?

**Comment by ericchristoffersen** [comment]
@amtriathlon : fix is now pushed into #3442 .

**Comment by amtriathlon** [comment]
> That change is part of #3442 .Can you let me know if that change will go in so I can build off it?

No, I can’t. That PR has a pending review request from @liversedge, he is the project leader and I have no intention to override his decision.

If you want my opinion, I prefer to keep fixes and features in separate commits and PRs, this is easier to verify and allows for easier debugging and maintenance.

Code refactoring and reformatting should be kept separate as explained in https://github.com/GoldenCheetah/GoldenCheetah/wiki/Guidelines-for-submitting-a-patch

**Comment by ericchristoffersen** [comment]
Sorry I didn't realize that it was waiting for mark. Totally agree that fixes should separate but this stuff is all interwoven and just getting worse. Either I make progress or I'll need to stop. Too many pans on the stove. Or maybe I'm just really bad at git.

I'll ping mark for feedback. Hopefully he can let me know what he wants. I just don't see an alternative to pulling runtime state out of the data files, which is the thing everything else depends on.

**Comment by amtriathlon** [comment]
> Sorry I didn't realize that it was waiting for mark. Totally agree that fixes should separate but this stuff is all interwoven and just getting worse. Either I make progress or I'll need to stop. Too many pans on the stove. Or maybe I'm just really bad at git.

Hi Eric, I could try to cherry-pick the commits fixing specific issues from that PR and apply them to master so we can close the issues they fix, then you can rebase the PR to contain only the refactoring  for reviewing.

**Comment by ericchristoffersen** [comment]
How about I extract the stuff that can be separated. Give me a few days. One problem is that the fixes rely on the data separation.

How do I get a response from Mark about separating the ergfile and videofile data from the training state? Does he have a problem with the core concept? Or is there something specific about what I did that he doesn't like?

**Comment by amtriathlon** [comment]
How you prefer, I was trying to help, and referring mainly to #3498, #3498 and #3582 which looks clearly independent, not sure about #3580 and this one.
