### ISSUE TITLE
Special characters don't work

### ISSUE THREAD

**Issue by kub3r4** [GoldenCheetah/GoldenCheetah#3602]
Special characters don't work. I'm talking about characters where you need to hold "Alt Gr". For example, i was not able to insert "@" in email for Strava login and in Garmin chart login.

So i had to type @ outside of GC and copy/paste it.

I'm using Developer build, build id 4001, in Win 10  in virtualbox

**Comment by amtriathlon** [comment]
This is a WebEngine regression in Qt 5.14.2, it is fixed in Qt 5.15.1: https://bugreports.qt.io/browse/QTBUG-83710

**Comment by kub3r4** [comment]
Can you or anyone else help mi with this, please? Don't have a clue what QT is or what/where to look for settings or whatever.

**Comment by amtriathlon** [comment]
The fix for this is included in a new version of one of the libraries used to build GoldenCheetah so you should wait for the next DEV build, in the meantime you already have a workaround and this only affects credentials entry.

**Comment by kub3r4** [comment]
amtriathlon thank you for your comment. i tried Dev Sept 2020 Appimage version and it worked. But i can't play videos when using Appimage in Linux. So i will have to use windows version in Virtualbox.

**Comment by amtriathlon** [comment]
This issue affects only the Windows version. Videos on Linux are supported, but please see the FAQs and use the forum to get help.

**Comment by kub3r4** [comment]
I just tried new Dev Sep 15 2020 version in windows and @ still not working in Garmin chart (train). Just one more question. Is forum on groups.google.com?

**Comment by amtriathlon** [comment]
https://groups.google.com/forum/#!forum/golden-cheetah-users
