### ISSUE TITLE
Very Slow Map Adjustments under MacOS using GC 3.6

### ISSUE THREAD

**Issue by dcquad** [GoldenCheetah/GoldenCheetah#3603]
I'm seeing very slow map rendering when attempting to manipulate maps. That is moving it around or click on into zoom in or out. Eventually this does the correct thing but nowhere near the speed of earlier builds.

Using GC 3.6 from Sept build, MacOS 11

thanks, Doug

**Comment by amtriathlon** [comment]
https://groups.google.com/d/msg/golden-cheetah-users/_9hW4aayxEs/_tvsHbeWAQAJ
