### ISSUE TITLE
Unable to access Menu Bar

### ISSUE THREAD

**Issue by Benjih77** [GoldenCheetah/GoldenCheetah#3607]
Hi, I am using the 3.6 Dev Build.

After installing the June version I experienced an issue where if I swiched from "Activites" to "Trends" then I would no longer be able to access the menu bar (Athlete, Actvity, Share etc) or access the drop down menus on the report tabs. I can try switching between different views and back and forth between tabs, but I cannot enable access to the menu bar / drop downs. So once I have gone to trends, the access is permanantly blocked. 

Today I updated to the September Dev build and the issue is still there.

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/wiki/GoldenCheeetah-locked-in-Full-Screen-mode-and-menus-don%27t-work

**Comment by Benjih77** [comment]
Thanks @amtriathlon - that fixed it
