### ISSUE TITLE
formel does not get a result

### ISSUE THREAD

**Issue by speedskier** [GoldenCheetah/GoldenCheetah#3609]
hello,

I want to solve my watts/kg in a graph, so I wrote  CP_setting / Weight, but there is no result. As I  entered for Weight a number is there an result.
My goal is an graph, wich divides my actual CP through my actual weight. How can I get this?

mfg speedskier

ps: sorry for my bad english

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.

**Comment by speedskier** [comment]
I think its an issue

**Comment by amtriathlon** [comment]
It is not.
