### ISSUE TITLE
Version 3.6 Sep. Preferences > Data Fields > Defaults are gone

### ISSUE THREAD

**Issue by specialex** [GoldenCheetah/GoldenCheetah#3610]
In the 3.6 Sep. version many of my Preferences > Data Fields > Defaults are gone :-(
Have a look to the pics below. 3.6 June vs 3.6 Sep
I use this settings to track the use of single components.
May someone can Help.
<img width="728" alt="Bildschirmfoto 2020-09-17 um 22 36 11" src="https://user-images.githubusercontent.com/22396006/93526939-7256d700-f938-11ea-9f76-8a6d3935ec05.png">
<img width="728" alt="Bildschirmfoto 2020-09-17 um 22 40 28" src="https://user-images.githubusercontent.com/22396006/93526960-7a167b80-f938-11ea-8c09-a30c7f3d0d46.png">

**Comment by amtriathlon** [comment]
This looks like a problem related to https://github.com/GoldenCheetah/GoldenCheetah/commit/80d7eed382fba765673db2645b8fbc83a5710926, likely you can fix your situation copying config/metadata.xml from your athlete folder to GC home, parallel to athletes folder, and restart.

**Comment by liversedge** [comment]
Will fix this, when the global settings are created I merge the metadata fields and color rules but forgot to merge the defaults. 
Like Ale says the short term fix is to copy the metadata.xml file to the athlete folder (replacing the one created at startup).

**Comment by amtriathlon** [comment]
If found defaults are considered, but just one per field:
https://github.com/GoldenCheetah/GoldenCheetah/blob/aaa788917245ca0ffe2e6a553d881d8c93a8873b/src/Metrics/RideMetadata.cpp#L319
This is consistent with OP results: one default per Rad field is preserved, all others are skipped.
It seems easy to fix including both field and value to consider a rule as duplicated.

**Comment by specialex** [comment]
Guys you are outstanding!
I am really sorry may it is ma fault but its still not working in the latest release.
Here is a pic of my defaults in the latest version.
May someone of you can help.
Kind regards 
Alex
<img width="691" alt="Bildschirmfoto 2021-01-31 um 17 35 57" src="https://user-images.githubusercontent.com/22396006/106391153-30609600-63ec-11eb-85f3-89a8724767cd.png">

**Comment by amtriathlon** [comment]
You need to remove metadata.xml in GoldenCheetah root folder, where you athlete’s folders are, so it will be rebuilt from your athlete’s config/metadata.xml on the next start.
