### ISSUE TITLE
Wrong distance when importing from fitlog file

### ISSUE THREAD

**Issue by failiz** [GoldenCheetah/GoldenCheetah#3612]
When I imported this fitlog file in GC, the distance is 415.232km when the real distance was around 8km. I imported the file to sporttracks.mobi and the distance is correct there (8.06km).
This looks to happen randomly in other files. In some of the the distance is correct, in other the distance is a couple of orders bigger than it should be.

GC version: V3.5
Build id: 3991
OS:Win

[2019-08-04_12-58-42.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5250129/2019-08-04_12-58-42.zip)

**Comment by amtriathlon** [comment]
This file has no distance or speed per sample and has gaps in recording, the specific problem seems to be related to the file containing abnormal altitude values:
```
	          <pt tm="405" lat="55.71215" lon="12.553983" ele="2" hr="0" />
	          <pt tm="406" lat="55.712163" lon="12.554007" ele="2" hr="0" />
	          <pt tm="407" lat="55.712175" lon="12.554028" ele="2" hr="0" />
	          <pt tm="408" lat="55.712185" lon="12.554053" ele="1" hr="0" />
	          <pt tm="409" lat="55.712195" lon="12.554077" ele="1" hr="0" />
	          <pt tm="410" lat="55.712203" lon="12.5541" ele="0" hr="0" />
	          <pt tm="411" lat="55.712222" lon="12.554115" ele="0" hr="0" />
	          <pt tm="412" lat="55.712237" lon="12.554128" ele="0" hr="0" />
	          <pt tm="413" lat="55.712253" lon="12.554145" ele="0" hr="0" />
	          <pt tm="414" lat="55.712272" lon="12.554163" ele="65535" hr="0" />
	          <pt tm="415" lat="55.712305" lon="12.554177" ele="0" hr="0" />
	          <pt tm="416" lat="55.712337" lon="12.554198" ele="65534" hr="0" />
	          <pt tm="417" lat="55.712365" lon="12.55422" ele="65534" hr="0" />
	          <pt tm="418" lat="55.712373" lon="12.55425" ele="65535" hr="0" />
	          <pt tm="419" lat="55.712388" lon="12.554283" ele="65533" hr="0" />
```
which provokes spikes in distance and speed computation.

Ideally you would need to import from a richer format for good results, but if this is all you have you can fix it using Edit tools:
1. Fix Gaps
2. Fix Elevation
3. Estimate Distance
4. Fix Speed from distance
