### ISSUE TITLE
Best Peak Power Indexes are missing from Banister Report

### ISSUE THREAD

**Issue by Benjih77** [GoldenCheetah/GoldenCheetah#3614]
Hi, I have noticed that some of my best "Peak Power Index" records are missing from the Banister Report. There are some examples below:

These sessions were done on the 15th and 20th Sep...
![image](https://user-images.githubusercontent.com/64849246/93722248-58620200-fb8d-11ea-801b-d84a29f2494f.png)
![image](https://user-images.githubusercontent.com/64849246/93722261-73347680-fb8d-11ea-9c67-ac8ee973f910.png)

... but I can't see them here (the last dot is for the 18th Sep:

![image](https://user-images.githubusercontent.com/64849246/93722308-a70f9c00-fb8d-11ea-91fc-a92228a4d94d.png)

**Comment by liversedge** [comment]
http://markliversedge.blogspot.com/2019/01/performance-tests-and-power-index.html
