### ISSUE TITLE
None option in Media

### ISSUE THREAD

**Issue by kub3r4** [GoldenCheetah/GoldenCheetah#3615]
It would be nice to have "None" option in "Media" (Train view), just like in "VideoSync". I sometimes do two workouts in a row. And because there is no "None" option in "Media", it plays video from previous workout, which i don't need to be played.

Or am i missing something, where i could "disable" video from previous workout?

I'm using Dev build, September 2020.

**Comment by amtriathlon** [comment]
In general, Ctrl+Click allows to deselect a selected item on single selection lists, it is a Qt feature.

**Comment by kub3r4** [comment]
Thank you for info.
