### ISSUE TITLE
Web Page Chart - More button not visible

### ISSUE THREAD

**Issue by kub3r4** [GoldenCheetah/GoldenCheetah#3617]
I noticed that downloaded train charts (ErgDB, Garmin and Training Peaks) display just a black rectangle where it should show "More".

Workout Editor which is also in download list does show "More".

I'm using Dev build Sep 23 2020 (with Live Map) in Linux.

![downloaded_train_chart](https://user-images.githubusercontent.com/70958207/94492813-68ac5980-01eb-11eb-8ba4-5afd8c51ef94.png)

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.

**Comment by amtriathlon** [comment]
It is a cosmetic issue with the Web chart in tile mode having the "more.." text without enough contrast, the text is here but it is hard to see in some color combinations, it doesn't depend on the chart being downloaded or being in Train view.

**Comment by kub3r4** [comment]
You're correct. It is because of the Theme i was using. So i guess this can be closed.
