### ISSUE TITLE
Question regarding the calculation of the power

### ISSUE THREAD

**Issue by cristianciutea** [GoldenCheetah/GoldenCheetah#3618]
My question is related with the way the power is calculated when the wind speed is taken into account:
https://github.com/GoldenCheetah/GoldenCheetah/blob/a1087c9bb39a4826e8e972457d5d830696ecb24c/src/FileIO/FixRunningPower.cpp#L255
I'm not sure about this but, shouldn't be calculated using the cube of the wind speed e.g. `wv^3` instead of `wv^2 * V`? wv seems to take into account V and also I'm thinking about the tail wind scenario

Thank you!

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
