### ISSUE TITLE
Map in Video Player chart hovering above GC when there is no video

### ISSUE THREAD

**Issue by ghost** [GoldenCheetah/GoldenCheetah#3621]
I'm using Dev build Sep 28 in Linux.

Weird behavior of Map in Video Player chart. As you scroll down, map is sort of hovering above GC. It does not hide behind athlete tab, menu etc., like Video Player and other charts.

Behind map is black background because i didn't use video.

![video_player_map](https://user-images.githubusercontent.com/70958207/94987511-30987400-0567-11eb-830e-521ff60738ea.png)

**Comment by amtriathlon** [comment]
Yes, it is a known issue and we have no solution for this, but probably of little practical relevance.
