### ISSUE TITLE
Compare Broken - 3v6 

### ISSUE THREAD

**Issue by edgegit** [GoldenCheetah/GoldenCheetah#3622]
Golden Cheetah 
Build Date sep15 2020 18:52:55
Build id 4002
Version (developer build)
OS: MacOSX 10.14

Issue 1: compare window disappears when attempting to resize => no possibility to resize compare window/section
Issue 2: drag & drop workouts to compare window is completely broken => no possibility to compare workouts

After installing, I'm pretty sure it worked when I was playing around, testing the new version. Nothing I am aware of has changed since.

Other than that, I'm really happy with the release. I can confirm both Python (3.7.9) and R (3.6.2) plots are working nicely in this release.

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/issues/3285

**Comment by edgegit** [comment]
I don't agree with the closure of this topic. 

The reset layout view did not solve issue 2 

I've just lost all my custom plots due to resetting the layout! Is there a way to retrieve my Python & R code changes?

**Comment by amtriathlon** [comment]
I can reproduce the no-resize problem on Linux after adding an R chart as described in https://groups.google.com/d/msg/golden-cheetah-users/_9hW4aayxEs/Q2LCovOEAwAJ, current workaround is to switch to Tile Mode and back to Tab mode.

**Comment by nenadjev** [comment]
> Issue 1: compare window disappears when attempting to resize => no possibility to resize compare window/section
> Issue 2: drag & drop workouts to compare window is completely broken => no possibility to compare workouts

I can confirm both Issues

**Comment by amtriathlon** [comment]
> > Issue 2: drag & drop workouts to compare window is completely broken => no possibility to compare workouts
> 
> **I can confirm Issues 2.**
> 
> After layout reset I am able to resize compare window/section

I would be useful if you or the OP can give more information s.t. versions used, how the issue manifest and steps to reproduce it.

Currently this issue is open only due to issue 1, I cannot reproduce issue 2.

**Comment by nenadjev** [comment]
Shoud I oppen new Issue? 

![image](https://user-images.githubusercontent.com/11903273/102622317-20913900-4141-11eb-941a-7222b6d66f89.png)

**Comment by amtriathlon** [comment]
Which is the issue exactly and which are the steps to reproduce it?

Just saying it is broken is not very helpful.

**Comment by nenadjev** [comment]
When I try to drag & drop activities to compare it GC has been crashed.

**Comment by amtriathlon** [comment]
Since it is not a general problem it may be related to specific data or chart, for further investigation we would need to understand under which conditions it happens. Starting with a new athlete and a couple of files would be useful, if you can reproduce the problem in that conditions please upload the files.

**Comment by nenadjev** [comment]
OK. I made new athlete and I imported couple activities. Comparation between activities or comparation between laps working with new athlete, but still not working in my profile. Also comparation is working on trends page, not working on activities page on my profile.

Any idea how to solve this?

**Comment by amtriathlon** [comment]
There are some ideas in FAQs to clean your data and we have a users forum for support: https://groups.google.com/g/golden-cheetah-users, better to discuss options there.

**Comment by nenadjev** [comment]
I just cleared Cache folder in my profile and now is working nice.

Maybe you can add option Clear Cache in GC.

**Comment by amtriathlon** [comment]
> I've just cleared Cache folder in my profile and now is working nice.

Do you mean cache or temp/Cache folder?

**Comment by nenadjev** [comment]
cache folder

...\GoldenCheetah\"athlete"\cache

**Comment by amtriathlon** [comment]
Update: the compare not working can be reproduced when trying to drag activities from the activities list in Activities view, drop over compare pane is forbidden, as detailed in https://groups.google.com/g/golden-cheetah-users/c/NDXjBtLUCnw/m/xp0uq9b-BAAJ
It seems to be a Qt bug, the workaround is to drag&drop ‘Entire Activity’ Interval from intervals list.

**Comment by amtriathlon** [comment]
An additional problem is dropped intervals are removed from the intervals list and date ranges dropped in Trends view loose their name, the only way to recover them is restarting GC.
