### ISSUE TITLE
Python Chart GC series for Power Phase mixed up

### ISSUE THREAD

**Issue by tjeerd-tx** [GoldenCheetah/GoldenCheetah#3625]
Returned data for GC.SERIES_RPPB, etc is not always correct.

Here is an example activity and Python Chart:
[Cycling Dynamics activity and chart.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5342752/Cycling.Dynamics.activity.and.chart.zip)

For this activity file this is what happens:
SERIES_RPPB seems to return LPPB value
SERIES_RPPE seems to return LPPE value
SERIES_LPPB returns 0 value
SERIES_LPPE seems to return RPPB value
SERIES_RPPPB seems to return LPPPB value
SERIES_RPPPE seems to return LPPPE value
SERIES_LPPPB seems to return RPPPB value
SERIES_LPPPE seems to return RPPE value

How it gets mixed up seems to be dependent on what values are present in the activity. I've seen another where PCO is returned for LPPE.

**Comment by amtriathlon** [comment]
GC.SERIES_LPCO=40 is missing before: https://github.com/GoldenCheetah/GoldenCheetah/blob/1023e599a092558c0e797a9fe0ba019c4d485dfb/src/Resources/python/library.py#L122
compared with
https://github.com/GoldenCheetah/GoldenCheetah/blob/1023e599a092558c0e797a9fe0ba019c4d485dfb/src/FileIO/RideFile.h#L215

This explains the following series are displaced, but not a random behavior.
