### ISSUE TITLE
Interval metrics in formulas for overview and User Charts

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#3626]
It would be interesting to have the equivalent of R/Python APIs:

1. activity.intervals
2. season.intervals

in GC formulas to be able to plot interval metrics in the new User Charts.

**Comment by liversedge** [comment]
Yes, the problem is we don't have the equivalent of a dataframe and since they can overlap we would need to return start, stop, name independently (we also could not return a vector with start, stop, name as values at idx 0,1,2 either because we need to coerce all vectors with strings in them to contain only strings.

e.g.
```
## get vectors
starts <- intervals(start); # return list of start indexes for intervals
stops <- intervals(stop); # return list of stop indexes
names <- intervals(name); # return list of names
```

Hope that makes sense?

**Comment by amtriathlon** [comment]
Yes, agree. I was thinking in the same line plus metrics values s.t.:

`Duration` <- intervals(Duration)`

**Comment by liversedge** [comment]
Oh yes, that would be slick.

**Comment by amtriathlon** [comment]
From #3910 we also need:
* is a performance test
* type (peak power, user)

and we also have
* color
* route

Lastly `interval(selected)` could be interesting to be able to restrict displayed data to selected intervals.

**Comment by amtriathlon** [comment]
`intervals(symbol|name|start|stop|type|test|color|route|selected|date|filename [,start [,stop]])
` returns a vector of values for the metric or field specified for each interval, if no start/stop is supplied it uses the currently selected date range, or activity when no date range.

`intervalstring(symbol|name|start|stop|type|test|color|route|selected|date|filename [,start [,stop]])` same as intervals above but instead of returning a vector of numbers, the values are converted to strings as appropriate for the metric (e.g. Pace_Rowing mm:ss/500m).

Both metricname and metricunit now support name, start, stop, type, test, color, route, selected, date, filename,
in addition to metric names and date, to get corresponding localized string.

Example program to build an intervals table in Activities displaying all intervals for selected activity,
similar to the one in RideSummary:

```
{

names {
    metricname(name,
               Duration,
               Distance,
               Pace,
               xPace,
               Average_Heart_Rate
               );
}

units {
    metricunit(name,
               Duration,
               Distance,
               Pace,
               xPace,
               Average_Heart_Rate
               );
}

values {
    c(
      intervalstrings(name),
      intervalstrings(Duration),
      intervalstrings(Distance),
      intervalstrings(Pace),
      intervalstrings(xPace),
      intervalstrings(Average_Heart_Rate)
      );, 
}

}
```

Next step would be to add a legacy program to Activities Overview, for Trends there was no equivalent in Summary, but it can be used much like the activities list, for example to show segments in the season.

**Comment by liversedge** [comment]
THIS IS TERRIFIC.

Being able to look at intervals across an entire season and filter them, chart them etc will be incredible. Then add in being able to click thru to activity. We considered adding an intervals view for this, but now we don't need it.

Great job

Thank you
