### ISSUE TITLE
REST API 3.6-DEV

### ISSUE THREAD

**Issue by olesendan** [GoldenCheetah/GoldenCheetah#3627]
On GoldenCheetah_3.6-DEV_x64.AppImage The REST API only returns the open athlete when I call the following from R

````
httr::GET("http://localhost:12021/")
````

From the wiki, my understanding is that the API should return all athletes. 

If I call the API for a athlete directly, evn if the athlete is not open, the metadata is returned.

````
httr::GET("http://localhost:12021/john-doe/")
````

So it seems that the REST API can access the data, but do notreturn all athletes as expected.

Am I doing something wrong?

Greetings from Denmark

**Comment by amtriathlon** [comment]
The problem seems to be the code expect Sex for the athlete is set, otherwise it is ignored:
https://github.com/GoldenCheetah/GoldenCheetah/blob/c52d260949db4120bbfef709f2147eee6f3d8cba/src/Core/APIWebService.cpp#L178

**Comment by amtriathlon** [comment]
There is an additional problem with the REST API: the code was not updated to look for the relocation of metadata.xml introduced when global settings were separated from athlete settings.
