### ISSUE TITLE
copying trend charts

### ISSUE THREAD

**Issue by MaxLaturte** [GoldenCheetah/GoldenCheetah#3631]
Hi,

I didn't find anything related to the issue I'm facing
Each time I open an athlete profile, the whole trend charts are duplicated.
For exemple my chart named "Tracker" is duplicated in a new tab. It consequently slows a lot the opening of the "Trends" window (and it's exponential with few athletes profiles openings... ^^)
I first experienced this issue when i tried dev3.6 version in September. I cleaned the tabs for one athlete and i copied the .xml file in other athletes root folder to correct for them.

I tried to go back to 3.5 version and I have the same issue. Anyone noticed that ?

Regards,*
MaxLaturte.

**Comment by MaxLaturte** [comment]
I'm working on Win64 version of 3.6 dev

The bug sometimes remain when I go back on 3.5version and appears again if I switch again on 3.6v after a few complete start & stop of the software.

I have 14athletes profiles and few downloaded R & Python additionnal charts and also my own created R Charts.

Hope it can help, thx for your amazing work !

**Comment by MaxLaturte** [comment]
Hi guys,

I guess I found the origin of this behaviour.
The problem occurs when you have "startup automatic import" in an athlete settings. (I had the same behavior with Strava & Today's Plan sync).
When you open an other athlete's tab, it automatically syncs the last rides, but it also copies all the charts. So if it syncs 3 rides, it copies 3times all the charts, and again if you open it an other time with again fews rides. So it becomes quickly exponential.

The only way to fix it is to stop automatic sync for my whole athletes profiles.

I searched in .xml files in config folder if there is something whom start this behavior, but didn't find anything.

The issue still occurs when I go back in v3.5 (but I also copied few of my config layouts to keep my settings). One of my colleague don't have this problem, even if we share our config files to work with same settings, but he never worked with v3.6 and is still on v3.5.

I hope it can help !

**Comment by amtriathlon** [comment]
> The problem occurs when you have "startup automatic import" in an athlete settings. (I had the same behavior with Strava & Today's Plan sync).
> When you open an other athlete's tab, it automatically syncs the last rides, but it also copies all the charts. So if it syncs 3 rides, it copies 3times all the charts, and again if you open it an other time with again fews rides. So it becomes quickly exponential.

Let me try to understand: does this happen only when you open an athlete with automatic download in an additional tab or does it also happen when you open that athlete as the first one at startup?

**Comment by MaxLaturte** [comment]
It both happens when I open an athlete tab with auto download & when first one startup.

But I don't have always the athlete's choice window at first start up (only after a crash), after it always startup with opening the first athlete I opened after last crash.

**Comment by amtriathlon** [comment]
In v3.6 you can let the option `start with last opened athlete` unchecked for GC to start with athlete selection

**Comment by amtriathlon** [comment]
> One of my colleague don't have this problem, even if we share our config files to work with same settings, but he never worked with v3.6 and is still on v3.5.

Are there other differences, s.t. athlete's library location (as reported in About dialog) or shared use by other GoldenCheetah instances?
