### ISSUE TITLE
Countdown to start workout

### ISSUE THREAD

**Issue by michelrdagenais** [GoldenCheetah/GoldenCheetah#3632]
The keyboard / mouse may not be available when on the bike. Thus, the workout clock may start before you are installed on the bike. Other training software like Tacx have a countdown feature. It should be optional and could be programmable (how many seconds). Another option could be to start the workout clock as soon as the wheel moves...

**Comment by human705** [comment]
I've used an app in the past with a similar feature that combines your 2 options. As soon as the wheel moves, you get a popup with a 10 second timer. The popup has 2 options, "warmup" and "start workout". The "start workout" option is selected by default when the timer runs out. If you click on the "warmup" option first, the popup stays and it shows you a timer (mm:ss) so you'll know how long you've been warming up. When you are ready you click the "start workout" button. When the workout ends you get another popup with a "cool down" and "end workout" options. At that point you have 3 seconds to go to "cool down" or the workout is over.

I found the 3 second delay for cool down too short. I'd like at least 5 or even 10 seconds. I think this will work good if there is no keyboard/mouse available. Also, if you have a keyboard/mouse you can control the options. I would also add a popup in the event the wheel stops in the middle of the workout defaulting it to pause after 5 seconds. Also, give the user the option to end the workout.

I should mention that the warmup, workout and cool down sections of the ride are saved in 3 different files.

**Comment by amtriathlon** [comment]
There is a related issue on wu&cd https://github.com/GoldenCheetah/GoldenCheetah/issues/1689

**Comment by adutton** [comment]
An alternative to this that I've seen is:
1. Training session initiated by user via keyboard/mouse
2. Message the user - "Start pedaling to begin warmup"
3. Once pedaling is detected (> 0 rpm or > 0 watts), message changes to "Stop pedaling for 10 seconds to begin ride"
4. Once 10 seconds of no pedaling (0 rpm or 0 watts) has been detected, begin ride session

This lets you choose to warmup or just ride without having to input anything, and it guarantees you are connected and sending power/cadence before starting a session.  I think this is superior to what's been mentioned before.
