### ISSUE TITLE
Athlete birth year limit 2 digits

### ISSUE THREAD

**Issue by PedroDives** [GoldenCheetah/GoldenCheetah#3635]
Athlete Date of Birth limit 2 digits does not allow for people born before 2000.  Example birth yr 1959 shows as 2059.   Lesson we learned back in Y2K.

**Comment by amtriathlon** [comment]
Date format is default for your system, the calendar pop-up allows to select pre 2000 dates:

![image](https://user-images.githubusercontent.com/1444784/96348510-b6e0aa00-107f-11eb-900c-73efc4d17306.png)

**Comment by PedroDives** [comment]
Thanks for the speedy reply.  I searched for an existing bug entry that covered this but found none.  Did I not search incorrectly?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by amtriathlon** [comment]
The users forum is the place to ask usage questions like this when you can't find the answer in the wiki: https://groups.google.com/forum/#!forum/golden-cheetah-users
