### ISSUE TITLE
Make the text in the python and R console selectable

### ISSUE THREAD

**Issue by MeisterP** [GoldenCheetah/GoldenCheetah#3637]
Currently, people have to post screenshots of error messages (eg. https://groups.google.com/d/msg/golden-cheetah-users/5haDQ5TUAH8/97NRJjLBBAAJ)
Having the error messages (or the output in general) selectable and be able to copy it would be way more convenient.

**Comment by amtriathlon** [comment]
Try using the standard shortcut (Ctrl+A)

**Comment by MeisterP** [comment]
Ctrl+A is working indeed, but Ctrl+C not. So copying is not possible.
This is a duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/2543

**Comment by amtriathlon** [comment]
Ctrl+C is used for interruption, but Ctrl+Insert works for copy.
For the whole list see https://doc.qt.io/qt-5/qtextedit.html#editing-key-bindings
