### ISSUE TITLE
Problem Modell no data n.v. 

### ISSUE THREAD

**Issue by andysaty** [GoldenCheetah/GoldenCheetah#3638]
Hello,

on my activity is no showing data in modell. shows only n.v.

what is the problem?

please help... no solution with delete teh activity
![Screnn](https://user-images.githubusercontent.com/73339019/96991910-72468a00-1529-11eb-989c-286751aa8d09.JPG)

best regards andy

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
