### ISSUE TITLE
Elite Turbo Muin Speed v3.6 Sep 2020

### ISSUE THREAD

**Issue by G1032** [GoldenCheetah/GoldenCheetah#3640]
Current speed incorrect for Elite Turbo Muin
Probably 10x faster than actual
100rpm in 39x12 is over 200km/HR
Wheel circumference set correctly
Selecting either Turbo Muin 2013 or 2015 for preset virtual power curve doesn't fix. 
No issues with speed on version 3.5

**Comment by amtriathlon** [comment]
This is a bug in Add Device Wizard, likely introduced with the new virtual power curves feature: when you use a custom wheel perimeter as required for this trainer, instead of select an standard rim/tire combination, wheel size is set to zero for the newly created device.
