### ISSUE TITLE
GoldenCheetah_v3.6-DEV2009_ x64.AppImage not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by twillis449** [GoldenCheetah/GoldenCheetah#3642]
When I run this version of GoldenCheetah on Ubuntu 18.04 it works fine. When I run it on Ubuntu 20.04 and click on the 'Power' button I get the error message 'Cannot open Ant + device' , so somehow my ANT + sensor is not being seen on this version of Ubuntu, whereas it is with Ubuntu 18.04
My computer system is a Dell Latitude E6540. I'm not sure if this is just a configuration error on my part or an actual bug  ...
Thanks
Tony Willis

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
