### ISSUE TITLE
Coros Pace 2 Activity Issues

### ISSUE THREAD

**Issue by david-chaves** [GoldenCheetah/GoldenCheetah#3645]
Hi, I just bought a new Coros Pace 2 and is importing the activities fine, however, when I started an structured training program with it, I'm having the error message "Error - local type 4 without previous definition" when I tried to import the activity files. Below I'm attaching both files, the post-workout one (since It took more than planned) and the workout itself.

[Activities.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5436711/Activities.zip)

**Comment by david-chaves** [comment]
Hi, does this means that the Coros Pace 2 watch is not using the standard fit file format?

**Comment by amtriathlon** [comment]
No, since this file is imported correctly both to Garmin Connect and Strava, likely it is using a variant not properly handled by our parser. Until this is fixed a workaround is to import to Strava a sync to GC.

**Comment by dlenski** [comment]
> Hi, does this means that the Coros Pace 2 watch is not using the standard fit file format?

https://github.com/dtcooper/python-fitparse chokes on your `/tmp/Bicicleta20201025061019.fit`.

```
$ scripts/fitdump -v -t json /tmp/Bicicleta20201025061019.fit
...
fitparse.utils.FitParseError: Invalid field size 1 for field 'data' of type 'uint32' (expected a multiple of 4)
```

It appears the fix is relatively simple.

**Comment by pR0Ps** [comment]
@david-chaves Would you be alright with your file being added as a test case in the `python-fitparse` repo?

**Comment by david-chaves** [comment]
Yup, no problem, go ahead

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by fulalas** [comment]
I also have a Coros Pace 2 and even using current Dev build (June 8, build 4004) it still doesn't import FIT files, returning the error that OP reported. Both Strava and many online converters (example: https://www.gpsvisualizer.com) import Coros FIT files just nice.
