### ISSUE TITLE
Thank you very much for the free open source program!

### ISSUE THREAD

**Issue by s-r-grass** [GoldenCheetah/GoldenCheetah#3646]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B/goldencheetah-%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85.html).

The project is interesting, so please don't abandon it!

**Comment by kub3r4** [comment]
Hey  s-r-grass,

This site is for issues and feature requests only. You can join google user group (forum) for posts like this one.
Here is link: https://groups.google.com/forum/#!forum/golden-cheetah-users

And project looks very much alive. So i don't think it will be abandoned any time soon.
