### ISSUE TITLE
Distance remaining for distance/slope workouts

### ISSUE THREAD

**Issue by ghost** [GoldenCheetah/GoldenCheetah#3648]
Would be nice to have Distance remaining for distance/slope based workouts.
It would be more or less the same as "Lap distance remaining" for crs workouts.

I mentioned it on forum a while ago. So i'm just adding feature request.

**Comment by amtriathlon** [comment]
For crs files a meta-lap is added to the end for this purpose:
https://github.com/GoldenCheetah/GoldenCheetah/blob/eb6f111a0d1b46e8e2bf5f52f62db96b85109cda/src/Train/ErgFile.cpp#L688
I think we should do the same with the newly added distance based formats to enable Lap Distance Remaining for them.
