### ISSUE TITLE
Enable reordering of defined filters ("namedsearches")

### ISSUE THREAD

**Issue by ward** [GoldenCheetah/GoldenCheetah#3656]
I am able to reorder them by editing the xml file in `config/namedsearches.xml`, but that is not very user friendly. An up/down button in the "Manage filters" dialog box could be sufficient, dragging them up or down would also work.

**Comment by ward** [comment]
I created a PR that adds an up/down button https://github.com/GoldenCheetah/GoldenCheetah/pull/3657

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/e05cf52446309c01656e129d063218c933d2b5dd
