### ISSUE TITLE
Applicytion crashes/hangs when trying to add a Kettler Racer S

### ISSUE THREAD

**Issue by christophgasser** [GoldenCheetah/GoldenCheetah#3658]
GC 3.5
OS: Windows 10
Connection type: Bluetooth (to COM port COM5)
The moment I click "Kettler Racer" to add the device, the app freezes. Have to kick it using the task manager,

Bluetooth connection seems to be OK (connection is working with Kettler World Tours).

Any idea?

**Comment by amtriathlon** [comment]
GC v3.5 doesn't even support Bluetooth, I would suggest to see the FAQs and use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
