### ISSUE TITLE
connect GoldenCheetah with FE-C to smarttrainer like Wahoo Kickr

### ISSUE THREAD

**Issue by roadrunnerspeedygonzales** [GoldenCheetah/GoldenCheetah#3659]
i would like to suggest a new function. It should be possible in goldencheetah to communicate with smarttrainers using the FE-C protocol and to control the smarttrainers regarding real life videos and variable resistance

**Comment by amtriathlon** [comment]
This is already implemented long time ago, see the wiki (https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-TRAIN#train) and use the forum if you have questions.
