### ISSUE TITLE
Mine Route, Segment, String Data from TTS Files

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3667]
TTS Files have rich route name, route description, and may have richly described segments. Currently all ignored by the tts reader. We should process these and bubble them up so available to ergfile parser.

**Comment by ericchristoffersen** [comment]
Currently ergfile have a route name and route description slot, so they can be populated immediatelly. Not sure how to bubble segments up into train mode. Appears the segments are used in tacx software to easily select pieces of very long files (>200km.)

**Comment by amtriathlon** [comment]
Laps in ErgFile could be a good mapping for segments, name is displayed on bottom bar when entering a lap and there is logic for moving to next lap & previous lap

**Comment by ericchristoffersen** [comment]
> Laps in ErgFile could be a good mapping for segments, there is logic for moving to next lap (FfwdLap). Texts are useful to show information while training, they are being used to show lap names from json files.

Woo. Good idea I'll give it a shot.

**Comment by ericchristoffersen** [comment]
Ok, pushed new commit. I populate ergfile texts and laps. This led to fixing some problems with how laps were handled:
- only update lap time stuff when in ergo mode
- recalc lap metrics during fwd and rew.

As far as I can tell laps work ok now in slope mode.

The display of lap names is awful though. Needs a serious redo because they names are printed over each other. The tts segments can be fully or partially overlapped. Maybe a project-type view with bars for each segment?

![routenameproblem](https://user-images.githubusercontent.com/46055145/99472579-c745a800-28fd-11eb-8c9c-38cb73747f7e.JPG)

**Comment by amtriathlon** [comment]
I added a button to Train bottom for FFwdLap method, it may be useful to play with this feature, also added lap markers from json files which makes easy to mark points where you may want to fast forward, s.t. climb starts.

**Comment by ericchristoffersen** [comment]
Cool! Don't forget a "rwndLp" button too. No doubt folks will wish to replay their favorites. Hey in a different thread someone suggested we autogenerate lap markers for climbs. I think thats such a good idea. We could follow the uci categorization rules. What do you think?

**Comment by ZajtiM** [comment]
@ericchristoffersen  are segments in TSS considered as laps? because i have few TSS files in which i can't pass certain segments with Next lap button. I can attach them later if you want.

**Comment by amtriathlon** [comment]
> Cool! Don't forget a "rwndLp" button too. No doubt folks will wish to replay their favorites.

Yes, we may add it if this feature proves to be useful.

> Hey in a different thread someone suggested we autogenerate lap markers for climbs. I think thats such a good idea. We could follow the uci categorization rules. What do you think?

For activities we already have climb detection, so for gpx/epm files it would be easy to import with auto detection enabled, smooth altitude and export as json including the relevant intervals, no sure how relevant is this for TTS or other formats.

**Comment by ZajtiM** [comment]
@ericchristoffersen  i noticed i can't pass a segment with "Next lap" button in two TTS files. I attached zip with both TTS files with this problem.
I don't know if is something wrong with TTS files, but everything else looks ok when selected.

To get to next segment with "Next lap" you need to pass the segment (that you're stuck at) by using "Fast forward" or by riding past it. And then "Next lap" will jump to next segment again.
Like i said. I'm not sure if is bad TTS file or some bug for some TTS files.
[TTS_nextLap_problems.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5568939/TTS_nextLap_problems.zip)

**Comment by ericchristoffersen** [comment]
> For activities we already have climb detection, so for gpx/epm files it would be easy to import with auto detection enabled, smooth altitude and export as json including the relevant intervals, no sure how relevant is this for TTS or other formats.

That climb detection is after the ride has been ridden, so too late to enjoy during the virtual ride. Maybe run a general recognizer pass as part of all ergfile load. I don't think I'd be offended if a bunch of uci classified climbs appeared on a ride because no ride will have more than a handful. I definitely would mind if every little climb on a rolling route was given a lap.

**Comment by ericchristoffersen** [comment]
> @ericchristoffersen i noticed i can't pass a segment with "Next lap" button in two TTS files. I attached zip with both TTS files with this problem.
> I don't know if is something wrong with TTS files, but everything else looks ok when selected.
> 
> To get to next segment with "Next lap" you need to pass the segment (that you're stuck at) by using "Fast forward" or by riding past it. And then "Next lap" will jump to next segment again.
> Like i said. I'm not sure if is bad TTS file or some bug for some TTS files.
> [TTS_nextLap_problems.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5568939/TTS_nextLap_problems.zip)

Its not your file. The concept of route distance is total rube-goldberg device in current code. I've been trying to get it untangled for 6 months.

Ale, can you please have another look at #3442? The lap fwd works fine there.

I'm going to push yet another merge conflict update to 3442. Try it you'll see the lap seek works properly and its much simpler because location is maintained in a single field in a single thread.

**Comment by ericchristoffersen** [comment]
Ok I've rebased the merge conflict, implemented a RewindLap and pushed the update to #3442 
I play with the exact lap limits so that rapid fire ffwd works. Also for slope mode it seeks to just before 10 meters ahead of lap start so the lap update text message triggers.

**Comment by amtriathlon** [comment]
Ok, I will take a look in the next few days, if it fixes otherwise hard to fix issues, we are talking ;-)
