### ISSUE TITLE
Workout Editor and training mode not working properly using .mrc and .erg-files

### ISSUE THREAD

**Issue by Bavarian-Barbarian** [GoldenCheetah/GoldenCheetah#3675]
Hi all,

i think in found a bug in DEV2009_x64.

When selecting an mrc file, the intervalls are not shown correctly. 
This happens when the %FTP defined in the mrc file are converted into absolute power.
for me, the Property-editor shows numbers with up to one decimal places.
Removing the one decimal place with the period, the intervals are shown correctly.
Also: Saving with the period leads to a crash.

Similar behaviour for erg files (the period seems to be the problem).

Software is running on Ubuntu 20.04.

**Comment by amtriathlon** [comment]
Can you attach zipped sample files to reproduce the issue?

**Comment by MeisterP** [comment]
As reported on golden-cheetah-users, the same happens with zwo files.
[test.zwo.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/5579608/test.zwo.txt)

**Comment by Bavarian-Barbarian** [comment]
Hi,

first of all: Thanks for the fix :+1: 

rounding works so far, but another issue came with that.
I think the problem is the rounding itself. I think it makes sense, to round up, if >=x.5, round down if <x.5.
-> no "normal" integer round, where the fractional part gets lost.

I had the issue where i opened the workout. 
E.g. An interval had 300W.
After saving and opening it had 299W.
Opening, saving and opening again: 298W
Opening, saving and opening again: 297W
and so on..

Build from 3 Dec 2020 Id 4002

Maybe someone else can verify that problem?
