### ISSUE TITLE
Lap taken form device are not syncronized in ride analysis

### ISSUE THREAD

**Issue by Vincyc77** [GoldenCheetah/GoldenCheetah#3679]
I noticed that the data from lap are not coincident between the graphic rapresentation in "ride data tab. I set up a training with the garmin device so it automatically passes from a phase to another recording the phase as lap. When this training is downloaded the lap are reported correct but not aligned as rapresentation in the graph 
[Issue1.pdf](https://github.com/GoldenCheetah/GoldenCheetah/files/5599418/Issue1.pdf)

![image](https://user-images.githubusercontent.com/61347542/100285476-3f9d1080-2f71-11eb-9d86-5aadd76dc3b2.png)

**Comment by amtriathlon** [comment]
If you attach the file, we can try to reproduce the issue, otherwise there is not much we can do.

**Comment by Vincyc77** [comment]
Please find here the json 
[2020_11_25_13_12_03.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5609471/2020_11_25_13_12_03.zip)

**Comment by amtriathlon** [comment]
The original file is required to reproduce the issue, not the json.

**Comment by Vincyc77** [comment]
Here the original file from device.
[5885393820_ACTIVITY.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5612859/5885393820_ACTIVITY.zip)

**Comment by amtriathlon** [comment]
That FIT doesn't even correspond to the JSON you posted before. and the laps are not overlapping like the case when the activity is sync from Strava. I suggest to use the forum if you need help.
