### ISSUE TITLE
Request support for IpBike's LSS developer field.

### ISSUE THREAD

**Issue by pepelisbon** [GoldenCheetah/GoldenCheetah#3682]
IpBike has now a new .fit format with developer fields.

They are exported correctly to Stryd, Runalyze, Final Surge  websites, and to the new Fit File Repair Tool v 8.11.16 app.

Golden Cheetah doesn't render one these developer fields: Leg Spring Stiffness.
The other two, Air Power and Form Power,  are well rendered.

Attached is IpBike_1367. fit file, screenshots from IpBike_1367. fit import in Stryd, Final Surge and Runalyze  websites, and a screenshot after importing in FIT File Repair Tool v8.11.16 app, showing that LSS and the other .fit file development fields where correctly parsed. 
[IpBikeStrydDeveloperFields.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5604896/IpBikeStrydDeveloperFields.zip)

**Comment by amtriathlon** [comment]
What I can see in debug mode is the Leg Spring Stiffness detected as FloatValue type, but I don't know if this is a specific problem with this field or a general issue with FloatValue type fields.

**Comment by iforpowell** [comment]
Here is the Java code from the app writing this field.  So it is meant to be a float.

            fieldDescLegSpringStiffness.setDeveloperDataIndex((short) 1);
            fieldDescLegSpringStiffness.setFieldDefinitionNumber((short) 9);
            fieldDescLegSpringStiffness.setFitBaseTypeId((short) Fit.BASE_TYPE_FLOAT32);
            fieldDescLegSpringStiffness.setFieldName(0, "Leg Spring Stiffness");
            fieldDescLegSpringStiffness.setUnits(0, "KN/m");


            DeveloperField legSpringStiffnessField = new DeveloperField(fieldDescLegSpringStiffness, developerIdMesgStryd);


            legSpringStiffnessField.setValue(data.getStrydLss());  // data.getStrydLss() returns float.
