### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by pavlinux** [GoldenCheetah/GoldenCheetah#3683]
https://github.com/GoldenCheetah/GoldenCheetah/blob/bed5f1e82068f4f5b84d49207062119676a139c1/src/Metrics/BikeScore.cpp#L34

New https://web.archive.org/web/20120712083017/http://www.physfarm.com/bikescore.pdf

**Comment by pavlinux** [comment]
[bikescore.pdf](https://github.com/GoldenCheetah/GoldenCheetah/files/5607914/bikescore.pdf)

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/56532be1ea781cb5832177b42b114aeb72138286
