### ISSUE TITLE
W'bal live graph in train mode doesn't match with activity log graph

### ISSUE THREAD

**Issue by jransp** [GoldenCheetah/GoldenCheetah#3684]
It seems that while in live train mode W'bal is being calculated and graphed with INTEGRAL formula but the activities log and the graph is being calculated and graphed with DIFFERENTIAL formula.

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
