### ISSUE TITLE
Power Curve for Elite Volare Mag basic trainer

### ISSUE THREAD

**Issue by piggz** [GoldenCheetah/GoldenCheetah#3687]
Hi

I would like to use GC with my basic trainer and a speed sensor.  I requested the data from Elite and was sent the attached file.  Hopefully it can be integrated into a future version of GC.

The 5 curves are for the 5 manual resistance settings.
[Mag Speed 5 livelli.xlsx](https://github.com/GoldenCheetah/GoldenCheetah/files/5616296/Mag.Speed.5.livelli.xlsx)

**Comment by amtriathlon** [comment]
In v3.6 you can add the curves by yourself in the last step of Add Device Wizard, check the users forum for more information.
