### ISSUE TITLE
Crash when connecting prior to workout on macos

### ISSUE THREAD

**Issue by gtibbitts** [GoldenCheetah/GoldenCheetah#3693]
I'm on Catalina 10.15.7. Using a SUUNTO Ant+ usb stick. I'm using a Wahoo Kickr. When I click the power icon to prepare for a workout Golden Cheetah hangs and never responds. I have to kill it. This may be during the connect process. This happens on the June development build and the latest snapshot.

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
