### ISSUE TITLE
Can't connect to my ANT+ device on latest update of Catalina

### ISSUE THREAD

**Issue by gtibbitts** [GoldenCheetah/GoldenCheetah#3694]
I'm on Catalina 10.15.7. Using a SUUNTO Ant+ usb stick. I'm using a Wahoo Kickr. Golden cheetah is no longer able to access my ANT+ device on the latest stable build. I have removed my kickr and GC still does not detect the device.

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/wiki/ANT--and-BTLE-Troubleshooting#macos-catalina-and-usb-issues-in-modern-macs
