### ISSUE TITLE
Train - Custom virtual power curve - Creation is not enforced

### ISSUE THREAD

**Issue by erdrobert** [GoldenCheetah/GoldenCheetah#3697]
Hello!

 I am new to GC, checking out the snapshot release (build ID 4002) on Win10.
 My main interest is the virtual power curve capabilities using a speed sensor and a dumb trainer.
 It seems that whatever I set when I add a new trainer, no speed to power conversion happens.

 Steps
 -Train/Add Device/Create  custom virtual power curve
 -Speed up, activate sensor 
 -BT speed sensor data is displayed in the training view
 Result
 -Speed data is not converted to power

Note
-Using a default power curve of a Magneto results in flawless speed to power conversion.

I am really looking forward to test/use this feature, so thank you for the effort already!
Rob

**Comment by ericchristoffersen** [comment]
I am super excited that you wish to try this out!

One thing that has tripped other people up is that you need to press 'create' after you name and define the device. If you do all the setup and then click next without clicking create then it will fall back to whatever choice is in the device dropdown.

**Comment by ericchristoffersen** [comment]
I see this device in the definitions:

"Power - CYCLOPS MAGNETO PRO (ROAD)"

Is that the device that works? 

Can you share a screen shot of your virtual power setup window?

**Comment by erdrobert** [comment]
Ok, that was really simple, thank you for the tip.
I made several screenshots, however they suddenly became useless.
I forgot to create as you described.
(Btw GC crashed when I saved my curve for the first time. Not sure about the root cause though.)

I made a note in https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-TRAIN about this create pitfall.

**Comment by ericchristoffersen** [comment]
The other thing... I recently added an 'inertial moment' setting. None of the predefined trainers have it set. I'd love to start getting them defined properly. Would you be able to estimate your trainer's moment? The correct value will be one where a spindown shows almost zero watts, but not zero. Is better to estimate low and see 30 watts during a coasted spindown.

Alternatively can you tell me:
- Its shape and mass
- how many turns it takes for each revolution of your bicycle's hub

Ive got to do something about that 'create' but the qt ui feature thats supposed to support that is making me nuts.

**Comment by erdrobert** [comment]
Hello!

Could you share an address where I can send data and videos, etc?
Or I can contact you on LinkedIn (I am able to send you a message once you accept the connection).

**Comment by ericchristoffersen** [comment]
> Hello!
> 
> Could you share an address where I can send data and videos, etc?
> Or I can contact you on LinkedIn (I am able to send you a message once you accept the connection).

Eric Christoffersen (impolexg@outlook.com)

**Comment by amtriathlon** [comment]
Is there something to fix related to this issue or it was just a forum question?

**Comment by ericchristoffersen** [comment]
> Is there something to fix related to this issue or it was just a forum question?

I think we should do something to make it more clear that create button must be pressed in order to apply new power curve. Either we gray out the next if there are pending changes, popup a warning, or simply apply the curve automatically. I'm thinking that automatic create might be the easiest for user. What do you think?

**Comment by amtriathlon** [comment]
Gray out Next will likely generate a new issue... Since you need a name I think a warning when there is unsaved data indicating to finish the creation or discard would be better, after creation the new curve could be automatically selected.

**Comment by erdrobert** [comment]
As a first-time user, I just ignored clicking on create (have not even noticed tbh), went for the next step, assuming that it is going to be saved automatically. This caused me to raise this ticket.

**Comment by amtriathlon** [comment]
I find the adding of new curve creation to the form intended to select an existing curve a tad confusing, a separate form perhaps would have been better but to minimize changes, at least there should be a visual indication they are different animals (for example an horizontal line https://stackoverflow.com/questions/5671354/how-to-programmatically-make-a-horizontal-line-in-qt) and checking for unsaved changes should be added.

**Comment by ericchristoffersen** [comment]
> I find the adding of new curve creation to the form intended to select an existing curve a tad confusing, a separate form perhaps would have been better but to minimize changes, at least there should be a visual indication they are different animals (for example an horizontal line https://stackoverflow.com/questions/5671354/how-to-programmatically-make-a-horizontal-line-in-qt) and checking for unsaved changes should be added.

Well... one case in favor of the combined ui is that its handy to start with an existing curve and then modify it a bit.

I'm confused what you mean by 'line', do you mean separate the top and bottom of ui with a line?

I think most people that do this don't really care what the name of their new private personal power curve is, might be best to just give it a generic name if they don't bother. That way out of site, out of mind. We certainly don't care what the name is, only that it has one that is stored. We could even fill out the default name in create if they choose not to, so at least they'll see what they're getting.

**Comment by amtriathlon** [comment]
> Well... one case in favor of the combined ui is that its handy to start with an existing curve and then modify it a bit.

That also can be done on a separate form, anyway I am not proposing to change that

> I'm confused what you mean by 'line', do you mean separate the top and bottom of ui with a line?

Yes, some visual indication they are 2 separate parts: the top one allows to select an existing curve for use while training and the bottom one allows to create/edit a custom curve.

> I think most people that do this don't really care what the name of their new private personal power curve is, might be best to just give it a generic name if they don't bother. That way out of site, out of mind. We certainly don't care what the name is, only that it has one that is stored. We could even fill out the default name in create if they choose not to, so at least they'll see what they're getting.

I disagree, the name is useful to avoid the need of input the same data if you need to add another device using the same trainer, for example to change between ANT+/BTLE or to add additional sensors. In the future they could be shared as we do with charts or custom metrics.

**Comment by piggz** [comment]
One thing that tripped me up was the name/button being above the curve definition.  Maybe it would help if they were below, as a clue when you a filling in the form that they come after the curve creation.
