### ISSUE TITLE
Feature request - Strava commute rides filter

### ISSUE THREAD

**Issue by megachweng** [GoldenCheetah/GoldenCheetah#3700]
GC sync all activities from strava, it is greet to add a checkbox to exclude activities marked as commute in syncing dialog.

**Comment by amtriathlon** [comment]
Sync doesn't have filters and I am afraid to add them as special cases open a can of worms, user tend to have very specific ideas about what is worth to sync. A solution better aligned with the way GC works would be to add a metadata field to mark commute rides so they can be included or not in charts using filters, which are more flexible.
