### ISSUE TITLE
Feature Request:Use mapbox GL with a terrain for simulated riding

### ISSUE THREAD

**Issue by piggz** [GoldenCheetah/GoldenCheetah#3706]
Just an idea, it would be neat to use mapbox GL, either the native Qt widget, or via mapbox js in a browser instance, to simulate 3d riding along a route, similar to the current map feature, but more immersive.

**Comment by amtriathlon** [comment]
This looks interesting, the problem is a pay service so it should include the ability for the user to enter their own registration, like we do for Google maps, I will put this in the parking lot until some developer shows interest to take it.

**Comment by piggz** [comment]
Sure ... in the pure-maps application which uses mapbox, the user can add their own api key.

If i get time and inclination, I may attempt to implement this myself.
