### ISSUE TITLE
Power Zones for non Bike/Run

### ISSUE THREAD

**Issue by tfk2** [GoldenCheetah/GoldenCheetah#3707]
Currently I can only set power zones for Bike & run in Build 3991

I would like to set zones for swim (Vasa Erg) and I would imagine that there are people who want Rowing power zones both from ConceptII/PM5 and from some oar-based PMs.

FYI: Golden Cheetah does seem to correctly build a power profile for my Vasa Erg in the SWIM sport. It's just the critical power/W' data on the CP chart that shows as being wrong and I assume that traces back to the lack of a swim power zone.

**Comment by amtriathlon** [comment]
https://github.com/GoldenCheetah/GoldenCheetah/issues/3280
