### ISSUE TITLE
Honor Simulated Speed Setting in Ergo Mode

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3712]
Ergo mode is a smart trainer mode where trainer requires N watts to move, without regard to speed or cadence. Currently ergo mode in gc reports speed according to whatever trainer reports and this often just spends on what gear rider chooses for their workout. This gear choice can have the effect of significantly skewing athlete statistics.

Suggestion from Laurent on gc user group to run bicycle simulation in ergo mode so that erg mode workouts will have consistent speed and distance.

https://groups.google.com/g/golden-cheetah-users/c/o3_0vHeGc1c/m/n0490j0aCAAJ

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/603c8cd651db5d3032a7ce137c9eb5f6c96b6595
