### ISSUE TITLE
Truncate non integer watts when importing workout files

### ISSUE THREAD

**Issue by Bavarian-Barbarian** [GoldenCheetah/GoldenCheetah#3721]
Hi all,

this issue is related to #3675 (fix 8e5a2b42d0168527487b19fb25e5c22dbf4ad023)
I tried to reopen the issue, but I can't. 

The integer-conversion in the issue mentioned above works so far, but another issue came with that.
I think the problem is the rounding itself. I think it makes sense, to round up, if the values are >=x.5, round down if the values are  <x.5.
-> actually round instead of truncate the fractional part.

I had the issue where i opened the workout.
E.g. An interval had 300W.
After saving and opening it had 299W.
Open, save and reopen: 298W
Open, save and reopen: 297W
and so on..

Tested with *.erg files
It's probably the same for *.zwo and *.mrc.

I tested with the build from 3 Dec 2020 Id 4002

Thanks in advance!

**Comment by amtriathlon** [comment]
> this issue is related to #3675 (fix [8e5a2b4](https://github.com/GoldenCheetah/GoldenCheetah/commit/8e5a2b42d0168527487b19fb25e5c22dbf4ad023))

That fix only affected zwo/mrc import, erg import was not changed at all.

**Comment by Bavarian-Barbarian** [comment]
yes, you're right. it is not related.
I'm sorry.

Nevertheless, Issue does exist, when opening files and truncating the fractional part.

**Comment by amtriathlon** [comment]
So it has been this way for years and I am not sure it is really an issue nor to change truncation to rounding solves it. Have you do some tests, can you attach a useful test file, besides to repeated saving?
I mean, to use only integers watts involves some limitations, but we need to enforce this to keep workout edit capability to work with qwkcode practical, it looks like a trade off.
