### ISSUE TITLE
Linux AppImage crashes after storage dialogue with reference to Undefined symbol EVP_idea_cbc

### ISSUE THREAD

**Issue by mondjef** [GoldenCheetah/GoldenCheetah#3727]
When I try to run the AppImage I get the following error in log after app crashes after display of storage dialogue, assume it happens when main application GUI is being initialized.

./GoldenCheetah_v3.5_amd64_Linux.AppImage: symbol lookup error: /usr/lib64/libssl.so.1.0.0: undefined symbol: EVP_idea_cbc, version OPENSSL_1.0.0

I am using Gentoo linux on a laptop, could this be a missing library?

**Comment by amtriathlon** [comment]
No, that indicates that library has been build without EVP_idea_cbc.
You could try GC v3.6 snapshot build which uses OpenSSL 1.1 instead of 1.0, and to ask on users forum for feedback from Gentoo users, I have no experience with that distribution.

**Comment by mondjef** [comment]
yes, I confirm that the v3.6 works without issues.  Thanks you!  I was a bit new to these AppImages and was not sure if it was something specific to my environment or the AppImage itself as I am not really familiar with how the work and interact with the OS.

**Comment by amtriathlon** [comment]
Thanks for the feedback, glad it also works on Gentoo!
