### ISSUE TITLE
Update Fortius Support

### ISSUE THREAD

**Issue by ericchristoffersen** [GoldenCheetah/GoldenCheetah#3728]
Opening this to cover behavior reported by several fortius users, first that slope mode doesn't work right, second that erg mode itself is not correct.

After connecting with the devs on the fortiusant project it is clear that the gc code to communicate with fortius is pretty seriously broken, both in slope and erg modes.

PR #3725 is in progress now. To support fortius we must determine correct load in newtons, which requires much more than a simple gradient.

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/1b18ec7eebb65d7fc24f5debee8ca3f533ddd3b6
