### ISSUE TITLE
Edit date ranges

### ISSUE THREAD

**Issue by msporting** [GoldenCheetah/GoldenCheetah#3744]
Edit date ranges
In the German version, the date ranges with dates newer than 09.2017 can no longer be entered or edited. 
This error occurs since version 3.5 up to and with version build ID 4002.

![Date_Range](https://user-images.githubusercontent.com/6757361/103414188-2fcea880-4b7d-11eb-8e5c-a4c643f8f1d8.png)

**Comment by amtriathlon** [comment]
This is likely due to:  https://github.com/GoldenCheetah/GoldenCheetah/commit/982d357a7b2231b4a7e2bd51dad54ed3c5de42fa
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
