### ISSUE TITLE
All Sigma iD.FREE laps start at 23:59:59 and therefore overlap

### ISSUE THREAD

**Issue by ChristophWurst** [GoldenCheetah/GoldenCheetah#3746]
Hi,

I noticed a little quirk with data imported from the .fit files of a Sigmasport iD.FREE (sports watch): the laps all start at 23:59:59, hence overlap each other.

![Bildschirmfoto von 2021-01-01 19-35-56](https://user-images.githubusercontent.com/1374172/103444540-494d1e80-4c69-11eb-88db-e4612e23b7ea.png)
![Bildschirmfoto von 2021-01-01 19-35-45](https://user-images.githubusercontent.com/1374172/103444541-49e5b500-4c69-11eb-9aac-c0f043614bcb.png)

This happens with both manual and auto laps.

Today's recovery ride recordings: [sigma.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5759274/sigma.zip)

It's very well possible that the Sigma data is skewed. If I import the file into the *Sigma Data Center*, the laps show up correctly. But they might just correct for their own errors. An export as TCX and another import in GC from this alternative format gives me correct results. The laps are no consecutive, with an occasional overlap of 1s, which I don't mind:

![Bildschirmfoto von 2021-01-01 19-48-16](https://user-images.githubusercontent.com/1374172/103444690-26bc0500-4c6b-11eb-9585-eb378a043b74.png)

Here's the converted file for comparison: [sigma-tcx.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/5759292/sigma-tcx.zip)

I'm not too familiar with fit file specs, but I used some readers to gain insight into the data. The timestamps for the lap event seemed legit, so I'm not yet sure if this could be a potential bug in GC as well.

I checked the forums and apparently I'm the first one to notice this behavior. Hence I'm assuming this is either a bug in GC or incorrect data written by the Sigma device.

Cheers

![Bildschirmfoto von 2021-01-01 20-07-38](https://user-images.githubusercontent.com/1374172/103444833-08ef9f80-4c6d-11eb-8e49-c5d3d31eabcc.png)

**Comment by amtriathlon** [comment]
Lap start time is computed from the difference between the field start_time (2) in lap message (19) and  start_time (2) in session message (18), if you want to debug your file:

https://github.com/GoldenCheetah/GoldenCheetah/blob/c6c5505610ba5de93cd83e5992ff321028343331/src/FileIO/FitRideFile.cpp#L1653

**Comment by ChristophWurst** [comment]
Oh, thanks for the insights. I'll try to set up a proper dev env to be able to build GC myself and attach a debugger.

In the meantime I used fitfileviewer.com to extract those values. Apparently the laps in my file do not have a `start_time`:
![Bildschirmfoto von 2021-01-02 15-49-22](https://user-images.githubusercontent.com/1374172/103460096-dba9fc80-4d13-11eb-8656-cd17e22c07a9.png)

**Comment by ChristophWurst** [comment]
Alright, I figured out how to do this debugging.

I'm running into https://github.com/GoldenCheetah/GoldenCheetah/blob/c6c5505610ba5de93cd83e5992ff321028343331/src/FileIO/FitRideFile.cpp#L1623, which validates that the data in the table is correct and the laps do not have a start_time. As a consequence, `this_start_time - start_time` is 0 for all laps.

Now the question is, how can we work around this? Is Sigma writing incorrect fit files?

At https://github.com/GoldenCheetah/GoldenCheetah/blob/c6c5505610ba5de93cd83e5992ff321028343331/src/FileIO/FitRideFile.cpp#L1573-L1575 we read the timestamp, but we only use that for `time`. I'll have to tinker with the logic a bit to understand what the individual fields mean.

**Comment by amtriathlon** [comment]
> Now the question is, how can we work around this?

To me the question is: should we?

> Is Sigma writing incorrect fit files?

I've tried to upload the sigma.fit file you attached to Garmin Connect and it fails, Strava can import but without laps, I would suggest to report the issue to the originator.

**Comment by ChristophWurst** [comment]
I agree that it's more an issue on Sigma's end. I'll report it to them.
