### ISSUE TITLE
Build break in VideoWindow.cpp without GC_VIDEO_VLC

### ISSUE THREAD

**Issue by ChristophWurst** [GoldenCheetah/GoldenCheetah#3747]
While setting up my dev env to debug #3746 I was prompted with a compile error at https://github.com/GoldenCheetah/GoldenCheetah/blob/944f0ba73d1505b15a0a12fb0ca75f973359e94e/src/Train/VideoWindow.cpp#L460. Unlike the builds on Travis, I did not define `GC_VIDEO_VLC`, hence `m` is undeclared.

I could trace this regression back to the recent commit https://github.com/GoldenCheetah/GoldenCheetah/commit/5f68d2dce0c0e5e56c05574209d0bbd2fa077071.

@amtriathlon what shall be done when `GC_VIDEO_VLC` isn't defined? Should we always hide the live map widget in that case?

**Comment by amtriathlon** [comment]
> Should we always hide the live map widget in that case?

Yes, overlay widgets are supported only with VLC

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/d84d329a789ec8f43fec613799715bdccaccc718
