### ISSUE TITLE
Import of *.zwo-files with xml-comments does not work 

### ISSUE THREAD

**Issue by JohnReader** [GoldenCheetah/GoldenCheetah#3751]
While the workouts in Zwift are working great, an import to GC v3.5 of workouts containing xml-comments does not work. An error message get's displayed instead (no supported workous for import were found). Deleting the comments is a possible workaround, but not preferred.

Excerpt from the <workout>-block:

    
    <SteadyState Duration="60" Power="0.8" Cadence="90" CadenceLow="85" CadenceHigh="95" NeverFails="1">
      <textevent timeoffset="0" Duration="7" message="A little more..."/>
    </SteadyState>
    
    <SteadyState Duration="60" Power="0.5" Cadence="80" CadenceLow="75" CadenceHigh="85" NeverFails="1">
      <textevent timeoffset="0" Duration="7" message="Great work. Let's bring that effort and cadance down."/>
    </SteadyState>
    
    <SteadyState Duration="30" Power="0.95" Cadence="65" CadenceLow="60" CadenceHigh="70" NeverFails="1">
      <textevent timeoffset="0" Duration="7" message="Time to bring it up again. This time a bigger effort but a lower cadance."/>
    </SteadyState>
    
    <SteadyState Duration="30" Power="0.5" Cadence="90" CadenceLow="85" CadenceHigh="95" NeverFails="1">
      <textevent timeoffset="0" Duration="7" message="Sit in."/>
    </SteadyState>

**Comment by amtriathlon** [comment]
We are using a general xml parser and comments are skipped, I confirmed this adding a comment to a working zwo test file:
```
<workout_file>
	<author>Poncho (via TrainingPeaks)</author>
	<name>Sweet Spot 2 x 8 minutes</name>
	<description>2 x 8 minutes ON; 4 minutes recovery
-
Building a Hemi-Powered Aerobic Engine!
For More Information Visit:
https://www.fascatcoaching.com/tips/sweet-spot-training/</description>
	<sportType>bike</sportType>
	<tags/>
	<workout>
		<Warmup Duration="300" PowerHigh="0.6" PowerLow="0.4">
		</Warmup>
		<SteadyState Duration="660" Power="0.65">
		</SteadyState>
                <!-- Starting interval section - test comment -->
		<IntervalsT Repeat="2" OnDuration="480" OnPower="0.92" OffDuration="240" OffPower="0.7">
		</IntervalsT>
		<Cooldown Duration="300" PowerHigh="0.4" PowerLow="0.6">
		</Cooldown>
	</workout>
</workout_file>
```
and import works as expected.
