### ISSUE TITLE
Help with command line parameters....

### ISSUE THREAD

**Issue by scr142** [GoldenCheetah/GoldenCheetah#3753]
I've looked in the Wiki and still none the wiser....

So I have two versions of GC (and separate athlete data) on my machine, a stable release for every day use, and a development version, so what I want to enter two separate command lines that open the different versions and their associated athlete date, but it just doesn't seem to work...

The last open directory or athlete seems to be problematic, and GC just opens an empty select Athlete dialog, so the commands I'd like to include in my desktop icons:

Stable
C:\Program Files\Golden Cheetah\GoldenCheetah.exe D:\Quick Access\Golden Cheetah Paul

Dev:
D:\Coding\GoldenCheetah\src\release\GoldenCheetah.exe D:\Coding\GoldenCheetah\Library Paul_test

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
