### ISSUE TITLE
Golden Cheetah says 'Cannot open Ant+ device'

### ISSUE THREAD

**Issue by kirrajaye** [GoldenCheetah/GoldenCheetah#3757]
I had to get a new Ant+ stick because I lost my old one.
Last time I just plugged it into the USB port, told Golden Cheetah to find Heartrate, Cadence, and Speed, and it all happened.
No that I plugged my new Ant+stick in it keeps just saying "Cannot open Ant+ device"
I dont write code, I have no idea how to access any of that fancy stuff.
I need a very easy to follow, laymans terms solution.
Thank you in advance! :-)

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.

**Comment by kirrajaye** [comment]
Ok. Thanks.
