### ISSUE TITLE
Cannot use GoldenCheetah after failed connection

### ISSUE THREAD

**Issue by JulianGro** [GoldenCheetah/GoldenCheetah#3761]
When trying to run a Tacx Fortius, if the connection fails GoldenCheetah opens an error message. This message will just reappear when clicking okay or closing it. You cannot use GoldenCheetah when this message is open and have to terminate it using a system monitor.
![Bildschirmfoto vom 2021-01-06 18-35-05](https://user-images.githubusercontent.com/11144627/103802574-a4a75400-504f-11eb-8ae8-6090d36ba176.png)
This is version 3.5-DEV1810 from the official Ubuntu 20.04 package repositories.
I assume the connection not working is a udev rule problem, so that it might make sense to add a hint to the error message as well.

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/b2e90c0af6189d39459611a5b689cf472862d632
BTW, 3.5-DEV1810 is an old development version, you can download updated official releases from http://www.goldencheetah.org/#section-download
