### ISSUE TITLE
Garmin Connect cloud account sync: available for free now! (activities and wellness) #cloud

### ISSUE THREAD

**Issue by nitishnag** [GoldenCheetah/GoldenCheetah#3762]
from https://developer.garmin.com/gc-developer-program/activity-api/
> Access to the Garmin Connect Developer Program is free to approved business developers.

> Ping/Pull or Push Architecture: Choose the integration option that best matches your needs

 Seems like this can now be added without cost! Is it possible to include this in the next 3.6 dev release for testing?

Given that API access is now free to approved businesses and supports a pull architecture, is this something that could be reconsidered?

_Originally posted by @kevindoveton in https://github.com/GoldenCheetah/GoldenCheetah/issues/587#issuecomment-751947472_

**Comment by liversedge** [comment]
There are no APIs suitable  for a desktop or mobile app. 
The Garmin APIs are for syncing across web sites.

**Comment by liversedge** [comment]
I have also checked again with Garmin support and they have confirmed it is still a server to server protocol.

**Comment by devdems** [comment]
I'm curious why do we need to have a web server for this to work? 

The client can be built inside the GC and it will directly call Garmin's API. Why do you think this route is not ok?

**Comment by liversedge** [comment]
They only offer a push API.

When you upload to Garmin Connect they make a call to push the data to the partner site at the same time.
So you need to have a permanent and fixed site for them to call. 

They do not offer an API for a desktop or mobille app to call.

**Comment by devdems** [comment]
Ok, that's a bummer...
