### ISSUE TITLE
Cannot play video

### ISSUE THREAD

**Issue by JulianGro** [GoldenCheetah/GoldenCheetah#3763]
Trying to use a video in mpeg-4 format renders the first frame and throws a lot of errors to log:
https://gist.github.com/JulianGro/5dded3357ae2650e626d8a084175302d
This is on Linux Mint 20 (Ubuntu 20.04). Xlib is installed.
The video is using an avi container, and "non-standard way to store B-frames (packed B-frames)" according to ffmpeg. It does play fine in VLC though.
This is on the development snapshot from 2021-01-05

Same thing happens with VP9 in an mp4 container: https://gist.github.com/JulianGro/0d2542801d1c3a9115fbda79e90a70d6

**Comment by amtriathlon** [comment]
> It does play fine in VLC though.

Using which VLC version?

**Comment by JulianGro** [comment]
> Using which VLC version?

3.0.9.2 Vetinari. Both files play fine in there.

**Comment by amtriathlon** [comment]
Included vlc is 3.0.8, you can check in Help > About, it is possible to use an external vlc install as explained in the forums: https://groups.google.com/g/golden-cheetah-users/c/0v9YcH9a958/m/QuGTOSTFBwAJ

**Comment by JulianGro** [comment]
I just tried system vlc according to that forum post. Unfortunately I get the same:
```
[00007f5b2000d0b0] main filter error: Failed to create video converter
[00007f5b1804e7a0] vdpau_avcodec generic error: Xlib is required for VDPAU
```
Online sources suggest that Xlib might not be properly initialized. I am getting the same error messages as in that forum post when running 3.5 release instead of 3.6dev2009 or the 3.6 snapshot, which makes me think that this is a different issue.

**Comment by amtriathlon** [comment]
> I just tried system vlc according to that forum post.

Have you checked in Help > About > Version GC is effectively using 3.0.9.2 Vetinari

The cache and Xlib errors seems unrelated and likely harmless, they are also reported on my system with videos playing without issues.

**Comment by JulianGro** [comment]
There is no "GC" version but VLC version is reported correctly. But you saying that the errors are harmless makes me think that video playback might actually work.
I just assumed it didn't because of the errors I got on 3.5, but I am probably having a different issue at this point. I assumed that nothing was happening when trying to use the Tacx Fortius because it couldn't play the video, but I guess I am just having problems interfacing with it properly.
Anyways, I am not actually sure that video isn't working at this point so I will close this for now.
