### ISSUE TITLE
Create New Athlete...

### ISSUE THREAD

**Issue by scr142** [GoldenCheetah/GoldenCheetah#3771]
I'm looking to create a new athlete from within the latest GC development build, but I cannot find the menu or option...

**Comment by amtriathlon** [comment]
It was removed during the introduction of Athlete View starting here: https://github.com/GoldenCheetah/GoldenCheetah/commit/11092bf436ef8d1878ba64dc0e9d9cb12a136280, this is WIP and part 3 is not included yet, likely others athlete operations besides open/close, like create/remove/backup/duplicate/etc. should be part of that.
For a workaround see https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-MOST-COMMON-QUESTIONS-OF-ALL#how-can-i-open-a-predefined-athlete-or-be-prompted-to-select-one-at-startup

**Comment by scr142** [comment]
I can survive without it, I was just looking for in it response to thinking about https://github.com/GoldenCheetah/GoldenCheetah/issues/308.

**Comment by amtriathlon** [comment]
For questions we prefer to use the forums to avoid issue proliferation, we have 2 according to the kind of question: user/developer.
