### ISSUE TITLE
ARM64 appimage builds

### ISSUE THREAD

**Issue by piggz** [GoldenCheetah/GoldenCheetah#3774]
Hi

Im probably in the minority here, but it might be useful to provide ARM64 appimage  builds for linux.  This would allow easy running on eg the Raspberry Pi4 or pinebook pro laptops.  I can certainly see a usecase for running golden cheetah on a pi4 with a dedicated connection to a TV.

**Comment by amtriathlon** [comment]
AppImage build tools are available if someone is interested in to give this a try: https://github.com/AppImage/AppImageKit/releases

**Comment by piggz** [comment]
Weird how I got a duplicate ... on the first attempt github gave me a 404 so I resubmitted, ah well!

**Comment by JulianGro** [comment]
Connecting to a Linux based aarch64 Linux PC or being able to use cheap devices like a Pinebook Pro seem fairly interesting.
GoldenCheetah shouldn't need much in terms of system resources so it should run on any current SoC. Only video playback could be an issue on some of them.

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/wiki/Building-Golden-Cheetah-on-a-Raspberry-Pi-4-on-a-fresh-Raspbian-Buster-install and search the forums if you are interested.

**Comment by amtriathlon** [comment]
I am closing this since we will not generate official builds for this platforms. Interested users can do it themselves.
