### ISSUE TITLE
Brake fault with Tacx Flow Smart connected via FE-C/ANT+

### ISSUE THREAD

**Issue by RumikPro** [GoldenCheetah/GoldenCheetah#3784]
Similar to Issue #3319 but hopefully I can add some further info. Attached is screenshot showing the Ride output of a 30 minute run using a Windows laptop, Windows 10, GC build 4001 developer build, ANT+ connection with a Tacx Flow Smart trainer, the run was carried out using full screen video and Zwerschstubental.gpx, .avi and . rlv downloaded from http://rlv-alucard.de/.
Everything works well except 'Brake fault' kept coming up on screen at which point the resistance of the trainer falls and power etc. drops with it. Every few seconds the fault would disappear and the trainer resistance would rise together with power for a few seconds then repeat the sequence. The effect can be clearly seen in the Ride output screenshot.

![Screenshot (1)](https://user-images.githubusercontent.com/77486951/104713652-13ee0980-571c-11eb-9da4-e2a5268a8d16.png)

The entire hardware setup works fine with Rouvy so it seems to me that the issue lies within the GC software and the way it is sending the resistance requirement to the trainer via ANT+. I shall attempt to investigate further but welcome any help that others can give.

**Comment by amtriathlon** [comment]
There is no known solution for this issue FC-C/ANT+, the alternative is to connect via Bluetooth, latest v3.6 can control these trainers using ANT+ over BLE.

**Comment by peret2000** [comment]
Just to have it clear: it is failing with FC-C/ANT+, not only in Erg mode but also in Slope mode?
I am thinking of buying a Garmin ANT+, because I only use Slope mode; BTLE is a bit ptoblematic connecting (there is always an uncertain process until I can connect it).
I had understood the problem was only in Erg workouts and BTLE (and already corrected). If it currently happens with ANT+ in Erg mode, for me it is not blocking. But if it happens with ANT+ in Slope mode, that means that ANT+ is useless for Tacx Flux. Am I ok?
thanks!

**Comment by amtriathlon** [comment]
> But if it happens with ANT+ in Slope mode, that means that ANT+ is useless for Tacx Flux. Am I ok?

Yes, if you have a newer model (S or 2) with updated firmware, it works with the original model and firmware.
See https://groups.google.com/d/msg/golden-cheetah-users/dpD4LdcQsvc/6VyYHl-HAwAJ for details.

**Comment by amtriathlon** [comment]
Can anyone else test https://github.com/GoldenCheetah/GoldenCheetah/pull/3818 to confirm it fixes this issue?

**Comment by bodypilot** [comment]
> Can anyone else test #3818 to confirm it fixes this issue?

I can test it this weekend on Linux Mint 20.1 and Tacx Flux S Smart if someone can please explain how to implement the fix. What exactly has to be done to set the 'transmission count to 4'  in GC?

**Comment by amtriathlon** [comment]
> I can test it this weekend on Linux Mint 20.1 and Tacx Flux S Smart if someone can please explain how to implement the fix. What exactly has to be done to set the 'transmission count to 4' in GC?

No need to change anything, you can download the AppImage from the PR as explained in https://groups.google.com/g/golden-cheetah-developers/c/5fZUO9DbJDY

**Comment by peret2000** [comment]
I have tested it, just manually modifying the code.
Tested on Linux 20.10, Tacx Flux S -> Working perfectly! Slope and Ergo modes tested.
Even more: with the ANT+ CYCPLUS dongle! So, maybe CYCPLUS was not that bad; it was a matter of adapting the protocol.
Very good job

**Comment by RumikPro** [comment]
> Can anyone else test #3818 to confirm it fixes this issue?

This fix has made no difference to my issue as described in #3784. Investigation of the ANT.log indicates that the trainer is not responding to a request from ANT for the trainer capabilities but the trainer does receive and act on the Track Resistance messages (for simulation mode). Messages also seem to be telling the ANT that the trainer needs the spindown time but power calibration is OK. It is also saying that User Configuration is needed. The trainer is also sending messages that indicate that periodically the trainer has "Undetermined (maximum or minimum) target power limit reached" I assume this is what is bringing up the "Brake fault" warning on the video screen. This latter is strange since I would have thought it only applied when in target power mode whereas I am operating in simulation mode? I'll keep digging!

**Comment by RumikPro** [comment]
Just as an update to my original post of the problem. Supersmoothing the gpx files has dramatically reduced the issue of rapidly rising and falling slopes. The 'brake fault' warning still comes up on screen periodically but doesn't seem to impact the ride now.
