### ISSUE TITLE
Last xxx date range selections don't work in Trends/Summary screen for new activities

### ISSUE THREAD

**Issue by jeffbromberger** [GoldenCheetah/GoldenCheetah#3786]
Reproduction steps:

1) Go to Activity -> Import From File... and add some new activities.
2) Go to Trends section, Summary tab
3) Select any of the Last ___ filters from the Date Ranges

Result - new activities are not shown in results listed under Athlete Bests.

If I select This Year or This Month the new results **are** shown.  If I restart Golden Cheetah then the Last ___ filters **do** work and show the new activities (including highlighting the one from today's date).

So it seems newly added activities are not being considered by some filters, but are by others.  This behavior has been present for years.  Currently using build id 3991 from Jan 18 2020, Windows.

**Comment by amtriathlon** [comment]
Relative date ranges (s.t. Last XXX) has been fixed by https://github.com/GoldenCheetah/GoldenCheetah/pull/3546 for v3.6

**Comment by jeffbromberger** [comment]
Ah great, thank you @amtriathlon and sorry for the unnecessary issue!
