### ISSUE TITLE
Feature request for external video playback and vlc

### ISSUE THREAD

**Issue by erickzmx** [GoldenCheetah/GoldenCheetah#3787]
I have an issue with the support for video playback since the application does not natively detect many formats such as mp4, webm or mkv. So the proposal is if it could be possible to make playback through an external player in order to play videos with the codecs of the system itself, in this case a more recent version 3.0 instead of the distributed version 2.2.x.
I run the Linux versions, but it could also be of interest for Windows users.

**Comment by amtriathlon** [comment]
v3.6 includes vlc 3.0.8: https://github.com/GoldenCheetah/GoldenCheetah/releases, if you want to use an external vlc install search the users forum, it is explained there.
