### ISSUE TITLE
Feature request: configure the scale and range of a chart metric

### ISSUE THREAD

**Issue by Genussradler** [GoldenCheetah/GoldenCheetah#3794]
in some charts it would be helpful if the scaling could be configured.
For example, I have a chart with the Efficiency Factor, a value with only very small changes around +-0.1.
With a scale from 0 - 1.4 you can't really see the changes in the values (first picture)
So if I could configure the scaling and the range of a certain metric I could create a better chart.
In my example I would configure a range between 0.9 and 1.5 with a scaling of 0.05 (second picture)

I know I can adjust the scaling in the chart but this always gets lost when I leave the chart. And it's a little bit annoying to adjust it every time I look at the chart.

![grafik](https://user-images.githubusercontent.com/35425767/105205952-17cbc280-5b46-11eb-8f44-e7c7771e0e11.png)

![grafik](https://user-images.githubusercontent.com/35425767/105207194-85c4b980-5b47-11eb-8df8-186b84e105e7.png)

**Comment by amtriathlon** [comment]
This request has been made repeatedly, let’s keep one instance https://github.com/GoldenCheetah/GoldenCheetah/issues/2044
