### ISSUE TITLE
Altitude not updated when seeking forward/backward in a .pgmf file

### ISSUE THREAD

**Issue by michelrdagenais** [GoldenCheetah/GoldenCheetah#3805]
With some types of workout files like .pgmf, the altitude is computed incrementally from the slope in TrainSidebar.cpp. When seeking forward or backward (by 1km), this is not taken into account to update the altitude. It seems that the ErgFile structure now already computes the altitude from the slope at reading time. It should be possible to access the altitude with a new function AltitudeAt, modeled after ErgFileQueryAdapter::gradientAt?

**Comment by mattipee** [comment]
I have a small .crs file I use for testing. I can confirm than fast-forwarding through that file does not update altitude.

By adding altitudeAt() alongside gradientAt() as you suggest, it indeed now updates altitude when seeking forward/backward.

So +1 from me, and it appears to be simple to implement.

**Comment by michelrdagenais** [comment]
We could probably extend gradientAt to provide the altitude as well. GradientAt is only called at two places. This would avoid traversing twice the ErgFile, once for the .val member (gradient) and once for the .y member (altitude), for the point corresponding to that displayDistance. All CRS files now appear to have the altitude anyway. In the worst case, it is a relative altitude derived from the accumulated gradient. Doing it in this way would be a very small PR.
