### ISSUE TITLE
Disable Erg control in watt-based workouts

### ISSUE THREAD

**Issue by tolgraven** [GoldenCheetah/GoldenCheetah#3810]
I need this feature for a specific purpose (buggy Bkool trainer firmware with broken Erg mode) but since most all other apps have this option I figure it might be worth trying to implement properly rather than just make my own patch.

Would there be interest in having this? And which files/classes in Train would be the relevant ones to start working on this?

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-developers to ask questions or get help.
Thanks.

**Comment by tolgraven** [comment]
So I take it the answer to "Would there be interest in having this?" is no. How come, though?
Will just make a personal quick and dirty patch then.

**Comment by amtriathlon** [comment]
I think the answer is clear, we use issues for tracking and forums for questions and discussions.
