### ISSUE TITLE
Support for Garmin Forerunner 35 over Bluetooth

### ISSUE THREAD

**Issue by gitdevmod** [GoldenCheetah/GoldenCheetah#3811]
Reading code I do not see if GC supports fetching data from Garmin Forerunner 35 over Bluetooth.
Does GC can fetch data over Bluetooth on this device ?
Thanks

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-developers to ask questions or get help.
Thanks.
