### ISSUE TITLE
SPEED problem in Training Mode

### ISSUE THREAD

**Issue by Guyuflo** [GoldenCheetah/GoldenCheetah#3816]
Hardware: Tacx neo2 connected to a Mac via bluetooth.

The speed drops to 0 for a few seconds and marks the real one for an instant. Average speed drops and track tracking becomes impossible.
Thanks!!

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
