### ISSUE TITLE
Feature: Allow the API Keys to be entered in a configurationfile too

### ISSUE THREAD

**Issue by worldcitizen** [GoldenCheetah/GoldenCheetah#3817]
Allow the API to be added to an external configuration file.
Currently it like this. https://github.com/GoldenCheetah/GoldenCheetah/wiki/Strava-configuration

I package Goldencheetah for openSUSE, It would be ideal that a user can use her/his own API Key.

Issue tracker is **only** for Bugs and Features, before to open a new issue please read the contributing guidelines (link below).

If you need help or technical support please see the wiki and use the forums:
Users: https://groups.google.com/forum/#!forum/golden-cheetah-users
Developers: https://groups.google.com/forum/#!forum/golden-cheetah-developers

**Comment by amtriathlon** [comment]
> Allow the API to be added to an external configuration file.
> Currently it like this. https://github.com/GoldenCheetah/GoldenCheetah/wiki/Strava-configuration
> 
> I package Goldencheetah for openSUSE, It would be ideal that a user can use her/his own API Key.

Sorry, but I fail to understand how to register as a Strava developers could be ideal for end users, especially when they can just download a build with all services enabled as explained in https://github.com/GoldenCheetah/GoldenCheetah/wiki/FAQ-GENERAL#for-which-operating-systems-are-binary-distributions-available

> Issue tracker is **only** for Bugs and Features, before to open a new issue please read the contributing guidelines (link below).
> 
> If you need help or technical support please see the wiki and use the forums:
> Users: https://groups.google.com/forum/#!forum/golden-cheetah-users
> Developers: https://groups.google.com/forum/#!forum/golden-cheetah-developers

Please use developers forum to discuss alternatives.
