### ISSUE TITLE
External API to connect Home Assistant

### ISSUE THREAD

**Issue by eerke2021** [GoldenCheetah/GoldenCheetah#3829]
Hi,

this is a feature request but it might already exist and I haven’t found it yet: is there an external API for training mode? 

I’m thinking to read a metric, such as heart rate, power, W’ etc. using calls from Home Assistant to your external API. I personally use a Rasperry Pi 3B running HASSIO but lots of people use virtual machines. You could then use the metric(s) to trigger events to start fans, change lighting, turn on dehumidifiers, open blinds etc. 

What do you think?

**Comment by amtriathlon** [comment]
There was a similar request some years ago: https://github.com/GoldenCheetah/GoldenCheetah/issues/1812

**Comment by eerke2021** [comment]
It says it was closed on the 5th of August 2016. Was it closed because it is implemented?

**Comment by amtriathlon** [comment]
No, it was dismissed.

**Comment by eerke2021** [comment]
Why? Their suggestion is to actually push information to a variety of specific places which might change over time using a specific protocol which might also change. That does seem complicated and liable to fail over time. Mine would be to answer generic requests for data locally using your own interface. There was a lot less home automation back then. Now you could provide an interface so people could control fans, dehumidifiers, lights etc.

**Comment by amtriathlon** [comment]
> Why?

I don't know, likely because of lack of interest.

**Comment by eerke2021** [comment]
There is a Zwift integration for ‘Home Assistant’. https://github.com/snicker/zwift_hass
I can’t see how many downloads there have been though.

**Comment by amtriathlon** [comment]
We have a users forum: https://groups.google.com/forum/#!forum/golden-cheetah-users and a developers one: https://groups.google.com/forum/#!forum/golden-cheetah-developers if you want to start a discussion about interest, feasibility, etc.

**Comment by eerke2021** [comment]
I actually went there first to see how many other people would use it. Maybe the developer at Zwift did it for fun, but I joined the users forum and can’t see a way to post a new topic.

**Comment by amtriathlon** [comment]
The first post is moderated to avoid spam, I am not a moderator so I cannot speedup the process, be patient.
