### ISSUE TITLE
XDG Base Dir Support

### ISSUE THREAD

**Issue by aleprovencio** [GoldenCheetah/GoldenCheetah#3833]
Hello, 
I wonder if we could follow the `XDG Base Directory` standards or maybe have an option to do so.

More information on [Arch's wiki](https://wiki.archlinux.org/index.php/XDG_Base_Directory)

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-developers
Thanks.
