### ISSUE TITLE
link to non-existent wikipage

### ISSUE THREAD

**Issue by mauro80** [GoldenCheetah/GoldenCheetah#3834]
In the windows installation, a link (Need help - Check the Wiki)  to the page
http://www.goldencheetah.org/wiki.html
is provided in the Start Menu, namely at
"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Golden Cheetah"
However the wiki page does not exist.

**Comment by amtriathlon** [comment]
Thanks, I will fix it. We need to fix the Readme file too.
