### ISSUE TITLE
CP(Ext) W'(Ext) p-Max(Ext) is not anymore shown in CP History after Release3.5 

### ISSUE THREAD

**Issue by sto1** [GoldenCheetah/GoldenCheetah#3835]
Works with Version 3.5
Does not Work with V3.6-DEV2101 
installated back and forth and is reproducable

**Comment by amtriathlon** [comment]
Model short names have changed, all charts using Estimates needs to be updated before release.

You can fix your instance by yourself selecting the right model from the dropdown list in Chart Options > Curve Settings.

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/0fe28abe5a58b1a99588b12deaa320cbaf48a31d
