### ISSUE TITLE
Error connecting with Strava if using Google account 

### ISSUE THREAD

**Issue by alessandrocornacchia** [GoldenCheetah/GoldenCheetah#3850]
I am experiencing problems in connecting my Strava profile with GC. 
Once I am prompted for credentials in Strava Login web page, I try logging with my Google account, since that's the way I am subscribed in Strava. 
Redirection to Google's OAuth page works, but as I proceed for login Google authentication gives me an error "Unsecure browser or application". Hence I am not able to sync with Strava

Any way to fix this? 

Thank you, regards

**Comment by amtriathlon** [comment]
I have not verified this, but I am afraid you would need to change your Strava authentication method to use sync, there is nothing you can configure about this in GC.

**Comment by amtriathlon** [comment]
V3.6 includes a new browser version, if you are using v3.5 it would be interesting to try a newer version.

**Comment by KoenFietst** [comment]
V3.6 gives the same error 'Deze browser of app is mogelijk niet veilig.'

**Comment by maxmargraf** [comment]
I can verify this issue for v3.5.

**Comment by amtriathlon** [comment]
We have a similar report from users trying to use Google Drive: https://groups.google.com/g/golden-cheetah-users/c/kUsTl9oLyo4/m/PLGm1T_qBgAJ, It looks like some has changed in Google authentication process.

**Comment by amtriathlon** [comment]
Here is an explanation of the authentication issue and a temporary workaround: https://github.com/qutebrowser/qutebrowser/issues/5182, it looks like a moving target...

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/46be903027f757a1489f28007418566d4769d118
