### ISSUE TITLE
Help > About GoldenCheetah

### ISSUE THREAD

**Issue by jschornak** [GoldenCheetah/GoldenCheetah#3856]
None of the hyperlinks on the About GoldenCheetah (dialog box) work, so I can not change the location (directory) of the Athlete Library.

**Comment by amtriathlon** [comment]
> None of the hyperlinks on the About GoldenCheetah (dialog box) work, so I can not change the location (directory) of the Athlete Library.

We need to enable open external link for the about box, I will do it.

To change Athlete library see https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Setting-the-athlete-library

**Comment by jschornak** [comment]
Alejandro,

 

The hyperlink you sent below is what I was already using.  And I read the Help Article multiple times, and I took it to mean that you click that default storage location (the hyperlink in my screenshot below) to change it.  It behave like a hyperlink when I mouse over it, but the only thing that works is a right-click and copy the link.  I can’t change where my Athlete Library is stored.

 



 

Perhaps I am confused … can you straighten me out?

 

Thanks!

John
