### ISSUE TITLE
config(sex) not work in user metrics

### ISSUE THREAD

**Issue by MaksVasilev** [GoldenCheetah/GoldenCheetah#3857]
In athlete-preferences.ini file field "sex" = 0 for "man" and 1 for "women".

But in the user metric, config (sex) is always assumed to be null:

1) { value { config(sex); } } -- always return "0"

2) "config(sex) = 0" and "config(sex) = 1" in the if expression always return false

Test on Windows AppVeyor Artifacts  on  commit 239f66fa6fcc9f391d612daa7704eb4e5c843a4d

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help. There is a working example there.
Thanks.

**Comment by MaksVasilev** [comment]
It's not a quest, it's a bug.

"{ value { config(cp); } }" return critical power from user profile, but config(sex) not return value.

**Comment by MaksVasilev** [comment]
![image](https://user-images.githubusercontent.com/1708135/113419629-7f1cb300-93d0-11eb-8fa9-416e9d7bd51a.png)

![image](https://user-images.githubusercontent.com/1708135/113419644-8643c100-93d0-11eb-8d47-484ea612dfd7.png)

**Comment by amtriathlon** [comment]
At least RTFM if you are not willing to use the forum.
