### ISSUE TITLE
open Street Map won't load

### ISSUE THREAD

**Issue by Rennschnecke21805** [GoldenCheetah/GoldenCheetah#3859]
Hi,

I've got trouble loading OpenStreetMap in map.
I will see the course I've been running/riding as a line and see my intervals displayed on a grey space with no map in the background. (I've been trying to load google maps with my own Google API-key, but this didn't work as well - and apart from that I don't like google maps)
Is there anyone out there who has resolved this issue? I'm currently on v3.5 - in v3.4 I had no issues loading OpenStreetMaps...

Thanks in advance

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
