### ISSUE TITLE
big file run-power.zones files

### ISSUE THREAD

**Issue by Genussradler** [GoldenCheetah/GoldenCheetah#3861]
Hi,
while cleaning my hard disk, I realized that the run-power.zones files uses 800MB of space.
Is this file just for running stats?
If yes, can I delete it without any side effects? I just use GC for cycling.
Is it possible to cleanup/shrink this file? If yes, how?

![grafik](https://user-images.githubusercontent.com/35425767/113556985-968cb380-95fd-11eb-9f16-3a429d02fb5b.png)

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
