### ISSUE TITLE
Not able to add new athlete to dev build 3.6

### ISSUE THREAD

**Issue by ajitsingh2208** [GoldenCheetah/GoldenCheetah#3864]
Hello all

I am not able to add new athlete in dev build 3.6, no option to add new athletes. Please address the issue.
I am using Macbook Pro M1.
Regards

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/pull/3836/commits/c4ec449466c8934ceab606430e87669cc1d01308
Please reade the wiki, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help and don’t open new issues if you are not sure it is one.
Thanks.
