### ISSUE TITLE
"Manual Slope Mode" does not record data Altitude and Slope

### ISSUE THREAD

**Issue by potashov** [GoldenCheetah/GoldenCheetah#3870]
Hi. I have Windows 10, GC 3.6DEV2101
The "Manual Slope Mode"training does not record data Altitude and Slope.
When I return to GC 3.5, then this data record again.

**Comment by amtriathlon** [comment]
Already fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/2be7a2c86edf2d286cdda3b3d7f520b8949cc0f8
