### ISSUE TITLE
GC does not load user.

### ISSUE THREAD

**Issue by hamaalmasburn** [GoldenCheetah/GoldenCheetah#3873]
Hello Ale,

Surprisingly yesterday GC stopped loading the user with the highest number of activities. Other users were fully loaded but it was still impossible to load the main user.
I have tried uninstalling R and GC to reinstall it still won't boot. Finally I have loaded it from cmd with the command GoldenCheetah --debug and it has started the main user with all the activities.

Versión: V3.5
built id: 3991

What could be the problem?

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
