### ISSUE TITLE
MMP in Golden Cheetah

### ISSUE THREAD

**Issue by sruby3530** [GoldenCheetah/GoldenCheetah#3875]
I'm analysing a set of data from a time trail and I'm looking to get the Mean maximal power for 1,2,3 and 5 minutes but I'm not sure how.

I know this might seem like a stupid question but I'm new to the software and it's all about confusing.

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
