### ISSUE TITLE
Feature Request - Alignment Bar and information pop-up for Stacked View Mode

### ISSUE THREAD

**Issue by edemattia** [GoldenCheetah/GoldenCheetah#3880]
Request a vertical alignment bar across categories while hovering in Stacked view mode. This would provide a method to see specifically each metric for each data type when hovering with precision. Also, while hovering, provide the specific value for each data type in a pop-up at the intersection of the alignment bar and the data field, like is currently provided with the existing cross-hair while hovering.

**Comment by amtriathlon** [comment]
This feature has been requested many times before, and I don't think it will be implemented in Activity chart. Currently it is available in the new [User Chart for v.3.6](https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Working-with-User-Charts)

**Comment by edemattia** [comment]
Thank you for the reply and for all your efforts.  I look forward to the new version!  All the best!
