### ISSUE TITLE
SARIS H3 ADDED BTLE BUT NOT WORKING. NO POWER AND NOT MOVING DURING WORKOUT.

### ISSUE THREAD

**Issue by iamjones2** [GoldenCheetah/GoldenCheetah#3882]
I am running Golden Cheetah v3.6 developmental build jan 2021 on Windows 10. My Saris H3 trainer is connected BTLE. The workout time starts when I ride but no watts appear and I do not move.

GC Google Group not responding to my join request.

**Comment by amtriathlon** [comment]
First message to the group is moderated to avoid spam, be patient. In the meantime you can read the FAQs on Train and Troubleshooting.

**Comment by iamjones2** [comment]
I get the moderated but why close it?

**Comment by amtriathlon** [comment]
Because we use the tracker for bugs and features, not technical support.
