### ISSUE TITLE
Importing files or borwsing the file system causes system hang on OS X

### ISSUE THREAD

**Issue by edemattia** [GoldenCheetah/GoldenCheetah#3883]
Latest snapshot (as of this post). Any function in GC that requires loading a file by browsing the file system (import activity, import workout, choose backup directory, etc.) causes OS X to hang for 20-90 seconds. It happens every time regardless of where in GC I am.  The common action is any function that needs to open the OS X finder process.

OS X Mojave

**Comment by amtriathlon** [comment]
This is a known issue on Mojave, please read the FAQs and use the users forum before open issues.

**Comment by edemattia** [comment]
Thank you for the reply.  I searched the forums for "Mojave" and didn't see anything related to my issue (other issues for sure). I may have missed it but did sincerely look.

**Comment by amtriathlon** [comment]
It has been discussed in the forum and there is an entry in FAQs: https://github.com/GoldenCheetah/GoldenCheetah/wiki/Severe-Performance-Issues

**Comment by edemattia** [comment]
Thank you.  Greatly appreciated!
