### ISSUE TITLE
, my daum 8008 trs3 is Not connected

### ISSUE THREAD

**Issue by reiniaustirol** [GoldenCheetah/GoldenCheetah#3893]
hello, what can i do, my daum 8008 trs3 is found but when starting a training it says “no connection to daum”, i connected the trainer serially to usb and selected the correct com. Unfortunately, I am not a programmer and therefore don't know much about it. thanks

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
