### ISSUE TITLE
New Nolio API access

### ISSUE THREAD

**Issue by MaxLaturte** [GoldenCheetah/GoldenCheetah#3896]
Hi,

Following few conversations with Nolio developers, a french very fast growing training platform.
Is it possible to integrate Nolio in the Cloud Account List in the same way as Today's Plan or others ?

They're ready to update their current API with a new fork to sync raw .fit files (with RPE, extra data or others)

https://www.nolio.io/api/
https://github.com/NolioApp/NolioAPI-Documentation

Don't know if it's the best place to ask for this, but thanks anyway !

**Comment by amtriathlon** [comment]
> Is it possible to integrate Nolio in the Cloud Account List in the same way as Today's Plan or others ?

Yes, the API is documented in https://github.com/GoldenCheetah/GoldenCheetah/wiki/Using-the-Cloud-Services-API if you want to give it a try.

**Comment by liversedge** [comment]
You should follow up with the NOTIO team directly- the fork is now published.

**Comment by MaxLaturte** [comment]
Just a reminder, NOTIO ≠ NOLIO, we are 2 different companies. Nolio provides web training sofware like Training Peaks and others (trying to be way more customizable) , not aero devices. -> https://www.nolio.io

They are currently doing the integration with between GC and Nolio API in a fork following the documentation thanks to @amtriathlon , and will request a merge in the next weeks.

I do not know if you think it makes senses to keep the issue open or not.

By the way, thanks for you answer and your work !

**Comment by liversedge** [comment]
OOPS! Sorry. Re-opening.

**Comment by Thomas-Plazas** [comment]
Hi,

A brief update on the advancement:

The integration is finished. It fully works and have been tested on our side.
You can find our fork at https://github.com/Thomas-Plazas/GoldenCheetah.

We'll send you secrets at liversedge@gmail.com during the week.
When do you think it will possible for you to pull and test our fork ?

Thomas

**Comment by liversedge** [comment]
Is there a pull request still ?
Do remember to rebase.

Thanks

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/pull/4169
