### ISSUE TITLE
Update default config for v3.6 release

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#3899]
Some charts has been added (s.t. Polarized zones) and other updated in non backward compatible way (s.t. Estimates due to model short names changes), so we need to create the web site folder for defaults, copy new layouts and to update 
https://github.com/GoldenCheetah/GoldenCheetah/blob/c3a1afa0a0c0d7d8e2c4c713c9e726f5b02d3ab1/src/Core/GcUpgrade.h#L121

Additionally a review of default layouts to include new chart would be desirable.

**Comment by liversedge** [comment]
The default charts should use named colours instead of fixed values too. Will update the trends chart to support named colors.
It means all the presets will need to be updated, which is a faff, but will be worth it-- most of mine assume a dark background and look terrible with a light theme,

**Comment by liversedge** [comment]
Named colors need to be expanded to support this, see #3914

**Comment by amtriathlon** [comment]
In the line of https://github.com/GoldenCheetah/GoldenCheetah/issues/4091#issuecomment-983942113, we need to add new perspectives to make the Train View experience easier for new users:

1. General or Ergometer: like current default, centered around Workout Editor, intended for ERG mode
2. Basic Simulation: similar to current default, but centered around Workout Chart, intended for Slope mode, manual or workout without coordinates
3. Map Simulation: similar to above, but centered around Workout Chart+Live Map, inteded for Slope mode workouts with coordinates.
4. Video Simulation: centered around Video with widgets enabled on Windows and Linux, intended for slope mode workouts with video sync and, optionally, coordinates.

**Comment by liversedge** [comment]
New train view defaults and config/3.6 subdirectory created in
https://github.com/GoldenCheetah/goldencheetah.github.io/commit/a6b10170c709fd3b457ab32530121437f960ff41

**Comment by amtriathlon** [comment]
> The default charts should use named colours instead of fixed values too. Will update the trends chart to support named colors. It means all the presets will need to be updated, which is a faff, but will be worth it-- most of mine assume a dark background and look terrible with a light theme,

I started to look at this, I understand fixed colors needs to be changed to standard ones, but I am not sure about metrics colors. The color automatically selected when you select a metric is Ok or also needs to be changed to a standard one?

**Comment by amtriathlon** [comment]
I added an additional switching mode for slope workouts with GPS data but without video, and the corresponding perspective including the new LiveMap chart to default config.

Also changed the switching to occur at Workout selection instead of connect, the objective is to display each workout in the proper perspective according to their type when browsing. To avoid unwanted switching when using the Editor, this only happens when the current perspective allows switching.
