### ISSUE TITLE
ANT+ USB heartrate monitor not detected MacOS Big Sur

### ISSUE THREAD

**Issue by nospam2k** [GoldenCheetah/GoldenCheetah#3904]
System Report shows:

ANT USBStick2:
  Product ID:	0x1008
  Vendor ID:	0x0fcf  (Dynastream Innovations Inc.)
  Version:	1.00
  Serial Number:	123
  Speed:	Up to 12 Mb/s
  Manufacturer:	Dynastream Innovations
  Location ID:	0x14c00000 / 28
  Current Available (mA):	500
  Current Required (mA):	100
  Extra Operating Current (mA):	0
  Built-In:	Yes

I verified the HRM works with USB on Android Device.

![Screen Shot 2021-06-21 at 8 22 03 PM](https://user-images.githubusercontent.com/1284287/122857999-5ec50c00-d2ce-11eb-95ca-bbfc3096e546.png)

**Comment by nospam2k** [comment]
UPDATE: When I unclipped the chest strap it changed to paired and there was a value and went to 0. When I reconnected the value doesn't change.
![Screen Shot 2021-06-21 at 8 41 11 PM](https://user-images.githubusercontent.com/1284287/122859545-093e2e80-d2d1-11eb-97ab-422fbd7209c3.png)

**Comment by nospam2k** [comment]
Ok, after messing with it for a while, it seems intermittant. I will do a workout with it and then report back.

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
