### ISSUE TITLE
is `QT_QPA_PLATFORM=wayland` supported?

### ISSUE THREAD

**Issue by aleprovencio** [GoldenCheetah/GoldenCheetah#3905]
Hello,
I'm on `GoldenCheetah`'s official `appimage` but it only works if forcing platform to `xcb (xwayland)`.

I'm a bit unsure about `wayland`'s native support so is this a bug or feature request?

**Comment by liversedge** [comment]
Wayland is only supported from Qt 6, we will migrate to Qt 6 when they have completed support for all the modules we need, this is likely at the end of 2021/ start of 2022.
NOTE: Qt charts will still use OpenGL in Qt 6, so you're not likely to see much of an improvement.

**Comment by liversedge** [comment]
Actually, this is supported in Qt5 but we do not include the module in our builds- we will address that in qt 6.
