### ISSUE TITLE
FR - previous runs as opponents in training mode

### ISSUE THREAD

**Issue by crobe87** [GoldenCheetah/GoldenCheetah#3908]
It would be nice to load previous trainings as opponents and GC would show live gap (time or distance) while you're riding.  

like what Tacx did in its TTS software. The opponents would shows as dots in the map, lines in the profile section, no need to implement the useless virtual 3d projection in the video player.
This is the Tacx implementation, you'll see the opponents gap (in seconds) in the top bar:
https://www.youtube.com/watch?v=v-55-S1b0l8

**Comment by amtriathlon** [comment]
Train vs opponents, recorded or online, is not likely to be implemented, there was a previous FR which was archived years ago: https://github.com/GoldenCheetah/GoldenCheetah/issues/316
More recently there was a forum discussion about a Virtual Partner feature you may find interesting:
https://groups.google.com/g/golden-cheetah-users/c/FviSfDtbLmQ/m/wgcPicN-BQAJ

**Comment by vlcvboyer** [comment]
FYI there was a PR on this subject last year: #4209 by human705
