### ISSUE TITLE
Segfault when adding a GPX trace to a new Athlete profile

### ISSUE THREAD

**Issue by jpotier** [GoldenCheetah/GoldenCheetah#3909]
## Steps to reproduce:

- Create a new athlete profile
- Click “Import data”
- Choose 
[2021-07-04_17-16_Sun.gpx.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/6760374/2021-07-04_17-16_Sun.gpx.zip) (unzip it first)
- Date is recognized properly, press “Save”
  ![image](https://user-images.githubusercontent.com/752510/124395382-82477800-dd0c-11eb-8390-b6dce89f9a8e.png)
- The program hangs a few seconds at:
  ![image](https://user-images.githubusercontent.com/752510/124395395-97bca200-dd0c-11eb-9f43-0af9e9572b63.png)
- The program segfaults.

## Context of execution

```
$ uname -a
Linux kktdr 5.13.0 #1-NixOS SMP Sun Jun 27 22:21:11 UTC 2021 x86_64 GNU/Linux
$ nixos-version
21.11-2021-07-04.09c38c2 (Porcupine)
$ GoldenCheetah --version
GoldenCheetah V3.5 (3990)
usage: GoldenCheetah [[directory] athlete]

--help or --version to print this message and exit
--debug             to direct diagnostic messages to the terminal instead of goldencheetah.log

Specify the folder and/or athlete to open on startup
If no parameters are passed it will reopen the last athlete.
```

Console output when going through the steps:
```
$ GoldenCheetah --debug
OpenData disabled, secret not defined.
[1]    120921 segmentation fault (core dumped)  GoldenCheetah --debug
```

**Comment by amtriathlon** [comment]
> ## Steps to reproduce:
> * Create a new athlete profile
> * Click “Import data”
> * Choose
>   [2021-07-04_17-16_Sun.gpx.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/6760374/2021-07-04_17-16_Sun.gpx.zip) (unzip it first)
> * Date is recognized properly, press “Save”
>   ![image](https://user-images.githubusercontent.com/752510/124395382-82477800-dd0c-11eb-8390-b6dce89f9a8e.png)
> * The program hangs a few seconds at:
>   ![image](https://user-images.githubusercontent.com/752510/124395395-97bca200-dd0c-11eb-9f43-0af9e9572b63.png)
> * The program segfaults.

I cannot recreate this on current master

> ## Context of execution
> ```
> $ uname -a
> Linux kktdr 5.13.0 #1-NixOS SMP Sun Jun 27 22:21:11 UTC 2021 x86_64 GNU/Linux
> $ nixos-version
> 21.11-2021-07-04.09c38c2 (Porcupine)
> $ GoldenCheetah --version
> GoldenCheetah V3.5 (3990)
> usage: GoldenCheetah [[directory] athlete]
> 
> --help or --version to print this message and exit
> --debug             to direct diagnostic messages to the terminal instead of goldencheetah.log
> 
> Specify the folder and/or athlete to open on startup
> If no parameters are passed it will reopen the last athlete.
> ```
> 
> Console output when going through the steps:
> 
> ```
> $ GoldenCheetah --debug
> OpenData disabled, secret not defined.

This indicates that is not likely an official build, I would suggest to use an AppImage for v3.5 or, better yet v3.6 last dev build which has lot of bug fixes and it is near to release and use the forum for technical support.

**Comment by navyjosh** [comment]
I have a very similar issue.  When I try to save a new ride or imported ride I get a crash.  I tried to use the new appimage (GoldenCheetah_v3.6-DEV_x64.AppImage) as well as the installation from ubuntu repository (3.5-DEV1810).

The virtual ride was performed using a GPX file (similar to the user who opened this issue).
