### ISSUE TITLE
Overview Data Table

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#3910]
A new overview item to display a data table

- a column should be configured and use an expression to calculate the value that is being displayed
- rows should be configurable as season or activity on trends view or activity or interval on analysis view

Since it might be useful to have rows which are metrics and columns such as min, avg, max then an option to swap rows and columns would make this more flexible.

When setting the defaults it might be good to have some examples that mimic. the old summary page.

**Comment by liversedge** [comment]
There are several parts to this
Part 1- basic summary table on activities view (e.g. Totals, Averages section)
Part 2- configuration to support legacy settings (e.g. recreate old Totals, Averages section)
Part 3- support trends view (will need to support paging results, sorting the list)
Part 4- support interval summary on activity view (possibly defer this till release 3.7)

**Comment by amtriathlon** [comment]
Hi Mark, I can implement https://github.com/GoldenCheetah/GoldenCheetah/issues/3626 if it helps with Part 4.

**Comment by liversedge** [comment]
@amtriathlon that would be superb, I'm close to merging part 1, the program to generate the table data looks like this (I have added an asstring() function so users don't have to muck about formatting data:
```
{

# column names, if using metrics then best
# to use name() to get correct name for locale
# otherwise it won't translate to other languages
names { 
    name(Duration,
         Time_Moving,
         Distance,
         Work,
         W'_Work,
         Elevation_Gain);
}

# column units, if using metrics then best
# to use unit() function to get correct string
# for locale and metric/imperial
units { 
    unit(Duration,
         Time_Moving,
         Distance,
         Work,
         W'_Work,
         Elevation_Gain);
}

# values to display as doubles or strings
# if using metrics always best to use asstring()
# to convert correctly with dp, metric/imperial
# or specific formats eg. rowing pace xx/500m
values { 
    asstring(Duration,
             Time_Moving,
             Distance,
             Work,
             W'_Work,
             Elevation_Gain); 
} 

}
```

**Comment by liversedge** [comment]
I would like to call values() multiple times to get a row of data, so would call it per interval, unless you can think of a better way.
Have no real opinions on this right now.

**Comment by liversedge** [comment]
I think the scheme should be in the program, not the way it is called.

So- I think ```values``` and of course ```names``` and ```units```  should only ever get called once.

The user then chooses to return rows of values (names x n) or just a single set (names x 1).
In which case we output a table of rows, or just 3 columns (name, value, units).

If its rows of activities (on trends) then the user will need to use metrics() to get the values. But of course they are columnar, so I think a function to convert columnar data into row data is needed too: e.g.

v1 = { m1 m1 m1 m1 m2 m2 m2 m2 m3 m3 m3 m3 }

becomes

v2 = { m1 m2 m3 m1 m2 m3 m1 m2 m3 m1 m2 m3 }

I think in R there is a function that does this for data.frames called ```transpose```, we will need to supply the number of rows and columns, so it might be:

```
v2 <- transpose(v1, 3, columns)
v1 <- transpose(v2, 3, rows)
```

I think this works best, because we let the user decide what they are putting into the table and will make it easier to handle special cases like zones or a power profile etc. And for intervals, we can have functions that follow similar semantics to the ```metrics``` function.

I think it will make the program a little more complicated, but so long as we have prebuilt stuff for migrating from the old metrics preferences most users won't use the clever stuff.

**Comment by liversedge** [comment]
I think the scheme should be in the program, not the way it is called.

So- I think ```values``` and of course ```names``` and ```units```  should only ever get called once.

The user then chooses to return rows of values (names x n) or just a single set (names x 1).
In which case we output a table of rows, or just 3 columns (name, value, units).

The values vector should be organised in columns:

v1 = { m1 m2 m3 } # one row of data
v1 = { m1 m1 m2 m2 m3 m3 } # two rows of data
v1 = { m1 m1 m1 m2 m2 m2 m3 m3 m3 } #three rows of data

If we adopt this scheme we don't need to transpose before returning.

The code for rows of metrics in trends view might be:

```
values {
    c(metrics(Average_Power), metrics(Distance), metrics(Duration));
}
```

**Comment by amtriathlon** [comment]
So replacing metrics() by intervals() it should allow to build an intervals table, I like that!

We would need an additional method to specify the row names using intervals(name)

**Comment by liversedge** [comment]
yes I think metrics() has some symbols that are a special case (e.g. Date) 

For intervals the only things that come to mind are:
* is a performance test
* type (peak power, user)
* name

Feels like we have a coherent (ish) design. Thanks.

**Comment by liversedge** [comment]
One last thing, I'm going to create a new function called metricstrings() which has the exact same syntax as metrics (and will use the same validation and execution code. The only difference will be the resulting values will be encoded using the toString metric function.

I reckon intervals() and intervalstrings() would make sense too?

**Comment by amtriathlon** [comment]
Yes, agree.

**Comment by liversedge** [comment]
@amtriathlon  Merged part 1 if you want to try it.

**Comment by liversedge** [comment]
Table paging will be done in v3.7, it gets complicated very quickly.

**Comment by liversedge** [comment]
When the data table is rich with lots of rows and columns it becomes hard to process the data, we need to be able to sort the contents by clicking on the header.
For intervals this is especially useful when we might sort by value, time or type.
