### ISSUE TITLE
Garmin index scale to Goldencheetah

### ISSUE THREAD

**Issue by StailerSL6** [GoldenCheetah/GoldenCheetah#3915]
Hello,

I have a Garmin index Scale and it would be nice to pair the data of the scale with Goldencheetah. I have been searching and I think this feature has not been developed yet. What do you think about it?

Thanks for all.
Regards.

**Comment by liversedge** [comment]
The garmin health api does not support desktop or mobile apps and only supports syncing to web sites.
see also #587
