### ISSUE TITLE
Compare mode

### ISSUE THREAD

**Issue by deepbend** [GoldenCheetah/GoldenCheetah#3928]
When in compare mode especially when stacked graphs used it is difficult to line up date between graphs. e.g, altitude and power. by the time you scroll from a point on altitude to power (you them cannot see the altitude graph you have to guess where the reference point is.
Can a movable vertical index line be added that locks onto a point in one graph and extends through all the other graphs so you have a reference when scrolling up and down between the various stacked graphs.
Movable when mouse button held, locks when released?

**Comment by amtriathlon** [comment]
Let's add this request to #1178
