### ISSUE TITLE
Golden Cheetah keeps breaking off

### ISSUE THREAD

**Issue by Tomi83614** [GoldenCheetah/GoldenCheetah#3985]
Good morning, I have installed Golden Cheetah on my new PC 64-bit version. I saved the old activities (1200 pieces) in the activities folder. Now I get the units displayed, but if I want to go to trends, for example, the program collapses. Can you help me because on the old laptop these units showed up without any problems. regards

Thomas Stoeckl

**Comment by liversedge** [comment]
There is not enough information in this report for us to help- suggest you raise at the forums here:
https://groups.google.com/g/golden-cheetah-users
