### ISSUE TITLE
July appimage Snapshot build

### ISSUE THREAD

**Issue by deepbend** [GoldenCheetah/GoldenCheetah#3995]
Overlays seem to be missing.

![Screenshot from 2021-07-16 12-33-24](https://user-images.githubusercontent.com/78499897/128338026-3bc2c0fa-4d23-471a-b194-d42c6c74bde5.png)
Above - June Snapshot above showing overlay

Below - July Snapshot No overlay or overlay half off screen

![Screenshot from 2021-07-16 12-34-45](https://user-images.githubusercontent.com/78499897/128338031-f90ec118-c0a2-4d51-b237-28a91674b961.png)
![Screenshot from 2021-07-16 12-35-51](https://user-images.githubusercontent.com/78499897/128338036-76f2b69d-aa31-460f-a1ab-5aad741571fd.png)

**Comment by judahrand** [comment]
Is this fixed then? Also having this issue

**Comment by amtriathlon** [comment]
The fix is in current master, it will be available to users in the next build.

In the meantime check your chart has a valid model since names have changed, and drag the model window if misplaced.
