### ISSUE TITLE
Trends | Summary tab data disappeared

### ISSUE THREAD

**Issue by ssp3nc3r** [GoldenCheetah/GoldenCheetah#3998]
The summary information usually on Trends | Summary tab has recently disappeared. Not sure how to troubleshoot or what information to provide. 

Build date: July 9, 2021
Build id: 4005

**Comment by liversedge** [comment]
It has been deprecated, replaced with the overview. See this on the forums:
https://groups.google.com/g/golden-cheetah-users/c/u68pPn1w958/m/uHooXbCYAwAJ

**Comment by liversedge** [comment]
![example](https://user-images.githubusercontent.com/142876/128624971-0e84978a-73c4-4740-af74-eec92e20ebe0.png)

**Comment by liversedge** [comment]
![another](https://user-images.githubusercontent.com/142876/128624994-2d1534d4-1fa6-4ed6-8a1d-ff261eb6eefb.png)
