### ISSUE TITLE
Workout Field

### ISSUE THREAD

**Issue by deepbend** [GoldenCheetah/GoldenCheetah#4004]
When I put a new workout field the choices are integer or double. A double only lets you put in 2 significant figures i.e 0.28 when I actually want to put in 0.286.
This is significant when in this case you are recording your CdA . the 3rd figure after the decimal point is significant and needs to to recorded.
This also courses problems when recording IF.
Can you modify the double to 3 significant figures please or give the choice to set your own.

**Comment by amtriathlon** [comment]
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/1196
