### ISSUE TITLE
Activity list spacing

### ISSUE THREAD

**Issue by deepbend** [GoldenCheetah/GoldenCheetah#4008]
This issue may have already been raised but I it is an issue that really needs addressing.
In the activities list if you want to put a line below the workout code it then puts about 4 or 5 spaces (gap) between activities. 
i.e.
I have created a short text called activity that I want to appear under the workout code but without creating a large gap underneath. Can this be made so just one line is used so no gap is made please.

See screen shot
![Screenshot from 2021-08-17 09-15-24](https://user-images.githubusercontent.com/78499897/129689751-1e3c411b-6a95-4c72-9a07-f9c91af31453.png)

**Comment by liversedge** [comment]
See: https://groups.google.com/g/golden-cheetah-users/c/6zZlV_bMnIU/m/nvRip1InAwAJ
