### ISSUE TITLE
Activities - Overview - Tile doesn't remember sizes

### ISSUE THREAD

**Issue by Bob7890** [GoldenCheetah/GoldenCheetah#4011]
If I create a data table tile under the activities -> overview. Then stretch the tile so I can see all the columns it looks great. If I then shutdown GC and restart it the tiles go back to even spacing and doesn't remember how I stretched certain ones. See attached.
![stretched](https://user-images.githubusercontent.com/17619761/129912246-0189d1dc-62bd-4d19-95e3-fa23b0a1283a.png)
![even_spaced_after_restart](https://user-images.githubusercontent.com/17619761/129912518-b2876cef-9ec9-4921-90ec-232182cf1f9f.png)

Windows 10. Aug 14 2021  Build Id: 4007

**Comment by liversedge** [comment]
Already fixed in master: 5fd1a08419e967c6fa850a585598f46467f0f51e

To support this kind of layout you should consider making the chart tile span columns - this is done by holding shift when dragging the right edge of the tile.

**Comment by Bob7890** [comment]
Thanks for the shift-drag, that does help somewhat. But just verifying the change you made will fix the issue when it re-opens to keep the same sizing? If I close GC and re-open it now looks like the attached which doesn't show distance, duration or pace columns.

![two_columns_view](https://user-images.githubusercontent.com/17619761/130239601-13e27147-30d8-489b-8718-6aa7960a7141.png)
