### ISSUE TITLE
Updated French Translation

### ISSUE THREAD

**Issue by jlaunay** [GoldenCheetah/GoldenCheetah#4016]
[gc_fr.ts.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/7017540/gc_fr.ts.zip)

Update of the French translation file with a correction of an error on line 24117 (Max Cadence) as reported on the forums.
Translation of several parts not currently translated, virtual bike specifications, some items in menu or options...

**Comment by jlaunay** [comment]
[gc_fr.qm.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/7026001/gc_fr.qm.zip)

Correction to add missing end spaces (problem when adding an "Overview" graph as discussed on the forum)

**Comment by jlaunay** [comment]
[gc_fr.ts.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/7033012/gc_fr.ts.zip)
Up to date version with more translation

**Comment by amtriathlon** [comment]
Applied by https://github.com/GoldenCheetah/GoldenCheetah/commit/2096342fe4f7bf478a0292427134f001103402c5
