### ISSUE TITLE
Overview - Tiles - Table

### ISSUE THREAD

**Issue by Bob7890** [GoldenCheetah/GoldenCheetah#4017]
Feature request. Allow user to change column headings. For example "Average Running Cadence" is quite long and makes the column quite wide when I'd like to be able to reduce the size of it to "Cad"
![stretched](https://user-images.githubusercontent.com/17619761/130240360-a4bd2fe9-5be6-4976-af47-3797609255f4.png)

**Comment by liversedge** [comment]
edit the program to change the headings. see ```name``` function.
