### ISSUE TITLE
Crash when creating tile

### ISSUE THREAD

**Issue by paulj49457** [GoldenCheetah/GoldenCheetah#4031]
To recreate:

i) create new tile

![Capture01](https://user-images.githubusercontent.com/46629337/131542955-ab6e938d-b7bd-4462-9353-f523039d5d8a.PNG)

ii) in the Legacy field select "Averages"
iii) GC crashes, debug below:

![Capture0](https://user-images.githubusercontent.com/46629337/131542697-acaaca6a-8cf8-4d7f-8264-eec14673d2c5.PNG)

**Comment by liversedge** [comment]
what type of tile did you choose?

**Comment by liversedge** [comment]
oh actually, I see it, this was a mistake, will fix.
