### ISSUE TITLE
Application hangs in trends and summary views.

### ISSUE THREAD

**Issue by dfelicesm** [GoldenCheetah/GoldenCheetah#4033]
Hello, 
I'm using Golden Cheetah v3.5 and the application keeps hanging when I click in either the Trends view or the Summary tab inside the Activity view. It happens very often but not 100% of the time. Do you know why this is? 
I also tried with the latest development version but I'm facing the same issue. 
This is my setup:
![imagen](https://user-images.githubusercontent.com/42378367/131989984-50d0448a-3171-465a-84b7-50207f335616.png)
Thanks in advance.

Log Name:      Application
Source:        Application Hang
Date:          03/09/2021 11:19:35
Event ID:      1002
Task Category: (101)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-4105I9T
Description:
The program GoldenCheetah.exe version 0.0.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 5234
 Start Time: 01d7a0a4b029f3bf
 Termination Time: 6
 Application Path: C:\Program Files\Golden Cheetah\GoldenCheetah.exe
 Report Id: e90766a2-ad03-45cc-87ae-f27fb0b20520
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Unknown

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Hang" />
    <EventID Qualifiers="0">1002</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>101</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-09-03T09:19:35.4308761Z" />
    <EventRecordID>38759</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-4105I9T</Computer>
    <Security />
  </System>
  <EventData>
    <Data>GoldenCheetah.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5234</Data>
    <Data>01d7a0a4b029f3bf</Data>
    <Data>6</Data>
    <Data>C:\Program Files\Golden Cheetah\GoldenCheetah.exe</Data>
    <Data>e90766a2-ad03-45cc-87ae-f27fb0b20520</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>Unknown</Data>
    <Binary>55006E006B006E006F0077006E0000000000</Binary>
  </EventData>
</Event>

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/wiki/GoldenCheetah-crashes-on-exit-or-when-saving-files and use the forum for technical support.
