### ISSUE TITLE
Label on Overview - version 3.6 build 4007

### ISSUE THREAD

**Issue by sabata4** [GoldenCheetah/GoldenCheetah#4034]
On the Overview tab, the WEEKLY HOURS the label is SECONDS not hours.

![Screenshot_1](https://user-images.githubusercontent.com/41129474/132061298-03e48787-5791-4ce8-a119-a65bd3184c26.png)

**Comment by amtriathlon** [comment]
That overview is an outdated example, change it to your taste or add a new one using the latest version.
