### ISSUE TITLE
Editing Workout Metadata

### ISSUE THREAD

**Issue by PonessM** [GoldenCheetah/GoldenCheetah#4035]
If the metadata of a training session is edited, then any change such as WorkoutCode, Keyword etc. will result in a recalculation.

In my case, this leads to the addition of:
 * Workoutcode
 * Feeling
 * RPE
 * Keyword
 * Equipment
to a long workout duration (5minutes per workout) for each workout.

Perhaps a save button like the one for raw data would be a more performant solution.

Greetings

**Comment by amtriathlon** [comment]
Immediate update is by design and GC users expect this behavior, so this will not be changed.
It is not normal your updates are taking so long, take a look to recommend hardware config in FAQs, the code in your custom metrics, if you have any, and use the forum to get help.
