### ISSUE TITLE
Tracker Athlete Weight units

### ISSUE THREAD

**Issue by hughlothrop** [GoldenCheetah/GoldenCheetah#4036]
Weight is labeled as kg but value is in pounds

**Comment by amtriathlon** [comment]
You can change it.

**Comment by hughlothrop** [comment]
How can I change the incorrect kg label?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hughlothrop** [comment]
Why would the data be labeled in kg when the data was input as pounds? How is this not a bug?

**Comment by amtriathlon** [comment]
> ese the wiki and use the forum if you need help.
