### ISSUE TITLE
Segment not identified

### ISSUE THREAD

**Issue by henolo** [GoldenCheetah/GoldenCheetah#4037]
With3.5/Win64
Just got an activity that do include a segment (that was previously defined) but somehow it does not show up in the list of Intervals. 
When looking at the activity GPS track it does not show any weird things (that I have discovered).
Attached activity and excerpt from routes.xml.
[routesxml_excerpt.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/7145743/routesxml_excerpt.txt)
[2021-09-09-16-51-33_fit.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/7145760/2021-09-09-16-51-33_fit.txt)

Thanks!

**Comment by amtriathlon** [comment]
It works on current master, likely fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/bbc7a03178038c97620ee44c81e42846a5f82214
