### ISSUE TITLE
Slope incorrectly estimated if distances are not strictly increasing

### ISSUE THREAD

**Issue by caspermurtonen** [GoldenCheetah/GoldenCheetah#4038]
If slope is not available in the input file it is estimated in https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/FileIO/RideFile.cpp:

        if (!dataPresent.slope && dataPresent.alt && dataPresent.km) {
            if (lastP) {
                double deltaDistance = p->km - lastP->km;
                double deltaAltitude = p->alt - lastP->alt;
                if (deltaDistance>0) {
                    p->slope = deltaAltitude / (deltaDistance * 10); // * 100 for gradient, / 1000 to convert to meters
                } else {
                    // Repeat previous slope if distance hasn't changed.
                    p->slope = lastP->slope;
                }
                if (p->slope > 40 || p->slope < -40) {
                    p->slope = lastP->slope;
                }
            }
        }

If any p->km values are replicated deltaDistance = 0 and p->slope is set to the slope of the prior ride point.  The altitude change deltaAltitude is discarded.  This is incorrect.  All changes in altitude must be accounted for at some stage.

For example the points:
KM  ALT  <p->slope as calculated above>
10.01  34.0  ..
10.02  34.2  2
10.02  34.4  2
10.02  34.6  2
...        ...      2
10.02  36.4  2
10.03  36.6  2
10.04  36.8  2

results in a slope of 2 % for all points.  However it is clear that the slope between 10.02 km and 10.03 km is actually (36.6 - 34.2)/((10.03 - 10.02)*10) = 24 %.

This issue arises in files imported from FulGaz as it increments distance in 10 m steps.  At low climbing speeds the slope is underestimated by a factor of 5 or so, but is an issue at all speeds under 10 m/s (36 kph).

**Comment by amtriathlon** [comment]
I think this is a data problem, it doesn’t seem to be a good general solution for such a bad data.
To allow the users develop specialized fixes for anomalies like this we added https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Custom-Data-Processors-in-Python, in v3.6 Python is already included and ready to use.
