### ISSUE TITLE
GC crashes upon file import

### ISSUE THREAD

**Issue by Giovanjane** [GoldenCheetah/GoldenCheetah#4048]
GC (both current 3.6dev and 3.5 stable) crashes upon file import on my Windows system all the time. Two logs are attached.

[crash_1447_111021.log](https://github.com/GoldenCheetah/GoldenCheetah/files/7322548/crash_1447_111021.log)
[crash_1448_111021.log](https://github.com/GoldenCheetah/GoldenCheetah/files/7322553/crash_1448_111021.log)

**Comment by amtriathlon** [comment]
Regrettably those files are not that helpful if we cannot reproduce the issue, see https://groups.google.com/g/golden-cheetah-users/c/uBOSQ9XerXQ/m/ifFr6oFlBgAJ
