### ISSUE TITLE
[Feature request] Enable all metrics with W' in the name for using in user charts

### ISSUE THREAD

**Issue by jgpallero** [GoldenCheetah/GoldenCheetah#4057]
As it was pointed out in https://groups.google.com/g/golden-cheetah-users/c/AQIPx-pQWkk, not all metrics listed in https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Formula-Syntax-and-Expressions#metric-reference whose name contains W' are available for use in Table tile of user metric charts. It would be nice if all of them where special cased in the file https://github.com/GoldenCheetah/GoldenCheetah/blob/04b6334f5900e3d01928e3e8a2eb3f4a58e28ff8/src/Core/DataFilter.l#L96-L100 

Also, the metric called `W'bal_Matches` is actually `W'bal_Matches_>_2KJ`. It would be nice to create other related metrics such as `W'bal_Matches_>_5KJ`, `W'bal_Matches_>_10KJ`, `W'bal_Matches_>_15KJ`

**Comment by liversedge** [comment]
If you need additional metrics these can be created with User Metrics since version 3.4 (released in 2016).
