### ISSUE TITLE
Compiling with Withings Keys

### ISSUE THREAD

**Issue by tommycw1** [GoldenCheetah/GoldenCheetah#4060]
I've been using GC for many years and have been compiling versions from time to time on my own without issues.

At some point I started using an appimage (V3.6-DEV2101) and connected GC to my Withings account.  i was able to download weight data from there directly into GC.

Anyway, next time I compiled GC I went and got my GC_WITHINGS_CONSUMER_KEY and GC_WITHINGS_CONSUMER_SECRET from my Wittlings account (I had already registered and gotten these keys for another project I was using).

I put these into GC and compile went fine.  When I try to sync data however I get an error:

If I go to Share->Get Measures->Body->Withings->Download, I get the following error in a popup:

Main Dialog: There was an error during fetching. Please check the error description.
Show Details: {"errors":[{"message":"invalid_grant: Invalid Params: invalid client id\/secret"}]}

So I decided, maybe I need to re-authorize this since I originally authorize when using the appimage which would have used different consumer key and secret.  

So I go to Athlete Settings->Accounts->Withings->Edit->Authorize

I successfully log into my account with my email/passwd and select my user and then click "Allow This App".  This gives a popup error titles "SSL Token Refresh Error":

Main Dialog: Error retrieving access token, Error transferring https://account.withings.com/oauth2/token? - server replied: Bad Request (302)
Show Details: Error retrieving access token, Error transferring https://account.withings.com/oauth2/token? - server replied: Bad Request (302)

I'm not sure how to trouble shoot this further.  I am using the latest dev release 2110 source, but had previously tried with dev-2108 and maybe some prior dev-21xx sources as well.

**Comment by tommycw1** [comment]
I tried two more things now, I first went into my athlete and deleted my Withings account from GC, then attempted to authorize.  I got the same error.  I next created a new athlete and tried adding a Withings account and got the same error when trying to authorize.

**Comment by amtriathlon** [comment]
> Anyway, next time I compiled GC I went and got my GC_WITHINGS_CONSUMER_KEY and GC_WITHINGS_CONSUMER_SECRET from my Wittlings account (I had already registered and gotten these keys for another project I was using).

Current code doesn't use those variables anymore, see the new names in:
https://github.com/GoldenCheetah/GoldenCheetah/blob/320cddb1e12ed7eec2a77b381aa0c555579873c1/src/Cloud/OAuthDialog.cpp#L329-L337

We need to update gcconfig.pri.in to reflect that.

**Comment by tommycw1** [comment]
I edited my local gcconfig.pri and changed GC_WITHINGS_CONSUMER_KEY to GC_NOKIA_CLIENT_ID and GC_WITHINGS_CONSUMER_SECRET to GC_NOKIA_CLIENT_SECRET and recompiled.  I was then able to connect to my Withings account and download data.

Note: when changing the gcconfig.pri.in I'd suggest adding instructions to set the callback uri to "http://www.goldencheetah.org" when creating your app on the Withings webiste else this fails during authroization.
