### ISSUE TITLE
Athlete Weight downloaded from Withings does not respect user config units in charts

### ISSUE THREAD

**Issue by tommycw1** [GoldenCheetah/GoldenCheetah#4061]
Using dev-2110

I have units set to Imperial in my config.  When plotting rider weight downloaded from Withings account, the chart labels the axis as lbs and data points as lbs, however the numerical value is shown in kg rather than lbs.

**Comment by amtriathlon** [comment]
In which chart, can you give us a more detailed description?

**Comment by tommycw1** [comment]
@amtriathlon - Good question, sorry I wasn't more specific.  The chart I had is under "Trends" side tab and it was already existing (I probably created it some time ago) so I created another because I didn't remember the process:

In the "Trends" side tab, I go to View->Add Chart->Trends->Curves->+->Athlete Weight

Under Axis Label it defaults to "kg", so I change it to "lbs".  Click OK and OK again to accept everything and create the chart.  I now have a weight vs time chart that has the y axis labeled in "lbs" but is reporting numerical values actually in kg.

**Comment by amtriathlon** [comment]
When Imperial is selected in Options, adding a new Athlete Weight curve defaults to lbs:
![image](https://user-images.githubusercontent.com/1444784/140326201-b0fd7b7b-068c-48f4-b821-bee1d4a107cf.png)
For charts created when units were Metric, the label needs to be manually changed or the curve recreated.
