### ISSUE TITLE
unprecise intervals from Garmin device

### ISSUE THREAD

**Issue by Rennschnecke21805** [GoldenCheetah/GoldenCheetah#4063]
Just realized, that when I import an Interval-Session from my Garmin device to GC the interval durations are off by 1-2 sec in the GC data records.
E.g.: for an 800m lap I recoded 02:55.40 with my watch but GC displays me 00:02:57 as the duration of this interval in the imported data-set. (The 800m Interval-distances are imported pretty precisely though...)
This error occurs consistently through all the intervals of this one dataset and through multiple other datasets.

**Comment by amtriathlon** [comment]
This is a known limitation due to the way intervals are represented in GC.

**Comment by Rennschnecke21805** [comment]
Ah ok - it's a little nasty, but if you know, never mind me noticing it.
