### ISSUE TITLE
storage of a training false

### ISSUE THREAD

**Issue by roadrunnerspeedygonzales** [GoldenCheetah/GoldenCheetah#4064]
I'm using version 3.5. and windows 10 21H1 Build 19043.1288

the last two times i could nit save a training, because GC only run till proofing files step2 of 4 and then GC still stand and is waiting and waiting and waiting.
What can i do?

I have read help manual and found an entry for openGL, but i dont know, what i should do. I dont use a Nvidia graphic-driver, only drivers from windows-system

with regards
Wolfgang

**Comment by amtriathlon** [comment]
> What can i do?
Use https://groups.google.com/forum/#!forum/golden-cheetah-users, search to find how other users have solved similar issues in their systems and ask for help there if that is not enough.
