### ISSUE TITLE
Failure to complete Withings OAuth process 'redirect_uri_mismatch'

### ISSUE THREAD

**Issue by tgradl** [GoldenCheetah/GoldenCheetah#4065]
On a fresh install of the official 3.5 and 3.6-DEV AppImage and new athlete profiles, I am unable to complete the OAuth process to connect Withings accounts. All dialogs in GC seem fine up to the final 'Allow this app' button, which is answered with an error message:

`{"errors":[{"message":"redirect_uri_mismatch: The redirect URI provided is missing or does not match partner callback url"}]}`

I have recently registered a client app with the Withings API myself and could no longer use a non-HTTPS callback URL (https://developer.withings.com/developer-guide/glossary/glossary#callback-url) in unrestricted mode. I wonder if the registered client app used in official GC releases has fallen back to restricted mode due to the use of `http://www.goldencheetah.org` as callback URL.

**Comment by grauser** [comment]
Thank you @amtriathlon

**Comment by ElSurfdude** [comment]
It's clear; thanks; but couldn't find these files in GC for Windows in versions 3.5 and 3.6

**Comment by JeanDiv14** [comment]
+1 on this issue this morning. Build ID 4002, Sep 15. 

{"errors":[{"message":"redirect_uri_mismatch: The redirect URI provided is missing or does not match partner callback url"}]}

Any help..?

Tx,
Jean

**Comment by amtriathlon** [comment]
You need to install the last version, see the dates…
