### ISSUE TITLE
Extended CP Model Does not Display in CP Tab

### ISSUE THREAD

**Issue by Aeroengineer1** [GoldenCheetah/GoldenCheetah#4070]
Using the August 3.6 release on Win10-64 Pro:

When trying to calculate CP in the CP tabe using the chart settings, the extended CP does not calculate with my data.  All the other models will calculate something, but the Extended CP does not calculate as shown below (and yes, I know that I am not in good shape, this is me getting on a bike for the first time in 10 years and trying to get it back, about a month's worth of progress here :):
![image](https://user-images.githubusercontent.com/5205655/141693930-d70b0299-1ae0-41f1-ae42-11976a66f1ea.png)
When I try and calculate it in 3.5, the fit looks good, but is shifted vertically substantially.  I am not sure why it does this.  I would take a screenshot, but I did not realize that I needed to do a better job of specifying the install folder for Golden Cheetah such that it did not overwrite the initial installation.  Overall the Extended CP curve followed very well in 3.5, but had ~150W average power vertical shift.

**Comment by amtriathlon** [comment]
This is explained the wiki, and the users forum is available if you need help or have questions.

**Comment by Aeroengineer1** [comment]
I did not find anything in the wiki or user forums that noted the behavior difference between the two where in 3.5 it shows up and in 3.6 it does not.  Offset or not.  It just does not calculate.

Can you please point me to it, I am sorry that my searching on this specific issue was in vain.  

Adam
