### ISSUE TITLE
Ignore Withings reported 0% body fat

### ISSUE THREAD

**Issue by tommycw1** [GoldenCheetah/GoldenCheetah#4072]
On Withings scales, if you step on the scale and wait a few seconds, it measures your weight.  Next it starts to measure your body fat.  If the user steps off after it measures the weight, it will not get a measurement for body fat and reports a 0 in its data.

When downloading this data, GC gets a data point since weight was recorded but also gets a 0% body fat data point.  If displaying Measures->Body-Fat Percentage on a trends chart, the chart is very ugly since it displays the line dipping to 0 to display these data points.  This also affects trend lines since they are trying to account for many 0 measurements.

I believe these 0% data points should be ignored since it is clearly impossible to actually have 0% body fat and therefore invalid data.

**Comment by liversedge** [comment]
this should be applied in the chart when plotting data (ignore zeroes). this can already be controlled by the user.

**Comment by tommycw1** [comment]
Hi @liversedge 

Thanks for this.  Can you explain how to Ignore Zeros, I don't see this anywhere in my trends graph options, so I assume I'm missing it somewhere.

I don't see it on my main options screen:
![image](https://user-images.githubusercontent.com/3934773/142431132-4de6a7c0-a3f5-4010-8cb9-c7fb94f79854.png)

Nor do I see it on the specific curve:
![image](https://user-images.githubusercontent.com/3934773/142431310-df4e524c-5efa-46d0-b17d-c8ff232e4863.png)

Thanks for your help!

**Comment by liversedge** [comment]
Ah- I was thinking of a user chart for this, where the series looks like this:
![bodyfat](https://user-images.githubusercontent.com/142876/142434235-7816f816-4688-4eef-86fa-67df2c4a5271.png)

**Comment by tommycw1** [comment]
OK - thanks Mark.  So should we reopen this issue?  Seems valid.

**Comment by liversedge** [comment]
No, because we wont add an ignore zeroes option to the trends charts when it can be achieved via a user chart.
Whilst the old charts won't go away any time soon, new development effort will go into the user chart instead.
If you're having trouble replicating the chart I can upload an example to the chart db?

**Comment by tommycw1** [comment]
OK, that's fair.  I didn't know trends charts were being depreciated (or not developed anymore or however you want to say that).

I'd really appreciate if you could upload an example chart.  I can't seem to get this to work from your screenshot.  I've never tried to use a user chart before so I really don't know what I'm doing.  What I was trying to actually show was Weight and Body Fat % on one chart, but anything would be helpful.

**Comment by liversedge** [comment]
Just uploaded a curated chart called Withings Trend. You will need v3.6 dev.

**Comment by tommycw1** [comment]
Thanks for uploading this!

I'm running 3.6-dev2110 from appimage in Linux

I go to View-Download Chart, search for keyword "Withings" and find nothing
![image](https://user-images.githubusercontent.com/3934773/142494080-3d368578-a426-4f4d-a801-f5d893d9e9fc.png)

I also paged though all the pages to see all 41 curated charts and don't see it.  Does it take some time to become available for download?

**Comment by tommycw1** [comment]
Hi @liversedge 

Thanks for uploading this chart.  I have added the chart but I'm not seeing any data:

![image](https://user-images.githubusercontent.com/3934773/142535570-66f764ca-07b1-4185-b1e2-5698c5f83937.png)

It looks like the scale on the X date axis has an issue - set to the day before the unix epoc 1-JAN-1970

If it matters I'm on 3.6-DEV2110 AppImage on Linux.

Also not sure how to change this to display weight in lbs rather than kgs.

**Comment by liversedge** [comment]
You should not change the X axis range- just select a date range from the sidebar that has withings data in it.

**Comment by liversedge** [comment]
Here is a chart with data collected from a withings scale in 2010

![works](https://user-images.githubusercontent.com/142876/142592571-abf3150e-4425-4e54-a628-967d09ecef5f.png)

**Comment by tommycw1** [comment]
Weird, I'm not seeing anything in the plot.  I have data from 2015-present for Date, Weight, Fat Mass, Lean Mass, Fat Percent with Source=Withings that I can see in the table when I go to Athlete Settings->Measures. 

I can also plot it in my trends graphs as I showed before.

However selecting any dates in my sidebar does not plot any data on this new graph.

**Comment by liversedge** [comment]
Can you post a pic of the measures history?

**Comment by tommycw1** [comment]
Last item in config/bodymeasures.json is:

        {
            "boneskg": 0,
            "comment": "",
            "fatkg": 11.189,
            "fatpercent": 13.221,
            "leankg": 73.444,
            "musclekg": 0,
            "originalsource": "",
            "source": 1,
            "weightkg": 84.633,
            "when": 1637076639
        }

![image](https://user-images.githubusercontent.com/3934773/142696637-7acc72d3-3246-4abd-985f-2d89099d23ed.png)
