### ISSUE TITLE
Training wirh RLV-Videos using BLE-protocol: speed not correct on TACX Vortex T2180

### ISSUE THREAD

**Issue by Peplord** [GoldenCheetah/GoldenCheetah#4075]
Cycling a RLV-Video on a smart-trainer using BLE-connection is unrealistic (Speed much too high). A PGMF-, RLV-, and AVI-File where used. Tried it with different files from different sources.
 
Example: cycling 5% uphill with only 75 Watt results in about 38 km/h speed. Otherwise the resistance of the trainer seems to be correct.

OS used: Windows 10 Pro
Trainer used: TACX Vortex T2180, the trainer uses the TACX "ANT+ over BLE" protocol not FTMS.
BLE adapter: LogiLink BT0015 nano USB Bluetooth Adapter 
Cheetah Version: Oct 9 2021 Build Id 4008 Developer Build

**Comment by amtriathlon** [comment]
On v3.6 you can use simulate speed from power if your trainer gives you unrealistic results.

**Comment by Peplord** [comment]
Thank you Alejandro, that worked for me, I can use GC now to train with RLV-videos. 
But still ... I think Golden Cheetah has a problem here. All apps I tried and my smartwatch show realistic speed information, but the speed GC shows is much too high (about 2x). It does not seem the trainer is sending wrong sensor data.
