### ISSUE TITLE
Windows 10 crash on 3.6Oct09

### ISSUE THREAD

**Issue by sscafidip** [GoldenCheetah/GoldenCheetah#4076]
I have installed 3.6 August and Oct on Windows 10, and as soon as I try to download rides from Cloud GC crashes and disappear from my screen.
I installed GC also on another PC with Windows 10, same
I installed GC also on Windows 7, all good. that does not happen

Can you help investigating
thanks

**Comment by amtriathlon** [comment]
https://groups.google.com/g/golden-cheetah-users/c/uBOSQ9XerXQ/m/ifFr6oFlBgAJ
