### ISSUE TITLE
Problems with \n character in Python chart

### ISSUE THREAD

**Issue by jgpallero** [GoldenCheetah/GoldenCheetah#4077]
I'm writing a Python chart and I want also to export a text file with some data. The problem is that the \n character is interpreted by the GC console as an actual break line instead of a part of the code. For example, if I write

```python
import os
from pathlib import Path
filename = str(Path.home())+os.path.sep+"file.txt"
idf = open(filename,"w")
idf.write("Hello\n")
idf.close()
```

the chart apparently works, but if I close GC, when I start it again and click on the Python chart the code appears as

```python
import os
from pathlib import Path
filename = str(Path.home())+os.path.sep+"file.txt"
idf = open(filename,"w")
idf.write("Hello
")
idf.close()
```

which produces the error

```
SyntaxError: EOL while scanning string literal
```

This issue can be managed in Linux using chr(10) as
```python
import os
from pathlib import Path
filename = str(Path.home())+os.path.sep+"file.txt"
idf = open(filename,"w")
idf.write("Hello"+chr(10))
idf.close()
```
but in Windows the sequence chr(10)+chr(13) is needed, so it will appear compatibility issues.

It would be nice if the GC Python console could be manage correctly the \n character

**Comment by amtriathlon** [comment]
> but in Windows the sequence chr(10)+chr(13) is needed, so it will appear compatibility issues.

That’s preposterous, ‘\n’ and chr(10) generate the same Unicode point, they’re indistinguishable.

OS dependency is handled by the file object, see https://docs.python.org/3.7/library/functions.html#open

**Comment by amtriathlon** [comment]
Subsumed in https://github.com/GoldenCheetah/GoldenCheetah/issues/4113
