### ISSUE TITLE
Fonts for Charts are very small

### ISSUE THREAD

**Issue by dimk1** [GoldenCheetah/GoldenCheetah#4078]
Hi there,

I've been testing v3.6 (AppImage) on Ubuntu 20.04 LTS. In the Trends -> Overview tab, the legends for PMC, Scatter PMC, and in general for charts in 2 axes are very small and not readable. Check for example the running legends on top of these diagrams for CTL, TSB, etc. theThe date axis for example in the Monthly Load bar chart is that way too. Any ideas?

![Screenshot from 2021-11-24 09-33-47](https://user-images.githubusercontent.com/24992349/143203080-ca95608d-73aa-4cb7-93e0-7c1ab48aa1ff.png)
![Screenshot from 2021-11-24 09-33-39](https://user-images.githubusercontent.com/24992349/143203085-ab0ded9b-79d7-47e6-9aaf-a953adcbfbbe.png)
![Screenshot from 2021-11-24 09-29-52](https://user-images.githubusercontent.com/24992349/143203086-2e2f4c65-802b-4c69-a54a-2dafe762eadc.png)

**Comment by liversedge** [comment]
There is an option to scale on the first page of the chart settings to address this.
