### ISSUE TITLE
User metric not respected when used in new tile (v3.6)

### ISSUE THREAD

**Issue by dimk1** [GoldenCheetah/GoldenCheetah#4083]
Running v3.6 on Ubuntu 20.04. I create a custom metric to measure the Power @ 164bpm as follows:
![Screenshot from 2021-11-24 20-47-14](https://user-images.githubusercontent.com/24992349/143304162-41ce280e-0e7f-4e98-81ff-14d59f981b45.png)

Then I go to Trends -> Overview->new Tile->User Chart with the following settings:
![Screenshot from 2021-11-24 20-49-09](https://user-images.githubusercontent.com/24992349/143304402-43919db9-065e-4b60-bdba-9d21c38a647b.png)

![Screenshot from 2021-11-24 20-49-20](https://user-images.githubusercontent.com/24992349/143304475-3a617d9f-0c4b-4971-9e62-9c8392f5747d.png)

The custom metric Average_Power_164bpm is not found. 

When I create a new KPI in the Overview with the same metric the metric is respected.

**Comment by liversedge** [comment]
The metric name will be constructed from the name, not the symbol.
Please, whilst you are learning, use the forums for your questions- we can raise bugs if/when they are confirmed.
