### ISSUE TITLE
Train: WorkoutEditor graph not updating when using "Manual Slope Mode"

### ISSUE THREAD

**Issue by erikboto** [GoldenCheetah/GoldenCheetah#4091]
If a manual slope mode workout is running, the Workout Editor-graph won't render the graphs as it does if a manual erg mode workout is run.

Steps to reproduce:

1. Go into Train View
2. Connect a Robot
3. Select "Manual Slope Mode"
4. Press Play
5. Watch how the Workout Editor-graph does not update

If you repeat the same steps but with "Manual Erg Mode" it works fine.

This issue was created after some discussion in the forums: https://groups.google.com/g/golden-cheetah-users/c/uGUUX7sXp9M

**Comment by amtriathlon** [comment]
That also happens when you use slope mode / simulation workouts, the way I understand this is Workout Editor is currently specific to Erg mode, and you are expected to use Workout chart (not editor) for them, both in manual or workout cases.

**Comment by liversedge** [comment]
I would say we setup a number of default perspectives
- erg mode
- slope mode
- video
- streetview

That way users just select the perspective that applies- we could also make the perspective switch based upon the type of workout being executed... would be happy to code that up

**Comment by erikboto** [comment]
Right, I see now that I made some bad assumptions about the Workout Editor. I though it would plot anything, but just be able to create ERG-workouts.

I wonder what it would take to make it plot any kind of data during e.g. the manual workouts. Since it's so pretty to look at I guess most would prefer it.

But I also agree that a number of default perspectives could probably be useful for those who maybe switch between e.g. video/streetview/other rides, so that one doesn't have to set up the view every time you change the type of workout.

**Comment by erikboto** [comment]
So it seems that it's just something with the time vector that is preventing it from being plotted properly. 

In `void TrainSidebar::loadUpdate()` there's a if/else checking if we're in RT_MODE_ERGO. 

If we are, we will call `context->notifySetNow(load_msecs);` and if not we will call `context->notifySetNow(displayWorkoutDistance * 1000);`

I don't fully grasp the details of why the code looks this way. A simple test where I replace the call to `context->notifySetNow(displayWorkoutDistance * 1000);` with `context->notifySetNow(load_msecs);` even in the non-ERG mode result in a working plot even when in Manual Slope Mode, but I guess I'm probably breaking some other graph?

**Comment by erikboto** [comment]
I don't think the change mentioned above is the way to go. But it might be possible to just plot the data based on the getMsecs() value for RealtimeData when not being in ERG-mode.

**Comment by amtriathlon** [comment]
> I would say we setup a number of default perspectives

Agree, I am willing to add some as part of https://github.com/GoldenCheetah/GoldenCheetah/issues/3899#issuecomment-984617850

**Comment by liversedge** [comment]
I think the right answer is for Workout Editor to be only relevant in ERG mode, closing this in preference for views that change depending on the workout type.

**Comment by liversedge** [comment]
The switching code has now been implemented as part of issue #4104
