### ISSUE TITLE
Multiple devices of same type problem

### ISSUE THREAD

**Issue by jaKenobi** [GoldenCheetah/GoldenCheetah#4101]
Hi,
I am trying to add multiple cadence/speed device with GoldenCheetah. 
Since I want to monitor 2 wheels, I want a separation of the data for each wheels. 
So I need one speed and one cadence for each. But when I do, the values change with both of the sensors even tho they are in different channels.
I'm testing with simulANT, and I setup a cadence sensor on CH2 and CH4. When I'm in the adding device Wizard in GoldenCheetah, I setup 2 Cadence type to detect my fake sensors. I see that they detect both of sensors but when reading values. The application seems to be confuse and since both input values are of cadence type. The values shows the value of CH2 and CH4, they toggling on both labels.

**Comment by liversedge** [comment]
we only record one cadence data series and only store one cadence series in the ride format. so what you are trying to achieve is not possible currently.

**Comment by jaKenobi** [comment]
Would it be possible for me to add new variables to store data for each wheels? and use externals id/#channel to separate data.
