### ISSUE TITLE
Renaming Data Fields - Maddeningly Difficult

### ISSUE THREAD

**Issue by darrencope** [GoldenCheetah/GoldenCheetah#4105]
It's extremely difficult to rename data fields, screen tabs, etc. under the Options > Data Fields dialog. You have to double-click on an exact spot, with no indication of where that spot is. In practice, this means that I spend minutes trying to get a single field renamed. This should behave normally, where double clicking anywhere in the field allows renaming (and ideally, F2 key would also work). This is currently an issue on Windows 11, running the Oct 9 dev build, but it has been an issue on every other version I've used over the past.. oh, 7 years, both Windows and Ubuntu.

**Comment by liversedge** [comment]
single click to a field or screen name to then rename it.

**Comment by liversedge** [comment]
apologies if this seems like a facetious answer-- the methods are not our design decision it is how the qt framework works.
