### ISSUE TITLE
Syntax checking in chart formulae

### ISSUE THREAD

**Issue by steveedmonds** [GoldenCheetah/GoldenCheetah#4109]
I am working on a chart and after receiving a number of syntax errors find;
apt <- 1.5-0.5; #causes a syntax error,
apt <- 1-0.5; #doesn't 
apt <- 1.5 -0.5; #doesn't
apt <- (1.5)-0.5; #doesn't

Steve

**Comment by amtriathlon** [comment]
It can be avoided adding space before the minus, the cause seems to be in this regular expression:
https://github.com/GoldenCheetah/GoldenCheetah/blob/d7e9e305c542050f6eb62382c4ad8bc98724e42e/src/Core/DataFilter.l#L90
