### ISSUE TITLE
Trends>Time in HR Zone has incorrect pop up info on chart.

### ISSUE THREAD

**Issue by steveedmonds** [GoldenCheetah/GoldenCheetah#4110]
This is the first time I have used this chart, so may be misinterpreting the information.
When you run the mouse onto the boarder between 2 zones a pop up box shows info. This shows correct for zones 1 - 3 but for zone 4 it says zone 5. This is possibly due to this workout having no zone 5. A workout that gets to zone 5 shows zone 4 in the popup. 

Images attached in PDF.
[HRzonesChart.pdf](https://github.com/GoldenCheetah/GoldenCheetah/files/7731400/HRzonesChart.pdf)

**Comment by steveedmonds** [comment]
Sorry, GC 3.6 build 4009

**Comment by amtriathlon** [comment]
This has been previously discussed in the users forum.

**Comment by steveedmonds** [comment]
Sorry, I searched the users group and only found discussions regarding HR zone calculation + something from 2014 and not a reason the H5 label shows on the chart for the top stacked bar regardless of the actual zone. I.e. if I record a warmup where I stay in zone 1, the label at the cursor for the activity on the chart shows 0.0 time in H5 rather than the time in H1. I am not sure what the work around is to show the correct time.

**Comment by amtriathlon** [comment]
Search for stacked chart, and use the forum for questions, please.
