### ISSUE TITLE
Check for RideFile::NA values in FIT Garmin Smart Recording handling

### ISSUE THREAD

**Issue by grmpl** [GoldenCheetah/GoldenCheetah#4117]
These two lines in FitRideFile.cpp do not work correctly:
```
2212            double deltaLeftRightBalance = (lrbalance>=0?lrbalance:50.0) - (prevPoint->lrbalance?prevPoint->lrbalance:50.0);
...
2253                        prevPoint->lrbalance + (deltaLeftRightBalance * weight),
```
There are several problems with these two lines:
1. `prevPoint->lrbalance` is compared to 0 in 2212, wereas 0 is a perfectly valid value and there is no reason to handle it seperately.
2. For `prevPoint->lrbalance = 0` `deltaLeftRightBalance` is calculated from 50.0 instead of 0, but the intermediate values in line 2253 are still calculated from 0 onwards, leading to intermediate values starting from 0 but not going up unto `lrbalance`.
3. If `prevPoint->lrbalance` is `RideFile::NA`, intermediate values will be calculated starting from -255 upwards.

To handle it properly, you would have to:
- compare `lrbalance` and `prevPoint->lrbalance?` against `RideFile::NA`
- If `prevPoint->lrbalance?` is `RideFile::NA` and `lrbalance` is not `RideFile::NA`, you have to calculate delta from 50.0 to `lrbalance` in 2212 and set starting point in 2253 to 50.0
- If `lrbalance` is `RideFile::NA` and `prevPoint->lrbalance` is not `RideFile::NA`, you have to calculate delta from `prevPoint->lrbalance` to 50.0 and leave starting point in 2253 at the given value
- if both are `RideFile::NA` you have to set intermediate values to `RideFile::NA`, too

This is a complex distinction of cases and I don't think it is worth the effort when doing a simple linear interpolation for a highly nonmonotonic function. Your analysis tools are handling NA-values perfectly well, so I would recommend to keep all intermediate values at `RideFile::NA` if previous or next value is `RideFile::NA`. 
I have made a suggestion for correct handling of intermediate values in pull request [https://github.com/GoldenCheetah/GoldenCheetah/pull/4108](url) . 

The change is combined with a revert of the change which excluded lrbalance from all devices with left based **l**rbalance. The revert is justified in my comment in the pull request, to "show how support for non-conformant devices can be added without breaking support for conformant devices" as asked for by @liversedge in issue #4067 . If I didn't investigate the issue properly or if you do have additional information, not written down in an issue, feel free to correct my reasoning.

**Comment by liversedge** [comment]
The interpolation should only apply where there are gaps in recording (e.g. garmin smart recording), not sure now common a gap in recording from an NA value is in that case (if ever).

Do you have a ridefile that can be used to understand this better (that is compliant with the ANT FIT spec) ?

**Comment by grmpl** [comment]
Sorry, I don't have a compliant ridefile, as my device does not set the right-bit according to spec. 
With my device gaps in recording from NA-values are very common, as it will pause recording when riding is stopped for some time. With stopped riding lrbalance will be set to NA-value, so last value before gap is nearly always NA.
If you want one of my non-compliant files: Is there a way to modify gpx-data in a fit-file? I don't want to upload my exact home location to a public web page without access restrictions.

**Comment by liversedge** [comment]
if you don't use smart recording you should disable it in options and then the interpolation won't be applied.

**Comment by grmpl** [comment]
Thanks, but I don't need a workaround. I'm happy with my locally patched and self-compiled version of GoldenCheetah.
It's just a suggestion for improvement of your tool, which I wanted to share. 
The code is wrong, but it's only a nuisance and I would assume nobody doesn't really care, so it's not important if it gets fixed or not.

**Comment by liversedge** [comment]
Put into the parking lot, we can bring into a release if it turns out to be a real issue for users with valid files.
