### ISSUE TITLE
NOT WORK WITH TAXC IMAGIC

### ISSUE THREAD

**Issue by fescob** [GoldenCheetah/GoldenCheetah#4122]
1)  good  installation of Goldencheetah 3.5 32 bits on my computer windows7 pro 
2)  I use a TACX IMAGIC
3) I launch the wizard for connect the Imagic
4) Is never found. (work correctly with Tacx Trainer software 4.0)

What's the problem?

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
