### ISSUE TITLE
Adding new Google Calendar/Drive fails, gives 'Browser not safe' error

### ISSUE THREAD

**Issue by Hezelnutt** [GoldenCheetah/GoldenCheetah#4123]
When trying to add a new google calendar to the sync services, this results in an error during the login process. 'Browser not safe, please update browser' after input of emailaddress.

Adding the google calendar thus cannot be completed. 

Please let me know if you need additional data or if I can help in an other way. I hope this can be fixed!

**Comment by amtriathlon** [comment]
This is a general issue with Google authentication, so it also applies to Google Drive and any other service using it.
I've tried a workaround before (https://github.com/GoldenCheetah/GoldenCheetah/issues/3876), but it is not working anymore.

**Comment by Hezelnutt** [comment]
Good to see you are aware of this.Too bad there is little you can do about his. Thanks for the help regardless  From: Alejandro MartinezSent: Wednesday, January 5, 2022 5:07 PMTo: GoldenCheetah/GoldenCheetahCc: Hezelnutt; AuthorSubject: Re: [GoldenCheetah/GoldenCheetah] Adding new Google Calendar fails, gives 'Browser not safe' error (Issue #4123) This is a general issue with Google authentication, so it also applies to Google Drive and any other service using it.I've tried a workaround before (#3876), but it is not working anymore.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by amtriathlon** [comment]
Impersonating a different User Agent is discouraged in [Google OAuth guidelines](https://developers.googleblog.com/2020/08/guidance-for-our-effort-to-block-less-secure-browser-and-apps.html), so I will revert the previous workaround and let it be. The alternative would be to use the system browser, but this requires major changes in our OAuth code.
