### ISSUE TITLE
Max value for double metadata filed is 99.99

### ISSUE THREAD

**Issue by MeisterP** [GoldenCheetah/GoldenCheetah#4125]
I recently noticed that the EPOC metadata field displays 99.99 instead of 120.

The default maximum value for qdoublespinbox is 99.99.
https://doc.qt.io/qt-5/qdoublespinbox.html#maximum-prop

The custom max value was removed in https://github.com/GoldenCheetah/GoldenCheetah/commit/e0ec5ba2d1c780a12ab0060f080a414b3b915ce0#diff-d83ad293ecebf19a3389d0f56ff7f7708f9ead2d7eb3517f6131f428e18b5c61L710
It was dropped for both, QSpinBox and QDoubleSpinBox

Maybe it was removed by mistake? The commit message doesn't actually mention min/max values.

**Comment by liversedge** [comment]
thanks for logging this and providing the root cause, it was indeed a mistake.
