### ISSUE TITLE
GC and multiple Bluetooth devices issue (macOS)

### ISSUE THREAD

**Issue by RudolfSch** [GoldenCheetah/GoldenCheetah#4126]
I am using GC 3.6 BETA (Build id: 4009) running on macOS 11.6 to train with the latest Wahoo Kickr (v5) and a Garmin HRM-Dual.

The goal is to use Bluetooth and not ANT+ as I don't have an ANT+ Stick and there might be other issues with USB-C to USB-A conversion etc. 

A) When I open GCs preferences -> Training and add ANT+ and FE-C then GC crashes every time. I can try to add more details (logs) if you would find it helpful and you can point me what you need and how I can access it. But that's only a sidenote as I want to proceed to my main issue B)

B) I added an Bluetooth 4.0 device in GCs preferences -> Training. 
In the Bluetooth assistant I can only proceed to "Next", I can't tell GC to only search for a Wahoo Kickr or only search for my Garmin HRM-Dual. 

<img width="737" alt="BT-Assistant" src="https://user-images.githubusercontent.com/443936/148777578-3ce56eb3-e269-4668-b68f-dc77325ac66a.png">

In my first try I just finished the BT assistant and afterwards I could start a training with the kickr. At this try I didn't have the Garmin HRM-Dual in use and everything worked. I should add that I also have an Favero Assioma UNO Powermeter for outdoor training on my bike. This device had no charge during the first try. But the meanwhile I charged the Assioma again.

Today I wanted to train and also add the heart rate sensor. My guess was to add another training device which I did. But then GC connected via Bluetooth to my Assioma power meter but apparently not to the kickr. So it could not control the power/resistance.

How can I tell GC to connect to Kickr and not to Assioma? E.g. by finding out and entering the correct port and profile in the configuration dialog. 

Or more general: How can I limit the GC connection to only the devices I want (focus macOS)? 
E.g. It could be the case that my neighbor is training below my flat and it would automatically pick up his devices instead of mine.

<img width="604" alt="BT-Configuration-Details" src="https://user-images.githubusercontent.com/443936/148778661-854feee3-fce3-4fd4-9fc9-13ea38962166.png">

I could not find any documentation mentioning how to add a Wahoo Kickr or the Garmin HRM-Dual. Probably because most of the time it should work out of the box. But it doesn't with multiple BT devices... Could you please shed more light on this?

Should I add two Bluetooth devices one for Kickr and one for HRM Dual then? 

BTW: Wahoo Kickr should be mentioned in the BT 4.0 Trainers list then.

If you need more information pls. let me know. Thx. Rudolf

**Comment by amtriathlon** [comment]
Please, see the FAQs and use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.

**Comment by RudolfSch** [comment]
here comes the Apple Crash report for ANT+ device search. 
[GC-Crash-No-Ant-Stick.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/7839661/GC-Crash-No-Ant-Stick.txt)

**Comment by RudolfSch** [comment]
@amtriathlon I am sorry if I have put my questions in the wrong place. Nevertheless I think I can add some extra BT info which is valuable for GC development here. I hope you don't mind if I put this info here.

I found out how to enable debug log and I created 2 different Logfiles and I found a slightly complicated workaround which I described in the Logfile "GC-debug-log2.txt". I hope that in future versions of GC there could be an improvement as I guess it will also affect other users with multiple BT devices in range.

[GC-debug-log.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/7839967/GC-debug-log.txt)

[GC-debug-log2.txt](https://github.com/GoldenCheetah/GoldenCheetah/files/7839966/GC-debug-log2.txt)

**Comment by amtriathlon** [comment]
This has been previously discussed at the forum, it is nothing new.
Issues are for confirmed bugs or new features once the scope has been defined.
If you want to discuss your ideas you can use the forum or the new https://github.com/GoldenCheetah/GoldenCheetah/discussions
