### ISSUE TITLE
Embedded Python 3.7 not working on MacOS version

### ISSUE THREAD

**Issue by dmedina2015** [GoldenCheetah/GoldenCheetah#4140]
Just installed GC 3.6-beta. Fail trying to activate Python. 

Steps:
(1) GoldenCheetah -> Preferences -> Mark 'Enable Python'
(2) 'Python Home' is automatically filled with: '/Volumes/Macintosh\ HD/Applications/GoldenCheetah.app/Contents/Frameworks/Python.framework/Versions/3.7/bin/python3.7'
(3) Press 'Save'
(4) Restart GC, get following error:
![image](https://user-images.githubusercontent.com/16577563/150133785-82b9fc11-b1d2-4001-be47-35ca3a32904f.png)

I'm using MacOS 11.5.2

**Comment by dmedina2015** [comment]
Additional information: Python exists at that location and works perfectly using terminal:
![image](https://user-images.githubusercontent.com/16577563/150134568-1b2ce251-8103-4355-af8e-890c7a847b34.png)

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Working-with-Python#working-with-python
