### ISSUE TITLE
Developer fields read differently on Linux and Windows version of GC

### ISSUE THREAD

**Issue by pledac** [GoldenCheetah/GoldenCheetah#4151]
A FIT file is analyzed differently for developer fields on Linux and Windows version of Golden Cheetah (Build Id 4009). Basic data is OK, but developer fields have weird data with Windows version.
Provided snapshots for the 2 versions + the FIT file:
Thanks

![GC_DevField_LinuxOK](https://user-images.githubusercontent.com/4377498/151650920-f293f5ec-0d81-4793-bcb1-963cc878e7df.png)
![GC_DevField_WindowsKO](https://user-images.githubusercontent.com/4377498/151650926-569e34a8-d838-43a4-8a6d-e8e2c4e0522f.png)
[Fit_2022_01_28_08_31_51.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/7963141/Fit_2022_01_28_08_31_51.zip)

**Comment by amtriathlon** [comment]
Cannot reproduce using current master:

![image](https://user-images.githubusercontent.com/1444784/151658986-db5740f0-6c5a-4da9-8d92-732d373f7d8b.png)

**Comment by pledac** [comment]
Ok thanks, and sorry it works also under Windows, now on my laptop.
