### ISSUE TITLE
Withings requires new OAuth2 API call

### ISSUE THREAD

**Issue by gador** [GoldenCheetah/GoldenCheetah#4152]
Withings is [shutting down the API endpoint](https://support.withings.com/hc/en-us/articles/360016745358--BREAKING-Deprecating-access-and-refresh-tokens-endpoints) on 2022-02-08 and requires a new form of access. 
The new [API reference](https://developer.withings.com/api-reference/#operation/oauth2-getaccesstoken) requires an `action` query paramater, not just a `token`
https://github.com/GoldenCheetah/GoldenCheetah/blob/32b1f0f7d1cb9d88baec64f5865ee4de4ababd37/src/Cloud/OAuthDialog.cpp#L331

**Comment by amtriathlon** [comment]
The response has changed too, it is embedded in the body part for the new API call.
