### ISSUE TITLE
[Feature Request] Add folders to Train -> Workouts

### ISSUE THREAD

**Issue by Blastman** [GoldenCheetah/GoldenCheetah#4167]
I'm trying out the workout functionality finally in GC and downloaded a lot of workouts but workouts I create are lost in the sea of other downloaded workouts. It would be nice if folders existed so I could separate items. It would also be nice if the downloaded workouts from Erg DB were downloaded into multiple folders but I don't know if their API gives any folder information. If not, maybe just stash them into a single `Erg DB Workout` folder.

**Comment by amtriathlon** [comment]
We have a long standing issue about training library management (https://github.com/GoldenCheetah/GoldenCheetah/issues/411), let’s consolidate all related requests in that one.
