### ISSUE TITLE
[Feature Request] Add filters to Train -> Workouts 

### ISSUE THREAD

**Issue by Blastman** [GoldenCheetah/GoldenCheetah#4168]
With all the workouts you can download, adding some filters would be nice to narrow down some workouts to try. Filters such as:
* Time (e.g. 1:30 - 2:15 or > 2 hours workout length)
* IF to find easy/recovery and hard workouts
* Maybe some Zone filtering (e.g. > 20 mins in Z5)

**Comment by amtriathlon** [comment]
We have a long standing issue about training library management (https://github.com/GoldenCheetah/GoldenCheetah/issues/411), let’s consolidate all related requests in that one.
