### ISSUE TITLE
Compile of 3.6 RC1 fails on Linux

### ISSUE THREAD

**Issue by tommycw1** [GoldenCheetah/GoldenCheetah#4173]
Hello,

I've been downloading and compiling all of the 3.6 dev releases successfully - most recently being Dev2111.

Today I downloaded the 3.6 RC1 dev source and tried to build unsuccessfully.

I am on Ubuntu 18.04 and using QT 5.15.2

```
$ /opt/qt515/bin/qmake --version
QMake version 3.1
Using Qt version 5.15.2 in /opt/qt515/lib
```
The dump was too long to include directly here.  Here is a pastebin link:
https://pastebin.com/fTjDrBUm

**Comment by liversedge** [comment]
Did you compile in qwt before src ? 

Also best to use the developer forums for this rather than defect / fr.
https://groups.google.com/g/golden-cheetah-developers
