### ISSUE TITLE
Gear Ratio Chart with SRAM eTap

### ISSUE THREAD

**Issue by steeler-fanatic** [GoldenCheetah/GoldenCheetah#4175]
The Gear Ratio plot in both versions 3.5 and 3.6 does not show any change in gear ratio when I ride my SRAM AXS eTap equipped bike.  It works properly on my Shimano 105 mechanical bike both on and off the Wahoo trainer.   See attached screenshot for what I see in Golden Cheetah when reviewing a ride.
![Screen Shot 2022-02-16 at 5 28 21 PM](https://user-images.githubusercontent.com/36704850/154368312-e3e1428b-7068-45e7-af7b-0dddc6ed1a9f.png)
Note I can see the gear ratio for the ride at axs.sram.com as shown on the second screenshot.
![Screen Shot 2022-02-16 at 5 36 10 PM](https://user-images.githubusercontent.com/36704850/154369128-2758ec47-fcfa-4cf8-9efc-812e3ed7549c.png)

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
