### ISSUE TITLE
Datafilter estimate(s) and config return wrong values in Trends View (latest RC Version)

### ISSUE THREAD

**Issue by PonessM** [GoldenCheetah/GoldenCheetah#4176]
Hi,

The Datafilter Functions estimates(Param1, Param2) and config(param1) ignore the Filter Settings "isRun <> 0" or "isRide <> 0".

There is no Difference between the global Search/Filter box in the MainWindow or the Filterbox in a Diagramm Settings or using activities(p1,p2) function. They are all ignored.

Instead, the Sport Typ from the last selected Activity (Activity View) is used to filter the Results. That means, you have to select a Run, to get the estimation or config Values for Running activities in TrendView. Changing to estimata / config for cycling, you have to go back in the ActivityView, select a Ride, go back to TrendView.

Maybe both Functions can be extended to use a SportType Parameter. 

Greetings, Marcel

**Comment by PonessM** [comment]
On the other Hand, it is not possible to compare the Athlete configured CP for a given Sport using config(). 

For both is lr and lm not useful.

**Comment by PonessM** [comment]
The Documentation says:

estimates(model, cp|ftp|w'|pmax|date|x) - since v3.6

As per estimate above, will retrieve the PD model estimates for a date range. For example, to plot a history of CP estimates using the Morton 3 parameter model for the currently selected date range in a user chart.

So for Running with Power, this KPI Code should show the estimated CP using internal CP3 Model for running.
{ 
  activities("isRun <> 0", {
    round(max(estimates(cp3, cp)));
  });
}

But is does it only, if the last activity was running. If the last activity was Cycling, this shows the Cycling estimation.

**Comment by liversedge** [comment]
Please use the forum for questions. Thanks.
