### ISSUE TITLE
error IF Y STRESS (INTENSITY FACTOR Y ESTRES)

### ISSUE THREAD

**Issue by corgon15** [GoldenCheetah/GoldenCheetah#4181]
DESDE HACE SEMANAS ME DA VALORES DE 0 AMBAS COSAS, NO HAY ERRORES NI EN WATIOS NI PULSO, CAIDA EN PICADO DE EL PMC FORMA ETC.. ME GUSTARIA CORREGIRLO

![image](https://user-images.githubusercontent.com/100403842/155669697-458a0130-bb50-48ab-a325-d7d52dcd5185.png)

**Comment by amtriathlon** [comment]
Por favor lee primero las preguntas frecuentes (FAQs), y usa el foro de usuarios psi sigues con dudas.
