### ISSUE TITLE
One time "Summary chart is deprecated" warning

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#4191]
When launching show a "Summary Chart has been deprecated" warning - and add a "do not show this again" checkbox.

**Comment by amtriathlon** [comment]
Can we made this part of the upgrade process?

I mean, add a dialog at https://github.com/GoldenCheetah/GoldenCheetah/blob/e34a36f98a7226d3069e5897cca2042e1b97fe14/src/Core/GcUpgrade.cpp#L383

informing:

- Summary Chart has been deprecated and replaced by Overview charts
- Layouts and data will be upgraded, you need a data backup to go back to previous version

and asking to confirm/continue or cancel/abort.
