### ISSUE TITLE
Ride-Tab: Can't hover over data at the top of the view - the drop down is activated.

### ISSUE THREAD

**Issue by awolff64** [GoldenCheetah/GoldenCheetah#4193]
In the ride tab I can not hover with the mouse over the graph a the very top of the screen.
Instead of displaying the details the settings with stacked, smooth ... drop down.

![GC-rideproblem](https://user-images.githubusercontent.com/35629366/157899467-036e250c-bde6-4ec5-b67b-1877496a816c.png)
I

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.

**Comment by amtriathlon** [comment]
I don’t, but I will not argument here, the forum is the place for discussions.
