### ISSUE TITLE
crashing when saving workout @ Train View

### ISSUE THREAD

**Issue by kazanderpersson** [GoldenCheetah/GoldenCheetah#4194]
GC RC3.6 Feb, fresh win11 install

I'm able to reproduce this - GC hangs & crashes everytime at this point when clicking "Stop" and trying to save

![GC3_6_RC_crash_at_train_save](https://user-images.githubusercontent.com/3967981/158183288-36ad8c9c-0553-434b-af83-9e2f4a7c873b.png)

Seems to happen to any longer workouts - short ~10s workouts can be saved normally

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.

**Comment by amtriathlon** [comment]
Latest snapshot builds in http://www.goldencheetah.org/#section-download have the fix for this issue applied.
