### ISSUE TITLE
Crash in Train mode when saving file post ride

### ISSUE THREAD

**Issue by Par5o** [GoldenCheetah/GoldenCheetah#4197]
After stopping ride in Training mode, file save appears as follows but freezes then app crashes, Windows 10
![Screenshot 2022-03-20 220105](https://user-images.githubusercontent.com/101975677/159161241-82dea1a6-f69c-418a-9bd6-70f0d48b0c94.png)

**Comment by Par5o** [comment]
latest ver 3.6

**Comment by amtriathlon** [comment]
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/4194
