### ISSUE TITLE
Default Dark Theme Setting has some almost invisible items

### ISSUE THREAD

**Issue by schubidoo** [GoldenCheetah/GoldenCheetah#4201]
When Running GC (Version 3.6 RC, Feb. 1, 2022) with the system set to dark mode, some things in the user interface become basically invisible. Particularly, I saw the filter markers in the "Trends" Tab (Which are "black on very dark"), and the "invisible" text in the filter dialog (also black on very dark).

See the attached screenshot, this is on a standard Win 10 20H2 install (19042).

![grafik](https://user-images.githubusercontent.com/17938073/159447396-2a602b97-c63d-4c0b-87c0-9d938237ed31.png)

**Comment by paulj49457** [comment]
I'm thinking that rather the current 8 or so pre-programmed themes it would be good if these were changed to be a set of files in a config directory. The GC installation would come with the 8 themes in file format which could be selected and loaded, also the user could save the values currently set in the colours tab as a file. This would make it easier to correct colour issues in GC themes, plus make it possible for people to create new themes and share them. If this would be generally useful I'm happy to work on improving this area.

**Comment by paulj49457** [comment]
I've been looking at this and I'm going to code a change to move the currently hardcoded themes definitions to an XML file so new ones can easily be created. I have also created a snapshot feature that writes the current colour settings to an XML file, so they can be reloaded assuming the user has defined a custom set they want to keep.

**Comment by liversedge** [comment]
Please don't do this. It will not be accepted.

**Comment by paulj49457** [comment]
Putting the hard coded themes in an xml file parsed at start-up. why would this not be acceptable?

It would be before all the other modifications, it would just replace the code sections such as:

    // MODERN LIGHT (SAP Fiori Belize inspired)
    add.dark = false;
    add.stealth = false;
    colors << QColor(Qt::white)  // Plot Background
           << QColor(0xef,0xf4,0xf9) // Toolbar and Sidebar Chrome
           << QColor(0x26,0x84,0xf6) // Accent color (markers)
           << QColor(Qt::blue) // Selection color
           << QColor(Qt::darkMagenta) // Critical Power and W'Bal
           << QColor(Qt::red) // Heartrate
           << QColor(85,170,0) // Speed
           << QColor(255,170,0) // Power
           << QColor(0,204,204) // Cadence
           << QColor(Qt::magenta) // Torque
           << QColor(0xcb,0xdc,0xea) // Overview Background
           << QColor(255,255,255) // Overview Tile Background
           << QColor(247,252,255) // Overview Tile Background 2
           << QColor(231,241,250);// Overview Tile Background 3
    add.colors = colors;
    themes << add;
    colors.clear();

to be something like:

<themes>
	
	<theme name="Modern Dark" dark=true stealth=false >
	<color index=0 rgb="19,19,19" > // Plot Background
        <color index=1 rgb="32,32,32" > // Toolbar and Sidebar Chrome
        <color index=2 rgb="85,170,255" > // Accent color (markers" >
        <color index=3 rgb="194,194,194" > // Selection color
        <color index=4 rgb="Qt::yellow" > // Critical Power and W'Bal
        <color index=5 rgb="Qt::red" > // Heartrate
        <color index=6 rgb="Qt::green" > // Speed
        <color index=7 rgb="255,170,0" > // Power
        <color index=8 rgb="0,204,204" > // Cadence
        <color index=9 rgb="Qt::magenta" > // Torque
        <color index=10 rgb="19,19,19" > // Overview Background
        <color index=11 rgb="39,39,39" > // Overview Tile Background
        <color index=12 rgb="60,60,60" > // Overview Tile Background 2
        <color index=13 rgb="84,84,84" > // Overview Tile Background 3
	</theme>
</themes>

Why is this problematic ?

**Comment by paulj49457** [comment]
See #4242 Configurable Themes & Backup Colour Settings

**Comment by liversedge** [comment]
This issue has nothing to do with configuring themes and everything to do with the cascading style sheet applied to this specific dialog and the way it interacts with system settings.

**Comment by amtriathlon** [comment]
This was recently reported at the forum: Athlete tabs become unreadable due to a light background when using dark themes, besides the weird aspect:
![image](https://user-images.githubusercontent.com/1444784/185183421-820f7b84-4451-4684-8a0e-5278e6f699c2.png)

This seems to be a problem for all dark themes, for reasons I don't understand the tabbar background is not set to ToolBar Background color as I would expect according to https://github.com/GoldenCheetah/GoldenCheetah/blob/6d4921ba09f71cb564b1b188e2a7d8daee332437/src/Gui/MainWindow.cpp#L2549-L2556

**Comment by paulj49457** [comment]
> This was recently reported at the forum: Athlete tabs become unreadable due to a light background when using dark themes, besides the weird aspect: ![image](https://user-images.githubusercontent.com/1444784/185183421-820f7b84-4451-4684-8a0e-5278e6f699c2.png)
> 
> This seems to be a problem for all dark themes, for reasons I don't understand the tabbar background is not set to ToolBar Background color as I would expect according to
> 
> https://github.com/GoldenCheetah/GoldenCheetah/blob/6d4921ba09f71cb564b1b188e2a7d8daee332437/src/Gui/MainWindow.cpp#L2549-L2556

Athlete tab colour fix #4257 should fix this issue

**Comment by amtriathlon** [comment]
Athlete Tab and dropdown in Filter/Search box was fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/fdb35bf74e2b2dc4cc02bbb4bd53a38551d9bc6e
