### ISSUE TITLE
CP curve for row same as bike

### ISSUE THREAD

**Issue by gogolo2** [GoldenCheetah/GoldenCheetah#4204]
GC 3.6 correctly shows different CP curves for run and bike according to the defined workout codes.

But the CP curve for rowing (workout code row) is the same as the bike curve. (which is impossible because the row workouts have much lower watts).

Why is it working for bike and run, but not for row? Is CP curve based on the workout code row not implemented?

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.

**Comment by liversedge** [comment]
messages are pre-moderated and I hadn't checked for new ones recently- its just got posted.

**Comment by gogolo2** [comment]
That's very good news, thx very much!
