### ISSUE TITLE
Persistent crashing at app launch

### ISSUE THREAD

**Issue by edgegit** [GoldenCheetah/GoldenCheetah#4205]
Suddenly experiencing persistent crashing at app launch. Appears to happen just as syncing* starts. 

Tried updating to the 3.6Dev release this morning (for Withings users). Same issue.

**System Info:**
Mojavi: 10.14.6 
MacBook Pro (15-inch, 2018)
*Strava

**Comment by amtriathlon** [comment]
We use the forum for technical support.
