### ISSUE TITLE
MapQuest Update and Sunset Announcement

### ISSUE THREAD

**Issue by MeisterP** [GoldenCheetah/GoldenCheetah#4206]
I've wrote them an e-mail to ask if there is a replacement/successor to https://developer.mapquest.com/documentation/open/elevation-api

Will update this issue if I get an answer from them. 

The api is used in https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/FileIO/FixElevation.cpp

On 12.04.22 20:54, MapQuest Support wrote:
(highlights in bold added by myself)
> 
> Hi there,
> 
> 
> Thanks for being a loyal MapQuest for Business customer. We are pleased to share some exciting news about updates to our full suite of APIs and mapping tools. MapQuest is getting ready to help developers build bigger, better, and more global apps. The first step in this process is deprecating some of our older and less utilized services to streamline our platform for substantial refinements over the coming months.
> 
> 
> What is Not Changing: The front end of the Geocode, Static Map, Directions, Search, Data Manager, and Traffic APIs will remain the same so no new development is needed. All of the request options remain the same and the response objects will not change. The MapQuest.js, MapQuestGL.js and Leaflet plugins v2 remain the same.
> 
> 
> What is Changing: The back end of these APIs are being updated to improve overall data quality, make data updates faster, broaden international support, and lay the foundation for the next version of all of the APIs. Benefits you will see after this update include:
> * Map and road data updates will happen in weeks rather than months
> * International geocoding and routing will be supported in more areas
> * Traffic will eventually include markets outside the US and Canada
> 
> **With the new backend updates, we are also sunsetting old versions and APIs with little usage, including all open APIs (open.mapquestapi.com).** Some functions within the APIs, and SDKs that were sunset several years ago will reach the end of their life. All Directions API requests should be updated to v2 and all Static Map API requests should be updated to v5.
> 
> 
> Timing for Changes: August 31, 2022 is the key date we wanted to alert you to. On this date, the following services will reach the end of their life:
> * **The open geocode, directions, guidance, mapping, elevation, and Nominatim APIs**
> * The Directions API Path from Route and Find LinkID functions
> * The unofficial/beta Geocode API v2
> * All Traffic API v1 and Directions API v1 will reach end of their life and all requests should be updated to v2
> * The MapQuest JavaScript v7, Leaflet plugins v1, and Flash SDKs that were sunset in 2016-2018 will stop functioning on April 31, 2022
> 
> 
> 
> Our support team is here to assist with any transitions, and our sales and account management team is ready to answer any questions you may have.
> 
> 
> Sincerely,
> 
> 
> The MapQuest for Business Team

**Comment by amtriathlon** [comment]
Do you received any response to you query?

Considering the timeframe, It seems we will need to disable/deprecate FixElevation before v3.6 release.

**Comment by MeisterP** [comment]
No, I didn't get any response.
Contacted them twice, once over e-mail and a second time using their homepage.
The documentation at https://developer.mapquest.com/documentation/open/elevation-api seems to be gone.

There are other elevation data providers available. Like https://open-elevation.com/

So either disabling FixElevation or implement a different provider would be the way forward.

**Comment by m4lvin** [comment]
Side note: I wanted to file an issue that `https` should be used in this line to avoid leaking location data in plaintext: https://github.com/GoldenCheetah/GoldenCheetah/blob/b9fbcce56e5a6af1e60309ba5edc218d096584cb/src/FileIO/FixElevation.cpp#L305
But if MapQuest is on the way out, then I guess any new elevation provider will use https anyway now.

**Comment by amtriathlon** [comment]
Open elevation public API referenced above seems a good replacement, ant it uses https: https://github.com/Jorl17/open-elevation/blob/master/docs/api.md
