### ISSUE TITLE
Import sometimes don't change status button to "save" in train mode when stoped

### ISSUE THREAD

**Issue by bengahl2** [GoldenCheetah/GoldenCheetah#4208]
I am using GC 3.6 RC 1 on macOS 10.16. Sometimes when doing exercises in Train mode with json workout and video the "import files" never change import status from Queued to Validated. I have to restart GC.
![Skärmavbild 2022-04-16 kl  11 23 43](https://user-images.githubusercontent.com/103821117/163669820-bc2b6a1b-0d5e-4783-b135-41c1fcdb306d.png)
![PastedGraphic-1](https://user-images.githubusercontent.com/103821117/163669878-77ef0be0-5cdf-428c-bb43-e4b0916237a2.png)
When importing the saved osv-file from "records" everything works fine.
-rw-r--r--   1 bengtahlen  staff  574280 13 Apr 19:13 2022_04_13_18_00_56_Vårrulle med Lok.csv
I'm new to this and I tried to follow the contributing guidlines but I'm not sure I have succeeded. Please direct me to an other post if I do something wrong. I will be happy to do more constructive analysis of what goes wrong or provide more information if needed If directed.
Regards Bengt

**Comment by liversedge** [comment]
the date and time of the ride cannot be derived from the file or filename so you need to manually enter them in the dialog.

**Comment by bengahl2** [comment]
I never get to do that because the program hangs in status Queued and the abortbutton Is disabled.

**Comment by bengahl2** [comment]
Hi Mark,
I can not enter the date and time because the program hangs. The rainbow colored wheel spins and I can not abort or change focus.
Regards Bengt

**Comment by bengahl2** [comment]
If the date and time of the ride cannot be derived from the file or filename I would say that is a bug considering GC generated the file and to me it looks like the osv file has a date and time in the filename.

**Comment by amtriathlon** [comment]
This is a duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/4194, please search existing issues before to create new ones.

**Comment by bengahl2** [comment]
Thanks. Missed that one.
