### ISSUE TITLE
Data validation freezes after longer workouts

### ISSUE THREAD

**Issue by IainMacdonald** [GoldenCheetah/GoldenCheetah#4213]
Using V 3.6 RELEASE CANDIDATE 1 FEBRUARY 2022. Twice it has frozen after workouts greater than 1 hour (works fine on shorter workouts) during the stage where the 'Import Files' popup is being displayed. The progress bar is at 25% and is on step 2 of 4 and the import status is 'Validated'. The entire interface (popup and main window) is non responsive. You end up with no data as you have to kill the process (I've left the computer for hours to see if it comes back to life, sadly it does not).

Could not find any issues that have raised this already. Will download code and run in debug mode to try and get a better handle on what the issue is.

**Comment by amtriathlon** [comment]
Duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/4194
