### ISSUE TITLE
Issue with CP Estimates in Estimator.cpp

### ISSUE THREAD

**Issue by steveedmonds** [GoldenCheetah/GoldenCheetah#4220]
In response to the discussion https://groups.google.com/g/golden-cheetah-users/c/-G7d-sBgiAI I have identified an issue in Estimator.cpp

I have uploaded 2 anonymised activity datasets to illustrate the issue.
[dataset1.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/8691119/dataset1.zip)
[dataset0.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/8691125/dataset0.zip)

To better follow the explanation below build GC with #define ESTIMATOR_DEBUG true in src/Metrics/Estimator.cpp and run GC from a prompt.
To reproduce the issue; 
1. Create a new athlete and load the activities from dataset0 into the athletes activity folder. 
2. GC runs the Estimator code on opening an athlete so you will need to close and reopen the athlete for the activities to process.
3. Create a new KPI tile in the activities overview (or edit the CP Estimates tile) with the formula {round(estimate(ext,cp),2);}
4. If you click on the last activity Apr 24, 2022 you will see that the CP estimate is 0 but for Apr 23 there is a value.

Explanation;
When you look at the debug output from Estimator.cpp you notice that the first activity defines the start of the weeks analysed and the  "week" is set as Sunday - Saturday. If the first activity had been on a Tuesday then the week would be defined Tuesday-Monday.

> Model progress 2021/11
> [Metrics/Estimator.cpp:304 run] Estimates for Sun Nov 7 2021 - Sat Nov 13 2021: CP=187 W'=8502

When you look towards the end of the debug output you can see the last week analysed is 

> Estimates for Sun Apr 17 2022 - Sat Apr 23 2022: CP=197 W'=7922

and so the activity Apr 24 is not considered, hence zero.

Now create another athlete (or delete the activities for this athlete) and load the activities from dataset1 into the athletes activity folder.
This dataset is the same as dataset0 except the activity of Apr 24 is deleted and added as Mon Apr 25. The activity is still in the same week Sun-Sat as the activity of Apr 24 and there is still only one activity in that week.

Close and reopen the athlete again. Now when you click on the last activity a value is shown for CP estimate. If you look towards the end of the debug output you will see another week has been added to the analysis that includes the Monday 25th activity.

> Estimates for Sun Apr 24 2022 - Sat Apr 30 2022: CP=219 W'=6561

A new week is not added to the analysis for an activity on the first day of the week but is for an activity on another day of the week.

I found that the issue was resolved by changing line 235 of Estimator.cpp and rebuilding GC
from
`     while (date < to) {`
to
`    while (date <= to) {`

**Comment by amtriathlon** [comment]
Good catch, thank you for the analysis!
