### ISSUE TITLE
Update Batch export... to Batch Processing....

### ISSUE THREAD

**Issue by paulj49457** [GoldenCheetah/GoldenCheetah#4223]
Rename the access menu option from  "Batch export..." to  "Batch Processing....".

  Rename the "Activity Batch Export" dialog to "Batch Processing", then add a radio box at the top with the following four options:

    i) Export as    xxxxxxx     to    xxxxx  Browse  overwrite  xx
 
    ii) Run data processor xxxxxxxxx 

    iii) Set metadata field (drop down?) to value (constant or formula?) for all selected

    iv) Delete all selected

update the Action column to display the option selected and change the Export button to Run or Execute.

**Comment by paulj49457** [comment]
So I have "delete all selected" working, and the dialog looks like:

![CaptureDial](https://user-images.githubusercontent.com/46629337/169643676-c63cbf6e-d39a-4804-aa96-d1516856dd94.PNG)

So I have a few questions:

i) When the data processors are run from here, are we expecting them to use the configuration defined in the Options->Processing menu? Or should I make it optional to use the config or not?

ii) Meta Data, can you tell me how many fields I should be expecting? Should it be the same list as in Options->Fields menu's Field column ? Also can you point me in the direction of the type of meta data processing that already exists that you would like to be made available?

**Comment by paulj49457** [comment]
To reduce confusion I think the "Settings" column heading (circled in red) should be renamed to "Auto & Save Settings", as the manual settings are entered in the individual data processor dialogs, what do you think ?

![Capture123](https://user-images.githubusercontent.com/46629337/169644991-fa02f1dd-b5fb-42b2-b921-089f94f952f7.PNG)

**Comment by amtriathlon** [comment]
> To reduce confusion I think the "Settings" column heading (circled in red) should be renamed to "Import, Save & Batch Processing Settings", as the manual settings are entered in the individual data processor dialogs, what do you think ?

Those settings are also used as defaults for interactive DP execution, perhaps "Default Settings" would be clear enough.

**Comment by paulj49457** [comment]
Hi Ale,

   Thank you for the feedback to my questions, but in the meantime I have created a PR for a version of the batch processing and submitted it #4226. So I'll look at the Meta Data info you have provided, and maybe you can try the PR I have submitted to see if anything else is required.

   As to the check boxes they are exclusive radio buttons.

Paul.

**Comment by amtriathlon** [comment]
> As to the check boxes they are exclusive radio buttons.

They don't look like that, see my comment above for an example, or Metric Trends chart config for how they are used in GC.

**Comment by paulj49457** [comment]
I've looked at getFields and have the implemented that, but after looking through the GC tutorials and Wiki I'm still none the wiser as to what would be a sensible set of options to provide the user in updating the Metadata fields.

i) I could provide a text field and just set the metadata field to the user entered text, but I'm not sure that is particularly useful.

ii) I could provide a text field and allow the user to enter an expression, but will just duplicate the existing functionality.

iii) I can remove the metadata option, leaving the framework for it in place and it can be revisited later

I have everything else working now, and the checkboxes with radio button behaviour now look like radio buttons, and I have fixed an issue with the initialisation of the python fixes scripts. So I'd like to complete the PR and see if this can start the process of getting merged back into GC.

On a similar topic (#4095  #4214) I think I now understand why the auto import of python fixes doesn't work correctly, its because the current ride in the context is pointing to the previously processes activity and is not aligned with the rideFile when the python scripts are called. The reason for this that rideitem is created when context->athlete->addRide is called, so I'm not sure the "import" option for python processors is working correctly, whilst save which is called afterwards has the correct rideItem for the rideFile. I'll take a look at this problem once the BatchProcessingDialog is finished. Although I do find it odd that both import and save are in the ImportWizard, as this appears to me to just duplicate the processing?

**Comment by amtriathlon** [comment]
> I've looked at getFields and have the implemented that, but after looking through the GC tutorials and Wiki I'm still none the wiser as to what would be a sensible set of options to provide the user in updating the Metadata fields.
> 
> i) I could provide a text field and just set the metadata field to the user entered text, but I'm not sure that is particularly useful.

I think this the most common use case for users looking for a simple way to set a field for a bunch of activities, for example use a filter to select activities with power but no GPS data and mark the as trainer.

> ii) I could provide a text field and allow the user to enter an expression, but will just duplicate the existing functionality.

Agree, for users fluent in expressions we have set, and for the rest the simpler option i)

> iii) I can remove the metadata option, leaving the framework for it in place and it can be revisited later

I think think is worth to keep as i)
 
> I have everything else working now, and the checkboxes with radio button behaviour now look like radio buttons, and I have fixed an issue with the initialisation of the python fixes scripts. So I'd like to complete the PR and see if this can start the process of getting merged back into GC.

When update the PR I will review it.
 
> On a similar topic (#4095 #4214) I think I now understand why the auto import of python fixes doesn't work correctly, its because the current ride in the context is pointing to the previously processes activity and is not aligned with the rideFile when the python scripts are called. The reason for this that rideitem is created when context->athlete->addRide is called, so I'm not sure the "import" option for python processors is working correctly, whilst save which is called afterwards has the correct rideItem for the rideFile. I'll take a look at this problem once the BatchProcessingDialog is finished. Although I do find it odd that both import and save are in the ImportWizard, as this appears to me to just duplicate the processing?

I think it is better to keep this in #4095 thread for clarity and easy of tracking.

**Comment by paulj49457** [comment]
Thanks for the reply, I'll implement option i) and update the existing PR and description.

I'll keep the discussion on the import aspects on #4095, once this is done I move the info I find onto #4095

**Comment by paulj49457** [comment]
When we update the metadata for those that can be overridden are wanting to override them as per the Data->Metric window, or are wanting to update the underlying GC calculated metric? If the later is there a case that the edits would get overwritten ?

The dialog is currently as below, with a read-only field to indicate the metadata type, and a hint of the required format in the user editable field:

![Captureyy](https://user-images.githubusercontent.com/46629337/171229908-e773ff84-6c76-49c3-97ec-f041905bf295.PNG)

**Comment by paulj49457** [comment]
Almost there....

So I cannot change:

 "Start Time" & "Start Date", but I assume this correct as they are the key to the activity ?
"Data" do you want people to be able to change this field ?

 If so the above are not required, I'll remove them from the Combobox.

And finally I'll add an unset option to remove the metric overrides.

**Comment by paulj49457** [comment]
PR pushed back and ready for review

**Comment by paulj49457** [comment]
I just thought that a "Revert all selected files to saved versions" might be useful addition ? Let me know if you want this added, and any review comments from the current PR and I'll address any changes in a few days time.

**Comment by amtriathlon** [comment]
I will test and review the PR, thanks.

**Comment by liversedge** [comment]
I think a data filter should be available to filter/select the activities to process, I will look to add this over the weekend.

**Comment by amtriathlon** [comment]
> I think a data filter should be available to filter/select the activities to process, I will look to add this over the weekend.

Currently it honors the filter on Activities view, i.e. the displayed list matches what the user is currently seeing in the sidebar, but a dedicated filter could be more intuitive.
