### ISSUE TITLE
Script travil/linux/afeter_success.sh fails when executed on a non clean environment

### ISSUE THREAD

**Issue by peret2000** [GoldenCheetah/GoldenCheetah#4228]
After creating AppImage file, it renames it to FINAL_NAME=GoldenCheetah_v3.6-DEV_x64.AppImage with the bash command:
`mv GoldenCheetah*.AppImage $FINAL_NAME`

If the script is exeecuted in a clean environment,as continuous integration usually does, it is not a problem, because there is no an older version of the file, from the previous execution.
But in case it is used, for example, in a nightly batch in a non clean environment, or on demand, there may exist file from the previous execution. In such case, the script ends with error:
`mv: target 'GoldenCheetah_v3.6-DEV_x64.AppImage' is not a directory`

And the file is not created, but the old remains there

I have created a pull request (#4227) the corrects the issue, simply adding a line to remove the file if it existed:
`[[ -f ./$FINAL_NAME ]] && rm $FINAL_NAME`

**Comment by amtriathlon** [comment]
It would be easier to add -f option to mv, but anyway, this is a Travis specific script, it is not intended to be used in other environments or situations, feel free to create the scripts you need in your own fork.
