### ISSUE TITLE
goldencheetah hangs on workout completion step 2 of 4

### ISSUE THREAD

**Issue by damodaranudas** [GoldenCheetah/GoldenCheetah#4237]
OS: UBUNTU 20.04
GoldenCheetah_v3.6-DEV_x64.AppImage
Fitness Equipment: BkoolSmart Pro2
Fitness Equipment2: Garmin Watch as an ANT+ broadcasting HR device
ANTUSB-m Stick:  0fcf:1009 Dynastream Innovations, Inc. 

/etc/udev/rules.d/51-garmin-usb.rules 

```
# Garmin ANT+ - USB1
ATTRS{idVendor}=="0fcf", ATTRS{idProduct}=="1004", MODE="0666"
# Garmin ANT+ - USB2
ATTRS{idVendor}=="0fcf", ATTRS{idProduct}=="1008", MODE="0666"
# hLine USB2 ANT2
ATTRS{idVendor}=="0fcf", ATTRS{idProduct}=="1009", MODE="0666"
```

When training from a GPX activity, if I ride for more than 20 minutes on completion it hangs, the only choice is to press the abort button and the activity is lost, I already tried different GPX files, same result goldencheetah.log doesn't show any issue, just slope and powermeter values. 

The --debug command is a verbose of the goldencheetah.log , so I can't get additional hints to debug the issue, the latest entries from the log file and debug command showed:
```

.....
Debug: Setting fitness equipment target gradient to 10.7659
Debug: Setting fitness equipment target gradient to 11.2743
Debug: Setting fitness equipment target gradient to 11.6863
Debug: Setting fitness equipment target gradient to 11.2031
Debug: Setting fitness equipment target gradient to 10.5116
Debug: Channel 1 reliability is 62 %
Debug: Setting fitness equipment target gradient to 7.87963
Debug: Setting fitness equipment target gradient to 11.7009
Debug: Channel 2 reliability is 65 %
Debug: Setting fitness equipment target gradient to 12.4528
Debug: Setting fitness equipment target gradient to 10.6194
Debug: Setting fitness equipment target gradient to 7.4167
Debug: Setting fitness equipment target gradient to 12.9752
Debug: Setting fitness equipment target gradient to 10.5885
Debug: Setting fitness equipment target gradient to 11.9268
Debug: Setting fitness equipment target gradient to 11.3781
Debug: Setting fitness equipment target gradient to 7.97941
Debug: Setting fitness equipment target gradient to 27.2568
Debug: Setting fitness equipment target gradient to 28.9323
Debug: Setting fitness equipment target gradient to 11.7915
Debug: Setting fitness equipment target gradient to -2.86132
Debug: Setting fitness equipment target gradient to 5.3114e-06
Debug: Setting fitness equipment target gradient to 7.35033e-06
Debug: Setting fitness equipment target gradient to 9.06573e-06
Debug: 0 type= 1 device type= 120 freq= 57
Debug: 0 assign channel type RX
Debug: 0 type= 1 device type= 120 freq= 57
Debug: 0 type= 1 device type= 120 freq= 57
Debug: 0 assign channel type RX
......
```

That's all the information, I checked all the way up and there wasn't any issue on the log file, in all the cases I waited for more than 2 hours hoping to don't lose my valuable data but it just kept hanged and I had no choice than abort the activity after completed the workout.
I already tried removing and adding again the fitness device, using another Athlete folder than the default empty field. The issue doesn't occur on short tests under 1km, just on rides longer than 20min/5km. The stable version 3.5 hasn't this issue but that version is missing a key future, the GPS Live Map and my training ended up without any slope and positioning data so I preferred to push as a beta tester on the Dev version 3.6 trying to figure out but I couldn't.

**Comment by amtriathlon** [comment]
This has been reported several times and it is already fixed in snapshot builds, to recover data from failed sessions see the FAQs.
