### ISSUE TITLE
Crash at chart import time when the chart uses perspective property

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#4247]
This was introduced in https://github.com/GoldenCheetah/GoldenCheetah/commit/b7380389071fc638019a2acf1888be9ad1f0e7a5, only Overview checks the property isValid before using it, and it looks like it is not at import time.

Problem reported at the forum: https://groups.google.com/g/golden-cheetah-users/c/NuXT89nbwBk/m/76J2MnebBwAJ

**Comment by liversedge** [comment]
The Perspective::importChart() method should set the "perspective" property but it was missed.
