### ISSUE TITLE
Add Garmin Stamina ID's

### ISSUE THREAD

**Issue by deix** [GoldenCheetah/GoldenCheetah#4253]
After my last ride with Edge 1040 solar I was able to record and decode the ID's from the FIT file, that are used for the stamina and potential data: 

https://www.garmin.com/en-US/garmin-technology/cycling-science/physiological-measurements/real-time-stamina/

FIELD 137 --> Potential Stamina
FIELD 138 --> Stamina

![Stamina](https://user-images.githubusercontent.com/8902727/182336166-75c53be9-c080-4d24-962e-237558aacc8f.png)

P.S. I would be interesting to see, how well Stamina feture corelates with GC Stress implementation...

Best regards
Michal

**Comment by amtriathlon** [comment]
Can you attach a sample file?

**Comment by deix** [comment]
Please find attached the commute ride that I have made screenschot from - contains raw data from Garmin 1040 Solar and sensors.

[2022-07-29-14-34-58.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/9244996/2022-07-29-14-34-58.zip)

Some more detailed explanations from Garmin:
https://www.garmin.com/en-US/blog/outdoor/introducing-the-garmin-real-time-stamina-feature/
