### ISSUE TITLE
Google OAuth needs to be migrated or deprecated

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#4259]
The use of internal web browser is discouraged and OAuth out-of-band (OOB) flow will be deprecated on October 3, 2022, we would need to use the system browser and [loopback IP address (localhost or 127.0.0.1) flow](https://developers.google.com/identity/protocols/oauth2/native-app#redirect-uri_loopback) to get the credentials as explained in https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

It looks like this will not match our current OAuth framework and, if an alternative solution is not implemented, we should disable Google OAuth for both Google Drive sync and Google Calendar which is not used anyway since Diary view was deprecated.

**Comment by liversedge** [comment]
Lets deprecate Google drive and Calendar, they are not that popular (they were broken for over 6 months and no one complained)
