### ISSUE TITLE
Can't edit workout title/name after import

### ISSUE THREAD

**Issue by slcpunk** [GoldenCheetah/GoldenCheetah#4266]
running 3.6 dev release  ( used to work in 3.5 ) in Linux.
I can't edit a workout title.  If I click on the "workout" box, it just flashes but doesn't bring up the text box.
![image](https://user-images.githubusercontent.com/5738127/187963842-33fe305a-3486-47c8-87f4-fda23eb45b26.png)

**Comment by josswinn** [comment]
You seem to be missing the 'Data' tab that allows editing of the title and adding notes, etc. The tiles are read only and have to be configured to display the info (metrics, etc.) you want. If you want to change the Workout Code from 'Bike Mountain' then you need the 'Data' tab. Go to the top right of the window, click the + icon and add the 'Data' chart. 

![Screenshot 2022-09-01 at 17 29 40](https://user-images.githubusercontent.com/25022/187965885-fb8f7eb4-fe1b-4f50-b631-5547c558a6c3.png)

**Comment by slcpunk** [comment]
Got it, sorry.  Didn't understand that. I can't combine elements of the data tab and overview?  I would like to add the map and remove a bunch of the other stuff from data.  I just want a simple screen with the basic info - and the ability to edit the workout name.

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
