### ISSUE TITLE
Crash when selecting first item on Details->Workout->SubSport.

### ISSUE THREAD

**Issue by jmoric** [GoldenCheetah/GoldenCheetah#4268]
GoldenCheetah crashes when I select first item on Details->Workout->SubSport. I have inserted my own custom values in the options->Data Fields (Road, Home Trainer).

When I select item number two on the list everything working as it should! 

I have tried version 3.6RC and latest snapshot (2022-09-03T15:07:28.000Z).

Crash dump file are empty!

Please ask if you have any future question on this issue. Thank you.

**Comment by amtriathlon** [comment]
We have a dedicated thread in Users Forum to diagnose v3.6RC2 issues, please use it if you want to collaborate with debugging.
