### ISSUE TITLE
Find Intervals (Power) not all displaying after saving activity and not being deleted from json file after deleting

### ISSUE THREAD

**Issue by josswinn** [GoldenCheetah/GoldenCheetah#4270]
I've reported this on the user group: https://groups.google.com/g/golden-cheetah-users/c/DcOwJ8z3uEo

In summary, Find Intervals for an activity is finding 10+ Power intervals, saving them to the json file, but after saving the activity, only showing 4 found Power intervals under the USER section of activity intervals. 

When I remove all found intervals, save the activity and look at the json file, the found Power intervals are still in the json file - even repeated attempts at finding the intervals remain in the file. This only happens with Power intervals. When adding HR intervals, they are all listed after saving and are removed from the json file if I delete them. However, Power intervals remain. For example, this is from a saved (running activity) file after removing all found Power intervals:

"INTERVALS":[
			{ "NAME":"Lap 1 ", "START": 0, "STOP": 4382, "COLOR":"#000000", "PTEST":"false" },
			{ "NAME":"Peak 1min  (408watts) ", "START": 4307, "STOP": 4366, "COLOR":"#0000ff", "PTEST":"false" },
			{ "NAME":"Peak 2min  (349watts) ", "START": 112, "STOP": 231, "COLOR":"#a0a0a4", "PTEST":"false" },
			{ "NAME":"Peak 5min  (317watts) ", "START": 113, "STOP": 412, "COLOR":"#008080", "PTEST":"false" },
			{ "NAME":"Peak 10min  (311watts) ", "START": 133, "STOP": 732, "COLOR":"#00ff00", "PTEST":"false" },
			{ "NAME":"Peak 20min  (305watts) ", "START": 113, "STOP": 1312, "COLOR":"#800000", "PTEST":"false" },
			{ "NAME":"Peak 30min  (302watts) ", "START": 1112, "STOP": 2911, "COLOR":"#008000", "PTEST":"false" },
			{ "NAME":"Peak 60min  (300watts) ", "START": 113, "STOP": 3712, "COLOR":"#000080", "PTEST":"false" },
			{ "NAME":"Peak 1min  (408watts) ", "START": 4307, "STOP": 4366, "COLOR":"#0000ff", "PTEST":"false" },
			{ "NAME":"Peak 2min  (349watts) ", "START": 112, "STOP": 231, "COLOR":"#a0a0a4", "PTEST":"false" },
			{ "NAME":"Peak 5min  (317watts) ", "START": 113, "STOP": 412, "COLOR":"#008080", "PTEST":"false" },
			{ "NAME":"Peak 10min  (311watts) ", "START": 133, "STOP": 732, "COLOR":"#00ff00", "PTEST":"false" },
			{ "NAME":"Peak 20min  (305watts) ", "START": 113, "STOP": 1312, "COLOR":"#800000", "PTEST":"false" },
			{ "NAME":"Peak 30min  (302watts) ", "START": 1112, "STOP": 2911, "COLOR":"#008000", "PTEST":"false" },
			{ "NAME":"Peak 60min  (300watts) ", "START": 113, "STOP": 3712, "COLOR":"#000080", "PTEST":"false" },
			{ "NAME":"Peak 1min  (408watts) ", "START": 4307, "STOP": 4366, "COLOR":"#0000ff", "PTEST":"false" },
			{ "NAME":"Peak 2min  (349watts) ", "START": 112, "STOP": 231, "COLOR":"#a0a0a4", "PTEST":"false" },
			{ "NAME":"Peak 5min  (317watts) ", "START": 113, "STOP": 412, "COLOR":"#008080", "PTEST":"false" },
			{ "NAME":"Peak 10min  (311watts) ", "START": 133, "STOP": 732, "COLOR":"#00ff00", "PTEST":"false" },
			{ "NAME":"Peak 20min  (305watts) ", "START": 113, "STOP": 1312, "COLOR":"#800000", "PTEST":"false" },
			{ "NAME":"Peak 30min  (302watts) ", "START": 1112, "STOP": 2911, "COLOR":"#008000", "PTEST":"false" },
			{ "NAME":"Peak 60min  (300watts) ", "START": 113, "STOP": 3712, "COLOR":"#000080", "PTEST":"false" },
			{ "NAME":"Peak 1min  (408watts) ", "START": 4307, "STOP": 4366, "COLOR":"#0000ff", "PTEST":"false" },
			{ "NAME":"Peak 2min  (349watts) ", "START": 112, "STOP": 231, "COLOR":"#a0a0a4", "PTEST":"false" },
			{ "NAME":"Peak 5min  (317watts) ", "START": 113, "STOP": 412, "COLOR":"#008080", "PTEST":"false" },
			{ "NAME":"Peak 10min  (311watts) ", "START": 133, "STOP": 732, "COLOR":"#00ff00", "PTEST":"false" },
			{ "NAME":"Peak 20min  (305watts) ", "START": 113, "STOP": 1312, "COLOR":"#800000", "PTEST":"false" },
			{ "NAME":"Peak 30min  (302watts) ", "START": 1112, "STOP": 2911, "COLOR":"#008000", "PTEST":"false" },
			{ "NAME":"Peak 60min  (300watts) ", "START": 113, "STOP": 3712, "COLOR":"#000080", "PTEST":"false" },
			{ "NAME":"Peak HR 30sec #1 (156bpm) ", "START": 4337, "STOP": 4366, "COLOR":"#ff00ff", "PTEST":"false" },
			{ "NAME":"Peak HR 30sec #2 (154bpm) ", "START": 1155, "STOP": 1184, "COLOR":"#00ffff", "PTEST":"false" },
			{ "NAME":"Peak HR 30sec #3 (153bpm) ", "START": 1958, "STOP": 1987, "COLOR":"#ffff00", "PTEST":"false" },
			{ "NAME":"Peak HR 30sec #4 (153bpm) ", "START": 3356, "STOP": 3385, "COLOR":"#ff0000", "PTEST":"false" },
			{ "NAME":"Peak HR 30sec #5 (151bpm) ", "START": 3288, "STOP": 3317, "COLOR":"#0000ff", "PTEST":"false" },
			{ "NAME":"Peak HR 30sec #6 (151bpm) ", "START": 2455, "STOP": 2484, "COLOR":"#a0a0a4", "PTEST":"false" },
			{ "NAME":"Peak HR 30sec #7 (151bpm) ", "START": 2670, "STOP": 2699, "COLOR":"#008080", "PTEST":"false" },
			{ "NAME":"Peak HR 30sec #8 (151bpm) ", "START": 3474, "STOP": 3503, "COLOR":"#00ff00", "PTEST":"false" },
			{ "NAME":"Peak HR 30sec #9 (151bpm) ", "START": 1798, "STOP": 1827, "COLOR":"#800000", "PTEST":"false" },
			{ "NAME":"Peak HR 30sec #10 (150bpm) ", "START": 3754, "STOP": 3783, "COLOR":"#008000", "PTEST":"false" }

**Comment by liversedge** [comment]
If you do not want to keep these intervals then turn them off in interval discovery settings- this is not a bug.

**Comment by josswinn** [comment]
I do want the intervals but it’s not displaying them all when I save the file. And why does it treat Power and HR found intervals differently when saving to file?

**Comment by josswinn** [comment]
Note that I’m referring to Power intervals I have opted to find in a running file, not the automatically found intervals, such as Pace.
