### ISSUE TITLE
Import from OpenTracks (KML) is unsuccessful

### ISSUE THREAD

**Issue by dennisguse** [GoldenCheetah/GoldenCheetah#4271]
Import KML files generate from OpenTracks (KML2.2 and KML2.3) cannot be imported.
No error message is given; just reported as unsuccessful.

Test data for KML2.2 attached.
[opentracks-kml22.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/9542596/opentracks-kml22.zip)
Please note:
* that OpenTracks creates locations without coordinates to properly store timestamps (i.e., if GPS is off/not available or has no fix yet). More info: https://github.com/OpenTracksApp/OpenTracks/issues/639
* as of [v3.24.0](https://github.com/OpenTracksApp/OpenTracks/releases/tag/v3.24.0) exported timestamps (in GPX and KML) can contain timezone offset at time of recording (according to KML and GPX standard)

And we will migrate to KML2.3 soonish: https://github.com/OpenTracksApp/OpenTracks/pull/1217

**Comment by amtriathlon** [comment]
Kml file import is not supported, see https://github.com/GoldenCheetah/GoldenCheetah/blob/cabe078453cbe8e136b8adf8d4187a5be878671b/src/FileIO/KmlRideFile.h#L26

**Comment by dennisguse** [comment]
Ok.
Still some user feedback would be great.
