### ISSUE TITLE
Provide a Flatpak Version via Flathub

### ISSUE THREAD

**Issue by mesonium** [GoldenCheetah/GoldenCheetah#4272]
It'd be convenient to have a Flatpak version in addition to the AppImage, since the first one uses

a) flatpak runtime dependencies, which are updated regularly and does not fully rely on developers library files included in the AppImage
b) runs sandboxed
c) runs under immutable OS such as Endless OS, Fedora Silverblue + Kinoite and SteamOS
d) Is easy to update via the `flatpak` command or via the distribution's app installer like `Discover` on KDE Plasma.

P.S. I hope this is the right place to request this as a feature. :)

**Comment by amtriathlon** [comment]
I don't think we have the resources to add and maintain yet another distribution format, but contributions are welcome.

**Comment by scholzri** [comment]
@amtriathlon I've created a Flatpak manifest and submitted a PR to Flathub: https://github.com/flathub/flathub/pull/7591

The package includes:
- Full Python 3.7 scripting support (matching the AppImage)
- Qt WebEngine for maps
- Automated version updates via x-checker-data (zero maintainance from upstream! - until Python stack (sip + python) is modernized in upstream which would require a onetime adjustment in the flatpak manifest)

https://github.com/user-attachments/assets/d38cff4f-6d3e-40d3-a4e6-82e8c3b9be06

### Why I think a flatpak makes sense
AppImage's FUSE2 dependency is no longer actively maintained and causes issues on modern/immutable distros (e.g. Fedora Atomic), while Flatpak has become the de facto standard with native support across distributions, automatic updates via software centers, and better security sandboxing. 


### Options for the GoldenCheetah team

1. **Integrate metadata files** (optional, recommended): The `org.goldencheetah.GoldenCheetah.desktop` and `org.goldencheetah.GoldenCheetah.metainfo.xml` files can be added to the main repository. This is common practice and helps keep metadata in sync with releases.

2. **Verify on Flathub** (optional, recommended): After the Flatpak is published, the app can be verified by adding a token file to goldencheetah.org. Verification adds a checkmark badge on Flathub showing the app is officially associated with the project.
**Docs:** https://docs.flathub.org/docs/for-app-authors/verification/

3. List Flatpak as an Install option for Linux on the website
   

Currently the submission is marked as community/unverified packaging. If the team wants to verify it later, I'm happy to coordinate.

Best,
Richard
