### ISSUE TITLE
cadence error in GC compare to Garmin tool

### ISSUE THREAD

**Issue by michel90300** [GoldenCheetah/GoldenCheetah#4276]
the cadence in GC is divided by 2 compare with teh real value given by Garmin.
In fact the cadence in Garmin file and in Garmin Edge 1030+ device are the double of the GC cadence
To help you find attached screens of the problem :
1 – screen copy in the GC summary with the average and maximum cadence
2 – screen copy of the cadence graph
3 – screen copy in the Garmin connect tool with the cadence.
In  Garmin the cadence is the double of the GC cadence 

And finally the export Garmin file in original mode of this training
![screen copy cadence in garmin connect](https://user-images.githubusercontent.com/115394946/194746049-cc5363fe-b0cf-43c1-80c5-f2922758ab53.jpg)
![screen copy of cadence](https://user-images.githubusercontent.com/115394946/194746071-ef0b1e2e-ebc7-428e-b076-f222cff6600d.jpg)
![screen copy of summury](https://user-images.githubusercontent.com/115394946/194746091-70886c8d-645b-49ec-ae3c-c58508ab8c3e.jpg)
[9673816305.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/9741076/9673816305.zip)

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
