### ISSUE TITLE
FR - Clone Charts

### ISSUE THREAD

**Issue by doyler78** [GoldenCheetah/GoldenCheetah#428]
It would be great to have the ability to clone charts as I like to have some of my charts with different date ranges attached to aid short term and long term analysis and it would save a bit of trouble in drawing up the second chart.

**Comment by amtriathlon** [comment]
I am closing this since:
a) the compared feature discussed above is available from version 3.2 as documented in https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Compare-Pane_General
b) charts can be cloned via Export Chart / Import Chart in v3.5
