### ISSUE TITLE
error importing HRV4Training data

### ISSUE THREAD

**Issue by bencoremans** [GoldenCheetah/GoldenCheetah#4280]
Trying to import the default exported data from HRV4Training in Goldev Cheetah.
Receiving a error:
Downloading of HRV measurements failed with error: Invalid 'timestamp' - Date/Time not ISO 8601 format.

And yes the timestamp isn't ISO 8601 format. 
Do I have to convert the timestamp format?

Or is something changed in the export?
[hrv4training.csv](https://github.com/GoldenCheetah/GoldenCheetah/files/9810360/hrv4training.csv)

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
