### ISSUE TITLE
Train: No sound from Videos with audio encoded in OPUS

### ISSUE THREAD

**Issue by somehowdifferent** [GoldenCheetah/GoldenCheetah#4282]
Hey,

Thank you very much for this great piece of software. Last winter season I used the train mode with a set of instruction videos and synced erg workouts too a great extend. This was a great pleasure. Now in train view, I have no sound on ubuntu 22.04 GC 3.6 RC2 and videos encoded with audio in opus.

For this winter season, I updated my setup. Got me a new computer, installed ubuntu 22.04 from scratch, downloaded the current release candidate as appimage and imported the old config. This is verision GC 3.6 RC2 build 4011.

Unfortunately, I get no sound in videos encoded with OPUS.  ffprobe of these videos gives e.g.:

`  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 3509 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
`

The Problematic videos have opus audio:

`  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 50 tbc (default)
    Metadata:
      HANDLER_NAME    : ISO Media file produced by Google Inc.
      DURATION        : 00:20:38.520000000
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 00:20:38.541000000
`
Currently, it's not working with some of the latest appimage builds (build 4011 & buil 4010).

This has worked before:

On my previous setup with ubuntu 20.04 this worked flawlessly with 3.6 RC1 build 4010 irrespective of the audio codec. Both type of audio codecs worked. In addition the native goldencheetah bundled with ubuntu 22.04 build 3990 version 3.5-DEV1810 works with AAC audio and OPUS audio.

The VLC version from ubuntu repo (3.0.16) plays those videos all with sound.

Is it a bug, or a packaging error or does it relate to ubuntu 22.04? How could I provide more logs?

Best
somehow.different

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/wiki/VLC-Troubleshooting and, please, use the forum if you need help.
