### ISSUE TITLE
Italian translation - "Choose Cyclist" dialog buttons + some minor typos

### ISSUE THREAD

**Issue by gicif** [GoldenCheetah/GoldenCheetah#4283]
Improved the captions of the "Choose Cyclist" dialog buttons, to avoid ambiguity.
Fixed some minor typos.
[gc_it.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/9879364/gc_it.zip)

**Comment by amtriathlon** [comment]
Thank you!
