### ISSUE TITLE
Issue with updating new Athletes Zones and Saving it.

### ISSUE THREAD

**Issue by GradusLinksdure** [GoldenCheetah/GoldenCheetah#4284]
Hey
My GC breaks down while pushing the saving button when i want to update the zones. If i repeat that like 2times than it crashes the athlete and i have to delete/build him or restore it from a backup.

working on an fairly old OS...
<img width="792" alt="Bildschirmfoto 2022-10-28 um 23 22 46" src="https://user-images.githubusercontent.com/116921252/198735302-8f865e31-7e45-46a4-9446-9f41ac7714f9.png">
<img width="261" alt="Bildschirmfoto 2022-10-28 um 23 23 36" src="https://user-images.githubusercontent.com/116921252/198735311-75937cd8-7219-4eae-bcf3-5389197943cc.png">

**Comment by amtriathlon** [comment]
Please see https://github.com/GoldenCheetah/GoldenCheetah/wiki/Crash-diagnosis and use the forum if you need help.
Currently we are fixing bugs on v3.6 which is about to be released which is built on Mohave and intended for Mohave or higher.
