### ISSUE TITLE
GC.setTag is applied to the same activitiy when used from a postprocess filter

### ISSUE THREAD

**Issue by MeisterP** [GoldenCheetah/GoldenCheetah#4288]
My Test:
```
from datetime import datetime
TAG = 'Route'
now = str(datetime.now())

GC.setTag(TAG, now)
```

`postprocess("My Test", (Sport = "Bike"))`

The Route field in the first activity matching `Sport = "Bike"` is updated over and over again while all other activities matching `Sport = "Bike"` are not changed at all.

**Comment by amtriathlon** [comment]
This is another instance of https://github.com/GoldenCheetah/GoldenCheetah/issues/4095, currently Python DP can handle metadata correctly only when applied to the current activity.
