### ISSUE TITLE
Unable to select multiple workouts in the workout list GC3.6

### ISSUE THREAD

**Issue by madetheweekend** [GoldenCheetah/GoldenCheetah#4289]
In version 3.5 it was possible to select multiple workouts for when one was to delete multiple workouts. In 3.6 its only possible to select one at the time. 

If this is incorrect just discard my post.

**Comment by madetheweekend** [comment]
Im new to github and reporting bugs and issue. Did I do it right or was this maby not an issue? 
Casue I might have found an other problem in 3.6.

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
