### ISSUE TITLE
3.6 Release - program is closing

### ISSUE THREAD

**Issue by MichaelBavaria** [GoldenCheetah/GoldenCheetah#4293]
HIs - made an observation
By using the Release version 3.6 and switching to Training mode, the program is closing immediately as long as i have not attached the ANT+ dongle.
When the dongle is connected, the program is running smoothly.

I am using an McBook Air with M1 processor.

just to let you know...

**Comment by amtriathlon** [comment]
https://groups.google.com/g/golden-cheetah-users/c/BW5pfoCW4KY/m/ffvYoktZAAAJ

**Comment by MichaelBavaria** [comment]
Hi,
Automatic connection is already active!

Michael 

Von meinem iPhone gesendet

**Comment by amtriathlon** [comment]
Then disable it.
