### ISSUE TITLE
Improving "Left/Right Balance" Train Telemetry Chart 

### ISSUE THREAD

**Issue by MarcoAzz** [GoldenCheetah/GoldenCheetah#4298]
Hi there!

i would appreciate so much the possibility , for "Left/Right Balance" Train Telemetry Chart,
of smoothing regulation by a slider (equal to some Power Telemetry Chart) 

and also possibility of swapping DX and SX data (using my Favero Assioma Duo, these data are already swapped on its own)

thanks in advance for your kind attention and spent time for this beautiful project!
Marco

**Comment by MarcoAzz** [comment]
Hello Alejandro,
first af all, thank you very much for your job! 

i used it a few times (with "Build date: Dec 23 2022 23:03:37 - Build id: 4012" dev. release) and it's correctly working, comparing with Balance data into my Garmin Edge 830.

Unfortunnatelly there's a strange "initialization" bug, displayed data are random/wrong, until Averaging Ratio is changed once during the train.
This happens at every start of a training (or at least at every start of GoldenCheetah SW) and it doesn't relate to the initial "Smooth (sec)" value.
It seems like "Smoothing procedure" is not correctly reading the smoothing value when the train starts, but only when the value is modified.

not a big problem anyway ;-)
thanks again!
Marco

**Comment by amtriathlon** [comment]
You are right, there is a pre-existing bug in the initialization of the rolling average code, it affect all series with rolling average, I will fix it.
