### ISSUE TITLE
Reorder Sync Activity Services as most used on top (userfriendly)

### ISSUE THREAD

**Issue by VNT974** [GoldenCheetah/GoldenCheetah#4300]
Hello.

I would like to request a better Sync Activity Services order to put the most used on top,
Today for the Top 5 it's as -- and I am far (10th) from the list to connect to Strava for the first sync.
Cycling Analytics
Dropbox
Local Store
Nolio
RideWithGPS

I would be more looking into something like:
Local Store (which is 3rd)
Strava  (which is 10th)
Today's Plan (which is 11th)
Xert (which is 14th)
Nolio (which is 4th)
Dropbox (which is 2nd)

Thank you.

**Comment by amtriathlon** [comment]
I am closing this since it will not likely be implemented considering it is a one time task where fast access is not that relevant, the list is not that long and alphabetic order makes easy to find what the user is looking for.
