### ISSUE TITLE
Missing distance when importing old Fitlog files.

### ISSUE THREAD

**Issue by JdjJr** [GoldenCheetah/GoldenCheetah#4301]
I just started using Golden Cheetah to import old SportTracks fitlog
data.  It is working well for most new workouts, but for workouts from
SportTrack Version 2 it often imports the data incorrectly. My
26.2-mile marathon is only 15.4 miles in Golden Cheetah.

I think the issue is the fitlog files have track points that have only
heartrate data, and no lat, lon, and ele data.  I think this is caused by
poor GPS reception. 

For example, the start of my fitlog marathon data is:

   Track StartTime="2005-03-06T15:00:27Z">
    pt tm="0" lat="38.5852851867676" lon="-122.570617675781" ele="110" hr="90" 
    pt tm="7" lat="38.5852851867676" lon="-122.570617675781" ele="110" hr="95" 
    pt tm="13" lat="38.585262298584" lon="-122.570587158203" ele="109" hr="101" 
    pt tm="17" lat="38.5852279663086" lon="-122.570518493652" ele="113" hr="107" 
    pt tm="23" lat="38.5851745605469" lon="-122.570434570312" ele="115" hr="113" 
    pt tm="33" lat="38.5850791931152" lon="-122.570281982422" ele="116" hr="118" 
    pt tm="47" lat="38.5849266052246" lon="-122.570014953613" ele="115" hr="124" 
    pt tm="61" hr="120" 
    pt tm="69" lat="38.5847282409668" lon="-122.569564819336" ele="113" hr="126" 
    pt tm="84" lat="38.5845756530762" lon="-122.569183349609" ele="114" hr="127" 
    pt tm="98" lat="38.5844573974609" lon="-122.568855285645" ele="113" hr="126" 

In Golden Cheetah (build Dec 11, 2022) the raw data for this becomes:

Time	Dist	  HR	Speed	Alt	Lat		Lon		Slope
...	
13	0.003813	101	2.28791	109	38.58526	-122.571	-26.2248	
17	0.011956	107	7.32847	113	38.58523	-122.571	-26.2248	
23	0.021582	113	5.77583	115	38.58517	-122.57		20.7762	
33	0.038612	118	6.13057	116	38.58508	-122.57		5.87221	
47	**0.067412**	124	7.40566	115	38.58493	-122.57		-3.47225	
61	**0.067412**	120	**0**	         0	0		0		-3.47225	
69	**0.067412**	126	**0**	        113	38.58473	-122.57		-3.47225	
84	0.104713	127	8.95236	114	38.58458	-122.569	2.68086	
98	0.136165	126	8.0877	113	38.58446	-122.569	-3.67165	

Note that the computed distance is unchanged for 3 data points at time
47,61, and 69. And that speed is zero for two points.

I think the issue is in the GoldenCheetah/src/FileIO/FitlogParser.cpp
file.  There is the code:

            foreach(RideFilePoint *point, rideFile->dataPoints()) {

                if (first == true) {
                    if (point->lat && point->lon) first = false;
                } else {

                    if (last.lat && last.lon && point->lat && point->lon) {

                        if (rideFile->areDataPresent()->alt)
                            rdist += distanceBetween(last.lat, last.lon, last.alt,
                                                     point->lat, point->lon, point->alt);
                        else
                            rdist += distanceBetween(last.lat, last.lon, point->lat, point->lon);
                    }
                    point->km = rdist; 
                }
                last = *point;
            }
            rideFile->setDataPresent(RideFile::km, (rdist > 0));
        }

I think the ‘last = *point;’ statement is executed for every track
point, even if there is no lat and log data.  This means ‘last’ will
hold the zeros form the missing lat and log.  And thus, the distance
covered by the point after the heart rate only line is lost on the
next pass through the loop. It will not execute either of the “rsist
+=” statements because “last” contains zeros.

Also, there are many “invalid recording gap” warning in the Raw Data
report.  I suggest the fitlog import should interpolate between the
data points as is done in the GPX import.

When I export this same workout from SportTracks as a GPX then Golden
Cheetah says the distance is 26.5 miles, and the Raw Data has point
every second.  But the GPX has no heartrate data.  If you want me to
upload some examples please let me know.

Thanks,
John

**Comment by amtriathlon** [comment]
GC has tools to fix data issues, please see the wiki and use the users forum if you need help.
