### ISSUE TITLE
Average_Heart_Rate metric in Trends view uses 0 values

### ISSUE THREAD

**Issue by jgpallero** [GoldenCheetah/GoldenCheetah#4302]
I did some bike routes without heart rate monitor and I can see that the Average_Heart_Rate metric for the activity is set to zero (values, asstring). But in Trends view these zero values are apparently aggregated to the total mean (values, asaggstring) as I can see an anomalous too small average heart rate for a period comprising these routes without the heart rate monitor. I think this kind of values (zero or, for example, less than 30 mean bmp) must not be taken into account for mean computation in trend analysis.

**Comment by amtriathlon** [comment]
Problem is asaggstring/aggmetric/aggmetricstrings don’t honor AggregateZero property of metrics like LTMPlot does, related to this but subtler is they don’t honor the count property either.

**Comment by amtriathlon** [comment]
We could reproduce the logic in LTMPlot, but since it is somewhat involved perhaps would be better to use:
https://github.com/GoldenCheetah/GoldenCheetah/blob/33ba1c03ecded8e919b916f64d5768c499fd790d/src/Core/RideCache.cpp#L589
like RideSumary did
