### ISSUE TITLE
GC crashed when changing from Activities to Trends

### ISSUE THREAD

**Issue by MatzeG** [GoldenCheetah/GoldenCheetah#4306]
Hello 

i´m not shure if it is a bug or my mistake. I think since the CI Build ci.4669 GC crashes when I change from Activities to Trends. When I revert the Version back to < ci.4669 everything works fine. Example Build Dec 30, 14:29:31 Build Id 4012 has no problems
I´m using GC on Windows 10 Build 2009

Matthias

[GC_Crash_Report.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/10401038/GC_Crash_Report.zip)

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
