### ISSUE TITLE
Select Workout and VideoSync automaticcaly when selecting video

### ISSUE THREAD

**Issue by vlcvboyer** [GoldenCheetah/GoldenCheetah#4316]
In train view when preparing a virtual activity workout:
When a video is selected, select automatically the VideoSync file and the Workout file accordingly (if any)

When no matching file is found (based on exact filename match): do nothing
When user overide this auto-select afterward: accept user choice

**Comment by amtriathlon** [comment]
It looks like a duplicate of https://github.com/GoldenCheetah/GoldenCheetah/issues/3886

**Comment by vlcvboyer** [comment]
#4320
