### ISSUE TITLE
BTLE on 3.6-DEV on Win10 not working

### ISSUE THREAD

**Issue by barsk** [GoldenCheetah/GoldenCheetah#4317]
Hi!
Trying to connect GC to an old Tacx T1932/T1901 trainer with the help of the FortiusANT project that converts the USB interface to BTLE or ANT+ with the help of a Raspberry Pi device (RPi 3). As the Pi has onboard BLTE it uses that and becomes a BTLE "stick". It supports power, cadence  etc. This is the background, but not the cause for this report

When I add a "Bluetooth 4.0" device there is no check. This is done at "Session startup". So I start a train session and click the red connect button. It changes to green and the message says it is connected. But to *what*?
It does not connect to the RPi device (acting as BLTE), and *everything* else that is BT is switched off, even the onboard BT on the computer, my mobile phone etc. I even tried switching off the RPi as well, but GC still connects to *something*. To what?
 
Tried starting in console with --debug, but the log file is empty. Have no idea how to get this to work or even get some feedback from CG what it is doing.

**Comment by amtriathlon** [comment]
Please see the FAQs on Train and Troubleshooting and use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
