### ISSUE TITLE
Lap selection is erratic in maps

### ISSUE THREAD

**Issue by argmac** [GoldenCheetah/GoldenCheetah#432]
The lap selection feature works fine in the ride view, but the behaviour is erratic in the map view. Generally this happens after jumping to different workouts. My environment is Windows 7.

I am attaching an example where a lap is selected but is not reflected in the map. It is followed with the same example after closing and reopening GC.

![08-01-2013 19-14-42](https://f.cloud.github.com/assets/2953773/51061/eaf8cd1a-59bf-11e2-9dea-d7c545162d52.png)

![08-01-2013 19-16-58](https://f.cloud.github.com/assets/2953773/51060/eadeb420-59bf-11e2-9ae7-027dafb5f4ca.png)

**Comment by amtriathlon** [comment]
This seems to be working much better now with OSM and Leaflet API.
