### ISSUE TITLE
Workout preview

### ISSUE THREAD

**Issue by vlcvboyer** [GoldenCheetah/GoldenCheetah#4321]
At present there is a preview for ERG workout but pgmf or gpx based workout do not have.
Same graph than alt/slope one in bike activity tab will be great:
![image](https://user-images.githubusercontent.com/13483855/213903769-8c0f720f-10aa-4a84-b4ad-dc84a5a1e9eb.png)
But showing distance instead of time of course

**Comment by amtriathlon** [comment]
Yes, they have using the Workout and Map charts, create a new athlete to try the new perspectives.
