### ISSUE TITLE
New Cloud Provider - Azum

### ISSUE THREAD

**Issue by DanielZelei** [GoldenCheetah/GoldenCheetah#4324]
This feature is about adding new cloud service provider - Azum (https://www.azum.com/en/)

Implementation is based on https://github.com/GoldenCheetah/GoldenCheetah/wiki/Using-the-Cloud-Services-API.

OAuth, Download and Query capabilities are used for the service. Client id is hard-coded, secret will be shared with the GC build team (please let me know how I should share it)

https://github.com/GoldenCheetah/GoldenCheetah/pull/4323

**Comment by amtriathlon** [comment]
Fixed by #4323
