### ISSUE TITLE
Perspective selector out of sync when switching athlete tabs

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#4325]
Steps to reproduce:
1) Open an athlete, go to Trends view and select a perspective other than the 1st one
2) Open another athlete
3) Go back to the 1st athlete, perspective is the last used but perspective selector points to the 1st one.

I tried to fix this via https://github.com/GoldenCheetah/GoldenCheetah/commit/3a16d1ecc2005eb87e520d8dfadc692fcab958fe, but it introduced other issues, so it was reverted.

**Comment by liversedge** [comment]
When switching athletes the perspective selector is refreshed correctly to list the perspectives that apply for the view and athlete combination but the current index is always reset to 0

**Comment by amtriathlon** [comment]
Yes, may be I was no clear enough, the “out of sync” refers to just the current index.

**Comment by liversedge** [comment]
It looks like MainWindow::resetPerspective() needs some work, it is called from restoreGCState() from switchAthleteTab() but doesn't quit finish the job, see 91f2c46c3e73e1dd5198abb3e52d63ff7c3ab3d6 for the original intent.

Fix should be fairly straight forward, will look into it tomorrow night

**Comment by amtriathlon** [comment]
Hi Mark, the strange behavior described in https://groups.google.com/g/golden-cheetah-users/c/w2CQHC2wUhI/m/2QLc9aJXCgAJ after my reverted fix is present again with your commit, but it seems easier to fix now, just adding

`pactive=true;`

before
https://github.com/GoldenCheetah/GoldenCheetah/blob/64386bc1ba81ea90f188eb674859860fcac771c0/src/Gui/MainWindow.cpp#L1465-L1467

Avoids the interference.

**Comment by liversedge** [comment]
Yes that makes a lot of sense since it will stop signals being processed, will update
