### ISSUE TITLE
Fit file: decode rider position (seated/standing)

### ISSUE THREAD

**Issue by vlcvboyer** [GoldenCheetah/GoldenCheetah#4328]
When using pedal powermeters rider position is part of FIT records.
Getting it will allow to change CdA estimate during ride analysis.
Associated PR is #4327

**Comment by vlcvboyer** [comment]
Hi developpers,
Any blocking points or comments related to this pending feature request and associated PR #4327 ?
Best regards
Vianney

**Comment by liversedge** [comment]
hey

I have been fixing bugs and working on generic parsing of message types into XDATA. Will be comitting sometime in the next couple of weeks and will come back to look at your PR.

My changes are quite large, so may need to redo your work- but will try and support that as I am the one causing the problem.

Also, apologies for the delay in looking at this.

**Comment by vlcvboyer** [comment]
Ok no problem
Thanks for this update

Please di not hesitate to send me reminder if I do not see any rebasing or
rewriting few weeks after your merge on master

Best regards


Le jeu. 9 nov. 2023, 16:13, Mark Liversedge ***@***.***> a
écrit :

**Comment by liversedge** [comment]
Hey- the code is committed can you fix the conflicts so I can merge?
