### ISSUE TITLE
Text in Details -> Notes disappears 

### ISSUE THREAD

**Issue by T-pyRacer** [GoldenCheetah/GoldenCheetah#4332]
Text enetered in "Notes" regularly stops displaying. 

The activities window shows the notes but they are no longer visible in the Notes window

<img width="894" alt="Screenshot 2023-02-14 at 08 45 58" src="https://user-images.githubusercontent.com/117720274/218672738-824d10e8-8b32-4f81-b08e-6eefd6ee3ba3.png">

Using snapshot build id: 4012
DB Schema: 157
Metrics: 384
OS: MacOS 10.16

**Comment by amtriathlon** [comment]
Try resetting metadata config and use the forum if you need help, there is a thread for feedback on this version: https://groups.google.com/g/golden-cheetah-users/c/w2CQHC2wUhI
