### ISSUE TITLE
Crash when saving activity after changing athlete

### ISSUE THREAD

**Issue by 0xAlittleCoder** [GoldenCheetah/GoldenCheetah#4335]
GC constantly crashes when I am trying to save a new activity (for example in the training mode) after I have switched the athlete in the same session. When I already start the session with the corresponding athlete (only with the athlete selection which occurs at the next start after GC crashed) no issues occur during saving.

I followed all steps proposed in: https://github.com/GoldenCheetah/GoldenCheetah/issues/3308
 - Graphics drivers updated
 - Disabled OPEN_GL

GC Version: 3.6-beta (build ID 4009).
OS: Win10 - 10.0.19044

Here is a crash dump:
[crash_0653_040323.log](https://github.com/GoldenCheetah/GoldenCheetah/files/10887624/crash_0653_040323.log)

Thanks in advance for your support!

**Comment by amtriathlon** [comment]
See https://github.com/GoldenCheetah/GoldenCheetah/wiki/Crash-diagnosis
