### ISSUE TITLE
python issue  - GC module is not found

### ISSUE THREAD

**Issue by marcelschilling** [GoldenCheetah/GoldenCheetah#4343]
Hey!

I am using GoldenCheetah v3.6 on Ubuntu  20.04. I tried to integrate python, but the GC module is not found:

<module>NameError: name "GC" is not found...

Here is my conda env:

name: golden-cheetah
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.15=h7a1cb2a_1
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.41.1=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==1.4.0
    - asteval==0.9.29
    - astunparse==1.6.3
    - boto3==1.26.98
    - botocore==1.29.98
    - cachetools==5.3.0
    - charset-normalizer==3.1.0
    - colour==0.1.5
    - flatbuffers==23.3.3
    - future==0.18.3
    - gast==0.4.0
    - goldencheetah-opendata==0.3.1
    - google-auth==2.16.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.51.3
    - h5py==3.8.0
    - idna==3.4
    - importlib-metadata==6.1.0
    - jmespath==1.0.1
    - joblib==1.2.0
    - keras==2.11.0
    - libclang==16.0.0
    - lmfit==1.1.0
    - markdown==3.4.3
    - markupsafe==2.1.2
    - numpy==1.21.6
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - packaging==23.0
    - pandas==1.2.3
    - pkgsettings==1.0.0
    - plotly==5.13.1
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - s3transfer==0.6.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - sip==4.19.7
    - six==1.16.0
    - tenacity==8.2.2
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.2.0
    - threadpoolctl==3.1.0
    - typing-extensions==4.5.0
    - uncertainties==3.1.7
    - urllib3==1.26.15
    - werkzeug==2.2.3
    - wrapt==1.15.0
    - zipp==3.15.0

Do you have any idea regarding this issue?

Best,
Marcel

**Comment by amtriathlon** [comment]
Please see the wiki and use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
