### ISSUE TITLE
CP, W', p-Max

### ISSUE THREAD

**Issue by Haas01** [GoldenCheetah/GoldenCheetah#4345]
For me, in the pre-release (March 4, 2023), the progressions of estimation values (CP, W', p-Max) are no longer displayed, or only in fragments. Canditate 3 (build 4012) works perfectly.

**Comment by amtriathlon** [comment]
There is a [thread in the users forum](https://groups.google.com/g/golden-cheetah-users/c/_oIVY4rgU6M) for RC4 feedback and discussion, please use it.
