### ISSUE TITLE
Initial settings and themes are terrible

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#4350]
Having reinstalled from scratch using the official installer on MacOS Monterey the following settings are terrible
* default font is times roman, looks ugly in GUI elements c97eac6
* default font scaling is not set and undefined, leading to tiny fonts c97eac6
* the sidebar is too wide c97eac6
* the color theme is old but with an ugly toolbar and sidebar c97eac6
* the default overview chart font scaling is way too small
* "chrome" "Flat" or "Mac" setting is very confusing since it is really deprecated and needs to be removed from code c97eac6

We should fix this before we release v3.6 as it creates a terrible first impression. It appears that most of these problems affect all platforms so should be fixed for all, not just MacOS

**Comment by liversedge** [comment]
So three areas to fix
* application settings for appearance
* sidebar settings for current athlete in all views
* overview user chart font settings

**Comment by liversedge** [comment]
Font fallback should try, in order:
* SF Pro Display
* Helvetica Neue
* Helvetica
* Trebuchet MS
* Verdana
* Arial

**Comment by liversedge** [comment]
Default theme should become
* Team Colours (light)

**Comment by liversedge** [comment]
Initial Window Size
* Center on the display
* Leave space for 1 toolbar height above and below
* Leave space for 2 view selectors width to the left and the right

**Comment by liversedge** [comment]
Bear in mind, even 2015 devices (iMac) can have a resolution of 1920x1080 whilst modern 5k Retina displays have a resolution of 5120x2880 and external 8k devices are now supported with a resolution of 7680x4320 -- scale factors are now becoming more important. We may need to support a larger value for scale factor in preferences.

**Comment by liversedge** [comment]
For overview, the scaling factor should only be "calculated" the first time the chart is displayed since the user may want to adjust to their personal taste.

To achieve this we should add an ```AthleteGUID``` to the user chart properties and set it to the current athlete once the settings have been defaulted. We can then check if the value matches, and if so avoid trying to calculate an appropriate scaling factor.

**Comment by liversedge** [comment]
To calibrate the font scaling of a user chart 
* it is only required when placed on an overview
* the height of the legend should match the height of the tile title
* the matching of heights should be calculated in screen pixels

**Comment by amtriathlon** [comment]
> The basic settings have been developed and need to be tested.

I built and did some tests on Windows 11 and Ubuntu 22.04 and initial settings look much better, no problems detected either.

**Comment by liversedge** [comment]
> > The basic settings have been developed and need to be tested.
> 
> I built and did some tests on Windows 11 and Ubuntu 22.04 and initial settings look much better, no problems detected either.

Thanks Ale- I need to test on MacOS with different resolutions. I also think the upgrade should ask if the user wants to upgrade to the latest charts (and put their current charts in a "Legacy" perspective).

I also think a button on the appearance pane in prefs to "Reset to defaults" should be available- and will be useful when people change resolution of their screen.

**Comment by liversedge** [comment]
I have noticed that QFont::exactMatch() does not work in Qt 5.15.1, so we MUST build official binaries with 5.15.2

**Comment by liversedge** [comment]
OK- so the issue with legends and fonts in overview charts in related to the way fontscaling is calculated-- at present it is always defaulted to 1 and the base font pointsize is adjusted but not adaptable in preferences, so we get stuck.

Instead the base pointsize should stay at 11 and the scaling should be adapted instead. The one issue with this is some users like small fonts on hidpi displays- in which case they can scale it back in prefs, rather than the current approach whic yields tiny fonts that the majority of users will dislike.

**Comment by liversedge** [comment]
Just tested latest snapshots on an old i5 based imac with crappy intel graphics (would not recommend using for gc in general !) and the default settings were good. The font was still on the larger size but was reasonable and much improved for the fixes in this issue.
