### ISSUE TITLE
v3.5 on Ubuntu 20.04 I keep getting "force quit or wait" notice about every 30 seconds

### ISSUE THREAD

**Issue by TheWayOfTheWheel** [GoldenCheetah/GoldenCheetah#4353]
I can't really get any further with this thing until I understand why it's doing this.

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.

**Comment by MeisterP** [comment]
I think this is actually an issue with goldencheetah and it is probably related to https://github.com/GoldenCheetah/GoldenCheetah/issues/3611

As mentioned on the forum, a workaround is to set the timeout for mutter either to 0 or to a higher value (default is 5000ms)
`$ gsettings set org.gnome.mutter check-alive-timeout 0`

**Comment by liversedge** [comment]
#3611 fixes the pool deadlock, so likely just updating metrics after upgrade

**Comment by MeisterP** [comment]
> so likely just updating metrics

Yeah, might be true. I think it most often happened to me when updating an activity and metrics were recalculated. Especially when the activity has lots of intervals.
