### ISSUE TITLE
Edits to notes/keywords are not persistent

### ISSUE THREAD

**Issue by diarmuid** [GoldenCheetah/GoldenCheetah#4355]
OS: Macos Version 13.3.1 (22E261)
GC: build 4013 ie  Goldencheetah 3.6 RC March 2023

All my files are stored on a Google Drive shared folder, 2402 entries in activities folder. As part of the debug for this issue ,I deleted the cache folder.

My recent activities have been imported from Strava (for information)

So the issue is simple. When I edit the Notes or keyword fields in an activity that I recently imported, the change is not persistent. I can save the file, but as soon as I do, the fields I have modified revert. 
If I open the raw json file, I can see that GC is recording that changes are happening. The "Change History" field is updated with the timestamp but the Notes and Keyword field are unchanged.
As a workaround I can edit the json file directly and the notes get updated.

Any ideas as to what I could be doing wrong. Or should I delete some config file?

**Comment by amtriathlon** [comment]
Please, see the caveat on [the wiki entry about the athlete library](https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Setting-the-athlete-library) and use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help. Thanks.
