### ISSUE TITLE
Runningzones not configurable

### ISSUE THREAD

**Issue by MicroWu1** [GoldenCheetah/GoldenCheetah#4361]
Operating system: MAC OS Catalina
GC version: 3.6 from March 2023

In the zone settings, only "*" can be selected as an alternative to "Bike". As a result, for example, the time in the zone diagram for the power zones in sports running is empty. In version 3.5 everything works correctly.

Kind regards

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
