### ISSUE TITLE
GoldenCheetah crashes when built with python 3.11

### ISSUE THREAD

**Issue by MeisterP** [GoldenCheetah/GoldenCheetah#4362]
Running current git master. It works as expected with python 3.10, but fails with python 3.11

With python debugging enabled:
```
$ GoldenCheetah --debug
[Python/PythonEmbed.cpp:69 pythonInstalled] PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/opt/bin:/usr/lib/llvm/15/bin
[Python/PythonEmbed.cpp:80 pythonInstalled] Binary found:4
[Python/PythonEmbed.cpp:116 pythonInstalled] Running: /usr/bin/python3.11
[Python/PythonEmbed.cpp:174 pythonInstalled] Python path:  :/usr/lib/python311.zip:/usr/lib/python3.11:/usr/lib/python3.11/lib-dynload:/usr/lib/python3.11/site-packages 
[Python/PythonEmbed.cpp:225 PythonEmbed] Python is installed: /usr/bin/python3.11
[Python/PythonEmbed.cpp:228 PythonEmbed] Py_SetProgramName: /usr/bin/python3.11
[Python/PythonEmbed.cpp:232 PythonEmbed] PyImport_AppendInittab: goldencheetah
[Python/PythonEmbed.cpp:236 PythonEmbed] PyInitializeEx(0)
Fatal Python error: memory allocation failed
Python runtime state: core initialized

Current thread 0x00007f98c8a7b940 (most recent call first):
  <no Python frame>
```

I don't know how to get a more meaningful debug output. Some help would be appreciated.

For people encountering the same issue: You can disable python by launching `GoldenCheetah --no-python` to get past the crash.

**Comment by liversedge** [comment]
It looks like SIP may need to be the very latest version since the ABI has changed and SIP needed patching.

To do this you will need to install the latest version of SIP, go into ```src/Python/SIP``` and ```make -f Makefile.hack``` to regenerate the sip generated sources. (if nothing is regenerated just do ```touch goldencheetah.sip```
You can stash and pop every time you pull from master to avoid having to repeat this all the time.

Can you let us know if this works for you ?

**Comment by liversedge** [comment]
Added to 3.7 milestone as we might choose to update SIP version and support 3.7 and up versions

**Comment by MeisterP** [comment]
Yes, I'm regenerating the sources in `src/Python/SIP` using `sip-4.19.25` which is the newest of the discontinued 4.* branch. (without that, the build would fail at compile time) Latest sip is sip-6, which works differently and is not backwards compatible. 

> Can you let us know if this works for you ?

It did work like you describe until python version 3.10. But no longer does for for 3.11

**Comment by zetxx** [comment]
same here, last sip but crash happen

**Comment by thejockl** [comment]
The attached patch fixed the issue for me. Since I am using the Debian provided python, I could not test it against 3.10
[32.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/11616110/32.zip)

**Comment by liversedge** [comment]
Moved to 3.6 milestone since its not an ABI issue per se, but a bug

**Comment by liversedge** [comment]
@thejockl apologies for committing the patch with the wrong author name.

**Comment by thejockl** [comment]
No issues, always happy to help :) Thanks for all your work on GC!
