### ISSUE TITLE
the variable kphd is expressed in m/s^2

### ISSUE THREAD

**Issue by MarcoCecotti** [GoldenCheetah/GoldenCheetah#4370]
I am not sure if this is an issue per se or not, but:
* The name kphd is probably misleading.
* This unusual naming convention seems to have generated some problems in the calculation of power.

I just wanted to flag this as a potential issue while I am investigating the power problem. Apologies if this is a draft for now, I will complete it shortly.

Below I have attached a snapshot of src/FileIO/RideFile.cpp, for reference:

![Screenshot from 2023-06-10 18-51-13](https://github.com/GoldenCheetah/GoldenCheetah/assets/12512866/14bea733-c4ec-43c8-b622-c0ddebb9177c)

**Comment by MarcoCecotti** [comment]
It doesn't seem to be an issue, so I have closed it :)

**Comment by amtriathlon** [comment]
No problem, but next time use the forums, we have one for users and other for discussions involving code.
