### ISSUE TITLE
Strava sync does not download all activities

### ISSUE THREAD

**Issue by Hezelnutt** [GoldenCheetah/GoldenCheetah#4376]
I use strava to download my activities to GC. When using the automatic sync on startup option, or the sync button in the bottom left corner, GC usually only syncs a couple of activities. For example, it only syncs 2 out of 10 new activities. 

When I keep pressing the sync button, it will download a couple of new activities every time, until eventually it is up to date.

When using the Strava download option via the top menu (Share > synchronise activities > strava) the issue is not there; all activities are downloaded at once.

I am not sure where the issue lies, but it would be great if it can be solved. If I can provide extra data please let me know.

**Comment by liversedge** [comment]
Automatic sync only looks for the last 30 days
