### ISSUE TITLE
Mac crashes

### ISSUE THREAD

**Issue by docsport77** [GoldenCheetah/GoldenCheetah#4379]
Use build 4013 on two different macs and both are crashing when I open GC.

Learned to live with it and start GC first when the Mac is on but maybe it is interesting for the one or other user.

When I start GC first the Mac freezes, then goes dark and then I have to fill in my password again, from there everything is normal.

From time to time it is opening without this trouble, 1-2 out of 10, not sure what is the difference then

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
