### ISSUE TITLE
CP Power estimate always 0

### ISSUE THREAD

**Issue by docsport77** [GoldenCheetah/GoldenCheetah#4388]
For some athletes the CP estimate implemented in a downloaded view is showing (always) as for others not (always).

For athletes it is working I have (it came with the download and I have changed nothing and let my fingers from things I don´t understand

{
 est <- round((estimate(cp3,cp) +
              estimate(cp2,cp) +
              estimate(ext,cp))/3);
}

for those not working

{
 est <- round((estimate(cp3,cp) +
              estimate(cp2,cp) +
              estimate(ext,cp))/3);
}

For those working it is even running for short and light rides as for those not even a 2hr race is producing nothing.
 Data is coming only from strava for all.

For those it is nor working you see in pic 3 that we have W' estimate 0 too while the peak estimate is working while for those the estimate from a single ride is working W' is working  too in the trends section (Pic 4)

![Bildschirmfoto 2023-08-21 um 08 50 34](https://github.com/GoldenCheetah/GoldenCheetah/assets/104032799/3cd2bea0-8670-4137-aaf9-5ef13d708a34)
![Bildschirmfoto 2023-08-21 um 08 51 33](https://github.com/GoldenCheetah/GoldenCheetah/assets/104032799/aa6a062a-d345-4ec0-878a-d9b3fb6b70c7)
![Pic 3](https://github.com/GoldenCheetah/GoldenCheetah/assets/104032799/9c8856b2-089b-4316-a822-5a9dda0dea16)
![pic 4](https://github.com/GoldenCheetah/GoldenCheetah/assets/104032799/96d23597-7696-4bf4-b5d0-35dc66636f33)

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
