### ISSUE TITLE
erg workout cannot be written to workout library 0, check permissions and free space

### ISSUE THREAD

**Issue by rommeswi** [GoldenCheetah/GoldenCheetah#4393]
I keep receiving the error "workoutname.erg cannot be written to workout library 0, check permissions and free space".

As far as I can tell, there should be no issue with writing to disk. For example, activities are downloaded from Strava and saved without issue (I tried saving workouts to various folders inside and outside the athlete library on the same disk)

The logs are empty.

Strangely, I can change and save existing workouts. Only creating new files does not work.

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
