### ISSUE TITLE
HR data not imported from garmin gpx file

### ISSUE THREAD

**Issue by slowrider16** [GoldenCheetah/GoldenCheetah#4397]
Version 3.6
HR data from garmin gpx files is not imported, if the data is stored in an gpx extension (garmin does is this way):

```
      <trkpt lat="49.72931946627795696258544921875" lon="11.47801299579441547393798828125">
        <ele>459.79998779296875</ele>
        <time>2023-09-15T16:24:56.000Z</time>
        <extensions>
          <ns3:TrackPointExtension>
            <ns3:hr>143</ns3:hr>
          </ns3:TrackPointExtension>
        </extensions>
      </trkpt>
```

Can the GPX parser be modified to read the hr data?

**Comment by amtriathlon** [comment]
Yes, see:
https://github.com/GoldenCheetah/GoldenCheetah/blob/d98249cf1fd970369ac21be2abee21ca10794228/src/FileIO/GpxParser.cpp#L126C59-L133

**Comment by slowrider16** [comment]
Thank you for the investigation.
I tried to verify this and tried to export an indoor bike training recorded on a Garmin Forunner 255 (connected to direto) as *.gpx
But since there are no gps points, the file is basically empty. So there is no Data at all.
Export as TCX or FIT works fine.
