### ISSUE TITLE
Speed Data missing

### ISSUE THREAD

**Issue by der-St3fan** [GoldenCheetah/GoldenCheetah#4402]
Despite seeing the speed data on Strava, Garmin Connect , i dont see the speed graph in golden cheetah.
For me it stoped showing the data after updating to v3.6 on Sep28.

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
We can open/reopen an issue if there is something we need to fix, which is impossible to know without more details.
Thanks.
