### ISSUE TITLE
Include Athlete CP data in CP graph

### ISSUE THREAD

**Issue by rommeswi** [GoldenCheetah/GoldenCheetah#4404]
Feature Request: I think the CP graph of an activity could be improved by including the athlete's CP model as a curve.

The estimated Morton 3 parameter model is often quite far off if you haven't done maximal sprint efforts in a while.

I tried the options to the graph (which otherwise has really everything I would wish for). The "Show Power Profile" option gives something similar but I'm pretty sure that the blue line is not the Morton 3 parameter model of the athlete data.

I think it would be a very helpful feature for many people because one quickly sees if one's model is not quite right. Perhaps it should even be activated in the graph by default.

**Comment by amtriathlon** [comment]
Please see the wiki for alternatives using existing features and the users forum if you need help or want to discuss about new features.
