### ISSUE TITLE
TrainView - no lap data auto-reset in slope workouts

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#4411]
Reported in https://groups.google.com/g/golden-cheetah-users/c/BQu2pDNei_I/m/rBI2OdUKAwAJ

While doing a crs workout with laps in slope mode the data for:

Lap Time
Lap Power
Lap Cadence
Lap Time
Lap Heart Rate

Are not reset automatically at the beginning of a new lap, only the Lap counter is incremented.
OTOH they work as expected when laps are triggered using workout control panel.
Additionally Lap Distance is wrong until the first lap happens.

**Comment by MarcoAzz** [comment]
Hello
i recently discovered these bugs on my own, searched for and found this issue

(LAP function in CRS Workouts is not resetting Lap Power and Lap Time, instead it correctly resets Lap Distance, and initial wrong Lap Distance until 1st lap)

Did i correctly understood, it will be solved with version 3.7 ?

Thank you anyway :-)
Marco

**Comment by amtriathlon** [comment]
Yes, but the fix is also included in snapshot builds, which at this time are like enhanced v3.6, we have a users forum for questions, BTW,

**Comment by MarcoAzz** [comment]
Thank you so much, and sorry for the wrong place ;-)
