### ISSUE TITLE
Doesn't display left sidebar at startup

### ISSUE THREAD

**Issue by Napator** [GoldenCheetah/GoldenCheetah#4414]
Despite the option is selected in the "view" menu. To display it i need to uncheck the option and then check it again.

Thank you !

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.

**Comment by Napator** [comment]
It is not a question, its an issue, the box is checked in the menu but the left sidebar is not displaying.

**Comment by amtriathlon** [comment]
It is not a general issue but a problem in your system. If, after carefully reading the wiki starting with FAQs, you are still not able to diagnose and fix it by yourself, please ask for help at the users forum.
