### ISSUE TITLE
Swim TSS

### ISSUE THREAD

**Issue by docsport77** [GoldenCheetah/GoldenCheetah#4415]
Swim workouts are leading to extremely high TSS values. 

I tested it data coming from Form goggles and Garmin watches and it is the same for both.

Example workout:

![Bildschirmfoto 2023-11-06 um 13 48 21](https://github.com/GoldenCheetah/GoldenCheetah/assets/104032799/c61123af-9d1e-4f93-b2fb-415fcaee6e18)

Time and distance are correct as it was executed

![Bildschirmfoto 2023-11-06 um 13 49 13](https://github.com/GoldenCheetah/GoldenCheetah/assets/104032799/e9195d97-fd5b-4bdb-8416-f8fe909b3de0)

Zones are set

![Bildschirmfoto 2023-11-06 um 13 50 18](https://github.com/GoldenCheetah/GoldenCheetah/assets/104032799/21e410bc-5997-49da-8dc4-666c572eeae1)

**Comment by docsport77** [comment]
I imported the data to WKO5, my old Race Day Apollo Software on the old Mac, intervals.icu  and Final Surge without any issue to double check and got correct TSS data but I will even if I am not sure what to fix (think there is no need to say that in the Garmin and Form app everything is correct too). Pace data recorded has no problem too and the data is coming from 4 different devices creating all the same problem only in GC. That was why to me it is an technical issue of the software.

**Comment by amtriathlon** [comment]
GoldenCheetah doesn't "massage" imported data without user intervention, but provides the tools to diagnose and fix them, this is by design and it is explained in FAQs.

**Comment by docsport77** [comment]
Thanks Alejandro, technically you are saying that other tools are correcting errors that are happening during the recording of swim data, is that correct?
I fixed one file but it is impossible to do it multiple times a week for all the incoming files, that was why I was asking if I understand it correctly why those weird numbers are always appearing for swimming no matter what device is used or from what athlete they come (as said, swim recordings tend to have some spikes). For others it was not really obviously what was the problem.
TSS of multiple thousand all the time are destroying all analysis so I think I would ask the athletes to exclude swimming then.

Think that is not such a problem regarding the small amount of swimming compared to cycling and running.

Thanks for the help

**Comment by amtriathlon** [comment]
If you have questions, or want to discuss your needs, use the forum like every other user.
