### ISSUE TITLE
Video-link on Wiki not working

### ISSUE THREAD

**Issue by Nikolai1** [GoldenCheetah/GoldenCheetah#4429]
A youtube-link on the [wiki](https://github.com/GoldenCheetah/GoldenCheetah/wiki/Getting-started-with-golden-cheetah-2.0-howto) is not working. Update link or delete wiki-page?

**Comment by amtriathlon** [comment]
It looks like a very old page, I will delete it.

**Comment by Nikolai1** [comment]
Page deleted
