### ISSUE TITLE
ctr-c not working on columns in data -> raw data

### ISSUE THREAD

**Issue by MeisterP** [GoldenCheetah/GoldenCheetah#4430]
Selecting a column and pressing ctr-c used to work to copy the data.

After [commit ea044a0c397d3aaad2dd600a9217568fca389d76](https://github.com/GoldenCheetah/GoldenCheetah/commit/ea044a0c397d3aaad2dd600a9217568fca389d76), the shortcut is broken. Reverting fixes the issue.

I'm running a locally compiled version of Goldencheetah on Linux.

![Screenshot from 2024-01-10 10-33-47](https://github.com/GoldenCheetah/GoldenCheetah/assets/781063/7fc2b1f4-3dbd-46d3-88d5-e80cfbfeb7ed)

**Comment by amtriathlon** [comment]
Agree, alternatives could be to use a different one (Ctrl-N is in use, may be Ctrl-R for refresh) or just remove it.
