### ISSUE TITLE
Drop down arrow not showing in Filter/Search input field

### ISSUE THREAD

**Issue by vischlatter** [GoldenCheetah/GoldenCheetah#4446]
The drop down arrow is not shown completely in the Filter/Search input field:
<img width="229" alt="image" src="https://github.com/GoldenCheetah/GoldenCheetah/assets/7930904/e8a87de7-2783-4576-81dd-fda7fbc9cf5a">

What I tried so far:

- Increase / decrease font size
- Use another screen
- Different window sizes

There is exactly one pixel that I can use to show the drop down. 

My setup:
MacBook Air M1, 2020, 8GB
MacOS: Sonoma 14.2.1

Golden Cheetah version: 
Build date: Aug 5 2023 14:06:41
Build id: 5000
Version: V3.6

Details:
<img width="291" alt="image" src="https://github.com/GoldenCheetah/GoldenCheetah/assets/7930904/2e9eb8d4-014b-42bf-8560-1b731e58c895">

**Comment by amtriathlon** [comment]
There was an attempt to fix this on Windows, but it was reverted since it was broken on Linux and macOS, I would no expect this to be fixed anytime soon, unless Qt6 makes it easier, see https://github.com/GoldenCheetah/GoldenCheetah/commit/fc106615417b35469b97229767aaefcea7aab518

**Comment by paulj49457** [comment]
Please see PR https://github.com/GoldenCheetah/GoldenCheetah/pull/4470 which aims to fix this issue.
