### ISSUE TITLE
OAuth Strava not working - Sign in with Apple ID

### ISSUE THREAD

**Issue by marcelschilling** [GoldenCheetah/GoldenCheetah#4447]
Hey,

Unfortunately, the Strava sync is not working with the option "Sign in with Apple ID" on my Mac.

Here are my specs:
GoldenCheetah 3.6
macOS Sonoma 14.2.1

When clicking on the button, nothing happens (Google, Facebook authentication is working).

Do you have any idea how to fix this issue?

Best,
Marcel

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
