### ISSUE TITLE
GoldenCheetah Linux KDE/Wayland and nVidia Graphics Cards Bug

### ISSUE THREAD

**Issue by Shadmeister** [GoldenCheetah/GoldenCheetah#4454]
Hi,
I have been using Golden Cheetah for a few years - it is a great program. 

I use Fedora 39, and KDE/Wayland has an issue with the Overview, and the Summary tab. Nothing is displayed and there is graphical problems with other tabs too. 

Using :

`QT_QPA_PLATFORM=xcb GoldenCheetah`

Within KDE/Wayland functions ok on my laptop which uses the Intel CPU GPU. On my desktop which has an nVidia GTX1050 card, the issue remains with the Nouveau and nVidia drivers. 

I saw the issue report :

[Port to QT6](https://github.com/GoldenCheetah/GoldenCheetah/issues/3983)

Fedora 40 will not include X11 (Golden Cheetah works no issue in X11/KDE/nVidia GPU), so does the aforementioned issue 3983 resolve the issue of Golden Cheetah with nVidia GPU's and Linux for Wayland and KDE, or is this a bug that will transfer to Fedora 40 KDE/Wayland and QT6 etc ?

Edit : I am using dual monitors on the desktop, not sure if this is an issue. 

Thanks and regards,
Shadmeister.

**Comment by thejockl** [comment]
Hi Shadmeister,

I am using KDE/Plasma (still version 5) and also experienced the invisible tiles on Wayland - this is not an issue any more with the current Qt6-port, at least on my machine running Debian unstable with Qt 6.4.2.
Current master of Golden Cheetah is compatible with both Qt5 and Qt6, so building with Qt6 should show you the progress. I would welcome reports on this!

Regards,
 Joachim
