### ISSUE TITLE
eCP without short intervals

### ISSUE THREAD

**Issue by tomazlaznik** [GoldenCheetah/GoldenCheetah#4457]
Dear!

First, I would like to say, I love GC and it is extremely usable analytical tool. Thanks for your work!!!

My question: Have you consider to make modified eCP based on data that consist of more than x sec. Excluding short intervals.
Why? 
I have noticed, that I have eCP jump based on one extreme sprint where honestly I might have wrong data etc.
I know the formula behind (proxy), however maybe cutting out short interval values, might reflect more appropriate values of eCP for sprinter type of riders. It could be called meCP.

If such function is already available in GC, please let me know.

Be well and thanks again.

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
