### ISSUE TITLE
Add Wahoo Kickr support VIA ANT+

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#446]
Need support for;
- ANT+ (extend existing to incorporate ANT+ trainer profile)

**Comment by maximus321** [comment]
Hey there,
Just wondering if you guys figured out how to send BroadcastMessage to the kickr.

I think I'm almost there, but the Kickr doesn't seem to be responding to my broadcast message
Here is the broadcast message sent.
I'm using the latest official firmware for the kickr 1.2.2
Hopefully we can help each other! 


    uint8_t aucTxBuf[ANT_STANDARD_DATA_PAYLOAD_SIZE];
    KickrAnt::EncodeTrainerSetErgMode(aucTxBuf, kickrDeviceID, load, false);
    pclMessageObject->SendBroadcastData(4, aucTxBuf);

    void KickrAnt::EncodeTrainerSetErgMode(uint8_t* pucBuffer, uint16_t usDeviceId, uint16_t    usWatts, bool bSimSpeed)
    {
        uint8_t ucOffset = 0;

    // frame the ANT message.
    pucBuffer[ucOffset++] = WF_KICKR_COMMAND_PAGE;  //0xF1
    pucBuffer[ucOffset++] = (uint8_t)WF_WCPMCP_OPCODE_TRAINER_SET_ERG_MODE; //0x42
    pucBuffer[ucOffset++] = (uint8_t)usDeviceId;
    pucBuffer[ucOffset++] = (uint8_t)(usDeviceId >> 8);
    pucBuffer[ucOffset++] = (uint8_t)usWatts;
    pucBuffer[ucOffset++] = (uint8_t)(usWatts >> 8);
    pucBuffer[ucOffset++] = (uint8_t)(bSimSpeed ? 1 : 0);
    pucBuffer[ucOffset++] = ANTPLUS_RESERVED;
    }

**Comment by Cadencevr** [comment]
Hi,

 

We also close to the sollution (we think J).

Do you use 2 usb ant+ sticks? One for receiving data and one for sending data.

 

What size is the ANT_STANDARD_DATA_PAYLOAD_SIZE?

 

Best Regards

Klaasjan

 

Van: maximus321 [mailto:notifications@github.com] 
Verzonden: dinsdag 3 maart 2015 21:49
Aan: GoldenCheetah/GoldenCheetah
CC: Cadencevr
Onderwerp: Re: [GoldenCheetah] Add Wahoo Kickr support VIA ANT+ (#446)

 

Hey there,
Just wondering if you guys figured out how to send BroadcastMessage to the kickr.

I think I'm almost there, but the Kickr doesn't seem to be responding to my broadcast message
Here is the broadcast message sent.
I'm using the latest official firmware for the kickr 1.2.2
Hopefully we can help each other! 

uint8_t aucTxBuf[ANT_STANDARD_DATA_PAYLOAD_SIZE];
KickrAnt::EncodeTrainerSetErgMode(aucTxBuf, kickrDeviceID, load, false);
pclMessageObject->SendBroadcastData(4, aucTxBuf);
 
void KickrAnt::EncodeTrainerSetErgMode(uint8_t* pucBuffer, uint16_t usDeviceId, uint16_t    usWatts, bool bSimSpeed)
{
    uint8_t ucOffset = 0;
 
// frame the ANT message.
pucBuffer[ucOffset++] = WF_KICKR_COMMAND_PAGE;  //0xF1
pucBuffer[ucOffset++] = (uint8_t)WF_WCPMCP_OPCODE_TRAINER_SET_ERG_MODE; //0x42
pucBuffer[ucOffset++] = (uint8_t)usDeviceId;
pucBuffer[ucOffset++] = (uint8_t)(usDeviceId >> 8);
pucBuffer[ucOffset++] = (uint8_t)usWatts;
pucBuffer[ucOffset++] = (uint8_t)(usWatts >> 8);
pucBuffer[ucOffset++] = (uint8_t)(bSimSpeed ? 1 : 0);
pucBuffer[ucOffset++] = ANTPLUS_RESERVED;
}

**Comment by maximus321** [comment]
I'm using a single USB2 stick (movestick mini) for my test.
I don't think 2 sticks are needed? 

The channel is opened in bidirectional so it should work like sending a Calibration Message?

      pclMessageObject->AssignChannel(Channel, 0x00, USER_NETWORK_NUM, MESSAGE_TIMEOUT);  //0x00 = Bidirectional Slave Channel = 2way

ANT_STANDARD_DATA_PAYLOAD_SIZE is equals to 8 (default broadcast message length)

Thanks

**Comment by Cadencevr** [comment]
We tried also one usb stick bi-directional, but no respons from the kickr.

 

Somewhere else I wrote that we have to use 2 usb stick 1 receiving and 1 sending. But for us no result unfortunately.

 

Van: maximus321 [mailto:notifications@github.com] 
Verzonden: dinsdag 3 maart 2015 23:04
Aan: GoldenCheetah/GoldenCheetah
CC: Cadencevr
Onderwerp: Re: [GoldenCheetah] Add Wahoo Kickr support VIA ANT+ (#446)

 

I'm using a single USB2 stick (movestick mini) for my test.
I don't think 2 sticks are needed? 

The channel is opened in bidirectional so it should work like sending a Calibration Message?

  pclMessageObject->AssignChannel(Channel, 0x00, USER_NETWORK_NUM, MESSAGE_TIMEOUT);  //0x00 = Bidirectional Slave Channel = 2way

ANT_STANDARD_DATA_PAYLOAD_SIZE is equals to 8 (default broadcast message length)

Thanks

**Comment by liversedge** [comment]
Chip originally shared this when I asked which firmware to use, maybe it will help here:

"I'd stick with the latest 1.3.22.  It's pretty close to final and we didn't remove anything.  I think we are going to remove the dedicated command channel because it is not friendly with ANT sticks in scan mode.  Scan mode can only operate on a single frequency.  Instead we are sending the commands from our command channel implementation on the standard broadcast channel that each KICKR is using.  Rick from NPE the makers of WASP brought an ANT feature to my attention we didn't know about.  Basically you can use a single ANT stick in scan mode and utilize the other 7 channels to send out commands.  It doesn't work well with burst commands, you can only queue for one device at a time with burst.  So we've moved the command channel command decoders onto the regular power channel.  You can queue up commands to go to 7 KICKRs on the other 7 channels if you don't use burst mode. Unfortunately we haven't implemented any demo code to communicate with the KICKRs using this method.  The wasp guys have implemented it and it seems to be working really well.  You should download the ANT_AN14_Continuous_Scanning_Mode document from Dynastream.  It works really well and I think anytime you have an ANT stick without having to worry about battery life it is the ideal way to implement."

**Comment by maximus321** [comment]
I'll try to get some input from Kickr company and post back my results. Using 2 stick is not something I would like and that people will want to use IMO.

From what I understood, just sending a simple broadcast message to the Kickr should work. But like you I do not get any feedback from the Kickr (resistance not changing)

**Comment by maximus321** [comment]
We just switched to CSM so we can have more than 8 devices at the same time.
We can send broadcast and ack message on the other 7 channel and it works really well.
The only sensor that is not replying to our message is the KICKR (FE-C, PowerMeter works).

Were you guys able to successfully send message to the KICKR in CSM?

**Comment by Yanick7** [comment]
Hi,

I have an issue using the Kickr with a speed and cadence sensor. I get speed drop.(sometime speed is 0 and sometimes is displaying the correct value.) I have the firmware 1.3.32 installed. I have try with version 3.0 and 3.3 GC. I have seen this issue in the device wizard and in a workout when both are pair. If I unpair the speed and cadence sensor the speed is accurate in the device wizard and in a workout. 

List of hardware use:
- Garmin ANT+ USB 1 dongle.
- Kickr
- Bluesc (speed and cadence)
- tickr(heart rate monitor)
