### ISSUE TITLE
Qt6: flickering window

### ISSUE THREAD

**Issue by MeisterP** [GoldenCheetah/GoldenCheetah#4465]
The flickering window issue for charts using QtWebEngine was fixed for me in https://github.com/GoldenCheetah/GoldenCheetah/pull/4452

I'm having the same or a very similar flickering issue if a perspective in train view contains a video chart. Goldencheetah is compiled with vlc support.

@thejockl are your able to reproduce this?

**Comment by thejockl** [comment]
Can't reproduce the flicker but get tons of these logging-messages if a vlc video player is present:
```
[12:29:07.883] warning: QOpenGLContext::makeCurrent() called with non-opengl surface 0x55bcf7a42b90 (unknown:0)
[12:29:07.883] warning: QRhiGles2: Failed to make context current. Expect bad things to happen. (unknown:0)
```

WIll try looking into this (Linux / Qt 6.4.2)

**Comment by thejockl** [comment]
When creating a Qt6 QVideoWidget with parent VideoWindow, the exact same warning messages as above are given
