### ISSUE TITLE
Arranging Overview Tiles

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#4467]
This issue has been discussed at the users forum (https://groups.google.com/g/golden-cheetah-users/c/xCMP0q83YNU) and also can be reproduced from default layouts just removing some tiles from upper rows in columns other than the first one and then try to replace them, it is very hard to achieve a similar layout again.

**Comment by amtriathlon** [comment]
We really need to fix this, it is very difficult to change layouts when there are tiles spanning several columns, ideas are welcome.

**Comment by thejockl** [comment]
Hi @amtriathlon , after playing with the code, my impression is that the layouting works just fine, however dragging the tiles is non-intuitive. Therefore I see the culprit here:
https://github.com/GoldenCheetah/GoldenCheetah/blob/412c995a43730dd2992c03c6ca6d52a54fdca66d/src/Gui/ChartSpace.cpp#L1116

Let me continue investigating, I have some prototype code running that prevents quite some tiles from jumping (but needs cleanup before publishing)

**Comment by thejockl** [comment]
My understanding of the layouting:
* Tiles are arranged in multiple columns
* The tiles within each column have a fixed order
* All tiles within one column have the same width
* Columns can have individual widths
* Tiles can have individual heights
* Tiles can span multiple columns
* Placement starts left to right, top to bottom per column
* Tiles are dragged to the next free space above them that has at least their size. The columns tile order is not violated by this
* Tiles spanning multiple columns are arranged in their leftmost column, creating a blocker in the additionally spanned columns. This can create empty spaces within a column, pushing other tiles further down

How I would like to see the dragging of tiles:
* Tiles are dragged to a column, inserted into the columns tile order
* Placing tiles left or right of the existing columns creates a new column (up to a fixed limit)
* As there is no concept of lines, the placement must
  * always respect the users choice of a column
  * never move a tile horizontally without user interaction
* Shift-resizing a tile allows spanning multiple columns

My prototype kind of implements this pattern and feels quite natural

**Comment by liversedge** [comment]
Your pattern is how it is supposed to work!

**Comment by thejockl** [comment]
Started implementing the pattern in #4549, it works on my machine (TM). So looking forward for others to test and try breaking it.
Please be aware that this PR still contains tons of debug-statements.

**Comment by amtriathlon** [comment]
My initial tests were satisfactory, drag-n-drop behavior is more predictable and aligned with what I expect, great!
