### ISSUE TITLE
Extra fields 136, 143 and 144

### ISSUE THREAD

**Issue by pepelisbon** [GoldenCheetah/GoldenCheetah#4480]
Dear GC Developers,

Extra tab undocumented Garmin fields 136, 144 and 143 have been decoded by FitFileViewer as following:

Wrist hr 136
External hr 144
Body battery 143

![imagem](https://github.com/GoldenCheetah/GoldenCheetah/assets/25418720/2bb7d70a-1152-4260-b702-4d306480b576)

Can parsing of these metrics be added to GC ?

**Comment by amtriathlon** [comment]
Can you attach a sample file for testing?

**Comment by pepelisbon** [comment]
> Can you attach a sample file for testing?

Garmin FR 955 v18 firmware file

**Comment by pepelisbon** [comment]
Thank you.
