### ISSUE TITLE
Extra field 140

### ISSUE THREAD

**Issue by pepelisbon** [GoldenCheetah/GoldenCheetah#4481]
Dear GC Developers,

Extra tab undocumented Garmin fields 140 seems to be a GAP speed in m/s *1000

![Capturar](https://github.com/GoldenCheetah/GoldenCheetah/assets/25418720/cc132ddf-6ee3-4db7-80ee-0bcb96767bf0)

Thank you

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/2d8bdd7427890b317d71456af87b648dbf1aab64

**Comment by pepelisbon** [comment]
Thank you
