### ISSUE TITLE
Missing cadence info exporting in CSV

### ISSUE THREAD

**Issue by Shika93** [GoldenCheetah/GoldenCheetah#4485]
I loaded a running training in .fit format from Coros Pace 3 and tried to export it in CSV.
I noticed the cadence column is full of zeros.

![image](https://github.com/GoldenCheetah/GoldenCheetah/assets/32034725/442233b1-a8c4-491a-97ef-e0699d75a202)

while I can see them inside Golden Cheetah

![image](https://github.com/GoldenCheetah/GoldenCheetah/assets/32034725/bd58e953-ff0a-43c8-aafc-c73d9d8011dd)

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
