### ISSUE TITLE
Wrong kilometer

### ISSUE THREAD

**Issue by karlammon** [GoldenCheetah/GoldenCheetah#4486]
Dear community,
i have a problem with the kilometers in my golden cheetah.
I have imported files from Trainingpeaks, were all kilometers was right. After the import all kilometers are complete wrong. Duration and speed is correct. Only the number of km. Maybe you have a solution of this. Thank you!
![Screenshot 2024-05-08 143803](https://github.com/GoldenCheetah/GoldenCheetah/assets/169265331/e25209b8-6713-4525-b02c-e858e5ee6ec2)

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users to ask questions or get help.
Thanks.
