### ISSUE TITLE
Garmin Record Field 87 as Distance Per Stroke for rowing and water paddlesports

### ISSUE THREAD

**Issue by pepelisbon** [GoldenCheetah/GoldenCheetah#4489]
[Downloads.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/15366090/Downloads.zip)
Dear GC Developers,

Garmin Record Field 87 is  CycleLength16  uint16    // Scale: 100; Units: m; Supports larger cycle sizes needed for paddlesports. Max cycle size: 655.35

Please consider adding Field 87 as Distance Per Stroke for rowing and water paddlesports
Thank you.
![imagem](https://github.com/GoldenCheetah/GoldenCheetah/assets/25418720/8325b296-0f5b-4045-95e9-72bb1ea7f8db)

**Comment by amtriathlon** [comment]
Hi, field 87 is not present in the attached file.

**Comment by pepelisbon** [comment]
It's ignored by the FIT parser.
Same indoor rowing fit file with fitfileviewer:
![Capturar1](https://github.com/GoldenCheetah/GoldenCheetah/assets/25418720/a9c5806b-40f2-40b4-baec-4ad75281e2cc)
View with runalyze fitfileviewer:
![imagem](https://github.com/GoldenCheetah/GoldenCheetah/assets/25418720/a0ed806a-24d4-4aa4-9619-bf374e450e39)

**Comment by pepelisbon** [comment]
Thank you.

Damien Grauser ***@***.***> escreveu (quinta, 23/05/2024 à(s)
21:50):
