### ISSUE TITLE
Qt6: colored squares are missing in the legend

### ISSUE THREAD

**Issue by MeisterP** [GoldenCheetah/GoldenCheetah#4495]
With qt6, the colored squares are missing in the legend. This renders the legend useless since you can't say what the labels refer to. I'm running current git master with qt 6.7.0

![Screenshot from 2024-05-21 19-07-21](https://github.com/GoldenCheetah/GoldenCheetah/assets/781063/c34057bd-2681-4b9f-9b82-84c1d8f0779a)

Same chart displays correctly with the appimage using qt5.

**Comment by amtriathlon** [comment]
If you mean on Metric Trends charts I cannot reproduce this, it works as expected for me using Qt 6.6.3

**Comment by amtriathlon** [comment]
![image](https://github.com/GoldenCheetah/GoldenCheetah/assets/1444784/9f02037e-0706-4b7b-baf7-33f52b26c86f)

**Comment by amtriathlon** [comment]
Not anymore after https://github.com/GoldenCheetah/GoldenCheetah/commit/49cf6340a4d2e218a60e5a80ef97ce4cba0f6894

**Comment by thejockl** [comment]
Golden Cheetah makes use of the multi-axes feature that (to my knowledge) is not part of any qwt release yet. Therefore the upgrade in your referenced commit was made to the 6.2-based multi-axes branch https://sourceforge.net/p/qwt/git/ci/qwt-multiaxes/tree/

**Comment by thejockl** [comment]
I will create a PR for upgrading qwt to 6.3 (again from the multi-axes-branch). Would have missed that release without this issue

**Comment by thejockl** [comment]
See the PR https://github.com/GoldenCheetah/GoldenCheetah/pull/4497 for upgrading qwt to 6.3
