### ISSUE TITLE
Wiki Documentation for #4400

### ISSUE THREAD

**Issue by thejockl** [GoldenCheetah/GoldenCheetah#4507]
This issue is meant to deliver the wiki documentation for #4400, with the zipped diff being meant to be applied against the wiki-project (GitHub unfortunately neither supports PRs against wiki nor attaching diff-files to Issues) while the pngs belong to the main-repo.
[4400-wiki.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/15475930/4400-wiki.zip)
![PreferencesTrainingWorkoutTags](https://github.com/GoldenCheetah/GoldenCheetah/assets/20986896/582c2726-f69d-4944-95dd-56aa3223a95a)
![SideBar_Train_Workout_Filter](https://github.com/GoldenCheetah/GoldenCheetah/assets/20986896/cbeefb1c-d32a-42cc-be29-0f69e03bc368)
![SideBar_Train_WorkoutInfo_Collapsed](https://github.com/GoldenCheetah/GoldenCheetah/assets/20986896/0cc42e1f-4656-476b-b003-c5ebfb7c7230)
![SideBar_Train_WorkoutInfo_Expanded](https://github.com/GoldenCheetah/GoldenCheetah/assets/20986896/52c271cc-5958-4080-8267-d02b16773e1a)
![SideBar_Train_WorkoutInfo](https://github.com/GoldenCheetah/GoldenCheetah/assets/20986896/0f03ee33-1311-4a4b-9f32-d5df0b306616)

**Comment by amtriathlon** [comment]
I am not sure I understand this.
The diff seems to reference images in https://github.com/GoldenCheetah/GoldenCheetah/tree/master/doc/wiki, so you could create a normal PR in this repo for them with the right name, which is lost when you attach them to the issue.
The alternative is to use the URI generated by the attachments in the wiki entry, but that doesn't seem to be you intention.

**Comment by thejockl** [comment]
Hi @amtriathlon, see #4510 for the images PR

**Comment by amtriathlon** [comment]
Thank you, Joachim, I merged the PR but I will not be able to apply the diff until the next week since I am traveling this weekend but, since the wiki is open, you could just replace the text using GitHub UI and check the preview tab to see if images are right, the a commit will be generated automatically on save.

**Comment by thejockl** [comment]
Thanks for merging! Don't worry, I will use the GitHub UI. Hope you have a great time!

**Comment by thejockl** [comment]
Updated the wiki:
* https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Side-Bar_Train-view
* https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Preferences_Training
* https://github.com/GoldenCheetah/GoldenCheetah/wiki/UG_Special-Topics_Workouts,-Media-and-VideoSync-Library
