### ISSUE TITLE
Startup crash when there are no Power Zones for the athlete

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#4508]
This has been reported at the users forum and it happens after #4400, which assumes there is always power zones available for Bike and the current date, but this can be not true for pure runners, swimmers, etc.

There are at least 2 places where this can happen:

https://github.com/GoldenCheetah/GoldenCheetah/blob/804a9046d940ce5ad3f9db27f6bca138584f6882/src/Train/TrainSidebar.cpp#L290-L295

https://github.com/GoldenCheetah/GoldenCheetah/blob/804a9046d940ce5ad3f9db27f6bca138584f6882/src/Train/TrainSidebar.cpp#L702-L707

And it should be replaced by something like:

https://github.com/GoldenCheetah/GoldenCheetah/blob/804a9046d940ce5ad3f9db27f6bca138584f6882/src/Train/TrainSidebar.cpp#L92-L96

**Comment by thejockl** [comment]
I will look into this

**Comment by thejockl** [comment]
See #4509 for my proposed fix

**Comment by amtriathlon** [comment]
Fixed by https://github.com/GoldenCheetah/GoldenCheetah/commit/e592645cfb89d76d22af611a7cc627577da73d1b
