### ISSUE TITLE
Golden Cheetah crashing when I try to connect to Trainer

### ISSUE THREAD

**Issue by GanymedFE** [GoldenCheetah/GoldenCheetah#4514]
Hi,

I used Golden Cheetah throughout the winter, and it worked great. However, now that I want to use my bike indoors again, I'm encountering a problem. When I try to connect to the trainer and click the red "Power" button in the bottom left corner, the program crashes and closes.

In the log, I get the message "PC register does not match crashing frame." I have tried updating and reinstalling the program, but it still doesn't work. Do you have any ideas on how to fix this?

Thank you.

**Comment by amtriathlon** [comment]
Please, see troubleshooting in the wiki, and use https://groups.google.com/forum/#!forum/golden-cheetah-users if you need help.
Thanks.
