### ISSUE TITLE
Arch Linux /usr/lib/libtiff.so.6: undefined symbol: jpeg12_write_raw_data, version LIBJPEG_8.0

### ISSUE THREAD

**Issue by calipomza** [GoldenCheetah/GoldenCheetah#4520]
In a Arch Linux system execute 
$ ./GoldenCheetah_v3.7-DEV_x64.AppImage
and show this error
/tmp/.mount_GoldenTqPLAR/GoldenCheetah: symbol lookup error: /usr/lib/libtiff.so.6: undefined symbol: jpeg12_write_raw_data, version LIBJPEG_8.0
then I execute
LD_PRELOAD=/usr/lib/libjpeg.so.8
from Error 2 from https://github.com/GoldenCheetah/GoldenCheetah/wiki/AppImage-starting-issues-on-some-Linux-distributions
and show the same error
Any help

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users for technical support.
Thanks.
