### ISSUE TITLE
Feature Request | Map Tile on Overview Page

### ISSUE THREAD

**Issue by ExtremOPS** [GoldenCheetah/GoldenCheetah#4530]
Hi there,

this is a very cool project and I really like it! I would love to have a little map tile on the Overview page. When I choose to have a Route Overview I get "only" the path and no overlayed information. I would be rather cool to have the map also as tile.

I hope I could express myself in an understandable manner. I am also happy to help if you would point me to the "right" interaction points.

Best,
Christoph

**Comment by amtriathlon** [comment]
Hi, this seems to be part of  https://github.com/GoldenCheetah/GoldenCheetah/issues/3535, please use the forums for feedback and to discuss new features.
