### ISSUE TITLE
Withing connection not working / no updates being pulled (v 3.6)

### ISSUE THREAD

**Issue by cbornBerlin** [GoldenCheetah/GoldenCheetah#4539]
Connection to Withings seems broken. No updates have been pulled since ~4 weeks. Deleted & re-authorized the API connection multiple times but issue persists. Screenshots to show how the authorization flow was completed. 

![Screenshot 2024-09-10 140402](https://github.com/user-attachments/assets/03078601-ec6b-40ad-b14c-c33f590e4d61)
![Screenshot 2024-09-10 140507](https://github.com/user-attachments/assets/07d43b7a-9e1d-4ff2-a870-a7608baddd84)
![Screenshot 2024-09-10 140537](https://github.com/user-attachments/assets/72923abc-6c10-45de-b3d7-54334ddb2a4f)
![Screenshot 2024-09-10 140624](https://github.com/user-attachments/assets/75587ea0-281c-4b53-8046-dafac3115129)

**Comment by amtriathlon** [comment]
Please, use https://groups.google.com/forum/#!forum/golden-cheetah-users for technical support.
Thanks.

**Comment by cbornBerlin** [comment]
@amtriathlon I was pretty sure about this being a possible bug and not a technical question. I technically also didn't ask a question but reported a bug ;-) Can you please confirm that this is not a bug?

**Comment by amtriathlon** [comment]
We use GitHub issues for confirmed/diagnosed bugs, and the users forum to rule out PEBCAKs, thank you for understanding and collaboration.
