### ISSUE TITLE
Creating custom table 

### ISSUE THREAD

**Issue by KDerik** [GoldenCheetah/GoldenCheetah#4548]
i would like to create a table of metric  for daily activites  in V3.6 for new user like this i had in in version 3.5(table i created  in 3.5 exsist also in 3.6 when updated for user i already have.)
![image](https://github.com/user-attachments/assets/cd7b8776-5248-434b-9060-faab2cd32ae3)

In V3.5 was this really easy. But in  V3.6 i dont know how to do it. 

Please help.

**Comment by amtriathlon** [comment]
Please, see [Issues Guidelines](https://github.com/GoldenCheetah/GoldenCheetah/blob/master/ISSUE_TEMPLATE.md).
