### ISSUE TITLE
Intervals in Compare Pane are 1 sample short

### ISSUE THREAD

**Issue by amtriathlon** [GoldenCheetah/GoldenCheetah#4552]
> I have tested the change. I thought it might fix the behavior when a 1-second interval is created under an activity, but in the sidebar view, it shows as a 2-second interval. When the interval is dragged into the Compare Pane, the correct time is displayed. Even with longer intervals, there is a 1-second difference from the Side Bar to the Compare Pane.![Image](https://github.com/user-attachments/assets/c56634f0-f7a1-4be4-84de-035a997100f4)
> 
>  

 _Originally posted by @marcenGC in [b62a2d3](https://github.com/GoldenCheetah/GoldenCheetah/commit/b62a2d31903af8ecd1338ecb01480ccb69ed462a#commitcomment-147826161)_

**Comment by amtriathlon** [comment]
Hi Marcen, that is effectively a 2 sec interval, 1 sec intervals have the same from/to time due to the way Duration metric works.
It looks like the activities created for intervals in compare pane are 1 sample short, so 1 sec intervals will not appear in compare pane and longer one are 1 sec short. I will look to fix that.

**Comment by marcenGC** [comment]
Hi, thank you for the fix and explanation.
