### ISSUE TITLE
Overview - QColorDialog "Cancel" clicked problem

### ISSUE THREAD

**Issue by ZajtiM** [GoldenCheetah/GoldenCheetah#4573]
This image shows "Custom" color window/tab, if you click on square with color.
![Overview_Color_Dialog_1](https://github.com/user-attachments/assets/65a814a3-edce-48f8-b371-fcd8e62d4acf)

This image shows what happens if you click on "Cancel" button when you're in "Custom" tab. If you're in "Standard" tab, it does close color window. But if you're in "Custom" tab, it only hides content of "Custom" tab (closes only QColorDialog).
![Overview_Color_Dialog_2](https://github.com/user-attachments/assets/41afca37-1fb1-45fd-9eec-3fd0af8e5559)

I have GC V3.7-DEV (AppImage), build date: 26. Oct. 2024 in Linux Mint.
I could submit a commit/PR request. But i think it would take me longer, than if any of you (who are accepting PR's) would change the code.
I didn't work with github for a long time. So, i would need to read / figure out everything (regarding commits / PR's).

All it needs to be done is to add one new line.
**/src/Gui/ColorButton.cpp - Line: 172-175 [most logical location]**
`connect(colordialog, SIGNAL(rejected()), this, SLOT(cancelClicked()));`
OR 
`connect(colordialog, &QDialog::rejected, this, &GColorDialog::cancelClicked);`

**Comment by amtriathlon** [comment]
Thank you, I will review and apply this the next week.
