### ISSUE TITLE
I can't connect strava

### ISSUE THREAD

**Issue by belinea1966** [GoldenCheetah/GoldenCheetah#4586]
Good morning, I have been using GoldenCheetah for three years, for my team of 12 guys, it has always worked, now I am trying to insert the new arrivals, but when I go to

"add account for cloud - activities - strava"
I click on the strava banner, I insert the credentials, the response is always

An unexpected error occurred. Try again.

The credentials entered directly on the strava site work.

I tried with versions, 3.5, 3.6 and also 3.7

N.B. the athletes already registered at the beginning of 2024 download without problems

Can you help me understand what is happening
Thanks

If you need help, technical support or want to ask questions or give feedback, please use users/developers forums:
- Users - https://groups.google.com/forum/#!forum/golden-cheetah-users
- Developers - https://groups.google.com/forum/#!forum/golden-cheetah-developers

Issue tracker is **only** for  previously discussed Bugs and Features, others will be closed without discussion.

**Comment by belinea1966** [comment]
sorry, did I do something wrong that you closed my request?Inviato dal mio Galaxy
-------- Messaggio originale --------Da: Alejandro Martinez ***@***.***> Data: 30/12/24  12:49  (GMT+01:00) A: GoldenCheetah/GoldenCheetah ***@***.***> Cc: belinea1966 ***@***.***>, Author ***@***.***> Oggetto: Re: [GoldenCheetah/GoldenCheetah] I can't connect strava (Issue
  #4586) 
Closed #4586 as completed.

**Comment by tilmanbeck** [comment]
Hi there,
newcomer here - really looking forward to using the app!
However, I have a similar issue as @belinea1966 . I installed the MacOS app (3.6 Current Stable Release) on Macbook Apple M1 Pro with Sequoia 15.2.
When clicking the Strava button the separate OAuth window is opened. I enter my email but the "Log in" button is never enabled to be clickable so I cannot proceed to enter my pw.

Any suggestions?

Best Regards,
Tilman

**Comment by amtriathlon** [comment]
We don’t use GitHub issues for technical support, that’s the reason this issue was closed without discussion, please use the users forum.

**Comment by amtriathlon** [comment]
> If you need help, technical support or want to ask questions or give feedback, please use users/developers forums:
> 
> * Users - https://groups.google.com/forum/#!forum/golden-cheetah-users
> * Developers - https://groups.google.com/forum/#!forum/golden-cheetah-developers
> 
> Issue tracker is **only** for previously discussed Bugs and Features, others will be closed without discussion.

The above text is not clear enough?

**Comment by tilmanbeck** [comment]
Thanks for the feedback.
I think 1) it is obviously a bug but not labeled as such and 2) was previously discussed as shown by @belinea1966 . But anyway, I will use the other forum.

**Comment by amtriathlon** [comment]
It is not, and there is already an ongoing discussion at the users forum: https://groups.google.com/g/golden-cheetah-users/c/jt8GcS742r8
