### ISSUE TITLE
Add Support for the O-Sync ANT+Remote

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#478]
They've sent me one, so need to add support!

**Comment by dresco** [comment]
I'm having a bit of a poke at this one. The main hurdle is that the controllable device (ie GC) is the master, so quite different to everything else in the existing ANT code (sigh)..

**Comment by liversedge** [comment]
I never got protocol docs either so not sure how it works!

**Comment by dresco** [comment]
The 'Controls' device profile doc looks pretty thorough. I've not got an O-sync, but can transmit from SimulANT+ or my ANT enabled Android phone for now. (Was thinking it might make a neat little Android app in due course).

**Comment by dresco** [comment]
I've got something working now, will clean it up a bit later and push to GitHub for review..

**Comment by liversedge** [comment]
damn and I can't find the one they sent me !

**Comment by dresco** [comment]
Initial code for review https://github.com/dresco/GoldenCheetah/tree/remote_control
