### ISSUE TITLE
Add BTLE support

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#479]
Already working on it in the code, but need to record the feature here, so we can track progress and add to the release notes when done.

Initially this will be just for Mac via the WF API.

Linux/Windows BTLE support is a whole new ball of wax.

**Comment by viiru-** [comment]
I have written most of the glue code to allow Goldencheetah to use BTLE sensors through the Qt builtin BTLE support. Proper integration with the add device wizard is still missing.

Currently I have this built as a new and completely separate controller. I later noticed that the current wfapi-based bt40controller is actually disabled, and incomplete. Are there still plans to finish that work, or would it be preferrable to you if I structured the Qt BTLE based version as a replacement for that one?

**Comment by liversedge** [comment]
Hi,

The Wahoo API should be removed from the code completely. We will never support it directly since it violates the GPL.

Please feel free to add support -- I can help, and also have a BT dongle and BT devices to test as well.

**Comment by liversedge** [comment]
If you are willing to pursue this we can add it to the v4 queue -- do let me know.

**Comment by viiru-** [comment]
Ok, I'll start working on a clean branch that replaces the bt40controller with the new stuff. I'm willing to pursue this, but I can't guarantee much about the timetable. I'll get back to you with a branch when I have one.

**Comment by liversedge** [comment]
ACE! Will put it into v4 queue.

CHEERS
Mark

**Comment by liversedge** [comment]
Fixed in https://github.com/GoldenCheetah/GoldenCheetah/pull/1936
