### ISSUE TITLE
Powertap Cadence in Train mode

### ISSUE THREAD

**Issue by paultyrrell** [GoldenCheetah/GoldenCheetah#502]
Hi,

Using GC version 3 build 02-25-2013

I have a Powertap hub.  I use a separate crank cadence sensor because the cadence data sent by the hub is highly inaccurate.  When setting up the Native Ant+ device it will pair up my cadence sensor, but GC it recording the cadence data from both the hub and the crank cadence sensor.

![pairing ant ](https://f.cloud.github.com/assets/3787924/227855/5b7945f8-866e-11e2-93cf-f9f3f8501edd.jpg)

In testing I found that if I don't pair up the power and I do pair up the crank cadence sensor,  GC displays the correct crank cadence data whether pedaling forward or backward.

When the hub is paired up for power and the crank cadence sensor is not paired, the cadence displayed (inaccurately, because the hub can't accurately extrapolate the cadence from the changes in force) while pedaling forward is from the hub. Pedal backward & cadence reads zero.

When both hub and crank cadence sensor are paired, both data are being displayed alternately in the cadence display.  The proof being that when you pedal backward the display alternates every other second (the refresh frequency of the display appears to be once per second) between 0, from the hub, and the correct cadence from the crank sensor (it matches the display on bike computer which is paired with the crank cadence sensor).

The graph below shows the bad data that the hub sends. Very annoying.  On the Powertap bike computer you can choose to use just the crank sensor data.

![last60sec](https://f.cloud.github.com/assets/3787924/228122/94227f5c-8676-11e2-9fd0-43548d8220e4.jpg)

It would be totally awesome if we could choose the cadence source!  Is there a plain text config. file that can be edited in the meantime to provide a workaround?

I love Golden Cheetah and have just recently purchased a used Ant+ USB stick so I can use the Training mode.  Thanks everyone for all the work on this project

Thanks, Paul Tyrrell

**Comment by liversedge** [comment]
shifting to 3.2 as we close out 3.11

**Comment by liversedge** [comment]
moving back to 3.11 as damien is looking at it !
