### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#515]
Want to be able to plan seasons, cycles and events. periodization concepts like base, peak, taper etc, training load, intensity/frequency etc, training mix, workouts etc:
- set goals and events
- plan load over seasons, cycles, weeks
- develop and plan workouts
- track compliance to plan
- track outcomes
- track training effect

**Comment by liversedge** [comment]
need to also consider how we want to handle workout quality i.e. staying true to the plan.
going to hard on easy vs going to easy on hard .. training black hole !

**Comment by liversedge** [comment]
Some comments from Alex Simmons on the GC list a while back when we discussed planning..

I have already built such a system for coaches to build custom 
training plans, design custom training descriptions, produce a sale 
able product, amongst all sorts of things - and would hope that it 
could become software widely available at some stage.  I have been 
using it for nearly 2 years and it works great.  A very efficient 
means to generate good quality plans. 

But offering it for nothing would damage a reasonably significant 
income stream for me, since coaching is my only income. 

Of course I'm sure the clever people here could make something similar 
and my tool would probably go the way of the dinosaur, but in reality 
probably not because it's the coach making decisions on what goes into 
the plan based on client assessment that is a critical element, and 
that requires experience.  Sure you could build a business rules based 
auto plan generator but I think the coach's touch can't be overlooked. 

The plans work (based on the client reported results), the clients 
love them and keep coming back for more, and I can't manage the demand 
(and do no marketing either). 

This is the dilemma of a self employed full time professional coach - 
while I do it for passion and my client's performance, it's also a 
business and pays my mortgage. 

My plans are described here: 
http://www.cyclecoach.com/index.php?option=com_content&view=article&id=89&Itemid=100 

we also provide for a user forum to interact with coaches when they 
have questions etc.  this is not, of course what I do with my higher 
level coaching clients who get a greater level of attention and focus.

**Comment by liversedge** [comment]
**And further from Julian**

've mentioned this once before and there seemed to be some interest 
but as it was the springtime most of us were too engrosed in actually 
riding our bikes to take up a new feature in GC...  In any event as 
the season has wrapped up for most of us and the long hours of the 
winter approach I thought I'd raise the idea again and see if anyone 
is game... 

For a few years I've been using an Excel workbook that allows me to 
build a training program  (I will share it with those who are 
interested).  Simple enough really but I've found it tremendously 
helpful (along with my teammates, many of whom stopped paying for 
coaching after seeing this) in planning backwards from races and 
peaks.  The basic idea is that for each workout I enter the specifics 
in time and IF (breaking workouts down into intervals etc...) and the 
spreadsheet computes the relevant metrics.  These metrics are then 
used on a performance manager style chart, a ramp rate chart, and a 
rolling TSS values chart.  Essentially what the workbook allows me to 
do is to plot out all of my workouts while seeing what the results 
will be all the while keeping track of my ramp rate and accumulating 
TSS so I don't blow up!  So I can plot out a month of training, say 
threshold, and look at the Performance Manager Chart and see where 
that month of training will leave me with respect to ATL, CTL and 
TSB... 

Of course it's not perfect and does take some massaging but it allows 
me to see what will happen if I would complete all the workouts to a 
T.  Further, when I plot my actual PMC against the Predicted PMC it 
shows me if I'm straying from my plan.  As is often the case I skip a 
few workouts or add a few but never knew what the effect on my 
trajectory was... now I know, and better yet, I can then take 
corrective action so to not miss my mark. 

When I first raised the idea I found Keisuke's patch that allows one 
to create stepped workouts and transfer them to the Edge 500 and 705. 
Essentially Keisuke has built the first part of my idea- a feature 
that allows a user to create a bank of stepped workouts.  Keisuke's 
patch didn't contain the ability to calculate metrics from the workout 
but I assume (perhaps naively?) that's fairly easy to add for some of 
you coding ninjas.  From there I can't see how the next step would be 
very hard as it seems it would be as simple as creating a mirror of 
the calendar to store all the projected training data and then using 
those values on the metrics tab...?  Further it would be great to be 
able to transfer those workouts from the calendar to a device... 

My belief is that this is the next logical step in training software- 
software that aides one in not just taking an analytic role in their 
training but a proactive role in creating the training.  Again I'm not 
going to be much use in coding  but I can help out in other ways and 
I'm not adverse to making some financial contribution to seeing this 
get off the ground. 

If anyone is interested by all means contact me as I truly believe 
this will be hugely beneficial to coaches, users and those people who 
are just learning how to balance all the factors that go into creating 
a training plan...  GC is without a doubt the most advanced and 
promising power analysis software around and I feel this feature would 
simply blow people away. 

**And then later**

FWIW, it took me 3 years of paying for coaching and devouring all the 
books and online resources until I felt comfortable enough on my own. 
While I went this way I know of more people who have a surplus of 
money over time and desire to coach themselves.  For those people this 
feature is irrelevant. 

For those of us who do want a very hand-on approach to our training, 
those of us who no longer pay for coaching this tool will be 
invaluable. 


-- 

Mark pretty much cracked open my small head and scooped the good stuff 
out... I totally agree with everything.  #10 may be a longer term 
project though... 

I've uploaded my workbook to dropbox... I'm still building my personal 
plan so the workbook is full of my own junk (and HIGHLY incomplete) 
but it will provide a reference for how it works... I don't recommend 
anyone follow my plan as it has me peaking in early June as that's 
when my season will end as I'll be on a month-long honeymoon come 
July... 

http://dl.dropbox.com/u/6564666/Training4.xls 

I wouldn't be surprised to find that there are errors in the 
spreadsheet, it's big and complicated etc...  That's my disclaimer... 

So yeah, that's about it.  I have plenty of ideas on how to implement 
this feature and how to make it simple (I'm a web dev/artist so I do a 
lot of UI stuff) but as for the coding I'm not much help.  That 
said... I really want to see this happen so I'm open to helping in 
other ways...

**Comment by liversedge** [comment]
One way of visualising over a longer period......
![visualisation](https://cloud.githubusercontent.com/assets/142876/9023598/83cee7a2-389a-11e5-9a74-e8ab57b94d6c.png)

**Comment by liversedge** [comment]
Obvs need to show training blocks across season for periodisation or whatever strategy folks want to adopt. Need to consider how to move from season > block > week > day > workout and if its something that applies to general navigation not just planning.............

**Comment by rkantos** [comment]
These features would also be what I'm hoping for! One could also mimic the rather simple Trainingpeaks yearly-Annual Training Plan creator, which just creates a timetable of number of hours per week in 3-week tapers based on set goal events.

(It does have some 'hidden' features, like the tooltips or recommendations based on Coggan & co)
https://www.trainingpeaks.com/blog/a-look-at-planning-by-tss-with-the-new-atp/


![ATP](https://home.trainingpeaks.com/TrainingPeaks/media/Images/Resource%20Articles/Creative%20Finished/05112-ATP.jpg)
![ATP](https://wpassets.trainingpeaks.com/wp-content/uploads/2017/01/new-atp-1.jpg)
![ATP](https://wpassets.trainingpeaks.com/wp-content/uploads/2017/01/new-atp-7.jpg)

**Comment by liversedge** [comment]
this is a duplicate of #2084.
