### ISSUE TITLE
Specify a preferred source for redundant signals in train mode

### ISSUE THREAD

**Issue by dresco** [GoldenCheetah/GoldenCheetah#526]
Multiple sources of the same signals (for instance when paired with both a powermeter and a speed/cadence sensor) can be a cause of unexpected values. 

This feature request is to allow the user to specify which paired device should be the source for specific signals. For instance, choosing to use cadence data from a speed/cadence sensor instead of the (estimated) cadence from a PowerTap, or choosing to use the cadence data from a crank based power meter instead of a speed/cadence sensor.

See this thread in the mailing list for more background - https://groups.google.com/forum/?fromgroups=#!topic/golden-cheetah-users/qxHaN99u9ic

**Comment by amtriathlon** [comment]
> Completing #974 would solve this as well.

In fact that would’ve the proper way to solve this, and since #974 will not be implemented as explained in https://github.com/GoldenCheetah/GoldenCheetah/issues/974#issuecomment-581028446, let’s close this too.
