### ISSUE TITLE
Support for keyboard shortcuts to switch between tabs

### ISSUE THREAD

**Issue by cernst72** [GoldenCheetah/GoldenCheetah#535]
It would be nice, if we could use Strg+1 .. Strg+9 to toggle between tabs like in Firefox.
Additionally I would propose to define Strg+Left and Strg+Right to scroll between tabs. Maybe with Strg+Up and Strg+Down one could scroll between Home..Training.

**Comment by liversedge** [comment]
is covered by issue #1388
