### ISSUE TITLE
Add support for upload/download to Garmin Connect

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#587]
From a recent discussion on the mailing list:

I would like to see the ability for the ride that has been uploaded via GarminConnect on my iPhone from my 810 at the end of my ride, be able to be sync'ed to GoldenCheetah via a sync method.

I would then not need to export the TCX from Garmin and import to GoldenCheetah.

Another set of code that may be useful is someone posted a web application that allow the download of all the activities from Garmin connect.

http://www.sideburn.org/garmin/

I would think the raw export code could be used in GoldenCheetah to offer a more integrated download method.

Here are some other links that may have usable code.

http://blog.jacobsonhome.com/2012/02/garcon.html

https://gist.github.com/tmcw/1098861

**Comment by liversedge** [comment]
I know that GC can sync from TrainingPeaks, but unfortunately the files come through with none of the 'new' training metrics - Ground Contact Time and Cadence for running, L/R balance for cycling, cadence for swimming. There may be more. I also tried linking the Tapiriik with my dropbox, but ran into the same problem. So I found myself either manually downloading .FIT files from connect, or creating Hazel rules to automatically copy the .fit files from my device when I plug them in to charge. Both felt a bit hacky, and I'm sure that other GC users are running into the same problem.

Then I stumbled upon Peter Gardfjall's excellent script on GitHub - https://github.com/petergardfjall/garminexport. It is brilliant because you can specify the format of the file that you want (.fit, .tcx, etc) and it will sync to a folder. I have my server run a cronjob every 30 minutes or so to check for new files, and the sync the new files only with BTSYNC to the GC auto-add folder. It feels MUCH neater and now I don't need to worry if my 920XT uploads over WiFi, or if my 520 automagically uploads after a ride while connected to bluetooth

**Comment by ROnderstal** [comment]
It has been a while any updates since then or Garmin still asking a lot for a partner program?

**Comment by liversedge** [comment]
I haven't asked, the webpage hasn't changed. :(

**Comment by teebee76** [comment]
How about a fundraiser for the one-time license fee at Garmin?  if it is currently 5000$ I bet it would be covered rather quickly if word got around to all the Garmin users that they would get a seamless integration with Garmin Connect.

**Comment by liversedge** [comment]
Its not just the garmin connect fee -- it pushes data to a web server -- we would need to create and maintain that too. So the only sensible way to do this is via a paid for service. 

Since there are many paid for services already, we don't need to replicate that -- instead we sync with those instead.

For a free way of doing this just link your garmin connect account to Strava and use 3.5 to sync with Strava (aka Strava as a proxy to Garmin Connect).

**Comment by kevindoveton** [comment]
from https://developer.garmin.com/gc-developer-program/activity-api/
> Access to the Garmin Connect Developer Program is free to approved business developers.

> Ping/Pull or Push Architecture: Choose the integration option that best matches your needs

  

Given that API access is now free to approved businesses and supports a pull architecture, is this something that could be reconsidered?
