### ISSUE TITLE
FR - Allow Default Value To Be Set in Data Fields

### ISSUE THREAD

**Issue by doyler78** [GoldenCheetah/GoldenCheetah#659]
It would be great to be able to select one of my list of data field values as a default so that it is automatically applied to all new rides that are downloaded. This would mean that I would only have to bother with this when I deviate from the norm. Example of this is that I have all my bikes listed so I track my bike usage. Typically I tend to favour one bike at certain times of the year therefore it would save a bit of hassle in doing that. I also like to analyse what type of ride it was ie turbo v road cycling or for others xc etc and usually at certain times of years one takes precedence over the others so great to just set a default to be picked up.

**Comment by amtriathlon** [comment]
Linked defaults support this functionality on v4.0, see https://github.com/GoldenCheetah/GoldenCheetah/commit/cc02714983e34d5a8418c361e1774f15fc00b914
