### ISSUE TITLE
Train View Popover Controls

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#668]
The current hack to put the controls into the scope bar is a bit crappy -- they're small and no keyboard support makes it real hard when on the trainer.

We should have a popover 'transparent' control with big buttons and allow the user to use the keyboard too.

**Comment by vlcvboyer** [comment]
How about using garmin ANT+ remote?
(I don't have one but this may be useful for those who own one)

**Comment by liversedge** [comment]
This is now done by placing in the "compare" pane area.
ANT+ remote support is also done.

So closing this for the v4.0 queue.
