### ISSUE TITLE
Speed wrong in Train view

### ISSUE THREAD

**Issue by gcoco** [GoldenCheetah/GoldenCheetah#669]
When selecting a Wheelsize that is not Road/Cross(700C) the speed displayed in the Train view is incorrect (slow by nearly 50%)

**Comment by erik-sk** [comment]
I am experiencing the opposite of this. I have entered a 26in wheel size and the speed is double compared to apps on my phone.  The cadence matches. My sensor is a Topeak Duoband and I am using the June 2020 build of version 3.6

**Comment by amtriathlon** [comment]
Does this happen connecting the sensor via ANT+, BTLE or both?

**Comment by erik-sk** [comment]
Right now it is on BTLE. I have ordered an ANT+ USB that should be here in a few days. Will be interested to see what happens with that.

**Comment by amtriathlon** [comment]
There was a change related to this on June/2020 build, it is not present in previous on previous releases: https://github.com/GoldenCheetah/GoldenCheetah/pull/3456

**Comment by erik-sk** [comment]
Okay. I am running that build. Will keep an eye on it and see what happens. I will also try reloading the stable build and see what is going on with that.
