### ISSUE TITLE
Merge Intervals

### ISSUE THREAD

**Issue by P-Brews** [GoldenCheetah/GoldenCheetah#670]
I would find it useful to be able to merge a number of time contiguous intervals into a single interval. 

For example - I do a 20min 'criss-cross' interval, 2min at one level, 1min at another, repeated for 20min. Afterwards, I would like to create a single interval from the 13 intervals that are downloaded from my Garmin.

**Comment by amtriathlon** [comment]
I am closing this since it will not be implemented, it easy to create a new interval for that as Mark remarked above.
