### ISSUE TITLE
crash when importing powertap csv

### ISSUE THREAD

**Issue by dsh79** [GoldenCheetah/GoldenCheetah#672]
applies to build id 3010 (June 7th) 

when importing a powertap csv file, GC will crash with an "assertion failed" message if the date of the workout is selected manually in the dialog. The import works fine if the date of the workout is set to "today" via the dropdown menu.
I've been able to reproduce the error with powertap csvs from various sources (including some I auto generated with a program I wrote and which are correctly formatted). Deleting the database does not get rid of the error.

Cyclist: "dh"

Version Info

Build date: Jun 7 2013 14:56:55
Build id: 3010
Version: 3.0
DB Schema: 48
OS: Win
QT	4.8.4
QWT	6.0.1
GCC	4.8.0
SRMIO	yes
OAUTH	1.0.1
D2XX	yes
QWTPLOT3D	0.2.6
KML	none
ICAL	0.44
USBXPRESS	yes
LIBUSB	yes
Wahoo API	none
VLC	yes
LUCENE	2.3.3.4

Metric Log

METRIC REFRESH STARTS: Sa 3. Aug 09:09:20 2013
COMMIT: Sa 3. Aug 09:09:20 2013
SIGNAL DATA CHANGED: Sa 3. Aug 09:09:21 2013
METRIC REFRESH ENDS: Sa 3. Aug 09:09:21 2013
Athlete Directory

.	Sa 3. Aug 09:12:18 2013
..	So 16. Jun 16:23:00 2013
index	Sa 3. Aug 09:09:20 2013
metric.log	Sa 3. Aug 09:09:21 2013
metricDBv3	Sa 3. Aug 09:09:21 2013
-4713_01_01_00_00_00.csv	Sa 3. Aug 09:08:22 2013
2013_08_03_09_04_46.csv.bak	Sa 3. Aug 08:56:38 2013
analysis-layout.xml	Sa 3. Aug 08:37:48 2013
diary-layout.xml	Sa 3. Aug 08:37:48 2013
namedsearches.xml	Sa 3. Aug 08:37:48 2013
home-layout.xml	Sa 3. Aug 03:20:22 2013
2013_08_03_01_36_58.csv.bak	Sa 3. Aug 03:06:41 2013
2013_07_31_08_47_19.csv.bak	Mi 31. Jul 00:39:13 2013
2013_07_23_14_31_36.json.bak	Fr 26. Jul 18:33:47 2013
2013_07_24_14_27_29.json.bak	Fr 26. Jul 18:33:35 2013
2013_07_24_14_29_47.json.bak	Fr 26. Jul 18:33:19 2013
2013_07_25_14_23_42.json.bak	Fr 26. Jul 18:27:25 2013
avatar.png	Fr 26. Jul 18:26:48 2013
hr.zones	Fr 26. Jul 18:26:48 2013
metadata.xml	Fr 26. Jul 18:26:48 2013
power.zones	Fr 26. Jul 18:26:48 2013
2013_06_15_12_35_20.json.bak	Fr 21. Jun 16:36:01 2013
2013_06_19_09_33_24.json.bak	Fr 21. Jun 16:34:36 2013
2013_06_21_09_26_07.json.bak	Fr 21. Jun 16:33:17 2013
2013_06_17_09_46_36.json.bak	Mo 17. Jun 13:48:49 2013
2013_06_17_09_32_27.json.bak	Mo 17. Jun 13:33:37 2013
2013_06_17_09_29_54.json.bak	Mo 17. Jun 13:31:08 2013
2013_06_16_12_47_10.json.bak	So 16. Jun 16:47:56 2013
2013_06_16_12_38_21.json.bak	So 16. Jun 16:38:28 2013
2013_06_16_12_37_35.json.bak	So 16. Jun 16:37:38 2013
All Settings

CALTPOWER	255:0:255
CBALANCELEFT	178:0:0
CBALANCERIGHT	128:0:50
CCALACTUAL	0:255:0
CCALCELL	255:255:255
CCALCURRENT	51:153:255
CCALHEAD	230:230:230
CCALPLANNED	255:255:0
CCALTODAY	0:255:255
CDIAL	160:160:164
COLORAEROEL	0:255:0
COLORAEROVE	0:0:255
COLORALTITUDESHADE	124:91:31
COLORALTITUTDE	124:91:31
COLORBIKESCORE	160:160:164
COLORCADENCE	0:204:204
COLORCALENDARTEXT	0:0:0
COLORCP	255:0:0
COLORDAILYSTRESS	255:0:0
COLORGRID	0:0:0
COLORHEARTRATE	0:0:255
COLORINTERVALHIGHLIGHTER	0:0:255
COLORLOAD	255:255:0
COLORLTS	0:255:0
COLORPLOTBACKGROUND	255:255:255
COLORPLOTMARKER	160:160:164
COLORPLOTSELECT	0:0:255
COLORPLOTTHUMBNAIL	160:160:164
COLORPLOTTITLE	0:0:0
COLORPLOTTRACKER	0:0:255
COLORPOWER	255:0:0
COLORRIDEPLOTBACKGROUND	0:0:0
COLORRIDEPLOTSYMBOLS	160:160:164
COLORRIDEPLOTXAXIS	0:0:255
COLORRIDEPLOTYAXIS	255:0:0
COLORSB	0:0:0
COLORSPEED	0:255:0
COLORSTS	0:0:255
COLORTEMPERATURE	255:255:0
COLORTORQUE	255:0:255
COLORTSS	0:255:0
COLORWINDSPEED	0:128:0
COLORZONE1	255:0:255
COLORZONE10	160:160:164
COLORZONE2	42:0:255
COLORZONE3	0:170:255
COLORZONE4	0:255:128
COLORZONE5	85:255:0
COLORZONE6	255:213:0
COLORZONE7	255:0:0
COLORZONE8	160:160:164
COLORZONE9	160:160:164
CPOPUP	192:192:192
CPOPUPTEXT	255:255:255
CRIDEGROUP	236:246:255
CSPINSCANLEFT	160:160:164
CSPINSCANRIGHT	0:255:255
CTILEBAR	160:160:164
CTILEBARSELECT	255:255:0
CTOOLBAR	240:240:240
HRCOLORZONE1	255:0:255
HRCOLORZONE10	160:160:164
HRCOLORZONE2	42:0:255
HRCOLORZONE3	0:170:255
HRCOLORZONE4	0:255:128
HRCOLORZONE5	85:255:0
HRCOLORZONE6	255:213:0
HRCOLORZONE7	255:0:0
HRCOLORZONE8	160:160:164
HRCOLORZONE9	160:160:164
LTS	LTS
LTSname	Long Term Stress
SB	SB
SBname	Stress Balance
STS	STS
STSname	Short Term Stress
antialias	false
bikeScoreDays	30
bikeScoreMode	time
crankLength	172.5
dataprocess/fixgaps/stop	1
dataprocess/fixgaps/tolerance	1
dataprocess/fixhrspikes/max	220
dataprocess/fixspikes/max	1500
dataprocess/fixspikes/variance	1000
dataprocess/torqueadjust/adjustment	0 nm
devices	0
dh/LTSdays	42
dh/PMshowSBtoday	0
dh/STSdays	7
dh/bavigator/headingwidths	0|80|50|50|
dh/blank/analysis	false
dh/blank/diary	false
dh/blank/home	false
dh/blank/train	false
dh/dv/url	
dh/gc/url	http://race.goldencheetah.org
dh/ltmwindow/lastDateRange	{00000000-0000-0000-0000-000000000001}
dh/navigator/groupby	-1
dh/navigator/headings	*|Workout Code|TSS|Datum|
dh/navigator/sortby	2
dh/navigator/sortbyorder	0
dh/nickname	0
dh/safeexit	false
dh/splitter/LTM/hide	true
dh/splitter/LTM/hide/0	false
dh/splitter/LTM/hide/1	false
dh/splitter/LTM/hide/2	false
dh/splitter/LTM/hide/3	true
dh/splitter/analysis/hide	true
dh/splitter/analysis/hide/0	false
dh/splitter/analysis/hide/1	true
dh/splitter/analysis/hide/2	false
dh/splitter/analysis/hide/3	true
dh/splitter/diary/hide	true
dh/splitter/diary/hide/0	false
dh/splitter/diary/hide/1	false
dh/splitter/diary/hide/2	true
dh/splitter/train/hide	true
dh/splitter/train/hide/0	false
dh/splitter/train/hide/1	false
dh/splitter/train/hide/2	false
dh/splitter/train/hide/3	false
dh/tp/type	0
dh/tp/url	http://www.trainingpeaks.com
dh/tw/url	http://www.twitter.com
dh/unit	Metric
dh/versionused	3010
dh/webcal_url	
dh/wi/url	http://wbsapi.withings.net/
dh/zeo/url	http://app-pro.myzeo.com:8080/
dp/Drehmomentwerte abgleichen/apply	Manual
dp/GPS Fehler beheben/apply	Manual
dp/HF-Ausreißer beheben/apply	Manual
dp/Leistungsausreißer beheben/apply	Manual
dp/Lücken in Aufzeichung beheben/apply	Manual
elevationHysteresis	3.
font/calendar	MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0
font/calendarsize	10
font/chartlabels	MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0
font/chartlabelssize	10
font/chartmarkers	MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0
font/chartmarkerssize	10
font/default	MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0
font/defaultsize	8
font/popup	10
font/titles	MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0
font/titlessize	10
garminHWMark	25
garminSmartRecord	2
lang	de
linewidth	2
mainwindow/geometry	
mainwindow/lastDownloadDevice	O-Synce Macro PC-Link
mainwindow/lastDownloadPort	Serial: COM5
mainwindow/lastImportPath	C:/Users/real-owl/Documents/NetBeansProjects/PowertapGenerat
mainwindow/lastOpened	dh
rideSummaryWindow/summaryMetrics	skiba_xpower,skiba_relative_intensity,skiba_bike_score,danie
shadezones	true
train/multi	false
wheelsize	2100
workoutDir	0

**Comment by liversedge** [comment]
no file provided
