### ISSUE TITLE
Streetview in train mode crashes after memory leak

### ISSUE THREAD

**Issue by marcber** [GoldenCheetah/GoldenCheetah#697]
It looks like the streetview images aren't getting freed as they are downloaded and displayed. You can see the memory usage grow steadily when the streetview window is active, in train mode, when playing a past activity. The second time I tried, as soon as I closed that streetview window, the memory dropped back to normal.

**Comment by liversedge** [comment]
Moved to 3.2 as we may be able to resolve this when we move to the new QT web engine.

**Comment by amtriathlon** [comment]
StreetView was removed by https://github.com/GoldenCheetah/GoldenCheetah/commit/99d90dea3255823e1e4acb3f41926b9eccd41e7e
