### ISSUE TITLE
Training view: Workout wizard, add capability to define sets and repetitions

### ISSUE THREAD

**Issue by stigbd** [GoldenCheetah/GoldenCheetah#701]
In the workout wizard, it would be nice to have the capability to define sets and repetitions to the workout. Would save a lot of work if one could e.g. set  "REPEAT_START/REPEAT_STOP 5 times" around block when trying to build a 5x8minute 4RBI-workout.

**Comment by liversedge** [comment]
this is covered by the workout editor
