### ISSUE TITLE
Workout Editor

### ISSUE THREAD

**Issue by stigbd** [GoldenCheetah/GoldenCheetah#702]
It would have been nice to be able to edit workouts created by the workout-wizard. Today I accomplish this by opening the .mrc in an editor and edit the workout "manually". Better way would be to be able to edit the workout in the workout-wizard.

**Comment by liversedge** [comment]
Lots of commits from about 18th Dec onwards (way too many to mention)

As at 1st jan 2015 the editor has a points based editing with undo/redo w'bal/tss/if plot as you edit and lots more to come.

![workout editor](https://cloud.githubusercontent.com/assets/142876/12071963/a92b4b38-b0bf-11e5-92ca-84ee80e7eade.png)

**Comment by liversedge** [comment]
Lots of commits so far:

f470803 Workout Editor SEGV
2b6af76 Workout Editor Create Block
a072163 Workout Editor Shift Toggles Draw/Select
cb6fb85 Workout Editor Block Cursor
5591ea7 Workout Editor Block Cursor Again!
30412d5 Workout Editor Block Cursor Performance
afb3be7 Workout Editor Block Cursor Fix
c8ee808 Workout Editor Block Cursor
b9bcd5f Workout Editor Select/Draw Mode
012511d Workout Editor Clear Selection on Rect Select
dfbb035 Workout Editor Cursor Keys Move Points
b1a3cd5 Workout Editor RideFileCache::fastSearch()
bdb8d63 Workout Editor Key Commands undo/redo/delete
2b35054 Workout Editor Selection Cosmetics
8e240ee Workout Editor Selection Tools
f7c31a7 Workout Editor Resampling Error
3cccd64 Workout Editor Toolbar Color
58352f4 Workout Editor Plot W'bal
dae514f Workout Editor Show TSS/IF
cd3474b Workout Editor QT4 compatibility
f6323a6 Workout Editor QT4 compatibility
58f2840 Workout Editor Scale via MouseWheel
83dea1b Workout Editor Redo/Undo
5106549 Workout Editor x/y labels
f445189 Workout Editor Alignment Guide
a1e8990 Workout Editor X-axis Constraint
38c5462 Workout Editor Rough Prototype
5e59fbe Workout Editor - Part 1 of MANY

**Comment by liversedge** [comment]
QWKcode has been devised to express sections of a workout in a simple and quick way, essentially it is:

[Nx]t1@w1[-w2][rt2@w3[-w4]]

Where [ and ] indicate optionality and:

Nx - N = repeat count .e.g 8x repeat 8 times
t1 = duration of effort
w1 = watts for effort
w2 = optional end watts, so a rise from w1 to w2 over the duration
r = indicates a recovery portion
t2 = duration of recovery
w3 = watts for recovery
w4 = optional end watts, so a rise from w3 to w4 over the duration

**Comment by liversedge** [comment]
The workout can be edited graphically or via the qwkcode, available from 'properties'. As you hover in the GUI the qwkcode line for the section is highlighted, as you cursor over the qwkcode text the section in the gui is highlighted.

![screen shot 2016-01-20 at 12 34 35](https://cloud.githubusercontent.com/assets/142876/12449029/38c8dd08-bf72-11e5-8917-81ab89f2cf9e.png)

There is a video covering this here:
https://vimeo.com/152278941

**Comment by liversedge** [comment]
This will be released without CRS support in 3.4 and will be finalised in 4.0

**Comment by liversedge** [comment]
We are not going to enhance the workout editor, it is pretty feature rich now.
Slope mode is too trivial and isn't compatible with the core concepts of the editor.
