### ISSUE TITLE
Workout wizard: Time Riding in Workout Metrics is not updated

### ISSUE THREAD

**Issue by stigbd** [GoldenCheetah/GoldenCheetah#722]
When creating a new workout in the workout wizard, the metric "Time Riding" remains 00:00:00. I believe this is a bug. 

The Time (seconds)-axis in the graph seems to be updated correctly.

Screenshot illustrating this issue attached.
![gc_workout_wizard](https://f.cloud.github.com/assets/1702357/1592403/d90327e6-52ba-11e3-8dd5-935d8cecc1a2.png)

**Comment by Joern-R** [comment]
Fixed https://github.com/GoldenCheetah/GoldenCheetah/commit/411ea4e77af744efebc43f4c19006701762a30c9
