### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [GoldenCheetah/GoldenCheetah#727]
I would like to point out that identifiers like "[```_GC_AddIntervalDialog_h```](https://github.com/GoldenCheetah/GoldenCheetah/blob/5054a9bc904b0d6c19cbd2706bd4fcb766f1dc55/src/AddIntervalDialog.h#L19)" and "[```_PLOT_H_```](https://github.com/GoldenCheetah/GoldenCheetah/blob/1a1a2d955ec1fc104a57235848c6cca5cb2ac461/qwt/examples/navigation/plot.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
How do you think about to avoid that [this software](https://github.com/GoldenCheetah/GoldenCheetah/blob/ef0b2e4acc18ed9c5ffda468d68f58b9f1b31c1f/src/Gui/AddIntervalDialog.h#L19 "Update candidate") [depends on undefined behaviour](http://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Avoid undefined behaviour?")?

**Comment by liversedge** [comment]
I've closed ALL parking lot reports since the dev tean are not going to work on them.
I can reopen if anyone is willing to work on them.

Is there a specific problem / clash you have experienced when compiling, related to _ in pragmas?
