### ISSUE TITLE
Sigma ROX10.0

### ISSUE THREAD

**Issue by MartinCer** [GoldenCheetah/GoldenCheetah#735]
Any chance to add Sigma Sport ROX10.0 device support? Would be great!

I have also tried to export the FIT file from the Sigma Data Center and open it in GC. I get the following report and the GC crashes. The file is validated by the way. If I try one more time I am told the workout has already been saved... Other formats also do not work (SLF, SMF).

![crash](https://f.cloud.github.com/assets/6137721/1701329/5103dcce-6051-11e3-9379-72b06fcb7e2d.png)

**Comment by liversedge** [comment]
This was added in v3.2
