### ISSUE TITLE
Add support for Movescount's KML files

### ISSUE THREAD

**Issue by mbmc** [GoldenCheetah/GoldenCheetah#743]
Hi,

when I try to import a KML file exported from movescount.com (downloaded from an Ambit 2), I see the following message: "Import Status Error -", without any more details.

Original discussion:
https://groups.google.com/forum/#!topic/golden-cheetah-users/_K2x6d-gx7Q

The file can be found here:
https://groups.google.com/group/golden-cheetah-users/attach/37f7972d992945fc/Move_2013_12_23_16_30_00.kml?part=4&view=1

Let me know if you guys need anything else from my side. Thanks!

**Comment by amtriathlon** [comment]
I am closing this since Movescount is being deprecated byt Suunto.
