### ISSUE TITLE
Add Virtual Power Support for ELITE Digital Mag

### ISSUE THREAD

**Issue by smagherini** [GoldenCheetah/GoldenCheetah#744]
This is a magnetics trainer with a 5 resistance selector (1 low, 5 hard). It sport an external unit which display power and other parameters.

I found that the Satori 4 option is short of approx 20W while the Satori 6 is over by about 20W. Hence if you could add the Satori 3,5,7 and 9 it might do the trick....

**Comment by liversedge** [comment]
2,4,6,8,10 should be enough, the reliability of virtual power is down to the coefficients !
