### ISSUE TITLE
Add compatibility with Elite Qubo digital 

### ISSUE THREAD

**Issue by megAvalanche** [GoldenCheetah/GoldenCheetah#745]
pairing via ant stick

**Comment by liversedge** [comment]
I am confused here, @bealsj do you own one of these? is it different to the Qubo that is already supported?

Can you provide a patch ?

**Comment by bealsj** [comment]
Hi,
I don't own one of these I was going to take any data that I got and do a
regression on it to produce an equation for the power curve.  Once I saw a
Qubo was already supported I just didn't follow through.

**Comment by liversedge** [comment]
fair enough !

I think I'll put this in the parking lot.
