### ISSUE TITLE
Improve Interval finder

### ISSUE THREAD

**Issue by alexx89** [GoldenCheetah/GoldenCheetah#748]
Now is possibile to find intervals only searching by power, distance and time. I think it would be useful to have the possibility to set intervals for range of power, cadence and bpm. Example: setting power range between 200 and 250 GC will found all (or just the number I need as it work already) intervals where my power output stand in this range.  Same for cadence and BPM. Is it possibile?

**Comment by superbole** [comment]
Would be great to be able to find peak cadence, heart rate and speed by time or distance intervals like you currently can with peak power.
