### ISSUE TITLE
Add Folder structure to Workout Directory

### ISSUE THREAD

**Issue by jjofre** [GoldenCheetah/GoldenCheetah#751]
If one collects many workouts, the sidebar becomes unwieldy.  Maybe we could have a folder structure under Workouts to better arrange workouts sets.  This would also allow for the creation of a Favorites workouts folder (see: https://github.com/GoldenCheetah/GoldenCheetah/issues/411)

**Comment by jjofre** [comment]
Ok, that would help. But to be clear, the ability too organize by meta data/columns only seems to exist for the Rides side view and not the Train Workouts side view, but I could be missing something.

**Comment by liversedge** [comment]
yes - I misread this !
