### ISSUE TITLE
Provide full support for ISO-8601 date formats

### ISSUE THREAD

**Issue by bpirenne** [GoldenCheetah/GoldenCheetah#752]
The Wahoo fitness app can save workout results in many format such .tcx, which GoldenCheetah can read. Unfortunately, the date format from the Wahoo conversion is not recognized by GoldenCheetah.  The full ISO-8601 standard would however accept both. See http://en.wikipedia.org/wiki/ISO_8601:

Combined date and time in UTC:  
2014-01-02T15:13:43+00:00
2014-01-02T15:13Z

It would be nice if GoldenCheetah would recognize both variations. 

Thank you for your consideration.

**Comment by vlcvboyer** [comment]
The first commit of this pull request :
https://github.com/GoldenCheetah/GoldenCheetah/pull/1467
should solve this issue

**Comment by liversedge** [comment]
Have applied, slightly simplified in d1ef783bf94c1b978e5e6f34b7d6b0b4f6f24518
