### ISSUE TITLE
Train Mode Workflow

### ISSUE THREAD

**Issue by baronbiosys** [GoldenCheetah/GoldenCheetah#762]
Troubleshooting ANT+ connectivity issues require that you start recording before seeing data.  End up with workouts that need to be deleted when there are connectivity issues.  Would be good if the display showed the data coming from devices even when not recording.

**Comment by liversedge** [comment]
We should change the workflow to

connect > start > calibrate > pause/ffwd etc > stop > save

**Comment by liversedge** [comment]
Jon has now resolved this with a connect and auto-connect feature so now closing.
