### ISSUE TITLE
hrTSS estimate when power not available

### ISSUE THREAD

**Issue by MonkeyclawTim** [GoldenCheetah/GoldenCheetah#769]
Would it be possible to get an estimated TSS based on heart rate when power is not available? This would be helpful when there are issues with the power meter (dead battery) or when riding a bike without a power meter (MTB, CX). I know it's not as accurate as using a power meter, but it would be something to show what kind of effort was put into the ride.

Thanks!

**Comment by liversedge** [comment]
trimps and others solve this
