### ISSUE TITLE
Feature: train view: allow setting / learning SRM zero offset

### ISSUE THREAD

**Issue by rclasen** [GoldenCheetah/GoldenCheetah#777]
currently srm_offset seems to be hard coded to 400/420. There's also some code that might learn srm_offset from calibration message, but I'm seeing no way to trigger such messages from GC or from a PC7.

Might be nice to
- trigger learning srm_offset
- and/or manually set srm_offset
through the GUI.

**Comment by liversedge** [comment]
incorporated into #1654
