### ISSUE TITLE
"Change Athlete Folder" on Startup "Choose and Athlete" Window

### ISSUE THREAD

**Issue by darrencope** [GoldenCheetah/GoldenCheetah#778]
With the ability to now have Athlete data stored in an arbitrary location (which is awesome!) the "Choose an Athlete" window that pops up upon opening GC should have an option to "Set Athlete Library Path."  

If I install a new version of GC, and open the program, it will not find my (arbitrarily located) athlete library. However, I have no choice but to create a 'new' athlete on the open athlete window, then go into options and change the Athlete library path, then restart GC and then delete the Temp user in the 'default' path that GC created.

**Comment by Joern-R** [comment]
Looking at the date I think you a referring to a Windows build < 3.1. With those builds the GC Settings were removed from Registry when uninstalling GC - leading to the effect you just described. With 3.2 the settings are not longer removed. So any new installation (3.3) will use the still existing settings and find your Athlete Library Path from the previous install.

(Disadvantage is if you uninstall GC forever - you have some unused artifacts in the Windows Registry).

I close the issue - if my description does not fit to your case - please re-open and give more details on your system/version/...
