### ISSUE TITLE
CRASH - When renaming and deleting intervals for a ride

### ISSUE THREAD

**Issue by jjofre** [GoldenCheetah/GoldenCheetah#788]
Post a Train session with a computrainer I clicked on Rides and selected the ride.  I was renaming intervals and deleting unwanted intervals and then it crash.  Details below:

Program Details and System Configuration
=================================
Process:         GoldenCheetah [16573]
Path:            /Users/USER/*/GoldenCheetah.app/Contents/MacOS/GoldenCheetah
Identifier:      com.yourcompany.GoldenCheetah
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [317]
Responsible:     GoldenCheetah [16573]
User ID:         502
Date/Time:       2014-02-05 19:39:40.563 -0500
OS Version:      Mac OS X 10.9.1 (13B42)
Report Version:  11
Anonymous UUID:  3C5ED0D3-F637-F36B-B5E9-FA516D507E31

Sleep/Wake UUID: 14197C2D-B22E-4B23-B796-B4B16D69581C

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000012

VM Regions Near 0x12:
--> 
    __TEXT                 0000000100000000-0000000100b79000 [ 11.5M] r-x/rwx SM=COW  /Users/USER/*/GoldenCheetah.app/Contents/MacOS/GoldenCheetah

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   QtWidgets                     	0x0000000101fdf390 QGestureManager::getGestureTargets(QSet<QGesture*> const&, QHash<QWidget*, QList<QGesture*> >*, QHash<QWidget*, QList<QGesture*> >*) + 1152
1   QtWidgets                     	0x0000000101fdd2ec QGestureManager::deliverEvents(QSet<QGesture*> const&, QSet<QGesture*>*) + 972
2   QtWidgets                     	0x0000000101fdc69f QGestureManager::filterEventThroughContexts(QMultiMap<QObject*, Qt::GestureType> const&, QEvent*) + 4255
3   QtWidgets                     	0x0000000101fde8e9 QGestureManager::filterEvent(QWidget*, QEvent*) + 889
4   QtWidgets                     	0x0000000101f96919 QApplication::notify(QObject*, QEvent*) + 457
5   QtCore                        	0x0000000101a3eb62 QCoreApplication::notifyInternal(QObject*, QEvent*) + 114
6   QtCore                        	0x0000000101a8de66 QTimerInfoList::activateTimers() + 982
7   libqcocoa.dylib               	0x0000000106c9b355 QCocoaEventDispatcherPrivate::activateTimersSourceCallback(void*) + 21
8   com.apple.CoreFoundation      	0x00007fff89bb68f1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
9   com.apple.CoreFoundation      	0x00007fff89ba8062 __CFRunLoopDoSources0 + 242
10  com.apple.CoreFoundation      	0x00007fff89ba77ef __CFRunLoopRun + 831
11  com.apple.CoreFoundation      	0x00007fff89ba7275 CFRunLoopRunSpecific + 309
12  com.apple.HIToolbox           	0x00007fff932ebf0d RunCurrentEventLoopInMode + 226
13  com.apple.HIToolbox           	0x00007fff932ebcb7 ReceiveNextEventCommon + 479
14  com.apple.HIToolbox           	0x00007fff932ebabc _BlockUntilNextEventMatchingListInModeWithFilter + 65
15  com.apple.AppKit              	0x00007fff8615228e _DPSNextEvent + 1434
16  com.apple.AppKit              	0x00007fff861518db -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
17  com.apple.AppKit              	0x00007fff861459cc -[NSApplication run] + 553
18  libqcocoa.dylib               	0x0000000106c9c0d4 QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2404
19  QtCore                        	0x0000000101a3c25e QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 398
20  QtCore                        	0x0000000101a3f102 QCoreApplication::exec() + 354
21  com.yourcompany.GoldenCheetah 	0x000000010051b32c main + 8220 (main.cpp:318)
22  com.yourcompany.GoldenCheetah 	0x000000010000abc4 start + 52

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff88371e6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8b0fff08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff8b102fb9 start_wqthread + 13

Thread 2:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib        	0x00007fff88372662 kevent64 + 10
1   libdispatch.dylib             	0x00007fff88fd143d _dispatch_mgr_invoke + 239
2   libdispatch.dylib             	0x00007fff88fd1152 _dispatch_mgr_thread + 52

Thread 3:: QProcessManager
0   libsystem_kernel.dylib        	0x00007fff883719aa __select + 10
1   QtCore                        	0x00000001019e37d8 QProcessManager::run() + 136
2   QtCore                        	0x000000010185e9a2 QThreadPrivate::start(void*) + 338
3   libsystem_pthread.dylib       	0x00007fff8b0fe899 _pthread_body + 138
4   libsystem_pthread.dylib       	0x00007fff8b0fe72a _pthread_start + 137
5   libsystem_pthread.dylib       	0x00007fff8b102fc9 thread_start + 13

Thread 4:: JavaScriptCore::BlockFree
0   libsystem_kernel.dylib        	0x00007fff88371716 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff8b100c3b _pthread_cond_wait + 727
2   QtWebKit                      	0x0000000103e456d5 JSC::BlockAllocator::blockFreeingThreadMain() + 261
3   QtWebKit                      	0x000000010408311f WTF::wtfThreadEntryPoint(void*) + 15
4   libsystem_pthread.dylib       	0x00007fff8b0fe899 _pthread_body + 138
5   libsystem_pthread.dylib       	0x00007fff8b0fe72a _pthread_start + 137
6   libsystem_pthread.dylib       	0x00007fff8b102fc9 thread_start + 13

Thread 5:: JavaScriptCore::Marking
0   libsystem_kernel.dylib        	0x00007fff88371716 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff8b100c3b _pthread_cond_wait + 727
2   QtWebKit                      	0x0000000103e465e7 JSC::GCThread::waitForNextPhase() + 119
3   QtWebKit                      	0x0000000103e46678 JSC::GCThread::gcThreadMain() + 88
4   QtWebKit                      	0x000000010408311f WTF::wtfThreadEntryPoint(void*) + 15
5   libsystem_pthread.dylib       	0x00007fff8b0fe899 _pthread_body + 138
6   libsystem_pthread.dylib       	0x00007fff8b0fe72a _pthread_start + 137
7   libsystem_pthread.dylib       	0x00007fff8b102fc9 thread_start + 13

Thread 6:: JavaScriptCore::Marking
0   libsystem_kernel.dylib        	0x00007fff88371716 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff8b100c3b _pthread_cond_wait + 727
2   QtWebKit                      	0x0000000103e465e7 JSC::GCThread::waitForNextPhase() + 119
3   QtWebKit                      	0x0000000103e46678 JSC::GCThread::gcThreadMain() + 88
4   QtWebKit                      	0x000000010408311f WTF::wtfThreadEntryPoint(void*) + 15
5   libsystem_pthread.dylib       	0x00007fff8b0fe899 _pthread_body + 138
6   libsystem_pthread.dylib       	0x00007fff8b0fe72a _pthread_start + 137
7   libsystem_pthread.dylib       	0x00007fff8b102fc9 thread_start + 13

Thread 7:: JavaScriptCore::Marking
0   libsystem_kernel.dylib        	0x00007fff88371716 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff8b100c3b _pthread_cond_wait + 727
2   QtWebKit                      	0x0000000103e465e7 JSC::GCThread::waitForNextPhase() + 119
3   QtWebKit                      	0x0000000103e46678 JSC::GCThread::gcThreadMain() + 88
4   QtWebKit                      	0x000000010408311f WTF::wtfThreadEntryPoint(void*) + 15
5   libsystem_pthread.dylib       	0x00007fff8b0fe899 _pthread_body + 138
6   libsystem_pthread.dylib       	0x00007fff8b0fe72a _pthread_start + 137
7   libsystem_pthread.dylib       	0x00007fff8b102fc9 thread_start + 13

Thread 8:: Qt bearer thread
0   libsystem_kernel.dylib        	0x00007fff883719aa __select + 10
1   libsystem_c.dylib             	0x00007fff8a943c80 pselect$1050 + 183
2   QtCore                        	0x0000000101a8ae17 qt_safe_select(int, fd_set*, fd_set*, fd_set*, timespec const*) + 103
3   QtCore                        	0x0000000101a8be18 QEventDispatcherUNIXPrivate::doSelect(QFlags<QEventLoop::ProcessEventsFlag>, timespec*) + 680
4   QtCore                        	0x0000000101a8cc7b QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 251
5   QtCore                        	0x0000000101a3c25e QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 398
6   QtCore                        	0x000000010185b2a8 QThread::exec() + 120
7   QtCore                        	0x000000010185e9a2 QThreadPrivate::start(void*) + 338
8   libsystem_pthread.dylib       	0x00007fff8b0fe899 _pthread_body + 138
9   libsystem_pthread.dylib       	0x00007fff8b0fe72a _pthread_start + 137
10  libsystem_pthread.dylib       	0x00007fff8b102fc9 thread_start + 13

Thread 9:
0   libsystem_kernel.dylib        	0x00007fff8836da1a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff8836cd18 mach_msg + 64
2   com.apple.CoreFoundation      	0x00007fff89ba8315 __CFRunLoopServiceMachPort + 181
3   com.apple.CoreFoundation      	0x00007fff89ba7939 __CFRunLoopRun + 1161
4   com.apple.CoreFoundation      	0x00007fff89ba7275 CFRunLoopRunSpecific + 309
5   com.apple.AppKit              	0x00007fff862f21ce _NSEventThread + 144
6   libsystem_pthread.dylib       	0x00007fff8b0fe899 _pthread_body + 138
7   libsystem_pthread.dylib       	0x00007fff8b0fe72a _pthread_start + 137
8   libsystem_pthread.dylib       	0x00007fff8b102fc9 thread_start + 13

Thread 10:
0   libsystem_kernel.dylib        	0x00007fff88371e6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8b0fff08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff8b102fb9 start_wqthread + 13

Thread 11:
0   libsystem_kernel.dylib        	0x00007fff88371e6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8b0fff08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff8b102fb9 start_wqthread + 13

Thread 12:
0   libsystem_kernel.dylib        	0x00007fff88371e6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8b0fff08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff8b102fb9 start_wqthread + 13

Thread 13:
0   libsystem_kernel.dylib        	0x00007fff88371e6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8b0fff08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff8b102fb9 start_wqthread + 13

Thread 14:
0   libsystem_kernel.dylib        	0x00007fff88371e6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8b0fff08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff8b102fb9 start_wqthread + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000600000232550  rbx: 0x0000600000655a20  rcx: 0x0000000000000003  rdx: 0x0000000000000000
  rdi: 0x0000600000232540  rsi: 0x0000600000906028  rbp: 0x00007fff5fbfd490  rsp: 0x00007fff5fbfd3c0
   r8: 0x00007fff5fbfc8a0   r9: 0x0000000000000002  r10: 0x00006180001f9b10  r11: 0x00007fff7660f420
  r12: 0x00007fff5fbfd3d0  r13: 0x0000600000655a20  r14: 0x00007fff5fbfd400  r15: 0x00007fff5fbfd608
  rip: 0x0000000101fdf390  rfl: 0x0000000000010293  cr2: 0x0000000000000012
  
Logical CPU:     0
Error Code:      0x00000004
Trap Number:     14

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 7
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 189235
    thread_create: 33
    thread_set_state: 8126

VM Region Summary:
ReadOnly portion of Libraries: Total=328.2M resident=269.6M(82%) swapped_out_or_unallocated=58.6M(18%)
Writable regions: Total=1.3G written=81.9M(6%) resident=127.0M(10%) swapped_out=0K(0%) unallocated=1.1G(90%)
 
REGION TYPE                        VIRTUAL
===========                        =======
CG backing stores                    13.5M
CG image                              108K
CG raster data                         84K
CG shared images                      236K
CoreAnimation                        2768K
CoreImage                               8K
Foundation                              4K
IOKit                                6296K
IOKit (reserved)                        4K        reserved VM address space (unallocated)
JS JIT generated code                   8K
JS JIT generated code (reserved)      1.0G        reserved VM address space (unallocated)
JS VM register file (reserved)       4096K        reserved VM address space (unallocated)
JS garbage collector                  256K
Kernel Alloc Once                       8K
MALLOC                              192.0M
MALLOC (admin)                         32K
Memory Tag 241                        140K
Memory Tag 242                         12K
Memory Tag 251                         28K
OpenCL                                 36K
STACK GUARD                          56.1M
Stack                                14.7M
VM_ALLOCATE                          20.8M
WebKit Malloc                        4368K
__DATA                               52.2M
__IMAGE                               528K
__LINKEDIT                           89.8M
__TEXT                              238.4M
__UNICODE                             544K
mapped file                          59.8M
shared memory                           4K
===========                        =======
TOTAL                                 1.7G
TOTAL, minus reserved VM space      752.4M
 

Model: iMac14,2, BootROM IM142.0118.B00, 4 processors, Intel Core i5, 3.2 GHz, 16 GB, SMC 2.15f2
Graphics: NVIDIA GeForce GT 755M, NVIDIA GeForce GT 755M, PCIe, 1024 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x111), Broadcom BCM43xx 1.0 (6.30.223.154.45)
Bluetooth: Version 4.2.0f6 12982, 3 services, 23 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: APPLE SSD SD0128F, 121.33 GB
Serial ATA Device: APPLE HDD WD10EZES-40UFAA0, 1 TB
USB Device: Hub
USB Device: USB-RS232 Cable
USB Device: iPhone
USB Device: ANT USBStick2
USB Device: FaceTime HD Camera (Built-in)
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Apple USB SuperDrive
USB Device: My Book 1112
Thunderbolt Bus: iMac, Apple Inc., 23.10

**Comment by hzzlzz** [comment]
Problem still exists in Qt 5.4.2
