### ISSUE TITLE
Handle basic events and register with Launch Services on OS X

### ISSUE THREAD

**Issue by BrettDikeman** [GoldenCheetah/GoldenCheetah#797]
GoldenCheetah should register itself with MacOS X as being able to open the document types it supports. Any Mac user will expect this behavior. See:

https://developer.apple.com/library/mac/documentation/Carbon/Conceptual/LaunchServicesConcepts/LSCConcepts/LSCConcepts.html

GC should also be able to handle some basic events passed to it, such as a "file open" event such that users can, in the Finder, use "Open With..." or double-click an activity file. For example:

http://doc.qt.digia.com/qq/qq12-mac-events.html

Aside from also being an expected behavior, this would open the door to Applescript/Automator actions allowing people to script automatically adding new activity files upon device connect, etc - a feature that's been requested multiple times on the mailing list.

**Comment by amtriathlon** [comment]
I am closing this because is not likely it will be implemented and, considering how problematic has become macOS specific features maintenance, it is probably not such a good idea either.
