### ISSUE TITLE
App mode messed up after workout

### ISSUE THREAD

**Issue by jjofre** [GoldenCheetah/GoldenCheetah#802]
After doing a workout (manual or erg) and either pressing Reset on Computrainer or the Stop button on the GUI, sometimes the app gets out of whack.  If I then switch views to Rides, then instead of switching the view, the button shows  being depressed, but that is also the case with the Train button.  They are both depressed.  In fact, I can toggle of the other buttons (e.g.  Diary, etc), but the main view does not change from Train view.  The menu system is all greyed out, so you can't quit, except from the Dock menu.

System: Mac OS X 10.9.1

![screen shot 2014-02-14 at 7 54 07 pm](https://f.cloud.github.com/assets/323484/2176689/b3031ac4-95db-11e3-9fb2-bbd0afbc9c97.png)

**Comment by liversedge** [comment]
I'd rather not fix this with a hack -- it should be resolved by QT now -- can you confirm ?

**Comment by jjofre** [comment]
Happy to test it out. Is there a new build I should try or should I build it myself? Which T version should I use?

**Comment by liversedge** [comment]
5.4 :)

**Comment by jjofre** [comment]
Ok, just got my local build up to par. I will do a few workouts this/next week and report back. It should be clear as it is easily repeatable.

**Comment by jjofre** [comment]
Closing this issue. Tested with Qt 5.4 and the problem is no longer there :)
