### ISSUE TITLE
Powermeter drop out

### ISSUE THREAD

**Issue by fupe339** [GoldenCheetah/GoldenCheetah#826]
Hi,
since I use Version 3.0.2 there is a extremely high number of drop outs between power meter and my Mac (connected via garmin ANT stick). Before update the power and cadence graphs were similar than the heart rate graph (see attachment). I all ready changed the power meter batteries. Thanks advance for your answer!
Peter
![bildschirmfoto 2014-03-11 um 18 51 57](https://f.cloud.github.com/assets/6953874/2424064/b7e97038-aba2-11e3-863d-e2d07c008750.png)

**Comment by liversedge** [comment]
I am not able to recreate this so am closing the issue as it is probably setup/hardware related.

Sorry.
