### ISSUE TITLE
Group By Ride - Feature request

### ISSUE THREAD

**Issue by benhowell** [GoldenCheetah/GoldenCheetah#831]
Hi Devs,
It would be great to have the functionality to group by ride in charts. I regularly do two sessions in one day (one hard ride at lunch time, and one LSD after work) so I'd like to be able to see these separately in all the various charts. Currently the lowest granularity is "Group By Days".

Thanks for the best cycling app I've ever used.
Regards,
Ben.

**Comment by amtriathlon** [comment]
In v3.6, both Trends Overview and User Chart have this functionality by default, I am closing this this since it is unlikely it will be retrofitted to older charts, and more likely be replaced by the new ones in the future.
