### ISSUE TITLE
Make cranklength specific to user

### ISSUE THREAD

**Issue by jpswemmer** [GoldenCheetah/GoldenCheetah#843]
The software does not allow to change the crank length per user.
Once you select a crank length for an user, it defaults it to all users

**Comment by superbole** [comment]
This should actually be bike dependent.

I (and I'm sure I'm not unique) ride road, track, MTB and commuter bikes. All have different length cranks.

**Comment by Joern-R** [comment]
Crank Length as well as Wheel Size are now Athlete dependent 
https://github.com/GoldenCheetah/GoldenCheetah/commit/f04592b62b1f357530a3805f86d3cbede3d80a6b
