### ISSUE TITLE
Add (Sport-)Filter possibility to 'Curve Settings'

### ISSUE THREAD

**Issue by robolaf** [GoldenCheetah/GoldenCheetah#844]
As a triathlete I use Sport to differentiate between Run, Bike, Swim and WO Code for Sub-Sport (TT, Road, Cyclo, MTB) Currently, the only chart type that supports differentiation between Sub-/Sports in one chart is the Collection Tree Map, which is very helpful.
However, for me, it would be very interesting to have a Filter possibility (not only on the overall chart but) for each Curve. This would allow for displaying and comparing for example running efforts and stacked bike (TT, Road, Cyclo, …) in one chart and much, much more. To illustrate I attached a mock up:
![filter](https://cloud.githubusercontent.com/assets/7139815/2657182/c065aef0-bff9-11e3-9d05-18f05169bdfd.png)
For me this were an extremly helpful feature (I guess for other triathletes, too).

**Comment by liversedge** [comment]
added filter for a curve in 3.3 .. finally realised what you were driving at ! :)
