### ISSUE TITLE
Feature request: W' Expended plot, for ride comparisons

### ISSUE THREAD

**Issue by Swuzzlebubble** [GoldenCheetah/GoldenCheetah#857]
I've been searching for a simple way to compare rides graphically - ie via a plot
The CP plot only gives the 'bests'
Power Profile charts etc are similarly limited
The full ride plots get confusing due to the variations between rides.

What I'm thinking is that using W' but sorting the data in order of % expended wil give a useful standardised comparison view.
Key features are that the entire ride duration is included
All rides start at a common point (the origin) of 0% expended
If a ride has a higher portion spent at a high % W'bal remaining, then the plot will start shallower.
Rides in which a higher portion is spent at low W'Bal remaining will start steeper and level out at the higher % level.

See attached mock up example:
![wprimeexpe](https://cloud.githubusercontent.com/assets/142876/2773872/fa9819dc-caa8-11e3-9c24-5114edc15e1a.png)

**Comment by amtriathlon** [comment]
I think we can close this since now it can be implemented as a R/Python chart and likely as User Chart in v3.6, so there is not much incentive to create a new builtin chart.
