### ISSUE TITLE
"Scale Data Series" option - scaling power for a ride

### ISSUE THREAD

**Issue by dinmal001** [GoldenCheetah/GoldenCheetah#887]
Many people these days have multiple power meters (or sources of power data - trainers with power, trainers with virtual power etc). Whilst these may all measure power consistently within their stated accuracy, there will nevertheless be a difference in measured power between power meters (e.g. my Powerbeam trainer with built in power meter gives value X for a FTP test, whilst my Stages give value Y for the very same test ride). This difference is often consistent and fairly predictable (after doing a few tests) - e.g. my Stages reads approximately 96% of the value at FTP that my Powerbeam reads. 

An athlete in GC has only one CP value at any given time - this is logically how it should be - which would be taken from one of the user's power meters. All other power meters' values should therefore ideally be "scaled" so that they match each other (in my case, I would scale any power data from my Stages by *0.96, and leave any data from rides using  my Powerbeam untouched). 

I would suggest that the functionality be created that allows power data (or perhaps any metric?) to be scaled by a user defined value. Perhaps a logical place would be on the Details-Metric tab of a ride. A user could then selectively apply a scaling to any chosen ride.

**Comment by amtriathlon** [comment]
Fixed in 3.2 https://github.com/GoldenCheetah/GoldenCheetah/commit/a0156aab27b2fd1d0d365e0f3f806663195b6a98
