### ISSUE TITLE
Temperature Off on CSV Imports from iBike

### ISSUE THREAD

**Issue by hawkesworthm** [GoldenCheetah/GoldenCheetah#891]
Ever since the last update my temperature numbers on my CSV imports are way off. It shows average temps around 150-170 with highs in the 190-200 range. I've looked at the details of the csv file and can't find any bad records, so I'm not sure where these figures are coming from.

Thanks,
Matt

**Comment by liversedge** [comment]
is this still a problem ?

**Comment by hawkesworthm** [comment]
Yes, this is still a problem. I've attached a screen shot and my import
file for reference.

Matt

**Comment by grauser** [comment]
corrected in 7cb72490a84d93ec4465ee3921635a5b0861638a
