### ISSUE TITLE
Train View Redesign

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#939]
I want to redesign the Train View completely and was one of the drivers behind looking to build 'opentrainer' as a separate application. The refactoring of the views in 3.1 means this is not needed, so can be incorporated into the main application.

Key principles of the redesign;
1. work on running a workout that comprises a device setup, a workout script and optional video or other visuals
2. work on a main view that uses a graphscene and is dynamic, layered, responsive and provides 'tv quality' visuals
3. Remove the need to drag/configure contents and positioning -- it is tedious !
4. avoid being constrained by re-using the approach in the 'tile mode' for the other GC views

**Comment by vlcvboyer** [comment]
I've made few tests which were successful:

![test speedometer overlay](https://cloud.githubusercontent.com/assets/13483855/9294869/3f1df7da-445a-11e5-8ab2-cb4e959d9549.jpg)

I have to clean the code then I'll put it on github.
It should be fully cross platform but I've tested only on Windows.

**Comment by liversedge** [comment]
What have you added?

Is it those overlays ?

If so, then GREAT JOB :)

**Comment by vlcvboyer** [comment]
Yes: overlays using Qt

**Comment by vlcvboyer** [comment]
You can see/check/test/... my code here:
https://github.com/vlcvboyer/GoldenCheetah/tree/trainview

Do not hesitate to send comments.

**Comment by vlcvboyer** [comment]
Hi,
I do not plan to raise a pull request as (from my point of view) it still have to be amended to allow customization (which meter to use and define size/position : XML file?).
Thereby beeing able, as a minimum, to disable it !
Otherwise it will always be part of Video playback but everyone do not want it...
What is your point of view?

**Comment by liversedge** [comment]
If the selected media has data to control playback it should be honoured!
otherwise don't adjust video speed.

What customisation is needed ?

**Comment by vlcvboyer** [comment]
Meters layout should be configurable from "none" to whatever the user want to see (speed, cadence, HR, power, distance, time, elevation profile, race map.....) it can be needle meters, digits, curves.... and placed wherever the user what to place them.
XML seems to be the better file format for this kind of job. The user will be able to select within the several preset layout (several XML files) the one he want to use.

This feature is not linked to video playback synchronization. But it works with it and do not interfere !

**Comment by vlcvboyer** [comment]
I've created XML file for configuring my video playback overlays.
Feel free to test/check and send comments.
Of course it will be easy to create others meters in the future. The ones I've created at present are not so beautiful...

In addition, as all are related to training view, I've merged the 3 forks I'm working on into one global for tests
Thus you can test separately from my github:
- Train view with overlays (this feed)
- ANT-FEC (original project from stschake, I've included gradient simulation mode associated to pgmf files)
- Video synchronisation using RLV files
or all together using latest GoldenCheetah master branch: 
- test_all branch
I've taken care of others platforms but I've not tested others builds. Thereby you'll likely have to do some adjustments if you're not using windows/VLC thus testing one by one may be useful if one take too much time to fix.

**Comment by liversedge** [comment]
Amazing !

I can't keep up with you :)

Seriously, I wonder what the best strategy is for including this into GC. Are you proposing to develop a working prototype that we then apply to the code base or are you planning on creating a pull request at some point ?

Happy to go either way.

**Comment by vlcvboyer** [comment]
I'll create a pull request when it will be more tested and when I'll have included few comments as it as to match anyone expectations. (it's the same for video-sync pull request that can be putted on hold until tested by others, etc.)
...thereby tests on other operating systems are welcome ! (as a minimum building executable even if feature is not available !)
Were you able to test it? Do you have any comments? Did it comply with GC philosophy and do you think it will be possible to merge when it will be ready?
FYI,due to business, I may have less time at present to work on it...

**Comment by liversedge** [comment]
Now the rugby season has started in the northern hemisphere I will be doing a lot less as I am a referee.
But will try and play with it and look more closely at the code over the next week.

**Comment by liversedge** [comment]
won't do.
