### ISSUE TITLE
Add more derived data series

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#976]
If they are not present then we could try and derive data series, each one listed separately below.

**Comment by ehrlinger** [comment]
I think we should indicate derived data somehow, and not include it in certain performance metrics. Or have a way to removed derived data from performance metric. 

Secifically, including derived power in CP curve can give wonky results.

**Comment by liversedge** [comment]
I agree !

**Comment by ehrlinger** [comment]
Turns out it was only two of the derived datasets, but still weird to have this type of result.

**Comment by liversedge** [comment]
this is now handled with userdata series. so closing.
