### ISSUE TITLE
Migrate to Unified LibUsb 1.1.18

### ISSUE THREAD

**Issue by liversedge** [GoldenCheetah/GoldenCheetah#980]
http://libusbx.1081486.n5.nabble.com/Libusbx-devel-Announcing-libusb-1-0-18-as-well-as-libusbx-1-0-18-FINAL-td2375.html

See here: https://github.com/libusb/libusb
And: http://libusb.info/

**Comment by lurdan** [comment]
It seems GC not to be going to support newer libusb versions (otherwise assumes to use bundled tarball), right?

**Comment by Ramoonus** [comment]
v 1.0.22 is out now
https://github.com/libusb/libusb/releases
