### ISSUE TITLE
Summary Trends Chart - Sort Order Selectable

### ISSUE THREAD

**Issue by doyler78** [GoldenCheetah/GoldenCheetah#985]
On the Summary Chart in the Trends section there is a section of ride information which could be enhanced by allowing each of the columns to be sortable ie clicking on the column header would change the sort order from asc to desc or vice-versa. This means that I could have the most recent rides show up first or I could click on duration to toggle by longest/shortest rides, etc.

**Comment by amtriathlon** [comment]
I am closing this since the Summary chart is being replaced by Overview and will not be updated anymore.
