### ISSUE TITLE
Appcrash - AllPlot - Power ReferenceLines

### ISSUE THREAD

**Issue by Joern-R** [GoldenCheetah/GoldenCheetah#996]
Hi,

I get an appcrash when using the Power-ReferenceLine feature on the ride 'All Plot'.
System: Windows 7 (RC3X 64 Bit Build on 4.8.6) as well as my build (Win 32, QT 5.3.1).

Can be reproduced this way:

- Open a Ride, Stacked by Series selected
- Mouse-drag to create a first reference line to the Power Chart
- Activate all other related metrics (NP, xPower, aPower,....)
- Mouse-drag to a create a reference line in one of the other power charts
- Move the cursor to the Y-Axis Label for 'Power'

-> SEGV in isolateAxis(....) 

So it only happens (for me) if I add a reference line for Power in the 'other' power related plots in stacked mode.

Thanks.
Joern

**Comment by liversedge** [comment]
is this still a problem ?

**Comment by Joern-R** [comment]
Yes - just tried it - one additional info - you need to "click" on the Y-Label for Power to get the SEGV.
